### ISSUE TITLE
[FEATURE REQUEST] Java extensions for PyTorch

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/pytorch#1000]
There is already a way to write **C** extesions some binding package (cffi). What about **Java/JNI** api binding?

**Comment by apaszke** [comment]
If you consider the fact that we're not using JVM in any place it seems like an unnecessary effort. Java files don't compile to C-compatible object files, so there's no easy way to link them with the current code.

Additionally, I have no idea what benefits would Java extensions give you? If you need super high performance, you can go with C/C++/CUDA, otherwise all extensions can be written in Python directly.

**Comment by loretoparisi** [comment]
@apaszke well I mean I'm not arguing any performance considerations here. By the say Tensorflow (and MXNet via amalgamation in Scala) has a Java JNI wrapper (Java and Android), that let you natively use CUDA, etc.

**Comment by soumith** [comment]
Hi Loreto,
We dont have an explicit plan on this for Java.
Our razor-sharp focus as core developers is Python / C / C++.
If anyone in the community will develop other language extensions we are looking forward to how it turns out.

**Comment by ajmssc** [comment]
@soumith I'm working on a JNI wrapper for pytorch and interested in open sourcing it. Can you let me know if this is something you would be interested in?
