### ISSUE TITLE
graph._export_onnx() incorrect data types in the binary string representation

### ISSUE THREAD

**Issue by Zeyad-Abdelreheem** [pytorch/pytorch#100289]
### 🐛 Describe the bug

This bug was aroused in the comments sections of this [post](https://github.com/pytorch/pytorch/issues/100097)

The model converted from torch to onnx is represented by a binary string through the `torch.onnx.export()` function, that function uses a private bounded function [graph._export_onnx](https://github.com/pytorch/pytorch/blob/9e1f46d55b9dfb48effdaf8eb3aa87ba5d072662/torch/onnx/utils.py#L1606) to construct the binary string. It works as expected except for the the data type of the output tensors, it is not accurate, it casts the int32 dtype to int64.

you can find tests [here](https://github.com/pytorch/pytorch/issues/100097)

### Versions

```
pytorch version: 2.0.0+cu118
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: None
onnx version: 1.13.1
```

**Comment by titaiwangms** [comment]
Hi @Zeyad-Abdelreheem 

We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
