### ISSUE TITLE
Add missing `OpInfo`s for prims ops

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#100223]
### 🚀 The feature, motivation and pitch

Some prims ops don't have OpInfos:

- [x] bessel_i0
- [x] bessel_i0e
- [x] bessel_i1
- [x] bessel_i1e
- [x] bessel_j0
- [x] bessel_j1
- [ ] broadcast_in_dim
- [ ] cbrt
- [ ] collapse
- [ ] collapse_view
- [ ] convert_element_type
- [ ] copy_strided
- [ ] copy_to
- [ ] device_put
- [x] empty_strided
- [ ] erf_inv
- [x] erfcx
- [ ] fft_c2c
- [ ] fft_c2r
- [ ] fft_r2c
- [ ] iota
- [x] item
- [ ] maximum_value
- [ ] minimum_value
- [ ] name
- [x] ndtri
- [ ] resize
- [ ] rev
- [ ] shift_left
- [ ] shift_right_arithmetic
- [ ] slice_in_dim
- [x] spherical_bessel_j0
- [ ] split_dim
- [ ] view_of
- [x] zeta

cc @mruberry @ezyang @ngimel @Lezcano @peterbell10

**Comment by khushi-411** [comment]
Hi, @justinchuby!
I just stumbled across this issue to work, and I found that the `bessel_j0`, `bessel_j1`, `erfcx`, `ndtri`, `spherical_bessel_j0`, and `zeta` OpInfo's are already present. Please see:

https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/opinfo/definitions/special.py#L693-L698

Also, I think OpInfo's for `bessel_i0`, `bessel_i0e`, and `bessel_i1` are also there but named as `i0`, `i0e`, and `i1`. It's because aten ops are called like that. Related PR #78111.

Does this make sense to you? Please let me know if I'm missing something. Thanks :)

**Comment by justinchuby** [comment]
Thank you! that's awesome.

**Comment by ngimel** [comment]
Original intention was not to test prim ops separately, and test them only through refs, did that change?

**Comment by justinchuby** [comment]
@ngimel we are trying to add onnx decomposition for prims ops and needed OpInfos for testing. Is there a suggested way of testing?

**Comment by ggold7046** [comment]
Hi, I'm looking for some testing related issues. Could anyone guide me how to look for it ?
