### ISSUE TITLE
nightly pip install loops on torchaudio install

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#100563]
### 🐛 Describe the bug

nightly online instructions fail to install, looping on torchaudio not finding the matching version:
```
$ pip3 uninstall torch torchvision torchaudio -y
$ pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu117 -U
[...]
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230502%2Bcu117-cp38-cp38-linux_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 40.9 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230501%2Bcu117-cp38-cp38-linux_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 41.2 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230429%2Bcu117-cp38-cp38-linux_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 26.0 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230428%2Bcu117-cp38-cp38-linux_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 26.2 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230427%2Bcu117-cp38-cp38-linux_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 38.6 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230426%2Bcu117-cp38-cp38-linux_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 35.5 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230425%2Bcu117-cp38-cp38-linux_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 43.7 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230424%2Bcu117-cp38-cp38-linux_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 44.0 MB/s eta 0:00:00
  Downloading https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.1.0.dev20230423%2Bcu117-cp38-cp38-linux_x86_64.whl (3.6 MB)
```

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by malfet** [comment]
Ok, I can reproduce the problem, but I don't think it has something to do with pytorch, but rather with torchaudio deps...

**Comment by malfet** [comment]
Also, looks like nobody bother to move torchaudio trunk version to 2.1.0...

**Comment by malfet** [comment]
Actually, it's a NOVA thing (and I'm curious how nightly build validation works). From `torchaudio-2.1.0.dev20230502+cu117.dist-info/METADATA`:
> Requires-Dist: torch (==2.1.0.dev20230502)

**Comment by malfet** [comment]
@atalman this might be a rhetoric question, but why automated installation testing did not catch it all this time?

**Comment by pmeier** [comment]
I [scraped out index](https://gist.github.com/pmeier/2c20264d41d4138e8dbcaa392fe720e5) and it seems to be very localized in time. The only affected wheels are

```
{'tag': 'cp311-cp311-linux_x86_64', 'torchaudio': '2.1.0.dev20230502+cu117', 'torch': '2.0.0'}
{'tag': 'cp311-cp311-linux_x86_64', 'torchaudio': '2.1.0.dev20230503+cu117', 'torch': '2.0.0'}
{'tag': 'cp311-cp311-macosx_10_9_x86_64', 'torchaudio': '2.1.0.dev20230501', 'torch': '2.0.0'}
{'tag': 'cp38-cp38-linux_x86_64', 'torchaudio': '2.1.0.dev20230503+cu117', 'torch': '2.0.0'}
{'tag': 'cp38-cp38-macosx_10_9_x86_64', 'torchaudio': '2.1.0.dev20230503', 'torch': '2.0.0'}
{'tag': 'cp38-cp38-macosx_11_0_arm64', 'torchaudio': '2.1.0.dev20230503', 'torch': '2.0.0'}
```

My guess is that this is caused by #100400. The SEV affected domain libraries heavily since `download.pytorch.org` not only hosts some weights, but also the the `torch` wheels that are downloaded to build and test the domain libraries.

I don't see any commit in `torchaudio` that could cause this. Same for the infra structure, which should have affected `torchvision` as well. Maybe the installation just picked the stable version from PyPI since it couldn't pull anything from our indices?

Since #100400 seems to be resolved now IMO we should wait if situation persists today. We should have more clarity in a few hours.

**Comment by malfet** [comment]
[I thought I've posted this comment yesterday, but I guess I didn't]  I've removed regression and high-priority labels, as indeed it was not caused by any code changes, but rather infra flakiness caused runners to use 2.0.0 on some days. 

Though I wonder if it'll be prudent to relax constraint on the nighly builds to `>= X.Y.Z.dev` version of pytorch rather than pin it to a specific version, to make previous nightly builds still accessible, rather than forcing one to go back all the way to Mar 13th unversioned build.
