### ISSUE TITLE
onnx.export fails if do_constant_folding=False

### ISSUE THREAD

**Issue by mzmssg** [pytorch/pytorch#100873]
### 🐛 Describe the bug

I am currently using the code below to convert a diffusion unet model to ONNX format. Noticed the unet model is larger than 2GB, which exceeds protobuf limitation, so the model weights will be exported as separate files.

```python
import onnx
import torch
from diffusers import UNet2DConditionModel

unet = UNet2DConditionModel.from_pretrained("CompVis/stable-diffusion-v1-4",
                                            torch_dtype=torch.float16,
                                            revision="fp16",
                                            subfolder="unet")
unet.cuda()
# unet.float()

with torch.inference_mode(), torch.autocast("cuda"):
    inputs = torch.randn(2,4,64,64, dtype=torch.float16, device='cuda'), torch.randn(1, dtype=torch.float16, device='cuda'), torch.randn(2, 77, 768, dtype=torch.float16, device='cuda')

    # Export the model
    torch.onnx.export(unet,
                    inputs,
                    "unet.onnx",
                    opset_version=14,
                    do_constant_folding=False,  # whether to execute constant folding for optimization
                    # do_constant_folding=True, 
                    input_names = ['input_0', 'input_1', 'input_2'],
                    output_names = ['output_0'])
```

The code works as expected when using either float32 precision or the "do_constant_folding=True" flag. However, when attempting to export the model using float16 version and "do_constant_folding=False", the code produces a libprotobuf error.

```
libprotobuf ERROR ../third_party/protobuf/src/google/protobuf/message_lite.cc:457] onnx_torch.ModelProto exceeded maximum protobuf size of 2GB: 2891617469
```

### Versions

1.12.1+cu113

**Comment by titaiwangms** [comment]
Hi @mzmssg 

We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
