### ISSUE TITLE
ROCM 5.5 support

### ISSUE THREAD

**Issue by idkwhodatis** [pytorch/pytorch#100840]
### 🚀 The feature, motivation and pitch

ROCM 5.5 has been released for a while, which added support for RDNA3 GPUs(RX 7900XT/XTX). 
Just wondering when is pytorch going to support it, thx

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by YellowRoseCx** [comment]
I have a 6800xt and Vega 64, both officially supported ROCm GPUs. Pytorch 2.0.0 broke multi GPU use with them. They should work on fixing that first ;p

Also, are you sure rocm 5.5 has the 7000 series support? I thought it was 5.6 that would have them. I saw someone from the ROCm team say to not expect a pytorch version for rocm 5.5, LIKELY because they're focusing on porting Pytorch 2 to rocm 5.6 which seems like it's not too far away from release

**Comment by idkwhodatis** [comment]
> 

Well rocm 5.5 didn't mention rdna3 series in the release note at all, but I saw this post few days ago: [reddit](https://www.reddit.com/r/Amd/comments/135f8we/amd_rocm_55_in_the_process_of_being_released/&ved=2ahUKEwi-y5jBjen-AhXKlWoFHcMdAQAQjjh6BAgrEAE&usg=AOvVaw1pxYCY8SgqBBQXEnx0nFOl), saying that rnda3 has been supported, and I did successfully installed rocm on my machine, so I guess yes?

**Comment by YellowRoseCx** [comment]
> > 
> 
> Well rocm 5.5 didn't mention rdna3 series in the release note at all, but I saw this post few days ago: [reddit](https://www.reddit.com/r/Amd/comments/135f8we/amd_rocm_55_in_the_process_of_being_released/&ved=2ahUKEwi-y5jBjen-AhXKlWoFHcMdAQAQjjh6BAgrEAE&usg=AOvVaw1pxYCY8SgqBBQXEnx0nFOl), saying that rnda3 has been supported, and I did successfully installed rocm on my machine, so I guess yes?

I can install rocm on a machine with a Rx 5600xt and typing rocminfo shows my gfx1010 card; but it doesn't work because there's no hip binaries, I don't see it on the GPU support page but hopefully rocm and pytorch get updated soon:)

**Comment by AviVahl** [comment]
See: https://github.com/pytorch/pytorch/issues/100625

**Comment by idkwhodatis** [comment]
> See: #100625

Thanks, did not see this post. 
BTW I'm closing this issue by duplicate, and I tried directml, it worked.

**Comment by idkwhodatis** [comment]
directml kinda suck, but it turns out you can have pytorch functional by building it yourself. 
[This](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/9591) is a docker workaround for stable-diffusion-webui, and with some modifications it works well on my native Ubuntu 22.04.2
it's not stable since rocm5.5 does not officially support for 7900xtx, and pytorch 2.0.1 does not officially support rocm5.5 either

**Comment by jithunnair-amd** [comment]
> I have a 6800xt and Vega 64, both officially supported ROCm GPUs. Pytorch 2.0.0 broke multi GPU use with them.

@YellowRoseCx Do you have an issue link for this?

**Comment by YellowRoseCx** [comment]
> > I have a 6800xt and Vega 64, both officially supported ROCm GPUs. Pytorch 2.0.0 broke multi GPU use with them.
> 
> @YellowRoseCx Do you have an issue link for this?

I never made an official Issue post since I was unsure of the proper formatting and all that; but I did write down everything I experienced, with what steps I used to have it happen, the errors, as well as trying to traceback the error . Ive tried different Transformers versions too. I also got the errors after using PyTorch I built from ROCm repo
I'm fairly certain it's not the program I was using (henk717/KoboldAI) as the issue is not apparent on torch 1.13.1 and single gpu works with torch 2.0+ 

https://rentry.org/tcahd

If you need me to paste what I posted in that Rentry post to a Github Issue post, let me know and I can do that. Just let me know what to and not to include from it

thank you for checking up with me on the issue I was having
