### ISSUE TITLE
Wrong Warning "compiler (c++) may be ABI-incompatible with PyTorch!"

### ISSUE THREAD

**Issue by rotabulo** [pytorch/pytorch#10114]
## Issue description
I get the warning about my compiler not being ABI-compatible even though it is.
I think the issue is due to CXX not being set, which defaults to `c++` and the ABI-compatibility check is not properly done in `https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L91`, because `c++` is not listed among the possible cases.

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 396.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

Also my C++ version is 5.4.0

**Comment by soumith** [comment]
cc: @goldsborough

**Comment by johnmarkwayve** [comment]
I'm having a similar issue. Please provide a mechanism to opt-out of this check (or at least opt-out of the extremely spammy warning).

**Comment by goldsborough** [comment]
There's not much more we can do than have heuristics for how we determine the compiler version. So the best way to help is to paste the output of `c++ --version` or `your_compiler --version` here so that I can look at it and understand how to make the heuristics more robust. You should also be able to just set the environment variable `CXX=g++` before running `python setup.py build` so that it'll use the `g++` binary instead of `c++`.

**Comment by johnmarkwayve** [comment]
@goldsborough you could add a simple flag to opt-out in a "trust me please, I know what I'm doing and accept the consequences" way

**Comment by johnmarkwayve** [comment]
Also, correct me if I'm wrong but right now I believe that you'd get spammed by this warning if you, for example, custom-compiled pytorch with `clang` on Linux.

**Comment by goldsborough** [comment]
@johnmarkwayve no, the warning is only raised if you're using a binary build of Pytorch, i.e. from Pip. It's never raised if you compile from source.

**Comment by johnmarkwayve** [comment]
@goldsborough thanks, my mistake

**Comment by rotabulo** [comment]
@johnmarkwayve as I mentioned at the beginning of this thread, I think the issue is simply due to having the following command `check_compiler_abi_compatibility(os.environ.get('CXX', 'c++'))`, which defaults to `c++` if `CXX` is not set, and later there is no check on `c++` in line `https://github.com/pytorch/pytorch/blob/v0.4.1/torch/utils/cpp_extension.py#L95`

**Comment by goldsborough** [comment]
Blindly accepting `c++` would be incorrect, since `c++` is clang on macOS. The idea behind defaulting to c++, and then checking for `gcc`, is that in most cases `c++` is a symlink to `gcc`, therefore `c++ --version` would usually print gcc's version output and thus also include `gcc` somewhere inside. Unfortunately this varies wildly from platform to platform :/ 

For example, my `c++ --version` prints:

```sh
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
