### ISSUE TITLE
cuda runtime error (8) : invalid device function

### ISSUE THREAD

**Issue by huwei1024** [pytorch/pytorch#10113]
how can i fix this problem:

RuntimeError: cuda runtime error (8) : invalid device function at c:\new-builder_2\win-wheel\pytorch\aten\src\thcunn\generic/Threshold.cu:34

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0

OS: Microsoft Windows 10 企业版
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 8.0.60
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by peterjc123** [comment]
@huwei1024 Yes, we are regenerating the binaries.

**Comment by huwei1024** [comment]
When can i download it?

**Comment by peterjc123** [comment]
@soumith Are the binaries updated? I think they will be available soon, maybe tomorrow.

**Comment by soumith** [comment]
The new binaries are updated for Windows.

If you have previously installed via anaconda, you have to do:

```
conda uninstall -y pytorch
conda clean -t -y
```

and then reinstall pytorch.


If you have installed via `pip` command on https://pytorch.org, first uninstall pytorch via `pip uninstall torch` and then rerun that command (so that the new wheel is downloaded and installed)
