### ISSUE TITLE
Do automatic replacement of scaled dot product with fast sdpa implementation in HF models. 

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#101458]
#100609 adds sdpa patterns to pattern matcher that are seen in models from HF suite. The status of the benchmarked models is as follows:

 - [x] Albert 
 - [ ] AllenAILongformer broken on master
- [x] Bart 
- [x] Bert 
- [ ] BlenderBot - has a  different pattern
- [x] CamemBert 
- [ ] Deberta custom autograd functions
- [x] DistilBert - works, but will need a different pattern for const folding
- [ ] DistillGPT - has causal mask, hard to match
- [x] Electra - works
- [ ] GPT2 - has causal mask
- [x] LayoutLM 
- [ ] M2M100 has a different pattern
- [ ] MBart has a  different pattern
- [ ] MT5 - non-zero (maybe causal) bias
- [x] Megatron 
- [x] MobileBert 
- [ ] OPT - does additional clipping, different math from _sfdp_params_check
- [ ] PLBart - non-0 attn mask
- [ ] Pegasus - causal mask, can't pattern match
- [x] Roberta
- [ ] T5 - non-zero mask
- [ ] TrOCR - non-zero (possibly causal) mask
- [ ] XGLM - additional clipping, different math
- [ ] XLNet - different formulas
- [x] YituTechConvBert 

However, to make this actually show up in the benchmarks we need to 
1) do constant folding to get rid of all-zero mask that's getting added to attention scores and forces sdpa to go on a slow path cc @zhaojuanmao @mrshenli @rohan-varma @awgu @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @eellison 
2) figure out either a way to pattern match with lowmem dropout, or run pattern-matching pass without lowmem dropout off, and if no match encountered, switch to  lowmem dropout cc @jancel
3) dynamic shapes present additional complications. During tracing, either memory efficient or flash or slow math implementation will be picked depending on the parameters, and, since (I think) we don't generate any guards for it, it will be used for other sizes that are later encountered, which will either lead to suboptimal performance or even runtime crashes, if fast implementation from trace cannot be used, cc @voznesenskym

**Comment by mikekgfb** [comment]
Re: 3) The answer may be to not pick one kernel but to build a small dispatcher similar to what the scaled_dot_product_attention kernel picker does - but can be with many fewer conditions because the hardware dependent options go away, leaving just dimensions.  (We can presumably specialize the picker for each data type iff we code gen it.  Otherwise, we still get a much simpler general dispatcher than is used by eager today.

**Comment by eellison** [comment]
1) is done: https://github.com/pytorch/pytorch/pull/103600

2) Low-mem dropout is now a pattern matcher pass (and temporarily reverted 😢) instead of happening earlier in the stack, so it no longer interferes.

3) I'm not sure this is actualy an issue. We won't trace out the exact backend use, just the high-level api. It's only an issue if the outputs have different striding depending on the implementation. In that case, we need to make sure that guards are added. This should be doable by symint-ifying the backend selection, just like we did for Conv.

**Comment by penguinwu** [comment]
@eellison @Chillee Since we made a lot of progress in this area, are the issues mostly done? If so, please close this one. If needed be, open new issues specific to remaining problems.
