### ISSUE TITLE
Documentation Error of torch.onnx

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#102084]
### 📚 The doc issue

https://pytorch.org/docs/stable/onnx.html#limitations says that 
- Any output that is a dict will be silently replaced with a flattened sequence of its values (keys will be removed). E.g. {"foo": 1, "bar": 2} becomes (1, 2).

- Any output that is a str will be silently removed.

But I find that str actually triggers error:

```
import torch
from torch import nn

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()

    def forward(self, x, y_dict):
        y = y_dict['value']
        output = x + y
        return 'haha', {'output': output}


# Create the module
module = MyModule()

# Example usage
x = torch.tensor(2.0)
y = {'value': torch.tensor(3.0)}
string, output_dict = module(x, y)
print(string)  # Prints: haha
print(output_dict)  # Prints: {'output': tensor(5.)}
torch.jit.trace(module, (x,y)) # RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions
```

I'm using PyTorch 1.12.0.

### Suggest a potential alternative/fix

Remove those two sentences.

cc @svekars @carljparker

**Comment by marqueslua** [comment]
Your documentation is about `torch.onnx`, but the code uses `torch.jit.trace`, which is a different function.

[jit.trace documentation](pytorch.org/docs/stable/generated/torch.jit.trace.html) says:
- Parameters: (...) func arguments and return values must be tensors or (possibly nested) tuples that contain tensors.

It says nothing accepting dicts or replacing dicts. That is a property of `onnx`.

Yes, `onnx` uses `jit.trace`, accordingly to its documentation:

- [Tracing](https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting): If torch.onnx.export() is called with a Module that is not already a ScriptModule, it first does the equivalent of [torch.jit.trace()](https://pytorch.org/docs/stable/generated/torch.jit.trace.html#torch.jit.trace)
- [Limitations](https://pytorch.org/docs/stable/onnx.html#limitations): Any output that is a dict will be silently replaced with a flattened sequence of its values (keys will be removed). E.g. {"foo": 1, "bar": 2} becomes (1, 2).

So the conclusion is that the property you are talking about is reffered to `onnx`, but does not extend to `jit.trace`.


> **However**, trying to run a simple onnx code, I also got errors while using dict.

    import torch
    import torch.nn as nn
    import torch.onnx as onnx
    
    class Net(nn.Module):
        def __init__(self):
            super().__init__()
            self.conv = nn.Conv2d(1, 1, 3)
    
        def forward(self, x_dict):
            x = x_dict['value']
            return self.conv(x)
    
    # Create the module
    n = Net()
    
    # Defining input
    example_input = {'value': torch.rand(1, 1, 3, 3)}
    
    # Exporting model in onnx format
    onnx.export(n, example_input, "model.onnx")

>     TypeError: Net.forward() missing 1 required positional argument: 'x_dict'

It only works when, instead of using a dict, I use a **list** containing a dict and another structure that is **not** a dict

    import torch
    import torch.nn as nn
    import torch.onnx as onnx
    
    class Net(nn.Module):
        def __init__(self):
            super().__init__()
            self.conv = nn.Conv2d(1, 1, 3)
    
        def forward(self, x_list):
            # receives a list with dict a tensor. x = the label 'value' inside the dict
            x = x_list[0]['value']
            return self.conv(x)
    
    # Create the module
    n = Net()
    
    # Defining input: a list with a dict and a tensor
    example_input = [{'value': torch.rand(1, 1, 3, 3)}, torch.rand(1, 1, 3, 3)]
    
    # Exporting model in onnx format
    onnx.export(n, example_input, "model.onnx")


### Conclusion

`torch.onnx` does not remove the labels, but yes completely remove the dict input (even if it is being used on `forward` function). When the input is just a dict, it is deleted and the function has a missing argument.

I don't know if that is the correct usage of this function, but it appears to be a incorrect information in `torch.onnx` documentation

**Comment by youkaichao** [comment]
@marqueslua so we share the same opinion that `torch.onnx` documentation needs to be fixed.

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add documentation, but contributions are still welcome

You can also try the new ONNX exporter and give us feedback: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
