### ISSUE TITLE
[Inductor] [CPU] sebotnet33ts_256 performance regression > 10% on 2023-05-21 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#102055]
### 🐛 Describe the bug

A performance regression on timm model **sebotnet33ts_256** on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1558372321) on 2023-05-21 as bellow:

|  2023-05-21  |   |     |   |  2023-05-18  |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|0.785037	 |0.121810745	|0.095625942	|1	|0.992768	 |0.096254825	|0.09555871	|0.79	|1	|0.79

2023-05-21 nightly release SW information:
SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[1c93857](https://github.com/pytorch/pytorch/commit/1c93857)|[9e8da7f](https://github.com/pytorch/pytorch/commit/9e8da7f)
Torchbench|/|[987bbec3](https://github.com/pytorch/benchmark/commit/987bbec3)
torchaudio|[894388d](https://github.com/pytorch/audio/commit/894388d)|[72d3fe0](https://github.com/pytorch/audio/commit/72d3fe0)
torchtext|[3cf1db6](https://github.com/pytorch/text/commit/3cf1db6)| [0dc07eb](https://github.com/pytorch/text/commit/0dc07eb)
torchvision|[50fb988](https://github.com/pytorch/vision/commit/50fb988)|[abc40ef](https://github.com/pytorch/vision/commit/abc40ef)
torchdata|[a754743](https://github.com/pytorch/data/commit/a754743)|[ba31745](https://github.com/pytorch/data/commit/ba31745)
dynamo_benchmarks|[174d01b](https://github.com/pytorch/pytorch/commit/174d01b)|/

2023-05-18 SW information:
SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[174d01b](https://github.com/pytorch/pytorch/commit/174d01b)|[ 41d668c](https://github.com/pytorch/pytorch/commit/41d668c)
Torchbench|/|[987bbec3](https://github.com/pytorch/benchmark/commit/987bbec3)
torchaudio|[894388d](https://github.com/pytorch/audio/commit/894388d)|[72d3fe0](https://github.com/pytorch/audio/commit/72d3fe0)
torchtext|[3cf1db6](https://github.com/pytorch/text/commit/3cf1db6)| [0dc07eb ](https://github.com/pytorch/text/commit/0dc07eb )
torchvision|[50fb988](https://github.com/pytorch/vision/commit/50fb988)|[abc40ef ](https://github.com/pytorch/vision/commit/abc40ef )
torchdata|[a754743](https://github.com/pytorch/data/commit/a754743)|[ba31745 ](https://github.com/pytorch/data/commit/ba31745 )
dynamo_benchmarks|[174d01b](https://github.com/pytorch/pytorch/commit/174d01b)|/

Graph dump by cosim:
2023-05-21:
[graph.txt](https://github.com/pytorch/pytorch/files/11540084/graph.txt)

2023-05-18:
[graph.txt](https://github.com/pytorch/pytorch/files/11540088/graph.txt)

### Versions

Minified repro:

```bash
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/timm_models.py --performance --inference --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only sebotnet33ts_256  --cold_start_latency --batch_size 1 --threads 1

```

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by XiaobingSuper** [comment]
@ESI-SYD, could you help break down which commit introduce this regression?

**Comment by XiaobingSuper** [comment]
@Valentine233, could you help see it?

**Comment by Valentine233** [comment]
Here is a rough break down for the regression and the regression is due to several commits. On 5/19, there existed an improvement for eager. On 5/20, there existed a regression for inductor and an improvement for eager.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xuanliao/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xuanliao/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72" lang=en-US>



Date | commit on nightly | commit on main | speedup | eager | inductor
-- | -- | -- | -- | -- | --
18-May | 329bb2a | 900ca4d | 1.211x | 0.147326 | 0.121633
19-May | 61239df | f66d5dd | 1.154x | 0.139017 | 0.120444
20-May | aa43e0d | 0c6f409 | 0.900x | 0.133408 | 0.14825
21-May | 1c938577d85610f3bd10fbd3689744d98e929989 | 9e8da7f | 0.904x | 0.13323 | 0.14731



</body>

</html>

**Comment by Valentine233** [comment]
The speed went back to 0.984456 on 5/31 via dashboard.
