### ISSUE TITLE
FX-ONNX exporter - TypePromotion

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#102179]
### 🚀 The feature, motivation and pitch

PyTorch might have implicit type promotion inside operators which if we don't type promote these cases, it will reuslt in a broken ONNX graph. In general, there are several points to consider:

1. Another graph-level pass vs inside `fx_to_onnxscript` pass: 
The former proposes another graph level pass that we leverage on torch api, such as `call_function` to add Cast into FX graph. In this case, we won't have to call out `Evaluator` to add external nodes. However, this could cost another loop of going through the torchlib functions we need in the graph. On the other hand, if we have it inside `fx_to_onnxscript`, we can only iterate the graph one time, but an extension of `Evaluator` (Or even another new evaluator) is needed.

2. Leverage in FX graph output type vs maintain `type_promotion_kind`s in torchlib
Ideally, `type_promotion_kind` represents a set of logic of how casting should be done based on arg/output types. Alternatively, we can leverage on FX graph output type to follow the torch type promotion.

cc @BowenBao @justinchuby @thiagocrepaldi 

### Additional context

https://github.com/microsoft/onnxscript/issues/563 - design discussion
https://github.com/microsoft/onnxscript/issues/746 - torchlib should provide the information of type promotion

**Comment by thiagocrepaldi** [comment]
Not sure if I understood option 2). Is it what we have discussed before?

The discussed idea is to not use a pre/post-process pass, but rather to delegate to dispatcher to make such decision.
In short, the ONNX dispatcher receives an operator and input dtypes and decides whether to dispatch the actual opname or if it will wrap cast nodes for the inputs and/or outputs.

With opname and dtypes, the dispatcher can
* mimic any built-in type promotion that python/pytorch would do before dispatching logic starts
* compare input dtypes with onnx candidates. The type comparison must account for the ONNX schema type constraints (T, T1, T2, etc) to make sure a valid (this feature is not available yet, but should be easy to implement)
  * when a perfect match happens, a dispatch for the opname happens
  * otherwise, dispatcher can dispatch a cast for the input(s) and then dispatch the actual opname.
    * The dispatcher could also dispatch a cast for the output, if necessary

Although passes are ideal when global information (e.g., full graph) is needed to make a decision, type promotion is a simpler case, in which local context is available to make the best decision.
local decision making is nice because it preserves eager behavior of python/pytorch. Passes, on the other hand, potentially allows a onnx node with mismatching type which would be fixed as a post-process step. Generating an incorrect graph to fix it later is harder to maintain because it creates order-dependency between passes execution. If any other pass need to run before the type promotion pass, for example, we would have problems (which pass will run first?!)

**Comment by titaiwangms** [comment]
I think one of the convincing point of doing type promotion inside `fx_to_onnxscript` pass is that we would be aboe to do it in "one iteration of the graph". Personally, I think using `call_function` is attenpting, but if we wanted to consult OpSchema from ONNX, it's inavoidable to run iteration twice to get its OpSchema for the graph pass. So I think graph-level pass is great if and only if we don't need to consult OpSchema.

Let's say we decide to do it inside `fx_to_onnxscript` pass with the very same iteration of op conversion. I think the dispatcher doesn't have to be part of the type promotion. It's job is done which is to find the perfect ONNX overload. The next step would be simply consult OpSchema, and add op.Cast if it's needed. And the step could either be in "between dispatch and calling OnxFunction" or in "OnnxFunction". This is discussable.

**Comment by thiagocrepaldi** [comment]
> I think one of the convincing point of doing type promotion inside `fx_to_onnxscript` pass is that we would be able to do it in "one iteration of the graph". Personally, I think using `call_function` is appealing, but if we wanted to consult OpSchema from ONNX, it's inavoidable to run iteration twice to get its OpSchema for the graph pass. So I think graph-level pass is great if and only if we don't need to consult OpSchema.
> 
> Let's say we decide to do it inside `fx_to_onnxscript` pass with the very same iteration of op conversion. I think the dispatcher doesn't have to be part of the type promotion. It's job is done which is to find the perfect ONNX overload. The next step would be simply consult OpSchema, and add op.Cast if it's needed. And the step could either be in "between dispatch and calling OnxFunction" or in "OnnxFunction". This is discussable.

Take into consideration that `fx_to_onnxscript` is not a proper pass, and will probably be refactored/deleted soon. In fact, the expectation is that the dispatcher abstraction would replace it entirely. Instead, the dispatching responsibility is now shared across the dispatcher class and fx_to_onnxscript

**Comment by thiagocrepaldi** [comment]
How is onnxscript considering to expose the constraint types information? Only when this is defined that we can define the best way to implement type promotion (which consumes such info)

**Comment by thiagocrepaldi** [comment]
@titaiwangms should we close this?

**Comment by BowenBao** [comment]
Thx @thiagocrepaldi, this is done in exporter. Closing.
