### ISSUE TITLE
Can't call allow_in_graph inside of a function being torch.compile'd 

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#103615]
### 🐛 Describe the bug

We are unable to call allow_in_graph inside of a function being torch.compile'd with fullgraph=True and the error message is confusing. We should either allow this or improve the error message.
```py
import torch
import torch._dynamo

@torch.compile(backend='aot_eager', fullgraph=True)
def f(x):
    @torch._dynamo.allow_in_graph
    def apply_func(x):
        return x.clone()
    
    return apply_func(x)

x = torch.randn([], requires_grad=True)

f(x)
```
produces: 
> Unsupported: call_function allow_in_graph in skip_files /raid/rzou/pt/debug-cpu4/torch/_dynamo/__init__.py

Discovered with @drisspg 

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @wconstab

**Comment by mlazos** [comment]
arbitrarily assigned @anijain2305 

initial thought is that we should have a better error message here. I don't think we can handle this in fullgraph mode since we want to guarantee that the code being traced is represented by the "full" FX graph and that there are no graph breaks, this isn't guaranteed with an arbitrary function allowed in the graph.

**Comment by mlazos** [comment]
@anijain2305 any progress on this?

**Comment by DuyguA** [comment]
Hello @mlazos  and @anijain2305  , I made a quick PR and added an error message. Please have a look :blush:
