### ISSUE TITLE
How some doc files are generated?

### ISSUE THREAD

**Issue by sdsy888** [pytorch/pytorch#10376]
I'm reading the doc files of the [pytorch](https://pytorch.org/docs/stable/tensors.html). And I know a little about the sphinx.

But when I see [this doc file](https://pytorch.org/docs/stable/tensors.html), I couldn't find the corresponding source file from which this doc file is generated.  For example,  the content below seems like it is written by hand directly in the `tensors.rst` file

```
.. class:: Tensor()

   There are a few main ways to create a tensor, depending on your use case.

   - To create a tensor with pre-existing data, use :func:`torch.tensor`.
   - To create a tensor with specific size, use ``torch.*`` tensor creation
     ops (see :ref:`tensor-creation-ops`).
   - To create a tensor with the same size (and similar types) as another tensor,
     use ``torch.*_like`` tensor creation ops
     (see :ref:`tensor-creation-ops`).
   - To create a tensor with similar type but different size as another tensor,
     use ``tensor.new_*`` creation ops.

```

Is all the content in [this doc file](https://pytorch.org/docs/stable/tensors.html) written by hand?

Thank you!

**Comment by weiyangfb** [comment]
The source you are looking for is [here](https://github.com/pytorch/pytorch/blob/master/torch/_tensor_docs.py). If I understand correctly, the API document htmls are autogenerated by Sphinx based on `*.rst` with docstrings at `*_docs.py`.

**Comment by sdsy888** [comment]
@weiyangfb Thank you for your kind reply!

My question is, **How does the `*.rst` files are generated?**

I've found these files, but these `*_docs.py` files is for adding`docString` to the corresponding class and methods in `*.rst`, rather than controlling the whole content in the `*.rst` files.

For short, I know the `*.rst` files could generate the htmls in `PyTorch` repo. But how does these `*.rst` files are generated? For my knowledge, these `rst` files could be generated by `sphinx-apidoc -o` command or by being written by hand.  

Some content in html files (or their corresponding `*.rst` files) do NOT exist in any of these `*_docs.py` files or other `*.py` files. 

For an example:
Just like I mentioned above, (please see [here](https://pytorch.org/docs/stable/tensors.html)), the docString below the `.. class:: Tensor()` in the `tensors.rst` (which could be used to generate html, like you said) could not be found in any `*.py` file.

**Comment by goodlux** [comment]
@sdsy888 That .rst file is written by hand...or actually, by...hands. You can see the history of the .rst file here. 

https://github.com/pytorch/pytorch/commits/master/docs/source/tensors.rst

The .rst references parts of the code base with sphinx directives, like:  

.. class:: Tensor() and .. automethod:: add

The directives are added in as new methods are added. It is not autogenerated. I think originally this was probably done because of limitations with autogenerated docs, and perhaps autogenerating would show some code that wasn't ready to be in the docs. 

The .rst files are processed with sphinx-build, sphinx-apidoc isn't used.
