### ISSUE TITLE
from torch._C import *  ImportError: DLL load failed: The specified procedure could not be found,in pycharm

### ISSUE THREAD

**Issue by sabareeshmj** [pytorch/pytorch#103961]
### 🐛 Describe the bug

from torch._C import *

### Versions

StatusCode        : 200
StatusDescription : OK
Content           :
                    # Unlike the rest of the PyTorch this file must be python2 compliant.
                    # This script outputs relevant system environment info
                    # Run it with `python collect_env.py`.
                    import datetime
                    import locale
                    impor...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src 'unsafe-inline'; sandbox], [Strict-Transport-Security, max-age=31536000],        
                    [X-Content-Type-Options, nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 21676

**Comment by janeyx99** [comment]
Hello, it looks like you are unable to import torch, which likely means you have not installed it properly. It also seems like you requested the contents of collect_env over the web instead of running it locally to help debug.

As the problem does not seem to come from torch, I am closing this issue for now. If you could clarify the request for pytorch with more context and a repro, please don't hesitate to reopen.
