### ISSUE TITLE
Calling all on empty MPS tensor yields wrong result

### ISSUE THREAD

**Issue by LMescheder** [pytorch/pytorch#104694]
### 🐛 Describe the bug

Minimal example:

```
import torch
x_cpu = torch.tensor([], dtype=torch.bool)
x_mps = x_cpu.to("mps")
assert x_cpu.all() == x_mps.all().cpu()
```
fails, since `x_cpu.all()` (correctly) yields `true`, while `x_mps.all()` yields `false`.

### Versions

PyTorch version: 2.1.0.dev20230702
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.3
Libc version: N/A

Python version: 3.8.16 (default, Mar  1 2023, 21:19:10)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.1.0.dev20230702
[pip3] torchaudio==2.1.0.dev20230702
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.16.0.dev20230702
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h59209a4_43558
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.1.0.dev20230702          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230702          pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.16.0.dev20230702          pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by davidradl** [comment]
I am investigating.

**Comment by davidradl** [comment]
I see that the numpy all() is defined as `In numpy, we can check that whether none of the elements of given array is zero or not with the help of numpy.all() function. In this function pass an array as parameter. If any of one element of the passed array is zero then it returns False otherwise it returns True boolean value. ` And an empty array for all() returns True.

So I agree the cpu case is correct.

I notice that the code in aten/native/mps/operations/reduce_ops.mm has code
```
TORCH_IMPL_FUNC(any_all_out_mps)(const Tensor& input_t, const Tensor& output_t) {
  using namespace mps;
  using CachedGraph = MPSUnaryCachedGraph;
  if (input_t.numel() == 0) {
    output_t.zero_();
    return;
  } else if (input_t.numel() == 1) {
    output_t.copy_(input_t.view_as(output_t).to(at::kBool));
    return;
  } else if (output_t.numel() == 0) {
    return;
  }
```
So for a zero length input tensor it should return True  - but we see False in the reported case.

I notice that operation count_nonzero() is also inconsistent - with cpu reporting 0 and mps reporting a large number.

**Comment by davidradl** [comment]
I am not sure if anyone can assign this to me as I am looking at it.
