### ISSUE TITLE
autograd.Function tracing errors loudly in some situations involving saved tensors

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#104792]
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_autograd_function.py#L324-L352
```py
        class LowerBound(torch.autograd.Function):
            @staticmethod
            def forward(ctx, inputs, bound):
                ctx.save_for_backward(inputs, inputs.new_ones(1) * bound)
                return inputs.clamp(min=bound)

            @staticmethod
            def backward(ctx, grad_output):
                inputs, bound = ctx.saved_tensors
                return (inputs >= bound) * grad_output, None
```
If we have something like the above:
- a SubgraphTracer gets created to run forward(), then gets discarded
- a new SubgraphTracer gets created to run backward()
- inputs, bound have Proxies that were created inside of forward's SubgraphTracer
- (inputs >= bound) constructs a new Proxy that has .tracer set to forward's SubgraphTracer (torch.fx has some special handling for dunder functions that bypasses calling call_function with the correct instruction translator?)
- `(inputs >= bound) * grad_output` - when the backward's SubgraphTracer sees this, it attempts to lift `(inputs >= bound)` to be an input and recursively to all parent SubgraphTracer. Unfortunately, the Proxy is not a part of any active tracer (the backward tracer and the root tracer are active), so this raises loudly.

https://github.com/pytorch/pytorch/pull/104378 was an attempt to fix this, but I reverted the change because it was more of a hack.

A fix could be something like: when we introspect the backward tracer, we should just take the proxies in ctx.saved_tensors and treat them as inputs to the subgraph being traced. cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym if you have more thoughts

### Versions

main

**Comment by ezyang** [comment]
Yes the morally right thing is for ctx.saved_tensors to be treated as inputs when tracing backwards.

**Comment by yanboliang** [comment]
I debug this with @ydwu4 this afternoon and we found the root cause is a dynamo bug when handling some particular op (```>=``` in this example). Let me explain with the above example:
* ```inputs```, ```bound``` have Proxies that were created inside of forward's SubgraphTracer.
* ```inputs >= bound``` constructs a new Proxy that has ```.tracer``` set to forward's SubgraphTracer. This is because for the [```fx.graph.magic_methods```](https://github.com/pytorch/pytorch/blob/6aa91c8dad7b94960fc4cc642ef27b6d406c215e/torch/fx/graph.py#L1594), FX create a new proxy using the first argument's tracer.
https://github.com/pytorch/pytorch/blob/6aa91c8dad7b94960fc4cc642ef27b6d406c215e/torch/fx/proxy.py#L540-L543
* This assumption was true when there is no higher order ops. Since ```autograd.Function``` was wrapped as higher order ops, when creating the proxy of ```inputs >= bound```, we should use the current tracer (the bwd SubgraphTracer) rather than the first argument's tracer (the fwd one). I sent #111277 to fix this.
* Another evidence is if we change ```inputs >= bound``` to ```inputs + bound``` in the original example, it works well even w/o my fix. This is because the ```+``` proxy was created with correct tracer in dynamo, only a few ops have wrong implementation.
