### ISSUE TITLE
torch.autograd.set_multithreading_enabled doesn't work as a function

### ISSUE THREAD

**Issue by kumpera** [pytorch/pytorch#104985]
### 🐛 Describe the bug

The documentation for `torch.autograd.set_multithreading_enabled` says that "It can be used as a context-manager or as a function." but it doesn't work unless you store the result as it will act as a context manager and undo the value once the returned value gets destroyed.

We should either document that fact of fix `set_multithreading_enabled` behavior.

It's rather complicated to write a test for such trivial situation as there's no getter for that autograd property.

### Versions

master

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
That does sound like a bug. I think we should:
- Update this function to set the flag on a function call (you shouldn't have to store the result)
- We can add a getter for this property to be able to test this

**Comment by MrinalTyagi** [comment]
Would like to work on this.

**Comment by albanD** [comment]
Thanks!
You can send a PR doing the two things above with corresponding tests!
Don't hesitate to ask here if you need any guidance.

**Comment by poseljacob** [comment]
Hi @albanD, 

Would it be ok if I tried to work on it too?

**Comment by albanD** [comment]
If @MrinalTyagi is not actively working on it, sure.

**Comment by poseljacob** [comment]
Thank you.
In terms of adding a getter, would we want to expose the C++ get_multithreading_enabled() getter to Python?
Or
Simply add a get_mode method to the python class?

**Comment by albanD** [comment]
Adding a `torch.autograd.get_multithreading_enabled()` sounds good.

For changing the behavior, it might just need an update on the py_context_manager wrapper. I'm not sure.

**Comment by poseljacob** [comment]
Hi @albanD. 
Is the expected behavior for 'acting as a function' the following?:
`
>>> torch.autograd.set_multithreading_enabled(False)
<torch.autograd.grad_mode.set_multithreading_enabled object at 0x10d4218e0>
>>> assert torch._C._get_multithreading_enabled == False
`
If so, are we sure it is possible for it to act as both a function and context-manager? I have added other getters for properties which are described as "It can be used as a context-manager or as a function." such `as _force_original_view_tracking`, which similarly do not work as functions:
`
>>> with torch.autograd._force_original_view_tracking(False):
...     torch._C._get_view_replay_enabled()
... 
False

>>> with torch.autograd._force_original_view_tracking(True):
...     torch._C._get_view_replay_enabled()
... 
True


# not working as function 
>>> torch.autograd._force_original_view_tracking(True)
<torch.autograd.grad_mode._force_original_view_tracking object at 0x10d421610>
>>> torch._C._get_view_replay_enabled()
False
`

I would really appreciate your guidance on this issue!

**Comment by albanD** [comment]
Hey!
`torch.set_grad_enabled()` should be a good example of one that behaves as expected!

**Comment by poseljacob** [comment]
Hey!

Thanks so much for your help so far. 

From my understanding, the behavior of set_multithreading_enabled when used as a function seems to be impacted by the way its underlying C++ implementation is structured.

When we use set_multithreading_enabled as a function, the goal is to set a global state that persists until explicitly changed. However, as the C++ class MultithreadingEnabled resets the multithreading state when the object is destroyed, the Python's garbage collector might lead to resetting at unpredictable times. This, I believe, is what is preventing the function from working as intended.

On the other hand, set_grad_enabled function works as expected, because its C++ implementation directly modifies a global state, which persists until it's changed again.

So, it seems like the desired functionality for set_multithreading_enabled to act as a function might require changes in the C++ implementation to align its behavior more closely to how set_grad_enabled function works. Possibly, we could consider changing the MultithreadingEnabled C++ class so it doesn't automatically reset the multithreading state upon object destruction, or perhaps we might need to create a new C++ function that directly modifies a global multithreading state.

Of course, I could be misunderstanding the situation, so any guidance or additional insight you could provide would be greatly appreciated.

Thank you!

**Comment by poseljacob** [comment]
Hi @albanD, I have created the above PR which attempts to implements that change, more closely aligning the pattern used by `set_grad_enabled`. I would appreciate your feedback! Thanks!
