### ISSUE TITLE
 torch.matrix_exp Performance Issue - Extreme Slowness on GPU (3x slower than CPU)

### ISSUE THREAD

**Issue by h-skibbe** [pytorch/pytorch#105225]
### 🐛 Describe the bug

Hi,

I have encountered a performance issue with the torch.matrix_exp function, where it becomes significantly slow, particularly when running on a GPU. The slowdown occurs despite the input matrix values seeming normal and correct.

This issue has been reproduced across multiple systems, including but not limited to the NVIDIA RTX A5000 Mobile GPU and the A100 GPU.

I am unsure if the problem is limited to these specific GPU models or if it's a more widespread issue. Any help or insight into this matter would be highly appreciated.

Thank you for your time and attention to this matter.

Best Regards,
Henrik 

Example:

```python
import time
import torch
ti = torch.tensor([[[[[[ 1.3928, -0.6127,  0.1813],
            [-0.7089,  1.6513, -0.4091],
            [-0.0032, -0.1018,  1.1634]]]]]])



for f in [0.1,1,2]:
    for dev in ["cpu","cuda"]:
        tmp2 = torch.zeros([20,32,32,32,3,3]).to(dev)
        tmp2[...] = f*ti[None,None,None,None,:,:].to(dev)
        
        start = time.time()
        tmp = torch.matrix_exp(tmp2)
        print("dev:",dev," time:",time.time()-start," f:",f)
```

Output:

```
dev: cpu  time: 0.028986215591430664  f: 0.1
dev: cuda  time: 0.0626072883605957  f: 0.1
dev: cpu  time: 1.7721340656280518  f: 1
dev: cuda  time: 4.586091041564941  f: 1
dev: cpu  time: 3.120410442352295  f: 2
dev: cuda  time: 10.301678657531738  f: 2
```

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB

Nvidia driver version: 525.125.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7502 32-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     2500.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4999.84
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                  AMD-V
L1d cache:                       2 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        32 MiB (64 instances)
L3 cache:                        256 MiB (16 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] numpydoc==1.5.0
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.5          py310hd5efca6_0  
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] numpydoc                  1.5.0           py310h06a4308_0  
[conda] pytorch                   2.0.1           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py310_cu118    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.2              py310_cu118    pytorch

cc @ptrblck @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment]
The original benchmark is not great, as it doesn't synchronise, but I can repro the numbers, e.g.
```python
import torch
from torch.utils.benchmark import Compare, Timer


def get_timer(A):
    timer = Timer(
        r""" torch.matrix_exp(A)""",
        globals=locals(),
        label="matrix_exp",
        description=f"{A.device}",
        sub_label=f"shape {tuple(A.shape)}",
        num_threads=torch.get_num_threads()
    )
    return timer.blocked_autorange()


def get_params():
    shape = [20,32,32,32,3,3]
    for device in ("cpu", "cuda"):
        yield (torch.randn(shape, device=device),)


compare = Compare([get_timer(*params) for params in get_params()])
compare.trim_significant_figures()
compare.print()
```

Gives in an RTX 2060
```
[------------------------ matrix_exp ------------------------]
                                    |   cpu   |  cuda:0
32 threads: -------------------------------------------
      shape (20, 32, 32, 32, 3, 3)  |  2.013  |  7.245 

Times are in seconds (s).
```

It all boils down to the fact that cusolver's  `gemm` (or our heuristics) are not optimised for huge batches of small matrices. I get similar numbers for the operation `A @ A` for the same shape.

**Comment by JubilantJerry** [comment]
Though I agree `gemm` seems not quite optimized for this shape, I think the issue is different, because `gemm` seems to improve with better hardware while `matrix_exp` does not:

```
On a GTX 1060:
In [5]: v = torch.randn(1000000, 2, 2, device='cuda')

In [6]: %timeit torch.bmm(v, v); torch.cuda.synchronize()
18.5 ms ± 19.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: %timeit torch.matrix_exp(v); torch.cuda.synchronize()
5.37 s ± 149 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [25]: v = torch.randn(100000, 8, 8, device='cuda')

In [26]: %timeit torch.bmm(v, v); torch.cuda.synchronize()
5.34 ms ± 20.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [27]: %timeit torch.matrix_exp(v); torch.cuda.synchronize()
1.92 s ± 70.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
```
On an A100:
In [11]: v = torch.randn(1000000, 2, 2, device='cuda')

In [12]: %timeit torch.bmm(v, v); torch.cuda.synchronize()
1.6 ms ± 549 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [13]: %timeit torch.matrix_exp(v); torch.cuda.synchronize()
5.01 s ± 29.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [21]: v = torch.randn(100000, 8, 8, device='cuda')

In [22]: torch.backends.cuda.matmul.allow_tf32 = True

In [23]: %timeit torch.bmm(v, v); torch.cuda.synchronize()
601 µs ± 395 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [24]: %timeit torch.matrix_exp(v); torch.cuda.synchronize()
1.98 s ± 6.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [25]: torch.backends.cuda.matmul.allow_tf32 = False

In [26]: %timeit torch.bmm(v, v); torch.cuda.synchronize()
601 µs ± 253 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [27]: %timeit torch.matrix_exp(v); torch.cuda.synchronize()
1.98 s ± 6.02 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I encountered a similar issue, for my case I believe it's a problem about parallelism: #107291

**Comment by nikitaved** [comment]
Is it not the case of huge batches of very tiny matrices dispatching to Magma?..

**Comment by lezcano** [comment]
That's due to the way we implement `matrix_exp`, indeed. We do a scale-squaring step, which is typical when using approximants, as we do. The squaring step needs to be done on a per-matrix base, and at the moment we do a synchronisation per matrix, and we do it sequentially in the batch dimension, hence the perf hit.

A better way of doing this would be to sort the matrices by their norm, and then do the squaring step on a bunch of matrices at the time. If done efficiently and somewhat in-place, it would speed-up the efficiency for large batches quite a bit.

**Comment by nikitaved** [comment]
Good catch, @lezcano. IIRC, we had a discussion about that, but decided not to over-complicate things back then...

**Comment by lezcano** [comment]
Also, we currently do even worse, with even more synchronisations, as we use a `compute_highest_degree_approx = false` flag. Probably setting `compute_highest_degree_approx=true` would already be a reasonable perf win. This would not affect accuracy, as we would be computing a more precise approximation really.

**Comment by lezcano** [comment]
That looks like it could work. There are a couple things that could be improved though:
- It's best to simply work with the base 2 logs of the pows rather than computing them explicitly, and then computing the squaring explicitly as well.
- Note that if you have to square once 20 matrices and then square twice another 20 matrices, it's best to first square once 40 matrices and then square once 20. The call to `matrix_power` here hides another loop, which we can elide if we compute things this way
- Most probably you'll need to call `contiguous` on the output to be sure you preserve the semantics.
- From getting `sorted_s[split_sizes]` probably the rest of the computation that's not matrix related is best to be done in python (in core it should be C++, but yeah).

@JubilantJerry  If you want to make a contribution to PyTorch, we would accept a PR implementing all these points in PyTorch. They may need to go with some threshold where for small batches we still do the loop, and for larger batches we move to this implementation. We should benchmark that.

**Comment by JubilantJerry** [comment]
I'm not so familiar with ATen code, assuming it works like the normal PyTorch interface where a graph tracks the backward, it seems like there could be some challenges with implementing the second optimization. If we want to preserve gradients then we can't use inplace operations except for special circumstances, so there might be problems with trying to overlap the matrix power operations without potentially forcing a lot of memory to be used in buffers for the backward. E.g. if 100% of the batch needs power 2 and 80% of the batch needs power 4 and 60% of the batch needs power 8, then I imagine it's easy for the implementation to require 240% of the input size as intermediate buffers.

If there's a separate backward instead, I'm not sure how that is implemented. From what I can tell, matrix exponentials don't have an analytic form for the derivative, so this must be really complicated.

As for the non-matrix computations, for an input of size `(N, D, D)` I think any array of size `(N,)` still shouldn't be transferred from device to host because it can still be a considerable amount of data. But indeed, `pows` and `split_sizes` are less than length 20 and they can be transferred to the host. I suspect that in practice, almost all values in a batch are accounted by 1 or 2 pieces.

If the change is simple, I think I can take some time to implement a PR in a few weeks, but I might not have time if the engineering effort is big and the code must become very different from my version.

**Comment by lezcano** [comment]
The backwards is implemented separately. For a reference, see theorem 6.3.3 and the reference in https://arxiv.org/pdf/2203.04794.pdf (insane self-plug). You can also have a read at 6.3.2 for a quick review of different algorithms and so on.

For the batchsize, you can test the two options and see which one's faster. 10k elements is very small (it almost fits in L2 even) so I really think that it'll be faster in CPU, as otherwise just the kernel launch overhead will probably be more costly than the CPU computation.

The PR should be pretty much an adaptation of your code. A prerequisite would be to build PyTorch from source in your machine. See the contribution guide for that. After that, ATen is relatively similar to the Python frontend, only that in C++. I will announce it as a good first issue, see if anyone wants to pick it up tho.

**Comment by lezcano** [comment]
Yes. You can see the function that implements its derivative (and that of any other function with explicit derivative) by looking at `derivatives.yaml`.

As per the result, just compute the powers of that matrix in there and you'll see that it's direct (a posteriori, of course) :)

**Comment by lezcano** [comment]
And yeah, the adjoint is the coordinate-free way to understand the "backward of a map between spaces". It helps to generalise these concepts to more general spaces like manifolds or Hilbert spaces.

**Comment by JubilantJerry** [comment]
I've since discovered that my workaround function from above runs slow for backward. This is because the function doesn't try to ensure that the matrix used in the backward call has a small L1 norm. The construction using the Adjoint of Analytic Functions of Matrices theorem can create a matrix whose L1 norm is high enough that the slow code path is used to calculate the matrix exponential, even though the matrix used in the forward call is processed with the fast code path.

This can be fixed simply by manually implementing the backward with the Adjoint theorem to once again use my workaround implementation:
```python3
class BatchMatrixExp(torch.autograd.Function):
    @staticmethod
    def forward(batch):
        """Workaround for poor matrix_exp parallelism for large batches
        See https://github.com/pytorch/pytorch/issues/107291 for details
        The result may be less precise than torch.matrix_exp"""
        assert batch.dtype == torch.float
        batch_shape = batch.shape
        mat_size = batch_shape[-1]
        batch = batch.reshape(-1, mat_size, mat_size)
        theta_thres = 1.461661507209034e+00
        norms = batch.data.abs().sum(-2).max(-1).values
        s = (torch.floor(torch.log2(norms / theta_thres)) + 1).clamp(min=0)
        s_max = s.max().cpu()
        has_nan = torch.isnan(s_max).item()
        s_max = s_max.item()
        if has_nan:
            # As of PyTorch 2.0.1, matrix_exp on nan causes undefined behavior
            return torch.full_like(batch, torch.nan)
        output_scaled = torch.matrix_exp(
            batch * torch.pow(2.0, -s).reshape(-1, 1, 1))
        sorted_s, sorted_s_inds = torch.sort(s, dim=0)
        sorted_s_aug = torch.nn.functional.pad(sorted_s, (0, 1), value=s_max + 1)
        split_edges = (torch.diff(sorted_s_aug) > 0).nonzero()[:, 0]
        pows = torch.pow(2, sorted_s[split_edges].long())
        split_sizes = torch.nn.functional.pad(split_edges, (1, 0), value=-1)
        split_sizes = torch.diff(split_sizes)
        split_sizes = tuple(split_sizes.cpu().numpy().tolist())
        ind_pieces = torch.split(sorted_s_inds, split_sizes, dim=0)
        output_pieces = []
        for pow_v, ind_piece in zip(pows, ind_pieces):
            output_pieces.append(torch.matrix_power(
                output_scaled[ind_piece], pow_v))
        output = torch.cat(output_pieces, dim=0)
        output = output[torch.argsort(sorted_s_inds)]
        output = torch.reshape(output, batch_shape)
        return output

    @staticmethod
    def setup_context(ctx, inputs, output):
        ctx.save_for_backward(*inputs)

    @staticmethod
    def backward(ctx, grad):
        batch, = ctx.saved_tensors
        dim = batch.shape[-1]
        batch_T = torch.transpose(batch, -2, -1)
        larger_mat = torch.cat((
            torch.cat((batch_T, grad), dim=-1),
            torch.cat((torch.zeros_like(grad), batch_T), dim=-1)), dim=-2)
        return torch.narrow(torch.narrow(
            BatchMatrixExp.apply(larger_mat), -2, 0, dim), -1, dim, dim)
```
This detail doesn't affect how the official fix should be written, since the fix occurs in a function that is used in both the forward and the backward calls.

**Comment by scruel** [comment]
Hi @nikitaved, after discussing with @JubilantJerry, I am now working to implement this.

**Comment by lezcano** [comment]
Here's a sketch for a better algorithm (we batch better the matmuls). This code *does not work* ATM and I don't have time to finish it, but you get the idea. I'm including also code to benchmark it:

```python
import torch
from torch.utils.benchmark import Timer, Compare


def mexp(A):
    """Workaround for poor matrix_exp parallelism for large batches
    See https://github.com/pytorch/pytorch/issues/107291 for details
    The result may be less precise than torch.matrix_exp"""
    A_shape = A.shape
    A = A.flatten(end_dim=-3)
    theta_thres = 1.461661507209034e+00
    norms = torch.linalg.matrix_norm(A, ord=1)
    s = (torch.floor(torch.log2(norms / theta_thres)) + 1).clamp(min=0)
    s_max = s.max().cpu().item()
    is_nan = s_max != s_max
    if is_nan:
        # As of PyTorch 2.0.1, matrix_exp on nan causes undefined behavior
        return torch.full_like(A, torch.nan)
    # rescale
    output_scaled = torch.matrix_exp(A * torch.pow(2.0, -s).view(-1, 1, 1))

    # sort
    sorted_s, sorted_s_inds = torch.sort(s, dim=0)
    split_counts = torch.unique_consecutive(sorted_s, return_counts=True)[1]
    split_edges = torch.cumsum(split_counts, dim=0) - 1
    split_adv = torch.diff(split_edges, prepend=split_edges.new_zeros([1]))
    unique_s = sorted_s[split_edges].long()
    diffs = torch.diff(unique_s, prepend=unique_s.new_zeros([1]))

    idxs = split_adv.tolist()
    ps = diffs.tolist()

    acc = output_scaled
    output_pieces = []
    for i, p in zip(idxs, ps):
        for _ in range(p):
            acc = acc @ acc
        output_pieces.append(acc[:i+1])
        acc = acc[i+1:]

    # Compose the result back
    output = torch.cat(output_pieces, dim=0)
    output = output[torch.argsort(sorted_s_inds)]
    output = torch.reshape(output, A_shape)
    return output


def gen_inputs():
    x = torch.randn(1000000, 8, 8, device="cuda")
    # 174ms
    for fn in (mexp,):
        yield fn, x


def benchmark(f, x):
    torch.testing.assert_close(f(x[:8]), torch.matrix_exp(x[:8]))
    return Timer("f(x)",
                 globals=locals(),
                 label="Norm",
                 sub_label=f"{f.__name__}",
                 description=str(tuple(x.shape)),
                 num_threads=torch.get_num_threads()).blocked_autorange(min_run_time=2)


results = []
for args in gen_inputs():
    results.append(benchmark(*args))

compare = Compare(results)
compare.trim_significant_figures()
compare.print()
```

**Comment by lezcano** [comment]
The issue above was that I was not sorting the input. Fixed :)

**Comment by scruel** [comment]
@lezcano 
Hi, we've done the draft version implementation in C++, and have some questions which might need your advice:
1. For accessing the values of tensor by index, we are using `Tensor.accessor<T, N>()` to do the implementation, consider we have no `tolist` method in C++, should it be ok or do you have any other advices?
2. For matrix multiplication, don't you think we can use `matmul_out` instead of `matmul` to prevent double buffer problem or not?

```cpp
  auto idxs = split_adv.accessor<int64_t, 1>();
  auto ps = diffs.accessor<int64_t, 1>();

  Tensor acc = mexp_scaled.index_select(0, sorted_s_inds);
  std::cout << "acc: " << acc << std::endl;
  std::vector<Tensor> output_pieces;
  for (int64_t i = 0; i < split_adv.numel(); ++i) {
    for (int64_t j = 0; j < ps[i]; j++) {
        acc = acc.matmul(acc);
    }
    output_pieces.push_back(acc.slice(0, 0, idxs[i] + 1));
    acc = acc.slice(0, idxs[i] + 1);
  }
```
Thanks!

**Comment by JubilantJerry** [comment]
The double buffer problem here refers to the fact that a new matrix is allocated for every call to `acc.matmul(acc)`, and that it may be possible to limit the allocations required if `matmul_out` is used along with two temporary buffers.
We thought it could be a problem because we aren't too sure what how exactly the memory for the `matmul` is allocated and managed throughout a function like this. This loop potentially creates a large memory spike since the whole batch is being processed in an overlapping way, if for any reason the memory for the temporary matrices accumulates. It's not as bad if the tensors immediately de-allocate themselves when they fall out of scope like a smart pointer, but still it might be inefficient to allocate a new tensor each iteration.

**Comment by lezcano** [comment]
Accessor is very general and quite expensive for what it does. You probably want to do something like:
```c++
TORCH_INTERNAL_ASSERT(split_adv.is_contiguous());
auto split_adv_ptr = split_adv.data_ptr<int64_t>();
// access split_adv_ptr[i]
```
If the tensors are not contiguous, call `contiguous()` first (or `expect_contiguous`), but I think in this case they should be contiguous.

Memory in ATen is realeased as soon as the pointer is not in use anymore. We also use a caching allocator, so chances are that the memory is simply reused as you would expect to do manually. At any rate, thinking about this right now is a bit of a premature optimisation. It will be best to first have a working implementation, then measure speed, memory usage, etc, and after that figure out whether we can do better, and potentially benchmark other solutions against the original one.
