### ISSUE TITLE
torch.onnx.export does not support divisor_override in AvgPool2d

### ISSUE THREAD

**Issue by quic-ykota** [pytorch/pytorch#105349]
```
import torch
 
# export works fine if divisor_override=None, but fails when divisor_override is integer value
model = torch.nn.AvgPool2d(kernel_size=5, stride=2, padding=1, divisor_override=3)
model.eval()
 
rand_inp = torch.randn(1, 3, 8, 8)
 
torch.onnx.export(model, rand_inp, "AvgPool2dModel.onnx", verbose=True)
```

Above code fails during export with the error “torch/onnx/symbolic_helper.py:243: UserWarning: ONNX export failed on avg_pool2d because divisor_override not supported”
Please add support for export of AvgPool2d with an integer divisor_override value.

### Versions

Torch version: 1.9.1

**Comment by mikaylagawarecki** [comment]
Hi, I see you are using torch version 1.9.1, could you try with the latest pytorch version 2.0.1 please?

**Comment by quic-ykota** [comment]
Hello @mikaylagawarecki I still see the error with torch version: 2.0.1. Below is the error message.

`torch.onnx.errors.OnnxExporterError: Unsupported: ONNX export of operator avg_pool2d, divisor_override. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues`

**Comment by keltonlee** [comment]
Hello @quic-ykota , I have the same problem now. Did you solve it?

**Comment by quic-ykota** [comment]
@keltonlee, Nope, I am waiting for the response from @mikaylagawarecki

**Comment by shubhambhokare1** [comment]
Hi @quic-ykota 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
