### ISSUE TITLE
Avoid calling AOTAutograd from AOTInductor, since Export has already done that

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#105555]
cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by angelayi** [comment]
Inductor has different set of decompositions which is why AOTAutograd is called again, but I think we can solve this by passing in the inductor decomposition table to export().

**Comment by angelayi** [comment]
Inductor has different set of decompositions which is why AOTAutograd is called again, but I think we can solve this by passing in the inductor decomposition table to export().

But is this desirable? Then inductor's compile_fx will be restricted to only take in the result of export. Unless we create a different function like "compile_from_export"?

cc @desertfire

**Comment by desertfire** [comment]
We already have `compile_fx_aot`, we can make its behavior diverge from `compile_fx`.

**Comment by eellison** [comment]
One issue is that freezing is going to change potentially change the set of parameters and buffers, with things like channels last conversion. I'm not sure if the current path of calling export, gathering buffers/params, and then calling inductor makes sense.

Could we call inductor first, and then generate the graph signature etc from it ?

We might need to do some refactoring.

**Comment by desertfire** [comment]
> Could we call inductor first, and then generate the graph signature etc from it ?

We can change _inductor.aot_compile to take an ExportedProgram and example inputs, and after running AOTInductor (with freezing), return an updated ExportedProgram with the right graph signature. In the new graph signature, only user inputs will be args and weights are folded.
