### ISSUE TITLE
Dynamic int not being propagated when used on `__setitem__`

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#105533]
### 🐛 Describe the bug

The following program:
```python
import torch

@torch.compile()
def wh(n, a):
    a[n] = -1
    return a

z = torch.zeros(7)
for n in range(2, z.shape[0]):
    print(wh(n, z))
```
compiles 5 different functions. Same same for `compile(dynamic=True)`. Dynamo installs a guard `L['n'] == 2` in the first iteration (expected) but then when `n == 3` it also installs a guard as `L['n'] == 3`.

Note that this does not happen if we change the line `a[n] = -1` by `a += n`.

We hit this bug when testing the NumPy compat layer on real NumPy programs.

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

**Comment by ysiraichi** [comment]
As far as I understand, this error is caused because of [this `PyNumber_index` call](https://github.com/pytorch/pytorch/blob/d2ee3d0675d89d39f7703aabf51a401641c38d02/torch/csrc/autograd/python_variable_indexing.cpp#L234). So, here's what I'm thinking I should do:

- Modify `THPVariable_setitem` function for handling `SymInt` (almost the same way as ints)
- Modify `TensorIndex` so that it accepts `SymInt` instead of integers
- (Following PR) Do the same for when the index is a tuple

@lezcano @ezyang
Let me know what you think.

**Comment by ezyang** [comment]
Seems like it should work.
