### ISSUE TITLE
UNSTABLE periodic / linux-focal-rocm5.6-py3.8 / test (distributed)

### ISSUE THREAD

**Issue by PaliC** [pytorch/pytorch#105761]
> Please provide a brief reason on why you need to mark this job as unstable.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by pruthvistony** [comment]
@PaliC ,
checking - https://hud.pytorch.org/pytorch/pytorch/commit/0af18f223490df7662c32c48128b2b475091c4ff
failing test is
`FAILED [0.0152s] distributed/_tensor/test_dtensor.py::TestDynamoDTensor::test_dynamo_dtensor - AssertionError:`

It is failing on below CUDA jobs also
- linux-bionic-cuda11.8-py3.10-gcc9 / test (distributed, 3, 3, linux.8xlarge.nvidia.gpu, unstable)
- linux-focal-py3.8-gcc7 / test (distributed, 1, 2, linux.2xlarge, unstable)

is it ok to disable the UT instead of moving all jobs to unstable, so that a review on the UT can be done.

**Comment by huydhn** [comment]
Closing as I don't see the job failing in trunk anymore
