### ISSUE TITLE
[dynamo.export] symbolic_shapes.GuardOnDataDependentSymNode

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#106183]
This was observed when exporting `BertForMaskedLM`. It turned out the model code is doing a input value check to produce a warning. Hence an intuitive workaround appears to be applying `@torch._dynamo.assume_constant_result` on the checker function. That indeed worked around the issue and enables export.

I'm wondering if it is technically feasible to create an "unsafe" config that, when opt in, automatically applies `assume_constant_result` onto the call that triggers `GuardOnDataDependentSymNode`, to essentially consider it a constant and prevent the graph break?

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 

Repro script
```python
import torch
import transformers

model = transformers.AutoModelForMaskedLM.from_pretrained("bert-base-uncased")
gm, _ = torch._dynamo.export(model, aten_graph=True, return_dict=False, input_ids=torch.tensor([[1, 2, 3]]))

gm.print_readable()

# Or below after the api change
# torch._dynamo.export(model)(return_dict=False, input_ids=torch.tensor([[1, 2, 3]]))
```
```
GuardOnDataDependentSymNode: It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and
thus we do not know the true value.)  The expression we were trying to evaluate is Eq(i0, 1) (unhinted: Eq(i0, 1)).  Scroll up to see 
where each of these data-dependent accesses originally occurred.

from user code:
   File "transformers/models/bert/modeling_bert.py", line 970, in 
forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "transformers/modeling_utils.py", line 3491, in 
warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

**Comment by ezyang** [comment]
@bdhirsh and I were actually discussing this for unrelated reasons. There are a few things going on here:

1. If the conditional happens inside Dynamo'ed Python bytecode, I agree it should be possible to do this automatically. However, don't really like `assume_constant_result` for this purpose. The problem is that you need to be absolutely certain that the function doesn't have any important pieces to trace. In your example, it's pretty easy to see, but imagine if the warning function was inlined, there's no logical place to put the `assume_constant_result`. Instead, what we have to do is when we do a conditional that hits a GuardOnDataDependentSymNode error, we should speculate both sides of the conditional, and if one of them hits an error, we can assume that we must go down the non-error path (and trace a runtime assert). If some model changes are permitted, we can use a special assert-style construct to indicate this cc @tugsbayasgalan 
2. If the conditional happens inside PyTorch core code, esp in C++, we can't play the automatic speculate trick from (1) easily (technically, it possible to do using the same idea as in https://gist.github.com/ezyang/192c1b5eb57ff95a46d3b50aa46e3193, but you have to repeatedly rerun the *entire* trace top-to-bottom to get to change your mind midway through since we don't have first class continuations / amb). But the special assert construct which says "if this is unhinted, just assume it's always true/false" works just as well in this case. We should add it.

I'm probably going to do this soon, as it's blocking some export cases I'm working on lol.

**Comment by ezyang** [comment]
cc @Chillee for fun

**Comment by BowenBao** [comment]
@ezyang Thank you for responses. Regarding the automatic solution I was visioning its application in a much smaller scope. From an overly simplified point of view to amend unhinted symbol with the hint value. For generality we wouldn't want the call to be made a constant in the graph completely by `assume_constant_result`, we just need similar mechanism to produce a hint value, and I'd assume this would be guarded and we can emit warnings or asserts. However, I'm not familiar with when/how/where dynamo handles the concrete run and what it requires so this idea may not be feasible from the start lol.

On the other hand for conditional speculation, I wonder if it would become a problem that the search space grows exponentially with the number of expressions, and that the erroring may only occur at a much later stage, or may not occur at all for either branch...

**Comment by ezyang** [comment]
But you... can't really soundly give unbacked ints a hint. You have no way to guard on it! The guard implies that you have to invalidate the graph, but you can't check the guard on entry because you don't have the data.

If you have some sort of bailout strategy this is more likely to work, but you need to reset the analysis with a different hint when the hint gets violated.

> On the other hand for conditional speculation, I wonder if it would become a problem that the search space grows exponentially with the number of expressions, and that the erroring may only occur at a much later stage, or may not occur at all for either branch...

Yes, this is why the special assert construct (which knows one branch is impossible) is a good idea.

**Comment by ezyang** [comment]
I want to note that we have `expect_true` now and are able to infer runtime asserts when the opposite path would error. IT doesn't help for this particular case though because it's a warning invocation.

**Comment by mlazos** [comment]
@BowenBao is this still an issue? I ran your repro and don't see the error you posted above anymore.

**Comment by BowenBao** [comment]
Closing, this seems to be resolved in upstream transformers with code changes

```
    def warn_if_padding_and_no_attention_mask(self, input_ids, attention_mask):
        """
        Shows a one-time warning if the input_ids appear to contain padding and no attention mask was given.
        """

        # Skip the check during tracing.
        if is_torch_fx_proxy(input_ids) or torch.jit.is_tracing() or is_torchdynamo_compiling():
            return
```
