### ISSUE TITLE
Use Shape Env Bounds in Inductor Bounds.by

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#106175]
### 🚀 The feature, motivation and pitch

Currently in inductor bounds analysis we pessimistically assume the bounds of SymInts are [2, inf - 1]. However, sometimes we have additional constraints which we can use in analysis. 

Changing `test_optimize_indexing_dtype` to:

```
        def test_optimize_indexing_dtype(self):
            from torch._export.constraints import constrain_as_size

            def fn(x: torch.Tensor) -> torch.Tensor:
                constrain_as_size(x.shape[0], 2, 8)
                return aten.upsample_bilinear2d.vec(x, None, True, [2.0, 2.0])

            fn_opt = torch._dynamo.optimize("inductor")(fn)
            inps = [torch.randn(2, 4, 16, 16, device="cuda")]

            torch._dynamo.mark_dynamic(inps[0], 0)

            code = run_and_get_triton_code(fn_opt, *inps)
```

shows an example of using `constrain_as_size` to get a tighter bound on the sym int. We should use this tighter bounds in inductor bound analysis. These bounds can be found in `torch._guards.TracingContext.get().fake_mode.shape_env.var_ranges` and should be plugged in to bounds.py. This should allow the int64->int32 optimization to fire as it is currently in `test_optimize_indexing_dtype`. 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @lezcano

**Comment by lezcano** [comment]
@ysiraichi and I were going in fact going to have a meeting tomorrow to discuss optimisations of this sort. A more general optimisation would account for having a table of shared bounds for symbols between dynamo and inductor, so that both can record data on it as they find it. (e.g. inductor could record bounds on variables involved on indirect indexing, that dynamo does not have access to).
