### ISSUE TITLE
[ONNX] scatter_reduce does not support `include_self=False`

### ISSUE THREAD

**Issue by zhuyu2015** [pytorch/pytorch#106373]
### 🐛 Describe the bug

the latest verison pytorch[2023-08-01] has support aten::scatter_reduce operator, when export the model to ONNX. but occurs error:
raise errors.OnnxExporterError(
    "ONNX does not support include_self=False for scatter_reduce"
)
how to fix the error?

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230731+cu118
[pip3] torchaudio==2.1.0.dev20230731+cu118
[pip3] torchvision==0.16.0.dev20230731+cu118
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230731+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230731+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230731+cu118          pypi_0    pypi

**Comment by SkylerHuang** [comment]
meet the same problem

**Comment by sevenineone** [comment]
meet the same problem

**Comment by MaanavD** [comment]
Hi @zhuyu2015 @sevenineone @SkylerHuang ,

We’ve gone ahead and closed this issue because we think it can be resolved with our new `torch.onnx.dynamo_export` api. Please try that instead! Apologies for not getting to this issue earlier.

If that doesn't work, feel free to reopen the issue and we will address it.
