### ISSUE TITLE
torch._dynamo.export(aten_graph=True) with FakeTensor and module with parameters don't work

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#106517]
### 🐛 Describe the bug

cc @thiagocrepaldi 

### Versions

master

**Comment by thiagocrepaldi** [comment]
This might be a common use case for the ONNX exporter in a near future.

The ONNX exporter uses `FakeTensor` to be able to export models that are too large to fit in memory otherwise. We would use `torch._dynamo.export(aten_graph=True)` to perform model decomposition into Aten operators, which would be translated into ONNX ops. 

Today this is not an issue yet because we set `aten_graph=False`, but internally we perform the same impl that calls `make_fx(tracing_mode="real")` when fake tensor is used; otherwise, `tracing_mode` is either `symbolic` or `fake`.
