### ISSUE TITLE
`pca_lowrank` already supports batches if input data is a strided tensor. For example:

### ISSUE THREAD

**Issue by hormone03** [pytorch/pytorch#107164]
I am working on a machine-learning classification model. It works fine on greyscale data set. But the performance on RGB images is poor. So, I decided to apply torch.pca_lowrank on the RGB data set to see if this can improve the feature representations and the model’s performance.

Here is my code sample:

U, S, V = torch.pca_lowrank(torch.as_tensor(train_dataset) , q=None, center=True, niter=3)
train_dataset = torch.matmul(train_dataset, V[:, :n_components])
I am getting this error:

ValueError: only one element tensors can be converted to Python scalars
Any suggestions, please? 
Or how can I possibly use PCA on torch.Datasets in dataloader? 

Thanks.

_Originally posted by @pearu in https://github.com/pytorch/pytorch/issues/99705#issuecomment-1517584269_

**Comment by colesbury** [comment]
Hi @hormone03, we use github issues only for bug reports or feature requests. Please use the forum to ask questions:[ https://discuss.pytorch.org/](https://discuss.pytorch.org/).

You'll want to include additional information in the forum post so that people can answer your question. You should provide enough information so that someone can reproduce the error you are encountering.

For context, `ValueError: only one element tensors can be converted to Python scalars` indicates that you are passing a Tensor in a place where the framework expects a single number (a scalar value).
