### ISSUE TITLE
LayerNorm outputs off for eps=1e-6

### ISSUE THREAD

**Issue by ankitade** [pytorch/pytorch#108072]
### 🐛 Describe the bug

LayerNorm is giving somewhat off values in the following case

```
import torch
x = torch.Tensor([[[2.0, 2.0], [14.0, 14.0]], [[2.0, 2.0], [14.0, 14.0]]])
ln = torch.nn.LayerNorm(2, eps=1e-6)
for n,p in ln.named_parameters():
  torch.nn.init.ones_(p)
ln.eval()

y = ln(x)
print(y)
```
The expected values is tensor will all 1s but I see this 

tensor([[[1.0000, 1.0000],
         [1.0001, 1.0001]],
        [[1.0000, 1.0000],
         [1.0001, 1.0001]]], grad_fn=<NativeLayerNormBackward0>)

### Versions

Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.109+-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by ankitade** [comment]
@albanD @ebsmothers

**Comment by mikaylagawarecki** [comment]
This indeed seems to be a cpu-only problem.

Based on the equation for LayerNorm, my understanding is that the value of $\epsilon$ should not affect the output in this case. 

We have $$\frac{X - E[X]}{\sqrt{Var[X} + \epsilon} * \gamma + \beta$$

Suppose we set `elementwise_affine=False`, then we can ignore $\beta$ and $\gamma$

$$\frac{X - E[X]}{\sqrt{Var[X} + \epsilon} $$

Since `normalized_shape=2`, per the docs, $E[X]$ should be computed over the last dimension and should be given by 

```
>>> x.mean(-1)
tensor([[ 2., 14.],
        [ 2., 14.]])
```

So the numerator $X - E[X]$ should be $0$ and the value of the denominator (or $\epsilon$ should not affect the output)

However, observe that even setting `elementwise_affine=False` in the above snippet (on cpu), we still have 

```
import torch
x = torch.Tensor([[[2.0, 2.0], [14.0, 14.0]], [[2.0, 2.0], [14.0, 14.0]]])
ln = torch.nn.LayerNorm(2, eps=1e-6, elementwise_affine=False)
for n,p in ln.named_parameters():
  torch.nn.init.ones_(p)
ln.eval()

y = ln(x)
print(y)

tensor([[[0.0000, 0.0000],
         [0.0001, 0.0001]],

        [[0.0000, 0.0000],
         [0.0001, 0.0001]]])
```

I believe that the offending lines are 63 and 68 here

https://github.com/pytorch/pytorch/blob/182a9cf366525e40b2f35ceb4fa00b7f173210ef/aten/src/ATen/native/cpu/layer_norm_kernel.cpp#L57-L68

where we do `x * scale + bias * gamma_v + beta_v`

```
rstd_val = T(1) / std::sqrt(rstd_val + eps);
const T scale = rstd_val;
const T bias = -rstd_val * mean_val;
```

which expands out as
```x * rstd_val + (-rstd_val * mean_val)```

or 

 $\frac{X}{\sqrt{Var[X] + \epsilon}} - \frac{E[X]}{\sqrt{Var[X] + \epsilon}} $
 
 This is mathematically correct, but **scaling $X$ and $E[X]$ separately as we do in the CPU kernel introduces precision issues**. If I change this [as in this draft PR](https://github.com/pytorch/pytorch/pull/108089) to do `(x - mean_val) * rstd_val`, the error disappears and we get zeros as expected.

**Comment by mingfeima** [comment]
nice work !

**Comment by mikaylagawarecki** [comment]
Closing since https://github.com/pytorch/pytorch/pull/108089 fixed this
