### ISSUE TITLE
feature request: unify tensor constructor interface for both CPU and GPU

### ISSUE THREAD

**Issue by david-leon** [pytorch/pytorch#1081]
1) add para `device` to constructor of `torch.Tensor()` and etc.  For example, 
     `x_tensor = torch.Tensor(np.random.rand(3,5), device=0)`

2) add attr. `device` to `Tensor` and etc. so we can check a tensor resides on which device, for example
     `device = x_tensor.device`

**Comment by albanD** [comment]
Hi,

1. You can already create a tensor directly on GPU with the constructor for cuda tensor: `x_tensor = torch.cuda.FloatTensor(3, 5, device=0)`
2. The cuda tensors have a `device = x_tensor.get_device()` accessor to check where a tensor resides. And you can use the `x_tensor.is_cuda` boolean value to check wether a tensor is a cuda tensor or a cpu tensor.

Does this answer your needs?

**Comment by david-leon** [comment]
Thanks @albanD, this partly meets my need. It would be better if we have unified interface for both CPU tensor and GPU tensor rather than checking .is_cuda() first.

**Comment by david-leon** [comment]
I modified the issue title, because except for the above issues, I've also experiences the following inconvenience:

Though I love pytorch, I've to say that the design of current tensor constructors of pytorch is UGLY.
There're so many different constructors (Tensor, FloatTensor, ByteTensor ... on CPU, and cuda.FloatTensor, cuda.xxx on GPU), and making the situation worse these constructors are behaving differently. To name a few, we can create a FloatTensor by:

` x_t = torch.FloatTensor(np.random.rand(3,5))`  or
` x_t = torch.from_numpy(np.random.rand(3,5).astype(np.float32))`

whereas when it comes to GPU, the same syntax won't work. Even both on CPU, the FloatTensor constructor behaves different with BytenTensor.

I'd suggest to unify all these constructors and their behaviors, making them more consistent with numpy interface. For example, to create a Tensor, I'd want:
` x_t = torch.Tensor(np.random.randint(0,5, (3,5), np.uint8), torch.Byte, device=1`
 to create a BytenTensor on GPU1 initialized with numpy array.

**Comment by apaszke** [comment]
I don't understand how that makes it more consistent and less ugly. All tensor constructors are necessary, because tensors containing the data of different types are different classes by design too, and taking the path you suggest seems to add a lot of redundancy and limits extensibility.

First thing, there are many ways to construct a tensor and these lines are not equivalent:
```python
x_t = torch.FloatTensor(np.random.rand(3,5))
x_t = torch.from_numpy(np.random.rand(3,5).astype(np.float32))
```

The first one guarantees to give you a FloatTensor, no matter what you give it, and if it happens to be a float ndarray, then it will construct it without performing any memory copy.
The second one guarantees to give you a CPU tensor, that matches the type of a given array, and that shares the same memory.
You can't use this syntax with GPU, because there is no GPU numpy array, and it wouldn't have the same semantics (it wouldn't share the data in memory). I have no idea how CPU FloatTensor constructors behave differently than CPU ByteTensor constructors, please be more specific.

This line is equivalent to the one you proposed. There's no need for putting everything in the constructor.
```python
# note that the .type(...) part is unnecessary
x_t = torch.from_numpy(np.random.randing(0, 5, (3, 5), np.uint8)).type(torch.ByteTensor).cuda(1)
```

**Comment by soumith** [comment]
@colesbury and I think the same as @apaszke
