### ISSUE TITLE
[Outdated documentation] Previous Versions Installation with Conda

### ISSUE THREAD

**Issue by fKunstner** [pytorch/pytorch#10855]
The [previous versions](https://pytorch.org/previous-versions/) page indicates that installing previous versions of PyTorch can be done using

```
conda install pytorch=0.1.12 -c soumith
```

However, the packages do not seem to be on the correct channel for **Windows** distributions; only `0.4.1` works on `-c soumith`. 

The `-c pytorch` channel distributes both `0.4.1` and `0.4.0`.

Not sure if the issue is in the documentation or on conda.

I am unable to test on a Linux system at the moment.

---

I tried the following versions/channels on conda `4.5.10`.

| Version | Channel | Results |
|-|-|-|
| `0.4.1`| `-c soumith` | Works|
| `0.4.0`| `-c soumith` | `PackagesNotFoundError`|
| `0.4.1`| `-c pytorch` | Works|
| `0.4.0`| `-c pytorch` | Works|

Full error message:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch=0.X.Y

Current channels:

<<<<<<< if -c pytorch
  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch
=======
  - https://conda.anaconda.org/soumith/win-64
  - https://conda.anaconda.org/soumith/noarch
>>>>>>> if -c soumith
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by soumith** [comment]
pointing `previous versions` to use `soumith` channel was a mistake. We switch from `soumith` to `pytorch` channel (i think in 0.3.1), but forgot to update the page. I just fixed the link via https://github.com/pytorch/pytorch.github.io/commit/398a3b8f6eb53ac3928cc544018e46744afcf5fa

PyTorch Windows support officially released from v0.4.0, and hence we only have 0.4.0 available from the `pytorch` channel since then. For unofficial / previous releases, see `peterjc123`'s channel: https://anaconda.org/peterjc123

Closed via https://github.com/pytorch/pytorch.github.io/commit/398a3b8f6eb53ac3928cc544018e46744afcf5fa
