### ISSUE TITLE
[dynamo][symbolic shapes] Long compilation time for KJT helper function

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#109484]
### 🐛 Describe the bug

Code - https://gist.github.com/anijain2305/94f59df4e5267fefa046b8cb718be2cd

Input has a list of integers, which changes from run to run, and this list goes to torch.split, triggering a large number of symbolic shape guards. I think Dynamo should skip compiling this type of function. Looking for ideas on how to proceed on this.

@voznesenskym @ezyang 

### Versions

NA

cc @ezyang @msaroufim @wconstab @bdhirsh

**Comment by ezyang** [comment]
what i texted animesh

first, there's a graph break, resulting in us trying to compile itty-bitty functions. This can make things worse, because there might be a lot more intermediates floating around than if you had managed the whole thing

are you sure it never gets past 0/0? because on the first run you shouldn't even have any dynamic shapes. i mean, if I had to guess, they set dynamic=True, but dynamic=True is rarely a good idea

**Comment by zhxchen17** [comment]
Hi @anijain2305 I'm cleaning up the old issues and wondering if you are able make progress on this? Thanks!

**Comment by anijain2305** [comment]
This issue is stale. Ivan and Ed have been making great progress in this area since last year. So there would be new issues coming up. Closing.
