### ISSUE TITLE
[dynamo] torch._dynamo.exc.Unsupported: comparison SymNodeVariable() <built-in function is_> ListVariable()

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#109504]
### 🐛 Describe the bug

Self explanatory.

Occurred when implementing self-referentiality check in torch.tensor ref

```
            if cur_item is obj:
                raise TypeError("new(): self-referential lists are incompatible")
```

### Versions

main

cc @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @bdhirsh @Xia-Weiwen @aakhundov

**Comment by aqbewtra** [comment]
This is my first issue. Do you mind providing more detail on how I can recreate the bug?

**Comment by ezyang** [comment]
```
import torch

@torch.compile(backend='eager', fullgraph=True, dynamic=True)
def f(x, xs):
    if x.size(0) is xs:
        return x + 1
    else:
        return x * 2

f(torch.randn(2), [1, 2])
```

**Comment by vdesai2014** [comment]
@ezyang 

Currently when the 'is' operator is used with a SymNodeVariable, an unimplemented exception is throw because 'is' isn't currently part of supported_tensor_comparison_ops (line 1442, dynamo/variables/built_in.py). There is an existing if statement to handle 'is' operator called on different types (lines 1458-1461) but the fact that its lower down in the function causes the unimplemented exception to get thrown first. 

I think moving the catch for 'is' op on different types to the top of the function should fix this issue without any second-order effects. Can you confirm this makes sense? My first Pytorch issue so want to make sure.

**Comment by ezyang** [comment]
Give it a try

**Comment by jon-chuang** [comment]
How about this test case?

```
import torch

@torch.compile(backend='eager', fullgraph=True, dynamic=True)
def f(x, xs):
    if x.size(0) is xs:
        return x + 1
    else:
        return x * 2

f(torch.randn(2), 2)
```

We also want to handle the case where it is indeed self-referential etc. For that we need something closer to https://github.com/pytorch/pytorch/issues/111550

**Comment by laithsakka** [comment]
@vdesai2014  @jon-chuang  is this still an open issue? is anyone working on this?

**Comment by ezyang** [comment]
Feel free to grab this

**Comment by ezyang** [comment]
still repros as of 0a1b3be2163ea99633f95c4927bd816eb713e9bd

**Comment by joshue031** [comment]
If this is still free to work on, I would propose adding the following logic to `_comparison_with_symnode`  in [torch/_dynamo/variables/builtin.py](https://github.com/pytorch/pytorch/blob/afa78ad08cc748c25e7e82cec02cec4c97c7d3af/torch/_dynamo/variables/builtin.py#L1847):
```python
if op in [operator.is_, operator.is_not]:
    is_result = (
        isinstance(left, SymNodeVariable)
        and isinstance(right, SymNodeVariable)
        and left.sym_num is right.sym_num
    )
    if op is operator.is_:
        return ConstantVariable.create(is_result)
    else:
        return ConstantVariable.create(not is_result)
```
This is similar to what is done in `_comparison_with_tensor` and seems to work for the two example test cases above.
