### ISSUE TITLE
sam: AssertionError at torch/_inductor/graph.py `assert isinstance(value, (TensorBox, sympy.Expr))`

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#110089]
Repro:
```
python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda  --inductor  --only sam
```

Error:
```
  File "/home/binbao/pytorch/torch/_inductor/graph.py", line 464, in run
    return super().run(*args)
  File "/home/binbao/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/home/binbao/pytorch/torch/_inductor/graph.py", line 735, in run_node
    result = super().run_node(n)
  File "/home/binbao/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/binbao/pytorch/torch/_inductor/graph.py", line 674, in output
    assert isinstance(value, (TensorBox, sympy.Expr))
AssertionError
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @Xia-Weiwen

**Comment by ezyang** [comment]
can you add `type(value)` to the assert message and give the updated assert output

**Comment by desertfire** [comment]
It's because of a boolean input here, https://github.com/pytorch/benchmark/blob/160bcfe8a5904610674bb271043fe8589f024a3b/torchbenchmark/models/sam/sam.py#L57C32-L57C32 . I thought in export boolean is specialized?

**Comment by angelayi** [comment]
Export does specialize the bool/int constants but we still add the inputs to the graph, with the number of users being 0: https://www.internalfb.com/intern/everpaste/?handle=GE7cyhZO565arfgCAD9pzzOPaBl9bsIXAAAz

If we look at self.graph_inputs, the inputs are: {'arg581_1': TensorBox(..), 'arg582_1': 256, 'arg583_1': 256, 'arg584_1': False} and the assertion is failing on arg584_1 but not arg582_1 or arg583_1. This is because the 256 value is actually a sympy.core.numbers.Integer, making it pass the isinstance(value, sympy.Expr) check. 

One solution is to change the boolean input to be some sympy.Expr type. I’m not sure if this is possible though — I see there’s sympy.true which is type sympy.logic.boolalg.BooleanTrue, but it’s not an sympy.Expr.

Another solution is to add bools to that assertion statement, but it seems to fail downstream.

torch.compile doesn't run into this issue because the graph passed to inductor does not contain these constant inputs.

**Comment by ezyang** [comment]
cc @ydwu4

**Comment by ydwu4** [comment]
From what I know, it still requires some effort to support SymBool Inputs in inductor.

A short term fix can be: check the placeholders and specialize the symbool to its hint in export. Since the number of users is 0 according to Angela's observation and export will specialize the python bool, this looks safe and sound to me.

I can work on the SymBool support for inductor if it's required.

**Comment by desertfire** [comment]
>  it still requires some effort to support SymBool Inputs in inductor.

This is not about supporting SymBool in Inductor? After specialization, I think Inductor should not see this boolean value as an input, unless you are talking about assertions  added by Export to check that value?

**Comment by ydwu4** [comment]
yeah, you're right. It's not related to the discussion in this thread. Export should specialize the symbool before passing into aot inductor. 

What I described as short-term is more from torch.compile(symbool) point of view because right now we fakify the symbool with symint in dynamo. The long-term plan is more about faithfully represent symbool but it's a different discussion.

**Comment by ezyang** [comment]
cc @tugsbayasgalan

**Comment by ezyang** [comment]
@angelayi why do you add it to the graph? That seems wrong to me: if you don't actually use it (specialize) we should just not add it to the graph.

**Comment by zhxchen17** [comment]
Hi @angelayi I'm cleaning up the old issues and wondering whether there's progress on this issue since then? Thanks for looking into this!

**Comment by angelayi** [comment]
should be fixed with https://github.com/pytorch/pytorch/pull/131594
