### ISSUE TITLE
[inductor]: Not handling `ConcatKernel/NopKernel` fusions leads to suboptimal fusions

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#110342]
### 🚀 The feature, motivation and pitch

Instead, perhaps try to refactor it as `ComputedBuffer`

Examples: Adamax

Already bad with `config.aggressive_fusion = True`:
![image](https://github.com/pytorch/pytorch/assets/9093549/b9679690-e984-48ae-83e6-ea77db55243f)

Worse when `config.aggressive_fusion = False`:
![image](https://github.com/pytorch/pytorch/assets/9093549/96d30ee2-0dcc-4b56-942b-fc70513dd3d9)

With `config.aggressive_fusion = False`, these kernels are treated as not sharing reads/writes. 

Further, the presence of these `ConcatKernel` nodes seems to obstruct fusion of other kernels, despite later being partly pruned away during kernel codegen. 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

**Comment by jon-chuang** [comment]
@mlazos is this related to https://github.com/pytorch/pytorch/issues/107005?

**Comment by mlazos** [comment]
I think we should be able to remove the concat op for the case that is driving this (adamax right?)

**Comment by jon-chuang** [comment]
Yes, but that's just a hot fix for a single case, it seems that concat would cause issues for users' models in general.

> but in order for this codegen to be used elsewhere in the stack (think input concatenation, more generalized horizontal fusion) dynamic shapes support is necessary.

It was mentioned in https://github.com/pytorch/pytorch/issues/107005 that input concatenation could be solved by dynamic shapes.

I guess they are actually orthogonal? 

I don't see how dynamic shapes would be able to solve this. I guess we would get rid of concatkernel entirely, and handle the concat op as a dynamic shape that is dynamic over the concat dim?

**Comment by mlazos** [comment]
Concat in general is handled well by inductor; in the usual case it modifies the upstream ops to write to the new concatenated buffer automatically and fusions occur normally after. In the case of inputs to the model (what inputs mean in this context) we can't do this rewriting since we don't have access to the original allocating ops. Inductor generates a sequence of copy kernels - this can be parallelized with for each. We can incrementally enable this by allowing it for static shapes until we have dynamic shapes support. I sent a PR out for this a while ago but it broke some internal models so it needs some debugging. 

In our case, removing the concat is the best option.

**Comment by zhxchen17** [comment]
Hi @mlazos I'm cleaning up the old issues and wondering whether there's progress on this issue? Thanks for looking into this!

**Comment by mlazos** [comment]
We refactored Adamax so this no longer an issue https://github.com/pytorch/pytorch/pull/117835/files#diff-148b16d4bd6bab9a518cc1052160cb2dc47f014855087eca0fd3a2a65519e10e
