### ISSUE TITLE
`test_pytorch_onnx_onnxruntime_cuda.py` is not run in CI

### ISSUE THREAD

**Issue by peterbell10** [pytorch/pytorch#110450]
Currently this file fails at import time because of this import:

https://github.com/pytorch/pytorch/blob/4069d1de59bb5cd60c5364acd2835fbf9c6e601c/test/onnx/test_pytorch_onnx_onnxruntime_cuda.py#L17-L21

which imports the `*_OPSET_VERSION` constants from the wrong file
https://github.com/pytorch/pytorch/blob/4069d1de59bb5cd60c5364acd2835fbf9c6e601c/test/onnx/onnx_test_common.py#L436-L439

I am incidentally fixing the import issue in https://github.com/pytorch/pytorch/pull/110310#discussion_r1342669352 but the fact it fails at all means it must not be run in CI.

cc @ptrblck @mruberry @ZainRizvi

**Comment by shubhambhokare1** [comment]
Hi @peterbell10 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
