### ISSUE TITLE
Some easier test failure reader?

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#110650]
I read through test logs very often (probably because the test failure summary that the HUD shows me isn't enough?). My workflow is: (1) download the logs, (2) open the logs in a text editor, (3) watch as searching for "FAILED [" freezes the text editor.

The reason why I need to download the logs in the first place is that viewing them on GitHub is not good (they freeze chrome due to their size).

Could we have some built-in log reader in the HUD that lets us CTRL-F logs without having them freeze up?

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by clee2000** [comment]
If the job fails, you can expand the log classifier line to see the rest of the logs and its ctrl-f-able.

If the job doesn't fail, you can click the raw logs link, i havent had i freeze, but it takes a few seconds to load, and if you search for a string like "test" it will take forever since there are a ton of matches.

I recently merged a change to remove the logging of successful test files, they are still accessible in the artifacts, but this should reduce log size for non failures.  I suggest right clicking and using 'view page source' to wrap long lines of text in chrome when using the raw logs link.

Let me know how it goes.

**Comment by malfet** [comment]
@zou3519 there is a log reader in hud with Ctrl-F features, isn't there (implemented 2+ years ago by @driazati )
<img width="960" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/6511a476-6015-4dec-86a6-deeb56bda968">

**Comment by zou3519** [comment]
I didn't realize you could ctrl-F the log reader. It works really well (and doesn't freeze up). Thanks for pointing that out, @malfet.
