### ISSUE TITLE
cufft errors after lots of plan generation

### ISSUE THREAD

**Issue by isaacgerg** [pytorch/pytorch#11089]
Regarding https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/CuFFTPlanCache.h
section starting at 281.  Has this bug been confirmed by NVIDIA or at least filed formally?  

@mruberry @SsnL

**Comment by SsnL** [comment]
We have informed NVIDIA about this bug/behavior we observed. But I haven't asked them if they reproduced it.

**Comment by mruberry** [comment]
I've notified the appropriate person at NVIDIA. They made a need a few days to respond to this particular issue.

**Comment by syed-ahmed** [comment]
Thanks for following-up on this. I'm investigating on our end.

**Comment by syed-ahmed** [comment]
We reproduced and fixed the bug on our end and won't be needing `CUFFT_MAX_PLAN_NUM` in the future.

**Comment by syed-ahmed** [comment]
Unfortunately I don't have a timeline for you, but I have put this on my todo list to clean up the `CuFFTPlanCache.h` file when the time comes :)

**Comment by isaacgerg** [comment]
@syed-ahmed Hy Syed. Just a friendly ask if there is any progress in NVIDIA land in providing a fix for this.

**Comment by syed-ahmed** [comment]
As of CUDA 10 release last week, the bug has been fixed in cuFFT and I have updated the note here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/CuFFTPlanCache.h#L349. Also, I have added CUDA 10 guards to `CuFFTPlanCache.h` through this commit https://github.com/pytorch/pytorch/commit/ffbac7d0bb4e0772cab0054f79339478124ea9aa. Hence, if you compile PyTorch with CUDA 10, the cufft plan cache array should grow as intended without failing at the 1024th plan. I have tested this commit by building pytorch with CUDA 10 and running the test suite successfully.

Please let me know if there are any other queries regarding this issue. Otherwise, I think we are good to close this issue.

**Comment by isaacgerg** [comment]
Thank you. I am okay if you close.
