### ISSUE TITLE
[Dynamo] Support more argument types for autograd Function speculate: HigherOrderOperator with body that accepts non-Tensors as input

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#111019]
### 🐛 Describe the bug

If I pass a user defined object, or a list, etc to an autograd.Function, speculate subgraph should work as long as I can flatten all accessed elements into the supported types.

### Versions

main

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @zou3519 @ydwu4 @aakhundov @Xia-Weiwen

**Comment by zou3519** [comment]
I think Yanbo fixed this

**Comment by parthmannan** [comment]
@zou3519 Can you point to the PR that fixed this?
We are seeing similar issue to #113612 with the error `the user-defined autograd.Function with body that accepts non-Tensors as input. Got: <class 'group_norm_cuda.Algo'>` and I think this could be related to this request here.

**Comment by zou3519** [comment]
@parthmannan https://github.com/pytorch/pytorch/pull/124360

Can you open a new issue if you can repro it on main or the nightlies? We don't look at closed issues very much

**Comment by parthmannan** [comment]
@zou3519 It's part of a large network and it may take some time to get a reproducible mini-script out. If I just find the PR you mentioned above that fixes this, I can pull in the fixes manually and try it?
I am also unable to pull in the full nightly due to dependencies. Would really appreciate if I can see the PR that closed this issue? Thank you!
