### ISSUE TITLE
torch.autocast() hangs on CPUs

### ISSUE THREAD

**Issue by YunfanZhang42** [pytorch/pytorch#111456]
### 🐛 Describe the bug

Hi PyTorch Team, 

First and foremost, thank you for your invaluable contributions to the ML community! I recently encountered a performance issue when using torch.autocast() on CPUs. In the FP32 mode, everything is fine. When turning on the AMP with BF16, the code seems to be stuck and never finishes. Here is a quick repo:
```python3
import time
import torch
from transformers import RobertaForSequenceClassification, RobertaTokenizer

SEQUENCE_LENGTH = 512


def generate_random_batch(tokenizer, batch_size, sequence_length=SEQUENCE_LENGTH):
    """Generate a batch of random sequences for testing."""
    return tokenizer(
        [" ".join(["I am a test string."] * sequence_length) for _ in range(batch_size)],
        padding="max_length",
        truncation=True,
        max_length=SEQUENCE_LENGTH,
        return_tensors="pt",
    )


def benchmark_throughput(model, tokenizer, mixed_precision=False, batch_size=32, num_iterations=3):
    """Test and print the throughput of the model."""
    input_data = generate_random_batch(tokenizer, batch_size).to(device)
    # Warm up
    for _ in range(3):
        with torch.no_grad():
            # PyTorch only supports bfloat16 mixed precision on CPUs.
            with torch.autocast(device_type="cpu", dtype=torch.bfloat16, enabled=mixed_precision):
                _ = model(**input_data)

    start_time = time.time()
    for _ in range(num_iterations):
        with torch.no_grad():
            with torch.autocast(device_type="cpu", dtype=torch.bfloat16, enabled=mixed_precision):
                _ = model(**input_data)
    end_time = time.time()

    elapsed_time = end_time - start_time
    sequences_per_second = (batch_size * num_iterations) / elapsed_time
    latency = 1000 / sequences_per_second * batch_size

    return sequences_per_second, latency


if __name__ == "__main__":
    device = torch.device("cpu")
    tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
    model = RobertaForSequenceClassification.from_pretrained("roberta-base").to(device).eval()

    model = torch.compile(model)

    throughput, latency = benchmark_throughput(model, tokenizer, mixed_precision=False)
    print(f"FP32 Throughput: {throughput:.2f} sequences/second, Latency: {latency:.2f} ms")

    throughput, latency = benchmark_throughput(model, tokenizer, mixed_precision=True)
    print(f"Mixed Precision Throughput: {throughput:.2f} sequences/second, Latency: {latency:.2f} ms")
```
On my Intel i7-13700K, FP 32 throughput is 4.98 sequences/second. Enabling AMP with autocast seems to hang the code, as 1 core spikes to 100% and the script would not finish after waiting for 30 minutes. Would appreciate a further look into this issue - thanks in advance!

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.2.0-34-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 535.113.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             24
On-line CPU(s) list:                0-23
Vendor ID:                          GenuineIntel
Model name:                         13th Gen Intel(R) Core(TM) i7-13700K
CPU family:                         6
Model:                              183
Thread(s) per core:                 2
Core(s) per socket:                 16
Socket(s):                          1
Stepping:                           1
CPU max MHz:                        5400.0000
CPU min MHz:                        800.0000
BogoMIPS:                           6835.20
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          640 KiB (16 instances)
L1i cache:                          768 KiB (16 instances)
L2 cache:                           24 MiB (10 instances)
L3 cache:                           30 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-23
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.1
[pip3] pytorch-lightning==2.1.0
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchmetrics==1.2.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] Could not collect

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel

**Comment by leslie-fang-intel** [comment]
Hi @YunfanZhang42, Thanks for reporting this issue. 

- I made some slight change of your script to enable BF16 with Inductor
  - Refer to here for details https://gist.github.com/leslie-fang-intel/b28ef9fbb0afeb7159e3356d81fc5493
    - For BF16, You need also run  `torch.compile` under autocast context
    - Running your test with `TORCHINDUCTOR_FREEZING=1 ` Environment variable. For example: `TORCHINDUCTOR_FREEZING=1  python test.py`
  - Here is initial performance data I got with this script:
    ```
    FP32 Throughput: 39.12 sequences/second, Latency: 817.90 ms
    Mixed Precision Throughput: 65.03 sequences/second, Latency: 492.06 ms
    ```

- Since your CPU `13th Gen Intel(R) Core(TM) i7-13700K` doesn't have Hardware AMX BF16 instruction acceleration. You may not got the speedup as I send out. The AMX BF16 instruction exists on Intel SPR servers.

**Comment by leslie-fang-intel** [comment]
_One thing I noticed is that FP32 execution would use all available cores and the BF16 would only use one core_
@YunfanZhang42, it also looks strange to me. I think we need to take a look of this model on system without AMX BF16 instructions. cc @Le-Zheng

**Comment by Le-Zheng** [comment]
> Hi @leslie-fang-intel, thank you a lot for following up with this issue. After running the script you provided with `TORCHINDUCTOR_FREEZING=1` set, the issue persists. However, I have realized that it is not the code hangs, it's actually because the BF16 mixed precision is extremely slow on the i7-13700K so that it never finishes. I changed the batch size to 1 and the code is able to finish within reasonable time, and I got:
> 
> ```
> FP32 Throughput: 3.61 sequences/second, Latency: 277.29 ms
> Mixed Precision Throughput: 0.05 sequences/second, Latency: 19003.20 ms
> ```
> 
> One thing I noticed is that FP32 execution would use all available cores and the BF16 would only use one core, which explains some, but not all, differences. I guess the other part of the difference is the lack of AMX BF16 instructions actually makes the BF16 slower than FP32.
> 
> In this case, should torch.autocast() disable BF16 execution on CPUs that do not support AMX BF16 instructions? Or, at least, should there be some documentation about this behavior?

@YunfanZhang42 Could you please share additional information on the steps or configuration you took to perform this testing? I'm actively working on reproducing the reported issue.

**Comment by YunfanZhang42** [comment]
Hi @Le-Zheng , thank you for digging into this issue. I did not change anything from the original code except for setting the batch size to 1, which shortens the run time and allows the super slow BF16 mode to finish. Here is the [gist](https://gist.github.com/YunfanZhang42/028abd327835593e8221758b2857dc21) for your convenience. The info on my platform could be found in my original issue - I did not change anything except for doing a clean install of PyTorch 2.1 on Ubuntu 22.04. Running `python3 pytorch_bf16_cpu.py` with or without `TORCHINDUCTOR_FREEZING=1` would reproduce the issue. Let me know if you need anything.

**Comment by Le-Zheng** [comment]
> Hi @Le-Zheng , thank you for digging into this issue. I did not change anything from the original code except for setting the batch size to 1, which shortens the run time and allows the super slow BF16 mode to finish. Here is the [gist](https://gist.github.com/YunfanZhang42/028abd327835593e8221758b2857dc21) for your convenience. The info on my platform could be found in my original issue - I did not change anything except for doing a clean install of PyTorch 2.1 on Ubuntu 22.04. Running `python3 pytorch_bf16_cpu.py` with or without `TORCHINDUCTOR_FREEZING=1` would reproduce the issue. Let me know if you need anything.

@YunfanZhang42  Thank you so much for the detailed information! With running the same script on system without AMX BF16 instructions, I did not find the same issue and I got:
```
FP32 Throughput: 17.55 sequences/second, Latency: 56.97 ms
Mixed Precision Throughput: 6.34 sequences/second, Latency: 157.78 ms
```
I noticed there is a difference is that the pytorch version I utilized is ` torch 2.2.0a0+git3ca81ae`. Would you consider to try a most recent version?

**Comment by YunfanZhang42** [comment]
Hi @Le-Zheng, thank you for your follow up. 

I think I have figured out the root cause of the problem: PyTorch would not select the correct math library or even the matmul kernel when running BF16 on Intel CPUs. Please see the following script for a simple reproduction:
```python3
import torch
import time


def benchmark_tflops(matrix_size=1024, dtype=torch.float32, num_of_runs=10):
    # Create random matrices
    a = torch.randn(matrix_size, matrix_size, dtype=dtype, device="cpu")
    b = torch.randn(matrix_size, matrix_size, dtype=dtype, device="cpu")

    with torch.no_grad():
        for _ in range(num_of_runs):
            # Warm-up: Run matrix multiplication once to initialize CUDA kernels and memory
            torch.mm(a, b)
    # Start timer
    start_time = time.time()

    with torch.no_grad():
        # Perform matrix multiplication
        for _ in range(num_of_runs):
            c = torch.mm(a, b)
        # Wait for all GPU operations to complete

    # End timer
    time_taken = time.time() - start_time

    # Calculate TFlops
    tflops = num_of_runs * (2.0 * matrix_size**3) / (time_taken * 1e12)
    return tflops


if __name__ == "__main__":
    matrix_size = 1024
    num_of_runs = 10
    tflops = benchmark_tflops(matrix_size=matrix_size, dtype=torch.float32, num_of_runs=num_of_runs)
    print(f"Matrix multiplication for size {matrix_size}x{matrix_size}, FP32 achieved: {tflops:.4f} TFlops")

    tflops = benchmark_tflops(matrix_size=matrix_size, dtype=torch.float16, num_of_runs=num_of_runs)
    print(f"Matrix multiplication for size {matrix_size}x{matrix_size}, FP16 achieved: {tflops:.4f} TFlops")

    tflops = benchmark_tflops(matrix_size=matrix_size, dtype=torch.bfloat16, num_of_runs=num_of_runs)
    print(f"Matrix multiplication for size {matrix_size}x{matrix_size}, BF16 achieved: {tflops:.4f} TFlops")
```
And then I got:
```
Matrix multiplication for size 1024x1024, FP32 achieved: 0.4611 TFlops
Matrix multiplication for size 1024x1024, FP16 achieved: 0.0019 TFlops
Matrix multiplication for size 1024x1024, BF16 achieved: 0.0021 TFlops
```
This is the result on PyTorch nightly torch-2.2.0.dev20231021. As you can see, selecting FP16 or BF16 on CPUs would result in extremely poor performance in things as simple as GEMM. I also noticed that only 1 core is being used in FP/BF16 GEMM. Selecting FP16 would lead to crashes on PyTorch 2.1, while the BF16 throughput stays the same. I did not have any special setup for my environment - just an install of PyTorch inside a completely clean virtualenv on Ubuntu 22.04, using [official instructions](https://pytorch.org/get-started/locally/).

Honestly, this kind of bug is a bit surprising to me - Intel's PyTorch integration would not be able select the right GEMM kernel on a completely normal setup, and running FP16/BF16 would lead to extremely poor performance or even crashes. I would imagine this type of bugs would have been detected by Intel's QC.

**Comment by YunfanZhang42** [comment]
Also, searching the error message `"addmm_impl_cpu_" not implemented for 'Half'` I encountered on running FP16 on CPU on PyTorch 2.1, it seems a lot of people has encountered the same problem, such as (issue 1)[https://github.com/tloen/alpaca-lora/issues/308], (issue 2)[https://github.com/pytorch/pytorch/issues/96292], and (issue 3)[https://github.com/THUDM/ChatGLM2-6B/issues/211], so I believe what I am seeing here is not an isolated case.

**Comment by mingfeima** [comment]
@YunfanZhang42 (13th Gen Intel(R) Core(TM) i7-13700K) does not have [AMX](https://www.intel.com/content/www/us/en/products/docs/accelerator-engines/advanced-matrix-extensions/overview.html) which means that the gemm of bf16 would go to a very slow reference path without hardware acceleration.

As for half float support, the work is not done on torch yet. @CaoE do we have a timeline when gemm will be supported on half ?

**Comment by CaoE** [comment]
@YunfanZhang42 Half or fp16 support for gemm has been landed in stock PyTorch recnetly, that's why matrix multiplication works for half  in torch-2.2.0.dev20231021 and you got `"addmm_impl_cpu_" not implemented for 'Half'`  in PyTroch 2.1. For the poor performance of fp16/bf16, it is because the platform does not have AMX for hardware acceleration.

**Comment by luohao123** [comment]
A float16 or bf16 saved model, how to make it run on CPU?

**Comment by CaoE** [comment]
@luohao123 You can explicitly do `model.cpu()` first then the model will be runed on CPU.

**Comment by CaoE** [comment]
model.float32() will invoke different kernels for data type conversion.

**Comment by mingfeima** [comment]
@YunfanZhang42 @CaoE have we solved this issue ?

**Comment by CaoE** [comment]
@mingfeima I think this issue has been solved.

**Comment by mingfeima** [comment]
closing this one as the issues has been solved :)

**Comment by neurohazardous** [comment]
Hey Pytorch team, thank you so much for everything you do! 

I would like to follow up on this issue because I think I am getting the same issue as @YunfanZhang42. 

When I run: 
``` python
import torch
import time


def benchmark_tflops(matrix_size=1024, dtype=torch.float32, num_of_runs=10):
    # Create random matrices
    a = torch.randn(matrix_size, matrix_size, dtype=dtype, device="cpu")
    b = torch.randn(matrix_size, matrix_size, dtype=dtype, device="cpu")

    with torch.no_grad():
        for _ in range(num_of_runs):
            # Warm-up: Run matrix multiplication once to initialize kernels and memory
            torch.mm(a, b)

    start_time = time.time()
    with torch.no_grad():
        # Perform matrix multiplication
        for _ in range(num_of_runs):
            c = torch.mm(a, b)
    time_taken = time.time() - start_time

    # Calculate TFlops
    tflops = num_of_runs * (2.0 * matrix_size**3) / (time_taken * 1e12)
    return tflops


if __name__ == "__main__":
    matrix_size = 1024
    num_of_runs = 10
    tflops = benchmark_tflops(matrix_size=matrix_size, dtype=torch.float32, num_of_runs=num_of_runs)
    print(f"Matrix multiplication for size {matrix_size}x{matrix_size}, FP32 achieved: {tflops:.4f} TFlops")

    tflops = benchmark_tflops(matrix_size=matrix_size, dtype=torch.float16, num_of_runs=num_of_runs)
    print(f"Matrix multiplication for size {matrix_size}x{matrix_size}, FP16 achieved: {tflops:.4f} TFlops")

    tflops = benchmark_tflops(matrix_size=matrix_size, dtype=torch.bfloat16, num_of_runs=num_of_runs)
    print(f"Matrix multiplication for size {matrix_size}x{matrix_size}, BF16 achieved: {tflops:.4f} TFlops")
```

I can reproduce the results obtained in this thread: 
```
Matrix multiplication for size 1024x1024, FP32 achieved: 0.4889 TFlops
Matrix multiplication for size 1024x1024, FP16 achieved: 0.0012 TFlops
Matrix multiplication for size 1024x1024, BF16 achieved: 0.0013 TFlops
```

I'm guessing the issue is closed cause we cannot do bfloat operations on CPUs without the AMX BF16? If that's the case, is there any workaround? If not, I'll just disabel the AMP for CPU use cases in my own code.

To make communication easier I also collected my env: 


# Version
Collecting environment information...
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 14.1.1 20240522
Clang version: 17.0.6
CMake version: version 3.29.4
Libc version: glibc-2.39

Python version: 3.8.19 (default, Apr  9 2024, 15:43:30)  [GCC 13.2.1 20230801] (64-bit runtime)
Python platform: Linux-6.9.3-arch1-1-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A2000 8GB Laptop GPU
Nvidia driver version: 550.78
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.9.1.1
/usr/lib/libcudnn_adv.so.9.1.1
/usr/lib/libcudnn_cnn.so.9.1.1
/usr/lib/libcudnn_engines_precompiled.so.9.1.1
/usr/lib/libcudnn_engines_runtime_compiled.so.9.1.1
/usr/lib/libcudnn_graph.so.9.1.1
/usr/lib/libcudnn_heuristic.so.9.1.1
/usr/lib/libcudnn_ops.so.9.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        39 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               20
On-line CPU(s) list:                  0-19
Vendor ID:                            GenuineIntel
Model name:                           12th Gen Intel(R) Core(TM) i7-12700H
CPU family:                           6
Model:                                154
Thread(s) per core:                   2
Core(s) per socket:                   14
Socket(s):                            1
Stepping:                             3
CPU(s) scaling MHz:                   18%
CPU max MHz:                          4700.0000
CPU min MHz:                          400.0000
BogoMIPS:                             5378.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            544 KiB (14 instances)
L1i cache:                            704 KiB (14 instances)
L2 cache:                             11.5 MiB (8 instances)
L3 cache:                             24 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-19
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Mitigation; Clear Register File
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] efficientnet_pytorch==0.7.1
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] segmentation-models-pytorch==0.3.3
[pip3] torch==2.3.1
[pip3] torchvision==0.18.1
[pip3] triton==2.3.1
[conda] Could not collect

**Comment by CaoE** [comment]
@neurohazardous Same reason.  Your machine doesn't have AMX and avx512. GEMM of bf16/fp16 would run to a slow reference path without hardware acceleration. You can just disable the AMP for CPU use cases in your code.
