### ISSUE TITLE
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::binary_cross_entropy' to ONNX opset version 14 is not supported.

### ISSUE THREAD

**Issue by raghavendraprasadmahoorkar** [pytorch/pytorch#111666]
### 🚀 The feature, motivation and pitch

Unable to export ONNX model from https://github.com/xue-pai/FuxiCTR/tree/main/model_zoo/AFM. While exporting onnx it throws torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::binary_cross_entropy'

**Comment by justinchuby** [comment]
Please report library versions by running

```
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by thiagocrepaldi** [comment]
Please provide a runnable script for local repro

**Comment by shubhambhokare1** [comment]
Hi @raghavendraprasadmahoorkar 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
