### ISSUE TITLE
pytorch support for cuda 12.2 ?

### ISSUE THREAD

**Issue by Rasantis** [pytorch/pytorch#111786]
### 🚀 The feature, motivation and pitch

.

### Alternatives

.

### Additional context

.

cc @seemethere @malfet @osalpekar @atalman @ptrblck

**Comment by sascharo** [comment]
> Considering that 12.3 is already added I don't see much value in moving to 12.2 rather than jumping directly to latest one.
Will PyTorch for cu121 work flawlessly with CUDA 12.3 on the system, or is it advisable to go to 12.1? @malfet

**Comment by malfet** [comment]
> Will PyTorch for cu121 work flawlessly with CUDA 12.3 on the system, or is it advisable to go to 12.1?


Yes, it should: in CI we run all 11.8 tests on machines with CuDA 12.1

**Comment by johnnynunez** [comment]
> @Rasantis what is the question here? Also what do you want from 12.2 compared to 12.1? (Considering that 12.3 is already added I don't see much value in moving to 12.2 rather than jumping directly to latest one) @atalman do we have a public document/wiki outlining the plans to update supported CUDA version?

Because Cuda 12.2 had initial support HMM, but well, now the last version of Cuda is 12.3 update 1

**Comment by atalman** [comment]
@malfet I don't think we have it public anywhere. Normally we publish compatibility matrix ahead of the release here:
https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix

**Comment by johnnynunez** [comment]
> @malfet I don't think we have it public anywhere. Normally we publish compatibility matrix ahead of the release here: https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix

thanks!

**Comment by johnnynunez** [comment]
cuda 12.4 is out!
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

**Comment by ZainRizvi** [comment]
Unfortunately due to hardware constraints we can only test pytorch builds on so many different configurations, and we have to make the hard call on what to support and what to cut.  That includes being mindful about what CUDA versions we support

Today PyTorch CI supports CUDA 11.8, 12.1 and 12.4. You can expect CUDA 12.1 to remain for a while and CUDA 12.4 to be phased out in favor of newer CUDA 12.x versions over time.

If you'd like any intermediate version of CUDA 12, it's should work if you try building it yourself.
