### ISSUE TITLE
Incorrect parsing of values in scientific notation in tensor constructors

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#11184]
## Code example
```
>>> torch.tensor(1.001e10)  # incorrect
tensor(10010000384.)
>>> torch.tensor(1e10)  # correct
tensor(10000000000.)
```

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py build develop
- OS: Ubuntu 16.04.2
- PyTorch version: master
- Python version: 3.6.5

**Comment by vishwakftw** [comment]
Seems like it, because it works with NumPy's `float32`.
```
>>> np.float32(1.001e10)
10010000000.0
```

I discovered weirder behavior:
```
>>> torch.tensor(10000000000.)
tensor(10000000000.)
>>> torch.tensor(10000000001.)
tensor(10000000000.)
>>> torch.tensor(10000000010.)
tensor(10000000000.)
>>> torch.tensor(10000000003.) - 100
tensor(10000000000.)
```

**Comment by vishwakftw** [comment]
`float32`'s max value is in order of 10^{38} (if IEEE 754) is being followed.

**Comment by ngimel** [comment]
@fmassa is correct, those values are not representable in fp32. The issue is not with fp32 max value which is indeed 10^38, but with insufficient mantissa bits that cause some of the integers that are more than 2^24 not to be exactly representable, with gaps getting wider and wider for bigger numbers. So e.g. for 1.001e10 the closest representation is indeed 10010000384 (http://www.binaryconvert.com/result_float.html?decimal=049046048048049101049048)

**Comment by vishwakftw** [comment]
Thank you for the explanation @ngimel . Why is NumPy able to do though? And do you have any comment about the subtraction bug?

**Comment by ngimel** [comment]
9999999900 
Most accurate representation = 1.0E10
http://www.binaryconvert.com/result_float.html?decimal=057057057057057057057057048048

**Comment by vishwakftw** [comment]
I guess the issue is resolved. Thank you @ngimel for the comments.
