### ISSUE TITLE
[ONNX] Exporting the operator 'aten::sparse_coo_tensor' to ONNX opset version 17 is not supported

### ISSUE THREAD

**Issue by SangwookBaek** [pytorch/pytorch#112487]
### 🚀 The feature, motivation and pitch

In my model, there is layer like this,
`A = SparseTensor(row=row, col=col, sparse_sizes=(m, self.num_nodes)).to_torch_sparse_coo_tensor()`
`Ax = mlp(A)`
where mlp is nn.Linear layer
I'm trying to export above model to onnx. But I get an above issue "unsupported operator Error : aten ::sparse_coo_tensor".
 My environment is 
 torch =2.0.0
 cuda = 11.7
 python=3.10

### Alternatives

I'm trying to rewrite above code not usin sparse tensor.
But it takes a lot of memory. Or it takes a lot of time

### Additional context

Is there any another option easier than writing custom onnx?

**Comment by justinchuby** [comment]
I don't think the pytorch ONNX exporter supports sparse tensors right now. @BowenBao do you have suggestions?

**Comment by shubhambhokare1** [comment]
Hi @SangwookBaek 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team
