### ISSUE TITLE
test_scalar_fusion is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#11360]
Sample log: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py2.7.9-test/16930//console

```
02:04:52 ======================================================================
02:04:52 FAIL: test_scalar_fusion (__main__.TestScript)
02:04:52 ----------------------------------------------------------------------
02:04:52 Traceback (most recent call last):
02:04:52   File "test_jit.py", line 3048, in test_scalar_fusion
02:04:52     self.assertExpectedGraph(ge.graph_for(x, y))
02:04:52   File "test_jit.py", line 248, in assertExpectedGraph
02:04:52     self.assertExpected(str(graph), *args, **kwargs)
02:04:52   File "/var/lib/jenkins/workspace/test/common.py", line 524, in assertExpected
02:04:52     self.assertMultiLineEqual(expected, s)
02:04:52 AssertionError: 'graph(%x : Float()\n      %y : Float()) {\n  %2 : Float() = prim::FusionGroup_0 [truncated]... != 'graph(%x : Float()\n      %y : Float()) {\n  %2 : Float() = aten::type_as(%y, % [truncated]...
02:04:52   graph(%x : Float()
02:04:52         %y : Float()) {
02:04:52 -   %2 : Float() = prim::FusionGroup_0[device=-1](%x, %y)
02:04:52 -   return (%2);
02:04:52 - }
02:04:52 - with prim::FusionGroup_0 = graph(%0 : Float()
02:04:52 -       %1 : Float()) {
02:04:52 -   %2 : Float() = aten::type_as(%1, %0)
02:04:52 ?                                 ^   ^
02:04:52 +   %2 : Float() = aten::type_as(%y, %x)
02:04:52 ?                                 ^   ^
02:04:52     %3 : int = prim::Constant[value=1]()
02:04:52 -   %4 : Float() = aten::add(%0, %2, %3)
02:04:52 ?                             ^
02:04:52 +   %4 : Float() = aten::add(%x, %2, %3)
02:04:52 ?                             ^
02:04:52     return (%4);
02:04:52   }
02:04:52 
02:04:52 
```

**Comment by zou3519** [comment]
Looks like the problem is that the `system()` library function is flaky. Here's what happens:
- we use `system()` to check if we can compile with the fusion compiler on CPU
- If `system()` fails due to flakiness (maybe `fork` just didn't run?) the graph fuser does not fuse the graph, resulting in a graph without the FusionGroup.
- Now the expect test always expects there to be a FusionGroup so it errors out.

**Comment by zou3519** [comment]
Update with some numbers so I don't forget about them:

On an AWS image used by the CI, with a docker image that has 8g of memory:
- test_jit.py's python process achieves > 4g of rss usage. This is probably not because of a memory leak (valgrind didn't detect anything) but probably because the malloc allocator didn't feel like freeing its memory.
- the `system()` call, most notably used by the CPU Fuser (and probably the cuda fuser as well), does a `fork()` syscall
- The docker image supports copy-on-write. Despite this, fork() fails when the process uses more than half of available RAM before forking (I tested a few small c++ programs that allocate memory and attempt to fork). 
- Because test_jit.py uses more than 4g of ram, fork() fails and the CPU fuser just fails to run.

A few possible action items:
- The fusers should have better error checking and reporting when they fail to run because that information is available.
- test_jit.py should not be using so much peak memory, that needs to be investigated.
- Investigate fork() semantics: is this different on other machines?

**Comment by t-vi** [comment]
Just to narrow this down: My impression is that the test case with the high memory use is `TestEndToEndHybridFrontendModels`.

**Comment by zou3519** [comment]
It is. In particular, test_snli uses a peak 4g of memory, but it really shouldn't be using that much

**Comment by t-vi** [comment]
There also is [mallopt with M_TRIM_THRESHOLD](https://github.com/pytorch/pytorch/issues/11360#issuecomment-421460118) that seems to work more automatically. It'd be interesting to know what the glibc heuristic makes out of pytorch's allocation pattern.

**Comment by zou3519** [comment]
The interesting thing is that on python 2.7, the RSS memory usage of test_jit goes:
200mb ... 4 gb (at test_snli) ... stays ~4gb

While on python 3.7, the RSS memory usage goes:
200mb .. 4 gb (at test_snli) .. 1.3gb (after test_snli)

Not really sure why that happens but I guess it doesn't matter

**Comment by zou3519** [comment]
I think we fixed this. Feel free to reopen if this comes back.
