### ISSUE TITLE
[export] VGG model export.load() failure

### ISSUE THREAD

**Issue by peri044** [pytorch/pytorch#113999]
### 🐛 Describe the bug

With recent torch nightly, torch.export.load() on torchvision vgg 16 fails with the following error

```
torch._export.verifier.SpecViolationError: State dict entry for parameter features.0.weight is not an instance of torch.nn.Parameter.
```

To reproduce 
```
import torch
import torchvision.models as models 

model = models.vgg16(weights=None).eval().cuda()
random_inputs = [torch.rand([32, 3, 32, 32]).to("cuda")]
dim_x = torch.export.Dim("dim_x", min=1, max=32)
exp_program = torch.export.export(model, tuple(random_inputs), dynamic_shapes={"x" : {0 : dim_x}})
torch.export.save(exp_program, "./vgg_test.ep")
des_ep = torch.export.load("vgg_test.ep")
print(des_ep.module())
```

### Versions

Versions of relevant libraries:
[pip3] mypy==1.5.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] onnx==1.14.1
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20231116+cu121
[pip3] torch-tensorrt==2.2.0.dev0+7ad927248
[pip3] torchvision==0.17.0.dev20231116+cu121
[pip3] triton==2.1.0

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by tringwald** [comment]
Now, this is an interesting one. The problem seems to be that the original tensor is created on a CUDA device. During the `torch.export.save` call, the tensor is moved to CPU here:
https://github.com/pytorch/pytorch/blob/0ec66b3be5a53ab960872981b5027c49c2e6b7e9/torch/_export/serde/serialize.py#L218-L234

However, calling `.cpu()` on a CUDA `nn.Parameter` (or `.cuda()` on a CPU `nn.Parameter`) will unwrap it and return a plain tensor.

```python3
>>> t = torch.nn.Parameter(torch.ones(10))
>>> type(t), type(t.cpu()), type(t.cuda())
(<class 'torch.nn.parameter.Parameter'>, <class 'torch.nn.parameter.Parameter'>, <class 'torch.Tensor'>)
>>> t = torch.nn.Parameter(torch.ones(10).cuda())
>>> type(t), type(t.cuda()), type(t.cpu())
(<class 'torch.nn.parameter.Parameter'>, <class 'torch.nn.parameter.Parameter'>, <class 'torch.Tensor'>)
```

I have put up a PR to fix the problem mentioned in this issue, but maybe we should fix this at the source instead.

**Comment by peri044** [comment]
Thank you @tringwald  for the details and the fix !!
