### ISSUE TITLE
Mutating graph inputs on torch.export fails

### ISSUE THREAD

**Issue by oulgen** [pytorch/pytorch#114142]
### 🐛 Describe the bug

```
import torch
from torch.export import export

def foo(x):
    x.mul_(2)
    return x

t = torch.tensor([1])
export(foo, args=(t,))
```
The above program fails with
```
Found following user inputs located at [0] are mutated. This is currently banned in the aot_export workflow.
```
I have ran into this while adding support for user defined triton kernels in PT2.

### Versions

origin/main

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by ydwu4** [comment]
Can you provide some context for request? Do we have other alternatives?

**Comment by oulgen** [comment]
For MRS kernels, we are using user defined triton kernel in PT2.
So if you write code like
```
def foo(x, y):
  output = torch.zeros_like(x)
  add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=16)
  return output
```
torch.export fails because triton kernels could mutate all input tensors. Since x is a graph input this does not work.
A fully fledge example on https://github.com/pytorch/pytorch/blob/934e9c3346150feb9e38b9c8a82ec52d240d90c8/test/inductor/test_aot_inductor.py#L1112-L1115
Notice there are x = x.clone() in order to get this case working.

I can point to real production use cases internally.

**Comment by ydwu4** [comment]
Error message:
```python
Traceback (most recent call last):
  File "/home/yidi/local/pytorch/repro5.py", line 9, in <module>
    export(foo, args=(t,))
  File "/home/yidi/local/pytorch/torch/export/__init__.py", line 449, in export
    return export__RC__(
  File "/home/yidi/local/pytorch/torch/_export/__init__.py", line 258, in export__RC__
    return _export(
  File "/home/yidi/local/pytorch/torch/_export/__init__.py", line 565, in wrapper
    return fn(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_export/__init__.py", line 711, in _export
    gm, graph_signature = aot_export_module(
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 5095, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 5277, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
  File "/home/yidi/local/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yidi/local/pytorch/torch/_functorch/aot_autograd.py", line 4507, in create_aot_dispatcher_function
    raise RuntimeError(f"""
RuntimeError: 
Found following user inputs located at [0] are mutated. This is currently banned in the aot_export workflow.
If you need this functionality, please file a github issue.

fw_metadata=ViewAndMutationMeta(input_info=[InputAliasInfo(is_leaf=True, mutates_data=True, mutates_metadata=False, mutations_hidden_from_autograd=False, requires_grad=False, mutation_type=<MutationType.MUTATED_OUT_GRAPH: 3>)], output_info=[OutputAliasInfo(output_type=<OutputType.is_input: 3>, raw_type=<class 'torch._subclasses.functional_tensor.FunctionalTensor'>, base_idx=0, dynamic_dims=set(), requires_grad=False)], num_intermediate_bases=0, keep_input_mutations=False, traced_tangents=[], subclass_inp_meta=[0], subclass_fw_graph_out_meta=[0, 1], subclass_tangent_meta=[], is_train=False, requires_subclass_dispatch=False, num_symints_saved_for_bw=None, grad_enabled_mutation=None)
```

**Comment by avikchaudhuri** [comment]
Short term, `aot_export` should emit a better error here, since it's part of the `export` call. (We do manage to get a graph from Dynamo here.)

I'm not sure what the long term fix is. Thoughts, @ydwu4 ?

**Comment by avikchaudhuri** [comment]
Also cc @angelayi @zhxchen17 @tugsbayasgalan

**Comment by zhxchen17** [comment]
I feel aot_export_module should support this in the long term. We need to add a new output type for mutated input though.

**Comment by oulgen** [comment]
Can't you support this via functionalization? Just make the input become a graph output?

**Comment by ydwu4** [comment]
> Can't you support this via functionalization? Just make the input become a graph output?

I think that's what @zhxchen17 means (the new output type). We think this could be a well-scoped feature to add and have strong use cases in my opinion.

**Comment by zhxchen17** [comment]
@oulgen not sure what you mean. we can support this via functionalization. that what I meant.

**Comment by tugsbayasgalan** [comment]
Yes I think we should support this in the long term! For immediate next action, i think we should emit a better error message. cc: @bdhirsh

**Comment by zhxchen17** [comment]
> Yes I think we should support this in the long term! For immediate next action, i think we should emit a better error message. cc: @bdhirsh

I'm wondering if we can directly support it for now instead of making it the long term, because I feel it shouldn't be that hard. but Brian might correct me lol.

**Comment by bdhirsh** [comment]
Hmm. Just to lay out the backstory that brought us here:

(1) `aot_export_module` bans several forms of input mutations today.

Why? Input mutations complicate the calling convention for the exported runtime. For every type of extra mutation, we need to attach extra metadata to the `GraphSignature` object.

`aot_export_module` promises to always output a functional graph, and so the way it handles input mutations is that it returns updated inputs as **extra outputs** in the graph. It's then on the runtime that handles the exported graph, to make sure to take these updated inputs and applying the mutation back to the inputs. The only case where this has really mattered in practice so far is from e.g. `BatchNorm`, which mutate buffers. And so `aot_export_module` has special handling for mutations on module buffers (along with extra metadata in the GraphSignature), but bans other types of mutations (unless we have a good reason for needing to allow them. For example: in practice, are there really any models we want to export where the forward/backward pass would mutate, say, one of the input images to the forward pass inplace?

(2) @oulgen 's work on plumbing triton kernels through torch.compile presents some problems in this approach: Today, we handle triton kernels in PT2 by converting the triton kernel to a HigherOrderOperator in our graph's IR. We also have to (pessimistically) assume that every input to the triton kernels **might** have been mutated, since we don't currently try to statically analyze the kernel. This results in some "false positive" mutations showing up in our graph, where we `torch.compile` thinks that there was an input mutation (we passed an input to a triton kernel), but in practice the triton kernel doesn't actually mutate the input.

(3) `torch.compile` does something quite different from `torch.export` to handle all of these (fake) input mutations: First, after running functionalization it inserts `inpt.copy_(inpt_updated)` nodes into the graph for each input, to reflect the fact that an input was mutated by a triton kernel. Then, it relies on inductor to run a reinplacing pass, which is smart enough to remove the `copy_()` nodes entirely, and directly run the original triton kernel in the generated code (which may or may not actually mutate the triton inputs, but will have the same behavior as the original user code

So my question (maybe for @oulgen / @zhxchen17 ?) is: what do we want the exported artifact to look like when we have triton kernels in it? The default thing that will happen today (if we remove the linked error message) is that if you try to export code like:
```
def forward(x, y):
    out = torch.zeros_like(x)
    triton_kernel[grid](x, y, out)
```

We never have a chance to run inductor's reinplacing, and so we will end up with an exported graph thinks that `x` and `y` were mutated inputs, where we expect the export runtime to "take" those updated inputs and `copy_()` them back to the original inputs.

@oulgen if we happen to know that this issue is always coming up in the context of "fake input mutations" (in your example above, we happen to know that x and y aren't actually mutated by the triton kernel), then I wonder if it's worth sidestepping this whole issue by adding some support for inspecting the triton kernel code to figure out which inputs aren't actually mutated? (this won't solve the issue if we have a mutable custom op that mutates a random input to the model, but maybe it's worth waiting for someone to actually run into that problem before we solve it for export)

**Comment by oulgen** [comment]
> then I wonder if it's worth sidestepping this whole issue by adding some support for inspecting the triton kernel code to figure out which inputs aren't actually mutated?
@bdhirsh I think getting this correct is actually very difficult. We can do simple stuff with like grep for tl.store etc but if there's aliasing and such, we would need to do graph capture which is likely more than we are willing to do. wdyt?

**Comment by zhxchen17** [comment]
> Hmm. Just to lay out the backstory that brought us here:
> 
> (1) `aot_export_module` bans several forms of input mutations today.
> 
> Why? Input mutations complicate the calling convention for the exported runtime. For every type of extra mutation, we need to attach extra metadata to the `GraphSignature` object.
> 
> `aot_export_module` promises to always output a functional graph, and so the way it handles input mutations is that it returns updated inputs as **extra outputs** in the graph. It's then on the runtime that handles the exported graph, to make sure to take these updated inputs and applying the mutation back to the inputs. The only case where this has really mattered in practice so far is from e.g. `BatchNorm`, which mutate buffers. And so `aot_export_module` has special handling for mutations on module buffers (along with extra metadata in the GraphSignature), but bans other types of mutations (unless we have a good reason for needing to allow them. For example: in practice, are there really any models we want to export where the forward/backward pass would mutate, say, one of the input images to the forward pass inplace?
> 
> (2) @oulgen 's work on plumbing triton kernels through torch.compile presents some problems in this approach: Today, we handle triton kernels in PT2 by converting the triton kernel to a HigherOrderOperator in our graph's IR. We also have to (pessimistically) assume that every input to the triton kernels **might** have been mutated, since we don't currently try to statically analyze the kernel. This results in some "false positive" mutations showing up in our graph, where we `torch.compile` thinks that there was an input mutation (we passed an input to a triton kernel), but in practice the triton kernel doesn't actually mutate the input.
> 
> (3) `torch.compile` does something quite different from `torch.export` to handle all of these (fake) input mutations: First, after running functionalization it inserts `inpt.copy_(inpt_updated)` nodes into the graph for each input, to reflect the fact that an input was mutated by a triton kernel. Then, it relies on inductor to run a reinplacing pass, which is smart enough to remove the `copy_()` nodes entirely, and directly run the original triton kernel in the generated code (which may or may not actually mutate the triton inputs, but will have the same behavior as the original user code
> 
> So my question (maybe for @oulgen / @zhxchen17 ?) is: what do we want the exported artifact to look like when we have triton kernels in it? The default thing that will happen today (if we remove the linked error message) is that if you try to export code like:
> 
> ```
> def forward(x, y):
>     out = torch.zeros_like(x)
>     triton_kernel[grid](x, y, out)
> ```
> 
> We never have a chance to run inductor's reinplacing, and so we will end up with an exported graph thinks that `x` and `y` were mutated inputs, where we expect the export runtime to "take" those updated inputs and `copy_()` them back to the original inputs.
> 
> @oulgen if we happen to know that this issue is always coming up in the context of "fake input mutations" (in your example above, we happen to know that x and y aren't actually mutated by the triton kernel), then I wonder if it's worth sidestepping this whole issue by adding some support for inspecting the triton kernel code to figure out which inputs aren't actually mutated? (this won't solve the issue if we have a mutable custom op that mutates a random input to the model, but maybe it's worth waiting for someone to actually run into that problem before we solve it for export)

@bdhirsh I'm not sure we can support triton kernel in export, because export also need to serialize the graph into a portable format, and we don't seem to support Triron kernel as part of the IR for now. I feel right now we should just ban capturing triton kernels in export because I'm also not sure whether there's real use case.

**Comment by oulgen** [comment]
> I feel right now we should just ban capturing triton kernels in export because I'm also not sure whether there's real use case

AOTI uses export and MRS kernels need user defined triton kernels. So there's a real use case for having this be supported.

**Comment by aakhundov** [comment]
> @bdhirsh I'm not sure we can support triton kernel in export in the short term, because export also need to serialize the graph into a portable format, and we don't seem to support Triron kernel as part of the IR for now. I feel right now we should just ban capturing triton kernels in export because I'm also not sure whether there's real use case.

@zhxchen17 Re real use case: It's very important to support Triton kernels in the export path, as we rely on the export path (`torch._export.aot_compile`) in the internal AOT Inductor-based lowering pipeline. Therefore, I believe, banning them altogether is not a good idea, as the user-written Triton kernels are ubiquitous in the new MRS models in the enablement pipeline. Alternative ways of AOTI-compiling through the user-written Triton kernels have serious drawbacks that we can't seem to resolve reliably, hence need the native Triton kernel support in PT2.

I think, the existing unit tests of the native Triton kernel support in the `test_aot_inductor.py` use the same export path as we use in the internal AOTI-based lowering (`torch._export.aot_compile`). And those tests are passing (except the input mutation issue that @oulgen has raised here). Does this should that we can export Triton kernels fine?

**Comment by oulgen** [comment]
To be clear, the original discussion started as exports not handling mutation of graph inputs. This I believe can be solved via functionalization and converting the input to also be a graph output.

Secondly, for user defined triton kernels, there are 2 export paths.
1) AOTI + export: This one currently works fine modulo if a graph input is passed to triton kernel it fails due to above unrelated issue.
2) just export: This one currently does not work but could be very easily implemented via serialization of triton kernel's source code + its dependancies. @Chillee recommended this a while ago anyway.

cc: @zou3519

**Comment by zhxchen17** [comment]
> > @bdhirsh I'm not sure we can support triton kernel in export in the short term, because export also need to serialize the graph into a portable format, and we don't seem to support Triron kernel as part of the IR for now. I feel right now we should just ban capturing triton kernels in export because I'm also not sure whether there's real use case.
> 
> @zhxchen17 Re real use case: It's very important to support Triton kernels in the export path, as we rely on the export path (`torch._export.aot_compile`) in the internal AOT Inductor-based lowering pipeline. Therefore, I believe, banning them altogether is not a good idea, as the user-written Triton kernels are ubiquitous in the new MRS models in the enablement pipeline. Alternative ways of AOTI-compiling through the user-written Triton kernels have serious drawbacks that we can't seem to resolve reliably, hence need the native Triton kernel support in PT2.
> 
> I think, the existing unit tests of the native Triton kernel support in the `test_aot_inductor.py` use the same export path as we use in the internal AOTI-based lowering (`torch._export.aot_compile`). And those tests are passing (except the input mutation issue that @oulgen has raised here). Does this should that we can export Triton kernels fine?

@aakhundov Thanks for explaining to me. Yeah it kinda makes sense, but afaik it's not on export team's radar right now. I believe there're some gaps between our understanding and I have concerns that if no one on export team knows what we're planning to do here, things will be broken easily later. 

As @oulgen pointed out, the original issue doesn't seem related to Triton. So I agree that we should be able to resolve this using functionalization.

(Anyone wants to follow up with the export team to discuss Triton kernel support btw?) cc @gmagogsfm @avikchaudhuri

**Comment by thiagocrepaldi** [comment]
This seems to be working on main branch. should we close it?
