### ISSUE TITLE
Tracing per-param sharding FSDP: User Defined Objects as inputs to HOPs (autograd.Function, specifically) 

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#114292]
### 🐛 Describe the bug

parent: https://github.com/pytorch/pytorch/issues/114286

Pretty self explanatory. There are cases where UDOs can show up in HOPs - we should support them. 

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @ydwu4 @kiukchung @lucasllc @d4l3k

**Comment by ezyang** [comment]
This showed up when we did torchrec enablement and I do not see a good route to handling this. The problem is that UDO is a Dynamo level concept, but HOPs have to make it all the way to AOTAutograd, where we are generally not allowed to be passing around UDOs anymore (it needs to be all primitive types). So you have to do the complicated via compiled autograd route, similar to how we were handling backward hooks.

**Comment by awgu** [comment]
For context, this autograd function looks like:
```
class RegisterPostBackwardHook(torch.autograd.Function):
    @staticmethod
    def forward(
        ctx,
        param_group,
        *inputs,
    ):
        # All tensors in `inputs` should require gradient
        ctx.param_group = param_group
        return inputs

    @staticmethod
    def backward(ctx, *grads):
        ctx.param_group._post_backward()
        return (None,) + grads
```
In flat-parameter FSDP, we have `ViewBackward` -> `SplitWithSizesBackward` -> `FlatParameter` `AccumulateGrad` as backward functions that always run after any input tensor's backward function because the `view` and `split` are called before `forward()`. In that case, using a post-accumulate grad hook on the `FlatParameter` gives a point in the execution where the gradients with respect to the input tensors _and_ with respect to the parameters must have been computed so we can both free parameters and reduce-scatter their gradients.

However, this approach does not carry over directly to per-parameter FSDP where the original parameters are the leafs with respect to autograd. Their gradients may be computed before gradients with respect to input tensors, so if we registered a multi-grad hook on the parameters, that hook cannot safely free parameters. We may need to register a multi-grad hook on the parameters and the input tensors together. Would that be easier to trace than this custom autograd function?

For this custom autograd function, my implementation extracts the tensors that require gradient from the forward input tensors and passes them into the autograd function forward above. I have confirmed that this approach resolves longstanding FSDP issues like https://github.com/pytorch/pytorch/issues/94857.

**Comment by ezyang** [comment]
What exactly is `param_group` here? Is it possible to pass a list of tensors and then reconstruct the param group later in backwards? That would also resolve the problem here.

**Comment by awgu** [comment]
The hook that we want to run (`_post_backward()`) will need a reference to the `param_group`, which is the user-defined object (IIUC). It holds necessary state like references to the parameters, streams, etc.

Would it change anything if we partially applied the `param_group` into `_post_backward()` so that the definition looked something like:
```
hook = functools.partial(_post_backward, param_group)
class RegisterPostBackwardHook(torch.autograd.Function):
    @staticmethod
    def forward(
        ctx,
        hook,
        *inputs,
    ):
        # All tensors in `inputs` should require gradient
        ctx.hook = hook
        return inputs

    @staticmethod
    def backward(ctx, *grads):
        ctx.hook()
        return (None,) + grads
```

**Comment by ezyang** [comment]
That doesn't help because hook is still a user defined object.

To be clear, there *is* a way to make autograd functions like this work, but it's much more similar to how we made register hook work: you need compiled autograd to deal with reconstruction out the other end.

**Comment by zou3519** [comment]
We support UDOs as inputs to autograd.Function now, please reopen if not.
