### ISSUE TITLE
__torch_function_ subclasses do not work with dynamic shapes

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#114369]
### 🐛 Describe the bug

Running the following code results in an infinite loop:
```python
class TestTensor(torch.Tensor):
    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}
        with torch._C.DisableTorchFunctionSubclass():
            out = func(*args, **kwargs)
            if func == torch.clone:
                return out * 2
            return out

def fn(x):
    return torch.clone(x)

with torch._dynamo.config.patch(traceable_tensor_subclasses={TestTensor}):
    inp = torch.ones(4, 4)
    x = TestTensor(inp)
    torch._dynamo.mark_dynamic(x, 0)
    compiled_fn = torch.compile(fn, backend="eager", fullgraph=True)
    out = compiled_fn(x)
    assert torch.allclose(out, torch.ones(4, 4) * 2)
```
What I think might be happening:
- When dynamo runs with dynamic shapes, it makes any Symbols on tensor inputs to the graph also inputs to the graph.  This means that during runtime there needs to be some extra logic that runs before compiled program runs that calls `inp.size()` in order to produce those symint/int inputs. 
- During runtime the user runs this logic with a torch function subclass, triggering torch compile to compile the `__torch_function__` frame and replacing the bytecode that runs on that subclass. Ordinarily `__torch_function__` subclass needs `torch._C.DisableTorchFunctionSubclass()` to avoid infinite looping, but this logic is traced away. 

A workaround:
- Disable torch.compile `__torch_function__` frames with `@torch._dynamo.disable(recursive=False)`. There is special logic that ignores this flag so that inlining still works.

```
  ===== __compiled_fn_0 =====
  <eval_with_key>.0 class GraphModule(torch.nn.Module):
     def forward(self, s0 : torch.SymInt, L_x_ : __main___TestTensor):
         l_x_ = L_x_

         # File: /Users/jw3468/local/.tests/tst3.py:1435, code: out = func(*args, **kwargs)
         out = torch.clone(l_x_);  l_x_ = None

         # File: /Users/jw3468/local/.tests/tst3.py:1437, code: return out * 2
         mul = out * 2;  out = None
         return (mul,)
```

### Versions

main

cc @hameerabbasi @rgommers @peterbell10 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by mlazos** [comment]
Hmm I think I've figured this out, basically during guard evaluation the `__torch_function__` is invoked, and then at the func call dynamo is invoked again, triggering guard evaluation etc. In previous discussions with @anijain and @bdhirsh we concluded that we should disable torch_function eval during guard eval because dynamo will have traced through torch function already. For example if you're accessing an attr x on a tensor subclass, dynamo will trace through the torch function and finally access x under a disable subclass at the end of the `__torch_function__` invocation, so any guards added should be on values without `__torch_function__` enabled. 

I will submit a PR and see if this works as expected.

**Comment by mlazos** [comment]
Finally root caused this - the `size()` calls in the generated bytecode (to pass the shapes to the graph) trigger torch function, which dynamo compiles, but then on subsequent calls, the bytecode for the compiled torch function has size calls, which introduce an infinite loop. Will wrap the size calls in a disable/skip for dynamo and should fix this.
