### ISSUE TITLE
[RFC] macOS x86 builds / test deprecation

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#114602]
### 🚀 The feature, motivation and pitch

As new Intel Mac's are no longer produced and with time fewer will remain in use, I propose stop testing and eventually building MacOS x86_64 binaries by the end of 2023 (i.e. release PyTorch-2.2 without x86_64 MacOS wheels)

### Alternatives

NA

### Additional context

https://en.wikipedia.org/wiki/Mac_transition_to_Apple_silicon

cc @seemethere @osalpekar @atalman @pytorch/pytorch-dev-infra @albanD

**Comment by atalman** [comment]
@malfet What about conda builds for MacOS x86? If we removing wheels we should probably also remove conda builds.

**Comment by malfet** [comment]
@atalman suggested we should announce it in 2.2 and disable in 2.3

**Comment by seemethere** [comment]
Totally agree that we should cut support here. I feel like we're already getting to the point where PyTorch developers don't even have the hardware to debug issues even if they do arise for x86 macOS

**Comment by huydhn** [comment]
AI: DevX to clean up MacOS x86 CI jobs (and may be release jobs as well)

**Comment by atalman** [comment]
In terms of deprecation strategy I think we should keep all scripts to build on MacOS x86 in place. This will allow people to build macOS x86 binaries from source.

**Comment by traderpedroso** [comment]
I believe it would be completely unfair, considering that Apple is still selling this year's Mac Pro with Intel processors. Moreover, the performance of the M1 and M2 compared to AMD GPUs is quite underwhelming. Especially for people like me who have invested over $100,000 in Apple machines, because even though there's talk about Apple Silicon, the Intel-based Apple computers are still much better for AI, at least for data scientists and developers.

**Comment by seemethere** [comment]
> I believe it would be completely unfair, considering that Apple is still selling this year's Mac Pro with Intel processors. Moreover, the performance of the M1 and M2 compared to AMD GPUs is quite underwhelming. Especially for people like me who have invested over $100,000 in Apple machines, because even though there's talk about Apple Silicon, the Intel-based Apple computers are still much better for AI, at least for data scientists and developers.

Hey Emerson! I appreciate your support / concern here and want to empathize about making a big purchase and feeling like it will not be supported by the tools that you would like to use. Unfortunately Intel macOS is a platform that we will not be able to continue to support in the future due to lack of hardware access for our developers as well as climbing costs for CI on the various platforms that we utilize for our CI.

We are expecting Intel macOS to continue to be a community supported model and will allow the build paths for Intel based macOS machines to exist but we will not be actively supporting them  through bug fixes or building binaries for them. More-so we will also continue to serve the previous versions of PyTorch that support Intel macOS so you should still be able to have a version that is usable.

Once again we appreciate your feedback and happy to continue this conversation on this issue. If you feel as though there is a larger representation of users concerned with this issue I'd encourage them to respond here since we are not seeing this representation within our current download numbers for PyTorch packages.

**Comment by seemethere** [comment]
> I believe it would be completely unfair, considering that Apple is still selling this year's Mac Pro with Intel processors.

As well, I'm not entirely seeing the Intel macOS offering with the Mac Pro on the current Apple website (https://www.apple.com/mac-pro/), can you provide a link to the page where they are selling these?

**Comment by malfet** [comment]
One can buy one from [here](https://www.apple.com/shop/refurbished/mac/mac-pro):
<img width="1007" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/0048d0b4-c38e-4dc2-80e5-4302f0530db0">

**Comment by seemethere** [comment]
> One can buy one from [here](https://www.apple.com/shop/refurbished/mac/mac-pro):
> 
> <img width="1007" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/0048d0b4-c38e-4dc2-80e5-4302f0530db0">
> 
> 

I wouldn't saying selling refurbished hardware is an indication of continued support here but I can understand the sentiment.

**Comment by malfet** [comment]
> the Intel-based Apple computers are still much better for AI, at least for data scientists and developers.

According to  [w6800x-duo specs](https://www.techpowerup.com/gpu-specs/radeon-pro-w6800x-duo.c3824) dual GPU system on $30+K MacPro can deliver 30 Tflops for fp32. At the same time, according to [wiki](https://en.wikipedia.org/wiki/Apple_M2#:~:text=In%20total%2C%20the%20M2%20Max,27.2%20TFLOPS%20of%20FP32%20performance.) M2 Ultra delivers about 27 TFlops, but costs about $4K.

That is, spending 7x times more money gives one 10% more perf. Or am I missing something in those calculations?

**Comment by sergei3000** [comment]
I totally agree with what @traderpedroso wrote here

**Comment by viktor765** [comment]
Surprised by, and strongly disagree with, this one. I have used a 2015 Macbook Pro for lighter tasks and prototyping with Pytorch for a while, and it does the job. This means we're not going to see a Pytorch version that supports Python 3.12 on those platforms, where there are tons of high-quality second-hand devices on the market, otherwise perfect for students.

**Comment by malfet** [comment]
- If one is prototyping, I'm not sure why Python version matters that much
- Python-3.12 builds are available for 2.2.0 (except torch.compile)
- Nobody stopping the community from proposing fixes and x86 Macs or coming up with PRs that will cross-compile x86 binary on Apple Silicon (Apple Silicon binaries were built on x86 Mac up until this release) and thus keeping builds alive

**Comment by atalman** [comment]
Assigning to 2.3.0 milestone. Since this our projected release when no MacOS x86 binaries will be produced

**Comment by yangsfang** [comment]
I think the deprecation timeline is a bit short. This was proposed in October but most people like myself didn't see the message until reading the 2.2.0 release notes from Jan 30. Would appreciate if you put it in low maintenance mode but still produce them for another quarter to give more time for migration.

ARM is indeed the future for macOS, but the Intel Macs are still relatively recent (many models are released in early-mid 2020). In the ideal world everyone will be using these faster, more energy efficient machines, but not sometimes people bought at the wrong time and not everyone (especially outside Silicon Valley, California, United States) is able to purchase new hardware as they become available.

Nobody stopping the community from producing these builds. But considering the short timeframe, would be nice if time is given for these community builds to become available and guides to be written before the cutoff happens. This would help many beginners such as myself for a smooth transition off the official builds to the community builds. If there are any community builds already available, then please point me to them.

Again, I think what you're doing completely makes sense. Just that the timeline seems a bit short.

**Comment by aisven** [comment]
Dear Team,

first of all thank you for providing this excellent library `torch`.

I am a university student in Europe using a 2019 MacBook Pro with an Intel CPU.

I just spend this whole holiday afternoon and evening with

- trying to install various PyTorch 2.3.0 wheels
- upgrading things in my environment such as python itself, poetry, pip, conda, then even the macOS itself
- again trying to install various PyTorch 2.3.0 wheels
 
until I figured out why neither poetry nor pip would let me upgrade or install PyTorch 2.3.0 through finding this very issue here via an elaborate Google search.

I do disagree, like most responders on this issue here, with this particular deprecation and removal.

Please bring back the official wheels for Apple hardware with Intel CPUs for PyTorch 2.3.x and ideally also for later versions.

**Comment by uwu-420** [comment]
@seemethere 

> We are expecting Intel macOS to continue to be a community supported model and will allow the build paths for Intel based macOS machines to exist but we will not be actively supporting them through bug fixes or building binaries for them.

Is this community supported model in the room with us right now?

**Comment by MiladInk** [comment]
I just wanted to say as a researcher with an x86 intel mac, I would really appreciate if they were continued to be supported. I know many friends of mine who have the same macs. Especially, purchasing a decent mac is a near 4000$ purchase and replacing this with student fundings is not easy. Professors mostly cover an upgrade for a single Ph.D. duration. I use my mac for local debugging and currently because the vmap over `scaled_dot_product_attention` raise an error on torch<2.4 I need to change my setup. All I am saying is that while I understand the reasoning behind deprecation, continued support would have lots of benefits for students. Thanks.

**Comment by traderpedroso** [comment]
> I just wanted to say as a researcher with an x86 intel mac, I would really appreciate if they were continued to be supported. I know many friends of mine who have the same macs. Especially, purchasing a decent mac is a near 4000$ purchase and replacing this with student fundings is not easy. Professors mostly cover an upgrade for a single Ph.D. duration. I use my mac for local debugging and currently because the vmap over `scaled_dot_product_attention` raise an error on torch<2.4 I need to change my setup. All I am saying is that while I understand the reasoning behind deprecation, continued support would have lots of benefits for students. Thanks.

I was really upset about the deprecation for Intel, but the only problem I found is that I have to compile myself for x86 and Apple Silicon. Same API for metal, zero difference. If you want to use it, just compile. I'm thinking about creating a fork to make the x86 version available.

**Comment by malfet** [comment]
>> I was really upset about the deprecation for Intel, but the only problem I found is that I have to compile myself for x86 and Apple Silicon. Same API for metal, zero difference. If you want to use it, just compile. I'm thinking about creating a fork to make the x86 version available.

If you can setup a CD pipeline using some sort of a free compute, please do not hesitate to propose a PR or mention it in discussion forums I would love to be able to use some of that stuff on my old Mac. But in terms of public compute, Intel Macs are getting harder to find, for example GitHub's `macos-latest` is now Apple Silicon only.

**Comment by girishponkiya** [comment]
Apparently, the latest version of vLLM (https://github.com/vllm-project/vllm/pull/6931) needs `torch==2.4.0`, and I'm not able to install it on my Intel Mac. 😞 
Ref: https://github.com/vllm-project/vllm/blob/main/requirements-cpu.txt#L5

**Comment by snimavat** [comment]
Sad, surya_ocr needs torch > 2.3.0 and i am unable to install it on my mac 12.5

Are there steps on how to build / install from source?

**Comment by mirceamironenco** [comment]
For macOS x86, you can install 2.4.0 via conda using the conda-forge channel.
See https://github.com/conda-forge/pytorch-cpu-feedstock/.

**Comment by caarmen** [comment]
> If you feel as though there is a larger representation of users concerned with this issue I'd encourage them to respond here since we are not seeing this representation within our current download numbers for PyTorch packages.

👋🏻 

Wanted to try out pytorch. I'm on a an intel mac. Can't download the latest version of pytorch.

**Comment by derkan** [comment]
Forcing us to buy M1 Macs?
Are 2019 Intel macs are dead?

**Comment by Unturned3** [comment]
God... what is this bullsh\*t? There's probably a zillion people out there (including me) that's still running Intel macs. I found out about this deprecation _today_ when I realized my pytorch is stuck on 2.2.2 when the latest is 2.5.1...

**Comment by dokterbob** [comment]
Just did a macOS build for 2.5.1 (for some reason version number isn't correctly set for the file).
Python 3.10 built on Sonoma 14.7.1

https://cloud.dokterbob.net/s/Fkt8LABqHoqTJHM

**Comment by lorentzenchr** [comment]
While I understand the decision to no longer support mac x86 on pypi, the timing is a bit unfortunate. Just one more version, namely 2.3, would be very valuable as it is the first one to support numpy 2.0 (#107302).
Would it be thinkable to upload wheels just for this one additional version and then end of story?

**Comment by Xgz20** [comment]
After analyzing for a long time, I realized that it's the intel mac that doesn't have the latest torch packages, tough luck!😞

**Comment by RoelantStegmann** [comment]
> 
> While I understand the decision to no longer support mac x86 on pypi, the timing is a bit unfortunate. Just one more version, namely 2.3, would be very valuable as it is the first one to support numpy 2.0 (https://github.com/pytorch/pytorch/issues/107302).
> Would it be thinkable to upload wheels just for this one additional version and then end of story?
> 

Agree, this would really unblock us - numpy 2.0 creates a chain of dependencies.

**Comment by lorentzenchr** [comment]
> While I understand the decision to no longer support mac x86 on pypi, the timing is a bit unfortunate. **Just one more version, namely 2.3, would be very valuable as it is the first one to support numpy 2.0** (https://github.com/pytorch/pytorch/issues/107302).
Would it be thinkable to upload wheels just for this one additional version and then end of story?

@gchanan @dzhulgakov @ezyang @malfet Is this possible to discuss this? I can also live with a no. But I wanted to make it explicit and also transparent that because of numpy 2.0, banning macOS x86 from pytorch 2.3 might have larger effects than you might have anticipated.

**Comment by uwu-420** [comment]
> Just did some macOS build for 2.5.1.

@dokterbob thanks for having made that build! Did the tests pass for you? When I `cd` into `build` and run `ctest` I get some failures for e.g. `vec_test_all_types_AVX2`.

Tbf, it looks like some floating point imprecision problems, so not really big divergences, but still. This is on `macOS 14.7.1` with a `Intel i5-8500B` CPU and `Apple clang version 16.0.0 (clang-1600.0.26.6)`

**Comment by uwu-420** [comment]
To quote @seemethere 
> We are expecting Intel macOS to continue to be a community supported model

So here we are, I'm making a dumb attempt to get a proper macOS x86_64 build of pytorch 2.6.0 with compatibility all the way back to macOS version 10.15 (the build for 10.14 is already terminally broken) so feel free to join the discussion in the pytorch forums https://discuss.pytorch.org/t/building-pytorch-2-6-0-from-source-on-macos-x86-64-intel/216283 an have a laugh at my miserable attempts so far :) Any help and feedback is highly appreciated.

**Comment by uwu-420** [comment]
@h-vetinari this is wonderful! Thanks for showing me this :) 

It's only compatible with macOS 10.15+ though. Otherwise I would have been quite surprised because it's impossible to compile latest upstream pytorch for macOS deployment targets below 10.15 due to usage of some C++ 17 functionality like the filesystem library which at least requires macOS 10.15+

Out of curiosity, is there something off in the https://github.com/conda-forge/pytorch-cpu-feedstock ? When I grep for `2.6.0` there is only one match while I see plenty of
```yaml
libtorch:
- '2.4'
```
and
```yaml
pytorch:
- '2.4'
```
in all those yaml files. I don't understand how that build process works, but just asking here. Is that an issue?

Also, is it theoretically possible to build a wheel this way? I guess that's what many people are interested in.

**Comment by h-vetinari** [comment]
> It's only compatible with macOS 10.15+ though. Otherwise I would have been quite surprised because it's impossible to compile latest upstream pytorch for macOS deployment targets below 10.15 due to usage of some C++ 17 functionality like the filesystem library which at least requires macOS 10.15+

Conda-forge ships an up to date C++ standard library, so it is not subject to the constraints of the system library. So it is actually 10.13+

> Out of curiosity, is there something off in the https://github.com/conda-forge/pytorch-cpu-feedstock ? When I grep for `2.6.0` there is only one match while I see plenty of

It only needs to be set once (in recipe/meta.yaml). The other occurrences are incidental (due to the way our bots overpopulate some configs), but harmless.

**Comment by uwu-420** [comment]
@h-vetinari okay that's pretty cool! Conda-forge seems like a really great ecosystem in that regard.

Do you have some advice with regard to how feasible it would be to try doing something like this outside of the conda-forge ecosystem? Having a ecosystem-independent plain standard wheel distribution of pytorch for x86_64 macOS would be a good thing imo.

**Comment by h-vetinari** [comment]
> Do you have some advice with regard to how feasible it would be to try doing something like this outside of the conda-forge ecosystem?

Very hard, which is presumably with pytorch deprecated it. Pytorch has a number of heavyweight dependencies, and stuffing all of that into a wheel is subject to many constraints and complications. 

Conda (the format) is a much more comprehensive paradigm that makes this effort much more feasible in conda-forge, and even then it was dozens of hours of work to catch up with the former pytorch channel (to say nothing of the combined expertise of many experienced people). That was across all platforms though, so if you're only concerned about osx-64 you might still have a chance.

Only way to find out is to try, but though I'm obviously biased, I'd say your time would be better spent switching to conda-forge (you should try the next-gen pixi installer, which is a joy to work with).

**Comment by uwu-420** [comment]
Thanks for the honest assessment! I appreciate it. I'll check out pixi 👍
