### ISSUE TITLE
[AOTAutograd] nit `assert_functional_graph` is misnamed

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#114760]
### 🐛 Describe the bug

Not sure if the usage is correct. In one point, it is just called. But it is not asserted that the `copy_` count is 0.

https://github.com/pytorch/pytorch/blob/4a4c9fb0b8e2fe11316a1f998a71a2fba7acfc16/torch/_functorch/aot_autograd.py#L3760

Is this correct @bdhirsh? Or should this be updated to also assert on the number of `copy_`s?

Regardless, the usage between `aot_dispatch_autograd_graph` and `aot_dispatch_base_graph` is slightly inconsistent.
### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by bdhirsh** [comment]
I'm going to close this because:

(1) it is technically true that the name is slightly off, because we **do** allow `copy_` nodes to show up in the graph (making it not functiona).. But the main purpose of that function is to assert that the functional invariants of our graph are upheld, which today are pretty much "the graph is fully functional, with an optional mutable epilogue of copy_ nodes at the end" (I don't think the name here is thaaat confusing, and you can see these invariants from reading the code)

(2) re-reading this issue, I think the confusion at the time had more to do with the fact that we asserted different things in inference vs training. We used to not allow `copy_` nodes in the graph for training only, but allowed them for inference, so we would assert slightly different things. Since then we've cleaned things up, and the functional invariants are the same across both paths.
