### ISSUE TITLE
models with backward hooks not serializing

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1148]
Douwe Kiela reports:

After registering a backward hook, when saving checkpoints, I get:

```
Traceback (most recent call last):
  File "main.py", line 472, in <module>
    torch.save(network, '%s/model-%s-%s.pkl' % (params.savedir, params.name, epoch))
  File "/home/dkiela/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/home/dkiela/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 186, in _save
    pickler.dump(obj)
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

**Comment by vadimkantorov** [comment]
I've stumbled upon this before. It's because standard `pickle` doesn't like lambdas, nested functions and nested classes. One workaround is using other pickles like `dill` or `cloudpickle` (and `hickle` if it works). Another may be hacking `pickle` in bad ways to support these (like converting lambdas to named global functions with random names, but it would probably break user expectations about reference identity of the passed lambdas).

**Comment by apaszke** [comment]
The problem occurs only for lambdas and closures but I really think there's no way around that. Passing in `dill` as `pickle_module` arg to `torch.save` should help, but serializing bytecode is a very bad idea. The checkpoints will likely only load under the exact same Python version that was used to save them.
