### ISSUE TITLE
UNSTABLE rocm / linux-focal-rocm5.7-py3.8 / test (default)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#115050]
Looks like https://github.com/pytorch/pytorch/pull/114772 broke a bunch of tests, though it shouldn't be the case...

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @seemethere @pytorch/pytorch-dev-infra

**Comment by jeffdaily** [comment]
@malfet it didn't just update the triton pin.  It changed other files
- .github/scripts/build_triton_wheel.py
  - changes triton_pkg_name to read from env var instead of earlier setting it to triton_pkg_name = "pytorch-triton-rocm"
- torch/_inductor/codegen/wrapper.py
- torch/_inductor/utils.py
  - this is using `nvsmi` from triton.testing, which calls out to nvidia-smi --- no rocm alternative within inductor or triton-rocm.

**Comment by huydhn** [comment]
This has been fixed by https://github.com/pytorch/pytorch/pull/115102 and ROCn signals in trunk are green now https://hud.pytorch.org/pytorch/pytorch/commit/f6b6fad1367804cebdfdd5f5b7f92b2fb1cefe79
