### ISSUE TITLE
[cppdocs] torch::load function istringstream example typo

### ISSUE THREAD

**Issue by D-K-E** [pytorch/pytorch#115243]
### 📚 The doc issue

Currently the docs show the following:
```c++
torch::nn::Linear model(3, 4);
torch::load(model, "model.pt");

torch::optim::SGD sgd(/*lr=*&zwj;/0.9);
std::istringstream stream("...");
torch::load(sgd, stream);

auto tensor = torch::ones({3, 4});
torch::load(tensor, "my_tensor.pt");
```

The comments that start with `sgd(/*` is never closed. This is probably not intentional.

### Suggest a potential alternative/fix

The following snippet can be used instead
```c++
torch::nn::Linear model(3, 4);
torch::load(model, "model.pt");

torch::optim::SGD sgd(/*lr=*/0.9);
std::istringstream stream("...");
torch::load(sgd, stream);

auto tensor = torch::ones({3, 4});
torch::load(tensor, "my_tensor.pt");
```

cc @svekars @carljparker @jbschlosser

**Comment by TechSis01** [comment]
After careful observation and reading through the documentation in order to fix this issue, I realised that the typo has already been corrected just like suggested above. 

///   torch::nn::Linear model(3, 4);
///   torch::load(model, "model.pt");
///
///   torch::optim::SGD sgd(/*lr=*/0.9);
///   std::istringstream stream("...");
///   torch::load(sgd, stream);

The comment has been closed properly and has better readability. I believe the issue can be considered as resolved.
Thank you for maintaining this project.

**Comment by D-K-E** [comment]
I can't verify this. Here is the [link](https://pytorch.org/cppdocs/api/function_namespacetorch_1ad98de93d4a74dd9a91161f64758f1a76.html#namespacetorch_1ad98de93d4a74dd9a91161f64758f1a76) to the function documentation. This is being rendered as the following in my browser (Firefox 120.0 (64-bit) Ubuntu 22.04):
 
![image](https://github.com/pytorch/pytorch/assets/22693287/3e6ffc06-7033-4a49-b180-ca525b46e6ba)

From the `&zwj;`, I am assuming that the documentation generator is not parsing the line correctly. I don't know why though, probably some characters need to be escaped.

**Comment by Ganesh2409** [comment]
I want to contribute .. :) I didn't found any of the docs folder in the repository  ...! can you please address me the document i needed to change
