### ISSUE TITLE
`nn.Module.to(dtype)` does not work for XLATensor

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/pytorch#115792]
### 🐛 Describe the bug

I am debugging a issue where `module.to(torch.bfloat16)` does not really move the underlying `XLATensorImpl` to the correct dtype. The code is really simple
```
    xla_resnet18 = torchvision.models.resnet18()
    xla_resnet18.load_state_dict(resnet18.state_dict())
    xla_resnet18.to(device)
    xla_resnet18.to(torch.bfloat16)
```

I did some debugging and finally find the culprit. in 
https://github.com/pytorch/pytorch/blob/626b7dc847bff19c70b200fa2228bf2b8f4df753/torch/nn/modules/module.py#L818-L830

nn.Module will perform the `to` operation by swapping the `param.data` by `param.data = param_applied` where `param_applied` is the `tensor` with correct dtype, I also confirm it with XLA API.
```
(Pdb) print(torch_xla._XLAC._get_xla_tensors_text([param.data]))
IR {
  %0 = f32[64,3,7,7]{0,3,2,1} xla::device_data(), xla_shape=f32[64,3,7,7]{0,3,2,1}, ROOT=0
}

(Pdb) print(torch_xla._XLAC._get_xla_tensors_text([param_applied]))
IR {
  %0 = f32[64,3,7,7]{0,3,2,1} xla::device_data(), xla_shape=f32[64,3,7,7]{0,3,2,1}
  %1 = bf16[64,3,7,7]{0,3,2,1} xla::cast(%0), xla_shape=bf16[64,3,7,7]{0,3,2,1}, ROOT=0
}
```

However for some reason `param.data = param_applied` becomes a noop. even if I manually do it 
```
(Pdb) param.data = param_applied
(Pdb) print(torch_xla._XLAC._get_xla_tensors_text([param.data]))
IR {
  %0 = f32[64,3,7,7]{0,3,2,1} xla::device_data(), xla_shape=f32[64,3,7,7]{0,3,2,1}, ROOT=0
}

(Pdb) print(torch_xla._XLAC._get_xla_tensors_text([param_applied]))
IR {
  %0 = f32[64,3,7,7]{0,3,2,1} xla::device_data(), xla_shape=f32[64,3,7,7]{0,3,2,1}
  %1 = bf16[64,3,7,7]{0,3,2,1} xla::cast(%0), xla_shape=bf16[64,3,7,7]{0,3,2,1}, ROOT=0
}
(Pdb) id(param.data)
139522013275696
(Pdb) id(param_applied)
139522042606432
```

it does correctly set the dtype for `param.data`
```
(Pdb) param.data.dtype
torch.bfloat16
```
but this is even worse because user will falsely believe conversion is completed.

This is a pretty serious issue since user will be train on the incorrect dtype without knowing what happened. I am not sure how to proceed from here.

FYI @albanD @bdhirsh @ezyang 

### Versions

nightly

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @bdhirsh

**Comment by JackCaoG** [comment]
If we call the `tensor.to` instead of `module.to` it works correctly.. which is why we didn't catch this in our unit tests.

**Comment by albanD** [comment]
That is interesting.
Are XLATensor a different python subclass? Do you override `.data` there to be different from the default propery?

**Comment by JackCaoG** [comment]
I don't think so, we just implement a `XLATensorImpl` in [here](https://github.com/pytorch/xla/blob/29b183b3a618a7899dbba16e994a2f9b372b88fe/torch_xla/csrc/tensor_impl.h#L23).

**Comment by awgu** [comment]
DTensor also has this same issue (as with other tensor subclasses I imagine). cc: @wanchaol

**Comment by wanchaol** [comment]
I think use `torch.swap_tensor` in nn.Module._apply` would resolve this issue given `swap_tensor` landed recently? @albanD

**Comment by JackCaoG** [comment]
gentle ping, do we have any update on this issue? I found this kind of silent incorrect behavior to be dangerous to users.

**Comment by mikaylagawarecki** [comment]
Hey @JackCaoG, apologies for the delay!

We discussed this offline and we plan to fix this by using [`torch.utils.swap_tensor`](https://pytorch.org/docs/main/generated/torch.utils.swap_tensors.html) in place of the `.data` setting in `nn.Module.to` over here
https://github.com/pytorch/pytorch/blob/9dc68d1aa9e554d09344a10fff69f7b50b2d23a0/torch/nn/modules/module.py#L827-L829 and move towards deprecating the `.data` path.

Separately (might not pertain to this issue) we also plan to integrate `torch.utils.swap_tensor` into `nn.Module.load_state_dict()` so that an `nn.Module`'s parameters can be swapped out (e.g. with a tensor subclass that doesn't have `__slots__`) without the optimizer losing the reference to the parameters.

I will have the PR open before the end of the week to address these

**Comment by JackCaoG** [comment]
Thanks @mikaylagawarecki for the update! Looking forward for the fix!

**Comment by ysiraichi** [comment]
@mikaylagawarecki @JackCaoG 
I did some digging, and turns out this problem also happens without using `nn.Module`:

```python
device = xm.xla_device()

a = torch.rand(3, device=device)
b = a.to(torch.float64)

# First, 'a' and 'b' are shown, as expected, as f32 and f64 data-types, respectively.
print("[bef] > a:", torch_xla._XLAC._get_xla_tensors_text([a]))
print("[bef] > b:", torch_xla._XLAC._get_xla_tensors_text([b]))

a.data = b

# But, then, we see that nothing changed, even after setting 'a.data'!
print("[aft] > a:", torch_xla._XLAC._get_xla_tensors_text([a]))
print("[aft] > b:", torch_xla._XLAC._get_xla_tensors_text([b]))
```

Here's what I've found:

- `a.data = b` calls `VariableHooks::set_data`, which calls `<TensorImplClass>::shallow_copy_from`
- Fortunately, `XLATensorImpl` does implement `shallow_copy_from`, which calls `XLATensor::ShallowCopyTo` (should have solved the error)
- **Problem:** `a` and `b` are actually functional tensors, i.e.:
    ```
   Tensor(
        impl_ = FunctionalTensorWrapper(
            value_ = Tensor(
                impl_ = XLATensorImpl(tensor_ = XLATensor())
            )
        )
    )
    ```
    - When `<TensorImplClass>::shallow_copy_from` is called, the dispatch goes to: `FunctionalTensorWrapper::shallow_copy_from`
    - Since it does not have an implementation there, it actually goes to `TensorImpl::shallow_copy_from`
        - Shallow copies only the underlying `TensorImpl` data, i.e. it ignores `FunctionalTensorWrapper::value_` member
- **Possible Solution:** actually implement `FunctionalTensorWrapper::shallow_copy_from` so that it also copies its members, including `value_`

**Comment by JackCaoG** [comment]
@bdhirsh regarding `FunctionalTensorWrapper::shallow_copy_from`
