### ISSUE TITLE
[PyTorch/XLA] XLAShardedTensor untraceable by Dynamo

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/pytorch#115970]
## Issue description

In PyTorch/XLA, we're trying to register a custom op with PyTorch to make it traceable by Dynamo. While testing, however, we saw that `XLAShardedTensor` (which is an extension of `torch.Tensor`, defined at https://github.com/pytorch/xla/blob/master/torch_xla/distributed/spmd/xla_sharded_tensor.py#L61) was not be able to trace by Dynamo:
```
torch._dynamo.exc.Unsupported: call_function UserDefinedClassVariable() [TensorVariable()] {}
...
x86_64.egg/torch_xla/distributed/spmd/xla_sharding.py", line 558, in wrap_as_sharded_tensor
    return XLAShardedTensor(t)
```

IIRC, PyTorch's `DTensor` which traceable by Dynamo, is implemented as an extension of `torch.Tensor`. Should we expect `XLAShardedTensor` to be automatically traced by Dynamo as well or do we need to do something to make this happen? 

## Code example

We have a draft PR at https://github.com/pytorch/xla/pull/6161. The relevant code is at `distributed/spmd/mark_sharding.py`, in the `mark_sharding` function as it returns a type of `XLAShardedTensor`. 

cc @bdhirsh

**Comment by JackCaoG** [comment]
@wanchaol in case you have some insights.

**Comment by bdhirsh** [comment]
If you're implementing a `__torch_dispatch__` tensor subclass, in order to make it traceable you need to give it a `__tensor_flatten__` and `__tensor_unflatten__` method (e.g. [DTensor](https://github.com/pytorch/pytorch/blob/main/torch/distributed/_tensor/api.py#L250))

Although: today, the "tensor subclass + compile" path only supports the case where you have a tensor subclass that "desugars into traceable operations". So if you compile with a tensor subclass, the compiler won't see your subclass directly, it will see the "desugared" operations that you subclass called into (potentially including any custom ops that your subclass calls).
