### ISSUE TITLE
Batched torch.matmul fails assert for differentiable inputs

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#116099]
### 🐛 Describe the bug

```
In [1]: import torch

In [2]: a = torch.empty((256, 512), requires_grad=True).unsqueeze(0)

In [3]: b = torch.empty((4, 128, 512), requires_grad=True).transpose(-1, -2)

In [4]: c = torch.empty((256, 4, 128)).movedim(1, 0)

In [5]: _ = torch.matmul(a.detach(), b.detach(), out=c)

In [6]: _ = torch.matmul(a, b, out=c)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[11], line 1
----> 1 _ = torch.matmul(a, b, out=c)

RuntimeError: !(transpose && t2_is_matrix) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1695392035629/work/aten/src/ATen/native/LinearAlgebra.cpp":2026, please report a bug to PyTorch.
```

### Versions

PyTorch 2.1.0 py3.9_cuda12.1_cudnn8.9.2_0 from conda

cc @ezyang @gchanan @zou3519 @kadeng @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by zou3519** [comment]
I can repro this

**Comment by alanhe151220037** [comment]
I'm a little confused that the above python script itself is supposed to be illegal as the error log saying. 
https://github.com/pytorch/pytorch/blob/376f0365700a2263aeef69bc7304d5bb9f804c9a/torch/csrc/autograd/VariableTypeUtils.h#L72-L77
And this error check is applied in the autograd impl of functions with out arguments in `VariableTypeEverything.cpp`. For example,
```
at::Tensor & bmm_out_out(c10::DispatchKeySet ks, const at::Tensor & self, const at::Tensor & mat2, at::Tensor & out) {
  ...
  if (compute_requires_grad( self, mat2 )) {
    throw_error_out_requires_grad("bmm");
  }
  if (compute_requires_grad( out )) {
    throw_error_out_requires_grad("bmm");
  }
  ...
}
```
However, the `matmul` there is a function with key `CompositeImplicitAutograd`. It will leave the autograd to the functions it calls like "mm" or "bmm". In order to optimize the impl of `matmul`, the `require_grad` attribute of arguments was taken as a if-condition in #97355. The problem here is that the code here work for both `matmul` and `matmul_out`, but it doesn't expect the above illegal condition in `matmul_out`, which finally lead to your `INTERNAL ASSERT FAILED` here.
https://github.com/pytorch/pytorch/blob/376f0365700a2263aeef69bc7304d5bb9f804c9a/aten/src/ATen/native/LinearAlgebra.cpp#L1929-L1941

**Comment by lw** [comment]
If I understand correctly, you're saying that the "correct" behavior would have been to raise a clear error about out= not supporting differentiation? Would that be an easy fix?

However, one thing I didn't mention in the initial issue, is that I'm hitting this assert inside the forward method of a torch.autograd.Function, where I don't care about automatic differentiation, and where I'd expect out= functions to work correctly. Is there a way to make this work?

**Comment by soulitzer** [comment]
the if-condition checking requires grad should also check for the global grad-enabled-ness
