### ISSUE TITLE
torch.onnx.export does not support tensor squeeze with multiple dims

### ISSUE THREAD

**Issue by Bycob** [pytorch/pytorch#116967]
### 🐛 Describe the bug

I get an issue similar to #22066 but with tensor.squeeze

```python
import torch

print(torch.__version__)

class Module(torch.nn.Module):

    def forward(self, x):
        return x.squeeze(dim=[2, 3])

torch.onnx.export(Module(), torch.zeros((2, 3, 1, 1)), "out.onnx", verbose=True)
```
yields
```
2.1.0+cu121
Torch IR graph at exception: graph(%0 : Float(2, 3, 1, 1, strides=[3, 1, 1, 1], requires_grad=0, device=cpu)):
  %10 : int[] = prim::Constant[value=[2, 3]]()
  %9 : Float(2, 3, strides=[3, 1], requires_grad=0, device=cpu) = aten::squeeze(%0, %10), scope: __main__.Module:: # onnx_bug.py:8:0
  return (%9)

Traceback (most recent call last):
  File "onnx_bug.py", line 10, in <module>
    torch.onnx.export(Module(), torch.zeros((2, 3, 1, 1)), "out.onnx", verbose=True)
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1940, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/symbolic_opset11.py", line 930, in squeeze
    dim = symbolic_helper._get_const(dim, "i", "dim")
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 178, in _get_const
    return _parse_arg(value, desc)
  File "/home/louisj/.local/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 83, in _parse_arg
    return int(node_val)
ValueError: only one element tensors can be converted to Python scalars
```

### Versions

Torch version = 2.1.0+cu121
Python version = 3.10

**Comment by razzzeeev** [comment]
The issue you're encountering stems from the squeeze operation in your Module class. The PyTorch squeeze method is used to remove dimensions of size 1 from the shape of a tensor. However, when exporting a model to ONNX  format, there is a specific way this operation needs to be handled, particularly regarding the dimension parameters.

In your code, x.squeeze(dim=[2, 3]) is attempting to squeeze multiple dimensions simultaneously. The PyTorch ONNX exporter seems to have an issue with handling a list of dimensions in the squeeze operation. The ONNX format expects a single dimension at a time for the squeeze operation.

To resolve this, you can modify your forward method to squeeze one dimension at a time. 


`import torch

print(torch.__version__)

class Module(torch.nn.Module):
    def forward(self, x):
        x = x.squeeze(dim=2)  # Squeeze the third dimension
        x = x.squeeze(dim=2)  # Squeeze what is now the third dimension (originally fourth)
        return x

torch.onnx.export(Module(), torch.zeros((2, 3, 1, 1)), "out.onnx", verbose=True)
`
This modification sequentially squeezes the dimensions, which is compatible with the ONNX exporter. The second squeeze uses dim=2 instead of dim=3 because after the first squeeze operation, the dimensions are reduced and what was originally the fourth dimension becomes the third.

**Comment by Bycob** [comment]
> The PyTorch ONNX exporter seems to have an issue with handling a list of dimensions in the squeeze operation.

Yeah that's precisely why I made this issue :)

The error message makes me think ithis is a bug and not a feature

**Comment by thiagocrepaldi** [comment]
Try `torch.onnx.dynamo_export(Module(), torch.zeros((2, 3, 1, 1)))` instead. this is the latest ONNX exporter API that we are working on. It exported on my end

**Comment by thiagocrepaldi** [comment]
Closedas there is no feedback from op

@razzzeeev suggestion makes sense
