### ISSUE TITLE
Wrapping multiple layers in Pytorch FSDP

### ISSUE THREAD

**Issue by halilakin** [pytorch/pytorch#116986]
### 🚀 The feature, motivation and pitch

Is it possible to wrap multiple nn.Modules (e.g., every two Transformer layers) with FSDP API to control communication and memory overlap at a more granular level? 

cc: @awgu 

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @penguinwu @kwen2501

**Comment by awgu** [comment]
Thanks for the issue! This is a good ask. The TL;DR is that we probably cannot support it with existing FSDP, but we may be able to support it in our upcoming FSDP rewrite in the future (https://github.com/pytorch/pytorch/issues/114299).

I will leave another comment with more in-depth discussion on this a bit later. I am finishing up some other work.

**Comment by halilakin** [comment]
Thanks @awgu for the prompt response. Do you have a suggested approach for this? I guess I can wrap my layers in another nn.Module, but it feels very hacky.

I really like the proposal you linked, particularly the support for Zero++ and state_dicts! Super curious if you have time estimates there! I will try leave comments once I have more time to read it.

**Comment by awgu** [comment]
For timeline, we are goaling internally on having the rewrite as a prototype feature by the end of this half (so ~6 months). We should land core components in the next month or two.

I will provide a more formal update on the issue later. The main immediate work items are around: (1) breaking up the implementation into PRs for review/landing, (2) formalizing the design for how to extend FSDP (e.g. fp8 all-gather, QLoRA), and (3) landing custom kernels for fast all-gather copy-out/reduce-scatter copy-in.

**Comment by halilakin** [comment]
Sounds good! Thanks again.

**Comment by awgu** [comment]
Sorry for the delay. Here are some additional thoughts:

One way to address this issue is to allow `FSDP(List[Module])` instead of only `FSDP(Module)`. A concern is how will the user express/configure this.

FSDP offers auto wrapping (`auto_wrap_policy`) as a syntactic sugar for manual wrapping (i.e. directly calling `FSDP` on each module). Auto wrapping applies FSDP using a given predicate (the wrap policy) following a depth-first traversal over the root module.

If we allow for `FSDP(List[Module])`, it is not obvious how:
- Auto wrapping would accommodate this tractably since we need a traversal that, in the most general case, applies the predicate over every combination of modules (one option could be to consider every consecutive `k` modules, where "consecutive" follows `root_module.modules()` order)
- Manual wrapping users would translate from a config file to actually passing in the `List[Module]` to FSDP

Another way to address this is to expose some new API to allow for merging existing FSDP instances. This is also another option but also complicates the API and testing. We should be confident that such an API is necessary if we add this. (Finalizing the FSDP configuration at construction time helps with reasoning about it and debugging, which is one reason that we are not a big fan of rebucketing at runtime.)

**Comment by awgu** [comment]
@halilakin Do you have any preference on whether we allow `FSDP(List[Module])` vs. having a separate API like `FSDP.fuse(*modules)` to fuse already initialized FSDP modules? See https://github.com/pytorch/pytorch/pull/118584 for an example.

I was leaning toward the latter (though it would introduce some more complexity internally to FSDP) because it allows the initial "wrapping" policy to be fixed while the fusing scheme could be tuned. Moreover, the separate API could mainly be targeting expert users without confusing general users as to why FSDP can take in a `List[Module]`.

**Comment by taekyounghan** [comment]
> Another way to address this is to expose some new API to allow for merging existing FSDP instances. This is also another option but also complicates the API and testing. We should be confident that such an API is necessary if we add this. (Finalizing the FSDP configuration at construction time helps with reasoning about it and debugging, which is one reason that we are not a big fan of rebucketing at runtime.)

Hello, Is there any updates?

I would like to wrap multiple `T5Block` with single FSDP unit, but cannot find any solutions..

**Comment by awgu** [comment]
Hi @taekyounghan! We do not have this functionality yet, but I am experimenting with this again.

I am leaning back toward allowing users to pass in a `List[nn.Module]` to FSDP, and we can wrap them together (e.g. your `T5Block`). The draft is in https://github.com/pytorch/pytorch/pull/127786.

**Comment by taekyounghan** [comment]
> Hi @taekyounghan! We do not have this functionality yet, but I am experimenting with this again.
> 
> I am leaning back toward allowing users to pass in a `List[nn.Module]` to FSDP, and we can wrap them together (e.g. your `T5Block`). The draft is in #127786.

I see!, thanks for quick and kind reply.
