### ISSUE TITLE
Distributed DataSampler does not work with old distributed module

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#11709]
We are moving to c10d, but people still have old code and will be reluctant to migrate. I've already found NVIDIA 's `apex` repo not working with c10d (cc @mcarilli ). So it would be good to provide an alternative solution to the data sampler.

cc @teng-li @pietern

**Comment by pietern** [comment]
@SsnL What part of apex doesn't work with it? torch.distributed should be fully backwards compatible and all the existing tests pass on the new implementation.

**Comment by SsnL** [comment]
@pietern They use `dist._backend` :( 
https://github.com/NVIDIA/apex/blob/327b24469236e467ce3a91fac9fea6a3540af56d/apex/parallel/distributed.py#L132

In the mean time, it would be cool to add a public API that gets the backend. Would be quite useful in `env` init method.

**Comment by mcarilli** [comment]
@SsnL Thanks for pointing this out.  If that's the only point of incompatibility, it's quite minor and easily fixed (as you can see, the only purpose is to check if we're using gloo rather than nccl).

Is there a better/blessed way to check which backend is currently in use?  I can't spot any such logic in c10d distributed (although strangely, I do see a place where `torch.cuda.nccl` [is accessed in an apparently unchecked way](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/distributed.py#L349)).

**Comment by SsnL** [comment]
@mcarilli Per @pietern 's comment above, it might be the only incompatibility, but I haven't tested.

> Is there a better/blessed way to check which backend is currently in use?

I'm also curious about that too. Maybe @pietern or @teng-li can tell us more.

> I do see a place where torch.cuda.nccl is accessed in an apparently unchecked way).

That line looks weird to me as well.

**Comment by pietern** [comment]
Unlike the previous version of torch.distributed there may be multiple backends in use at the same time (e.g. cpu side send/recv as well as NCCL), but you will need to work with the groups API to be exposed to that. There is the `get_default_group` function you can use to get the global/default group.

In the light of backwards compatibility I'm re-adding the _backend property, with the caveat that its value will only reflect the type of the process group that is created first through `init_process_group`.

When you're ready to take a hard dependency on the new version of PyTorch, once it is released, then you would change this to use a new `get_backend` function I'm adding now, so that you can take the process group as argument to apex (or default it to equal `get_default_group`).

**Comment by SsnL** [comment]
@pietern I made a PR at #11715  trying to address this. It would be great if you can comment on that. :)

**Comment by pietern** [comment]
ACK, thanks :)

**Comment by SsnL** [comment]
@mcarilli It'd be great of you could try the new master (with #11715 ) with Apex, and let me know if it works. :)

**Comment by mcarilli** [comment]
Thanks for letting me know.  I'll try that today.

**Comment by SsnL** [comment]
@mcarilli The current syntax should work with that! But yes, the recommendation is to use `get_backend` (probably with a `hasattr` check for now) :).

**Comment by mcarilli** [comment]
Understood, thanks very much.
