### ISSUE TITLE
[Feature Request] ModuleDict non-string keys

### ISSUE THREAD

**Issue by davidmascharka** [pytorch/pytorch#11714]
## Issue description

Currently, `ModuleDict` only supports string keys:

``` python
In [1]: import torch

In [2]: torch.nn.ModuleDict({'key': torch.nn.Linear(1, 1)})
Out[2]: 
ModuleDict(
  (key): Linear(in_features=1, out_features=1, bias=True)
)

In [3]: torch.nn.ModuleDict({1: torch.nn.Linear(1, 1)})
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-0f67c1a0790f> in <module>()
----> 1 torch.nn.ModuleDict({1: torch.nn.Linear(1, 1)})

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py in __init__(self, modules)
    221         super(ModuleDict, self).__init__()
    222         if modules is not None:
--> 223             self.update(modules)
    224 
    225     def __getitem__(self, key):

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py in update(self, modules)
    290             else:
    291                 for key, module in sorted(modules.items()):
--> 292                     self[key] = module
    293         else:
    294             for j, m in enumerate(modules):

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py in __setitem__(self, key, module)
    227 
    228     def __setitem__(self, key, module):
--> 229         self.add_module(key, module)
    230 
    231     def __delitem__(self, key):

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in add_module(self, name, module)
    172         elif not isinstance(name, torch._six.string_classes):
    173             raise TypeError("module name should be a string. Got {}".format(
--> 174                 torch.typename(name)))
    175         elif hasattr(self, name) and name not in self._modules:
    176             raise KeyError("attribute '{}' already exists".format(name))

TypeError: module name should be a string. Got int
```

It would be lovely if non-string keys were allowed in `ModuleDict`.

cc @albanD @mruberry

**Comment by zou3519** [comment]
@davidmascharka what is your use case? You can use str(int) to make it into a string.

**Comment by davidmascharka** [comment]
Mainly I'd expect something called `*Dict` to behave like a dictionary. That is, I'd expect any hashable object to work as a key. Calling `str` on my ints (or otherwise formatting them) is what I'm doing now, but avoiding that intermediate step would be nicer.

**Comment by SsnL** [comment]
Here is a problem with generally hashable value: we need to register a string as the key to a submodule for things like saving state dictionary. While many things are hashable, not all of them hash to the same values when the same code is run in a different process. We can extend to allowing a broader set of types, e.g., including `int` and `float`, but it would be hard to allow generally hashable value IMO.

**Comment by davidmascharka** [comment]
@SsnL Python should be able to operate with a deterministic hash; it's possible to set [PYTHONHASHSEED](https://docs.python.org/3.7/using/cmdline.html#envvar-PYTHONHASHSEED) to disable hash randomization. Is there a more subtle issue (beyond dealing with versioning)?

**Comment by SsnL** [comment]
@davidmascharka Two problems with `PYTHONHASHSEED`:
1. We shouldn't touch global python flag (at least not by default) that changes behavior of other user code and other imported libraries.
2. Even if we use `PYTHONHASHSEED`, it only controls `str`, `bytes` and `datetime` objects. Other things like user defined hash functions still can't be controlled.

**Comment by davidmascharka** [comment]
Are user-defined hashes often salted/nondeterministic? I'm curious how big a problem that really is. Which types do we need to worry about having different hashes from run to run?

**Comment by SsnL** [comment]
E.g. tensors hashes to their memory address locations. You asked about
generally hashable values. So I answered in terms of generally hashable
values.

That said, I already mentioned that we can probably relax to a larger set
of types, but even for things like Python byte array it will be hard
because there is no straightforward 1-to-1 correspondence between the
object and a string. So actually I don’t think float qualifies as well. We
can certainly allow int still.

**Comment by randolf-scholz** [comment]
I second this request, having integer indices would be very nice.

**Comment by rpryzant** [comment]
Thirded! Ints and tuples would be nice indeed.

**Comment by ezyang** [comment]
I think this request is considerably more involved than "just" allowing non-string keys in ModuleDict. In particular, we maintain the invariant that every child module has a string name. So if you allow non-string keys in ModuleDict, we now have to either (1) come up with a mapping of non-string keys to strings, or (2) relax Module to allow non-string names. (2) is fairly far reaching and I don't know what the implications one; (1) is difficult because for a general class like ModuleDict, we need to be able to answer questions like "what happens if you have the string key "1" and the integer key 1 at the same time.

It would be pretty easy to write a crappy version of ModuleDict that accepts non-string keys by just stringifying keys on the way in. It wouldn't be "correct" but it would probably be good enough for many use cases.

**Comment by rpryzant** [comment]
That makes sense to me! It seems then like the real issue is the error message, maybe there should be a check in the ModuleDict constructor that tells people to use a string b/c it's going to be used as the module name instead of letting things go to add_module before throwing an exception? 

If so I can make the pr.

**Comment by albanD** [comment]
I will close this as even though it would be easy to write a simple version for specific use case, it will be very hard (as mentioned above) to have a fully featured version without shortcomings.
