### ISSUE TITLE
Factory functions unable to accept FakeTensor as input

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#117288]
### 🐛 Describe the bug

It seems like factory functions like `torch.zeros` and `torch.empty` are unable to accept fake tensors as inputs. It errors with something like: `TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, but found element of type FakeTensor at pos 0`

Repro:
```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode, FakeTensor
from typing import cast

with FakeTensorMode():
    t = cast(FakeTensor, torch.empty([]))
print(torch.zeros(t))
```

### Versions

main

cc @eellison @ezyang

**Comment by eellison** [comment]
This doesn't work without fake tensors:

```
t = torch.empty([])
print(torch.zeros(t))
```

> TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, but found element of type Tensor at pos 0

**Comment by angelayi** [comment]
This works:
```
t = torch.tensor(3)
print(torch.zeros(t))
```

**Comment by ezyang** [comment]
Internal post for xref: https://fb.workplace.com/groups/1075192433118967/permalink/1361525244485683/

**Comment by ezyang** [comment]
It's not altogether clear what the intended semantics of this program are with a fake tensor. In the case that works, we know the actual value inside tensor (3) and so we can produce a tensor of size 3. But if I have fake tensor, I don't actually know what the value inside the tensor is, so how can I generate a output tensor of some unknown size?

That being said, there is a case to be made that this should work under make_fx symbolic tracing, where the intended semantic is you get a i0 size tensor (where i0 is an unbacked SymInt).

**Comment by ezyang** [comment]
This patch "fixes" it but someone had a reason for only allowing it for dynamo and I'm not sure yet.

```
diff --git a/torch/csrc/utils/python_arg_parser.cpp b/torch/csrc/utils/python_arg_parser.cpp
index 9ce373e0356..ca1e4ed0e4f 100644
--- a/torch/csrc/utils/python_arg_parser.cpp
+++ b/torch/csrc/utils/python_arg_parser.cpp
@@ -789,7 +789,7 @@ static bool is_int_or_symint(PyObject* obj) {
   }
 
   // FakeTensor(..., size=()) is qualified for SymInt param
-  if (is_dynamo_compiling && THPVariable_Check(obj)) {
+  if (THPVariable_Check(obj)) {
     auto& var = THPVariable_Unpack(obj);
     if (var.numel() == 1 && var.sizes().empty() &&
         at::isIntegralType(var.dtype().toScalarType(), /*include_bool*/ true)) {
```

**Comment by ezyang** [comment]
So what's going on here, is that there's a special for the tensor case in Dynamo (probably to handle fake tensor when done in https://github.com/pytorch/pytorch/pull/97508) but we actually probably solved it the wrong way in that PR.

We must consider the question: why does it work for regular eager mode? It works for that case because a scalar tensor implements `__index__()` and so the earlier conditional

```
  if (THPUtils_checkIndex(obj)) {
```

will consider the tensor to be an index.

Now, if we try to run index on a fake tensor, we get

```
torch.fx.experimental.symbolic_shapes.GuardOnDataDependentSymNode: It appears that you're trying to get a value out of symbolic int/float whose value is data-dependent (and thus we do not know the true value.)  The expression we were trying to evaluate is i0 (unhinted: i0).  For more information, run with TORCH_LOGS="+dynamic".
```

This is because we don't know what the value of the fake tensor is, so we generated a SymInt, but then we are forced to convert it into an int because that's what `__index__` demands, we can't do it, so we fail.

One way we can solve this problem, is avoid calling `__index__` even in the regular tensor case.
