### ISSUE TITLE
[FSDP] HYBRID_SHARD Apply FULL_SHARD across multiple nodes instead of just intar-node

### ISSUE THREAD

**Issue by OrenLeung** [pytorch/pytorch#117470]
### 🚀 The feature, motivation and pitch

Feature: allow hybrid sharding to full shard across group of multiple nodes then replicate across the groups.
Current State: hybrid sharding only allows full_sharding intar-node
Benefit: decrease inter-node communication volume

`HYBRID_SHARD` is great when you can fit the model inside 1 node, but it currently does not work when you can't fit the model on a single node. then you have to use `FULL_SHARD` across all your nodes.

As a motivating example, let's say you have 8 nodes and the min numbers of nodes that are model can fit in is 4 nodes. It would be beneficial if we can have `HYBRID_SHARD`  apply full sharding within each group of 4 nodes then replicate the parameters between these 2 groups.

In this example, we decrease communication across the network by half. This is amazing when your inter-node comms is limited but you can't fit your model inside 1 node. This would be also beneficially when you have a blocking inter-node network topology

I am happy to contribute this feature

<img width="1007" alt="image" src="https://github.com/pytorch/pytorch/assets/47992694/ec989624-1a1a-464e-8d8a-28dbf121e4f4">

https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.FullyShardedDataParallel
<img width="693" alt="image" src="https://github.com/pytorch/pytorch/assets/47992694/9ca6ed88-9226-4796-8dae-a1bee5c078c7">

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @penguinwu @kwen2501

**Comment by awgu** [comment]
You can do this with `HYBRID_SHARD` today if you pass in the `process_group` argument yourself.

**Comment by taekyounghan** [comment]
> You can do this with `HYBRID_SHARD` today if you pass in the `process_group` argument yourself.

Hello, @awgu 

I'm newbie for FSDP but I'm handling it even more interesting. (Thank's for your dedication)

Can you elaborate about how to pass `process_group` to do like @OrenLeung 's idea? (i.e., Multiple Inter-node Sharding group)  

I have 4 nodes with 2 GPUs. (i.e., total 8 GPUs) and want to make 2 replicate group (Node 0, Node 1) and (Node 2, Node 3).

Then Sharding should be done with (Node0-GPU0, Node0-GPU1, Node1-GPU0, Node1-GPU1) and (Node2-GPU0, Node2-GPU1, Node3-GPU0, Node3-GPU1).

To do so, I'm confused because there's also a parameter named `device_mesh`, should I utilize this or passing specific  `process_group`?

Any comments would be of great help.

Thanks!

**Comment by awgu** [comment]
IIUC, we prefer to use the `device_mesh` argument. cc: @wz337 
```
from torch.distributed.device_mesh import init_device_mesh
device_mesh = init_device_mesh("cuda", (2, 4))
```

**Comment by taekyounghan** [comment]
> IIUC, we prefer to use the `device_mesh` argument. cc: @wz337
> 
> ```
> from torch.distributed.device_mesh import init_device_mesh
> device_mesh = init_device_mesh("cuda", (2, 4))
> ```

Thanks for kind and quick reply!

**Comment by OrenLeung** [comment]
> IIUC, we prefer to use the `device_mesh` argument. cc: @wz337
> 
> ```
> from torch.distributed.device_mesh import init_device_mesh
> device_mesh = init_device_mesh("cuda", (2, 4))
> ```

works! ty
