### ISSUE TITLE
"Check mergeability and dependencies for ghstack prs / pr-dependencies-check / check" fails when stack is based off of merged PR

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#117646]
In https://github.com/pytorch/pytorch/pull/117604, I have a stack of PRs. After merging the bottommost one, the mergeability check fails. The PR is still mergeable though (and this workflow of incrementally merging stacked PRs works and used to work in the past). Can we relax the check? cc @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
cc @izaitsevfb @PaliC

**Comment by izaitsevfb** [comment]
I'm working on fixing this issue.

The problem stems from the way ghstacks are "merged" — instead of actually being merged, the PRs are cherry-picked one by one into `main`. When the stack is partially merged, the bottom of the stack exists in `main` as a set of unrelated commits which conflict with themselves in the base branch of the PR.

**Comment by izaitsevfb** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/118258 and followups.
