### ISSUE TITLE
UNSTABLE Check mergeability and dependencies for ghstack prs / pr-dependencies-check / check

### ISSUE THREAD

**Issue by izaitsevfb** [pytorch/pytorch#117698]
See https://github.com/pytorch/pytorch/issues/117646

Mergeability check is not working correctly for partially merged ghstacks.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
Well, I don't think this issue would work unfortunately because making a job as unstable requires the running of `filter-test-configs` GHA https://github.com/pytorch/pytorch/blob/main/.github/actions/filter-test-configs/action.yml#L130 and that's not part of https://github.com/pytorch/pytorch/blob/main/.github/workflows/check_mergeability_ghstack.yml.

On the other hand, we could add the failure into https://github.com/pytorch/test-infra/blob/generated-stats/stats/flaky-rules.json to explicitly set it as flaky, which achieve the same thing. Let me update that now.

**Comment by huydhn** [comment]
https://github.com/pytorch/test-infra/blob/generated-stats/stats/flaky-rules.json#L54-L57 this should work I think.
