### ISSUE TITLE
User modes don't run necessarily run before user subclasses if user mode returns NotImplemented

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#117900]
If I have multiple user modes [modeA, modeB], and some args [SubclassA], I would expect to dispatch into mode A, mode B, then subclassA, but it is actually possible to make it so that we call into SubclassA's torch dispatch before that of mode B if we make mode A return NotImplemented. 

```python
import torch
from torch.utils._python_dispatch import TorchDispatchMode

class NotImplementedMode(TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        print("NotImplementedMode", func)
        return NotImplemented

class TestMode(TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        print("TestMode", func)
        kwargs = {} if kwargs is None else kwargs
        return func(*args, **kwargs)

class TestTensor(torch.Tensor):
    @staticmethod
    def __new__(cls, elem):
        r = torch.Tensor._make_subclass(cls, elem, elem.requires_grad)
        r.elem = elem
        return r

    @classmethod
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        print("TestTensor", func)
        def unwrap(e):
            if isinstance(e, TestTensor):
                return e.elem
            else:
                return e

        def wrap(t):
            if isinstance(t, torch.Tensor):
                return TestTensor(t, self)
            else:
                return t

        return wrap(func(*tuple(unwrap(a) for a in args), **kwargs))

a = TestTensor(torch.tensor(1.))
with TestMode():
    with NotImplementedMode():
        a.clone()
```

cc @Chillee @ezyang @zou3519 @albanD @samdow

**Comment by samdow** [comment]
At least as of ~a year ago, this was intended behavior. More info in [this long thread](https://github.com/pytorch/pytorch/pull/91521#issuecomment-1371627546) but tl;dr is that NotImplemented is a multiple dispatch thing when deciding ordering in OO. This doesn't really apply to modes because there's a clear ordering

There's probably something to think about of if we should make this behavior clearer or better documented, maybe by implementing one of the purist approaches mentioned in the thread. I'm definitely not certain what, if anything, happened with that

**Comment by ezyang** [comment]
The particular example here it is working exactly as you would hope. Here's the output:

```
NotImplementedMode aten.clone.default
TestTensor aten.clone.default
NotImplementedMode aten.clone.default
Traceback (most recent call last):
  File "/data/users/ezyang/c/pytorch/wu.py", line 42, in <module>
    a.clone()   
  File "/data/users/ezyang/c/pytorch/torch/_tensor.py", line 1412, in __torch_function__
    ret = func(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/wu.py", line 37, in __torch_dispatch__
    return wrap(func(*tuple(unwrap(a) for a in args), **kwargs))
  File "/data/users/ezyang/c/pytorch/torch/_ops.py", line 571, in __call__
    return self_._op(*args, **(kwargs or {}))
TypeError: Multiple dispatch failed for 'torch._ops.aten.clone.default'; all __torch_dispatch__ handlers returned NotImplemented:

  - mode object <__main__.NotImplementedMode object at 0x7f64b7e428c0>

For more information, try re-running with TORCH_LOGS=not_implemented
```

First, NotImplementedMode tries to handle the dispatch. But it doesn't know how to (in a less synthetic example, the NotImplemented would have been returned because it detected a subclass it can't handle). We then attempt to run TestTensor, in case this subclass desugars itself away (it does), and then reapply the mode. In this case, the mode still returns NotImplementedError, so we fail multiple dispatch.

Is there an actual use case you had in mind here where this is undesirable?

**Comment by soulitzer** [comment]
Thanks for the context, this behavior makes sense to me now. I don't have an actual use case where I'd actually require the opposite behavior, I just wasn't sure what the correct behavior to expect when calling `NotImplmented` is. 

(I originally ran into this when I realized that my subclass's torch dispatch still ran before ProxyTensorMode even though ProxyTensorMode did not properly return NotImplemented (this is in the context of singleton ints) and after some investigation I realized that it was because FunctionalTensorMode was above ProxyTensor and that modes returning NotImplemented allowed subclasses to desugar.)
