### ISSUE TITLE
Min Cut Partitioner Issue with float8_experimental

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#117901]
# Summary

Float8_experimental is using a torch.autograd.autograd function to reduce the memory usage. It is doing so by recomputing a casted Float8Tensor during the backwards from the original module weight ( in higher precision).

From looking at TORCH_LOGS="AOT"

We can see that the "casted weight" in this case `permute_2` is being returned  from the forward graph
```Shell
        permute_2: "f8e4m3fn[7168, 8192]" = torch.ops.aten.permute.default(clone, [1, 0]);  clone = None
        permute_3: "f8e4m3fn[8192, 16384]" = torch.ops.aten.permute.default(view, [1, 0]);  view = None
        clone_1: "f8e4m3fn[8192, 16384]" = torch.ops.aten.clone.default(permute_3, memory_format = torch.contiguous_format);  permute_3 = None
        return [getitem, full_default, reciprocal_2, reciprocal_3, permute_2, clone_1]
        
```

while the joint graph:
The input to scaled_mm is the converted weight

@bdhirsh was able to get the correct backward graph by using the "default_partitioner"

PR: https://github.com/pytorch-labs/float8_experimental/pull/186
PyTorch Stack that you need to be based on: https://github.com/pytorch/pytorch/pull/117667
Repro Script: https://gist.github.com/drisspg/30e0864d55d8f431134cf8dc1e4c6e2a

## Update
Brian did more digging and if based on: https://github.com/pytorch/pytorch/pull/117898
And setting: `functorch_config.max_dist_from_bw = 7`
We do get the split we want from the partitioner

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by zou3519** [comment]
@drisspg we're scrubbing old issues, is this still relevant?

**Comment by drisspg** [comment]
This is still relevant but correct me if I am wrong that this might be a very similar issue: https://github.com/pytorch/pytorch/issues/128730

**Comment by bdhirsh** [comment]
Hmm @drisspg i think my claim is that:

(1) this issue is about compile not respecting checkpointing decisions made by custom autograd.Function. From talking to @Chillee it sounds like this is not something we want to fix, and torch.utils.checkpoint is the “blessed” way to signal to the compiler exactly what checkpointing decisions you want to be preserved. So I think we can close this one

(2) https://github.com/pytorch/pytorch/issues/128730 is to track compile (the partitioner) *also* not respecting user-specified selective checkpointing decisions from utils.checkpoint. @yf225 ’s recent partitioner PR should have fixed this, but we should probably confirm our e2e repro by re-running the torch titan job with fp8 + SAC enabled and making sure the memory output looks ok. Have you / anyone else had a chance to try that?
