### ISSUE TITLE
[dynamo][eval frame] frame->f_locals is empty after call_callback

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#118068]
I wanted to add a check in eval_frame.c after the first compilation to check that `cache_entry->check_fn(frame->f_locals)` is True. This validates `check_fn` even for test cases that call opt_fn (torch-compiled result) just once (most tests call it just once).

However, I found that frame->f_locals is empty after we `call_callback` here - https://github.com/pytorch/pytorch/blob/main/torch/csrc/dynamo/eval_frame.c#L1002-L1003

Before diving deeper, I was wondering if anybody knows why thats the case.

cc @ezyang @msaroufim @bdhirsh @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @williamwen42 @jansel

**Comment by anijain2305** [comment]
It seems to be coming from here - https://github.com/pytorch/pytorch/pull/103456/files#r1227487259

cc @voznesenskym Seems like we should revisit this?

**Comment by jansel** [comment]
It should be populated by https://github.com/pytorch/pytorch/blob/5b671ce48650c1769e1daa92a7462ff2b592eab4/torch/csrc/dynamo/eval_frame.c#L951-L954

Maybe rather than calling clear() we should set it to NULL in C so that it gets repopulated if read.

**Comment by ezyang** [comment]
cc @albanD

**Comment by albanD** [comment]
First I would like to prepend this discussion with which version of CPython we're talking about: <=3.12 or 3.11. The f_locals handling changed between the two and so might need separate handling.

> Maybe rather than calling clear() we should set it to NULL in C so that it gets repopulated if read.

I would definitely agree, especially in 3.11: clearing the locals dict in python or f_locals in c++ will have no impact on the local variables saved on the frame IIRC. So I don't think this will achieve what you want.
You would need a LocalToFast call with an empty dict to make sure the fast slots are cleared up if that's what you want to do.

Also in general, you should always call FastToLocals before accessing f_locals otherwise it might be in an inconsistent state if anything changed any local variable since the last call to FastToLocals.

**Comment by anijain2305** [comment]
Thanks for the discussion. I will remove the `f_locals.clear()` from Python and move it to C++. This will also club the creation and deletion of f_locals completely to C++. This PR is trying to do that https://github.com/pytorch/pytorch/pull/118071

**Comment by anijain2305** [comment]
Closing. This is no longer relevant.
