### ISSUE TITLE
Make NPU as a public key in PyTorch.

### ISSUE THREAD

**Issue by huihoaan** [pytorch/pytorch#118268]
### 🚀 The feature, motivation and pitch

`NPU` (Ascend Neural Networks Process Unit, Huawei) have already gained widespread application in the Chinese market, and it is foreseeable that there will be an even larger market in the future.

In past year, with the help of the Pytorch community, we contributed to the completion of the `PrivateUse1-related` code,which allow NPU can work in PyTorch as a plugin. However, through last year’s contributions, we also find that PrivateUse1 is a **public** key, and some of NPU’s logic is not universal for it. Therefore, it is impossible to merge optimizations specific to NPU into the Pytorch as optimizations to PrivateUse1.

Therefore, we hope that NPU can be a public device in torch. We know that `DispatchKeys` are precious. But as we can see that AI market in China will definitely become larger in the future, and more Chinese will use NPU. We hope that users can have a better experience using NPU, and developers can also better contribute NPU-related logic to the community.

**Comment by huihoaan** [comment]
@ezyang  cc

**Comment by dzhulgakov** [comment]
The goal of PrivateUse devices is to enable building fully-featured backends out of tree. You're right that DispatchKeys are precious. So, going forward, we're trying to avoid adding new ones. Instead, one should utilize PrivateUse keys unless the backend is going to get shipped from the official PyTorch distributions (which is not the case here).

> However, through last year’s contributions, we also find that PrivateUse1 is a public key, and some of NPU’s logic is not universal for it. Therefore, it is impossible to merge optimizations specific to NPU into the Pytorch as optimizations to PrivateUse1.

Then, we should add extension points so that backends could introduce their own optimization logic. E.g. like #99808 did for serialization. What are the extension points needed? We'd be happy to add those or review a PR that does so.
