### ISSUE TITLE
DISABLED test_index_put_with_none_index_abi_compatible_cuda (__main__.AOTInductorTestABICompatibleCuda)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#118307]
Platforms: rocm

First known bad: https://hud.pytorch.org/pytorch/pytorch/commit/ee1dbb2acf3f9b304c5f47b919e8de0fe8fee45c
https://github.com/pytorch/pytorch/actions/runs/7654095452/job/20858411754

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_aot_inductor.py%3A%3AAOTInductorTestABICompatibleCuda%3A%3Atest_index_put_with_none_index_abi_compatible_cuda%22%5D)).

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
Looks like test failure was caused by one of these commits:

https://github.com/pytorch/pytorch/commit/5c7a18c5cbfa2cb6e8494f454043f3f522ca085c
https://github.com/pytorch/pytorch/commit/d1e661a1ced100dda18093d81041c402b6c20ae7
https://github.com/pytorch/pytorch/commit/ee1dbb2acf3f9b304c5f47b919e8de0fe8fee45c

CC @desertfire
