### ISSUE TITLE
compiled_autograd should not recompile after optimizer.zero_grad() is called

### ISSUE THREAD

**Issue by fegin** [pytorch/pytorch#118435]
### 🚀 The feature, motivation and pitch

When using `compiled_autograd` with `register_post_accumulate_grad_hook()` and with an optimizer. compiled_autograd will recompile the backward after `optimizer.zero_grad()` is called. See the example below:

```
def compiler_fn(gm):
    def inner(gm_, example_inputs_):
        return inductor.compile(gm_, example_inputs_)
    return torch.compile(gm, fullgraph=True, backend=inner)

def hook(param):
    param.grad *= 2

x = torch.ones(10)
x.requires_grad = True
def run(input):
    return x * input

x.register_post_accumulate_grad_hook(hook)
with compiled_autograd.enable(compiler_fn):
    for i in range(5):
        run(input).sum().backward()
        # Mimic optimizer.zero_grad() to clear the gradient
        print(x.grad)
        x.grad = None
```

For this code snippet, I would expect `compiled_autograd` to compile the backward once but it actually compile the backward 5 times. 

We should change the behavior to avoid recompiling every backward in this case.

If `set_to_none=False` is passed to optimizer.zero_grad(), then the backward will be recompiled once. So totally 2 compilation of the backward will happen. This is still not an ideal case as users may face OOM issue and compiling the backward twice is still time-consuming.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by anijain2305** [comment]
Maybe we should not guard on `x.grad`? @jansel

**Comment by jansel** [comment]
If we want to compile accumulate_grad_, we need to guard on x.grad (since it will result in a different graph).

We could keep accumulate_grad_ as an op, in which case the guard wouldn't be needed.  But this would result in fewer fusions.

**Comment by bdhirsh** [comment]
Just thinking: isn't the guard coming from from the fact that dynamo is inlining the `post_accumulate_grad_hook` (where it inlines `x.grad * 2`)?

I would think that if we are in a post_accumulate_grad hook, then we would know that `accumulate_grad_` will have just finished executing, so we should be guaranteed that `param.grad` is not None inside the hook (and we could add maybe a runtime assertion for it for safety, without having to guard and recompile on it).

**Comment by anijain2305** [comment]
There are a few problems here

First, Dynamo does something hacky [here](https://github.com/pytorch/pytorch/blob/ca55468416ec96d31564304efe7a63bd92892e0b/torch/_dynamo/variables/builtin.py#L1288-L1300) ([PR](https://github.com/pytorch/pytorch/pull/112811)). It artificially constucts an example value of `x.grad` and uses that to symbolically trace rest of the code. However, this leads to a bad TENSOR_MATCH guard by guarding on this artificial value instead of original value in frame.f_locals. This is the reason we see that `check(L["inputs"][2].grad, ..` line in the recompilation above.

I tried separating out the value to trace and value to guard to fix this. But this is not enough. We now have a graph with .. sort of Optional[Tensor] type for grad .. which is not really supported. This is generated inductor code (I hacked/removed the size_asserts because examples_value for arg3_1 was still artificially generated) 

![image](https://github.com/pytorch/pytorch/assets/13822661/a563c10d-fbd7-4ed3-9f67-e4237a054790)

In this example, `arg3_1 = arg2_1.grad`

The above graph does not work for `arg3_1 = None` because `inductor_ops.accumulate_grad` internally mutates `arg2_1 .grad` but there is no connection to `arg3_1` here.


IIUC, we need to somehow functionalize `inductor_ops.accumulate_grad` op here. @jansel let me know if you have any suggestions.

**Comment by jansel** [comment]
Maybe we need to model `x` to `x.grad` relations better when constructing TensorVariables

**Comment by fegin** [comment]
Not sure if it is related, but there is another `accumulate_grad_` and `post_accumulate_grad_hook` issue. https://github.com/pytorch/pytorch/issues/119906

**Comment by ezyang** [comment]
I've discussed this with Voz before he left, and what I told him is that what I expected for grad modeling is for there to be a TensorVariable to TensorVariable relationship between the base variable and the grad, ideally lazily initialized.

**Comment by ezyang** [comment]
see also https://github.com/pytorch/pytorch/issues/119906#issuecomment-1944649073
