### ISSUE TITLE
I don't turn on Dynamo debug logs, "logs go to 1gb"

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119294]
### 🐛 Describe the bug

@flaviotruzzi recently sent me some logs that were missing information I needed. I eventually realized Dynamo debug logs were not on. I asked Flavio why not:

> you mean +dynamo ? I don't have that, logs go to 1gb

Let's do something about this.

### Versions

main

cc @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by tringwald** [comment]
There are many different ways to tackle this. We could:
- Reduce the amount of log messages by de-duplicating repeated messages
- Reduce the length of single log messages. There's a lot of redundant text, e.g. every single line has the date (probably won't change often in normal use cases) and fully qualified package names.
- Stop logging absolute paths
- Stream logs into compressed formats: `TORCH_LOGS=... python test.py 2> >(gzip > logs.gz)` actually yielded a 15x smaller file. Not really a fix, but a workaround for now.
- Remove "spammy" logging calls
- Combine certain logging calls into a single line when they share a common prefix. Instead of `Skipping guard A\nSkipping guard B\n...`, we could have `Skipping guard: A, B, ...`

**Comment by soulitzer** [comment]
> reduce the length of single log messages. There's a lot of redundant text, e.g. every single line has the date (probably won't change often in normal use cases) and fully qualified package names.

There is an env variable that controls the format of the guards, so you can do something like `TORCH_LOGS_FORMAT="%(levelname)s: %(message)s"` to get rid of most of the preeamble. @oulgen added this pretty recently.

**Comment by oulgen** [comment]
Off-topic: Maybe we should make no preamble the default and make like TORCH_LOGS_FORMAT=verbose be the current default

**Comment by ezyang** [comment]
The main problem with disabling the preamble by default is if some random user is running a live training job at Meta, I really do want the preamble.

**Comment by tringwald** [comment]
The preamble wouldn't be much of a problem if we use compression, as it's quite perfectly compressible. If we also combine it with log rotation, we could have an upper bound for disk space. Something like

```
TORCHDYNAMO_LOGS_DIR=./logs TORCHDYNAMO_LOGS_MAXBYTES=100MB TORCHDYNAMO_LOGS_KEEPNUM=3 ...
```

which would log to the given dir and silently rotate + gzip the old logs when they surpass 100 MB.

```
# ./logs dir
torchdynamo.log          at most 100 MB
torchdynamo-1.log.gz     <100MB as it is gzipped
torchdynamo-2.log.gz     <100MB as it is gzipped
```

We would always end up with less than `KEEPNUM x MAXBYTES` of logs. Then we'd just need to have `TORCHDYNAMO_VERBOSE` or `TORCH_LOGS=+dynamo` to imply those flags and log to `/tmp` if not set explicitly.

Might be a bit overengineered though, perhaps streaming to a compressed file is good enough.

**Comment by ezyang** [comment]
obviated by tlparse
