### ISSUE TITLE
aot_export should support user input mutation

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#119330]
```
RuntimeError: 
Found following user inputs located at [0, 2, 3, 5] are mutated. This is currently banned in the aot_export workflow.
If you need this functionality, please file a github issue.
```
Guess I'm filing the GitHub issue 😛. Export has to [work around](https://fburl.com/kv0xgxfz) this atm, would be nice to just support it in `aot_export` proper.

**Comment by suo** [comment]
@bdhirsh any thoughts on if this would be easy/hard?

**Comment by bdhirsh** [comment]
If we're ok with forcing the input to not require grad, I think it shouldn't be too bad. Handling "mutated input that requires grad" is harder, because the model could mutate autograd metadata on the input.

To support mutating inputs that don't require grad, I think the main annoyance is beefing up the `ExportedProgram/GraphSignature` to know about which inputs were mutated (by which outputs): https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/schemas.py#L540

**Comment by bdhirsh** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/119356
