### ISSUE TITLE
gather / scatter dont respect non-contigous out Tensor

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1193]
As @tudor-berariu reports:

```python
import torch
source = torch.rand(1, 3, 3)
# print(source)
idxs = torch.LongTensor(1, 3, 3).random_(0, 2)
# print(idxs)

a = torch.zeros(1, 4, 5)
a[0,:3,2:] = torch.gather(source, 2, idxs)
b = torch.zeros(1, 4, 5)
torch.gather(source, 2, idxs, out=b[0,:3,2:])

print(a)
print(b)
```

```
(0 ,.,.) = 
  0.0000  0.0000  0.3503  0.3527  0.3503
  0.0000  0.0000  0.6724  0.6724  0.1911
  0.0000  0.0000  0.2204  0.2204  0.2204
  0.0000  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 1x4x5]

(0 ,.,.) = 
  0.0000  0.0000  0.3503  0.3527  0.3503
  0.6724  0.6724  0.1911  0.2204  0.2204
  0.2204  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 1x4x5]
```

We need to add the `freeCopyTo` pattern to the two functions in TH and THC

**Comment by tudor-berariu** [comment]
Since the issue mentions just `torch.gather` and `torch.scatter` I'll add here the observation that `torch.index_select` has the same problem.

Code to demonstrate the error:

```
import torch
source = torch.randn(1, 3, 4)
dim = 2
indices = torch.LongTensor([1, 3])

# Selected values are not placed correctly in out location when
# selecting from a 3D tensor
z = torch.zeros(1, 5, 4)
torch.index_select(source, dim, indices, out=z[0, 1:4, 1:3])
print(z)

# But it works fine when selecting from a 2D Tensor
z = torch.zeros(1, 5, 4)
torch.index_select(source[0], dim-1, indices, out=z[0, 1:4, 1:3])
print(z)
```

produces
```
(0 ,.,.) = 
  0.0000  0.0000  0.0000  0.0000
  0.0000 -0.1609 -0.8457  1.1015
 -0.2982 -0.4014 -0.8759  0.0000
  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 1x5x4]

(0 ,.,.) = 
  0.0000  0.0000  0.0000  0.0000
  0.0000 -0.1609 -0.8457  0.0000
  0.0000  1.1015 -0.2982  0.0000
  0.0000 -0.4014 -0.8759  0.0000
  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 1x5x4]
```

**Comment by albanD** [comment]
I think there is a slight problem with how the `out=` interface works.
* What you expect here is that the result of the computation should be placed in the given tensor. You expect it to be equivalent to:
```
t = func(args)
```

* But what is implemented is actually different. It expects a tensor that will be used to store the output. The behavior is actually equivalent to:
```
tmp = func(args)
t.resize_as(tmp)
t.copy_(tmp)
```
Since a `resize` is called on the tensor, you cannot expect the result to be written inplace in whatever Tensor was given. In this case you observe a side effect of the `resize` where you resize a tensor of size (3, 3) to (1, 3, 3) which completely invalidates the storage/stride of the original tensor.


The question is: do we want to change this to implement the first behavior, because you can trigger the same kind of error for many other function (min/max/mean for example)?
This will prevent usage where a buffer tensor (which currently has unknown size and content) as argument for out as this tensor should be resized by the user before giving it to the function's `out` kwarg.

**Comment by zou3519** [comment]
I don't think this is a bug; right now this is expected behavior as @albanD pointed out. The out= semantics can be strange and unintuitive; many users run into it, so we should think about if and how we can retire it.

**Comment by gchanan** [comment]
this is covered by https://github.com/pytorch/pytorch/issues/8989.
