### ISSUE TITLE
torch.nn.MaxPool3d returns junk indices

### ISSUE THREAD

**Issue by alexander-beer-weiss** [pytorch/pytorch#1197]
```MaxPool3d(return_indices=True)``` returns junk indices, both on CPU and GPU.

Here is an example:
```python
pool3d = nn.MaxPool3d(kernel_size=2,stride=2,return_indices=True)
img3d = Variable(torch.rand(1,1,4,4,4))
out, indices = pool3d(img3d)
print(indices)
```
The output looks like this:
```
Variable containing:
(0 ,0 ,0 ,.,.) = 
  4.6117e+18  4.6117e+18
  4.2950e+09  2.3224e+18

(0 ,0 ,1 ,.,.) = 
  4.2950e+09  4.2950e+09
 -8.9845e+18  4.2950e+09
[torch.LongTensor of size 1x1x2x2x2]
```

**Comment by ngimel** [comment]
It's kind of Ok (but not really). Unpooling example from the samples work (http://pytorch.org/docs/nn.html?highlight=maxunpool3d#torch.nn.MaxUnpool3d) even with these seemingly junk indices. 
MaxPooling3d has a very special way of setting indices that is different from MaxPooling2d, where it sets only the lower 4 bytes of an 8-byte long value: 
https://github.com/torch/nn/blob/master/lib/THNN/generic/VolumetricDilatedMaxPooling.c#L188-L191, 
and indices are never properly zeroed, so the upper bytes are initialized to garbage (that's why you have all those e+18 values). So, bottom line, indices as output are Ok for subsequent backprop and for unpooling (because neither of those routines ever read upper 4 bytes), but they are not human-readable.

**Comment by alexander-beer-weiss** [comment]
I see.  It's a bit annoying that 2d and 3d pooling follow completely different indexing conventions.  I actually ran into a problem because I was trying to slice indices from a MaxPool3d layer and feed those sliced indices into a MaxUnpool2d layer.  Of course, now that I understand the structure, I can convert the indices properly; although maybe it's more efficient to just use a MaxUnpool3d layer with a kernel_size=(1,x,x).  I don't think PyTorch currently has bit manipulation operators for Tensors.

I would suggest that the indexing conventions be discussed in the PyTorch documentation (possibly with a note that they are different).  I wasted a lot of time on this, so probably others will as well.  Even better would be if there was one consistent (preferably human-readable) convention for both 2d and 3d.

**Comment by gchanan** [comment]
I also ran into this while implementing double backwards for MaxPooling; 1-d and 2-d are easy because the indices can be fed to a gather, but in the 3-d case they can't be.  Either you have to do bit manipulations or change the 3-d case to be consistent with 1-d/2-d.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/5328#pullrequestreview-102142689
