### ISSUE TITLE
Seemingly equivalent torch.tensor and np.array do not compare equal

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#119965]
For the Torch version on Google Colab (`2.1.0+cu121`), this happens even with plain int/float types:

```python
>>> a = torch.tensor([1, 2])
>>> b = np.array([1, 2])
>>> a == b
False
```

[Colab notebook](https://colab.research.google.com/drive/1b9IlrhI7AF7KnOGwXI9XnYWv6ZJ4CEdN?usp=sharing).

(Edit: The presentation of the bug is a bit different than the original example since we're comparing the whole array, instead of just a single element from it, so we're expecting a boolean array out. This is probably a separate bug, since the code-paths are different, which I infer from the fact that the data-type of the boolean result is different; see the bottom of the notebook.)

_Originally posted by @kcarnold in https://github.com/pytorch/pytorch/issues/43579#issuecomment-1944470315_
            

cc @gchanan @zou3519 @kadeng @mruberry @rgommers @albanD

**Comment by lezcano** [comment]
cc @kurtamohler

**Comment by rgommers** [comment]
I had a quick peek at this. I'm guessing that `__eq__` is special because of Python language rules around evaluating with `is`. NumPy seems to have kinda unusual semantics here, not its normal "call `asarray` on array-like inputs":
```python
>>> a.__eq__(b)
NotImplemented
>>> b.__eq__(a)
NotImplemented

>>> # try with lists: PyTorch behaves as expected, NumPy does special-case lists apparently:
>>> a == [1, 2]
False
>>> b == [1, 2]
array([ True,  True])
>>> a.__eq__([1, 2])
NotImplemented
>>> b.__eq__([1, 2])
array([ True,  True])

>>> # although:
>>> class Custom:
...     def __init__(self, data):
...         self.data = data
...     def __array__(self, dtype=None):
...         return np.asarray(self.data)
... 
>>> b == Custom([1, 2])
array([ True,  True])

>>> class Custom2:
...     def __init__(self, data):
...         self.data = data
...     def __array__(self, dtype=None):
...         return np.asarray(self.data)
...     def __array_wrap__(self, x):
...         return torch.tensor(x)
... 
>>> b == Custom([1, 2])
array([ True,  True])
>>> b == Custom2([1, 2])
DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  b == Custom2([1, 2])
False

>>> class Custom2:
...     def __init__(self, data):
...         self.data = data
...     def __array__(self, dtype=None):
...         return np.asarray(self.data)
...     def __array_wrap__(self, x):
...         return torch.from_numpy(x)
... 
>>> b == Custom2([1, 2])
tensor([True, True])
```

Something like `__array_wrap__` being called too early or the logic in `Tensor.__array_wrap__` creating a hiccup?

**Comment by lezcano** [comment]
a couple minor notes on this one:
- The two arrays in the OP have different dtypes (oops) but the issue still happens when they have the same dtype
- As Ralf mentioned, a == b and b == a both break
- In general, we do not support particularly well mixed PyTorch / NumPy ops, but I guess that this one's so basic that'd be nice to support.

**Comment by kurtamohler** [comment]
I can work on fixing this

**Comment by kurtamohler** [comment]
I'm confused about why `a == b` is different from `a.__eq__(b)`. Can anyone give a brief explanation?

**Comment by kurtamohler** [comment]
Ah I see, this was a piece that I was missing: `==` falls back to `is` if `__eq__` is not implemented for the given arguments.

 So when `a == b` is executed, it ends up calling `THPVariable_eq` because of this:

https://github.com/pytorch/pytorch/blob/b1657beac174811acb03024327b8d6e972e9eca9/tools/autograd/templates/python_variable_methods.cpp#L1212

`THPVariable_eq` throws a TypeError in the case where the second arg is a numpy array, because that case doesn't match any of its signatures. Then this `TypeError_to_NotImplemented_` thing converts that `TypeError` to `NotImplemented`. And then because of that, `a == b` turns into `a is b`, which is clearly False.
