### ISSUE TITLE
[ROCm] ROCm 6.x support in PyTorch stable

### ISSUE THREAD

**Issue by 2eQTu** [pytorch/pytorch#120433]
### 🚀 The feature, motivation and pitch

Based on https://pytorch.org/get-started/locally/ ,  ROCm 6.0 support is only available in the Preview/Nightly builds.

However it would be nice if ROCm 6.x was supported in the stable releases as well.   Clearly there is work ongoing in this direction, but I did not see any obvious bug or feature request to capture this.

As an end user, I'd much prefer to rely on builds from the PyTorch project directly once things are stable and well performing.  In particular for the desktop navi 3x / gfx11 GPU models.

### Alternatives

AMD provided builds.  For example see the docs at:
https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/install-pytorch.html

Which point to whl files such as:
https://repo.radeon.com/rocm/manylinux/rocm-rel-6.0.2/torch-2.1.2+rocm6.0-cp310-cp310-linux_x86_64.whl

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
You've pointed out the alternatives.  Unfortunately the ROCm release cadence doesn't align with the PyTorch release cadence.  We make efforts to upgrade the CI jobs and nightly wheels to the latest available ROCm versions within 1-2 weeks of general availability of the ROCm release.  Those steps are required to occur before PyTorch branches for a release, and preferably some weeks before branching to allow sufficient confidence in the newer ROCm version and tip of tree PyTorch main.  It's not trivial for the PyTorch release management team to put out new versions including patches.  Supporting a new ROCm version is considered a new minor pytorch release version such as 2.3, not something we could do with a bugfix patch such as 2.2.1.  That's why we try to provide the alternatives you've pointed out.

**Comment by hongxiayang** [comment]
It will be available when pytorch 2.3 is released.

**Comment by hongxiayang** [comment]
Closing this issue since pytorch 2.3/ROCm 6.x is available in Stable now.

![Image](https://github.com/pytorch/pytorch/assets/62075498/7bceaf59-3e7f-4752-97d7-2664a4bbb36a)
