### ISSUE TITLE
Matrix autograd for per element

### ISSUE THREAD

**Issue by Lavender912** [pytorch/pytorch#120980]
### 🚀 The feature, motivation and pitch

I want to use pytorch to calculate the derivative of a multidimensional tensor with respect to a scalar, but it seems that pytorch's differentiation mechanism does not support this approach (such as method one), so I had to resort to element by element differentiation (such as method two), but this approach is not efficient. What is the solution
![微信图片_20240301163414](https://github.com/pytorch/pytorch/assets/76023581/562f6f3b-e4bc-46f0-89f6-b0db8b3fc72c)

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
Autograd does allow differentiating functions that have outputs with multiple elements, but you'll need to explicitly specify the grad_output, e.g. something like `torch.autograd.grad(grad_outputs=)` as it is ambiguous to autograd in what direction you would like to compute the gradient. 

Closing this issue as this should be expected behavior.

**Comment by Lavender912** [comment]
> Autograd does allow differentiating functions that have outputs with multiple elements, but you'll need to explicitly specify the grad_output, e.g. something like `torch.autograd.grad(grad_outputs=)` as it is ambiguous to autograd in what direction you would like to compute the gradient.
> 
> Closing this issue as this should be expected behavior.

Ok I see, thank you
