### ISSUE TITLE
[AC] CUDA random seed not restored if input is list of tensors

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#121212]
### 🐛 Describe the bug

# Context

If the user pass as input a nested structure to `checkpoint`, the random state might not be properly restored. This happens because in https://github.com/pytorch/pytorch/blob/8ba49d0e53f8015d9d141bca3d47a0dcf0e92d2a/torch/utils/checkpoint.py#L165-L183
we only iterate over the arguments of the function, and we don't recurse over the nested structure.

### Versions

Present in PyTorch master.

cc @soulitzer

**Comment by soulitzer** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/121462

Initially had two solutions we were considering:
- just get/set random state of all visible devices
- only consider devices found in the inputs to the checkpoint region

From benchmarking, it appears that there is significant overhead to getting/setting random state, and so we are taking the more conservative second approach to avoid unnecessarily get/set state for extra devices.

This also means for the new checkpoint approach where we could potentially begin recompute from intermediary states, naively save random state for each RecomputeTensor could introduce noticeable overhead.

cc @albanD @Chillee @zou3519 @bdhirsh

**Comment by soulitzer** [comment]
Fix has landed
