### ISSUE TITLE
[inline-inbuilt-nn-modules] Compiling lumiere-pytorch results in ~600 recompiles and cache size exceeded

### ISSUE THREAD

**Issue by xmfan** [pytorch/pytorch#121369]
### 🐛 Describe the bug

repro: https://gist.github.com/xmfan/331a4f10fab539e1c1a09127d48312b2 + clone repos
details: https://docs.google.com/document/d/11tYKkaHfMK6khQCl7fqWYOzm_xKsR3BrCX1VvuhTvfs/edit

The user code in lumiere-pytorch (text2video) is doing a lot of dim channel manipulation and reshaping, it would be good to see if there's some gaps in our guarding

### Versions

pytorch nightly
lumiere_pytorch and denoising-diffusion-pytorch from source

cc @ezyang @anijain2305 @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @oulgen @jamesjwu @aorenste @laithsakka @msaroufim @bdhirsh @zou3519

**Comment by anijain2305** [comment]
First reason of over-recompilation can be solved by using `inline_inbuitl_nn_modules` falg.

**Comment by anijain2305** [comment]
Second set of recompiles comes from automatic dynamic not triggering, but the reason is subtle. The function input has a parameter tensor which keeps on changing. Repro is

~~~
import torch

@torch.compile(backend="eager")
def fn(x):
    return torch.cos(x)



torch._dynamo.config.cache_size_limit = 7

x1 = torch.nn.Parameter(torch.rand(32, 16))
x2 = torch.nn.Parameter(torch.rand(8, 4, 3, 3))
x3 = torch.nn.Parameter(torch.rand(8, 8, 3, 3))
x4 = torch.nn.Parameter(torch.rand(8, 32))
x5 = torch.nn.Parameter(torch.rand(16, 8, 1, 1))
x6 = torch.nn.Parameter(torch.rand(16, 16, 3, 3))
x7 = torch.nn.Parameter(torch.rand(16, 32))
x8 = torch.nn.Parameter(torch.rand(32, 16, 1, 1))

fn(x1)
fn(x2)
fn(x3)
fn(x4)
fn(x5)
fn(x6)
fn(x7)
fn(x8)
~~~

If we set `torch._dynamo.config.force_parameter_static_shapes=False`, then the recompiles are way fewer, as automatic dynamic kicks in very quickly.

cc @ezyang if we should change the heuristic. If not, maybe we need to give better error message.

In nutshell, with these two flags, the recompiles are in control

~~~
torch._dynamo.config.inline_inbuilt_nn_modules = True  ## we are hoping this will be turned on by default in few weeks
torch._dynamo.config.force_parameter_static_shapes = False
~~~

**Comment by anijain2305** [comment]
cc @eellison there is an inductor error now. This is the repro file - https://gist.github.com/anijain2305/c270b6a67a1dee51fe951aadd0e08808

You will have to git pull the lumiere-pytorch repo, as instructed in the original post. 

~~~
  File "/data/users/anijain/pytorch2/torch/_inductor/runtime/triton_heuristics.py", line 418, in _precompile_config
    triton.compile(*compile_args, **compile_kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anijain/local/miniconda3/envs/pytorch2/lib/python3.11/site-packages/triton/compiler/compiler.py", line 276, in compile
    module = src.make_ir(options, codegen_fns, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anijain/local/miniconda3/envs/pytorch2/lib/python3.11/site-packages/triton/compiler/compiler.py", line 113, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options, codegen_fns=codegen_fns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
triton.compiler.errors.CompilationError: at 33:50:
    tmp13 = tmp0 >= tmp3
    tmp14 = ks1
    tmp15 = tmp0 < tmp14
    tmp16 = tl.load(in_ptr1 + (x0 + (ks4*ks5*(x1 + ((-1)*ks2))) + (ks4*ks5*ks6*x2)), tmp13 & xmask, eviction_policy='evict_last', other=0.0)
    tmp17 = tmp16 * tmp6
    tmp18 = tl.broadcast_to(libdevice.sqrt(ks6.to(tl.float32)), [XBLOCK])
    tmp19 = tmp18.to(tl.float32)
    tmp20 = tmp17 / tmp19
    tmp21 = tl.full(tmp20.shape, 0.0, tmp20.dtype)
    tmp22 = tl.where(tmp13, tmp20, tmp21)
    tmp23 = tl.where(tmp4, tmp12, tmp22)
    tmp24 = libdevice.sqrt((ks1.to(tl.float64)) / 0.500000000000000.to(tl.float32))
                                                  ^
AttributeError("'constexpr' object has no attribute 'to'")


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
~~~

**Comment by ezyang** [comment]
@anijain2305 I'm willing to try nixing the logic of "if it's a parameter, it's static forever" but I must admit, I'm not entirely sure what the implications of this are. https://github.com/pytorch/pytorch/pull/130870

**Comment by anijain2305** [comment]
This model is enabled now

Couple of fixes/log improvements that have gone in 
1) Graph break fix in lumiere repro - https://github.com/lucidrains/lumiere-pytorch/pull/7
2) Better logging - https://github.com/pytorch/pytorch/pull/131827 and https://github.com/pytorch/pytorch/pull/131825

If you want to repro the results - use this script - [gist.github.com/anijain2305/c270b6a67a1dee51fe951aadd0e08808](https://gist.github.com/anijain2305/c270b6a67a1dee51fe951aadd0e08808)

Results look pretty good

Accuracy - Pass
Compile time - 195 seconds
Speedup - 15.4x

I am seeing fusions.
