### ISSUE TITLE
Profiler traces for python subclasses are missing fwd-bwd links

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#121758]
## TL;DR

When you run the profiler with tensors that require grad (and run both the forward and backward passes), you should get links that connect the forward and backward kernels:

<img width="1131" alt="Screenshot 2024-03-12 at 2 11 12 PM" src="https://github.com/pytorch/pytorch/assets/5067123/66706d3a-4204-4abb-860f-71a21559abab">

But when the tensor is a Nested Tensor (NT) (or, presumably any type of python tensor subclass?), the links don't appear

## Repro
```python
import torch
from torch.nested._internal.nested_tensor import ViewNestedFromBuffer, buffer_from_jagged

# set this to "False" and the test will stop failing
use_nt = True

with torch.profiler.profile() as prof:
    values = torch.randn(4, 6, requires_grad=True)
    offsets = torch.tensor([0,2,4])
    values = values * 2
    l = torch.nn.Linear(6,8)
    if use_nt:
        nt = ViewNestedFromBuffer.apply(values, offsets)
    else:
        nt = values

    nt = l(nt)
    if use_nt:
        val = buffer_from_jagged(nt)
    else:
        val = nt

    loss = val.sum()
    loss.backward()

found_seq_nr = False
for evt in prof.events():
    if "linear" in evt.name and "backward" not in evt.name:
        found_seq_nr = found_seq_nr or evt.sequence_nr != -1

assert found_seq_nr
```

## Reason

**How fwd-bwd links work**: We collect a "sequence number" from the autograd engine that is attached to every autograd-enabled forward kernel; the same sequence number is attached to the corresponding backward kernel. The profiler collects the sequence number for the forward and backward kernel, and then does some post-processing to connect them.

**Why we don't see fwd-bwd links for NT**: 

The record_function added in the dispatcher (which is responsible for adding the profiler events) does not always get called for every dispatch event.

https://github.com/pytorch/pytorch/blob/522d9729247d30cc4e96437023e66a516add4c04/aten/src/ATen/core/dispatch/Dispatcher.cpp#L511-L519

We'll only include the sequence number if we find that the current dispatch key that we're handling is an Autograd key.

*Debugging tip: build with DEBUG=1 and run with TORCH_SHOW_DISPATCH_TRACE=1 to see a list of all the dispatch calls.*

If we look at the `linear` call, we see:

```
 [call] op=[aten::linear], key=[PythonTLSSnapshot]
  [redispatchBoxed] op=[aten::linear], key=[AutogradNestedTensor]
   [redispatch] op=[aten::linear], key=[Python]
    [callBoxed] op=[aten::linear], key=[CPU]
     [call] op=[aten::t], key=[CPU]
      [call] op=[aten::transpose.int], key=[CPU]
       [call] op=[aten::as_strided], key=[CPU]
     [call] op=[aten::addmm], key=[CPU]
      [call] op=[aten::expand], key=[CPU]
       [call] op=[aten::as_strided], key=[CPU]
      [call] op=[aten::copy_], key=[CPU]
      [call] op=[aten::resolve_conj], key=[CPU]
      [call] op=[aten::resolve_conj], key=[CPU]
```

and, when we compare with a debugger, we see that the recordFunction is only called for `[call] op=[aten::linear], key=[PythonTLSSnapshot]` and for `[callBoxed] op=[aten::linear], key=[CPU]`. This checks out; when we see the profiler trace, we only see 2 `linear` calls, not the 4 shown by the dispatch trace debug shown above.

## Solution ideas

**1. Collect more dispatch events**

 i.e. also collect `[redispatch]` and `[redispatchBoxed]`. This is probably somewhat straightforward; now we'll collect all the events including the Autograd events that will have the sequence number attached. *However*, this will probably increase trace sizes globally, which is bad in itself and may have additional effects depending on complexity of downstream processing of traces.

**2. Relax condition for attaching sequence_nr**

Maybe do something like: "if the current dispatch key set contains autograd, then include sequence_nr". Then we'd include sequence_nr for the PythonTLSSnapshot event, even though it is not directly an Autograd dispatch key. *Problem*: we may introduce multiple events with the same sequence_nr; we'll have to check the fwd-bwd postprocessing to see how this will be handled, and in general it would be confusing.

**3. Special handling for PythonTLSSnapshot?**

We seem to be calling PythonTLSSnapshot in this case - maybe we can handle this dispatch key specially?

* redispatchBoxed vs. callBoxed: what's the difference? Can we callBoxed instead of redispatchBoxed?
* Can we assume that if PythonTLSSnapshot is called, then we'll never call Autograd directly internally? If so, can we put the sequence_nr here?
* AutogradNestedTensor handling - is it special?

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @ezyang @msaroufim @albanD

**Comment by soulitzer** [comment]
`call` means you always start from the top of the dispatch keys (while still respecting the included/excluded keys)
`redispatch` means the caller is responsible for telling the dispatcher what the include/exclude keys are so we can avoid an expensive TLS access. My understanding is that we always begin with callBoxed, then kernel implementations use redispatch.
Ordinarily Autograd is the first key dispatched to, and so we get a "call-autograd", and the event gets registered. 

So I think what is going on is in the case where we have subclasses, PythonTLSSnapshot becomes the highest key, so autograd is redispatched to instead of called to. 

I'm not sure we also want to record for PythonTLSSnapshot because that if aten.foo were composite for NestedTensor, we'd record an event for both the aten.foo op and the ops aten.foo decomposes into.

Collecting for both "call-autograd" and "redispatch-autograd" seems to solve this issue, but you mention in the issue descr that this can collect extra unnecessarily events? I feel like I don't understand that part yet.

**Comment by davidberard98** [comment]
> Collecting for both "call-autograd" and "redispatch-autograd" seems to solve this issue, but you mention in the issue descr that this can collect extra unnecessarily events?

the issue is that presumably a lot of kernels are doing redispatch. If we add all the redispatch calls to profiler, it'll significantly increase the number of events (looking at the trace dispatch logs for linear, it seems like we have roughly the same number of redispatches and calls - so it would roughly double the number of events). AFAIK we have limits on storage internally for the traces we collect. It's also annoying for users - both for redundancy, and because larger traces are going to be slower to use in the trace viewer.

It's also possible that by collecting the extra events that we'll skew traces more.

**Comment by soulitzer** [comment]
I see thanks

> another workaround idea is to add special handling for PythonTLSSnapshot (or whatever dispatch key we expect to see at the top for python subclasses) so that we peek at the other dispatch keys and decide whether this will eventually get to Autograd. Is this reasonable?

This sounds reasonable to me. Though I wonder if we run into the same issue if any other key gets executed above autograd. If the first key were PreDispatch, it might not actually be possible to predict whether we get to autograd with just the keyset, since functorch can modify what is in the include/exclude set.

>  we may introduce multiple events with the same sequence_nr

It looks this is already what is happening with composite ops today. Let's say you had a linear that decomposed into t and some other ops. Both linear and t have the same seq nr. I'm not sure if/how it is being handled today, but if we go with the also possibly add seq nr for PythonTLSSnapshot solution, it doesn't seem to make this situation worse at least.

**Comment by soulitzer** [comment]
Discussed this a little with @albanD offline and an argument in favor of proposal 2 is that it seems possible to make certain assumptions about how callBoxed/redispatchBoxed so that at that point where you do callBoxed you should be able to predict that autograd will definitely not be reached.

The idea is that we want to maintain the invariant that - if at the current point in time, the dispatch resolution does not contain autograd, the current callBoxed-redispatchBoxed sequence will definitely not reach autograd because if somewhere down the redispatch, a kernel for a particular key updated TLS so that the dispatch resolution DOES now contain autograd, that key is also responsible for calling callBoxed.

This means that it is sufficient to only record seq nr when dispatch resolution contains autograd. What this might allow one to do is during post-processing, as long as events are sorted, the record that should be linked with bw via seq nr is the last record for that given seq nr.
