### ISSUE TITLE
`merge -i` does not seem to work sometimes

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#122422]
### 🐛 Describe the bug

I've issued `merge -i` and bot promised to ignore MacOS failure, per
https://github.com/pytorch/pytorch/pull/122000#issuecomment-2013172399

But then decided not to, see

https://github.com/pytorch/pytorch/pull/122000#issuecomment-2013192649

### Versions

CI

cc @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by huydhn** [comment]
At first glance, the failure looks a bit weird as its name is `.github/workflows/trunk.yml / macos-12-py3-arm64 / test (default, 1, 3, macos-m1-stable)` instead of the usual `trunk / macos-12-py3-arm64 / test (default, 1, 3, macos-m1-stable)`.  It could be a hint here, but I need to take a closer look.

**Comment by clee2000** [comment]
Probably due to the changes in add_conclusion in https://github.com/pytorch/pytorch/issues/92097
