### ISSUE TITLE
add `torch.distributed.get_local_rank`

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#122816]
### 🚀 The feature, motivation and pitch

For a symmetry with `torch.distributed.get_global_rank` it would be useful to add `torch.distributed.get_local_rank` rather than have the user fish for it in the `LOCAL_RANK` env var. This feature is almost always used in dist applications.

Discussion: https://pytorch.slack.com/archives/C3PDTEV8E/p1711155684960319

In it you can see a proposal for creating a default local process group to match the `group` argument in the existing similar APIs.

Thank you.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

**Comment by kwen2501** [comment]
Hi Stas, would this API be a symmetric candidate?
```
def get_group_rank(group: ProcessGroup, global_rank: int) -> int:
```
Document is available [here](https://pytorch.org/docs/stable/distributed.html#torch.distributed.get_group_rank).

**Comment by stas00** [comment]
Thank you for the suggestion, Ken - but the onus of figuring out the `group` is then on the user, no? reading `os.environ["LOCAL_RANK"]` is much easier then - the point is to make things easier for the user, not more complicated.

**Comment by kwen2501** [comment]
True. Here are my naive thoughts:

Wrt `torch.distributed` (if viewed standalone instead of in combination with `TorchRun`): 
- If there is no _group_, there is no _rank_. 
- torch.distributed so far does not have a concept of _local_. That's why it doesn't have an API related to it.

Wrt `"LOCAL_RANK"`:
It is a contract between the user and the launching environment:
- SLURM can set it or not set it (needs user's explicit implementation in the launching script). 
- TorchRun sets it for convenience.

Thus, it seems to me that `os.environ` is indeed a suitable level to query such contract. In the SLURM case, there isn't any contract between torch.distributed and SLURM, so torch.distributed wouldn't know the env is named "LOCAL_RANK" or "local_rank", etc.

Now, a fair ask is whether `TorchRun` would provide an API for its user to query `LOCAL_RANK` in the processes it launches. I'd like to invite @kurman to comment here. Btw, does TorchRun have any API today?

**Comment by stas00** [comment]
Thank you for clarifying that `torch.dist` has no notion of local_rank, Ke.

But if you look at any framework: deepspeed, accelerate, lightning - they all use the concept of local_rank - so perhaps it can just be a helper method and add the contract that the method only works if the launcher sets it?

In the case of SLURM the user has to set it explicitly only if they choose to use `srun` as the end point instead of the launchers. Here is an [example](https://github.com/stas00/ml-engineering/blob/c561894508efd61045f669634b50aa75e1e55e22/orchestration/slurm/launchers/srun-launcher.slurm#L73)

**Comment by obilaniu** [comment]
If `torch.distributed.init_process_group()` were called with kwargs `local_rank` and `local_size`, or the env contained `LOCAL_RANK` or `LOCAL_SIZE`, then could PyTorch automatically create such a node-local group?

---

Re: SLURM: Using `srun` with SLURM is good practice, it has many features that no launcher could easily reproduce like locking tasks to their individual GPUs, setting the appropriate CPU affinities, etc. However, its contract with the programs it runs is to set various `SLURM_*` envvars, notably `SLURM_NPROCS`, `SLURM_PROCID`, `SLURM_LOCALID` and `SLURM_NODEID`.

But that does put SLURM users in a difficult position re: distributed launches.

---

To that end, I will reveal that I have written the theoretical solution for SLURM-PyTorch compatibility: [An all-new `mpi/torchrun` plugin for SLURM](https://github.com/obilaniu/slurm/tree/mpi-plugin-autoconfed). I have never tested nor run this code at all, nor offered it upstream (because I haven't tested it yet), and I wrote it on the employer's dime. I do wish for it to be upstreamed, however. If SchedMD would like to contact the Mila-IQIA or me, I welcome it.

If you're adventuresome and try compiling this plugin (@stas00?), and the code does what it is supposed to, then

```bash
srun --mpi=torchrun python main.py
```

should [set the required PyTorch rank-variables](https://github.com/obilaniu/slurm/blob/4da92dee8fccb8bc10c457c937a2139449b5f234/src/plugins/mpi/torchrun/mpi_torchrun.c#L97-L149) appropriately in each instance of the distributed Python program, in a like manner to the real `torchrun`, without ugly delayed-evaluation shell-script wrappers.

I welcome reports of success with that plugin, particularly whether the nasty attempt at securing a `MASTER_PORT` number actually works.

**Comment by kurman** [comment]
Just to clarify based on discussion in slack and here: the proposal is not about new rank specific API but rather creating local group by default to help with a topology discovery, correct? And if so, what would be the expected UX?

**Comment by stas00** [comment]
@obilaniu, I have been gradually working through getting the popular launchers to support the performance features like numa affinities, started with cpu affinity:
1. https://github.com/huggingface/accelerate/issues/2241
2. https://github.com/pytorch/pytorch/issues/115305
and I'm documenting the current state and know-how [here](https://github.com/stas00/ml-engineering/tree/master/training/performance#numa-affinity)

I believe that having the launchers support all these features is much easier on the users than getting them to read the orchestration manuals.

very cool work on the SLURM plugin, Olexa! perhaps it'd work better to get your work merged into SLURM if it came from the PyTorch org, i.e. perhaps start another thread and find internal collaborators? Just an idea!

**Comment by stas00** [comment]
> Just to clarify based on discussion in slack and here: the proposal is not about new rank specific API but rather creating local group by default to help with a topology discovery, correct? And if so, what would be the expected UX?

The idea came to why the user can get the global rank by just calling `get_global_rank` but there is no equivalent of `get_local_rank` - surely torch.dist can know which gpu belongs to which machine rank and can devise that from say hostname. 

As I'm writing this I'm thinking why do we even need `LOCAL_RANK` env var? If it can be derived from the topology of the `world_size/nproc_per_node` since the global rank is known.

**Comment by kurman** [comment]
> As I'm writing this I'm thinking why do we even need the `LOCAL_RANK` env var If it can be derived from the topology of the `world_size/nproc_per_node` since the global rank is known.

That makes sense but won't work in a heterogeneous layout. This is most likely mirroring MPI env variables as well: https://www.open-mpi.org//faq/?category=running#mpi-environmental-variables


> I realize that probably a lot of this logic lives in torchrun but is there any reason why torch.dist.init_process_group couldn't derive many of those things automatically?

- torchrun does fair bit of node discovery, support for elastic topology and host process management (MP) so it makes sense for torchrun to manage those env variables. 
- [`torch.dist.init_process_group`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group) supports non `env` based init_method as other mechanisms to setup the ranks.

**Comment by stas00** [comment]
OK, so I hear that my proposal doesn't quite fit the reality of `torch.dist` - as Ke said it doesn't have a notion of local rank, because it doesn't have a use for it, even though every framework I know extends it to add the notion of local rank. 

If there are no other suggestions let's close it then?

**Comment by wanchaol** [comment]
@stas00 if you use DeviceMesh ([tutorial](https://pytorch.org/tutorials/recipes/distributed_device_mesh.html)) instead of ProcessGroup, DeviceMesh offers a `get_local_rank` API that might fit your need: https://github.com/pytorch/pytorch/blob/main/torch/distributed/device_mesh.py#L444

**Comment by stas00** [comment]
That's a very cool new API, Wanchao. But it's only useful if one already uses a 3D parallelism or HSDP. So it's not a generic solution and it's more complicated than looking up a LOCAL_RANK env var.

**Comment by wanchaol** [comment]
> That's a very cool new API, Wanchao. But it's only useful if one already uses a 3D parallelism or HSDP. So it's not a generic solution and it's more complicated than looking up a LOCAL_RANK env var.

Oh yes its more useful in 2D/3D parallelism cases, a 1D device mesh would resolve to the process group case, which I agree it's way simpler to just look at env-vars from torchrun

**Comment by wconstab** [comment]
i'm sympathetic to this proposal, people actually do use stuff like this in pytorch scripts
`torch.device(f"cuda:{int(os.environ['LOCAL_RANK'])}")`

so it follows that making this easier is good.  I think we need to define it carefully though, because it does clash a bit with the 'local rank' concept relative to an established process group/devicemesh.

ideally, it feels like it would have been better if we named the device_mesh api `get_group_rank` instead of `get_local_rank` , because when the group in question represents something like pipeline parallelism which is cross-host, the 'group rank' really is not local!

can we rename that @wanchaol or is it too late?

if we were to define a new api for 'local_rank' that is not relative to a group, how would we define it?  would it have any semantics at all, or would we just define it as "a convenience for accessing LOCAL_RANK"?

**Comment by wanchaol** [comment]
> I think we need to define it carefully though, because it does clash a bit with the 'local rank' concept relative to an established process group/devicemesh.

My view on this naming is a bit different. I think `group_rank` might not be a proper name, at least when I first use distributed I feel confused about what's a "group rank", when we have a global rank already and user might create as many groups as they want in regardless of whether it's multi-dimensional or no, i.e. "group_rank" can also mean that this is the idx of the groups that I created, but what user really want is the "local" id "within" that group. A natural correspondance of "global" is actually "local", where the local rank here means it's the rank that is local to this "group" instead of a global rank.

If we want it to be super clear maybe it should be called as "get_group_local_rank"

**Comment by stas00** [comment]
to avoid the confusion, I think it should be called `get_local_to_node_rank` or `get_node_local_rank` or something similar - then it's unambiguous and obvious that it's not related to any group, other than perhaps an implied per node group?

I think `LOCAL_RANK` is an ambiguous name to start with, but we are just so used to know what it means it's unambiguous to old timers. So perhaps `LOCAL_TO_NODE_RANK` or `NODE_LOCAL_RANK`?

Probably the same with just `RANK` naming - we are used to what it is supposed to imply, but really it should be called `JOB_GLOBAL_RANK`?

**Comment by vadimkantorov** [comment]
Some nit: maybe now it's too late to impact the conventions, but it is nice if all TORCH-introduced env vars could be started with TORCH_ prefix (or at least supported this variant), then it's a tad easier to work with shell scripts to immediately understand what is related to torch

**Comment by stas00** [comment]
I concur. 

It's never late to do the renaming but would require a lot of backward compat code - which perhaps could be reduced to a single file which would automatically remap any previously known env vars to the new ones when `torch` is imported. So perhaps it will be quite a simple change as the back-compat layer can be fully automated.

You'd probably want to start a new Issue for that for it to have any chance of being implemented, Vadim.
