### ISSUE TITLE
compile creates FakeTensors with dynamic shapes even when dynamic=False when inputs are views

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#123298]
Example:

```
import torch
from torch.testing._internal.two_tensor import TwoTensor


@torch.compile(backend="aot_eager", dynamic=False)
def f(x):
    if x.shape[0] > 5:
        return x + 1
    else:
        return x + 2


x_inner = torch.ones(4)
x = TwoTensor(x_inner, x_inner)
x_view = x.view(2, 2)
out = f(x_view)
```

Running with `TORCH_LOGS="+dynamic"`, you can see a lot of symint compute going on. If you put a breakpoint [here](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L1278), the returned FakeTensor has SymInts for its sizes, even though we compiled with `dynamic=False`

cc @eellison

**Comment by jbschlosser** [comment]
I'm surprised to see this behavior because I thought we had logic to handle this:
https://github.com/pytorch/pytorch/blob/98e5238ad8b23d62f52549c88ee39f7cbacb46d8/torch/_subclasses/meta_utils.py#L851-L856

Looks like it doesn't quite work though due to the use of `sym_eq()` there? I think what we want there is to go through each element of the returned fake tensor size / stride / storage offset and ensure comparison against each element of the outer sizes / strides / storage offset.
