### ISSUE TITLE
DISABLED test_buffer_mutation_3_abi_compatible_cuda (__main__.AOTInductorTestABICompatibleCuda)

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#123251]
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22inductor%2Ftest_aot_inductor.py%3A%3AAOTInductorTestABICompatibleCuda%3A%3Atest_buffer_mutation_3_abi_compatible_cuda%22%5D)).

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @desertfire @chenyang78

**Comment by atalman** [comment]
Caused by: https://github.com/pytorch/pytorch/pull/123164/
Re-enable once this is resolved

**Comment by jithunnair-amd** [comment]
@atalman This might not be the only unit test introduced by that PR and failing for ROCm. I just cc'ed you on a comment I posted on that PR: https://github.com/pytorch/pytorch/pull/123164#issuecomment-2033494012 to see how we can mitigate this in the future, since AOTI feature seems to be in heavy development.

**Comment by shunting314** [comment]
cc @desertfire

**Comment by anijain2305** [comment]
Test is flaky, reopening.
