### ISSUE TITLE
In Torch 2.1.0, when I use torch.compile, it will use asynccompile.warm_pool () to create many sub -processes, why it is not recycled until the program stops.

### ISSUE THREAD

**Issue by zte-tcb** [pytorch/pytorch#123329]
### 🐛 Describe the bug

I think that after the first round, the compilation is completed, and these sub -processes can be recycled.  If I want to terminate these processes, whether these processes can be terminated after the first round of training.

### Versions

Torch 2.1.0

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by shunting314** [comment]
Hey, it's because inductor does not know if there will be more triton kernels that need to be compiled. It can either due to recompilation or due to multiple torch.compile calls 

If you are sure that no more compilation will happen your code, you can call `torch._inductor.codecache.shutdown_compile_workers` to shutdown the pools explicitly. 

Alternatively, you could also set torch._inductor.config.compile_threads to 1 which will not create the thread/process pool for parallel compilation.

**Comment by zte-tcb** [comment]
thanks. I get it.
