### ISSUE TITLE
Multiplying large matrices returns 0 matrix when matrices are in mps

### ISSUE THREAD

**Issue by jmacedoit** [pytorch/pytorch#123716]
### 🐛 Describe the bug

Multiplying large matrices returns a zeroes matrix when matrices are in mps.

Example:

```
>>> import torch
>>> a = torch.eye(1000, device="mps")
>>> b = torch.eye(1000, device="mps")
>>> a @ b
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], device='mps:0')
>>> c = torch.eye(32000, device="mps")
>>> d = torch.eye(32000, device="mps")
>>> c @ d
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='mps:0')
 ```

### Versions

```
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.0
Libc version: N/A

Python version: 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.16.0
[pip3] onnxruntime==1.15.1
[pip3] torch==2.2.2
[pip3] torchvision==0.17.2
[pip3] tritonclient==2.36.0
[conda] Could not collect
```

Reproducible on two machines:
```
Apple M2
16GB Memory
macOS Sonoma 14.4.1
```

and:

```
Apple M1 (13 inch, 2020)
16Gb Memory
macOS Monterey 12.4
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by kulinseth** [comment]
We are not able to reproduce this issue:
```
>>> 
>>> a = torch.eye(1000, device="mps")
>>> b = torch.eye(1000, device="mps")
>>> a @ b
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], device='mps:0')
>>> c = torch.eye(32000, device="mps")
>>> d = torch.eye(32000, device="mps")
>>> c @ d
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], device='mps:0')
>>> 
```

And the Torch version was 2.2. Can you tell us which machine you are running this on ?

**Comment by jmacedoit** [comment]
@kulinseth
I can reproduce it on two distinct machines:

```
Apple M2
16GB Memory
macOS Sonoma 14.4.1
```

and:

```
Apple M1 (13 inch, 2020)
16Gb Memory
macOS Monterey 12.4
```

If this is a memory related issue, maybe you can try it with an even larger matrix?

**Comment by jmacedoit** [comment]
@kulinseth Have you managed to reproduce the issue?

**Comment by jhavukainen** [comment]
Hi @jmacedoit! We have the issue reproducing and we know where the issue is coming from. To summarize the current status:

- The root issue is coming lower down the stack from Metal where allocating a buffer that exceeds a specific fraction of the system memory errors out due to a safety check in Metal drivers IIUC. On an 8GB machine with 32Kx32K matmul this gives an error of type

`-[_MTLCommandBuffer didCompleteWithStartTime:endTime:error:], line 1080: error 'Execution of the command buffer was aborted due to an error during execution. Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)`

- Unfortunately this seems to be a silent error out on the driver side and the caller is just getting back a zero initialized buffer that ends up being the zero filled matrix we see in the output.
- We are currently discussing this with the driver team to get a better understanding on what is the best long term approach here but in the meanwhile we will be addressing this issue by adding an assert on pytorch level where we detect if the requested buffer size ends up exceeding this watermark and let the user know. I'm hoping to get that PR going today.

**Comment by kulinseth** [comment]
Thanks @jhavukainen . This is the link:
https://developer.apple.com/documentation/metal/mtldevice/2369280-recommendedmaxworkingsetsize?language=objc

**Comment by jmacedoit** [comment]
@jhavukainen @kulinseth Great job finding the issue. Thank you for the dedication!
