### ISSUE TITLE
quant tests green on OSS CI but red internally

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#123865]
In two days @DanilBaibak saw 2 diffs ([D55961000](https://www.internalfb.com/intern/diff/D55961000/) #122387, [D56012480](https://www.internalfb.com/intern/diff/D56012480/) #122776) with the same issue - the authors added the tests, OSS CI is green, but internally tests failed. Do we run the quantization tests properly on the OSS side?  What is the cause of this discrepancy?  

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @supriyar @andrewor14

**Comment by jerryzh168** [comment]
yeah this is weird, I'm asking @leslie-fang-intel to take look since all the test failures are from x86 inductor backend tests

**Comment by leslie-fang-intel** [comment]
@clee2000 I am not able to access the link of ([D55961000](https://www.internalfb.com/intern/diff/D55961000/), [D56012480](https://www.internalfb.com/intern/diff/D56012480/)). Could you help to post the failure message?

**Comment by leslie-fang-intel** [comment]
Hi @jerryzh168 @clee2000 @DanilBaibak,

- I have created a dummy test PR: https://github.com/pytorch/pytorch/pull/123923 which should intentionally fail with running command `python -u -m pytest -s -v test/quantization/pt2e/test_x86inductor_quantizer.py -k test_attention_block`. Let's see whether OSS preCI will run and capture the failure in that PR.
- Regarding to the internal failure in https://github.com/pytorch/pytorch/pull/122776, I suspect it may due to that I didn't write the checker in UT `test_attention_block` well which causes the random failures among different systems.
  - From the failure message @DanilBaibak posted here https://github.com/pytorch/pytorch/pull/122776#issuecomment-2051082366. The graph after convert in internal preCI has all the `quantized_decomposed.dequantize_per_channel` nodes before the `quantized_decomposed.quantize_per_tensor`. 
  - However, in the UT I added, I intentionally check the node_list order as `quantized_decomposed.dequantize_per_channel` after `quantized_decomposed.quantize_per_tensor`. However, actually, the only hard request for `quantized_decomposed.dequantize_per_channel` is before the linear node. So `quantized_decomposed.dequantize_per_channel`  can be before or after the `quantized_decomposed.quantize_per_tensor` decided by the system.
  - Reviewed the code in `fx.graph.py`, I didn't find the exactly rule to decide whether `quantized_decomposed.dequantize_per_channel` should be before or after `quantized_decomposed.quantize_per_tensor`. I think maybe I should delete `quantized_decomposed.dequantize_per_channel` from node_list since its order is ambiguity.

**Comment by clee2000** [comment]
> @clee2000 I am not able to access the link of ([D55961000](https://www.internalfb.com/intern/diff/D55961000/), [D56012480](https://www.internalfb.com/intern/diff/D56012480/)). Could you help to post the failure message?

Looks like you've already found the second one, the first one is https://github.com/pytorch/pytorch/pull/122387#issuecomment-2048329855

**Comment by leslie-fang-intel** [comment]
> Do we run the quantization tests properly on the OSS side?

I've created a test PR: https://github.com/pytorch/pytorch/pull/123923 designed to intentionally fail when running the command `python -u -m pytest -s -v test/quantization/pt2e/test_x86inductor_quantizer.py -k test_attention_block`. From the test result, we find the OSS preCI has run the test and captured the expected failure.

> What is the cause of this discrepancy?

- For [D56012480](https://www.internalfb.com/intern/diff/D56012480/) https://github.com/pytorch/pytorch/pull/122776, I suspect that's due to reason mentioned in https://github.com/pytorch/pytorch/issues/123865#issuecomment-2051264703 which will fail the test randomly. I have modify the test case to avoid the random failure. Could you kindly help to import the https://github.com/pytorch/pytorch/pull/122776 and checking if it can pass the internal CI.
- For [D55961000](https://www.internalfb.com/intern/diff/D55961000/) https://github.com/pytorch/pytorch/pull/122387, the failing reason @DanilBaibak posted in https://github.com/pytorch/pytorch/pull/122387#issuecomment-2048329855 is a different cause which wants to check `aten.add_` node but found `aten.add` node in the graph. @Xia-Weiwen Could please help to further investigate the  discrepancy between OSS CI and internal CI for this failure?

**Comment by leslie-fang-intel** [comment]
Close this issue as verified.
