### ISSUE TITLE
device_mesh / fsdp issue with _get_device_handle

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#124327]
In our FSDP2 code, we expect `device_handle.current_device()` to work as part of `_get_device_from_mesh`.

However, depending on how we initialize our device-mesh, it does or doesn't work.

This snippet makes FSDP happy (assuming we pass `device_mesh` to FSDP).
```
device = f'cuda:{rank}'
torch.cuda.set_device(device)
device_mesh = init_device_mesh(
    "cuda", mesh_shape=mesh_shape, mesh_dim_names=mesh_dim_names
)
```

But this snippet fails:
```
  device = f'cuda:{rank}'
  device_mesh = init_device_mesh(
      device, mesh_shape=mesh_shape, mesh_dim_names=mesh_dim_names
  )
```

```
#   File "/data/users/whc/pytorch/torch/distributed/_composable/fsdp/_fsdp_init.py",
#   line 69, in _get_device_from_mesh
#              return torch.device(mesh.device_type, device_handle.current_device())
#   AttributeError: 'NoneType' object has no attribute 'current_device'
device_mesh = init_device_mesh(
    "cuda", mesh_shape=mesh_shape, mesh_dim_names=mesh_dim_names
)
```

**Comment by awgu** [comment]
The surface issue is that `init_device_mesh` should take in something like `"cuda"` as the 1st `device_type` arg, so passing `"cuda:0"` for example breaks the code. The `_get_device_handle()` helper just calls `getattr(torch, device_type, None)`, so it wants something like `getattr(torch, "cuda", None)` so that it can return `torch.cuda`.

Either we should add some sanitization logic to strip the `:0` from `cuda:0` or clarify what the accepted values are for `device_type`.

**Comment by shink** [comment]
let me fix this
