### ISSUE TITLE
FlexAttention isn't using decompositions

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#124643]
### 🚀 The feature, motivation and pitch

We don't trace with any decompositions today (https://github.com/pytorch/pytorch/blob/main/torch/_higher_order_ops/templated_attention.py#L125).

This can cause errors in the case that we use a pointwise op that's actually decomposed (e.g. `q // kv`).

cc: @ydwu4 who was looking at how this should be done properly.

### Alternatives

N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @SherlockNoMad

**Comment by bdhirsh** [comment]
Since we stash the current decomposition table in a global while tracing [here](https://github.com/pytorch/pytorch/blob/main/torch/fx/experimental/proxy_tensor.py#L58), would it be reasonable for all HOP's that use `make_fx` on their inner subgraphs to poke at the global if it's available?

I guess a minor downside is that this is easy to get (silently) wrong without some auditing.

**Comment by ydwu4** [comment]
A related issue: https://github.com/pytorch/pytorch/pull/122972. I'll work on it asap.
