### ISSUE TITLE
Pytorch Conda nightly build failures due to timeout

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#124667]
### 🐛 Describe the bug

For the past week we started seeing the build failure due to timeout:
HUD: https://hud2.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=linux-binary-conda

Failure: https://github.com/pytorch/pytorch/actions/runs/8780240438/job/24098371529#step:17:239

```
Uploaded /home/ec2-user/actions-runner/_work/_temp/artifacts/pytorch-2.4.0.dev20240422-py3.11_cuda11.8_cudnn8.7.0_0.tar.bz2 (88.1%) bytes 1484783616:1493172223
Error: The operation was canceled.
```

To Fix we would like to investigate why conda builds take more then 3 hours to build.

Mitigation applied to Release: https://github.com/pytorch/pytorch/commit/94d6463255211bdd397e4eab6ad0cddedc922fea

### Versions

2.4.0 nightly

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
High priority to investigate and report what have caused build time increases and just for posterity report on the issue what are they right now

**Comment by ZainRizvi** [comment]
Build step went from ~30 minutes -> ~2 hrs 30 mins. That's a huge jump

**Comment by ZainRizvi** [comment]
Looking at historical builds, while CPU builds have been pretty fast (30 mins) CUDA builds have been slow (at least going back to Jan 26th).  Those runs completed just a few minutes shy of the 3hr timeout. The build step is about 2hrs 40 minutes of that time
https://github.com/pytorch/pytorch/actions/runs/7665217432/job/20890726800

For comparison, cuda CPU builds take just 30 mins

Whatever has been happening here has been going on for a long time, and we've just slowly grown past 5 mins of buffer that we had.

For an immediate mitigation @atalman you'll want to increase the job timeout, since the fundamentals haven't changed in a while. But we should explore why CUDA builds take 5x longer than CPU

**Comment by atalman** [comment]
hi @ZainRizvi the assessment is correct we have been experiencing slight increase in build time over past few month, mitigation is applied here : https://github.com/pytorch/pytorch/pull/124668 . Will be looking at why build time for conda is almost 2x of wheel build time for wheels

**Comment by atalman** [comment]
09.14: https://github.com/pytorch/pytorch/actions/runs/6182352148 - Build,Test,Upload time 2.05Hrs
09.22: https://github.com/pytorch/pytorch/actions/runs/6271454280 - 2:20
10.07: https://github.com/pytorch/pytorch/actions/runs/6439845854 - 2:37
11.09: https://github.com/pytorch/pytorch/actions/runs/6808730699 - 3:29

**Comment by clee2000** [comment]
@atalman Did this get root caused?
