### ISSUE TITLE
UNSTABLE rocm

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#124951]
There is more than 4 hours queuing on linux.rocm.gpu.2 machines, and there are failures on what managed to finish.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by huydhn** [comment]
This is not supported atm, not due to any technical difficulties, but out of a concern about disabling too many thing, i.e. `UNSTABLE trunk`.  Let's cut an issue on test-infra, so this can be implemented if we think this is an useful feature to have, for example, as a middle ground we might limit it only to ROCm.

**Comment by kit1980** [comment]
> This is not supported atm

I wanted to try.
Would be nice to have at least some feedback also, like a job link.
