### ISSUE TITLE
Mitigate pypi issue with space  (short term)

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#125179]
### 🐛 Describe the bug

Trying to mitigate issue with pyi space: https://github.com/pypi/support/issues/3836

I propose to delete following releases from pypi:
1.0.1.post2 - 3GB
1.1.0.post2 - 352MB
1.3.0.post2 - 284MB
1.10.1 - (since there are 1.10.0 and 1.10.2) - 5.4 GB
2.1.1 - (since there are 2.1.0 and 2.1.2) - 4.6GB 

---------------------------------------------------
Total ~13.62GB

This should clear space for 2 more releases
Please note all these releases are available on : https://download.pytorch.org/whl/torch/

cc @seemethere @malfet @osalpekar @albanD 

### Versions

2.4.0

**Comment by malfet** [comment]
This idea good to me as long as we are sure that those releases are mirrored to download.pytorch.org (up to a hash sum) and instructions for installing previous releases are updated

**Comment by albanD** [comment]
Sounds good with @malfet suggestions above.

**Comment by DEKHTIARJonathan** [comment]
@atalman @albanD  could you maybe wait for 1.10.1 and 2.1.1 ? I'm trying to negotiate for you that space increase.
Feel free to delete it when you need it, but there's no emergency to delete 2 release ahead.

**Comment by atalman** [comment]
@DEKHTIARJonathan Thank you very much! Will wait deleting 1.10.1 and 2.1.1.

**Comment by atalman** [comment]
Update, Following releases where deleted:
1.0.1.post2 - 3GB
1.1.0.post2 - 352MB
1.3.0.post2 - 284MB

They are still available on:
https://download.pytorch.org/whl/torch/

Current limit on pypi:
Project size: 141.4 GiB
Project total size limit: 160.0 GiB

**Comment by DEKHTIARJonathan** [comment]
Still working on it. Trying to not push too hard.
@atalman  Can you send me an email: jdekhtiar@nvidia.com, we have a meeting: NV/Meta next week I'd like to loop you in

**Comment by rgommers** [comment]
> 2.1.1 - (since there are 2.1.0 and 2.1.2) - 4.6GB

The more recent a release is, the higher the impact of deleting it. It'd be good to avoid having to delete especially 2.1.1, because it's only 7 months old and therefore almost certainly going to break a fair amount of users.  It looks like the need for doing that is still at least a couple of releases away. I'd prefer pinging a bit louder before deleting such a recent release.

**Comment by DEKHTIARJonathan** [comment]
@rgommers @gottbrath still working on it. I'm also voting in favor of waiting until absolutely necessary to delete anything

**Comment by PaliC** [comment]
We are planning on releasing another package which contains the python independent portions pytorch (currently called torch_cpp), this should reduce torch's memory footprint as we only need to distribute this part of torch once instead of 5 times (for each version of python we support). However, in order to do this we need another pypi package. We are requesting increased space for this.

https://github.com/pypi/support/issues/4379 and https://github.com/pypi/support/issues/4378 are the relevant requests.
cc: @gottbrath @rgommers

**Comment by DEKHTIARJonathan** [comment]
PyPA size issue fixed. Now can move toward a longer-term plan.
Potentially can close this issue

**Comment by atalman** [comment]
Thank you @cmaureir @rgommers  @DEKHTIARJonathan @gottbrath for looking into this! Closing this issue now!
