### ISSUE TITLE
Failed to deploy distributed pytorch in clusters with dockers using "bridge network"

### ISSUE THREAD

**Issue by qjfytz** [pytorch/pytorch#12527]
We are working on deploying pytorch in a GPU cluster.  But find the distributed process group cannot be established. 

Say we have two machines and in each machine we create a docker where pytorch runs in. Since the network mode is "bridge mode"  for the dockers, the process in docker of machine A cannot directly connect to that in docker of machine B. It makes the initialization of process group failed.

If we change the network mode to 'host mode', everything is OK. But we have to use the "bridge mode". 

## Environment

backend: gloo
Script: the script is downloaded from https://github.com/pytorch/examples/tree/master/imagenet
Distributed mode:  we use DistributedDataParallel and each gpu is governed by a process.
```

 - PyTorch Version (e.g., 1.0): 0.4.1
 - OS (e.g., Linux): ubuntu 16.04.4
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0/7.1.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by teng-li** [comment]
Two notes from your experimental setup:

(1), if the two machines share the same shared file system, please use `file://` init method while we will be fixing the `tcp://` init method.

(2), if you are using multi-processing distributed training and each GPU is governed by a process,  you are recommended to use NCCL backend for this purpose, since it is optimized for such multi-process scenario with CUDA IPC and can be a lot faster.

**Comment by ngimel** [comment]
Closing due to age
