### ISSUE TITLE
`nn.Linear` dtype clarification / doc issue?

### ISSUE THREAD

**Issue by db7894** [pytorch/pytorch#125552]
### 📚 The doc issue

Hi, I was using `nn.Linear` in `torch==2.2.2`, and the [doc](https://pytorch.org/docs/2.2/generated/torch.nn.Linear.html#torch.nn.Linear) for the layer says it supports `TensorFloat32`. When I initialized a layer without specifying any dtype, like this
```
self.affine1 = nn.Linear(4, config.width)
```
I found the default `weight` dtype was `torch.float64` and not `torch.float32`. Do you mean something different by "support" vs. "default", or is it worth mentioning that the default isn't float32 in the doc? 

### Suggest a potential alternative/fix

Maybe specify default `weight` dtype is `float64` instead of `float32` or clarify that supports float32 means something different. 

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by david20571015** [comment]
The dtype depends on `torch.get_default_dtype()` (which I think is determined by your device), and you can set it using `torch.set_default_dtype(torch.float32)`.

The [documentation](https://pytorch.org/docs/2.2/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices) says that if you:
- use NVIDIA GPUs since Ampere, and
- set `torch.backends.cuda.matmul.allow_tf32` to `True`,
the linear layer will internally compute matmul with TF32 (and remain float32 as its result).

**Comment by albanD** [comment]
The default dtype is always float32. If you see it being anything else, that means that your code or some library you're using is changing it!

**Comment by db7894** [comment]
Thanks—I don't think either of those explain my case. I'm not using CUDA (I'm running things locally on a macbook), and am just declaring standard layers like this. I confirmed by printing the dtypes for `self.affine1.weight` and `self.affine2.weight`. 
```
self.affine1 = nn.Linear(env.observation_space.shape[0], config.width)
self.dropout = nn.Dropout(p=0.6)
self.affine2 = nn.Linear(config.width, env.action_space.n)
```

**Comment by albanD** [comment]
Right, and if you run that in a separate script, I'm sure the dtype of the weights is going to be float32.

**Comment by db7894** [comment]
Yeah, sorry for wasting your time
