### ISSUE TITLE
Why I can't differentiate the output of ODE solver(Scipy) by autograd.grad

### ISSUE THREAD

**Issue by Chen-Ssu-Chien** [pytorch/pytorch#125532]
### 🐛 Describe the bug

Below is a simple example for my question, why I can not differentiate y respect to t using torch.autograd.grad()?
Can someone explain? And how to solve it?
```import torch
import numpy as np
from scipy.integrate import odeint

def model(y,t):
    k = 0.3
    dydt = -k * y
    return dydt

y0 = 5

t = np.linspace(0,20,10)

y = odeint(model,y0,t)
y=torch.tensor(y,requires_grad=True)
t=torch.tensor(t,requires_grad=True).reshape(-1,1)
dy=torch.autograd.grad(y[-1,0],t[-1,0],torch.ones_like(t[-1,0]))

print(dy)

Traceback (most recent call last):
  File "C:\Users\piyan\Desktop\PINN\test.py", line 22, in <module>
    dy=torch.autograd.grad(y[-1,0],t[-1,0],torch.ones_like(t[-1,0]))
  File "C:\Users\piyan\anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

### Versions

.

**Comment by MazenAmria** [comment]
If you take a look at `y` and `t` after `odeint` then they're just `numpy.ndarray`s. Taking the gradient won't work, because there isn't any computational graph that relates both tensors together. For example, if you take this code, the operations on `x1` and `x2` tensors have created the computational graph, which relates the variables with the output variable `y`, and thus we're able to backpropagate the gradients to `x1`.

```python
import torch

x1 = torch.rand((10, 10), requires_grad=True)
x2 = torch.rand((10, 10), requires_grad=True)

y = x1 * x2
dydx1 = torch.autograd.grad(y, x1, torch.ones_like(y))
```

The operations should be performed after defining the tensors and ensuring that they require gradients, not before that.

**Comment by jbschlosser** [comment]
Closing for now as resolved but feel free to reopen with more detail if you identify a bug in PyTorch.
