### ISSUE TITLE
[feature request] Support tuple scale_factor in Bilinear upsampling

### ISSUE THREAD

**Issue by andrewgiessel** [pytorch/pytorch#1257]
I have a simple and straightforward proposal:  allow more flexible upsampling specifications in [UpsamplingBilinear2d](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/upsampling.py#L72).  

In particular, I would like to relax the constraint that `scaling_factor` be equal in both dimensions.  This is not required for bilinear interpolation (but is for nearest neighbor as far as I can tell).  If you know what size of image you'd like to rescale too, you can directly specify even non-integer scaling by using the `size` parameter.  However, knowing these values beforehand can be cumbersome to calculate and is limiting in fully convolutional networks, for instance.  

As a point of reference, Keras allows independent scaling factors in their UpSampling2D layers.  In the tensorflow keras backend, these propagate to a bilinear interpolation routine.

I've implemented this locally and it works- it's pretty straightforward and only touches python.

Thoughts?  If approved I'll clean it up, figure out some tests, and open a PR.

**Comment by soumith** [comment]
sounds good, please send a PR and I'm happy to merge.

**Comment by fmassa** [comment]
In such cases I'd say that using the functional interface is the most straightforward way, and in your forward function you can just do `output = F.upsample_bilinear(input, size=input.size()[2:]`.

Plus, in your use-case of pixelwise predictions, specifying a single upsampling factor (even if it's non-integer) is not enough to handle all input sizes, due to the rounding nature of strided convolutions / max-pooling, so I don't see much benefit in it.
As an example, think about applying a 2x2 max pooling in a 4x4 image (outputs a 2x2 image), and now applying the same max pooling in a 5x5 image also outputs a 2x2 image, so the upsampling factor so that the output matches the output would be dependent on the input size.

**Comment by andrewgiessel** [comment]
@fmassa @soumith Thanks for commenting.  In particular, I appreciate your feedback, @fmassa!

@fmassa Indeed, I tried to use that first.  In my case, I'm building my architecture programmatically, and so am building a `ModuleList` in the constructor that I can compose in`foward`.   I think the only way I could mix modular and functional approaches would be to use partial function application to bake in the parameters for the functions, which is part of the role of Modules, as far as I can tell.

More generally, my use case is a bit peculiar (pixel-level predictions), but rather an autoencoder architecture where I max pool in only in one dimension through the encoder net.  The max pooling kernel can be asymmetric, but the current implementation of UpsamplingBilinear is not.  

Finally, I completely agree that the scaling factor can not give you arbitrary output images.  It makes sense to me to still constrain the scaling factors to integers>=1, but for each dimension instead of one.

Anyway, I'll open a PR soon and we can continue discussion there once I have a concrete
