### ISSUE TITLE
Contribution `clang-tidy` section outdated

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#125920]
### 📚 The doc issue

I cannot execute the current `clang-tidy` instructions on recent commits:
https://github.com/pytorch/pytorch/blob/main/CONTRIBUTING.md#running-clang-tidy

cc @svekars @brycebortree

**Comment by spzala** [comment]
@bhack thanks for reporting the issue. It will be helpful if you can provide more information like what platform have you tried the instructions (as clang-tidy is supported for only couple of platforms), which part of instructions failed, and what was the error. Thanks!

**Comment by bhack** [comment]
Just take any official nightly image so that we are in a reproducible environment and execute the official markdown instructions I linked in the ticket.

E.g you can use yesterday image:
https://github.com/orgs/pytorch/packages/container/pytorch-nightly/215236821?tag=2.4.0.dev20240513-cuda12.4-cudnn8-devel

**Comment by eugenekoran** [comment]
I confirm the issue.

[CONTRIBUTING.md](https://github.com/pytorch/pytorch/blob/main/CONTRIBUTING.md#running-clang-tidy) suggests to run clang-tidy locally with 3 steps:

## Steps Attempted:

### 1. Install clang-tidy

```bash
python3 -m tools.linter.clang_tidy.generate_build_files
```

**Result:** This step works as expected.

### 2. Install clang-tidy driver script dependencies

```bash
pip3 install -r tools/linter/clang_tidy/requirements.txt
```

**Result:** This step fails because the file doesn't exists:
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'tools/linter/clang_tidy/requirements.txt'
```

### 3. Run clang-tidy

```bash
make clang-tidy
```

**Result:** This step fails with the following error:
```
make: *** No rule to make target `clang-tidy'.  Stop.
```
