### ISSUE TITLE
[ONNX] Requesting support for aten::bitwise_right_shift for torch.onnx.export

### ISSUE THREAD

**Issue by zjgarvey** [pytorch/pytorch#126194]
### 🚀 The feature, motivation and pitch

When trying to export the hugging face models:

- "jlsilva/facebook-opt-125m-gptq4bit"
- "TheBloke/Llama-2-7B-GPTQ"

I get an error:

```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::bitwise_right_shift' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

And similarly for the later onnx opset_versions. 

If possible, I'd like to request support for this op in the onnx exporter.

**Comment by titaiwangms** [comment]
Hi @zjgarvey,

We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team

**Comment by sholevs66** [comment]
@zjgarvey Did you manage to export "TheBloke/Llama-2-7B-GPTQ" using 'torch.onnx.dynamo_export' ?
I'm getting other issues using it...
