### ISSUE TITLE
ConvOptions stride, padding etc.

### ISSUE THREAD

**Issue by mhubii** [pytorch/pytorch#12649]
## 🚀 Feature
Would be cool if you could pass the stride, padding, and so on to the `torch::nn::ConvOptions` constructor, see: https://pytorch.org/cppdocs/api/structtorch_1_1nn_1_1_conv_options.html#exhale-struct-structtorch-1-1nn-1-1-conv-options

Is it planned for future releases of the cpp api? How could I contribute to this?

**Comment by fmassa** [comment]
cc @goldsborough

**Comment by goldsborough** [comment]
@mhubii is this because you'd like to pass them all at once instead of using the chaining functions? 

Our design for these options was kind of centered around avoiding that, because it leads to long argument lists which are generally hard to read, so we wanted to have more of a keyword argument approach like in Python. I guess we could have constructors for all `Options` that also accept all arguments. But then I think we'd make that constructor take *all* arguments that the `Options` has (otherwise we need `n` constructors for `n` options, where each constructor adds one more option), and that may be cumbersome too.

Happy to hear your thoughts about this @mhubii

**Comment by mhubii** [comment]
Hi @goldsborough and thanks for the response. Yes having a constructor to which you could pass all arguments was what I thought of. But I didn't understand that you could chain the functions, guess that is what `TORCH_ARG` implements. Is it for example supposed to be used like this:
´´´
torch::nn::Conv2d conv(/*input_channels=*/3, /*output_channels=*/16, /*kernel_size=*/5);
conv->options.stride(2).padding(2); // And possibly other settings.
´´´
This is actually quite handy. Having a constructor that always takes all arguments or `n` constructors would indeed mess it up a little.

Thank you guys for doing this great work. Keep it up!

**Comment by goldsborough** [comment]
@mhubii  Not quite, that wouldn't always have an effect because you're changing the options after the `Conv2d` is created. The idea is to construct the `Options` object via chaining and pass it to the constructor of `Conv2d`:

```cpp
torch::nn::Conv2d conv(torch::nn::Conv2dOptions(3, 16, 5).stride(2).padding(2));
```

Sorry that wasn't clear. I will write some more tutorials for this.
