### ISSUE TITLE
Access activations stored for backprop

### ISSUE THREAD

**Issue by tychovdo** [pytorch/pytorch#12664]
When performing a forward pass (without `with torch.no_grad():`) pytorch saves intermediate activations  (in "context"?) to perform backpropagation.

Is there a way to access these saved activations?

**Comment by apaszke** [comment]
Theoretically yes, but it's not the case that all intermediate values are saved. This is highly implementation dependent, and changes between versions, therefore I wouldn't recommend it. If you need to access something, just save it explicitly.

**Comment by arquolo** [comment]
But, what about getting access to shapes of them, at least?
For checking memory footprint?

**Comment by soumith** [comment]
@arquolo it's not a question of why we dont provide access, it's a matter of "how". we simply throw away the whole activation Tensors actively, and dont keep any metadata around. Something like `torch.autograd.profiler` can record the shapes for you if that's what you are looking for.

**Comment by arquolo** [comment]
Ok, I got it.
By the way, at `pytorch<1.0`, pretty every `torch.autograd.Function` filled `saved_tensors` attribute.
That's why, we could parse computation graph via `Tensor.grad_fn` attribute, and get access to all saved tensors, [like here on forum (see orange nodes)](https://discuss.pytorch.org/t/print-autograd-graph/692/16).
However, for `pytorch>=1.0`, attribute `saved_tensors`, almost always empty (except for custom Functions, or `torch.utils.checkpoint`).
So, the question is, how can I get access to this info?
How can I find modules, which eat much memory?
