### ISSUE TITLE
Requesting dynamo support for fraction.Fraction

### ISSUE THREAD

**Issue by alba-saco** [pytorch/pytorch#126917]
### 🚀 The feature, motivation and pitch

Currently, dynamo_export does not support fraction.Fraction, resulting in graph breakage when attempting to use this functionality. This would enhance the compatibility of dynamo_export, enabling users like myself to export models that rely on this functionality under the hood. [Please see my original github issue for more context.](https://github.com/pytorch/pytorch/issues/126618) Thank you.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by ezyang** [comment]
This is probably not too hard to do with a polyfill

**Comment by StrongerXi** [comment]
I looked into this a bit, and right now Dynamo traces through `Fraction(...)` without any issue. I think it was failing because
1. `Fraction` had a custom `__new__`: https://github.com/python/cpython/blob/8cdd636f877c906121b27934522876a1d9ac12db/Lib/fractions.py#L203
2. At the time Dynamo didn't support tracing through custom `__new__`; the support was added later in #132977.

**Comment by StrongerXi** [comment]
@alba-saco would you mind trying again on the latest PyTorch?
