### ISSUE TITLE
Overly demanding PyTorch CLA

### ISSUE THREAD

**Issue by OverLordGoldDragon** [pytorch/pytorch#127285]
I shouldn't have to provide my address so I can contribute to an open source project. Where I live is none of Meta's business.

I urge PyTorch to provide alternatives.

**Comment by malfet** [comment]
PyTorch CLA is not Meta one, but rather one mandated by [PyTorch Foundation](https://pytorch.org/foundation), which is part of a Linux Foundation.  So you would see similar requirement if you are to contribute to say Linux kernel, but information you submit are sent to LF, rather than to Meta. If I remember correctly there were some precedent almost a decade ago that made Linux kernel developers community consider this rule for the first time contributors. 

If you believe this is too restrictive, please do not hesitate create a support ticket on https://easycla.lfx.linuxfoundation.org/#/ or file an issue at https://github.com/communitybridge/easycla
