### ISSUE TITLE
Torch rocm 6.0 breaks gfx900 amd gpus (fixed in 6.1)

### ISSUE THREAD

**Issue by thenightterorx** [pytorch/pytorch#128302]
### 🐛 Describe the bug

In my case, I was trying to run stable diffusion. The error occurs on both ComfyUI and Automatic1111

During generation, the display server and the gpu will crash with dmesg error "ring0 page1 timeout"

I am using a radeon instinct mi25 (with wx 9100 bios), which is gfx900.

### Versions

torch with rocm 6.0 (fixed on 6.1)

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment]
Not trying to sound flippant, but if it works in rocm 6.1 please use that instead of the older rocm 6.0.  Also, [gfx900 is unsupported](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-gpus).  I'm glad to hear it was working for you on rocm 6.1.

**Comment by hongxiayang** [comment]
@thenightterorx I am going to close since it is fixed for you on rocm6.1.
