### ISSUE TITLE
torch.gather can be slow on AMD with duplicated index

### ISSUE THREAD

**Issue by Yuzhen11** [pytorch/pytorch#128631]
### 🐛 Describe the bug

We found that torch.gather can be very slow running on AMD GPU compared with NVIDIA GPU with duplicated index. 

To repro:

```
	
import torch
import triton

device = "cuda"
input = torch.randn([100], dtype=torch.float, device=device, requires_grad=True)
indices = torch.randint(low=0, high=1, size=(74544,), dtype=torch.int64, device=device)

def gather():
    output = torch.gather(input, dim=0, index=indices)
    output.sum().backward()

triton.testing.do_bench(lambda: gather())

```

The slowness comes from the backward kernel: _scatter_gather_elementwise_kernel

On AMD MI300X: 

I0612 223553.302 test_gather.py:41] Link to trace: https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree/traces/test/testttt_20240612_223534_3731825843.json.gz&bucket=pyper_traces  (Meta internal only)
I0612 223608.688 test_gather.py:42] Time (ms): 1887.4288330078125

Trace: 
<img width="584" alt="image" src="https://github.com/pytorch/pytorch/assets/10265048/9f1b6899-27e3-4cc9-ba9f-79ecb039bc37">

On H100: 

I0612 224254.306 test_gather.py:41] Link to trace: https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree/traces/test/testttt_20240612_224254_3319354165.json.gz&bucket=pyper_traces  (Meta internal only)
I0612 224254.408 test_gather.py:42] Time (ms): 0.26988503336906433

### Versions

Latest PyTorch trunk. 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jerrymannil** [comment]
The issue seems to be fixed by using `atomicAdd` instead of `atomicAddNoRet` [here](https://github.com/pytorch/pytorch/blob/c1875934181153e19965a68ecb36028314ec7406/aten/src/ATen/cuda/Atomic.cuh#L337)

I was getting a deprecated warning for `atomicAddNoRet`; hence tried with `atomicAdd`.
They are implemented using different compiler intrinsics.

atomicAddNoRet: https://github.com/ROCm/clr/blob/4ec3a977b21da0025609fad0564edaa98436e077/hipamd/include/hip/amd_detail/amd_hip_atomic.h#L283

atomicAdd:  https://github.com/ROCm/clr/blob/4ec3a977b21da0025609fad0564edaa98436e077/hipamd/include/hip/amd_detail/amd_hip_atomic.h#L1425
