### ISSUE TITLE
RuntimeError: variable impl does not have is_contiguous in C++ extension function

### ISSUE THREAD

**Issue by iacolippo** [pytorch/pytorch#12872]
## 🐛 Bug

Opening this issue because I'm not sure if it's a bug or I'm just doing something wrong.

When calling `temp.index_put_(mesh1, slice1 + slice2)` with `temp` and `slice1+slice2` as `at::Tensor` and `mesh1` as `TensorList`, I get:

`RuntimeError: variable impl does not have is_contiguous (is_contiguous at /home/iacolippo/pytorch/torch/csrc/autograd/variable.cpp:57)`

It seems that it can't find an implementation of the `is_contiguous` method for `slice1+slice2`, even though if I call `(slice1 + slice2).is_contiguous()` right before the incriminated line it evaluates to true with no problems (from `gdb` the Error is raised at this line of the `.cpp` file https://gist.github.com/iacolippo/c278680717fb4622f958e37caa721fe3#file-ex-cpp-L27 ). I tried to trace back the origin of the issue from `gdb` but it's a rabbit hole down to `THC` code that I don't understand.

## To Reproduce

1. GIst with `cpp`, `setup.py` and `test.py` file here: https://gist.github.com/iacolippo/c278680717fb4622f958e37caa721fe3
2. `python setup.py install` - contains extra compile args for debug (`-g`, `-0O`)
3. `python test.py`

## Expected behavior

I would expect the `is_contiguous` to work on my `at::Tensor` inside the `input_put_` method. Even though I'm not sure I'm doing things correctly.

## Environment

```
Collecting environment information...
PyTorch version: 1.0.0a0+5b8a640
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 17.10
GCC version: (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (1.0.0a0+5b8a640)
[conda] torch                     1.0.0a0+5b8a640           <pip>
```

**Comment by iacolippo** [comment]
Ok, problem solved by including

`#include <torch/tensor.h>`

and using `torch::Tensor` instead of `at::Tensor`.

The [C++ extensions tutorial](https://pytorch.org/tutorials/advanced/cpp_extension.html) uses `at::Tensor` and now I'm confused: should we always use `torch::Tensor`, when should we use `at::Tensor`? Is the tutorial wrong? :-)

You can close this issue, but I think the distinction between the two should be clarified somewhere, or if it already is, can you point me to it?

Thank you!

**Comment by zou3519** [comment]
cc @goldsborough should we fix the tutorials?

**Comment by goldsborough** [comment]
There is nothing wrong here. `torch::Tensor` is a typedef to `at::Tensor` and it is meant to be used in the C++ frontend, not C++ extensions. The problem with your code is not the tensor class, but the fact that you use `at::` functions to create tensors instead of `torch::` functions. When you write
```cpp
at::Tensor temp = at::zeros({n_samples, G, 2});
```
then `temp` will be a tensor. You pretty much never want it to be tensor, but instead a variable, which you get with
```cpp
at::Tensor temp = torch::zeros({n_samples, G, 2});
```

I recommend you leave your existing code as-is and don't include `torch/torch.h` in your extension, but instead replace all uses of `at::` in tensor factories with `torch::`, but leave `at::` usage for everything else (i.e. `at::Tensor` and any free functions).

This should probably be clarified in the tutorial somewhere, although it doesn't actually create any tensors in C++, that's why there's no good situation to showcase it.
