### ISSUE TITLE
expand_as export to ONNX

### ISSUE THREAD

**Issue by ArmenAg** [pytorch/pytorch#12896]
## 🚀 Feature
expand_as is a very heavily used call within pytorch but yet it's not supported when exporting to ONNX. The fix should be simple in the onnx/symbolic.py file.

Along the same lines, expand isn't being properly exported either.

**Comment by alwc** [comment]
Hi @ArmenAg 

I'm trying to convert a model from PyTorch to ONNX to Core ML and I'm confused of how to convert the model properly when there is either `expand` (or `expand_as`) function in the model.

Initially my model has a line with 

`y = y.expand_as(x)` where `y.shape` is `torch.Size([1, 1, 40, 30])` and `x.shape` is `torch.Size([1, 256, 40, 30])`. 

I can successfully converted the model into ONNX format, but then I failed to convert it to Core ML model using [`onnx/onnx-coreml`](https://github.com/onnx/onnx-coreml).

Next I tried to use

`y = y.expand(torch.Size([1, 256, 40, 30]))` since I thought ONNX supports the `expand` operator, then the Core ML converter might work. But then now I'm getting

```
RuntimeError: ONNX export failed: Could not export a broadcasted operation; ONNX likely does not support this form of broadcasting.  
```

 Is there any hack that I can solve the problem currently? Thanks!

**Comment by vuamitom** [comment]
Maybe you can try `repeat` instead of `expand`. 

```python
y = y.repeat(1, 256, 1, 1)
```

**Comment by rgommers** [comment]
Support for `expand` and `expand_as` was added in Dec 2018, as reported in https://github.com/pytorch/pytorch/issues/10882#issuecomment-478213419. There's a test for `expand` in `test/onnx/test_operators.py`, and `expand_as` is defined in terms of `expand` in `torch/onnx/symbolic.py`.  Also confirmed that the example using `expand_as` given in the description of gh-10882 works with current master. So this issue can be closed.
