### ISSUE TITLE
`list(model.Parameters())` behaves differently for custom `nn.module`

### ISSUE THREAD

**Issue by pavanramkumar** [pytorch/pytorch#1291]
I'm trying to write a custom module. Listing its parameters seems to depend on whether you define an operation in `__init__()` as an instance variable. 

So for instance, this lists the parameters correctly:

```python
class ThreeLayerNet(torch.nn.Module):
  def __init__(self, D_in, H, D_out):
    super(ThreeLayerNet, self).__init__()
    self.linear1 = torch.nn.Linear(D_in, H)
    self.linear2 = torch.nn.Linear(H, H)
    self.linear3 = torch.nn.Linear(H, D_out)

  def forward(self, x):
    h_relu = self.linear1(x).clamp(min=0)
    h_relu = self.linear2(h_relu).clamp(min=0)
    y_pred = self.linear3(h_relu)
    return y_pred

D_in, H, D_out = 1000, 100, 10
model = ThreeLayerNet(D_in, H, D_out)
list(model.parameters())
```

But this does not:

```python
class ThreeLayerNet(torch.nn.Module):
  def __init__(self, D_in, H, D_out):
    super(ThreeLayerNet, self).__init__()

  def forward(self, x):
    h_relu = torch.nn.Linear(D_in, H)(x).clamp(min=0)
    h_relu = torch.nn.Linear(H, H)(h_relu).clamp(min=0)
    y_pred = torch.nn.Linear(H, D_out)(h_relu)
    return y_pred

D_in, H, D_out = 1000, 100, 10
model = ThreeLayerNet(D_in, H, D_out)
list(model.parameters())
```

Is this expected behavior? If so, it is sufficient to define all layers with parameters alone as instance variables, or do we also define non-linearities?

```python
self.activation1 = torch.nn.Sigmoid()
```

Any help is appreciated. Thanks!

**Comment by soumith** [comment]
this is expected behavior. You are creating a fresh `nn.Linear` on every forward call.

What you probably want is to define your weights as `nn.Parameter` in `__init__` and then use `F.linear`, where F is `torch.nn.functional`. http://pytorch.org/docs/nn.html#torch.nn.functional.linear

Here's an example: https://github.com/szagoruyko/attention-transfer/blob/master/imagenet.py#L149

In the future, questions go to: https://discuss.pytorch.org
