### ISSUE TITLE
TORCHINDUCTOR_FORCE_DISABLE_CACHES=1 doesn't appear to clear file cache

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#129159]
### 🐛 Describe the bug

Comment out all models [here](https://github.com/pytorch/pytorch/blob/e84cf805d2e815b8fecd847f5947b8cd8fbf61f3/benchmarks/gpt_fast/benchmark.py#L236) except run_llama2_7b_bf16
run benchmark.py
output:
```
`-->                                                
TORCHINDUCTOR_FORCE_DISABLE_CACHES=1 python benchmark.py
Loading model Llama-2-7b-chat-hf
Time to load model: 0.73 seconds
Compilation time: 184.44 seconds
Average tokens/sec: 94.46 tokens/sec
Average bandwidth achieved: 1248.25 GB/s
Memory used: 14.51 GB
.-(~/local/pytorch/benchmarks/gpt_fast)----(mlazos@devgpu004)-
`--> 
TORCHINDUCTOR_FORCE_DISABLE_CACHES=1 python benchmark.py
Loading model Llama-2-7b-chat-hf
Time to load model: 0.87 seconds
Compilation time: 125.37 seconds
Average tokens/sec: 93.92 tokens/sec
Average bandwidth achieved: 1241.16 GB/s
Memory used: 14.51 GB
```

Compilation time still decreases from 184 -> 125
Removing or renaming the file cache solves the problem.

### Versions

nightly 0f89e66d1745b8f4b304ebf46174bc726f0c28f5

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by masnesral** [comment]
My first guess is that we're still hitting the Triton cache. @oulgen are you already investigating, or would you like me to have a look?

**Comment by oulgen** [comment]
@masnesral Right, we currently only disable remote triton cache, not the local one. So disabling that will be the first step, nice catch.

**Comment by masnesral** [comment]
So there are a few issues here:

1) The decorator `with_fresh_cache_if_config` isn't decorating properly, therefore we don't actually get a fresh cache in the first place.
2) I can fix the decorator, but `compile_fx_inner` isn't the right place to decorate because files in the cache dir are accessed later (after we'd have removed the "fresh" tmp dir).
3) The parallel compile subprocesses are started as early as possible, so any changes to the env vars that influence the cache location will not be recognized by those and they'll use the default location for the triton cache. 

Couple ideas:
a) Instead of building on `fresh_inductor_cache`, we could just define all cache-related settings in _inductor/config.py to be False if `TORCHINDUCTOR_FORCE_DISABLE_CACHES=1`
b) We could add a special mode or keyword to `TORCHINDUCTOR_CACHE_DIR` that means "create a new fresh temp dir and use that"

I'm inclined to do a) because in b), technically the caching wouldn't be disabled completely, i.e., we could still get hits within the same process. And b) by itself wouldn't disable remote caches anyway.
