### ISSUE TITLE
FP8 Emulation

### ISSUE THREAD

**Issue by tsengalb99** [pytorch/pytorch#129991]
### 🚀 The feature, motivation and pitch

Currently, pytorch has limited operation support for FP8 E4M3 and E5M2 datatypes. Furthermore, existing "FP8 packages" like NVIDIA TransformerEngine require hardware FP8 support, meaning that people without the latest GPUs cannot easily experiment with FP8. Is it possible to have an FP8 emulation mode that takes two FP8 tensors, casts them to a supported higher precision format (eg FP16 or BF16), does the operation in high precision, and then casts the result back to FP8? While it is possible to manually implement this for every operation, there should be an automatic way to do handle this. 

### Alternatives

Manually implementing an FP8 emulator.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @yanbing-j @vkuzo @albanD @kadeng @penguinwu

**Comment by malfet** [comment]
I though there is already a FP8 emulation (at least one can call fill, etc on both CPU and GPUs without FP8 support), but I wonder if something could be done better about it. On the other hand, FP8 is only used for a very specific applications, when one expect certain speed gain from using it. 
But adding `triage review` to discuss

**Comment by vkuzo** [comment]
> Currently, pytorch has limited operation support for FP8 E4M3 and E5M2 datatypes.

Hi @tsengalb99 , this is expected.  For the newer low precision dtypes such as float8, in PyTorch Core we only support ops which are either just moving bytes around (copy, fill, etc) or have silicon support for mathematical operations (such as `torch._scaled_mm` backed by hardware accelerated gemm kernels).  Please see https://dev-discuss.pytorch.org/t/supporting-new-dtypes-in-pytorch/1833 for more context on this.

For modeling logic of expanding op support beyond what is supported by silicon, we recommend to use Python to implement the ops.  For example:
* https://github.com/pytorch-labs/float8_experimental/tree/main has a `Float8Linear`, which supports emulation mode
* https://github.com/pytorch/ao/tree/main/torchao/dtypes has other examples of tensor subclasses which implement various operations on custom dtypes, in Python

> Is it possible to have an FP8 emulation mode that takes two FP8 tensors, casts them to a supported higher precision format (eg FP16 or BF16), does the operation in high precision, and then casts the result back to FP8?

You could implement this by extending `Float8Tensor` to cast up to original precision for ops not in its dispatch table instead of throwing an exception, here: https://github.com/pytorch-labs/float8_experimental/blob/d4cf2ad0c2a240cf6e6e51b601639a43930ed2c9/float8_experimental/float8_tensor.py#L305.  Note that we currently don't have plans to support this in `float8_experimental` due to lack of use case, but definitely open to hearing more about real world use cases for this.

**Comment by tsengalb99** [comment]
Thanks, I'll take a look at those pointers. My use case is being able to test out FP8 algorithms on older hardware without FP8 acceleration. I think adding support for an emulation mode would be really useful for people to develop better FP8 algorithms since even today getting access to Hopper GPUs can be difficult.
