### ISSUE TITLE
`dot()` outputs `tensor(0.)` with two of empty 1D tensors

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130063]
### 🐛 Describe the bug

[dot()](https://pytorch.org/docs/stable/generated/torch.dot.html) outputs `tensor(0.)` with two of empty 1D tensors as shown below:

```python
import torch

t1 = torch.tensor([])
t2 = torch.tensor([])

torch.dot(input=t1, tensor=t2)
# tensor(0.)

# Additional
t1 = torch.tensor([0.])
t2 = torch.tensor([0.])

torch.dot(input=t1, tensor=t2)
# tensor(0.)
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by davidgonmar** [comment]
Isn't this correct mathematically though? The dot product is defined as $\sum_{i=0}(a_i b_i)$, and the sum of an empty vector is 0.

**Comment by malfet** [comment]
Closing as this is indeed an expected behavior, as dot product of two empty 1D vectors should be zero.

**Comment by malfet** [comment]
@hyperkai if your goal is to explore all op behaviors with empty tensors, do you mind filing an umbrella issue first, and report all your findings here. Or at the very least add a paragraph about expected behavior and why do you think it should be that way (for example, behavior is inconsistent with other framework, or makes no sense mathematically or something of that nature)
