### ISSUE TITLE
click test name to copy-paste in test failures

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#130332]
<img width="1238" alt="image" src="https://github.com/pytorch/pytorch/assets/5652049/d91a4b33-623d-4398-8c3b-4b948b29b760">

I wish there were a way to click the test name to copy-paste. I spend a couple of seconds fumbling around on this page before I can actually copy-paste the test name (clicking it opens the log, and then you have to drag your mouse over the test name in the log. 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Not sure why it needs triage review, as there is `module: ci` already

**Comment by jbschlosser** [comment]
Alternatively / additionally, I think it'd be nice to have a similar feature to copy / paste the full repro command.

**Comment by clee2000** [comment]
There are two buttons that copy to clipboard

The revert info button copies the test name and some markdown formatted links, and the other copy button copies an attempt at the repro command.  It's not the exact one in the logs since we don't have a way to hook into that atm

![Image](https://github.com/user-attachments/assets/ec575f4d-8454-4093-8f2d-25fb7c43c475)

I am going to close this issue for now but please reopen if these options are not good for your use case
