### ISSUE TITLE
API To Make Custom Post Grad Passes Hashable

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#130772]
### 🚀 The feature, motivation and pitch

Currently we hash miss if there are any custom post grad passes. We should fix this.

One purposal would be to add an API so that when users register a custom pass they provide `__hash__` and `__eq__`. typically folks here would be power users so a little extra work is okay.

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @chauhang @penguinwu @voznesenskym @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @anijain2305 @masnesral @oulgen

**Comment by masnesral** [comment]
@eellison, Actually since we currently pickle to create a byte string to hash, I think users would need to implement the `__reduce__` method?

**Comment by eellison** [comment]
We don't have to use pickle for the post grad passes.

**Comment by masnesral** [comment]
> Currently we hash miss if there are any custom post grad passes. We should fix this

Actually in https://github.com/pytorch/pytorch/issues/136883 we don't cache miss. We pickle the custom function successfully, but since that example uses global state it's not appropriate to serve a cache entry. Presumably this API would need to take that into account when implementing, e.g.,  `__hash__` and `__eq__`

**Comment by eellison** [comment]
Well, I guess we don't cache miss, we're just wrong. But in either case I think we want an API to make custom post grad passes hashable. We could provide convenience function that hashes based on a directory or file source code.

**Comment by masnesral** [comment]
> We could provide convenience function that hashes based on a directory or file source code.

Sure that sounds good, but users would also need to be aware that the hash they compute would need to take into account external state that affects the operation of the custom pass. I'm brainstorming with myself, but I can't immediately think of a good way to protect against it being a foot gun. Seems like a very easy thing to overlook or get wrong, then you get silent incorrectness because of a bad cache entry.  Is the pattern in https://github.com/pytorch/pytorch/issues/136883 the recommended way to implement custom pattern matchers?

**Comment by eellison** [comment]
That pattern is a reasonable way to do, sure. 

I think there's two ways of doing it :
- give file/directory path
- try to recursively look into function. this might get difficult with state, etc, but could be an option. 

We do file/directory path for our own caching. So i'm inclined to do that as well. cc @oulgen 

cc @ezyang

**Comment by masnesral** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/137298
