### ISSUE TITLE
byte() conversion in torch.compile gives incorrect results for CPU Inductor

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#131910]
Repro:
```python
import torch

torch.manual_seed(1)

def f(x):
    return x.byte()

# non-Inductor backend gives same result as eager
# compiled_f = torch.compile(fullgraph=True, backend="aot_eager_decomp_partition")(f)
compiled_f = torch.compile(fullgraph=True)(f)

x = torch.randn(20)
out = f(x)
compile_out = compiled_f(x)

# tensor([255,   0,   0, 255,   0,   0,   0,   0,   0,   1,   1,   0,   0,   0,
#           0,   0,   0,   0,   0,   1], dtype=torch.uint8)
print(out)

# tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
#        dtype=torch.uint8)
print(compile_out)

# False
print(torch.allclose(out, compile_out))
```

I can't repro this on CUDA, so I'm flagging it as a CPU inductor specific problem.

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by jgong5** [comment]
This is because you are converting negative floating point values to unsigned integers which is UB.
https://embeddeduse.com/2013/08/25/casting-a-negative-float-to-an-unsigned-int

To get consistent result, please make sure the floating point values are positive first. I'm closing this issue. Please reopen if you have different opinions.
