### ISSUE TITLE
[dynamo][side-effects] Add mutable_local invariants to Variable Trackers

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#133027]
### 🐛 Describe the bug

In a recent PR - https://github.com/pytorch/pytorch/pull/132912 - we came across a nasty silent incorrectness bug. This prompted me to think about a few invariants that we should maintain

1) if `var.mutable_local` is `MutableSideEffects` - `var.source` must not be None
2) if `var.mutable_local` is `MutableLocal` - `var.source` must be None (this was in violation in the above issue, making side effects infra to do funky things)
3) if `var.mutable_local` is `None` - var must be a `ConstantVariable` (this could be relaxed and needs more thought, TupleVariable with constants etc) - This will ensure that we track mutable_local correctly in all cases.

We should probably change the attr name `mutable_local` to something else. The `local` in the name suggest to me that the tracked object is created inside the frame (as opposed to existing). Some suggestions for rename are

`var.mutable_local` to `var.mutation_type` (Not fully convinced that this good name, suggestions welcome)
`MutableLocal` to `MutableNew` (even local is confusing - is it from f_locals? Or is it created inside the frame?)
`MutableSideEffects` to `MutableExisting` (opposite of  `MutableNew`)

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @jansel if this makes sense.

### Versions

NA

**Comment by ezyang** [comment]
I find I do not have an opinion on the names. Pick something distinctive, if you are worried that people will misinterpret.

**Comment by anijain2305** [comment]
cc @mlazos @williamwen42 @mlazos

**Comment by mlazos** [comment]
I was thinking about this last year when I worked on side effects. I think this can actually be simplified quite a bit. I think we really only need an `is_modified`/`is_mutated` flag now that VTs are mutable. The only thing side_effects needs to know is if it needs to do some mutation replay at the end/instantiate any newly created objects to be returned. This might be overly simplifying things, but I do think a larger refactor beyond enforcing these invariants is possible. I will spend some time looking at this on Monday and make my proposal more concrete.

**Comment by anijain2305** [comment]
Sounds good. Without knowing all the intricacies, your proposal makes sense.

Yes, one thing that bugs me today is - why do we have 'var.mutable_local.source'? Are there cases where var.source will be different from 'var.mutable_local.source'? If not, then your proposal seems good enough.

**Comment by mlazos** [comment]
Talked about this with @StrongerXi.
We opted to phase this into
1) rewrite names as above with the invariants
2) Remove sources from mutable_local (shouldn't be needed since var trackers are mutable now)
3) Should be able to remove dict indexing on mutable_local and just use the var tracker (id of a var tracker should be consistent throughout dynamo execution)
4) (optional) Move store_attr_mutation tracking into the var tracker itself? This might be cleaner but open to opinions about this
5) (optional) Move codegen updated mutated into the var trackers because it's a big switch statement on var tracker type

**Comment by jansel** [comment]
> if var.mutable_local is None - var must be a ConstantVariable (this could be relaxed and needs more thought, TupleVariable with constants etc) - This will ensure that we track mutable_local correctly in all cases.

This seems wrong to me.  It just means it can't be mutated.  Which will be true for many types of VaribleTrackers.

`var.mutable_local = None` means (Python, not torch) mutation is not allowed

`var.mutable_local = MutableLocal()` means mutation can be done freely since the object is a local and mutations aren't visible outside the frame.  Originally this was the only value it could have, hence the name.

All other values means mutating the object would be a side effect visible outside the frame, and we need to generate bytecodes to re-apply the mutation.

**Comment by StrongerXi** [comment]
More documentation on side effects and codegen:
- #139538
- #139670

**Comment by StrongerXi** [comment]
> 4. (optional) Move store_attr_mutation tracking into the var tracker itself? This might be cleaner but open to opinions about this
> 5. (optional) Move codegen updated mutated into the var trackers because it's a big switch statement on var tracker type
> 6. `is_modified` I think can be simplified when the above are finished

I thought about this and decided to hold off (4), (5), and consequently (6), mainly because the side-effect codegen logic is a bit involved, and honestly feels easier to reason about when they are centralized in `SideEffects`.

**Comment by mlazos** [comment]
> > 4. (optional) Move store_attr_mutation tracking into the var tracker itself? This might be cleaner but open to opinions about this
> > 5. (optional) Move codegen updated mutated into the var trackers because it's a big switch statement on var tracker type
> > 6. `is_modified` I think can be simplified when the above are finished
> 
> I thought about this and decided to hold off (4), (5), and consequently (6), mainly because the side-effect codegen logic is a bit involved, and honestly feels easier to reason about when they are centralized in `SideEffects`.

This sounds fine to me, but you might want to reconsider when we subclass dict. I imagine in the future we may subclass other builtin types and I think the switch statement may become unwieldy at that point. I don't feel strongly about this though, just something to consider.
