### ISSUE TITLE
The doc of `Sigmoid()` says there are `*args` and `**kwargs` but they don't work

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#133688]
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html) of `Sigmoid()` says there are `*args` and `**kwargs` as shown below:

> CLASS torch.nn.Sigmoid(*args, **kwargs)

But they don't work as shown below:

```python
import torch
from torch import nn

my_tensor = torch.tensor([-1., 0., 1.])

sigmoid = nn.Sigmoid(3, 5) # Error

sigmoid= nn.Sigmoid(num1=3, num2=5) # Error
```

> TypeError: Sigmoid.__init__() takes 1 positional argument but 3 were given

> TypeError: Sigmoid.__init__() got an unexpected keyword argument 'num1'

### Suggest a potential alternative/fix

So, `*args` and `**kwargs` should be removed from [the doc](https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html) of `Sigmoid()` as shown below:

> CLASS torch.nn.Sigmoid()

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by awgu** [comment]
The `*args` and `**kwargs` are because `Sigmoid` does not override the constructor and hence shares the same constructor as the base `Module` class.
https://github.com/pytorch/pytorch/blob/51e13745be7052c02913db79b268e637c32546dd/torch/nn/modules/module.py#L473
You could define a dummy constructor for `Sigmoid` that does not take in `*args` and `**kwargs` to fix this.
