### ISSUE TITLE
How to Manage CPU Memory Usage in PyTorch After Moving Model to CPU?

### ISSUE THREAD

**Issue by prisnguyen** [pytorch/pytorch#133643]
### 📚 The doc issue

Hi everyone,

I'm currently working on a deep learning project using PyTorch, and I've run into some issues with managing CPU memory after transferring a model to the GPU.

In specific, I'm loading a pre-trained model using PyTorch, then moving the model to the GPU. However, I've noticed that after moving the model to the GPU, the CPU memory usage doesn't decrease as much as I expected.

I used 'memory_profiler' to analyze memory usage, and here's what I found:

Before moving to GPU: The model uses a significant amount of CPU memory during the loading and preparation stages.

After moving to GPU: The memory usage on the CPU doesn't drop much. It seems like some data or buffers might still be retained in CPU memory.

I've tried deleting references to the model on CPU using 'del' and forced garbage collection using 'gc.collect()' but this doesn't seem to affect the memory.

So is that because PyTorch inherently keep some CPU memory for caching or other purposes? Is it possible to fully release the CPU memory after moving a model to GPU in PyTorch?

I would appreciate any insights or advice on how to better manage CPU memory in this context. Thanks in advance for your help!Hi everyone,

I'm currently working on a deep learning project using PyTorch, and I've run into some issues with managing CPU memory after transferring a model to the GPU.

In specific, I'm loading a pre-trained model using PyTorch, then moving the model to the GPU. However, I've noticed that after moving the model to the GPU, the CPU memory usage doesn't decrease as much as I expected.

I used **'memory_profiler'** to analyze memory usage, and here's what I found:

Before moving to GPU: The model uses a significant amount of CPU memory during the loading and preparation stages.

After moving to GPU: The memory usage on the CPU doesn't drop much. It seems like some data or buffers might still be retained in CPU memory.

I've tried deleting references to the model on CPU using **'del'** and forced garbage collection using **'gc.collect()'** but this doesn't seem to affect the memory.

So is that because PyTorch inherently keep some CPU memory for caching or other purposes? Is it possible to fully release the CPU memory after moving a model to GPU in PyTorch?

I would appreciate any insights or advice on how to better manage CPU memory in this context. Thanks in advance for your help!

**Comment by colesbury** [comment]
I don't think this is PyTorch holding on to the memory.

Most of the time, the system's memory allocator (i.e., glibc's malloc) holds on to unused memory in the process because it's likely to be re-used in the future and that's more efficient than returning it to the OS.

If you're using Linux, see https://sourceware.org/glibc/wiki/MallocInternals for more details.

You can use the C function [`malloc_trim`](https://man7.org/linux/man-pages/man3/malloc_trim.3.html) to encourage libc to release memory to the OS. (You can probably call it from Python via ctypes or cffi)

Please use the forum to ask questions: https://discuss.pytorch.org/](https://discuss.pytorch.org/
