### ISSUE TITLE
Unexpected Termination in PyTorch When Applying torch.atan to Large Tensors

### ISSUE THREAD

**Issue by sametcopur** [pytorch/pytorch#133617]
### 🐛 Describe the bug

I am experiencing an issue while running two pieces of PyTorch code that seem to behave differently despite their apparent similarity.

The first piece of code works as expected:

```python
for i in torch.rand(10000):
    torch.atan(i)
```

This code generates 10,000 random numbers using torch.rand(10000) and then applies the torch.atan function to each of these numbers in a loop. It runs without any issues.

However, when I try to execute the following code:

```python
torch.atan(torch.rand(10000))
```

The program terminates abruptly without throwing any exceptions or errors. It simply exits as if sys.exit() was called. When I try to debug this issue in a debugger, the program also exits, with the debugger reporting ```No more messages``` before the program completely shuts down.

### Versions

Collecting environment information...
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchvision==0.19.0

**Comment by bdhirsh** [comment]
The program will not have any output unless you print the output of your tensor operations:
```
out = torch.atan(torch.rand(10000))
print(out)
```

Your second program will also run signficantly faster, because the call to `torch.rand` and `torch.atan` are vectorized. Your first program is slower because you are manually looping through a tensor of 10000 elements in python, requiring converting every element of the tensor (which lives in C++) into a python number.

Feel free to post any further questions on the pytorch forums! https://discuss.pytorch.org/
