### ISSUE TITLE
SDPA batching rules need randomness handling

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#135020]
cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki @Chillee @samdow @kshitij12345

**Comment by kit1980** [comment]
@zou3519 Is there a fix? If not, let's remove the milestone.

**Comment by zou3519** [comment]
this was fixed

**Comment by huydhn** [comment]
@zou3519 Could you help verify that this has been fixed in the upcoming 2.5.0 release?  You can install the final RC using `pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121`.  There is no additional info or linked PRs here in the issue to do the validation
