### ISSUE TITLE
How to gracefully mask CompositeImplicitAutograd for different backends

### ISSUE THREAD

**Issue by yangxiaorun** [pytorch/pytorch#135098]
### 🐛 Describe the bug

I implemented torch.compile’s backend for my hardware via privateUserOne. I also found that torch.compile by default decomposes upsample_nearest2d into a bunch of small operators, just like _upsample_nearest does. But on my hardware, the _unsafe_index operator doesn’t perform well, so I’d like to be able to call the custom upsample_nearest2d operator directly for better performance. I don't know if this is a bug or if there could be a better implementation.

### Versions

It is irrelevant to the execution environment and is related to code implementation.

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by yangxiaorun** [comment]
I'll provide more details of the analysis in the next discussion.
https://discuss.pytorch.org/t/how-to-gracefully-mask-compositeimplicitautograd-for-different-backends/208651

**Comment by ezyang** [comment]
I'm putting this in the export mailbox because this is the thing people are always asking about in export which is to not decompose. We have a plan, please point this user to it

**Comment by angelayi** [comment]
You can do something like what we do [here](https://github.com/pytorch/pytorch/blob/main/torch/export/exported_program.py#L240-L261) to prevent decompositions on CompositeImplicitAutograd ops. But it seems like you already do something similar in your discussion post. Could you test this out to see if this works? cc @tugsbayasgalan 

As for why upsample_nearest2d is CompositeImplicitAutograd, I think it's because there isn't a derivative written for it? So instead it will get decomposed into other operators which have autograd rules written for them. cc @bdhirsh, please correct me if I'm wrong

**Comment by bdhirsh** [comment]
yep that's right - in theory you could use similar infra to what export is doing (cc @tugsbayasgalan) to disable those decomps.

Although in this narrow case of `upsample_nearest2d`, it looks like:

(1) we have a (long-standing) CIA decomp that goes from `aten.upsample_nearest2d.vec` -> `aten.upsample_nearest2d.default`

(2) it was tweaked in compile earlier this year to directly decompose into other ops like `unsafe_index` above autograd (which inductor can handle better) here: https://github.com/pytorch/pytorch/pull/122783

That new decomp is probably friendly to inductor, but may not be friendly to other backends. So @yangxiaorun another option here is to use the same overriding mechanism above - but instead of avoiding running any decomps at all, just use the (previous) decomp from `aten.upsample_nearest2d.vec` -> `aten.upsample_nearest2d.default`. Then you'll see `aten.upsample_nearest2d.default` in the graph, and you can provide your own lowering for it.

**Comment by yangxiaorun** [comment]
I fixed the problem this way.
https://gitee.com/ascend/torchair/pulls/1198
