### ISSUE TITLE
Cannot solve divisibility test on non-trivial expression

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#136044]
### 🐛 Describe the bug

Internal xref: https://fb.workplace.com/groups/6829516587176185/permalink/7886529994808167/

```
import torch

torch._dynamo.config.capture_scalar_outputs = True

@torch.compile(fullgraph=True)
def f(x):
    u0, u1 = x.tolist()
    torch._check_is_size(u0)
    if ((u0 + 10) * (u0 + 10)) % (u0 + 10) != 0:
        return torch.tensor(True)
    else:
        return torch.tensor(False)

f(torch.tensor([20, 21]))
```

A simple fix might be to avoid expanding at which point the divisibility is obvious. IDK.

cc @chauhang @penguinwu @isuruf 

### Versions

main

**Comment by ezyang** [comment]
cc @Chillee

**Comment by StrongerXi** [comment]
Currently the expression doesn't simplify because of the followings
1. Such `(a + c)^2` expressions are unconditionally expanded into `a^2 + 2ac + c^2`
   when Dynamo trace the corresponding bytecode instruction (`BINOP ...`)
2. When we construct the mod expression, we immediately get `Mod(u0**2 + 20*u0 + 100, u0 + 10)`,
   which won't get simplified down the line.

A few ways to fix this specific issue; each might likely break something else, but
then I'll learn more the constraints and workings of our symbolic shape system
1. don't expand during binop construction -- we already do it in
   `ShapeEnv.simplify`, which seems to be triggered when we really need the
   simplified expression, e.g., `SymNode.expect_true`. This way sympy can
   already simplify the unexpanded expr modulus upon construction. Moreover,
   we tend to lose high level simplifications if we expand early (like the one
   in this issue), and we'll expand in the end anyways to enable low level
   simplifications (e.g., additions cancelling). So maybe this is reasonable
   in general?
2. call `sympy.simplify(p / q)` in our own `Mod.eval`. I don't see a lot of
   calls to `sympy.simplify`, is it too slow?
3. create our own simplification logic for such cases `Mod(u0**2 + 20*u0 + 100, u0 + 10)`,
   which is a milder and more ad-hoc version of (b)

**Comment by ezyang** [comment]
from wc: not expanding is very interesting, but potentially a big yak. maybe worth a quick experiment

**Comment by StrongerXi** [comment]
- Update `benchmarks/dynamo/pr_time_benchmarks/expected_results.csv`
- Rebase over f3c3f3a3 for `inductor-A100-perf-nightly`
