### ISSUE TITLE
Remove cusparselt deprecated API usage

### ISSUE THREAD

**Issue by nWEIdia** [pytorch/pytorch#136553]
### 🚀 The feature, motivation and pitch

PyTorch is now using cusparseLt 0.6. 
The cusparseLt 0.6 has these two deprecated APIs that are currently used by pytorch:  https://docs.nvidia.com/cuda/cusparselt/functions.html#cusparseltspmmacompressedsize2-deprecated 
https://docs.nvidia.com/cuda/cusparselt/functions.html#cusparseltspmmacompress2-deprecated 

https://github.com/pytorch/pytorch/blob/9abdc62065e8e3860bc6aa189c5658d1479f6d9e/aten/src/ATen/native/sparse/cuda/cuSPARSELtOps.cpp#L88 
and 
https://github.com/pytorch/pytorch/blob/9abdc62065e8e3860bc6aa189c5658d1479f6d9e/aten/src/ATen/native/sparse/cuda/cuSPARSELtOps.cpp#L78 

### Alternatives

Using the recommended cusparselt APIs: 
https://docs.nvidia.com/cuda/cusparselt/functions.html#cusparseltspmmacompress and 
https://docs.nvidia.com/cuda/cusparselt/functions.html#cusparseltspmmacompressedsize

### Additional context

The isolation of a standalone https://github.com/pytorch/pytorch/blob/9abdc62065e8e3860bc6aa189c5658d1479f6d9e/aten/src/ATen/native/sparse/cuda/cuSPARSELtOps.cpp#L28 may also be problematic in the long run, as the documentation of cusparselt recommends: 

"Before 0.6.1 there's only one compression format for a tensor and therefore the compressed tensor can be used with all algorithms, but this is not the case anymore in 0.6.2." 

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip @ptrblck @msaroufim @eqy @Aidyn-A @syed-ahmed @malfet @atalman

**Comment by jcaip** [comment]
cc @nWEIdia 

Thanks for flagging this! One concern I have here is that in order to compress using `cusparseLtSpMMACompress` is that we need a reference to the matmul plan, which isn't needed for `cusparseLtSpMMACompress2`. 
The matmul plan needs the dense descriptor, but we don't know the activation shape until runtime. 

In our current workflow we prune and compress the matrix offline, using `torch._cslt_compress`, which calls `cusparseLtSpMMACompress2`. Compressing the matrix as part of the matmul will reduce our performance. 

I'm wondering if you have any thoughts on how to get around this problem? Happy to share more details.

**Comment by nWEIdia** [comment]
> cc @nWEIdia
> 
> Thanks for flagging this! One concern I have here is that in order to compress using `cusparseLtSpMMACompress` is that we need a reference to the matmul plan, which isn't needed for `cusparseLtSpMMACompress2`. The matmul plan needs the dense descriptor, but we don't know the activation shape until runtime.
> 
> In our current workflow we prune and compress the matrix offline, using `torch._cslt_compress`, which calls `cusparseLtSpMMACompress2`. Compressing the matrix as part of the matmul will reduce our performance.
> 
> I'm wondering if you have any thoughts on how to get around this problem? Happy to share more details.

Thanks @jcaip ! I imagine our cusparselt team would have considered such use cases when re-designing the API or they might have good suggestions to get the best performance possible even if this case was not considered. 
I have asked our cusparselt expert to help respond to this. Please stay tuned.

**Comment by j4yan** [comment]
Hi @jcaip 
Before 0.6.2, there's only one compression format for all gemm kernels and therefore the compression can be done without matmul plan. Since 0.6.2 we introduced more kernels to improve performance but they may have different compression format. 
That is, the compression depends on the algorithm and therefore matmulplan.

>> Compressing the matrix as part of the matmul will reduce our performance.
I don't know too much about the workflow, but with `cusparseLtSpMMACompress` the compression doesn't have to be part of matmul; it can be done offline with an initialized matmulplan.

**Comment by eqy** [comment]
@j4yan does this mean that the matmul e.g., shape etc. that is planned to be used must be known before the compression?

**Comment by nWEIdia** [comment]
It increasingly sounds like this feature request (to remove cusparselt deprecated API usage) would not make sense, as cusparselt new APIs do not fit PyTorch's needs?

**Comment by nWEIdia** [comment]
Looks like the existing API use case is an important one that there is no hurry to remove cusparselt deprecated API usage. 
If the need arises again and no alternatives are available, I will re-open this feature request.
