### ISSUE TITLE
nn.html page has too much content

### ISSUE THREAD

**Issue by karlind** [pytorch/pytorch#13712]
## 📚 Documentation

[https://pytorch.org/docs/stable/nn.html](https://pytorch.org/docs/stable/nn.html) this page contains too much content, every time I open this page my browser almost freezes. There are many sub topics stacked in one page, can this page be divided into some sub pages so that every page hold a separate topic? This page is pretty useful, but it always freezes...

**Comment by jatentaki** [comment]
I second this. At least the `functional`  part could go to an entirely new webpage
1. most items there have a link to relevant "objective" `nn` item anyway
2. they double the keywords in objective `nn`, which means even ctrl+f doesn't really do it's job

Another pain point is that (at least in firefox) the math formulae are rendered after the page itself, which interacts with links. When I click a link to an item halfway through the `nn` page (often from the corresponding `functional` item), I will be directed to the right item, and after a second it will slide off my screen due to all the formulae above expanding and taking its place. Not that I have a good idea how to deal with that...

**Comment by suo** [comment]
Seems reasonable, I'll take a stab at sharding the docs in the next few days

**Comment by Chillee** [comment]
https://github.com/pytorch/pytorch/issues/20984 is tracking the same issue. Closing this one in favor of that one.
