### ISSUE TITLE
Dynamo fails to propagate updates to nonlocal variables across different functions

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#138112]
### 🐛 Describe the bug

When two functions, `A` and `B`, share a `nonlocal` variable `z`, an update in one function does not always propagate to the other. For instance, in the reproducer below, `run_fn` updates `z` to `3`. However, when `fn` assigns `k = z`, it references the old value of `z.

### Reproducer

```python
import torch

def nonlocal_test():
    z = 1
    k = 2

    def create_fn():
        def fn(x):
            nonlocal k, z
            k = z
        return fn

    def run_fn(fn, x):
        nonlocal z
        z = 3
        fn(x)
        return x.cos()

    @torch.compile(backend="eager", fullgraph=True)
    def foo(x):
        fn = create_fn()
        return run_fn(fn, x)

    x = torch.randn(2, 3)
    foo(x)
    print(f'{z=} - {k=}')
    assert z == 3
    assert k == 3  # `k` still references the previous value of `z` (1)

nonlocal_test()
```

This seems to be ok for globals.

### Versions

main

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

**Comment by ezyang** [comment]
cc @williamwen42

**Comment by williamwen42** [comment]
@StrongerXi do you want to take a look?

**Comment by StrongerXi** [comment]
Here's what happened:

First see
https://github.com/pytorch/pytorch/blob/2b7c7a20b9c0e8e7f2773ffc5c9f79c3cae2070b/torch/_dynamo/variables/functions.py#L263-L266

The above optimization needs `closure_cell_contents.name()` and the cell to have 1-to-1 mapping. However, we could have multiple `UserFunctionVariable`s that refers to the same cell, and those `closure_cell_contents.name()` would differ because they have different sources.

In this issue's example, `z` is captured by both `create_fn` and `run_fn`, and respectively the `closure_cell_contents.name()` are:
- `"L['create_fn'].__closure__[1].cell_contents"`
- `"L['run_fn'].__closure__[0].cell_contents"`

So eventually Dynamo would restart tracing twice (because of the 2 writes `k = z` and `z = 3`), and in the final round of tracing, its `mutated_closure_cell_contents` contains
- `"L['run_fn'].__closure__[0].cell_contents"`
- `"L['create_fn'].__closure__[0].cell_contents"`

So when Dynamo inline-traces `fn = create_fn()`, the `UserFunctionVariable` for `create_fn` would see that for _its_ `z`, the source `"L['create_fn'].__closure__[1].cell_contents"` is not in `mutated_closure_cell_contents`, so it'll model `z` as its content `1` (stored as a `ConstantVaribale` as part of the `NestedFunctionVariable` for `fn`). This causes the effect of the subsequent `z = 3` to escape inliner of `fn(x)`, and consequentially causes `k = z` to be interpreted as `k = 1`.

**Comment by StrongerXi** [comment]
So I have some idea about either removing or replacing this optimization with something else, which should solve this issue and #137456.

But for this specific issue, I think we can get away by replacing `closure_cell_contents.name()` with `id(cell)`, which should serve as a truly unique identity here (since `cell` exists prior to dynamo tracing, it shouldn't go out of scope during tracing, so `id(cell)` should be safe..?)
