### ISSUE TITLE
[docs] Error in doc in formula for torch.frac()

### ISSUE THREAD

**Issue by TomekOs** [pytorch/pytorch#13968]
## 📚 Documentation

a = torch.tensor([-3.2])
frac_from_torch = torch.frac(a)
frac_from_doc = a - torch.floor(a)

print("Frac() calculated by Pytorch:", frac_from_torch)
print("According to Pytorch documentation frac() is calculated as: a - torch.floor(a) whis is:", frac_from_doc)
print("Those two values are not equal! I believe there is an error in Pytorch documentation in formula for frac() method/function.")
print("https://pytorch.org/docs/stable/torch.html#torch.frac")

**Comment by rohan-varma** [comment]
It looks like the issue here is how `torch.frac` and `torch.floor` deal with negatives - `torch.floor` seems to "round down" and truncates a negative value to the next smallest negative number (i.e. `-3.2 becomes -4`), while `torch.frac` seems to truncate `-3.2 to -3` explaining why the output of `torch.frac(torch.Tensor([-3.2]))` is `-0.2`.

**Comment by ailzhang** [comment]
cc: @soumith  @gchanan @fmassa I came across this in testing xla. IMHO we should fix it in 1.2 release. 
The easiest thing to do is fixing the doc as numpy doesn't have a `frac` method. It has `numpy.modf` which does a similar thing as our `frac`, and for the inconsistent `frac` formula we have in doc, that indeed match `numpy.divmod` behavior. 
Let me know if you have any preference here, I can send a quick fix if we have agreement on which behavior to keep.

**Comment by gchanan** [comment]
@ailzhang ya, let's fix the docs.  It would be better if we added those functions torch and referred to them in the docs, but fixing the docs should be sufficient for now.
