### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled - macOS Sequoia 15.1.1 (intel, AMD)

### ISSUE THREAD

**Issue by SkyForceCoder** [pytorch/pytorch#141973]
### 🐛 Describe the bug

I found an issue while working with the HunyuanVideo repository. The repository relies on PyTorch's CUDA functionality, which leads to compatibility issues on macOS systems using Intel or AMD GPUs (such as the Radeon Pro Vega 56). Since PyTorch does not support CUDA on non-NVIDIA GPUs, this results in errors when trying to move the model to the GPU.

I’ve created an issue on the repository related to this problem: [HunyuanVideo Issue #22](https://github.com/Tencent/HunyuanVideo/issues/22).

Expected Behavior:
It would be great if the repository could add support for Intel/AMD GPUs on macOS, leveraging Metal for GPU acceleration. This would ensure that macOS users with Intel or AMD processors can use the repository without encountering issues related to missing CUDA support.

**Environment:**

> **Processor:**

Model: Intel(R) Xeon(R) W-2140B CPU
Speed: 3.20 GHz
Cores: 8 cores (with Hyper-Threading enabled)

> **Memory (RAM):**

Total RAM: 32 GB (34359738368 bytes)

> **GPU:**

Model: Radeon Pro Vega 56
VRAM: 8 GB
Bus: PCIe (x16)
Metal Support: Metal 3 (supports Apple's graphics framework)

### Versions

2.1.1

cc @seemethere @malfet @osalpekar @atalman @albanD

**Comment by malfet** [comment]
CUDA support were always limited to NVIDIA GPUs, and last CUDA version with MacOS support were CUDA-10.2, and to the best of my knowledge, ROCm were never available on MacOS

I guess, what you are looking for is https://pytorch.org/docs/stable/notes/mps.html backend, which could be used to accelerate workflows on GPUs, but alas we no longer building nor testing PyTorch on Intel Macs because they are much harder to come by in the cloud, see https://github.com/pytorch/pytorch/issues/114602

Supporting Intel Macs going forward feels like a great discussion topic, please do not hesitate to keep discussing it on https://discuss.pytorch.org/
