### ISSUE TITLE
inductor-rocm workflows failing in "configure aws credentials" step (OIDC)

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#142016]
We are seeing _inconsistent_ failures for the inductor-rocm workflows.

**Failing examples:**
https://github.com/pytorch/pytorch/actions/runs/12125789348/job/33860895576?pr=140172
`Secret source: None`
```
It looks like you might be trying to authenticate with OIDC. Did you mean to set the `id-token` permission? If you are not trying to authenticate with OIDC and the action is working successfully, you can ignore this message.
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

**Working example:**
https://github.com/pytorch/pytorch/actions/runs/12145650264/job/33869370513
`Secret source: Actions`
```
Assuming role with OIDC
Authenticated as assumedRoleId AROAUPVRELQNLLCOPFEJR:GitHubActions
```

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

**Comment by xinyazhang** [comment]
Analysis:

The `Secret source: None` is the most suspicious part of the log, which is the determining line to separate success/fail cases:

All runs with `Secret source: Actions` succeeded, and all runs with `Secret source: None` failed.

After digging a little bit, I found  for success cases the `inputs` of `get-label-type / runner-determinator` uses the branches from the pytorch repo, either created by users, or copied by pytorch-bot from forked repo in the name of `ciflow/**`.

I also realized the failed cases are initiated by users other than pytorch-bot, and use the branch from the forked repo.

Then I recalled this from GitHub Action's documentation
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

Now the problem is how to ensure the workflow is always triggered by pytorch-bot which will perform the copy of branch, instead of running the workflow on forked repo's branch which will stop the workflow using the non-GITHUB_TOKEN secrets.

**Comment by jithunnair-amd** [comment]
Should be resolved by https://github.com/pytorch/pytorch/pull/143205

**Comment by huydhn** [comment]
Yes, @clee2000 PR fixes this.  The difference here is that:

* Use a pull_request trigger with path will use the fork branch, which fails OIDC (it trusts only pytorch/pytorch)
* On the other hand, when ciflow/inductor-rocm is used, the bot will pushed to a branch on `pytorch/pytorch`, thus passing the check.

If a trigger using file path is needed, we can have it in autolabel bot https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/autoLabelBot.ts#L24
