### ISSUE TITLE
Inconsistent description of AMSGrad with code

### ISSUE THREAD

**Issue by Tony-Y** [pytorch/pytorch#142323]
### 📚 The doc issue

https://github.com/pytorch/pytorch/blob/0bd7b7ae58970f565eb22766549ad9d6d2e23fe6/torch/optim/adam.py#L469-L476

In the code, the bias correction term $1-\beta_2^t$ is used after the max operation. However, [the documentation](https://pytorch.org/docs/main/generated/torch.optim.Adam.html#adam) describes that it is used before the max operation:
<img width="254" alt="max operation" src="https://github.com/user-attachments/assets/77e6016d-b225-4aa3-b507-d8fc49d1d4fd">

### Suggest a potential alternative/fix

<img width="500" alt="amsgrad algo notes" src="https://github.com/user-attachments/assets/4aeedca2-457d-4bca-8f7e-a879bae45ef4">

cc @svekars @brycebortree @sekyondaMeta @AlannaBurke @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

**Comment by Tony-Y** [comment]
$\widehat{v_{t}}$ may be used instead of $\widehat{v_{t}}^{max\ \ }$ in order to simplify the description:
<img width="500" alt="amsgrad algo2 notes" src="https://github.com/user-attachments/assets/28ad7e59-e8d1-438d-a6ac-83216b4fa490">

**Comment by Tony-Y** [comment]
By the way, `optax` implements the AMSGrad algorithm described in PyTorch 2.5 docs:
https://github.com/google-deepmind/optax/blob/78fe20e75c79b2f615bcd9e8a653af9d988f8992/optax/_src/transform.py#L356-L361

**Comment by janeyx99** [comment]
To be clear, the actual math is equivalent between the docs and the code, right? The v_max thing is consistent in docs + computation even though the order is different, since dividing by a constant doesn't affect the max, yes?

By the way, we don't actually have guarantees on the code and the docs being exactly matching (as I'm sure you'll find other instances of this) and it is okay for them to not match to allow the code to take performance wins and for the docs to be more readable. In this case, your suggestions are more readable so let me go review ur PR 😛

**Comment by Tony-Y** [comment]
Not equivalent. The bias correction term is not a constant. It depends on `t`. 
```python
>>> t = [1, 2, 3]
>>> v = [5, 4, 3]
>>> b2 = 0.5
>>> vmax = 0
>>> for i in range(3):
...     vmax = max(vmax, v[i]) / (1-b2**t[i])
...     
>>> vmax
15.238095238095239
>>> vmax = 0
>>> for i in range(3):
...     vmax = max(vmax, v[i] / (1-b2**t[i]))
...     
>>> vmax
10.0
```

**Comment by janeyx99** [comment]
ah........in that case we should make sure our calculation is aligned with the AMSGRAD paper if possible.

**Comment by Tony-Y** [comment]
The PyTorch implementation is similar to Tensorflow one:
https://github.com/keras-team/keras/blob/f6c4ac55692c132cd16211f4877fac6dbeead749/keras/src/optimizers/adam.py#L130-L150

The AMSGrad paper does not mention any bias correction.
