### ISSUE TITLE
[feature request] RePr convolution method

### ISSUE THREAD

**Issue by mwmuni** [pytorch/pytorch#14303]
## 🚀 Feature

Implementation of RePr as a toggleable option for convolutional layers.

## Motivation

RePr appears to promote a good improvement to generalization speed for general use.

## Additional context

Arxiv Link: [RePr: Improved Training of Convolutional Filters](https://arxiv.org/pdf/1811.07275.pdf)

**Comment by 994374821** [comment]
How to use RePr with pytorch? Thanks

**Comment by YijiaZhao** [comment]
I also want to know how to use it

**Comment by SunAriesCN** [comment]
Mark

**Comment by nan0755** [comment]
mark

**Comment by samlong-yang** [comment]
Mark

**Comment by ezyang** [comment]
@soumith could you look at this?

**Comment by ezyang** [comment]
(and @fmassa too)

**Comment by fmassa** [comment]
I don't see this as something that should be added to core PyTorch, but more to a full training framework for classification.

**Comment by soumith** [comment]
I concur with @fmassa 

Basically, the way RePR needs to be implemented is in the training loop:

```python
for iter, input, target in enumerate(dataset):
    reprune(model, iter)
    loss(model(input), target).backward()
    optim.step()
```

(I am simplifying the implementation here for discussion).

The reason is because it needs knowledge of "iterations", and I can see follow-up methods might want whole graph analysis (for example seeing multiple layers of conv weights at once).

Secondly, RePR doesn't have **any** citations yet, even though it's been around for a year. I am not entirely sure why, because the method looks interesting. Keeping with our policy of only including well-established baselines in the industry, this wont go into pytorch/pytorch

If someone is motivated, I would suggest implementing it into contrib: https://github.com/pytorch/contrib
