### ISSUE TITLE
[fsdp2] mixed precision reduce dtype is clamped before lazy init

### ISSUE THREAD

**Issue by leonardo0lyj** [pytorch/pytorch#143277]
Hi Andrew @awgu 😊,

As a big fan of fsdp2, I found an potential issue in mixed precision in context of lazy init:

- ideally, fsdp2 allows user to change param dtype after initialization but before forward, so comes the lazy init of mixed precision's `param_dtype`
(https://github.com/pytorch/pytorch/blob/d745b2b5163e821585d0701ebaf16a38f4d57eab/torch/distributed/fsdp/_fully_shard/_fsdp_param.py#L418)

- however, the mixed precision's `reduce_dtype` is set in `post_init` of MixPrecision dataclass (before lazy init) and but still depends on the `param_dtype` (which is clamped during lazy init), thus causing logical complexity and potential bugs:
https://github.com/pytorch/pytorch/blob/d745b2b5163e821585d0701ebaf16a38f4d57eab/torch/distributed/fsdp/_fully_shard/_fsdp_api.py#L50

- no sure we can move clamp of `reduce_dtype` into lazy init as well, i.e., after clamping `param_dtype`, which simplifies logic and enhances debugability.

Thanks 🙏

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @zhaojuanmao @mrshenli @rohan-varma @chauhang

**Comment by awgu** [comment]
@leonardo0lyj so I can make this change, but I am actually curious now what is the example that broke this.

Suppose we start with `mp_policy = MixedPrecisionPolicy(param_dtype=torch.bfloat16, reduce_dtype=torch.bfloat16)`. The current `__post_init__` will clamp `reduce_dtype` to `None`.

If we want to change the `model` dtype after init but before `forward`, I would guess that we are either changing from fp32 -> bf16, or we are changing from bf16 -> fp32.
- Suppose we are changing from fp32 -> bf16. Then, at lazy init, `param_dtype` will be clamped to `None`. `reduce_dtype` being `None` is still correct, as reduce-scatter will be done in `param_dtype`, which is the "original dtype" (at lazy init), which is bf16.
- Suppose we are changing from bf16 -> fp32. Then, at lazy init, `param_dtype` will not be clamped to `None`. `reduce_dtype` being `None` is still correct, as reduce-scatter will be done in `param_dtype`, which is bf16.

I am asking this because I am having trouble to come up with a good unit test.  The change itself should not be too hard.

**Comment by leonardo0lyj** [comment]
@awgu Thanks for lightning reply : )

As a counter example,

* Suppose we have original model parameters in torch.float32.

* Somehow user uses mp_policy = MixedPrecisionPolicy(param_dtype=bfloat16, reduce_dtype=torch.bfloat16). The current __post_init__ will clamp reduce_dtype to None.

* After init but before forward, users change param from bfloat16 to float8.

* At lazy init, param_dtype stays float8, not clamped. reduce_dtype stays None.

* Now reduce-scatter will be done in param_dtype (float8), as reduce_dtype is None, which is not the promosed reduce_dtype=torch.bfloat16

**Comment by awgu** [comment]
> After init but before forward, users change param from bfloat16 to float8.

Do you mean change from float32 to float8? (since the original model parameters are in float32, so I assume that the change must be from float32)

**Comment by awgu** [comment]
The introduction of float8 as a third dtype involved in this is what I was missing. This example makes sense. I think I can just land my PR then.
