### ISSUE TITLE
What happened to symbolic_override?

### ISSUE THREAD

**Issue by szali** [pytorch/pytorch#14338]
## 🐛 Bug

symbolic_override was removed but no mechanism is provided (at least not in a documented way) to replicate its function, i.e. to specify that a Python function should be exported as a whole, as a specific ONNX op, instead of a traced graph.

## To Reproduce

1. Use symbolic_override
2. Pull torch master
3. symbolic_override no longer works

## Expected behavior

symbolic_override still exists or there is a way to emulate it.

## Environment

PyTorch version: 1.0.0a0+8e1e3ba
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.0-rc2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 396.26
cuDNN version: 7.2.1

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[pip3] torch (1.0.0a0+8e1e3ba)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.1.9)
[conda] Could not collect

## Additional context

symbolic_override was removed here:
https://github.com/pytorch/pytorch/pull/13441
specifically:
https://github.com/pytorch/pytorch/pull/13441/commits/59b75397e1045a2b459c0449bf59b9889fd3ecd6

One can use a torch.autograd.Function but then you have to implement the backward separately which I want autograd to do automatically. The only thing I need is that the function is exported as a single onnx operation.

**Comment by soumith** [comment]
cc: @houseroad @zrphercule

**Comment by houseroad** [comment]
I think adding a symbolic function for the nn.Module should still work. Will create an example to explain it.

**Comment by szali** [comment]
> I think adding a symbolic function for the nn.Module should still work. Will create an example to explain it.

Thanks, I did not know about that. Indeed an example would be quite helpful.

**Comment by houseroad** [comment]
right now, only `Function` supports module symbolic override. You can find examples here: https://github.com/pytorch/pytorch/tree/master/caffe2/contrib/aten#example-usage-via-pytorch-symbolic

However, using symbolic override is not encouraged, since it means you will modify the jit IR directly through symbolic. You should understand what change you will bring to the IR graph when overriding the symbolic.

**Comment by hessamb** [comment]
@houseroad 
Thanks for sending out this example.
I have one question. How do I define a symbolic node for an `autograd.Function` that consists of operations that are not already supported by ONNX? It seems like the new `symblic` static method is called during the graph optimization time. So I'm reading as if the `autograd.Function` has some operations in the forward that are not supported by the ONNX exporter, it will barf before it gets to the optimization step.

For instance, the following script barfs because there's a `masked_fill_` in the forward pass, that is not known to ONNX:
```
import numpy as np

from torch import nn
from torch.autograd import Variable, Function

import onnx


class MyFunction(Function):

    @staticmethod
    def forward(ctx, x, y):
        x = x.clone()
        x.masked_fill_(y > 0, 0)
        return x*x + y

    @staticmethod
    def symbolic(graph, x, y):
        return graph.op("MyFunction", x, y)


class MyModule(nn.Module):
    def forward(self, x, y):
        # you can combine your ATen ops with standard onnx ones
        x = nn.ReLU()(x)
        return MyFunction.apply(x, y)


import torch.onnx
torch.onnx.export(MyModule(),
                  (Variable(torch.ones(3,4)), Variable(torch.ones(3,4))),
                  "output.onnx",
                  verbose=True)
```
with the exception:
```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    verbose=True)
  File "/path/to/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/path/to/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/path/to/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/path/to/torch/onnx/utils.py", line 227, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/path/to/torch/onnx/utils.py", line 132, in _optimize_graph
    torch._C._jit_pass_constant_propagation(graph)
RuntimeError: 
Schema not found for node. File a bug report.
Node: %9 : Float(3, 4) = aten::masked_fill(%5, %7, %8), scope: MyModule

Input types:Float(3, 4), Byte(3, 4), int
candidates were:
graph(%input : Float(3, 4)
      %y : Float(3, 4)) {
  %2 : float = prim::Constant[value=0](), scope: MyModule/ReLU
  %3 : float = prim::Constant[value=0](), scope: MyModule/ReLU
  %x : Float(3, 4) = aten::threshold(%input, %2, %3), scope: MyModule/ReLU
  %13 : Float(3, 4) = ^MyFunction()(%x, %y), scope: MyModule
  %5 : Float(3, 4) = aten::clone(%x), scope: MyModule
  %6 : int = prim::Constant[value=0](), scope: MyModule
  %7 : Byte(3, 4) = aten::gt(%y, %6), scope: MyModule
  %8 : int = prim::Constant[value=0](), scope: MyModule
  %9 : Float(3, 4) = aten::masked_fill(%5, %7, %8), scope: MyModule
  %10 : Float(3, 4) = aten::mul(%9, %9), scope: MyModule
  %11 : int = prim::Constant[value=1](), scope: MyModule
  %12 : Float(3, 4) = aten::add(%10, %y, %11), scope: MyModule
  return (%13);
}
```
But if I comment out the `masked_fill_`, I get a very clean ONNX export:
```
graph(%input : Float(3, 4)
      %y : Float(3, 4)) {
  %2 : Float(3, 4) = onnx::Relu(%input), scope: MyModule/ReLU
  %3 : Float(3, 4) = onnx::MyFunction(%2, %y), scope: MyModule
  return (%3);
}
```

Am I reading all this right? Is there a way to get the same functionality of `symbolic_override` that existed in `torch=0.4.0`?

I'm on `torch==1.0.1.post2` stable release.

**Comment by hessamb** [comment]
I was reading it wrong.

Future readers, if you're having the same problem, it's a bug related to `masked_fill_` operation, just like the exception message says. I got around it by using `x[mask] = value` instead of `masked_fill_` function.
