### ISSUE TITLE
Unable to print half tensors

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#14344]
## 🐛 Bug

Earlier, a bug was reported (https://github.com/pytorch/pytorch/issues/12093) about not being able to print large half Tensors. Now, half Tensors cannot be printed at all.

## To Reproduce

```python
>>> import torch
>>> a = torch.randn(1)
>>> print(a.half())
RuntimeError: s__th_eq is not implemented for type torch.HalfTensor
```

## Expected behavior

Tensors should be printed, at least small ones.

**Comment by bhushan23** [comment]
s__th_eq is called because of == is torch.isfinite which is being called from _tensor_str : _Formatter
Just to give out the options 
1. Implement all relevant functions for half tensors as well (faster- for now)
      e.g. _th_eq, _th_cat, abs_out
2. Smart way to re-use the existing methods  (more discussion needed hence longer)
      - Good design (IMO) base tensor class with all generic function implemented to be re-used.
      - Make a friend class?

I am exploring th_ arena for the first time, so I might be wrong.

**Comment by bhushan23** [comment]
@fmassa I thought we don't want to convert it to float and instead declare th_* specific functions for half

**Comment by soumith** [comment]
@bhushan23 for printing purposes it seemed irrelevant, hence we just used float cast

**Comment by bhushan23** [comment]
makes sense. Now, we only need to expose th_ methods for cat and other similar operations, right?
have anyone audited all the methods that needs support?
