### ISSUE TITLE
torch.multiprocessing.spawn should clean up orphaned processes when daemon=False

### ISSUE THREAD

**Issue by teng-li** [pytorch/pytorch#14394]
We should get this fixed as well. Passing to you to investigate since you wrote the spawn class @pietern 

CC: @ppwwyyxx

**Comment by ppwwyyxx** [comment]
Behavior:
With https://github.com/pytorch/pytorch/pull/14391 patched (daemon=False),  run this command in pytorch/examples:
`python main.py -a resnet18 --lr 0.01 --dist-url 'tcp://127.0.0.1:12345' --dist-backend 'nccl' --multiprocessing-distributed /path/to/data/imagenet/ -j 0`

After training has started, Ctrl-C to kill it. Some processes are left.

When `daemon=True`, no processes are left (because daemonic processes will get automatically killed).

**Comment by pietern** [comment]
@ppwwyyxx Can you try out the patch in #14491? I just tried your command and didn't see any remaining processes after a SIGINT. I think the fix works but extra confirmation would be great.
