### ISSUE TITLE
Example_inputs in JIT trace

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#14476]
## 📚 Documentation
At https://github.com/pytorch/pytorch/blob/master/torch/jit/__init__.py#L564-L568 is declared that the resulting trace can be run with inputs of different types and shapes.

So can we use an arbitrary input at trace time? If yes it seems that currently there is any optimization related to the exact input size (and so also to the batch size), right? 
Is there a plan to introduce features in JIT that could impact the performance with mismatching input shape on trace and inference?

**Comment by bhack** [comment]
Also it is not clear if tracing on CPU and inferencing on GPU or the inverse will create any optimization inefficiency.

**Comment by apaszke** [comment]
JIT is designed in such a way that it will not specialize to particular shapes/types/devices at parsing/tracing time, so you're safe to pass in inputs with various configurations. For some of those (most notable when any input changes the number of dimensions, dtype or device) you will see recompilation happen, but it will *not happen* just because you changed a size along a single dimension.

**Comment by bhack** [comment]
@apaszke What about GPU/CPU tracing?

**Comment by soumith** [comment]
@bhack 
> it will not specialize to particular shapes/types/devices at parsing/tracing time

that covers devices

**Comment by bhack** [comment]
@soumith But I see also 
> For some of those (most notable when any input changes the number of dimensions, dtype or device)
