### ISSUE TITLE
clamp returns empty tensor if no min or max limit

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#14470]
## 🐛 Bug

```
t=torch.tensor([-1, 0, 1])
torch.clamp(t,None,None)
tensor([], dtype=torch.int64)
```
If no min or max, an empty tensor returned. (by design?)
The in-place method behaves more as I would expect, leaving the tensor as is:

```
t.clamp()
tensor([], dtype=torch.int64)
```
```
t.clamp_(None,None)
tensor([-1,  0,  1])
```

**Comment by SsnL** [comment]
This is a bug.

**Comment by zou3519** [comment]
I don't know what the old behavior of this was but it should definitely get fixed

**Comment by yf225** [comment]
This throws `RuntimeError: At least one of 'min' or 'max' must not be None` on both 0.4.0 and 0.4.1, so this is a recent bug.

**Comment by zou3519** [comment]
We should fix it to disallow this case as well then. Not a release blocker but nice to have.

**Comment by YodaEmbedding** [comment]
`RuntimeError: torch.clamp: At least one of 'min' or 'max' must not be None`

It would be nicer to just be the identity function (instead of raising an error) if the user does `x.clamp()`.

Example use case:
```python
def normalize(x, eps=None):
    x = (x - mu) / std.clip(min=eps)
```

...Unfortunately, this raises an error if the user doesn't explicitly specify some epsilon. (Of course, in this particular example, eps=0 would work as a default since std≥0 anyways, but this is just an example.)
