### ISSUE TITLE
Optimizer state dict should be defaultdict when loading

### ISSUE THREAD

**Issue by nitishgupta** [pytorch/pytorch#1488]
The state attribute in the opt. class is a defaultdict which helps to add new parameter states in the state dict as they are being used while training. Once the optimizer's state_dict is saved and loaded, the state attribute is a dict and not a defaultdict which assumes that before saving, all the parameters in the network are present in the state dict. 

When loading the opt. using a saved state_dict the state attribute should be a defaultdict. 
I currently do the following to have this behavior

`o.load_state_dict(torch.load(path))`
`o.state = defaultdict(dict, o.state)`

Corresponding [PyTorch-Discuss post](https://discuss.pytorch.org/t/possible-issues-in-optimizer/2685)
@soumith

**Comment by randxie** [comment]
Hi all, it is my first time trying to contribute to an open-source project. I took a look on the bug. It seems that it is related to the function "state_dict()" of class "optimizer.py". When the state is transformed to packed_state, it uses dict instead of defaultdict, which is inconsistent with the type of state.

The solution I am proposing is to let the packed_state be defaultdict to maintain consistency with self.state. Here is my proposed change:

**packed_state = defaultdict(dict, {(id(k) if isinstance(k, Variable) else k): v for k, v in self.state.items()})**

Is there anything I am missing? Is "run_test.sh" in the pytorch/test enough to validate my change? Where could I add a test point to ensure the type of state remain the same after saving and loading? Thanks a lot for your patience.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/2796 thanks to @randxie !!

Thanks a lot @randxie !
