### ISSUE TITLE
DataParallel does not effectively use GPU RAM on device_id 1

### ISSUE THREAD

**Issue by elistevens** [pytorch/pytorch#1499]
Example program here: https://gist.github.com/elistevens/d20debf24b82d57b06913cfa34da2662

Note that the GPU 1 RAM used does not significantly change with calling `loss_var.backward()` with any combination of `0` or `1` `Variables`, nor with increasing the number of models.

I don't think the problem is explicitly with `.backward()` since the problem still happens just by calling `model.forward()` (in the `... in {None}` cases from the gist).

The end result is that training bottlenecks on GPU 0 RAM usage, even though there is free GPU RAM on the other device(s).

I'm using:
http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp35-cp35m-linux_x86_64.whl
Ubuntu 16.04
nvidia-375 from the graphics-drivers PPA
2x GTX 1080

**Comment by apaszke** [comment]
This looks ok for me - the reason why you're seeing that is because parameters for all ResNet clones are permanently stored on the first device, but are broadcast to the second one only when DataParallel is is forward, and are freed immediately afterwards. Since you only run at most a single forward at a time, the memory usage on the first GPU scales nearly linearly with the number of models (storage for parameters), while usage on the second one should stay constant (storage for a single copy of parameters).

**Comment by elistevens** [comment]
> parameters for all ResNet clones are permanently stored on the first device
Right, this is the issue. I want to be able to tell DataParallel to use a different device (or keep the model cpu in pinned memory or something, whatever doesn't bottle neck on one device's RAM).

I'm guessing that all of the models being on GPU 0 is also why calling `.backward()` also only seems to use GPU 0 RAM.

**Comment by apaszke** [comment]
`.backward()` uses memory of both devices, but it's still a constant + it barely uses any memory, because it will reuse the freed buffers from last layers to compute grads of all previous ones.

**Comment by apaszke** [comment]
About the second thing, you can call `.cuda(1)`, but then you need to tell the DataParallel that your devices are `[1, 0]`, not `[0, 1]` (default in your case).

**Comment by xu-ji** [comment]
Actually never mind, I just updated to pytorch 0.4.1 (from 0.3.0) and the spread is much more even now, I guess you have improved DataParallel.
