### ISSUE TITLE
Torchscript tutorial

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#15006]
## 📚 Documentation
I've built over the official Torchiscript c++ tutorial adding a loop to test performances:
- CPU input tensor
- `.to` GPU
- `.forward`
-  output back `.to` CPU.
 I've used non-blocking flags and `pin_memory()` for the input tensor.
When I was profiling with Nividia tools I see that we have no Kernel Computer and host to device overlap in the loop (so mainly in the output to CPU execution).
Is it not documented other then "use non-blocking flags" so I want to ask for a simple loop that can overlap gpu->cpu transfer an kernel computiation.
To confirm this I've commented the last step (output .to CPU) and with that I can have a reach a full compute load of the GPU.
/cc @goldsborough

**Comment by bhack** [comment]
Also without [`is_pinned()`](https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L210) availability in c++ I cannot directly test if:
```
auto output_cpu = torch::empty_like(output_gpu, at::kByte).pin_memory();
output_cpu = out_gpu.to(at::kCPU, at::kByte, true);
```
is the same as (cause it is implicitly pinned) :
```
auto output_cpu = out_gpu.to(at::kCPU, at::kByte, true);
```

**Comment by suo** [comment]
Hi! Sorry for the late response, this fell between things during the holidays. Thanks for bringing this stuff to our attention—we have put is_pinned() on our list of potential feature enhancements. As for StreamGuards, working with multiple streams is not super well supported in TorchScript now, it's definitely something we'll take a look at.

I'm going to close this for now since there's no immediate action we plan to take. Anyone should feel free to comment/reopen and we'll take it as signal that people want these changes and prioritize accordingly
