### ISSUE TITLE
Support torch.abs for ByteTensor, CharTensor

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#15089]
**UPD:** for torch.isinf I filed another issue: https://github.com/pytorch/pytorch/issues/15123

This is on `1.0.0a0+9d9e5f8`. (Can't update to 1.0 yet because of https://github.com/pytorch/pytorch/issues/14995#issuecomment-446413669)

 ```
  File ".../vadim/env/lib/python3.7/site-packages/torch/functional.py", line 288, in isinf
    return tensor.abs() == inf
RuntimeError: _abs_out is not implemented for type torch.ByteTensor
```

I think it makes sense to support `abs` on ByteTensor, even if it's a no-op. And it definitely makes sense to support `isinf` - to allow for some generic code.

**Comment by vadimkantorov** [comment]
confirmed on master

**Comment by soumith** [comment]
abs, I agree.
But isinf, really? that makes no sense.

**Comment by vadimkantorov** [comment]
isinf would be useful for some generic guard checks

**Comment by vadimkantorov** [comment]
and the fix is super-easy:
```python
if tensor.dtype in [torch.uint8, torch.int16, torch.int32, torch.int64]:
   return torch.zeros_like(tensor, dtype = torch.uint8)
```

**Comment by vadimkantorov** [comment]
Also NumPy doesn't break on integral tensors:
```
>>> np.isinf(np.array([1, 2, 3], dtype = np.int32))
array([False, False, False])
>>> np.isinf(np.array([1, 2, 3], dtype = np.int64))
array([False, False, False])
>>> np.isinf(np.array([1, 2, 3], dtype = np.uint8))
array([False, False, False])
```

**Comment by surgan12** [comment]
@vadimkantorov would adding the types to declarations.cwrap be a fix to this ?

**Comment by gchanan** [comment]
@surgan12 porting it to ATen would be better.

**Comment by hameerabbasi** [comment]
If someone isn't working on this I'd be willing to take it on.

**Comment by hameerabbasi** [comment]
(It'd be nice if someone could point me to the current code for `abs`).

**Comment by fmassa** [comment]
Hi @hameerabbasi 

This task is currently assigned to @ericnakagawa , and I believe it will be worked on soon.

Thanks for offering to tackle this issue though! Just pick an issue tagged as `good first issue` that hasn't been assigned to someone yet, and that should be a good start!

**Comment by fmassa** [comment]
So, here is how we should go into addressing this issue:

There are two implementations of `torch.abs` that would need to be improved: one for CPU, and one for CUDA. As it turns out, I believe the CUDA implementation is already done, so you'll probably only need to handle the CPU part.

Here is where the CPU part is implemented for  `int64`, `int32` and `int16` types:
https://github.com/pytorch/pytorch/blob/0d366e1bde42265d764a6a9aad27a38753156fb0/aten/src/TH/generic/THTensorMoreMath.cpp#L1403-L1409

I believe you basically need to add support for the `Char` type (`int8`), and the implementation for `Byte` (or uint8) will be simply the identity function (because `Byte` is unsigned).

For CUDA, the function is defined in
https://github.com/pytorch/pytorch/blob/0d366e1bde42265d764a6a9aad27a38753156fb0/aten/src/THC/generic/THCTensorMathPointwise.cu#L70
which dispatches the implementation to THCNumerics, which it turns out already implements `abs` for `int8` and `uint8` types
https://github.com/pytorch/pytorch/blob/0d366e1bde42265d764a6a9aad27a38753156fb0/aten/src/THC/THCNumerics.cuh#L85
so it seems that the CUDA part is done already.

Finally, you just need to declare what types are supported in the codegen in
https://github.com/pytorch/pytorch/blob/0d366e1bde42265d764a6a9aad27a38753156fb0/aten/src/ATen/Declarations.cwrap#L911-L920
and I believe if you don't specify the types it dispatches to everything.

@hameerabbasi let me know if you have further questions

**Comment by fmassa** [comment]
cc @gchanan, if you think we should instead implement this directly in ATen

**Comment by gchanan** [comment]
I think either approach is fine.  The TH approach is probably more straightforward if you want to start out there, the ATen approach is a little more involved.

**Comment by hameerabbasi** [comment]
I'm willing to do the ATen... I'll probably need some guidance either way. 🙂

**Comment by gchanan** [comment]
@hameerabbasi happy to help :).  The current `abs` functions exist in ATen and are implemented (partially) as call-throughs to the TH functions that @fmassa listed above (i.e. https://github.com/pytorch/pytorch/blob/1aa90192eae306e4375c68f12f46eb329042e07d/aten/src/ATen/native/cuda/CUDAUnaryOps.cpp#L53 and https://github.com/pytorch/pytorch/blob/1aa90192eae306e4375c68f12f46eb329042e07d/aten/src/ATen/native/UnaryOps.cpp#L154).

You can perhaps use TensorIterator to implement it.  See the implementation of `threshold` for inspiration: https://github.com/pytorch/pytorch/blob/1aa90192eae306e4375c68f12f46eb329042e07d/aten/src/ATen/native/Activation.cpp#L53-L81

**Comment by hameerabbasi** [comment]
I agree... It would be a good introduction to both ATen and TH/THC, as well as cleanly separating commits.

**Comment by hameerabbasi** [comment]
I added modified the file `aten/src/TH/generic/THTensorMoreMath.cpp` like so:

```
#if defined(TH_REAL_IS_SHORT) || defined(TH_REAL_IS_INT) || defined(TH_REAL_IS_CHAR)
LAB_IMPLEMENT_BASIC_FUNCTION(abs,abs)
#endif /* int only part */

#if defined(TH_REAL_IS_BYTE)
LAB_IMPLEMENT_BASIC_FUNCTION(abs,)
#endif /* for byte, identity due to it being unsigned */
```

and `Declarations.cwrap` like so:
```
[[
  name: _th_abs
  cname: abs
  types:
    - floating_point
    - Long
    - Int
    - Short
    - Byte
    - Char
  backends:
    - CPU
    - CUDA
  variants: function
  return: argument 0
  arguments:
    - arg: THTensor* result
      output: True
    - THTensor* self
]]
```

And I face the following compilation errors:

```
/Users/hameerabbasi/Quansight/pytorch/build/aten/src/ATen/CPUByteType.cpp:1172:5: error: 
      use of undeclared identifier 'THByteTensor_abs'
    THByteTensor_abs(result_, self_);
    ^
/Users/hameerabbasi/Quansight/pytorch/build/aten/src/ATen/CPUByteType.cpp:1181:5: error: 
      use of undeclared identifier 'THByteTensor_abs'
    THByteTensor_abs(result_, self_);
    ^
/Users/hameerabbasi/Quansight/pytorch/build/aten/src/ATen/CPUCharType.cpp:1172:5: error: 
      use of undeclared identifier 'THCharTensor_abs'
    THCharTensor_abs(result_, self_);
    ^
/Users/hameerabbasi/Quansight/pytorch/build/aten/src/ATen/CPUCharType.cpp:1181:5: error: 
      use of undeclared identifier 'THCharTensor_abs'
    THCharTensor_abs(result_, self_);
    ^
2 errors generated.
```

I believe I missed something or made a mistake. The code is in this branch: https://github.com/Quansight/pytorch/tree/abs-byte

I didn't open a PR yet as I didn't want to waste CI resources for something I knew was broken.

**Comment by hameerabbasi** [comment]
It turns out `THTensorMath.h` needed changes too:

```
#if defined(TH_REAL_IS_SHORT) || defined(TH_REAL_IS_INT) || defined(TH_REAL_IS_LONG) || defined(TH_REAL_IS_CHAR) || defined(TH_REAL_IS_BYTE)
TH_API void THTensor_(abs)(THTensor *r_, THTensor *t);
#endif
```
