### ISSUE TITLE
Some operations after `.copy_()` results in error in backward

### ISSUE THREAD

**Issue by joh4n** [pytorch/pytorch#15115]
## 🐛 Bug

Some operations after `.copy_()` results in the error: `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`. This worked with pytorch 0.4.0.

## To Reproduce

Just run code snippit, try some of the different commented out lines to see what is broken.

Try the same with pytorch 0.4.0
```
import torch
mu = torch.ones(1, requires_grad=True)
x = torch.randn(1)
loss = 0
for _ in range(3):
    x.detach_()
    new_calc = torch.exp(mu)
    x.copy_(new_calc)
    loss += (x * 2).sum() #broken
    # loss += torch.mul(x, 2) # broken
    # loss += (x * torch.tensor([2.])).sum() #broken
    # loss += ((x+0) * torch.tensor([2.])).sum() #works
    # loss += (x+0)*torch.randn(1) #works
    # loss += x+torch.randn(1) #works
    # loss += torch.exp(x) #works
loss.backward()
```
```
Traceback (most recent call last):
  File "/home/johan/alvis-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-cdfe91fca4b8>", line 20, in <module>
    loss.backward()
  File "/home/johan/alvis-env/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/johan/alvis-env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```
## Expected behavior
Expect the backward function to not trow a runtime error.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None
OS: Manjaro Linux
GCC version: (GCC) 8.2.1 20180831
CMake version: version 3.12.4
Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] torch (1.0.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by RomanSteinberg** [comment]
I'm not sure ... @joh4n Is it legal to use Tensor instead of Variable when you run backward pass? Or it version dependent?

**Comment by albanD** [comment]
Hi,

The problem comes from the fact that for ops like `.mul()`, we extract the second argument as a tensor in the python parser, code [here](https://github.com/pytorch/pytorch/blob/00a4c8d41cf8a7504a4300b3fc741d8a4ccc5795/torch/csrc/utils/python_arg_parser.h#L198-L221), which always return a Tensor.
This means that `mul` is always considered as a tensor * tensor op and so both tensors are kept for gradient computations. This is the `MulBackward0`.
There is a `MulBackward1` in the case where the second argument is a Scalar, but this is actually never used because we always unpack as a Tensor.

So I would see two possible fix here:
- We change parsing for `.mul` and always try to get a scalar and if not possible a Tensor.
- We change the automatically generated function to only save the needed Tensors when only some input require gradients.

Did I missed something here about how Scalar/Tensor are handled in the wrapping?

**Comment by ezyang** [comment]
cc @colesbury

**Comment by colesbury** [comment]
1. We should change the generated function to only unpack variables that are needed. 
2. It would be nice to change VariableType.cpp to only save variables that are needed (as @albanD suggests). This probably depends on (1).

To expand on (1):

MulBackward0 looks like:

```c++
variable_list MulBackward0::apply(variable_list&& grads) {
  IndexRangeGenerator gen;
  auto self_ix = gen.range(1);
  auto other_ix = gen.range(1);
  variable_list grad_inputs(gen.size());
  auto& grad = grads[0];
  auto self = self_.unpack();
  auto other = other_.unpack();
  if (should_compute_output({ other_ix })) {
    auto grad_result = grad * self;
    copy_range(grad_inputs, other_ix, grad_result);
  }
  if (should_compute_output({ self_ix })) {
    auto grad_result = grad * other;
    copy_range(grad_inputs, self_ix, grad_result);
  }
  return grad_inputs;
}
```

Roughly, the `auto self = self_.unpack();` and ` auto other = other_.unpack();` should be moved inside the if should_compute_output statements. In practice, it will be a bit more complicated because some variables are used to compute multiple derivatives.

**Comment by zou3519** [comment]
cc @gchanan could you route this to someone?

**Comment by TrigonaMinima** [comment]
@gchanan @zou3519 I'd like to work on this one. Is anyone working on this?

I'll be starting from scratch with pytorch source code so will need some help. I've read the ```CONTRIBUTING.MD```.

**Comment by gchanan** [comment]
@TrigonaMinima sorry, this was already fixed by https://github.com/pytorch/pytorch/pull/16583.
