### ISSUE TITLE
AttributeError: Assignment not allowed (no field "cuda_gpu_id" in protocol message object).

### ISSUE THREAD

**Issue by amoghj8** [pytorch/pytorch#15168]
Following the link https://pytorch.org/docs/master/onnx.html, after trying to run:

```
import caffe2.python.onnx.backend as backend
import numpy as np
rep = backend.prepare(model, device="CUDA:0") # or "CPU"
```

Results in the following error description:

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-82-2c396422089b> in <module>
      2 import numpy as np
      3 
----> 4 rep = backend.prepare(model, device="CUDA:0") # or "CPU"
      5 outputs = rep.run(np.random.randn(10, 3, 224, 224).astype(np.float32))

/opt/conda/lib/python3.6/site-packages/caffe2/python/onnx/backend.py in prepare(cls, model, device, raw_values_dict, **kwargs)
    712 
    713         ws = Workspace()
--> 714         device_option = get_device_option(Device(device))
    715 
    716         init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)

/opt/conda/lib/python3.6/site-packages/caffe2/python/onnx/backend.py in get_device_option(device)
     56     m = {DeviceType.CPU: caffe2_pb2.CPU,
     57          DeviceType.CUDA: caffe2_pb2.CUDA}
---> 58     return core.DeviceOption(m[device.type], device.device_id)
     59 
     60 

/opt/conda/lib/python3.6/site-packages/caffe2/python/core.py in DeviceOption(device_type, cuda_gpu_id, random_seed, node_name, numa_node_id, extra_info)
     93     option = caffe2_pb2.DeviceOption()
     94     option.device_type = device_type
---> 95     option.cuda_gpu_id = cuda_gpu_id
     96     if node_name is not None:
     97         option.node_name = node_name

AttributeError: Assignment not allowed (no field "cuda_gpu_id" in protocol message object).```

**Comment by hasiftwistcode** [comment]
Ran this to verify caffe2 and how many cuda devices:

`# To check if Caffe2 build was successful
python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"

# To check if Caffe2 GPU build was successful
# This must print a number > 0 in order to use Detectron
python -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'`

Then, I tried to verify the either my caffe2 using cuda or not : 

`from caffe2.proto import caffe2_pb2
from caffe2.python import workspace

device_opts = caffe2_pb2.DeviceOption()
device_opts.device_type = caffe2_pb2.CUDA
device_opts.cuda_gpu_id = 0

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Assignment not allowed (no field "cuda_gpu_id" in protocol message object).`

Anything that I missed?

**Comment by hasiftwistcode** [comment]
same problem. Anything that I miss?

**Comment by ezyang** [comment]
@amoghj8 Your version of Caffe2 is not new enough. If you upgrade to 1.0 or master your problem will go away. CC @bddppq c.f. #12456
