### ISSUE TITLE
torch.utils.serialization.load_lua no longer supported 

### ISSUE THREAD

**Issue by johnlambert-argo** [pytorch/pytorch#15307]
## 🐛 Bug

I'm trying to load a .t7 torch model into PyTorch. I read [here](https://discuss.pytorch.org/t/convert-import-torch-model-to-pytorch/37/2) from Soumith that this was supported functionality previously. Was it removed, and if so, why?
     
from torch.utils.serialization import load_lua 
ImportError: No module named 'torch.utils.serialization'

## To Reproduce

```
import torch
from torch.utils.serialization import load_lua
```
## Environment
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.13.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.15.2)
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] mkl_fft                   1.0.10                   py36_0    conda-forge
[conda] mkl_random                1.0.2                    py36_0    conda-forge
[conda] pytorch                   1.0.0                   py3.6_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch

**Comment by soumith** [comment]
this was removed in 1.0, as it's been more than 1.5 years since PyTorch released. We also removed `torch.legacy.nn` in the process.
If you want to just load the weights / tensors from a .t7 file, you can try using https://github.com/bshillingford/python-torchfile or load them via pytorch `0.4.1` and save them as pickle format.

**Comment by kielpins** [comment]
Well, that just broke my attempt to port the company's whole codebase to PyTorch. `load_lua` is essential functionality and backward compatibility for Torch users is not optional if you want widescale adoption.

**Comment by soumith** [comment]
@kielpins you can install PyTorch 0.4.1 which still has this functionality.

**Comment by kielpins** [comment]
@soumith I can't see a good reason why people should be forced to freeze at 0.4.1 if they need the ability to load Torch files. `torchfile` works for the moment but its community is much smaller than PyTorch. Who knows, PyTorch may be updated in a way that breaks `torchfile` compatibility too. So these aren't adequate replacements for the original `load_lua` feature.

**Comment by soumith** [comment]
@kielpins there aren't adequate replacements for `load_lua`, but `load_lua` experience itself wasn't very good to begin with. When you load_lua a torch neural network, you didn't get a PyTorch model, you got a PyTorch torch.legacy.nn model, with which you could do nothing further other than run forward-backward on it. You couldn't use it as part of a regular PyTorch network.
At some point, it started costing us a lot of maintenance overhead and performance, because we had to keep around this old library, for no other reason than to maintain `load_lua`, which didn't even give people a useful experience by giving them PyTorch models.
At some point we did a cost-benefit analysis, and pulled the plug. You are forced to freeze at 0.4.1 if you want to keep running legacy lua-torch models (from more than 2 years old stack), that's the last version you can do so. Unfortunately we aren't bringing this feature back.

**Comment by soumith** [comment]
> Who knows, PyTorch may be updated in a way that breaks torchfile compatibility too.

No, `torchfile` loads the lua-torch Tensors as numpy arrays. So, you should be good.

**Comment by Amir-Arsalan** [comment]
@johnlambert-argo I would say use PyTorch 0.4.1 and use this to convert your Lua Torch model to PyTorch model, not just the `torch.nn.legacy` model. Then use PyTorch 1.xx to do whatever with it. You can also train your converted Lua Torch models in PyTorch this way :)

**Comment by HusseinBarakat89** [comment]
Unfortunately the majority of the repos that tries to provide the functionality counts on load_lua, the function which is not supported .Even the copy on the official site for PyTorch 0.4.1 doesn't include the functionality any more.

**Comment by StEvUgnIn** [comment]
@HusseinBarakat89 Maybe that if this functionality is sought until now, it was worth keeping it as part of newer releases.
