### ISSUE TITLE
Usage of the python's built-in function "input" as variable name

### ISSUE THREAD

**Issue by kuzand** [pytorch/pytorch#15394]
I have noticed that there is an extensive usage of variable named `input` for data inputs, but `input` is Python's built-in function. So I think this should be changed to something like `inpt` to avoid any possible problems.
https://stackoverflow.com/questions/20670732/is-input-a-keyword-in-python

**Comment by SsnL** [comment]
I can't think of any case that this will cause any problem in user code except for possibly being rendered incorrectly in IDEs. Can you give some example?

**Comment by zou3519** [comment]
as @SsnL mentioned, it's not a problem with our functions because we do not need to use the python built-in `input()`. The alternative would be to replace `input` with something like `inp` or `inpt` or `input_`, all of which take me a few more seconds to process; `input` is clearer to the users IMO. 

@kuzand please let me know if you have specific examples of how this could cause problems

**Comment by soumith** [comment]
It's a nice to have, but really not essential. The above comments reflect my thoughts as well.

**Comment by YodaEmbedding** [comment]
`x` is also a good alternative name for an arbitrary "no-name" input. Generic Haskell code uses it all over the place.
