### ISSUE TITLE
Bad error message when creating a class instance in script functions

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#15409]
This code:
```py
import torch
import torch.nn as nn

@torch.jit.script
def f(x):
    return nn.Softmax(dim=-1)(x)
```

produces the following error:
```
Traceback (most recent call last):
  File "fail.py", line 4, in <module>
    @torch.jit.script
  File "/home/apaszke/pytorch/torch/jit/__init__.py", line 693, in script
    _jit_script_compile(mod, ast, _rcb, get_default_args(fn))
  File "/home/apaszke/pytorch/torch/jit/annotations.py", line 67, in get_num_params
    raise RuntimeError("expected a single top-level function")
RuntimeError: expected a single top-level function
```

It seems that the reason for this is that it thinks that `nn.Softmax` is supposed to be a Python function, but sees a `ClassDef` in the AST and throws because of that. We should give a nicer error message in this case, as this pattern is unfortunately somewhat common. An easy fix would be to check for `ast.ClassDef`, but a proper one should really point to the place where the failure originates from.

**Comment by Squadrick** [comment]
@apaszke Let me take a crack at this.

**Comment by Squadrick** [comment]
I think I've figured out where the error occurs.

After the `jit.script` function is converted to JIT AST, and passed off to the compiler, the compiler recursively emits the apply expressions in the AST, until it arrives at the class instance creation. We `call` the `SugaredValue` expression in `init.cpp`. To ascertain the function's signature, we call `get_num_params`, but this fails since Python's AST parses it as a `ClassDef`. 

Like you mentioned, a simple fix would be to check for `ast.ClassDef`. I couldn't think of a better way to tackle the issue, any advice would be much appreciated.

**Comment by Squadrick** [comment]
```python
if isinstance(py_ast.body[0], ast.ClassDef):
    module_name = source[source.index('class') + 6 : source.index('(')]
    raise RuntimeError("cannot create a module (%s) inside jit.script" % module_name)
```

I've added this snippet on line 66 in `pytorch/torch/jit/annotations.py`

**Comment by Squadrick** [comment]
@apaszke This issue can be closed. This [PR](https://github.com/pytorch/pytorch/pull/16416) solves it.
