### ISSUE TITLE
Auto-convert GPU arrays that support the __cuda_array_interface__ protocol

### ISSUE THREAD

**Issue by mrocklin** [pytorch/pytorch#15601]
A few projects now implement the `__cuda_array_interface__` protocol, which was originally designed by the Numba developers to enable clean operation on arrays managed by other projects.  I believe that today both PyTorch and CuPy have implemented this protocol, and that Numba is the only consumer.

However, libraries like PyTorch and CuPy could also identify this protocol on input objects and use it within their functions.  Probably the first use case would be to allow users to easily convert between different GPU array libraries.  For example, ideally the following would work.

```python
import cupy
x = cupy.random.random((1000, 1000))

import torch
t = torch.tensor(x)
```

Ideally the check within `torch.tensor` would be something like the following:

```python
if hasattr(x, '__cuda_array_interface__'):
    ...
```

rather than the following:

```python
if isinstance(x, cupy.ndarray):
    ...
```

which would be useful for support of future GPU libraries.

xref https://github.com/pytorch/pytorch/issues/11914

**Comment by mrocklin** [comment]
As additional incentive we could change code like the following:

```python
def isnan(tensor):
    if not isinstance(tensor, torch.Tensor):
        raise ValueError("The argument is not a tensor", str(tensor))
    return tensor != tensor
```

To the following:

```python
def isnan(tensor):
    tensor = as_tensor(tensor) # converts or raises as appropriate
    return tensor != tensor
```

This would allow torch operations to work on compatible array objects more easily.

**Comment by apaszke** [comment]
I think that's very reasonable. Would you like to send a PR with that feature?

**Comment by dotsdl** [comment]
I'll begin developing a PR implementing this proposal. It'll be my first dive into the `pytorch` codebase, but should serve as a nice tour with a real objective. I should have a WIP PR up by EOD Friday. 

@apaszke, any pointers on where most of the work will need to take place within the library? I can start there.

**Comment by apaszke** [comment]
@dotsdl Great, but you have to be prepared that it's a purely C++ task (or at least it will involve quite a bit of dabbling with CPython's C API)! `as_tensor` is implemented [here](https://github.com/pytorch/pytorch/blob/master/tools/autograd/templates/python_torch_functions.cpp#L322), but it pretty much immediately calls into [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_new.cpp#L534), which passes most of the work on to [`internal_new_from_data`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_new.cpp#L190). This is the place where we e.g. check if the thing is a NumPy array, and this is also where we should try to check if it has the `__cuda_array_interface__` attribute, and try to use it if it does. Hope this helps!

**Comment by dotsdl** [comment]
@apaszke it helps quite a bit! I'll ask more questions as I move it along. Thanks!

**Comment by datametrician** [comment]
Small correction to the above, but I believe CuPy is also a consumer in their latest release.

**Comment by csarofeen** [comment]
Can we go to/from CuPy through DLPack? 
https://github.com/cupy/cupy/blob/806349701f9fd714cc06de0e924c432af1c077c8/cupy/core/dlpack.pyx
https://github.com/pytorch/pytorch/blob/0bf1383f0a6caa34945feaf19191986d18205251/torch/csrc/Module.cpp#L316-L351

**Comment by matthieuheitz** [comment]
I would be very interested in that auto-conversion.
It would allow me to write a custom Pytorch `Function` and use the `Pyculib` library in the forward and the backward.
Right now, to transform a `torch.Tensor` to the Pyculib vector type (`DeviceNDArray`), I just have to do:
`t = pyculib.cuda.as_cuda_array(my_torch_tensor)`, and it works since the `__cuda_array_interface__` is implemented in Pytorch (https://github.com/pytorch/pytorch/pull/11984)

It's possible to go back from a `DeviceNDArray` to a `torch.Tensor`, but you have to go through the host (```torch.tensor(t.copy_to_host())```) which is inefficient.
Is there a workaround in the meantime this PR is done and merged ?

**Comment by matthieuheitz** [comment]
Actually, I found the easiest workaround !
When we do `t = pyculib.cuda.as_cuda_array(my_torch_tensor)`, the 2 tensors share the same underlying data (no copy is done), so since my operation only modifies `t` in-place, then to get a `torch.tensor` with the result, `my_torch_tensor` is the answer since it shares its data with `t` !
And if my operation wasn't in-place, I would just have to create a result torch tensor, get its Numba equivalent, copy the result in it (costs 1 copy device->device), and voila, the result is in a `torch.tensor` !

**Comment by matthieuheitz** [comment]
Actually, I found the easiest workaround to my problem !
When we do `t = pyculib.cuda.as_cuda_array(my_torch_tensor)`, the 2 tensors share the same underlying data (no copy is done), so since my operation only modifies `t` in-place, then to get a `torch.tensor` with the result, `my_torch_tensor` is the answer since it shares its data with `t` !
And if I wanted a copy of a Numba vector as a torch.tensor, I would just have to create a result torch tensor, get its Numba equivalent, copy the result in it (costs 1 copy device->device), and voila, the result is in a `torch.tensor`:
Thanks @albanD for [your answer](https://discuss.pytorch.org/t/creating-variable-from-existing-numba-cuda-array/14474/2)

**Comment by mrocklin** [comment]
Does anyone have any thoughts on the relative merits of having everyone use DLPack vs using something like the `__cuda_array_interface__` protocol?  It looks like both PyTorch and CuPy currently include dlpack though not TensorFlow or Numba.  I'm not particularly informed on this topic, but here are some thoughts:

-  In favor of `__cuda_array_interface__`: The `__cuda_array_interface__` protocol seems lighter weight to me, which is often valuable.  I don't have enough experience in this field to know how lightweight dlpack feels and how willing infrastructure projects typically are to including dependencies like this.  

    In my experience it's easy to go up to a project and say "Hey, I want to implement this `def __my_protocol_name__()` function in your project to help with interoperability" and have them say "yes" almost all of the time.  Saying "Hey I want to include these source files into your project is often harder".  

-  In favor of `dlpack`: actually it appears that dlpack is just a header file?  It's also at the C level, so this could be used lower down as well.  

cc @seibert @sklam from Numba, any thoughts here?  You are both probably more informed and capable here than I am.

**Comment by ezyang** [comment]
As far as I am concerned, dlpack and `__cuda_array_interface__` are orthogonal mechanisms to solve the interoperability problem in C and Python respectively. If I have a tensor which is some PyObject, I still need a protocol (like `__cuda_array_interface__`) by which I can retrieve a dlpack, or other standardized, representation.

**Comment by escorciav** [comment]
is this going to move along?
👍 for an official (zero-copy) bridge btw pytorch<=>numba, GPU tensors.

**Comment by ezyang** [comment]
We'll accept a PR, just needs someone to roll up their sleeves and do it :)

**Comment by mrocklin** [comment]
@madsbk any interest in trying to add a `__cuda_array_interface__` property to torch tensors?

**Comment by madsbk** [comment]
@mrocklin sure, look interesting.

I gather @dotsdl, you are not working on a PR anymore right? Did you encounter any showstoppers?

**Comment by escorciav** [comment]
@madsbk you may wanna sync up with @ezyang 
It seems it was implemented in #11984 (as @matthieuheitz mentioned before). I think that it's missing that the unit-test passes the CI #12614.

**Comment by mrocklin** [comment]
I think that #11984 implements the `__cuda_array_interface__` so that other projects can easily understand how to operate on data stored in torch tensors.  However I don't think that it supports the other direction, where torch becomes able to operate on other projects that implement the `__cuda_array_interface__`.

```python
numba_func(torch_tensor)  # works today
torch_func(numba_array)  # doesn't work today
```

The second option, where torch functions work on objects that implement this protocol is the topic of this issue.  As a first pass, I think that the `as_tensor` or `Tensor` constructors should probably check for this attribute and convert as necessary.

**Comment by mrocklin** [comment]
(I could be mistaken though, to be honest I only glanced through things)

**Comment by madsbk** [comment]
@mrocklin, I think you are right. #11984 implements the [`__cuda_array_interface__`](https://github.com/pytorch/pytorch/pull/11984/files#diff-cc0c64d106a6a6ac17e095af0ce1d6b6R450) property.

**Comment by ezyang** [comment]
Yes, I need to clarify that we alerady have a `__cuda_array_interface` property on Tensor, so the ask here is to make it so that relevant parts of our Python binding code can accept non-Tensor, non-numpy objects that do implement `__cuda_array_interface__`, in the same way we accept numpy objects in some cases.  I think I would look into `torch/csrc/utils/tensor_new.cpp` as a start; grep for `tnesor_from_numpy`.
