### ISSUE TITLE
[JIT] support __constants__ in python module

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#15767]
## 🚀 Feature
`__constants__` is only available when I work with torch.jit.ScriptModule and not supported in `@torch.jit.script`.
It would be great if `@torch.jit.script` support it by reading `__constants__` of the module where the script is in.

## Pitch

```python
__constants__ = ['some_const']
some_const = 1234

@torch.jit.script
def some_script():
    ...

```

**Comment by zdevito** [comment]
We currently do not support this because, unlike modules, it is not possible for us to enforce that a value somewhere stays constant. 

For instance, in the example above:

```__constants__ = ['some_const']
some_const = 1234

@torch.jit.script
def some_script():
    ...

some_const = 333 # error! some_script will not see this change
```

In ScriptModules, we can enforce the const-ness using a custom `__setattr__` property. 

We do currently treat public properties of modules, e.g. `math.pi` as constants. The assumption is that since it is public property and not a function, it wouldn't atypical for it to be modified. 

So a current workaround is to put the constants that you want to use in a module:

```
import my_constants
@torch.jit.script
def some_script():
    return my_constants.some_const
```

Since this overall design is a tradeoff between surprising behavior and connivence, it is something we will likely reconsider as we see more examples of how it is used.  Feel free to post more comments in this issue with particular use-cases where this arises so the team can get a better understanding of what you want to use constants for.

**Comment by suo** [comment]
Going through a cleanup pass over old issues.

I think @zdevito's comment stands, so closing this for now. If anyone wants this badly, feel free to reopen with a comment.
