### ISSUE TITLE
Need GPU implementation of dirichlet_grad (originally: Reparameterized gradient on GPU for beta / Dirichlet)

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#15773]
## 🐛 Bug

Reparameterized gradient computation fails when dirichlet (hence beta) parameters are dispached on GPU.

this works:
```
a,b = torch.ones(3,4,1,5,requires_grad=True),torch.ones(3,4,1,5,requires_grad=True)
s = torch.distributions.beta.Beta(a,b).rsample(torch.Size((10,)))
torch.sum(s).backward()
a.grad
```

but this doesn't
```
a,b = torch.ones(3,4,1,5,requires_grad=True,device='cuda'),torch.ones(3,4,1,5,requires_grad=True,device='cuda')
s = torch.distributions.beta.Beta(a,b).rsample(torch.Size((10,)))
torch.sum(s).backward()
a.grad
```

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
...

Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] magma-cuda92              2.4.0                         1    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl-include               2019.1                      144  
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0  
[conda] mkl_random                1.0.1            py37h4414c95_1
In [ ]:

**Comment by vishwakftw** [comment]
For clarity, this is the error message printed:
```RuntimeError: _th_dirichlet_grad is not implemented for type torch.cuda.FloatTensor```

**Comment by cloversjtu** [comment]
did you find some methods to solve the dirichlet reparametrization can't be implemented on gnu？

**Comment by cloversjtu** [comment]
Thank you for your help, I will try it later.

**Comment by Diego999** [comment]
Any news on this ?

**Comment by gui11aume** [comment]
I find it surprising that there is no implementation of the Dirichlet gradient because there is already an implementation of the Gamma gradient. The standard way to generate a Beta variable is to generate two Gamma variables (see for instance [Wikipedia](https://en.wikipedia.org/wiki/Beta_distribution#Generating_beta-distributed_random_variates)) and compute their fractional ratio. For instance, the following fix on the code of @vmoens seems to work:

    a,b = torch.ones(3,4,1,5,requires_grad=True,device='cuda'),torch.ones(3,4,1,5,requires_grad=True,device='cuda')
    s1 = torch.distributions.Gamma(a,1).rsample(torch.Size((10,)))
    s2 = torch.distributions.Gamma(b,1).rsample(torch.Size((10,)))
    s = s1 / (s1+s2)
    torch.sum(s).backward()
    a.grad

Same goes for sampling Dirichlet variables, on actually samples independent Gamma variables. So, right now users should be able to use this fix, but it seems to me that it should not be difficult to implement native support for Beta gradients with CUDA because all the functions are already there.

**Comment by vishwakftw** [comment]
I’ve sent in a PR that fixes the issue.
