### ISSUE TITLE
[RFC] Integration with MKL-DNN

### ISSUE THREAD

**Issue by yinghai** [pytorch/pytorch#16038]
## 🚀 Feature
Two options: 
- Opaque integration akin to the current Caffe2’s ideep tensor. The tensor would support only a subset of operations that are explicitly implemented and fine-grained access of the tensor will not be efficient (e.g. operator[]). This is how e.g. sparse tensors are supported today. Note, that TensorImpl doesn’t need to be virtualized for it as top-level tensor operations (including resize_ and all math/nn ops) go through the dispatch mechanism (in TensorMethods.h and a few other places) and can be routed to another implementation.
- Fine grained integration where PyTorch has visibility into what MKLDNN layout is. In this case majority of tensor ops would work and even many regular PT kernels would work against mkldnn tensors if they rely on TensorAccessor and friends. It’s a more powerful integration and provides a better UX but it’d require “opening the covers” for MKLDNN and also higher complexity for core PT code to recognize other layouts.

**Comment by ezyang** [comment]
cc @colesbury

**Comment by ezyang** [comment]
Another way of stating the pitch for option (2), is a recognition of the fact that a tensor X represented in blocked format, is still a tensor X. So if you say X + Y, where one is blocked, and the other is not, you'd expect this to still give you a result (even if it's slow to compute.) Just like how we call X.contiguous() when X is strided and we have a kernel that doesn't understand strides.

**Comment by colesbury** [comment]
Some minor points:
- This doesn't have much to do with TensorImpl being virtual or not. You can support blocked layouts and still have TensorImpl be non-virtual.
- The MKL-DNN layout is documented in [Understanding Memory Formats](https://intel.github.io/mkl-dnn/understanding_memory_formats.html).
- It's probably *not* worth supporting blocked layouts in TensorAccessor. TensorAccessor isn't very efficient to start-with and the extra modulo (%) operation will likely slow it down. It's probably worth it to support it in something like TensorIterator, at least for element-wise kernels, since we can re-arrange and combine dimensions to avoid expensive indexing.
- A fine grained integration will require a lot of work. Even the minimum of throwing an error for unsupported layouts will require substantial work. (And it would be better to do something like @ezyang's comment about X.contiguous())

**Comment by Jianhui-Li** [comment]
We had a couple of internal discussions on this and converged that we probably can't afford the second option which allows broad set of Pytorch ops to access MKL-DNN block format directly. There are multiple blocking format for activation depending on the data type, and are many for weight. Given the feedback above on the efforts and complexity concerns raised in the PR, we also think it is better to take the first option where the MKL-DNN tensors supports a subset of ops which are most frequent executed and performance critical.    

     One thing needs to be aware of is that MKL-DNN blocking format can be decided at the static time. The data format is decided at run time by MKL-DNN algorithm depending on the input tensor shape and data type. So the reordering has to be done at run time. The reordering may be needed between a serious of MKL-DNN convolution ops (like between group conv and regular conv for certain shape). The MKL-DNN integration layer needs to check the incoming tensor's format, query the expected format from MKL-DNN, and does the reordering on the fly.  

    One of our design goal is to reduce layout reordering. Instead of converting the MKL-DNN block format back to plain format at the end of each operation, we would like to have lazy reordering so that the activation tensor can stay in MKL-DNN format when it travels through MKL-DNN operations. When the activation tensor leaves the MKL-DNN op, it could stay in blocking format without reordering, and upon dispatch time, the tensor is converted to the format expected by the next op.

**Comment by ezyang** [comment]
Thanks. We'll have to move forward with this as an opaque integration then

**Comment by Jianhui-Li** [comment]
We (Intel Pytorch team) have a couple of discussions with @bddppq on whether MKL-DNN op should be visible to user and how MKL-DNN op should be implemented in Pytorch C10 backend.  We summarize the discussion below to capture the motivation and directions on the high level design.  Your feedback is welcome.   

====
The Pytorch C10 design would like to make MKL-DNN operation visible to user. So if user wants to use MKL-DNN operations, user needs to explicitly convert cpu tensor to MKL-DNN tensor, and vice versa.  The motivation of explicit user conversion is to support performance debugging. If the conversion is done implicitly in the C10 ops/runtime, the model designer may produce a model with hidden conversion cost which it is hard to debug the conversion related performance issues during the deploy time. When the pytorch program is statically compiled to a computation graph, C10 would like to able to differentiate MKL-DNN op from cpu op in the computation graph, and the tensor conversion is represented as a node in the graph. This facilitates the graph optimization and also ease the performance debugging. This involves changes in both Pytorch front-end and back-end. Pytorch front-end needs to expose MKL-DNN to user through certain mechanism, and Pytorch back-end needs to treat MKL-DNN as a backend device so the MKL-DNN OP is represented as Aten OP’s implementation on MKL-DNN device.  
 
Intel Pytroch team would like to have the MKL-DNN optimization enabled without user changing code. With the computation graph, an optimization pass may be done to promote CPU op to MKL-DNN op, and add or delete the format conversion op for best performance. The optimization pass ensures that the graph path can enjoy the performance benefit from the latest MKL-DNN version without user changing the program. 
 
FB Pytorch team understands that MKL-DNN op decides the input/output tensor format at runtime. The user specified to_mkl-dnn() may not trigger the actual format conversion, which may actually happen at the entry of the following MKL-DNN op. The user specified to_cpu() usually triggers a conversion since the MKL-DNN tensor is typically not the plain format. The format conversion may happen between two consecutive MKL-DNN ops.  
 
Intel Pytorch team would like to not confuse Pytroch user taking MKL-DNN as a HW device. As MKL-DNN is essentially an optimization library on the base device (CPU), calling  MKL-DNN a device on Pytorch front-end may cause confusion. For example, the MKL-DNN library may extended to cover another Intel device in the future, in that case, user may be confused by a MKL-DNN device on top of the new Intel device. So, if the MKL-DNN OP has to be exposed in Pytorch front-end, it may be exposed as OPs working with special format tensors, not a device.  It is like how sparse tensor is presented to user using torch.to_sparse(), so it could be tensor.to_mkl-dnn(), not tensor.to(device='mkl-dnn-x86').   
 
In early experiment stage, if Pytorch user (model designer) complains such usage model, Pytorch team may consider a Python compatible layer, which enlarges MKL-DNN operation scope by simply implementing the non-MKL-DNN Ops by a conversion to cpu tensor and cpu op implementation.  This simplifies MKL-DNN op usage since user only needs to specify the conversion to MKL-DNN format at the beginning of the program, but it also defeat the purpose of having user aware of the conversion and an accurate computation graph.

**Comment by uyongw** [comment]
@yinghai @ezyang As for the 2nd choice, I know currently PyTorch does not even support NHWC plain format. If we uncover MKL-DNN blocked format in the tensor integration, will it break the design philosophy indicated from https://github.com/pytorch/pytorch/issues/1220 ?

**Comment by Jianhui-Li** [comment]
Beside activation, MKL-DNN weight also requires blocking format so we need to reorder the weight before feeding to the MKL-DNN primitives. There are two options: user needs to reorder the weight for MKL-DNN op, or user don't need. Following discussions with some Pytorch developers, we are heading the direction that user don’t need to reorder the weight in the program. In the JIT path, the weight are reordered at the graph init time. In the impreative path, the MKL-DNN OP accept CPU weight tensor with public format.  We would like to post this direction here to get feedback from stakeholders and community. @yinghai @ezyang @dzhulgakov @Soumith @gchanan @bddppq @mingfeima @uyongw @jiong5

**Comment by Jianhui-Li** [comment]
Beside activation, MKL-DNN weight also requires blocking format so we need to reorder the weight before feeding to the MKL-DNN primitives. There are two options: user needs to reorder the weight for MKL-DNN op, or user don't need. Following discussions with some Pytorch developers, we are heading the direction that user don’t need to reorder the weight in the program. In the JIT path, the weight are reordered at the graph init time. In the impreative path, the MKL-DNN OP accept CPU weight tensor with public format.  We would like to post this direction here to get feedback from stakeholders and community. @yinghai @ezyang @dzhulgakov @Soumith @gchanan @bddppq @mingfeima @uyongw @jiong5

**Comment by dzhulgakov** [comment]
I think it's a good idea to do weights prepacking, but it should be opt-in (as e.g. some ops for a custom optimizer might not be implemented on mkldnn tensor). Effectively, we just need to walk parameters of a module in question and change them to mkldnn - we can expose it on module as `mod.mkldnn()` similarly to `mod.cuda()`.

The tricky part would be behavior during serialization - it's unclear whether after save/load cycle the tensor should stay as mkldnn.

**Comment by Jianhui-Li** [comment]
Thanks @dzhulgakov for the feedback.   

For user opt-in approach, there is an issue that mod.mkldnn() reorders weights for all the MKL-DNN op in the model but activation tensor.to_mkldnn()/to_dense() may specify a smaller scope of MKL-DNN ops due to the program was developer at an ealrier Pytorch with less MKL-DNN op support.  In the JIT path,  we assume that we could expand the activation scope to match with weight.  However, in the imperative path, the out of scope activation tensor (in CPU dense format) is dispatched to CPU device not MKL-DNN device, but with the weight reordered for MKL-DNN.  There are multiple options to solve this - 1) change CPU OP to accept MKL-DNN format tensor; 2) change the dispatch to send the pair (activation in CPU, weight in MKL-DNN) to MKL-DNN op which needs to be enhanced to input CPU activation other than MKL-DNN activation, 3) leave the issue as is, user should expect the issue for Pytorch upgrade.   All looks unnatural to me.  

This issue above is the main reason why we think we may not want to follow CUDA style for explicit weight transfer - which is a must to run op on a separate device so user may accept option 3) above.  But MKL-DNN is fundamentally not a device,  and it only accelerates small amount of operations. The reordering cost is much smaller than dispatching to a device.  The purpose of having user aware of using MKL-DNN is already fulfilled by requiring tensor.to_mkldnn()/to_dense().

**Comment by jgong5** [comment]
@dzhulgakov Consider the custom optimizer case you mentioned, and users *don't* need to change the weight format, we guarantee that MKL-DNN backward op always returns the same tensor type as weight for gradient, i.e. weight/gradient in CPU tensor (imperative path) or weight/gradient in MKL-DNN tensor (JIT path). Is that OK?

> The tricky part would be behavior during serialization - it's unclear whether after save/load cycle the tensor should stay as mkldnn.

I think they should be serialized as CPU tensors to be compatible in most cases.

**Comment by soumith** [comment]
implemented in some form now.

**Comment by louie-tsai** [comment]
@aice-support
