### ISSUE TITLE
[multiprocessing] does not play well with distributions in GPU

### ISSUE THREAD

**Issue by fehiepsi** [pytorch/pytorch#16141]
## 🐛 Bug

Continued from some discussions at https://github.com/pytorch/pytorch/pull/14736 and https://github.com/uber/pyro/pull/1694.

Running the following script gives the error **RuntimeError: Assertion `self->allocator() != nullptr' failed**:
```sh
Traceback (most recent call last):
  File "testt.py", line 31, in <module>
    sample = q.get()
  File "/home/fehiepsi/miniconda3/envs/pydata/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/fehiepsi/miniconda3/envs/pydata/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 104, in rebuild_cuda_tensor
    t = torch._utils._rebuild_tensor(storage, tensor_offset, tensor_size, tensor_stride)
  File "/home/fehiepsi/miniconda3/envs/pydata/lib/python3.6/site-packages/torch/_utils.py", line 131, in _rebuild_tensor
    return tensor_class().set_(storage, storage_offset, size, stride)
RuntimeError: Assertion `self->allocator() != nullptr' failed.  at /opt/conda/conda-bld/pytorch-nightly_1547631207535/work/aten/src/THC/THCStorage.cpp:16
```

## To Reproduce

Running the following script

```
import torch
import torch.distributions as dist
import torch.multiprocessing as mp

torch.set_default_tensor_type(torch.cuda.FloatTensor)
n = 10

def model():
    d1 = dist.Normal(torch.zeros(3), 1)
    v1 = d1.rsample()  # no error when replace `.rsample()` by `.sample()`
    d2 = dist.Normal(v1, 2)
    v2 = d2.rsample()
    return [(d1, v1), (d2, v2)]

def worker(q, e):
    for i in range(n):
        sample = [torch.zeros(1), torch.ones(1)]  # no error when remove this line ???
        sample = model()
        q.put(sample)
        e.wait()
        e.clear()

if __name__ == "__main__":
    ctx = mp.get_context("spawn")
    q = ctx.Queue()
    e = ctx.Event()
    p = ctx.Process(target=worker, args=(q, e))
    p.start()
    for i in range(n):
        print("=== ITER {} ===".format(i))
        sample = q.get()
        print(sample)
        e.set()
    p.join()
```

## Expected behavior

No error as when running in CPU.

## Environment

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 9
 - GPU models and configuration: GTX 1080

## Additional context

The error does not happen with PyTorch 1.0.dev.20181202 version.

cc @neerajprad @ailzhang @ezyang

**Comment by ailzhang** [comment]
I think I know the problem and pushed a PR to fix it. The fix is kinda hacky though, please let me know if there’s a better way to do it. @ezyang

Here is what happened:
- The error always happens in the second iteration when rebuilding `v1`. It happened because the storage is found in cache, but the returned storage from cache is 4 bytes, while the tensor to be rebuilt is actually 12 bytes.
- The reason for mismatched size if storage expires by the storage ptr is still valid, but the content it points to has changed from a 12 bytes storage to a 4 bytes storage. On python side, we aren’t aware of the change, and we **think** the storage is still valid but it’s not true. On python side, receiver has no way to prevent sender from allocating a new tensor on the same address where had a tensor with different size before. And it has no way to free dead references in `shared_cache` to catch the changes.
- My fix is to also use `id(storage)` from sender side as a key in `shared_cache`. Even on the sender side a new tensor is allocated to a address where it was shared before, the receiver still knows it has changed and construct a new tensor with the right size & type.
- This also explains why `sample=[torch.zeros()....]` is required to trigger this error. My guess is this additional memory allocation pushed the new tensor to be created with an offset compared to the old tensors in last iteration. And coincidentally they are allocated to an old shared address with a different tensor size and triggered the problem.

Thanks,
Ailing

________________________________

**Comment by fehiepsi** [comment]
@ailzhang Your fix solved the issue in the above script but this error is still happening with my pyro codes (due to mismatched sizes). I am still not able to construct a solely pytorch example yet. In the mean time, the following phenomenon might be relevant: when we put a list of dicts instead of a list of tuples to the queue, the value by `storage_from_cache` is not None after second iteration.

```
import torch
import torch.distributions as dist
import torch.multiprocessing as mp

torch.set_default_tensor_type(torch.cuda.FloatTensor)
n = 10

def model():
    d1 = dist.Normal(torch.zeros(3), 1)
    v1 = d1.rsample()  # no error when replace `.rsample()` by `.sample()`
    d2 = dist.Normal(v1, 2)
    v2 = d2.rsample()
    return [({"dist": d1, "value": v1}), ({"dist": d2, "value": v2})]

def worker(q, e):
    for i in range(n):
        sample = [torch.zeros(1), torch.ones(1)]  # no error when remove this line ???
        sample = model()
        q.put(sample)
        e.wait()
        e.clear()

if __name__ == "__main__":
    ctx = mp.get_context("spawn")
    q = ctx.Queue()
    e = ctx.Event()
    p = ctx.Process(target=worker, args=(q, e))
    p.start()
    samples = []
    for i in range(n):
        print("=== ITER {} ===".format(i))
        sample = q.get()
        #del sample
        e.set()
    p.join()
```
I do `print(storage, storage_size_bytes)` at [this line](https://github.com/pytorch/pytorch/pull/16194/files#diff-0d553ed0e9ca41fdac21632b4d503a10R94) and observe that after the second iteration, the above phenomenon happened.

**Comment by SsnL** [comment]
@ailzhang Yeah, `id` is not reliable if the old object can be deallocated. I'm curious. Why can't we just add `storage_size_bytes` to the cache key?

**Comment by fehiepsi** [comment]
I am not sure if things are correct but @SsnL works for all of my pyro codes (I don't see the topic's error anymore).

**Comment by fehiepsi** [comment]
Though @SsnL can solve the error in this topic, results obtained from the queue can not be saved (**unless we clone it**) as shown in the below script.

```
import torch
import torch.distributions as dist
import torch.multiprocessing as mp

torch.set_default_tensor_type(torch.cuda.DoubleTensor)
n = 10

def model():
    return torch.rand(3)

def worker(q, e):
    for i in range(n):
        sample = model()
        q.put(sample)
        e.wait()
        e.clear()

if __name__ == "__main__":
    ctx = mp.get_context("spawn")
    q = ctx.Queue()
    e = ctx.Event()
    p = ctx.Process(target=worker, args=(q, e), daemon=True)
    p.start()
    samples = []
    for i in range(n):
        print("=== ITER {} ===".format(i))
        sample = q.get()
        print(sample)
        samples.append(sample)
        e.set()
    p.join()
    print(samples)
```
Tensor values which are put to the queue are retrieved correctly with `q.get()`. However, it seems that in the next iteration, the last sample's storage is overwritten. The last print `print(samples)` gives samples different from the samples obtained from queue.

**Comment by fehiepsi** [comment]
@ailzhang That is what I did, but it only solves the error **Assertion `self->allocator() != nullptr' failed**. In the example of my last comment (I just edit it to reflect the remaining problem), `real_examples` is different from `examples`.

**Comment by ailzhang** [comment]
Oh I think the behavior is expected? On the receiver side it doesn’t have control over the lifetime of the tensor, it’s on the sender side. Once the sender destroys and reallocates a new tensor on that storage, the content in example changes. Unless you clone it (copy the content to somewhere receiver can manage), the memory on receiver side is only a peek of storage of sender side.

Thanks,
Ailing

________________________________

**Comment by fehiepsi** [comment]
Thanks for your explanation! It makes sense. Currently we don't see the advantage of GPU over CPU on our sampling so it is not quite necessary. In addition, cloning or moving results to cpu are doable on our side. Because of that, let's only fix the error in the topic.

@ailzhang , your PR fixes all of my pyro scripts. Thanks a lot for looking at this issue!

**Comment by ailzhang** [comment]
@fehiepsi See https://github.com/pytorch/pytorch/pull/16194#issuecomment-457343050
Actually I was wrong above as `sample` is still alive until it's reassigned and this is invalid in CUDA multiprocessing. Receiver should never use `sample` after `event.set()`. By calling `event.set()`, receiver is saying to sender, " okay I'm done using this tensor, feel free to do anything with it, I WILL NOT touch it anymore. To make sure my hands are off this storage, I'm going to `del sample`" . 
So the right way to do it is 
```
import torch
import torch.distributions as dist
import torch.multiprocessing as mp

torch.set_default_tensor_type(torch.cuda.FloatTensor)
n = 10

def model():
    d1 = dist.Normal(torch.zeros(3), 1)
    v1 = d1.rsample()  # no error when replace `.rsample()` by `.sample()`
    d2 = dist.Normal(v1, 2)
    v2 = d2.rsample()
    return [({"dist": d1, "value": v1}), ({"dist": d2, "value": v2})]

def worker(q, e):
    for i in range(n):
        sample = [torch.zeros(1), torch.ones(1)]  # no error when remove this line ???
        sample = model()
        q.put(sample)
        e.wait()
        e.clear()

if __name__ == "__main__":
    ctx = mp.get_context("spawn")
    q = ctx.Queue()
    e = ctx.Event()
    p = ctx.Process(target=worker, args=(q, e))
    p.start()
    samples = []
    for i in range(n):
        print("=== ITER {} ===".format(i))
        sample = q.get()
        del sample ### REQUIRED! Once you call e.set(), this memory is no longer valid. It can be random.
        e.set()
    p.join()
```
Please let us know if this solves your problem. Indeed cross-process refcounting for CUDA IPC memory is the right long term solution for this. 
As I said in the PR, I will push an example to our multiprocessing best practices for our current implementation.

**Comment by neerajprad** [comment]
@ailzhang - Thanks for the clarifying example! Let me talk about our use case a bit, because it is possible that there are certain alternatives that we haven't considered. 

We would like to be able to use multiprocessing to run MCMC chains in parallel. For this, we spawn workers in parallel that generate samples and put them on a shared queue. The main process then reads off the samples from the queue. Currently, it appears that there are two ways to deal with CUDA tensors:

 - *Clone the tensors in the main process* so that the memory that it points to remains valid throughout its lifetime in the main process. This seems reasonable but I suppose that we now have two memory copies per sample - one in the worker when we move the tensor into shared memory and another in the main process when we clone the tensor again. I am wondering if it is possible to use tensors as [proxy objects](https://docs.python.org/2/library/multiprocessing.html#proxy-objects) to achieve this, as this seems like a fairly common use case. In the torch multiprocessing docs, it says `Even if you have a pool of processes sending data to a single one, make it send the buffers back - this is nearly free and will let you avoid a copy when sending next batch.` - could you elaborate on what is meant by sending the buffers back?
 - *Maintain reference to the original tensor in the worker process* - This seems like another solution, but to prevent holding on to memory unnecessarily in the worker process once the tensors are reduced in the main process, is there any way we can signal that they can be garbage collected in the worker process?

**Comment by ezyang** [comment]
cc @VitalyFedyunin who is looking into implementing interprocess refcounting for CUDA tensors. When this is done, the naive code you've written above should just work.

In the meantime, however, I think manually implementing some sort of message passing to garbage collect (or some sort of polling mechanism on server side). You are using multiprocessing already, so you could use one of the primitives there to signal when you're done processing a sample. If your processing is done in just this manner (and the tensors don't otherwise "leak") this seems like a relatively simple way to avoid the copying. (But to reiterate: this shouldn't be necessary, but it will take us some time before we can fix it.)

**Comment by neerajprad** [comment]
Thanks for the pointers, @ezyang. I think we will just clone the tensors for now since keeping the worker processes alive until the main process has no remaining references to any of the sampled tensors will make the code more complicated than it needs to be. We are looking forward to the implementation of interprocess refcounting for CUDA!

**Comment by VitalyFedyunin** [comment]
#16854 merged to master, please let me know if it solves your problem(s)

**Comment by fehiepsi** [comment]
Thanks a lot for a great work @VitalyFedyunin ! I'll test and get back to you.

**Comment by fehiepsi** [comment]
@VitalyFedyunin The PR works great for multi-chain MCMC in GPU, which is our main usage of multiprocessing in GPU! Thanks a lot! cc @neerajprad
