### ISSUE TITLE
Floating Point Exception on PyTorch nightlies

### ISSUE THREAD

**Issue by syed-ahmed** [pytorch/pytorch#17029]
## 🐛 Bug
We are seeing a floating point exception in the nightly containers but not in v1.0.1 container. I believe there is a mkl-dnn patch that needs to be on master?

@soumith

**Comment by ngimel** [comment]
This is fixed in the latest mkl-dnn https://github.com/intel/mkl-dnn/blob/b88908909240bdab10f1cb7c256caa264fc15067/src/cpu/xbyak/xbyak_util.h#L216, but not in the mkl-dnn hash pytorch is using https://github.com/intel/mkl-dnn/blob/830a10059a018cd2634d94195140cf2d8790a75a/src/cpu/xbyak/xbyak_util.h#L186.
mkl-dnn comes as ideep submodule, and ideep is not updated to point to the latest mkl-dnn, so it's a bit of a mess.

**Comment by ngimel** [comment]
#16183 is related

**Comment by soumith** [comment]
@mingfeima can you help get this patch into a ideep/mkl-dnn release that pytorch uses. For v1.0.1, I manually patched the source before building binaries.

**Comment by mingfeima** [comment]
@soumith will do.

**Comment by Jianhui-Li** [comment]
@Soumith  We has done the internal validation and submit a patch for this. https://github.com/pytorch/pytorch/pull/17107

**Comment by soumith** [comment]
Thank you.
Fixed via https://github.com/pytorch/pytorch/pull/17107
