### ISSUE TITLE
Convlstm module?

### ISSUE THREAD

**Issue by leesunfreshing** [pytorch/pytorch#1706]
Any plans to have this implemented as a basic module? Moreover, it would be really nice if pytorch have the rnn package in torch wrapped

**Comment by Kaixhin** [comment]
Would like to have a solid implementation as part of the library too. Started drafting up peephole LSTMs and convolutional LSTMs for some people [here](https://gist.github.com/Kaixhin/57901e91e5c5a8bac3eb0cbbdd3aba81), but while the convolutional LSTM works on basic options I haven't a) correctly followed the equations from the original paper and b) adapted the hidden state to work with all kinds of conv options (like stride, dilation etc.).

On that note, implementing this would be easier if peephole connections were added to the main code too (https://github.com/pytorch/pytorch/issues/630).

**Comment by ndrplz** [comment]
I also drafted a ConvLSTM version [here](https://github.com/ndrplz/ConvLSTM_pytorch).

I'm still working on it, but maybe someone can find it useful nonetheless.

**Comment by yl1991** [comment]
Any plans to officially support it?

**Comment by guanfuchen** [comment]
Convolutional LSTM is great for video prediction, can't wait for the official support for relaxing the coding for video prediction.

**Comment by geolvr** [comment]
Because there is no official implementation of this module, I have to turn back to keras.

**Comment by AlexeyAB** [comment]
It would be nice to add a `conv-LSTM` layer that is much better for Training and Detection on Video - faster and higher mAP@0.5: https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-494148968

Implementation: https://github.com/AlexeyAB/darknet/blob/24f7d94ab4214dd43805270056effd95bfd9a5d9/src/conv_lstm_layer.c#L809-L1185


You can use the same conv-LSTM approach that is used in Keras: https://github.com/keras-team/keras/blob/master/keras/layers/convolutional_recurrent.py#L902-L906

from this paper: http://arxiv.org/abs/1506.04214v1

With parameter that enables/disables the Peephole-connection (red rectangles): 

![image](https://user-images.githubusercontent.com/4096485/58435238-2ee3b400-80c8-11e9-85d5-a863121332f2.png)

since there are variants without the peephole-connection when it isn't required: https://en.wikipedia.org/wiki/Long_short-term_memory#Variants

**Comment by Kaixhin** [comment]
Given the current level of the JIT, would definitely be worth getting an official module in.

**Comment by ailzhang** [comment]
We'll be happy to accept a PR from community if someone wants to take it.

**Comment by soumith** [comment]
before we see a PR, I'd want to see what the proposed API is. Wouldn't want to go all the way to making a PR and then iterating on the API a lot.

**Comment by Kaixhin** [comment]
Might make sense to do `nn.Conv2dLSTMCell` first (functional wrapper) and then `nn.Conv2dLSTM`. Going by Keras (linked above) and [Sonnet](https://github.com/deepmind/sonnet/blob/master/sonnet/python/modules/gated_rnn.py#L1225-L1241), they just assume the same convolution hyperparameters (e.g. kernel size) for both the input and hidden state, so doing this would mean the same API as `nn.Conv2d` (though seems like it would be useful to also have a `peephole` bool flag at end). Changing hyperparameters for both input and hidden separately would be more flexible but I don't think we need to support this at this point.

**Comment by tcapelle** [comment]
Is this still on the way?

**Comment by aiqc** [comment]
Without ConvLSTM, multivariate forecasting with sliding windows is limited to 2D input from a single site. 

`[batch, windows, timepoints, features]`

**Comment by tcapelle** [comment]
I am still hoping to have a fast/native ConvLSTM/GRU layer in 2021

**Comment by MarcoVela** [comment]
still hoping in 2022
