### ISSUE TITLE
How to release base/all cuda memory(including cuda context, cudnn handles etc)?

### ISSUE THREAD

**Issue by dragonbook** [pytorch/pytorch#17157]
## ❓ Questions and Help
Hi, all,

I want to free all gpu memory which pytorch used immediately after the model inference finished. I tried torch.cuda.empty_cache(), it released some but it cannot release the final ~600MB gpu memory, and can only be released after the program or python script finished.  As pointed out by @soumith at [discussion](https://discuss.pytorch.org/t/how-to-free-gpu-memory-nothing-works/23158/5), I think they might be the final **base memory**.

So, How can I release all used cuda memory, including the **base memory** which pytorch used as GPU for cuda context, CUDA RNG context, streams and GPU for CuDNN handles etc?

Thanks!

**Comment by ezyang** [comment]
This may be difficult to do. Can you help us understand why you want to release all GPU memory after model inference is finished? For example, would it be sufficient to do CUDA processing in a separate process, and terminate the process immediately when you're done?

**Comment by dragonbook** [comment]
Hi, ezyang,

I am depolying a keypoints estimation model into a 3d c++ application and the model currently is implemented in Pytorch(python). I added a simple c++ interface which uses pybind11 [py::eval_file](https://pybind11.readthedocs.io/en/master/advanced/pycpp/utilities.html) method to call the python script. I tried to call that c++ interface with a separate c++ std::thread, the gpu memory was not released after the thread was joined.  And when I open more applications, the gpu will out of memory.

I'm not fully understand how to use a separate process to make it as you suggested. Is that mean I must start a new *process* in my python script to do the model inference(CUDA processing)? 

Besides, I am also starting to try libtorch, is there a same problem?

**Comment by ezyang** [comment]
Is it possible for you to share some of the code involved? If you for example, load PyTorch and then run multiple models through it, it's true that there will be a base allocation, but it should be reused across the invocations and no memory leak should occur. So I'm not sure why exactly an out of memory is occurring here, if you aren't leaking something else.

My original interpretation of your comment was, after running the PyTorch program you wanted to completely shut down the Python interpreter and CUDA interpreter and dispose it, because the fixed allocation means you don't have enough GPU for other things. In that case, I do agree, running Python in a separate process seems like a good idea. So you wouldn't run `py::eval_file`; instead you'd just call the Python interpreter yourself. (Maybe pybind11 has a helper to do this.) You could also have the Python script itself create a subprocess before it imports torch.

**Comment by colesbury** [comment]
The CUDA driver uses a a few hundred MBs of GPU memory at initialization for all the CUDA kernels in PyTorch. On Pascal GPUs it uses ~600-650 MB. On Maxwell GPUs it uses ~350 MB. There is no way to release this memory.

**Comment by dragonbook** [comment]
Yes, I want to completely shut down the python interpreter and release all GPU memory. The target computer only has 2GB GPU memory. Before I use torch.cuda.empty_cache(), it used about 1.5GB, and launching the second application(and call the python script again) will result in gpu out of memory error. With torch.cuda.empty_cache(), it uses ~600MB now. 

Thank you all, I'll experiment with a separate process to try to release the base memory. And my final question is if multiple *processes* share the same base memory?

**Comment by ezyang** [comment]
They don't.

**Comment by dragonbook** [comment]
Ok, thanks!
