### ISSUE TITLE
[feature request] Variable.attach() method to set requires_grad = True

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1734]
`autograd.grad(...)` requires Variables attached to the graph (this is a tiny bit counter-intuitive, since gradients are explicitly asked for).

Given that `volatile` would propagate from the beginning of the network, maybe an `attach()` method would be convenient to have (conversely from `detach`, it would enable `requires_grad`).

```python
import torch
import torch.nn

i = torch.autograd.Variable(torch.Tensor(1, 4, 8, 8))
m = torch.nn.Conv2d(4, 4, 1)
o = m(i)
g = torch.autograd.grad(o.sum(), i)[0]

print(g.sum())
```

```
Traceback (most recent call last):
  File "test_.py", line 7, in <module>
    g = torch.autograd.grad(o.sum(), i)[0]
  File ".../torch/autograd/__init__.py", line 153, in grad
    inputs, only_inputs)
RuntimeError: One of the differentiated Variables appears to not have been used in the graph
```

**Comment by apaszke** [comment]
Can you give an example showing how you'd imagine using `.attach()`? cc @Kaixhin

**Comment by vadimkantorov** [comment]
Introducing `attach` to the example above, it may be:
```python
import torch
import torch.nn

def attach_(variable):
    variable.requires_grad = True
    return variable

i = torch.autograd.Variable(torch.Tensor(1, 4, 8, 8))
m = torch.nn.Conv2d(4, 4, 1)
o = m(attach_(i))
g = torch.autograd.grad(o.sum(), i)[0]

print(g.sum())
```

Here `attach_` ensures that no-error execution of `autograd.grad`. I guess `attach` generating a new variable object should also be possible.

**Comment by Kaixhin** [comment]
Looks like what I need is making the graph modifiable - what Chainer exposes with [`set_creator`](https://docs.chainer.org/en/latest/reference/core/generated/chainer.variable.VariableNode.html#chainer.variable.VariableNode.set_creator) and [`unchain`](https://docs.chainer.org/en/latest/reference/core/generated/chainer.variable.VariableNode.html#chainer.variable.VariableNode.set_creator). If you can keep on going up `creator`s, backwards in the graph, then you can detach and reattach further down in the graph (without having to keep multiple copies, as I discussed in https://github.com/pytorch/pytorch/issues/2203).

So whilst PyTorch gives you plenty of freedom in constructing the forwards graph, this could potentially allow you to "transplant" the top of one graph onto the bottom of another one. Rather than going backwards on what happened on the forwards, you can go backwards on all kinds of possibilities.

**Comment by vadimkantorov** [comment]
fixing undergoing in https://github.com/pytorch/pytorch/pull/6561
