### ISSUE TITLE
The Python __doc__ for each global op should be carried over from its source

### ISSUE THREAD

**Issue by rdipietro** [pytorch/pytorch#17355]
## 🐛 Bug

`__doc__` is missing for many global operators (`torch.log_softmax`, `torch.logsumexp`, ...).

## To Reproduce

```python
print(torch.log_softmax.__doc__)
# None
```

```python
print(torch.nn.functional.log_softmax.__doc__)
# Correctly prints documentation.
```

## Expected behavior

Global ops should contain valid `__doc__`s.

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX TITAN Black
GPU 1: GeForce GTX TITAN Black
GPU 2: GeForce GTX TITAN Black
GPU 3: GeForce GTX TITAN Black

Nvidia driver version: 390.30
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.1

**Comment by rdipietro** [comment]
This is especially relevant because sometimes the global op differs from e.g. the `torch.nn.functional` op, and in these cases `__doc__` should be filled in appropriately (see e.g. https://github.com/pytorch/pytorch/issues/16322)

**Comment by SsnL** [comment]
You shouldn't use `torch.log_softmax`. It is not a public API.

**Comment by rdipietro** [comment]
@SsnL I also mentioned `torch.logsumexp`, which is part of the public API. And, as also noted, both of these are just examples, as there are many other examples, too.

Your response seems more like a passive way of saying "we don't care enough about proper `__doc__`s to fix this." If this is the case, it would be simpler to just say so.

**Comment by rdipietro** [comment]
@SsnL My apology! I was wrong about this. I was naively thinking that the problem held for many other ops, but I think you are correct in saying that it's specific to unsupported ops.

**Comment by rdipietro** [comment]
I'm sorry for the confusion. Closing.

**Comment by SsnL** [comment]
Sorry for giving that impression. I think `logsumexp` does have docstring (code at https://github.com/pytorch/pytorch/blob/562fa55f3dfc2d3ce1cac19e3ec9dab202e06b3b/torch/_torch_docs.py#L2500-L2526). In fact, we really care about documentation. We have specific tests for checking the existence of docstrings (see https://github.com/pytorch/pytorch/blob/562fa55f3dfc2d3ce1cac19e3ec9dab202e06b3b/test/test_torch.py#L160). At the moment it covers `tensor.*`, `torch.nn.*`, and `torch.nn.functioanl.*`. The reason that it doesn't yet check `torch.*` is due to the namespacing problem (we dump all ops into `torch.*`). As you can see in the test, we plan to test those as well when the issue is fixed.

**Comment by rdipietro** [comment]
Sorry, this was really my mistake. I fooled myself into believing that yesterday I also printed `torch.logsumexp.__doc__`, but obviously I had not, and I must have been incorrectly generalizing from `torch.log_softmax`. Thanks for the response.
