### ISSUE TITLE
What is a version/git-hash of nightly build? 

### ISSUE THREAD

**Issue by junjihashimoto** [pytorch/pytorch#17368]
## 🚀 Feature

Nightly build does not include git-hash of pytorch.
So we can not know what the build is.

https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

I know the zip includes build_version which is like "1.0.0dev20190221".
Could you add git-hash of pytorch in build_version and include native_functions.yaml and the README of the yaml?

## Motivation

We are writing ffi-bindings by using nightly build and native_functions.yaml of pytorch-github.
Both the build and the yaml-spec's format are changed frequently and do not match version.

**Comment by soumith** [comment]
cc: @pjh5 

If I remember it's the first commit of that date in GMT timezone

**Comment by ezyang** [comment]
NB: we must not back this hash into a C++ header for development as that will trigger lots of recompiles

**Comment by junjihashimoto** [comment]
> If I remember it's the first commit of that date in GMT timezone
Thx.

**Comment by pjh5** [comment]
It is actually 05:05 GMT.

cc @kostmo

**Comment by junjihashimoto** [comment]
@soumith 
If I make PR to insert git-hash and *.yaml, Could you merge it?

**Comment by soumith** [comment]
@junjihashimoto where would you insert the git-hash, and what yaml are you going to insert?

**Comment by austinvhuang** [comment]
For context, we're transitioning away from building (an older) aten from scratch as part of our build towards piggybacking on the pre-built libtorch binaries. 

I'm not sure a single PR would solve this since the hash in the repo would need to continually be updated. The underlying goal would be to have a handle on correspondence between the libtorch zip deployment artifact and git hash.

The ideal scenario would be for the git hash in the deployment artifact (for example, as the 2nd line of the build-version file) while also persisting past builds so they are consumable at a fixed link. This could be useful for other users as well for testing / comparisons / rolling back (if needed) between versions.

If this is too much work, we'll figure out some other way. We'd probably pin to a particular artifact, hold onto it locally and periodically jump to the latest so we're not guessing at the version correspondence too often.

**Comment by pjh5** [comment]
Fwiwi t's not much work at all. When we built the linux wheel and libtorch packages we unzip them, mess around with them, and then rezip them back up. If you just want a txt file called build_hash or something like that you could just add that file before the wheel gets zipped up here https://github.com/pytorch/builder/blob/master/manywheel/build_common.sh#L300 . A line like
```
echo "$(pushd $pytorch_rootdir && git rev-list --max-count 1 HEAD)" > $PREFIX/build_hash
```
would probably do the trick. There is more work to get the same file in the python packages or on non-linux.

**Comment by kostmo** [comment]
FYI @pjh5 here's a more compact `git` command for that:

    git rev-parse HEAD

**Comment by junjihashimoto** [comment]
Are these all?

```
$ git grep -n 'zip -r'
manywheel/build_common.sh:156:        zip -rq /tmp/$LIBTORCH_HOUSE_DIR/libtorch-$VARIANT-$PYTORCH_BUILD_VERSION.zip libtorch
manywheel/build_common.sh:301:    zip -rq $(basename $pkg) $PREIX*
wheel/build_wheel.sh:185:    zip -rq "$PYTORCH_FINAL_PACKAGE_DIR/libtorch-macos-$PYTORCH_BUILD_VERSION.zip" libtorch
```

**Comment by junjihashimoto** [comment]
If these are corrent, see the PR.
