### ISSUE TITLE
[jit] Support for modules that have hooks when compiling

### ISSUE THREAD

**Issue by rami3e** [pytorch/pytorch#17571]
## 🚀 Feature

Currently forward or backward hooks (i.e concatenation of features in UNET) are not supported in jit tracing.  

Run into this error when attempting: `ValueError: Modules that have hooks assigned can't be compiled` 

source: torch.jit.TracedModule(ScriptModule)

**Comment by suo** [comment]
Hi, could you explain a little bit more about your use case? For example, would it be possible as a workaround to inline the hook into the `forward()` of your model?

**Comment by rami3e** [comment]
Sure. It is similar to U-net style skip connections but I also pass these features through another conv layer. It is actually in the `forward()` currently. ie.
```
def forward(self, input, enc_feats):  
     # ....
     y2 = torch.cat((y0, (nn.Conv2d...)))
```

**Comment by rami3e** [comment]
has this been addressed elsewhere ?

**Comment by eugeneware** [comment]
@suo It's for getting U-nets to work where hooks are used to store activations from the forward pass. See [code here](https://github.com/fastai/fastai/blob/master/fastai/vision/models/unet.py#L46) for the model that many people in the fast.ai course are trying to compile.

It turns out that if you just comment out that error the compilation works.

So it would be great if there was some option that we could pass to bypass that exception, and perhaps just get a warning.

You can follow some of the discussion in this forum thread [here](https://forums.fast.ai/t/loading-unet-model-into-c-using-the-new-torch-script-feature-of-pytorch-1-0/23810/9) for some more context.

Thanks for your great work!

**Comment by eugeneware** [comment]
FYI [this issue](https://github.com/pytorch/pytorch/issues/20862) is related to this issue also.

**Comment by suo** [comment]
@zdevito do you remember why we explicitly disallow hooks?

**Comment by zdevito** [comment]
I can't remember. We should revisit it and see if wean just enable it.

**Comment by pshashk** [comment]
`nn.utils.spectral_norm` is also implemented via hook.
```python
torch.jit.trace(nn.utils.spectral_norm(nn.Linear(8,8)), torch.rand(4,8))
```
```
ValueError: Modules that have hooks assigned can't be compiled
```

**Comment by fuzic** [comment]
weight norm also. Are models using these just unexportable?

https://pytorch.org/docs/stable/_modules/torch/nn/utils/weight_norm.html

**Comment by eellison** [comment]
@zdevito @suo any thoughts ?

**Comment by eugeneware** [comment]
Thank you @eellison ! :tada: :clap:
