### ISSUE TITLE
Why torch wheel is so huge (582MB)?

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/pytorch#17621]
## 🚀 Feature

Please reduce the size of the Pytorch installation wheel.

torch-gpu (~583MB)

```
Collecting torch (from stanfordnlp->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/31/ca/dd2c64f8ab5e7985c4af6e62da933849293906edcdb70dac679c93477733/torch-1.0.1.post2-cp36-cp36m-manylinux1_x86_64.whl (582.5MB)

```
## Motivation
The current installation wheel (GPU) is huge (582.5MB) compared to other frameworks:

Tensorflow-gpu (~350MB)

Tensorflow-cpu (~93MB)
```
  Downloading https://files.pythonhosted.org/packages/77/63/a9fa76de8dffe7455304c4ed635be4aa9c0bacef6e0633d87d5f54530c5c/tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (92.5MB)
```

Gensim (24.2MB)
```
Collecting gensim (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/d7/b9/6c93685bed0026b6a1cce55ab173f6b617f6db0d1325d25489c2fd43e711/gensim-3.7.1-cp36-cp36m-manylinux1_x86_64.whl (24.2MB)
```

scikit-learn (~13MB)
```
Collecting scikit-learn==0.19.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/3d/2d/9fbc7baa5f44bc9e88ffb7ed32721b879bfa416573e85031e16f52569bc9/scikit_learn-0.19.1-cp36-cp36m-manylinux1_x86_64.whl (12.4MB
```

etc.

This causes Docker images having Pytorch installed, that are typically for ML tools between 2-4GB to have at least 1/4 of the space due to Pytorch installation (!).

**NOTE.**
This is the GPU version. My aim is not to compare Pytorch wheel to other framework, the point is why the torch wheel is a half of a Gigabyte?

**Comment by shane-carroll** [comment]
You're comparing the CPU tensorflow to the GPU pytorch. Non-gpu pytorch is much smaller. The GPU tensorflow is about 350MB.

**Comment by loretoparisi** [comment]
@shane-carroll thank you for the clarification. Okay. The GPU version is still huge, a half of a gigabyte!

**Comment by HapeMask** [comment]
The number of GPU architectures targeted by the binary is a large contributor to binary size. If you'd like a smaller GPU binary, you can change TORCH_CUDA_ARCH_LIST accordingly. For example, if you want to only support compute 5.0, you can set TORCH_CUDA_ARCH_LIST=5.0+PTX as opposed to the more comprehensive list built by default by the PyTorch devs.

(I'm not a PyTorch developer, just someone who has built smaller versions of the library.)

**Comment by l1t1** [comment]
interesting

**Comment by loretoparisi** [comment]
@HapeMask thanks, this means that the python binary wheels are released with

``` 
TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX"
TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
```

So one option would be to build it from scratch, targeting a specific architecture. The problem is that if you have `torch` as a dependency of other frameworks, you should install it *before* everything else, so that next `pip install` will skip the fat binary wheel install eventually.
Otherwise, it should be possible to make a slice of the fat-binary removing extra architectures, but not sure how to do it in this case.

**Comment by yf225** [comment]
@loretoparisi you are correct. Unfortunately there is no way to let `pip install` skip a dependency currently.

Making a slice of the fat-binary is likely not possible technically. cc @soumith @pjh5

**Comment by pjh5** [comment]
Yes a big part of this is GPU bits, especially including code for multiple CUDA architectures so the same binary will work on several Nvidia GPUs. You can get a smaller binary by building from source and only specifying the architecture that you need for your GPU, but for the public binaries we just want one to fit them all.

**Comment by loretoparisi** [comment]
@pjh5 maybe you could deploy a light version with only the latest architecture

**Comment by pjh5** [comment]
@loretoparisi I don't think we're planning on special binaries for 'advanced' use cases like this for python distros for a while (GCC ABI of 1 also falls into this category) because of the potential confusion it will cause. To work this into pip or conda we'd need a different name like pytorch-nightly-latestcuda, but then once the latest architecture changes that will be out of date. We don't want to end up with many pytorch-nightly-cudaarch7.5 , pytorch-nightly-cudaarch8.0 then that will likely cause confusion with 'pytorch-nightly cuda80' , plus we don't want to mantain so many different packages.
cc @kostmo

**Comment by loretoparisi** [comment]
@pjh5 @kostmo I see, it makes sense. I'm curious why latest TF (1.13) is more than 200MB smaller.

**Comment by de-code** [comment]
From pip, torch 1.9.1:

* torch-1.9.1-cp39-cp39-manylinux1_x86_64.whl (831.4 MB)
* torch-1.9.1-cp39-cp39-win_amd64.whl (222.0 MB)
* torch-1.9.1-cp39-none-macosx_10_9_x86_64.whl (218.8 MB)

**Comment by loretoparisi** [comment]
@de-code Wow! Why `macOS` version is only 218MB and `linux` is 831MB? Is this due to GPU slice in `linux` versions?

**Comment by aakashsur** [comment]
From torch 1.10.0 for CUDA 11 - **1.8 GB**
 https://download.pytorch.org/whl/cu113/torch-1.10.0%2Bcu113-cp38-cp38-linux_x86_64.whl (1821.4 MB)

**Comment by arogozhnikov** [comment]
scale is already harsh, but how fast it grows is scary. 
Solid part of CI resources would be just downloading torch

**Comment by guest271314** [comment]
I have not completed an installation of https://github.com/coqui-ai/TTS due to torch download over 700MB. 

> You can get a smaller binary by building from source and only specifying the architecture that you need for your GPU

How to achive that?

**Comment by guest271314** [comment]
@loretoparisi Did you figure out a way to build a minimal torch?

**Comment by merryHunter** [comment]
This seems to be a serious issue for production deployments in docker containers. Seriously, what can be execution plan to reduce the wheel size (at least for inference purpose ) to at e.g. ~200 MB instead of 776 MB?

**Comment by loretoparisi** [comment]
> This seems to be a serious issue for production deployments in docker containers. Seriously, what can be execution plan to reduce the wheel size (at least for inference purpose ) to at e.g. ~200 MB instead of 776 MB?

totally agreed and you went straight to the point. For deployment in production environment it is a struggle every time the docker image is built. A significant percentage of the container is taken by torch's 776MB as lower boundary!, when adding other necessary packages for datasets, parallel distributed training, etc. lower bound for a complete working env may be accounted for > 1 - 1,5GB image space.

**Comment by loretoparisi** [comment]
> @loretoparisi Did you figure out a way to build a minimal torch?

unfortunately not so far, the effort of compiling from scratch is still too much.

**Comment by merryHunter** [comment]
@loretoparisi I see the reason of that for GPU runtime, though in our case we use CPU for inference. Do you think it could be public wheels instead of compiling myself?

**Comment by merryHunter** [comment]
Can we possibly bring other maintainers into our conversation? Of course, optimizations are not liked as new cool features, yet it will resolve pain for many devs building docker images locally and pulling over this 700MB every time docker layers rebuilt.

**Comment by de-code** [comment]
> @loretoparisi I see the reason of that for GPU runtime, though in our case we use CPU for inference. Do you think it could be public wheels instead of compiling myself?

Just pointing out that there are public CPU builds that are of a more reasonable size (~180 MB), unfortunately not on pypi but pytorch's own repo.

e.g. you could install it using the following `requirements.txt`:

```text
-f https://download.pytorch.org/whl/torch_stable.html
torch==1.9.1+cpu
torchvision==0.10.1+cpu
```

**Comment by soumith** [comment]
- for CPU inference, as @de-code commented, you do not need the full giant wheel.
- for GPU inference, the PyTorch wheel includes everything including the relevant CUDA bits. So in your base docker image, you can avoid including the ~2.5GB of CUDA/CUDNN dependencies entirely because PyTorch wheel statically links to the CUDA/CuDNN dependencies that it needs.

**Comment by ArtemSokolov** [comment]
How is everybody getting it down to 700MB? Every time I include `RUN pip install torch` inside a `Dockerfile`, the image size jumps 5+GB. It's a bit out of control.

Minimal example:
```
$ cat Dockerfile
FROM python:3.8

RUN pip install torch

$ docker build -t test .

$ docker images
REPOSITORY                             TAG       IMAGE ID       CREATED         SIZE
test                                   latest    c08d23d59847   7 seconds ago   6.04GB
python                                 3.8       e96a212a8ca8   9 days ago      915MB
```

**Comment by arogozhnikov** [comment]
@ArtemSokolov I guess your 5GB = 2.5GB of torch with gpu (see prev comment) + additional copy in pip cache (which you'd better bypass in dockerfiles).

**Comment by ArtemSokolov** [comment]
Good call. Flipping to `RUN pip install --no-cache-dir torch` drops the image size to 4.26GB. Thanks, @arogozhnikov!

**Comment by edgahan** [comment]
Some people mentioned minimal torch above. I ended up installing CPU only version which was smaller. So perhaps helpful.

My use case: Building a docker image for a PaaS that had a size limit. (Also just generally good to keep it low). Python web app with some torch stuff going on due to Whisper, etc. No GPU usage, all CPU.

Problem: When building the docker image on my mac it was 2.5GB due to Arm architecture but when being built by a remote builder on AMD64 architecture the image size exploded to 12.5GB. A lot of this size was due to torch and nvidia packages and an assumption on GPU usage.

What I did: 
- Build the AMD version locally: `docker build --platform linux/amd64 -t image:latest .`
- Looked at what was making it so big, I inspected layers:`docker history image:latest`
- Saw that it was a `poetry` install command (I'm sure pip would do similar)
- Bash'ed into it: `docker run -it image:latest bash`
- Find out where site-packages are installed (e.g. `poetry env info`)
- Confirm there's some big packages: `du -h --max-depth=1 /root/.cache/pypoetry/virtualenvs/<some-python>/lib/python3.11/site-packages/ | sort -hr` (basically find site-packages)
<img width="1015" alt="Screenshot 2024-02-27 at 23 55 46" src="https://github.com/pytorch/pytorch/assets/287499/98c2fb5d-9ce9-4f9b-b683-b4fcd60d3a72">

- In `pyproject.toml` set torch source and re-run `poetry install` or similar.
```
[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
priority = 'primary'
```
- Verify torch size is reduced
<img width="790" alt="Screenshot 2024-02-27 at 23 57 07" src="https://github.com/pytorch/pytorch/assets/287499/1afdbf51-45bb-40b5-b0e0-dc5cdc48fa1c">

- As a bonus don't forget to clear some caches and artefacts from poetry/pip (e.g. 
```
rm /root/.cache/pypoetry/{cache,artefacts}
poetry cache clear --no-interaction --all pypi && \
  poetry cache clear --no-interaction --all _default_cache && \
  poetry cache clear --no-interaction --all torch
  ```

**Comment by wltjr** [comment]
I know this is closed, why I have no idea, as this problem is far from being solved!

This really needs to be split up into multiple packages, and people can install what ever for the hardware they have. This is pretty insane to go from [1.38GB to 4.05GB](https://hub.docker.com/repository/docker/unfrobotics/docker-ros1-noetic-gazebo-gym/tags) and that is with the much appreciated suggestion of `--no-cache-dir`. I can see about building from source, but the GPU may change, so probably need something with options. But I don't understand why the package cannot be split up.

I understand there is a [monolithic shared object](https://discuss.pytorch.org/t/libtorch-cuda-so-is-too-large-2gb/103155) `libtorch_cuda.so` which is the bulk of the size, and not easily repackaged etc, and support for various GPUs are compiled into that, but there has to be another way. This is crazy to have such space requirements for things not used, and no option for modularization. Also, to think about what all I have in my container, yet I need 2x the space for Torch...

I have packaged stuff for a few decades, and I have yet to see a package as big as that for such minimal usages. I think OpenOffice/LibreOffice might be jealous... But that is a lot of programs and software, and still requires less disk space than Torch.

Torch needs Ozempic bad!!!! Its morbidly obese!!!!

**Comment by merryHunter** [comment]
@wltjr Yes, and to imagine how much space and time to build so many Docker image deployments that may just use inference, or even training of certain network type is just insane. However, there is no roadmap to be proposed, apparently this is a very fundamental design issue...

**Comment by wltjr** [comment]
@merryHunter yes, it is a big problem for building and using docker images, I keep having space issues with 5x the amount of available disk space. I am having to let Github do the building, and even download, I have to nuke existing copies to free up space. Plus, all the bandwidth to transfer these bloated images around, that probably makes some telco happy!

**Comment by pablodz** [comment]
6Gb to have a pytorch working on docker image is crazy

**Comment by alireza-hariri** [comment]
I just noticed that there are two official versions of pytorch in docker-hub. the `-devel` and the `-runtime` versions.

Question 1. How do they reduce the  `-runtime` version?

Question 2. Is it possible to separate `torch` and `invidia` from other dependencies and mount them as an external volume to the docker image?

**Comment by wltjr** [comment]
Just as an observation, I may have to change some of my base docker images to Gentoo from Ubuntu. I went through a nightmare trying to get an env setup on hardware using Ubuntu, no docker. I finally reverted back to my archnemesis I been stuck on for decades, Gentoo.

If you can specific the `TORCH_CUDA_ARCH_LIST` for pip, assuming its building the package, which seems to be caffe2 inside of pytorch sources that provides actual `libtorch_cuda.so` it heavily reduces the install size.

I have not done this in a docker image yet, pip maybe download a prebuilt version, but the cachedir makes me think its building. Either way FYI. This is for 1 GPU, 4070, 8.9. The more you add to the list the bigger it gets, but if you know your hardware you can build a docker image specific for that much smaller but may have to use Gentoo as a docker base.

![Image](https://github.com/user-attachments/assets/f967f504-5988-4cb3-8d6a-0eadaf31765f)
