### ISSUE TITLE
Memory leak in ReduceLROnPlateau ?

### ISSUE THREAD

**Issue by YujiaBao** [pytorch/pytorch#17630]
## 🐛 Bug
The GPU memory keep increasing when calling `torch.optim.lr_scheduler.ReduceLROnPlateau` multiple times. Using `torch.optim.lr_scheduler.StepLR` does not have such issue.

## To Reproduce

```python
   while True:
        net = torch.nn.Linear(5000,5000)
        net = net.cuda()
        optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau( optimizer,
                'max', patience=args.patience, factor=0.5, verbose=True)
        # scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=30,
        #         gamma=0.1)
```

## Expected behavior
GPU memory keeps increasing until out of memory

## Environment

Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 14.04.5 LTS
GCC version: (GCC) 4.8.5
CMake version: version 3.13.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X

Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.3
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.1.9
[conda] magma-cuda80              2.1.0                         5    soumith
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.10                   py36_0    conda-forge
[conda] mkl_random                1.0.2                    py36_0    conda-forge
[conda] pytorch-pretrained-bert   0.3.0                    pypi_0    pypi
[conda] tensorflow-base           1.12.0          mkl_py36h3c3e929_0
[conda] torch                     1.0.0                    pypi_0    pypi
[conda] torchtext                 0.2.3                    pypi_0    pypi
[conda] torchvision               0.2.1                 py36_1000    conda-forge

**Comment by soumith** [comment]
I cant reproduce the issue in latest master. I have been running the following code snippet for hours.

```python
import torch

while True:
        net = torch.nn.Linear(5000,5000)
        net = net.cuda()
        optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau( optimizer, 'max', patience=20, factor=0.5, verbose=True)
```

Please check with 1.0.1 or latest pytorch nightly and see if somehow the issue got fixed for you as well.

**Comment by JohnGiorgi** [comment]
@soumith Hi, I am also getting the same issue in my setup. I am trying to run k-fold cross-validation. In each loop of my cross-validation code, I initialize a model, optimizer and scheduler. Memory on my GPU accumulates until I get `RuntimeError: CUDA out of memory`.

## To Reproduce

Steps to reproduce the behavior:

```python
import torch
from pytorch_transformers import WarmupConstantSchedule, WarmupCosineSchedule, WarmupLinearSchedule, WarmupCosineWithHardRestartsSchedule

# In my actual project, this is a for loop over the k-folds of k-fold cross-validation.
# In this example I use a while just to demonstrate the OOM error.
while True:
    net = torch.nn.Linear(10000, 10000)
    net = net.cuda()

    optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 1)

    # I also tried all these other schedulers. Same issue.
    # scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, 0.1, last_epoch=-1)
    # scheduler = WarmupCosineWithHardRestartsSchedule(optimizer, 1, 1000)
    # scheduler = WarmupConstantSchedule(optimizer, 1)
    # scheduler = WarmupCosineSchedule(optimizer, 1, 1000)
    # scheduler = WarmupLinearSchedule(optimizer, 1, 1000)

    del net, optimizer, scheduler
```

It does not seem to matter which scheduler I use. I originally ran into this issue using the schedulers for [`pytorch-transformers`](https://huggingface.co/pytorch-transformers/main_classes/optimizer_schedules.html#schedules) so I opened [an issue there](https://github.com/huggingface/pytorch-transformers/issues/1134), but after trying @YujiaBao example with various `pytorch` schedulers I run into the same issue. 

The issue occurs for both `torch==1.2.0` and `torch-nightly`  (as of 08/28/2019).

## Expected behavior

I expect to be able to initialize a new instance of `torch.optim.lr_scheduler` in each fold of a cross-validation loop without accumulating memory on the GPU across folds.

If I am simply doing this wrong, is someone able to point out how I might initialize a new scheduler for each fold _without_ this issue of accumulating memory?

## Environment
```
Collecting environment information...
PyTorch version: 1.3.0.dev20190827
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 410.104
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] pytorch-transformers==1.1.0
[pip] torch==1.3.0.dev20190827
[pip] torchvision==0.5.0a0+0bd7080
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.3.0.dev20190827 py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch-nightly
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torchvision               0.5.0.dev20190827      py37_cu100    pytorch-nightly
```
