### ISSUE TITLE
ONNX graph exporter: Gather operator on Axis 0

### ISSUE THREAD

**Issue by drnikolaev** [pytorch/pytorch#17697]
## 🐛 Bug

See also #16908 
After fixing INT64 issue we moved forward and stumbled upon the following:
```
ERROR:  In node 175 (convert_axis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
```
This is Gather on Axis 0. Seems like it has to be another axis. Please check it out.

**Comment by borisfom** [comment]
See also https://github.com/pytorch/pytorch/issues/17606

**Comment by borisfom** [comment]
Update: while it's similar in effect to #17606, its origin is slightly different. This one is being triggered by this code or equivalent: 
 x = x.view(x.size(0), -1)

One TRT workaround is to pre-compute x.size(0) and save in the class. I wonder if there is a better way to express same flatten operation without explicitly referring to size(0) though.

> See also #17606

**Comment by gottbrath** [comment]
Folks, 

According to the info I am seeing this issue is affecting PyTorch -> ONNX -> TRT with a wide range of frequently used and relatively well understood models that arguably "should just work"

bvlc_alexnet
resnet50 (both the standard torchvision and the nvidia variant)
densenet121
inception_v1
inception_v2
inception_v3
squeezenet
vgg16
vgg19

**Comment by joohoonl-nv** [comment]
Also see PR #18698

**Comment by drnikolaev** [comment]
Duplicate of #17606
