### ISSUE TITLE
DataLoader autoconverts Float to Double

### ISSUE THREAD

**Issue by vlasenkov** [pytorch/pytorch#1773]
Attempting to extract tensors from pandas dataframe:
```
>>> df.dtypes
A                           float64
B                        float64
C                             float64
```
Then building a DataLoader:
```
train_set = data_utils.TensorDataset(
    torch.from_numpy(df.as_matrix(['A', 'B'])).float(),
    torch.from_numpy(df['C'].values).float(),
)
train_set_loader = data_utils.DataLoader(train_set, batch_size=50, shuffle=True)
```
Despite the call of `float` method:
```
>>> next(iter(train_set_loader))
...
  1
 [torch.DoubleTensor of size 50]]
```
... I get double tensor

**Comment by fmassa** [comment]
Could you provide a minimum reproducible code example?
The only way I see that this could happen is if your target (or second) tensor is 1D, so when you index it (in the dataset, `C[0]`) it returns a python `float` (which is double), and thus the [created tensor is a double](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L103).

I see no way of fixing it in pytorch except if we introduce scalar types, and indexing returns a scalar instead of a python number.

For your problem, an easy solution is to return numpy arrays instead of torch tensors. This will be less efficient on multi-threaded setups (and can lead to errors for very large arrays), but should fix your case.

**Comment by vlasenkov** [comment]
Yes, the target is 1D. The issue is solved by adding a dimension to the target:
```
train_set = data_utils.TensorDataset(
    torch.from_numpy(df.as_matrix(['A', 'B'])).float(),
    torch.from_numpy(df.as_matrix(['C'])).float(),
)
```
