### ISSUE TITLE
Default forward method for ModuleList and ModuleDict

### ISSUE THREAD

**Issue by eskjorg** [pytorch/pytorch#17765]
## 🚀 Feature
Add default `forward()` methods for `nn.ModuleList` and `nn.ModuleDict` that returns list/dict of item-wise forward.

## Motivation

At several places in my projects, I have code like the following:

```
class NetworkHeads(nn.ModuleList):
    def forward(self, x):
        return [module(x) for module in self]
```

or like

```
class TaskHeads(nn.ModuleDict):
    def forward(self, x):
        return {key: module(x) for key, module in self.items()}
```

The classes `NetworkHeads` and `TaskHeads` are necessary since ModuleList and ModuleDict doesn't come with their own forward methods. Although being only 3 lines long, these classes are slightly annoying.

## Proposal
I believe that my use case above might be very common. Could it make sense to define such forward methods by default in these containers?

**Comment by apaszke** [comment]
I'm a bit ambivalent. I can't see why parallel composition would be the right choice when you have e.g. an option of composing those modules sequentially. It's ambiguous, so I don't think we should implement it. As you've noticed you only need 3 lines to implement this in any project that needs this.

**Comment by soumith** [comment]
the exact `forward` methods to be specified will get controversial, because the most natural usage of ModuleList or ModuleDict are not obvious.

However, the biggest danger is that people will use the `forward` expecting it to do something smart wrt memory (or worse, do what people want which is again not obvious), but it'll default-compute all outputs.

For example, viewing a `forward` for `ModuleList` similar to `Sequential` is actually not far-fetched (I actually thought of a `forward` for ModuleList as a first-reaction to be similar to Sequential)

I thought a bit about it, and I'm a bit ambivalent, but am leaning torwards conservatively not adding the functionality.

**Comment by fmassa** [comment]
I second @apaszke and @soumith here. There is no single well-defined semantics for `ModuleList` and `ModuleDict`.

Historically, `ModuleList` and `ModuleDict` are only `nn.Module` wrappers to make using `dict` / `list` easier to handle inside `nn.Module`. In an ideal world, I think we wouldn't have those abstractions and would use just `dict` / `list` instead, but that complicates other things down the road.

I'd vote for closing this issue as a wontfix

**Comment by eskjorg** [comment]
Those are good points. Thanks for your input.

I am doing fine with 3-liners so long.
