### ISSUE TITLE
[autodiff] Fix owning model used in `differentiate`

### ISSUE THREAD

**Issue by ZolotukhinM** [pytorch/pytorch#17929]
Currently `differentiate` takes in a pointer to a graph, then steals it and stores inside a Gradient object it returns ("steals" means that the original object holding the graph is emptied while the graph itself is moved to another graph object stored inside Gradient). The moved graph is then mutated according to the differentiate logic.

A cleaner contract here would be to either
1) Create a copy of the original graph in the grtadient
2) Work on the original graph directly

Currently we have some halfway solution, and it would be good to choose one way or the other. That would also help us to get rid of this assert.
```
AT_CHECK(graph.use_count() == 1, ...);
```

Files of interest:
`torch/csrc/jit/autodiff.cpp`

**Comment by Krovatkin** [comment]
tagging @zdevito @suo

**Comment by suo** [comment]
cc @ailzhang this is another example of the autodiff graph shenanigans causing headaches

**Comment by Krovatkin** [comment]
copy-pasting from the original task: 

I don't understand much yet, but I really like 1) since autodiff mutates an original graph (e.g. adds outputs for intermediate values, fuses, optimizes)
If you guys are okay with 1) I could change the current logic

```
Gradient differentiate(std::shared_ptr<Graph>& graph) {
  Gradient grad_desc;
  // Take ownership of the graph
  AT_CHECK(
      graph.use_count() == 1,
      "differentiate will mutate and destroy the graph, so it requires "
      "graph.use_count() == 1, but found %d",
      graph.use_count());
  std::swap(graph, grad_desc.f);
```

to

```cpp
Gradient grad_desc(graph->copy());
```

or 

```cpp
Gradient grad_desc;
grad_desc.f = graph->copy();
```

and ofc clean up extra copies callers are already creating.
we may slow down the case where a caller doesn't actually care whether the original fprop graph mutates or not . 1) would be very appealing if the said case isn't too common.

**Comment by apaszke** [comment]
Ok, so I wrote it that way because of:
1. *Performance considerations.* When we apply AD to a graph, we never need it later, so that's why a copy would be a waste of time
2. *Correctness considerations.* AD is not meant as a graph-to-graph transformation, but is supposed to take a graph, and produce a pair of graphs + some description telling you how to interpret them. Hence leaving the original argument to be in some weird state which is specified by values that seem independent of it seems wrong. Hence, we check that we can destroy the graph, and we make sure that no one accidentally tries to use it by setting the pointer to `nullptr`.

To be honest I think it's ok to keep it like that. I don't have a better idea for a solution here.

**Comment by ZolotukhinM** [comment]
@apaszke, How critical is it for performance? I suspect that copying a graph once would be almost free compared to all other stuff we're doing there, but to me it would lead to a cleaner API. Completely agree with the correctness considerations.

**Comment by Krovatkin** [comment]
I added `needs_discussion`, so we could briefly discuss it at the next sync and finally put this issue to rest.

**Comment by apaszke** [comment]
It's hard to say how important it is, but why should we copy if we don't have to? It's not an API that's meant to be widely used anyway, so what's the deal? There's no reason to generalize this function if we don't foresee any other important use cases.

**Comment by apaszke** [comment]
Also, our IR can get really large (think ~1-2GB) for bigger models, so while it might not be a huge perf hit, it might significantly increase memory pressure.

**Comment by ZolotukhinM** [comment]
Is it 1-2GB graphs, or full models that include weights as well? We're talking only about copying a graph here.

In general it's not a big deal, we can keep it as-is. I just did some spring-cleaning and thought it was a premature optimization that added non-obvious conditions and unnecessary restrictions on the API.

**Comment by Krovatkin** [comment]
> it might significantly increase memory pressure.

Anecdotally speaking, if someone is going to run 1-2GB worth of **IR** and at the same time that much memory also constitutes a **significant** chunk of their RAM, they might want to reconsider running that particular model on that particular machine 😄 We might just save them the world of pain 😹 
Although, copying that much wouldn't be a lot of fun on **any** machine. Optimizing that much which might not be linear as @ZolotukhinM pointed out would be even less fun 😢

**Comment by apaszke** [comment]
I mean the size of the IR alone. It's not a very optimized data structure, and we keep a fair amount of redundancy to speed up lookups.

> Anecdotally speaking, if someone is going to run 1-2GB worth of IR and at the same time that much memory also constitutes a significant chunk of their RAM, they might want to reconsider running that particular model on that particular machine

This reasoning is why my 2012 MacBook cannot handle more than two slack channels being open at the same time, so I respectfully disagree :blush:

**Comment by apaszke** [comment]
> non-obvious conditions and unnecessary restrictions on the API

Well the conditions are relatively tightly guarded, so it's not that easy to make a mistake (even those I agree the semantics are a bit goofy). Still, it's used in one place and there's little win for unnecessary pessimization, so I'd rather keep it as is.

**Comment by Krovatkin** [comment]
We seem to have agreed to leave this as is.
