### ISSUE TITLE
TH_TENSOR_DIM_APPLY3 needs OpenMP support

### ISSUE THREAD

**Issue by danieljl** [pytorch/pytorch#1799]
It should calculate topk for each dimension in parallel.

**Comment by soumith** [comment]
More generally, the issue is:
- Add OpenMP support to [TH_TENSOR_DIM_APPLY3](https://github.com/pytorch/pytorch/blob/96febbb7622db6864542bd0e8735774b715c6a12/torch/lib/TH/THTensorDimApply.h#L4)
- topk pointer: https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THTensorMath.c#L2547-L2566

**Comment by albanD** [comment]
Closing as topk does not use this macro, has been moved to ATen and now uses OpenMP.
