### ISSUE TITLE
Undefined variable from import:log, Undefined variable from import:add

### ISSUE THREAD

**Issue by brimb** [pytorch/pytorch#18002]
## 🐛 Bug

undefined variable from import:log

## To Reproduce
1. install anaconda and eclipse
2. install pytorch using conda install pytorch-cpu torchvision-cpu -c pytorch
3. copy and paste code on eclipse IDE

import torch
import numpy as np
a = torch.Tensor(np.array([1]))
test_torch = torch.log(a) + torch.add(a,a)

Error: Undefined variable from import:log

## Expected behavior

I expected to be able to perform at least all basic mathematical operations like log, add, with torch. Also, torch.FloatTensor is not available.

## Environment
 - PyTorch Version : 1.0.1
 - OS : Windows 10
 - How you installed PyTorch :`conda`
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: none
 - GPU models and configuration: none

## Additional context
basic mathematical operations like torch.log, torch.add, torch.FloatTensor, etc are not available. However, if I use jupyter notebook these work perfectly well.

**Comment by soumith** [comment]
what is `torch` is a local file in your current working directory call `torch.py` or a folder in your current working directory called `torch`, and not the actual `torch` that was installed into site-packages.

**Comment by brimb** [comment]
Thank you for your response Soumith. I have double checked and I do not have a local file named torch.py in my working directory.

**Comment by soumith** [comment]
this looks like a common problem with Python + Eclipse, if the Eclipse IDE is misconfigured.

I've found some stackoverflow threads that are relevant: 
https://stackoverflow.com/questions/2112715/how-do-i-fix-pydev-undefined-variable-from-import-errors
https://stackoverflow.com/questions/13842194/undefined-variable-from-import-when-importing-numpy-in-eclipse-pydev?rq=1
http://notesofaprogrammer.blogspot.com/2017/03/python-script-runs-fine-but-pydev-in.html


Since this has no action from the PyTorch side, I'm closing the issue
