### ISSUE TITLE
Clarify precedence for ternary tensor operators in documentation

### ISSUE THREAD

**Issue by nilsjohanbjorck** [pytorch/pytorch#18049]
## 📚 Documentation

The documentation in https://pytorch.org/docs/stable/torch.html#torch.addcmul seem to suggest that the precedence for the operators are as follows

out = tensor + value * (tensor1 * tensor2)

Is that correct? In general, since floating point operators do not commute, could the precedence for addcmul and addcdiv be clarified? Such information is important for numerical troubleshooting.

**Comment by soumith** [comment]
there are absolutely no guarantees of the ordering of operations in such a case.

The precise reason is because the ordering might differ on particular devices. On CPU, we might have one particular ordering and on GPU another due to maximizing for efficiency.

Currently, on CPU, we are doing:

```
*r__data += value * *src1_data * *src2_data
```

and on GPU, we are doing:

```
   *out = THCNumerics<T>::add(
      *out,
      THCNumerics<T>::mul(
        val,
        THCNumerics<T>::mul(*in1, *in2)
      )
    );
```
