### ISSUE TITLE
cosine_similarity function produces results more than 1.0

### ISSUE THREAD

**Issue by serbulent** [pytorch/pytorch#18057]
## 🐛 Bug

Cosine similarity function should not calculate a result over 1.0 but it does if vector size is over 84 and more. 

## To Reproduce

```
def cos_sim(v1,v2):
    return F.cosine_similarity(v1.unsqueeze(0),v2.unsqueeze(0))

vv1 = tensor(list([float(i) for i in range(84)])).unsqueeze(0)
vv2 = tensor(list([float(i) for i in range(84)])).unsqueeze(0)

F.cosine_similarity(vv1,vv2).item()

1.0000001192092896

```

## Environment

Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro RTX 5000
Nvidia driver version: 410.93
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.2.post2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2            py37h90e4bf4_5  
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0  
[conda] mkl_random                1.0.1            py37h4414c95_1  
[conda] pytorch                   1.0.1           py3.7_cuda10.0.130_cudnn7.4.2_2    pytorch
[conda] torchvision               0.2.2.post2              pypi_0    pypi

**Comment by ezyang** [comment]
Yeah, this looks like a real problem. The root cause is probably floating point errors, but we should probably clamp to prevent it from becoming >1.0

The implementation is sum, norm, division, clamp. But it only clamps on the division, so you don't divide by zero. So we should clamp at the end, probably.

@ailzhang, do you want file a bootcamp task to add the missing clamp here?

**Comment by colesbury** [comment]
Probably better to re-order the computations to improve numerical precision. Might want to look at SciPy:

https://github.com/scipy/scipy/blob/453932337f4a67170e4e7fda3f808b273a787a41/scipy/spatial/distance.py#L717-L721

I think the issue is that we're doing:

```
x / (sqrt(x) * sqrt(x))  # bad
```

vs.

```
x / sqrt(x * x)  # good
```

I don't know enough about floating point arithmetic to argue why the second is more accurate, but it seems to be. (You can look at the min/max over a large random tensor)

**Comment by CaypoH** [comment]
Looks like this issue in not fixed. I am using google colab with pytorch version 1.9.0+cu102. Full precision tensors. And still getting an error from BCELoss after torch.nn.functional.cosine_similarity

**Comment by ezyang** [comment]
@CaypoH could you submit a new issue with an updated repro? Thanks!
