### ISSUE TITLE
Builds should include the git commit hash in torch.version.git_version

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#18293]
## 🚀 Feature
Builds, especially nightlies, should include the PyTorch commit hash in torch.version.git_version.

## Motivation
It can be difficult to figure out which commits are in a nightly build. We encode the git commit hash in `torch.__version__` for local builds, but nightlies use the date. The `torch.version` package already includes some useful version information like the CUDA version. We should add the git commit hash as well.

## Alternatives
Bisect. Build. Suffer. Repeat.

## Additional context
See, for example, https://www.tensorflow.org/api_docs/python/tf/version

**Comment by ezyang** [comment]
cc @kostmo

**Comment by pjh5** [comment]
The libtorch binaries (c++ only) store the hash in a file called 'build-hash' since https://github.com/pytorch/builder/pull/275 . Is this needed for the Python binaries too? We did not include this file in the Python binaries because we did not know where to install the file a Python installation (the c++ binaries are just zips of files and must be installed manually).
