### ISSUE TITLE
Different behavior of sum() in-place on CPU vs GPU

### ISSUE THREAD

**Issue by melange396** [pytorch/pytorch#1930]
```
x = torch.randperm(16).resize_(4,4) # create tensor
y = x.cuda() # copy to GPU
# perform same operation on both:
x.sum(dim=0,out=x)
y.sum(dim=0,out=y)
print(y) # see expected behavior
print(x) # see zeros instead
```

**Comment by gchanan** [comment]
passing the input as the output for a function that does resizes should be an error; these functions usually resize the outputs at the start of the call and it's likely they don't even do the calculations correctly since that also modifies the input.

Or maybe we just check that output tensors aren't resized?  (this is what numpy does).  I believe @zdevito had a use case where he wanted to pass in a big buffer, or let it grow dynamically, and just wanted to use that for the output without worrying about the sizes himself.  Do I have that right, Zach?

**Comment by zdevito** [comment]
The cases I had in mind was when you had done some optimization pass and
come up with pre-allocated Tensor buffers rather than relying on a caching
allocator. I know that two Tensors are not live at the same time, and want
to use the same buffer for two different ops, but I don't want to have to
manage their sizes manually because the Op should know what size the output
would need to be. In this case, I would make two tensors and back them with
the same storage, allowing the op itself to resize each individual tensor
to the right size for that op.

**Comment by cpuhrsch** [comment]
With recent changes in how reductions are implemented this issue might not be current anymore @melange396

**Comment by gchanan** [comment]
covered by https://github.com/pytorch/pytorch/issues/17935.
