### ISSUE TITLE
[build][omp] Conflict when MKL dynamically links OpenMP

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#19764]
## 🐛 Bug

`MKL` may dynamically link  `OpenMP`. This causes conflict if we link another `OpenMP`.
So in `FindOpemMP.cmake`, in stead of trying out `OpenMP_libomp_LIBRARY` when it exists, we should just try link against all `MKL` libs at 
https://github.com/pytorch/pytorch/blob/556c8a300b5b062f3429dfac46f6def372bd22fc/cmake/Modules/FindOpenMP.cmake#L198-L267.

**Comment by fmassa** [comment]
cc @ilia-cher as this is related to the work you are doing for unifying threadpools in PyTorch.

**Comment by ilia-cher** [comment]
When you say "`MKL` may dynamically link `OpenMP`", do you mean `libmklrt` and the case when you choose threading layer with`mkl_set_threading_layer`, or something else?

**Comment by ilia-cher** [comment]
Oh, and also when do we statically link OpenMP? I think it is recommended to never do this?

**Comment by ilia-cher** [comment]
In what cases OpenMP is linked statically? I think it's recommended to never do this.

**Comment by SsnL** [comment]
@ilia-cher Ah I wrote that description wrong. I think the issue arises when we dynamically link another openmp that is not the same one as what mkl links.

**Comment by ilia-cher** [comment]
Yes, it is important to use the same openmp runtime library. At the moment, afaik we specifically link MKL with compiler's runtime, so, when it comes to building PyTorch, both MKL and cases of explicit usage of OpenMP (through pragma's) should use the same runtime library.

**Comment by SsnL** [comment]
@ilia-cher Yes, we do specifically link MKL. However, in the above code section I linked (which I wrote), we also tries to link an omp if the there isn't a MKL lib with name `*omp`. We can't just not run `FindOpenMP` because it is not guaranteed that we link with MKL. So the section should be changed to trying linking against all mkl libs.

**Comment by ilia-cher** [comment]
I see, and by 'linking against all mkl libs' - you mean cases when there isn't an MKL lib with `omp` in the name? Is it `libmkl_rt` or smth else? And feel free to send a PR, we'll gladly review)

**Comment by SsnL** [comment]
Yep, exactly. I can't remember what was the mkl lib that tried to link omp (probably the `_threads` one?).

**Comment by ilia-cher** [comment]
I think I'm still not sure I understand.
So, in the `FindOpenMP.cmake` fragment mentioned above, we call `FindMKL.cmake` and then if `MKL_FOUND` and `MKL_OPENMP_LIBRARY` is not empty, then we use `MKL_OPENMP_LIBRARY` as an OpenMP library, makes sense. Otherwise we try to find OpenMP library with `find_library(OpenMP_libomp_LIBRARY NAMES omp gomp iomp5 ... )`

What are the cases when we have MKL but don't have `MKL_OPENMP_LIBRARY`.
Our `FindMKL.cmake` seems to be pretty simple and doesn't support TBB or `libmkl_rt`, but let's assume we update `FindMKL.cmake` to support all possible cases.
Then `MKL_OPENMP_LIBRARY` empty would mean - either we don't use OpenMP at all (e.g. we use sequential version of MKL, or TBB version). Then `FindOpenMP.cmake` should do its job and find OpenMP library to use.
Or this is `libmkl_rt` scenario, but then.. we don't know exactly what OpenMP library will be used (?)
Then it's not clear what to do in FindOpenMP.cmake.
According to https://software.intel.com/en-us/mkl-linux-developer-guide-using-the-single-dynamic-library , it seems that the default option for `libmkl_rt` is Intel threading (i.e. Intel OpenMP library), so I assume it would load it on startup and I assume it might load other .so libraries dynamically in runtime when you call `mkl_set_threading_layer` (need to double check).

**Comment by SsnL** [comment]
> Then MKL_OPENMP_LIBRARY empty would mean - either we don't use OpenMP at all (e.g. we use sequential version of MKL, or TBB version).

In the case where I saw this, the mkl definitely still uses omp. It's a long time ago so I don't remember what if actually found. But I can try to reproduce.

**Comment by ilia-cher** [comment]
Sounds good, thanks, that would be interesting to see what configuration led to this.

**Comment by SsnL** [comment]
haven't been able to reproduce this so I'll close!

**Comment by cjolivier01** [comment]
This doesn't happen when I use anaconda python3, but does when using system ubuntu python3 (default). presumably, anaconda links to older mkl which doesn;t do the dlopn on libomp5
