### ISSUE TITLE
Distributed Training throws NCCL reduce error if layer inside module is not used in forward

### ISSUE THREAD

**Issue by tsauri** [pytorch/pytorch#19791]
## To Reproduce
Say if I have this
```python
class MyLayer(nn.Module):
  def __init__(self):
    self.a = nn.Linear(784,200)
    self.b = nn.Linear(784,20)
  def forward(self,x):
    return self.a(x)
```
If I make train this model in distributed training setup, I get error similar to this.
(The solution is to set `self.b.requires_grad=False`, but I didn't find in the docs)
```
   self._queue_reduction(bucket_idx)
lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 495, in _queue_reduction
    self.device_ids)
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupNCCL object at 0x2aabf228eea0>, [[tensor([[[ 6.8699e-04,  7.5125e-04,  7.8579e-04,  ..., -8.7296e-05,
          -4.2330e-05, -6.5678e-05]],

        [[ 5.2465e-04,  4.9833e-04,  4.8579e-04,  ...,  3.5678e-06,
           2.7221e-05,  2.8122e-06]],

        [[ 6.5310e-04,  6.8523e-04,  8.8740e-04,  ...,  9.3483e-05,
          -2.3784e-05,  1.0097e-04]],


```

## Expected behavior

Pytorch shouldn't throw error if a module inside a module is left unused in forward pass.
At least give error message that some module is left unused, give instruction to user to self.requires_grad=False
## Environment
Pytorch 1.0
```

**Comment by fmassa** [comment]
I believe this has been fixed in the nightly version of PyTorch. Can you try updating PyTorch with the nightly build and see if your error is fixed?

**Comment by pietern** [comment]
This is indeed fixed in the latest nightlies. You'll get a different error message that encourages you to pass `find_unused_parameters=True` to the `DistributedDataParallel` constructor. This will find any unused parameters and deal with reducing them across processes. If these parameters are defined in error and *never* used, you should either set `requires_grad` to `False` like you already do, or just remove them.

If you still have an issue running the snippet you mention please feel free to open a new issue.
