### ISSUE TITLE
Using DistributedDataParallel through NCCL throws RuntimeError

### ISSUE THREAD

**Issue by mfuntowicz** [pytorch/pytorch#19840]
Hello :),

I have a setup with DDP and a training using BPTT over a sequence of images, but trying to call backward over the critic (Adversarial setup, with detached Generator output) it leads to the following:  

```python
self.reducer.prepare_for_backward(list(_find_tensors(output)))self.reducer.prepare_for_backward(list(_find_tensors(output)))

RuntimeErrorRuntimeError: : Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /home/mfuntowi/Workspace/pytorch/torch/csrc/distributed/c10d/reducer.cpp:401)
```

Python 3.7, CUDA 10.0, CuDNN 7.5.0, PyTorch master (3803d1c901b6e2632682b02589b2d5aa888b0a88)

Distributed Data Parallel, Multi-Process Single-GPU over 4xV100

I was working fine with the same code before updating this afternoon.

**Comment by mfuntowicz** [comment]
It's working fine over c182824f692a8325f9f57f557418e589a05a148d

**Comment by mrshenli** [comment]
Does your model have unused parameters when running backward? Before updating, which version of PyTorch are you using?

**Comment by mfuntowicz** [comment]
I shouldn't be using any unused parameters, but I'm training two networks in an adversarial setup, defined like this:

```python
       critic = DistributedDataParallel(
            critic, find_unused_parameters=True,
            device_ids=[args.device], output_device=args.device
        )

        generator = DistributedDataParallel(
            generator, find_unused_parameters=True,
            device_ids=[args.device], output_device=args.device
        )
...
        with freeze_parameters(critic.parameters()):
           d_y_fake_hat = critic(generator(x))
```

```python
@contextmanager
def freeze_parameters(parameters):
    _parameters = []
    for p in parameters:
        p.requires_grad = False
        _parameters += [p]

    yield

    for p in _parameters:
        p.requires_grad = True
```

So during the generator backward, it's using the output of the critic which is frozen w.r.t its parameters.

**Comment by pietern** [comment]
I think #19901 addresses this. The underlying problem was interaction between `find_unused_parameters` and outputs that don't accumulate into the module's parameters. While verbose, the error message incorrectly instructed you to set `find_unused_parameters=True`. If you update to the latest nightly or master and try again, while removing the `find_unused_parameters` argument, it should work as expected.

**Comment by mfuntowicz** [comment]
Sorry for the time to get back on this issue. 

I'll have some extra time to have a look at the solution you proposed @pietern  and will update my comment just after that.

**Comment by mfuntowicz** [comment]
It's working fine with your fix, thanks @pietern !

**Comment by JialeTao** [comment]
> I think #19901 addresses this. The underlying problem was interaction between `find_unused_parameters` and outputs that don't accumulate into the module's parameters. While verbose, the error message incorrectly instructed you to set `find_unused_parameters=True`. If you update to the latest nightly or master and try again, while removing the `find_unused_parameters` argument, it should work as expected.

Hi, I have the same problem and I just read the #19901, but I didn't found the resolution code. It just show the changed source code of the reducer method. How can we modify our personal code to solve this or to use "require_finalize_" parameter?

**Comment by JialeTao** [comment]
> It's working fine with your fix, thanks @pietern !

Hi, could you share that how do you fix this? Did you reinstall the latest pytorch version? I install the pytorch1.5 but still face the issue.

**Comment by Ze-Yang** [comment]
@pietern I met the same problem. I am using pytorch 1.4.0, which I check already includes the fix #19901 you mentioned. By the way, I also tried to set the flag `find_unused_parameters` to True and the error disappeared. However, I don't know where the real reason lies. I don't think this is a good choice to handle this problem, as you emphasize at both here and #22436.

I use the DistributedDataParallel and have confirmed that anything not used in the loss computation is not returned as the output of forward function (#22436). Is there any other possible reason that may lead to this error? Any help is appreciated. Thanks a lot.

**Comment by Ze-Yang** [comment]
I have built a [dummy model](https://github.com/Ze-Yang/Bug_Shooting) as below to reproduce the problem `RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one`. Hope for your kind favor. Thanks.

```python
import os
import argparse
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.parallel import DistributedDataParallel
import torch.optim as optim
import torch.multiprocessing as mp
# import comm


parser = argparse.ArgumentParser(description='Distributed Data Parallel')
parser.add_argument('--world-size', type=int, default=2,
                    help='Number of GPU(s).')


class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.stem = nn.Linear(10, 10)
        self.branch1 = nn.Sequential(
            nn.Linear(10, 10),
            nn.ReLU(),
            nn.Linear(10, 10))
        self.branch2 = nn.Sequential(
            nn.Linear(10, 10),
            nn.ReLU(),
            nn.Linear(10, 10))

    def forward(self, x):
        x1 = F.relu(self.stem(x))  # [20, 10]
        branch1 = self.branch1(x1[:10])
        branch2 = self.branch2(x1[10:])
        branch1_list = [torch.empty_like(branch1, device='cuda') for _ in range(dist.get_world_size())]
        dist.all_gather(branch1_list, branch1)
        # branch1_list = comm.all_gather(branch1)
        pred_weight = torch.cat(branch1_list, dim=0).mean(0, keepdim=True).expand(5, -1)  # [5, 10]
        out = branch2.mm(pred_weight.t())
        return out


def demo_basic(rank, world_size):
    print(f"Running basic DDP example on rank {rank}.")
    setup(rank, world_size)

    # create model and move it to GPU with id rank
    model = ToyModel().to('cuda')
    ddp_model = DistributedDataParallel(model, device_ids=[dist.get_rank()], broadcast_buffers=False)
    ddp_model.train()

    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    for _ in range(5):
        optimizer.zero_grad()
        inputs = torch.randn((20, 10), device='cuda')
        outputs = ddp_model(inputs)
        labels = torch.randn_like(outputs).to('cuda')
        loss_fn(outputs, labels).backward()
        optimizer.step()

    cleanup()


def run_demo(demo_fn, world_size):
    mp.spawn(demo_fn,
             args=(world_size,),
             nprocs=world_size,
             join=True)


def setup(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # initialize the process group
    dist.init_process_group("NCCL", rank=rank, world_size=world_size)
    torch.cuda.set_device(rank)


def cleanup():
    dist.destroy_process_group()


if __name__ == "__main__":
    args = parser.parse_args()
    run_demo(demo_basic, args.world_size)
```

**Comment by martinrebane** [comment]
@Ze-Yang Pytorch DDP has a serious flaw which is not documented: the computational graphs for all the nodes must be the same or you will get this error or training sometimes just hangs at 100% CPU (even when training on GPU) on backward() call. You can debug your problem by visualising the computational graphs on each node and see if they are the same. If not, make them (or fix the pytorch source).

An example: if your loss function contains an IF condition with additional computation, and one node goes into IF and other does not, this will be enough to crash DDP training. Instead of IF try to solve the same thing some other way and/or trick pytorch to make the graph look the same on each node. Of course, there might be other causes for different autograd graph too.

My case was this. Buggy code (crashed):
```
if positive_class.shape[0] > 0:
   loss += torch.somefunction(positive_class)
```
Fix:
```
# concat with tensor that has no effect on loss calculation, but positive_class always has content
positive_class = torch.cat(positive_class, dummy)
loss += torch.somefunction(positive_class)
```

I don't know if your problem is similar, I do not see any obvious divergence of graphs here, but it's worth to look at graphs if you are stuck :)

**Comment by Ze-Yang** [comment]
Thanks for your advice. I seek help from Pytorch repo and find that the real cause is that the `dist.all_gather`  is not an autograd function, so all operations prior to all_gather is not linked to the out tensor in the autograd graph  (refer to pytorch/pytorch#40690). I need to manually implement the backward function at present, but I think it will be added into the official release soon (pytorch/pytorch#40762).

Indeed the point you mention is important, and I will pay more attention to the computational graph while implementing DDP codes. Again thanks a lot for you share.
