### ISSUE TITLE
torch.arange always generate constant result in tracing

### ISSUE THREAD

**Issue by houseroad** [pytorch/pytorch#20075]
We hope to get dynamic result, however, in the traced onnx graph, we alway get constant directly.

For a reproduction, please https://github.com/pytorch/pytorch/pull/20072

**Comment by lara-hdr** [comment]
This gets fixed by setting traceable=true in arange's arg parser as explained in my comment in https://github.com/pytorch/pytorch/issues/12580. 
I am trying to figure out if there is a reason traceable is set to false, and if there are any unwanted consequences of switching it to true.
@houseroad, do you know who can help answering this?
Thanks!

**Comment by lara-hdr** [comment]
I was adding a test in test_jit.py and noticed a test test_trace_checker_arange_as_constant was already added in https://github.com/pytorch/pytorch/pull/10841 to ensure that arrange was traced as a constant.
@jamesr66a why is this needed? can we allow arrange to have variable args like mentioned above?

**Comment by houseroad** [comment]
Fixed
