### ISSUE TITLE
[FR] make IncompatibleKeys print nicer when there is no error

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#20128]
Now it prints `IncompatibleKeys(missing_keys=[], unexpected_keys=[])` upon a successful `load_state_dict`, and could be quite confusing. This can happen a lot, e.g., in jupyter notebooks.

We can just subclass and overwrite `__repr__`.

**Comment by designnner** [comment]
how to solve this error ? IncompatibleKeys(missing_keys=[], unexpected_keys=[])

**Comment by SsnL** [comment]
@designnner This is not an error. It's just the `repr` that isn't ideal. Feel free to ignore.

**Comment by iArunava** [comment]
Hi! I am looking into this.
And I would like to know whose `__repr__` are you suggesting to change?

Also, I was thinking of replacing the following
https://github.com/pytorch/pytorch/blob/163f0e182c7e092d6b61600e3a5e20347abab848/torch/nn/modules/module.py#L778
with
```
return _IncompatibleKeys(missing_keys, unexpected_keys) if len(missing_keys) or len(unexpected_keys) else 'state_dict loaded successfully!'
```
or some other message, or nothing at all.
Let me know.

**Comment by piyush-kgp** [comment]
Hey, this issue seems to have been dealt with in a later version: 
In master `_IncompatibleKeys `  prints `<All keys matched successfully>` when all keys match:
https://github.com/pytorch/pytorch/blob/e870a9a87042805cd52973e36534357f428a0748/torch/nn/modules/module.py#L9-L15
whereas
v1.1 doesnt do any such thing. It always prints a message in the format `IncompatibleKeys(missing_keys=[..], unexpected_keys=[..])`
https://github.com/pytorch/pytorch/blob/0b868b19063645afed59d6d49aff1e43d1665b88/torch/nn/modules/module.py#L11-L12

But since (I think) many people are still using v1.1, maybe we should make the same changes in earlier versions too. This wasted a lot of time for me today.
