### ISSUE TITLE
Official instructions for how to build libtorch don't have same structure as prebuilt binaries

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#20271]
On Slack, Geoffrey Yu asked:

> Are there instructions for building libtorch from source? I feel like I'm missing something since I've tried building with `tools/build_libtorch.py`. However the build output doesn't seem to have the same structure as the prebuilt libtorch that you can download on pytorch.org

@pjh5 responded: "If you're curious, here's exactly what builds the libtorches https://github.com/pytorch/builder/blob/master/manywheel/build_common.sh#L120 . It's mostly tools/build_libtorch.py but also copies some header files from a wheel file"

This is not mentioned at all in the "how to build libtorch" documentation: https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst Normally we give build instructions in README but there are no libtorch build instructions in the README. Additionally, the C++ API docs https://pytorch.org/cppdocs/ don't explain how to build from source.

Some more users being confused about the matter:
* https://discuss.pytorch.org/t/building-libtorch-c-distribution-from-source/27519/2
* https://github.com/pytorch/pytorch/issues/20156

**Comment by pjh5** [comment]
I was not aware of https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst , but it is more recent than the binary jobs that build libtorch. I have never tried building libtorch myself, but if these instructions work then we should really switch the binaries to these; the binary way is a little hacky right now.

**Comment by Chillee** [comment]
The instructions do not work for me as is. In particular, I run into this issue: https://github.com/pytorch/pytorch/issues/17181

~~I'm new to this codebase, but doesn't `python setup.py develop` already build `libtorch.dylib` in `build/lib/`? At the very least, I've verified that after doing the standard pytorch build, I can use the custom operators stuff.~~

Looking at the slack, it seems like Thomas Vman provided instructions that work for me.

> you make a directory (e.g. `build_libtorch`) in your checkout root dir, then you call `../tools/build_libtorch.py` from that)
> or you just run setup.py build and then copy stuff from build/lib.* (for the lazy).

I can write some PR's to update the documentation to use those instructions.

**Comment by pjh5** [comment]
So it looks like we've been messy in how we're building libtorch. I propose we fix https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst to follow Thomas's instructions, with the extra information that
- Make an extra directory and call build_libtorch.py within that to avoid polluting the source directories, and since our cmake might not support in-place builds in all circumstances based on that issue @Chillee linked
- Running setup.py will also build libtorch, but also builds the python bits too. If given the 'install' or 'develop' commands then this will also copy a bunch of files into the active python installation. Also, setup.py sets a lot of default flags which are definitely different from the defaults in build_libtorch.py . 

@ezyang , @kostmo , and @soumith , does this seem good?

**Comment by soumith** [comment]
@pjh5 this sounds good to me.

**Comment by ezyang** [comment]
Yes please!

Excerpts from Soumith Chintala's message of 2019-05-28 16:47:16 -0700:
> @pjh5 this sounds good to me.
>
