### ISSUE TITLE
assertEqual in tests ignores dtype when comparing tensors.

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#20376]
In unit tests, a check like this: 
`self.assertEqual(torch.tensor([1], dtype=torch.int), torch.tensor([1], dtype=torch.double))` should fail but it doesnt.

cc @ezyang @gchanan @zou3519

**Comment by jeffreyksmithjr** [comment]
I could see us desiring the current behavior or the proposed behavior. Labeling needs discussion.

**Comment by ezyang** [comment]
@ailzhang suggests maybe we add a assertEqualAndDtype.  @izdeby says that he had the assumption that it had the exact same dtype checked.

I think this suggested change is fine, but we should check if there are other asserts (e.g., assertAllClose shouldn't check the dtype, since things are expected to be a little different). It will be good to find out exactly what breaks if we make it more strict.

**Comment by ezyang** [comment]
I'm raising the priority of this as the lack of dtype check is why https://github.com/pytorch/pytorch/issues/33651 was not caught in testing.

**Comment by ezyang** [comment]
Note that we've always done conversions for a really long time; it's as old as 88b42324e73a603fa585583555e2a7a270ac1e89

**Comment by VitalyFedyunin** [comment]
WIP for test_torch
cc @VitalyFedyunin create issues one per test_* files.

**Comment by mruberry** [comment]
This was fixed by updating assertEqual to default to `exact_dtype=True`. See 

https://github.com/pytorch/pytorch/blob/8aad66a7bd35782a0e662d133276830204499656/torch/testing/_internal/common_utils.py#L1005
