### ISSUE TITLE
SyncBN doesn't support fp16 inputs with fp32 parameters

### ISSUE THREAD

**Issue by Randl** [pytorch/pytorch#20634]
## To Reproduce

1. Convert network to 16 bits while keeping SyncBN in 32 bits
2. Get `RuntimeError: expected scalar type Half but found Float` error

## Expected behavior
BatchNorm works with different types of input and parameters.

## Environment
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 418.56
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

cc @csarofeen @ptrblck

**Comment by mruberry** [comment]
I think this is by design, and you have to manually add a conversion from fp16 to fp32 before the batchnorm and then from fp32 to fp16 afterwards. 

I also encourage you to take a look at NVIDIA's Automatic Mixed Precision (AMP) tool, which can automatically convert your network to a mix of fp16 and fp32 operators. AMP is part of the APEX Github here: https://github.com/NVIDIA/apex.
