### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by PranovD** [pytorch/pytorch#20706]
## 🚀 Feature

Can you please add support for building from source in Visual Studio 2019
## Motivation
It would allow developers who do not have the previous Visual Studio versions to work with and contribute to this repository.

## Pitch

Add support for building in Visual Studio 2019 to increase potential contributors with a relatively easy fix.  Most of what is needed would be updating scripts/build_windows.bat file to include a code generate for Visual Studio 2019 along with having CMake 3.14+ installed.  This has been done in ML.net and was a relatively simple fix. 
[ML.net Solution](https://github.com/PranovD/machinelearning/commit/b0fdb444a4acaf402c706dcbeaf157eb2668ccd3)

[Warning: CMake 3.14 does not support placing Win32 or other architecture flags directly after named Generator](https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2016%202019.html)

**Comment by peterjc123** [comment]
What error did you get when you build with VS 2019? BTW, you'll need CMake >=3.14.3.

**Comment by peterjc123** [comment]
Sorry, I misunderstood it. The fix is on the way.

**Comment by peterjc123** [comment]
The fix is in https://github.com/pytorch/pytorch/pull/20752. However, we won't change the default generator this time. 
Should we add a flag for the user to choose between VS 2017/2019, or just do it for the user? If the latter one is preferred, then we have two options: 
1. Use `_overlay_vc_env` to get the latest env, but it is not available on all python versions.
2. Use `vswhere`, but that will introduce some specific code for finding VS2017/2019.
3. Let the user choose by using the environmental variable `CMAKE_GENERATOR`.
What do you think, @zdevito?

**Comment by soumith** [comment]
i think we should start with (3)

**Comment by peterjc123** [comment]
Closed as it's included in #21026.
