### ISSUE TITLE
libcurand.so.8.0: cannot open shared object file

### ISSUE THREAD

**Issue by HelloSeeing** [pytorch/pytorch#20750]
## 🐛 Bug
import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: libcurand.so.8.0: cannot open shared object file: No such file or directory

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): sudo pip3.5 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp35-cp35m-linux_x86_64.whl
 - Python version: 3.5
 - CUDA/cuDNN version: cuda(10.0),cuDNN(7.5.1)

**Comment by soumith** [comment]
you have an older pytorch install somehow on your machine.

**Comment by ezyang** [comment]
Yeah, try reinstalling PyTorch; if that doesn't work, try making a fresh conda environment and installing.

**Comment by HelloSeeing** [comment]
@soumith @ezyang Thanks, it works!

**Comment by wangg12** [comment]
I have the same issue, I have installed cudatoolkit 10.0 by conda and cuda 10.0 on system. I deleted the old cuda-8.0 folder. The old pytorch has been uninstalled from both conda and pip. Then I tried to install pytorch 1.1 by both conda and pip with cuda 10, but both got `libcurand.so.8.0: cannot open shared object file`.
Then I installed the nightly version, the problem was gone. I still can not figure it out.
