### ISSUE TITLE
NervanaSystems/nervanagpu Repository not found for 0.4.0

### ISSUE THREAD

**Issue by eric4337** [pytorch/pytorch#20845]
## ❓ Questions and Help
NervanaSystems/nervanagpu Repository not found for 0.4.0
is there any way to workaround this? thanks

**Comment by mrshenli** [comment]
Would I be correct if I assume you are experiencing a build failure due to the `nervanagpu` submodule? The repo https://github.com/NervanaSystems/nervanagpu.git is no longer available. You can proceed with the build by removing it from [.gitmodules](https://github.com/pytorch/pytorch/blob/v0.4.0/.gitmodules#L29-L31). Then do:

```
git clean -xdf
git submodule deinit -f .
git submodule sync
git submodule update --init --recursive
```

Any reason for not using more recent PyTorch versions (e.g., 1.1)?

I am closing this issue, but feel free to reopen it if you still see build failures.

**Comment by reckdk** [comment]
I remove `nervanagpu` by doing this:
```bash
git submodule deinit third_party/nervanagpu
git rm --cached third_party/nervanagpu
```

**Comment by alaeddineHarizi** [comment]
> I remove `nervanagpu` by doing this:
> 
> ```shell
> git submodule deinit third_party/nervanagpu
> git rm --cached third_party/nervanagpu
> ```

thank you, worked for me
