### ISSUE TITLE
Improve Windows build from source instructions

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#21026]
Right now, the Windows build from source instructions can be improved in a few ways.

- Specify whether VS2017 is the only supported one, or if VS2019 is also supported.
  - The language says: "At least Visual Studio 2017 Update 3 ", but @aijayadams reported that the builds dont actually work with VS2019. Maybe we say "Visual Studio 2017 (atleast Update 3)?"
- `FORCE_PY27_BUILD` line doesn't make it clear that it's only needed for Python 2.7 builds, if you want. It makes it confusing to the user who might assume that only Python 2.7 is supported

**Comment by soumith** [comment]
@peterjc123 can you make these improvements

**Comment by peterjc123** [comment]
@soumith

> Specify whether VS2017 is the only supported one, or if VS2019 is also supported.
> The language says: "At least Visual Studio 2017 Update 3 ", but @aijayadams reported that the builds dont actually work with VS2019. Maybe we say "Visual Studio 2017 (atleast Update 3)?"

Visual Studio 2019 is also supported but it will not be auto-selected if `ninja` is not used. Because we hardcode the generator in cmake to `Visual Studio 15 2017`. In https://github.com/pytorch/pytorch/issues/20706#issuecomment-494329983, I have some suggestion for fixing this. But nobody responds to it. I am strongly against changing the default value to VS 2019 because for now, for CUDA builds, only CUDA 10.1 is supported. BTW, the `BUILD_SHARED_LIBS=OFF` builds are broken for 2019 too, which is discussed here: https://github.com/pytorch/pytorch/issues/20686#issuecomment-495501084. 

> FORCE_PY27_BUILD line doesn't make it clear that it's only needed for Python 2.7 builds, if you want. It makes it confusing to the user who might assume that only Python 2.7 is supported

Could you please give me a good alternative?

**Comment by soumith** [comment]
responded in #20706 and #20686  , sorry for the delay. I think we should allow env variable config with cmake, and document that in README.


> Could you please give me a good alternative?

```
REM Only add the next two lines if you need Python 2.7. Otherwise Python-3 will build.
set MSSdk=1
set FORCE_PY27_BUILD=1
```
