### ISSUE TITLE
JIT Array Attribute is broken

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#21040]
## 🐛 Bug

Cannot append

## To Reproduce
```
import torch
from typing import List

class AttributeAccumulation(torch.jit.ScriptModule):
    def __init__(self):
        self.array = torch.jit.Attribute([], List[int])

    def forward(self):
        self.array.append(0)
        print self.array
        return self.array

print AttributeAccumulation().forward()
```

```
[]
[]
```

## Version

'1.1.0a0+72e171d'

**Comment by driazati** [comment]
This is happening since `forward` isn't a `@script_method` and it's grabbing the empty list attribute from the C++ `ScriptModule`, converting it to a Python list, appending to that, then throwing it away.

There's no easy fix for this since it's all happening in the Python interpreter, but the attribute changes in #20939 should fix this.

**Comment by sidazhang** [comment]
So I just need to add a script_method annotation and that’s it?

**Comment by driazati** [comment]
Right, that should fix it
