### ISSUE TITLE
C++ runs slower than python version

### ISSUE THREAD

**Issue by songziqin** [pytorch/pytorch#21246]
I have a requestion, the C++ code belows:
auto start = std::chrono::system_clock::now();
//sparse_segment_forward(input_batch, values, indices);
auto a = torch::randn({10000, 100});
auto b = torch::randn({1000,10000});
auto ret = b.mm(a);
auto end = std::chrono::system_clock::now();
std::chrono::duration elapsed_seconds = end - start;
std::cout << "sparse embedding elapsed time: " << elapsed_seconds.count() << “s\n”;
it shows the mm operation cost 0.5s.
but my python version as follows:
x = torch.randn(10000,100,device=device, dtype=dtype)
y = torch.randn(1000, 10000, device=device, dtype=dtype)
import torch
device = torch.device(“cpu”)
dtype = torch.float
import time
start = time.time()
x = y.mm(x)
end = time.time()
print end -start
python program costs 0.02s。 Both run the same machine,so I want to know if I have not use the cpu
openblas,and I want to ask how to use the openblas in C++.thanks.

**Comment by n-west** [comment]
I'm not with the pytorch org at all, but I think there's a few problems that might help this get addressed if there is a problem:

Some pointers from a friendly neighbor and general fan of torch:

1) Put code in code blocks so it's easier to read, you get syntax highlighting, and it's easier to copy paste
2) The C++ code would be a little bit nicer to reproduce if it was a fully-compilable short program with a main and the proper includes. I think it might also be invalid because you need to do a `std::chrono::duration_cast` on the difference between end and start.
3) The python code seems out of order. x and y use names like `torch`, `device`, and `dtype` before they are defined/imported.
4) They created several issue templates for the repo. Using them and filling them out provides a lot of context that can be useful in reports like this

That said, I don't think the c++ version is any slower than the python version. Your example is timing the creation of random tensors in c++ as well as the multiply; however, the python version only times the matrix multiply so it's not a fair comparison. I modified the c++ version so that only the matrix multiply is timed and got similar timing as the python version on my machine. The variance is rather large though because we're only timing one example. Ideally you want to measure a lot of iterations so you get a smaller measurement variance.

I modified both examples to repeat the matrix multiply 10000 times and on my machine measure python version 69019ms at and the c++ version at 63768ms.

Here's my modified programs:
c++ version:
```c++
#include <iostream>
#include <chrono>
#include <torch/torch.h>

int main() {

        //sparse_segment_forward(input_batch, values, indices);
        auto a = torch::randn({10000, 100});
        auto b = torch::randn({1000,10000});
        auto start = std::chrono::system_clock::now();
        for (size_t count=0; count < 10000; ++count) {
                auto ret = b.mm(a);
        }
        auto end = std::chrono::system_clock::now();
        auto elapsed_seconds = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
        std::cout << "sparse embedding elapsed time: " << elapsed_seconds.count() << "ms" << std::endl;

        return 0;
}
```

python version:
```python
import torch
import time
device = torch.device("cpu")
dtype = torch.float
x = torch.randn(10000,100,device=device, dtype=dtype)
y = torch.randn(1000, 10000, device=device, dtype=dtype)
start = time.time()
for _ in range(10000):
    z = y.mm(x)
end = time.time()
print end -start
```

**Comment by LJXLJXLJX** [comment]
@n-west 
In fact, the official built libtorch is normal, but my libtorch built from source is REALLY slow.
Test on the same code, the official libtorch use 50ms , but the one I build from source use 1200ms.
So wierd.
