### ISSUE TITLE
torch::nn::Linear can not access weight

### ISSUE THREAD

**Issue by songziqin** [pytorch/pytorch#21333]
## ❓ Questions and Help

I have a question, I want to set and get the Tensor of torch::nn::Linear  object, and I read the document https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_linear_impl.html#classtorch_1_1nn_1_1_linear_impl, it says the Tensor weight is the public member.but when i compiler my code ,the compiler gives me an error as follows:
 error: 'class torch::nn::Linear' has no member named 'weight'. so i want to know is there a method i can get/set the Tensor of  torch::nn::Linear weight.

**Comment by tada123** [comment]
I had the exact same issue, and fixed by using `->` to access the variable.
`torch::nn::Linear` is actually a `shared_ptr` holding `torch::nn::LinearImpl` class. When you use `somelinearlayer.weight`, it actually means, that you want to access `shared_ptr.weight`, which does not exist. 
`somelinearlayer->weight` will dereference the `shared_ptr` and accesses the actual `torch::nn::LinearImpl::weight`, which should work.
