### ISSUE TITLE
Unexpected output size for Maxpool

### ISSUE THREAD

**Issue by lara-hdr** [pytorch/pytorch#21935]
The output of Maxpool has an unexpected size for some corner cases.

Repro:
Maxpool1d(kernel_size=3, stride=2, padding=0, dilation=2)
input=torch.randn(1,1,4)

If I use the L_out formula from the documentation (https://pytorch.org/docs/stable/nn.html?highlight=maxpool#torch.nn.MaxPool1d) to compute the output size, I get {1,1,0}.
However, the output generated has a size of {1, 1, 1}.

And with ONNX, the same operation results in an output of shape {1,1,0}
(https://github.com/microsoft/onnxruntime/issues/1224).

Since this case is not mentioned in the documentation, I was wondering if this is a special case that is handled separately by design (to avoid returning an output with a dim of 0), or if it is a bug.

**Comment by jignparm** [comment]
Any updates on this? It seems like the PyTorch implementation doesn't match the documentation for Maxpool1d, at least in the expected output shape computation.

**Comment by ailzhang** [comment]
@skrah @xmnlab can you take a look? Thanks!

**Comment by skrah** [comment]
Yes, it does not match. This is the implementation of the shape calculation:

```
template<typename T>
static inline T pooling_output_shape(
        T inputSize, T kernelSize, T pad, T stride, T dilation, bool ceil_mode) {
    T outputSize = ((inputSize + 2 * pad - dilation * (kernelSize - 1) - 1 + (ceil_mode ? stride - 1 : 0)) / stride + 1);
    if (pad) {
        // ensure that the last pooling starts inside the image
        // needed to avoid problems in ceil mode
        if ((outputSize - 1) * stride >= inputSize + pad)
          --outputSize;
    }
    return outputSize;
}
```

Looking at it very briefly, the most likely thing is that the right floor bracket in the documentation should exclude the `+1`.

But I'd need to see the original algorithm to be sure.

**Comment by skrah** [comment]
It must be a documentation issue:  Looking at c19af59, the original code had the `+ 1` outside of `ceil()` and `floor()`.

**Comment by jignparm** [comment]
>It must be a documentation issue: Looking at c19af59, the original code had the + 1 outside of ceil() and floor().

Could this be a bug in the implementation (instead of documentation)? The **+1** being outside or inside the `floor()` function should still result in same value since.
```
           floor(x + 1) = floor(x) + 1
```



For example, in issue  microsoft/onnxruntime#1224 , the  tensor size, kernel etc. variables are **i=4 ,k=3 d=2, s=2, p=0**

If the **+1** is **inside** the size computed is:

```
  outsize = floor ( (i + 2p - d*(k - 1) - 1) / s  +1 )
          = floor ( (4 + 0 - 2 *(3 - 1) - 1) / 2  +1 )
          = floor ( (4        - 2 *2    - 1) / 2  +1 )
          = floor ( (                   - 1) / 2  +1 )
          = floor (                         -0.5  +1 ) 
          = floor ( 0.5 )
          = 0
```

If the **+1** is **outside** the function then:

```
  outsize = floor ( (i + 2p - d*(k - 1) - 1) / s ) + 1 
          = floor ( (4 + 0 - 2 *(3 - 1) - 1) / 2  ) +1 
          = floor ( (4        - 2 *2    - 1) / 2  ) +1 
          = floor ( (                   - 1) / 2  ) +1 
          = floor (                         -0.5  ) +1  
          = floor (  -0.5 ) +1
          = -1 + 1
          = 0
```
In either case, the size evaluates to 0.

**Comment by skrah** [comment]
@jignparm Thanks, I replied too hastily. :)

So, revisiting c19af59:  Integer division in `C++` truncates toward zero, which gives unexpected results if the intermediate result in `pooling_output_shape()` before the division is negative:

```
(gdb) p -1 / 2
$12 = 0
```

Contrast with Python, which does not:

```
>>> -1 // 2
-1
```

So the question is if this was deliberate or not, perhaps @f0k can say more.  Removing the doc label.

**Comment by jignparm** [comment]
The implementation should allow for the output size to be 0 if the kernel is larger than input.

For example, if ** i=2, p=0, d=1, s=2, k=3**, the kernel is 1 pixel larger than the input.

The formula says output size =  **(2 - 3 )/ 2 + 1** =  **-1/2 + 1**

However, in  the C++ implementation above, because of truncation (and not flooring) we get output size = 1. In Python we get 0.

If k=4, then the C++ behavior becomes correct again, and we get output size = 0. It seems like a corner case in the C++ implementation. The  floor function seems correct to use, versus rounding towards zero.

**Comment by f0k** [comment]
> So the question is if this was deliberate or not, perhaps @f0k can say more.

Oh, good catch @lara-hdr. I'm quite sure I was not aware of different truncation rules between Python and C++ when I wrote this, my goal was to have the implementation match the documentation, and I relied on the existing test suite to tell me whether all edge cases were handled correctly. So this is a bug in the implementation and the test suite.

Note that only C++11 and above are guaranteed to truncate to zero, but that's [what PyTorch uses](https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L15), so we can rely on that.

> The floor function seems correct to use, versus rounding towards zero.

Good, since we have to stick with integer arithmetic, we will need to check whether the size is negative before dividing by the stride and apply a correction.

Side question: What do we want to happen if the kernel is much larger than the input? Follow the equation in the documentation to give a negative output size, or give an output size of zero?

**Comment by skrah** [comment]
> What do we want to happen if the kernel is much larger than the input?

It should raise an error in `shape_check()`:

```
>>> m = MaxPool1d(kernel_size=2**31-1, stride=2, padding=0, dilation=2, ceil_mode=True)
>>> m(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/rel2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stefan/rel2/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 75, in forward
    self.return_indices)
  File "/home/stefan/rel2/lib/python3.7/site-packages/torch/_jit_internal.py", line 129, in fn
    return if_false(*args, **kwargs)
  File "/home/stefan/rel2/lib/python3.7/site-packages/torch/nn/functional.py", line 458, in _max_pool1d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (1x1x4). Calculated output size: (1x1x-2147483643). Output size is too small
```

**Comment by skrah** [comment]
@jignparm However, in your example with `k=4`, the shape check (which is separate code) raises:

```
>>> input = torch.randn(1,1,2)
>>> m = MaxPool1d(kernel_size=4, stride=2, padding=0, dilation=1)
>>> m(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/conda/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/conda/miniconda3/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 75, in forward
    self.return_indices)
  File "/home/conda/miniconda3/lib/python3.7/site-packages/torch/_jit_internal.py", line 133, in fn
    return if_false(*args, **kwargs)
  File "/home/conda/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 461, in _max_pool1d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (1x1x2). Calculated output size: (1x1x0). Output size is too small at /opt/conda/conda-bld/pytorch-nightly_1557205623994/work/aten/src/THNN/generic/SpatialDilatedMaxPooling.c:51
```

**Comment by f0k** [comment]
>> What do we want to happen if the kernel is much larger than the input?
>
> It should raise an error in shape_check():

Ok, for that it's enough if we return an output size of zero:
https://github.com/pytorch/pytorch/blob/31e1e63/aten/src/ATen/native/Pool.h#L64-L69

I'm asking because then we could just return 0 if the nominator is <= zero before dividing by the stride, instead of implementing [a properly flooring integer division](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,lang:c%2B%2B,source:'%23include+%3Cstdio.h%3E%0A%23include+%3Cstdlib.h%3E%0A%23include+%3Cstring.h%3E%0A%0Aint+floor_div_a(int+a,+int+b)%0A%7B%0A++++//+requires+stdlib+div()%0A++++div_t+r+%3D+div(a,+b)%3B%0A++++if+(r.rem+!!%3D+0+%26%26+((a+%3C+0)+%5E+(b+%3C+0)))%0A++++++++r.quot--%3B%0A++++return+r.quot%3B%0A%7D%0A%0Aint+floor_div_b(int+a,+int+b)+%7B%0A++++//+portable+implementation%0A++++int+d+%3D+a+/+b%3B%0A++++int+r+%3D+a+%25+b%3B%0A++++if+(r)+%7B%0A++++++++return+d+-+((a+%3C+0)+%5E+(b+%3C+0))%3B%0A++++%7D+else+%7B%0A++++++++return+d%3B%0A++++%7D%0A%7D%0A%0Aint+floor_div_c(int+a,+int+b)+%7B%0A++++//+only+valid+for+%3E%3D+C99+/+C%2B%2B11%0A++++return+(a+%3E%3D+0)+%3F+(a+/+b)+:+-((-a)+/+b)%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:48.35509138381202,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g74,filters:(___0:(),b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',jquery:'3.2.1',length:1,libraryCode:'1',prevObject:(___0:(),length:1,prevObject:(___0:(jQuery321065988541133087141:(display:'')),length:1)),trim:'0'),lang:c%2B%2B,libs:!(),options:'-O3+-xc%2B%2B+-std%3Dc%2B%2B11',source:1),l:'5',n:'0',o:'x86-64+gcc+7.4+(Editor+%231,+Compiler+%231)+C%2B%2B',t:'0')),header:(),k:51.644908616188,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

**Comment by f0k** [comment]
> I'm asking because then we could just return 0 if the nominator is <= zero before dividing by the stride, instead of implementing a properly flooring integer division.

Just checked what the convolution shape computation does, turns out they use a `div_rtn` function, which is the second of the implementations I linked to: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/div_rtn.h
So we should just reuse it here, and extend the test suite accordingly.

**Comment by jignparm** [comment]
>Side question: What do we want to happen if the kernel is much larger than the input? Follow the equation in the documentation to give a negative output size, or give an output size of zero?

From the the case of K=4 that @skrah mentioned above,  it looks like the prevailing pattern is to  raise an exception. A negative value would be confusing -- so 0 or else raising exception seems most logical.,

**Comment by f0k** [comment]
The exception is not raised by the shape computation code, but outside, and [the exception message includes the computed shape](https://github.com/pytorch/pytorch/blob/31e1e63/aten/src/ATen/native/Pool.h#L64-L69). Not sure if it would make a difference for anything else but the message. But I'd suggest to be consistent with the convolution, since it's the same problem.
