### ISSUE TITLE
when i use the max_unpool2d ,i got some error

### ISSUE THREAD

**Issue by visonpon** [pytorch/pytorch#2222]
the error like this 

```
file "****/funtional.py" line 253, in _unpool_output_size
kernel_size[d]-2*padding[d]
typerror:unsupported operand type(s) for * long nad nonetype
```

**Comment by soumith** [comment]
can you give a code snippet that reproduces this error?

**Comment by visonpon** [comment]
@soumith when i call ther max_unpool2d function like` out=F.max_unpool2d(input,2,ouput_size=(n,n))` ,
 **i got the following message:**
```
File"/home/*/torch/nn/functional.py" line 292, in max_unpool2d outputsize)
File"/home/*/torch/nn/functional.py" line252 in _unpool_output_size 
default_size.append((input_size[d+2]-1)*stride[d]+kernel_size[d]-2*padding[d])
TypeError: unsupported perand type(s) for *: 'long' and 'NoneType'.
```

**Comment by fmassa** [comment]
@visonpon you are using the wrong function signature. You should pass the `indices` from the `max_pool2d` as the second argument of `max_unpool2d`, as mentioned in the [docs](http://pytorch.org/docs/master/nn.html#torch.nn.functional.max_unpool2d)

**Comment by visonpon** [comment]
@fmassa 
- when i do like this` out=F.max_unpool2d(input,indices,kernel_size=m,stride=m,ouput_size(n,n))`, i got a `NameError: global name 'indices' is not defined.`

Is there something i ignore ? since i am a new user, i sincerely hope you can show me details about how to debug this problem, thanks.

**Comment by fmassa** [comment]
Have a look a the [full documentation of MaxUnpool](http://pytorch.org/docs/master/nn.html#torch.nn.MaxUnpool2d). You first need to get the indices from `MaxPool`, and then pass those indices to `MaxUnpool`. For example:
```python
out1, indices = F.max_pool2d(x, kernel_size=2, return_indices=True)
result = F.max_unpool2d(out1, indices, kernel_size=2, stride=2, output_size=x.size())
```
Note that you need to pass the `stride` parameter manually to `max_unpool2d` for the moment.
We should change a bit how we handle the default in `max_unpool` so that we don't have to pass the `stride` manually. I'll send a fix for it.

**Comment by visonpon** [comment]
@fmassa thanks,  follow your detailed instruction ,i have solved thisd problem，thanks~
