### ISSUE TITLE
Why is THPVariable_invert implemented on the python level and not c++

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#22262]
It looks like THPVariable_invert should be implemented in C++ to avoid duplicate work from a JIT team. 

For more details, please, see [PR](https://github.com/pytorch/pytorch/pull/21113) comments.

**Comment by colesbury** [comment]
To clarify, it's [written in C++](https://github.com/pytorch/pytorch/blob/5f84f372a6fcd265bdd00f1f4481a47815ee6fc3/tools/autograd/templates/python_variable_methods.cpp#L285-L299) but it's defined in python_variable_methods.cpp not in ATen.

For the "why" part, it was because of the funky name in Python (`__invert__`) and because it was implemented as a simple one-liner: `1 - self`.

The name turns out not to matter. We have other native_functions defined with double underscore prefixes, so that should be OK. It should totally be fine to move it to ATen.

**Comment by xuhdev** [comment]
Fixed in 9c4c9c3af042498144c40b30d64443cca943906a

**Comment by xuhdev** [comment]
Reverted for now, see https://github.com/pytorch/pytorch/pull/22326#issuecomment-510280113

**Comment by xuhdev** [comment]
Fixed in 865c7eea4854fcfb50584e7f19450b4271c1b4f1
