### ISSUE TITLE
Set OMP_NUM_THREADS in torch.distributed.launch

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#22260]
Per #20311 the default value for this (and related) settings may be too high if you launch multiple PyTorch processes per machine. We can do better and provide a more sane default that is tuned to the number of processes to launch in `torch.distributed.launch`.

@VitalyFedyunin Besides OMP_NUM_THREADS, which other variables could we provide a better default for, knowing the number of processes we'll launch on a single machine?

**Comment by pietern** [comment]
cc @zhaojuanmao

**Comment by mfuntowicz** [comment]
Ran exactly on the same issue while debug performance issues on DGX-2 station. 

When allocating more than 4 GPUs the performances started to drop significantly. It took some times to figure out the issue was related to OMP_NUM_THREADS.

It seems that an optimal value is given by OMP_NUM_THREADS = nb_cpu_threads / nproc_per_node.

I can have a look at this if you want to :)

**Comment by zhaojuanmao** [comment]
@mfuntowicz I had a diff out yesterday, I will export the PR soon

**Comment by mrshenli** [comment]
closed by #22501
