### ISSUE TITLE
element-wise multiplication out of memory

### ISSUE THREAD

**Issue by hadifar** [pytorch/pytorch#22305]
How can I do following element-wise multiplication in Pytorch without out of memory? 

```
import torch

g = torch.rand([20, 75, 1024, 1024])
w = torch.rand([1024, 1024])

res = torch.einsum('ijkl,kl->ijkl', [g, w])
# w..unsqueeze(0).unsqueeze(0) * g --> also try this but not work!
print(res.shape)
#
```
```
Original exception was:
Traceback (most recent call last):
  File "", line 6, in <module>
    res = torch.einsum('ijkl,kl->ijkl', [g, w])
  File "", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

```

I did the same thing in tensorflow and worked fine:

```
import tensorflow as tf

g = tf.random_normal([20, 75, 1024, 1024])
w = tf.random_normal([1024, 1024])

res = tf.einsum('ijkl,kl->ijkl', g, w)
print(res.shape)
# (20, 75, 1024, 1024)
```

**Comment by colesbury** [comment]
You need ~12.6 GB of memory for your example (20 *75 * 1024* 1024 * 4 bytes * 2 = 12.58 GB). The last 2 is because you need space for `g` and `res`. If you don't care about keeping the value of `g` do:

```python
import torch

g = torch.rand([20, 75, 1024, 1024])
w = torch.rand([1024, 1024])
g *= w
res = g
```

That will require ~6.3 GB of memory.

Also, element-wise multiplication is just `g * w` in general. You can use einsum if you want, but it's not necessary.

You're Tensorflow example isn't actually running anything (you'd need a `session.run()` call) so it doesn't require any memory for storing tensor data.
