### ISSUE TITLE
Ambiguous torch.Tensor int vs float comparison

### ISSUE THREAD

**Issue by azakhtyamov** [pytorch/pytorch#22301]
## 🐛 Bug

Ambiguous torch.Tensor int vs float comparison

## To Reproduce
input: torch.Tensor([0]).int() < 0.5
output: tensor([0], dtype=torch.uint8)

## Expected behavior
Expected numpy-like behavior:
input: torch.Tensor([0]).int() < 0.5
output: tensor([1])

- PyTorch 1.0.1
- Ubuntu 18.04

**Comment by zou3519** [comment]
cc @nairbv: I think type promotion things might be able to fix this?

**Comment by nairbv** [comment]
Thanks @azakhtyamov for pointing this out.

Yes @zou3519 this is related to https://github.com/pytorch/pytorch/issues/9515. 

In this particular case the `<` operator casts the operand (0.5) to an int before performing the comparison. Essentially this means it's checking `< 0` instead of `< 0.5`.

The relevant code is in the generated LegacyTHFunctionsCPU.cpp.

Similarly `torch.IntTensor([2]) * 1.9` results in `tensor([2], dtype=torch.int32)` instead of `3`, because the 1.9 is cast to an int tensor `1`.

**Comment by OneMoreSecond** [comment]
The promotion from float to int Tensor is really confusing.

**Comment by nairbv** [comment]
I think we've only fixed for one comparison operator so-far so re-opening.
@ifedan

**Comment by ifedan** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/26981
