### ISSUE TITLE
Error when converting np.float32 array to torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by DmitryUlyanov** [pytorch/pytorch#2246]
Hi, for some reason it fails, only float64 can be converted.

```
torch.cuda.FloatTensor(np.random.rand(10,2).astype(np.float32))
```
gives

```
RuntimeError: tried to construct a tensor from a nested float sequence, but found an item of type numpy.float32 at index (0, 0)
```

while
```
torch.cuda.FloatTensor(np.random.rand(10,2).astype(np.float64))
```

works fine.

**Comment by CDLuminate** [comment]
The error message is likely from here
```
torch/csrc/generic/Tensor.cpp
322:        THPUtils_setError("tried to construct a tensor from a %s%s sequence, "
```

**Comment by lynic** [comment]
I think this is the same issue as https://github.com/pytorch/pytorch/issues/1957.

**Comment by vadimkantorov** [comment]
Seems a bug, but if I understand well, `torch.from_numpy` should be used for conversion (at least currently), because the constructor would treat their input as a generic sequence and will iterate over it (which is inefficient and will hurt except for really small tensors).

**Comment by lantiga** [comment]
For the records,
```
torch.DoubleTensor(np.array([0,1,2], dtype=np.float32))
```
also fails. /cc #1957

Just to clarify: performance-wise, currently the operation is exactly equivalent to `torch.from_numpy` if the `dtype` of the array is the same as the type of the tensor, otherwise it falls back to treating the tensor as a sequence (thus iterating over every element, as @vadimkantorov was mentioning). See https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/Tensor.cpp#L231 onwards.

Given the subtlety and the resulting impact on performance, we have two options:
- have a constructor with a numpy array as an argument throw if the numeric types do not match
- avoid throwing an exception, but cast the array by looping over the underlying `PyArray_DATA(array)`, thus avoiding treating the array as a sequence.

I'd look into the second option.

**Comment by apaszke** [comment]
Yea. A simpler way to implement second option would be to construct a tensor of appropriate toe and use TH functions to cast it.

**Comment by lantiga** [comment]
👍🏻 I'll take care of this

**Comment by lantiga** [comment]
Although, I still have a doubt: if we go this route, the semantics will change depending on types: if types match, changing the tensor will also change the numpy array, but this won't happen if types don't match. Isn't this a bit too subtle? 

It's almost like we should always copy in the constructor and only share memory with from_numpy.

I'm fine either way, just want to be sure.

**Comment by lantiga** [comment]
@apaszke before I proceed, should we always copy to ensure the semantics do not change? (See last comment for context). Thanks!

**Comment by apaszke** [comment]
The semantics would be exactly equivalent to what we have right now - tensors share data if they can, otherwise they don't (they didn't share it when they treated numpy arrays as sequences of numbers)

**Comment by lantiga** [comment]
Good point
