### ISSUE TITLE
Improve documentation of torch.lu

### ISSUE THREAD

**Issue by arvidfm** [pytorch/pytorch#22552]
## 📚 Documentation

Currently it is not clear from the description how to interpret what `torch.lu` returns, i.e. how exactly to recover the matrices P, L and U from the return values. This indirectly means that it's also unclear what format `torch.lu_solve` expects. Note that the format of the return values differs from `scipy.linalg.lu`.

**Comment by vishwakftw** [comment]
Thank you for opening the issue. The way to recover the P, L, U matrices is to use torch.lu_unpack.

However, I do agree that it is better to mention this in the docs. I’ll fix this soon.

**Comment by arvidfm** [comment]
Ah, yes, I see. I was hoping for more of an explicit description of the format, as in my case I already have an LU-factorized matrix, and I need to know how to convert it into the format required by `torch.lu_solve`. Or perhaps there could be a `torch.lu_pack` function.

**Comment by Lezcano** [comment]
This was solved with the introduction of [`torch.linalg.lu_factor`](https://pytorch.org/docs/master/generated/torch.linalg.lu_factor.html). Hopefully now you'll find the documentation more readable. `torch.lu` is being deprecated.

Note: A couple of links are missing as it's waiting for a few other PRs to be merged, but that should be fixed in a few weeks :)
