### ISSUE TITLE
Drop 'add extra samples to make it evenly divisible' constraint in DistributedSampler

### ISSUE THREAD

**Issue by lpuglia** [pytorch/pytorch#22584]
## 🚀 Feature
Drop 'add extra samples to make it evenly divisible' constraint in DistributedSampler 

## Motivation

I was having problem with [distributed](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/distributed.py) module in v1.1.0 (and master as well), my function for `validation_set_eval` was giving different results according to the number of processes.

Then i discovered that some sample are repeated by:
https://github.com/pytorch/pytorch/blob/d4464d3418cd02a09ac75f60b9661b6671e60b11/torch/utils/data/distributed.py#L54

I know how this is uninfluential during training step, but it could be annoying to write validation procedure that takes into account multiple entry for the same input.

## Pitch

The sampling instruction:
https://github.com/pytorch/pytorch/blob/d4464d3418cd02a09ac75f60b9661b6671e60b11/torch/utils/data/distributed.py#L58
is gonna work no matter the divisibility anyway.

is it possible to drop this constraint? if not, why is it important for the dataset to be spread into evenly divisible bins?

**Comment by zou3519** [comment]
cc @mrshenli

**Comment by SsnL** [comment]
Because otherwise a rank will have less samples and thus possibly less iterations, and the other ranks running all reduce will hang waiting for it.

**Comment by ngimel** [comment]
That's true, but the concern of repeating samples during validation/testing is also valid, repeating samples can noticeably distort results.

**Comment by lpuglia** [comment]
> Because otherwise a rank will have less samples and thus possibly less iterations, and the other ranks running all reduce will hang waiting for it.

well, that is not a valid concern, let's say you have 4 ranks and 202 inputs, a the moment the split gives you:
```
rank 0: 51 samples
rank 1: 51 samples
rank 2: 51 samples (1 repeated)
rank 3: 51 samples (1 repeated)
```
what i'm proposing is to split the input in the following way:
```
rank 0: 51 samples
rank 1: 51 samples
rank 2: 50 samples
rank 3: 50 samples
```
the current splitting strategy is gonna take ALWAYS more-or-equal time, so unless there is some optimization that is done at `reduce` time that requires ranks of the same size there is no reason to repeat inputs.

**Comment by SsnL** [comment]
I don't think you understand what I meant. It is not about extra time or whatsoever. 

In your example, if `batch_size=1`, then rank 2 and 3 run 1 less iteration, and the other ranks must know and account for it in distributed collectives, e.g., `DistributedDataParallel`'s all reduce, otherwise the they will just hang forever. 

That said, it is true that this could be solved by adding extra logic in actual code using calling these collectives. But it will be a bit tricky to implement. E.g., in core library, `DistributedDataParalllel` and `DistributedSampler` are two independent components, so it requires some careful design to let `DistributedDataParalllel` know what is going on in the sampler.

**Comment by fmassa** [comment]
If there is a way to query the dataset indices that have been returned by the dataloader at a given point in time, then it is possible to have distributed evaluation (with metrics) which works fine even if there are repeated examples.

I have some examples in `torchvision/references` and `maskrcnn-benchmark`, but it currently requires overwriting the dataset to return the sampled `idx`, which could potentially be queried from the dataloader.

**Comment by lpuglia** [comment]
> If there is a way to query the dataset indices that have been returned by the dataloader at a given point in time, then it is possible to have distributed evaluation (with metrics) which works fine even if there are repeated examples.
> 
> I have some examples in `torchvision/references` and `maskrcnn-benchmark`, but it currently requires overwriting the dataset to return the sampled `idx`, which could potentially be queried from the dataloader.

that is for sure, in fact this is what i'm doing right now to use `torchvision/references/detection` in conjunction with PASCAL VOC python evaluator (which uses files), anyway, mine was just a proposal to make the use of the library more neat, if it is too hard/unoptimizable to implement there is no need to work on it.

**Comment by fmassa** [comment]
@lpuglia I tried doing what you proposed in `maskrcnn-benchmark`, but it used to give deadlocks (at least with an older version of PyTorch and DDP), precisely because some GPUs would compute a different number of forward operations.

This might have been fixed since then, but I believe what we need to have is a set of evaluation metrics which work on distributed settings (like the one I have in `torchvision/references/detection` for COCO).

**Comment by miquelmarti** [comment]
@fmassa Any updates on this? Seems like correct distributed evaluation with DDP is currently only possible by keeping track of sample ids as you did here? https://github.com/pytorch/vision/blob/f2f490b10bfb4e498478d4cad25300db955bcfcd/references/detection/coco_eval.py#L172
