### ISSUE TITLE
Missing Implicit Flattening in v0.2

### ISSUE THREAD

**Issue by ritchieng** [pytorch/pytorch#2313]
**Error after upgrading to v0.2**

`RuntimeError: Expected argument self to have 1 dimension(s), but has 4 at /opt/conda/conda-bld/pytorch_1502006348621/work/torch/csrc/generic/TensorMethods.cpp:23086`

**Line that has issue**
`torch.dot(tensor_1, tensor_2)`
- tensor_1 size: (512L, 256L, 3L, 3L)
- tensor_2 size: (512L, 256L, 3L, 3L)

Used to work prior to v0.2 (I downgraded to 0.1.12 and it worked) @Soumith_Chintala

**Comment by fmassa** [comment]
This is an explicit choice, see https://github.com/pytorch/pytorch/pull/1781
I believe the reason why it was removed was that it made implicit assumptions that do not hold anymore because of broadcasting/
For example, before we could add a `2x2` and a `4` dimensional tensor, which is not supported anymore (or raises a warning).
Also, it's behavior was different from numpy's when multiple dimensions are taken into account, which could confuse users.

cc @gchanan if I missed something here.

**Comment by gchanan** [comment]
Here is a relevant thread where the above PR was discussed: https://github.com/pytorch/pytorch/issues/138#issuecomment-307053246

**Comment by fmassa** [comment]
For a bit more info on the choice of removing flattening of `dot`, check https://github.com/pytorch/pytorch/issues/1756
