### ISSUE TITLE
torch.mean() calculations are not consistent across CPU/GPU

### ISSUE THREAD

**Issue by rtarquini** [pytorch/pytorch#23392]
## To Reproduce

1. import torch
1. a=torch.linspace(10000,1.7,10000)
1. a.mean()
1. a.cuda().mean()
1. a.sum()/a.numel()

>>> a=torch.linspace(10000,1.7,10000)
>>> a.mean()
tensor(5000.9077)
>>> a.cuda().mean()
tensor(5000.8501, device='cuda:0')
>>> a.sum()/a.numel()
tensor(5000.8496)

## Expected behavior

The mean should be sum()/#elements = tensor(5000.8496)
Both the CPU and GPU mean values are incorrect for Xavier, on the x86 Linux box the CPU mean is correct. 

## Environment

Please copy and paste the output from our
Collecting environment information...
PyTorch version: 1.1.0a0+ceb9702
Is debug build: No
CUDA used to build PyTorch: 10.0.166

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.11.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.166
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/aarch64-linux-gnu/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0a0+ceb9702
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

## Additional context

On an x86 based Linux box the CPU mean is correct, but does not match the GPU mean

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.11.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080
GPU 3: GeForce GTX 1080

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] PytorchMakefileTutorial==0.1.0
[pip3] torch==1.1.0
[pip3] torchvision==0.2.1
[pip3] torchviz==0.0.1
[conda] Could not collect

>>> a=torch.linspace(10000,1.7,10000)
>>> a.mean()
tensor(5000.8496)
>>> a.cuda().mean()
tensor(5000.8501, device='cuda:0')
>>> a.sum()/a.numel()
tensor(5000.8496)

**Comment by rtarquini** [comment]
Using float64 results in a closer calculation between cpu/gpu.  I suspect there is precision problem in the mean() code associated with the summing the float32 values.  i.e small values summed at the end of array may be rounded off.  Sorting the array from smallest->largest before summing would produce a more precise sum. 

>>> a=torch.linspace(10000,1.7,10000,dtype=torch.float64)
>>> a.mean()
tensor(5000.8500, dtype=torch.float64)
>>> a.cuda().mean()
tensor(5000.8499, device='cuda:0', dtype=torch.float64)

**Comment by andreaskoepf** [comment]
Sum itself seems to behave a bit different for gpu & cpu for your array of values.

This is what I see:

```
a=torch.linspace(10000,1.7,10000)
b=a.cuda()
a.sum()
# tensor(50008496.)
b.sum()
# tensor(50008504., device='cuda:0')
```
I am not sure if this really is to be classified as a bug or as an acceptable artifact of parallel floating point summation on the GPU. The order of fp summation operations generally matters since a summand with larger exponent will ignore bits from a smaller summand's mantissa. Different algorithms exist to counter this, e.g. [Kahan_summation_algorithm](https://en.wikipedia.org/wiki/Kahan_summation_algorithm). Also one should keep in mind that internally different register width might be used, even on CPU e.g. 80 bits for the x87 while SSE uses stictly 64/32 bit float registers etc.

A GPU summation precision related discussion (with some papers) is in the NVIDIA dev forums [here](https://devtalk.nvidia.com/default/topic/1044661/how-to-improve-float-array-summation-precision-and-stability-/).

**Comment by RafayAK** [comment]
@rtarquini  Check out the following post on the PyTorch Forums they answer all your questions:

https://discuss.pytorch.org/t/significance-of-the-difference-between-cpu-and-gpu-results/14739/3

https://discuss.pytorch.org/t/why-different-results-when-multiplying-in-cpu-than-in-gpu/1356/3
