### ISSUE TITLE
Log NCCL version in NCCL exceptions

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#23549]
## 🚀 Feature

We don't know which version of NCCL was used from an exception trace. NCCL may be built from tree or may be supplied externally (and loaded dynamically) so we have to figure this out at runtime. The version number should be included in NCCL error messages.

## Motivation

See issue #23534 for an example that made me think we should do this. If we include the NCCL version in the exception, there is no longer any ambiguity whether or not the error happened on a NCCL version with/without some fix.

## Pitch

Figure out the NCCL version with [`ncclGetVersion`](https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/api/comms.html#ncclgetversion) and use it in any exception that gets thrown.

See `torch/lib/c10d/ProcessGroupNCCL.cpp` for the macros.

**Comment by yaroslavvb** [comment]
Could also be useful to get NCCL version accessible through PyTorch interface, so I could log it on all runs. Maybe `torch.__version_and_libs__` to return string with pytorch, cuda, nccl versions.

 Sometimes updates in NCCL version make it slow instead of crashing. Using NCCL_DEBUG=INFO prints debug info but no version info so you have to choose whether to see more version or debug info.

**Comment by rohan-varma** [comment]
Done in https://github.com/pytorch/pytorch/pull/27068.
