### ISSUE TITLE
[quant] use qconfig_dict in graph mode

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#24062]
## 🚀 Feature

Extend the initial implementation to use qconfig_dict,
Need scoping support, cc @ZolotukhinM

**Comment by ZolotukhinM** [comment]
PR for adding Scopes: #21939 

But there is also an alternative now. We need the scope info to recover the info we're losing during inlining. Instead of recovering this info (which is done in the PR above), we can disable inlining. That's also planned and @suo is currently working on it. Without inlining we would be always  able to figure out the parent Function/Module for any node.

**Comment by jerryzh168** [comment]
this is done, but we want to support non-scriptable observer as well
