### ISSUE TITLE
IB network card in distribution

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#24069]
```
# node1 
export NCCL_SOCKET_IFNAME=ib0
export NCCL_DEBUG=INFO 
export NCCL_DEBUG_SUBSYS=ALL
unset NCCL_IB_DISABLE

init_method="tcp://66.66.66.75:10087"

# node2
export NCCL_SOCKET_IFNAME=ib0
export NCCL_DEBUG=INFO 
export NCCL_DEBUG_SUBSYS=ALL
unset NCCL_IB_DISABLE

init_method="tcp://66.66.66.75:10087"
```

I have two IB network card at every node, but only one be used. When I run by mpi, I config `NCCL_SOCKET_IFNAME=ib0, ib1`， the two IB network card are used, every 4 GPU use the same IB network card.

I want to know that pytorch distribution only use one IB network card, or my config in pytorch is error?

**Comment by pietern** [comment]
Looking at the [NCCL documentation](https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/env.html#nccl-socket-ifname), I think that `NCCL_SOCKET_IFNAME` acts as a whitelist only, and not as an instruction that it **must** use all of those interfaces. It says:

> Define to a list of prefixes to filter interfaces to be used by NCCL.

Also, if I understand correctly, `NCCL_SOCKET_IFNAME` only applies if you're using socket I/O. If you have a setup with IB cards, then it should use native IB instead.

If you expect something else, I encourage you to open an issue at https://github.com/nvidia/nccl.

I'm closing the issue because this related to NCCL only.
