### ISSUE TITLE
pytorch inference eat all cpu

### ISSUE THREAD

**Issue by kakaluote** [pytorch/pytorch#24142]
![2019-08-10-10-07-13](https://user-images.githubusercontent.com/9446310/62816302-4246dd00-bb57-11e9-9a04-e33859fde7ca.png)

ubuntu16.04, pytorch1.0, no dataloader , run on gpu ,all cpus are 100% when inference images in a loop. why there are 10 process with no dataloader,  why transform a image use so big cpu load（model forward run on gpu）, and when i have other process use cpu , the inference will be slow

also on windows10,pytorch1.1

**Comment by SsnL** [comment]
These look like threads rather than processes. Pytorch does not launch multiple processes outside dataloader and distributed training launcher. Multithreading could be coming from pytorch ops (e.g., if your preprocess fn uses pytorch ops on CPU) or other libs. If it is the former, you can limit them by using `torch.set_num_threads`. For the later case you should check with the libraries you
 use.

**Comment by kakaluote** [comment]
yes，i move the preprocess (image transform) to gpu, the cpu usage drop down
