### ISSUE TITLE
Documentation for torch.argsort includes an `out` argument

### ISSUE THREAD

**Issue by calincru** [pytorch/pytorch#24158]
Perhaps it has been recently removed. [The documentation](https://pytorch.org/docs/stable/torch.html#torch.argsort) should be updated.

**Comment by calincru** [comment]
Actually, I just realized that maybe *it is* supposed to work with an `out` argument. Then take it as a bug report -- it's not working (using the latest nightly build).

**Comment by tczhangzhi** [comment]
It works well for me:
```
def test_sort(self):
        SIZE = 4
        x = torch.rand(SIZE, SIZE)
        res1val, res1ind = torch.sort(x)

        # Test use of result tensor
        res2val = torch.Tensor()
        res2ind = torch.LongTensor()
        torch.sort(x, out=(res2val, res2ind))
```

**Comment by calincru** [comment]
@tczhangzhi I was talking about `torch.argsort`, not `torch.sort`.

**Comment by tczhangzhi** [comment]
Oh, my bad!
Then I think you are right:
https://github.com/pytorch/pytorch/blob/0dcb8755c8ba23922a3940e0d835cbb3db5944ad/tools/autograd/gen_python_functions.py#L916-L923
So, if the `len(output_args) == 1`, the API won't have parameter `out`. And because of the API `torch.sort(...) -> (Tensor, LongTensor)` and `torch.argsort(...) → LongTensor`, `sort` has an `out` but `argsort` not.

**Comment by tczhangzhi** [comment]
I have checked the release history:
In PyTorch 1.0, `argsort` was implemented by python #9600
In PyTorch 1.1, `argsort` was rewritten in C++ and the Doc went wrong #17099

**Comment by pietern** [comment]
Thanks for investigating, @tczhangzhi! Would you be willing to post a PR to fix this?

**Comment by tczhangzhi** [comment]
Sure~

**Comment by mruberry** [comment]
This was addressed by the linked PR.
