### ISSUE TITLE
Pin flake8 version in CI

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#24188]
## 🚀 Feature
We should pin the flake8 version in our CI.

## Motivation

flake8 updated and broke our Python lint: https://github.com/pytorch/pytorch/pull/24184 . To prevent against random breakages in the future and to make our CI less flaky, we should pin the flake8 version and upgrade periodically.

**Comment by antocuni** [comment]
FWIW, it happened again. This time the culprit is not flake8 itself but flake8-bugbear.
According to [flake8-bugbear changelog](https://github.com/PyCQA/flake8-bugbear#change-log) version 20.11.1, released on 2020-11-24, added new warning such as `B015: Pointless comparison` and others, and our CI started to fail. Examples of recent failed runs:
- https://github.com/pytorch/pytorch/runs/1451855010
- https://github.com/pytorch/pytorch/runs/1451183549
- https://github.com/pytorch/pytorch/runs/1449556331

The last run which did **not** fail flake8 is [this](https://github.com/pytorch/pytorch/runs/1442181297), which used `flake8-bugbear==20.1.4`.

**Comment by huydhn** [comment]
This has already been done https://github.com/pytorch/pytorch/blob/main/requirements-flake8.txt
