### ISSUE TITLE
Migrate `index_fill_` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24577]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by anjali411** [comment]
hi pri because https://github.com/pytorch/pytorch/issues/50381

**Comment by mattip** [comment]
These are the kernels in [`THTensor_(indexFill)`](https://github.com/pytorch/pytorch/blob/master/aten/src/TH/generic/THTensorEvenMoreMath.cpp#L246)? Would it make sense to use a template instead of the big switch in [`_th_index_fill_`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/LegacyTHFunctionsCPU.cpp#L446) ?

**Comment by anjali411** [comment]
@mattip We use the dispatch macro in ATen, so we won't need the switch statement anymore

**Comment by mattip** [comment]
xref the issue gh-24714 and PR  gh-50527 to migrate the CPU version of `index_fill_`
