### ISSUE TITLE
Migrate `scatter` and `scatter_` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24621]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Marking high priority as these exercise `zero_dim_dispatch_when_scalar`

**Comment by v0dro** [comment]
CC : @nikitaved 

# Porting approaches

There are three ways of porting the scatter operation from TH to ATen:

1. Directly copy the TH looping approach and utilize the same CUDA kernels. (non-deterministic)
2. Use TensorIterator similar to https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/IndexKernel.cu . (non-deterministic)
3. Sort indices before iteration so that it always happens in sequence and leads to a
   deterministic operation. (determinisitic)
4. Force CUDA threading to use a threading mode similar to the CPU implementation
   such that each thread iterates over the numbers always in the same order. (determinisitic)
   
## Analysis of non-deterministic approaches
   
Approach `1`, `2` are non-deterministic implementations while `3` and `4` are deterministic
algorithms. @ngimel in https://github.com/pytorch/pytorch/issues/24567#issuecomment-590990662
points out that restricting the memory access for the opearational dimesion to a single thread
can be extremely slow due to memory access latency. Therefore, `4` is ruled out.

`1` and `2` would mimic the behaviour of the current TH implementation and will lead to the
same problems regarding determinism (pointed out in https://github.com/pytorch/pytorch/issues/23151) when we eventually use the scatter algorithm for implementing reduction operations. Building
deterministic algorithms on top of this will require implementation of Demmel's [algorithms](https://ieeexplore.ieee.org/document/6545904/).

## Analysis of determinisitic approaches

Sorting the indices (approach `3`) and then iterating on them is something that is implemented
in the CUDA version of `index_put_` (with accum=True), find it [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Indexing.cu#L180). The cost of sorting is typically not so much since the index tends to be of much lower dimension than the input. In case of `index_put_`,
the computation is spread to a different worker per index, which ensures that a single worker (or
CUDA thread) only accesses a single location in the output buffer for writing. This ensures that there
is no need for an expensive locking operation.

If we apply the sorting approach of `3` to the scatter reduction operations, we can first sort
the indexes and distributed each sorted interval to a different CUDA thread. Since this will
ensure that the write accesses on the output will always happen in sequence, we will have a
highly parallel and determinisitic implementation of scatter and scatter reduction algorithms
without having to implement Demmel's algorithm as pointed out above.

If the cost of Demmel's algorithm (and the overhead of performing an atomic reduction operation)
is more than the sorting cost of approach `3`, it makes sense to implement the sorted
indices approach. The implementation of `3` is also substantially easier (and more maintainable)
than implementing a brand new algorithm from a research paper.

## Conclusion

Therefore, I would propose use of approach `3` for porting `scatter_` to ATen and using the
primitives that will be subsequently implemented for implementation of the scatter reduction.

**Comment by ezyang** [comment]
OK, sounds reasonable. cc @ngimel if she has any further thoughts.

**Comment by ngimel** [comment]
How strongly do we feel about determinism? If the answer is "not particularly", I'd suggest using approach 1. Approach 3 with sorted indices might still result in some very awkward access patterns when scattering along last dimension.

**Comment by ezyang** [comment]
Well, we definitely will want to provide a speedy non-deterministic scatter at some point. And there are beneficial side effects to migrating to TH to ATen, so you don't *have* to fix "all the problems" when you do a port; a slavish port is OK too, and then fix it up afterwards.

**Comment by v0dro** [comment]
Hmmm in that case it might be worthwhile to see if Demmel's algorithm is faster than performing the index sorting.

**Comment by v0dro** [comment]
As was agreed in today's meeting, I will work on a straightforward port to ATen and Nik will work on porting using TensorIterator, after which we can compare the performance and see which implementation is faster.

**Comment by Baranowski** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/35697
