### ISSUE TITLE
Migrate `_cumsum` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24669]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by v0dro** [comment]
@VitalyFedyunin since `cumsum` is a native function that internally calls `_cumsum` that is a TH function, is it okay to remove `_cumsum` altogether and simply move the logic in the TH-implemented `_cumsum` to the ATen-implemented `cumsum`?

**Comment by v0dro** [comment]
Here's my progress so far:

The current implementation essentially relies on the `shape_` array
inside TensorIterator that is populated by `compute_shape` when the
iterator is built. This array is built using an algorithm that can
figure out how the shape of the output tensor can be broadcast over
the input tensor. Say for example we have an output of shape `[1,4]`
and input of `[3,4]` it means that the reduction has to be calculated
on the 0th dimension of the input.

This works for things like sum or prod, but for cumsum it fails since
both the input and output tensors are of the same shape and therefore
`shape_` turns out to be `[12]`.

Therefore, the implementation of this boils down to understanding
and implementing two things:
1. Changing the `shape_` to reflect broadcast over a specific dimension even though the default would suggest a single large dimension.
2. Implement a looping functionality that would allow nicely looping over any given dimension for two tensors that have the exact same shape.

Please correct me if I am wrong.

**Comment by XiaobingSuper** [comment]
@v0dro and @ifedan(https://github.com/pytorch/pytorch/pull/28507) , do you stll work on it? if not, this [patch](https://github.com/XiaobingSuper/pytorch/commit/bcc5d5d7c9de595fa32fbb5db9d550fae17bdc53) have implemented it.

**Comment by VitalyFedyunin** [comment]
@XiaobingSuper can you please create PR out of this patch. Thanks.
