### ISSUE TITLE
Migrate `remainder` and `remainder_` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24753]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
Marking high priority as these exercise zero_dim_dispatch_when_scalar

**Comment by ezyang** [comment]
An alternative is to just move the codegen into the implementation (which is a shorter thing to do).

**Comment by kurtamohler** [comment]
I based my changes on other ATen operations, like div and mul, which made me think I might as well include complex number support. The TH version did not have complex support. Is that alright?

**Comment by VitalyFedyunin** [comment]
Sure, as soon as you extend test coverage.

**Comment by kurtamohler** [comment]
I thought a bit more carefully about how I was attempting the calculate the remainder for complex numbers. I assumed that it would be the same as what we're doing for floating point numbers, but that idea doesn't really make sense. At the moment, I'm not exactly sure what it would mean to have a remainder for a complex division.

Wolfram defines their remainder function as "_m_ mod _n_". If m and n are complex numbers, the formula on this page is used: http://functions.wolfram.com/IntegerFunctions/Mod/27/01/02/02/0001/

I probably shouldn't just copy what Wolfram is doing without understanding it myself. If I can't figure it out, I'll just remove the complex support.

**Comment by kurtamohler** [comment]
So after some more searching and thinking, I haven't found any convincing definition of a remainder or mod function for complex numbers. With real numbers, the remainder is defined as `mod(a, b) = a - b * floor(a / b)`. The `floor(a / b)` basically means "the integer number of times you can subtract `b` from a without going negative", or "the integer number that you can multiply `b` by to get the closest value below or equal to `a`". Then the remainder is just the distance away from `a` after you multiply `b` by `floor(a / b)`.

Translating this idea into the complex space doesn't really make any sense to me. If `a` and `b` are complex, then what is `floor(a / b)`? There's not really a concept of an "integer" complex number (there are gaussian integers, but I don't think that's really the same thing), and there's not really an absolute concept of "less than/greater than" or "positive/negative" complex numbers. But yet Wolfram has a definition of a remainder for complex numbers, so maybe I'm wrong. Let me know if anyone here can shed any light.

For now, I'll just remove the complex remainder. Would anyone even want to use it anyway?

**Comment by ezyang** [comment]
cc @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
@kurtamohler For a porting task, I would definitely not expect you to add extra functionality that didn't exist before. So not handling complex is fine.

**Comment by kurtamohler** [comment]
The single-core performance of the ATen implementation of remainder is a bit slower than it was in TH:

dtype | num_elements | th time | aten time | cpu_aten_speedup
-- | -- | -- | -- | --
torch.float32 | 1000 | 0.0000404 | 0.000045 | 0.8977777778
torch.float32 | 10000 | 0.0001216 | 0.0002138 | 0.5687558466
torch.float32 | 100000 | 0.0009386 | 0.001894 | 0.4955649419
torch.float32 | 1000000 | 0.0102662 | 0.020459 | 0.5017938316
torch.float32 | 10000000 | 0.1067806 | 0.2163726 | 0.4935033364
torch.float64 | 1000 | 0.0000462 | 0.000062 | 0.7451612903
torch.float64 | 10000 | 0.0001254 | 0.0003942 | 0.3181126332
torch.float64 | 100000 | 0.0008038 | 0.0037252 | 0.2157736497
torch.float64 | 1000000 | 0.0078996 | 0.0390346 | 0.2023743038
torch.float64 | 10000000 | 0.1048736 | 0.3988242 | 0.262956962
torch.int32 | 1000 | 0.0000456 | 0.0000978 | 0.4662576687
torch.int32 | 10000 | 0.0001824 | 0.000755 | 0.241589404
torch.int32 | 100000 | 0.0015858 | 0.0073278 | 0.2164087448
torch.int32 | 1000000 | 0.0150388 | 0.0732916 | 0.205191318
torch.int32 | 10000000 | 0.1661234 | 0.7425 | 0.2237352189
torch.int64 | 1000 | 0.0000424 | 0.0000932 | 0.4549356223
torch.int64 | 10000 | 0.0001238 | 0.0007162 | 0.1728567439
torch.int64 | 100000 | 0.0010318 | 0.0069764 | 0.1478986297
torch.int64 | 1000000 | 0.0085434 | 0.0704638 | 0.1212452351
torch.int64 | 10000000 | 0.1148014 | 0.7106772 | 0.1615380372

This performance decrease must be coming from how the `cpu_kernel()` dispatcher function works, rather than what I put inside of it. The reason I believe that is because the performance of `torch.div` is very close to my `torch.remainder` implementation when using integer types. I copied everything about `torch.div`, except for the actual per-element operation code, so it makes sense that div and remainder would have the same performance for integer types because an integer division and an integer mod operation should use the same exact cpu instruction.

So it seems that there is probably something within `cpu_kernel()` that could be changed to improve single-core performance. But that's outside of the scope of this issue. I could potentially speed things up by avoiding using `cpu_kernel()` and use some other dispatching mechanism, but I feel like staying consistent with the other methods in `BinaryOpsKernel.cpp` is a better idea.

**Comment by ezyang** [comment]
OK, see you on the PR.

**Comment by nikitaved** [comment]
Are complex numbers implemented as the Gaussian numbers? If so, then [this](http://fermatslasttheorem.blogspot.com/2005/06/division-algorithm-for-gaussian.html) could help.

**Comment by nikitaved** [comment]
> So after some more searching and thinking, I haven't found any convincing definition of a remainder or mod function for complex numbers. With real numbers, the remainder is defined as `mod(a, b) = a - b * floor(a / b)`. The `floor(a / b)` basically means "the integer number of times you can subtract `b` from a without going negative", or "the integer number that you can multiply `b` by to get the closest value below or equal to `a`". Then the remainder is just the distance away from `a` after you multiply `b` by `floor(a / b)`.
> 
> Translating this idea into the complex space doesn't really make any sense to me. If `a` and `b` are complex, then what is `floor(a / b)`? There's not really a concept of an "integer" complex number (there are gaussian integers, but I don't think that's really the same thing), and there's not really an absolute concept of "less than/greater than" or "positive/negative" complex numbers. But yet Wolfram has a definition of a remainder for complex numbers, so maybe I'm wrong. Let me know if anyone here can shed any light.
> 
> For now, I'll just remove the complex remainder. Would anyone even want to use it anyway?

Are the complex numbers for this method supposed to be implemented as Gaussian Integers? If so, then this could help. It assumes the abs norm defined as |a+ib| = sqrt(a^2 + b^2), a,b in Z and makes sure that y=kx+r with |r| < |x|. Did not check for correctness however... If they are not represented as Gaussian Integers, then the remainder is always 0.

**Comment by kurtamohler** [comment]
Maybe a new issue should be created for complex remainder. But here's what I'm thinking at the moment.

> Are the complex numbers for this method supposed to be implemented as Gaussian Integers?

> Or, maybe, we could define floor for complex numbers using their polar representation?

I'm lacking the math knowledge to know the answers, but I have some more questions. If we have a choice between two different methods, which would both give different results, maybe we shouldn't just pick one. Are there only two choices, or are there many possible algorithms that could fit the description "the remainder of a complex integer division"? If so, then maybe we shouldn't implement it. Is there any reason someone would want to calculate a complex remainder using our arbitrarily-chosen method out of many other possible methods?

Would anyone want to calculate a complex remainder at all?

**Comment by nikitaved** [comment]
@kurtamohler, the mathematical perspective is like this. If you have a complex number defined as a polinomial x = a + i *b, the question is what are these a, b are? Are they reals? Are they Integers? If you restrict them to integers, then the reminder and the division result have to be represented as a pair of Integers, otherwise reals would do. 
If, on the other hand, both (a,b) are always reals, then the argument with polar representation does make sense. 

The issue is how you define the remainder and over which set. Because I can say that any real number is divided by non-zero real, hence the reminder is always zero. But it is not the case if you strictly define the remainder to be this and that for reals.

**Comment by kurtamohler** [comment]
Thanks for all the details @nikitaved ! I think this discussion should be continued in #34266
