### ISSUE TITLE
Migrate `sort` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24770]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by fmassa** [comment]
For information, we already have topk and kth_value ported to ATen in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Sorting.cpp

Also, I wonder if this task shouldn't be tackled via a generalization of TensorIterator that takes a vector and returns a vector, instead of taking a number and returning a number?

**Comment by nikitaved** [comment]
It looks like topk and kth_value indeed do not utilize TensorIterator. I am thinking about fixing that.
