### ISSUE TITLE
[FR] More consistent matrix norm for torch.norm

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#24802]
`torch.norm` currently have the following inconsistent behavior where for matrix inputs and `ord` is a numerical value, **vector** norm is computed instead:
```
            =====  ============================  ==========================
            ord    matrix norm                   vector norm
            =====  ============================  ==========================
            None   Frobenius norm                2-norm
            'fro'  Frobenius norm                --
            'nuc'  nuclear norm                  --
            Other  as vec norm when dim is None  sum(abs(x)**ord)**(1./ord)
            =====  ============================  ==========================
```
(Even though the last row reads `when dim is None`, same behavior happens when `dim` is a 2-tuple).

However, the matrix Lpq norms are useful. And users are justified in expecting that `mat.norm(2)` computes the L2 norm (max e-value) since `mat.norm('fro')` computes the matrix Frobenius norm. If we follow the [NumPy interface](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html), the following behavior should be less surprising and error prune:

```

    =====  ============================  ==========================
    ord    norm for matrices             norm for vectors
    =====  ============================  ==========================
    None   Frobenius norm                2-norm
    'fro'  Frobenius norm                --
    'nuc'  nuclear norm                  --
    inf    max(sum(abs(x), axis=1))      max(abs(x))
    -inf   min(sum(abs(x), axis=1))      min(abs(x))
    0      --                            sum(x != 0)
    1      max(sum(abs(x), axis=0))      as below
    -1     min(sum(abs(x), axis=0))      as below
    2      2-norm (largest sing. value)  as below
    -2     smallest singular value       as below
    other  --                            sum(abs(x)**ord)**(1./ord)
    =====  ============================  ==========================
```

cc @ezyang @gchanan @zou3519 @SsnL @vishwakftw @jianyuh

**Comment by vadimkantorov** [comment]
Related about the spectral matrix norm: https://github.com/pytorch/pytorch/issues/12760

**Comment by vishwakftw** [comment]
How does NumPy handle batching?

**Comment by vishwakftw** [comment]
So, I did some trials and this is what I found:
- If inputs are 2-D and axis is not specified, then the input is considered to be a matrix
- If inputs are 2-D and an axis is specified, then the input is considered to be a batch of vectors whose corresponding norms are output
- If inputs are > 2-D, then an axis argument is mandatory when `ord` is not `None`. Furthermore, you will have to provide one axis for vector inputs, and 2 axes for matrix inputs.

**Comment by ezyang** [comment]
It does seem like this may merit a BC-breaking change. Some things we should check before doing so: (1) when was this consistency introduced, (2) is the inconsistent behavior tested for in our test suite, or is this actually totally untested.

This seems like a case where we can easily give a deprecation warning, since the forward compatible way of batching (specify an axis explicitly) works today,

**Comment by VitalyFedyunin** [comment]
We need to separate 'needs discussion' label from the triage process.

**Comment by ailzhang** [comment]
Any objections if we fix the documentation first for 1.3? Now it says we give matrix norm in some cases, which is not true. 
We can change it later with a bc-breaking change to match numpy behavior.

**Comment by kurtamohler** [comment]
@ailzhang , are you still planning on doing this? If not, I would be happy to take over.

**Comment by ailzhang** [comment]
Hey @kurtamohler , feel free to take it over! Please let us know if you need any help! Thanks!

**Comment by kurtamohler** [comment]
Cool, thanks!

**Comment by kurtamohler** [comment]
I don't fully understand what numpy's norm is supposed to do when `ord=2` in the matrix norm case. The documentation says `2-norm (largest sing. value)`, which is unclear to me. "largest sing. value" would seem to just mean `max(x, axis=(0,1))`, but that's not the result I get:
```
>>> numpy.linalg.norm(numpy.array([[1,2,3],[4,5,6]]), ord=2, axis=(0,1))
9.50803200069572
```

**Comment by vishwakftw** [comment]
Largest singular value is the largest value of the diagonal elements of S, where X = USV^{T} (SVD).

**Comment by kurtamohler** [comment]
Got it, thanks @vishwakftw!

**Comment by kurtamohler** [comment]
I think I might need to introduce a new function `at::matrix_norm`. At first, my approach was just to change `at::norm` to calculate a matrix norm if `dim.size() == 2`. But the problem is that `at::frobenius_norm` calls `at::norm`, expecting it to act like a vector norm even if `dim.size() > 1`.

An alternative solution could be to add an optional bool argument to `at::norm` to allow the caller to force the vector norm to be used, no mater what `dim.size()` is, but to me it seems less confusing to just make a new function. If anyone sees an issue with that, please let me know!

**Comment by ailzhang** [comment]
cc: @mruberry here: do we have some preferred way to handle this change? Thanks!

**Comment by mruberry** [comment]
In the near-ish future we'll have torch.linalg.norm analogous to NumPy's numpy.linalg.norm (https://numpy.org/doc/1.18/reference/generated/numpy.linalg.norm.html?highlight=norm#numpy.linalg.norm) and want to deprecate this function. Once we have torch.linalg.norm like that, would you still want to add a separate function?

**Comment by vadimkantorov** [comment]
on side note: will all other linear algebra functions like lu, qr, eig, svd, solvers, cholesky etc be moved in linalg? (like they are in numpy)

**Comment by kurtamohler** [comment]
@mruberry, the separate function would only be in the C++ `at` namespace. I'm still planning on keeping everything within the Python `torch.norm` function so it has the same interface as `numpy.linalg.norm`. The decision whether or not to add an `at::matrix_norm` function should not affect the plan to move `torch.norm` to `torch.linalg.norm`.

**Comment by mruberry** [comment]
> on side note: will all other linear algebra functions like lu, qr, eig, svd, solvers, cholesky etc be moved in linalg? (like they are in numpy / scipy)

Yes. We're going for naming consistency.

**Comment by vadimkantorov** [comment]
Are instance methods going to disappear as well? It's going to be a bit strange to have `tensor.norm(...)` that is synonym `torch.linalg.norm(...)`. Are fft functions are also getting moved to `fft` namespace? I have mixed feelings, PyTorch API is more concise :)

**Comment by mruberry** [comment]
Yes. fft functions are also being moved to the fft namespace. No, we don't plan to add a namespace to methods on torch.Tensor.

**Comment by kurtamohler** [comment]
I have a working implementation, but some other tests are failing. Currently working on fixing them.

**Comment by kurtamohler** [comment]
Most of the failures I've seen in `test_torch.py` so far are related to `torch.dist`, which calls `at::norm` underneath. Similar to the `at::frobenius_norm` issue, I had to flatten the input to `at::norm` so that the vector norm would be used, which fixed almost everything. But now I'm seeing one remaining error in `test_torch.py` because a 1-dim vector norm, as opposed to an 2-dim vector norm, seems to introduces a little more precision error in this case. In other words, reducing the 2 dimensions separately gives a more precise result than flattening to 1 dimension and then reducing.
```
$ python test/test_torch.py TestTorchDeviceTypeCUDA.test_triangular_solve_batched_cuda_float64
F
======================================================================
FAIL: test_triangular_solve_batched_cuda_float64 (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/kurtamohler/development/pytorch-matrix-norm/torch/testing/_internal/common_utils.py", line 769, in wrapper
    method(*args, **kwargs)
  File "/work/kurtamohler/development/pytorch-matrix-norm/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
    result = test(self, device_arg, dtype)
  File "/work/kurtamohler/development/pytorch-matrix-norm/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/work/kurtamohler/development/pytorch-matrix-norm/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test/test_torch.py", line 10156, in test_triangular_solve_batched
    triangular_solve_batch_helper((batchsize, 5, 5), (batchsize, 5, 10),
  File "test/test_torch.py", line 10153, in triangular_solve_batch_helper
    self.assertLessEqual(b.dist(torch.matmul(A, x_act)), 3e-12)  # Correctness check
AssertionError: tensor(5.0628e-12, device='cuda:0', dtype=torch.float64) not less than or equal to 3e-12
```

The difference is still fairly minimal, 5.0628e-12 vs 3e-12. So would it be acceptable for me to just increase the correctness threshold in this test to 6e-12, or should we re-enable a way to calculate n-dim vector norms in `at::norm`? If we want to enable n-dim vector norms, then I'll likely have to create the `at::matrix_norm` function I mentioned before.

**Comment by kurtamohler** [comment]
Does anyone have any thoughts on my previous comment? To me, it seems like it would be best if I create the `at::matrix_norm` function. That way, `at::norm` can retain its original behavior, we will have less precision error in `torch.dist`, and `at::norm` callers won't have the extra overhead of flattening to 1-d when they want to calculate a vector norm for an n-d tensor.

**Comment by vadimkantorov** [comment]
> Yes. fft functions are also being moved to the fft namespace. No, we don't plan to add a namespace to methods on torch.Tensor.

One other thing to note is that splitting functions in namespaces may create discrepancy between Python functions and TorchCpp functions (which is not end of the world, so maybe not a big problem)

**Comment by ezyang** [comment]
@kurtamohler I'm not sure I have a good answer for you. Precision in reductions has always been a sensitive matter; for example, look at https://github.com/pytorch/pytorch/pull/39516 where we added a tree based sum for floats to reduce numerical stability. The more numerically stable the reduction is, the better.

That being said, it seems like the old "two reductions" strategy seems like it only accidentally is more precise, e.g., you could come up with dimension sizes where it is no benefit. And one could maybe apply the same technique as #39516 to get back numerical stability. The counterpoint, however, is that maybe users EXPECT a 2-dim vector norm to have numerics similar to what would happen if you did one reduction first, then another reduction.

cc @peterbell10 if you have any comments

**Comment by peterbell10** [comment]
I have checked and reduced dimensions can already be coalesced by `TensorIterator`. So, e.g. a `dim=None` reduction over a contiguous tensor would do a single large reduction anyway and thus be less accurate than successive reductions over each dim. So, from that perspective I think this is an issue.

I would add that `flatten`ing could add a fair bit of overhead. Having a C++ function which always does vector norm would probably be better from that point of view.

**Comment by kurtamohler** [comment]
I've created the `norm_matrix` function, but right now it's callable from Python with `torch.norm_matrix`. I'd like to disable that somehow, and only have it callable from `torch._VF`. I added the function schema in `native_functions.yaml`, is there a simple way for me to disable it from generating `torch.norm_matrix`? Or do I need to remove it from `native_functions.yaml` and then manually make it available in `torch._VF`?

**Comment by ailzhang** [comment]
@kurtamohler I think https://github.com/pytorch/pytorch/blob/master/tools/autograd/gen_python_functions.py#L53 might be helpful to stop exposing it in python

**Comment by kurtamohler** [comment]
> @kurtamohler I think https://github.com/pytorch/pytorch/blob/master/tools/autograd/gen_python_functions.py#L53 might be helpful to stop exposing it in python

That does remove `torch.norm_matrix`, but it also removes `torch._VF.norm_matrix`.

**Comment by kurtamohler** [comment]
Ok I did some experimenting. Removing `norm_matrix` from `python_torch_methods.cpp` while keeping it in `python_variable_methods.cpp` ends up removing `torch.norm_matrix` like I wanted, but it also removes `torch._VF.norm_matrix` and it's still callable from a Tensor object, like `torch.rand(2,2).norm_matrix()`. So it seems like I will need to remove `norm_matrix` completely from autogen, but I'll need to somehow make it available to be called from `torch.functional.norm`. Although, if accomplishing that is going to be a problem, we could consider just letting `norm_matrix` be callable from Python, just like `frobenius_norm` and `nuclear_norm` are.

**Comment by ezyang** [comment]
Can't you just put a leading underscore on the name?

**Comment by kurtamohler** [comment]
The above commit accomplishes the main goals of this issue, adding matrix norm, and making `torch.norm`'s interface consistent with numpy. I've added tests to cover the changed behavior.

There are a few things I still have to do: create backward formula for matrix norm, update jit for `torch.norm`, and fix any call sites of `torch.norm`

**Comment by kurtamohler** [comment]
@nikitaved suggested that I try using an iterative approximation of the largest and smallest eigenvalues when `matrix_norm` is called with `p = 2`, rather than my current implementation which unnecessarily calculates every eigenvalue with SVD. With Nik's help, and after learning a bit more linear algebra, I wrote a proof-of-concept script to calculate these approximations for a range of matrix sizes and measure the average relative error of the approximation with respect to `torch.svd()`'s output. The script also performs the same experiment with `torch.linalg.norm`, also calculating relative errors with respect to `torch.svd()`. Here's the script: https://github.com/kurtamohler/pytorch-perf-test-scripts/blob/master/matrix-norm/approx_matrix_2_norm.py

Here are my error measurements:
```
norm_method: Custom power iteration with 20 iterations
input_mat_size, num_power_iters, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 1, 0.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 20, 0.003551+/-0.010526, 0.004238+/-0.010306
(10, 100), 20, 0.003675+/-0.010524, 0.005366+/-0.011072
(25, 100), 20, 0.003551+/-0.010705, 0.006823+/-0.011533
(50, 100), 20, 0.002584+/-0.009173, 0.008246+/-0.011727
(75, 100), 20, 0.001489+/-0.007720, 0.008855+/-0.011634
(100, 100), 20, 0.082762+/-2.306321, 0.009587+/-0.011537
(100, 75), 20, 0.001409+/-0.007336, 0.008830+/-0.011568
(100, 50), 20, 0.002652+/-0.009674, 0.008188+/-0.011711
(100, 25), 20, 0.003707+/-0.010962, 0.006787+/-0.011480
(100, 10), 20, 0.003829+/-0.010687, 0.005386+/-0.011016
(100, 5), 20, 0.003605+/-0.010303, 0.004366+/-0.010697
(100, 1), 1, 0.000000+/-0.000000, 0.000000+/-0.000000

norm_method: Custom power iteration with 1000 iterations
input_mat_size, num_power_iters, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 1, 0.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 1000, 0.000000+/-0.000000, 0.000000+/-0.000000
(10, 100), 1000, 0.000000+/-0.000000, 0.000000+/-0.000000
(25, 100), 1000, 0.000003+/-0.000028, 0.000000+/-0.000000
(50, 100), 1000, 0.000000+/-0.000000, 0.000000+/-0.000000
(75, 100), 1000, 0.000001+/-0.000001, 0.000000+/-0.000000
(100, 100), 1000, 0.082079+/-0.674274, 0.000000+/-0.000000
(100, 75), 1000, 0.000001+/-0.000001, 0.000000+/-0.000000
(100, 50), 1000, 0.000000+/-0.000000, 0.000000+/-0.000000
(100, 25), 1000, 0.000000+/-0.000001, 0.000000+/-0.000000
(100, 10), 1000, 0.000000+/-0.000000, 0.000000+/-0.000000
(100, 5), 1000, 0.000000+/-0.000000, 0.000000+/-0.000000
(100, 1), 1, 0.000000+/-0.000000, 0.000000+/-0.000000

norm_method: numpy.linalg.norm
input_mat_size, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 0.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 0.000000+/-0.000000, 0.000000+/-0.000000
(10, 100), 0.000000+/-0.000000, 0.000000+/-0.000000
(25, 100), 0.000000+/-0.000001, 0.000000+/-0.000000
(50, 100), 0.000000+/-0.000000, 0.000000+/-0.000000
(75, 100), 0.000000+/-0.000001, 0.000000+/-0.000000
(100, 100), 0.000046+/-0.000754, 0.000000+/-0.000000
(100, 75), 0.000000+/-0.000001, 0.000000+/-0.000000
(100, 50), 0.000000+/-0.000000, 0.000000+/-0.000000
(100, 25), 0.000000+/-0.000001, 0.000000+/-0.000000
(100, 10), 0.000000+/-0.000000, 0.000000+/-0.000000
(100, 5), 0.000000+/-0.000000, 0.000000+/-0.000000
(100, 1), 0.000000+/-0.000000, 0.000000+/-0.000000
```

First of all, `numpy.linalg.norm` is more accurate than both power iterations I tried. I also compared `numpy.linalg.norm` to `numpy.linalg.svd`, and they matched exactly for all input sizes. That led me to suspect that `numpy.linalg.norm` just calls `numpy.linalg.svd`, and indeed it does: https://github.com/numpy/numpy/blob/19f91f3935069229bbc23bbda4294c36957901a5/numpy/linalg/linalg.py#L2355

Looking at the power iteration's accuracy, it doesn't look especially great. Typically it's off by 1-2% with 20 iterations. One important outlier, though, is that when the matrix is square, the smallest eigenvalue approximation is considerably inaccurate, with a relative error of about 8 +/- 230% at 20 iterations. That's pretty terrible. Perhaps there's a way to fix that special case.

I did try simply running the approximation for more iterations and got much better accuracy. At 1000 iterations, almost all the errors effectively disappear, aside from the case of the smallest eigenvalue of a square matrix.

It's worth noting that my power iteration algorithm could be improved with an adaptive number of iterations. The amount of change per iteration could be tracked, and once it's less than some small threshold, the iteration could stop.

The whole point of doing the power iteration is to gain performance over SVD. But without actually implementing the power iteration in C++, I can't really measure the performance. I don't know, for instance, if 1000 power iterations will take longer than SVD, because at the moment, I don't know how SVD is implemented (I'll skim over the code to see if I can get and understanding of its perf characteristics).

In any case, I think I should prioritize finishing up the functionality changes to `torch.norm`. Performance improvements could be addressed with a second PR.

**Comment by nikitaved** [comment]
@kurtamohler , could you please also compare against the power method implemented for the Spectral Normalization? In the paper they operate on the right and the left sides of a rectangular matrix, without "squaring" it by multiplying with A or A^T. So, I would speculate that the power method on a matrix after the "squaring" process should be faster if the largest singular value > 1 (although it really depends more on the gap between the largest and the second largest singular value).

**Comment by kurtamohler** [comment]
@nikitaved , unfortunately, it seems like the `torch.nn.utils.spectral_norm` method actually calculates `A / largest_eigenvalue(A)`. Maybe there's a function exposed to `at::` that will just calculate the eigenvalue, but it doesn't seem to be exposed to Python, as far as I can tell. So I had to calculate `A / spectral_norm(A)` to get the eigenvalue back out. This will introduce some amount of error.

```
def approx_spectral_largest(a, iters: int, method: str):
    class MyModule(torch.nn.Module):
        def __init__(self, weight):
            super(MyModule, self).__init__()
            self.weight = torch.nn.Parameter(weight)
    
        def forward(self):
            return self.weight
    
    b = torch.nn.utils.spectral_norm(
        MyModule(a),
        n_power_iterations=iters)()
    
    if method == 'median':
        return (a / b).median()
    elif method == 'mean':
        return (a / b).mean()
    else:
        raise RuntimeError('method "%s" not available' % method)
```

It seemed like `(a / b).median()` would give a more stable result than mean, but I chose to just see what happens with both. Unfortunately, I don't think `spectral_norm` offers any simple way of generating the smallest eigenvalue. I could use the same trick I did before--run it on `a.inverse()`, and then invert the result--but as far as I understand, one of the reasons for your suggestion to use `spectral_norm` is that we'd like to avoid using `torch.inverse()` because we want to find something more stable.

Anyway, I updated my script to compare the largest eigenvalue given by `torch.svd()` to approximation calculated with `spectral_norm`. Here's what I get:

```
norm_method: spectral_norm_mean with 20 power iters
input_mat_size, num_power_iters, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 1, 1.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 20, 1.000000+/-0.000000, 0.004382+/-0.010909
(10, 100), 20, 1.000000+/-0.000000, 0.004943+/-0.010852
(25, 100), 20, 1.000000+/-0.000000, 0.006596+/-0.011450
(50, 100), 20, 1.000000+/-0.000000, 0.007680+/-0.010872
(75, 100), 20, 1.000000+/-0.000000, nan+/-nan
(100, 100), 20, 1.000000+/-0.000000, nan+/-nan
(100, 75), 20, 1.000000+/-0.000000, nan+/-nan
(100, 50), 20, 1.000000+/-0.000000, 0.007666+/-0.011079
(100, 25), 20, 1.000000+/-0.000000, nan+/-nan
(100, 10), 20, 1.000000+/-0.000000, 0.005632+/-0.011497
(100, 5), 20, 1.000000+/-0.000000, 0.004194+/-0.009806
(100, 1), 1, 1.000000+/-0.000000, 0.000000+/-0.000000

norm_method: spectral_norm_median with 20 power iters
input_mat_size, num_power_iters, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 1, 1.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 20, 1.000000+/-0.000000, 0.004430+/-0.011574
(10, 100), 20, 1.000000+/-0.000000, 0.005337+/-0.011300
(25, 100), 20, 1.000000+/-0.000000, 0.006165+/-0.011069
(50, 100), 20, 1.000000+/-0.000000, 0.007965+/-0.011132
(75, 100), 20, 1.000000+/-0.000000, 0.008640+/-0.010371
(100, 100), 20, 1.000000+/-0.000000, 0.009096+/-0.010769
(100, 75), 20, 1.000000+/-0.000000, 0.008996+/-0.011594
(100, 50), 20, 1.000000+/-0.000000, 0.007649+/-0.011365
(100, 25), 20, 1.000000+/-0.000000, 0.006805+/-0.011834
(100, 10), 20, 1.000000+/-0.000000, 0.005269+/-0.011231
(100, 5), 20, 1.000000+/-0.000000, 0.004419+/-0.010279
(100, 1), 1, 1.000000+/-0.000000, 0.000000+/-0.000000

norm_method: spectral_norm_mean with 100 power iters
input_mat_size, num_power_iters, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 1, 1.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 100, 1.000000+/-0.000000, 0.000042+/-0.000456
(10, 100), 100, 1.000000+/-0.000000, 0.000081+/-0.000668
(25, 100), 100, 1.000000+/-0.000000, 0.000161+/-0.000933
(50, 100), 100, 1.000000+/-0.000000, 0.000138+/-0.000836
(75, 100), 100, 1.000000+/-0.000000, nan+/-nan
(100, 100), 100, 1.000000+/-0.000000, 0.000351+/-0.001577
(100, 75), 100, 1.000000+/-0.000000, 0.000293+/-0.001414
(100, 50), 100, 1.000000+/-0.000000, 0.000253+/-0.001272
(100, 25), 100, 1.000000+/-0.000000, 0.000143+/-0.001031
(100, 10), 100, 1.000000+/-0.000000, nan+/-nan
(100, 5), 100, 1.000000+/-0.000000, 0.000087+/-0.000839
(100, 1), 1, 1.000000+/-0.000000, 0.000000+/-0.000000

norm_method: spectral_norm_median with 100 power iters
input_mat_size, num_power_iters, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 1, 1.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 100, 1.000000+/-0.000000, 0.000044+/-0.000444
(10, 100), 100, 1.000000+/-0.000000, 0.000109+/-0.001012
(25, 100), 100, 1.000000+/-0.000000, 0.000140+/-0.000906
(50, 100), 100, 1.000000+/-0.000000, 0.000241+/-0.001447
(75, 100), 100, 1.000000+/-0.000000, 0.000238+/-0.001229
(100, 100), 100, 1.000000+/-0.000000, 0.000267+/-0.001272
(100, 75), 100, 1.000000+/-0.000000, 0.000224+/-0.001295
(100, 50), 100, 1.000000+/-0.000000, 0.000204+/-0.001156
(100, 25), 100, 1.000000+/-0.000000, 0.000160+/-0.001028
(100, 10), 100, 1.000000+/-0.000000, 0.000078+/-0.000658
(100, 5), 100, 1.000000+/-0.000000, 0.000092+/-0.000961
(100, 1), 1, 1.000000+/-0.000000, 0.000000+/-0.000000
```

The median turned out to behave better. This is because the division operation I used can sometimes be a division by zero, and those NaN results make the mean become NaN as well.

This `spectral_norm` method seems to have pretty similar accuracy to the power iteration that I implemented. However, as I mentioned, since I have to calculate the eigenvalue from `A / spectral_norm(A)`, I'm introducing extra error than might be possible if I could access `spectral_norm`'s internal approximation of the eigenvalue.

**Comment by nikitaved** [comment]
@kurtamohler, the power method from Spectral Normalization does the following:
```
u_k = A u_k / ||A u_k||_2
v_k = A^T v_k / ||A^T v_k||_2
return ||A||_2 approximated by v_k^T A u_k
```
So you can use your code to test the stability.
It also makes sense to actually try matrices with different spectra.

Maybe, it is easier for now just to implement these things with SVD?

P.S. inverse might not work because the matrix might have very poor condition number. It makes sense to stick to SVD for the smallest value imo...

**Comment by kurtamohler** [comment]
@nikitaved , how does spectral normalization handle non-square matrices though? If `u_1` is size(n) and A is size(m, n), then the first `A u_k` multiply will result in `u_2` size(m). After that, `u_3` couldn't be calculated.

So I assume you'd have to obtain a square matrix from A somehow. One method would be `A_gram = A^T A`. But `A_gram == A_gram^T`, so if we input `A_gram` into the algorithm you posted, `u_k` and `v_k` would eventually converge to the same vector.

**Comment by nikitaved** [comment]
See that the two sequences operate over A and A^T. They are trying to compute the leading right and left singular vectors.

**Comment by kurtamohler** [comment]
I still don't understand how this can be done for a non-square matrix. `u_{k+1} = A u_k / ||A u_k||_2` can only be calculated for one iteration because after that, `u_k.size() == A.size()[0]`, and you can't right-multiply an m-by-n matrix with an m-element vector if `m != n`.

**Comment by vishwakftw** [comment]
The procedure is: u_{k + 1} = A_{gram} u_{k} / ||A_{gram} u_{k}||_{2} and v_{k+1} = A A^{T} v_{k} / ||A A^{T} v_[k}||_{2}. Note that A_{gram} != A A^{T}

**Comment by nikitaved** [comment]
@kurtamohler , you are right! I have noticed that I made a mistake, confused `v_k+1` and `u_k+1`.

**Comment by nikitaved** [comment]
@vishwakftw , this is the method that @kurtamohler  already implemented. The the spectral normalization method for GANs does not compute "squaring". See https://arxiv.org/abs/1802.05957

**Comment by kurtamohler** [comment]
@nikitaved , ah I see, `u_k` and `v_k` are just swapped every iteration. I've implemented it like this:

```
def approx_spectral_largest_custom(a, iters: int):
    a_t = a.transpose(-1, -2) 
    u = torch.rand(a.size()[-1])
    u /= u.norm()
    v = torch.rand(a_t.size()[-1])
    v /= v.norm()
    
    for _ in range(iters):
        v_new = a.matmul(u)
        v_new /= v_new.norm()
        u_new = a_t.matmul(v)
        u_new /= u_new.norm()
        v = v_new
        u = u_new

    return v.matmul(a).matmul(u).abs()
```

But that seems to give worse results than any of the other methods I've tried so far. Even with 100 iterations, the error is around 10% +/-20%.

```
norm_method: spectral_custom with 100 iters
input_mat_size, num_power_iters, smallest_eigenvalue_relative_error_mean+/-std, largest_eigenvalue_relative_error_mean+/-std
(1, 100), 1, 1.000000+/-0.000000, 0.000000+/-0.000000
(5, 100), 100, 1.000000+/-0.000000, 0.029276+/-0.124689
(10, 100), 100, 1.000000+/-0.000000, 0.027529+/-0.108172
(25, 100), 100, 1.000000+/-0.000000, 0.054939+/-0.160119
(50, 100), 100, 1.000000+/-0.000000, 0.078416+/-0.185919
(75, 100), 100, 1.000000+/-0.000000, 0.092660+/-0.205146
(100, 100), 100, 1.000000+/-0.000000, 0.105025+/-0.210512
(100, 75), 100, 1.000000+/-0.000000, 0.098235+/-0.208307
(100, 50), 100, 1.000000+/-0.000000, 0.075219+/-0.178002
(100, 25), 100, 1.000000+/-0.000000, 0.056817+/-0.163138
(100, 10), 100, 1.000000+/-0.000000, 0.036192+/-0.132674
(100, 5), 100, 1.000000+/-0.000000, 0.023488+/-0.099956
(100, 1), 1, 1.000000+/-0.000000, 0.000000+/-0.000000
```

**Comment by nikitaved** [comment]
Cool, it exactly in accordance to my claim, as "squaring" squares singular values, hence has a potential for better convergence.

**Comment by vadimkantorov** [comment]
I propose to migrate "spectral normalization" method into torch matrix_norm and have `algorithm` argument to specify if fast and approximate solution is expected. Then spectral normalization can use torch.matrix_norm under the hood

**Comment by nikitaved** [comment]
Makes sense, but I think it is better to leave spectral normalization as is. It avoids the matrix matrix multiply at the cost of slower convergence, but it is faster and cheaper the way it is..

**Comment by vadimkantorov** [comment]
This behavior can also be desirable for similar scenarios. Or do you mean that if it's factored out of spectral normalization, it would have to do those matrix multiplies?

**Comment by nikitaved** [comment]
Yep, you kind of expect norm to give high quality results I guess... And for GANs it is speed then the quality of norm I presume. Actually, it makes sense to contact the authors and ask whether they tried better approximations...

**Comment by vadimkantorov** [comment]
Fast inaccurate estimate may still be useful in other contexts too. But yes, it maybe requires some explicit choice of algorithm or some flag to enable it...

**Comment by kurtamohler** [comment]
I'm opening this back up because there are a few more features that I need to add, which we decided should be separate from the main PR #42749:

- Add `dtype` arg support to nuclear and frobenius norm
- Add named tensor support in matrix norm
- Simplify frobenius and nuclear norm implementations by making the non-out variants call the out variant.
- Use out variants of functions called from `linalg_norm_out_impl`
- Add `axis`-->`dim` argument alias
- Add integer type support for `dim`/`axis` argument

**Comment by mruberry** [comment]
> * Add `axis`-->`dim` argument alias

Do we not get this for free from the arg parser?

**Comment by kurtamohler** [comment]
Oh you're right! I thought I had tried that out before and it didn't work, but evidently I was wrong:
```
>>> torch.linalg.norm(torch.randn(10, 10), axis=(0,))
tensor([1.8172, 5.7318, 3.8068, 4.4812, 3.1311, 4.0102, 3.0276, 2.8259, 1.9159,
        2.1431])
```

**Comment by kurtamohler** [comment]
Closing because the issue's request has been fulfilled. I will open new issues/PRs for the few remaining tasks:

* Add dtype arg support to nuclear and frobenius norm
* Add named tensor support in matrix norm
* Use out variants of functions called from linalg_norm_out_impl
