### ISSUE TITLE
[features] broadcast version of torch.gather

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#2480]
Wondering if someone can add broadcast support to `torch.gather` which would broadcast the `index` matrix to the same size as `input`.
I can work around by repeat input in a new dimension but the speed is limited.

**Comment by gchanan** [comment]
I don't think we should support this; the issue is that so far we broadcast shapes to a unique valid shape for the operation, but there is not a unique valid index shape for gather (the size of the specified dim can be any value -- some implementations might enforce an upper bound, I'm not sure).  Consider if you wanted the index to be of size 1 in the specified dimension where the source wasn't of size 1 -- how would you specify that you didn't want to expand that dimension vs that you did?

I'm sure we could define rules for all of this (https://github.com/gchanan/pytorch/wiki/Broadcasting-Notes has some thoughts), but I don't think it's worth it.
