### ISSUE TITLE
Feature request: nn.View

### ISSUE THREAD

**Issue by kefirski** [pytorch/pytorch#2486]
Is there any ability to add layer `View` identical to Tensor.view in order to do something like this

```
self.conv = nn.Sequential(
    nn.Conv2d(1, 3, kernel_size=5, stride=2, padding=2),
    ...
    Various Conv Layers
    ...
    
    nn.View(-1, conv_out_size)
    nn.Linear(conv_out_size, out_size)        
)
```

**Comment by vabh** [comment]
You define a module like this:
```
class View(nn.Module):
       def __init__(self):
            super(View, self).__init__()
   
        def forward(self, x):
            return x.view(-1) 
```

This flattens the input but similarly you could provide a size object.

**Comment by soumith** [comment]
as noted in https://discuss.pytorch.org/t/non-legacy-view-module/131 and https://discuss.pytorch.org/t/what-is-reshape-layer-in-pytorch/1110/3
This was an explicit choice to not provide an `nn.View` and instead encourage users to write `forward` functions. `nn.Sequential` was reluctantly provided as well.

**Comment by Serhiy-Shekhovtsov** [comment]
> and instead encourage users to write forward functions

And what is the point of this encourage? To help users improve their typing skills?

**Comment by soumith** [comment]
@Serhiy-Shekhovtsov improving users' typing skills was not the motivation

**Comment by Serhiy-Shekhovtsov** [comment]
Honestly, the motivation is not clear to me. Making transformation in `forward` function will break the model into pieces and will make code little bit more messy.
On the other hand, having it as a step or a layer will make the whole model look linear, straightforward and elegant. So, anyone who wants to keep his code clean and beautiful will spend some time to google and to copy\paste something similar to what @vabh have put.

**Comment by maximecb** [comment]
In agreement with @Serhiy-Shekhovtsov. I think `nn.Sequential` makes a lot of sense for sequential transformations, and not having a view/reshape layer just makes the code less well organized, harder to follow.

**Comment by dashesy** [comment]
Also asked [here](https://github.com/pytorch/vision/issues/720).  
I wanted to take some `torchvision.models` and break them into featurizer + extra layers, but because there is a reshape required before FC layer I will have to know that for example this is [torchvision.models.resnet34](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L207) that does a reshape in its forward layer. The abstraction breaks.
If there was a `nn.View` module and used instead in `resnet34`,`resnet34` could avoid implementing `forward` and breaking it would have been as simple as taking `net._modules`.

```python
class FCView(nn.Module):
    def __init__(self):
        super(FCView, self).__init__()

    # noinspection PyMethodMayBeStatic
    def forward(self, x):
        n_b = x.data.size(0)
        x = x.view(n_b, -1)
        return x

    def __repr__(self):
        return 'view(nB, -1)'

class ResNet(nn.Sequential):
   def __init__():
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fcv = nn.FCView()
        self.fc = nn.Linear(512 * block.expansion, num_classes)

```
No need to implement `forward`. Of course `resnet34` is just an example.
