### ISSUE TITLE
Missing libfoxi

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#24988]
## 🐛 Bug

```
ERROR: missing input file '@torch_repo//:torch/lib/libfoxi.so'
ERROR: /home/sidney/.cache/bazel/_bazel_sidney/b5c90ed864441a50c6f7542613715de8/external/torch_repo/BUILD.bazel:47:1: @torch_repo//:rpath-torch_lib_libfoxi.so: missing input file '@torch_repo//:torch/lib/libfoxi.so'
ERROR: /home/sidney/.cache/bazel/_bazel_sidney/b5c90ed864441a50c6f7542613715de8/external/torch_repo/BUILD.bazel:47:1 1 input file(s) do not exist
```
Is libfoxi perhaps moved somewhere else?

## To Reproduce
I built from this diff on Pytorch master:

1efdf57aa7bc9f085c8d7ae569e0463d9463c8d5

**Comment by suo** [comment]
@houseroad, if you have a sec, can you take a look?

**Comment by sidazhang** [comment]
After I built, it seems like libfoxi is not there in torch/lib

```
torch/lib/libtbb.so
torch/lib/libshm.so
torch/lib/libcaffe2_nvrtc.so
torch/lib/libcaffe2_observers.so
torch/lib/libtorch.so
torch/lib/libcaffe2_detectron_ops_gpu.so
torch/lib/libtorch_python.so
torch/lib/libc10_cuda.so
torch/lib/libcaffe2_module_test_dynamic.so
torch/lib/libc10.so

```

**Comment by yxjiang** [comment]
@houseroad, thanks for taking a look!

**Comment by shubhambhokare1** [comment]
Hi @sidazhang ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
