### ISSUE TITLE
weight_norm assertion error when using bias=False and using cuda

### ISSUE THREAD

**Issue by jramapuram** [pytorch/pytorch#2515]
Running python3.6 w/ pytorch0.2:

```python
import torch
import torch.nn as nn
from torch.autograd import Variable


g = nn.GRU(100, 20, bias=False).cuda()
g = nn.utils.weight_norm(g, name='weight_hh_l0')
g = nn.utils.weight_norm(g, name='weight_ih_l0')
g.flatten_parameters()
zero_state = Variable(torch.zeros(1, 32, 20).cuda())

x = Variable(torch.randn(20, 32, 100).cuda())
output, state = g(x, zero_state)
```

```bash
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-15-bacede2d81b6> in <module>()
     11 
     12 x = Variable(torch.randn(20, 32, 100).cuda())
---> 13 output, state = g(x, zero_state)

/home/jason/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    222         for hook in self._forward_pre_hooks.values():
    223             hook(self, input)
--> 224         result = self.forward(*input, **kwargs)
    225         for hook in self._forward_hooks.values():
    226             hook_result = hook(self, input, result)

/home/jason/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
    143         if has_flat_weights:
    144             first_data = next(self.parameters()).data
--> 145             assert first_data.storage().size() == self._param_buf_size
    146             flat_weight = first_data.new().set_(first_data.storage(), 0, torch.Size([self._param_buf_size]))
    147         else:

AssertionError: 
```

**Note**: This works fine when not using cuda, i.e:
```python
import torch
import torch.nn as nn
from torch.autograd import Variable


g = nn.GRU(100, 20, bias=False)
g = nn.utils.weight_norm(g, name='weight_hh_l0')
g = nn.utils.weight_norm(g, name='weight_ih_l0')
g.flatten_parameters()
zero_state = Variable(torch.zeros(1, 32, 20))

x = Variable(torch.randn(20, 32, 100))
output, state = g(x, zero_state)
```

**Comment by ngimel** [comment]
One of corner cases for #2179, it thinks the module still has flat weights, whereas after weight norm it no longer does.

**Comment by jramapuram** [comment]
@ngimel : Doesn't explain why it works without cuda though.  i.e note `bias=True` below:

```python
import torch
import torch.nn as nn
from torch.autograd import Variable


g = nn.GRU(100, 20, bias=True)
g = nn.utils.weight_norm(g, name='weight_hh_l0')
g = nn.utils.weight_norm(g, name='weight_ih_l0')
g.flatten_parameters()
zero_state = Variable(torch.zeros(1, 32, 20))

x = Variable(torch.randn(20, 32, 100))
output, state = g(x, zero_state)
```

**Comment by Smerity** [comment]
This issue is the same issue as raised in https://github.com/pytorch/pytorch/issues/2343 and is due to the way in which RNNs now flatten their weights. This also breaks code for the [weight dropped LSTM](https://github.com/salesforce/awd-lstm-lm/blob/master/weight_drop.py).

I realized that weight norm would have the same issue so searched hoping for an elegant solution, but alas :)

I've fixed it by setting `rnn.flatten_parameters = lambda *args, **kwargs: None`, which results in a warning (below) but otherwise running code. You could (and others have) converted the RNN to CUDA early but that would break other parts of my code. Killing the `flatten_parameters` function seems the most consistently backward compatible option.

`UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().`
(Just realized the error has a typo in "greatly" but oh well ;))

@apaszke, have you got any insights as to a more elegant solution either temporarily or longer form? I know `flatten_parameters` is already a complicated and low level beast.

**Comment by ngimel** [comment]
@Smerity, in your case I think you can use in-place dropout (or use raw_w.mul_(...) in this line https://github.com/salesforce/awd-lstm-lm/blob/master/weight_drop.py#L29)

**Comment by Smerity** [comment]
Thanks for the suggestion @ngimel. Unfortunately I can't actually use in place dropout or multiplication there as I'd be destroying the original weight matrix (`raw_w`) that must remain unmodified. Luckily weight drop is only called once per forward+backward which is then run over multiple timesteps.

Regardless, I'm more focused on finding a clean fix for this broader `flatten_parameters` issue :)

**Comment by apaszke** [comment]
I have a proposal for a more robust for for the `flatten_parameters` issue [here](https://gist.github.com/apaszke/8959cf0eaf468eaeb2f9e9b84c81ea69). We're gathering feedback and will hopefully get to the implementation sometime soon

**Comment by PetrochukM** [comment]
Checking back in:

```
import torch
import torch.nn as nn

g = nn.GRU(100, 20, bias=False).cuda()
g = nn.utils.weight_norm(g, name='weight_hh_l0')
g = nn.utils.weight_norm(g, name='weight_ih_l0')
g.flatten_parameters()

x = torch.randn(20, 32, 100).cuda()
output, state = g(x)
```

Trace:
```
Traceback (most recent call last):
  File "abc.py", line 10, in <module>
    output, state = g(x)
  File "/home/michaelp/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michaelp/.local/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 173, in forward
    assert first_data.storage().size() == self._param_buf_size
AssertionError
```

Tried to get rid of ``flatten_parameters`` but I quickly run out of memory:
```RuntimeError: CUDA error: out of memory```

**Comment by soumith** [comment]
hopefully this issue is fixed via https://github.com/pytorch/pytorch/commit/461dc9a28b132f032e1ae81bfdab27e9d3770fe9 as well.

**Comment by soumith** [comment]
I verified that it is indeed fixed on master
