### ISSUE TITLE
exponential_() samples infinity on GPU

### ISSUE THREAD

**Issue by hyqneuron** [pytorch/pytorch#2561]
`torch.Tensor(100000000).exponential_().max()` usually gives around 19+-2
`torch.Tensor(100000000).cuda().exponential_().max()` usually gives inf

On GPU, about 3 out of 100 million samples is greater than 30. When it's greater than 30, it's always inf. I'm on 0.2 but I think I observed this in 0.1 also.

**Comment by colesbury** [comment]
The CUDA exponential generator uses:
`(-1/lambda) * log(1 - curand_uniform())`

https://github.com/pytorch/pytorch/blob/0f65c9267d5ec55584b0ec65acb5374c95af9c16/torch/lib/THC/THCTensorRandom.cu#L139

curand_uniform() can return between 0.0 (exclusive) and 1.0 (inclusive). I'm not sure why we don't use:
`(-1/lambda) * log(curand_uniform())`

It seems like that would avoid the inf problem.

The CPU generator is much less likely to hit this issue because it uses double-precision random numbers and only truncates to single-precision at the end.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/2947
