### ISSUE TITLE
pytorch version is 1.3?????

### ISSUE THREAD

**Issue by zhjw0927** [pytorch/pytorch#25756]
Today, I suddenly found torch version is 1.3.
I build torch 1.2 from source, but don't know how to auto update.

![image](https://user-images.githubusercontent.com/42128459/64406141-a22b9780-d0b3-11e9-8456-60a1d7111d3e.png)
Who can explain it ?
Thank you very much!

**Comment by peterjc123** [comment]
Well, since the master branch is newer than the v1.2.0 branch, it's fine to assign the version as 1.3.0. As for your second question, there's no way to do automatical update, but you can try out the nightlies.

**Comment by zhjw0927** [comment]
Thank you to explain for me. I seem to understand something, but don’t understand a little. 
If build from source, master update and my  torch will also update?
What do you mean by not automatically updating?
And last question: what's nightlies? 
Thanks again!

**Comment by peterjc123** [comment]
If you do `python setup.py install`, then it will override your old version. But I'd suggest you remove the old one first. Nightlies are binaries generated every night, you can download them through https://pytorch.org/ by selecting `Preview` instead of `Stable`. Auto-update is mentioned by you first, in my context, it means it will prompt up something when you import torch, telling you that we have a new version. Apparently, there isn't a thing like this for PyTorch.

**Comment by zhjw0927** [comment]
Thank you explain it for me again.
I know it, and  also know what is nightlies .
This is the first time I heard it.
Thank you very much!
