### ISSUE TITLE
[jit] Implement `in` for list and tuple

### ISSUE THREAD

**Issue by Godricly** [pytorch/pytorch#25758]
## 🐛 Bug
The *in* operator is bond to Dict when I tried to use it on List or Tuple typle.  I can bypass this with a for loop. But I think this one still should be reported.

## To Reproduce
uncomment to see the bug
```python
import torch
from typing import Dict, Tuple, List

@torch.jit.script
def foo(v: Dict[int, int], k: int):
    if k in v:
        return True
    else:
        return False

# @torch.jit.script
# def foo1(v:List[int], k: int):
#     if k in v:
#         return True
#     else:
#         return False

# @torch.jit.script
# def foo2(v:Tuple[int], k: int):
#     if k in v:
#         return True
#     else:
#         return False


def python(v, k):
    if k in v:
        return True
    else:
        return False

if __name__ == "__main__":
    a = [1,2,3,4,5,6]
    b = 3
    print(python(a,b))
```
## Expected behavior
```
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following operator variants are available:
  
  aten::__contains__(Dict(str, t) dict, str key) -> (bool):
  Could not match type Tuple[int] to Dict[str, t] in argument 'dict': Cannot match a dict to Tuple[int].
  
  aten::__contains__(Dict(int, t) dict, int key) -> (bool):
  Could not match type Tuple[int] to Dict[int, t] in argument 'dict': Cannot match a dict to Tuple[int].
  
  aten::__contains__(Dict(float, t) dict, float key) -> (bool):
  Could not match type Tuple[int] to Dict[float, t] in argument 'dict': Cannot match a dict to Tuple[int].
  
  aten::__contains__(Dict(Tensor, t) dict, Tensor key) -> (bool):
  Could not match type Tuple[int] to Dict[Tensor, t] in argument 'dict': Cannot match a dict to Tuple[int].

The original call is:
at slice.py:20:7
@torch.jit.script
def foo2(v:Tuple[int], k: int):
    if k in v:
       ~~~~~~ <--- HERE
        return True
    else:
        return False
```
## Environment
Collecting environment information...
PyTorch version: 1.3.0.dev20190905
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.0
[pip3] torch==1.3.0.dev20190905
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

cc @suo

**Comment by driazati** [comment]
Thanks for the report! `in` isn't implemented for all types. A complete solution is complicated since we don't have a way to check the equality of all value types yet, but #25796 adds support for `in` on basic types of lists.

Also to clarify, `List[int]` refers to a list that contains any number of elements, all of which are type `int`. Tuples in TorchScript are fixed size and can have different element types, so `Tuple[int]` refers to a tuple that has a single element of type `int`. You can read more about it [here](https://pytorch.org/docs/master/jit.html#supported-type).

**Comment by Godricly** [comment]
Oops， my mistake for the tuple case. But that one is still strange when trying to handle it as a dict.

**Comment by wconstab** [comment]
This appears to have been fixed by a previous change.  I'm able to run the following snippet with a recent pytorch build.  Please reopen if there is still an issue.

`import torch
from typing import Dict, Tuple, List

@torch.jit.script
def foo(v: Dict[int, int], k: int):
    if k in v:
        return True
    else:
        return False

@torch.jit.script
def foo1(v:List[int], k: int):
    if k in v:
        return True
    else:
        return False

@torch.jit.script
def foo2(v:Tuple[int, int, int], k: int):
    if k in v:
        return True
    else:
        return False

def python(v, k):
    if k in v:
        return True
    else:
        return False

if __name__ == "__main__":
    print(python([1,2,3], 3))
    print(foo({1:1, 2:2, 3:3}, 3))
    print(foo1([1,2,3], 3))
    print(foo2((1,2,3), 3))`
