### ISSUE TITLE
[jit] Missing source highlight error

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#25801]
```
@torch.jit.script
def fn(x):
    # type: (List[int], int) -> bool
    return max(x)
```

cc @suo

**Comment by tanmay1618** [comment]
I would like to work on this issue. Can someone give me some context or let me know how to start?

**Comment by driazati** [comment]
RIght now the output is like
```

**Comment by PyExtreme** [comment]
Hi @driazati , I am looking forward to contribute to PyTorch. Is it still an open issue?

**Comment by hi-ogawa** [comment]
Hi @driazati, I was looking  around the code of pytorch jit mechanism.
I found that this "type annotation comment" parsing is currently done in a separate parser independent from whole source as in:

https://github.com/pytorch/pytorch/blob/6a4ca9abec1c18184635881c08628737c8ed2497/torch/csrc/jit/script/init.cpp#L878-L881

That's why `SourceRange` (`type_annotation_decl.range()`) passed to `ErrorReport` here

https://github.com/pytorch/pytorch/blob/6a4ca9abec1c18184635881c08628737c8ed2497/torch/csrc/jit/script/parser.cpp#L12-L28

doesn't include source location information as a part of whole source.

I can think of two ways to approach this problem though.

One quick way to "fix" this is to use `throw ErrorReport(decl.range())` instead of `throw ErrorReport(type_annotation_decl.range())`, which would work like this:

```
=== Example code ( __scratch__/example.py) ==

import torch
def f1(x):
    # type: (int, int) -> None
    pass
torch.jit.script(f1)



=== Error message ==

RuntimeError: 
Number of type annotations (2) did not match the number of function parameters (1):
at __scratch__/example.py:2:0
def f1(x):
~~~~~~~~ <--- HERE
    # type: (int, int) -> None
    pass
```

Second way is to properly handle `SourceRange` for `type_annotation_decl`, which, I think, requires to implement a better version of `parse_type_comment` or some way to inject proper `SourceRange` into `Decl` afterward. A bit complicated part is that "type annotation comment" extraction is currently handled in python code (`torch.jit.annotations.get_type_line`)

https://github.com/pytorch/pytorch/blob/6a4ca9abec1c18184635881c08628737c8ed2497/torch/jit/annotations.py#L137

which doesn't concern with SourceRange concept used in cpp-part of parser/lexer.


Anyways, if you guys are fine with the first way of fixing this, then I can make PR. But if more proper fix is desired, I might not be able to work on this.
Please let me know how you think. Thanks.

Btw, reading pytorch source is so interesting, thank you very much for such a great code base.

**Comment by driazati** [comment]
I think 1 and 2 are pretty similar, but I'm slightly partial to 2 since it's saying what was expected (the function parameters) vs what is actually there (the type annotations), and highlighting the actual part. But since they're so similar I think it's fine to do 1, especially since that change is so simple.

Go ahead and make the PR (and add a test for it! see `test_jit.py`)
