### ISSUE TITLE
Provide a way to select SVD algorithm in PyTorch?

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#25978]
PyTorch seems to use `gesdd` for singular value decomposition. Alternative `gesvd` is slower, but more accurate/robust. PyTorch could follow scipy syntax and provide a way to choose between them using `lapack_driver` kwarg

Some background on gesvd vs gesdd
https://epubs.siam.org/doi/10.1137/17M1117732
https://savannah.gnu.org/bugs/?55564

```
import numpy as np
import torch, scipy
fn = "pinv2_crash.txt"
if not os.path.exists(fn):
  import urllib.request
  url="https://s3.amazonaws.com/yaroslavvb2/data/"+fn
  response = urllib.request.urlopen(url)
  body = response.read()
  print("Read %d bytes"%(len(body),))
  open(fn, "wb").write(body)

mat = np.genfromtxt(fn, delimiter= ",").astype(np.float32)
scipy.linalg.svd(mat, lapack_driver="gesdd")  # crashes
torch.svd(torch.tensor(mat))  # crashes
scipy.linalg.svd(mat, lapack_driver="gesvd")  # works
```

**Comment by yaroslavvb** [comment]
On second thought, this problem can also be fixed by manually regularizing the matrix. The specialized case of needing accurate estimates of small eigenvalues is going to be quite slow either way, and can be done through scipy
@vishwakftw

**Comment by fmassa** [comment]
If we add support for selecting the underlying algorithm, I think having `lapack_driver` for the argument could be misleading as a name, given that we only use lapack for the CPU backend.

**Comment by yaroslavvb** [comment]
Maybe `driver`? But also, `gesdd` is a lapack naming convention, so `lapack_driver` keyword implies that argument has to correspond to a name of lapack driver routine 
https://icl.cs.utk.edu/projectsfiles/magma/doxygen/routines.html#driver

JAX scipy wrapper accepts that keyword (but ignores it) https://jax.readthedocs.io/en/latest/_modules/jax/scipy/linalg.html

**Comment by pearu** [comment]
Should `svd` also handle the specialized SVD algorithms such as for truncated or partial SVD (see #8049)? The corresponding algorithms would introduce algorithm-specific parameters to `svd`.

So, instead of `driver`, perhaps the different algorithms could be selected using `algorithm` keyword argument that may contain also driver-specific information (`lapack_gesvd`, etc) as well as of the assumptions on the input tensor (general, symmetric, etc. tensors) for which different decompositions (eigenval, schur, etc) may give SVD result more efficiently.
