### ISSUE TITLE
Make what RPC module wants to expose clearer

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#27229]
This is to summarize maintability requests from #26919, #26997.

I think rpc should create a folder like `distributed/autograd` does
Maintain the names want to be exposed to users in `torch/distributed/rpc/__init__.py`.
Do the actual implmentation in `torch/distributed/rpc/rpc_api.py`.

Also, do not use `from "something" import *`, as descirebd in https://docs.quantifiedcode.com/python-anti-patterns/maintainability/from_module_import_all_used.html, it's not clear what has been imported to current module.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma

**Comment by rohan-varma** [comment]
Looks like the specific steps would be:

1. Figure out our external facing APIs
2. Instead of importing everything like we currently do with code such as `from x import *`, import only what is required into `__init__.py`.
3. in `__init__.py`, define an `__all__` that exports everything that is our public facing API

**Comment by pietern** [comment]
I put up a stack for this at #27290. Will rebase after #25499 is merged.

It's not everything yet, but at least moves all RPC related code to `torch.distributed.rpc`.

**Comment by pietern** [comment]
I think the only thing remaining is before we can close this issue is an `__all__` in `__init__.py`.

**Comment by mrshenli** [comment]
closing as this is has been addressed
