### ISSUE TITLE
[jit] `index_put_` on a tensor slice with the element type does not work

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#27493]
This works in eager mode

```python
# this works
def fn(x):
    a = zeros_like(x, dtype=torch.uint8)
    a[torch.tensor(0)] = torch.tensor(2)
    return a

# this works
def fn(x):
    a = zeros_like(x, dtype=torch.uint8)
    a[0] = 2
    return a

# this  doesn't work
def fn(x):
    a = zeros_like(x, dtype=torch.uint8)
    a[torch.tensor(0)] = 2
    return a

x = torch.jit.script(fn)
```

cc @suo

**Comment by eellison** [comment]
This is another python_torch_functions error

**Comment by suo** [comment]
Closing as this issue is tracked in https://github.com/pytorch/pytorch/issues/30788

**Comment by eellison** [comment]
To support this, I would look at the python behavior in `python_variable_indexing.cpp` and the C++ behavior in `TensorIndexing.cpp` and first understand what happens in python with `a[torch.tensor(0)] = 2`. 

Then, I would look through https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/frontend/ir_emitter.cpp#L2019 and see how the current JIT compilation fails. 
Two options for fixes are:
- update the ir_emitter file
- add a declaration forr `_set_item` in [this file](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/frontend/builtin_functions.cpp) that does the correct conversion so that `a[torch.tensor(0)] = 2` compiles
