### ISSUE TITLE
torch.nn.transformer.py missing .pyi.in file.

### ISSUE THREAD

**Issue by yyb1995** [pytorch/pytorch#27842]
## 🚀 Feature
`transformer.py` in [https://github.com/pytorch/pytorch/tree/master/torch/nn/modules](https://github.com/pytorch/pytorch/tree/master/torch/nn/modules) lacks `transformer.pyi.in` file, resulting in no code hints in PyCharm. I have no idea how to generate such one.

## Pitch

Add the missing `transformer.pyi.in` file.

## Additional context

cc @ezyang

**Comment by ezyang** [comment]
@yyb1995 You don't need an `.in` file, the problem is just you need to add type stubs in `transformer.pyi`. Check out mypy docs like https://github.com/python/mypy/wiki/Creating-Stubs-For-Python-Modules for info how to do it (we've also got plenty of examples you can work off of.) Tag me on a PR if you make one.

**Comment by yyb1995** [comment]
OK, I will try to generate one asap. Thanks for your suggestion.
