### ISSUE TITLE
How to speed up installing pytorch1.3?

### ISSUE THREAD

**Issue by PingHGao** [pytorch/pytorch#28066]
I am installing pytorch1.3 using pip. The command from the official site is `pip3 install torch===1.3.0 torchvision===0.4.1 -f https://download.pytorch.org/whl/torch_stable.html`.
![pytorch](https://user-images.githubusercontent.com/19465753/66896730-02551800-f028-11e9-8301-42856ef44589.png)
My pip are using a mirror source which is fast for me. But the `-f https://download.pytorch.org/whl/torch_stable.html` part in the commad force pip to download things from the official site, which is slow for me. 
**So my question is how to replace the `-f site` part to speed it up using mirror sites?**
Thanks for help!

**Comment by peterjc123** [comment]
It is actually impossible because the switch `-f` only points to the index, which doesn't contain the actual files. So as a mirror, he should download this file, extract links from it, download those files, upload them and then regenerate the index file, which is quite complex. The better idea may be to set up a CDN, which hosts files on multiple servers to accelerate the download speed.
@soumith Do you think that it is possible to set up a CDN for the files in `download.pytorch.org`?

**Comment by peterjc123** [comment]
The issue is somehow related to https://github.com/pytorch/pytorch/issues/990.

**Comment by PingHGao** [comment]
It is the same problem, but #990 can be solved by setting pip or conda source to the right mirrors. But this command using `-f site` making the solution above useless. So I think this should be a new problem and really need help. @peterjc123

**Comment by peterjc123** [comment]
@PingHGao Could you please open a new issue at https://github.com/tuna/issues/issues? Actually, https://github.com/tuna/issues/issues/363 is not resolved. Only anaconda and pypi packages are hosted.

**Comment by PingHGao** [comment]
OK, with pleasure^_^

**Comment by soumith** [comment]
download.pytorch.org is already on Amazon CloudFront CDN.

**Comment by peterjc123** [comment]
Okay, maybe the connection speed from China to the CloudFront servers are not good enough.
