### ISSUE TITLE
Implement destructor for ProcessGroupAgent that cleans up resources and doesn't wait

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#28126]
## 🚀 Feature
This blocks #26336 from landing, since we need to be able to force a worker to exit without having to `join` and wait for the other workers. If we currently do this, then we get an exception:

`terminate called without an active exception`, since the process group agent did not join it's joinable thread. One idea is to implement a destructor that cleans up everything without waiting, as per @pritamdamania87 's suggestion.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pietern** [comment]
@rohan-varma The underlying problem is that the recv-from-any is not interruptible.

Instead of hacking around this it should be addressed at the root. Detaching a thread means we'll invariably run into cleanup issues later on (either with the operation unblocking and accessing bad memory, or with zombie processes, or...). I created https://github.com/facebookincubator/gloo/issues/227 to track.

**Comment by rohan-varma** [comment]
Agreed, this is a much better way to solve the problem.
