### ISSUE TITLE
The reporitory is mislabeled: The master git label v1.0rc0-8021-g56eb4f7daa doesn't match the latest release v1.3.0

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#28336]
```git describe --tags``` on the master branch says that it is a release candidate for the version ```1.0```: ```v1.0rc0-8021-g56eb4f7daa```, but the releases page lists ```1.3.0``` as the latest release.

**Comment by pietern** [comment]
Stable releases are cut from master and then continue to receive commits. This is why they are separate from the master lineage and why the tags for stable releases are not in the master history. 

@soumith Can we remove this tag entirely?

**Comment by soumith** [comment]
i have no idea how to fix this. if anyone has an idea I'm happy to run the relevant command

**Comment by yurivict** [comment]
Easy: just make a release from the master branch - problem solved.

**Comment by pietern** [comment]
OK, turns out this is not as easy as removing a tag. Earlier PyTorch versions were all tagged off of master without cutting a release branch. This means we can remove `v1.0rc0` but then `git describe --tags` will return `v0.1.11`.

We can do a few different things (elaborating for posterity):
* Nothing. It's not the end of the world if this is not accurate.
* Add a new empty commit on top of all previous releases and re-tag. The result being that no tag can describe master (and we assume future releases are always tagged on a branch different from master).
* Start tagging on master so that `git describe` on new commits shows something other than `v1.0rc0`. Tags are supposed to be immutable, so we'd need a new tag every once in a while (perhaps date based).
* Tag the last commit before the release branch was cut as `vX.Y.Zrc0`, so that `git describe` for all commits on master shows after which release a commit was introduced.

Also cc @ezyang.

How commits would be described for all of our tags today:

```
$ git tag -l | sort -V | xargs -n1 -I% -t git describe --tags %^
git describe --tags v0.1.1^ 
fatal: No tags can describe 'ee838422f72a644b8f2746e15889a07e6a979d9f'.
Try --always, or create some tags.
git describe --tags v0.1.2^ 
v0.1.1-18-ga2a840df93
git describe --tags v0.1.3^ 
v0.1.2-103-ga0a2d9885a
git describe --tags v0.1.4^ 
v0.1.3-187-gb555588f5d
git describe --tags v0.1.5^ 
v0.1.4-381-g7a837b7a14
git describe --tags v0.1.6^ 
v0.1.5-468-g30d208010c
git describe --tags v0.1.7^ 
v0.1.6-32-g2ad967dbe4
git describe --tags v0.1.8^ 
v0.1.7-122-g833b8cbc7a
git describe --tags v0.1.9^ 
v0.1.8-69-gdd844f741b
git describe --tags v0.1.10^ 
v0.1.9-205-g60736bdf99
git describe --tags v0.1.11^ 
v0.1.10-141-g5c79046d39
git describe --tags v0.1.12^ 
v0.1.11-225-g3cc21b5a46
git describe --tags v0.2.0^ 
v0.1.11-1267-gdf44c571c6
git describe --tags v0.3.0^ 
v0.1.11-2465-g1645546aa9
git describe --tags v0.3.1^ 
v0.3.0-95-g902d57be9f
git describe --tags v0.4.1^ 
v0.1.11-9386-gf08f222db3
git describe --tags v1.0rc0^ 
v0.1.11-10789-g696498d9e4
git describe --tags v1.0rc1^ 
v0.1.11-10789-g696498d9e4
git describe --tags v1.0.0^ 
v1.0rc0-1458-g524574ab73
git describe --tags v1.0.1^ 
v1.0.0-96-g48fcfdaccb
git describe --tags v1.1.0^ 
v1.0rc0-3983-ge39ab6632f
git describe --tags v1.2.0^ 
v1.0rc0-5925-g64069120e4
git describe --tags v1.3.0^ 
v1.0rc0-7574-g92c6401bb9
```

**Comment by ezyang** [comment]
Because we cut release branches, there will never be an accurate release signifier. I suggest (3). When we rev version numbers on master, we should also add a tag like `v1.4.0.dev0` just saying when development on 1.4.0 started. This will give you accurate info to correlate with nightlies, which is what I think the issue author here actually cares about

**Comment by pietern** [comment]
I like that idea @ezyang. I went and found the most recent series of version bumps:

* `1.0.0a0` -- 73738ec570fa907045e89dd573d2fd945aa2585c (#11717)
* `1.1.0a0` -- 4c5b1cc02601ae5bcc00cefa592874139f4e22c2 (#15554)
* `1.2.0a0` -- 47043220ee3f532ab01a265336ef78d18f6b6645 (#20812)
* `1.3.0a0` -- a1d945b295d367ec32c889de5d2e74dbf8ab9479 (#23895)
* `1.4.0a0` -- 2c51e0659b79dce39b27efb9d5e6755524eeb21c (#27374)

Therefore, we can simply tag those commits as `v<VERSION>` and be done. Then for future version bumps, we need to make sure we tag accordingly post-bump.

@ezyang Do you want to stick to `v1.4.0.dev0` or use the version from `version.txt` verbatim?

I just checked and can push these tags when ready.

**Comment by ezyang** [comment]
Use the version.txt verbatim, whatever it is :>

**Comment by pietern** [comment]
Pushed tags for above commits:

```
$ git push origin v1.{0,1,2,3,4}.0a0
Total 0 (delta 0), reused 0 (delta 0)
To github.com:pytorch/pytorch
 * [new tag]               v1.0.0a0 -> v1.0.0a0
 * [new tag]               v1.1.0a0 -> v1.1.0a0
 * [new tag]               v1.2.0a0 -> v1.2.0a0
 * [new tag]               v1.3.0a0 -> v1.3.0a0
 * [new tag]               v1.4.0a0 -> v1.4.0a0
```

Confirmed that `git describe` now returns something more sensible on master:

```
$ git describe --tags
v1.4.0a0-43-gb9b9fd4fad
```

**Comment by ezyang** [comment]
@pietern we need to add info to add these tags to a release checklist somewhere so we don't forget in the future

**Comment by pietern** [comment]
@ezyang +1 --  do we have one currently?

**Comment by ezyang** [comment]
Not that I'm aware of. cc @soumith @kostmo @mingbowan
