### ISSUE TITLE
Boolean tensor transpose bug in 1.3.0

### ISSUE THREAD

**Issue by DaDaMrX** [pytorch/pytorch#28502]
## 🐛 Bug

There is problem when use a transpose a boolean tensor. It seems like that it hasn't been transposed.

## To Reproduce

```python
import torch

a = torch.tensor([[True,  True],
                  [False, True]])
print(a.t() == 0)
```

I got

```
tensor([[False, False],
        [ True, False]])
```

## Expected behavior

```
tensor([[False, True],
        [False, False]])
```

However, when I try an int tensor, it doesn't happen.

## Environment

pytorch 1.3.0

cc @ezyang @gchanan @zou3519 @jerryzh168 @izdeby

**Comment by albanD** [comment]
Hi,

As a temporary workaround, you can use boolean:
`print(a.t() == False)` will work as expected.

We still have a problem as the two following print show the same thing:
```
In [1]: import torch
In [2]: a = torch.randn(3,3).ge(0)
In [3]: a.eq(0)
Out[3]:
tensor([[ True,  True, False],
        [ True,  True, False],
        [False,  True, False]])

In [4]: a.t().eq(0)
Out[4]:
tensor([[ True,  True, False],
        [ True,  True, False],
        [False,  True, False]])
```

**Comment by hi-ogawa** [comment]
Not sure if it helps, but It seems that this generally happens when non-contiguous tensor (e.g. transposed tensor) is type-promoted (e.g. int32 to int64, float32 to float64), for example:

```
[ Example code ]
import torch
print(
    torch.tensor([[1, 0], [1, 1]], dtype=torch.int32).t() == torch.ones(2, 2, dtype=torch.int64),
    torch.tensor([[1, 0], [1, 1]], dtype=torch.float32).t() == torch.ones(2, 2, dtype=torch.float64),
    torch.ones(2, 2, dtype=torch.int64) == torch.tensor([[1, 0], [1, 1]], dtype=torch.int32).t(),
    torch.ones(2, 2, dtype=torch.float64) == torch.tensor([[1, 0], [1, 1]], dtype=torch.float32).t(),
    
    torch.tensor([[1, 0], [1, 1]], dtype=torch.int64).t() == torch.ones(2, 2, dtype=torch.int32),
    torch.tensor([[1, 0], [1, 1]], dtype=torch.float64).t() == torch.ones(2, 2, dtype=torch.float32),
    torch.ones(2, 2, dtype=torch.int32) == torch.tensor([[1, 0], [1, 1]], dtype=torch.int64).t(),
    torch.ones(2, 2, dtype=torch.float32) == torch.tensor([[1, 0], [1, 1]], dtype=torch.float64).t(),
    
    sep='\n\n'
)


[ Output (first 4 examples are incorrect) ]
tensor([[ True, False],
        [ True,  True]])

tensor([[ True, False],
        [ True,  True]])

tensor([[ True, False],
        [ True,  True]])

tensor([[ True, False],
        [ True,  True]])

tensor([[ True,  True],
        [False,  True]])

tensor([[ True,  True],
        [False,  True]])

tensor([[ True,  True],
        [False,  True]])

tensor([[ True,  True],
        [False,  True]])
```

Also while digging into this, it looks like current type-promotion `maybe_promote_common_dtype` (which does `to(dtype)`) makes a contiguous tensor (so "strides" are different from original transposed tensor), but the later manipulation of `op.stride_bytes` (L166) is assuming "strides" are unchanged (which, I think, is incorrect).

https://github.com/pytorch/pytorch/blob/2f1628423192af91e2ead67f4f35051c4d1b9dc9/aten/src/ATen/native/TensorIterator.cpp#L151-L171

Not really tested comprehensively (only tested above simple examples), but I'm thinking/hoping that adding `MemoryFormat::Preserve` to L157 will make it work:

```
op.tensor = op.tensor.to(common_dtype, /* non_blocking */ false, /* copy */ false, MemoryFormat::Preserve);
```

**Comment by albanD** [comment]
As discussed in other reports, this breaks potentially a lot of code, including our own examples.
cc @gchanan

**Comment by zhangguanheng66** [comment]
@gchanan I think it is definitely a very high priority issue. It would be great if we could fix it soon.

**Comment by nairbv** [comment]
I just verified that this will be fixed by: https://github.com/pytorch/pytorch/pull/28253
