### ISSUE TITLE
tensor.FloatTensor(100) and torch.tensor(100, dtype=torch.float) are not equal

### ISSUE THREAD

**Issue by GinSoda** [pytorch/pytorch#28867]
```
tensor.FloatTensor(10)
will give a random 1D tensor
tensor([-6.4422e+21,  4.5737e-41, -6.4422e+21,  4.5737e-41,         nan,
                nan,  0.0000e+00,  0.0000e+00,  6.3850e+24,  3.0777e-41])
while
torch.tensor(10, dtype=torch.float)
will give 
tensor(10.)
```
Is this a legacy issue or a thoughtful design？

**Comment by fmassa** [comment]
`torch.Tensor` (and `FloatTensor`, etc) are legacy constructors.
The reason why they were "deprecated" is because they have a dual functionality: the arguments can either represent the size of a new tensor, or the data we are passing to it.
```python
torch.Tensor(5, 5)  # shape 5, 5
torch.Tensor([5, 5]) # shape 2, with content [5, 5]
```
when we introduced scalars in PyTorch (0-d tensors), there was no way of representing them with `torch.Tensor`. So we followed numpy and created two new constructs, one taking data (`torch.tensor`), and one taking sizes (`torch.empty`).
