### ISSUE TITLE
squeeze dimension after mean / sum

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#289]
Currently,

```python
torch.FloatTensor(3, 4).normal_().sum(0)
```

returns a vector of shape (1, 4), but shouldn't the dimension over which we sum / mean / etc disappear?

**Comment by soumith** [comment]
This seems like an awesome feature to have, but at the same time will break everyone's existing code in various ways.

Considering that, we'll add this for the 0.2 major release.

Broadcasting itself can be added sooner as it doesn't need any thought on backward-compatibility.

We've added the first step to broadcasting by now having expand / expand_as automatically add leading dimensions as needed.

I like the opinion of @jph00 and largely agree with it, but we are putting a lot of thought into backward-compatibility and not breaking existing code.

**Comment by gchanan** [comment]
I've been working on broadcasting, and it probably makes sense to introduce broadcasting and squeeze dimension together (i.e. "Broadcasting itself can be added sooner as it doesn't need any thought on backward-compatibility" isn't quite true).

For example, consider test_nn.test_InstanceNorm1d:
```
        output = IN(input_var)
        
        input_reshaped = input_var.transpose(1, 0).contiguous().view(c, -1)
        mean = input_reshaped.mean(1)

        # do some calculation based on mean.data - IN.running_mean
```

Here, mean.data is (4,1) (because the dimension is not squeezed) and In.running_mean is (4).  The broadcast causes the result of the calculation to be (4,4) instead of (4,1), which changes the calculation (e.g. imagine a sum).  If mean is changed to squeeze the dimension, this calculation "just works" as written.  Clearly there are cases where this won't hold, but it seems like introducing them together may cause less disruption.

**Comment by soumith** [comment]
done via https://github.com/pytorch/pytorch/pull/1563
