### ISSUE TITLE
[feature request] Reinterpret tensor as different dtype

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#29013]
I'd like to read audio file by using a sox utility directly. Currently I can do it as:
```python
signal = torch.from_numpy(np.frombuffer(subprocess.check_output(['sox', '-V0', audio_path, '-b', '16', '-e', 'signed', '--endian', 'little', '-r', str(sample_rate), '-c', '1', '-t', 'raw', '-'], dtype = np.int16))
```

Is there a way to reinterpret a torch byte tensor (or python's `bytearray(...)`) as another type without invoking first NumPy? (or a generic numpy.view(dtype) functionality) If not, I think it'd be quite useful (mainly for integral types, but also maybe for some integer bit-tricks on float32 tensors, which can hopefully be fused by jit)

Also reported in https://discuss.pytorch.org/t/reinterpret-pytorch-array-as-a-different-dtype/24256

This probably can also be helpful for conversions between complex <-> pair or real/imag.

cc @mruberry @rgommers

**Comment by colesbury** [comment]
FWIW, I also have needed to do this. It's difficult to do now and it would be nice to have a function that does this.

Vadim already mentions this above, but the corresponding NumPy function is `ndarray.view`:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.view.html

**Comment by vadimkantorov** [comment]
My current torch-only workaround for now is:
`torch.ShortTensor(torch.ShortStorage.from_buffer(subprocess.check_output(['sox', '-V0', audio_path, '-b', '16', '-e', 'signed', '--endian', 'little', '-r', str(sample_rate), '-c', '1', '-t', 'raw', '-']), byte_order = 'little')`

**Comment by vadimkantorov** [comment]
This can also be useful for casting bool<->uint8 for no-copy casting legacy ByteTensor masks

**Comment by vadimkantorov** [comment]
Found something like this in the wild for removing exactly duplicate matrix rows: https://github.com/PFGimenez/ecf-anomaly-detection/blob/master/ecf/__init__.py#L150

**Comment by mruberry** [comment]
I wonder if @zasdfgbnm's view overload does what you'd like? 

https://pytorch.org/docs/master/generated/torch.Tensor.view.html?highlight=view#torch.Tensor.view

**Comment by vadimkantorov** [comment]
Nope, it has constraint `dtype must have the same number of bytes per element as self’s dtype.`

**Comment by vadimkantorov** [comment]
> Found something like this in the wild for removing exactly duplicate matrix rows: https://github.com/PFGimenez/ecf-anomaly-detection/blob/master/ecf/__init__.py#L150

And for this usecase, NumPy makes use of

**Comment by jakirkham** [comment]
Also interested in this. AIUI the goal would be to recast an existing tensor to a different type as opposed to copying into a new typed tensor (`.view(...)`'s behavior).

**Comment by kurtamohler** [comment]
After some thinking, I'm not too sure about expanding `Tensor.view(dtype)` anymore.

At the moment, `Tensor.view(dtype)` preserves the exact shape of the tensor, which is why it currently requires the dtypes to have the same element size.

```python
>>> torch.ones(5, 2, 1, dtype=torch.float).view(torch.int).size()
torch.Size([5, 2, 1])
```

On the other hand, `torch.view_as_complex()` and `torch.view_as_real()` change the shape of the tensor being casted.

`view_as_complex` requires that the last dimension's size is exactly 2, to indicate real-imaginary pairs. When the pairs are combined, the last dimension is dropped.

```python
>>> torch.view_as_complex(torch.ones(5, 2, 1, dtype=torch.float))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Tensor must have a last dimension of size 2
>>> torch.view_as_complex(torch.ones(5, 2, 2, dtype=torch.float)).size()
torch.Size([5, 2])
```

In the reverse, when `view_as_real` splits the real-imaginary pairs, it adds a new dimension of size 2.

```python
>>> torch.view_as_real(torch.ones(3, 4, dtype=torch.cfloat)).size()
torch.Size([3, 4, 2])
```

Considering these things, I'm not 100% sure what we should do. The sizing requirements and outputs of `Tensor.view(dtype)` and `view_as_real`/`_complex` are different enough that it seems like it would be conceptually confusing to enable `view_as_real`/`_complex` behavior within `Tensor.view(dtype)`. I imagine this might be why they are currently separate functions. Furthermore, if we did expand `Tensor.view(dtype)`, what should the output tensor's shape be for cases where the input and output dtype have different element sizes? Also, what should the input size requirements be in these cases?

Perhaps it would be conceptually simpler to just offer a completely new function (maybe `torch.reinterpret_cast`) that ignores the size of the input completely. The output is just a 1-D tensor and all dtype pairs are supported. The user could just reshape the output as needed. It seems like it should also be possible to add autograd support for the appropriate cases.

One drawback with adding a new function is obviously that we'd have basically two different ways for casting between real-complex dtypes and two different ways for casting between dtypes of equal element size. But I think it might be less confusing than trying to combine conceptually different functionality into `Tensor.view()`.

I guess another question is deciding what should happen when casting non-contiguous tensors. Maybe an error should just be thrown in that case.
