### ISSUE TITLE
Error while updating shared grads

### ISSUE THREAD

**Issue by shiretzet** [pytorch/pytorch#2905]
I followed the example of A3C - [link](https://github.com/ikostrikov/pytorch-a3c), and got an error in this function:
```python
def ensure_shared_grads(model, shared_model):
    for param, shared_param in zip(model.parameters(),
                                   shared_model.parameters()):
        if shared_param.grad is not None:
            return
        shared_param._grad = param.grad
```
ERROR:
```python
...
shared_param._grad = param.grad
RuntimeError: assigned grad has data of a different type
```
Type of shared_param._grad == <class 'NoneType'>
Type of param.grad == <class 'torch.autograd.variable.Variable'>

Why is that?

Thanks

UPDATE : This does not happen on CPU, only CUDA

**Comment by JunhaoWang** [comment]
I have the same problem

**Comment by vergilus** [comment]
I think I figure it out.
there is no grad in global params (None type), the way to solve this problem is to move the local parameters to CPU, then you can assign local parameter. to make life easier, you can wrap this function in the model.
` ensure_shared_grads(model, shared_model)`
becomes
` model.to("cpu").ensure_shared_grads(shared_model)`
but do mind that when you run your model on GPU,  you have to switch it back to the device which it was running for next backward() (in case sometimes model can have "expected GPU but got CPU backend" error)
