### ISSUE TITLE
[BUG] mypy error for TorchScript module

### ISSUE THREAD

**Issue by edgarriba** [pytorch/pytorch#29099]
## 🐛 Bug

I got the following error when I run mypy's type system  in a TorchScript module. To be precise in the forward call.

```bash
Typechecker (mypy)
kornia/color/gray.py:30: error: Signature of "forward" incompatible with supertype "Module"
Makefile:21: recipe for target 'mypy' failed
make: *** [mypy] Error 1
```

## To Reproduce

Check the issue here: https://github.com/kornia/kornia/pull/261

## Expected behavior

I expect that mypy doesn't detect any error during the static analysis for forward methods. Now we hardcoded adding ` # type: ignore` but this make torch script useless.

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py37_cu101    pytorch

## Additional context

We need this to be fixed in order to export kornia functions to onnx 

cc @suo

**Comment by eellison** [comment]
Could you provide a repro ? You might try just adding a `noqa`?

**Comment by t-vi** [comment]
As mentioned on slack, the problem seems to be that subclassing really requires that the signature of the superclass is implemented in the subclass (because one would need to allow passing a subclass instance to a function taking a superclass instance and so the type inference for calling the latter's forward must match what happens with subclass's forward, too).
We don't have that and we cannot really pretend we do, either...

**Comment by artbataev** [comment]
I have the same issue, and I can't find any method to suppress `mypy` error (except suppressing mypy for the whole file in config)
Minimal code to reproduce the issue:
```python
import torch
import torch.jit
import torch.nn as nn


class CustomModule(nn.Module):
    def forward(self, x: torch.Tensor):
        return x * 3.0


if __name__ == "__main__":
    model = torch.jit.script(CustomModule())
    torch.jit.save(model, "model.pt")

```

Pytorch: `ok`
Mypy: `sample.py:7: error: Signature of "forward" incompatible with supertype "Module"  [override]`

I tried to modify code:
```python
class CustomModule(nn.Module):
    def forward(self, x: torch.Tensor):  # type: ignore
        return x * 3.0
```
Mypy: `ok`
Pytorch: `RuntimeError: expected type comment but found 'def' here: def forward(self, x: torch.Tensor):  # type: ignore`

I also tried to use *args and **kwargs
```python
class CustomModule(nn.Module):
    def forward(self, *args: torch.Tensor, **kwargs: torch.Tensor):
        x = args[0]
        return x * 3.0
```
Mypy: `ok`
Pytorch: `ValueError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults`

**Comment by suo** [comment]
Unfortunately, as @t-vi mentioned, PyTorch does not play well with mypy, because the common usage is to override `forward()` in your module with a type signature that will not match the supertype `nn.Module` `forward()` signature.

The easiest workaround at the moment is to disable mypy entirely for the file. Since you are putting the module into TorchScript anyways, you will get type safety since TorchScript is statically typed.

We could also special case `# type: ignore` so that our type parser throws it out but it will still suppress mypy warnings correctly. I'm a little hesitant to do this though, since it would be confusing (users may think that `# type: ignore` disables type checking in TorchScript, which it would not).

**Comment by suo** [comment]
One *other* alternative is to replace the current:
```
    def forward(self, *input: Any, **kwargs: Any) -> T_co: ...  # type: ignore
```
with the more permissive:
```
    forward: Callable[..., T_co]
```
The current signature basically will always fail to type check, because mypy enforces that the subclass method's input types must be "wider" than their superclass method's input types (i.e. they can vary contravariantly). And nothing is wider than `Any`.

This change would ensure mypy doesn't complain to you about `forward()` typing, which resolves the problem nicely. I'll put a PR when I get a sec.

**Comment by artbataev** [comment]
@suo, thank you very much for proposed solution, works perfectly! I can open pull request (with modification of forward and __call__ method annotations), if this is convenient
