### ISSUE TITLE
[C++] Deprecate Tensor.type() (DeprecatedTypeProperties)

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#29161]
`tensor.type()` gives you a DeprecatedTypeProperties object, but we didn't actually deprecate the call.  We should do this ASAP so we can delete DeprecatedTypeProperties.

CC @ezyang.

cc @ezyang @gchanan @zou3519 @jerryzh168 @yf225 @SsnL

**Comment by gchanan** [comment]
See also https://github.com/pytorch/pytorch/pull/25306.

**Comment by ngoldbaum** [comment]
I think I can take this on but don't have the context for why this was deprecated. Is there a suggested alternate API that users should use instead of `Tensor.type()`?

**Comment by ezyang** [comment]
It's a long and windy story but basically people should generally use `Tensor.options()` instead of `type()`. Usual use of `Tensor.type()` is to pass it to a factory function, and options in the new mechanism.

**Comment by ngoldbaum** [comment]
OK, I think I have this sorted more or less (modulo any code review suggestions I get on the pull requests I'll be opening later today) except for one place where I'm not sure how to migrate from `DeprecatedTypeProperties` to `TensorOptions`. Specifically, here:

https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_flatten.cpp#L10-L63

and here (in the same file):

https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_flatten.cpp#L65-L81

The problem is that these routines sort tensors according to the type, either via `DeprecatedTypeProperties.id()` or by sorting on the address of the pointer to the individual `DeprecatedTypeProperties` instances. The latter was a little surprising to discovere but works because the type instances are singletons that live in a global namespace. This is no longer the case for `TensorOptions`.

One way forward would be to define a `type_id()` method that returns a unique integer index and depends only on the layout, dtype, and device type. Is that something that would make sense? Is there something else I should be doing?

**Comment by ezyang** [comment]
Hmm, this is pretty surprising! Here is the reference Python implementation:

```
def _reorder_tensors_as(tensors, ordered_tensors):
    """Assume that tensors are of same order as ordered_tensors within their
    types, e.g., from _take_tensors. Reorder them to be of same order as
    ordered_tensors.

    Arguments:
        tensors (Iterable[Tensor]): tensors to be reordered. They should be of
          the same order as ordered_tensors within their own types.
        ordered_tensors (Iterable[Tensor]): tensors whose order will be the
          reference.

    Returns:
        Ordered tuple of tensors with contents from tensors and order of
        ordered_tensors.
    """
    type_dict = defaultdict(list)
    for tensor in tensors:
        type_dict[tensor.type()].append(tensor)
    type_dict = {t: iter(coll) for t, coll in type_dict.items()}
    return tuple(next(type_dict[tensor.type()]) for tensor in ordered_tensors)
```

I am wondering if you can just use TensorTypeId as the basis for the ordering and maybe that is sufficient.

**Comment by ezyang** [comment]
cc @apaszke

**Comment by ezyang** [comment]
Reading over the use site, it seems that there are only a few concrete tensor types that this code knows how to handle: dense tensors and sparse tensors. So if you make a little struct representing this and make it hashable and comparable, that may also be sufficient.
