### ISSUE TITLE
distribute training with both cpu and gpu

### ISSUE THREAD

**Issue by zlcnju** [pytorch/pytorch#29191]
[code here](https://github.com/kubeflow/pytorch-operator/blob/master/examples/mnist/mnist.py)

The training block in the cluster both cpu and gpu machines exist. And it work well in a cluster all cpu or gpu. So i wonder does pytorch support distribute training in a Heterogeneous cluster where both cpu and gpu exist

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pietern** [comment]
Sure, there is no fundamental limitation to do that. It's uncommon that heterogeneous systems are used for data parallel training though, because the performance imbalance means your better performing hardware will mostly be idle.

Closing the issue, because this is not an issue.

Please direct future questions to the forums at https://discuss.pytorch.org/.
