### ISSUE TITLE
[ONNX] export of AvgPool2d produces no-op Pad node

### ISSUE THREAD

**Issue by louyanyang** [pytorch/pytorch#29282]
model graph include : 
down_1 = F.avg_pool2d(input, (2,2), stride=(2,2))

pytorch -> onnx include:
  %496 : Tensor = onnx::Pad[mode="constant", pads=[0, 0, 0, 0, 0, 0, 0, 0], value=0](%0),
  %497 : Float(1, 3, 256, 512) = onnx::AveragePool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%496)

why arise onnx::Pad ?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by knsong** [comment]
@louyanyang Have you found the answer?

**Comment by ahangchen** [comment]
@knsong @louyanyang 
Onnx opset 11 split pad op from all operators with pad. If you don't need pad actually,  you can set count_include_pad=False to avoid this pad layer:
`x = F.avg_pool2d(input, (2, 2), stride=(2, 2), count_include_pad=False)`

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1563557>

**Comment by louyanyang** [comment]
呵呵，我（娄艳阳）已收到您的信，祝你事事顺心，快乐相随

**Comment by BowenBao** [comment]
Hi @louyanyang @ahangchen @knsong ,

We’ve gone ahead and closed this issue because it has a workaround. This workaround can be found [here](https://github.com/pytorch/pytorch/issues/29282#issuecomment-961716300).
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team

**Comment by louyanyang** [comment]
呵呵，我（娄艳阳）已收到您的信，祝你事事顺心，快乐相随
