### ISSUE TITLE
windows release of pytorch 1.3 is missing several required cuda libraries

### ISSUE THREAD

**Issue by mkatsevVR** [pytorch/pytorch#29356]
## 🐛 Bug

cublas64_100.dll, cusparse64_100.dll and a few others are missing from torch-1.3.0-cp37-cp37m-win_amd64.whl but were included in torch-1.2.0-cp37-cp37m-win_amd64.whl

## To Reproduce

1. `pip3 install torch===1.3.0 torchvision===0.4.1 -f https://download.pytorch.org/whl/torch_stable.html`
1. don't install cuda toolkit separately
1. `import torch`
1. observe `ImportError: DLL load failed: The specified module could not be found`

## Expected behavior

import should not fail

## Environment

 - PyTorch Version (e.g., 1.0): 1.3
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 
 - Any other relevant information:

cc @ezyang @peterjc123

**Comment by peterjc123** [comment]
Thanks for pointing out, we'll fix this issue in 1.3.1.

**Comment by peterjc123** [comment]
Reading the build log, we didn't copy the following DLLs for CUDA 10.1:
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cusparse64_101.dll* 
        0 file(s) copied.
The system cannot find the file specified.
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cublas64_101.dll* 
        0 file(s) copied.
The system cannot find the file specified.
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\curand64_101.dll* 
        0 file(s) copied.
The system cannot find the file specified.
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cufft64_101.dll* 
        0 file(s) copied.
The system cannot find the file specified.
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cufftw64_101.dll* 
        0 file(s) copied.
```

**Comment by peterjc123** [comment]
Well, the suffix of those DLLs is changed to `_10.dll` instead of  `_101.dll`.

**Comment by Yunseong-Jeong** [comment]
Could you check if there is only a cpu? I could be very thankful for that :)

**Comment by peterjc123** [comment]
Waiting for @soumith to upload the binaries.

**Comment by mkatsevVR** [comment]
1.3.1 is out but doesn't appear to be fixed..?

**Comment by peterjc123** [comment]
Yes, looks like @soumith is on a holiday. We have to wait for a while.

**Comment by peterjc123** [comment]
If you want to get the fixed wheels, you can find them here: https://dev.azure.com/peterjc123/_git/pytorch_builder/branches.

**Comment by Rustin333** [comment]
@soumithSent from my Samsung Galaxy smartphone.
-------- Original message --------From: peterjc123 <notifications@github.com> Date: 11/15/19  2:20 AM  (GMT-06:00) To: pytorch/pytorch <pytorch@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [pytorch/pytorch] windows release of pytorch 1.3 is missing several required cuda libraries (#29356) Yes, looks like @soumith is on a holiday. We have to wait for a while.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pytorch/pytorch/issues/29356?email_source=notifications\u0026email_token=AMQUHBJCPQ6YZG7SFFDEBHDQTZLUTA5CNFSM4JKAZ6IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEEVMUI#issuecomment-554260049",
"url": "https://github.com/pytorch/pytorch/issues/29356?email_source=notifications\u0026email_token=AMQUHBJCPQ6YZG7SFFDEBHDQTZLUTA5CNFSM4JKAZ6IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEEVMUI#issuecomment-554260049",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by soumith** [comment]
uploaded fixed wheels. Please uninstall pytorch and reinstall according to the commands on https://pytorch.org
