### ISSUE TITLE
backward_compatibility_check_test doesn't play well with reverts

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#29373]
bc test is broken on master because of this revert commit: https://github.com/pytorch/pytorch/pull/29329

In general, it's ok to break BC if we're reverting a diff. It would be nice if the test knew something about this.

cc @ezyang @houseroad

**Comment by zou3519** [comment]
This pattern happened again today:

The `pytorch_linux_backward_compatibility_check` is currently broken on master. This is because:
1) we merged a PR to add `logical_and`
2) The `logical_add` commit broke master, so we reverted it
3) The backward compatibility check noticed that `logical_and` didn't exist anymore so it started complaining.

(thanks to @albanD for noticing the breakage and pointing it out)

I think these "add a new operator" and then "revert that new operator" workflows are probably going to be relatively common so it would be nice for the BC test to understand these.

**Comment by houseroad** [comment]
If we add a timestamp to each function schema, it's possible to have a buffer window. For now, I would suggest to add these reverted ops to the whitelist to make the CI happy. 

I have created https://github.com/pytorch/pytorch/pull/30537 to fix current breakage in op BC check.

**Comment by huydhn** [comment]
This is a known issue but I think it's minor.  My attempt to fix this https://github.com/pytorch/pytorch/pull/92708 was dropped because of the lack of interest.  So I think we can close this issue.
