### ISSUE TITLE
ATen rebuild process consistently fails to pick up new symbols

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#2952]
Steps to reproduce:

1. Check out 7ff9e0eb6c61855ba9721b3fdfa28c20c527cf4b
2. Do a clean build
3. Fast forward one commit to d5a7e304fa858136eeffa1ebe35e22ed886bf256 (which adds a new THNN implementation)
4. Do an incremental build with `python setup.py build develop`
5. Do `python -c "import torch"`

Expected result: It works
Actual result: It fails with:

```
(/home/ezyang/local/onnx-pytorch/env) [ezyang@devgpu005.ash6 ~/local/benchmark] python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/ezyang/onnx-pytorch/pytorch/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /data/users/ezyang/onnx-pytorch/pytorch/torch/lib/libATen.so.1: undefined symbol: THNN_CudaDoubleVolumetricAdaptiveMaxPooling_updateGradInput
```

Work around is to `rm -rf torch/lib/build` but I would much rather we fix our build system so I don't have to do this.

CC @zdevito @killeent

**Comment by killeent** [comment]
I have run into this a couple times before. I will take a look.

**Comment by zdevito** [comment]
I wouldn't be surprised if CMake cannot track the dependencies correctly because they exist in generated cpp files and refer to header files only which are handled by a completely separate CMake build.

**Comment by apaszke** [comment]
It's not CMake, it's not even ATen. It's just setuptools/distutils that is dumb and doesn't track modifications in files other than those listed in `setup.py` explicitly (even if they are included), and if it finds that once file has to be rebuild it will still rebuild everything. I'd say this is a wontfix. Use `rm -rf build && python setup.py build_deps develop` (note `build_deps` instead of `build` so you don't waste your time). I'd say this is a wontfix, unless you want to spend hours fiddling with setuptools internals.
