### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [pytorch/pytorch#2971]
Hello,

Today I ran into this error:

```RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method```

I saw #1494 and it seems pretty similar except in my case it only happens after a while and is solved by  a reboot.

I run Ubuntu 16.04, the latest version of pytorch from conda.

The code is super simple. I have a function that takes a numpy array and process it with pytorch and return a numpy array. I have multiple inputs so I use `torch.threading.Pool` and map all the inputs with the function. Therefore there is no sharing of tensors between processes.

Does anyone know what might be happening ? Since this is in a process the stack trace is useless.

Thank you

**Comment by apaszke** [comment]
Can you please post a small example that reproduces the problem?

**Comment by Erotemic** [comment]
I'm also seeing this error in 0.4.1

I think I can work around this, so I'm not investing effort in coming up with a MWE, but I can at least post some information about what I think is happening which may help others. 

The relevant part of the traceback I get is: 

```python
RuntimeError: Traceback (most recent call last):
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])

...

  File "/home/joncrall/code/netharn/netharn/util/nms/nms_core.py", line 123, in non_max_supression
    device = torch.cuda.current_device()
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 332, in current_device
    _lazy_init()
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 159, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

I think this is happening because I'm using a GPU implementation of nonmax-suppression in my data loader. So perhaps calling `torch.cuda.current_device()` in a background process is not ok? 

I can work around this by changing my NMS implementation to use a CPU instead. Unfortunately this doesn't fix whatever the underlying issue is.

**Comment by mruberry** [comment]
PyTorch, like other deep learning frameworks, manages its device context's very carefully and these contexts cannot be used across multiple processes. That's why we require you rely on PyTorch's multiprocessing patterns, which carefully handle this behavior.
