### ISSUE TITLE
Request: oneAPI support

### ISSUE THREAD

**Issue by sbrl** [pytorch/pytorch#30029]
## 🚀 Feature

Intel have announced their new oneAPI, which provides hardware acceleration support on a diverse range of underlying devices. Supporting it would give a huge boost to performance on a wide range of devices that do not contain an Nvidia® GPU.

## Motivation
Nvidia® GPUs are expensive, and I do not currently own one. I do however own an AMD Radeon and, of course, Intel Integrated Graphics. It's really frustrating that I'm limited to slow CPU-based training when I have the hardware _right in front of me_ that _could_ be used to make it go faster, but I _can't_ because PyTorch doesn't support it.

## Pitch
[Intel Announced](https://arstechnica.com/gadgets/2019/11/intels-oneapi-aims-to-unify-ai-code-efforts-across-disparate-hardware/) their new oneAPI to abstract the complexity of hardware acceleration away from higher-level libraries and code. I propose that PyTorch implements support for this, to bring hardware-accelerated GPU training to everyone who doesn't own an Nvidia® GPU.

## Alternatives
Implementing support for OpenCL was discussed in #488, but for some reason that I don't quite understand the suggestion was dismissed. I don't know the PyTorch internals, but by contrast it looks like implementing support for oneAPI would bring a similar benefit to implementing OpenCL, while supporting more different devices.

## Additional context
I can't afford to buy a new £1000 device just to get an Nvidia® GPU - and I suspect that I'm not the only one here. I find it supremely frustrating that the device I have now contains the hardware necessary to greatly accelerate machine-learning workloads without being able to use it. Had I know a few years ago that I'd be getting into machine learning and AI, I might have bought a different device.

cc @ngimel

**Comment by xsacha** [comment]
Also, OneAPI can work with Nvidia GPUs anyway:
https://www.phoronix.com/scan.php?page=news_item&px=Intel-oneAPI-DPC-SYCL-NVIDIA-CU

**Comment by narfanar** [comment]
Disruption to NVidia's hold on the ML market can't come fast enough :D

**Comment by gchanan** [comment]
Though we are sympathetic to concerns raised in the issue, integrating this library is expensive in terms of developer time and we'd like to see adoption before we do that.

**Comment by sbrl** [comment]
I see, @gchanan. What adoption would you be looking for before considering adding support for it? If nobody adopts it, then it'll probably just fade away.

As it stands, over 30 industry-leading companies have their formal support for oneAPI: https://newsroom.intel.com/articles/fact-sheet-oneapi/

**Comment by E3V3A** [comment]
@sbrl @gchanan @mijosch @Wulfsta @soumith @hughperkins @cathalgarvey 

As PyTorch is featured on all sorts of webpages by nVidia, my suspicion is that nVidia is the sole sponsor of *this* project. It would be great if people who have continuously closed all the issues related to any future-proof alternatives to nVidia, would come forward in full disclosure to their relationship to nVidia and how pytorch is related to them. At least in that manner we could write off this project as dead end, and move forward in with more altruistic projects, perhaps forking this in the process, since after all, **this projects success has fundamentally rested on the open source community**, saving nVidia hundreds on millions of dollars! Those of us who contribute to these kind of projects, just want to be heard.

**Comment by soumith** [comment]
@E3V3A do you know that PyTorch supports AMD ROCm GPUs, has a continuous build for it for years?
That itself throws out your theory.

> As PyTorch is featured on all sorts of webpages by nVidia, my suspicion is that nVidia is the sole sponsor of this project. 

NVIDIA promotes many open source projects. They also promote MATLAB and stuff. I presume they promote what is relevant to their customers.

>  It would be great if people who have continuously closed all the issues related to any future-proof alternatives to nVidia, would come forward in full disclosure to their relationship to nVidia and how pytorch is related to them. 

I probably closed a few issues around OpenCL, and I started / lead PyTorch (and maintained Torch7 before that). NVIDIA makes good GPUs, we have built a CUDA backend into Torch-7 project from 2011 or so. With a LOT of energy from AMD and PyTorch team, we have ROCm backend. We don't have OpenCL backend because every time we spent time on it, we burn our hands because of bad driver stack or / latency. NVIDIA has a few engineers working on PyTorch, some have contributed enough code to be called maintainers https://pytorch.org/docs/stable/community/persons_of_interest.html . We also have people from Intel, AMD in the same bucket.

**Comment by soumith** [comment]
@sbrl the way we went about accepting the AMD backend for example is the following, though we don't have a formal document or program to accept new backends

1. Decide to evaluate the backend: see the addressable market for the backend, and the maturity of the backend. This is a bit of chicken-egg issue.
2. Evaluate the backend: Someone (either a pytorch core dev or an enthusiastic open source dev) evaluates the backend, writes initial bindings and buys hardware and tests things and deals with bugs and issues and perf regressions. This effort itself is highly difficult and takes multi-months, which is why we have (1) as a filter. If we find issues in (2) that are unfixable or fixable-but-no-one-is-fixing-them, then we stop, if not we continue to (3)
3. Ask the company building the backend if they have energy and priority to support PyTorch as a frontend (often this conversation happens at (1) because the company asks us in the first place). We get commitments of number of engineers and time allocated. The last thing you want is to build a multi-person-year effort around a dead-end future
4. Formalize an engineering plan to go to covering all PyTorch API (~450+ API functions) and unit-test the whole thing 

With oneAPI, I think we are in step 1.
Someone in the community can definitely try to give us data on step 2.

The current backends PyTorch tests for (on every commit) are:
- CPU
- CUDA
- AMD ROCm
- Google TPU via XLA

**Comment by Wulfsta** [comment]
@soumith unrelated question: what's the hardware that you're running ROCm builds and tests on look like (or where can I find this information)? NixOS is having some trouble packaging PyTorch and TensorFlow for ROCm versions 3.1.0 and above, and this might be useful information.

**Comment by gchanan** [comment]
@Wulfsta you can see our CI builds here: https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master (search rocm in the top column).

**Comment by Wulfsta** [comment]
@gchanan: will take a look, thanks!

**Comment by hughperkins** [comment]
@sbrl @E3V3A 

I did a partial port of lua torch to OpenCL, and I agree 100% with Soumith's approach here. For the record, when I was porting lua torch to OpenCL, Soumith was *very* supportive.

As far as Intel OneAPI, there is nothing stopping Intel from sponsoring work on pytorch. Or yourselves for that matter.

As far as OpenCL, after dabbling in opencl for a while, what I reckon is that OpenCL is destined to lag behind CUDA, by virtue of the way it is created. Which is by a large committee of vendors having to negotiate in painstaking detail every single tiny detail. And imagine that, for every little tiny feature and detail, one has to design it so it will work across a zillion vendors and platforms. That's neither going to be fast to create, nor efficient to execute.

I kind of see OpenCL like this:

![Screen Shot 2020-04-27 at 5 34 36 PM](https://user-images.githubusercontent.com/123560/80426385-91829880-88b3-11ea-86ce-780bdde80ff8.png)

![Screen Shot 2020-04-27 at 5 34 47 PM](https://user-images.githubusercontent.com/123560/80426395-9b0c0080-88b3-11ea-8200-454b926328e5.png)

That said, concretely, if you port pytorch by hand, to opencl, like I did for lua torch, you will likely find yourself I imagine with lots of great companies throwing job offers at you. It was certainly extremely exhilarating for me, though I had to slog for ~6 months, 40 hours a week, whilst holding down a full time job, before that started happening. (nuance: you might go with SYCL, or ... there's some lower level language, that I forget the name of right now, or there might be some newer things by now...).

Alternatively, if you figure out how to implement https://github.com/hughperkins/coriander/blob/multiple-walks/doc/walking.md , you could plausibly 1. write some kind of paper on it, or at least a workshop presentation (no guarantees, but doesnt seem out of the realm of possibility), 2. get coriander working on pytorch, https://github.com/hughperkins/coriander/tree/master , which compiles NVIDIA® CUDA™ code into OpenCL 1.2 code.

Or you could try some other approach. There are many possible approaches, most of which will all work, with different good and bad points, caveats, etc. Just pick the one that takes your own fancy. Or get OneAPI working on pytorch :)

**Comment by cathalgarvey** [comment]
I have hopes for Futhark as a nice high-level way to write kernels that can be transpiled into various lower-level frameworks like CUDA, HIP, OpenCL etc. I had fun playing with it a year ago or so, but the docs were at that time very far behind what appeared to be a big refactor-in-progress.

But, as projects to bridge the monopoly gap in AI, it's one route that a future AI framework has open that wasn't there before. And it's not alone, I know of a few other high-level, expressive, but supposedly "cost-free" concepts floating around. Futhark seems to be the best supported right now though.

Anyways, on topic, I'm glad that at least some more proprietors vendor frameworks are supported. I didn't see strong documentation last time I looked for Rocm so I'm looking forward to another dive tomorrow. Thanks. :)

On 27 April 2020 23:26:53 GMT+01:00, Hugh Perkins <notifications@github.com> wrote:
>@sbrl @E3V3A >
>>
>I did a partial port of lua torch to OpenCL, and I agree 100% with
>Soumith's approach here. For the record, when I was porting lua torch
>to OpenCL, Soumith was *very* supportive.>
>>
>As far as Intel OneAPI, there is nothing stopping Intel from sponsoring
>work on pytorch. Or yourselves for that matter.>
>>
>As far as OpenCL, after dabbling in opencl for a while, what I reckon
>is that OpenCL is destined to lag behind CUDA, by virtue of the way it
>is created. Which is by a large committee of vendors having to
>negotiate in painstaking detail every single tiny detail. And imagine
>that, for every little tiny feature and detail, one has to design it so
>it will work across a zillion vendors and platforms. That's neither
>going to be fast to create, nor efficient to execute.>
>>
>I kind of see OpenCL like this:>
>>
>![Screen Shot 2020-04-27 at 5 34 36
>PM](https://user-images.githubusercontent.com/123560/80426385-91829880-88b3-11ea-86ce-780bdde80ff8.png)>
>>
>![Screen Shot 2020-04-27 at 5 34 47
>PM](https://user-images.githubusercontent.com/123560/80426395-9b0c0080-88b3-11ea-8200-454b926328e5.png)>
>>
>That said, concretely, if you port pytorch by hand, to opencl, like I
>did for lua torch, you will likely find yourself I imagine with lots of
>great companies throwing job offers at you. It was certainly extremely
>exhilarating for me, though I had to slog for ~6 months, 40 hours a
>week, whilst holding down a full time job, before that started
>happening. (nuance: you might go with SYCL, or ... there's some lower
>level language, that I forget the name of right now, or there might be
>some newer things by now...).>
>>
>Alternatively, if you figure out how to implement
>https://github.com/hughperkins/coriander/blob/multiple-walks/doc/walking.md
>, you could plausibly 1. write some kind of paper on it, or at least a
>workshop presentation (no guarantees, but doesnt seem out of the realm
>of possibility), 2. get coriander working on pytorch,
>https://github.com/hughperkins/coriander/tree/master , which compiles
>NVIDIA® CUDA™ code into OpenCL 1.2 code.>
>>
>Or you could try some other approach. There are many possible
>approaches, most of which will all work, with different good and bad
>points, caveats, etc. Just pick the one that takes your own fancy. Or
>get OneAPI working on pytorch :)>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/pytorch/pytorch/issues/30029#issuecomment-620268346

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sbrl** [comment]
Hey there! Sorry for not getting back to anyone.

I was not aware of an AMD ROCm backend to PyTorch. Is there any documentation on this please? A list of supported GPUs would be very helpful too. I have an AMD R7 M445, so that  sounds like a  potentially feasible backend for me.

**Comment by Wulfsta** [comment]
@sbrl https://github.com/ROCmSoftwarePlatform

**Comment by sbrl** [comment]
That seems to be a link to the AMD ROCm org on GitHub? I don't see any pytorch there

**Comment by Wulfsta** [comment]
@sbrl Most of the development for the ROCm backend of PyTorch takes place in their pytorch repository, to my knowledge. There are build instructions in the wiki there.

**Comment by soumith** [comment]
more precisely, here's the link to build PyTorch + ROCm: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm

You don't need any code changes to your existing PyTorch code, your pytorch's `.cuda()` runs on your ROCm GPU

**Comment by E3V3A** [comment]
Hi Guys! 

First of all, I would like to apologize for having been wrong and accusingly so. However, I have also been equally unaware and confused by this support, as you have been by my statement above. Because everywhere I come across PyTorch dependencies, everyone says, "no, only CUDA is supported". So how am I supposed to deal with this? Clearly I am mostly an end-user and quite a new one to "torch" use, so I believe I am not alone, (which seem further confirmed by even more users in this very thread) in this confusing mess. 

Anyway, thanks for the feedback, and I really hope we can find a more solid and common ground for users to better understand what can and cannot be done (and how) for their respective graphics cards. 

PS. The windows "support" and installations instructions in the README here, is horrible. Extremely confusing as the various numbers and filenames and package names etc. etc.,  are not easily found (at best) and not anywhere (at worst.)

**Comment by xsacha** [comment]
If you're wondering why every deep learning package supports CUDA first, CUDA in prebuilts, it's just because it's the oldest and most stable API that most people will use.
Adding an extra framework adds a lot of size to the prebuilts and is usually in an experimental state or outdated by the time of release. Also AMD's ROCm does not work on Windows. OneAPI is brand new.

**Comment by soumith** [comment]
@E3V3A I think the reason for "only CUDA is supported" is mainly because support is an overloaded term.

Officially Supported:
- If you file a bug, especially a serious one, the core PyTorch team will fix it within reasonably quick timeframe. We do this for CPU, CUDA and the Google team does this for pytorch/xla.

Supported by the codebase, but PyTorch team didn't say Officially supported:
- works on master, has continuous integration
- If you file a bug, especially a serious one, the core PyTorch team does not know how to fix it, because  a support workflow has not been established (either for the lack of people, hardware or commitment from vendor).
We don't do this for ROCm yet, a plan is being formulated on how to have official support.

**Comment by cathalgarvey** [comment]
I do wish frameworks would stop using the name of CUDA in method names and APIs though, it gets silly when newer systems like ROCm are added yet the APIs are still called by the legacy name.

Something similar happened with torch7 when the method titles for OpenCL were different so users of OpenCL had to manually edit libraries and scripts to switch over from the cuda calls.

The pytorch system is just to use cuda for everything which is less silly, but still far sillier than using neutral words to name APIs like "coprocessor" or "GPU".

On 1 May 2020 19:03:44 GMT+01:00, Soumith Chintala <notifications@github.com> wrote:
>@E3V3A I think the reason for "only CUDA is supported" is mainly
>because support is an overloaded term.
>
>Officially Supported:
>- If you file a bug, especially a serious one, the core PyTorch team
>will fix it within reasonably quick timeframe. We do this for CPU, CUDA
>and the Google team does this for pytorch/xla.
>
>Supported by the codebase, but PyTorch team didn't say Officially
>supported:
>- works on master, has continuous integration
>- If you file a bug, especially a serious one, the core PyTorch team
>does not know how to fix it, because  a support workflow has not been
>established (either for the lack of people, hardware or commitment from
>vendor).
>We don't do this for ROCm yet, a plan is being formulated on how to
>have official support.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pytorch/pytorch/issues/30029#issuecomment-622496263

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielbraun89** [comment]
> Though we are sympathetic to concerns raised in the issue, integrating this library is expensive in terms of developer time and we'd like to see adoption before we do that.

Now that tensorflow 2.9 natively supports oneAPI maybe its time to reconsider as the adoption is obviously there

**Comment by redthing1** [comment]
Hope this can come soon

**Comment by vpirogov** [comment]
@danielbraun89, @redthing1, oneAPI support for Pytorch is now available via [Intel Extension for Pytorch](https://github.com/intel/intel-extension-for-pytorch).
