### ISSUE TITLE
figure out how to deliver gcc 4.9 to source install users

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3050]
According to https://github.com/conda/conda/issues/6132 'gcc' was always intended to be an internal package that users were not supposed to use. So we should stop advising that users install it in https://github.com/pytorch/pytorch#install-optional-dependencies

I would just go ahead and fix this but I am not sure if the 'gcc' line there solves a concrete problem for users (e.g., maybe it helps smooth over C++ ABI problems).

**Comment by mingwandroid** [comment]
You can use `gcc_linux-64` and/or `gxx_linux-64` instead. We are promoting as something users will want to use. AD 5 has been rebuilt from scratch using them. Using the old `gcc` package will clobber the needed `libstdc++.so` with an older one.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/commit/f74665f0c4b0caa8d667cd8d3e2bb764ac92bae0

However, we do need to figure out how to give users gcc 4.xx because CUDA8's `nvcc` doesn't support gcc 5 and above. I think CUDA9 `nvcc` doesn't support `7.2.0` which is what `gcc_linux-64` will give you.

**Comment by ngimel** [comment]
Correct, but we also had build problems with cuda 9 and gcc 4.8.x, which is what ```conda install gcc``` gives you.

**Comment by mingwandroid** [comment]
What *exactly* does 'does not supports' mean? Afaict some header deliberately excludes it.. but does anything break?

GCC is backwards compatible and improves as time progresses.

**Comment by ngimel** [comment]
See e.g. here https://tercatech.com/a/Blog/NVIDIA%20CUDA%208.0%20with%20GCC%207 about making cuda 8 work with gcc 7 as a host compiler. Apparently it can be done, but modifications are quite invasive and involve changing both cuda headers and stl headers.

**Comment by mingwandroid** [comment]
Ok thank you very much for the link. I'll study it tomorrow. I'm happy to build old compilers targeting centos6 if *necessary* but it just feels so wrong!

**Comment by ngimel** [comment]
Nvcc is usually slightly behind the latest gcc version, here http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html you can find supported host compilers for cuda 9. So gcc 6.x is supported (fedora 25, ubuntu 17.04), but gcc 7.x is not.

**Comment by ezyang** [comment]
Thanks @soumith, making nvcc work out of the box is a good reason to specify a compiler for non power-users.

**Comment by obilaniu** [comment]
Gentlemen and gentlewomen, [this commit](https://github.com/pytorch/pytorch/commit/502aaf39cf4a878f9e4f849e5f409573aa598aa9) from PR #3456 breaks GCC 4.9. In the `stdatomic.h` header that ships with GCC 4.9, `ATOMIC_INT_LOCK_FREE` is implemented with compiler builtins and `?:`, causing the preprocessor to vomit a cryptic message

```
In file included from /PATH/TO/pytorch/aten/src/TH/THAllocator.c:8:0:
PATH/TO/pytorch/aten/src/TH/THAllocator.c:9:5: error: missing binary operator before token "("
#if ATOMIC_INT_LOCK_FREE == 2
    ^
```

because the expansion of `ATOMIC_INT_LOCK_FREE` eventually reaches

```
#define __atomic_type_lock_free(T) \
(__atomic_always_lock_free (sizeof (T), (void *) 0) \
? 2 \
: (__atomic_is_lock_free (sizeof (T), (void *) 0) ? 1 : 0))
```

with `T=atomic_int`, and since the preprocessor is unaware of compiler builtins it substitutes them with `0`, wherefore you see complaints about what effectively is the junk expression `#if 0(0(0)(0)....` that appears at first glance to be a math expression that is simply lacking in binary operations.

The effective requirement for PyTorch is now GCC 5.3.0, where `ATOMIC_x_LOCK_FREE` were reimplemented in `stdatomic.h` in terms of preprocessor defines, whose value is numerically available to the preprocessor.

**Comment by ezyang** [comment]
We don't want to break GCC 4.9. We added this ifdef to work around bugs we saw in other configurations. Would you happen to know what the "right" way to test for this is?

**Comment by obilaniu** [comment]
@ezyang The best that can be done, provided no other functionality of `stdatomic.h` is needed in that file when GCC is used, is to apply, in that file, the [`stdatomic.h` change of 2014](https://github.com/gcc-mirror/gcc/commit/aedd2947e223fda8838a2d2d9e7a4dc9327d8855), which mapped `ATOMIC_x_LOCK_FREE` directly to the GCC preprocessor define macros already available in GCC 4.8:

```
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
```

**Comment by apaszke** [comment]
And the standard clearly states that these macros:

> Expands to preprocessor constant expressions ...

Eh, I guess we'll have to check if those gcc specific macros are set

**Comment by zdevito** [comment]
So it seems like C11 atomics are just poorly supported in general. I think the best thing might just be to alter the C11 atomics check in the CMakeFile to include checking ATOMIC_INT_LOCK_FREE, and fall back to GCC atomics (which we already do in some cases) if they are not.

**Comment by ozancaglayan** [comment]
FYI, I build pytorch from source frequently on Ubuntu 16.04, CUDA8 and with system's GCC 5.x without a problem.

**Comment by zhFuECL** [comment]
@ozancaglayan Our server is Ubuntu14.04 with CUDA8.0
Do you know which gcc version I should use？

**Comment by 98noob** [comment]
Is there any working / recommended way to use a conda gcc to install from source on linux (in order to install from source without sudo rights)? Which conda gcc package to use? The only gcc 4.9 I could find: `conda install -c serge-sans-paille gcc_49`. But after installing it in the environment, it seems not to be used by the pytorch installer (1. I still get the"gcc versions later than 7 are not supported" error, 2.) $CC remains empty).
