### ISSUE TITLE
[jit] `@staticmethod`s retrieved from `self` don't work

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#30755]
```python
class M(nn.Module):
    @staticmethod
    def some_method(x):
        return x + 10

    def forward(self, x):
        return self.some_method(x)

torch.jit.script(M())
```

The compiler treats `some_method` as a regular method instead of a static method, so `x` ends up having the type `M` instead of `Tensor`.

The error is: 
```
RuntimeError:
Tried to access nonexistent attribute or method '__add__' of type '__torch__.M'. Did you forget to initialize an attribute in __init__()?:
  File "/private/home/suo/scratch/test.py", line 21
    @staticmethod
    def some_method(x):
        return x + 10
               ~~~~~~ <--- HERE
'M.some_method' is being compiled since it was called from 'M.forward'
  File "/private/home/suo/scratch/test.py", line 24
    def forward(self, x):
        return self.some_method(x)
               ~~~~~~~~~~~~~~~~~~ <--- HERE
```
cc @suo

**Comment by suo** [comment]
Some commentary: the script compiler will start from the `forward()` method and recursively descend any functions that are called and try to compile them too. The logic for orchestrating this on the Python side is in `_recursive.py`. 

In this case, it seems that the compiler is mistakenly trying to compile `some_method` as an `instancemethod` instead of a `staticmethod`, and treating `x` the implictly passed `self` instead of a regular as a regular argument.

The code for where we look up uncompiled methods on a module is [here](https://github.com/pytorch/pytorch/blob/e98ad6c05b21f9ee04447de69e809af42f4e114a/torch/csrc/jit/python/python_sugared_value.cpp#L447), and indeed we don't check that something is a `staticmethod` before trying to compile it like an `instancemethod` :(

A fix would be to check whether the requested method is a static method. If it is, instead of compiling it as a method, compile it as a free function (I guess), and return that. 
- [toSugaredValue](https://github.com/pytorch/pytorch/blob/cd4c3b48a6ef32dc2e9e937bc23ed1a4b7113bfb/torch/csrc/jit/python/python_sugared_value.cpp#L602) is our one-stop shop from converting an arbitrary Python object into a `SugaredValue` (basically a representation of a value that knows how to emit IR for itself ([see overview](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/OVERVIEW.md#sugaredvalue)).
