### ISSUE TITLE
init_process_group creates context on the current device, even when it does not seem necessary

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#3082]
```
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
import ctypes
import argparse
lib = ctypes.cdll.LoadLibrary(None)

parser=argparse.ArgumentParser(description='distributed_bug')
parser.add_argument('-rank', default=0, type=int,
                                                help="""distributed rank of process""")
opt = parser.parse_args()

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 3200)
        self.fc2 = nn.Linear(3200, 84)
        self.fc3 = nn.Linear(84, 10)
        self.bn2 = torch.nn.BatchNorm2d(16)

    def forward(self, x):
        x = self.pool(F.relu((self.conv1(x))))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

#torch.cuda.set_device(opt.rank)    
net = Net().cuda(opt.rank)
world_size=2
dist_url = 'tcp://224.66.41.62:23456'
dist_backend = 'gloo'

dist.init_process_group(backend=dist_backend, init_method=dist_url, world_size=world_size)
torch.cuda.synchronize()
net = torch.nn.parallel.DistributedDataParallel(net, device_ids=[opt.rank])
torch.cuda.synchronize()
inp = Variable(torch.randn(64, 3, 32,32))
torch.cuda.synchronize()
for i in range(10):
    out = net.forward(inp)
    loss = out.sum()
    loss.backward()
    torch.cuda.synchronize()
lib.cudaProfilerStop()
print("Finished")
```
when torch.cuda.set_device is commented out, there would be as many python processes on device 0 as there are ranks, each taking ~450 MB memory. For 8 GPUs that adds up. Extra processes are created by init_process_group call, before that each process initializes context and allocates memory on its own GPU. While there's an easy workaround (set gpu before calling init_process_group), still looks like a bug. Run with 
```
python test.py -rank 0 &
python test.py -rank 1 &
```

**Comment by ailzhang** [comment]
Hi @ngimel , I looked into this problem and imho this is not a pytorch bug.
The extra context was created by `torch.cuda.synchronize()` in the provided script.  This can be verified by the following logic:
1. I added another `torch.cuda.synchronize()` before `init_process_group()`, I saw there were already 2 processes running on GPU 0 before `init_process_group()`, which tells us that the extra process was not created by `init_process_group()`.
2. I ran a simple script below
```
import torch
torch.cuda.synchronize()
```
It creates a context on GPU 0( default) because nothing was on GPU yet, it needs to do initialization.
3. Trying to explain what happens in your example, `net = Net().cuda(opt.rank)` only copies all model parameters and buffers to the specified GPU, without ` torch.cuda.set_device(opt.rank)`, when `torch.cuda.synchronize()` is called, it actually doesn't know its visible device is limited. So it defaults to create a new context on GPU 0. 
On the other hand, if ` torch.cuda.set_device(opt.rank)` is called, it initializes a context on the specified device, and kind of set a environment variable for cuda to limit the visible device. In this case, `torch.cuda.synchronize()` will respect what's already set and there is no need to create context any more. 
Hope this explains, please correct me if I'm wrong @apaszke , thanks!

**Comment by apaszke** [comment]
This makes sense, thanks a lot @ailzhang!

**Comment by ngimel** [comment]
Ok, so it could be that ```torch.cuda.synchronize``` creates context, rather than ```init_process_group```. Makes sense, closing.
