### ISSUE TITLE
Bad interplay between indexing and in-place operations?

### ISSUE THREAD

**Issue by lopezpaz** [pytorch/pytorch#3085]
Hi all,

Are the following two alternatives different on purpose? Thanks!

```python
import torch

x1 = torch.randn(10)
idx = torch.LongTensor([1,4,6,2,3])
y = torch.randn(5)

x2 = x1.clone()
x2[idx].add_(-0.1, y)
print((x1 - x2).norm()) # zero, unexpected

x2 = x1.clone()
x2[idx] -= 0.1 * y
print((x1 - x2).norm()) # non-zero, expected
```

Thanks!
dlp.

**Comment by lopezpaz** [comment]
@glample

**Comment by apaszke** [comment]
Yes, that's expected. It's a weird interplay of Python and PyTorch semantics. The first case is obviously expected to fail, because advanced indexing always returns a tensor that doesn't share memory with the source.

The second case is more complicated. These in-place operators are really a syntactic sugar.

```
<A expression> -= <B expression>
```
is actually rewritten as
```
<A expression> = <A expression>.__isub__(<B expression>)
```

The important part is that it's the entire expression so it includes indexing as well. In your case, it will expand to (note that `__isub__` just calls `sub_`, so you could replace one with another):
```python
x2[idx] = x2[idx].__isub__(0.1 * y)
```
This works fine, because you'll slice `x2`, get a new tensor with new data, mutate it, and do `x2[idx] = new_tensor`, which will correctly copy its data back into `x2`.

**Comment by lopezpaz** [comment]
Thanks @apaszke !
