### ISSUE TITLE
Negative learning rate does not raise error after the optimizer is created

### ISSUE THREAD

**Issue by chenwydj** [pytorch/pytorch#30889]
## To Reproduce

```python
N, D_in, H, D_out = 2, 2, 2, 1
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
model = torch.nn.Sequential(
     torch.nn.Linear(D_in, H),
     torch.nn.ReLU(),
     torch.nn.Linear(H, D_out),
)
````
```python
optimizer = torch.optim.Adam(model.parameters(), lr=-0.1)
# >>> ValueError: Invalid learning rate: -0.1
```
```python
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
optimizer.param_groups[0]['lr'] = -0.1
# no errors
```

## Expected behavior

I wonder any reason for not checking the negative learning rate after the optimizer instance is created?

## Environment

 - PyTorch Version: 1.1.0
 - OS: Ubuntu
 - How you installed PyTorch: `pip`
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 1080Ti

**Comment by SsnL** [comment]
Well, the reasoning is that we can't check all cases. For example, this case can't be checked at assignment time unless we write our own dictionary class, and even then you can get around it with `object.__setitem__`. Even if we check at `step`, we can't prevent setting `lr` with an object with custom comparison (so that `lr > 0` is true), but is effectively negative at computation.

**Comment by chenwydj** [comment]
Thank you for the explanation!
