### ISSUE TITLE
Move hypothesis installation to docker

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#31136]
Most of our test CI broke today because hypothesis did an update that changed their internal module structure and we were importing things from an internal module. 

In the long-term we should install hypothesis while building our docker images instead of asking our CI to install it every time the CI runs. i.e., remove this line: https://github.com/pytorch/pytorch/blob/7a8261e962f26f84f6211bca4270713a3102146c/.jenkins/pytorch/test.sh#L52 .

I'm going to mark this issue as high-pri because it is related to flaky tests, please correct me if the guidance is incorrect.

cc @ezyang @gchanan @zou3519

**Comment by zou3519** [comment]
We should probably pin a lot of the packages in https://github.com/pytorch/pytorch/blob/7a8261e962f26f84f6211bca4270713a3102146c/.jenkins/pytorch/test.sh as a quick preventative thing to avoid future surprises. One failure mode for our CI is that we start seeing seemingly unrelated failures because we forgot to pin a package and the package got updated.

**Comment by Enealor** [comment]
I'm not certain, but it looks like we can pin the installed versions in the [python install script](https://github.com/pytorch/pytorch-ci-dockerfiles/blob/master/common/install_travis_python.sh#L73) in the [pytorch-ci-dockerfiles] repository. If this sounds right, I can bring it up there.

**Comment by ezyang** [comment]
Yep; however, pytorch-ci-dockerfiles is defunct (I just fixed this with a README) you should edit `.circleci/docker` now

**Comment by Enealor** [comment]
I've been looking into this again, and I wanted to check if I am understanding what changes are necessary here. There are two places where `pytest` is installed in `.circleci/docker/common`, and this leads me to believe we are testing in two environments. In the environment used by [install_travis_python.py](https://github.com/pytorch/pytorch/blob/b10761d8900af1dc48bee807ab39c80fd4334b79/.circleci/docker/common/install_travis_python.sh#L73), `hypothesis` is installed but not pinned. In the environment used by [install_conda.py](https://github.com/pytorch/pytorch/blob/b10761d8900af1dc48bee807ab39c80fd4334b79/.circleci/docker/common/install_conda.sh#L89), `pytest` is installed but `hypothesis` is not.

I'm not sure which of the two environments strictly need `hypothesis` to be added and pinned. Are both being used for testing? If so, then I can add a pinned `hypothesis` to both. However, if one is more intended for building rather than testing, then should we consider removing `pytest` from one of the environments?

**Comment by ezyang** [comment]
Both of these environments are being used for testing, and we should pin both.
