### ISSUE TITLE
python test/run_test.py -i cpp_extensions doesn't recompile extension

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#31173]
I wasted some time because I fixed a bug, reran cpp extension tests, and it still failed, and I spun wheels until I realized that the C++ extensions didn't get recompiled. That's wrong: we should always recompile the extensions when running these tests.

cc @yf225

**Comment by nolifenameless** [comment]
Pull Request: https://github.com/pytorch/pytorch/pull/32495
Not quite sure about if this PR had resolved this issue.

**Comment by ezyang** [comment]
It's possible @zou3519's PR fixed the issue, but on its face it isn't what it's testing. @zou3519, do you happen to know?

**Comment by zou3519** [comment]
that PR doesn't modify the non-ninja path (although it does refactor the testing for that a little bit). Because of that I expect that `python test/run_test.py -i cpp_extensions` won't recompile the non-ninja extensions that are being tested :/ (but I am not sure what the behavior for the ninja extensions is)

**Comment by nolifenameless** [comment]
On the basis of lastesd code, the include choice `-i cpp_extensions` has devide into three choices    
 `test_cpp_extensions_aot_no_ninja`
 `test_cpp_extensions_aot_ninja`
 `test_cpp_extensions_jit`
the first two already have called `setup.py install` before test execute, which implemented by zou. 

the last choice , which renamed from the old `cpp_extensions`, won't recompile extension due to some tests are wrapped in decorator `@dont_wipe_extensions_build_folder`,should I move on and fix this issue? @ezyang

**Comment by ezyang** [comment]
Yes, it looks like you can validly try to fix this issue, although it might be a good idea to talk to whoever added  `dont_wipe_extensions_build_folder` because it sounds like we may be *intentionally* not recompiling in this case, based on your sleuthing.

**Comment by nolifenameless** [comment]
trying fixing this, pls review this PR  https://github.com/pytorch/pytorch/pull/40169.thx a lot.
