### ISSUE TITLE
cumsum backward for zero-length zensors

### ISSUE THREAD

**Issue by felix-schneider** [pytorch/pytorch#31515]
## 🐛 Bug

Calling `cumsum` on a zero-dimension tensor raises an error in backward.
The error occurs for both `cumsum` and `cumprod` and on both CPU and GPU

## To Reproduce

```python
import torch

x = torch.zeros(2, 0, requires_grad=True)
xx = x.cumsum(dim=-1).sum()
xx.backward()
```

Output:
```
Traceback (most recent call last):
  File "narrow_test.py", line 6, in <module>
    xx.backward()
  File "xxx/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "xxx/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: start (0) + length (1) exceeds dimension size (0).
```

## Expected behavior

I'm not sure if the gradient calculation makes any sense in this edge case, but at least the error message should be more clear.

## Environment

```
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.2.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX
GPU 4: TITAN RTX
GPU 5: TITAN RTX

Nvidia driver version: 430.50
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch
```

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by mruberry** [comment]
Thanks for filing this issue, @felix-schneider!

**Comment by mrshenli** [comment]
self-assigned to reserve for Bootcamp

**Comment by mrshenli** [comment]
As I am making this a bootcamp task, let me add more context here.

The backward function implementation for `cumsum` is at

https://github.com/pytorch/pytorch/blob/e46babb6378b9bf18265e4ff2bb9e8ebe0b50522/tools/autograd/templates/Functions.cpp#L417-L426

The fix should be simple, just replace `x.dim() == 0` with `x.numel() == 0`. For the above failure case, the dimension of the tensor is 2, but the number of elements (numel) is 0, because the 2nd dimension is 0. 

Besides the fix, we also need to tests coverage to:

https://github.com/pytorch/pytorch/blob/e46babb6378b9bf18265e4ff2bb9e8ebe0b50522/test/test_torch.py#L10394-L10399

cc @gchanan

**Comment by mrshenli** [comment]
cc @leedtan
