### ISSUE TITLE
`cdist` backward for euclidian distance should be expressed through matrix multiplies

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#31599]
## 🚀 Feature
#25799 provides optimized implementation for `cdist` with `p=2` that uses matrix multiplies instead of specialized (inefficient) kernels. However, that PR did not change the backward logic, so backward even for the optimized case calls inefficient kernels. The logic for `cdist` operation should be rewritten in such a way that euclidian distance becomes a compound operation w/o backward defined (thus the backward would be optimized automatically), and the general case can go through the inefficient kernels.  
## Motivation
Optimized forward implementation improves performance by upto 50x, we expect similar improvements for backward.  
Also, current implementation suffers from the bugs with large sizes (see #31167). Those bugs still have to be fixed for the general case, but gemm-based implementation seems more robust. Large memory usage reported in #24345 also might be due to inefficient implementation.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @VitalyFedyunin @ngimel

**Comment by jasam-sheja** [comment]
I'm writing gemm-based `cdist` with forward and backward functions. 
However, I'm facing a problem with the CPU in the forward function.
I'm getting _`Intel MKL ERROR: Parameter 14 was incorrect on entry to cblas_sgemm_batch.`_ with this:
`at::Tensor sq_dist = x1_norm.add(x2_norm.transpose(-2, -1)).baddbmm_(x1, x2.transpose(-2, -1), 1, -2);`

The problem is in `baddbmm_`. I couldn't figure out what's triggering it exactly but the input sizes matter as for example inputs with shapes `x1= torch.Size([?, 1, 100])` and `x2= torch.Size([?, 4, 100])` or another example `x1= torch.Size([?, 1, 80])` and `x2= torch.Size([?, 5, 80])` but there's no error when swaping `x1` and `x2` or when using smaller sizes

Other than that, it's working nicely on the GPU. There isn't a 50x speedup, though! But it works fine with large inputs, which #31167 was trying to fix.

**Comment by ngimel** [comment]
This was implemented fixed in #31167

**Comment by jasam-sheja** [comment]
#31167 fixed it by skipping the manual backward. I'm trying to use `addbmm` instead of `cat` and `matmul`, which is currently implemented in `euclidean_dist_out`. I'm seeing the same or less peak memory (forward + backward) and speedup of 1.1x-2.3x.
I believe there are some improvements to gain.
