### ISSUE TITLE
Linspace+logspace support all integral types on CUDA but not CPU

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#31991]
## 🐛 Bug

Linspace+logspace support all integral types on CUDA. On CPU, they support integral types only when the `steps` argument is 0 or 1. This discrepancy is weird; it does not exist in 1.4.0.

## To Reproduce
On pytorch master
```
import torch

x = torch.linspace(0, 10, steps=10, dtype=torch.long, device='cuda')  # OK

x = torch.linspace(0, 10, steps=0, dtype=torch.long, device='cuda')  # OK

x = torch.linspace(0, 10, steps=1, dtype=torch.long, device='cuda')  # OK

x = torch.linspace(0, 10, steps=0, dtype=torch.long, device='cpu')  # OK

x = torch.linspace(0, 10, steps=1, dtype=torch.long, device='cpu')  # OK

x = torch.linspace(0, 10, steps=10, dtype=torch.long, device='cpu')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-9554d84beda1> in <module>
----> 1 x = torch.linspace(0, 10, steps=10, dtype=torch.long, device='cpu')

RuntimeError: "linspace_cpu" not implemented for 'Long'
```

## Expected behavior

linspace + logspace should have consistent behavior across CUDA and CPU. It would be nice for them to support integral types on CPU.

## Environment

PT master

cc @ngimel

**Comment by Enealor** [comment]
It looks like this is caused by the two using different dispatch commands. Both `linspace_cpu_out` and `logspace_cpu_out` use `AT_DISPATCH_FLOATING_AND_COMPLEX_TYPES` (see [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/RangeFactories.cpp#L11)), while `linspace_cuda_out` and `logspace_cuda_out` use `AT_DISPATCH_ALL_TYPES_AND` (see [here](https://github.com/pytorch/pytorch/blob/829499e626362e6a1badeba4e28c0f7a7a120fde/aten/src/ATen/native/cuda/RangeFactories.cu#L14)). The fact that they are implemented for steps = 0 or 1 comes from the fact that those cases are handled automatically without progressing to the dispatch functions.

Making the behavior consistent should just be a matter of changing them to use the same dispatch.

**Comment by ngimel** [comment]
@enealor your analysis is correct, do you mind sending a PR?

**Comment by Enealor** [comment]
@ngimel Sure. I can start working on this later today.

**Comment by Enealor** [comment]
As an update, the `linspace` and `logspace` functions have been modified. Both functions now support (almost) all the same types on both CPU and CUDA devices, with two exceptions. 
1. The float16 type is not implemented for the CPU. This was forced by the lack of support for float16 operations on the CPU. 
1. The complex types are not implemented for CUDA devices. This came from needing to use a separate repository to write the tests for this type.

I'm under the impression that there's no interest in offering float16 CPU support, but I can work on adding complex support for CUDA tensors if there's interest in that.

**Comment by mruberry** [comment]
This now works as expected.
