### ISSUE TITLE
Import error after docker build

### ISSUE THREAD

**Issue by amrit110** [pytorch/pytorch#3221]
The latest docker build using the Dockerfile seems to throw import error. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Any ideas why? Have built images successfully before (like 2 weeks ago)

**Comment by amrit110** [comment]
Solved, had to use nvidia-docker run while starting container

**Comment by Sanjeev2487** [comment]
Hi amrit110,

I am also facing same issue, can you please elaborate 'nvidia-docker run staring container'.
Thanks

**Comment by ds-gong** [comment]
@Sanjeev2487 
I faced the same error.I
you should run a new container use nvidia-docker,such as:

nvidia-docker run -it pytorch/pytorch:nightly-devel-cuda9.2-cudnn7 /bin/bash

Instead of : docker run -it pytorch/pytorch:nightly-devel-cuda9.2-cudnn7 /bin/bash

then,you maybe can import torch normally!
