### ISSUE TITLE
Second derivative fails if first derivative happens to be constant

### ISSUE THREAD

**Issue by mathisgerdes** [pytorch/pytorch#32304]
The derivative of a linear function is constant, and so the second derivative is zero.
Trying to replicate these derivatives in pytorch fails, because the first gradient does not get a `grad_fn`.

This will make a straight forward implementation of the second derivative fail for linear functions, while working fine for non-linear functions.

## To Reproduce

Here is a basic implementation of the second derivative for functions with scalar input and output.
```python
def second_deriv(y, x):
    # first derivative of scalar y = f(x) wrt scalar x
    first = torch.autograd.grad(y, x, create_graph=True)[0]
    # second derivative of y wrt x
    second = torch.autograd.grad(first, x, create_graph=True)[0]
    return second
```

For non-linear functions this works just as expected.
```python
>>> x = torch.tensor(1.0, requires_grad=True)
>>> second_deriv(x**2, x)
tensor(2., grad_fn=<MulBackward0>)
```

However, for linear functions the second derivative fails. The reason is that in `second_deriv`, the tensor `first` doesn't have a `grad_fn`.
```python
>>> second_deriv(x*2, x)
```
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

## Expected behavior

I would expect the gradient to always get a `grad_fn` when `retain_graph=True`, even if it is just a trivial dependence (i.e. no actual dependence) on input variables as in the linear case.

One can manually work around this by checking if `grad_fn == None` for the first gradient.
Any algorithm using higher derivatives could then manually create zero tensors as required.
However, in this case at least the documentation should be amended to mention that the presence of a gradient function is not guaranteed.

It seems to me that an implementation of my expected behavior is essentially just a Function  producing a zero tensor as gradient based on the shape of input variables.
Since I suspect this is an issue few people will notice when using pytorch, I can't decide if the increase in code is worth it. 

## Environment

The described behavior appears in all pytorch versions I have used, including `1.3.1`.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
Hi,

This is expected behavior.
We represent `0` gradient with any of the things below:
- Tensor full of `0`s
- None (for p.grad for example)
- Element does not requires grad. Meaning that its gradient wrt all other Tensors that require gradients are `0`.
- Error in `autograd.grad()` when `allow_unused=False` stating that some inputs are not used and thus will have a gradient of `0`.

The main reason why you see this behavior is because when we call backward, traversing the graph can be very expensive if we create it for everything. So in general, we try not to create the graph if we know that only `0` gradients will flow back.
You can see this for all the non-differentiable functions for example. Like the indices returned by max.

Does this make sense?

**Comment by mathisgerdes** [comment]
Yes it does. I already suspected it might be a performance reason, but I wanted to confirm it is expected behavior. Thank you!
