### ISSUE TITLE
Broken wheel, 1.4.0

### ISSUE THREAD

**Issue by tmctgr** [pytorch/pytorch#32349]
## 🐛 Bug

At least one of the published PyTorch 1.4.0 wheels is not a valid zip file.

## To Reproduce

1. Download https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp36-cp36m-win_amd64.whl
1. Try to `pip install --no-index` the local wheel file
1. Witness something along the lines of:
```
PS F:\> .\my_env\python.exe -mpip install F:\torch\torch-1.4.0_cpu-cp36-cp36m-win_amd64.whl --no-index
Processing f:\torch\torch-1.4.0_cpu-cp36-cp36m-win_amd64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "F:\my_env\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "F:\my_env\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "F:\my_env\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "F:\my_env\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "F:\my_env\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "F:\my_env\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "F:\my_env\lib\site-packages\pip\_internal\download.py", line 452, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "F:\my_env\lib\site-packages\pip\_internal\download.py", line 416, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "F:\my_env\lib\site-packages\pip\_internal\utils\unpacking.py", line 252, in unpack_file
    flatten=not filename.endswith('.whl')
  File "F:\my_env\lib\site-packages\pip\_internal\utils\unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "F:\my_env\lib\zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "F:\my_env\lib\zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Renaming the wheel as a `.zip` and attempting to open in Windows Explorer confirms that it is invalid.

## Expected behavior

The provided wheels are all valid and tested.

## Environment

N/A (install-time)

I'm specifically looking at the Windows/py36/CPU-only wheel though.

## Additional context

These Windows wheels don't seem to be getting a lot of love, as we've seen with issues like #29356 where some crucial CUDA DLLs were missing. It would be great if these wheels went though some basic checks, and we'd really appreciate Windows distribution being better supported in general - for example, putting these wheels onto PyPI. A lot of our ML work needs to be on Windows at present, and we're more likely to use it over rival frameworks if the developer experience is good.

**Comment by peterjc123** [comment]
I cannot reproduce the issue. You can verify the MD5 of the file you downloaded, which should be `4d81fa573afbafea7052c485948c5d89` by entering `certutil -hashfile .\torch-1.4.0+cpu-cp36-cp36m-win_amd64.whl MD5`.

> These Windows wheels don't seem to be getting a lot of love, as we've seen with issues like #29356 where some crucial CUDA DLLs were missing.

Again, I apologize for not doing this carefully. It doesn't necessarily mean we don't love Windows. Once an issue is marked related to Windows, I'll look into it. But sometimes, I may have no idea what is happening because there are all kinds of issues (e.g. the topics of them including but not limited to usage, build, performance, correctness, C++, JIT and etc.). Second, Windows staffing is very insufficient. So we may need help from the outside. Third, the testing framework on Windows is not so mature. However, sometimes you don't know there will be problems if the problems don't actually occur. You may think that we have no smoke tests on Windows, but that's not true. We have CI and nightly jobs for Windows, but we simply cannot test for all the possibilities for Windows. If you have some good ideas, please feel free to share.

So in a word, keeping the library in a working state is not so easy as you may think but we are working hard to achieve this. I hope you can understand our difficulties.

>  - for example, putting these wheels onto PyPI.
This is currently disabled because the Windows wheels are too big. cc @soumith 
Again, this doesn't mean we don't love Windows. We host the packages on Anaconda Cloud and even on Tsinghua mirror.



> A lot of our ML work needs to be on Windows at present, and we're more likely to use it over rival frameworks if the developer experience is good.

Could you please elaborate a bit more about your use case? Are you using PyTorch/LibTorch? What function do you often use?

**Comment by tmctgr** [comment]
Hi Peter, thanks very much for getting back to me quickly.

Apologies, I should have attempted the download more than once - my MD5 does not match so I strongly suspect that my download has been corrupted somehow. I'll test the new one now, but it feels rather likely that this will resolve my problems.

I appreciate your detailed comments about Windows - we're very much aware that we're going against the industry grain by using it over Linux, and I'm very glad that the Windows binaries are available - we will try to aid you where we can by proactively reporting bugs and feedback, and sending PRs as appropriate.

It's understandable that testing all combinations equally isn't going to be feasible, and I now appreciate why those wheels aren't on PyPI - if I think of concrete improvement ideas I will get back to you.

Thanks,
Tom

I'd rather not
