### ISSUE TITLE
GroupNorm not well traced when export to onnx

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#32341]
## 🐛 Bug

First the problem is:

GroupNorm will traced to InstanceNorm when export to ONNX, and the graph generated is really complicated:

![image](https://user-images.githubusercontent.com/21303438/72591583-7c54b000-393b-11ea-91ed-ff717466cb85.png)

As you maybe notice, this is a simply layer of:

```
nn.GroupNorm(32, 128)
```

generated onnx.

Full code to generate this graph is :

```
import torch
from torch import nn
try:
    from alfred.dl.torch.common import device
except ImportError:
    print('install alfred-py first, pip install alfred-py')

torch.manual_seed(1024)
model_p = 'model_instancenorm.onnx'


class TinyModel(nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()
        self.expander = nn.Conv2d(3, 192, 1, 1)
        self.channel_c = nn.Conv2d(192, 128, 1)
        self.l = nn.GroupNorm(32, 128)

    def forward(self, x: torch.Tensor):
        x = self.expander(x)
        x = self.channel_c(x)
        print(x.shape)
        x = self.l(x)
        print(x.shape)
        return x


def export_onnx():
    model = TinyModel().to(device)
    sample_input = torch.rand(1, 3, 544, 1920).to(device)
    model.eval()
    torch.onnx.export(model, sample_input, model_p, input_names=[
                      'img'], output_names=['output'])
    print('onnx model exported. forward now...')
    # forward now


if __name__ == "__main__":
    export_onnx()
```

**the issue is that, group norm traced too much complicated, this can work but can not convert to many other frameworks such as TensorRT**.

But nowadays many decent methods were using GroupNorm more and more, such as FCOS, CenterMask, EmbedMask etc.

Hope pytorch optimize this node export way. At least reduce some node.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@jinfagang - not all ops in PyTorch have an exact equivalent in ONNX. Therefore, such operators (e.g. GroupNorm) are exported using a subgraph of ops that are in ONNX. Such graphs are perfectly legal ONNX graphs and all frameworks that adhere to ONNX spec should be able to work with them. 

Since you have opened this as a bug, I want to clarify that the graph that is exported for GroupNorm should be functionally equivalent. If you see otherwise, please let us know. Otherwise, I would suggest that we close this bug and possibly open a feature request for optimizing the GroupNorm op.

**Comment by garymm** [comment]
Closing due to lack of reply from @jinfagang. If there's a more optimal ONNX representation of GroupNorm, please re-open or open a new issue and clearly state what the better ONNX sub-graph would be.
