### ISSUE TITLE
onnx export : return output

### ISSUE THREAD

**Issue by pfeatherstone** [pytorch/pytorch#32434]
Line 62 of torch/onx/utils.py, please add the return statement

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by garymm** [comment]
Very unclear what this is asking for since the code has changed so much in the past 2 years. Please open a new issue with more details and a GitHub permalink to the code in question if this is still relevant.
If `torch.onnx.export` is not working for a particular model, include the model source code and the call to `export()`.
