### ISSUE TITLE
torch::jit::script::Module::clone() is not actually cloning parameters

### ISSUE THREAD

**Issue by ziyuv** [pytorch/pytorch#32519]
## 🐛 Bug

If you take a look at the highlighted section: https://github.com/pytorch/pytorch/blob/4314620ba05bc1867f6a63455c4ac77fdfb1018d/torch/csrc/jit/script/module.cpp#L191-L203, you would notice that when `IValue s` is not a module, `Module r` will simply register it. Therefore, the new module will share the same parameters.

## To Reproduce

1. Load any TorchScript model `model`
2. Run `clone = model.clone()`
3. Find any parameter in `model` and that same parameter in `clone`, `isAliasOf` will evaluate to `true`

## Expected behavior

Expect `clone()` to deep copy  everything in a TorchScript model.

## Environment

N/A

## Additional context

N/A

cc @ezyang @gchanan @zou3519 @suo

**Comment by suo** [comment]
@jerryzh168: I feel that `clone()` is not well-defined and we are receiving many issues due to it not behaving as people expect.

I propose we follow more closely Python's scheme to avoid confusion:
- Implement a `deepCopy()` method on `script::Module` that clones all state of the module recursively. This includes cloning all tensors. The type should not be cloned; the new module should share the same time
- Implement `__deepcopy__` on the Python `torch.jit.RecursiveScriptModule` to call `deepCopy()` internally and return the new thing.
- If we have *any* other methods that do anything else, they should be explicitly hidden from the public API.

cc @bzinodev we were talking about this today

**Comment by suo** [comment]
Note that probably the above involves defining `deepCopy` on `IValue` as well.

**Comment by jerryzh168** [comment]
clone without cloning the type is clone_instance, we have that here: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.cpp#L216
`clone` is for cloning both type and instance actually. this is used when we want to modify the type of the cloned module, like in quantization. probably not going to be used for public I think

**Comment by suo** [comment]
@jerryzh168 `clone_instance` also does not clone parameters.

**Comment by jhhurwitz** [comment]
A deepcopy `clone`, if possible, would be useful for applications like multi-gpu training.

**Comment by ZolotukhinM** [comment]
Yeah, in the current state it probably would makes sense to:
1) change `clone_instance` to be a deep copy (i.e. add copying of tensors to it)
2) rename it to `clone` and make it the public API for cloning/copying
3) remove the current `clone` (that creates a new type) from the public API. It probably will still be used internally in implementations of freezing and quantization, but external users probably would never need that (~never would be able to use it correctly without understanding of underlying mechanisms)

**Comment by jhhurwitz** [comment]
It would be nice if clone looked something like this: https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/cloneable.h#L34

To align it better with the `nn::module` and (optionally) avoid the extra step of moving a copy to another device.

**Comment by bzinodev** [comment]
Yeah, I need this cloning for freezing to encapsulate the frozen module. I will experiment nn::module cloning. Thanks

**Comment by jerryzh168** [comment]
@bzinodev I believe `nn::module` cloning is for C++ API not for `script::Module`

**Comment by jerryzh168** [comment]
> Yeah, in the current state it probably would makes sense to:
> 
> 1. change `clone_instance` to be a deep copy (i.e. add copying of tensors to it)
> 2. rename it to `clone` and make it the public API for cloning/copying
> 3. remove the current `clone` (that creates a new type) from the public API. It probably will still be used internally in implementations of freezing and quantization, but external users probably would never need that (~never would be able to use it correctly without understanding of underlying mechanisms)

I think we still have use cases of `clone_instance` which does not deepcopy the Tensors, for example, when we are trying to quantize a model with very large weights, I'll probably add a new deepcopy method and keep both `clone` and `clone_instance` private

**Comment by jerryzh168** [comment]
> @jerryzh168 `clone_instance` also does not clone parameters.

parameter information is in types I think

**Comment by ziyuv** [comment]
Any update on the PRs? :)

**Comment by yulinhuyang** [comment]
hi everyone! I define my module  like this:

struct ConvModel : torch::nn::Module
{
  ConvModel(int stride, int stride_radio,int valid_querylen,torch::Tensor query_weight)
  {
    stride = stride;
    stride_radio = stride_radio;
    valid_querylen = valid_querylen;
    query_weight = query_weight;
  }
  torch::Tensor forward(at::Tensor gallery)
  {

    auto result = torch::nn::functional::conv1d(gallery, query_weight);
    return result;
  }

and  I use like this:

  auto replicas_module = torch::nn::parallel::replicate(share_module, devices);

but it error :  what():  clone() has not been implemented for ConvModel. Subclass torch::nn::Cloneable<ConvModel> instead of torch::nn::Module 

if  I  inhert it  torch::nn::Cloneable<ConvModel>

another error is happened ? can you give me some suggestion
