### ISSUE TITLE
invalid argument 2: out of range for Sparse matrix cuda() function

### ISSUE THREAD

**Issue by deepmipt-VladZhukov** [pytorch/pytorch#3258]
```
torch.sparse.LongTensor(torch.Size((1, 2, 3))).cuda()
```
raises an error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-170-910f9c37ab21> in <module>()
----> 1 sparse_zeros((1, 2, 3)).cuda()

/home/zhukov/anaconda3/envs/torch/lib/python3.6/site-packages/torch/_utils.py in _cuda(self, device, async)
     61             indices = self._indices().cuda(device, async)
     62             values = self._values().cuda(device, async)
---> 63             return new_type(indices, values, self.size())
     64         else:
     65             new_type = getattr(torch.cuda, self.__class__.__name__)

RuntimeError: invalid argument 2: out of range at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensor.c:23
```

**Comment by deepmipt-VladZhukov** [comment]
temporal solution is to use:
```
torch.cuda.sparse.LongTensor
```

**Comment by apaszke** [comment]
What's your PyTorch version? cc: @SsnL

**Comment by SsnL** [comment]
Not fixed, but I will look into this.

**Comment by SsnL** [comment]
Cause: `_indices()` and `_values()` are both empty. Since we neither support dimension with size `0` nor support a special sparse tensor size that contains dimI info, backend code errors when it tries to infer dimI from inputs, i.e., `indices, values, size`.

This, along with many other sparse issues, requires some special treatment to sparse tensor's sizes.  Properly fixing the issue requires a some API discussion and nontrivial code change. It will take some time to do so. I'll try to come up a detailed explanation post to discuss this.

For now, should we do a temporary solution? It would be easy to do an additional constructor taking in `torch.Size, long dimI`, and special case this in `_utils._cuda()`.

cc @ezyang

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/pull/5361 fixes this. I've verified that the error goes away on master.
