### ISSUE TITLE
Delayed cuda error after wrong indexing

### ISSUE THREAD

**Issue by kingjr** [pytorch/pytorch#32832]
## 🐛 Bug

When a wrong indexing is used for a tensor on cuda, I don't get an error right away, but at the following cuda operation.
 
## To Reproduce

```python
import torch
    
foo = torch.randn(2).cuda()
foo = foo[range(10000)]  # should not be legal

bar = torch.randn(2) # goes fine
bar.cuda()  # crashes because of foo indexing
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-d7c1dd574d04> in <module>
      5 
      6 bar = torch.randn(2) # ok
----> 7 bar.cuda()  # crashes

RuntimeError: CUDA error: device-side assert triggered
```

## Expected behavior

The error should occur at the indexing level to facilitate debugging.

## Environment
- Python 3.6
- PyTorch Version 1.4.0 installed via pip command, as given by torch website.
- Ubuntu 18.04.3 LTS
- GPU: Quadro GP100
- Nvidia driver version 418.116.00
- Cuda used to buld pytorch: 10.1
- Cmake 3.10.2

@fmassa

**Comment by ngimel** [comment]
This is expected behavior because cuda execution is asynchronous, and your subsequent operations are enqueued before the error actually happens. To get errors as they occur run with env variable CUDA_LAUNCH_BLOCKING=1 (this should be done for debugging purposes only, because it is a pretty big performance penalty), or call torch.cuda.synchronize() after each operation.
