### ISSUE TITLE
Migrate `masked_select` from TH to ATen (CUDA)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#33054]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko as this affects complex tensor bring up

**Comment by ezyang** [comment]
This is high priority because `masked_select` is called when printing tensors

**Comment by kurtamohler** [comment]
Unassigned myself from this for now, in case @mingfeima wants to take it, since he's porting the CPU version in PR #33269

**Comment by mingfeima** [comment]
@kurtamohler please continue with CUDA part. I am working for Intel so mostly work on CPU part...

Also feel free to drop any comment for the CPU code as well :)

**Comment by kurtamohler** [comment]
I started off measuring the performance of `masked_select` using the current implementation, so I can compare with my implementation once I have it working. My performance script is here: https://github.com/kurtamohler/pytorch-perf-test-scripts/blob/master/masked_select/masked_select-perf.py

Looks like the current CUDA implementation is slower than single-core CPU in every case. It also sounds like mingfeima has sped up the CPU version, so the difference will only increase. Right now, the CPU version is about 40-60x faster than cuda with input tensors of size 1,000. That speedup decreases as the tensor size increases, and it bottoms out at about 1-2x around tensor size 100,000.

So while I'm porting this, I'll look for ways to improve performance. There's bound to be a lot of room for improvement since this function is very logically parallelizable.

**Comment by kurtamohler** [comment]
The performance of my latest commit is pretty similar to the original TH cuda implementation's performance. However, a performance profile from py-spy shows that only about 5% of time is spent in the cuda-specific portion of masked_select that my commits added on top of mingfeima's cpu work. The vast majority of time is spent in `masked_select_out_impl` in `TensorAdvancedIndexing.cpp` before `masked_select_stub` is called to dispatch to either the cpu or cuda masked_select kernels. So it should be possible for me to replace all the shared cpu/cuda code with something that is much more performant in cuda.

**Comment by kurtamohler** [comment]
I'm having an issue with calling `AT_WARN()` from a cuda source file, on this line: https://github.com/pytorch/pytorch/compare/master...kurtamohler:port-masked_select-cuda#diff-6bd62f9ef0c4de92f12b98666db8ac90R191

This other `AT_WARN()` call from a cpu source file is exactly the same as far as I can tell: https://github.com/pytorch/pytorch/compare/master...kurtamohler:port-masked_select-cuda#diff-5312d553f68ae8e12304275aab5ac43cR576

Yet when my `AT_WARN()` is called, I get an extra bit of garbagey text that comes out:
```
/home/kurtamohler/development/pytorch-masked_select-cuda/aten/src/ATen/native/cuda/IndexKernel.cu:119: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
  "please use a mask with dtype torch.bool instead.");
```

That extra `"please use a mask with dtype torch.bool instead.");` at the end shows up only from the cuda call, not in the cpu call. Maybe AT_WARN doesn't work properly when nvcc builds it?

**Comment by kurtamohler** [comment]
I found a workaround for the AT_WARN issue I was having. Apparently the issue has something to do with the __FILE__ macro in nvcc, because if I avoid using it, I no longer see the extra line printed out at the end of the warning.

**Comment by kurtamohler** [comment]
The performance of my implementation is fairly close to the original one. It's a little worse for smaller tensors, but a little better for larger tensors.

Unfortunately it's not as possible to improve the performance as I had hoped earlier on. The main performance sink is calculating a cumulative sum of the mask, so that we know where each selected element from the input will be placed in the output. Parallelizing the cumulative sum is not so simple. The best possible parallelized solution has a logarithmic runtime. I'm assuming that `thrust::inclusive_scan` offers one of the most performant solutions available (although I haven't found any documentation saying whether it has logarithmic runtime or not). My implementation calls `thrust::inclusive_scan` directly (I first tried `at::cumsum`, and it gave a little bit worse performance), and that call is about 60% of the total runtime inside `masked_select` if I use inputs size 1,000 or 10,000, and up to about 84% with input size 10,000,000. So I think the only way I could make any significant performance improvements would be if I could implement a significantly faster version of `thrust::inclusive_scan`, which is probably not a realistic goal.

Below is the performance comparison between my current implementation and the original TH one.


dtype | tensor_size | mask_true_ratio | TH cuda time, seconds | ATen cuda time, seconds | ATen speedup
-- | -- | -- | -- | -- | --
torch.float64 | 1000 | 0 | 0.0008886 | 0.0009074 | 0.9792814635
torch.float64 | 1000 | 0.25 | 0.0007048 | 0.0009164 | 0.7690964644
torch.float64 | 1000 | 0.5 | 0.0007026 | 0.0009192 | 0.7643603133
torch.float64 | 1000 | 0.75 | 0.0007026 | 0.0009174 | 0.7658600392
torch.float64 | 1000 | 1 | 0.0007028 | 0.0009184 | 0.7652439024
torch.float64 | 10000 | 0 | 0.000736 | 0.000915 | 0.8043715847
torch.float64 | 10000 | 0.25 | 0.0007414 | 0.0009346 | 0.7932805478
torch.float64 | 10000 | 0.5 | 0.000742 | 0.0009106 | 0.8148473534
torch.float64 | 10000 | 0.75 | 0.0007418 | 0.0009046 | 0.8200309529
torch.float64 | 10000 | 1 | 0.0007414 | 0.0008452 | 0.877188831
torch.float64 | 100000 | 0 | 0.0012012 | 0.0009282 | 1.294117647
torch.float64 | 100000 | 0.25 | 0.001206 | 0.0008956 | 1.346583296
torch.float64 | 100000 | 0.5 | 0.0012028 | 0.0008952 | 1.343610366
torch.float64 | 100000 | 0.75 | 0.0012072 | 0.000897 | 1.345819398
torch.float64 | 100000 | 1 | 0.0012098 | 0.0008972 | 1.348417298
torch.float64 | 1000000 | 0 | 0.0080662 | 0.0058624 | 1.375921124
torch.float64 | 1000000 | 0.25 | 0.0080976 | 0.0058758 | 1.378127234
torch.float64 | 1000000 | 0.5 | 0.0081056 | 0.0058756 | 1.379535707
torch.float64 | 1000000 | 0.75 | 0.008133 | 0.0058746 | 1.384434685
torch.float64 | 1000000 | 1 | 0.0081642 | 0.0058806 | 1.388327722
torch.float64 | 10000000 | 0 | 0.0582518 | 0.0533958 | 1.090943482
torch.float64 | 10000000 | 0.25 | 0.0588252 | 0.0538952 | 1.091473823
torch.float64 | 10000000 | 0.5 | 0.0590256 | 0.0539744 | 1.093585107
torch.float64 | 10000000 | 0.75 | 0.0591236 | 0.0540118 | 1.094642282
torch.float64 | 10000000 | 1 | 0.0593282 | 0.054034 | 1.09797905
