### ISSUE TITLE
About parallel_for(const int64_t begin, const int64_t end, const int64_t grain_size, const F& f)

### ISSUE THREAD

**Issue by ghost** [pytorch/pytorch#33141]
## ❓ Questions and Help
when I see aten/src/ATen/native/AveragePool2d.cpp, I don't understand at::parallel_for(0, nInputPlane, 0, [&](int64_t start, int64_t end) {...}), why is the value of third parameter equal to 0. I think the value of grain_size is not equal to zero. Can you tell me the reason of situation? 

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @VitalyFedyunin @ngimel

**Comment by cpuhrsch** [comment]
In the case of [OpenMP](https://github.com/pytorch/pytorch/blob/861194e3f8fe59b6877f62722fa1cd28b69ba45b/aten/src/ATen/ParallelOpenMP.h#L16) a grain_size of 0 simply means it will always be run in parallel, no matter the number of elements to be considered. The work that is being parallelized is pretty heavy, so that each chunk requires [a lot of work](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/AveragePool2d.cpp#L32), which is why I imagine this value was chosen.
