### ISSUE TITLE
rpc.shutdown() does not abort pending sends created in separate threads.

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#33208]
## 🐛 Bug

If there was a recent call to `agent.send()` by some RPC thread and then we shutdown RPC with `rpc.shutdown()`, the shutdown process could hang because we could still be waiting on Gloo to wait for sends to be completed in `pendingSends->wait()` in`handleSend`: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/process_group_agent.cpp#L384

A similar issue would have occured by calling into `recvWork->wait()` in `ProcessGroupAgent::listenLoop()`, however we abort these calls when shutting down: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/process_group_agent.cpp#L256

We have similar hooks in Gloo to abort waits on send as well, so we should abort these during shutdown also.

This issue was reported by @pritamdamania87 

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by Baranowski** [comment]
@rohan-varma can you please elaborate on the scenario you expect to be buggy? It seems you expect `rpc.shutdown()` to interfere somehow with `pendingSends->wait()`.

I have tried to reproduce this by inserting `sleep(5)` in various spots in `ProcessGroupAgent::handleSend()` and `ProcessGroupGloo::SendWork::wait()` but still my RPC workers shut down cleanly.

BTW, the links to the source code in the issue description got out of sync with the code, since they point to hard-coded line numbers of the current `master`, rather than a specific revision.

**Comment by rohan-varma** [comment]
@Baranowski thanks for flagging, this should actually be fixed by https://github.com/pytorch/pytorch/pull/34413. 

`rpc.shutdown()` also accepts a flag `graceful` that is by default True, meaning that all workers will wait for outstanding requests to be processed before shutting down. If this flag is passed in as False, then each worker will attempt to shutdown as quickly as possible by cancelling all pending work. 

I'll close the issue for now, though if you are able to reproduce the issue with `rpc.shutdown(graceful=False)`, please feel free to reopen.
