### ISSUE TITLE
Include PyTorch version in serialization formats

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#33307]
Based on discussion in #31877, it is useful for tooling (and users) to know which version of PyTorch produced a particular binary. The easiest way to do this is probably to put `torch.__version__` into the serialization format somewhere. This will probably only go into the "Eager v2" and "Script v4" formats described [in this comment](https://github.com/pytorch/pytorch/issues/31877#issuecomment-572761949) (as well as any future formats).
 
* add version information to C++ (since the jit serialization needs to know this to add it to the serialized binary)
* add a file to the serialized zip called `archive/pytorch_version` or something that will contain the version string

**Comment by lutzroeder** [comment]
@driazati @zdevito @ezyang what are next steps?

`archive/producer` would be a better name for the file instead of `archive/pytorch_version` as it should also include the name of the package that created the file. For example, `pytorch 1.4.0` or `torch 1.4.0`. 

If adding this in `torch.serialization` is all that is need I can submit a PR. 

`PyTorchStreamWriter::setup` would be the other place but not sure there is a way to get the Python module name and version in C++?

**Comment by driazati** [comment]
In order to avoid confusion about versions in the serialized code, we'd rather have a library function that will tell you the version of some zip file. This can encode all the rules from #31877 so you don't have to track those and should still let you figure out the right info you need

**Comment by lutzroeder** [comment]
@driazati That is not going to work. Netron for example doesn’t have Python or C++ dependencies and needs to work without PyTorch being installed.

**Comment by driazati** [comment]
Closing this to collapse discussion back to the other issue
