### ISSUE TITLE
libtorch CUDA version compile and link error

### ISSUE THREAD

**Issue by ygwangthu** [pytorch/pytorch#33415]
I compile the source libtorch [master] with  windows10, vs2017, python3.8, cuda 10.1. 
![image](https://user-images.githubusercontent.com/19385144/74637752-91746700-51a5-11ea-97e0-c7cf4700e84c.png)
It can run sucessfully.
![11](https://user-images.githubusercontent.com/19385144/74637663-5c681480-51a5-11ea-840e-ccc19fa696f5.png)
![12](https://user-images.githubusercontent.com/19385144/74637672-61c55f00-51a5-11ea-80ae-b24f49e78923.png)

However, when I link the library
![image](https://user-images.githubusercontent.com/19385144/74637703-7275d500-51a5-11ea-98c8-624a1ac62ace.png)

The compiler tells me the error 
![image](https://user-images.githubusercontent.com/19385144/74637843-c2ed3280-51a5-11ea-844d-1456e55df84f.png)

If I add the CPU version
![image](https://user-images.githubusercontent.com/19385144/74637908-e2845b00-51a5-11ea-9fa1-39fd73d1bbc0.png)
The comipler does not have wrong information. But I still can not use the cuda version, since libtorch can not excute with the CUDA support
![13](https://user-images.githubusercontent.com/19385144/74638262-8b32ba80-51a6-11ea-8d84-75f14b362839.png)

Has libtorch been decomposed into a cpu version and cuda version? I think it is a critial bug for the decomposition. 
One more thing, the prebuilt version in https://pytorch.org/ is okay.

**Comment by peterjc123** [comment]
Yes, even if you use the CUDA APIs of LibTorch, you need to link against `torch_cpu.lib`. And the `torch.lib` is only a empty stub. Maybe you need to link against `torch_cuda.lib` as well. As for your second problem, it is related to https://github.com/pytorch/pytorch/issues/31611. The workground is to explicit load `torch_cuda.dll` by calling `LoadLibraryA("torch_cuda.dll");`.

**Comment by ygwangthu** [comment]
cool! problem has been solved! thanks a lot!

**Comment by LESSuseLESS** [comment]
The root cause is,

1. at::cuda::detail::CUDAHooks.cpp uses a static initializer "REGISTER_CUDA_HOOKS(CUDAHooks);" to register the critical CUDAHooks class. Without this class correctly registered, default class will report a hard-coded device count of 0.
2. torch::cuda::device_count() goes through the hook as in at::detail::getCUDAHooks().getNumGPUs(), hence getting 0.
3. at::cuda::getNumGPUs() doesn't go through the hook, hence getting a correct non-zero count.

I think it is plainly wrong to count on static initializer to register an important class like this:

1. The given workaround of adding "-INCLUDE:?warp_size@cuda@at@@YAHXZ" is NOT acceptable in long run.
2. It is totally legit for a linker not to link an .a in these scenarios.
3. Forcing linking with -whole-archive has its own downsides: larger sizes of binary, potentially collision of symbols, etc..

I would recommend completely change the way how CUDAHooks is registered in future versions.
