### ISSUE TITLE
Sparse tensor persistency - error when loading

### ISSUE THREAD

**Issue by HekpoMaH** [pytorch/pytorch#33439]
## 🐛 Bug 🐛

When loading a saved sparse tensor an error occurs: `RuntimeError: size is inconsistent with indices: for dim 0, size is 3 but found index 140115406052656`
Clearly, that is impossible (can't even fit such a large tensor on my memory)

## To Reproduce

1. Install PyTorch and torch-sparse
1. Run the below code (which produces the above error for me)

```
import torch
x=torch.zeros(3,3)
x[1][1]=1
x=x.to_sparse()
torch.save(x, './scratch/test4e')
y = torch.load('./scratch/test4e')
```

## Expected behavior

Loads `y` normally ...

## Environment
```

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 440.59
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] torch                     1.4.0                     <pip>
[conda] torch-cluster             1.4.5                     <pip>
[conda] torch-geometric           1.4.1                     <pip>
[conda] torch-scatter             2.0.3                     <pip>
[conda] torch-sparse              0.5.1                     <pip>
```

cc @ezyang @gchanan @zou3519 @vincentqb

**Comment by VitalyFedyunin** [comment]
Reproducible on current master

**Comment by albanD** [comment]
This is most likely a duplicate. Still high priority.

**Comment by Baranowski** [comment]
The cause is in `_legacy_load()` in `torch/serialization.py`. In line 766 we try to load the entire tensor (`result = unpickler.load()`) and validate that indices are valid. But the indices are stored in another (dense) tensor and its storage has not yet been loaded by this point. The storages will be only loaded in the following statements of the same function:

```
    766     result = unpickler.load() # Note-to-self: this uses storages
    767 
    768     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)
    769 
    770     offset = f.tell() if f_should_read_directly else None
    771     for key in deserialized_storage_keys:
    772         assert key in deserialized_objects
    773         deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly) # Note-to-self: but they are read only here
    774         if offset is not None:
    775             offset = f.tell()
    776 
    777     return result
```

Possible solutions:
* Load storages before the tensor. This would require to compute the size of the serialized tensor, in order to find offset of the storages.
* Introduce a hook that fires after the entire pickle is loaded that would allow `sparse_coo_tensor` to register sanity checks to be performed afterwards.
* For the purpose of (de-)serialization convert indices and values to ArrayRef (this might mean duplication of data, if several tensors share the same storage).

I'm leaning towards the first option but will think more about it and come back.

**Comment by ezyang** [comment]
Hmm. This seems like some very useful sleuthing. But what I am a little uncertain about, is why the validation happens before we have everything. Is this because we're doing something like allocating the sparse tensor upfront with uninitialized storage, and then setting the storage to real data afterwards? I wonder why we do that...

**Comment by Baranowski** [comment]
> Is this because we're doing something like allocating the sparse tensor upfront with uninitialized storage, and then setting the storage to real data afterwards

It appears so. We are creating a storage with desired size before the data is read, and I think that means allocation.

> I wonder why we do that...

My guess is simply developers' convenience. The storages are serialized at the end of a pickle. So it's easier to initialize objects in the order they appear in the file.

As for why that's the order of the file, I have two guesses:

* The only alternative I can think of would be serializing each storage eagerly the first time it's needed, and then referring to it later in the pickle. It's not obvious to me that it's a better choice.
* Apparently the old serialization format supported storage views, so the ordering might be an artefact from that time. You only know what view has to be serialized once you process all the objects using that particular storage.

**Comment by Baranowski** [comment]
It's challenging to skip tensors and read in storages first because the size of the tensor pickle is not known. `cPickle` has the `noload()` method on `Unpickler` to do just that but PyTorch by default uses the (python) `pickle` which doesn't offer this functionality.

JIT has its own `Unpickler` and it could probably be modified to read data without instantiating objects but there is a risk it might not keep up with future changes to the `pickle` module, and besides there must be a reason why JIT's `Pickler` and `Unpickler` are not being used already for that.

Next up, I will explore creating a hook for `sparse_coo_tensor` to do its validation after storages are properly filled.
