### ISSUE TITLE
torch.rfft returns NaNs for some half precision CUDA inputs

### ISSUE THREAD

**Issue by SamPruden** [pytorch/pytorch#33485]
## 🐛 Bug

When using half precision and CUDA, torch.rfft sometimes returns NaNs.

## To Reproduce

```Python3
size = 64
wn = torch.rand(size, size, size, dtype = torch.half, device = "cuda")
assert torch.isfinite(wn).all()
wn_freq = torch.rfft(wn, 3, onesided = True)
assert torch.isfinite(wn_freq).all() # <- FAILS
```

Setting `size` to 32 or smaller seem to work fine, 64 or bigger seems to fail. I haven't tested this rigorously. I'm 80% sure that I was running the same code on the same setup with the same version without hitting this error a few days ago, but I can't be sure. The issue survives a restart of the machine.

## Expected behavior

Not NaNs.

## Environment
Google Colab.

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.5
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect
```

cc @ngimel

**Comment by xwang233** [comment]
Hi @SamPruden , thanks for the issue! 

I checked your script, and the first element of the output tensor is either `nan` or `inf`. This is because in a FFT process, the first element of the output is the summation of all input elements. In your example, all elements are randomly sampled from [0,1), so the expected summation is `64^3 * 0.5 = 131072`, which is well beyond the range of a half precision float number ~65536 (see [this](https://en.wikipedia.org/wiki/Half-precision_floating-point_format)). This is also confirmed in Nvidia cuFFT documentation at [here](https://docs.nvidia.com/cuda/cufft/index.html#accuracy-and-performance). 

> Half precision transforms might not be suitable for all kinds of problems due to limited range represented by half precision floating point arithmetics. Please note that the first element of FFT result is the sum of all input elements and it is likely to overflow for certain inputs.

To resolve this overflow problem, I would suggest use either higher precision such as `torch.float`, or change the distribution of the input tensor such as `torch.randn`.

**Comment by SamPruden** [comment]
Oh. Now that you mention it @xwang233, that's quite obvious. Sorry for the frivolous issue and taking your time! I wonder if it might be worth adding a short warning about that to the function documentation to stop other people having dumb moments like mine.
