### ISSUE TITLE
torch.nn.utils.prune.remove prevents future model training

### ISSUE THREAD

**Issue by SamG97** [pytorch/pytorch#33618]
## 🐛 Bug

After calling `torch.nn.utils.prune.remove` on a parameter, future calls to `loss.backward()` result in:
```
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

## To Reproduce

Minimal code example:
```python
import torch
import torch.nn as nn
import torch.nn.utils.prune as prune

LR = 10


class ExampleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(512, 512, batch_first=True)
        self.linear = nn.Linear(512, 32)

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.linear(out)


# Initialise model
model = ExampleModel()
model = model.cuda()

# Prune weights
lstm_weights = [
    p for p in dict(model.lstm.named_parameters()).keys() if "weight" in p
]
for p in lstm_weights:
    prune.l1_unstructured(model.lstm, p, 0.5)
    prune.remove(model.lstm, p)
model.lstm.flatten_parameters()  # Make parameters contiguous

criterion = nn.MSELoss()
for step in range(10):
    print(f"Step {step}")
    # Dummy training data
    x = torch.randn(1, 10, 512, device="cuda:0")
    y = torch.randn(1, 10, 32, device="cuda:0")

    # Forward pass
    model.zero_grad()
    z = model(x)

    # Compute loss & gradients
    loss = criterion(z, y)
    loss.backward()

    # Update params
    for p in model.parameters():
        p.data.add_(-LR, p.grad.data)

print("Done training")
```

## Expected behavior

The model should be able to train normally. It is able to successfully complete the first training iteration but dies on the second iteration; i.e. the above code prints:
```
Step 0
Step 1
```
before dying with the above error.

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.16.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 440.59
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] numpydoc==0.9.1
[pip3] torch==1.4.0
[pip3] torchaudio==0.3.1
[pip3] torchtext==0.5.0
[pip3] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch
```

## Additional context

The main motivation for wanting to call `prune.remove` in the first place is that I would like to use a pruning schedule as given by [this paper](https://arxiv.org/abs/1710.01878) and so want to call `prune.l1_unstructured` multiple times throughout training to gradually increase the level of sparsity. My training process works fine when training on the CPU by just calling this method without using `prune.remove` but when using the GPU, I get the warning:
```
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cudnn/RNN.cpp:1266: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
```
printed to the console on every minibatch. This seems to be because a pruned parameter `weight` is renamed to `weight_orig` and `weight` becomes a computed attribute which CuDNN is not happy about. The training process still works fine but this console spam makes the console useless for any logging during training (and if the warning is to be believed, the non-contiguous weights could be problematic when trying to train larger models). I therefore was trying to use `prune.remove` to fix the pruned values to 0 but ran into the problem above.

cc @ezyang @gchanan @zou3519

**Comment by albanD** [comment]
cc @mickypaganini who is the original author of the module. Do you know where this comes from?

**Comment by mickypaganini** [comment]
Thanks for the detailed documentation of the issue.

This has to do with RNNs modifying their `_flat_weights` every time an attribute is set. This is impacted by pruning, because, when we prune, we set a new attribute (`weight`), and, as a result,  the RNN-specific `_flat_weights` will now contain a tensor instead of a parameter, and that tensor will accumulate gradient due to the mask*parameter op. Since, when `.remove()` is called, there is no `__setattr__()` call, `_flat_weights` still points to the tensor instead of the reinstated parameter. 

To unblock you in the short term, you can add `model.lstm._apply(lambda x: x)` before the `criterion = nn.MSELoss()` line, instead of the `.flatten_parameters()` call.

Meanwhile, I will change the last line of `remove()` from `module.register_parameter(self._tensor_name, orig)` to 
```
module._parameters[self._tensor_name] = None
setattr(module, self._tensor_name, orig)
```
which will trigger the resetting of `_flat_weights`.

The bigger issue is that you shouldn't have to call `.remove()` to begin with, but that has more to do with what exactly `.flatten_parameters()` is doing, and whether it can be used to make weights contiguous even if they are tensor attributes and not parameters... 🤔

Another alternative quick fix for you would be to move the line `model = model.cuda()` from where it is now to after the line `model.lstm.flatten_parameters()`, which also seems to work. In fact, in this case, I think you can now also remove the `.flatten_parameters()` call altogether because you are moving device after pruning.
* Issue: at this point, I thought I'd be able to also comment out the `prune.remove(model.lstm, p)` line, but instead I get : `RuntimeError: param_from.type() == param_to.type() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/cudnn/RNN.cpp:541, please report a bug to PyTorch. parameter types mismatch`, because, in an RNN, `model.cuda()` makes a call to `flatten_parameters()`, which fails with that error at this block (https://github.com/pytorch/pytorch/blob/v1.4.0/torch/nn/modules/rnn.py#L121-L129).
As far as I can tell, `_cudnn_rnn_flatten_weight` calls `_copyParams` which calls `_viewOrCopyParams`, which fails at this assertion (https://github.com/pytorch/pytorch/blob/v1.4.0/aten/src/ATen/native/cudnn/RNN.cpp#L541). Not sure how to debug all that... @ezyang 

Note to self: the RuntimeError is not directly cuda related. Removing `model = model.cuda()` and data movement to cuda, also throws it. But the contiguity warning is only present when moving stuff to cuda.

**Comment by ezyang** [comment]
Hmm. If you could crack it open in a debugger and get out the types (or recompile the assert to print the types) that would give some useful information.

**Comment by mickypaganini** [comment]
I actually can't repro the type mismatch error on master... Seems to work fine there. Types are all `CUDAFloatType`.

**Comment by SamG97** [comment]
Thanks for the response. The `model.lstm._apply(lambda x: x)` solution is working well for my use case for now until your patch is in a PyTorch release.

As you mentioned, it would be nice to not have to call `.remove()` since I'm having to store the masks anyway for masking gradients during training to keep pruned parameters at 0 but it seems like this is a larger design problem to solve.

**Comment by mickypaganini** [comment]
> As you mentioned, it would be nice to not have to call .remove() since I'm having to store the masks anyway for masking gradients during training to keep pruned parameters at 0 but it seems like this is a larger design problem to solve.

Right, and it's not pruning or reparametrization specific, so let's see if somebody on the RNN side will chime in here.

Note: the weight norm reparameterization will suffer from same issue, as it does not setattr, which will cause the RNN case to not behave as expected.

**Comment by albanD** [comment]
Corresponding PR has been merged.
