### ISSUE TITLE
XNNPACK raises a ton of warnings on compilation

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#33760]
Sample:

```
[959/3019] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-vscaleextexp/gen/avx512f-p5-scalef-x144.c.o
In file included from ../third_party/XNNPACK/include/xnnpack.h:15:0,
                 from ../third_party/XNNPACK/src/xnnpack/params.h:15,
                 from ../third_party/XNNPACK/src/xnnpack/vscaleextexp.h:11,
                 from ../third_party/XNNPACK/src/f32-vscaleextexp/gen/avx512f-p5-scalef-x144.c:16:
../third_party/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_1d_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:189:2: warning: ‘pthreadpool_function_1d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_1d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:196:2: warning: ‘pthreadpool_function_2d_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_2d_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:203:2: warning: ‘pthreadpool_function_2d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_2d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:212:2: warning: ‘pthreadpool_function_3d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_3d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_4d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Please fix! @AshkanAliabadi

**Comment by AshkanAliabadi** [comment]
Definitely. Thanks.

**Comment by ezyang** [comment]
These warnings are still happening!!

**Comment by mattip** [comment]
I think [this](https://github.com/Maratyszcza/pthreadpool/commit/29f0e2ced866e321d8293d4d1bdae71a5fdc90ec) is the relevant changeset in pthreadpool.

**Comment by AshkanAliabadi** [comment]
This is not an easy issue to resolve from within PyTorch.  Basically the core of the problem is that XNNPACK depends on updated version of pthreadpool which exposes a new backward incompatible interface, meaning that the new version of pthradpool is required for XNNPACK to build successfully.  On the other hand, we have NNPACK and QNNPACK which still rely on the old interface which the new version of pthreadpool has deprecated, hence the warnings.

We have two options as far as I can tell:

1) The easy solution would be to add an option to the pthreadpool library (and its CMake consequently) to allow the use of deprecated API without raising any warnings (which in turn is a result of tagging the old API with `__attribute__((__deprecated__))`.

2) The more involved solution would be to migrate NNPACK and QNNPACK to the new API which is a lot of work.

**Comment by mattip** [comment]
Isn't the NNPACK author also the author of pthreadpool?

**Comment by AshkanAliabadi** [comment]
Yes but NNPACK is not actively maintained and we can't expect him to do all the work. :) Do you want to do (1) mentioned above and I'll handle the PyTorch side.  If you don't have the time I can do both.
