### ISSUE TITLE
Allow typecasting of uint16 to float32

### ISSUE THREAD

**Issue by Sentient07** [pytorch/pytorch#33831]
## 🚀 Feature

Currently, `torch.tensor` does not support conversion of `uint16` to `float32` format. 

```
 temp = torch.tensor(np.ones((128,128,1)).astype(np.uint16), dtype=torch.float32, device="cpu")                                          
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-bc76fb094310> in <module>
----> 1 temp = torch.tensor(np.ones((128,128,1)).astype(np.uint16), dtype=torch.float32, device="cpu")

TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.
```

## Motivation

A present easy workaround as mentioned in the error message would be to convert to `int16` and then to `float32`. I think this redundancy can be removed

## Pitch

Useful in case of depth -> disparity conversion.

## Alternatives

```
 temp = torch.tensor(np.ones((128,128,1)).astype(np.uint16).astype(np.int16), dtype=torch.float32, device="cpu")
```
works just as fine for my case

**Comment by ailzhang** [comment]
This seems to be related our API between torch and numpy.

**Comment by mruberry** [comment]
The actual issue here is that PyTorch doesn't have a uint16 dtype, and that's why we don't support converting NumPy arrays of that type into torch tensors. As you mention, you'll have to convert to another dtype, like int32, first.

You could file a new issue requesting that PyTorch add support for the uint16 dtype, if you like.

**Comment by paramhanji** [comment]
I ran into this issue and couldn't afford to lose precision in my uint16 images. At the same time, I did not want to prematurely cast to int32 since I didn't want to transfer 2x bits.

I ended up packing into int16 as suggested. But while unpacking on the GPU, I first cast to int32 and apply a bitmask to extract my uint16 values. So the operations are:
```
a = np.random.randint(2**15, 2**16, dtype=np.uint16)    # A random uint16 number
t_int16 = torch.from_numpy(a.astype(np.int16)).cuda()   # Notice that only 16 bits are transferred
t_uint16 = t_int16.to(torch.int32) & (2**16 - 1)        # Extract required bits to match value store in "a"
```
This way, I get efficient transfer, as well as no loss of precision.
