### ISSUE TITLE
`max_pool2d` fails with channels_last and specific shapes.

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#34083]
To reproduce:
```python
x = torch.randn(200, 512, 28, 28, device='cuda', dtype=torch.float16).contiguous(memory_format=torch.channels_last)
y = torch.max_pool2d(x, 2, 2, 0, 1, False)
```

Result:

```
RuntimeError: max_pool2d_with_indices_out_cuda_frame failed with error code 0
```

cc @ngimel @VitalyFedyunin @jamesr66a

**Comment by VitalyFedyunin** [comment]
CC @jjsjann123

**Comment by xwang233** [comment]
The direct cause of the problem is at here https://github.com/pytorch/pytorch/blob/2ba74b741e75940649556ff50a032f97d321363e/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu#L377-L383

The third parameter of the cuda kernel launch, shared memory per block, exceeds 48 kb. If you change 512 to 256, it runs. If you change 512 to 257, it fails with the same error message. 

The cuda error code 0 is from a design at here 
https://github.com/pytorch/pytorch/blob/2ba74b741e75940649556ff50a032f97d321363e/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu#L402-L404
where the "last error" was already retrieved.

I will provide a fix to the problem. 

cc @ptrblck

**Comment by VitalyFedyunin** [comment]
Thanks @xwang233 this is very helpful
