### ISSUE TITLE
Complex support for torch.remainder

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#34266]
## 🚀 Feature
Add complex number support for `torch.remainder`.

## Motivation

When porting remainder from TH to ATen, I noticed that other operators, like `torch.div`, have support for complex numbers. It wasn't mathematically clear to me how to implement support for complex numbers in `torch.remainder`, and since the original TH implementation did not have it, it was outside the scope of that issue.

## Pitch

@nikitaved explained some of the details of how complex support could be implemented in these comments:

https://github.com/pytorch/pytorch/issues/24753#issuecomment-594253979

https://github.com/pytorch/pytorch/issues/24753#issuecomment-594723479

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by mruberry** [comment]
Sounds good, @kurtamohler! We would take a PR implementing this.

**Comment by aocsa** [comment]
Last week I was looking into this issue.  I created a [PR](https://github.com/pytorch/pytorch/pull/47606)  and asked for an internal review first. @Pearu suggested me to  do some research why numpy and Python 3 does not support remainder as this issue is about numpy compatibility. On the other hand @nikitaved suggested me to use a different definition that I found at [wolframalpha](https://www.wolframalpha.com/input/?i=remainder%286%2B4i%2C+3%2B5i%29) whis is:  `mod (a, b) = r * ((a - q * b) / (a - q * b).abs())`, where `q`, `r` are the div and reminder for reals. Note, I have done some tests and the definition suggested by @nikitaved and the definition found in  [wolframalpha](https://www.wolframalpha.com/input/?i=remainder%286%2B4i%2C+3%2B5i%29) [4] doesn't return the same result.   

A few disclaimer here, I am lacking the math knowledge to know the answers and my findings are addressed for looking standard API definition and compatibility.

- There are neither python3 nor numpy compatibility supporting remainder for complex numbers [1, 2, 5]. Also, matlab does not support remainder for complex numbers [3].
- Computing mod for complex numbers as it used in [wolframalpha](https://www.wolframalpha.com/input/?i=remainder%286%2B4i%2C+3%2B5i%29) [4] is defined as follows:  `mod(a,b) = a - (a / b).floor() * b` . This [](https://www.wolframalpha.com/input/?i=remainder%286%2B4i%2C+3%2B5i%29) is a possibility but that wouldn't be consistent with python.
- Moreover, in order to compute the latest equation we have to define  the `floor` function for complex numbers. As it is defined as the largest integer less than or equal to the real number given and since "less than or equal to" isn't defined for complex numbers you can't have a floor function for them [5]. This is usually the most accepted understanding of why operators like floor, trunc, fmod, remainder doesn't support complex numbers.

So I am creating this thread here to discuss the next steps. Based on this quick research I can conclude that even though we can use one of the definition suggested by Nik  for the remainder function, that wouldn't be consistent with Python/Numpy though. cc @mruberry, @rgommers, @pearu, @nikitaved  

**References**:

[1] Not for complex numbers. Instead, convert to floats using abs() if appropriate.

[https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex)

[2] Changed in version 2.3: Using divmod() with complex numbers is deprecated.

[https://docs.python.org/2/library/functions.html?highlight=remainder](https://docs.python.org/2/library/functions.html?highlight=remainder)

[2] The `rem` function does not support complex numbers: all values must be real numbers.

[https://www.mathworks.com/help/symbolic/rem.html](https://www.mathworks.com/help/symbolic/rem.html)

[4] Mod for complex numbers in wolframalpha. 

[https://www.wolframalpha.com/input/?i=remainder(6%2B4i%2C+3%2B5i)](https://www.wolframalpha.com/input/?i=remainder%286%2B4i%2C+3%2B5i%29)

[5] Doing floor division on both real and imaginary parts makes some sense if we document that Gaussian integers are the result. That wouldn't be consistent with Python.

[https://github.com/numpy/numpy/issues/13236](https://github.com/numpy/numpy/issues/13236)

**Comment by ezyang** [comment]
cc @boeddeker, perhaps.

**Comment by ezyang** [comment]
Based on a quick read of your summary, though, this sounds like a good excuse to not do torch.remainder for complex numbers, and instead prioritize one of other high priority complex issues, if you're looking to help with complex.

**Comment by boeddeker** [comment]
@ezyang Sorry, I have never worked with complex numbers and operations that require an ordering (e.g. smaller).
I personally would follow here python and wouldn't implement the operation, because it is not well-defined.
Numpy has already defined some operations that require ordering, but I don't know a use case for it.

**Comment by anjali411** [comment]
@aocsa thanks for starting this thread. And I agree that operations like floor, trunc etc., don't make sense for complex numbers, and exactly why we don't support them in torch now. Going by the definition on wikipedia https://en.wikipedia.org/wiki/Modulo_operation, it's not even mathematically possible to satisfy the condition that quotient is an integer while `|remainder| < |divisor|`, for e.g. (mod(6, 5i), no matter what integer q you choose, |remainder| > |divisor|).

So, I don't think we should support `torch.remainder` for complex numbers.

In future, we can consider supporting remainder if and when we support complex polar representation, since we can just look at the magnitude and ignore the phase ...

**Comment by nikitaved** [comment]
@anjali411 , good catch! But it is still possible with the quotient being a Gaussian number (complex numbers with integer coordinates).

**Comment by aocsa** [comment]
All right, thanks @anjali411, @ezyang.  I will close this issue and look other high priority complex issues. cc @mruberry, @pearu, @nikitaved  @rgommers.

**Comment by mruberry** [comment]
Thanks for resolving this issue, @kurtamohler and @aocsa.

**Comment by anjali411** [comment]
@aocsa would you like to work on adding vectorization for `torch.complex` and  `torch.polar` https://github.com/pytorch/pytorch/issues/35312

**Comment by aocsa** [comment]
Sure, I was looking into it, and I found a PR already merged. 
https://github.com/pytorch/pytorch/pull/39617

So I guess the task is adding work on top of that?

**Comment by mruberry** [comment]
One final thought is that we may want to reflect this thinking in our documentation, especially when the documentation is revised to consistently use "Supports..." statements it would be nice to be clear that we explicitly do not support complex remainder (same with complex comparison operators).

**Comment by anjali411** [comment]
> Sure, I was looking into it, and I found a PR already merged.
> #39617
> 
> So I guess the task is adding work on top of that? cc @anjali411

yeah that PR didn't add support for vectorization which is something that would be very useful to have

**Comment by anjali411** [comment]
> One final thought is that we may want to reflect this thinking in our documentation, especially when the documentation is revised to consistently use "Supports..." statements it would be nice to be clear that we explicitly do not support complex remainder (same with complex comparison operators).

yes I agree!

**Comment by rgommers** [comment]
> One final thought is that we may want to reflect this thinking in our documentation, especially when the documentation is revised to consistently use "Supports..." statements it would be nice to be clear that we explicitly do not support complex remainder (same with complex comparison operators).

@aocsa or @kurtamohler is one of you doing this for `remainder`?

**Comment by kurtamohler** [comment]
> @aocsa or @kurtamohler is one of you doing this for `remainder`?

I'm happy to do it, unless you'd rather do it @aocsa

**Comment by aocsa** [comment]
Ohh sure not problem, go ahead. 
Thanks @kurtamohler.
