### ISSUE TITLE
Allow accessing or save/restore of SavedVariables

### ISSUE THREAD

**Issue by neonbjb** [pytorch/pytorch#34273]
## 🚀 Feature
Allow users to save and restore the state of the intermediate variables used to compute the backward pass of a graph.

## Motivation
Some interesting model parallelism schemes involve splitting a computational graph up into several chunks, then scheduling the forward and backward passes on these chunks so that the CPU/GPU is saturated on each computational node. This effectively means that each node might perform several forwards or backwards in a row. As a result, the node needs to save the autograd state after each forward so that it can "get back to it" later when the gradients are available to it.

## Pitch
In order to support this, there needs to be a way to save the intermediate variables (in autograd lingo, the ```SavedVariables``` which many ```Nodes``` retain) after a forward pass, and restore them before a backward pass.

This save/restore could be implemented in Python if the SavedVariables of a Node were explosed, perhaps through the interface in python_cpp_function.h.

Alternatively, the save/restore could be implemented directly into each Node. Calling save() could create some sort of compressed bundle which could be restored on an equivalent graph with a call to a restore() function.

## Alternatives

The only workaround that I know of right now is to just build a new graph every time you perform a forward pass. You can then perform backward() on that graph once you have the gradients from the adjacent node and dispose of it. The problem with this approach is it is wasteful of memory. In most cases, you do not need to copy all of the model parameters nor the entire autograd graph, for example.

## Additional context

I'd be interested in implementing this if there is interest. I've done some of the work for the first solution in the pitch already as a proof of concept and it would be trivial to clean up and submit as a PR. 

If you wanted to go with the second solution, I'd need some guidance on how best to bundle and serialize multiple variables together.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by neonbjb** [comment]
This is more or less what I'm requesting. I'm still playing with it to test how usable it is.

https://github.com/neonbjb/pytorch/commit/8ddcba20fd5744d877bcf03101cc86fd1bfff74e

**Comment by gchanan** [comment]
SavedVariables is an implementation detail that changes regularly.  Can you, instead, write your own custom Function implementations to avoid the recompute?

**Comment by albanD** [comment]
As greg mention, the main problem here is that we don't have a single way to implement Nodes in the graph.
The only api that nodes must have is the `release_variables()` that should release all buffers. But how these buffers are saved is "user-defined". In particular, our codegen has one way. Custom python autograd.Function has one for input/output otherwise the user can do whatever he wants. custom cpp autograd.Function is similar. And we have some special Nodes that are directly implemented in [here](https://github.com/pytorch/pytorch/tree/master/torch/csrc/autograd/functions) that are just custom cpp classes that store them in different ways.

One solution would be to use custom.Function for each node so that you can do whatever you want with the buffers (might be tricky if you want to do double backward though).

**Comment by neonbjb** [comment]
Alright, I can understand that. Feel free to close if you feel this doesn't warrant any other discussion. For now I'll use the modification linked above since it does seem to work with the models I've been running. I'll re-open if I come up with a better solution that might be more amenable to the torch team.

**Comment by albanD** [comment]
Feel free to ask on the forum: https://discuss.pytorch.org/ if you need any help for your custom implementation.

I'll close this issue for now.
Feel free to re-open if you have a general idea of things we could add!
