### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by FDuiv** [pytorch/pytorch#34366]
![image](https://user-images.githubusercontent.com/45262140/76094207-2e842c00-5ffd-11ea-9ba2-6b03827be759.png)

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

Given the size of the difference, this is most likely due to the fact that floating point operations are not commutative. So doing operations in different order can change the result by 1 bit.
