### ISSUE TITLE
ONNX export of nn.interpolate scripted module is broken due to removal of aten::__interpolate op

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#34718]
## Issue description

There's a recent change in jit scripting path for nn.interpolate operator. After aten::__interpolate operator is removed and the scriptable nn.interpolate module has become scriptable as part of this PR: https://github.com/pytorch/pytorch/pull/34514, the graph new graph is exported using hundreds of extra nodes.
This means that the the jit graph for interpolate op is now scripting the whole module and creates the inflated graph below for a single op:
torch.nn.functional.interpolate(x, mode="trilinear", size=(4, 4, 6))
[graph.txt](https://github.com/pytorch/pytorch/files/4330624/graph.txt)

Currently, this change broke onnx export of scripted nn.interpolate module, and the following tests are disable:
https://github.com/pytorch/pytorch/blob/8e8a37d7464638efef2bc0c372712b57e4b4f678/test/onnx/test_pytorch_onnx_onnxruntime.py#L1294

As part of this change, onnx export of torchvision Keypoint RCNN module is also broken.
 https://github.com/pytorch/pytorch/blob/8e8a37d7464638efef2bc0c372712b57e4b4f678/test/onnx/test_pytorch_onnx_onnxruntime.py#L349
https://l.facebook.com/l.php?u=https%3A%2F%2Fcircleci.com%2Fapi%2Fv1.1%2Fproject%2Fgithub%2Fpytorch%2Fpytorch%2F4791771%2Foutput%2F105%2F0%3Ffile%3Dtrue%26allocation-id%3D5e6ab6cf58b6cb1d3d495d0d-0-build%2F61B5E26C%26fbclid%3DIwAR0kYcxY742VnXh6lpnH4FckYIJAhE03bp8vcRWdS-Yh4PsylwBZBFA5Dfk&h=AT0tPobGkR1UpwhdxgJ3JEH7udDQRrgMW0GNWD7Smsq4_fqZD8DJnCqLT06ppG-kwzXrRA6k00KS40CiaaAjFtxblyXg8JwjmVqv7F0XPTD_hvQhUnSGj8lv5Zt5JDBfjDWZtTtacm8

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @eellison @suo

**Comment by spandantiwari** [comment]
With the change https://github.com/pytorch/pytorch/pull/34514, the TorchIR graph will now have many more nodes as compared to before. Is there any plan to optimize this to reduce/consolidate the nodes? Interpolate is a popular op and I am thinking about the perf impact of this change.

cc: @ebarsoum

**Comment by eellison** [comment]
Hi all, 

for context: we basically hacked in compilation of `torch.nn.functional.interpolate` when we were adding support for interpolate in the standard library, because we could not then compile it as python code. It was always the intention that we were going to work towards compiling the function normally, as we do for the rest of the standard library. This means that we can optimize through interpolate, remove away if statements and constant fold it as it were python code. It also means that we can decompose interpolate into ops which are easier to reason about. Imagine the guard elimination or codegen logic for `upsample_linear1d(Tensor self, int[1] output_size, bool align_corners, float? scales=None) -> Tensor` compared to the guard elimination pass for `aten::__interpolate(Tensor input, int? size = None, float[]? scale_factor = None, str mode = 'nearest', bool? align_corners = None, bool? recompute_scale_factor = None) -> Tensor`. 

As a result of the `aten::__interpolate` hack, we essentially had to maintain a separate interpolate version in `register_prim_ops`, `symbolic_script`, `nn.functional.interpolate`, and `onnx_export`. This is not very sustainable. 

When we were making the recent interpolate floats scales change, I said that we were going to remove "aten::__interpolate", and offered to implement it so we didn't have to duplicate work. We decided to land the float/scales PR with the duplication instead. 

It is true that there are more ops than there were previously. Personally I think the Pytorch JIT should should focus on compiling pytorch python code well, instead of making the IR composed of increasingly opaque ops with larger semantic meaning. 

As far as ONNX goes, if there is a divergence in approach here, there are a couple of options how to proceed: 
- ONNX could implement a pass on the uninlined graph, and replace function calls to `functional.interpolate` with a single op that it then has exporting logic for. I don't think this would be too difficult to do. 
- We could go through the normal mechanism of moving a python function into a natively declared builtin.

**Comment by eellison** [comment]
As far as 

> ONNX could implement a pass on the uninlined graph, and replace function calls to functional.interpolate with a single op that it then has exporting logic for. I don't think this would be too difficult to do.

I can help provide guidance and do code reviews to get this through.

**Comment by neginraoof** [comment]
Thanks Elias for providing the details and also suggestions.
I just did a perf test for the single interpolate op (that I have put the graph for) and I'm seeing 2x slowdown on jit script module compared to before.

About the suggestions for ONNX export:

I will look more into how the uninlined graph looks like and how it could be translated to an ONNX node. I need to see if we can do this without breaking the jit graph.
Even if possible, I think this has to be a temporary solution. I think for long term it's better to move all the code into a native builtin to help optimizing jit graph as well.

**Comment by jerryzh168** [comment]
we may need the same thing for quantization. @neginraoof let me know if you have any update on this

**Comment by neginraoof** [comment]
This PR addressed the issue: https://github.com/pytorch/pytorch/pull/35744
