### ISSUE TITLE
Sparse-dense matrix multiple not using multiple threads on CPU

### ISSUE THREAD

**Issue by bryan-he** [pytorch/pytorch#3472]
I am running a dense-sparse matrix multiply on CPU with a multicore machine.

Code:
    import torch

    print torch.get_num_threads()

    n = 10000
    nnz = 1000000

    v = torch.randn([nnz]).type(torch.DoubleTensor)

    ind = torch.rand(2, nnz).type(torch.LongTensor)

    A = torch.sparse.DoubleTensor(ind, v, torch.Size([n, n])).coalesce()
    B = torch.randn(n, n).type(torch.DoubleTensor)

    C = torch.mm(A, B)

`get_num_threads()` gives 28, and when I run the mm, 28 threads are started as expected.
However, running `top` shows that only one of the threads actually does any work, and all of the other threads have 0% CPU usage.

Tested on Python 2.7 with Pytorch built from source (commit 0e38d3bbb3dc3ea677ad24ac3aeef79fb7acdab6).

**Comment by ebetica** [comment]
This is expected behavior AFAIK, in general, multithreaded Sparse MM is inefficient for most workloads, and it's difficult to detect the cases when it is. If it's important to you, there is a multithreaded implementation in [Torch](https://github.com/torch/nn/blob/master/lib/THNN/generic/SparseLinear.c) which may be useful for your workloads.

**Comment by weiyangfb** [comment]
I think right now `mm(S, D) -> D` is parallelize at CPU: https://github.com/pytorch/pytorch/blob/c3817e85fabd59cb40a2c5b0a5c0ab5b5da3a01c/aten/src/ATen/native/sparse/SparseTensorMath.cpp#L492-L508

I am closing this right now, please feel free to open a new issue if needed
