### ISSUE TITLE
libTorch version not matching checked out version when building with build_libtorch.py

### ISSUE THREAD

**Issue by ksasso1028** [pytorch/pytorch#35210]
I have noticed that when building libtorch using build_libtorch script on the newest version, the TorchVersion file indicates it builds Torch 1.1. However if i build pytorch using the setup.py build command, the libtorch version will match the checked out version. Whats going on here?

Also where are the required libTorch libs needed for standalone c++ when you do setup.py build? the documentation indicates ../../tmp_install but i cannot even find that path

This happens on any linux setup i have tried.

cc @ezyang @seemethere

**Comment by seemethere** [comment]
This is most likely because the default version set in the `CmakeList.txt` is `1.1.0`, see https://github.com/pytorch/pytorch/blob/7ab25b2e6bc0ae4883248cef270c137313163965/CMakeLists.txt#L366

However the `setup.py` defaults to whatever is in the base `version.txt`, or gets overridden by the environment variable `PYTORCH_BUILD_VERSION`. What this means is that default `cmake` variable never actually gets used by any builds that use the `setup.py`.

The script `tools/build_libtorch.py` does not call the `setup.py` so it gets the default (and most likely forgotten) `1.1.0` version.

As another note, for release builds we're not actually using the `tools/build_libtorch.py` script anymore and instead are deferring to a method of using `python setup.py install` along with shell script to restructure the output archive to the correct file structure. (See: https://github.com/pytorch/builder/blob/master/manywheel/build_libtorch.sh)
