### ISSUE TITLE
Cuda Problem

### ISSUE THREAD

**Issue by shersoni610** [pytorch/pytorch#35270]
Hello,

I had Cuda10.2 installed on my machine but after reading Pytorch I installed
10.1 and changed /usr/local/cuda ->/usr/local/cuda-10.1 instead of cuda-10.2.
I am keeping 10.2 also for other applications.

here is what I see:
drwxr-xr-x 13 root root 4096 Mar 23 17:12 .
drwxr-xr-x 14 root root 4096 Aug 25  2019 ..
drwxr-xr-x  2 root root 4096 Oct 30 20:48 bin
lrwxrwxrwx  1 root root    9 Mar 23 17:12 cuda -> cuda-10.1

I used the given command on Pytorch:

conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

it take 3-4 hours to install it with the following error:

Package toolchain_cxx_linux-64 conflicts for:
keras -> theano -> toolchain_cxx_linux-64
theano -> toolchain_cxx_linux-64The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0
  - feature:|@/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

I do not know why the installation is picking 10.2 ? What should I do to install pytorch successfully.

Thanks

**Comment by ptrblck** [comment]
The conda binaries ship with their own CUDA lib, so your local CUDA installation won't be used.
There is no need to change the sym link to cuda-10.2.

It seems that your conda takes a long time to try to resolve conflicts in your current conda environment due to other installed libraries, e.g. Theano.

Usually the binary installation takes a couple of minutes, so the conflict resolution is most likely taking this long and failing.

I would recommend to use a new and clean conda environment and install the PyTorch binaries there:
```python
conda create -n my_env_name Python=3.7 Anaconda
conda activate my_env_name
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```

The `Anaconda` argument installs additional libs such as scipy, spyder etc., so you might want to skip it.

Have a look [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) for more information about managing conda environments.

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

Feel free to re-open if you think this is a bug but closing given that it seems to be an installation issue.
