### ISSUE TITLE
copy cuda tensor to cpu numpy is slow

### ISSUE THREAD

**Issue by sjf18** [pytorch/pytorch#35292]
## ❓ Questions and Help
Hi, when i convert cuda tensor to cpu numpy using `tensor.cpu().data.numpy()`, it is so slow. 
it takes more than 100ms, but my network inference time is only 5ms,  are there any ways to accelerate the operation?
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/ as mentionned in the template you used.

Note that in your case, you are most likely missing `torch.cuda.syncrhonize()` when timing your GPU code which makes the copy look much slower than it is because it has to wait for the rest of the work to be done.
