### ISSUE TITLE
torch.onnx flip tensor required

### ISSUE THREAD

**Issue by qiuqiangkong** [pytorch/pytorch#35295]
torch.onnx flip tensor required. I want to do x[::-1] but it says "ValueError: negative step not yet supported". I am wondering why such a simple operation is not supported.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Can you add repro steps and all the installation information.

**Comment by spandantiwari** [comment]
@qiuqiangkong - could you add a repro?

**Comment by qiuqiangkong** [comment]
@spandantiwari What do you mean by repro? Is that the code script?

**Comment by garymm** [comment]
@qiuqiangkong please provide code that can be run to reproduce the problem on the latest nightly version of PyTorch, including the call to `torch.onnx.export` and everything before it.

**Comment by AllenTiTaiWang** [comment]
Hi @qiuqiangkong ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
