### ISSUE TITLE
Pytorch from source and anaconda

### ISSUE THREAD

**Issue by shersoni610** [pytorch/pytorch#35383]
Hello,

I have compiled Pytorch from the source as the distributed binary package was not working
on Titan GPU.

1.   I use Anaconda package which have other useful packages (numpy, panda etc). I want
      to use my compiled Pytorch within conda environment. How can I do that?

2.   If I call conda update --all, will it overwrite torch and torchvision with its own versions. How
      can I disable conda not to touch my compiled Pytorch? Will it conflict with other packages
      in conda?

Thanks

**Comment by 6etacat** [comment]
The best way to build PyTorch is to create a Python wheel so you can keep the compiled PyTorch installer in a neat package. To do so, run `python setup.py bdist_wheel` instead of `python setup.py install`. You should get a wheel file that ends with `.whl` and you will be able to install it using `pip install wheel_file.whl`. 

Conda will install everything in your Anaconda install location (presumably `~/Anaconda` if you're using Linux). If the file is installed by pip, conda will recognize that and not upgrade it. 

However, it's very unusual that the conda PyTorch binaries won't work with your Titan GPU. Can you provide more information (steps you took to get the error, your platform, Python version, driver versions, error logs)?

**Comment by shersoni610** [comment]
Hello,
Here is the error output because of which  I was trying to build pytorch from the source.

Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch

>>> dev = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
>>> t1 = torch.randn(1,2)
>>> t2 = torch.randn(1,2).to(dev)
>>> print(t1)  # tensor([[-0.2678,  1.9252]])
tensor([[-0.9011, -1.5422]])
>>> print(t2)  # tensor([[ 0.5117, -3.6247]], device='cuda:0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.7/site-packages/torch/tensor.py", line 159, in __repr__
    return torch._tensor_str._str(self)
  File "/home/.local/lib/python3.7/site-packages/torch/_tensor_str.py", line 311, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/.local/lib/python3.7/site-packages/torch/_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/.local/lib/python3.7/site-packages/torch/_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: no kernel image is available for execution on the device
>>>

**Comment by 6etacat** [comment]
It seems like your GPU isn't supported by the CUDA version you are running. Which CUDA version are you running and what GPU is that? NVIDIA has many GPUs named Titan. Please provide output of `nvidia-smi`.

**Comment by rgommers** [comment]
No update in 10 months and no build log, so closing. Thanks everyone.
