### ISSUE TITLE
Does it make sense to cast from complex to floating types?

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#35487]
Currently casting from complex tensors to floating points has the same behavior as
```python
complex_tensor.real()
```
But does this make sense? Mathematically `1 + i` never equals `1`, and therefore should never be casted to `1`. It would make more sense if we simply disable the casting from complex to anything that is not complex.

cc @ezyang @anjali411 @dylanbespalko

**Comment by dylanbespalko** [comment]
@zasdfgbnm,

Casting from complex to float is widely used for embedded systems because the embedded system may not support the standard library (std::complex). I rely heavily on the following solution in numpy:

```python
  c = np.zeros(4096, dtype=np.complex)
  embedded_device.set_value(c)  #   does not work
  c.dtype = np.float
  embedded_device.set_value(c)  # this sends r, i, r, i to embedded device
```

This currently does not work in PyTorch. I'm told that there is a limitation in the storage classes and it is being addressed in #33950 .  Once that problem is solved, the ideal solution is to produce a python level solution that is equivalent to a C++ reinterpret_cast between std::complex<T> and T. 

Please keep it possible to cast between complex and float until the the storage classes are fixed.

**Comment by colesbury** [comment]
For reference, NumPy supports casting from complex to (real) floating point types, but raises a `ComplexWarning`.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

@dylanbespalko is asking for a different type of cast -- what NumPy calls [`view`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.view.html) and C++ calls `reinterpret_cast`. It would be good to support reinterpret-style operations in general, not just for complex, but we should not implement it via `tensor.to(torch.float)` or `tensor.float()`. That would be inconsistent with how we handle other types of casts. For example, casting from float to integers (via `tensor.to(torch.int32)`) keeps the integer part and discards the fraction; it doesn't do a reinterpret-style cast.

**Comment by vadimkantorov** [comment]
@colesbury For NumPy, does it return real() or abs() when casting c2f?

**Comment by colesbury** [comment]
@vadimkantorov NumPy returns a floating-point type array with the real components (so basically np.real not np.abs)

**Comment by mruberry** [comment]
Although I'm sure there could be a healthy debate about whether casting complex to float values has an intuitive meaning, our goal is to be consistent with NumPy here. @colesbury is correct that NumPy does warn you when you do this, however, and maybe PyTorch should, too. @zasdfgbnm if a warning sounds helpful please open an issue for that behavior.

**Comment by anjali411** [comment]
yeah I think we should add a warning to be consistent with numpy
