### ISSUE TITLE
RuntimeError: CUDA error: out of memoryy

### ISSUE THREAD

**Issue by mugheesahmad** [pytorch/pytorch#35670]
I started working on a new workplace virtual system and did all the necessary installations. But currently, I am unable to create a simple cuda variable. I don’t know what requirement is I am lacking.

I am using Windows Server 2016 and just installed latest official pytorch

Attached is the screenshot and any guidance is highly appreciated.

Thanks alot
![cuda error](https://user-images.githubusercontent.com/13232862/77918025-fc848380-72a3-11ea-8e7d-637b079fe387.png)

**Comment by ailzhang** [comment]
Looks like GPU is not setup properly. What does `workplace virtual system` mean? 
Is it a docker? 
I'm going to close this since it's more like a question instead of bug report, but feel free to reopen it with "proper environment information" (can be obtained by running the script available in bug report template) if you think it's a bug on pytorch.
