### ISSUE TITLE
Stop using javasphinx

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#36064]
We currently use javasphinx in our doc system but per https://github.com/bronto/javasphinx the project is no longer maintained. We should stop using it. It's not compatible with the latest version of Sphinx:

```
Apr 05 22:38:18 Extension error:
Apr 05 22:38:18 Could not import extension javasphinx (exception: cannot import name 'l_')
```

https://app.circleci.com/pipelines/github/pytorch/pytorch/151310/workflows/f4b09377-b712-4240-bc97-23032e08a625/jobs/5058853

@jlin27 I saw in #31956 that you removed javasphinx from requirements.txt, but it was reverted by @bwasti in 021e1e20c10a07d43e3d7e62bc015270c5ae9e3d and it looks like the change never relanded. Also cc'ing @gottbrath who appears to have originally added javasphinx in #27721

cc @ezyang @zou3519

**Comment by jlin27** [comment]
Thanks for the headsup. The reason it was removed was because we only used it to generate the html javadocs which were directly added to pytorch.github.io. To my knowledge, javasphinx is not part of the usual pytorch docs build process so we don't need to re-land; however, we probably should look into other options for when future javadocs are needed. 
@dreiss - do you know when should anticipate when we'll need to update the javadocs?

**Comment by mattip** [comment]
Now there are orphaned [`.. java:*` directives](https://github.com/pytorch/pytorch/blob/b9105f42a15a5551ed623c3bc6a88d551d59f892/docs/source/org/pytorch/Module.rst) in RST files. Is there a follow on PR to remove/refactor them? These cause warnings when building documentation via sphinx. xref gh-32703 and gh-38011

**Comment by ezyang** [comment]
@mattip Not that I'm aware of. Thank you for filing the issue.
