### ISSUE TITLE
Update the MSVC toolchain for Windows release CIs

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#36145]
## Background
The current MSVC toolchain we use (14.11) doesn't support AVX512. So `USE_FBGEMM` will automatically be set to `OFF`. (even in release/1.5) To enable fbgemm in the packages, we should update the MSVC toolchain we used in our release CIs.

## Plan
1. Update to 14.12 for all jobs (If we use Azure, then it is a bit complicated because all the agents have to be updated. However the migrating process to CircleCI is going on well in https://github.com/pytorch/pytorch/pull/36139. So maybe we could do the work in CircleCI. )
2. Update to vs latest for all jobs except the ones targeting CUDA 9.2 ( I don't think we could make the switch at this time. It seems that we might meet some troubles when building the conda packages. But this could be done in the long run. )
3. We try to be conservative and don't do the update this time for release/1.5. However, the users may be unhappy about this.

Any thought? cc @ezyang @seemethere @peterjc123 @malfet @soumith

**Comment by ezyang** [comment]
If I recall correctly, we're also only running 14.11 in our regular CI too, right? I think upgrading makes sense, but it seems a bit dangerous, since we have never actually run on 14.12. I think I'd be happy releasing Windows binaries on 14.12 if it passed the test suite (honestly, that's about as good as we're going to get, as far as testing goes), but I don't know how hard it would be to get there. But I guess we can try bumping the version on master and see how it goes.

I think it would also be ok to hold back for versions of CUDA that don't support 14.12; that seems very reasonable.

**Comment by peterjc123** [comment]
> If I recall correctly, we're also only running 14.11 in our regular CI too, right?

We test for 14.11, 14.16 and 14.24 in our regular CI.

> But I guess we can try bumping the version on master and see how it goes.

Sounds reasonable.



> I think it would also be ok to hold back for versions of CUDA that don't support 14.12; that seems very reasonable.

You mean 14.16/14.24, right? Then it would be better to build the CUDA 9.2 binaries with VS 14.11.

**Comment by ezyang** [comment]
Yes, I got confused by your option (1) which was to upgrade to 14.12. We should go straight to 14.16 or 21 if we don't upgrade CUDA 9.2. And since we're testing these on master this seems relatively low risk to me.
