### ISSUE TITLE
Dataset goes into infinite loop when used as iterator

### ISSUE THREAD

**Issue by w4nderlust** [pytorch/pytorch#3636]
In the examples on how to use a Dataset object, it is suggested to access it with:
```python
for i in range(len(dataset)):
    print(dataset[i])
```
but it would be reasonable to expect that you can access a dataset as an iterator, like:
```python
for item in dataset:
    print(item)
```
unfortunately doing so leads to an infinite loop.

Here's a simple code example that shows this behavior:
```python
from torch.utils.data import Dataset

class TestDataset(Dataset):
    def __init__(self, num):
        self.num = num

    def __len__(self):
        return self.num

    def __getitem__(self, index):
        return index

td = TestDataset(10)
for i in range(len(td)):
    print(td[i])
for item in iter(td):
    print(item)
```

**Comment by bheinzerling** [comment]
Here are a couple of points that should help clear up this issue:

- Python iterators are either created explicitly by defining `__iter__` and `__next__` methods, or implicitly via `__getitem__`. In the latter case, the `__getitem__` method is responsible for ending the iteration by raising an IndexError or a StopIteration exception. It doesn't matter if the iterator implements __len__ or not: an iterator's length is never checked during iteration and some (e.g. infinite) iterators don't have lengths. Btw, it is redundant to call `iter(X)` in a for loop, just `for x in X:` is enough.

- `__getitem__` in your example just returns index, and never stops the iteration because it doesn't raise StopIteration and there is no way for an IndexError to occur.

- `__getitem__` in DataSet looks like this:
```Python
def __getitem__(self, index):
    return self.data_tensor[index], self.target_tensor[index]
```
This will throw an IndexError at some point and thereby stop the iteration.

**Comment by w4nderlust** [comment]
Got it so `IndexError` or `StopIteration` are catched and they stop the iteration.
My case was actually different from that code I posted, it would return `ValueError: result of slicing is an empty tensor`.

This is a more faithful code:

```python
import math
import torch
from torch.utils.data import Dataset


class PatchDataLoader(Dataset):
    def __init__(self, image_dataset, patch_shape, strides, batch_size=1):
        self.image_dataset = image_dataset
        self.patch_shape = patch_shape
        self.strides = strides
        self.batch_size = batch_size
        self.num_images = image_dataset.size()[0]
        self.num_patches_x = math.ceil((image_dataset.size()[2] - patch_shape[0] + 1) / strides[0])
        self.num_patches_y = math.ceil((image_dataset.size()[1] - patch_shape[1] + 1) / strides[1])
        self.num_patches = self.num_images * self.num_patches_x * self.num_patches_y

    def __len__(self):
        return self.num_patches_x * self.num_patches_y * math.ceil(self.num_images / self.batch_size)

    def __getitem__(self, index):
        # convert index -> i,j,k
        i, j, k = self.map_index(index)

        # return some patch from the image dataset
        return self.image_dataset[k * self.batch_size:(k+1) * self.batch_size, i:i + self.patch_shape[1], j:j + self.patch_shape[0]]

    def map_index(self, index):
        k = index // (self.num_patches_x * self.num_patches_y)
        k_mod = index % (self.num_patches_x * self.num_patches_y)
        i = self.strides[1] * (k_mod // self.num_patches_x)
        j = self.strides[0] * (k_mod % self.num_patches_x)
        return i, j, k


images = torch.randn(2, 4, 4)

pdl1 = PatchDataLoader(images, [2,2], [2,2])
p1 = []
for i in range(len(pdl1)):
    p1.append(pdl1[i])
patches1 = torch.cat(p1)

pdl2 = PatchDataLoader(images, [2,2], [2,2])
p2 = []
for i in pdl2:
    p2.append(i)
patches2 = torch.cat(p2)
```

I guess I can put the slicing operation inside a `try` and `except ValueError` and raise a `StopIteration` inside the except clause to solve my problem.
But maybe pytorch could raise a `IndexError` when the result of slicing is an empty tensor instead of a `ValueError`? Ultimately the problem is with the indexing of the tensor rather than it's values, like trying to access an index that is not there.

**Comment by fmassa** [comment]
@w4nderlust I suppose you are looking for the DataLoader http://pytorch.org/docs/master/data.html#torch.utils.data.DataLoader

**Comment by w4nderlust** [comment]
No @fmassa I'm not. I'm writing my own custom one for dealing with my specific usecase (dealing with patches of tensors). And @bheinzerling answer lead me to find a solution to my problems, but now the issue is different I guess, and it is:
If the result of slicing is an empty tensor, should pytorch return a `ValueError` like it is doing today or should it return an `IndexError`? My use case suggests it should return an `IndexError` because that's part of `__getitem__` in an iterator, but maybe there are arguments against it.

**Comment by fmassa** [comment]
@w4nderlust I think that the semantics of indexing will change in this case once zero-dimensional tensors are exposed to pytorch, making it more consistent. I think in this particular case `ValueError` is justified, because there is no out-of-range scenario (just that PyTorch doesn't support zero-dim tensors yet).
For example
```python
a = torch.rand(3)
b = a.numpy()
print(a[:0])  # ValueError
print(b[:0])  # works fine
```

Also, small tip for your use-case: you can use two dalaloaders, one for loading the images, and the other one for loading the patches in each image. This way you can still have multithreaded image loading, and single-threaded patch extraction.

**Comment by w4nderlust** [comment]
@fmassa I see, so there's a discrepancy on how zero-dimensional tensors are treater and you're going to conform to the numpy behavior. In that case, my workaround catching `ValueError` won't work anymore as there won't be any error to catch, so I guess I should probably just check myself if the requested index in less than `len` and return `IndexError` in that case.
Thanks for the suggestion, it makes a lot of sense. At hte moment I'm just testing with a small dataset that fits in memory, so I don't really need it, but as soon as I'll start using bigger datasets it will make a huge difference!
