### ISSUE TITLE
GatherElements

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#36385]
I want get scores by idxs from a tensor, a minimal script to discribe my model:

```
import torch

class MyModel(torch.nn.Module):


    def __init__(self):
        super().__init__()
    

    def forward(self, x):
        # pred_prob [1, 1023, 4]
        prob = x
        # # box and prob (N, n_cls)
        idxs = torch.argmax(prob, dim=-1)
        # # GatherElements: should replace this one
        scores = torch.gather(prob, -1, idxs.unsqueeze(-1))
        return idxs, scores

    
if __name__ == "__main__":

    a = torch.randn([1, 1023, 4])
    model = MyModel()
    b = model(a)
    
    torch.onnx.export(model, a, 'a.onnx', opset_version=11)
    print('done.')



```

but in opset 11, the exported model is using `GatherElements`.

However GatherElements is not wide using and unsupported by onnx-tensorrt.

Is anyway to make it export more easy and simple? (Gather is very common when export onnx

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions. Thank you

**Comment by bonlime** [comment]
@jinfagang 
Hi,
I'm encountering the same problem with GatherElements not being supported in TensorRT. Did you manage to find a workaround for this problem?

**Comment by jinfagang** [comment]
@bonlime I have solved the problem.

**Comment by AleiChan** [comment]
@jinfagang hi, how solve it, thanks

**Comment by bonlime** [comment]
@AleiChan 
The workaround is to perform the same gather operation manually. This could be done by reshaping tensors, adding offsets and then using usual tensor indexing instead of gather. It may sound complicated, but here is an example of bbox decoding for object detection which avoid using gather and is fully supported by TensorRT: 

https://github.com/bonlime/pytorch-tools/blob/0859cf4caa0bb8b5a3cfc59e844b2e341dc0d9a3/pytorch_tools/utils/box.py#L301

The magic happens on lines 350-353.
Hope it will help to perform the same trick in your case.

**Comment by stevenDW** [comment]
> 

Hi,
I'm encountering the same problem with GatherElements not being supported in TensorRT. Did you manage to find a workaround for this problem? Can you tell me how to solve it? Thanks.

**Comment by bonlime** [comment]
@stevenDW see by response above for a workaround

**Comment by 1806610292** [comment]
@jinfagang can you enjoy how to solve this problem that GatherElements in not support in tensorrt?
