### ISSUE TITLE
Empty batch support for SyncBatchNorm

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#36530]
## 🚀 Feature

Support empty batches in SyncBatchNorm.

## Motivation

#36382 has fixed SyncBatchNorm for cases where different workers have different batch sizes. But when some worker or all workers have zero batch size, the behavior is still unexpected.

Similar to how BatchNorm supports empty batch sizes now (in https://github.com/pytorch/pytorch/issues/12013#issuecomment-569876108), the expected behavior for SyncBatchNorm should be:

1. forward/backward should work properly when some or all workers have zero batch size. In particular, inputs of no elements should have non-None gradients, parameters should have zero gradients if the total batch size is 0.
2. when the total batch size is 0, moving_mean/moving_var should not be updated.

However, currently using SyncBatchNorm with empty batch produces this error:
```
  File "..../torch/nn/modules/_functions.py", line 17, in forward                           
    mean, invstd = torch.batch_norm_stats(input, eps)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 3, -1] because the unspecified dimension size -1 can be any value and is ambiguous   
```

## Alternatives

We implement it [here](https://github.com/facebookresearch/detectron2/blob/2ca36e3cbfb2c84c18502221564b629f3877e8be/detectron2/layers/batch_norm.py#L216-L239) but it's a python-based inefficient implementation.
cc @jjsjann123

**Comment by jjsjann123** [comment]
Took a brief look at the python implementation.
Basically we wanted a branch in the syncBN kernel kernel to return empty stats and count (similar things for backward as well, and remember to forward grad_output to grad_input).

@ptrblck @csarofeen to prioritize.

**Comment by v0dro** [comment]
# Feature

SyncBatchNorm currently fails if any of the tensors that are distributed onto different processes has a 0-dim batch size. In order to make the behaviour of SyncBatchNorm consistent with BatchNorm, it is advisable to make SyncBatchNorm accept 0-dim batch sizes on any process rank.

# Motivation

The python function being called by SyncBatchNorm exists in `_functions.py` by the name of `SyncBatchNorm::batch_norm_stats`. This Python function has various calls to CUDA functions, such as `batch_norm_elemt_cuda_template` which should be modified to support 0-dim batch sizes.

Normally such a change would be done by adding simple if-checks within these C++/CUDA functions to support 0-dim batch sizes, however, in case of SyncBatchNorm this does not lead to correct output due to the distributed all-reduce at the end of the computation turning up wrong results when a 0-dim tensor exists on one of the ranks.

One such problematic function is `batch_norm_reduce_statistics_kernel`, which computes the mean and std-dev for each rank.

Figuring out a way to deal with this issue such that the changes applied can be used by DDP for more modules than SyncBatchNorm would be a useful way to approach this issue.

**Comment by datumbox** [comment]
Is there any update on this? We are hitting this problem on TorchVision's MaskRCNN model.
