### ISSUE TITLE
torch.save does not use zipfile serialization

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#36585]
In my PR that changes the serialization of quantized modules to use TorchBind class: https://github.com/pytorch/pytorch/pull/35923, `torch.save` doesn't work(failed with corrupted memory) if I have a torchbind object in the `state_dict`, but with `_use_new_zipfile_serialization=True` it works. to reproduce the error,
1). change _use_new_zipfile_serialization option:
`torch.save(model_dict, bytes_io, _use_new_zipfile_serialization=False)` in file `test/quantization/test_quantized_nn_mods.py` in `ModuleAPITest._test_conv_api_impl` function.
2). run `python test/quantization/test_quantized_nn_mods.py ModuleAPITest.test_conv2d_api`
3). error(mismatch because of memory corruption):
```
Falsifying example: test_conv2d_api(self=<__main__.ModuleAPITest testMethod=test_conv2d_api>, batch_size=1, in_channels_per_group=2, H=4, W
=4, out_channels_per_group=2, groups=1, kernel_h=1, kernel_w=1, stride_h=1, stride_w=1, pad_h=0, pad_w=0, dilation=1, X_scale=1.2, X_zero_p
oint=0, W_scale=[0.2], W_zero_point=[0], Y_scale=4.2, Y_zero_point=0, use_bias=False, use_fused=False, use_channelwise=True, qengine='fbgem
m')
Traceback (most recent call last):
  File "test/quantization/test_quantized_nn_mods.py", line 729, in test_conv2d_api
    Y_zero_point, use_bias, use_fused, use_channelwise)
  File "test/quantization/test_quantized_nn_mods.py", line 585, in _test_conv_api_impl
    self.assertEqual(m.weight(), l.weight())
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 889, in assertEqu
al
    exact_dtype=exact_dtype)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 901, in assertEqu
al
    assertTensorsEqual(x, y)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 867, in assertTen
sorsEqual
    self.assertLessEqual(max_err, prec, message)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/unittest/case.py", line 1232, in assertLessEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: tensor(0.2000, dtype=torch.float64) not less than or equal to 1e-05 :
```

This is related to the issue: https://github.com/pytorch/pytorch/issues/26567

cc @ezyang @gchanan @zou3519 @suo @jamesr66a

**Comment by jamesr66a** [comment]
Context: Original discovery of this issue was in https://github.com/pytorch/pytorch/issues/24045. In current serialization, classes are deserialized (i.e. `__setstate__` is called) before Tensors. This doesn't work for quantization with explicit prepacking in `__setstate__`, since the Tensor data is necessary to properly construct the packed tensor.

First attempt to fix was https://github.com/pytorch/pytorch/pull/24794 but was not landed, instead opting for the approach described in https://github.com/pytorch/pytorch/issues/26567. Functionality was landed in https://github.com/pytorch/pytorch/pull/26573. However, zipfile serialization is not enabled by default, pending https://github.com/pytorch/pytorch/pull/32958.

In the meantime, quantized implementations have opted to error out in the case that someone is trying to use `torch.save` serialization: https://github.com/pytorch/pytorch/blob/8a60d8bfe25758fd42857079c608627dfb56ab43/torch/nn/quantized/modules/linear.py#L70

**Comment by jerryzh168** [comment]
Is this fixed now? @jamesr66a

**Comment by ezyang** [comment]
Given https://github.com/pytorch/pytorch/issues/40140 ...
