### ISSUE TITLE
Add TracedModule attribute for the constants table

### ISSUE THREAD

**Issue by ifeherva** [pytorch/pytorch#36625]
## 🚀 Feature

TracedModuel currently returns the compiled code via the .code() member function. This code can possible contain constants (e.g. CONSTANTS.c0), however the value of these are not accessible from python at the moment. It would really useful to surface the constant mapping to python so libraries that interpret the module can get the full picture.

## Motivation

I am currently writing a pytorch/torchscript -> mxnet code converter and currently it cannot resolve the constants in the torchscript code.

## Pitch

tracedmodule.code -> returns code (done)
tracedmoduel.constants -> returns a mapping between constant name and value (dict)

## Alternatives

Any other function from jit that can return the constants of a tracedmodule

## Additional context

https://discuss.pytorch.org/t/extract-constants-from-torchscript-module/

cc @suo

**Comment by zdevito** [comment]
You can extract the constants by looking at the graph, for instance:
```

import torch
a = torch.rand(3, 4)


def foo(x):
    return x + a
r = torch.jit.trace(foo, torch.rand(3, 4))
print(r.graph)
all_nodes = list(r.graph.nodes())
print(all_nodes[0].t("value"))
```

```
graph(%x : Float(3, 4)):
  %1 : Float(3, 4) = prim::Constant[value=<Tensor>]() # what.py:6:0
  %2 : int = prim::Constant[value=1]() # what.py:6:0
  %3 : Float(3, 4) = aten::add(%x, %1, %2) # what.py:6:0
  return (%3)

tensor([[0.9243, 0.8836, 0.0624, 0.3324],
        [0.5121, 0.9444, 0.6407, 0.8464],
        [0.4154, 0.3708, 0.4425, 0.3128]])
```

**Comment by ifeherva** [comment]
My issue with this approach is that from the .code() I do not have the mapping to the right node (or I do not know how to do that without parsing the whole graph)

**Comment by suo** [comment]
Looks like I'm not getting a ton of free time to work on this issue, but I'll write what needs to be done here, and if someone wants to put up a PR I am happy to review.

The way we pretty print `.code` is with `PythonPrint`. This function populates one of its arguments `tensor_table` with tensor constants (see "Uses of tensor constants" [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/docs/serialization.md#printing-code-objects-as-python-source) for a more detailed description). Indices in this tensor table correspond to `CONSTANTS.c*` in the pretty printed code. 

Right now in the python binding for `.code` ([here](https://github.com/pytorch/pytorch/blob/999d7f6ab2d1196a1f6e2bb7123e9da0e5a2592d/torch/csrc/jit/python/script_init.cpp#L896)) populates this `tensor_table` and throws it away. We just want to keep it and return it to the user.

Some additional notes:
1. The constants table is only associated with a single `PythonPrint` pass, so you shouldn't store them separately from `.code` (they might get out of sync). We should probably have a `.code_with_constants` or something that returns a `(code_str, constants_table)`. 
2. Worth creating a little wrapper for the constants table in Python that overrides `getattr` so that `.c0` returns the 0th element of the table, so that you can just assign the constants table to  `CONSTANTS` and all the calls to `CONSTANTS.cN` will just work.

**Comment by ifeherva** [comment]
Thanks a lot for the quick turnaround @suo

**Comment by suo** [comment]
Thank @voznesenskym he is the one who implemented it :)
