### ISSUE TITLE
masked_selected does not broadcast tensors

### ISSUE THREAD

**Issue by Sleepychord** [pytorch/pytorch#3664]
torch.FloatTensor([[1,2],[3,4]]).masked_select(torch.ByteTensor([0,1])) return a runtime-error "nconsistent tensor size at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:193".
But the docs says boardcastable tensors can work.

**Comment by Sleepychord** [comment]
Just because I use a wrong version...

**Comment by Sleepychord** [comment]
But the latest version does not work either.

**Comment by zou3519** [comment]
I tested this on master and v0.3.0 and the code snippet works on both:
![image](https://user-images.githubusercontent.com/5652049/32786015-dd5c7ff0-c920-11e7-961b-0a7d1b3d9a75.png)

@Sleepychord what is the output of your `torch.__version__`?

**Comment by Sleepychord** [comment]
Oh, I found the latest version on pip is 0.2 and it did not work. Maybe this can only work on versions after 3.0. I will build a new pytorch from source,  thank you @zou3519 .

**Comment by acgtyrant** [comment]
![2018-01-25-202141_942x659_scrot](https://user-images.githubusercontent.com/3921062/35388103-67a1e63a-020d-11e8-8b7d-29644f3197f2.png)

What is the wrong!

**Comment by fmassa** [comment]
@acgtyrant broadcasting only add new dimensions to the beginning of the tensor, so if you want broadcast to work you need either to have `b` be of shape `3x1` or of shape `2`, because `a` is of size `3x2`. Check https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html for more details on the broadcasting rules
