### ISSUE TITLE
PyTorch to ONNX issue

### ISSUE THREAD

**Issue by Louyu666** [pytorch/pytorch#36899]
When I execute the following code come across an problem:
```
import torch
import torchvision

dummy_input = torch.randn(10, 3, 224, 224, device='cpu')
model = torchvision.models.alexnet(pretrained=True)
input_names = [ "actual_input_1" ] + [ "learned_%d" % i for i in range(16) ]
output_names = [ "output1" ]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
```
```
Traceback (most recent call last):
  File "/Users/louyu/Code/Python/PyTorch2onnx/main.py", line 9, in <module>
    torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 666, in _run_symbolic_function
    value = torch.stack([torch.tensor(v) for v in n["value"]]) if n["value"] else []
  File "/Users/louyu/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 784, in _node_getitem
    return getattr(self, sel)(k)
RuntimeError: required keyword attribute 'value' has the wrong type
```
## System Info
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: version 3.16.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] _pytorch_select           0.1                       cpu_0    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.4                      233    defaults
[conda] mkl-service               2.3.0            py37hfbe908c_0    defaults
[conda] mkl_fft                   1.0.15           py37h5e564d8_0    defaults
[conda] mkl_random                1.1.0            py37ha771720_0    defaults
[conda] numpy                     1.18.1           py37h7241aed_0    defaults
[conda] numpy-base                1.18.1           py37h6575580_1    defaults
[conda] numpydoc                  0.9.2                      py_0    defaults
[conda] pytorch                   1.4.0           cpu_py37hf9bb1df_0    defaults
[conda] torchvision               0.5.0                  py37_cpu   defaults
[conda] onnx               1.6.0                  defaults

Any ideas about the issue? Thanks!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Alexnet is part of CI tests. 
https://github.com/pytorch/pytorch/blob/c03d149483a90980928579c0c10eee126c0413c1/test/onnx/test_models.py#L80

**Comment by Louyu666** [comment]
> Alexnet is part of CI tests.
> 
> https://github.com/pytorch/pytorch/blob/c03d149483a90980928579c0c10eee126c0413c1/test/onnx/test_models.py#L80

When I run this code on my linux server with cuda, it works. But on my Mac it doesn't work, I need to have PyTorch->onnx->Core ML conversion test on my Mac.

**Comment by imalsogreg** [comment]
I'm seeing this on MacOS too. Any hints about how to debug? Minimal repro script:

```
import torch.nn as nn
import torch.nn.functional as F
import torch

import numpy as np

import torch.onnx

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()

x = torch.randn(4,3,32,32, requires_grad=True)

torch.onnx.export(net, x, "test.onnx", export_params=False, do_constant_folding=False)
```

`RuntimeError: required keyword attribute 'value' has the wrong type`

**Comment by KsenijaS** [comment]
@imalsogreg @Louyu666 I cannot reproduce the error in neither of your scripts. Are you saying this happens only on Mac OS?

System info:
- PyTorch 1.7
- Ubuntu 1.8
- Python 3.7

**Comment by imalsogreg** [comment]
@KsenijaS I've only tried my script on MacOS. I will try in on an Ubuntu machine today hopefully.

**Comment by spandantiwari** [comment]
@imalsogreg  - were you able to repro this issue on Ubuntu?

**Comment by spandantiwari** [comment]
@Louyu666 @imalsogreg - please reopen if you are able to repro this issue.

**Comment by JanBrabec** [comment]
I reproduced this today with the exact same error and also **resolved it.**

**System info which reproduced the issue**
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.14.6 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.12.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.4
[pip] torch==1.6.0
[conda] _pytorch_select 0.1 cpu_0
[conda] blas 1.0 mkl
[conda] libmklml 2019.0.5 0
[conda] mkl 2019.4 233
[conda] mkl-service 2.3.0 py37hfbe908c_0
[conda] mkl_fft 1.0.15 py37h5e564d8_0
[conda] mkl_random 1.1.0 py37ha771720_0
[conda] numpy 1.19.4 pypi_0 pypi
[conda] pytorch 1.6.0 cpu_py37hd70000b_0


**System info which resolved the issue**
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.14.6 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.12.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.4
[pip] torch==1.6.0
[conda] _pytorch_select 0.1 cpu_0
[conda] libmklml 2019.0.5 0
[conda] mkl 2019.4 233
[conda] mkl-service 2.3.0 py37hfbe908c_0
[conda] numpy 1.19.4 pypi_0 pypi
[conda] torch 1.6.0 pypi_0 pypi


**You can see I removed blas because I do not need it anymore, but what probably fixed this is different version of [conda] torch 1.6.0.**

The issue occurred with **[conda] pytorch 1.6.0 cpu_py37hd70000b_0** but not with **[conda] torch 1.6.0 pypi_0 pypi**

**Comment by Louyu666** [comment]
> @imalsogreg @Louyu666 I cannot reproduce the error in neither of your scripts. Are you saying this happens only on Mac OS?
> 
> System info:
> 
> * PyTorch 1.7
> * Ubuntu 1.8
> * Python 3.7

Yeah, Ubuntu can work, but macOS doesn't work.

**Comment by Louyu666** [comment]
> @imalsogreg - were you able to repro this issue on Ubuntu?

The script can work on Ubuntu, but macOS doesn't work.
