### ISSUE TITLE
Make multi-label datasets for images

### ISSUE THREAD

**Issue by ngchanway** [pytorch/pytorch#36918]
## 🚀 Feature
I would like to see a PyTorch feature to generate a dataset, ideally Pandas DataFrame with the image name as index and lists of labels for each image.

## Motivation
For multi-label image classification, it is important to generate the dataset from scratch given a custom datasets. Most likely, the images would be duplicated in multiple folder if the image has multiple label, similar to how `ImageFolder` works. Unfortunately, I have not seen any of such features offered in most PyTorch implementation.

## Pitch
Multi-label image classification is definitely an important topic as most images can be classified with multiple labels. It is also much easier to implement compared to object detection if such level of detection is not required.

## Alternatives
@SpandanMadan had proposed a [working solution](https://discuss.pytorch.org/t/multi-label-classification-in-pytorch/905/26). I would like to clean it up and make it consistent with PyTorch implementation.

cc @fmassa

**Comment by bradezard131** [comment]
Adding a dependency on pandas seems very unnecessary. Also, it is already supported, just subclass `torch.util.data.Dataset` and have it read the files and produce the labels. Automatically building it like with `torchvision.datasets.ImageFolder` (which by the way is a different repo) is tricky because there isn't some obvious standard way to arrange the folders like there is with a single label.

**Comment by gchanan** [comment]
@fmassa can you take a look?  I'm going to close given @bradezard131's comment, but reopen if you think it's worthwhile to discuss further.
