### ISSUE TITLE
Possible bug with the experimental Jacobian 

### ISSUE THREAD

**Issue by johnshin86** [pytorch/pytorch#37129]
## 🐛 Bug

I am testing the new experimental Jacobian function in Pytorch 1.5. From the documentation, it looks like the input needs to be either a single tensor, or a tuple of tensors. When passing in a tensor of shape batch_size * input_dim, a Jacobian tensor of shape (batch_size * output_dim * batch_size * input_dim) will be returned. My expectation is that it would return a tensor of shape (batch_size * output_dim * input_dim). Is this intended behavior?

## To Reproduce

1. Create NN model
2. Compute Jacobian of NN model with data of shape batch_size*input_dim

```import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision import transforms

class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.Linear = nn.Linear(3072, 512)
    self.Linear2 = nn.Linear(512, 10)

  def forward(self, x):
    x = x.view(-1, 3072)
    out = self.Linear(x)
    out = self.Linear2(out)
    return out

def get_data():
  transform_test = transforms.Compose([
        transforms.ToTensor()])
  test_dataset = datasets.CIFAR10(root='data', 
                                train=False, 
                                transform=transform_test,
                                download=True)  
  test_loader = DataLoader(dataset=test_dataset, 
                         batch_size=100,
                         num_workers=4,
                         shuffle=False)
  return test_loader

model = MLP()

test_loader = get_data()
for batch, data in enumerate(test_loader):
  if batch == 0:
    features, labels = data
    jacobian = torch.autograd.functional.jacobian(model, features)
    break
```

## Expected behavior

When passing in a tensor of shape batch_size * input_dim, a Jacobian tensor of shape (batch_size * output_dim * batch_size * input_dim) will be returned. My expectation is that it would return a tensor of shape (batch_size * output_dim * input_dim).

**Comment by gchanan** [comment]
@albanD.

**Comment by albanD** [comment]
Hi,

Yes this is the intended behavior. The function defined by your model takes a Tensor of size (batch_size * input_dim) as input and returns a Tensor of size (batch_size * output_dim). So the Jacobian for that function will be of size (batch_size * output_dim * batch_size * input_dim) (the output dimension concatenated with the input dimension).

If you want the Jacobian for each element in the batch independently, You can either take the diagonal elements of that matrix: `full_jac[i, :, i, :]` to get the Jacobian for the `i`th element.
Otherwise, you can make a function that takes an input of size (input_dim) and returns an output of size (output_dim) (so a function that processes only a single sample). And call the jacobian API on that new function for each Sample in your batch.

**Comment by johnshin86** [comment]
Thank you for the clarification! Appreciate your fast response.
