### ISSUE TITLE
JIT should let people know we inferred an argument as a tensor

### ISSUE THREAD

**Issue by mhamilton723** [pytorch/pytorch#37200]
## 🐛 Bug

Torch Jit fails on simple examples with dim argument

## To Reproduce
```python
@torch.jit.script
def dot(points, query, dim):
    return (points * query).sum(dim)
````

```
Traceback (most recent call last):
  File "/mnt/phd-projects/conditional_knn/ball_tree.py", line 21, in <module>
    @torch.jit.script
  File "/data/anaconda/envs/py37/lib/python3.7/site-packages/torch/jit/__init__.py", line 1290, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::sum.IntList_out(Tensor self, int[1] dim, bool keepdim=False, *, int? dtype=None, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'List[int]' for argument 'dim' but instead found type 'Tensor'.
  
  aten::sum(Tensor self, *, int? dtype=None) -> (Tensor):
  Expected at most 0 arguments but found 1 positional arguments.
  
  aten::sum.dim_IntList(Tensor self, int[1] dim, bool keepdim=False, *, int? dtype=None) -> (Tensor):
  Expected a value of type 'List[int]' for argument 'dim' but instead found type 'Tensor'.

The original call is:
  File "/mnt/phd-projects/conditional_knn/ball_tree.py", line 23
@torch.jit.script
def dot(points, query, dim):
    return (points * query).sum(dim)
            ~~~~~~~~~~~~~~~~~~ <--- HERE


Process finished with exit code 1
```

## Expected behavior

No error

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla M60
GPU 1: Tesla M60
GPU 2: Tesla M60
GPU 3: Tesla M60

Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.5.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               9.2                           0
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.17.2           py37haad9e8e_0
[conda] numpy-base                1.17.2           py37hde5b4d6_0
[conda] numpydoc                  0.9.1                      py_0
[conda] torch                     1.5.0                    pypi_0    pypi
[conda] torchvision               0.4.1                 py37_cu92    pytorch

cc @suo

**Comment by suo** [comment]
Hi, torchscript is statically typed. If you do not give an argument a type annotation, we assume it is a Tensor. As you can see, the `dim` argument is expected to be a list of integers, not a Tensor. 

The following modified code snippet compiles correctly: 
```
@torch.jit.script
def dot(points, query, dim: List[int]):
    return (points * query).sum(dim)
```

**Comment by mhamilton723** [comment]
Thank you @suo :)

**Comment by eellison** [comment]
It should be saying "inferred Tensor bc no type annotation is present" however, not sure why `is_inferred_type` isn't properly propagating

**Comment by suo** [comment]
zach suggests that we add the inferred_type tag to TensorType instead of Argument

**Comment by SplitInfinity** [comment]
I think Zach's suggestion indicates that he probably already figured out everything I'm about to say, but I thought I'd give some more detail on what's happening in case we decide to bootcamp this task.

It is true that we are recording whether a type is inferred or not in the `is_inferred_type_` member of the `Argument` class. And so, the `FunctionSchema` generated for `dot` does indeed have this member set to `true` for its arguments. But this error is encountered during IR generation while trying to resolve the call to `sum`. At that time, `dim` is a `Value` in the graph with type `Tensor`, but there is no way to tell that it was inferred because that is not recorded in `Value` when values are emitted for formal arguments. 

In addition, the message @eellison was referring to is printed when there is an argument type mismatch due to the type of a *schema argument* being inferred as `Tensor`. So in this case, even if we were propagating `is_inferred` to `Value` or to `Type`, we would only print that if any of the ops that were considered had a type mismatch because of the schema not having a type annotation, which is not the case for any of the variants in this issue.
