### ISSUE TITLE
Multi-Node multi-process distributed training

### ISSUE THREAD

**Issue by jinglin80** [pytorch/pytorch#37428]
We try to use Multi-Node multi-process distributed training ( https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py) on slurm, may we know whether we can run the sbatch commands separately, i.e.:
 
1.) First `sbatch` executes the following:
 
python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr=mdc-1057-25-4 --master_port=1234 YOUR_TRAINING_SCRIPT.py (--arg1 --arg2 --arg3
 
2.) Second `sbatch` executes the following, with a possible delay.
 
python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="mdc-1057-25-4 --master_port=1234 YOUR_TRAINING_SCRIPT.py (--arg1 --arg2 --arg3

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment]
@jinglin80 I am not familiar with slurm, but from DDP's perspective, above should be fine. The first  process would block waiting for the second process to join the rendezvous when it calls `init_process_group`. 

Could you please post followup questions to the [forum](https://discuss.pytorch.org/) under "distributed" tag? I am closing this issue for now, if it turns out to be a bug report or feature request. Please feel free to create another issue. Thx!
