### ISSUE TITLE
Update RPC examples/docs/tutorials to use RRef helper

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#37459]
As #36619 is landed, RRef now exposes three helper functions to run method on the RRef owner. We should update tutorials/examples/docs accordingly to use this feature. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by abitrolly** [comment]
* [ ] https://pytorch.org/tutorials/intermediate/rpc_tutorial.html

What else?

**Comment by mrshenli** [comment]
Hey @abitrolly, thanks to suggestions. 

The [parameter server](https://pytorch.org/tutorials/intermediate/rpc_param_server_tutorial.html) is also not using the new RRef helper API. 

Thinking about this again, I am not sure if it is still necessary to make all RPC tutorials to use RRef helpers. Because:

1. RRef helpers are already demonstrated in [dist pipeline tutorial](https://pytorch.org/tutorials/intermediate/dist_pipeline_parallel_tutorial.html) and [batch RPC tutorial](https://pytorch.org/tutorials/intermediate/rpc_async_execution.html).
2. The RRef helper API is only available in v1.6, we might want to keep some tutorials that would work for v1.4 and v1.5.
3. I am not user if it would be too many new concepts if we also pack RRef helper into the "Getting Started with RPC".

But even if we decided not to update `rpc_tutorial.html` with RRef helper, we should still at least add a note to mention that certain part of the code can be simplified using RRef Helper and include a pointer to the API.

**Comment by abitrolly** [comment]
I am not sure the RPC tutorials help me. My story is that right now I've spent a day training 40/150 epoch of https://github.com/NeuroSYS-pl/objects_counting_dmap and it is still 110 epoch or 3 days to go on my CPU notebook. At the same time people proposed me access to more powerful hardware, but I don't feel like the experience of repeating everything I did locally over SSH. I'd rather give them the instructions how to setup "PyTorch Render Farm" and how to generate access credentials. I haven't tried RPC tutorial yet, because of these new updates in 1.6, but I've got a feeling that it is still too low level and doesn't cover my story completely.

I would really just start with a very small example of making sure a connection between machines work.

Then I would try to pass PyTorch computation to remote machine with as little modifications as possible. The best is to specify the address of additional remote worker from command line.

And ideally I'd like to be able to add worker dynamically without losing the progress I made so far.

**Comment by mrshenli** [comment]
> Then I would try to pass PyTorch computation to remote machine with as little modifications as possible. The best is to specify the address of additional remote worker from command line.

In this case you might want to start from `DistributedDataParallel`?

> And ideally I'd like to be able to add worker dynamically without losing the progress I made so far.

This is not possible in `torch.distributed.rpc` yet. For `DistributedDataParallel`, there is a [`torchelastic`](https://pytorch.org/elastic) project built for this purpose. cc @kiukchung

**Comment by mrshenli** [comment]
Tutorials are updated. Closing this issue.
