### ISSUE TITLE
layer-by-layer profiling feature

### ISSUE THREAD

**Issue by xhzhao** [pytorch/pytorch#3749]
Our team is working on the PyTorch performance(DeepSpeech2 first) optimization for IA platform. We first use the default [profiler](https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py) in pytorch, and found that this profiler is a low level(functional) profiler. We tried the CProfile, but still we could not get a layer-by-layer result.
It would be great for PyTorch to provide a layer-by-layer profiler, just like caffe time.
And this layer-by-layer profiler will be very useful for the performance tuning, and model level perception.

**Comment by apaszke** [comment]
Most layers don't do more than 3 operations, so it should be pretty straightforward to figure out what operations correspond to different layers. I don't think adding annotations in Python by default is a good idea, because that would increase the overhead and skew the results. CProfile won't be useful if you want to get this kind of information, but autograd profiler should be just fine (that's what we've been using quite successfully so far).

**Comment by xhzhao** [comment]
@apaszke Thanks for you quick response, and totally agree with you about the Python overhead. We tried to build [a lightweight layer-by-layer profiler ](https://github.com/zhuwenxi/pytorch-profiling-tool)as a pytorch third-patry package. This profiler is very easy to enable or disable. We use the PyTorch hook function in module and you could get a layer-by-layer profiling result for both forward and backward. 
To do this profiling, we have to make a little code change in backward hook.(see readme).

**Comment by apaszke** [comment]
I see. One thing to note is that you probably don't want to use the module-based profiler. If you use `F.relu` it will never show up, while it will still appear in the autograd profiler. Additionally, this profiler won't be able to measure CUDA time as is, while autograd profiler can deal with that.

**Comment by zhuwenxi** [comment]
@apaszke, it is notable that our layer-by-layer profiler is not aim to substitute autograd profiler, but a supplement to it. We intent to provide a tool which could benefit not only Pytorch developers, but also users (researchers/data scientist).
Autograd profiler is a fantastic tool and we believe it must have did a lot help to PyTorch development work. However some users may not care too much about low-level function performance at first place, since they're not so familiar with PyTorch source as us. layer-by-layer profiler could provide a higher level and straightforward profile of a DL model, which could help data scientists to find out which layer is the performance bottleneck. And then they can use autograd profiler to narrow down it into low-level function range. In fact, as a performance engineer, this is the actual workflow of my daily work.

**Comment by zhuwenxi** [comment]
@apaszke, it is also notable that, although autograd profilier works perfectly with existing primitives (conv, relu, bn...) implemented in PyTorch code, it possibly may not work quite properly with user customized primitives in real-world models, unless they manually add autograd profiler code there, right?
Our layer-by-layer profiler could be a supplement to that, because we use runtime replacement to Python functions rather than modifying the native code, so the tool could always intercept models' forward/backward function and provide performance result. This is at least a fallback to autograd profilier, right? :)

**Comment by zhuwenxi** [comment]
@apaszke, and also I don't think <code>F.relu</code> and CUDA time would be problems, because there technique problem and could always be resolved (actually we already have some solutions).  The above layer-by-layer profiling tool we list above is just a quick prototype to demo basic functionalities. We can improve it soon if we decide that we really need this tool. Have a nice day! :)

**Comment by xhzhao** [comment]
should we move our discussion to the PR section?

**Comment by zhuwenxi** [comment]
@apaszke, thanks for your reply, very inspiring! BTW, just curious, what does "community package" stand for? Is it something like the torchvision package, which will be promoted by you guys?

**Comment by apaszke** [comment]
It's not any specific term, I've been mostly thinking about sth like a regular repo that you can install as a package (from your/your company's org). If it's good then we will also be recommending it in the forums and other places if someone will be looking for a tool like it.

I hope you understand the problem I had in mind, so I'll let myself close this issue, as I don't think we will be taking any action on it right now. Feel free to comment if you have any other related questions. Thanks!

**Comment by tartavull** [comment]
Here is a quick and dirty prototype that combines both approaches.
It lets you decorate a module with `@profile` and it overwrites the default print function
for the module so that it looks like:
```
  CPU Time   GPU Time  Architecture  
=====================================
  22.64ms       -       Encoder(
  22.64ms       -         (down_convs): ModuleList(
  22.64ms       -           (0): DownConv(
  22.64ms       -             (conv1): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  5.46ms        -             (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  1.34ms        -             (pool): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1), ceil_mode=False)
                            )
  7.28ms        -           (1): DownConv(
  7.28ms        -             (conv1): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  4.34ms        -             (conv2): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
 683.46us       -             (pool): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1), ceil_mode=False)
                            )
  5.87ms        -           (2): DownConv(
  5.87ms        -             (conv1): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  3.84ms        -             (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                            )
                          )
                        )

```
@zhuwenxi it doesn't yet support backward
@apaszke I was wondering if it was possible to extract other metrics that you can usually access with the nvidia profiler, like memory usage.

Here is the code ( again rather dirty, buggy and limited, but happy to improve it if it is of any use ):
```
from __future__ import division

from collections import defaultdict
from functools import lru_cache, reduce
import math
import operator

import torch


def profile(module, display_cpu=True, display_gpu=True):
    assert issubclass(module, torch.nn.Module)
    monkey_patch_init(module)
    return module

def monkey_patch_init(_class):
    old_init = _class.__init__
    def new_init(self, *args, **kwargs):
        old_init(self, *args, **kwargs)
        self.profiler = Profiler(self)
        _class.__str__ = self.profiler.__str__
    _class.__init__ = new_init

class Profiler(object):
    def __init__(self, module):
        """
        An operation is a graph node that performs computation on tensors.
        """
        self._module = module
        self._events = {
            'forward': defaultdict(Event),
            'backward': defaultdict(Event)}
        self._operations = {}
        self._enable = True

        #consume generator
        list(map(self._hook_operation, operations(self._module)))
    
    def _hook_operation(self, op):
        def wrapper_call(op, *input, **kwargs):
            # Wrapper function to "__call__", with time counter in it.
            if not self._enable:
                return self._operations[op.__class__](op, *input, **kwargs)

            with torch.autograd.profiler.profile() as prof:
                result = self._operations[op.__class__](op, *input, **kwargs)
            
            self._events['forward'][op] += Event(
                cpu_time=int(prof.total_average().cpu_time),
                gpu_time=int(prof.total_average().cuda_time),
                hits=1)
            
            def backward_pre_hook(*args):
                if not self._enable:
                    return
                self._events['backward'][op].append(time.time())
            #result.grad_fn.register_pre_hook(backward_pre_hook);
            return result

        # monky patch "__call__" with "wrapper_call"  for this operation`
        if op.__class__ not in self._operations:
            self._operations[op.__class__] = op.__class__.__call__
            op.__class__.__call__ = wrapper_call

        #def backward_post_hook(*args):
        #    if not this_profiler.profiling_on:
        #        return
        #    # adds ending time
        #    backward = this_profiler.record['backward']
        #    backward[-1] = backward[-1] + (time.time(),) 
        #op.register_backward_hook(backward_post_hook)   
    
    @lru_cache(maxsize=None)
    def get_metrics(self, module):
        if module in self._events['forward']:
            #it's an operation
            return self._events['forward'][module]
        
        # How do you handle hits ?
        # You don't wanna sum them for sure.
        # We are asuming that all of them were hit the same amount of time
        # Maybe not if we do gradient checkpointing
        # Easiest thing si to only display this  
        return reduce(operator.add, map(self.get_metrics, module._modules.values()))
    
    def __str__(self, module=None, indentation=0, pre_msg=''):
        tmpstr = ''
        if module is None:
            module = self._module
            tmpstr += Event.header()

        # this is an operation
        metrics = self.get_metrics(module).tostring()
    
        if module.__class__ in self._operations:
            return  tmpstr + metrics + indent(pre_msg + module.__repr__(), indentation) + '\n'
        
        name = module.__class__.__name__
        tmpstr += metrics + indent(pre_msg + name  + '(', indentation) + '\n'
        for key, sub_module in module._modules.items():
            tmpstr +=  self.__str__(sub_module, indentation+2, pre_msg='(' + key + '): ')
        tmpstr +=  indent(')',indentation+len(metrics)) + '\n'
        return tmpstr        

class Event(object):
    def __init__(self, cpu_time=0, gpu_time=0, hits=0):
        self.cpu_time = cpu_time
        self.gpu_time = gpu_time
        self.hits = hits
    
    @classmethod
    def header(cls):
        header = format_columns(['CPU Time','GPU Time','Architecture'])
        return '\n'.join([header,'='*len(header),''])

    def tostring(self):
        return format_columns([
                format_time(self.cpu_time),
                format_time(self.gpu_time)])
    
    def __add__(self, other):
        self.cpu_time += other.cpu_time
        self.gpu_time += other.gpu_time
        self.hits += other.hits
        return self

    def __radd__(self, other):
        return self.__add__(other)

def format_columns(cols, width=10):
    assert isinstance(cols, list)
    return  ' ' + ' '.join(col.center(width,' ') for col in cols) + '  '

def format_time(time_in_ns):
    if not time_in_ns:
        return '-'

    human_powers = ['n','u','m','']
    power = int(math.log(time_in_ns, 10) // 3)
    return '{:.2f}{}s '.format(
            time_in_ns/1000.**power,
            human_powers[power])

def operations(module):
    """
    Given a module recursively transverse it
    to find all atomic operations.

    Atomic operations are the nodes in the graph which
    perform computations on the tensors.
    """
    if not len(list(module.children())):
        # nn.Module who doesn't have sub nn.Module, hook it.
        yield module

    for name, sub_module in module.named_children():
        if (isinstance(sub_module, torch.nn.Container)
            or isinstance(sub_module, torch.nn.Sequential)
            or isinstance(sub_module, torch.nn.ModuleList)
            or isinstance(sub_module, torch.nn.Module)):
            # Recursively visit their decendants.
            for op in operations(sub_module): #python2 compatibility
                yield op

def indent(s, indent):
    return '\n'.join((indent* ' ') + line for line in s.split('\n'))
```

**Comment by apaszke** [comment]
@tartavull you could use one of the `torch.cuda` functions we provide to inspect the current state of GPU memory before and after the op

**Comment by tartavull** [comment]
I've tried a few things to enable the backward computation, but haven't had any luck.
hooks are not called when expected.
@apaszke would you have any general advice on how to implement that?

**Comment by apaszke** [comment]
We don’t have anything else than hooks that would let you inspect the backward computation :confused:

**Comment by tartavull** [comment]
And there is no pre and post hook for backward computation that I could you to start and stop your profiler, right?

**Comment by apaszke** [comment]
No, I don't think so. It's not that easy to implement

**Comment by awwong1** [comment]
In case this is useful to anyone else, I've created a python package for layer by layer profiling that extends the autograd profiler. It only supports forward computation.
https://github.com/awwong1/torchprof
https://pypi.org/project/torchprof/

**Comment by soumith** [comment]
@awwong1 this looks really cool!
