### ISSUE TITLE
Tensor initialization: Incorrect IDE typing hints

### ISSUE THREAD

**Issue by ikamensh** [pytorch/pytorch#37722]
## 🐛 Bug

Initializing a torch.Tensor with an argument in PyCharm IDE causes inspection warning: 
`Unexpected argument(s) Possible callees: object(self: object) object.__new__(cls: object)`

The code actually works, but triggers inspections:
```
import torch

a = torch.Tensor()              # OK
b = torch.Tensor([1, 2, 3])     # inspection triggered
c = torch.Tensor(12)            # inspection triggered
d = torch.Tensor(a)             # inspection triggered
```

## To Reproduce

1. create a Pycharm project
2. install torch with pip to the interpreter used by this project
3. paste code 
```
import torch

a = torch.Tensor()              # OK
b = torch.Tensor([1, 2, 3])     # inspection triggered
c = torch.Tensor(12)            # inspection triggered
d = torch.Tensor(a)             # inspection triggered
```

4. Observe highlighted warnings on lines 4, 5, 6. Roll the mouse over the highlighted code to see the text of the complaint: `Unexpected argument(s) Possible callees: object(self: object) object.__new__(cls: object)`
5. Run the code: it works.

## Expected behavior

Normal initialization of Tensor class doesn't show any warnings in IDE.

## Environment
PyCharm: 2019.3.2 Professional
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.16.5

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.3
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0
[conda] Could not collect

cc @ezyang

**Comment by zou3519** [comment]
I think at some point in the past we wanted to deprecate tensor constructors. e.g., instead of using `torch.Tensor(...)`, users should use `torch.tensor` or `torch.empty`. However, we haven't issued any real deprecation warnings. If we are going to dissuade users from using `torch.Tensor`, then I would prefer there to not be a type hint, just like how there is no current documentation on it.

**Comment by zou3519** [comment]
cc @gchanan are we planning to officially deprecate `torch.Tensor` anytime in the near future?

**Comment by ezyang** [comment]
What @zou3519 said!

**Comment by ikamensh** [comment]
Interesting. Any logic that could reside in `torch.tensor` could also be in the `Tensor.__init__` as long as we want a return type `Tensor`. Why create a separate function when most intuitive way to get an instance of a class is to construct it via constructor?

**Comment by zou3519** [comment]
@ikamensh there were two main reasons I believe:
- the Tensor constructor is error-prone due to how it is overloaded. `torch.Tensor(2, 3, 4)` constructs a tensor with initialized values of size [2, 3, 4], but `torch.Tensor([2, 3, 4])` constructs a tensor of size [1] with elements [2, 3, 4]!
- numpy compatibility. numpy prefers the usage of separate functions than the actual ndarray constructor (see https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html)

**Comment by rgommers** [comment]
If I remove the annotation for `Tensor.__init__`, I get a bunch of failures like:
```
torch/onnx/symbolic_opset10.py:209: error: Too many arguments for "LongTensor"  [call-arg]
test/test_torch.py:4035: error: Too many arguments for "FloatTensor"  [call-arg]
```

Related, there's this in `tools/pyi/gen_pyi.py`:
```
    # TODO: These are deprecated, maybe we shouldn't type hint them
    ...
    legacy_class_hints = []
    for c in ('DoubleTensor', 'FloatTensor', 'LongTensor', 'IntTensor',
              'ShortTensor', 'HalfTensor', 'CharTensor', 'ByteTensor', 'BoolTensor'):
        legacy_class_hints.append('class {}(Tensor): ...'.format(c))
```
If I remove those hints completely, we instead get (same lines, slightly different failures):
```
torch/onnx/symbolic_opset10.py:209: error: Module has no attribute "LongTensor"  [attr-defined]
test/test_torch.py:4035: error: Module has no attribute "FloatTensor"  [attr-defined]
```

There's still quite a lot of usage of `LongTensor` et al. in the code and docs, so I'm not sure that getting rid of all that at once for this issue is the right thing to do.

Alternatives are to just remove the `__init__` annotation and add `# type: ignore` comments to all current usages of Tensor (subclass) constructor, or to leave things as is until these things are actually deprecated. 

Any preferences?

**Comment by ezyang** [comment]
Alternatively, we could just give it an Any annotation so that everything works?

**Comment by rgommers** [comment]
There's multiple constructor signatures, with one already typed as `Any`:
```
        '__init__': ['def __init__(self, *args: Any, {}) -> None: ...'.format(DEVICE_PARAM),
                     'def __init__(self, storage: Storage) -> None: ...',
                     'def __init__(self, other: Tensor) -> None: ...',
                     'def __init__(self, size: {}, *, {}) -> None: ...'.format(type_to_python('IntArrayRef'), DEVICE_PARAM),
```

Ah, the report is for `1.5.0`, this should actually be solved. Or it's a bug in PyCharm. @ikamensh can you please confirm with a nightly?

**Comment by rgommers** [comment]
I'll assume this is fixed in master, closing.
