### ISSUE TITLE
Automatically collect worker_name_to_id in TensorPipeAgent

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#37784]
Ideally, `TensorPipeAgent` should not expect applications to provide a `worker_name_to_id` map, instead, it can automatically collect it, maybe, through a `c10d` store.  

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by xush6528** [comment]
A related topic for discussion.

Can user only provide worker_name when init_rpc?
rank is a ProcessGroup concept. Given worker_name to a ProcessGroup worker, it can find out the worker_name to rank mapping on their own, which could be transparent to users.
Thrift uses IP address directly, and does not have a rank concept.

**Comment by mrshenli** [comment]
> Can user only provide worker_name when init_rpc?
rank is a ProcessGroup concept. Given worker_name to a ProcessGroup worker, it can find out the worker_name to rank mapping on their own, which could be transparent to users.
Thrift uses IP address directly, and does not have a rank concept.

That would need some coordination? It might be sth like, it uses the URL to create/find the store, and then use the store to reach a consensus on the rank assignment. 

But at least, we can move the rank to the `ProcessGroupAgentOptions` config instead of as a required arg in `init_rpc` for all agent implementations.

**Comment by lw** [comment]
The only reason the TensorPipe agent requires users to provide an explicit map of names to ranks is in order to implement the getWorkerInfo(s) methods required by the agent interface. Apart from that it only needs the names: each worker adds its own address to the store, with its name as key, and then fetches the other workers' names from the store when needed. In fact, since the agent brings those pipes up on demand, it doesn't even need to know all the names of all the workers beforehand, or even how many workers there are in total. In short, having to deal with ranks is a burden which brings no benefit.

While we discuss whether to remove the ranks from the agent interface altogether, I was wondering what would happen if the TensorPipe agent stopped implementing the getWorkerInfo(s) method, either by raising an error or by returning a dummy value. Does something depend on that? Would it break? If we could do this change then we could remove the requirement for the user to provide the `worker_name_to_id` map as an option.

**Comment by mrshenli** [comment]
@lw 

>  I was wondering what would happen if the TensorPipe agent stopped implementing the getWorkerInfo(s) method, either by raising an error or by returning a dummy value. Does something depend on that? Would it break?

`get_worker_info` is used in several places in `rpc/api.py` and is already exposed as a public API, so we probably should keep that. 

But `get_worker_infos` are mostly internal and only used in a small number of places. We probably can get rid of that later. For now, not implementing `get_worker_infos` would break RPC as it is used to initialize `_ALL_WORKER_NAMES` which is used during shutdown.

**Comment by lw** [comment]
I see, thanks!

I've got another question: are users required to provide a rank when calling `init_rpc`? In the doc, [here](https://pytorch.org/docs/stable/rpc.html#torch.distributed.rpc.init_rpc), I see that `rank` has a default argument of -1. Does it means that specifying a rank is optional? What happens if users don't provide it? The agent receives the rank in its constructor as `selfId`: does the agent need to take care of the case in which that rank is -1?

I'm asking all of this because if each worker knows its rank I suspect we can have the agent send that information to the all the other workers, thus avoiding the need to pass the complete name-to-rank map everywhere. Would that work?

**Comment by lw** [comment]
I think the immediate problem this issue was about has been fixed in #38052. The agent however is still accepting a rank and a world size even though it doesn't really need it, just so that it can implement the `getWorkerInfo(s)` methods. It would be great if we could avoid that.

In principle, we can implement those methods without knowing each worker's rank and the world size in advance, using the store. The store has an atomic pre-increment operation, so we could have each worker generate its own rank by doing:
```
myRank = store->add("world_size", 1) - 1
```
However this wouldn't solve the general problem since ranks and world size seem to still be needed to create such a store and to initialize the distributed autograd. (And, if the agent starts generating its own ranks, they would not match with the user-provided ones and I don't know if this could cause issues). So, in short, fixing that requires a larger coordinated effort.
