### ISSUE TITLE
Support DataParallel for Python list

### ISSUE THREAD

**Issue by elbaro** [pytorch/pytorch#3779]
Sometimes I need to give a python list as input to Module. An example is `pack_padded_sequence`.

```
batch_size = 128
model = DataParallel(model, device_ids=[0,1])
out = model(txts, txt_lengths)  # [128,..], [128, ..]

.. model.forward(txts, txt_lengths):
pack_padded_sequence(txts, txt_lengths)  # error: 64 != 128
```

**Comment by apaszke** [comment]
I don't think we will ever want to add this functionality. It's not always the case that you actually want the list to get sliced (what if one of the arguments to your network is a list of ops it is supposed to perform?). Since there's no reasonable default I think we will just stick the the current behavior.
