### ISSUE TITLE
Scheduler.step() doesn't perform optimizer.step()

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#3814]
It seems counter-intuitive (to the extent I wondered why the hell nothing works, until took a look on weights change between steps, or more accurate it's absence), as scheduler looks like a wrapper over an optimizer. 
Moreover, I can't imagine a situation when one would need to do a scheduler's step, but not optimizer's, so writing both is redundant.

**Comment by dmarnerides** [comment]
Optimizer step is performed on every mini batch, while scheduler step is usually performed per-epoch.

**Comment by VladislavZavadskyy** [comment]
Fair point.

**Comment by muzi-8** [comment]
@VladislavZavadskyy @dmarnerides
I want to konw if I can do like this :
def train():
      ....
      loss.backward()
      optimizer.step()
      scheduler.step()
      ......
nemaly, I use  optimizer and scheduler simultaneously ?
Thanks!
...

**Comment by apaszke** [comment]
Scheduler should step after the end of each epoch, not after every iteration

**Comment by dmarnerides** [comment]
You can do it but it's not advised, unless you really want your learning rate to be able to change at every optimizer gradient step and not at every epoch, which is the common approach.

**Comment by muzi-8** [comment]
@apaszke @dmarnerides I get it! Thank you very much!

**Comment by xforceco** [comment]
This confuses me as well, instead I was thinking scheduler.step() will implicitly perform optimizer.step() as well since scheduler wraps optimizer.
It would be appreciated if one comment (or example code) can be added to the official documentation, saying that scheduler.step() performs on epoch-level that only changes learning rate, while optimizer.step() performs on batch-level that does update to parameters.
Many thanks

**Comment by dmarnerides** [comment]
I think it's much clearer if the scheduler is independent of the optimization (as is now), since its name suggests it only schedules the learning rates. and it also gives you the freedom to use it anywhere in the code depending on the scheduling you want.

Maybe if the method was renamed to scheduler.update() or scheduler.update_lr() things could be clearer.

**Comment by evarenieto** [comment]
Hello!!!
I am using :

`def train_model(model, criterion, optimizer, scheduler, num_epochs=25, device = 'cuda'):
    since = time.time()

    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0

    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch, num_epochs - 1))
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['training', 'validation']:
            if phase == 'training':
                scheduler.step()
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            running_corrects = 0

            # Iterate over data.
            for inputs, labels in dataloaders[phase]:
                inputs = inputs.to(device)
                labels = labels.to(device)

                # zero the parameter gradients
                optimizer.zero_grad()

                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'training'):
                    outputs = model(inputs)
                    _, preds = torch.max(outputs, 1)
                    loss = criterion(outputs, labels)

                    # backward + optimize only if in training phase
                    if phase == 'training':
                        loss.backward()
                        optimizer.step()

                # statistics
                running_loss += loss.item() * inputs.size(0)
                running_corrects += torch.sum(preds == labels.data)

            epoch_loss = running_loss / dataset_sizes[phase]
            epoch_acc = running_corrects.double() / dataset_sizes[phase]

            print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                phase, epoch_loss, epoch_acc))

            # deep copy the model
            if phase == 'validation' and epoch_acc > best_acc:
                best_acc = epoch_acc
                best_model_wts = copy.deepcopy(model.state_dict())

        print()

    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))
    print('Best val Acc: {:4f}'.format(best_acc))

    # load best model weights
    model.load_state_dict(best_model_wts)
    return model`
`criterion = nn.NLLLoss()
optimiz = optim.Adam(model.classifier.parameters(), lr = 0.001)
scheduler = lr_scheduler.StepLR(optimizer, step_size=4, gamma=0.1)
epoch = 10`
`model_nw = train_model(model, criterion, optimizer, epoch, device = 'cuda')`

and i got this error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-1a3153bc02ac> in <module>()
----> 1 model_nw = train_model(model, criterion, optimizer, epoch, device = 'cuda')

<ipython-input-6-ac85c67d8254> in train_model(model, criterion, optimizer, scheduler, num_epochs, device)
     15         for phase in ['training', 'validation']:
     16             if phase == 'training':
---> 17                 scheduler.step()
     18                 model.train()  # Set model to training mode
     19             else:

AttributeError: 'int' object has no attribute 'step'
`

some help? because i don understand it
