### ISSUE TITLE
Future callbacks in RPC should capture and restore autograd context id

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38439]
In early versions of RPC, all threads on server side are block-waiting until the request is fully processed. Hence we use a guard to clear the `thread_local` autograd context. 

https://github.com/pytorch/pytorch/blob/3d0279862db2602d684ec246e18424c405582f5d/torch/csrc/distributed/rpc/request_callback_impl.cpp#L563-L564

However, since we gradually making the RPC non-blocking on server side, the above guard is no longer correct. For example, in `FORWARD_AUTOGRAD_REQ`, the bottom half of the processing is done in a callback, which could run on a different thread. If it indeed runs on a different thread, the autograd context id is no longer valid. 

https://github.com/pytorch/pytorch/blob/3d0279862db2602d684ec246e18424c405582f5d/torch/csrc/distributed/rpc/request_callback_impl.cpp#L445-L483

This could be the cause of the recent flakiness in distributed autograd test. 

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by xush6528** [comment]
FTI, worked on a similar issue recently. https://github.com/pytorch/pytorch/pull/36395
Adding extra argument seems more like a temporary fix rather than a scalable one.

I think we should consider leveraging ThreadLocalState.cpp this time. It also transfers profiler thread-local state. Otherwise, an ad-hoc fix will still leave the profiler broken after RPC thread switch.

**Comment by mrshenli** [comment]
@xush6528 Thanks for the suggestion! Didn't realize we have a ThreadLocalState util before. Will learn its usage from autograd/engine and autograd/profiler.

**Comment by mrshenli** [comment]
@xush6528 Looks like the existing `ThreadLocalState.h` is an overkill as it contains things like dispatch key, debug info, callbaks, while what we need for now is just an autograd context id. Are you suggesting that, instead of using existing `ThreadLocalState`, we should create our own ThreadLocalState type like profiler did with `ProfilerThreadLocalState`?

**Comment by xush6528** [comment]
ThreadLocalState was initially added by https://github.com/pytorch/pytorch/pull/34360.

But dist_autograd_context_id is removed from ThreadLocalState in https://github.com/pytorch/pytorch/pull/35523, because of considering thread jump introduced in https://github.com/pytorch/pytorch/pull/33157 where the dist_autograd_context_id shouldn't be transferred.

For Facebook employee:
See https://www.internalfb.com/intern/diff/D20615714/?dest_fbid=207469870540623&transaction_id=1402532763242413

I think we should make dist_autograd_context_id similar to the "grad_mode_enabled_" field in ThreadLocalState, which has a "keep_grad_mode" to decide whether to transfer the thread state in the particular case.

**Comment by mrshenli** [comment]
I see,  makes sense, will put up a PR for that.

**Comment by xush6528** [comment]
@mrshenli 

The 3 elements you mentioned, dispatch key, debug info, callbacks are all thread-local states used by profiler. We need to transfer them as well to make profiler work after RPC server thread continuation.

They might be too much for the concern of a single PR, but we eventually need it so that distributed profiler can work correctly. Now it's broken. 
This thread switching on user thread pool (here it is the RPC thread pool, created by ProcessGroupAgent or ThriftRpcAgent) other than the c10 inter op thread pool is one of the issues. cc @ilia-cher 

So at least we should have a solution around ThreadLocalState so that we can re-use the same building block already used by profiler as well as soon by dist autograd in different thread pool.

`ProfilerThreadLocalState` is for profiler range that allows nesting. dist autograd container doesn't do nesting, right? but we can still have a subclass similar to `ProfilerThreadLocalState`.

**Comment by ilia-cher** [comment]
cc. @pritamdamania - I think you have context on this?

**Comment by ilia-cher** [comment]
I believe in the earlier conversations @pritamdamania87

**Comment by ilia-cher** [comment]
I believe @pritamdamania87 raised concerns earlier and we specifically did not include this variable in ThreadLocalState, cc. @pritamdamania87 on that

also it has nothing to do with ProfilerThreadLocalState,
re. ProfilerThreadLocalState - we had a discussion with @rohan-varma, yes the plan is to partially serialize it across RPC calls so that we can do remote profiling and return profiling events back

**Comment by ilia-cher** [comment]
`ProfilerThreadLocalState` is internal (and anonymous) to profiler and should not be used outside of it

**Comment by ilia-cher** [comment]
`ThreadLocalState` is intended to carry TLS values, so that they can be passed to another thread when needed, e.g. we do it when we move from forward pass into backward, when we execute JIT continuation (and restore original context).
I believe the proper solution would be to reuse this, if you need to send/recv it over RPC, it should be fine to add partial serialize/deserialize methods into ThreadLocalState (we don't need to send it all over the wire, and we also can't - e.g. it has local observer thread local callbacks, which are shared only within single process)

**Comment by xush6528** [comment]
> I believe the proper solution would be to reuse this, if you need to send/recv it over RPC, it should be fine to add partial serialize/deserialize methods into ThreadLocalState (we don't need to send it all over the wire, and we also can't - e.g. it has local observer thread local callbacks, which are shared only within single process)

Need to point out it's not about sending thread state over wire. It's when RPC server thread executes request handling code, it could do a continuation similar to JIT continuation. In other words, future callbacks could be created in server handler code, and the callbacks could be executed on other server threads.

**Comment by ilia-cher** [comment]
"It's when RPC server thread executes request handling code, it could do a continuation similar to JIT continuation"

I see, this is fine, `ThreadLocalState` can be propagated across threads (taking a snapshot is creating a new instance of `ThreadLocalState`, setting it can be done with `ThreadLocalStateGuard`). I'd specifically check with @pritamdamania87 re. adding this into ThreadLocalState, I also wouldn't want to encourage adding another flag like `keep_grad_mode` - we can think of a better interface rather then passing a bunch of bools into `ThreadLocalState` ctor, but generally it seems reasonable that in some cases you'd want to 'tell' ThreadLocalState what variables you want to propagate

**Comment by mrshenli** [comment]
@ilia-cher @pritamdamania87  how about we create an `RpcThreadLocalState` and `RpcThreadLocalStateGuard` that inherits from `ThreadLocalState` and `ThreadLocalStateGuard`. The only difference is that it also sets distributed autograd ctx ID?
