### ISSUE TITLE
Runtime Error for torch.set_() when using Variables storage

### ISSUE THREAD

**Issue by dmarnerides** [pytorch/pytorch#3849]
The following code:

```
import torch
from torch.autograd import Variable

a = Variable(torch.FloatTensor([1]))
a.set_(a.storage(), storage_offset=0, size=a.size(), stride=a.stride())
```
throws
> RuntimeError: set_(): argument 'sourceStorage' (position 1) must be torch.Storage, not torch.FloatStorage

whereas not using a variable
```
a = torch.FloatTensor([1])
a.set_(a.storage(), storage_offset=0, size=a.size(), stride=a.stride())
```
works just fine.

**Comment by dmarnerides** [comment]
Would using the following code bypass the problem, while keeping the correct Variable graph?
```
import torch
from torch.autograd import Variable

a = Variable(torch.FloatTensor([1]))
a.data.set_(a.data.storage(), storage_offset=0, size=some_size, stride=some_stride)
```

**Comment by colesbury** [comment]
It's not implemented yet on Variable. It probably can't be implemented in a differentiable manner with the current API since it takes in a `Storage`. You can use `Variable.as_strided(storage_offset, size, stride) -> Variable` for now, but keep in mind that it's currently undocumented, and we may change the name or API before the next release.
