### ISSUE TITLE
Will the next version of libtorch provide modules instead of header files in the c++20 standard?

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#38636]
Now the libtorch header file is too slow to debug and compile.Will the next version of libtorch provide modules instead of header files in the c++20 standard?

like this:
import torch
torch::Tensor a=torch::tensor({1,2});

cc @yf225 @glaringlee

**Comment by peterjc123** [comment]
You mean C++ modules? I don't think it is a easy work for us because we have so many dependencies.

**Comment by peterjc123** [comment]
You mentioned `instead of`. Even if under the most optimistic condition that the dependencies get the support for the C++ modules before our next release, we won't stop to provide C++ headers. The reason is clear. We need to support the old toolchains and old CUDA. It is impossible to deprecate the C++ headers only in several months.

**Comment by gchanan** [comment]
I think it's safe to close this given @peterjc123's comment.

**Comment by glaringlee** [comment]
per @gchanan close it for now.
