### ISSUE TITLE
One PyTorch Upsample op balloons into over 20 ONNX operations

### ISSUE THREAD

**Issue by glenn-jocher** [pytorch/pytorch#38991]
## 🐛 Bug

A single pytorch upsample operation exports as a large mess of over 20 (yes 20) different onnx operations with connections going all over the place. This is a major and unnecesary complication that the export process burdens the onnx model with. There must be a better way.

## To Reproduce

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()
        # m = nn.UpsamplingBilinear2d(scale_factor=2)  # also occurs
        # m = nn.UpsamplingNearest2d(scale_factor=2)  # also occurs

    def forward(self, x):
        # return m(x)
        return F.interpolate(x, scale_factor=2)


print('torch version %s' % torch.__version__)
print('onnx version %s' % onnx.__version__)
img = torch.randn(1, 3, 256, 256)
tml = TestModel()
print(img.shape, tml(img).shape)
torch.onnx.export(tml, img, 'model.onnx', verbose=False, opset_version=11)

oml = onnx.load('model.onnx')  # onnx model
onnx.checker.check_model(oml)
```

Code runs without error:
```bash
torch version 1.5.0
onnx version 1.6.0
torch.Size([1, 3, 256, 256]) torch.Size([1, 3, 512, 512])

Process finished with exit code 0
```

Then when the model is viewed with Netron:
<img width="744" alt="Screen Shot 2020-05-20 at 9 26 29 AM" src="https://user-images.githubusercontent.com/26833433/82471764-02187180-9a7c-11ea-84fe-753d0414afd2.png">

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment]
This is expected since by default, interpolate recomputes the given scale_factor using input size. If you try torch.nn.Functional with recompute_scale_factor = False, you'll see a single Resize node in the graph.
The default value of interpolate is going to change to set recompute_scale_factor = False by default,  as part of the PR: https://github.com/pytorch/pytorch/pull/38362

**Comment by glenn-jocher** [comment]
@neginraoof thank you for your reply! Yes I see that applying `recompute_scale_factor = False` works for F.interpolate. I tested this with nn.Upsample() however, and it will not allow me to pass this argument. I suppose my only recourse then is to wait for 1.6 to be released. Do you know when that might be?

```python
class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()
        self.m = nn.Upsample(scale_factor=2, recompute_scale_factor=False)

    def forward(self, x):
        return self.m(x)
```

**Comment by Red-Eyed** [comment]
@glenn-jocher 
I sake of simplicity, I used `partial` to imitate `nn.Upsaple` (just to not change code much)
`self.upsample = partial(F.interpolate, scale_factor=2, recompute_scale_factor=False)`

**Comment by spandantiwari** [comment]
@houseroad Are there any plans for nn.Upsample to be deprecated/discouraged or will it stay alongside nn.Interpolate in perpetuity? 

Also, @glenn-jocher - the PR for change in default has not made it to 1.6 branch yet. https://github.com/pytorch/pytorch/pull/39453 @houseroad @fmassa - can you please help merge this PR so that this can make it 1.6. Thanks.

**Comment by glenn-jocher** [comment]
Thank you!
