### ISSUE TITLE
regarding to('cuda') in init

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#39062]
current scenario -

when I do something like,
```
import torch, torch.nn as nn

class CustomLayer(nn.Module):
  def __init__(self):
    super().__init__()
    self.threshold = nn.Parameter(torch.randn(1)).to('cuda')
  def forward(self, input):
    return input

model = nn.Sequential(CustomLayer()).to('cuda')
list(model.parameters())
```
then it give me,
```
[]
```

expected scenario -

it give me a warning or error message, that I have mentioned ```to('cuda')``` in init, and it will not register parameter, otherwise I carry neural network training, and later get to know that no parameter only.

**Comment by zou3519** [comment]
Replace `self.threshold = nn.Parameter(torch.randn(1)).to('cuda')` with `self.threshold = nn.Parameter(torch.randn(1, device='cuda'))`.

This is a known issue: https://github.com/pytorch/pytorch/issues/9303 . The problem is that calling ".to()" on an nn.Parameter gives a torch.Tensor, not an nn.Parameter

**Comment by vainaijr** [comment]
Ok, thanks for your reply.
