### ISSUE TITLE
test_argminmax_large_axis_cuda is broken

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#39060]
```
======================================================================
ERROR: test_argminmax_large_axis_cuda (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/home/mruberry/git/pytorch/torch/testing/_internal/common_utils.py", line 804, in wrapper
    method(*args, **kwargs)
  File "/private/home/mruberry/git/pytorch/torch/testing/_internal/common_utils.py", line 804, in wrapper
    method(*args, **kwargs)
  File "/private/home/mruberry/git/pytorch/torch/testing/_internal/common_device_type.py", line 210, in instantiated_test
    return test(self, device_arg)
  File "/private/home/mruberry/git/pytorch/torch/testing/_internal/common_utils.py", line 473, in wrapper
    fn(*args, **kwargs)
  File "test/test_torch.py", line 9378, in test_argminmax_large_axis
    self.assertEqual(x.argmax(1), [x.shape[1] - 1] * 2)
RuntimeError: ndim() >= 1 && shape()[ndim() - 1] >= 2 INTERNAL ASSERT FAILED at "../aten/src/ATen/native/TensorIterator.cpp":901, please report a bug to PyTorch. 
```

This test doesn't appear to be run in OSS CI (see https://github.com/pytorch/pytorch/issues/39061). 

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by kurtamohler** [comment]
It sounds like the remaining issue is that `test_argminmax_large_axis_cuda` doesn't run on CI because it requires too much memory, is that right?

I wonder if we could change the tensor that's being tested such that it still effectively has the same number of elements, but it uses a strided view to repeat the same set of elements multiple times, reducing the memory footprint to a fraction of what it is now. For instance, in the following example, `b` uses the same amount of memory as `a`, but its strided view size is twice as large because it loops over the same memory twice:

```
>>> a = torch.rand(3)
>>> b = torch.as_strided(a, (2,3), (0,1))
>>> a
tensor([0.5445, 0.9170, 0.1065])
>>> b
tensor([[0.5445, 0.9170, 0.1065],
        [0.5445, 0.9170, 0.1065]])
>>> a.storage().size()
3
>>> b.storage().size()
3
```

I notice that the tensor in the `test_argminmax_large_axis` test is defined like this: `x = torch.zeros((2, 2**32)`. Is there anything special about that particular size, or could we get away with using something like `(2**16, 2**17)`, keeping the same numel?

Are there any other potential problems with this approach?

**Comment by ezyang** [comment]
This would work if the overflow is occurring in the logical index calculation, rather than the physical index calculation. If you're overflowing the actual physical index, overlapping in this way will mask the error, since your physical index will always be below the overflow point.

**Comment by ngimel** [comment]
In this case, the error is occurring in the physical index calculation, so we do need the physical memory.
