### ISSUE TITLE
Modifying inplace views of leaf gives unclear error message

### ISSUE THREAD

**Issue by kaijfox** [pytorch/pytorch#39150]
I was working with slicing up images and passing the pieces to a neural network separately when I came across a bug in my code that would have been much easier to fix if torch gave me the proper warning or raised an error when I was performing the operation that caused the eventual error.

Performing an inplace operation on a leaf yields a very helpful error:

    foo = torch.ones(20, 20).requires_grad_()
    bar = foo
    bar *= 10
    bar.sum().backward()

Results in

    Traceback (most recent call last):
    
      File "...", line 3, in <module>
        bar *= 10
    
    RuntimeError: a leaf Variable that requires grad has been used in an in-place operation.

However the very similar code

    foo = torch.ones(20, 20).requires_grad_()
    bar = foo[10:, 10:]
    bar *= 10
    bar.sum().backward()

produces the far less helpful error

    Traceback (most recent call last):

      File "...", line 4, in <module>
        bar.sum().backward()

      File "...", line 118, in backward
        torch.autograd.backward(self, gradient, retain_graph, create_graph)

      File "...", line 93, in backward
        allow_unreachable=True)  # allow_unreachable flag

    RuntimeError: leaf variable has been moved into the graph interior

I'm sure that if I knew more about the way the internals of PyTorch worked it would have been obvious to me that I shouldn't do this inplace operation, and I'm far from being an expert on API design, however it seems to me that either:

- PyTorch should provide some error when the inplace operation is performed is performed  like when the inplace operation is performed on the leaf.

- PyTorch should support inplace operations on slices of leaf variables. For instance using `foo = bar * 10` allows the backward() call to work.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by gchanan** [comment]
CC @albanD.

**Comment by albanD** [comment]
Hi,

For the first point we could add a custom creation meta to the views created from leafs to raise an error earlier.
Another approach would be to just change this error message with one saying that a view of a leaf has been modified inplace because this is the only way to trigger this message as far as I know.

For the second point. These inplace operations cannot be done because the inplace here means that you get a new Tensor with new values and new gradients. But the original Tensor gets lost (because you change it inplace). And so your leaf Tensor would not exist any more.
Since the only reason for a user to create a leaf Tensor is because they want gradient for that partircular Tensor, making this Tensor un-reachable is an error. As either you wanted these gradients, but this op would make it impossible for you to get them. Or you did not wanted them and you should not set requires_grad=True to begin with.

**Comment by albanD** [comment]
This has been replaced to properly state that a view of a leaf is being modified inplace.
