### ISSUE TITLE
Allow ATen::cat to take in vector<Variable>

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#3965]
Currently, only at::cat(vector\<Tensor\>) will work, which may be confusing in the code.

**Comment by goldsborough** [comment]
This won't work per se because `vector<A>` is unrelated to `vector<B>` in C++ even if `B` inherits `A`. The workaround I have created for this is `TensorListView(...)` which constructs a `vector<Tensor>` from a `vector<Variable>` inside: https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/src/nn/modules/rnn.cpp#L156
