### ISSUE TITLE
Allow ATen to index a tensor by a Scalar

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#3971]
```
at::Tensor x, y;
x[y]
```

Should work if y is a scalar. Otherwise, we have to do the more verbose x[y.toCInt()] to do the indexing.

**Comment by colesbury** [comment]
Seems reasonable. @zdevito what do you think?

**Comment by ebetica** [comment]
Not too much, but it would mirror Python syntax more closely. Will ATen really fail at compile time if your Scalar is float but you call .toCInt()? I thought it was type erased in a way that it would only fail at runtime (or do the proper conversion.

**Comment by goldsborough** [comment]
No `.toInt()` will fail at runtime -- I was a bit unclear, sorry. The question is whether it's better to put the error into user code (`x[y.toInt()]`) or raise an error from within the library about `y.toInt()` failing inside `operator[]`. We'd also have to get rid of `operator[](int64_t)` because `int64_t` converts implicitly to `Scalar`, so the overloads would be ambiguous. That may add a bit of overhead from wrapping/unwrapping the ints

**Comment by goldsborough** [comment]
Just talked to @zdevito about this. The concerns I just raised aren't that bad. I'll implement this.
