### ISSUE TITLE
Can you offer pytorch for c#

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#39929]
Can you offer pytorch for .net core (c#)？C++ debugging and compilation are too slow.

**Comment by peterjc123** [comment]
I don't get what you really want.
If you are asking for a C# wrapper, there're already plenty of projects, including https://github.com/SciSharp/Torch.NET and https://github.com/xamarin/TorchSharp.
If you want to run your model trained using PyTorch in C#, then there is ONNX and WinML.
If you want a whole framework based on C#, then I have to say that this is impossible.

> C++ debugging and compilation are too slow.
Well, this depends on your use case. Given the compiled binaries, I don't think it will take too long to compile a user problem depends on libtorch. As for debugging, it is more complicated for C++ but I don't think things will get better with C# because the hard ones are often the low-level ones.

**Comment by laizewei** [comment]
Thank you!
