### ISSUE TITLE
There is no interation between no_grad, enable_grad, set_grad_enabled

### ISSUE THREAD

**Issue by Yura52** [pytorch/pytorch#40158]
##  📚 Documentation
torch==1.5.0

The problem is the same for all three functions. For example, let's consider [no_grad](https://pytorch.org/docs/stable/autograd.html#torch.autograd.no_grad).

The documentation says: "This mode has no effect when using `enable_grad` context manager". This is not true:
```python
import torch
x = torch.tensor([1.0], requires_grad=True)
with torch.enable_grad():
    with torch.no_grad():
        y = x * 2
assert not y.requires_grad
```

And I mean that the documentation should be fixed, not the behavior of `torch` 😄 
These functions just set grad enabled/disabled in `__enter__` (or in the constructor in the case of `set_grad_enabled`) and set the _previous_ state in `__exit__`. This is very intuitive. IMHO, it will be confusing if, for example, the behavior of `no_grad` changes depending on some other context.

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @jlin27

**Comment by colesbury** [comment]
This was changed in https://github.com/pytorch/pytorch/pull/23310 apparently because of https://github.com/pytorch/pytorch/issues/19189.

The complaint in #19189 was legitimate -- the original terminology was confusing. But the PR #23310 confuses things by also adding erroneous claims:

https://github.com/pytorch/pytorch/pull/23310/files#diff-a1d32fe3effc8d03f2cf3e8af9216de9R106-R107

https://github.com/pytorch/pytorch/pull/23310/files#diff-a1d32fe3effc8d03f2cf3e8af9216de9R15

We should have caught that in the PR review. Oops.

**Comment by colesbury** [comment]
I'm bumping this to high priority considering @ezyang marked #19189 high-pri. The current documentation is incorrect. We should remove these two statements:

```
This mode has no effect when using :class:`~enable_grad` context manager .
```

```
    When using :class:`~enable_grad` context manager, :class:`~set_grad_enabled(False)`
    has no effect.
```

**Comment by vfdev-5** [comment]
@colesbury just to confirm, this issue is about documentation only (no code change required), right ? If so, I can send a PR if OK.

**Comment by colesbury** [comment]
@vfdev-5 yes, documentation only

**Comment by peterbell10** [comment]
@vfdev-5 friendly reminder to assign yourself to issues you're working on.
