### ISSUE TITLE
Expose rpc._wait_all_workers as rpc.barrier

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40166]
RPC uses `_wait_all_workers` as a barrier to do graceful shutdown. This might be a useful feature to applications as well, i.e., we can have `rpc.barrier()` for RPC and `dist.barrier()` for c10d. 

Note that this is different from #40107:

* The `rpc.barrier()` only makes sure that all workers reach the same point, while there could still be on-going concurrent execution in other RPC threads to satisfy futures created by the main thread. 
* The context manager collects and waits for all futures created in scope, but does not communicate with other workers.

https://github.com/pytorch/pytorch/blob/3fb1e73a4e928a0452c3b73ca6815f67127424e9/torch/distributed/rpc/api.py#L137-L198

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @xush6528

**Comment by lw** [comment]
Making the barrier part of the API would consolidate the assumption that the RPC framework is aware of all its participants and can perform collectives among them. This is true and trivial when using ProcessGroup, but will become less so as we move to TensorPipe. I think that instead of leaning more into that direction we should try to pull away from it, and also remove other relics of that behavior, such as the rank and world size options of init_rpc.

In principle, when using RPC for a standard client-server protocol, there shouldn't be a requirement for the server to be aware of what all its clients can be: clients should be able to come and go, be "anonymous", and the server should handle that. This, to me, seems to also be a requirement to have real robust elastic behavior.

**Comment by pritamdamania87** [comment]
> Making the barrier part of the API would consolidate the assumption that the RPC framework is aware of all its participants and can perform collectives among them. This is true and trivial when using ProcessGroup, but will become less so as we move to TensorPipe. I think that instead of leaning more into that direction we should try to pull away from it, and also remove other relics of that behavior, such as the rank and world size options of init_rpc.

Wouldn't each node be aware of all other nodes in the TensorPipe world as well? The RPC API allows any participating node to send an RPC to any other node.

> In principle, when using RPC for a standard client-server protocol, there shouldn't be a requirement for the server to be aware of what all its clients can be: clients should be able to come and go, be "anonymous", and the server should handle that. This, to me, seems to also be a requirement to have real robust elastic behavior.

I agree with this and staying away from a "collective" notion would be useful in general for the RPC framework. Although, there is one tricky part here in terms of cleanly shutting down nodes. Currently, if you start up C client nodes and N server nodes, the N server nodes don't do much and just wait for a shutdown signal via `rpc.shutdown()`. Although, our rpc mechanism has a timeout for the shutdown, so the servers might just timeout before the clients are done with processing.

I think instead of barrier(), we need some way to cleanly shutdown the RPC framework where long running servers wait for a shutdown signal from clients. One proposal would be to rename, `_wait_all_workers` to `wait_for_shutdown` and have no timeout for that operation. On the other hand, rpc.shutdown() can have a timeout as we have today.

**Comment by mrshenli** [comment]
> Making the barrier part of the API would consolidate the assumption that the RPC framework is aware of all its participants and can perform collectives among them.

We don't have to support collectives. In the future, when we get rid of ProcessGroup, we should still be able to worker infos from Store. Wouldn't that be sufficient?

> I think instead of barrier(), we need some way to cleanly shutdown the RPC framework where long running servers wait for a shutdown signal from clients. One proposal would be to rename, _wait_all_workers to wait_for_shutdown and have no timeout for that operation. On the other hand, rpc.shutdown() can have a timeout as we have today.

The original motivation was actually not for shutdown. Instead, it is for per-iteration synchronization inspired by [this discussion](https://discuss.pytorch.org/t/distributed-pagerank-with-pytorch/78529/17). The developer is trying to use `dist.barrier()` to perform the sync. Although that would work, the application will have to maintain the mapping from RPC `WorkerInfo` to `ProcessGroup` ranks, which seems to be an overkill especially as we already have `_wait_all_workers`. Another option to implement this sync using today's RPC API is to install a master which tells all workers what to do, but that would force applications to implement a master.

----

We can also let the `rpc.barrier(worker_names=["worker1", "worker2"])` take a list of worker names, and perform the barrier only within the subgroup. But this will look like @kiukchung's role-based RPC proposal, which makes me wonder whether we should add the API into app/elastic instead of `distributed.rpc`.

**Comment by lw** [comment]
> Wouldn't each node be aware of all other nodes in the TensorPipe world as well?

Not necessarily or, at least, not until this is needed. As all nodes have a common store, each node is able to look up the address of any other node and connect to it, but it doesn't do so until it has a reason to connect.

Imagine a client-server topology. The server's address is advertised in the store. Clients can come, look that address up, connect to the server, send a request, obtain a response, disconnect and go away. In all of this the server doesn't ever even need to know how many clients there are, what are their names or addresses, ...

> there is one tricky part here in terms of cleanly shutting down nodes

Yes, this is indeed not easy to handle. Compared to other "production" RPC frameworks, the PyTorch one has a few differences: it is used for "batch jobs" (meaning that the servers must eventually shut down, rather than staying up forever), each node is at the same time both a client and server, and servers aren't aware of what the clients are asking them to run. This means there's not much "reference literature" we can look at to decide what to do here...

> we should still be able to worker infos from Store

If we keep using Stores then, yes, we could leverage them to get some approximation of collectives. Note however that stores aren't the only way we can possibly do discovery. If you think about the client-server example I mentioned above, we'd only need the store to contain the server's address, and not the client ones. Which means the store could be replaced by simpler solutions (e.g., using a fixed addr/port for the server, or having the user provide it manually when spawning new clients, ...).

> makes me wonder whether we should add the API into app/elastic instead of distributed.rpc.

That may make sense...

**Comment by rohan-varma** [comment]
Adding high-pri and oncall:distributed to track for better engineering purposes
