### ISSUE TITLE
ModuleDict documentation misleadingly describes ordering of keys

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#40227]
## 📚 Documentation

The current documentation says it's an "ordered dictionary that respects the order of insertion", but it can, in fact, destroy its order. For example: 

![image](https://user-images.githubusercontent.com/38511765/85050917-aeb54400-b14b-11ea-9e61-5aa455df6019.png)

We should update our documentation to clarify its behavior, especially as users might try to enumerate the dict sequentially. 

cc @jlin27 @albanD @mruberry

**Comment by colesbury** [comment]
I don't think updating the docs is sufficient to justify confusing behavior. I propose:

1) Don't sort the keys
2) Warn in Python 3.5 when `update` (or the constructor) is called with an unordered dict

**Comment by colesbury** [comment]
Although if we're going to address this in 1.5 release branch as well then it's probably worth only updating docs there.

For context PyPI downloads of 1.5.0 by Python version in the last 3 months:

| Python version | 1.5.0 downloads (percent) |
|----------------|---------------------|
| 3.8            | 7.0%                |
| 3.7            | 48.3%               |
| 3.6            | 39.4%               |
| 3.5            | 4.7%                |
| 2.7            | 0.6%                |

(We've since dropped support for 2.7)

So about 95% of our PyPI downloads use Python versions that order regular `dict`.

**Comment by gchanan** [comment]
we just released 1.5.1 so I don't think we'll change the 1.5 release branch.

**Comment by yl-to** [comment]
Hi there, I am going to create a PR for this change.

**Comment by yl-to** [comment]
@colesbury

**Comment by yl-to** [comment]
Creating a new PR for this issue.
