### ISSUE TITLE
[dist_autograd] GPU continuations does not work in distributed autograd

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#40255]
The Distributed Autograd engine right now only support CPU workloads, and it works by creating its own cpu ready queue and consume the tasks until it's empty. If there's GPU continuations or mix CPU/GPU training workloads, it will fail silently. See the current implementation in https://github.com/pytorch/pytorch/blob/262ad8e6abdc20f4ec9fc30b0b0299af94b314e6/torch/csrc/distributed/autograd/engine/dist_engine.cpp#L253

A complete solution would comes from a rewrite of the local autograd engine, or proper design to resolve the GPU continuation specifically in dist autograd.

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @aazzolini @xush6528 @osalpekar @jjlilley

**Comment by pritamdamania87** [comment]
In cases where we have a CPU continuation after GPU, we see the following error (since the cpu_ready_queue is null for distributed autograd GraphTask):

```
>   what():  cpu_ready_queue INTERNAL ASSERT FAILED at "caffe2/torch/csrc/autograd/engine.cpp":1027, please report a bug to PyTorch. 
> Exception raised from ready_queue_by_index at caffe2/torch/csrc/autograd/engine.cpp:1027 (most recent call first):
> frame #0: <unknown function> + 0x8a32f (0x7fa300b2332f in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_c10_c10.so)
> frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x4d (0x7fa300b227ad in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_c10_c10.so)
> frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x57 (0x7fa300b22ad7 in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_c10_c10.so)
> frame #3: torch::autograd::Engine::ready_queue_by_index(std::shared_ptr<torch::autograd::ReadyQueue>, int) + 0xd6 (0x7fa3604f6736 in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #4: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x87e (0x7fa3604f4aee in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #5: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x1dd (0x7fa3604f3e1d in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #6: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x63 (0x7fa367a02783 in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2__C_impl_cuda.so)
> frame #7: <unknown function> + 0x1a9ee58 (0x7fa36050be58 in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #8: <unknown function> + 0x1a9ec91 (0x7fa36050bc91 in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #9: <unknown function> + 0x1a9ec0d (0x7fa36050bc0d in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #10: <unknown function> + 0x1a9eb75 (0x7fa36050bb75 in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #11: <unknown function> + 0x1a9e539 (0x7fa36050b539 in /data/users/pritam/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/ddp_under_dist_autograd#binary,link-tree/libcaffe2_libtorch.so)
> frame #12: <unknown function> + 0xc86e0 (0x7fa2f084b6e0 in /usr/local/fbcode/platform007/bin/../lib/libstdc++.so.6)
> frame #13: <unknown function> + 0x76ce (0x7fa37478d6ce in /usr/local/fbcode/platform007/bin/../lib/libpthread.so.0)
> frame #14: clone + 0x3f (0x7fa373d6b35f in /usr/local/fbcode/platform007/bin/../lib/libc.so.6)
```

**Comment by mrshenli** [comment]
Is this a regression? Or will it still work if I move inputs to GPU and outputs back to CPU in a `forward` function? (like what we do in our existing tutorials)

**Comment by rohan-varma** [comment]
Echoing @mrshenli's comments, is there a repro that could potentially trigger the error case above? I'm guessing it has to do with using GPU tensors with DDP + RPC?

**Comment by mrshenli** [comment]
@amirstar confirmed that moving tensors from GPU to CPU before feeding to RPC worked for the forward pass but failed in the backward pass. 

Marking this issue as high-priority as this is a regression, and if this does not work it means we cannot support GPU at all. If this true, let's try to get a fix into v1.6.

**Comment by rohan-varma** [comment]
It looks like the RPC tutorial at https://github.com/pytorch/examples/blob/master/distributed/rpc/parameter_server/rpc_parameter_server.py is also broken, with the same error @pritamdamania87 posted. This was working earlier, not sure at what point it regressed.

**Comment by pritamdamania87** [comment]
This is a test that will reproduce the problem:

```
    @dist_init
    def test_ddp_dist_autograd_local_vs_remote(self):
        dist.init_process_group(
            backend="gloo",
            init_method="file://{}".format(self.file_name),
            world_size=self.world_size,
            rank=self.rank)

        layer1 = nn.Linear(10, 5, False)
        # Start with the same parameters for remote and local

        layer2 = nn.Linear(5, 1).cuda(self.rank)
        inputs = torch.rand((10, 10))
        ddp_model = DistributedDataParallel(layer2, device_ids=[self.rank])

        with dist_autograd.context() as context_id:
            loss = ddp_model(torch.rand(10, 5)).sum()
            dist_autograd.backward(context_id, [loss])
```

Some context here regarding what might have caused the regression. The multithreaded autograd change in conjunction with distributed autograd was designed and built for CPU-only to keep the scope of the changes simple. This was primarily done since PyPer was CPU-only and support for our RPC framework was CPU-only as well. To fix this, we probably need to add GPU support for multithreaded autograd/dist_autograd. This might be quite an involved change touching the autograd engine and I'm not sure if we'll be able to land such a change before the branch cut. I'll try to think if there is some quick workaround here that we can implement for 1.6.

**Comment by pritamdamania87** [comment]
I think I have a proposal that might work but isn't the best from a performance perspective, but will at least not break existing GPU use cases: 

1) Have a single CPU thread in DistEngine to execute CPU continuations. This thread will have its own dedicated ready_queue.
2) For each GraphTask created by DistEngine, set its ready_queue to the queue mentioned above in 1)
3) This would ensure that if there is a continuation from a GPU task to CPU, it would be enqueued on the ready_queue of the CPU thread in 1) and that thread would execute these tasks.

This would fix the GPU issues we're seeing and won't affect our CPU-only use cases since the newly proposed CPU thread would not be used in those cases. This is not a great solution however, but should be good enough for 1.6. As we think about complete GPU support in 1.7, we can redesign this and come up with something better.

cc @wanchaol @albanD

**Comment by wanchaol** [comment]
> 1. Have a single CPU thread in DistEngine to execute CPU continuations. This thread will have its own dedicated ready_queue.

Do you mean a long live standalone thread in the DistEngine that is always waiting for tasks from continuation?

> 2. For each GraphTask created by DistEngine, set its ready_queue to the queue mentioned above in 1)

The continuation logic create its own ReadyQueue and works with it during each GraphTask execution, do you mean setting the thread local `local_ready_queue` in the autograd engine to this long-live ReadyQueue that DistEngine created?

So IIUC, each continuation call might push tasks to this long-live ready queue, and there's always a single thread that is working on them. I think this approach could work, and from the performance perspective, it should be ok as the previous behavior is also always single threaded, so at least we will not regress the perf.

**Comment by mrshenli** [comment]
Regarding the proposed solution, will it offer the similar perf compared to v1.5 when the autograd graph contains GPUs ops?

**Comment by albanD** [comment]
From what I remember from the discussionson multithreaded backward and how the dist engine uses it, this is expected behavior right now. It was ok not to support GPU ops. (It is discussed in the PR here for example: https://github.com/pytorch/pytorch/pull/36606#pullrequestreview-394226162) 

If you want to add this feature I think @wanchaol 's proposal is the simplest: Have a CPU worker thread with a ready queue in the dist engine shared by all the backward.

**Comment by mrshenli** [comment]
It seems we will have to fix this in v1.6. In past releases, we only say that apps cannot pass CUDA tensors to RPCs, but didn't say GPU ops cannot be used in local autograd graph. 

The [stable doc for v1.5](https://pytorch.org/docs/stable/rpc.html) says the following. All three of our RPC examples are using GPU ops.

> We intentionally disallow transmitting CUDA tensors because it might crash if the device lists on source and destination workers do not match. In such cases, applications can always explicitly move the input tensors to CPU on the caller and move it to the desired devices on the callee if necessary.

**Comment by mrshenli** [comment]
> This might be quite an involved change touching the autograd engine and I'm not sure if we'll be able to land such a change before the branch cut. I'll try to think if there is some quick workaround here that we can implement for 1.6.

I would consider this as a regression fix. If so, we should be able to get it in to v1.6 by cherry-picking.

**Comment by pritamdamania87** [comment]
> Do you mean a long live standalone thread in the DistEngine that is always waiting for tasks from continuation?

Yes, similar to the old CPU thread in the local autograd engine.

> The continuation logic create its own ReadyQueue and works with it during each GraphTask execution, do you mean setting the thread local local_ready_queue in the autograd engine to this long-live ReadyQueue that DistEngine created?

Apart from setting the thread local, don't we also need to set the cpu_ready_queue in the GraphTask itself? When a GPU task has finished and we need to execute a CPU task, the autograd engine looks up the cpu_ready_queue in the GraphTask. This is always null in case of distributed autograd which causes the failures we're seeing.

**Comment by ezyang** [comment]
Does anyone know why this wasn't caught by test coverage?

**Comment by mrshenli** [comment]
Removing high-pri and milestone as #40312 has temporarily fixed this issue by using a single thread for GPU continuation in RPC. After #40312, there is no regression compared to v1.5, but let's still keep this issue open as we are looking to add a better solution to make multi-thread autograd also work in this case.

**Comment by mrshenli** [comment]
@ezyang 

> Does anyone know why this wasn't caught by test coverage? Also, do we have a sense for how many GPU RPC users we have in the wild right now?

Because we don't have tests to cover `torch.distributed` examples code. We are thinking about adding all examples to our unit tests until `pytorch/examples` set up its own testing infra.

**Comment by mrshenli** [comment]
Yep, we should have added test to cover it (it's now added in #40312).  But GPU over RPC is not yet a major feature. It is a WIP feature which we plan to work on in H2.  There was a discussion earlier (see #28881 and #33604) to disable it. The current solution used in examples is a temporary comprise because:

1. we don't want to completely disable GPU over RPC in v1.4-v1.6
2. the current GPU over RPC solution is not elegant and won't be the final solution.

So in our docs we avoid using dedicated sections to advertise it until the final solution is in (it will be solution similar to `map_location`).

**Comment by pritamdamania87** [comment]
Following up on this thread to ensure we have a good long term solution for this instead of the hack in https://github.com/pytorch/pytorch/pull/40312. This is the idea I had and looking for feedback in terms of whether this makes sense:

1. In https://github.com/pytorch/pytorch/pull/40312, we have a single global thread in DistEngine that runs all CPU continuations.
2. We can keep this thread and have it only perform the operation of dequeue from the the [global_cpu_ready_queue_](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/autograd/engine/dist_engine.cpp#L79).
3. Once the global thread has dequeued a task, it basically schedules the operation on the JIT thread using `at::launch` which calls [execute_graph_task_until_ready_queue_empty](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/autograd/engine/dist_engine.cpp#L282) to complete the operation.

Another alternative is the following which might be more involved:

1. Allow users to specify a cpu continuation lambda in GraphTask.
2. If the autograd engine finds there is no cpu_ready_queue for a continuation, it would call this continuation lambda instead.
3. For DistEngine, this cpu continuation lambda would just call [execute_graph_task_until_ready_queue_empty](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/autograd/engine/dist_engine.cpp#L282).

The advantages of the second approach is that we don't need an extra thread and a queue. It might be slightly faster as a result since we don't enqueue and dequeue on a global cpu thread. The downsides are that in might involve some messy logic in the autograd engine in terms of calling this lambda in the appropriate places instead of just pushing tasks to a `cpu_ready_queue`.

@albanD @wanchaol @mrshenli Thoughts?

**Comment by albanD** [comment]
> ensure we have a good long term solution

This would be mid term right? Only until we can clean up the vanilla engine threading to work with the global thread pool.
cc @gqchen Do we have an ETA on that? to have a better idea how long this new fix would be needed for?


From a solution point of view. What is the actual use case where the current implementation is problematic?
While the current solution is a hack. I would argue that these solutions are also kind of hacks. 

But if the problem is just that we have models for which this single thread is an issue, the first solution sounds like a simple fix.
But if we don't have examples in the wild where this happens, I'm not sure why we would want to go through the trouble of doing it (because we expect to change this again in a couple months when we do the larger threading update).

**Comment by pritamdamania87** [comment]
> This would be mid term right? Only until we can clean up the vanilla engine threading to work with the global thread pool.

Yes, you are correct. Eventually the proposed rewrite of the autograd engine would be the long term solution here.

> But if the problem is just that we have models for which this single thread is an issue, the first solution sounds like a simple fix.
But if we don't have examples in the wild where this happens, I'm not sure why we would want to go through the trouble of doing it (because we expect to change this again in a couple months when we do the larger threading update).

This would be problematic in the scenario where there is a CPU continuation after a GPU continuation and the single thread would be a performance issue. We're focussing on improving our performance and GPU support for the RPC framework this half. This includes torchscript support, optimizing the DistributedOptimizer and perf improvements as part of TensorPipe. If we'd like to communicate to our OSS users that we've improved performance quite a bit in PT 1.7/1.8, I feel it would be good to fix this problem we have currently.

I don't have any examples in the wild where this happens currently, but the first solution is simple enough that I feel its worth the effort now instead of optimizing it later when we receive user reports of degraded perf. Do you think we can go with the first solution as part of our PT 1.7 release?

**Comment by pritamdamania87** [comment]
@jia-kai Could chime in on the proposed rewrite of the autograd engine which involves the new threading model? We were wondering if you had the bandwidth to look into it?

**Comment by albanD** [comment]
That sounds good.
In that case, solution 1 definitely has a large benefit compared to the current version and should be fairly simple yes.
But the extra work to get solution 2 to work for unknown benefit compared to 1 might not be worth it.
