### ISSUE TITLE
JIT fuser is not working with pytorch 1.5

### ISSUE THREAD

**Issue by Midhilesh29** [pytorch/pytorch#40558]
I have currently started learning torchscript and tried to visualize the optimized graph but I am unsuccessful. The following is my code

```
@torch.jit.script
def cell_end(ingate, forgetgate, cellgate, outgate, cx):
    ingate = torch.sigmoid(ingate)
    forgetgate = torch.sigmoid(forgetgate)
    cellgate = torch.tanh(cellgate)
    outgate = torch.sigmoid(outgate)

    cy = (forgetgate * cx) + (ingate * cellgate)
    hy = outgate * torch.tanh(cy)

    return hy, cy
```
For the above function i got the following graph
```
graph(%ingate.1 : Tensor,
      %forgetgate.1 : Tensor,
      %cellgate.1 : Tensor,
      %outgate.1 : Tensor,
      %cx.1 : Tensor):
  %19 : int = prim::Constant[value=1]()
  %ingate.3 : Tensor = aten::sigmoid(%ingate.1) # check.py:46:13
  %forgetgate.3 : Tensor = aten::sigmoid(%forgetgate.1) # check.py:47:17
  %cellgate.3 : Tensor = aten::tanh(%cellgate.1) # check.py:48:15
  %outgate.3 : Tensor = aten::sigmoid(%outgate.1) # check.py:49:14
  %15 : Tensor = aten::mul(%forgetgate.3, %cx.1) # check.py:51:10
  %18 : Tensor = aten::mul(%ingate.3, %cellgate.3) # check.py:51:30
  %cy.1 : Tensor = aten::add(%15, %18, %19) # check.py:51:10
  %23 : Tensor = aten::tanh(%cy.1) # check.py:52:19
  %hy.1 : Tensor = aten::mul(%outgate.3, %23) # check.py:52:9
  %27 : (Tensor, Tensor) = prim::TupleConstruct(%hy.1, %cy.1)
  return (%27)

```
Running with an input

```
inp = torch.randn(5, 10, 4)
cell_end(*inp)
```

Even after running the input over the graph I got the same graph
```
graph(%ingate.1 : Tensor,
      %forgetgate.1 : Tensor,
      %cellgate.1 : Tensor,
      %outgate.1 : Tensor,
      %cx.1 : Tensor):
  %5 : int = prim::Constant[value=1]()
  %ingate.3 : Tensor = aten::sigmoid(%ingate.1) # check.py:46:13
  %forgetgate.3 : Tensor = aten::sigmoid(%forgetgate.1) # check.py:47:17
  %cellgate.3 : Tensor = aten::tanh(%cellgate.1) # check.py:48:15
  %outgate.3 : Tensor = aten::sigmoid(%outgate.1) # check.py:49:14
  %10 : Tensor = aten::mul(%forgetgate.3, %cx.1) # check.py:51:10
  %11 : Tensor = aten::mul(%ingate.3, %cellgate.3) # check.py:51:30
  %cy.1 : Tensor = aten::add(%10, %11, %5) # check.py:51:10
  %13 : Tensor = aten::tanh(%cy.1) # check.py:52:19
  %hy.1 : Tensor = aten::mul(%outgate.3, %13) # check.py:52:9
  %15 : (Tensor, Tensor) = prim::TupleConstruct(%hy.1, %cy.1)
  return (%15)

```
I don’t know the reason behind it, Anyone please help me with this

**Comment by suo** [comment]
cc @ZolotukhinM

**Comment by ZolotukhinM** [comment]
The fuser was disabled in 1.5, that's probably why you're not seeing an optimized graph. To turn it back on, you could use the following workaround:
```
torch._C._jit_set_profiling_executor(False)
```

Also, please note that the fuser by default only works on GPU, so you might need to specify `device='cuda'` when you create `inp`. Otherwise, the computation would be carried out on CPU where fusion is disabled.

**Comment by Midhilesh29** [comment]
Thank you sir, I worked. Also, I have a doubt. Can we use `torch.jit.script` instead of using `torch.jit.trace`?. Till now I did find a good solution for this. Can you please help me to understand the difference between `torch.jit.script` and `torch.jit.trace`?

**Comment by ZolotukhinM** [comment]
Yes, generally you should be able to use `torch.jit.script` instead of `torch.jit.trace` (you could find some docs about both of them here: https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html). In a nutshell, `script` tries to parse your python program and convert it to a so called TorchScript, while `trace` requires a sample run (that's why it requires sample inputs) and records what tensor operations were invoked in that run. The main issue with tracing is that it only sees operations on tensors and doesn't see other things in your program, such as if-s and loops, for instance.

**Comment by ZolotukhinM** [comment]
I'm going to close this issue since the problem seems to be resolved - feel free to reopen if the issue persists. Also, please file other issues that you hit or post on the pytorch forum if you have other questions!
