### ISSUE TITLE
NNPack does not respect thread settings

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#40668]
## 🐛 Bug

When NNPack convolutions are used user thread settings are not respected. This is important because nnpack is used by default in most situations when dnnl is disabled. 

## To Reproduce

```import os
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"

import torch
torch.set_num_threads(1)
torch.set_num_interop_threads(1)

conv2d_pt = torch.nn.Conv2d(
    128, 128,
    (7, 7),
    stride=(1, 1),
    padding=(0, 0), groups=1, bias=True
)

class ConvNet(torch.nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv2d = conv2d_pt

    def forward(self, x):
        return self.conv2d(x)

model = ConvNet()

torch._C._set_mkldnn_enabled(False)
x = torch.ones((64, 128, 256, 256))
for _ in range(100):
    model(x)
```
@robieta discovered the problem, and here's his script that demonstrates it. Note that even though environment variables and `set_num_threads` is set to use 1 thread, there will be more than 1 core used. 

## Expected behavior

Respect number of threads set by user via environment variable or via `torch.set_num_threads`

## Environment
```
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```
## Additional context
History:
Before #37243, the number of participating threads was supposed to be set by a call to `at::get_num_threads`. This did not work however, because this call was guarded by INTRA_OP_PARALLEL ifdef, and, since NNPACK.cpp did not include ATen/Parallel.h INTRA_OP_PARALLEL ended up not defined. The fix would be simple, just include ATen/Parallel.h.
After #37243 was applied, reverted and reapplied in https://github.com/pytorch/pytorch/commit/b7e044f0e58624676130b2ef6a376a453fc6b090, number of threads for nnpack is determined by a call to caffe2::pthreadpool_ and ignores aten parallel settings. I cannot comment if it is the right behavior for mobile, but nnpack is used on desktop also when dnnl is disabled, and thread settings should be respected. 
cc @ezyang @gchanan @zou3519 @AshkanAliabadi @dreiss

**Comment by AshkanAliabadi** [comment]
Thanks for reporting this.  I'll revert to the previous behavior.

**Comment by ngimel** [comment]
@AshkanAliabadi are there any other places that could be similarly affected by your change?

**Comment by AshkanAliabadi** [comment]
> @AshkanAliabadi are there any other places that could be similarly affected by your change?

NNPACK, QNNPACK, PyTorch QNNPACK, and XNNPACK.  PyTorch QNNPACK is primarily used on mobile, and QNNPACK is Caffe2-only, while NNPACK is shared between PyTorch and Caffe2 but the code path you are referring to is PyTorch specific, unless Caffe2 can access ATen as well.  I am not sure XNNPACK is used on non-mobile builds at all but we never respected set_num_threads there to begin with, on mobile or otherwise.  We never also respected set_num_threads on PyTorch QNNPACK as far as I know, so that leaves us with NNPACK and [Caffe2] QNNPACK.

The motivation behind this change was better performance, which is definitely the case on mobile but I thought I extend it to all users of NNPACK and family as well regardless of the platform.  The problem you pointed out never occurred to me so my bad there.  What I am going to do now is to limit this change to mobile builds and continue using Caffe2 ThreadPool for non-mobile builds, which means everything should go back to how it was for anything except mobile.

**Comment by ngimel** [comment]
> I am not sure XNNPACK is used on non-mobile builds at all but we never respected set_num_threads there to begin with, on mobile or otherwise. We never also respected set_num_threads on PyTorch QNNPACK as far as I know, 

@AshkanAliabadi @dreiss Is ignoring `set_num_threads` on mobile desired behavior? Is it documented somewhere? Also, out of curiosity, why is caffe2::pthreadpool better than ATen threading facilities? Should it be brought to ATen if so, and reused if possible, so that desktop users get better performance too?

**Comment by AshkanAliabadi** [comment]
This is somewhat of a hairy situation.  I'll do my best to explain.  David will correct me if I am wrong.

We do support `set_num_threads` through JNI on Java.  If `torch.set_num_threads` ends up calling `at::set_num_threads` eventually we now support `torch.set_num_threads` on mobile through the Python front-end as well after that patch, but otherwise don't.  For me personally, not supporting `torch.set_num_threads` has been a result of not being aware of the existence of such a Python function rather than a conscious decision. :)

As for ATen vs Caffe2 threading, the threading comparison I was making above was between caffe2::Threadpool and third_party/pthreadpool, and not ATen's.  We were using caffe2::Threadpool on mobile before this change, either from within {Q}NNPACK or from at::parallel_for, but now use third_party/pthradpool all across the board, be it in {Q/X}NNPACK or ATen.

I have not done any measurements to see how third_party/pthreadpool compares to ATen's threading, but considering that {Q/X}NNPACK expect a threading implementation that is written against the third_party/pthreadpool API, using ATen from within {Q/X}NNPACK is not trivial.

The only benefit I see to desktop as a result of my change, is better performance on PyTorch QNNPACK (i.e. the fork of QNNPACK inside ATen - if you care about it to begin with since non-mobile builds use FBGEMM if I am not mistaken).  That is because previously we were disabling threading completely in PyTorch QNNPACK on non-mobile builds while now it is using third_party/pthreadpool.

I was hoping I could clean up nnpack_threadpool in nnpack.cpp as well but that ended up breaking torch.set_num_threads.  I'll revert that.

**Comment by AshkanAliabadi** [comment]
https://github.com/pytorch/pytorch/pull/40707

**Comment by AshkanAliabadi** [comment]
Fix merged.
