### ISSUE TITLE
Dataloader convert to cuda 

### ISSUE THREAD

**Issue by jzju** [pytorch/pytorch#40985]
## 🚀 Feature
Add a flag for dataloader to convert output to cuda

## Motivation
Avoiding boilerplate code.
In case whole dataset fits in GPU memory avoid copy from cpu to gpu every epoch.  

From
```
training_generator = torch.utils.data.DataLoader(Dataset(), pin_memory=True)
for x, y in training_generator:
    x = x.to('cuda')
    y = y.to('cuda')  
```
To
```
training_generator = torch.utils.data.DataLoader(Dataset(), to="cuda", pin_gpu_memory=True)
for x, y in training_generator:
```

cc @SsnL

**Comment by ngimel** [comment]
Thank you for the suggestion. Is it a common situation where you can keep the whole dataset in the GPU memory?
There are 2 issues mixed here
1) make dataloader send data to the GPU. You can currently achieve this by implementing a custom `collate_fn` that would send the data to the GPU.
2) Have the whole dataset in the gpu memory. This case is tricky because if there are multiple dataloader workers, they cannot initialize context on the gpu. 
cc @VitalyFedyunin

**Comment by jzju** [comment]
Thanks for the reply,
If I would make a PR with a builtin move to GPU collate_fn do you think it the idea can be accepted?

Case 2 is not a bottleneck that I have experienced or measured it just feel like a waste to copy in every epoch.
I guess something like [this](https://www.kaggle.com/c/abstraction-and-reasoning-challenge) may fit in memory but I don't know if or for which memory compute ratio it will make a considerable speedup. Case 2 could be ignored for now.

**Comment by SsnL** [comment]
> If I would make a PR with a builtin move to GPU collate_fn do you think it the idea can be accepted?

Probably not, because you can already do so with the current API, with not much code actually, but you would also need to set the correct start method etc. There would be quite a lot of case dependent things (like how many GPU memory you should use for instance) that I personally don't feel that a general abstraction would be useful.

**Comment by jakelevi1996** [comment]
> Thank you for the suggestion. Is it a common situation where you can keep the whole dataset in the GPU memory? There are 2 issues mixed here
> 
> 1. make dataloader send data to the GPU. You can currently achieve this by implementing a custom `collate_fn` that would send the data to the GPU.

Please could you explain how to define such a custom `collate_fn`? I just tried the following, which raised both `AttributeError: Can't pickle local object 'get_data_loaders.<locals>.<lambda>'` and `EOFError: Ran out of input` (with not very helpful error messages):

```python
pin_memory_device = "cuda:%i" % cuda_device_id
collate_fn = lambda batch: (
    torch.utils.data.default_collate(batch).cuda(pin_memory_device)
)
```

I'm new to PyTorch, but I assume it's quite a common use case to want `torch.utils.data.DataLoader` to load the upcoming batch of data into GPU memory using a background worker rather than waiting around in the main process for `torch.Tensor.cuda(pin_memory_device)` to copy from CPU to GPU memory? If this is not going to be addressed with a code change, would it make sense to at least explain how to do this in the documentation at [https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html#DataLoader](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html#DataLoader) ?

**Comment by ste362** [comment]
Hi, I write this module for move a dataloader to gpu ram. You can read all the informations at this link https://github.com/ste362/WrappedDataloader

**Comment by ste362** [comment]
> 

Hi, I write this module for move a dataloader to gpu ram. You can read all the informations at this link https://github.com/ste362/WrappedDataloader

**Comment by ste362** [comment]
> > Grazie per il suggerimento. È una situazione comune in cui è possibile conservare l'intero set di dati nella memoria della GPU? Ci sono 2 problemi mescolati qui
> > 
> > 1. fare in modo che il dataloader invii i dati alla GPU. Attualmente puoi raggiungere questo obiettivo implementando una personalizzazione `collate_fn`che invierebbe i dati alla GPU.
> 
> Per favore, potresti spiegare come definire tale usanza `collate_fn`? Ho appena provato quanto segue, che ha sollevato entrambi `AttributeError: Can't pickle local object 'get_data_loaders.<locals>.<lambda>'`e `EOFError: Ran out of input`(con messaggi di errore non molto utili):
> 
> ```python
> import torchvision
> 
> if __name__ == "__main__":
>     batch_size = 64
>     cuda_device_id = 0
>     train_dataset = torchvision.datasets.MNIST(
>         './data',
>         train=True,
>         download=True,
>         transform=torchvision.transforms.ToTensor(),
>     )
>     pin_memory = True
>     pin_memory_device = "cuda:%i" % cuda_device_id
>     collate_fn = lambda batch: (
>         torch.utils.data.default_collate(batch).cuda(pin_memory_device)
>     )
> 
>     train_loader = torch.utils.data.DataLoader(
>         dataset=train_dataset,
>         batch_size=batch_size,
>         shuffle=True,
>         num_workers=1,
>         collate_fn=collate_fn,
>         pin_memory=pin_memory,
>         pin_memory_device=pin_memory_device,
>     )
>     for i, [x, t] in zip(range(3), train_loader):
>         print(pin_memory, pin_memory_device, x.device, t.device)
> ```
> 
> Sono nuovo in PyTorch, ma presumo che sia un caso d'uso abbastanza comune voler `torch.utils.data.DataLoader`caricare il prossimo batch di dati nella memoria della GPU utilizzando un lavoratore in background piuttosto che aspettare nel processo principale per `torch.Tensor.cuda(pin_memory_device)`riprodurre dalla CPU alla memoria della GPU? Se questo non verrà risolto con una modifica del codice, avrebbe senso almeno spiegare come farlo nella documentazione su [https://pytorch.org/docs/stable/data.html#torch.utils.data .DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) ?

Hi, I write this module for move a dataloader to gpu ram. You can read all the informations at this link https://github.com/ste362/WrappedDataloader

**Comment by prolearner** [comment]
`torch.utils.data.default_collate` should now be changed to
`torch.utils.data.dataloader.default_collate`

**Comment by slerman12** [comment]
How does this compare with pin_memory?

**Comment by jakelevi1996** [comment]
I think pin_memory doesn't move data into GPU memory, it just moves data into a part of/type of CPU memory (?) from which data transfers to GPU memory are faster. But with pin_memory, the tensors are still on the CPU, and have to be explicitly moved to GPU, EG with `x.to(device=0)`.

If you want something to wrap data loaders to automatically move tensors into GPU memory as you iterate through the data loader, something like this should work:

```python
class DeviceMap:
    def __init__(self, dataloader, device=0):
        self._dataloader = dataloader
        self._device = device

    def _map(self, batch):
        x, t = batch
        return x.to(device=self._device), t.to(device=self._device)

    def __iter__(self):
        return map(self._map, self._dataloader)

data_loader_gpu = DeviceMap(data_loader)
for x, t in data_loader_gpu:
    # x and t should now be in GPU memory
    print(x.device, t.device)
```
