### ISSUE TITLE
torch/distributed/launch.py better control multiprocessing relationship 

### ISSUE THREAD

**Issue by zjjott** [pytorch/pytorch#41067]
## 🚀 Feature
When we are using multiprocess train,there is some issue when one fail other process running
1. when some subprocess fail,end other process,this will avoid deadlock when one wait other one,and also avoid program hung
2. 
## Motivation
Make Multi-Process Single-GPU (MPSG) which using `python -m torch.distributed.launch` more friendly to use,

## Pitch

1. all suceess, exit 0
2. one fail: terminal others, exit 1
3. some suceess ,other is running, waiting 

Can I make a PR?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
Hey @zjjott, if I understand the request correctly, this is for DDP failure handling. Can you check if [torchelastic](https://pytorch.org/elastic) is sufficient?

**Comment by mrshenli** [comment]
cc @kiukchung

**Comment by zjjott** [comment]
@mrshenli yes, `torchelastic` is a better solution to resolve a large train cluster, but I just want fix this simple code: https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py#L254
```
   for process in processes:
        process.wait()
```
this `wait()` will wait until process end, even at this time,other processes have exited

**Comment by mrshenli** [comment]
@zjjott I see. How do you plan to fix this?

**Comment by mrshenli** [comment]
> 1. all suceess, exit 0
> 2. one fail: terminal others, exit 1
> 3. some suceess ,other is running, waiting

This LGTM. Just one question, how do plan to handle the case where the first process hangs while the second process returned non-zero code?

**Comment by kiukchung** [comment]
could you describe the deadlock scenario in more detail? To echo @mrshenli I’d like to understand:

1. Is the deadlock you are observing due to the wait() call in the launcher or is it deadlocking on the gpu kernel (we’ve had issues in the past where using backend nccl in a multi worker topology with worker failures result in surviving workers to hang indefinitely on a nccl op)

2. In torchelastic we deal with disparities in exit codes by having a monitoring loop. Curious what your “simple” fix. 

Thanks!

**Comment by zjjott** [comment]
> > 1. all suceess, exit 0
> > 2. one fail: terminal others, exit 1
> > 3. some suceess ,other is running, waiting
> 
> This LGTM. Just one question, how do plan to handle the case where the first process hangs while the second process returned non-zero code?

yep,this case is No.2 ,to resolve that case ,is it a good idea to  terminal the first process ?

@kiukchung `wait()` function is a block call, `Wait for child process to terminate`,so will not able to end process when other are teminate or finish. however, it also hard to resolve gpu kernel deadlock such as nccl. This is not what I can solve by this PR
Can I make a merge request? or  with some unittest?

**Comment by kiukchung** [comment]
@zjjott  `process.wait()` will return immediately with a non-zero `returncode` if the process it is waiting for has already terminated. The code below demonstrates this behavior:

```
import subprocess as sp

p = sp.Popen(["sleep", "100"])
p.kill()
p.wait()
print(f"done waiting for proc = {p.pid}, exit_code = {p.returncode}")
```

**Comment by zjjott** [comment]
@kiukchung as a simple example. one train will success on 10 hours if there is no any exception. when we launch 2 process, there will be one `rank=0` and `rank=1`.Many user custom exception will be raise when `rank=1`, but this code:
```
for process in processes:
        process.wait()
```
`processes` is a list which first one is `rank=0`, so it will wait `rank=0` finish,and then check `rank=1`, at least we need wait for 10 hours or more but this process group can terminate more early. I meet the scene which `rank=0` process will not be finish, cause by waiting `rank=1` broadcast tensor

**Comment by kiukchung** [comment]
@zjjott you are correct that the scenario you describe can technically happen. However if you are using process groups, any collectives API call (`broadcast`, `all_reduce`, etc) on rank 0 that is invoked AFTER rank 1 has failed will raise and exception and fail, so its unlikely that rank 0's process is still alive for 10 hours when rank 1 has failed way before that.

This said, with torch.rpc based scripts this is more likely to happen as the rank 0 would fail only when it makes an rpc call to rank 1 (assuming rank 1 has failed already) but rank 0 could make this call 10 hours into the job.

I'm happy to review the PR to fail-fast in `torch.distributed.launch` but based on what you are experiencing I think there might be a deeper issue with the way your script is written and hence making the launcher fail fast will not really solve your root cause.

**Comment by zjjott** [comment]
@kiukchung I have send PR, do you need some unittest? I'll work on it
