### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn’t export Python operator qfn 

### ISSUE THREAD

**Issue by octavianmm** [pytorch/pytorch#41179]
Hi,
I’m trying to convert a pytorch model to onnx, but the conversion gives the following error:

RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

The definition for qfn is:
>
class qfn(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input, k):
        n = float(2**k - 1)
        out = torch.round(input * n) / n
        return out
    @staticmethod
    def backward(ctx, grad_output):
        grad_input = grad_output.clone()
        return grad_input, None

cc @ezyang @SsnL @zou3519 @gqchen @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@octavianmm - Only native PyTorch operators are supported for ONNX export at this point.

**Comment by Stonesjtu** [comment]
Is it possible to at least customize the default op name of the python op when exporting to ONNX.

eg: instead of `^PythonOP`, `domain::my_op` should be prefered.

Or is it possible to add a few extra attributes to `torch.autograd.Function` to make it ONNX friendly.

**Comment by shubhambhokare1** [comment]
https://pytorch.org/docs/1.10.0/onnx.html#torch-autograd-functions
Please take a look at this. This should enable you to export models with autograd functions

**Comment by BowenBao** [comment]
Hi @octavianmm @Stonesjtu ,

We’ve gone ahead and closed this issue because it has a [resolution](https://pytorch.org/docs/1.10.0/onnx.html#torch-autograd-functions).
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
