### ISSUE TITLE
torch.erf(c) type promotion is inconsistent with scipy.special.erf(c)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#41247]
`scipy.special.erf` will promote float16 inputs to float32 outputs:

```
from scipy import special
a = np.array(.5, dtype=np.half)
special.erf(a).dtype
: dtype('float32')
```

but PyTorch (on CUDA, where torch.erf(half) is implemented) does not. Maybe we should be consistent with erf? 

cc @mruberry @rgommers

**Comment by rgommers** [comment]
This is because the ufuncs in `scipy.special` have no support for `float16` at all: https://github.com/scipy/scipy/blob/master/scipy/special/_generate_pyx.py#L21, it's not specific to `erf`. No one ever asked for `float16` support as far as I can remember, and I also cannot find any issue related to it on the SciPy issue tracker.

I think following the normal PyTorch casting rules here and sticking with `float16` is the right thing to do.

**Comment by mruberry** [comment]
Let's close this issue, then.
