### ISSUE TITLE
/home/lc/pytorch-cxx/libtorch/include/torch/csrc/api/include/torch/nn/cloneable.h:69:56: error: no matching function for call to ‘at::Tensor::to(const c10::Device&) const’

### ISSUE THREAD

**Issue by luochuanoo** [pytorch/pytorch#41320]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet

**Comment by malfet** [comment]
Can you please provide more details on how you've encountered the issue and what version of PyTorch/libpytorch are you using, what compiler, build system, etc. Having an isolated repro case would be truly invaluable.

**Comment by malfet** [comment]
Closing this issue, because we need more information to effectively triage it. When you provide the requested information, feel free to reopen the issue, to let us know that we can continue with assessing the issue. This open/close/open cycle is how we manage the flow of issues, so your reopening of the issue will constitute the signal that lets us know to take a look at the issue again.
