### ISSUE TITLE
torch.distributed NCCL backend does not support bitwise reduction ops

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#41362]
## 🐛 Bug

The documentation at https://pytorch.org/docs/stable/distributed.html specifies that BAND, BOR, BXOR are supported reduction operators, however, they do not work with `all_reduce` using the NCCL backend.

We can see in the [code](https://github.com/pytorch/pytorch/blob/c451ddaeda3e58d0f51d4026add4de1b3cf9657d/torch/lib/c10d/ProcessGroupNCCL.cpp#L39) that there is no mapping for the bitwise operators, and we [use this mapping](https://github.com/pytorch/pytorch/blob/c451ddaeda3e58d0f51d4026add4de1b3cf9657d/torch/lib/c10d/ProcessGroupNCCL.cpp#L744) to get the nccl operation to run. What happens when the mapping is not specified is that the map attempts to default construct a `ncclRedOp_t` type (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#ncclredop-t) and ends up incorrectly mapping these reduction types to `ncclSum`. This will mean that if we use these bitwise reduction ops we will just end up doing a sum. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by thinking-tower** [comment]
Hey @rohan-varma, I'm keen on working on this issue! Could you go into more detail about what's the expected resolution for this?

**Comment by rohan-varma** [comment]
The tricky part here is that per https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#ncclredop-t, NCCL only supports those operations and I'm not sure if something like BAND/BOR can be implemented using those. We could always roll our own solution (which is what the [Gloo backend](https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/ProcessGroupGloo.cpp#L137) does). In this way, we could do a D2H copy, then run the bitwise op, then kick off a H2D copy. Any thoughts on this approach (cc @mrshenli @pritamdamania87 @zhaojuanmao)?

**Comment by pritamdamania87** [comment]
> What happens when the mapping is not specified is that the map attempts to default construct a ncclRedOp_t type (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#ncclredop-t) and ends up incorrectly mapping these reduction types to ncclSum

I think the first step would be throw an exception to the user indicating that the operation is not supported instead of silently using ncclSum.

> We could always roll our own solution (which is what the Gloo backend does). In this way, we could do a D2H copy, then run the bitwise op, then kick off a H2D copy. Any thoughts on this approach

Are you suggesting that we should do an allgather of all the tensors and then do the reduction ourselves? Do we need to do the D2H copy and vice-versa? We can probably use something like [torch.bitwise_and](https://pytorch.org/docs/master/generated/torch.bitwise_and.html)(looks like there is xor and or as well) to perform the reduction on the GPU itself?

This would work, however allgather is pretty expensive compared to allreduce and ideally NCCL performing this reduction as part of the ring allreduce would be much more efficient.

I'd suggest fixing the issue of silently defaulting to `ncclSum` first and then checking with NCCL if they plan to support this in the future. We should probably invest time implementing this ourselves only if there is an urgent need from users and NCCL doesn't have anything coming soon.

**Comment by rohan-varma** [comment]
Sounds good, @thinking-tower I think the first step for now can just be to throw a descriptive error if the operation is not supported (not in the `ncclOp` map) and probably update our distributed documentation indicating that BAND, BOR, and BXOR is not supported with the NCCL backend currently. 

In the longer term, we can discuss with NCCL and see if there is demand for these ops from users.
