### ISSUE TITLE
Is STFT in torchaudio consistent with librosa?

### ISSUE THREAD

**Issue by LordOfLuck** [pytorch/pytorch#41533]
Are pytorch implementations of signal processing tools from torchaudio consistent with librosa implementations?

**Comment by dangpzanco** [comment]
I think you'd better ask that on https://github.com/pytorch/audio

**Comment by zou3519** [comment]
cc @vincentqb, @mthrok

**Comment by mthrok** [comment]
As far as I know, `stft` was not part of `torchaudio`. (@vincentqb can clarify on this one)

`istft` was originally `torchaudio`, but recently moved to `pytorch`. 

See https://github.com/pytorch/pytorch/issues/3775 for the development around FT.

We check that `istft` is inverse of `torch.stft`, (see [the tests here](https://github.com/pytorch/audio/blob/master/test/functional_cpu_test.py) the same tests have been ported to PyTorch main repo.) but we do not check the parity against `librosa`.

@LordOfLuck

> consistent with librosa implementations?

If you can give the configuration you are considering to use, we can provide you better insight. In general, I do not expect PyTorch's `stft` to match `librosa` for all the possible combination of parameters. (at least I did not see a test torch check the parity of `stft`).

**Comment by SsnL** [comment]
`torch.stft` was written to exactly match librosa's (other than possibly not supporting some padding options).

**Comment by SsnL** [comment]
@mthrok https://github.com/pytorch/pytorch/blob/fbd960801a221c1d0197dbbae3ef2cdfaaeed60f/test/test_torch.py#L13834-L13896

**Comment by vincentqb** [comment]
Beyond `stft` and `istft`, as suggested above, this question is better asked on [torchaudio](https://github.com/pytorch/audio/issues) -- which does offer more operations that are consistent with librosa that you can take a look at :) Please feel free to open an issue there to ask about operations you are specifically interested in.

Otherwise, for more general non-development question about pytorch, please also visit the [forum](https://discuss.pytorch.org/). In the meanwhile, I will close this issue, but feel free to re-open if this does not address your issue.
