### ISSUE TITLE
Export LSTM to ONNX with sequence length and dynamic batch size

### ISSUE THREAD

**Issue by zhujiangang** [pytorch/pytorch#41774]
I use LSTM to modeling text with the following code, the shape of `inputs` is [batch_size, max_seq_len, embedding_size], the shape of `input_lens` is [batch_size]. `rnn` is simply a bidirectional LSTM defined as follows:

```python
self.rnn = nn.LSTM(self.input_dim, self.hidden_size, self.num_layers,
                               bidirectional=self.bidirectional, dropout=self.dropout, batch_first=True)

padded_seq_len = inputs.shape[1]

# Sort by length (keep idx)
_, idx_sort = torch.sort(input_lens, dim=0, descending=True)
_, idx_unsort = torch.sort(idx_sort, dim=0)

inputs = inputs.index_select(0, idx_sort)
input_lens = list(input_lens[idx_sort])

# Handling padding in Recurrent Networks
inputs_packed = nn.utils.rnn.pack_padded_sequence(inputs, input_lens, batch_first=True)
self.rnn.flatten_parameters()
if str(self.cell).lower() == 'lstm':
    outputs, (hn, cn) = self.rnn(inputs_packed)
elif str(self.cell).lower() == 'gru':
    outputs, hn = self.rnn(inputs_packed)

outputs = nn.utils.rnn.pad_packed_sequence(outputs, batch_first=True, total_length=padded_seq_len)[0]

# Un-sort by length
outputs = outputs.index_select(0, idx_unsort)
hn = hn.index_select(1, idx_unsort)
```

However, when I try to export this model to ONNX with dynamic batch_size, I cannot get the parity result with the original pytorch checkpoint. Anyone has such experience?

I also posted this question in discussion forum.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@zhujiangang - can you check if there's anything obviously wrong in your exported ONNX model. Please make sure that the model export is semantically correct by using scripting wherever there is input-dependent control flow. See this page for details: https://pytorch.org/docs/stable/onnx.html

If there's an export issue, please add sufficient repro steps here. If the export is fine, this could be an issue with the ONNX backend that you are running and it would be better to open an issue there.

**Comment by garymm** [comment]
@zhujiangang is this still an issue with the latest nightly version of PyTorch?
If so, we'll need more info to work on this. Can you provide a checkpoint of the trained model, and code that loads the checkpoint, exports, and demonstrates the output mismatch between the ONNX and PyTorch models?

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
