### ISSUE TITLE
Feature request: convNd and im2col

### ISSUE THREAD

**Issue by szagoruyko** [pytorch/pytorch#419]
Would be good to have N-dimensional convolution and separate im2col-col2im ops, like in caffe: https://github.com/BVLC/caffe/blob/master/src/caffe/util/im2col.cu

**Comment by andreaskoepf** [comment]
For CPU there seems to be some functionality that is similar to im2col with `unfolded_copy` and `unfolded_acc`, e.g. see [THNN/generic/unfold.c](https://github.com/pytorch/pytorch/blob/0f65c9267d5ec55584b0ec65acb5374c95af9c16/torch/lib/THNN/generic/unfold.c).

Since GPU version is missing I guess unfolded_copy and unfolded_acc are currently not integrated into the autograd system but they are already 'inofficially' callable from python, e.g. 

```
torch._thnn.type2backend[torch.FloatTensor].unfolded_copy(...)
torch._thnn.type2backend[torch.FloatTensor].unfolded_acc(...)
```

Internally these functions are used from CPU C code in the [SpatialConvolutionMM_updateOutput_frame](
https://github.com/pytorch/pytorch/blob/0f65c9267d5ec55584b0ec65acb5374c95af9c16/torch/lib/THNN/generic/SpatialConvolutionMM.c#L56-L97) function. Currently they operate only on a single element of a batch.

+1 for im2col and col2im support.

**Comment by thisismohitgupta** [comment]
Need this implementation. I am trying to feed an input window of 3X3 through out the feature map directly to an Rnn. Really looking forward for the reply...

**Comment by jbarker-nvidia** [comment]
@soumith I would like to get access to im2col too and am happy to help on the implementation.  Any pointers on how to proceed would be helpful.  Thanks

**Comment by szagoruyko** [comment]
@jbarker-nvidia @thisismohitgupta I have cupy/pytorch implementation here https://gist.github.com/szagoruyko/16f82748d73d2051c11bb7e47a3f9953

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/2580
