### ISSUE TITLE
What the meaning of pooled_w in roi_align function?

### ISSUE THREAD

**Issue by xudongwang0828** [pytorch/pytorch#41919]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
![image](https://user-images.githubusercontent.com/55836558/88287366-c40e2700-cd24-11ea-8a7f-56d88ad5ca8c.png)
Hello, i wonder what the meaning of the pooled_w when sampling_ratio <=0 ,i think it is the output_size, and i implement roi_align function by myself,when the sampling_ratio is 1,i have the same results with torchvision's results,but when i set this parameter to -1,the results of mine have a big gap with torchvision result.
So can you tell me what the meaning of pooled_w?

cc @fmassa @vfdev-5

**Comment by mrshenli** [comment]
Hey @xudongwang0828, could you please use [the forum](https://discuss.pytorch.org/c/vision/5) for questions? You can create a new topic under the "vision" category. I am closing this issue for now, but please feel free to create a new issue if this turns out to be bug report of feature request. Thanks!
