### ISSUE TITLE
Bad link to a tutorial about Distributed Overview

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/pytorch#42000]
## 📚 Documentation

"Distributed RPC Framework" documentation (master version) contains the following note:

> Please refer to [PyTorch Distributed Overview](https://pytorch.org/docs/master/rpc.html) for a brief introduction to all features related to distributed training.

<img width="976" alt="Screen Shot 2020-07-24 at 12 44 58" src="https://user-images.githubusercontent.com/2459423/88383996-dd0deb00-cdab-11ea-86ed-89def1b30e58.png">

The link behind "PyTorch Distributed Overview" is missing.

I could send a PR with a quick fix, but I can not figure out where is the correct ressource...

cc @mrshenli

**Comment by colesbury** [comment]
cc @mrshenli where should the link point to?

**Comment by mrshenli** [comment]
Hey @vfdev-5, this is expected. The page you accessed is the master instead of the stable doc release. The distributed overview page is at https://github.com/pytorch/tutorials/blob/release/1.6/beginner_source/dist_overview.rst. @jlin27 will flush contents in `release/1.6` branch into the master branch when we announce v1.6 release. After that, the link would work.

**Comment by vfdev-5** [comment]
@mrshenli thanks for the explanation, make sense ! Let me close the issue, then.

**Comment by mrshenli** [comment]
Hey @vfdev-5, v1.6 is released, and here is the link to the overview page: https://pytorch.org/tutorials/beginner/dist_overview.html

Please let us know if you hit any broken link from there, then we will need a fix for sure. :)

**Comment by vfdev-5** [comment]
@mrshenli links work perfectly 👍
