### ISSUE TITLE
The cuda version of torch.det is much slower than cpu version, why?

### ISSUE THREAD

**Issue by densechen** [pytorch/pytorch#42108]
I test torch.det function with the following script:

`
import torch
import time

t = torch.randn(4, 784, 4, 3, 3)
tic_start = time.time()
torch.det(t)
print("cpu: ", time.time() - tic_start)

t = t.cuda()
tic_start = time.time()
torch.det(t)
print("cuda: ", time.time() - tic_start)

`

and get the following output:
cpu:  0.01205134391784668
cuda:  1.553579330444336

I am using a TITAN X GPU. 
Why the det calculation on cuda is much slower than it on cpu?

**Comment by Nikronic** [comment]
Try to run your experiment using `timeit`. For the first run cuda might be slower due to some overload.
Here is my experiments:
```
t = torch.randn(4, 784, 4, 3, 3)
%timeit torch.det(t)
# 1000 loops, best of 3: 1.83 ms per loop

t = t.cuda()
%timeit torch.det(t)
# 1000 loops, best of 3: 659 µs per loop
```

**Comment by ngimel** [comment]
It's correct that the first cuda run is slower because it includes Magma library initialization. The script in the second comment is not performing correct synchronizations either. Please use Timer utility to properly benchmark code, see [README](https://github.com/pytorch/pytorch/tree/master/torch/utils/_benchmark) and simple_timeit in the examples. You'd need a recent pytorch build for that. With proper timing, cuda det is much faster than cpu det.
