### ISSUE TITLE
Custom collate_fn and _use_shared_memory

### ISSUE THREAD

**Issue by mikepound** [pytorch/pytorch#4232]
Hi,

I'm writing my own batch collate function, and I was trying to re-implement the tensor concatenation bit of default_collate. Your default implementation uses the variable _use_shared_memory, but I'm struggling to get access to it from within my own function. Plus it's marked as "private", should it be passed to the collate as a parameter? Or am I best just ignoring it and using torch.stack? Any advice appreciated!

Mike

**Comment by apaszke** [comment]
It's a variable local to the default collating function, so you shouldn't depend on it. It's just an optimization and isn't required (`torch.stack` is sufficient). If you want to mimic that code, you can assume that it's True if you have worker subprocesses and False otherwise.

Also, note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
