### ISSUE TITLE
LSTMCell and GRUCell need autocast patching

### ISSUE THREAD

**Issue by mcarilli** [pytorch/pytorch#42605]
https://github.com/pytorch/pytorch/pull/42385 fixes cudnn RNNs with `torch.cuda.amp.autocast` but it appears the cell-based RNN API is also broken:
https://discuss.pytorch.org/t/runtimeerror-expected-scalar-type-half-but-found-float/91628

I thought cell-based RNNs were implemented in terms of autograd-exposed primitive ops (gemms, etc) already covered by autocast, but LSTMCell and GRUCell have [dedicated autograd functions](https://github.com/pytorch/pytorch/blob/db52cd7322ccf3f2121f1a6e592ddb436968aa50/tools/autograd/derivatives.yaml#L1756-L1761).  I should add FP16 cast wrappers for these.  I may need to add wrappers at a higher level instead, ie wrap the Python-exposed `at::lstm_cell` and `at::gru_cell`, depending where in the call chain input type checking occurs.

cc @mcarilli @ppwwyyxx @ngimel @zou3519

**Comment by dlrac** [comment]
@mcarilli I saw your patch for RNNs has been merged (#42385) and many, many thanks for the patch! 

I would be very grateful if you would be so kind to to let me know what's the status on this one?

PS: while they have a different interface, I know LSTM can be used instead of LSTMCell, but would still like to know about the patch before I start converting the whole code base...

**Comment by mcarilli** [comment]
My intention is to have a PR up by next Friday.  Will ping this issue.

**Comment by dlrac** [comment]
@mcarilli Thanks for the response (and future PR ofc)!

**Comment by mcarilli** [comment]
^

**Comment by mcarilli** [comment]
try with current master, it should work now.
