### ISSUE TITLE
download  documentation

### ISSUE THREAD

**Issue by XiaoJiNu** [pytorch/pytorch#42659]
Hi , I want to download documentaion in order to make notes, how can I do it?

**Comment by mariosasko** [comment]
One option is to clone this repo, and build the docs following the [guidelines](https://github.com/pytorch/pytorch#building-the-documentation). Since the docs are autogenerated using Sphinx, if you want to add notes you will have to use markdown. 

For a bit easier approach, check this [repo](https://github.com/unknownue/PyTorch.docs) that relies on html and seems up to date. Right now, I don't think there is a more human-friendly approach (e.g. docs in pdf).

**Comment by ailzhang** [comment]
Yup I think @mariokostelac's suggestions makes sense.

**Comment by mariokostelac** [comment]
You've probably meant @mariosasko :).

**Comment by XiaoJiNu** [comment]
@mariokostelac thank you!
