### ISSUE TITLE
Improvement of autograd engine original task placement in worker threads

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#42890]
Currently, when a call to the autograd engine is done, the original task is always placed on the CPU worker queue.
While this works great, it can lead to surprising behavior, in particular when re-entrant autograd happen from a GPU thread.

Indeed, even though the whole code runs on a GPU and should run serially on the GPU thread, the original task happening on the CPU can lead to non-determinism and bad ordering of the execution (which can lead to very bad memory usage when using checkpointing and independent branches).

From the top of my head, I think we should:
- Remove [this code](https://github.com/pytorch/pytorch/blob/4fc525e72976a470ca7a56264734c3cb0afe1fe8/torch/csrc/autograd/engine.cpp#L867) when there is a single input: we can just use that input's grad_fn as the graph root. That will be better perf-wise, especially for very small graphs.
- Change [this code](https://github.com/pytorch/pytorch/blob/4fc525e72976a470ca7a56264734c3cb0afe1fe8/torch/csrc/autograd/engine.cpp#L892-L893) to push on the right queue based on the inputs (mimicking the logic [here](https://github.com/pytorch/pytorch/blob/4fc525e72976a470ca7a56264734c3cb0afe1fe8/torch/csrc/autograd/input_buffer.cpp#L121-L137)).

Even though I wouldn't expect anyone to rely on this, this would be BC-breaking. But I think the determinism and gain in memory in these cases will be worth it.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @gchanan @SsnL

**Comment by wanchaol** [comment]
Seems to me that the main change here is to determine the correct device ready queue for GraphRoot by examing the inputs device? This sounds good to me as I didn't see any potential issues for this approach. 

For distributed engine, we are still doing similar thing like the current local autograd engine, but it's a bit different, we maintain a `ready_queue` per GraphRoot, and always push to this newly allocated ready queue (see code [here](https://github.com/pytorch/pytorch/blob/54c05fa34e1fbbb5096746a8ae92e27a08116de4/torch/csrc/distributed/autograd/engine/dist_engine.cpp#L291)). since it's manually polled off tasks from this newly allocated queue, the approach you proposed might not just work for the dist engine. @pritamdamania to confirm here.

**Comment by albanD** [comment]
> we maintain a ready_queue per GraphRoot

What about the re-entrant case?
A particular example that can be problematic is something like 
```python
inp = torch.rand(10, requires_grad=True, device="cuda")
out1 = checkpoint(f1, inp)
out2 = checkpoint(f2, inp)
loss = crit(out1, out2)
loss.backward()
```
Here, when the first checkpoint backward is hit, the re-entrant enqueues the GraphRoot on the CPU queue. And so the GPU worker starts doing the second checkpoint (recomputing another forward, etc).
So there will be no memory benefit by using checkpoint in this case because the engine runs both of them in an interleaved manner even even though they only contain GPU tasks that should run sequentially on a single thread.

What would happen if we do this in the distributed engine?

**Comment by wanchaol** [comment]
> What about the re-entrant case?
> A particular example that can be problematic is something like
> 
> ```python
> inp = torch.rand(10, requires_grad=True, device="cuda")
> out1 = checkpoint(f1, inp)
> out2 = checkpoint(f2, inp)
> loss = crit(out1, out2)
> loss.backward()
> ```
> 
> Here, when the first checkpoint backward is hit, the re-entrant enqueues the GraphRoot on the CPU queue. And so the GPU worker starts doing the second checkpoint (recomputing another forward, etc).
> So there will be no memory benefit by using checkpoint in this case because the engine runs both of them in an interleaved manner even even though they only contain GPU tasks that should run sequentially on a single thread.
> 
> What would happen if we do this in the distributed engine?

I think when we added the functionality of maintaining separate ready_queues for each graph root, we had the assumption that we don't support re-entrant bnackward case in dist_engine. And there's no distinction for all ready_queues in the dist_engine as we all do this `execute until empty` style on a separate CPU thread (no dedicated GPU thread). 

For the case that you mentioned above, I agree with you that it's kinda losing the benefits of checkpointing. I don't really know how would checkpointing works together with the dist engine in today's design. @pritamdamania can you chime in here?

**Comment by pritamdamania87** [comment]
reentrant-backward/checkpointing are not officially supported in the distributed engine and we explicitly didn't target support for this to keep the original implementation simple.

Although to resolve this issue for the distributed engine, why can't we first check the root to see if it needs to be enqueued on the GPU queue and push it to the appropriate GPU queue instead of enqueueing it on the CPU queue. If we have a CPU task, we create a new queue and just execute until empty.

**Comment by albanD** [comment]
After more exploration, the change in the threading system, when we perform re-entrant from a GPU worker thread, it is (wrongfully?) picking up the GPU worker thread queue as its new CPU queue and so the new task is actually enqueued on the right queue.
So the non-determinism mentioned above does not actually exist in master anymore and this won't be BC-breaking.
