### ISSUE TITLE
[jit] global class variable used in Module can't be compiled

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#42945]
```python
import torch
from torch import nn

@torch.jit.script
class GroupType(object):
    def __init__(self):
        self.WORLD = 5

group = GroupType()


class TestMod(nn.Module):
    def __init__(self, group):
        super(TestMod, self).__init__()

    def forward(self, input: int):

        if input > 2:
            return group.WORLD + 1
        else:
            return group.WORLD + 5

scripted_mod = torch.jit.script(TestMod(group))
print(scripted_mod.graph)
```
cc @ezyang @gchanan @zou3519 @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Some background: This request comes from supporting [c10d all_to_all API](https://github.com/pytorch/pytorch/blob/8094228f26cdef24529bffadd6a6e43b56df2d6e/torch/distributed/distributed_c10d.py#L1669).

The requirement is that we can not change how users interact with the API. I think there are three ways users call it.

1. Not passing group at all
2. Passing default `group=group.WORLD` explicitly
3. Passing custom `group=FooGroup`

2 and 3 already are incompatible with each other because group.WORLD is an `object` while `FooGroup` is a TorchBind class (ProcessGroup). Since TorchScript doesn't support union type yet, this is already a problem.

I think there is a way to reconcile this issue though, if we change the API to:
```python
def all_to_all(output_tensor_list,
               input_tensor_list,
               group=None: Optional[ProcessGroup],
               async_op=False):
    if group is None:
        group = _default_pg                 # Need to figure out a good way to pass global variable _default_pg

   # replace all references to group.WORLD with _default_pg
```

This will make use pattern 1 and 3 just work. As for 2, we can go two ways:

a) Globally set `group.WORLD` to None
b) Globally set `group.WORLD` to _default_pg (possibly as an object property so that it can access latest _default_pg value

Technically, this will maintain all usages in user code even though it changes the API a little bit. Do you think this is acceptable from c10d design perspective? Are there any other BC promise that we need to keep?

If we do this, `group` argument only has a single type and

**Comment by wanchaol** [comment]
I think if we choose the option a) it's fine as the user API almost not change. (Unless user use `group.WORLD` separately and do some isinstance check on their own, which I believe happens rarely). It's still a minor API change though, @jiayisuse @mrshenli @lw what do you guys think about this API change?

**Comment by gmagogsfm** [comment]
This is no longer an issue. We are taking an approach that pushes all these states inside C++.
