### ISSUE TITLE
Enable torch.jit typechecks during CI 

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#42981]
`TestTypeHints.test_run_mypy_strict` should pass with `[mypy-torch.jit.*]` deleted from `mypy.ini`

cc @suo @gmagogsfm @ezyang @malfet @rgommers

**Comment by SplitInfinity** [comment]
I'm working on this in the few minutes I have here and there: #43862. It's not ready yet but should be after a week or two.

**Comment by SplitInfinity** [comment]
I don't see an existing stubs file for `torch._VF`. Can someone point me to an example of how I can create one?

**Comment by SplitInfinity** [comment]
Also, `TestTypeHints.test_run_mypy_strict` already passes on master with `[mypy-torch.jit.*]` deleted from `mypy.ini`. Did you mean `TestTypeHints.test_run_mypy`? That one fails.

**Comment by rgommers** [comment]
Since `_VF.py` is a hack to access the functions in `_C._VariableFunctions`, what should work is to copy the generated stub file for the latter. If you add the copy below 
```
write(out, 'torch/_C/_VariableFunctions.pyi', TORCH_C_VARIABLE_FUNCTIONS_TYPE_STUBS, env)
```
in `tools/pyi/gen_pyi.py`, it may be a one-liner fix.

If that doesn't work (but it really should), it's probably not worth doing more work to add a new stub file - then you can just add `# type: ignore` to the `_VF.xxx` calls.


> Also, `TestTypeHints.test_run_mypy_strict` already passes on master with `[mypy-torch.jit.*]` deleted from `mypy.ini`. Did you mean `TestTypeHints.test_run_mypy`? That one fails.

First step is to make them pass with the non-strict config indeed, for that you can run `TestTypeHints.test_run_mypy` (or simply type `mypy` in the repo root).

The request for `strict` here is probably because the JIT related files should be treated more strictly - given that subtle errors in the JIT have large consequences, trying harder to find bugs is worth it.

To do so, add the files you want to have strict mode on to `files = ...` at the bottom of `mypy-strict.ini` in the root of the repo.

**Comment by SplitInfinity** [comment]
```
write(out, 'torch/_C/_VariableFunctions.pyi', TORCH_C_VARIABLE_FUNCTIONS_TYPE_STUBS, env)
```
 already exists in `tools/pyi/gen_pyi.py`. Did you meant to write
```
write(out, 'torch/_VF/__init__.pyi', TORCH_C_VARIABLE_FUNCTIONS_TYPE_STUBS, env)
```

**Comment by rgommers** [comment]
Yes, that's what I meant.

**Comment by SplitInfinity** [comment]
Cool, seems to work, thanks.

**Comment by SplitInfinity** [comment]
I just tried strict mode like you suggested and I see a lot of failures in non-JIT code, probably due to mypy following imports. Do those need to be fixed too? I'm most familiar with JIT code, so I am not the right person to address those.

**Comment by SplitInfinity** [comment]
In any case, I enabled standard typechecks during CI for JIT in #43862 and it seems to be working.

**Comment by rgommers** [comment]
I'm not quite sure, hard to say without seeing the failures. Maybe put up a WIP PR? Maybe I can help by just pushing a fix to your branch, or if there's too much to fix in strict mode we can just merge the regular mode first - that'd be a good step forward already.

**Comment by rgommers** [comment]
Oh never mind, you have gh-43862 up already. I'll try that with strict mode.

**Comment by SplitInfinity** [comment]
Yeah, that PR has regular mode passing. Documentation tests are mysteriously failing and I've contacted the contributors most familiar with them in order to investigate but the rest of the tests look okay.

**Comment by rgommers** [comment]
That's an awful lot of failures (10000+) if I add one JIT file to the `files=` list in `mypy-strict.ini`. I'd say it's not worth bothering with those now, let's merge the PR in its current form and call it good.

Only once all of PyTorch has type annotations does it make sense to try and enable strict mode for the files in `torch/jit/` it seems.

**Comment by SplitInfinity** [comment]
My PR to enable basic type annotations has landed. Let's pause on enabling strict mode until more of the codebase has type annotations.

**Comment by rgommers** [comment]
Makes sense. I think we can close this issue. Having one that's not actionable for a few months isn't too useful; once we're at the "kind of complete" stage, we can reconsider what should have strict mode. For now with `--follow-imports` the `test_run_mypy_strict` doesn't make sense except for codegen scripts that don't import anything else.
