### ISSUE TITLE
PyTorch binaries for macOS has serial at::parallel_for because it is built with OpenMP which  is not available

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#43036]
A silly performance test linearly depends(1000 times slower on 1000x larger tenor) on tensor size on macOS(with 6 cores i9) but  can be 4-10 time faster on Linux or Windows:
```
In [2]: t = torch.ones(1000, device='cpu')

In [3]: timeit t.pow(123)
7.45 µs ± 343 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: t = torch.ones(1000000, device='cpu')

In [5]: timeit t.pow(123)
5.83 ms ± 246 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

`torch.__config__.parallel_info()` says for all OSes that PyTorch was compiled with OpenMP but it's not actually available on macOS:

```
at::get_num_threads() : 1
at::get_num_interop_threads() : 6
OpenMP not found
...
ATen parallel backend: OpenMP
```

Version.cpp:
```
std::string get_openmp_version() {
#ifdef _OPENMP
...
#else
  ss << "OpenMP not found";
#endif
}
```

ParallelOpenMP.h:
```
inline void parallel_for(..., const F& f) {
...
#ifdef _OPENMP
...
#else
  f(begin, end);
#endif
}
```
which looks like serial invocation.

This affects at least PyTorch 1.3.0-1.6.0 both pip and conda

cc @ezyang @gchanan @zou3519 @malfet @VitalyFedyunin

**Comment by malfet** [comment]
Grabbing this one for myself.

**Comment by malfet** [comment]
I think this is controlled here:
https://github.com/pytorch/pytorch/blob/059aa34b124916dfd761f3cbdb5fa97d7a01fc93/caffe2/CMakeLists.txt#L13-L17

**Comment by ezyang** [comment]
As follow up, we should have binary testing that ensures we are actually getting multithreaded speed up.

**Comment by rfeinman** [comment]
@malfet @pbelevich I wonder if switching to native threading was the best solution for this. Here is my concern.

#### Problem

I've been working with the pre-built Mac OS binaries from the conda pytorch channel (both stable and nightly). Since the binaries use native threading, I am unable to call `torch.set_num_threads` more than once. When I do, I get the following message:

```
Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
```

This is a bummer, since I can't tune the number of threads for an op as per the [PyTorch threading tutorial](https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html#tuning-the-number-of-threads). I also can't use the "num_threads" feature in the new `torch.utils.benchmark.Timer` tool to test runtime performance at different thread counts.

Another strange finding with the Mac OS binaries is that, looking at `torch.__config__.parallel_info()`, pytorch seems to think my mkl distribution is configured with `mkl_get_max_threads() : 1`, even though it reports `at::get_num_threads() : 6`. When I check the same mkl distribution in C++ (e.g. by linking the library and include directories from my conda environment), I see that `mkl_get_max_threads() == 6`. It's unclear what the performance implications are, but if MKL-based BLAS and LAPACK operations are unable to benefit from parallelism, this would certainly be a concern. In an equivalent linux binary, I see that mkl_get_max_threads() matches at::get_num_threads(), the expected behavior.

#### Suggestion

Rather than use native threading, there is an easy fix to make OpenMP work properly as per Linux and Windows binaries. According to [this discussion](https://github.com/oneapi-src/oneDNN/issues/591) on oneDNN, the problem seems to be that [FindOpenMP.cmake](https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindOpenMP.cmake) does not work properly with Apple Clang. They found two quick fixes - [number 1](https://github.com/oneapi-src/oneDNN/issues/591#issuecomment-552293435) and [number 2](https://github.com/oneapi-src/oneDNN/issues/591#issuecomment-553742873) - which can be used to solve the issue with Homebrew Clang and native Apple Clang, respectively. Perhaps we can add these fixes to whatever Clang compiler is used to build the conda Mac OS binaries.
