### ISSUE TITLE
How to use torch.utils.checkpoint and DistributedDataParallel together

### ISSUE THREAD

**Issue by devilztt** [pytorch/pytorch#43135]
when I use DistributedDataParallel in mutil-GPU , If I use checkpoint  in the model forward ,it can not work 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by cyy5358** [comment]
Hi, code below works fine with me.
```python
model = torch.nn.parallel.DistributedDataParallel(model)
ms = model.module if data_parallel else model
ms.load_state_dict(checkpoint["model_state"])
```
If there is better practice, please let me know

**Comment by devilztt** [comment]
emmm... That was not  what I meant ，I’m talking about ‘torch.utils.checkpoint’, which can help save gpu memory

> Hi, code below works fine with me.
> 
> ```python
> model = torch.nn.parallel.DistributedDataParallel(model)
> ms = model.module if data_parallel else model
> ms.load_state_dict(checkpoint["model_state"])
> ```
> 
> If there is better practice, please let me know

**Comment by mrshenli** [comment]
Hey @devilztt, this does not work yet, see #24005. One workaround is to synchronize gradients manually after the backward call.

**Comment by devilztt** [comment]
@mrshenli Hey,I have seen #24005,but when I try your mrshenli:delay , There is another error appeared.

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your modul$
has parameters that were not used in producing its output (the return value of forward). You can enable unused parameter detection by
passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel. If you already have this argu$
ent set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's forwar$ function. Please include the structure of the return value of forward of your module when reporting this issue (e.g. list, dict, ite$
able)

It also appeared in the official pytorch version，regardless of whether I added find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel. The apex.parallel.DistributedDataParallel can work ,but it can't work with torch.utils.checkpoint even though I add delay_allreduce=True.

**Comment by mrshenli** [comment]
Hey @devilztt if you are manually synchronizing gradients, then you don't need DDP anymore. 

```python
init_process_group(...)
model = MyModel(...)
model(inputs).sum().backward()
works = []
for p in model.parameters():
    # to speed it up, you can also organize grads to larger buckets to make allreduce more efficient
    works.append(dist.all_reduce(p.grad, async_op=True))
for work in works:
    work.wait()
...
```

**Comment by devilztt** [comment]
@mrshenli Thank you very much.I found out that the problem was due to the use of apex's syncbn ,when I use the syncbn and checkpoint , It would die in loss backward.Now I use apex.parallel.DistributedDataPallel with delay_allreduce = True  and torch.utils.checkpoint , it can work .

**Comment by ekhahniii** [comment]
Hi @mrshenli, I currently take [your suggested approach](https://github.com/pytorch/pytorch/issues/43135#issuecomment-676852360) (verbatim) to use torch.utils.checkpoint in a distributed setting. Unfortunately, I do notice a significant accuracy drop compared to DDP when manually reducing (and averaging) gradients, without other code changes (besides not wrapping the model in DDP). 

I'm wondering, would you say it is reasonable to expect similar task (not computational) performance between these two approaches?

**Comment by visionscaper** [comment]
@mrshenli @ekhahniii I have the same issue that when I manually `all_reduce` the gradients, and don't wrap my model in DDP, the training loss degrades (isn't as low as when using DDP without checkpoints). When I use `nn.DataParallel` I'm not observing this loss degradation when using checkpoints, unfortunately `nn.DataParallel` is much slower and uses more GPU memory.

I already ensured that my (Float type) inputs to the checkpoints have `input.requires_grad_()` as [suggested here](https://discuss.pytorch.org/t/training-with-gradient-checkpoints-torch-utils-checkpoint-appears-to-reduce-performance-of-model/78102/2?u=visionscaper) by @albanD.

What else could be wrong?

Some more info that might be relevant:
1) I know I use a shared embedding layer in the modules that I checkpointed.
2) I can't apply to `requires_grad_()` to non-float tensors; my checkpointed modeles also have `LongTensor` inputs.

I really hope this can be resolved because the multi-process training is so much more efficient than when using `nn.DataParallel`.

**Comment by zhaojuanmao** [comment]
to use all_reduce manually, you need to divide your gradient to world size first, and then call all_reduce. In this way, you can get averaged gradient instead of summed gradient.

**Comment by visionscaper** [comment]
@zhaojuanmao Ah yes of course, thanks, good point. However, unfortunately, it didn't make a difference, I just tried it.

Earlier, I also checked if it could be related to dropout (related to RNG state) or using the shared embedding layer, so I refactored out the embedding layer and tried with dropout 0.0; there was no effect, the loss was still degraded.

In one of the checkpointed modules I do make new tensors, but I directly transfer them to the device that all other tensors also use. Could this still cause the problem I'm experiencing? I'm at a loss (pun not intended), I tried so many different variations, but the loss keeps degraded compared to using `nn.DataParallel`.

**Comment by visionscaper** [comment]
@zhaojuanmao I solved my issue, I just made a silly mistake; in my training software I added the manual `all_reduce` in a callback after the optimizer step(). Because I didn't realize that, I ended up spending a lot of time in trying to find the issue in other places. 🤦🏻‍♂️

Very happy now that training uses approx. a factor 3x (!!) less GPU memory than without checkpointing. This is amazing.

**Comment by fliman** [comment]
Looks like in pytorch v1.13 'DistributedDataParallel' doesn't have 'delay_allreduce' option, so what's the suggest solution for this issue now?

**Comment by zhangxinyu-xyz** [comment]
> Looks like in pytorch v1.13 'DistributedDataParallel' doesn't have 'delay_allreduce' option, so what's the suggest solution for this issue now?

Hi, I met the same problem. How do you solve it?
