### ISSUE TITLE
MASTER_ADDR and MASTER_PORT

### ISSUE THREAD

**Issue by XiaoJiNu** [pytorch/pytorch#43207]
Hi, when I want to use mutiple gpus to train a model, Distributed Data Parallel tells me that I should set MASTER_ADDR and MASTER_PORT, but I don't konw what they are and what value I should set ?

**Comment by ag14774** [comment]
If the GPUs are on the same computer, just set an environment variable MASTER_ADDR=127.0.0.1  and set MASTER_PORT to any number e.g MASTER_PORT=6006.

**Comment by XiaoJiNu** [comment]
@ag14774 Thank you very much! So, could you please tell me what they are or any documentation about them?

**Comment by ag14774** [comment]
When you are using DistributedDataParallel, multiple processes are launched and create a process group. In the process group, one process needs to be the master process. MASTER_ADDR needs to be the address of the host running the master process. If you were running processes across a network on different nodes/computers/hosts, MASTER_ADDR would need to be set to the address of one of those computers. Since I assume all processes are running on the same host, you set MASTER_ADDR to 127.0.0.1 which means use current computer as host. 127.0.0.1 means localhost.

**Comment by pbelevich** [comment]
Please use https://discuss.pytorch.org/ for questions and discussions

**Comment by XiaoJiNu** [comment]
@ag14774 @pbelevich Thank you so so so much good men!
