### ISSUE TITLE
Uninformative forward trace in detect_anomaly for double backward

### ISSUE THREAD

**Issue by mfkasim91** [pytorch/pytorch#43405]
## 🐛 Bug

`torch.autograd.detect_anomaly()` produces uninformative forward trace if nan is produced in double backward using built-in functions.

## To Reproduce

Here's a sample code to illustrate what I meant:

    import torch

    def main():
        x = torch.tensor(0.4, requires_grad=True)
        y = torch.tensor(0.0, requires_grad=True) # zero to induce nan in 2nd backward
        z = x / y
        gy, = torch.autograd.grad(z, (y,), create_graph=True)
        gyx, gyy = torch.autograd.grad(gy, (x, y), create_graph=True)
        return gyx, gyy

    with torch.autograd.detect_anomaly():
        main()

The output:

    Warning: Error detected in MulBackward0. Traceback of forward call that caused the error:
      File "/home/mfkasim/anaconda3/lib/python3.7/traceback.py", line 197, in format_stack
        return format_list(extract_stack(f, limit=limit))
     (print_stack at /opt/conda/conda-bld/pytorch_1591914794252/work/torch/csrc/autograd/python_anomaly_mode.cpp:60)
    Traceback (most recent call last):
      File "testtest.py", line 12, in <module>
        main()
      File "testtest.py", line 8, in main
        gyx, gyy = torch.autograd.grad(gy, (x, y), create_graph=True)
      File "/home/mfkasim/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 158, in grad
        inputs, allow_unused)
    RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.

The forward trace only points to `format_stack` in python's `traceback` and it doesn't point to where I'm supposed to look at.

## Expected behavior

I would expect the forward trace would point to the line in python's script if there is a nan in autograd operation, even when nan is in higher order autograd operation.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Ubuntu 16.04.6 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7 (64-bit runtime)
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: -

## Additional context

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by mfkasim91** [comment]
Thanks for the suggestions! I'm interested in taking this one.
Could you please give me a hint on where to look at?

**Comment by albanD** [comment]
Sure!

I was thinking of having a state similar to [this one](https://github.com/pytorch/pytorch/blob/db78c07cedd1fef8a26000293e688fda7f6a0e54/torch/csrc/autograd/engine.cpp#L80-L82) but that track the current `Node`.
You can create a class like [this](https://github.com/pytorch/pytorch/blob/db78c07cedd1fef8a26000293e688fda7f6a0e54/torch/csrc/autograd/engine.cpp#L296-L306) to easily handle recursion.
And you want to set it at the same place [here](https://github.com/pytorch/pytorch/blob/db78c07cedd1fef8a26000293e688fda7f6a0e54/torch/csrc/autograd/engine.cpp#L378) but **only** when anomaly mode is enabled!

Then you can update the anomaly mode code to store the Node that is in this thread local if it exists [here](https://github.com/pytorch/pytorch/blob/db78c07cedd1fef8a26000293e688fda7f6a0e54/torch/csrc/autograd/function.h#L98-L100) (or directly in the "store_stack()" function.
I think the most useful thing to do use would be to store in the metadata a "parent" key that points to the parent Node. That way, we can actually inspect this from python as well if needed!
Because we know that the graph is directed, you can keep a strong reference to the parent Node and that should not leak memory.

Hope this helps!

**Comment by mfkasim91** [comment]
Thanks! I'll give it a try

**Comment by Sibozhu** [comment]
Hi @mfkasim1 ,

I just realized that the gist URL to your debugger is unavailable: https://gist.github.com/mfkasim91/9120b0864d52fecb59b1f2cbfacc3d82

Are you still working on this debugger? Would love to try it!

**Comment by mfkasim1** [comment]
Hi @Sibozhu, it's done. You can try it on the new pytorch (I think this is included in version 1.7)

**Comment by albanD** [comment]
Yes it is in 1.7 (and nightly as well of course)!
