### ISSUE TITLE
Add iterator like functionality for DispatchKeySet

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#43441]
As discussed in https://github.com/pytorch/pytorch/pull/43070/files, creating an issue to so that we can link to issue number in the comment.

cc: @ezyang

**Comment by ezyang** [comment]
DispatchKeySet represents an (ordered) set of dispatch keys in bitset form. A common thing people would like to do is to be able to iterate through all of the keys in a DispatchKeySet, in the usual idiomatic C++ way (e.g., using a range for loop). To do this, we have to create a auxiliary iterator class for DispatchKeySet that has all of the necessary methods.

Your job is to augment DispatchKeySet with an iterator type, so that you can iterate through dispatch keys. Research from a trustworthy source what exact API you need to implement to properly implement the iterator type. Decide on a reasonable implementation strategy for the iterator. Add some tests in `c10/test/core/DispatchKeySet_test.cpp` for your functionality. You don't have to wire it up anywhere; @ailzhang knows where this functionality would come in handy.

**Comment by ailzhang** [comment]
Closing since @linux-jedi 's PR is already merged. :D
