### ISSUE TITLE
Missing `IndexError` when accessing elements outside of shape of CUDA tensor

### ISSUE THREAD

**Issue by dichotomies** [pytorch/pytorch#43864]
## 🐛 Bug

A CUDA tensor can be used to access elements outside of its own memory scope (i.e. with indices that are invalid for its shape). 

## To Reproduce

```
zz = torch.ones(1, 2, 3).cuda()
for i in range(3):
    print(zz[0, [i]])
    print(zz.cpu()[0, [i]])
```

Results in output:
```
tensor([[1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.]])
tensor([[1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.]])
tensor([[4.2039e-45, 0.0000e+00, 5.6052e-45]], device='cuda:0')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-213-b304741f3d8f> in <module>
      2 for i in range(3):
      3     print(zz[0, [i]])
----> 4     print(zz.cpu()[0, [i]])

IndexError: index 2 is out of bounds for dimension 0 with size 2
```

## Expected behavior

The indices that can be used to access the elements of a tensor should be limited by the tensors shape. This works as expected if the tensor is initialized on CPU, but no `IndexError` is raised if the tensor is initialized on GPU.

In the example above, zz[0, [2]] should raise `IndexError`, because 2 is out of bounds for dimension 1 out of 0,1,2.

Note that the index error for the CPU tensor is raised because of "dimension 0", although I would expect dimension 1 to be the problem. Maybe that's helpful in finding the problem.

## Environment

```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: False
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (GCC) 7.1.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] pytorch3d==0.2.0
[pip] torch==1.5.0
[pip] torchfile==0.1.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] faiss-cpu                 1.6.3            py37h6bb024c_0    pytorch
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch3d                 0.2.0                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.6.0                py37_cu101    pytorch
```

**Comment by ailzhang** [comment]
I agree that the CUDA one should indeed raise...
On the CPU error message part, it's actually "makes sense" that you're essentially doing zz[0][2] where `2` is the size of dimension 0. If you call `zz[0, 2]` it'll correctly report the dimension. We could probably live the current error message for now but the CUDA issue might be a high pri.

**Comment by VinodSKumar** [comment]
Looks like this issue is already fixed in the latest version.  Could you please check once in the latest version.

**Output in latest version**
tensor([[1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.]])
tensor([[1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.]])
/home/vinod/forks/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/home/vinod/forks/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/home/vinod/forks/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(zz[0, [i]])
  File "/home/vinod/forks/pytorch/torch/tensor.py", line 172, in __repr__
    return torch._tensor_str._str(self)
  File "/home/vinod/forks/pytorch/torch/_tensor_str.py", line 372, in _str
    return _str_intern(self)
  File "/home/vinod/forks/pytorch/torch/_tensor_str.py", line 352, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/vinod/forks/pytorch/torch/_tensor_str.py", line 241, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/vinod/forks/pytorch/torch/_tensor_str.py", line 89, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

**Env details**

PyTorch version: 1.7.0a0+665feda
Is debug build: False
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 450.36.06
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0a0+665feda
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.18.5           py38ha1c710e_0  
[conda] numpy-base                1.18.5           py38hde5b4d6_0  
[conda] numpydoc                  1.1.0                      py_0  
[conda] torch                     1.7.0a0+665feda           dev_0    <develop>

**Comment by dichotomies** [comment]
I am not sure if this issue is fixed in the latest version (I'm using `1.7.0.dev20200907`), because this command now results in a runtime error instead of an index error.

For example, running:
```
zz = torch.ones(1, 2, 3).cuda()
zz[0, [2]]
```

results in `RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered`. This error makes this tensor now inaccessible. For example, if you try to access another element of this tensor (say with `zz[0, [0]]` or even simply `zz`), then you'll get another runtime error: `RuntimeError: CUDA error: device-side assert triggered`, which should not happen.

**Comment by ezyang** [comment]
@dichotomies you're referring to the problem that if we have a data dependent CUDA-side failure that triggers an assert, the CUDA context is permanently trashed. This *is* something worth working on, see for example a prototype for this at https://github.com/pytorch/pytorch/pull/26776 but it's distinct from the absence of a bounds check on a particular operator.

**Comment by VitalyFedyunin** [comment]
It is only 1.5 issue and it is already fixed.
