### ISSUE TITLE
torch.cat is over 300x slower than torch.index_copy / numpy.concatenate on CPU

### ISSUE THREAD

**Issue by david-macleod** [pytorch/pytorch#44025]
## 🐛 Bug

When running `torch.cat` on CPU tensors the execution time is over 300x longer than iterating over the tensors and calling `torch.index_copy_` to copy into slices of a pre-existing tensor. This may be due to the overhead of allocating new memory in the case of `torch.cat`, but passing a pre-existing tensor to the `out` argument in `torch.cat` produces the same slow behavior. Also running the equivalent with `numpy.concatenate` is as fast as `torch.index_copy_`.

## To Reproduce

```py
import torch
import numpy as np
import time
import torch.multiprocessing as mp

def torch_cat(_, in_xs, out_x):
    s = time.perf_counter()
    torch.cat(in_xs)
    print("torch_cat", time.perf_counter() - s)


def torch_cat_out(_, in_xs, out_x):
    s = time.perf_counter()
    torch.cat(in_xs, out=out_x)
    print("torch_cat_out", time.perf_counter() - s)
    assert torch.eq(torch.cat(in_xs), out_x).all()


def torch_index_copy(_, in_xs, out_x):
    s_time = time.perf_counter()
    part_size = in_xs[0].shape[0]
    for i, in_x in enumerate(in_xs):
        idxs =  torch.arange(i * part_size, (i+1) * part_size)
        out_x.index_copy_(0, idxs, in_x)
    print("torch_index_copy", time.perf_counter() - s_time)
    assert torch.eq(torch.cat(in_xs), out_x).all()

def numpy_cat(_, in_xs, out_x):
    s = time.perf_counter()
    np.concatenate(in_xs)
    print("numpy_cat", time.perf_counter() - s)

if __name__ == '__main__':

    n_procs = 10
    n_parts = 8
    shape = (8, 128, 100)

    in_xs = [torch.randn(*shape) for _ in range(n_parts)]
    out_x = torch.randn(shape[0] * n_parts, shape[1], shape[2])
    for func in [torch_cat, torch_cat_out, torch_index_copy]:
        for i in range(5):
            mp.spawn(func, nprocs=n_procs, args=(in_xs, out_x), join=True)

    in_xs = [np.random.randn(*shape) for _ in range(n_parts)]
    out_x = np.random.randn(shape[0] * n_parts, shape[1], shape[2])
    for func in [numpy_cat]:
        for i in range(5):
            mp.spawn(func, nprocs=n_procs, args=(in_xs, out_x), join=True)
```
### Output
```
torch_cat 0.698929596692323
torch_cat_out 0.6533345761708915
torch_index_copy 0.00210731104016304
numpy_cat 0.003372536040842533
```

## Expected behavior

`torch.cat` should be as fast as `tensor.index_copy_` / `np.concatenate` when using the `out` argument

## Environment

```
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti
GPU 8: GeForce RTX 2080 Ti
GPU 9: GeForce RTX 2080 Ti

Nvidia driver version: 440.100
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-memlab==0.2.1
[pip3] torch==1.6.0
```

## Additional information 
There is an existing [issue](https://github.com/pytorch/pytorch/issues/18634) which compares the execution times of `torch.cat` and `torch.clone`, and I have been able to confirm cat is slower than clone, but both are still orders of magnitude slower than `index_copy`. The issue I am raising seems closer to [this ](https://discuss.pytorch.org/t/the-efficiency-of-torch-cat/54271) post.

cc @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
cc @peterbell10, @ilia-cher - does it look like some threading issues you guys have dealt with? fwiw, we can't repro in single-threaded setting w/o multiprocessing.

**Comment by david-macleod** [comment]
Just to clarify, I see these issues regardless of the number of threads (`torch.set_num_threads`), but increasing the number of processes through `mp.spawn` exacerbates the slowdown.

**Comment by peterbell10** [comment]
>Just to clarify, I see these issues regardless of the number of threads (torch.set_num_threads), but increasing the number of processes through mp.spawn exacerbates the slowdown.

How are you using `torch.set_num_threads` and how many CPU cores do you have? With all 10 processes operating single threaded on a 24-core CPU, I get `cat`, `index_copy` and `np.concatenate` all taking around 1-4 ms. With your original script I see `cat` on some processes taking only 1-2 ms but also sometimes taking much longer; as high as 50 ms or even 100 ms. I presume you've cherry picked the figures in the original report to emphasize these values.

What I think is happening is that each process creates its own OpenMP thread pool, causing over subscription of hardware threads. NumPy doesn't suffer because it's single threaded, `index_copy` does many smaller copies (one for each index) all of which are less than [`at::internal::GRAIN_SIZE`](https://github.com/pytorch/pytorch/blob/ccea3726da3aca338eb7753e84ba370a13148855/aten/src/ATen/Parallel.h#L14) which means the copies aren't multithreaded.

To confirm this, I can increase the `shape` parameter to `(8, 128, 1000)` where `128*1000` is greater than the grain size, therefore `index_copy` is multithreaded. As expected, I see a huge drop in performance of `index_copy`, in line with the `cat` performance. If I run again with `torch.set_num_threads(2)` it uses at most 20 threads of my 24-core machine and both `cat` and `index_copy` slightly out-perform NumPy. 

My suggestion is to use `torch.set_num_threads(n_threads)` so that `n_threads * n_procs <=` your actual hardware threads and that way you won't run into over-subscription issues.

**Comment by david-macleod** [comment]
Thanks for your reply, this definitely seems to fix my issue! The problem was that I had `torch.set_num_threads(1)` set in the main process but not the (spawned) child processes, not realising this setting wouldn't propagate.

If I want to define single threading in the parent process, and then have it true for all subprocesses, would setting `os.environ["MKL_NUM_THREADS"] = "1" ; os.environ["OMP_NUM_THREADS"]= "1"` be the best approach, or is there something fundamentally different to doing this compared to `torch.set_num_threads`?

**Comment by peterbell10** [comment]
>The problem was that I had torch.set_num_threads(1) set in the main process but not the (spawned) child processes, not realising this setting wouldn't propagate.

That explains it then. Unlike forking, `spawn` won't propagate global state values over to the child process. Either calling `torch.set_num_threads` in the child process or setting the environment variables should work fine. `set_num_threads` also works when pytorch isn't built with OpenMP so should be more portable.

**Comment by vadimkantorov** [comment]
I think all these issues ask for some clear guidance in docs to bring attention to these considerations: thread state inheritance, oversubscription etc
