### ISSUE TITLE
Input missing in the exported ONNX model and dynamic axes not working

### ISSUE THREAD

**Issue by wangzbo** [pytorch/pytorch#44299]
## To Reproduce

I am using the pytorch onnx to export a nl2sql model:

    _input1 = torch.randn(1,24,300)
    _input2 = torch.ones((1,), dtype=torch.int64)*24
    _input3 = torch.randn(6,16,300)
    _input4 = torch.tensor([5,12,6,7,7,16],dtype=torch.int64)
    _input5 = torch.ones((1,), dtype=torch.int64)*6
    _input6 = torch.ones((1,), dtype=torch.int64)*6
    _input = (_input1,_input2,_input3,_input4,_input5,_input6)

    torch.onnx.export(model, _input, "nl2sql.onnx", opset_version=11,
    export_params=True, verbose=True, do_constant_folding=False,
    input_names = ['input1','input2','input3','input4','input5','input6'],
    output_names = ['output1','output2','output3','output4','output5','output6','output7','output8'],
    dynamic_axes={'input1' : {0:'batch_size', 1:'_q_len'}, 'input2' : {0:'batch_size'}, 'input3':{0:'batch_size_col_num', 1:'_col_len'}, 
    'input4':{0:'batch_size_col_num'}, 'input5':{0:'batch_size'}, 'input6':{0:'batch_size'},
    'output1':[0],'output2':[0,1],'output3':[0],'output4':[0],'output5':[0,1],'output6':[0],'output7':[0,3],'output8':[0]})
    
    check_model = onnx.load("nl2sql.onnx")
    onnx.checker.check_model(check_model)

There is no problem when loading the nl2sql.onnx. The problems are:
1) When I view the onnx model graph using Netron, I only found input1, input2 and input5. The other input can not be found in the graph.
2) There is a node reshape_2901 in the graph accept a 6*100 input. But actually here 6 should be dynamic and I specified it in input4{0:'batch_size_col_num'}. When I am doing the testing with input4 with a different dimension, onnxruntime will throw an error: "The input tensor cannot be reshaped to the requested shape. Input shape:{4,100}, requested shape:{1,6,100}"

I upload the exported onnx model here:

[nl2sql.onnx.zip](https://github.com/pytorch/pytorch/files/5186509/nl2sql.onnx.zip)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): mac
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by xin-w8023** [comment]
> ## 🐛 Bug
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> I am using the pytorch onnx to export a nl2sql model:
> 
> ```
> _input1 = torch.randn(1,24,300)
> _input2 = torch.ones((1,), dtype=torch.int64)*24
> _input3 = torch.randn(6,16,300)
> _input4 = torch.tensor([5,12,6,7,7,16],dtype=torch.int64)
> _input5 = torch.ones((1,), dtype=torch.int64)*6
> _input6 = torch.ones((1,), dtype=torch.int64)*6
> _input = (_input1,_input2,_input3,_input4,_input5,_input6)
> 
> torch.onnx.export(model, _input, "nl2sql.onnx", opset_version=11,
> export_params=True, verbose=True, do_constant_folding=False,
> input_names = ['input1','input2','input3','input4','input5','input6'],
> output_names = ['output1','output2','output3','output4','output5','output6','output7','output8'],
> dynamic_axes={'input1' : {0:'batch_size', 1:'_q_len'}, 'input2' : {0:'batch_size'}, 'input3':{0:'batch_size_col_num', 1:'_col_len'}, 
> 'input4':{0:'batch_size_col_num'}, 'input5':{0:'batch_size'}, 'input6':{0:'batch_size'},
> 'output1':[0],'output2':[0,1],'output3':[0],'output4':[0],'output5':[0,1],'output6':[0],'output7':[0,3],'output8':[0]})
> 
> check_model = onnx.load("nl2sql.onnx")
> onnx.checker.check_model(check_model)
> ```
> 
> There is no problem when loading the nl2sql.onnx. The problems are:
> 
> 1. When I view the onnx model graph using Netron, I only found input1, input2 and input5. The other input can not be found in the graph.
> 2. There is a node reshape_2901 in the graph accept a 6*100 input. But actually here 6 should be dynamic and I specified it in input4{0:'batch_size_col_num'}. When I am doing the testing with input4 with a different dimension, onnxruntime will throw an error: "The input tensor cannot be reshaped to the requested shape. Input shape:{4,100}, requested shape:{1,6,100}"
> 
> I upload the exported onnx model here:
> 
> [nl2sql.onnx.zip](https://github.com/pytorch/pytorch/files/5186509/nl2sql.onnx.zip)
> 
> ## Expected behavior
> ## Environment
> Please copy and paste the output from our
> [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
> (or fill out the checklist below manually).
> 
> You can get the script and run it with:
> 
> ```
> wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
> # For security purposes, please check the contents of collect_env.py before running it.
> python collect_env.py
> ```
> 
> * PyTorch Version (e.g., 1.0): 1.6.0
> * OS (e.g., Linux): mac
> * How you installed PyTorch (`conda`, `pip`, source): pip
> * Build command you used (if compiling from source):
> * Python version: 3.7.6
> * CUDA/cuDNN version:
> * GPU models and configuration:
> * Any other relevant information:
> 
> ## Additional context
> cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

I think it caused by onnx graph optimization. As your case, maybe the `input3, input4, input6` have no relation with the final output. You may check this by modifying these three inputs while holding the other three inputs to see whether the final output changes or not

**Comment by AlfredWGA** [comment]
@HenryDashwood I'm working on converting `pegasus` to `onnx` and ran into the exact same issue as yours, the `encoder_hidden_states` input for the decoder disappears  after the conversion.

**Comment by BowenBao** [comment]
@wangzbo @HenryDashwood @AlfredWGA Thank you for reporting and providing detailed repros. A quick look over the example, I agree with @xin-w8023 and my guess is that when exporting BART decoder with `past` provided, the `encoder_hidden_states` is then unused in the graph (passed in to attention layer as `key_value_states`, and neglected due to `past_key_value` being provided) https://github.com/huggingface/transformers/blob/bc6f51e53925e118f04a76f9a59a3d16fc9684a2/src/transformers/models/bart/modeling_bart.py#L176), and thus optimized away. 

The same applies for T5 as well (https://github.com/huggingface/transformers/blob/bc6f51e53925e118f04a76f9a59a3d16fc9684a2/src/transformers/models/t5/modeling_t5.py#L465). However the reason why T5 export keeps `encoder_hidden_states`, is probably due to that the shape of `encoder_hidden_states` is used to construct `encoder_attention_mask`, if the latter is not provided (https://github.com/huggingface/transformers/blob/bc6f51e53925e118f04a76f9a59a3d16fc9684a2/src/transformers/models/t5/modeling_t5.py#L929), whereas for Bart, it is the opposite (https://github.com/huggingface/transformers/blob/bc6f51e53925e118f04a76f9a59a3d16fc9684a2/src/transformers/models/bart/modeling_bart.py#L990).

You can validate the exported onnx model and check how the `encoder_hidden_states` input is used in the graph. 

And FYI current ONNX standard is under work to introduce the concept of optional inputs. This is specifically to support this kind of use case such that input `past` can be deemed as optional. It would allow model to decide whether to use `encoder_hidden_states` or not at runtime based on provided inputs.

**Comment by BowenBao** [comment]
cc @jiafatom for the second issue on shape mismatch.

**Comment by AlfredWGA** [comment]
@BowenBao Thank you very much for the explanation! It makes sense that unused Tensors are optimized. Also I'm wondering when will this new ONNX standard be released? Now I'm facing issues that Decoder for Seq2Seq models cannot be directly exported, due to the fact that ONNX do not accept `None` variable and optional inputs. Once the new feature is on that'll be a great help.

**Comment by jiafatom** [comment]
@wangzbo As discussed above, the missing input is probably due to that it is not used in the model. For dynamic axes not working part, could you please share nl2sql model script or the small repro for that?

**Comment by wangzbo** [comment]
Sorry for the late response, it has been a long time and I am not working on this model now. My understanding is the same as xin-w8023 and BowenBao's opinions. These inputs has been treated as constant inputs and ignored due to the optimization when converting to the ONNX format. The exported onnx model can still be used to inference and you do not have to specify the missing input variables.  For my exported onnx model, the result is that it can only inference for one specific table instead of all different kinds of tables.

During my tests, this missing input issue is related to the parameter **do_constant_folding** in torch.onnx.export for torch versions <=1.6.0. If I set it False, the exported model has all the inputs. If it is true, some inputs will disappear in the onnx model. But for torch version >=1.7.0, the issue occurs no matter whether do_constant_folding is True or False.

For the second issue, it is explainable if we know the input4 has been treated as a constant variable. It has a fixed shape as  _input4 fed into the model when exporting. So the dynamic_axes is not working even specified for input4.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
