### ISSUE TITLE
Convert num_kernels to int64 before calling into CUDA GET_BLOCKS

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#44472]
## 🐛 Bug

Follow up on #43476. 
Scanning CUDA KernelUtils.GET_BLOCKS might be called with overflowed 32bit integers. should convert to int64 to hold num_kernels 

## Additional context

See examples such as:
https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/ATen/native/cuda/vol2col.cuh#L107

https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/THCUNN/generic/SpatialDepthwiseConvolution.cu#L71

https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/THCUNN/generic/SpatialDepthwiseConvolution.cu#L154

https://github.com/pytorch/pytorch/blob/c010ef7f0c6d837809a7e973048afac76373e3de/aten/src/ATen/native/cuda/MaxUnpooling.cu#L431

cc @ngimel

**Comment by dipanshug124** [comment]
@walterddr in the python 3.x the size of int is not defined, it would work as well for 64 bit.  
I'm not getting your issue, can you explain it using an example?

**Comment by kshitij12345** [comment]
@dipanshug124 You can look at https://github.com/pytorch/pytorch/issues/43476#issuecomment-689642123 for more context.

**Comment by Fowley-P** [comment]
Hey, I'm looking at fixing this issue, but as someone who doesn't have a lot of experience with the size of datasets used for this, would a u32 suffice, or does it have to be i64? I'd like to avoid using the full i64 if possible, especially for something like CUDA kernels, which can't have a negative value.

**Comment by Randl** [comment]
I don't think u32 is enough (or will soon be not enough). Not sure whether negative values (say, -1) are used for some purposes, else you could use u64.

**Comment by ngimel** [comment]
i64 in this case won't get passed to cuda kernels, it is used to compute number of blocks without overflow.

**Comment by Fowley-P** [comment]
Yeah I mentioned the negative value aspect of it because it's specifically to compute the number of kernels needed, and you'll never have negative values for the kernels so might as well use uints instead of ints to increase the capacity for almost no cost. And with respect to the extra space, I try to avoid using unnecessary space no matter which part of the code I'm working on. I'll get to work making the changes, but it'll take me a bit to make the changes in all the places I need to. Thanks for your input.

**Comment by walterddr** [comment]
only partially closed via #44688
