### ISSUE TITLE
__call__ signature of nn.Module

### ISSUE THREAD

**Issue by vpj** [pytorch/pytorch#44605]
## 🚀 Feature

https://github.com/lab-ml/labml_helpers/blob/master/labml_helpers/module.py

This is a class I wrote than subclass nn.Module and let modules implement __call__ instead of forward. I did this to get better type checking and type inference in python.

This module uses __init_subclass__ set the __call__ method of it’s subclasses to forward so that it doesn’t mess up with nn.Module hooks and stuff. I’ve been using this for a while and hasn’t encountered problems.

Are there implications that I haven’t seen?

## Motivation

Static type analysis

## Pitch

Be able to do static type analysis on module calls.

## Additional context

Posted on discuss.pytorch.org but didn't get a proper response
https://discuss.pytorch.org/t/call-signature-of-nn-module/80962

cc @albanD @mruberry @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by VitalyFedyunin** [comment]
This likely was already discussed previously, adding as internal discussion topic.

**Comment by albanD** [comment]
Is there something preventing the type from being propagated from the call to the forward function in the vanilla module?

**Comment by ezyang** [comment]
The relevant bg issue is probably https://github.com/pytorch/pytorch/issues/35566

**Comment by ezyang** [comment]
This trick seems like it should work. The usual caveats apply with regards to metaclass style shenanigans: you are likely going to confuse users who expect their method to be called directly, tricks like this don't generally compose well with each other. It's pretty magical and almost sure to break a user of PyTorch, which is why we're probably never going to add something like this in core, but you should feel free to keep doing this.

An alternative way to do this that is more boilerplatey is to redefine the function with correct type and have it `super()` the parent implementation; this avoids user surprise of the init subclass.

**Comment by vpj** [comment]
Thanks!

**Comment by RishiMalhotra920** [comment]
leaving this here, in case this code example helps anyone:

```python
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(10, 10)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return super().forward(x)

    def __call__(self, x: torch.Tensor) -> torch.Tensor:
        return super().__call__(x)
```

i ended up writing some duplicated type hints but to me, this is better than having no type hints and banging your head trying to debug shape issues. ymmv.
