### ISSUE TITLE
polygamma(n, x) fails on Variables x (but works on Tensors)

### ISSUE THREAD

**Issue by fritzo** [pytorch/pytorch#4466]
To reproduce:
```py
>>> x = torch.ones(1)
>>> torch.polygamma(0, x)                   # <-------- Works as intended.
-0.5772
[torch.FloatTensor of size 1]

>>> v = torch.autograd.Variable(x, requires_grad=True)
>>> torch.polygamma(0, v)                   # <-------- Fails.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor 'polygamma' requires a 'torch._C._VariableBase' object but received a 'int'
```
Note that `polygamma(n,0)` works as intended in computing derivatives of `digamma()`:
```py
>>> torch.autograd.grad([torch.digamma(v)], [v])
(Variable containing:
 1.6449
[torch.FloatTensor of size 1]
,)
```

**Comment by fritzo** [comment]
@apaszke we got most of the plumbing right in #4399, but this usage does not yet work.

**Comment by sighingnow** [comment]
When dispatch the module methods to variables, if the `self` argument comes second, the first two arguments need to be swapped.

https://github.com/pytorch/pytorch/blob/35abc4efa2d08ef2e9b7d978089fbd98b8d14187/torch/csrc/Module.cpp#L222-L224

We could use `polygamma` as

```python
>>> x = torch.ones(1)
>>> v = torch.autograd.Variable(x, requires_grad=True)

>>> torch.polygamma(1, x) # works
>>> torch.polygamma(1, v) # doesn't work
>>> torch.polygamma(v, 1) # works
```

We should call `IMPLEMENT_STATELESS` for `polygamma` rather than `IMPLEMENT_STATELESS`. I will open a PR for that.

**Comment by vishwakftw** [comment]
#4527 has fixed this. Closing in view of this.
