### ISSUE TITLE
nn.Module.script

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#45072]
## Motivation

There is a pervasive pattern within the PyTorch community where users have the need to prepare a Module before calling torch.jit.script. An example here might include replacing an instance of an object with an instance of its JIT-able equivalent (e.g. [PyText ScriptVocab](https://github.com/facebookresearch/pytext/blob/master/pytext/torchscript/vocab.py#L12)) for deployment.

## Pitch

Add a method .script to nn.Module, which is called in a fashion similar to nn.Module.eval. 

The method can be overridden by the user to allow a user-defined preparation of the object for scripting. This might, for example, involve replacing or removing member variables that are not JIT-able.

## Alternatives

Concrete user-defined methods such as torchtext’s [to_ivalue](https://github.com/pytorch/text/blob/53e3ae293359bc2a629d27e195e99d1e7f7b85c3/test/data/test_functional.py#L93) or separate wrappers such as [PyText ScriptVocab](https://github.com/facebookresearch/pytext/blob/master/pytext/torchscript/vocab.py#L12)
## Additional context

The method should be out of place so the original module input, which the user may continue to use, is not modified. The method should be called within torch.jit.script (if present) so as not to expand the API surface for the end user.

cc @gmagogsfm @albanD @mruberry

**Comment by cpuhrsch** [comment]
cc @zdevito @gchanan @zhangguanheng66 @suo @jamesr66a @dongreenberg @mthrok @vincentqb

**Comment by gchanan** [comment]
CC @dzhulgakov

**Comment by gchanan** [comment]
we have other "prepare for running in other mode" APIs already, right?  I'm thinking about some of the packing work that @jamesr66a worked on.

**Comment by JiesiZhao077** [comment]
PyText is replacing `ScriptVocab` with TorchText's `Vocab`. However we have to add this `to_ivalue` to our transforms in order to scriptify them because of this issue. It would be great if users like us don't need to add this additional function to all layers to keep our interface clean. Thanks! CC @hudeven

**Comment by dzhulgakov** [comment]
The problem is that the proposed `script` method is destructive (unlike `eval` that can be un-done with `train`), so it's not a very intuitive API to put in core.

How wide-spread do you think it'd be? Because one can always do `m.apply(lambda x: x.script() if hasattr(x,'script') else None)` manually

**Comment by cpuhrsch** [comment]
> The problem is that the proposed `script` method is destructive (unlike `eval` that can be un-done with `train`), so it's not a very intuitive API to put in core.

It's not supposed to be descrutive. torch.jit.script is meant to call .script on its input nn.Module as a first step before further processing. The user defined .script then needs to have been implemented as an out-of-place operation. It won't touch the input given to torch.jit.script outside of its scope.

> How wide-spread do you think it'd be? Because one can always do `m.apply(lambda x: x.script() if hasattr(x,'script') else None)` manually

This applies to the current ```to_ivalue``` method in torchtext as well. It's another step a user needs to take. We can gather more information on how widespread this is if we find that the risk of introducing is too high.

**Comment by cpuhrsch** [comment]
cc @astaff

**Comment by dongreenberg** [comment]
> Because one can always do m.apply(lambda x: x.script() if hasattr(x,'script') else None) manually

This will expand the API surface, adding risk, and force the user to decide for themselves whether they need to run that preparation line every time they script a module. For submodules with preparation logic (e.g. inside of an nn.Sequential) this would mean traversing the module tree. If a library developer wants to implement a custom module for deployment with specific execution considerations (which I think is reasonable, considering the heterogeneity of deployment environments), this is the only way @jamesr66a @suo and @zdevito and us could think of to do that.

**Comment by dzhulgakov** [comment]
> It's not supposed to be descrutive. torch.jit.script is meant to call .script on its input nn.Module as a first step before further processing. The user defined .script then needs to have been implemented as an out-of-place operation. It won't touch the input given to torch.jit.script outside of its scope.

So is the proposal to make sure that `script()` always does shallow copy in its implementation? Because JIT today doesn't do it for the duration of scripting.

> For submodules with preparation logic (e.g. inside of an nn.Sequential) this would mean traversing the module tree. 

Well, `module.apply` actually works recursively for all submodules. But the overall point is taken.

I wonder whether this method should be called with name like `__torchscript__` to signify it's magical and is not supposed to be called by the user directly (kind of similar to pickle's `__reduce__`)
