### ISSUE TITLE
Windows, dataloader, MapViewFile, incorrect parameters

### ISSUE THREAD

**Issue by blacksailer** [pytorch/pytorch#45581]
## 🐛 Bug

Trying to train model with dataloader on Windows Server 2012 R2 and if num_workers > 0 , it fails with next output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\cwx955460\.conda\envs\cwx955460\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\cwx955460\.conda\envs\cwx955460\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\cwx955460\.conda\envs\cwx955460\lib\site-packages\torch\multiprocessing\reductions.py", line 300, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: Couldn't map view of shared file <torch_18696_987327738>, error code: <87>
```

As I found out that 87 error on windows is invalid parameter, I've [edited](https://github.com/pytorch/pytorch/blob/96540e918c4ca3f0a03866b9d281c34c65bd76a4/torch/multiprocessing/reductions.py#L294) to print size variable.
```
size - 478686912
size - 337664960
size - 827519312
size - 312159968
size - -1996924288
...
RuntimeError: Couldn't map view of shared file <torch_18696_987327738>, error code: <87>
``` 

But can't find what generates negative size.

P.S. MNIST Example DataLoader works properly.

## Expected behavior

DataLoader with num_workers works properly

## Environment

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Windows Server 2012 R2
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1 / 7.5.3

cc @SsnL @VitalyFedyunin @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by izdeby** [comment]
@blacksailer, can you, please, provide a repro?

**Comment by blacksailer** [comment]
Hello, I'll try to recreate it. If someone will stumble here, here what we managed to do.

In code there was Dataset class which stores all data in variable (reads all data in __init__() to variable). As we thought spawned process tries to copy all data and with many workers causing error above.

We workaround it with reading from hard disk, not from variable.

**Comment by peterjc123** [comment]
@ezyang Do you have any idea why `size` was defined as `ptrdiff_t` instead of `size_t` [here](https://github.com/pytorch/pytorch/blame/master/aten/src/TH/THAllocator.h#L62)?

**Comment by peterjc123** [comment]
Actually, when I use `(ptrdiff_t)2147483648L` on https://godbolt.org/ using "x64 msvc 19.27", it returns `-2147483648`.

**Comment by peterjc123** [comment]
Let me have a wild guess on the whole story.

First, our user passed in a quite big number as size to `Storage._new_shared_filename` and it didn't overflow. (Otherwise, it will throw an exception on https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/python_numbers.h#L43). And then the overflow happens on https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/StorageSharing.cpp#L129, in which a 64-bit signed integer multiplies an unsigned number, whose result is still a 64 bit signed number.

To workground the problem, we need to fix a few things including:
1. Change the type of `size` from `int64_t` to `uint64_t` or `size_t` in https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/StorageSharing.cpp#L124 
2. Change the type of `size_` from `ptrdiff_t` to `size_t` in https://github.com/pytorch/pytorch/blame/master/aten/src/TH/THAllocator.h#L62

What do you think, @ezyang?

**Comment by peterjc123** [comment]
@blacksailer Wait, are you saying that the negative `size` are captured at the Python side?

**Comment by peterjc123** [comment]
Wow, there are 9 occurrences of `PyLongFromLong` in https://github.com/pytorch/pytorch/blob/v1.6.0/torch/csrc/generic/StorageSharing.cpp and almost 50% are related to `size`. We should fix this.

**Comment by blacksailer** [comment]
Yes, this numbers of shared file size are was seen from python side. In multiprocessing package to be exact.

**Comment by ezyang** [comment]
Eek, PyLongFromLong! We should fix these, definitely. (And probably also add a lint rule to complain about it.)
