### ISSUE TITLE
What would happen if torch.clamp() has min greater than max?

### ISSUE THREAD

**Issue by qysnn** [pytorch/pytorch#45664]
It seems the current implementation will cut the tensor to min or max according to their values, which might be a problem when debugging logical errors or typos. Maybe it would be better to just throw an exception? Also it would be nice to note that in the [documentation](https://pytorch.org/docs/stable/generated/torch.clamp.html).
```
>>> import torch
>>> print(torch.__version__)
1.6.0
>>> a = torch.randn(4)
>>> a
tensor([-1.1582,  0.0216,  0.6430,  0.5723])
>>> torch.clamp(a, min=0.5, max=-0.5)
tensor([ 0.5000,  0.5000, -0.5000, -0.5000])
```

cc @jlin27 @mruberry

**Comment by mrshenli** [comment]
Throwing an exception makes sense to me. @gchanan please correct me if I am wrong.

**Comment by theanshm** [comment]
What should be the expected behaviour here? I would like to give this issue a shot if it is open to work on.

**Comment by mruberry** [comment]
We actually have a PR to update this behavior to be consistent with NumPy, see https://github.com/pytorch/pytorch/pull/43288. Throwing an error message when min > max seems OK when min and max are scalars on the CPU. In the future we may support min and max as device tensors, and we typically don't test the values of device tensors since it would cause a device->cpu synchronization.

**Comment by xamm** [comment]
In PyTorch version 1.8.0, if the specified min value is greater than the max value, the clamp function effectively sets all values to the specified max value.

This is shown in the equation in the clamp documentation [clamp documentation](https://pytorch.org/docs/stable/generated/torch.clamp.html).

The equation from the documentation is:

>  y<sub>i</sub> = min(max(x<sub>i</sub>, min_value), max_value)

If the max_value is greater than the min_value, the first max() function will always return a value greater than the specified max_value, and therefore the min() function will always return the max_value.


Is this an expected behavior or should a warning / error be written when this occurs?

**Comment by mruberry** [comment]
Yep, @xamm, that is the intended behavior. It's consistent with NumPy's clip().

Maybe we should be warning when this occurs... I wonder if anyone has ever been bitten by this? NumPy doesn't warn.

**Comment by xamm** [comment]
The [NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.clip.html) states:
> No check is performed to ensure a_min < a_max.

I would argue that to be consistent with NumPy, such a warning should also be written in the documentation when active user warning is not necessary.

**Comment by mruberry** [comment]
Sure, we would accept a PR updating the documentation for clamp to clarify the behavior when min is greater than or equal to max.
