### ISSUE TITLE
The meaning of deterministic for torch._C._cudnn_batch_norm_forward

### ISSUE THREAD

**Issue by mingminzhen** [pytorch/pytorch#4580]
I try to use **torch._C._cudnn_batch_norm_forward**.
The prototype is as following in source code.
```
at::Tensor cudnn_convolution_full_forward(
    const at::Tensor& input, const at::Tensor& weight, const at::Tensor& bias,
    IntList padding, IntList stride, IntList dilation,
    int64_t groups, bool benchmark, bool deterministic);
```
What's the meaning of the **"bool deterministic"**?

**Comment by ezyang** [comment]
Hi @mingminzhen, 'deterministic' controls cuDNN convolution algorithm selection, so that only deterministic convolution algorithms are selected. This excludes some of the faster algorithms.

BTW, we haven't decided to make this a public API yet, so the signature of this function may change without warning.

**Comment by mingminzhen** [comment]
thanks. It's useful.
