### ISSUE TITLE
[Feature request] PackedSequence with length = 0

### ISSUE THREAD

**Issue by stefanonardo** [pytorch/pytorch#4582]
If you run `pack_padded_sequence(input, lengths)` with one of the lengths <= 0 it raises a `ValueError: length of all samples has to be greater than 0, but found an element in 'lengths' that is <=0`.   
Would it be possible to change it in order to accept even sequences with length zero? The reason is that when you run truncated backpropagation it could happen that some sequences become empty in the last steps and it would be easier to use the same batch size along the whole backpropagation.

**Comment by apaszke** [comment]
I don't think that's a good idea. If you know it can happen in your use case just filter out the empty sequences before you call this function

**Comment by yucoian** [comment]
uha.... I found this problem too. In order to learn the BiRNN char level embedding ,  the char of the pad token obviously is pad again. Thus,  the length of the pad token is zero. That's to say, when we learn the char level embedding of the pad token, the batch_size is zero. So, in this way, it' not very convenient. However I put forward a nice method to solve it. Maybe it helps:

class CharEncoder(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=1, batch_first=True, bidirectional=True):
        super(CharEncoder, self).__init__()
        self.rnn = nn.GRU(input_size=input_size,
                          hidden_size=hidden_size,
                          num_layers=num_layers,
                          batch_first=batch_first,
                          bidirectional=bidirectional)

    def forward(self, x, mask):
        """
        :param x:            [batch*seq_len,  max_word_len, char_emb_size]
        :param mask:         [batch*seq_len, max_word_len]
        :return result:      [batch, output_dim]
        """
        lengths = mask.eq(0).long().sum(1)         # NOTE: 1 for mask.
        lengths_sort, idx_sort = torch.sort(lengths, dim=0, descending=True)
        _, idx_unsort = torch.sort(idx_sort, dim=0)

        x_sort = x.index_select(0, idx_sort)

        # NOTE : in case pad token.
        for i, _ in enumerate(lengths_sort):
            if lengths_sort[i] == 0:
                lengths_sort[i] = 1
        print("lengths_sort:", lengths_sort)
        print("x_sort.shape", x_sort.size())
        x_pack = torch.nn.utils.rnn.pack_padded_sequence(x_sort, lengths_sort, batch_first=True)
        o_pack, hn = self.rnn(x_pack)
        o, _ = torch.nn.utils.rnn.pad_packed_sequence(o_pack, batch_first=True)

        # unsorted o
        o_unsort = o.index_select(0, idx_unsort)  # Note that here first dim is batch
        hn = hn.transpose(0,1).index_select(0, idx_unsort)

        o_unsort = o_unsort.transpose(0, 1)       # Note that here first dim is seq_len，for gather purpose.

        # get the last time state
        for i, _ in enumerate(lengths):  # NOTE : in case pad token.
            if lengths[i] == 0:
                lengths[i] = 1
        len_idx = (lengths - 1).view(-1, 1).expand(-1, o_unsort.size(2)).unsqueeze(0)
        # bidirectional bugs
        len_idx_reversed = torch.zeros_like(len_idx)
        o_last = torch.cat([o_unsort.gather(0, len_idx)[:, :, :int(o_unsort.size(2) / 2)],
                            o_unsort.gather(0, len_idx_reversed)[:, :, int(-o_unsort.size(2) / 2):]], -1)
        o_last = o_last.squeeze(0)

        print(o_unsort.transpose(0, 1))             #[batch, seq_len, output_dim]
        #print(o_last)
        print("hn.shape:", hn.shape)
        print("hn",hn)
        print("self.rnn(x)", self.rnn(x))
        return o_last

**Comment by yucoian** [comment]
@stefanonardo

**Comment by turangojayev** [comment]
Hi @yucoian , I also want to use char embeddings with LSTM now and stumbled upon this post and was trying to understand your code, however having difficulty with understanding it completely. I am a newbie to pytorch and have some questions:
1. `:return result:      [batch, output_dim]` - is the return shape [batch, output_dim] or [batch * seq_len, output_dim]?
2. `o_last = torch.cat([o_unsort.gather(0, len_idx)[:, :, :int(o_unsort.size(2) / 2)],
                        o_unsort.gather(0, len_idx_reversed)[:, :, int(-o_unsort.size(2) / 2):]], -1)`
Why do you gather it this way? Doesn't pytorch take care of bidirectional rnns itself and you have to gather as if it were only one direction from the output?

**Comment by praateekmahajan** [comment]
A workaround might be, 
- to keep the track of sequence that has length 0
- pack_padded_sequence with `length.clamp(min=1)`
- in the output of the rnn, mask the index of the output that had length 0.

```python
class Model(nn.Module):
    def __init__(self, in_features, embedding_dim, dropout_prob=0, max_length=30):
        super(Model, self).__init__()
        
        self.hidden_dim = embedding_dim
        self.max_length  = max_length
        
        self.num_layers = 3
        self.rnn = nn.GRU(input_size=in_features, hidden_size=embedding_dim,
                          num_layers=self.num_layers, batch_first=True, bidirectional=True, dropout=dropout_prob)

    def forward(self, x, seq_lengths):
        # Clamp everything to minimum length of 1, but keep the original variable to mask the output later
        seq_lengths_clamped = seq_lengths.clamp(min=1, max=self.max_length)
        x_packed = torch.nn.utils.rnn.pack_padded_sequence(x, seq_lengths_clamped, 
                                                           enforce_sorted=False, batch_first=True)  
        out_packed, hidden = self.rnn(x_packed)
        # hidden is of the shape num_layers * num_directions, batch, hidden_size
        hidden = hidden.view(self.num_layers, 2, -1, self.hidden_dim)        

        # SOME TRANSFORMATIONS HERE
        # get the last element i.e from the last layer, rearrange shape to be batch, num_directions, hidden_size
        hidden = hidden[-1].permute(1, 0, 2)
        # since it's bidirectional, we combine both outputs from last layer
        hidden = hidden.reshape(-1, 2 * self.hidden_dim)

       # MASKING HERE
        # mask everything that had seq_length as 0 in input as 0
        hidden.masked_fill_((seq_lengths == 0).view(-1, 1), 0)
        return hidden
```

**Comment by carlosgmartin** [comment]
@apaszke I see no reason to not handle the 0 case. There's a very good reason why 0 shows up as a natural base case in *many* situations. For example, it is convenient to have tensors with dimensions of size 0. Why? Because we've found that it simplifies our programming logic. Thus PyTorch handles arithmetic with dimensions of size 0.

Likewise, treating natural numbers (including 0) uniformly simplifies our programming logic. Forcing users to build their own scaffolding around the method call just to handle the 0 case separately is inefficient and error-prone.

**Comment by Animiral** [comment]
Oof! This is indeed inconvenient.

Ever heard of the sort routine that throws on 0 inputs? And the database table that must always have at least one row, because nobody in their right mind would use an empty table? We wouldn't want to silently accept a state that might indicate a problem in some use cases.

But in fact, the empty list is a list. The empty table is a table. And an empty sequence is still a sequence. Please reconsider this feature request so that future users do not have to build special-case logic for empty sequences.
