### ISSUE TITLE
Singular value decomposition of complex valued matrices does not match mathematical definition

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#45821]
## 📚 Documentation

Now when `torch.svd` supports complex input both for CPU and CUDA. Let's discuss the docs.
Currently, SVD documentation is fully in agreement with the implementation. This function returns`(U, S, V)` such that `input = U @ diag(S) @ V.T`
However, the mathematical definition of SVD is the decomposition of a matrix **M** such that ![image](https://user-images.githubusercontent.com/19621411/95017939-e72e4e80-0664-11eb-8efe-a853724d142a.png), where `V^*` is the conjugate transpose of `V`. 

What is the opinion on this? Should the documentation and implementation match math and be updated such that `A = U @ diag(S) @ V.T.conj()`?

[Link to `torch.svd` documentation](https://pytorch.org/docs/stable/generated/torch.svd.html).

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @anjali411 @dylanbespalko @mruberry @jlin27 @vishwakftw @jianyuh @nikitaved @pearu @vincentqb

**Comment by pearu** [comment]
xref: https://github.com/pytorch/pytorch/issues/45063 - conjugate transpose operator feature request

**Comment by pearu** [comment]
IIUC, the current SVD documentation uses transpose because previously only real input was supported (and hence using conjugate transpose would have been unnecessary). With the new complex input support in SVD, I would suggest updating the SVD documentation to use conjugate transpose to match the mathematical definition of general SVD. While doing so, also mention that when M is real then V will be real and conjugate transpose falls back to transpose.

**Comment by ezyang** [comment]
Yes, please just generalize the docs, in this case it seems to be straightforward and the right thing to do.

**Comment by nikitaved** [comment]
The current SVD implementation returns `V` that is silently conjugated. I guess it makes sense to fix that too.

**Comment by mruberry** [comment]
> The current SVD implementation returns `V` that is silently conjugated. I guess it makes sense to fix that too, is that correct?

As far as I understand what you're saying: yes.

**Comment by antocuni** [comment]
I'd like to add my 2 cents to this discussion. By looking at the source code, it seems to me that the current behavior or `torch.svd` was not designed, but simply a byproduct of a bug. In particular, look at `_create_U_S_VT`:

https://github.com/pytorch/pytorch/blob/a814231616f5db7fcdb8793f64c12d652d1e8572/aten/src/ATen/native/LinearAlgebraUtils.h#L221

As the name suggests, it should create a `VT` tensor, which is done here:
https://github.com/pytorch/pytorch/blob/a814231616f5db7fcdb8793f64c12d652d1e8572/aten/src/ATen/native/LinearAlgebraUtils.h#L246

However, the comment is wrong: the lapack's function `_gesdd` returns a `VT` in *column-major* order.

The rest of the code keeps calling it `VT`; e.g., this is `_svd_helper_cpu` returning a tuple `(U, S, VT)`:
https://github.com/pytorch/pytorch/blob/a814231616f5db7fcdb8793f64c12d652d1e8572/aten/src/ATen/native/BatchLinearAlgebra.cpp#L1058

However, since we are creating the tensor with the wrong strides, we are effectively returning `VT.transpose()`, which is `V`. To summarize:
* `numpy.linalg.svd` returns `VT`
* lapack retusn `VT`
* our implementation returns something which is called `VT` (but it's not)

So, it looks to me that the intention was to return `VT` as well, but because of the bug in `_create_U_S_VT`, we started to return `V` and instead of fixing the bug we simply "fixed" the documentation.

There isn't much that we can to at this point without breaking compatibility, but this confusing/unexpected/nonstandard behavior of `svd` might indicate that we should deprecate it in favor or `torch.linalg.svd`, once it lands.

Note: in my WIP PR #45562 I fixed `_create_U_S_VT` by creating `VT` with the correct strides, and `transpose_()`ing it upon return to keep b/c.
In the same PR I am also going to fix the docs for `torch.svd`.

**Comment by mruberry** [comment]
Sounds great, @antocuni! I agree we should consider deprecating torch.svd once torch.linalg.svd lands. It will also be confusing to have a method torch.Tensor.svd when both functions are in because users may not know which svd it refers to.

**Comment by antocuni** [comment]
> It will also be confusing to have a method torch.Tensor.svd when both functions are in because users may not know which svd it refers to.

This is something which I didn't think about. What should `Tensor.svd` do if/when we remove `torch.svd`? Ideally it would do the same as `torch.linalg.svd`, but this will break compatibility.

> In the same PR I am also going to fix the docs for torch.svd.

FWIW, this is the commit which aims to fix the documentation:
https://github.com/pytorch/pytorch/pull/45562/commits/97662da54aba366dd547e46d557edc2b86ff86dc

**Comment by mruberry** [comment]
> > It will also be confusing to have a method torch.Tensor.svd when both functions are in because users may not know which svd it refers to.
> 
> This is something which I didn't think about. What should `Tensor.svd` do if/when we remove `torch.svd`? Ideally it would do the same as `torch.linalg.svd`, but this will break compatibility.

We should warn/deprecate for a release and then remove both functions for a release. Then we can consider adding torch.Tensor.svd back and mapping it to torch.linalg.svd.

**Comment by antocuni** [comment]
>> The current SVD implementation returns V that is silently conjugated. I guess it makes sense to fix that too, is that correct?

> As far as I understand what you're saying: yes.

**Comment by antocuni** [comment]
(sorry guys, I closed the issue by mistake, reopening it)

**Comment by pulkin** [comment]
You probably do know that `numpy` returns `u, s, vh = svd(A)` such that `A = u @ s @ vh`. I would prefer to have this convention in `pytorch` because many people use `numpy` for prototyping.

**Comment by antocuni** [comment]
while working on PR #45562 we realized that we can't fix `torch.svd` without breaking existing code. OTOH, the upcoming `torch.linalg.svd` is completely compatible with numpy.
As discussed on the PR, the current plan is to document the current behavior of `torch.svd` and tell people to use `torch.linalg.svd` for new code: this is the commit which tentatively tries to improve the docs, but feel free to suggest a better wording:
https://github.com/pytorch/pytorch/pull/45562/commits/abf9baffc200ac6a459e78c70ce5e5c05594608e
