### ISSUE TITLE
Don't use DoubleTensor as default global type in common.py

### ISSUE THREAD

**Issue by prigoyal** [pytorch/pytorch#4588]
I have been bitten hard many times (again today) by the usage of global DoubleTensor in common.py

This is really hard to track and the consequences are severe: memory usage blows up and speed becomes horrible too. We should not use default tensor type as DoubleTensor in any module. If some test requires doubleTensor, then explicity use DoubleTensor in that particular test rather than global setting. 

cc @mruberry @VitalyFedyunin

**Comment by ezyang** [comment]
It's not obvious to me that we should default to FloatTensor either. My preferred resolution is to disable use of torch.Tensor and force all tests to explicitly say what they want.

**Comment by prigoyal** [comment]
agreed @ezyang, that sounds better!

**Comment by apaszke** [comment]
The default is like this, because a lot (most?) of our tests involve comparing to approximations/computing finite differences and that requires higher precision than float. Also, it doesn't really hurt perf/mem usage, because most tests should be very small and double math is as fast as float math on the CPU. For CUDA, we're using `torch.cuda.FloatTensor` in most places IIRC

**Comment by dlmacedo** [comment]
When I am creating my models on GRU, they are using DoubleTensor by default instead of tensor.cuda.Float.

Is this the expected behavior?

How could I change this to the default cuda be Float instead of DoubleFloat?

**Comment by ezyang** [comment]
It's 2020, and we still default to double tensor (lol)

**Comment by mruberry** [comment]
I actually fixed this.

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/27444
