### ISSUE TITLE
 RuntimeError: Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.

### ISSUE THREAD

**Issue by Darshcg** [pytorch/pytorch#46237]
I was converting our custom Pytorch model to Trt and run it on a Jetson.
While converting pt to ONNX I am getting an error like:
RuntimeError: Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.

Code for the Conversion:
```

from models import *
from datasets import letterbox #*
from utils import *
import numpy as np
import sys, random
import torch
import torchvision
from torchvision import models, transforms
from PIL import Image
import io
import torch.nn as nn
from torch.autograd import Variable
import cv2
import os
import logging

img_size=(416, 416)
cfg = 'yolov3-spp.cfg'
imgsz = img_size

import torch
import torch.onnx


model_pt_path = "last.pt"
model_def_path = "models.py"

model = Darknet(cfg, imgsz)
model.load_state_dict(torch.load(model_pt_path),strict=False)

dummy_input = torch.randn(1,3,416,416)

torch.onnx.export(model, dummy_input, "SL-PMH.onnx")
```

May I know how this can be resolved?
Torch version: 1.6

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @ezyang

**Comment by spandantiwari** [comment]
Can you please set `opset_version=11` or `opset_version=12` in your export API call.

**Comment by spandantiwari** [comment]
@Darshcg - let us know if this works for you.

**Comment by Darshcg** [comment]
Hi @spandantiwari,
Thank you a lot for your kind response.
I really appreciate your time.

 Actually, I am further converting the ONNX model to TRT Model, but with opset_version=11, the Scatter op is being generated, but Scatter op is not Supported for tensorrt.

Can you please guide for an Alternative Conversion from the PyTorch model to ONNX other than torch.onnx.export?
And what is the reason for the error with Opset_version=9 and 10?

Thanks

**Comment by whatyouknow123** [comment]
I have meet the same problem when I try to trans pytorch model to onnx. I also try to set the opset_version=11, but it dose't works. Because when I try to use onnxruntime.InferenceSession to predict, it inform me that onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : invalid indice found, indice = -1

Do you fix your problem? If you have fix it, please let me know you solution

**Comment by spandantiwari** [comment]
@Darshcg  - ONNX adds more ops every new opset version in order to improve coverage. That's why some ops are not supported in older opsets, but supported in newer ones. The exporter tries to detect these situations and give out a useful error message, as it does here. If there's any particular node that is not supported in the backend you are using, my suggestion would be to use the ONNX Python APIs to modify the ONNX graph (once it is exported) as per your need.
Please reopen this if you see any specific issue.

**Comment by wwdok** [comment]
what if there is no 'torch.onnx.export()' ? see https://github.com/waleedka/hiddenlayer/issues/95

**Comment by whatyouknow123** [comment]
您好，邮件我已经收到了，会尽快回复的，祝安
