### ISSUE TITLE
libtorch_cpu.a is huge (1 GB) with build_android.sh

### ISSUE THREAD

**Issue by SoulSharer** [pytorch/pytorch#46246]
## 🐛 Bug

I've seen [similar issue #34058](https://github.com/pytorch/pytorch/issues/34058). However unlike in that issue libtorch_cpu.a is 5 times larger. With CUDA and a lot of other modules already turned off by default in the build_android.sh script.
What causes it to bloat to a such degree? 1GB is way too much, especially for mobile platforms. 
![image](https://user-images.githubusercontent.com/7026184/95865691-9f4bad80-0d6f-11eb-9cff-822680d0d6d7.png)

Since it's a static library one would think that not all of the archive will be linked into final executable however without `-Wl,--whole-archive` directives pytorch is missing ops while running TorchScript.

Did anyone encounter such an issue, is there any possible solution or any plans to tackle this problem?
Thanks for the help.

## To Reproduce

1. Download v.1.6.0 branch
2. Setup development environment
3. Run scripts/build_android.sh

## Expected behavior

* Be able to identify which modules cause bloat to turn them off.
* Be able to link static library without `-Wl,--whole-archive` directive

## Environment
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Debian GNU/Linux 10 (buster)
 - GCC version: (Debian 8.3.0-6) 8.3.0
 - CMake: version 3.13.4
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): script/build_android.sh
 - Python version: 3.7.3

cc @ezyang @seemethere @malfet @walterddr

**Comment by ezyang** [comment]
You need selective build. @dhruvbird @ljk53

**Comment by dhruvbird** [comment]
@linbinyu @iseeyuan Any idea why @bdhirsh is unable to build w/o link-whole?

My very naïve guess regarding why you need to `--whole-archive` is because there are some global object whose constructors are used to register ops, and those object are not referenced anywhere. If the compiler decides to leave them out, then their constructors won't be called, and the operator registration won't happen (which is why you are seeing missing ops).

@bdhirsh You need to use selective/custom build as @ezyang  mentioned. Documented here: https://pytorch.org/mobile/android/

Please could you use custom build with just the set of ops you need (from your pytorch model), and see how it impacts the binary size?

That said, I'm surprised that the size is 1G!

**Comment by dhruvbird** [comment]
@bdhirsh Did you try disabling MKL?

**Comment by malfet** [comment]
`.a` files are much bigger than actual executables, because they contain multiple repeated instantiations of the standard templates (i.e. every .o file withing static library that uses say std::vector<int> would likely contain an implementation of `std::vector<int>:operator[]()`) 
Please try linking it to the hello world executable, and something tells me even with the wholearchive option total size should be less than 200Mb (which is still a lot, but much less than original 1Gb)

**Comment by SoulSharer** [comment]
Using selective ops build won't allow us to update TorchScript model on the fly, we would have to recompile application to include new ops that might be used. However it might be a good compromise for now. Thanks for pointing that out.

@malfet While it is true that final binary is less than 1Gb even with `-Wl,--whole-archive,` however it is still huge. It's around 500 MB instead of 250 MB like you guessed. Here is the final binary, look at libCapsule.so raw size.
![image](https://user-images.githubusercontent.com/7026184/95958332-ad4e0c80-0e09-11eb-9ffe-c390c21dc169.png)

I tried to gather as much info on symbols inside libCapsule.so to prove my point, so here's the most useful dump I believe.
I ran `nm -gDCS --size-sort libCapsule.so` on it.
[nm.txt](https://github.com/pytorch/pytorch/files/5376449/nm.txt)

I will try to compile libCapsule without PyTorch to prove my point even further soon enough.

**Comment by ljk53** [comment]
This is because the Android NDK cmake toolchain file always add "-g" flag to generate debug info regardless of CMAKE_BUILD_TYPE - it's expected that later build step will strip before releasing.

pytorch's master cmake file has logic to add "-s" compiler flag for Android build to neglect the "-g" flag. However, it only works for GCC compiler. Newer Android NDK has moved to clang so this 'hack' no longer works.

#46331 fixed it for clang by adding '-g0' flag, which can neglect the '-g' flag. I verified the output "torch_cpu.a" size has been reduced to ~120M.

As others have pointed out, the static library is just an archive of object files, which doesn't accurately reflect the size cost to your app.

When building the pytorch object files, we added "-fdata-sections -ffunction-sections", i.e. function and data symbols are emitted to separate sections. When linking the objects with your binary, you should make sure you have "-Wl,--gc-sections" linker flag. This way it will make sure symbols that are not used by your app are stripped at link time. You should check the dynamic library / binary size after linking, the single architecture uncompressed size should be around ~26M ~ 40M - depending on the target architecture (armv7, arm64, x86, x86-64, etc).

"--whole-archive" asks linker to consider every object file regardless of whether any symbols in it are referenced by any other object files. It can work together with "--gc-sections" flag - one works at object files level, the other works at sections level. As @dhruvbird explained, "--whole-archive" flag is used to keep some "global registers", which are not referenced by any other symbols. If they are skipped then pytorch operators won't be registered correctly and you will get missing operator error at run time.

> Using selective ops build won't allow us to update TorchScript model on the fly, we would have to recompile application to include new ops that might be used.

There are probably a lot operators your models won't use in foreseeable future. You probably can try a conservative list. Also note that old pytorch library might not be "forward compatible" with the models created from newer pytorch. For example, the app linked with pytorch 1.7 library might not be able to run pytorch 1.8 model. You might need "recompile application" for newer models in certain cases anyway.

**Comment by SoulSharer** [comment]
Thanks for the fix! '-g0' flag solved the problem. It reduced overall size by ~460 MB which is perfect.
Had no clue about NDK generating debug symbols for release builds behind the scenes, now it makes sense why the resulting binary was huge.

We do use both "--whole-archive" and "--gc-sections" at the same time. And we will consider limiting ops we use for our modules to trim down size even more.
Thanks for the quick and thorough response!
