### ISSUE TITLE
`tensor.mode()` takes extraordinarily long for sizes larger than `65536`

### ISSUE THREAD

**Issue by msieb1** [pytorch/pytorch#46507]
## 🐛 Bug

See title. The operation below takes around 20 seconds. On cpu(), or with batch size smaller than 65336, it's less than a second.

## To Reproduce

```
a = torch.randint(0, 2, size=(65537, 50)).cuda()
a.mode(-1)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.3
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6

## Additional context

cc @ngimel @VitalyFedyunin @heitorschueroff

**Comment by VitalyFedyunin** [comment]
Hello! How do you time it? Are you sure that you are not counting coda context initialization time?

**Comment by msieb1** [comment]
Yes, I accounted for that. Feel free to try
```
b = torch.randint(0, 2, size=(65532, 50)).cuda()
b.mode(-1) --> fast, even with context initialization time
a = torch.randint(0, 2, size=(65537, 50)).cuda()
a.mode(-1) --> super slow
```

```

**Comment by ngimel** [comment]
Yeah, that's because for number of slices > 65K it's offloaded to naive implementation which launches O(65K) kernels https://github.com/pytorch/pytorch/blob/e6ed8879089c92edb6dd698980c4d7b353ee95e6/aten/src/THC/generic/THCTensorMode.cu#L210-L280. That can be fixed, easy workaround is to split your tensor into 65K slices and loop over them.

**Comment by ngimel** [comment]
Reopening, as the issue is not fixed
