### ISSUE TITLE
torch.inverse based on cuSOLVER does not raise error for singular input

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#46557]
## 🐛 Bug

The cuSOLVER path in `torch.inverse` seems not to raise an error for non-invertible input.

## To Reproduce

Single matrix and 2xNxN batched input inversion is based on cuSOLVER
```python
import torch
batch_dim = 2
A = torch.eye(3, 3, dtype=dtype, device=device)
A = A.reshape((1, 3, 3))
A = A.repeat(batch_dim, 1, 1)
A[0, -1, -1] = 0  # Now A[0] is singular
Ainv = torch.inverse(A) # Doesn't raise errors Ainv[0] contains NaNs
```
General batched input case is based on MAGMA
```python
import torch
batch_dim = 3
A = torch.eye(3, 3, dtype=dtype, device=device)
A = A.reshape((1, 3, 3))
A = A.repeat(batch_dim, 1, 1)
A[0, -1, -1] = 0  # Now A[0] is singular
Ainv = torch.inverse(A) # Raises RuntimeError because input is singular
```

## Expected behavior

`torch.inverse` should raise an error for singular input when input is single matrix or a batch of matrices with batch size less or equal than 2 (cuSOLVER's code path).

cc: @xwang233 

cc @ngimel @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff

**Comment by ngimel** [comment]
@IvanYashchuk is it because `info` is not checked for cuSolver (that would be an easy fix then), or because cuSolver just returns bogus results?

**Comment by IvanYashchuk** [comment]
Taking a quick look at the code, `info` is being checked [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cu#L120).
cuSOLVER correctly returns `info = 3` for this input (checked via CuPy).

**Comment by xwang233** [comment]
https://github.com/pytorch/pytorch/blob/d75c402755af27c44c9f909dcc65e7ba35dffd91/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cu#L28-L35

I found the problem. In your example, `getrf` returns `info = 3`, but it was later overwritten by `getrs` with `info = 0`. So we definitely need to check `info` returned by the first call as well. 

I was thinking if we can do this asynchronously to avoid performance drop due to the device -> host memory copy.

**Comment by ngimel** [comment]
You can use 2-element infos to save both.
