### ISSUE TITLE
when trace a program, it run three times?

### ISSUE THREAD

**Issue by HeYingnan** [pytorch/pytorch#46650]
when i use traced_script_module = torch.jit.trace(self.am_model, example_inputs) to trace a model, and i write a print in forward fuctions, i found the print show 3 times, is it right?

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi HeYingnan,

I think this is because of `check_trace`, which verifies generated trace function matches original behavior. So the 3 prints are from:

1) Tracing the python function
2) Running the traced python function once as part of `check_trace`
3) Running the original python function once as baseline for `check_trace"

If you add `check_trace=False` to `torch.jit.trace` call, the function would only be called once.

```
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x):
        print("I am printing")
        return self.conv(x)

n = Net()
example_forward_input = torch.rand(1, 1, 3, 3)

module = torch.jit.trace(n.forward, example_forward_input, check_trace=False)
```

**Comment by HeYingnan** [comment]
> Hi HeYingnan,
> 
> I think this is because of `check_trace`, which verifies generated trace function matches original behavior. So the 3 prints are from:
> 
> 1. Tracing the python function
> 2. Running the traced python function once as part of `check_trace`
> 3. Running the original python function once as baseline for `check_trace"
> 
> If you add `check_trace=False` to `torch.jit.trace` call, the function would only be called once.
> 
> ```
> import torch
> import torch.nn as nn
> 
> class Net(nn.Module):
>     def __init__(self):
>         super(Net, self).__init__()
>         self.conv = nn.Conv2d(1, 1, 3)
> 
>     def forward(self, x):
>         print("I am printing")
>         return self.conv(x)
> 
> n = Net()
> example_forward_input = torch.rand(1, 1, 3, 3)
> 
> module = torch.jit.trace(n.forward, example_forward_input, check_trace=False)
> ```

Thank you very much.
