### ISSUE TITLE
torch.multinomial behave unexpectedly on float16 GPU input tensor

### ISSUE THREAD

**Issue by ycli90** [pytorch/pytorch#46702]
## 🐛 Bug
torch.multinomial behave unexpectedly on float16 GPU input tensor when num_samples=1 and replacement=True
1. fails on probability distribution with odd items
2. produce unrepeatable result for large input tensor

## To Reproduce

For problem 1, simply run
`print(torch.multinomial(torch.rand(2, 3, dtype=torch.float16, device="cuda"), num_samples=1, replacement=True))`

It throws error:
RuntimeError: CUDA error: misaligned address

For problem 2, generate large distributions multiple times using the same seed, the result is not totally match
```
import torch
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
seed = 5
rows = 10000
cols = 1000
trails = 10
num_samples = 1
for i in range(trails):
    torch.manual_seed(seed)
    probs = torch.rand(rows, cols, dtype=torch.float16, device="cuda")
    fake_token1 = torch.multinomial(probs, num_samples=num_samples, replacement=True)
    torch.manual_seed(seed)
    probs = torch.rand(rows, cols, dtype=torch.float16, device="cuda")
    fake_token2 = torch.multinomial(probs, num_samples=num_samples, replacement=True)
    diff_ratio = (fake_token1 != fake_token2).sum().item() / probs.shape[0] / num_samples
    print('trail {} inconsistency ratio = {}'.format(i, diff_ratio))
    if diff_ratio > 0:
        print(torch.nonzero(fake_token1 != fake_token2, as_tuple=False))
        print(fake_token1[fake_token1 != fake_token2])
        print(fake_token2[fake_token1 != fake_token2])
```

## Expected behavior
The function should not throw error, and produce deterministic result using the same seed.

## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Alibaba Group Enterprise Linux Server 7.2 (Paladin) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB

Nvidia driver version: 440.33.01
cuDNN version: /home/common/cuda_toolkit/cuda10.0/lib64/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi

## Additional context
If num_samples>1, both problem disappear.
For smaller input (e.g. rows = 100, cols = 100), the result is reproducible. 

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @ngimel @pbelevich

**Comment by jingqiao** [comment]
It is a crucial issue that the above torch.multinomial issue leads to (hidden) irreproducibility of experiments even with the same seed in situations which are supposed to be deterministic. 

For now, a valid and simple workaround is to simply set num_samples=2 and use one of its output. Look forward to someone identifying the root cause and providing a solution/fix soon.

**Comment by ezyang** [comment]
cc @vishwakftw who enabled float16 on multinomial in #29266. Also cc @kshitij12345 who most recently worked on the algos here and may have some insights.

**Comment by ngimel** [comment]
It looks like sampleMultinomialOnce kernel is busted. 
So we have 2 options here:
1) look over it and fix what's broken. The kernel is not the easiest one to look at, and fixing weird errors where cumsum of positive numbers is not guaranteed to be monotonic is very painful (for sample-more-than-once there's a special kernel fixing that weirdness I believe)
2) use sample without replacement algorithm for 1 sample. Currently it's slow for smaller sizes but it can be made faster by 
   - using argmax instead of topk for one sample
  - writing some easy tensorIterator kernels to fuse multiple ops. Currently it launches O(10) kernels, maybe ~20, we should be able to bring it down to ~5?
Quick perf numbers - for large sizes (10000x1000) after switching to argmax I see without-replacement approach being faster (700 us vs 1.2 ms)
For small sizes without-replacement is 200+ us (because of large number of kernels) compared to ~20 us of current buggy kernel.
