### ISSUE TITLE
torch.jit.unused

### ISSUE THREAD

**Issue by omeryasar** [pytorch/pytorch#46759]
Hi,
I have an pytorch model which I want to be able to make inference in c++. So to do that I try to obtain torchscript model. But as you know torchscript do not allow all some datatypes, some code flows(try except blocks) etc. But I have some dependencies like numpy and other libraries that torch.jit.script do not likes. So when I use @torch.jit.unused annotation is this have a meaning that I can't use this in c++ yet ? If It is, what should I do to be able to use my model in c++. Thanks in advance.

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
If you have part of code that's not TorchScript-friendly and not actually used in the model, you can annotate those method calls with `@torch.jit.unused` so that TorchScript won't error out during compilation and exporting. 

More info can be found here:
https://pytorch.org/docs/stable/generated/torch.jit.unused.html

Closing for now, feel free to reopen if you have additional questions.
