### ISSUE TITLE
torch.fft does not give the same result as torch.stft

### ISSUE THREAD

**Issue by KinWaiCheuk** [pytorch/pytorch#47104]
## 🐛 Bug
I would expect that `torch.stft` is built on `torch.fft` and will slices the audio frames with `n_fft` sample each.
However, when I run slice my audio frames and run `torch.fft`, the result is different from `torch.stft` and other libraries such as `librosa.stft` and `scripy.fft.fft`

## To Reproduce
I have a colab code this demonstrate how `torch.fft` is different from others
https://colab.research.google.com/drive/1F7DS4TyBy6Im5Q_HS0bm2SarXQ7T1KKY?usp=sharing

![image](https://user-images.githubusercontent.com/37035802/97671383-177dd700-1ac3-11eb-9263-2096bf117de5.png)

## Expected behavior

I would expect `torch.fft` would be same as `torch.stft`

## Environment

 - PyTorch Version: 1.6.0
 - OS: Linux
 - How you installed PyTorch: `pip`
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.1

cc @mruberry @peterbell10

**Comment by peterbell10** [comment]
The difference is because torch.fft's second argument isn't the transform axis, instead it's `signal_ndim` or the number of dimensions to transform. So, `torch.fft(x_torch, 3)` is actually equivalent to `scipy.fft.fftn(x_scipy, axes=(-1, -2, -3))`. For a more `numpy`-like interface use the new [`torch.fft.fft`](https://pytorch.org/docs/master/fft.html#torch.fft.fft) function, or if you're stuck with PyTorch 1.6 you can use `transpose(axis, -2)` to move the desired transform axis into the right place:

```
S_torch = torch.fft(x_torch.transpose(1, -2), signal_ndim=1).transpose(1, -2)
```
Which results in:
![image](https://user-images.githubusercontent.com/13238737/97711956-abe13d00-1ab5-11eb-9910-7fa99580663f.png)
