### ISSUE TITLE
Legacy tensor ctor returns uninitialized tensor when input and output device differ

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#47112]
## 🐛 Bug

Follow-up from https://github.com/pytorch/pytorch/issues/33899#issuecomment-718374923:
Using the legacy tensor constructor with a `CUDATensor` as the input and specifying `device='cpu'` returns an uninitialized tensor.
Note that other combinations seem to work properly and yield a proper error message.

## To Reproduce

```python
a = torch.tensor(1, device='cuda')
b = torch.Tensor(a, device='cpu')
print(b)
> tensor([8.9683e-44])
print(a)
> tensor(1, device='cuda:0')
```

Reproduced on the latest nightly binary `1.8.0.dev20201029` + CUDA11.0.

Based on the behavior of the similar calls:
```python
a = torch.tensor(1, device='cpu')
b = torch.Tensor(a, device='cuda')
> RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu
```
I think the problematic code should also raise an error and not accept `a` as a `CUDATensor`.

Based on some initial debugging it seems that [`legacy_tensor_ctor`](https://github.com/pytorch/pytorch/blob/6c34aa720c43d2959a1154a076c5ffdc0da07fb6/torch/csrc/utils/tensor_new.cpp#L471-L526) and [`new_with_size`](https://github.com/pytorch/pytorch/blob/6c34aa720c43d2959a1154a076c5ffdc0da07fb6/torch/csrc/utils/tensor_new.cpp#L519) are called.

## Environment
```
PyTorch version: 1.8.0.dev20201029
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.86
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: TITAN V

Nvidia driver version: 455.23.05
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.8.0.dev20201029
[pip3] torchvision==0.9.0.dev20201029
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.2           py37h54aff64_0
[conda] numpy-base                1.19.2           py37hfa32c7d_0
[conda] numpydoc                  1.1.0                      py_0
[conda] pytorch                   1.8.0.dev20201029 py3.7_cuda11.0.221_cudnn8.0.3_0    pytorch-nightly
[conda] torchvision               0.9.0.dev20201029      py37_cu110    pytorch-nightly
```

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff

**Comment by ChuanchuanZheng** [comment]
@ptrblck Reply here. My PyTorch version is 1.3.0. The segmentation fault problem was solved by upgrading torch version to 1.6.0. Thanks for your kindly reply.

**Comment by gchanan** [comment]
reproduced and verified it's not a regression from 1.6.

**Comment by mruberry** [comment]
Thanks for reporting this issue, @ptrblck. We would definitely accept a PR fixing this. Stepping back, it'd be nice if we revisited the tests and implementation of these legacy tensor creation ops, and even reviewed deprecating them. @gchanan suggested we should consider rewriting the legacy ops to call the non-legacy constructors, for example, with a deprecation message.

**Comment by kshitij12345** [comment]
@ptrblck Thanks for pointing to the files.

`legacy_tensor_ctor` is called from this point below. 
Interestingly, for `dispatch_key` argument it passes `torch::tensors::get_default_dispatch_key()` irrespective of the passed Tensor from Python land.
https://github.com/pytorch/pytorch/blob/2c3c2a4b7afac5240d39177e7208ba15bbc62f24/torch/csrc/autograd/python_variable.cpp#L148

In addition to above error, it also results in this incorrect error
```python
a = torch.tensor(1, device='cuda')
b = torch.Tensor(a, device='cuda')
> RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
```

**Comment by ysiraichi** [comment]
I am interested in taking care of this issue. Below, there are the program I used to replicate the bug, and some tables representing the obtained results (```1.9.0a0+613bf6c```).

But first, given the following table, here's how to interpret the results:

| LHS => RHS | COL_A | COL_B |
|------------|-------|-------|
| ROW_A      |       |       |
| ROW_B      |       |       |

```python
a = torch.<ROW_Y>(1, device = <LHS>)
b = torch.<COL_X>(a, device = <RHS>)
```

<details>
<summary>Program for reproducing the bug.</summary>

```python
import torch
import traceback

devices = ['cpu', 'cuda']
ctors = [ torch.tensor, torch.Tensor ]

for src_dev in devices:
    for dst_dev in devices:
        for src_ctor in ctors:
            for dst_ctor in ctors:
                try:
                    a = src_ctor(1, device = src_dev)
                    b = dst_ctor(a, device = dst_dev)
                    if a == b: print("OK")
                except:
                    traceback.print_exc()
```
</details>

<details>
<summary>Actual result tables.</summary>

| CPU => CPU | Tensor                    | tensor              |
|------------|---------------------------|---------------------|
| **Tensor** | Error (data not sequence) | OK                  |
| **tensor** | Not Equal                 | Warning (use clone) |

| CPU => CUDA | Tensor              | tensor                       |
|-------------|---------------------|------------------------------|
| **Tensor**  | Error (expects cpu) | Error (expected same device) |
| **tensor**  | Error (expects cpu) | Error (expected same device) |

| CUDA => CPU | Tensor                       | tensor              |
|-------------|------------------------------|---------------------|
| **Tensor**  | Error (expects cpu)          | Error (expects cpu) |
| **tensor**  | Error (expected same device) | OK                  |

| CUDA => CUDA | Tensor              | tensor              |
|--------------|---------------------|---------------------|
| **Tensor**   | Error (expects cpu) | Error (expects cpu) |
| **tensor**   | Error (expects cpu) | OK                  |

| Short                        | Long                                                                                                                                                                                                      |
|------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Error (data not sequence)    | ```TypeError: new(): data must be a sequence (got Tensor)```                                                                                                                                              |
| Warning (use clone)          | ```UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).``` |
| Error (expects cpu)          | ```RuntimeError: legacy constructor expects device type: cpubut device type: cuda was passed```                                                                                                           |
| Error (expected same device) | ```RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!```                                                                                        |
</details>

Given that, I propose we change to the following:

| CPU => CPU | Tensor                            | tensor               |
|------------|-----------------------------------|----------------------|
| **Tensor** | Warning (deprecated)              | Warning (deprecated) |
| **tensor** | Warning (copying from deprecated) | OK                   |

| CPU => CUDA | Tensor                            | tensor                      |
|-------------|-----------------------------------|-----------------------------|
| **Tensor**  | Warning (deprecated)              | Warning (deprecated)        |
| **tensor**  | Warning (copying from deprecated) | Warning (different devices) |

| CUDA => CPU | Tensor                            | tensor                      |
|-------------|-----------------------------------|-----------------------------|
| **Tensor**  | Warning (deprecated)              | Warning (deprecated)        |
| **tensor**  | Warning (copying from deprecated) | Warning (different devices) |

| CUDA => CUDA | Tensor                            | tensor               |
|--------------|-----------------------------------|----------------------|
| **Tensor**   | Warning (deprecated)              | Warning (deprecated) |
| **tensor**   | Warning (copying from deprecated) | OK                   |

I understand that these might be breaking changes, so maybe not the best approach. There are two points in my proposal:

1. We could show one deprecation warning, plus another warning (e.g. copying from different devices);
2. For different devices, we could return a valid tensor from the specified device `device = ??`, but issue an warning that they live in different devices.

What do you think?

**Comment by mruberry** [comment]
I'm not sure how to read your tables, @ysiraichi. If you want to do tables like that then couldn't you do one table for torch.Tensor( ) and another for torch.tensor() with the rows and columns being CPU and CUDA?

**Comment by rgommers** [comment]
This is confusing because there are two separate issues here.

### Issue 1 - legacy constructor returns uninitialized memory with 0-D as well as size-1 inputs

A one-liner is enough to demonstrate, no need for mismatching devices:
```
>>> torch.Tensor(1, device='cpu')                                           
tensor([732257.])
>>> torch.Tensor([1], device='cpu')  # this is fine                                         
tensor([1.])
>>> torch.Tensor(torch.tensor(1), device='cpu')   # 0-D tensor              
tensor([2.1177e+28])
>>> torch.Tensor(torch.tensor([1]), device='cpu')   # 1-D tensor            
tensor([2.1177e+28])
>>> torch.Tensor(torch.tensor([1, 2]), device='cpu')   # 1-D tensor, size > 1 - this is fine too, if a little inconsistent with a size-1 tensor                                                            
Traceback (most recent call last):
  File "<ipython-input-30-b2ee4397fcf9>", line 1, in <module>
    torch.Tensor(torch.tensor([1, 2]), device='cpu')   # 1-D tensor, size > 1
TypeError: new(): data must be a sequence (got Tensor)
```

### Issue 2 - inconsistent behavior in legacy constructor when `input.device != device`

This line:
```
b = torch.Tensor(a, device=device)
```
gives different results that seem to be influenced by:
- `a.shape`: test `[]`, `[1]`, `[2]`
- `a.dtype`: `float32` and `int32` seem different

This requires the tables with CPU/CUDA for both rows and columns. And then repeat those tables for the different shapes and dtypes as needed.

Important: each issue is a one-liner. Mixing the two constructors in both `a = ...` and `b = ...` just confuses the problems.

**Comment by ysiraichi** [comment]
@rgommers Thanks for the clarifications.

Since `torch.Tensor(..., device = 'cuda')` is not supposed to work, I will omit those (they correctly raise an error).

# Summary
- As pointed out, **Issue 1** appears to be the root of uninitialized tensors (I will start working on this one).
- There are some behavior inconsistencies caused by **Issue 2**.
- There are some behavior inconsistencies when omitting the `device = 'cpu'` for the legacy constructor.
- We always get `float32` as dtype independent of input dtype (is that intended behavior?).

# Actual Behavior
For each row in the tables below, only one line is executed (shown right before each table) for each row (`input` varies). The **behavior** column is either an `error` (code formatting) or a unexpected behavior description.

## `torch.Tensor(input, device = 'cpu')`

| input                      | input dtype | output dtype | behavior                         |
|:--------------------------:|:-----------:|:------------:|:---------------------------------|
| `1`                        | `int32`     | `float32`    | uninitialized                    |
| `1.0`                      | `float32`   | --           | `new(): data must be a sequence` |
| `[1]`                      | `int32`     | `float32`    | different dtype                  |
| `[1.0]`                    | `float32`   | `float32`    | OK                               |
| `[1, 2]`                   | `int32`     | `float32`    | different dtype                  |
| `[1.0, 2.0]`               | `float32`   | `float32`    | OK                               |
| `torch.tensor(1)`          | `int32`     | `float32`    | uninitialized                    |
| `torch.tensor(1.0)`        | `float32`   | --           | `new(): data must be a sequence` |
| `torch.tensor([1])`        | `int32`     | `float32`    | uninitialized                    |
| `torch.tensor([1.0])`      | `float32`   | --           | `new(): data must be a sequence` |
| `torch.tensor([1, 2])`     | `int32`     | --           | `new(): data must be a sequence` |
| `torch.tensor([1.0, 2.0])` | `float32`   | --           | `new(): data must be a sequence` |

- Input device does not change behavior
- While we get an uninitialized tensor for `1`, we get an error for `1.0` 
- When the input is a 0-D or 1-size tensor, behavior depends on the dtype:
  - `int32`: uninitialized tensor
  - `float32`: `TypeError: new(): data must be a sequence`
- When the input is a tensor with more than one element (independent of dtype), we get `new(): data must be a sequence`.

## `torch.Tensor(input) # device is omitted`

| input                      | input dtype | output dtype | behavior                                      |
|:--------------------------:|:-----------:|:------------:|:----------------------------------------------|
| `1`                        | `int32`     | `float32`    | uninitialized                                 |
| `1.0`                      | `float32`   | --           | `new(): data must be a sequence`              |
| `[1]`                      | `int32`     | `float32`    | different dtype                               |
| `[1.0]`                    | `float32`   | `float32`    | OK                                            |
| `[1, 2]`                   | `int32`     | `float32`    | different dtype                               |
| `[1.0, 2.0]`               | `float32`   | `float32`    | OK                                            |
| `torch.tensor(1)`          | `int32`     | --           | `expected Float`                              |
| `torch.tensor(1.0)`        | `float32`   | --           | `slice() cannot be applied to a 0-dim tensor` |
| `torch.tensor([1])`        | `int32`     | --           | `expected Float`                              |
| `torch.tensor([1.0])`      | `float32`   | `float32`    | OK                                            |
| `torch.tensor([1, 2])`     | `int32`     | --           | `expected Float`                              |
| `torch.tensor([1.0, 2.0])` | `float32`   | `float32`    | OK                                            |

- Behavior or error message changes **if the input is a tensor**
- When the input device is CUDA, the constructor raises another error: `expected CPU`
- When the input is a tensor, we no longer get an uninitialized tensor, but an error (as expected)

# Questions

- Should `torch.Tensor` work only with `float32`, raising an `expected Float` whenever `int32` is given?
- Should `torch.Tensor` work with scalars?
- Should `torch.Tensor` behave differently when given tensor as input (comparing with non-tensor python types)?
- Should `torch.Tensor` behave differently when omitting `device = 'cpu'`?
- How should `torch.Tensor` behave when given a tensor that lives on CUDA?
- Up to what point do we want to change `torch.Tensor`?

**Comment by ysiraichi** [comment]
After reading a bit of investigation, here's what I have found:

1. `torch.Tensor(1)`: is expected to return an uninitialized tensor of size `1` (the behavior is exactly that of `torch.empty`)
2. `torch.Tensor(torch.tensor(...))`: correctly interpreted as `new(Tensor tensor)`
3. `torch.Tensor(torch.tensor(...), device = 'cpu')`: incorrectly (?) interpreted as `new(PyObject* data, *, Device? device=None)`
4. The legacy constructor seems to work only with `float` dtypes

I think the only thing worth changing is to add a `Device? device` parameter, i.e. fix (3). The rest is, as far as I understand, the intended behavior.

https://github.com/pytorch/pytorch/blob/b9e12a0e8290af1c05107cf7e9a6117355e5ac1a/torch/csrc/utils/tensor_new.cpp#L500

Any thoughts?

**Comment by mruberry** [comment]
Thank you @ptrblck, @rgommers, and @ysiraichi for taking a look at this issue and helping identify the behavior.

I had some time to look at this and I now think we should not change the behavior. While I initially said we would accept a PR fixing this, I think I was mistaken. It seems like torch.Tensor()'s behavior is simply too much of a mess to productively much with. Instead, I want to propose we leave it's odd behavior as-is but investigate deprecating the operation.

**Comment by rgommers** [comment]
> but investigate deprecating the operation

Do you have a preference for going about that @mruberry? Investigating through code search of code out in the wild will undoubtedly turn up quite a bit of usage, but that won't tell us anything new.

Would it make sense to add a deprecation warning to the whole constructor, and possibly revert it before the next release, to assess the impact and see who complains?

**Comment by mruberry** [comment]
> Would it make sense to add a deprecation warning to the whole constructor, and possibly revert it before the next release, to assess the impact and see who complains?

We might get complaints, although I don't know if we have to revert the deprecation notice.

Pursuing the deprecation could look like:

- verifying all torch.Tensor() scenarios are covered by other functions (torch.tensor(), torch.empty()...)
- scrubbing internal torch.Tensor() uses, if any
- updating the docs and throwing TORCH_WARN_ONCE if someone uses torch.Tensor()

I don't think we even need to warn people that we're removing torch.Tensor(), necessarily. I think a lot of people accidentally use it (mistyping torch.tensor()) or don't know we recommend not using it. A warning might help them out.

What are your thoughts on that approach, @rgommers?

**Comment by rgommers** [comment]
That sounds good to me. I would start with

> scrubbing internal torch.Tensor() uses, if any

because that's a concrete and useful task. And doing that will give an important data point for:

> verifying all torch.Tensor() scenarios are covered by other functions

which is quite fuzzy to do otherwise.

**Comment by ezyang** [comment]
Funnily enough, I *just* filed an issue on this: https://github.com/pytorch/pytorch/issues/53146

**Comment by ysiraichi** [comment]
In total, there are 6 different `torch.Tensor()` scenarios listed in the source code. 4 of which I found uses in the PyTorch codebase.

https://github.com/pytorch/pytorch/blob/98baad57642115d1f66723f6f10585ed933fd731/torch/csrc/utils/tensor_new.cpp#L460-L467

I found a replacement for some of them:

| | In PyTorch | Legacy | Replacement |
| :--: | :--: | -- | -- |
| 1 | :heavy_check_mark: | `new(*, Device? device=None)` | `torch.tensor([])` |
| 2 | :x: | `new(Storage storage)` | ?? |
| 3 | :x: | `new(*, int64_t cdata)` | ?? |
| 4 | :heavy_check_mark: | `new(Tensor other)` | `torch.tensor(other)`  |
| 5 | :heavy_check_mark: | `new(IntArrayRef size, *, Device? device=None)` | `torch.empty(...)` |
| 6 | :heavy_check_mark: | `new(PyObject* data, *, Device? device=None)` | `torch.tensor(...)` |

## Observations:

- Apparently, the replacement in (4) doesn't do exactly the same thing. While the legacy constructor creates an alias to `other`, the replacement clones it.
- I don't think I've seen (2) and (3) at all.

## Questions

- In my understanding, the idea is to point the user towards the replacements (via `TORCH_WARN_ONCE`, right?
- Should we have (are there)  replacements for (2) and (3)?
- Is there a better replacement for (4)?

**Comment by rgommers** [comment]
> In my understanding, the idea is to point the user towards the replacements (via `TORCH_WARN_ONCE`, right?

Yes that sounds right.
 
> Should we have (are there)  replacements for (2) and (3)?

I think that will just over-complicate the warning message. I think you just need to point out two cases: for tensors and other tensor-like input like lists and numpy arrays, use `torch.tensor`. For integer input, use `empty`.

> Is there a better replacement for (4)?

See the current warning message for the recommended method:
```
>>> t = torch.tensor([1, 2, 3.])
>>> torch.tensor(t)
... UserWarning: To copy construct from a tensor, it is recommended to use
sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True),
rather than torch.tensor(sourceTensor).
```

**Comment by fmassa** [comment]
Can we provide the [equivalent of `numpy.frombuffer`](https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html)? This is currently a use-case that I think might be missing in PyTorch

With the deprecation of case 2, with `new(Storage storage)`, I believe there is currently no efficient way of avoiding a memory copy for creating a Tensor from a bytes object

This is currently [used in torchvision](https://github.com/pytorch/vision/blob/eee424922e998dddcaabe927e823ec515aa2927b/torchvision/transforms/functional.py#L135) to avoid a memory copy

```python
img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
```

**Comment by ezyang** [comment]
@fmassa this sounds very reasonable to me

**Comment by ysiraichi** [comment]
Is it something like the [`set_`](https://pytorch.org/docs/stable/tensors.html?highlight=tensor#torch.Tensor.set_) method? I believe it's possible to use it like:

```python
> img = torch.tensor([], dtype=torch.uint8)
> img.set_(torch.ByteStorage.from_buffer(pic.tobytes()))
```

That said, there is no `torch.set` like function. Should we add it? Or would it be better to implement something like `set_`, but accepting array-like objects (not only `Storage` or `Tensor`)?

**Comment by mruberry** [comment]
> Is it something like the [`set_`](https://pytorch.org/docs/stable/tensors.html?highlight=tensor#torch.Tensor.set_) method? I believe it's possible to use it like:
> 
> ```python
> > img = torch.tensor([], dtype=torch.uint8)
> > img.set_(torch.ByteStorage.from_buffer(pic.tobytes()))
> ```
> 
> That said, there is no `torch.set` like function. Should we add it? Or would it be better to implement something like `set_`, but accepting array-like objects (not only `Storage` or `Tensor`)?

I don't think we want to promote set or set-like functions as they can be tricky to use correctly, but a frombuffer() function that's compatible with NumPy's https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html?highlight=frombuffer#numpy.frombuffer would be interesting.

**Comment by gchanan** [comment]
> When the input is a 0-D or 1-size tensor, behavior depends on the dtype: int32: uninitialized tensor

what is happening here is that the constructor is interpreting the Tensor as an IntArrayRef because a 1-element integer tensor passed PyLong_Check.

**Comment by rgommers** [comment]
There's a `frombuffer` mention and a number of related issues linked in https://github.com/pytorch/pytorch/issues/38349#issuecomment-670444956 (the numpy compat tracking issue). That's hard find though. It's not quite clear from the above or from https://github.com/pytorch/vision/issues/3666 if this is a priority for the next release. @mruberry?

**Comment by mruberry** [comment]
> There's a `frombuffer` mention and a number of related issues linked in [#38349 (comment)](https://github.com/pytorch/pytorch/issues/38349#issuecomment-670444956) (the numpy compat tracking issue). That's hard find though. It's not quite clear from the above or from [pytorch/vision#3666](https://github.com/pytorch/vision/issues/3666) if this is a priority for the next release. @mruberry?

Sorry I noticed this just now, @rgommers.

@fmassa can speak to torchvision priorities but definitely not a PyTorch 1.9 release priority.

**Comment by rgommers** [comment]
No worries, just wanted to make sure it didn't fall through the cracks. @ysiraichi is working on it in gh-58549.

> but definitely not a PyTorch 1.9 release priority.

**Comment by mruberry** [comment]
> No worries, just wanted to make sure it didn't fall through the cracks. @ysiraichi is working on it in [gh-58549](https://github.com/pytorch/pytorch/issues/58549).
> 
> > but definitely not a PyTorch 1.9 release priority.
> 
> Yeah, that ship had sailed in my mind already - I meant 1.10

Yep, it would be nice to have for 1.10.
