### ISSUE TITLE
Make Python Storage untyped

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#47442]
In C++, storages no longer store dtype. However, for BC reasons, we preserved the typedness of Python side storages in #33950. We now should make Python-side storages completely untyped. This is BC-breaking, because the user visible API changes; however, we did a similar change when we got rid of IntTensor/FloatTensor which was well received, so it should be doable here too.

This would help @chengjunlu at Intel, because they need to make a device-specific Python storage wrapper otherwise.

This would also subsume #6836.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @bhosmer @smessmer @ljk53 @ailzhang

**Comment by gchanan** [comment]
should we do the "fake type" thing we do with Tensors, e.g.:

```
>>> type(torch.randn(2,3))
<class 'torch.Tensor'>
>>> isinstance(torch.randn(2,3), torch.FloatTensor)
True
```

**Comment by ezyang** [comment]
Yeah, seems reasonable enough

**Comment by ezyang** [comment]
This is also affecting meta tensors now

**Comment by kurtamohler** [comment]
I can start working on this

**Comment by kurtamohler** [comment]
@gchanan, let me make sure I understand your question about fake typing. Were you suggesting that we have this behavior for `torch.Storage`?

```python
>>> s = torch.randn(10).storage()
>>> isinstance(s, torch.FloatStorage)
True
>>> isinstance(s, torch.DoubleStorage)
False
>>> type(s)
<class 'torch.Storage'>   # Note that currently, this gives <class 'torch.FloatStorage'>
```

I'm also wondering about how `torch.Storage.__str__()` should act. Should it just print the bytes in the storage? For instance, right now we have:

```python
>>> torch.randn(10).storage()
...
<10 lines float values>
...
[torch.FloatStorage of size 10]
```

Would we want it to behave like the following instead?

```python
>>> torch.randn(10).storage()
...
<40 lines of byte values>
...
[torch.Storage of size 40]
```

Or should we use the "fake type" in `torch.Storage.__str__()` so that its output is unchanged? (Just FYI, I haven't yet looked into how the fake typing works for `torch.Tensor`, so I'm not sure whether or not this makes sense)

**Comment by ezyang** [comment]
storages internally know what their dtype is (like tensors), so you can preserve the printing.

**Comment by ezyang** [comment]
Yeah we can't actually do the fake typing thing, because storages actually don't know what their type is. We'll have to print byte values.

**Comment by kurtamohler** [comment]
Cool, that makes sense, thanks

**Comment by kurtamohler** [comment]
I wanted to give an update. On my branch, I've removed the dtype member from `torch.Storage`. I've removed all the different `FloatStorage`, `LongStorage`, etc, types except for `ByteStorage`. At this point, almost everything works correctly using just `ByteStorage` (I plan on renaming it to just `Storage` once I've fixed the remaining issues). The only things I know of which don't work yet are serialization and copying.

I'm looking into how to fix serialization. The problem is that when a tensor is saved, the storage's type (like `FloatStorage`, `LongStorage`, etc) is saved as a string, and it's the only thing (as far as I can tell) in the saved data that reflects the tensor's dtype. So when the tensor is loaded, the storage is loaded first, and then the tensor's dtype is determined by the storage's type. Since I only have `ByteStorage`s now, every loaded tensor is interpreted with the byte dtype. A fairly simple fix would be to just add the tensor's dtype to the serialized data, and use that to determine what dtype a loaded tensor should be. However, I don't think that's acceptable--changing what information gets stored would break backward compatibility.

It would probably be best to keep the serialized data in the format that it's in now. So when we save a tensor, we can convert `tensor.dtype` to the corresponding `<type>Storage` string and save that. Then when we load, convert the string back into the tensor dtype and use that when the tensor is created. The serialization code is a bit tricky for me, so it will take me some time to figure out how to get this working.

@ezyang, does this plan make sense? We do want backward compatibility with serialization, right?

**Comment by ezyang** [comment]
Serialization BC is subtle. Clearly, we want it to be possible to load serialized tensors from older versions of PyTorch (backwards compatibility). What is more ambiguous is whether or not it should be possible to load serialized tensors from new versions of PyTorch to older versions (forwards compatibility). We don't really give a guarantee for forwards compatibility https://discuss.pytorch.org/t/torchscript-compatibility-between-pytorch-versions/87655 https://discuss.pytorch.org/t/attempted-to-read-a-pytorch-file-with-version-4-but-the-maximum-supported-version-for-reading-is-3-your-pytorch-installation-may-be-too-old/85412/12 and some tensor structures (namely, tensors with differing dtype that are backed by the same storage) cannot be serialized without changing the serialization format, so we're going to have to break FC eventually.

That being said, Tensor serialization affects EVERYBODY, and it will probably be better for your sanity to do a version that is 100% FC compatible, and then cut us over to a non-FC compatible scheme later. So yeah, you will need to monolithically do the storage serialization at the same time you're doing tensor serialization, so you can record the correct Storage string. Note that you need to make sure you deduplicate storages (assuming their dtypes are the same), which will probably be the most complicated part of the patch. Holler if you need some pointers on the code (I guess I'll do a podcast about serialization at some point.)

cc @dzhulgakov @houseroad @albanD @mruberry

**Comment by ezyang** [comment]
BTW the last time we broke Tensor FC was 2018: #5225

**Comment by ezyang** [comment]
Also you will need to update torch/csrc/jit/serialization/unpickler.cpp and torch/csrc/jit/serialization/pickler.cpp

**Comment by kurtamohler** [comment]
FYI, I was thinking about how to support FC for unpickling tensors of different dtypes that share the same data, and I found out that it's not actually working at the moment, so that's maybe one less case to have to think about. I filed an issue for this here: #58970

**Comment by kurtamohler** [comment]
Hey @ezyang, I've been thinking about how to maintain BC/FC for serialization. I think I came up with a scheme that would work, let me know what you think.

I'm going to focus on strided tensors for now for simplicity. As far as I understand, we should be able to apply the same idea to the other tensor types that directly own a storage.

The first thing to note is that we currently serialize tensors like this, [within `Tensor.__reduce_ex__`](https://github.com/pytorch/pytorch/blob/a5660056791fbd6c9c9cf6bc7d42197fc0dfcb66/torch/_tensor.py#L172):
```python
            args = (self.storage(),
                    self.storage_offset(),
                    tuple(self.size()),
                    self.stride(),
                    self.requires_grad,
                    backward_hooks)
            return (torch._utils._rebuild_tensor_v2, args)
```

After this is returned, the pickler serializes all the objects in `args` and then saves them to the file, along with the function name string `torch._utils._rebuild_tensor_v2`. When unpickling, all the args are unpickled first and then `torch._utils._rebuild_tensor_v2` is called with the args to recreate the tensor. The only arg that contains information about the dtype of the tensor is `self.storage()`. So after we remove the dtype from storage, `_rebuild_tensor_v2` no longer knows what dtype to use.

To maintain BC and FC, we can't just add a new argument for the dtype, and we can't just create a new function `_rebuild_tensor_v3`. We would have to keep using `_rebuild_tensor_v2`, and we would have to give it the same number of arguments. Also, each of the arguments has to have the same serialization format that it currently has. But as long as all those things stay the same, we should be able to change the Python representation of one of these arguments.

My proposal is to change the storage argument to be something like this:
```python
            args = (PickleStorage(self.storage(), self.dtype()),
                    self.storage_offset(),
                    tuple(self.size()),
                    self.stride(),
                    self.requires_grad,
                    backward_hooks)
            return (torch._utils._rebuild_tensor_v2, args)
```

`PickleStorage` would be a specialized typed storage object used only for pickling. It would simply contain the `torch.Storage` and the dtype. We would update [`_rebuild_tensor_v2`](https://github.com/pytorch/pytorch/blob/a5660056791fbd6c9c9cf6bc7d42197fc0dfcb66/torch/_utils.py#L136) to pull out the `torch.Storage` and dtype from the `PickleStorage`, and create the tensor from those. (Note: also `_rebuild_tensor` (v1) would be updated to do the same thing)

When a `PickleStorage` is pickled, we would make it have the same serialized format that `<type>Storage`s currently have. This would require some changes to [`persistent_id`](https://github.com/pytorch/pytorch/blob/a5660056791fbd6c9c9cf6bc7d42197fc0dfcb66/torch/serialization.py#L461).

When a storage is loaded up, we would pull out the type from the `"<type>Storage"` string and wrap the storage with `PickleStorage`. This would require some changes to [`persistent_load`](https://github.com/pytorch/pytorch/blob/a5660056791fbd6c9c9cf6bc7d42197fc0dfcb66/torch/serialization.py#L848). Probably [`find_class`](https://github.com/pytorch/pytorch/blob/a5660056791fbd6c9c9cf6bc7d42197fc0dfcb66/torch/serialization.py#L873) would need an update as well, to translate `<type>Storage` to a `PickleStorage`, and I might need to make a bunch of `Pickle<type>Storage` child classes to get that to work.

Since the serialized format would be exactly the same, it should be BC and FC.

However, there is one problem with this that I haven't figured out yet. If someone saves a standalone storage, like `torch.save(a.storage(), <file>)`, from an old PyTorch version (with typed storages), and loads it back up in a new version (with untyped storages), we'll need to detect that the storage is standalone and avoid wrapping it with a `PickleStorage`. I'm not sure yet how to detect that.

(It is worth noting that if we're unpickling a standalone `<type>Storage`, we will no longer be able to return a `<type>Storage`. It will be the untyped storage. So this is a BC-breaking case, but that's to be expected obviously.)

Does this idea make sense? Or is there a simpler way to solve this problem?

**Comment by ezyang** [comment]
Maybe name it TypedStorage rather than PickleStorage. Having it load in this way doesn't seem like the worst thing in the world; it's easy to get the underlying storage and then use it as you used it before; plus, you might actually need the dtype.

**Comment by kurtamohler** [comment]
I implemented the above idea for strided tensors and it seems to work alright so far. I can save and load tensors of different types on both cpu and cuda, between pytorch's built with my branch and the main branch.

There's a small problem though. When saving the `<type>Storage` class type to file, our pickling format requires this to be stored as an actual class type under the `torch` module (not a string, as I had assumed would be possible). I had removed all the `torch.<type>Storage` classes except for `torch.ByteStorage`, so I tried to fake the class type with something like this:

```python
>>> type('<type>Storage', (object,), {'__module__': 'torch'})
<class 'torch.<type>Storage'>
```

But pickle complained that these types weren't importable from `torch` ([comment about that here](https://github.com/kurtamohler/pytorch/commit/16ff559248da4c3565d6f6c24345cb2fdd8ebf8d#diff-caa1f0155fc8a88f080bf4ded22b19fc6fb0308f02930aca5cd473687eee6adbR472)). As a workaround, I added all the `torch.<type>Storage`s back in, but I made them unable to be instantiated ([see note](https://github.com/kurtamohler/pytorch/commit/16ff559248da4c3565d6f6c24345cb2fdd8ebf8d#diff-c8835eba8562819a44e70a30545213c96e68c588a2cfa673fa495b187b1ea8dfR528)).

I think keeping `torch.<type>Storage`s around is confusing, and I would like to be able to get rid of them if possible.

Interestingly, `Unpickler` has a mechanism to deal with this kind of situation and maintain BC when loading a file ([find_class](https://docs.python.org/3/library/pickle.html#pickle.Unpickler.find_class)), which we are making use of [here](https://github.com/kurtamohler/pytorch/commit/16ff559248da4c3565d6f6c24345cb2fdd8ebf8d#diff-caa1f0155fc8a88f080bf4ded22b19fc6fb0308f02930aca5cd473687eee6adbR912). But there doesn't appear to be anything analogous to that for `Pickler` to maintain FC for saving a file.

What are your thoughts, @ezyang?

**Comment by ezyang** [comment]
https://stackoverflow.com/questions/10898268/cant-pickle-type-function-attribute-lookup-builtin-function-failed seems to suggest that working around this problem in cPickle is literally impossible. (It might also be possible to workaround the problem by manually emitting pickle bytecode but I didn't see any API surface area that does that). So I think you're not going to have a choice: we'll have to keep around the typed storages until we kill FC entirely.
