### ISSUE TITLE
Cannot build PyTorch with Python 3.9 on Windows

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#47460]
## 🐛 Bug

I'm trying to add Python 3.9 builds for all PyTorch packages and am currently hitting a roadblock with Python 3.9 on Windows:

```
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\w\b\windows\conda\envs\py39\include -IC:\w\b\windows\conda\envs\py39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /d1trimfile:C:\w\b\windows\internal\\.. /Tctorch/csrc/stub.c /Fobuild\temp.win-amd64-3.9\Release\torch/csrc/stub.obj /MD /EHsc /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275
  stub.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\w\b\windows\pytorch\torch\lib /LIBPATH:C:\w\b\windows\conda\envs\py39\libs /LIBPATH:C:\w\b\windows\conda\envs\py39\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 /LIBPATH:C:\w\b\windows\mkl\lib torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-3.9\Release\torch/csrc/stub.obj /OUT:build\lib.win-amd64-3.9\torch\_C.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\torch/csrc\_C.cp39-win_amd64.lib /NODEFAULTLIB:LIBCMT.LIB
  LINK : fatal error LNK1181: cannot open input file '.obj'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\link.exe' failed with exit code 1181
  Building wheel for torch (setup.py): finished with status 'error'
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  Running command 'C:\w\b\windows\conda\envs\py39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\w\\b\\windows\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\w\\b\\windows\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  Building wheel torch-1.8.0.dev20201105+cpu
  running clean
  'build\lib.win-amd64-3.9' does not exist -- can't clean it
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.9' does not exist -- can't clean it
Failed to build torch
ERROR: Failed to build one or more wheels
Exception information:
Traceback (most recent call last):
  File "C:\w\b\windows\conda\envs\py39\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "C:\w\b\windows\conda\envs\py39\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "C:\w\b\windows\conda\envs\py39\lib\site-packages\pip\_internal\commands\wheel.py", line 184, in run
    raise CommandError(
pip._internal.exceptions.CommandError: Failed to build one or more wheels
Removed build tracker: 'C:\\Users\\circleci\\AppData\\Local\\Temp\\pip-req-tracker-yhteizny'
```

Full logs: https://app.circleci.com/pipelines/github/pytorch/pytorch/234093/workflows/ad02606d-b28f-40a5-8b6c-27161b0e4849/jobs/8731723

Related PRs:
* https://github.com/pytorch/pytorch/pull/47235
* https://github.com/pytorch/pytorch/pull/47238
* https://github.com/pytorch/builder/pull/565

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by ezyang** [comment]
Looks like forwardslash/backslash confusion

**Comment by mszhanyi** [comment]
It might have something with ninja.
I can build it successfully with visual studio 2019 generator (set CMAKE_GENERATOR=Visual Studio 16 2019).

From your log,
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\w\b\windows\pytorch\torch\lib /LIBPATH:C:\w\b\windows\conda\envs\py39\libs /LIBPATH:C:\w\b\windows\conda\envs\py39\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 /LIBPATH:C:\w\b\windows\mkl\lib torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-3.9\Release\torch/csrc/stub.obj /OUT:build\lib.win-amd64-3.9\torch\_C.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\torch/csrc\_C.cp39-win_amd64.lib /NODEFAULTLIB:LIBCMT.LIB
  LINK : fatal error LNK1181: cannot open input file '.obj'
```
The link path like `/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64 ` should be quoted since there's white space in the path.  I need take more time to investigate why it isn't quoted for building with python 3.9 and ninja

From any pytorch_windows_vs2019_py36_cpu_build log, [for example](https://app.circleci.com/pipelines/github/pytorch/pytorch/236559/workflows/5ea3b717-d058-4c99-8554-a7ac3b3f4c6b/jobs/8779914), we could find such paths are quoted.
`**"/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64"**`

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\circleci\project\torch\lib /LIBPATH:C:\Jenkins\Miniconda3\libs /LIBPATH:C:\Jenkins\Miniconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" /LIBPATH:C:\Users\circleci\project\build\win_tmp\mkl\lib /LIBPATH:LIB torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-3.6\Release\torch/csrc/stub.obj /OUT:build\lib.win-amd64-3.6\torch\_C.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\torch/csrc\_C.cp36-win_amd64.lib /NODEFAULTLIB:LIBCMT.LIB 
   Creating library build\temp.win-amd64-3.6\Release\torch/csrc\_C.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\torch/csrc\_C.cp36-win_amd64.exp

**Comment by peterjc123** [comment]
Can reproduce even without building PyTorch.
```bash
conda create -n py39 python=3.9
conda activate py39
pip install pyyaml
python setup.py build --cmake-only
# Turn off `build_deps` in setup.py
python setup.py build
```

**Comment by peterjc123** [comment]
Related issue: https://github.com/pypa/setuptools/issues/2417.  In line 687 of the `setup.py`, we passed in an additional empty string for `extra_link_args` and it is now causing problems on Python 3.9.

**Comment by peterjc123** [comment]
@seemethere Do we need to do anything to add python 3.9 support for Windows binaries?
