### ISSUE TITLE
DDP mismatch in rank to GPU selection

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#47629]
## 🐛 Bug

Possible root cause for https://github.com/pytorch/pytorch/pull/45435.  CC @walterddr 
Thanks to @jaglinux for the following triage information.

For barrier call, all reduce uses tensor of device type cuda with the following formula:

`int16_t deviceIdx = static_cast<int16_t>(rank_ % numGPUs);`

https://github.com/pytorch/pytorch/blob/a49367e9c9fcfa9547782420a24441f13fef19dc/torch/lib/c10d/ProcessGroupNCCL.cpp#L1413

But when the tests are called, the tensors uses different formula to calculate rank to GPU selection.

https://github.com/pytorch/pytorch/blob/a49367e9c9fcfa9547782420a24441f13fef19dc/torch/testing/_internal/distributed/distributed_test.py#L367-L374

Hence for rank 0,1,2 ; barrier uses tensors of cuda0, cuda1, cuda2 device type and for testing, tensors of cuda0, cuda2, cuda4 are used.

If we change `rank_to_GPU` data structure in distributed_test.py to return `rank % numGPUs`. With this change, all the tests are passing.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by jaglinux** [comment]
I was running the python test_distributed_spawn tests on a 8 gpu machine with rank as 3. All the tests belonging to default group testing (group.WORLD) were failing due to timeout. Reason is rank to gpu mapping is different in  barrier and distributed_test.py.
Issue does not happen in new groups because it uses nccl new stream for the test run (after barrier call).
Quick fix is to mimic the rank % numGPUs behavior in distributed_test.py rank_to_GPU.
https://github.com/pytorch/pytorch/blob/a49367e9c9fcfa9547782420a24441f13fef19dc/torch/testing/_internal/distributed/distributed_test.py#L367-L374
--- a/torch/testing/_internal/distributed/distributed_test.py
+++ b/torch/testing/_internal/distributed/distributed_test.py
@@ -364,7 +364,7 @@ class DistributedTest:
             if BACKEND == "nccl":
                 apply_hack_for_nccl()

-            nGPUs_per_process = nGPUs // world_size
+            nGPUs_per_process = 1
             rank_to_GPU = {
                 i: list(
                     visible_devices[i * nGPUs_per_process: (i + 1) * nGPUs_per_process]


Long term fix could be adding a new function parameter to specify tensor in barrier() for nccl backend.
https://github.com/pytorch/pytorch/blob/a49367e9c9fcfa9547782420a24441f13fef19dc/torch/lib/c10d/ProcessGroupNCCL.cpp#L1413
When calling barrier for nccl backend (https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L480),
 user can specify the tensors with appropriate rank to gpu mapping instead of using the default one.
