### ISSUE TITLE
jit/test_recursive_script.py is not Python 3.6+ compatible

### ISSUE THREAD

**Issue by surak** [pytorch/pytorch#47760]
https://github.com/pytorch/pytorch/blob/88ec72e1c2a4b1e2a15cbe4703b9567bf9369a09/test/jit/test_recursive_script.py#L4

The [Typing_extensions](https://github.com/python/typing/blob/master/typing_extensions/README.rst) is meant to be used on Python up to 3.6, since _Typing_ comes by default from then on and should be used instead. 

One should not force the installation of a backport compatibility library on current software.

It is only used once, at https://github.com/pytorch/pytorch/blob/88ec72e1c2a4b1e2a15cbe4703b9567bf9369a09/test/jit/test_recursive_script.py#L175 , and replacing `typing_extension` with `typing` just works. 

cc @gmagogsfm

**Comment by skyline75489** [comment]
Correct me if I'm wrong, but according to the doc, [typing.Final](https://docs.python.org/3/library/typing.html#typing.Final) is first added in Python 3.8. Right now we need to support Python 3.6+. I guess we can not just replacing `typing_extension` with `typing`.

**Comment by suo** [comment]
Thanks for raising this issue! I believe we're okay here; `typing_extensions` is intended makes handling typed Python code a bit easier across versions, since it includes backports of many common types (including `Final`, which @skyline75489 correctly notes was only added in 3.8). Its inclusion does not make the code incompatible with Python 3.6+ versions, since the exported objects will just point to the standard library ones if necessary.

Going to close out this issue to clear up our tracking, but feel free to reopen or comment further if you have any questions.

**Comment by surak** [comment]
Correct me please if I am wrong. The source asks specifically for `typing_extensions`, not `typing`, so it fails on 3.8+ unless you install typing_extensions - which is redundant on 3.8+. 

It does not point to the right library magically, since there is no version checking or mechanism to do so. It simply fails until you install it.
