### ISSUE TITLE
Figure out a better way to find libuv on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#48304]
## 🐛 Bug

The current implementation can be seen in https://github.com/pytorch/pytorch/blob/ec256ab2f2f7c65c3fa25e16438a467f9959937c/CMakeLists.txt#L242-L256, which heavily depends on the environmental variable `CONDA_PREFIX`. This won't work on all possible situations.
Actually according to https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html, 
`CONDA_PREFIX` is only an optional variable that can be set by users. They happen to be set when you are using Anaconda Prompt or using `conda activate`. But if you are using `conda-build` or relying on `PATH`, then it won't work. 

There are several things we could improve
1. Better hints for finding libuv. `CONDA_PREFIX` is not enough, `conda-build` uses `PREFIX`. (Or would it be better to use `[PYTHON ROOT]\Library`?)
2. Better error message. Users are completely at a lost when they see the following error message.
```CMake Error at CMakeLists.txt:242 (find_library):
  Could not find libuv_tmp_LIBRARY using the following names: uv, libuv
```
Tell me them how to install libuv or disable `USE_DISTRIBUTED` (automatically?)

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by mrshenli** [comment]
cc @gunandrose4u

**Comment by gunandrose4u** [comment]
@peterjc123, base on doc from conda-build, I think we need add PREFIX as one of HINTS to find_library. And for error message, it is threw out by find_library, I think we can not customize the error message. So add script after find_library to detect if libuv does not find, will show a more friendly warning message to tell user due to libuv is not installed in current conda env, distributed feature is disabled for the build in order to not break the build. And in readme document we tell user that how to install libuv, https://github.com/pytorch/pytorch#install-dependencies. Do you mean we need add same message in error message?

**Comment by peterjc123** [comment]
@gunandrose4u Actually, the fix could be quite simple.
1. Just remove the `REQUIRED` item from `find_library` so that it won't throw an error if `libuv` is not found
2. `if(NOT EXISTS ${libuv_tmp_LIBRARY})` can be simplied to `if (NOT libuv_tmp_LIBRARY)`
3. Add more message to the warning(e.g. "You may install libuv using `conda install libuv`.")
4. Add more hints to `find_library` ('PREFIX' and probably `Python_ROOT_DIR`)
5. Use `get_file_component` with `libuv_tmp_LIBRARY` instead in `set(ENV{libuv_ROOT} $ENV{CONDA_PREFIX}\\Library) `

**Comment by gunandrose4u** [comment]
@peterjc123 , I've created a PR to fix it. Please help to review. Thank you! 
https://github.com/pytorch/pytorch/pull/48571
