### ISSUE TITLE
Filestore path should be checked in the launch.py

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#48475]
## 🚀 Feature
If the file couldn't be created, the process will hang for a long time.
It'd better to check if the file can be created with the provided file path and the error can be thrown promptly.

## Motivation

It's annoying that the process hang for a long time. 

## Pitch

The error can be found before spawning processes.
So, the user can know the error quickly.

## Alternatives

Reminder user to provide a right filepath, for example, the directory exists, in the tutorial. But it isn't a perfect solution.

## Additional context

Now, Windows users can only run distributed training with FileStore

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by osalpekar** [comment]
@mszhanyi This timeout is intentional. Earlier we would see processes race to create the file, so we implemented a timeout that will wait for the file to be created if the first attempt to open the file was unsuccessful (See issue: https://github.com/pytorch/pytorch/issues/13750 and PR: https://github.com/pytorch/pytorch/pull/14388).

I would suggest using the Python tempfile library to create a named file and use that for the FileStore ([docs](https://docs.python.org/3/library/tempfile.html)). We use this method in our Python FileStore tests - this way you are guaranteed to have a file of that name created before instantiating the store.

2 more thoughts (as an aside):
* You can make the timeout for all store operations smaller in general using the `Store.set_timeout()` function ([docs](https://pytorch.org/docs/stable/distributed.html#distributed-key-value-store))
* Windows support for the TCPStore is in progress - see https://github.com/pytorch/pytorch/pull/47749

**Comment by mszhanyi** [comment]
@osalpekar Thank your explain for the background. 
I think we might use dist_url to replace the parameters of master_addr/port.
https://github.com/pytorch/pytorch/blob/e7ca62be08f96b07efc1271baf9b02d4e7be226a/torch/distributed/launch.py#L170-L175
When we find the dist_url is a file url schema, we can check if the file could be created before spawning processes. So, there's no chance to pass the improper file path to the processes. And we may not come across this timeout any more.
It would make launch.py more friendly to users who use FileStore.

**Comment by osalpekar** [comment]
I see, thanks for this feedback - a `dist_url` argument for the distributed launch utility indeed sounds like it would be more intuitive for FileStore users.

**Comment by mszhanyi** [comment]
@osalpekar , thank your reply. I'll try to improve it.

**Comment by mantaionut** [comment]
@mszhanyi do you have a repro case where this issue happens?

**Comment by mszhanyi** [comment]
You could try https://github.com/pytorch/examples/tree/main/distributed/ddp
