### ISSUE TITLE
PyTorch Static Symmetric Quantization Results in Non-Zero Zero Point Values.

### ISSUE THREAD

**Issue by leimao** [pytorch/pytorch#48473]
## 🐛 Bug

By definition, the symmetric quantization will have zero points of value 0. However, the zero point values are not 0 after symmetric quantization calibration.

In the PyTorch [official static quantization example](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html), we have
```
QConfig(activation=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, reduce_range=True), weight=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_tensor_symmetric))
Post Training Quantization Prepare: Inserting Observers

 Inverted Residual Block:After observer insertion

 Sequential(
  (0): ConvBNReLU(
    (0): ConvReLU2d(
      (0): Conv2d(
        32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32
        (activation_post_process): MinMaxObserver(min_val=inf, max_val=-inf)
      )
      (1): ReLU(
        (activation_post_process): MinMaxObserver(min_val=inf, max_val=-inf)
      )
    )
    (1): Identity()
    (2): Identity()
  )
  (1): Conv2d(
    32, 16, kernel_size=(1, 1), stride=(1, 1)
    (activation_post_process): MinMaxObserver(min_val=inf, max_val=-inf)
  )
  (2): Identity()
)
..........Post Training Quantization: Calibration done
Post Training Quantization: Convert done

 Inverted Residual Block: After fusion and quantization, note fused modules:

 Sequential(
  (0): ConvBNReLU(
    (0): QuantizedConvReLU2d(32, 32, kernel_size=(3, 3), stride=(1, 1), scale=0.1516050398349762, zero_point=0, padding=(1, 1), groups=32)
    (1): Identity()
    (2): Identity()
  )
  (1): QuantizedConv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), scale=0.17719413340091705, zero_point=63)
  (2): Identity()
)
Size of model after quantization
Size (MB): 3.631847
..........Evaluation accuracy on 300 images, 66.67
```

The `qscheme` is `qscheme=torch.per_tensor_symmetric`, but we see that the zero point value for the `QuantizedConv2d` layer is 63.

In addition, sometimes I was using `qscheme=torch.per_channel_symmetric`, the zero point values should be a vector whose length is the number of channels, but I also see a single value for the zero point from the print-outs.

## To Reproduce

To reproduce, please follow the PyTorch [official static quantization example](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html).

## Expected behavior

The zero points should be all zero for symmetric quantization.

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.16.8

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torchvision==0.8.1
[conda] Could not collect

## Additional context

I also asked a similar question in the PyTorch forum, but nobody responded.
https://discuss.pytorch.org/t/non-zero-values-for-zero-point-in-symmetric-quantization/103996

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by leimao** [comment]
@ngimel Any follow-up or clarifications? Thank you.

**Comment by vkuzo** [comment]
> By definition, the symmetric quantization will have zero points of value 0. However, the zero point values are not 0 after symmetric quantization calibration.

There might be some confusion here on what is meant by zero_point.  The zero_point as meant by PyTorch docs is from this equation, there is no requirement that it should or should not be equal to zero.
```
fp32_value = float(q_value - zero_point) * scale
```

The boundaries of quantized values are represented by `quant_min` and `quant_max` in the code, you can check https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L181 for the logic of how different quantization schemes map to these values.

> In addition, sometimes I was using qscheme=torch.per_channel_symmetric, the zero point values should be a vector whose length is the number of channels, but I also see a single value for the zero point from the print-outs.

Is there a repro we can take a look at?  I would guess that you can get the behaviour you need by using per-channel observers, instead of per-tensor observers.  Check out `torch.quantization.get_default_qconfig('fbgemm')`.

**Comment by leimao** [comment]
Thanks @vkuzo for the quick response. However, by definition, symmetric quantization with dtype of `int8` has to have `zero_point` to be exactly zero. See the [TensorFlow documentation](https://www.tensorflow.org/lite/performance/quantization_spec#symmetric_vs_asymmetric) and a [white paper](https://arxiv.org/abs/2004.09602) published by NVIDIA.

**Comment by vkuzo** [comment]
> Thanks @vkuzo for the quick response. However, by definition, symmetric quantization with dtype of `int8` has to have `zero_point` to be exactly zero. See the [TensorFlow documentation](https://www.tensorflow.org/lite/performance/quantization_spec#symmetric_vs_asymmetric) and a [white paper](https://arxiv.org/abs/2004.09602) published by NVIDIA. Note that in the printouts, it shows that
> 
> ```
> dtype=torch.qint8, qscheme=torch.per_tensor_symmetric
> ```

@leimao, I think you are right, looks like the confusion was on my end.  Let me take a closer look.

**Comment by leimao** [comment]
Thank you very much @vkuzo.

**Comment by vkuzo** [comment]
```
    (0): QuantizedConvReLU2d(32, 32, kernel_size=(3, 3), stride=(1, 1), scale=0.1516050398349762, zero_point=0, padding=(1, 1), groups=32)
```

If you are printing out the conv object, the scale + zp here are for the activation (code: https://github.com/pytorch/pytorch/blob/55919a47588630d27333df37a94753b8d1f14eb8/torch/nn/quantized/modules/conv.py#L72).  To confirm, are you also using `symmetric` qscheme for activations?  

The scale + zp for the weight can be checked by inspecting the packed weight object, i.e. `conv_obj._weight_bias()[0]`.  Do you see a zp != 0 there?

**Comment by leimao** [comment]
@vkuzo I was using the code from the tutorial. The code did not specify the `qscheme` explicitly. However, since the program prints out 
```
QConfig(activation=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, reduce_range=True), weight=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_tensor_symmetric))
```
I considered the program is using `torch.per_tensor_symmetric` globally for the entire neural network.

**Comment by leimao** [comment]
@vkuzo Looks like for PyTorch, the zero point value is also 0 when the `dtype` is `qint8`. See [MinMaxObserver](https://pytorch.org/docs/stable/torch.quantization.html#torch.quantization.MinMaxObserver).

**Comment by leimao** [comment]
@vkuzo Oh, Jesus. The `qscheme` and `dtype` were not explicitly defined for activation.
```
activation=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, reduce_range=True)
```
The default `qscheme` is `torch.per_tensor_affine` and `dtype` is `torch.quint8`. This means that the activation is not symmetric and the zero-point value could be non-zero.

**Comment by leimao** [comment]
@vkuzo But I don't understand why in [MinMaxObserver](https://pytorch.org/docs/stable/torch.quantization.html#torch.quantization.MinMaxObserver), it also says:
```
Only works with torch.per_tensor_symmetric quantization scheme
```

**Comment by leimao** [comment]
@vkuzo Could you please also confirm whether the `scale` and `zero_point` for `QuantizedConvReLU2d` are for the weights or activations? I cannot determine whether the `scale` and `zero_point` are for the weights or activations by just reading the code snippets you pointed me to. Thank you.

**Comment by vkuzo** [comment]
> @vkuzo Could you please also confirm whether the `scale` and `zero_point` for `QuantizedConvReLU2d` are for the weights or activations? I cannot determine whether the `scale` and `zero_point` are for the weights or activations by just reading the code snippets you pointed me to. Thank you.

If you print out modules like `QuantizedConv2d`,  `QuantizedConvReLU2d`, etc, the scale and zero point values are for the outgoing activations.  They are displayed by this function: https://github.com/pytorch/pytorch/blob/55919a47588630d27333df37a94753b8d1f14eb8/torch/nn/quantized/modules/conv.py#L72. 

If you'd like to inspect the scale + zp for the weights, you could unpack and inspect the quantized conv weights, with the `conv_obj._weight_bias()[0]` function.

> Only works with torch.per_tensor_symmetric quantization scheme

Thanks, we will look into this.  We should either remove this from the docs if it's outdated, or explain the reasoning.

**Comment by vkuzo** [comment]
Please let us know if there are any more questions on this one

**Comment by matcosta23** [comment]
# Same Issue in a Similar Context

Two years later, I am still struggling with the same problem. I will introduce you to the context I am working in and ask two questions, one of them very similar to the one proposed in this topic, but with more nuances.

## Context.

I am exploring the [**FX Graph Mode Post Training Static Quantization**](https://pytorch.org/tutorials/prototype/fx_graph_mode_ptq_static.html) and I adapted the tutorial to quantize a ResNet50, which worked very well.

However, my second step is to export this quantized version as a TensorRT engine. To achieve this goal, I am using the [Torch-TensorRT library](https://github.com/pytorch/TensorRT) and followed the [**quantized_resnet_test.py**](https://github.com/pytorch/TensorRT/blob/main/examples/fx/quantized_resnet_test.py) example.

I ran this example with the same versions of torch and tensorrt described in this [TensorRT issue with no solution (#1813)](https://github.com/pytorch/TensorRT/issues/1813) and I got the same TRT error message.

When we take a look at the **quantized_resnet_test.py** example, we see that the *QConfig* is not the default one used in the **FX Graph Mode Post Training Static Quantization** tutorial. The difference between them and the impact on the quantized graph is quite relevant.

### Difference between the torch.ao.quantization.QConfig

QConfig used in the **FX Graph Mode Post Training Static Quantization** tutorial (let's call it qconfig_default):

```python
>>> qconfig_default = get_default_qconfig("x86")
>>> qconfig_default.activation
functools.partial(<class 'torch.ao.quantization.observer.HistogramObserver'>, reduce_range=True){}
>>> qconfig_default.weight
functools.partial(<class 'torch.ao.quantization.observer.PerChannelMinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_channel_symmetric){}
```

The custom QConfig proposed by the **quantized_resnet_test.py** example (let's call it qconfig_trt):

```python
>>> qconfig_trt= QConfig(
        activation=torch.ao.quantization.observer.HistogramObserver.with_args(
            qscheme=torch.per_tensor_symmetric, dtype=torch.qint8
        ),
        weight=torch.quantization.default_per_channel_weight_observer,
    )
>>> qconfig_trt.activation
functools.partial(<class 'torch.ao.quantization.observer.HistogramObserver'>, qscheme=torch.per_tensor_symmetric, dtype=torch.qint8){}
>>> qconfig_trt.weight
functools.partial(<class 'torch.ao.quantization.observer.PerChannelMinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_channel_symmetric){}
``` 

In other words, the authors of *qconfig_trt* just wanted to make sure that the quantization for activation would also be symmetric and represented as torch.qint8.

### Impact of the QConfig on the Quantized FX Graph.

After preparing (*prepare_fx*), calibrating and quantizing (*quantize_fx*) a ResNet model with these two different instances of QConfig, we can compare the FX graphs obtained.

>⚠️ Disclaimer
>
> The function *convert_to_reference_fx* has been replaced by *quantize_fx* in **quantized_resnet_test.py**.

```python
>>> quantized_resnet_18_from_qconfig_trt
GraphModule(
  (conv1): ConvReLU2d(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
    (1): ReLU(inplace=True)
  )
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Module(
    (0): Module(
      (conv1): ConvReLU2d(
        (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): ReLU(inplace=True)
      )
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (relu): ReLU(inplace=True)
    )
    ...
>>> quantized_resnet_18_from_qconfig_default
GraphModule(
  (conv1): QuantizedConvReLU2d(3, 64, kernel_size=(7, 7), stride=(2, 2), scale=0.010285161435604095, zero_point=0, padding=(3, 3))
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Module(
    (0): Module(
      (conv1): QuantizedConvReLU2d(64, 64, kernel_size=(3, 3), stride=(1, 1), scale=0.018722333014011383, zero_point=0, padding=(1, 1))
      (conv2): QuantizedConv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), scale=0.032894741743803024, zero_point=67, padding=(1, 1))
    )
    ...
``` 

## :one: Why does QConfig have such a big impact on the final quantized graph?

When comparing the two quantized graphs, we see that the scale and zero points are not printed when using *qconfig_trt*. Also, we see that Conv2d and ReLU are not fused. **Do you know why we have this behavior?**

This lack of calibration statistics could be a possible cause of the error message illustrated in the [issue #1813](https://github.com/pytorch/TensorRT/issues/1813) when trying to export the graph to TensorRT.

## :two: Why does the quantized and fusion model not respect QConfig?

When trying, however, to export the quantized_resnet_18_from_qconfig_default, the error is the one encountered by @leimao .

```bash
...
  File "/root/miniconda3/envs/lib/python3.8/site-packages/torch_tensorrt/fx/converters/acc_ops_converters.py", line 3253, in acc_ops_quantize_per_tensor
    raise RuntimeError(f"Only support zero_point == 0, get {q_zero_point}")
RuntimeError: Only support zero_point == 0, get 64
...
``` 

However, following @vkuzo 's recommendations, I tried to check why the non-zero zero values problem was occurring only in the *QuantizedConv2d* layer and not in the *QuantizedConvReLU2d*.

```bash
>>> # Code to access the QuantizedConvReLU2d of module 0 of layer 1.
>>> list(list(quantized_rn18.layer1.children())[0].children())[0]._weight_bias()[0]
       tensor(...), dtype=torch.qint8, quantization_scheme=torch.per_channel_affine, scale=(...),
       zero_point=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       axis=0)
>>> # Code to access the QuantizedConv2d of module 0 of layer 1.
>>> list(list(quantized_rn18.layer1.children())[0].children())[1]._weight_bias()[0]
       tensor(...), dtype=torch.qint8, quantization_scheme=torch.per_channel_affine, scale=(...),
       zero_point=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       axis=0)
``` 

This result shows two weird aspects:
1. Although the graph shows that the zero_points of the QuantizedConv2d module are non-zero, access to this tensor shows otherwise.
2. The quantization scheme in both modules was illustrated as torch.per_channel_affine. However, the scheme chosen was torch.per_channel_symmetric.

Thank you very much for your attention!
