### ISSUE TITLE
Torchscript does not work with type: ignore comments for mypy

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#48643]
## 🚀 Feature

torchscript should work with [`type: ignore` comments](https://mypy.readthedocs.io/en/stable/common_issues.html#spurious-errors-and-locally-silencing-the-checker) from `mypy`.

## Motivation

In `torchvision` we are beginning to type check our annotations with `mypy`. Since torchscript as of now only supports a subset of the annotations, we need to silence `mypy` on some lines. This can be done with `type: ignore` comments that are added to the offending line. 

Unfortunately and as of now, this doesn't work with torchscript. You can find two examples below:

### Overload

```python
from torch import nn, jit, Tensor
from typing import List


class Foo(nn.Module):
    @jit._overload_method
    def forward(self, input: List[Tensor]) -> Tensor:
        pass

    @jit._overload_method  # type: ignore[no-redef]
    def forward(self, input: Tensor) -> Tensor:
        pass

    def forward(self, input: Tensor) -> Tensor:  # type: ignore[no-redef]
        pass


foo = Foo()
jit.script(foo)
```

```
RuntimeError: expected type comment but found 'def' here:
def forward(self, input: Tensor) -> Tensor:  # type: ignore[no-redef]
~~~ <--- HERE
```

### Override

```python
from torch import nn, jit, Tensor


class Bar(nn.ModuleDict):
    def forward(self, input: Tensor) -> Tensor:  # type: ignore[override]
        pass


bar = Bar()
jit.script(bar)
```

```
RuntimeError: expected type comment but found 'def' here:
def forward(self, input: Tensor) -> Tensor:  # type: ignore[override]
~~~ <--- HERE
```

## Additional context

See https://github.com/pytorch/vision/issues/3027 for a real-world example.

Cc @eellison @fmassa @frgfm 

cc @gmagogsfm

**Comment by frgfm** [comment]
@pmeier should we ignore the modules that have mypy `type: ignore` then?

**Comment by pmeier** [comment]
> should we ignore the modules that have mypy `type: ignore` then?

We should fix torchscript to able to handle these comments. If I'm not wrong, they simply need to be discarded.

**Comment by frgfm** [comment]
@pmeier my bad, I thought you opened the issue in the torchvision repo!
Happy to help but I would need some guidance as I haven't worked on JIT so far

**Comment by pmeier** [comment]
@frgfm Lets wait for the "pros" to asses the situation first. I've never worked on `torch.jit` so far and thus I can't comment if this is viable / doable / ...

**Comment by pmeier** [comment]
@gmagogsfm Any update on this?

**Comment by gmagogsfm** [comment]
Sorry for the delay. Just did some investigation.

The bug is due to an assumption in TorchScript when parsing source code: In function declaration, any line that contains `# type:` is considered to be a type line. Then TorchScript lexer expects the type line to contain only type comment, nothing else.

This is obviously at odds with mypy's ignore syntax, which requires `# type: ignore` to be at the end of a line together with other code. So we do have a special case for it, just that it doesn't currently allow you to specify particular type check rules to ignore. In other words, following code would work:

```
class Bar(nn.ModuleDict):
    # general type: ignore works!
    def forward(self, input: Tensor):  # type: ignore
        pass
```

Hopefully, this work-around is enough for the short term need, we will make parser logic more robust and update here.

**Comment by gmagogsfm** [comment]
The proper fix has landed, you shouldn't need to use the workaround in my earlier comment any more (provided you use recent enough pytorch build)
