### ISSUE TITLE
Test self.assertEqual with msg does not print numerical comparison results

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#48879]
## 🐛 Bug

Test `self.assertEqual` with kwarg `msg=` does not print numerical comparison results

e.g. if the following test fails

```python
    self.assertEqual(a, b, msg='something')
```

we only get **"AssertionError: False is not true : something"**

This is not as intuitive as the `assertEqual` without `msg=`, which prints something like

AssertionError: False is not true : Scalars failed to compare as equal! Comparing 5.067170143127441 and 5.067152976989746 gives a difference of 1.71661376953125e-05, but the allowed difference with rtol=1.3e-06 and atol=1e-05 is only 1.658729887008667e-05!

cc @mruberry @VitalyFedyunin @walterddr

**Comment by xwang233** [comment]
and why do we have two labels of "tests" and "testing" 🤔

**Comment by mruberry** [comment]
"testing" could probably have a better, more distinct, name, but it's intended to be used for issues related to the torch.testing module vs. PyTorch's actual tests (which get "module: tests"). 

I think we would accept a PR combining custom messages and the default message. I don't have an immediate design for what these messages would look like. Maybe some other testing libraries have similar functionality and formatting we can use for inspiration? We also don't need to overthink it. We could probably print the "default" message and then just append the the provided msg string, for example.

**Comment by walterddr** [comment]
IMO assert utilities should differentiate between different type of assertions easily. out of top of my head, junit does something very similar to this. 
since we are already extending/overriding the assert function we might be able to use something similar to https://github.com/junit-team/junit5/tree/cfdf09aad5ed70fae210fe14fad6d6356f749242/junit-jupiter-api/src/main/java/org/junit/jupiter/api?

**Comment by mariosasko** [comment]
@walterddr Could you please be more specific? The link you provided points to the whole API.

**Comment by walterddr** [comment]
oops. actually I was wrong. there's already a mechanism to customized assert messages based on content type in : https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1049 - 

The problem is it doesn't process use message that well. Preparing an improvement to attach user-provide `msg` after internal `debug_msg`
