### ISSUE TITLE
bucket_cap_mb not honored by AllReduce ops

### ISSUE THREAD

**Issue by pro-panda** [pytorch/pytorch#48880]
Running the [imagenet example](https://github.com/pytorch/examples/tree/master/imagenet) on a single node, 4-GPU setup calls 3 NCCL AllReduce ops per batch for gradient synchronization, with sizes `2052000`, `28852224`, and `15853824` bytes.

I assumed that each op will follow the `bucket_cap_mb` limit, i.e. none of the allReduce would have sizes more than say, 25 MB (default)

Changing bucket_cap_mb to 35 changes allReduce calls to `2052000`, `38297600`, and `6408448`. It does impact the allReduce calls, but now by putting a direct limit

Am I missing something, or is this a bug?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by pritamdamania87** [comment]
DDP uses 1MB for the last bucket to avoid high latency of large allreduce after backward is done. We don't split parameters across buckets, so the actual bucket size might be slightly higher, as a result this is the `2052000` bytes bucket you see. After this, DDP would allocate buckets of 25MB each, but again since we don't split parameters across buckets and instead create a new bucket each time the current bucket's size exceed 25MB, that is why you see a bucket size of `28852224`. Finally, the bucket size of `15853824` is just the remaining parameters left in the model.

**Comment by pro-panda** [comment]
@pritamdamania87 

> DDP uses 1MB for the last bucket to avoid high latency of large allreduce after backward is done

* first bucket ?
And how does this improve performance?

> Finally, the bucket size of 15853824 is just the remaining parameters left in the model.

Makes sense. But, in a [BERT-base fine tuning example](https://github.com/huggingface/transformers/tree/master/examples/question-answering), I am seeing bucket sizes (kbs) in the following order,
 - 1 round of `15368`,
 - 11 rounds of `28351488`,
 - 1 round of `29927424`,
 - 1 round of `93763584` (90 MB!),
 - 1 round of `796`.

I'm surprised by the initial `15368`, and the 90MB rounds. Does PyTorch use a bucket smaller than 1 MB initially to avoid splitting parameters?
