### ISSUE TITLE
ONNX export is successful but failed in ONNX runtime

### ISSUE THREAD

**Issue by padmasreenagarajan** [pytorch/pytorch#49218]
The YOLOv3 model is trained in PyTorch and converted to ONNX format successfully and it passed the ONNX checker also.
But with ONNX runtime, it throws the following error.

**AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

(shapes (22743, 85), (1, 22743, 85) mismatch)
 x: array([[1.017466e+01, 2.567739e+01, 8.318379e-01, ..., 9.088111e-10,
        7.015010e-10, 8.703636e-10],
       [4.127174e+01, 2.935895e+01, 2.139306e+00, ..., 1.084030e-10,...
 y: array([[[-1.462450e-03,  3.089583e-41,  2.334467e+01, ...,
          0.000000e+00,  0.000000e+00,  0.000000e+00],
        [-1.458824e-03,  3.089583e-41, -1.458803e-03, ...,...**

I used
Pytorch 1.3
ONNX 1.5
Opset 10

I have also tried with different torch versions 1.4 and 1.5. But with Torch 1.5, the model did not pass the checker also. Why?
Is there any issue with the PyTorch for ONNX export?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@padmasreenagarajan - First, I would recommend using the latest PyTorch version for export. There have been numerous updates to ONNX exporter since 1.5. Also, if the checker is passing and if you don't see anything obvious issue with the exporter, then I would recommend opening an issue in ORT repo. If you think there's a export issue then feel free to reopen the issue with proper repro (model and export code).

**Comment by asherp7** [comment]
I also had the same problem when exporting a YOLOv3 from PyTorch to ONNX.
After some investigation, I found that the problem is inherent to the YOLOv3 architecture:
The bounding boxes in YOLOv3 are computed with an exponent see for example: [PyTorch-YOLOv3](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/models.py#:~:text=x%5B...%2C%202%3A4%5D%20%3D%20torch.exp(x%5B...%2C%202%3A4%5D)%20*%20self.anchor_grid%20%23%20wh).
Therefore, when dealing with large bounding boxes, the tiny numerical differences between PyTorch and ONNX are amplified to huge differences. 
For example: The difference between 15.00002 and 15.00001 is only 0.00001 (which is a feasible difference when exporting a PyTorch model to ONNX), but after exponentiation it would cause a difference of: exp(15.00002) - exp(15.00001) = 32.690
