### ISSUE TITLE
conv2d sometimes produces wrong results on cpu

### ISSUE THREAD

**Issue by quinor** [pytorch/pytorch#49268]
## 🐛 Bug

I'm trying to separate grouped conv2d into the grouped convolutions. The following code fails nondeterministically:

## To Reproduce

```
import torch
from torch import nn
from torch.nn import functional as F


good = 0
bad = 0

for _ in range(1000):
    groups = 12
    conv = nn.Conv2d(12, 12, 3, 1, 1, groups=groups, bias=False)
    kernels = torch.stack(conv.weight.chunk(groups, 0))
    # Reference
    x = torch.randn(1, 12, 24, 24)
    out = conv(x)
    # Comparison
    o1 = F.conv2d(x[:, :1], kernels[0], padding=1)
    if not torch.allclose(o1, out[:, :1]):
        bad += 1
    else:
        good += 1

print(f"good {good} bad {bad}")
```
output:
```
good 498 bad 502
```

## Expected behavior

The could should be "good" for all 1000 trials.

## Environment

```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.0
CMake version: version 3.19.1

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-lightning==1.1.0
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect
```

## Additional context

The test code taken from https://discuss.pytorch.org/t/how-to-access-weights-of-each-group-in-a-grouped-convolution/47868/12 . @ptrblck (you were looking at it in the discussion)

possibly related to #21597

cc @albanD @mruberry

**Comment by glaringlee** [comment]
@quinor 
Which pytorch version you were using? I run your test code under latest pytorch, got 1000 good.

**Comment by quinor** [comment]
@glaringlee please see the environment I posted originally, pytorch version 1.7.1. Maybe the issue is with the specific CPU backend used; how to check which one is it?

**Comment by albanD** [comment]
Hi,

I can actually reproduce this on colab.
But if you actually print the biggest difference, it is in the order of `1e-7` and that would be expected for floating point precision.
If you add a `torch.set_default_dtype(torch.double)` at the beginning, you will see that you get all goods.

So I would say this is expected behavior of limited floating point precision right?

**Comment by quinor** [comment]
So, I was expecting something of an order of 1e-15 (fp32 machine epsilon -> rounding errors) and that would I have dismissed. The 1e-7 just seemed big to me, would you mind to explain @albanD why you find that order of magnitude expected?

**Comment by albanD** [comment]
1e-15 is the precision of double precision floating point numbers.
Single precision float (that are the default in pytorch) is 1e-6.

That is why I was expecting this kind of precision.
Also that is why changing the default dtype to use double precision numbers makes your test script pass as you get much better precision (in the order of 1e-15 as you would expect).

**Comment by quinor** [comment]
Thank you! That's actually pretty embarassing, I had confused the fp32 and fp64 machine epsilons... It's good to me then, thanks!

Still, should the cpu execution be non-determininistic? I know there is a flag for that in the cuda backend...

**Comment by albanD** [comment]
You won't be able to make it so that the difference between the two is exactly 0 just because they run different code.

For the determinism, tough, you can check the [note about this](https://pytorch.org/docs/stable/notes/randomness.html?highlight=determinism) but it is mostly towards CUDA indeed.
On CPU, I think the biggest offender for determinism is multi-threading. But in general third party libraries we use might not be deterministic either (I don't know for OpenBLAS, MKL, etc).

**Comment by quinor** [comment]
Thank you for the explaination, I'm closing the issue then.

**Comment by mruberry** [comment]
fyi @kurtamohler for the determinism discussion

**Comment by kurtamohler** [comment]
@quinor, if you put `torch.set_deterministic(True)` at the top of your script, does that fix it? I would try it myself, but the issue doesn't reproduce for me.

**Comment by quinor** [comment]
@kurtamohler it's same with `torch.set_deterministic(True)`.

**Comment by kurtamohler** [comment]
Maybe we should track down what conditions cause the slight difference and then add a nondeterministic alert for those conditions. What do you think @mruberry ?

**Comment by mruberry** [comment]
Analyzing why this is occurring could be interesting but I wonder if this issue speaks to two more fundamental challenges with a flag for selecting "deterministic" algorithms that we just need to document more clearly:

- when running with multiple threads a lot of operations are probably "nondeterministic" 
- we don't want to police math libraries like MKLDNN that don't provide their own mechanisms for selecting deterministic algorithms

For example, in this case I imagine that running with a single thread would be deterministic, and I bet there's a lot of float addition that's not always occurring in the same order when PyTorch or a math library uses multiple threads.

**Comment by ptrblck** [comment]
For this I think it would be interesting to know which CPU you are using, as I'm unable to reproduce the issue using
* `Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz`
* `Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz`

but it fails on
* `AMD EPYC 7742 64-Core Processor`

The latter case also fails with:
```python
MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 OMP_NUM_THREADS=1 python tmp.py
good 513 bad 487
```
as well as setting
```python
torch.set_num_interop_threads(1)
torch.set_num_threads(1)
```

I assume MKL is not used by default on AMD CPUs and it seems one can use `MKL_DEBUG_CPU_TYPE=5` to "fool MKL into using an AVX2 optimization level on AMD CPU's" ([source](https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/)), which solves the issue:
```python
MKL_DEBUG_CPU_TYPE=5 python tmp.py
good 1000 bad 0
```
Do you know, what default implementation would be used on AMD CPUs instead of MKL?

**Comment by quinor** [comment]
I had the issue on `Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz`.
