### ISSUE TITLE
Better engineering on perf testing scripts

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4948]
Our perf testing scripts (as seen in https://github.com/pytorch/pytorch/pull/4945) have a lot of hardcoded bits that let us get them up and running, but now there is some better engineering work to be done.

- [ ] Record exact specifications for performance numbers, and specify the applicability of our numbers to them. As our performance tests are being done on Amazon EC 2 infrastructure, it is sufficient to identify what EC2 instance type (https://aws.amazon.com/ec2/instance-types/) is being run and record this alongside the test. This improves reproducibility as interested parties can spin up an equivalent EC2 instance and rerun the numbers if they want to.
  - [ ] A nice subtask is to document the process for getting an EC2 instance to reproduce results. Maybe Docker can help here too.
- [ ] Move `compare_with_baseline.py` out of line from the shell script
- [ ] Refactor `compare_with_baseline.py` to separate the recorded test data, and the z-value computation (deduplicating the z-value code between the cpu and gpu perf tests)
- [ ] Make tests not rely on @yf225 gists and GitHubs, so that they can be easily updated by other parties without having to synchronize on @yf225 
- [ ] Performance numbers are supposed to be correlated with a particular commit, but in general the commit that something gets merged to master will be different from the commit you can actually conveniently put into the benchmark commit when you are upgrading baselines. Not sure what to do here; maybe we can link to Pull Requests.

cc @VitalyFedyunin @ngimel @ppwwyyxx

**Comment by yf225** [comment]
For CPU perf tests, it's necessary to run them on dedicated machines (vs. shared VPC instances) to avoid runtime fluctuation. However, both dedicated instances and dedicated hosts on EC2 are quite expensive compared to shared instances. For our CI system we can get around it by running the CPU perf tests on our Mac machines which are dedicated, but it will be hard for developers to spin up a strictly equivalent instance and run the tests themselves.

One solution is to encourage the developers to run the CPU perf tests on their own dev machines (using docker to set up the same test environment, but not the same hardware specs), and pay more attention to where the slowness are before/after the change rather than comparing the absolute numbers with the CI benchmark.

**Comment by ezyang** [comment]
Maybe we can use dedicated spot instances to run these stably? Otherwise we can just run these on our own hardware.

**Comment by yf225** [comment]
Spot instances seem to be a great option for developers to run perf tests on. :)

**Comment by ngimel** [comment]
Closing, perf testing is done differently now.
