### ISSUE TITLE
torch::cat_out unexpected result on views

### ISSUE THREAD

**Issue by mreppen** [pytorch/pytorch#49878]
## 🐛 Bug

`cat_out` does two unexpected things on views:
1. It does not fill the target as expected.
2. Subsequent uses of the view with other functions have changed behavior.

I could not find this documented.

## To Reproduce

1. Use e.g. `ones_out` on a view.
2. Use `cat_out` one the view.
3. Use `ones_out` on the view.

- 1 works as expected.
- 2 does not behave as 1.
- 1 and 3 do not do the same thing.
- `index_put` changing behavior suggests the view itself is changed.

```
#include <torch/torch.h>
#include <iostream>

int main() {
  torch::Tensor x = torch::zeros({3, 2});
  torch::Tensor y = x.narrow(/*dim=*/1, /*start=*/0, /*length=*/1);

  y.index_put_({2, 0}, 2);
  std::cout << x << std::endl;
  torch::ones_out(y, {3, 1});
  std::cout << x << std::endl;

  torch::cat_out(y, {torch::ones({3, 1}) * 3.}, /*dim=*/1);
  std::cout << x << std::endl;

  y.index_put_({2, 0}, 2);
  std::cout << x << std::endl;
  torch::ones_out(y, {3, 1});
  std::cout << x << std::endl;
}
```

The lines before and after the `cat_out` behave differently.

## Expected behavior

I think this is clear. Fill the view as if it were a regular tensor and leave the indexing unmodified.

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1
[conda] Could not collect

(just for reference: 
https://github.com/LaurentMazare/ocaml-torch/issues/52)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @VitalyFedyunin @jamesr66a @ppwwyyxx

**Comment by ngimel** [comment]
The bug is this line
https://github.com/pytorch/pytorch/blob/bc4ff7ba0506190524d598be1bbe8112f3e09935/aten/src/ATen/native/TensorShape.cpp#L180 (similar in cuda implementation) - we don't respect `out` strides even if it is correct size.

**Comment by kshitij12345** [comment]
@ngimel I think the issue is with `resize_`, it does check for the shape and strides of the tensor to be resized and returns the original if it matches,

https://github.com/pytorch/pytorch/blob/d434ac35e49a886542a8487e46ec8a49b569ad97/aten/src/ATen/native/Resize.h#L48-L50

But when `optional_memory_format` is given it unconditionally restrides the tensor even if the original tensor was returned and memory format is same as the current one,
https://github.com/pytorch/pytorch/blob/d434ac35e49a886542a8487e46ec8a49b569ad97/aten/src/ATen/native/Resize.cpp#L77-L97

To handle that I think `resize_impl_cpu_` can return tuple,`<Tensor&, bool>`, bool will represent if the tensor was modified or not.

And then,
`self_->empty_tensor_restride(memory_format)` will only be executed if 
```C++
if (optional_memory_format.has_value() && (is_modified || self.suggest_memory_format() != optional_memory_format.value()) {
```

Similarly for CUDA and other dispatches
https://github.com/pytorch/pytorch/blob/d434ac35e49a886542a8487e46ec8a49b569ad97/aten/src/ATen/native/native_functions.yaml#L1810-L1818

Let me know if that sounds right or I am missing something.

Thanks!

**Comment by ngimel** [comment]
@kshitij12345 your analysis is correct, when given a memory format argument, `resize_` unconditionally restrides the output, even if original size was correct. However, I think we should fix it at the call site rather than in `resize_` implementation - people sending memory format argument want to see it honored and not selectively ignored. So in `cat` implementation you can check the `out` size and call `resize_` with memory format only if needed. Also check the following `cat` implementation to make sure that it can handle potentially discontiguous `out` - there is a slow path that definitely can do it, so make sure all problematic cases are sent to the slow path.

**Comment by gchanan** [comment]
But isn't this not what the documentation of `resize_` says?

> memory_format (torch.memory_format, optional) – the desired memory format of Tensor. Default: torch.contiguous_format. Note that memory format of self is going to be unaffected if self.size() matches sizes.

**Comment by ngimel** [comment]
Better fix the docs than change behavior.

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/issues/50076
