### ISSUE TITLE
PyTorch's angle is inconsistent with C++'s and Python's

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#49884]
In Pytorch, `0j` and `-0j` are treated as equivalent while in C++'s `std::complex` both are distinct values.
Sample snippets below.

**Pytorch**
```python
>>> import torch
>>> torch.__version__
'1.8.0a0+23c46c4'
>>> t = torch.tensor(-1 + 0.j)
>>> t
tensor(-1.+0.j)
>>> torch.angle(t)
tensor(3.1416)
>>> t1 = torch.tensor(-1 - 0.j)
>>> t1
tensor(-1.+0.j)
>>> torch.angle(t1)
tensor(3.1416)
```

**C++ Snippet**
```c++
#include <iostream>
#include <complex>
 
int main() 
{
    std::complex<double> z(-1, 0); 
    std::cout << "phase angle of " << z << " is " << std::arg(z) << '\n';
 
    std::complex<double> z2(-1, -0.0); 
    std::cout << "phase angle of " << z2 << " (the other side of the cut) is "
              << std::arg(z2) << '\n';
}
```

Output
```
phase angle of (-1,0) is 3.14159
phase angle of (-1,-0) (the other side of the cut) is -3.14159
```

**Note**: Pytorch's behavior is consistent with Numpy.

```python
>>> import numpy as np
>>> a = np.array(-1 + 0.j)
>>> a
array(-1.+0.j)
>>> np.angle(a)
3.141592653589793
>>> a1 = np.array(-1 - 0.j)
>>> np.angle(a1)
3.141592653589793
```

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by mruberry** [comment]
How does Python handle these values?

**Comment by kshitij12345** [comment]
Even python treats them as equal.
```python
>>> complex(0, -0) == complex(0, 0)
True
```

**Comment by gchanan** [comment]
I don't think the question of whether the two complex numbers equal-evaluate to true is the same as whether the angle should be positive or negative.

For example, consider `arctan2` which doesn't involve complex numbers:
```
>>>  np.arctan2(-0,-1)
3.141592653589793
>>> torch.atan2(torch.tensor(-0.), torch.tensor(-1.))
tensor(-3.1416)
```

**Comment by gchanan** [comment]
Here's another example where this type of argument doesn't hold:

`0.` and `-0.` evaluate-equal in python:
```
>>> 0. == -0.
True
```

but the division results are different:

```
>>> np.divide(-0., -1.)
0.0
>>> np.divide(0., -1.)
-0.0
```

**Comment by mruberry** [comment]
In Python:

```
cmath.phase(complex(-1, 0.))
: 3.141592653589793

cmath.phase(complex(-1, -0.))
: -3.141592653589793
```

Which appears to be consistent with C++.

**Comment by mruberry** [comment]
I updated the title of this issue to be more specific. I think we should be consistent with Python and C++ here. We should also make a note to improve our testing of -0.

@kshitij12345 Would you also file an issue with NumPy for their angle implementation being inconsistent with C++ and Python and link that issue here?

**Comment by kshitij12345** [comment]
Sure!

**Comment by WarrenWeckesser** [comment]
When you test these functions, be careful that the input value is what you think it is.  For example, Python evaluates the expression  `-1 - 0j` to `(-1+0j)`:
```
In [114]: -1 - 0.j                                                                                                                
Out[114]: (-1+0j) 
```
To make the imaginary part `-0.0`, use `-0j - 1` or `complex(-1, -0.0)`:
```
In [118]: -0j - 1                                                                                                                 
Out[118]: (-1-0j)

In [119]: complex(-1, -0.0)                                                                                                       
Out[119]: (-1-0j)
```
Note that you must use `-0.0` in the last example, and not `-0`, because `-0` is an integer, and Python doesn't have a negative integer zero.

With the correct input, `np.angle` gives the expected value:
```
In [120]: np.angle(complex(-1, -0.0))                                                                                             
Out[120]: -3.141592653589793
```
The earlier example with `np.arctan2` used `-0`, which is the same as `0`, so `np.arctan2(-0, -1)` returned `3.141592653589793`.  If the input argument is the floating point negative 0, the return values is `-3.141592653589793`:
```
In [121]: np.arctan2(-0.0, -1)                                                                                                    
Out[121]: -3.141592653589793
```

**Comment by kshitij12345** [comment]
@WarrenWeckesser Thank you for correcting us.

I can verify with `-0.` both numpy.angle and torch.angle behave as expected.

```python
>>> np.angle(complex(-1, -0))
3.141592653589793
>>> np.angle(complex(-1, -0.))
-3.141592653589793
>>>
>>> torch.angle(torch.tensor(complex(-1, -0)))
tensor(3.1416)
>>> torch.angle(torch.tensor(complex(-1, -0.)))
tensor(-3.1416)
```
