### ISSUE TITLE
CI report test failure when in fact there wasn't one

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#49901]
See: https://app.circleci.com/pipelines/github/pytorch/pytorch/255345/workflows/e02ff0a7-0117-4001-8615-e1dfbd132952/jobs/9870031

![circle screenshot](https://user-images.githubusercontent.com/3581352/103244267-525c8980-4911-11eb-9391-4efe4b2300c8.png)

The failed test was an in-lined stringify test case which is rigged to blow off CUDA assert and early terminate. However, it still reports as a test failure. 

Not sure how circle actually grabs the test failure summary page, but it might be good if we can improve the CI report to ignore these wrapped failures. 

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by ezyang** [comment]
I know what the problem is; `test_cuda_assert_should_stop_test_suite` internally uses TestCase to trigger the CUDA assert, but if you use TestCase, that will by default cause XML to be output, and then CircleCI is hoovering up the XML and reporting it as failed. I guess we can't make this stop using the test suite, so what you actually need to do is suppress the XML generation in this case.

**Comment by malfet** [comment]
@walterddr please note, that XML generation is controlled by `IN_CI` environment variable, which we can remove when subprocess is spawned
https://github.com/pytorch/pytorch/blob/05542f62220ab356358dbc9425ca4b005857f879/torch/testing/_internal/common_utils.py#L157-L159
