### ISSUE TITLE
pytorch_windows_vs2019_py36_cuda11.1_test1 intermittently fails

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#50051]
See this one for example:
https://app.circleci.com/pipelines/github/pytorch/pytorch/256070/workflows/f04f84fb-07ca-463a-87d4-dc8bf9f24a75/jobs/9911398

Please note, that it will most likely disappear after re-run

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by skyline75489** [comment]
I'm seeing `CUDA error: unspecified launch failure` and `cuDNN error: CUDNN_STATUS_NOT_INITIALIZED` on both Windows & Linux occasionally with `test_nn.py`. I'm using CUDA 10.2 & cuDNN 7.6.5, though.

**Comment by malfet** [comment]
@skyline75489 did you see it every time you start a test? Or in the middle of test execution?

**Comment by skyline75489** [comment]
About 3 out 10 times I’m seeing the error in the middle of test execution. But I don’t think this is the same error as you mentioned in the log. In that log no exception detail was printed. I’ve also seen this one locally, which is even harder to know why since absolutely no exception info can be used.

**Comment by malfet** [comment]
@skyline75489 is it possible to configure Windows to print some message in system log if process terminates with unhandled exception?

**Comment by skyline75489** [comment]
For C# & other CLR-based application, the unhandled exceptions will be logged in the event viewer. For Python I honestly have no idea. I'll need to take some to time to investigate this

**Comment by peterjc123** [comment]
https://docs.microsoft.com/en-us/cpp/cpp/unhandled-cpp-exceptions?view=msvc-160 Looks like MSVC provides a path for catching those unhandled exceptions.

**Comment by peterjc123** [comment]
Seems related: https://github.com/pytorch/pytorch/issues/49652 and resolved by https://github.com/pytorch/pytorch/pull/50164.
But I think it is better to add the terminate handler so that it will be better to debug those uncaught exceptions easily next time. My work is in #50320. What do you think, @malfet @ezyang ?
