### ISSUE TITLE
[bug] wrong result in torch.ge()

### ISSUE THREAD

**Issue by piaozhx** [pytorch/pytorch#5008]
- OS: ubuntu 16.04
- PyTorch version: 0.3.0.post4
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.3
- CUDA/cuDNN version: cuda8/ cudnn6

I think there exists bug in type-check of torch.ge() for example:
```
>>> a = torch.LongTensor([0,1]).cuda()
>>> b = torch.ge(a, 0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: torch.ge received an invalid combination of arguments - got (torch.cuda.LongTensor, float), but expected one of:
 * (torch.cuda.LongTensor tensor, int value)
      didn't match because some of the arguments have invalid types: (torch.cuda.LongTensor, float)
 * (torch.cuda.LongTensor tensor, torch.cuda.LongTensor other)
      didn't match because some of the arguments have invalid types: (torch.cuda.LongTensor, float)
 * (torch.cuda.LongTensor tensor, int value)
      didn't match because some of the arguments have invalid types: (torch.cuda.LongTensor, float)
 * (torch.cuda.LongTensor tensor, torch.cuda.LongTensor other)
      didn't match because some of the arguments have invalid types: (torch.cuda.LongTensor, float)
```

of course it throws a typeError because a is LongTensor.

but if a is Variable
```
>>> a = Variable(torch.LongTensor([0,1]).cuda())
>>> b = torch.ge(a, 0.5)
>>> b
Variable containing:
 1
 1
[torch.cuda.ByteTensor of size 2 (GPU 0)]
```

it works and give wrong result ?! maybe there are some bugs in type-check about Variable or something else.

**Comment by Stonesjtu** [comment]
I met another type related bug, which is much harder to debug:

```python
a = LongTensor([1,2])
b = Variable(a)
a / 0.3 # results in a FloatTensor
b / 0.3 # results in a LongTensor Variable
```

**Comment by SsnL** [comment]
@a367 The tensor variable inconsistency will be fixed when they become the same class. But giving the incorrect results is definitely problematic. Thanks for reporting this.

@Stonesjtu This will also be fixed when the two classes merge. But at the moment, actually outputs of your code is somewhat expected. Reduction ops on tensors gives numeric values. But on variables they give a numel=1 Variable (so that they can keep track of history and do autograd). `a.sum()` gives you python int 3, and then `3 * 0.3 = 0.9`. `b.sum()` gives you `Variable(LongTensor([3]))`, so multiplying by 0.3 gives you what you see.

**Comment by ailzhang** [comment]
This behavior mismatch is gone in master. I think we're good to close this issue.
