### ISSUE TITLE
Is there a way to create eye matrix that can be converted to onnx?

### ISSUE THREAD

**Issue by bes-dev** [pytorch/pytorch#50719]
I use eye matrix in my model, but when I try to convert the model to ONNX it fails because torch.eye(...) is not supported in 'opset 9'. Is there a way to create eye matrix that can be converted to onnx? Thanks in advance!

I tried different ways to create eye matrix such:
``` python
eye = torch.eye(size)
```
or
``` python
eye = torch.diag(torch.ones(len_s))
```
But both of these operations are not supported in 'opset 9'

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
We have support for `eye` type operator in ONNX: https://github.com/onnx/onnx/blob/master/docs/Operators.md#EyeLike

I think we have support for `torch.eye` in opset 9. See here: https://github.com/pytorch/pytorch/blob/aeefe2ce31cac554d48de1372eb426dcf4a3a301/torch/onnx/symbolic_opset9.py#L1731

What exact error are you seeing when exporting these ops? Also what version of PyTorch are you using? Can you share some repro code?

**Comment by BowenBao** [comment]
Hi @bes-dev ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
