### ISSUE TITLE
nan comparision for complex numbers

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#50749]
Currently, the complex number comparison is done by comparing real and imaginary separately. This is not always correct, because, for example, for `x = -inf+nanj`, on CUDA 11.2, `asin(x) = nan-infj` and on gcc 10.2, `asin(x) = nan+infj`. They are both correct and I don't think one is more correct than the other. However, this way of comparing causes two test failures on my machine:
```
FAILED test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_asin_cuda_complex128 - AssertionError: False is not true : Scalars failed to compare as equal! Comparing the imaginary part -inf and inf gives a difference of inf, but the allowed difference...
FAILED test/test_unary_ufuncs.py::TestUnaryUfuncsCUDA::test_reference_numerics_asin_cuda_complex64 - AssertionError: False is not true : Scalars failed to compare as equal! Comparing the imaginary part -inf and inf gives a difference of inf, but the allowed difference ...
```

In https://github.com/pytorch/pytorch/pull/50550, I relaxed the nan comparison at `test_unary_ufuncs.py` to
> as long as any of the real or imag is nan, then the whole number is considered as nan and considered as equal. That is `nan + 2j == 3 + nan j`.

However, as @ngimel pointed out in https://github.com/pytorch/pytorch/pull/50550#issuecomment-761905289, this is too relaxed  to make the whole `test_unary_ufuncs.py` compare `nan`s in the relaxed mode. So we need a more detailed plan about relaxed comparison and where should it be used. And this issue is for the purpose of this discussion.

cc: @mruberry 

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by mruberry** [comment]
This is an interesting issue because it involves several nontrivial concepts:

- complex NaN
- cross-platform consistency
- numerical correctness when multiple results are valid

Note that we consider any complex number with a NaN as NaN (see https://pytorch.org/docs/master/generated/torch.isnan.html?highlight=isnan#torch.isnan). 

For this particular issue we could say that "NaN is NaN," and give up on cross-platform consistency or numerical correctness beyond that.

Alternatively we could try to reconcile cross-platform differences. This comes up for functions that do not have unique solutions, too.

**Comment by ezyang** [comment]
One thing that would be good to mention here is how Numpy, e.g., handles these situations

**Comment by mruberry** [comment]
This appears to be the extent of NumPy's complex asin testing:

https://github.com/numpy/numpy/blob/3095b43db1831d876915bb581078e8d11c9febfb/numpy/core/tests/test_umath.py#L3064

In general they compare with Python or use reference values for validating mathematical operations. Python is much more likely to be consistent with a NumPy operation, however, because they're both on the CPU.

**Comment by mruberry** [comment]
For additional context, NumPy's np.testing.assert_allclose will say that NaN is close to NaN. PyTorch's allclose and isclose also do this:

https://github.com/pytorch/pytorch/blob/3f052ba07b2da4801d8f52f4116357760d5b632d/aten/src/ATen/native/TensorCompare.cpp#L24

In the context of our test suite, however, we decided to implement separate real and imaginary checks.

**Comment by zasdfgbnm** [comment]
So how do we deal with the failing tests? Do we want to somehow modify `test_unary_ufuncs.py` to fix the failing tests? For which op can we say "nan is nan" and consider different nans as the same?

**Comment by mruberry** [comment]
Having slept on this issue, I would like to propose:

- we focus on splitting test_reference_numerics into easy/hard/extremal versions of the test. Where easy uses "small" numbers within a function's domain, hard uses "large" numbers with a function's domain, and extremal tests the the extremal values.
- then we can consider a "NaNIsNaN" option where complex NaNs compare as equal in the test suite. This option could be added to our test suite comparison function.

Splitting test_reference_numerics is mentioned as an item in https://github.com/pytorch/pytorch/issues/50006. We could discuss the details of that split if someone is seriously interested in pursuing it.

**Comment by zasdfgbnm** [comment]
Splitting `test_reference_numerics` sounds like a big thing that is already in plan? Do we have to overlap the fixing of a failing test with that plan? Shouldn't fixing a failing test have higher priority, and should be done separately?

**Comment by mruberry** [comment]
> Splitting `test_reference_numerics` sounds like a big thing that is already in plan? Do we have to overlap the fixing of a failing test with that plan? Shouldn't fixing a failing test have higher priority, and should be done separately?

If this were an isolated case then probably, but we already have a ton of test_reference_numerics skips.
