### ISSUE TITLE
Implement torch.pow for float16 and bfloat16 on CPU

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#50789]
## 🚀 Feature
Add support for `torch.pow` with float16 and bfloat16 on CPU

## Motivation

Currently, these types are not supported.

```
>>> torch.rand(10, dtype=torch.float16).pow(1.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "pow" not implemented for 'Half'
>>> torch.rand(10, dtype=torch.bfloat16).pow(1.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "pow" not implemented for 'BFloat16'

```

float16 and bfloat16 are supported for CUDA, however:
```
>>> torch.rand(10, dtype=torch.float16, device='cuda').pow(1.5)
tensor([0.4597, 0.6592, 0.6777, 0.0105, 0.7349, 0.0492, 0.5186, 0.1809, 0.4202,
        0.3423], device='cuda:0', dtype=torch.float16)
>>> torch.rand(10, dtype=torch.bfloat16, device='cuda').pow(1.5)
tensor([5.7861e-02, 1.5234e-01, 8.7500e-01, 6.4373e-05, 7.0703e-01, 2.5977e-01,
        3.6133e-01, 6.7578e-01, 1.4648e-01, 8.4839e-03], device='cuda:0',
       dtype=torch.bfloat16)
```

**Comment by mruberry** [comment]
We would accept a PR adding this functionality.

**Comment by imaginary-person** [comment]
Hello @kurtamohler & @mruberry,

Please help me with a doubt regarding pow().

Please consider this small snippet of code:
```
t = torch.tensor([0.5], dtype=torch.float16, device='cpu')
t.pow(34554657676.0)
```
This would result in a Runtime overflow error with my implementation (essentially, merely I duplicated existing code) **as well as the existing implementation for CUDA**. I cast the exponent to `iter.common_dtype()` (which is the dtype in which the computations should be performed) when it's `float16` or `bfloat16`, which is why the overflow occurs.

Since the existing CUDA approach has similar behavior, please confirm if my corresponding approach for CPU is okay.

**Comment by imaginary-person** [comment]
Hello @mruberry, please advise if you or a partner were able to take a look at #50999, in order to determine if `pow_tensor_scalar_kernel` can be made concise without a redesign. Thank you!

**Comment by mruberry** [comment]
Hey @imaginary-person - thanks for the ping, and sorry I wasn't able to get back to you sooner! I'm still catching up from taking some time off. I've added this to my queue and will review ASAP! I appreciate your patience.

**Comment by imaginary-person** [comment]
No worries, @mruberry! Please review as per your convenience & feasibility. Thanks for your guidance so far!
