### ISSUE TITLE
count_nonzero: autograd internal assert failure

### ISSUE THREAD

**Issue by kernfel** [pytorch/pytorch#50792]
## 🐛 Bug

Calling `count_nonzero` on a tensor that `requires_grad` causes an error in autograd/functions/utils.h:64

## To Reproduce

```python
import torch
foo = torch.empty(5).requires_grad_()
foo.count_nonzero()
```
Output:
```
>>> foo.count_nonzero()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch.
```

## Expected behavior

Expected a count of non-zero elements, as I get when doing it under `torch.no_grad()` or on tensors that do not `requires_grad`.

## Environment

```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Pop!_OS 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro RTX 5000
Nvidia driver version: 455.38
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0
```

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer

**Comment by kernfel** [comment]
Related: #49235, #47851

**Comment by narain1** [comment]
I'm interested to know why would you like to do count zeros in the middle of the graph 🤔

**Comment by narain1** [comment]
you could detach and then count

**Comment by kernfel** [comment]
I'm not disputing that - I came across this during testing, and the workaround there is obvious and trivial. I could imagine use cases involving spiking neural networks where you'd actually want to do this online, but that's not the point here: I was merely following the instructions; `please report a bug to PyTorch` is fairly unambiguous.

**Comment by albanD** [comment]
Hi,

Thanks for the report!
Yes this is an issue with some of the formulas we have.
In partcular, we should fix [this](https://github.com/pytorch/pytorch/blob/1e0809dbf9f10158e2427ca1f5fccde59ffdf2d1/tools/autograd/derivatives.yaml#L360) one to set `  output_differentiability: [False]` instead of providing a formula. With the final entry looking like [this one](https://github.com/pytorch/pytorch/blob/1e0809dbf9f10158e2427ca1f5fccde59ffdf2d1/tools/autograd/derivatives.yaml#L517-L518).

@kernfel could you send a PR that does that change? And add a new entry in [this test](https://github.com/pytorch/pytorch/blob/1e0809dbf9f10158e2427ca1f5fccde59ffdf2d1/test/test_autograd.py#L4875) to make sure that it does not raise the error and properly return a result that does not require gradients.

**Comment by kernfel** [comment]
@narain1 was faster, cheers!
