### ISSUE TITLE
{**dict} syntax for TorchScript results in inscrutable error message

### ISSUE THREAD

**Issue by gibiansky** [pytorch/pytorch#50821]
## 🐛 Bug

```
class A(torch.nn.Module):
    @torch.jit.export
    def test(self):
        s= {"hello": None}
        return {**s}
        
torch.jit.script(A())
```

Instead of gracefully telling you that `{**s}` is unsupported by TorchScript, you get a very confusing error message:

```
torch/jit/frontend.py in __init__(self, ctx, offending_node, reason)
    109         node_type = type(offending_node)
    110         range_len = len(node_start_tokens.get(node_type, ' '))
--> 111         source_range = ctx.make_range(offending_node.lineno,
    112                                       offending_node.col_offset,
    113                                       offending_node.col_offset + range_len)

AttributeError: 'NoneType' object has no attribute 'lineno'
```

## Expected behavior

Either this works or gives a clearer error message.

## Environment

Inside fbcode.

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
This is because expanding dictionary like `{**dict}` results in an irregular ast. 

Specifically, at:
https://github.com/pytorch/pytorch/blob/19358808604129573dba354558ca4019acf2503f/torch/jit/frontend.py#L776

`expr.keys` is `None`, which results in the referenced error. 

We should handle this special case and add a check there to get a clear error for this special case.

**Comment by gmagogsfm** [comment]
@ansley Ansley, do you have bandwidth to work out a quick fix for this?
