### ISSUE TITLE
Typing not preserved on reassignment

### ISSUE THREAD

**Issue by ansley** [pytorch/pytorch#51023]
## 🐛 Bug

Type annotations aren't preserved on variable reassignment. It seems unintuitive to me that we would throw here:

```python
@torch.jit.script
def fn():
    x: int = "foo"
    return x
```

...but not here:

```python
@torch.jit.script
def fn():
    x: int = 1
    x = "foo"
    return x
```

FWIW, `mypy` doesn't accept either example.

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Note: Though mypy doesn't accept this example, vanilla Python actually does allow this.

**Comment by ansley** [comment]
To add on to what @gmagogsfm mentioned above, the Python runtime never enforces type annotations. `typing` is used by third party tools like type checkers, IDEs, linters, etc.

**Comment by gmagogsfm** [comment]
Did some more investigation, and found a few interesting things:

1) There seems to be a bug here:
https://github.com/pytorch/pytorch/blob/f7e90cf31129163e31ee8bcbd37f54e7f9ddc39c/torch/csrc/jit/frontend/ir_emitter.cpp#L399

When `annotate_type` is `null`, `as_simple_value`'s type would be used to check against itself in the next few lines. This would always be true. 

2) If I am understanding this correctly, we should use previous `annotate_type` for type checking there. However, it is impossible to get the accurate `annotate_type` at this point, the best we could manage is the value types of previous assignments, which are narrower sub-types of original `annotate_type`. So we can't use them for type-checking here either.

3) The example given in this bug report passes compilation time type check because of reasons 1). It also passes runtime type check, because TorchScript identifies that the two assignments are WAW, thus first assignment is removed as dead code. Resulting IR only has the second assignment with `StringType`, thus not triggering any error.

How to fix:
Given that it is difficult to perform proper type checking in frontend lowering, maybe it is better to insert a pass that validates types for assignments before DCE so that we can catch cases like this.

**Comment by gmagogsfm** [comment]
@eellison suggested we keep the behavior as is, for a few reasons:

1) Changing it would break existing user models
2) Many other Python type checkers allow this as well, even MyPy can allow this if user flips a flag [[more info](https://github.com/python/mypy/issues/1174#issuecomment-209465957)]

So we think it's best if we don't change it for now. Other than fixing the bug discovered in #1 of my last comment.
