### ISSUE TITLE
[JIT] Value for torch.device argument not passed correctly to scripted function

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#51098]
## 🐛 Bug

Strings passed for `torch.device` type arguments appear to be ignored.

## To Reproduce
```
@torch.jit.script
def gn(d: torch.device):
    print(d)

print(gn("test"))
```
### Actual Output
```
opencl:0
```
### Expected Output
Probably an error that says that `test` is not a valid device. This is what is printed when the line `if d == "awesome_device"` is added:
```
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, msnpu, xla, vulkan device type at start of device string: awesome_device
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @gmagogsfm

**Comment by gmagogsfm** [comment]
Superficially the bug is here:
https://github.com/pytorch/pytorch/blob/2de4ecd4ebc99d509b8f13ff12ed241c7433a0ad/torch/csrc/jit/python/pybind_utils.cpp#L76

It tries to convert a `py::handle` to an IValue with the help of type information from IR (which says `device`). But the code doesn't check if `py::handle` is actually corresponding C++ type for device, thus resulting in random behavior. 

We could just treat the symptom and add logic here to check for string and convert to correct device, but I am not entirely sure if that's the right thing to do. At the end of the day, `torch.Device` and `string` are two different types, the fact that we allow passing in string as a `torch.Device` seems ad-hoc to me.
