### ISSUE TITLE
[TorchScript Usability] Non-intuitive error message for class attributes

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#51139]
## Problem description

Test case: [test-class2.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-class2.py)

In this test case, a custom class defines a class attribute, which is not allowed. Instead of informing users that class attributes are not allowed, the error message is like this (treating the class attribute as an instance attribute):
```
RuntimeError: 
Tried to access nonexistent attribute or method 'name' of type '__torch__.MyClass'. Did you forget to initialize an attribute in __init__()?:
  File "test-class2.py", line 10
def fn(a: MyClass):
    return a.name
           ~~~~~~ <--- HERE
```

## Desired behavior

Could the error message inform users that custom classes could not define class attributes?

Related to #50444 

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Jotting down some notes on root cause and possible solutions.

TorchScript currently only supports instance attribute (like `self.a = 1`) but doesn't support class attribute (like `MyClass.name` in the example above). When seeing a class attribute, TorchScript decides to silently drop it and only errors out when it is being used. The problem is that, since TorchScript completely "forgets" about an attribute being a dropped class attribute, it generates an error message that make users think "why does TorchScript think there is no attribute called `name` when I cleared defined it". 

I think there are two potential ways to fix it:

The simpler way: Just change this error message to something like 
```
Tried to access nonexistent attribute or method 'name' of type '__torch__.MyClass'. Did you forget to initialize an attribute in __init__()? Or is it a class attribute, which isn't supported by TorchScript?
```

The harder way:
A `ClassType` instance models a user-defined Python class. It has a member called [`attributes_`](https://github.com/pytorch/pytorch/blob/409a76f72ceda78a78fe42edb7becd15fbf4282b/aten/src/ATen/core/jit_type.h#L2241) that tracks all attributes that TorchScript successfully compiled.

We can enhance `ClassType` to include another field called `dropped_class_attributes` that is essentially a vector of strings, each map to the name of a dropped class attribute. When generating the error message above, we should check whether the missing attribute is a member of `dropped_class_attributes`. If it is, then error message can be very specific and clear about what went wrong (class attribute not supported) and how to improve (make it an instance attribute).

In order to populate `dropped_class_attributes`:

1. TorchScript frontend should be enhanced to parse source code portion that defines class attributes somewhere near [here](https://github.com/pytorch/pytorch/blob/409a76f72ceda78a78fe42edb7becd15fbf4282b/torch/jit/_script.py#L70). Concretely, an array of strings should be produced here representing class attribute names.
2. [`_jit_script_class_compile`](https://github.com/pytorch/pytorch/blob/409a76f72ceda78a78fe42edb7becd15fbf4282b/torch/csrc/jit/python/script_init.cpp#L1489) should be enhanced to take an additional argument of class attribute names. Then the names should be used to set `dropped_class_attributes` in created `ClassType` instance [here](https://github.com/pytorch/pytorch/blob/409a76f72ceda78a78fe42edb7becd15fbf4282b/torch/csrc/jit/python/script_init.cpp#L1501).

**Comment by penguinwu** [comment]
I think the harder way is a better solution

**Comment by gmagogsfm** [comment]
Thanks @beningodfrey4 for the fix!
