### ISSUE TITLE
CUDA driver version is insufficient 

### ISSUE THREAD

**Issue by LucasColas** [pytorch/pytorch#51213]
## 🐛 Bug

Hello, I'm on Ubuntu 18.04. I use torch. Torch worked very well. Until today. I get this error : 

> cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:47

## To Reproduce

1.Be on Ubuntu 18.04.5
2.Install Torch
3. Use torch.jit.load()

`model_object = torch.jit.load("weights")`

## Expected behavior

I expected a return of a ScriptModule object.

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Ubuntu 18.04.5
 - How you installed PyTorch : with pip
 - Python version: 3.6.5
 - GPU models and configuration: AMD Raven
 

cc @jeffdaily @sunway513

**Comment by skyline75489** [comment]
The error message is crystal clear. What hardware/drive setup do u have? CUDA requires Nvidia GPU.

**Comment by jeffdaily** [comment]
I need more info.  Since you're using pip to install, I'm assuming you are using one of the ROCm nightly wheels?  Did you perform an update to your torch install such that the latest wheel was broken, but an earlier one was not?

Since you are using and AMD GPU, and the error is "CUDA", this indicates you installed torch for CUDA accidentally.  The ROCm and CUDA builds of pytorch are separate.  ROCm "masquerades" as CUDA -- all the public interfaces will use "cuda" for the device, but error messages will be "ROCm".  

This error tends to happen when pip installing other packages that list "torch" as a dependency.  For some reason, pip will pull the torch wheel from PyPI even if you have torch+rocm already installed.  The torch wheel from PyPI is built for CUDA only.

I suggest uninstalling torch and reinstalling from the ROCm nightly wheel to see if it resolves your issue.

**Comment by LucasColas** [comment]
I tried to reinstall. Same issue.

**Comment by edrozenberg** [comment]
Took a while to find the nightly wheels, now I know also :).

Try removing all pytorch installs (remove any pytorch os package, and remove any pip pytorch install for ex. `pip3 uninstall torch`). Then pip install the appropriate rocm wheel from https://download.pytorch.org/whl/nightly/torch_nightly.html

For ex. depending on your rocm version, one of these (latest as of today) if you're still on python3.6:
https://download.pytorch.org/whl/nightly/rocm3.10/torch-1.9.0.dev20210219%2Brocm3.10-cp36-cp36m-linux_x86_64.whl
https://download.pytorch.org/whl/nightly/rocm4.0.1/torch-1.9.0.dev20210219%2Brocm4.0.1-cp36-cp36m-linux_x86_64.whl
