### ISSUE TITLE
Is `torch.multiprocessing.spawn` compatible with `DataLoader`? 

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#51688]
## 📚 Documentation

Is `torch.multiprocessing.spawn` compatible with `DataLoader(num_workers)`? 

PyTorch-Lighting has produced a lot of content saying that `multiprocessing.spawn` isn't compatible with a multiprocessing `DataLoader`. For example:
https://youtu.be/a6_pY9WwqdQ?t=197
https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#distributed-data-parallel
https://github.com/PyTorchLightning/pytorch-lightning/pull/2029

Personally, I have been using `torch.multiprocessing.spawn` (in-place of `torch.distributed.launch`) to spawn workers. And each worker handled training for a model wrapped in `DistributedDataParallel`. Lastly, my approach involved each worker created a `DataLoader(num_workers=4)` for loading data. I haven't had any significant performance issues compared to my baseline performance without `multiprocessing`. 
 
With so much content from PyTorch-Lighting saying that `multiprocessing.spawn` and `DataLoader` are not compatible, I think it'd be helpful to either affirm or deny that in PyTorch docs. The contradictions online are confusing, and I think it'd be helpful to get some clarity. 

cc @SsnL @VitalyFedyunin @ejguan

**Comment by SeanNaren** [comment]
hey @PetrochukM!

I think this is less a PyTorch issue and something the Lightning team should investigate. 

I'll hijack this issue for now to make sure my thoughts are documented!

Forgive me since I wasn't there when the original DDP docs for Lightning were made and this caveat was introduced, but from working with DDP in a spawn setting vs using `Popen` like `torch.distributed.launch`, the main issue with spawn is the need to serialize all state objects. This becomes an issue when using functions defined at runtime like so:

https://gist.github.com/SeanNaren/f4a99235fc736a438637c31ee94f082f

To fix you just need to move `TestModel` outside of the main script. I also tested with multiple workers and it seems fine. The message in the Lightning Docs may be outdated or incorrect, and if thats the case we should update it ASAP!

**Comment by ejguan** [comment]
Closing the issue. Feel free to re-open it if needed.
