### ISSUE TITLE
JIT Module forward pre-hooks do not support default arguments

### ISSUE THREAD

**Issue by Lilyjjo** [pytorch/pytorch#51885]
## 🐛 Bug

Eager pre-hooks handle default arguments on a module's forward while TorchScript does not. The difficulty of supporting this arises from the need to type the arguments of the pre-hooks. Currently the inputs of pre-hooks are required to be typed to match the forward's inputs exactly, ignoring default arguments. 

```
class ModuleDefault(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input1: str, input2: str = 'default'): # Note default argument 
        return input1 + "-" + input2

def pre_hook_default(self, input: Tuple[str, str]) -> Tuple[str, str]: # currently required signature 
    return input

m_default = ModuleDefault()
m_default.register_forward_pre_hook(pre_hook_default)
m_default_s = torch.jit.script(m_default)

m_default("a") # works with eager, returns "a-default"
m_default_s("a") # doesn't work with script
```

Error: 
```
RuntimeError: pre_hook_default() Expected a value of type 'Tuple[str, str]' for argument 'input' but instead found type 'tuple'.
Position: 1
Value: ('a',)
Declaration: pre_hook_default(__torch__.ModuleDefault self, (str, str) input) -> ((str, str))
Cast error details: Object ('a',) had a different number of elements than type Tuple[str, str]
```

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
Ah, nice catch. Just brainstorming here but should we require that an argument of type `T` with a default valueson `forward` should be present in the signature in the pre-hook and hook typed as `Optional[T]`? Since we control the hook invocation code we can provide a value or `None` as appropriate based on how `Module.__call__` is invoked?

Once union types arrive, we can require the type of the input tuple to be the union of all possible tuple types accounting for default values of arguments to forward. In your example, it would be `Union[Tuple[str], Tuple[str, str]]`. UX for this is terrible though so we should probably infer the types of hooks based on that of `forward`.
