### ISSUE TITLE
Half precision convolution not working

### ISSUE THREAD

**Issue by eladhoffer** [pytorch/pytorch#520]
to reproduce
```python
import torch
import torch.nn as nn
from torch.autograd import Variable

x = Variable(torch.rand(1,3,100,100).cuda().half())
m = nn.Conv2d(3,16,5).cuda().half()

y = m(x)
```

Will result in:
`RuntimeError: CUDNN_STATUS_ARCH_MISMATCH`

**Comment by apaszke** [comment]
What's your GPU?

**Comment by eladhoffer** [comment]
TitanX Maxwell,  cuda 8.0

**Comment by ngimel** [comment]
In cudnn bindings convolution math type is inferred from input data type (and inferred to be equal to input data type):
https://github.com/pytorch/pytorch/blob/master/torch/csrc/cudnn/Conv.cpp#L353-L361
https://github.com/pytorch/pytorch/blob/master/tools/cwrap/plugins/CuDNNPlugin.py#L51
Math type for convolutions with half inputs and weights should be CUDNN_DATA_FLOAT because
1) computations with half math are not supported anywhere except Pascal and TX1
2) Even on Pascal, 6.1 cards have very low performance fp16 math
3) fp16 math comes with a set of accuracy problems
@colesbury

**Comment by eladhoffer** [comment]
Thanks. Seems like batchnorm fp16 support is still missing.
e.g:
```python
import torch
import torch.nn as nn
from torch.autograd import Variable
 
x = Variable(torch.rand(1,16,100,100).cuda().half())
bn = nn.BatchNorm2d(16).cuda().half()

y = bn(x)
```
will result in
```
<ipython-input-1-c9c578acf3d8> in <module>()
      7 bn = nn.BatchNorm2d(16).cuda().half()
      8 
----> 9 y = bn(x)

/home/ehoffer/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    200 
    201     def __call__(self, *input, **kwargs):
--> 202         result = self.forward(*input, **kwargs)
    203         for hook in self._forward_hooks.values():
    204             hook_result = hook(self, input, result)

/home/ehoffer/anaconda2/lib/python2.7/site-packages/torch/nn/modules/batchnorm.pyc in forward(self, input)
     41         return F.batch_norm(
     42             input, self.running_mean, self.running_var, self.weight, self.bias,
---> 43             self.training, self.momentum, self.eps)
     44 
     45     def __repr__(self):

/home/ehoffer/anaconda2/lib/python2.7/site-packages/torch/nn/functional.pyc in batch_norm(input, running_mean, running_var, weight, bias, training, momentum, eps)
    386     state = _functions.batchnorm.BatchNorm(
    387         running_mean, running_var, training, momentum, eps)
--> 388     return weight and state(input, weight, bias) or state(input)
    389 
    390 

/home/ehoffer/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/batchnorm.pyc in forward(self, input, weight, bias)
     37                 self._save_std, self.training, self.momentum, self.eps)
     38         else:
---> 39             backend = type2backend[type(input)]
     40             backend.BatchNormalization_updateOutput(
     41                 backend.library_state, input, output, weight, bias,

/home/ehoffer/anaconda2/lib/python2.7/site-packages/torch/_thnn/__init__.pyc in __getitem__(self, name)
     13 
     14     def __getitem__(self, name):
---> 15         return self.backends[name].load()
     16 
     17 

KeyError: <class 'torch.cuda.HalfTensor'>

```

**Comment by ngimel** [comment]
Ah, yes. fp16 support was removed from cudnn bn backend (because it still requires fp32 for parameters), and probably it is not properly routed to or not supported in nn backend. @colesbury? BTW, be careful with truncating bn params to 16 bits, in our experiments on wide resnets/cifar it cost ~ half a percent of accuracy, though there may be ways to overcome this.

**Comment by JohanVer** [comment]
Is there an update regarding this? Could you describe how to truncate the bn params?

**Comment by apaszke** [comment]
@JohanVer did you update PyTorch to a recent version? The snippet no longer raises an error for me

**Comment by JohanVer** [comment]
Thanks for the fast response. I installed the newest version over conda.
Just retried the above code snippet, it works indeed. Shouldn't it be possible to "half" a entire model like this: 
```
import torch
from torch.autograd import Variable
import torchvision

x = Variable(torch.rand(1, 16, 100, 100).cuda().half())
model = torchvision.models.resnet50().cuda().half()

y = model(x)
```
For this i get: CUDNN_STATUS_BAD_PARAM

**Comment by ngimel** [comment]
Your input size is wrong, models in torchvision expect specific input sizes. You can play around with the batch size, but number of channels and image size are fixed. When I change input size to (64,3,224,224) the snippet above does not return an error.
