### ISSUE TITLE
[TorchScript usability] More intuitive error message for type annotated `self`

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#52053]
## 🐛 Bug

Test case: [test-self-annotation.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-self-annotation.py)

When annotating type for `self`, got the following error message:
```
python test-self-annotation.py 
Traceback (most recent call last):
  File "test-self-annotation.py", line 5, in <module>
    class MyClass(object):
  File "test-self-annotation.py", line 6, in MyClass
    def __init__(self: MyClass, x: int):
NameError: name 'MyClass' is not defined
```

## Desired behavior

A better error message is to tell users that `self` should not be annotated, e.g.,

```
AnnotationError: type of `self` is automatically inferred,  please remove the type annotation on `self`
```

Related to #50444 

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
I think this is because "MyClass" is used inside its own implementation. TorchScript only adds a class type to class type registry after compiling it, thus this annotation is not resolved correctly. One way to fix it is:

```
class MyClass(object):
   def __init__(self: "MyClass", x: int):    # <--- use string literal of class name
      self.x = x
```

With that being said, this error message can still be improved to tell users that they can use this string-type trick.

**Comment by penguinwu** [comment]
In this particular case, I think we should tell users not to annotate type for `self`. MyPy follows the same rule and does not allow annotation of `self`.

**Comment by penguinwu** [comment]
Mypy allows annotation of `self`, the same example passes mypy type checking:
```
mypy test-self-annotation.py 
Success: no issues found in 1 source file
```

Having observe that I still think it is more user-friendly to prohibit annotation of self type (less typing and less chance of getting things wrong).

**Comment by mullachv** [comment]
Hi,
Can I take this on? Thank you,

**Comment by penguinwu** [comment]
@mullachv Thanks for helping out. Assigned to you.

**Comment by mullachv** [comment]
Hi @penguinwu 
Following is the behavior with standard `Python 3.8.5` as well, not just `TorchScript`:
```
(base) bad-examples % cat in_base.py 
class SecondClass(object):
    def __init__(self: SecondClass, x: int):
       self.x = x 

y = SecondClass(2)
print("Second: ", y.x)
(base) bad-examples % 
```
```
(base) bad-examples % python in_base.py
Traceback (most recent call last):
  File "in_base.py", line 1, in <module>
    class SecondClass(object):
  File "in_base.py", line 2, in SecondClass
    def __init__(self: SecondClass, x: int):
NameError: name 'SecondClass' is not defined
(base) bad-examples % 
```
```
(base) bad-examples % python --version
Python 3.8.5

```

And we are maintaining that the behavior in `TorchScript` needs to be made different from standard Python, if `self` is annotated. Am I right?

**Comment by penguinwu** [comment]
This fix does not change the fundamental behavior of TorchScript, where `def __init__(self: SecondClass, x:int)` would trigger an error in TorchScript. What this one fixes is the error message so that users encountering this error can take action to fix it. 

Instead of the current error message of:
```
NameError: name 'MyClass' is not defined
```

We suggest changing the error message to:
```
AnnotationError: TorchScript does not support type annotation of `self` using the class name. Since the type of self is automatically inferred,  you can either remove the type annotation on `self` or annotate it using the class-name in string quotation.
```

**Comment by ps-19** [comment]
@penguinwu mam i guess this is working completely fine:
https://github.com/ps-19/Competitive-Programming/blob/main/updated_test-self-annotation.py

**Comment by mostafaelhoushi** [comment]
I am trying to help fix this issue. 
So my understanding is that the error is triggered by Python rather than Torchscript. As @mullachv said, even if we are not using TorchScript at all, this:
```
class SecondClass(object):
    def __init__(self: SecondClass, x: int):
       self.x = x 

y = SecondClass(2)
print("Second: ", y.x)
```
throws an error. 

So our goal here is to make Torchscript catch the error before Python and throw a more meaningful message as @penguinwu mentioned?

**Comment by tugsbayasgalan** [comment]
I think it is sufficient for this task to modify the error message to be more meaningful when we are doing torch.jit.script.

**Comment by mostafaelhoushi** [comment]
I have been trying with the help of @tugsbayasgalan  to implement this task. But I am leaning towards that changing the error message may not be feasible:

1. The error message is thrown by the Python interpreter whether we use eager or scripted mode, whether we decorate `MyClass` with `torch.jit.script` or not. The error will also be thrown even if we don't `import torch` at all.
2. I have tried debugging using pdb as well as print statements. Debugging functions like `init_then_script` in `torch/jit/_script.py` did not help either.

I believe this issue is different from - for example - this issue https://github.com/pytorch/pytorch/issues/51135 where the error message only happens in scripted mode but not in eager mode.
