### ISSUE TITLE
Memory leak when implementing functionals

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#52140]
## 🐛 Bug

(pardon my posts from a few days back about memory leak, I'm in the middle of hunting memory leaks in my applications)
I extended PyTorch with `torch.autograd.Function` to write the gradient of some functionals (i.e. functions that receives other functions as their inputs), but I found a memory leak when there is a circular reference with the functionals.

## To Reproduce

```python
import torch

def functional(fcn, y0):
    params = fcn.__self__.parameters()  # assuming fcn is a method of `torch.nn.Module`
    return Functional.apply(fcn, y0, *params)  # NO_MEMLEAK_IF: params is an empty list

class Functional(torch.autograd.Function):
    @staticmethod
    def forward(ctx, fcn, y0, *params):
        y = fcn(y0)
        ctx.fcn = fcn  # NO_MEMLEAK_IF: removing this line, but fcn is needed in backward
        return y

class DummyModule(torch.nn.Module):
    def __init__(self, a):
        super().__init__()
        self.a = torch.nn.Parameter(a)
        x0 = torch.ones_like(a)
        xsol = functional(self.forward, x0)  # NO_MEMLEAK_IF: changing this line to self.forward(x0)
        self.xsol = xsol  # NO_MEMLEAK_IF: removing this line or using xsol.detach()

    def forward(self, x):
        return self.a * x

def test_functional():
    a = torch.ones((200000000,), dtype=torch.double, device=torch.device("cuda"))
    model = DummyModule(a)

for i in range(5):
    test_functional()
    torch.cuda.empty_cache()
    print("memory allocated:", float(torch.cuda.memory_allocated() / (1024 ** 2)), "MiB")
```

When I run the code above, I got

```
$ python memtest.py
memory allocated: 3052.0 MiB
memory allocated: 6104.0 MiB
memory allocated: 9156.0 MiB
Traceback (most recent call last):
  File "memtest.py", line 34, in <module>
    test_functional()
  File "memtest.py", line 31, in test_functional
    model = DummyModule(a)
  File "memtest.py", line 20, in __init__
    x0 = torch.ones_like(a)
RuntimeError: CUDA out of memory. Tried to allocate 1.49 GiB (GPU 0; 11.91 GiB total capacity; 10.43 GiB already allocated; 918.25 MiB free; 10.43 GiB reserved in total by PyTorch)
```

## Expected behavior

No memory leak should happen.

In the example code above, I put a comment `NO_MEMLEAK_IF` to indicate how to remove the memory leak.
Only one `NO_MEMLEAK_IF` should be followed to remove the leak.
However, the memory leak should not appear even if the code is like above.

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.0a0+4803eaf
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: TITAN X
 - Any other relevant information: -

## Additional context

I cannot do `ctx.save_for_backward(fcn)` because `fcn` is a method, not a tensor.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @jlin27 @mruberry

**Comment by albanD** [comment]
> pardon my posts from a few days back about memory leak, I'm in the middle of hunting memory leaks in my applications

No worries!
This one is clearly leaking with a nice repro, thanks a lot for making such a concise code example!

## Why this leaks

After looking into this, it is indeed, our fault, but based on the comment in the code, it is expected.
What happens here is that (each arrow is an owning reference). Let's call model the instance of DummyModule we created.
model.xsol -> xsol
xsol.grad_fn -> an instance of Functional (let's call it ctx)
ctx.fcn -> DummyModule.forward (bound version)
DummyModule.forward.__self__ -> model

So this is a nice ref cycle in python, so the gc should properly collect it.
But
https://github.com/pytorch/pytorch/blob/0de7a4582e4adb5a279925e7e6e2c2afdeba3cbd/torch/csrc/autograd/python_variable.cpp#L86-L99

We don't actually tell the gc that the Tensor owns a reference to the grad_fn. And so the gc does not detect this as a cycle and this leaks.

## Can we fix that?

Based on the comment there, a fix is most likely going to be tricky as just visiting the grad_fn will subtle consequences.
So maybe? But not sure.

## Could you avoid this?

There is something suspicious in your code sample: precomputing some differentiable thing and saving it for later:
```python
        xsol = functional(self.forward, x0)  # NO_MEMLEAK_IF: changing this line to self.forward(x0)
        self.xsol = xsol  # NO_MEMLEAK_IF: removing this line or using xsol.detach()
```
If you do this and do some backward calls in the for loop, then you will (almost always) run into the "the graph has already been freed" error. Because that part of the graph will be shared across multiple iterations.
So you should either make this non-differentiable or compute this in the forward. Note that both these things would remove the cycle here!

Another thing you might want to be careful about is about creating cycles in python in general.
Such cycles mean that the memory is only freed when the gc runs.
And the python gc is not running very often, and if you don't allocate a lot of ram, it basically never runs.
And cuda Tensors are very dangerous here because they don't use much ram but can use a lot of the GPU memory. This can lead to OOM on the GPU even though all the memory could be properly free by the python gc (we have some issues talking about this but I don't have the link handy).
So you might want to refactor your code to avoid such cycles anyways.

**Comment by mfkasim1** [comment]
Thanks for the comprehensive response, @albanD!

> There is something suspicious in your code sample: precomputing some differentiable thing and saving it for later

In my actual code, the `DummyModule` is not a `torch.nn.Module`, but just a general class in a scientific computing stuff, which might appear depending on the design choice.
For example, having the `functional` and `DummyModule` like below also leaks (and was my first design choice in my application, unaware of the leak):
```python
def functional(fcn, y0):
    params = [fcn.__self__.a]
    return Functional.apply(fcn, y0, *params)  # NO_MEMLEAK_IF: params is an empty list

class DummyModule(object):
    def __init__(self, a):
        self.a = a
        x0 = torch.ones_like(a)
        xsol = functional(self.function4functional, x0)  # NO_MEMLEAK_IF: changing this line to self.forward(x0)
        self.xsol = xsol  # NO_MEMLEAK_IF: removing this line or using xsol.detach()

    def function4functional(self, x):
        return self.a * x
```

> Another thing you might want to be careful about is about creating cycles in python in general.

Yes, I've just painfully realized this in the past few days.

> So you might want to refactor your code to avoid such cycles anyways.

Another thing that I just found out is if the function for the functional belongs to other class/object, the leak doesn't happen.
For example:

```python
class DummyModuleEngine(torch.nn.Module):
    def __init__(self, a):
        super().__init__()
        self.a = torch.nn.Parameter(a)

    def forward(self, x):
        return self.a * x

class DummyModule(torch.nn.Module):
    def __init__(self, a):
        super().__init__()
        self.engine = DummyModuleEngine(a)
        x0 = torch.ones_like(a)
        xsol = functional(self.engine.forward, x0)
        self.xsol = xsol
```

If it is hard to fix this, a warning message on the `torch.autograd.Function` page might be enough? (although we have to think what kind of simple message to illustrate the problem)

**Comment by albanD** [comment]
> Another thing that I just found out is if the function for the functional belongs to other class/object, the leak doesn't happen.

Yes anything that breaks the cycle here would work.

> If it is hard to fix this, a warning message on the torch.autograd.Function page might be enough? (although we have to think what kind of simple message to illustrate the problem)

cc @zou3519 who wrote that original comment. Maybe he has some ideas.
But from afar it doesn't look easy to fix indeed.
Adding an update in the doc sound useful though if we just show an example of a cycle (btw it should also mention the issue with a hook that reference the Tensor it is registered on).

**Comment by zou3519** [comment]
> cc @zou3519 who wrote that original comment. Maybe he has some ideas.
But from afar it doesn't look easy to fix indeed.

The comment and the PR that introduced it (#4437) were from a while ago so my memory is fuzzy. Here's some context:
- Initially, we did have some logic that would clean up refcycles using Python's GC
- However, it didn't work well (sometimes functions got randomly deallocated, but we only noticed this happening with DataParallel).

The specifics of that problem was:
- Python GC happens in two stages. Python's GC assumes that nothing changes between its two stages.
- PyTorch can perform operations without the GIL; it releases the GIL from time to time
- If PyTorch does something (change the refcount of the backward Function in this case) in between the two Python GC stages, then we have a problem.

Some potential fixes are:
- guard the access to `grad_fn` with acquiring the GIL. This seems difficult to do and potentially non-performant.
- inflate the refcount of `grad_fn` and lower it only when we can acquire the GIL. This could be easier but I don't have a clear picture of what it would look like.

I agree that the fixes don't look easy so a doc fix for now is the best way to proceed.

**Comment by albanD** [comment]
Note that this is actually fixed in master now that we're doing proper traversal of the attributes of the `ctx`.
This is still a ref-cycle though so you might need to add a `gc.collect()` before the `empty_cache()` call to make sure that everything is properly cleared.
