### ISSUE TITLE
`torch.load(..., weights_only=True)` currently raises a Deprecation warning + [proposal] `weights_only=True` should become default for safe legacy-loading pickles

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#52181]
That doesn't allow arbitrary unpickling and thus arbitrary code execution.  Maybe an option for torch.load?

Yes, one should not load/run code from unknown locations, but sometimes intermediate controls could be good: e.g. allowing to load only known types, such as tensors (and not model instances or other things), bypassing generic unpickling mechanism

+ maybe make it super-clear that torch.hub.load actually executes code at load/unpickling time

(i've long time been proponent of standardized formats for weight storage such as HDF5, but this didn't get traction)

cc @ezyang @gchanan @zou3519 @mruberry @nairbv @NicolasHug @vmoens @jdsgomes @bdhirsh @jbschlosser @anjali411 @ailzhang

Also, popularity of HuggingFace hub (and existing torch.hub) makes it more acute. At some point we will have a malicious model uploaded there and become popular on twitter e.g. because it would composite in very cute cats into existing images. The malicious model can at least hijack some precious GPU compute, and at worst take over institute / company local computer networks.

**Comment by rgommers** [comment]
+1 for building on standardized formats. Zarr may be nicer than HDF5 because it's better in cloud environments and it doesn't need such heavyweight libraries to support it.

The one interesting thing I noticed in https://pytorch.org/docs/stable/notes/serialization.html is that when saving multiple tensors together, their view relationships get preserved. That will require something a little custom perhaps.

**Comment by vadimkantorov** [comment]
advantages of HDF5: mature and has bindings for all languages; libhdf5 is relatively easy to compile from sources and doesn't have dependencies
disadvantages: it doesn't support number of columns more than 64000 (or didn't support a few years ago); relatively heavyweight; (but maybe better suited that abusing protobuf and its constant warnings about unsupported files larger than 2Gb

**Comment by rgommers** [comment]
There also seems to be some confusion about what `save` and `load` are actually for. https://pytorch.org/docs/stable/hub.html has this example:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/98330/108770171-47f9ed00-755a-11eb-9ad6-c63dea6b3e51.png">

Local checkpointing makes perfect sense, and for that pickling is just fine. But pickling isn't guaranteed to be portable across Python versions, so shouldn't be used for publishing models for download like that.

> advantages of HDF5: mature and has bindings for all languages

Does this matter? The current use cases for `.pt` certainly are Python-only. If it's about binary storage for data exchange, that's a different thing than what `save` is meant for.

**Comment by vadimkantorov** [comment]
Exchange somewhat matters, since at times people would be re-implementing models, say, in TFv2 or whatever new flavor of JAX and want to consume older weights without relying on other framework as a dependency. I fought this a lot when consuming Caffe weights from PyTorch :( or TFv1 weights from PyTorch. I wish frameworks thought more of this interop :(

**Comment by rgommers** [comment]
Yes that makes sense. Data exchange certainly matters. But then you'd not want features like storing the state of modules, and preserving view relationships (or odd strides, etc.). You'd just want one or more tensors in a well-optimized and portable binary format. Import/export capability for both HDF5 and Zarr would be nice for that.

**Comment by KOLANICH** [comment]
>Local checkpointing makes perfect sense, and for that pickling is just fine.

No, it's not really. Imagine a proprietary app we don't trust running in a heavily sandboxed environment and an own app consuming the model produced by a proprietary app. In this case it would be a sandbox escape.

>But pickling isn't guaranteed to be portable across Python versions, so shouldn't be used for publishing models for download like that.

People will still use pickle if they had the opportunity, at least because it is the laziest possible solution of the problem of storage models and apps settings. No matter deprecated or not, if it works for them, they will use it. So the only sensible way, if we want to get rid of the insecurity at all, is to make it unusable for them, so either to make them a little less lazy, or let them go and trouble users of other frameworks ecosystems with their insecure code.

**Comment by rgommers** [comment]
> No, doesn't really. Imagine a proprietary app we don't trust running in a heavily sandboxed environment and an own app consuming the model produced by a proprietary app. In this case it would be a sandbox escape.

That example has nothing to do with local checkpointing. It's model exchange, for which indeed there is ONNX.

**Comment by vadimkantorov** [comment]
Well, these "local checkpoints" end up as weights files for all torchvision models... Whereas those could have used ONNX...

**Comment by rgommers** [comment]
> Well, these "local checkpoints" end up as weights files for all torchvision models... Whereas those could have used ONNX...

This still sounds confusing. "weights files" contain, I assume, **data**. ONNX is "neural network exchange" - it's for storing **models**. Pickling has yet again different tradeoffs, it can capture **state** for pytorch models in ways that ONNX cannot (even aside from ONNX's incompleteness - because ONNX has to work cross-library while picking can be pytorch-specific).

It looks to me to disentangle this, we need to clearly separate these three things.

**Comment by KOLANICH** [comment]
>it can capture state for pytorch models in ways that ONNX cannot

I guess it shouldn't capture whole any state, but only precisely defined subset of state that can be restored without any execution of any Turing-complete code (or that can be escallated to execution of Turing-complete code) stored within the "checkpoint" (and any Turing-complete code shouldn't be stored there). If someone has to store the Turing-complete code that must be executed within the data even for such cases, it means he is too lazy to implement the functionality properly. If one has no other choice than to do that, it feels like there is something is wrong with the system.

So, is there any real necessity ("it absolutely cannot be done without a Turing-complete deserialization even if we spent a year of full-time work on redesigning the code and written auxilary code that currently is not needed because `pickle` does that for us?") in using `pickle`s?

**Comment by rgommers** [comment]
@KOLANICH as I pointed out in my first comment, it's about things like _"when saving multiple tensors together, their view relationships get preserved"_. Turing completeness is besides the point. 

> even if we spent a year of full-time work on redesigning the code ...

You made your point, you dislike `pickle` a lot. These kind of engineering tradeoffs are for the PyTorch maintainers to make though. As I pointed out, there _are_ correct and useful ways of using pickle.  And PyTorch isn't alone in that - Python stdlib provides, pickle, and libraries like NumPy and scikit-learn use it as well. So I'd say it's unlikely that anyone will be willing to spend that much effort to design something new to replace _correct_ usage of pickling. 

That doesn't negate the point that `torch.hub` is doing something inappropriate here. That can hopefully be fixed.

**Comment by KOLANICH** [comment]
>Python stdlib provides, pickle, and libraries like NumPy and scikit-learn use it as well. So I'd say it's unlikely that anyone will be willing to spend that much effort to design something new to replace correct usage of pickling.

That made the pretrained models available in the Net (produced by some large corps BTW) completely useless without additional efforts about reverse engineering the pickle files to make sure that there is no backdoors within them.

> "when saving multiple tensors together, their view relationships get preserved".

I wonder how complex are the relations and if they really can be preserved, i.e. by keeping them in a JSON-like dict serialized into some serialization format for JSON-like dicts and restored with a custom code.

>These kind of engineering tradeoffs are for the PyTorch maintainers to make though.

I absolutely aggree. Just wanna know how much the task is complex and how much work it is. I also have created [a framework](https://github.com/KOLANICH-libs/urm.py) that may (or may not) simplify the task.

**Comment by rgommers** [comment]
When you pay attention to it, there's indeed a lot of `.pt`(`h`) files floating around. Just saw https://github.com/POSTECH-CVLab/PyTorch-StudioGAN coming by on Twitter - no warnings, and many people will just start downloading pickle files (they won't know or care about what `.pth` means).

I searched all repos for other formats and asked a few people. There's not much, only a couple of examples using HDF5 like https://github.com/pytorch/fairseq/blob/89a4d2bc70fd680c4768803d20707ef65df89b0f/examples/wav2vec/wav2vec_featurize.py#L95. And a set of issues and Discourse posts with discussions around correct usage through `h5py`.

> I also have created [a framework](https://github.com/KOLANICH-libs/urm.py) that may (or may not) simplify the task.

It looks like you're using JSON - that's not a great alternative, it'll be way too slow compared to binary formats.

> Just wanna know how much the task is complex and how much work it is.

Right now this isn't actionable, it needs deciding what to do first.

**Comment by vadimkantorov** [comment]
And PTH is extra-bad for https://github.com/pytorch/pytorch/issues/14864

**Comment by KOLANICH** [comment]
>It looks like you're using JSON - that's not a great alternative, it'll be way too slow compared to binary formats.

Not quite. The framework `urm` deals only with

* linking several unrelationally-stored data to each other and convenient access to the data
* storing them in cold and hot storages and transferring between them when needed.

For serialization it entirely relies on `transformerz` lib and a framework, allowing to specify a transformation chain. `json` is only one format within it, and can be easily replaced with CBOR or MSGPack or BSON (and CBOR and BSON have some customization points ([1](https://github.com/KOLANICH/kaitai_struct_formats/blob/cbor/serialization/cbor.ksy#L163L185), [2](https://github.com/kaitai-io/kaitai_struct_formats/blob/164d0a448a9142c830b3d1775ef550130adbcc17/serialization/bson.ksy#L105L113))), or an own transformer can be written and plugged there (also a compressor/decompressor).

>they won't know or care about what .pth means.

It was a big mistake to give the format an own extension. If it was given `.pytorch.pkl` extension, it would have been immediately obvious it is a `pickle` file.

TBH, I usually use TensorFlow (because it has built-in complex numbers). 

When I had to use one pretrained model, and it turned out the code is for pytorch, I have detected that the files are pickle only because I have large experience of dealing with python projects and know that when most of projects need to ship some data with code or serialize, they just rely on pickle instead of developing a format and serialization and parsing routines.

`pickle` is a large success in the sense it gives developers something they need at the cost of something they don't care, don't need and are willing to sacrifice. Unfortunately it turns out that the thing that is sacrificed is security, this transforms the landscape, and I see absolutely no reasons for rational data scientists not to register a bunch of fake accounts on GH, each new paper publish under a new account and embed legal backdoors (most of open source software licenses (except WTFPL) explicitly disclaim any liability, so by using software and data user authorizes software to scan his PC for unfinished drafts of articles and source code and other confidential information such as ssh keys and exfiltrate it) into each model (that's why really serious orgs allow their employees only use the software that was audited (internally or externally, there are corps having business on auditing dependencies for backdoors) ). I absolutely won't be surprised to hear that it is already done.

**Comment by turian** [comment]
I am currently organizing a NeuroIPS competition, in which participants might be submitting pytorch models to our evaluation server for the leaderboard.

**Is there a secure way of serializing/loading untrusted pytorch models?**

Are there alternatively to pickle, which can be insecure? Is there a pytorch model format we can insist upon that is secure?

I believe that ONNX + tensorflow use protobuf, which avoids the security issues of pickling. That's an alternative to HDF5 to consider

I see that this is related to #52596

**Comment by KOLANICH** [comment]
https://github.com/CensoredUsername/picklemagic may be helpful to implement an own loader for pth files in a controlled way.

**Comment by turian** [comment]
@KOLANICH thank you but that repo is five years old with a single contributor. It's hard to trust abandonware that might not even work with the latest pickle format.

**Comment by KOLANICH** [comment]
I have recently used it, not for pytorch files though. The stuff having date of this year hasn't worked, that library has.

**Comment by turian** [comment]
@KOLANICH have you used it recently?

**Comment by vadimkantorov** [comment]
Is PyTorch 1.9 Package feature still using unsafe pickle under the hood?

**Comment by rgommers** [comment]
yes indeed

**Comment by vadimkantorov** [comment]
:(

**Comment by ezyang** [comment]
A quick update here: it will take some care, but if we implement a custom Unpickler and override `find_class` to only allow certain types (example at https://github.com/facebookresearch/CrypTen/blob/main/crypten/common/serial.py ) we can provide a safe unpickler by default this way. And it's pretty easy to wire this up to torch.load; CrypTen is doing it in a bad way but it turns out you can do it a lot more simply

```
class safe_pickle:
    Unpickler = RestrictedUnpickler
    @staticmethod
    def load(f):
        return RestrictedUnpickler(f).load()
    
# Adapt torch.load to use RestrictedUnpickler - patched for torch.storage._load_from_bytes
def _safe_legacy_load(f):
    return torch.serialization._legacy_load(f, map_location=None, pickle_module=safe_pickle)
```

**Comment by KOLANICH** [comment]
What are the pros and cons of your approach of reusing `pickle.Unpickler` instead of implementing an own virtual machine, as existing packages for "secure unpickling" do?

**Comment by ezyang** [comment]
I think the difference here is mostly a matter of how much you trust the underlying cpickle implementation to be secure against malicious input. Within the Pickle VM, there are a very small number of instructions (two) which go through arbitrary calls, and these are all supposed to go through `find_class`. If you believe this reasoning, and you think the cpickle implementation doesn't have memory errors on malformed input (not a great assumption to make, although it's certainly easier to write a bytecode interpreter securely than it is to write a parser securely), then reusing cpickle ought to be fine.

**Comment by dzhulgakov** [comment]
We also have our own pickle implementation as part of torchscript (that powers `torch::load/save` in C++). It supports only subset of types (tensors/list/dict/tuple) but it should be sufficient for checkpoint loading. Have we evaluated this option? Maybe expose it as `torch.load(..., restricted_pickle=true)`. cc @gmagogsfm

Or does anybody want to land the `RestrictedUnpickler` approach ezyang suggested?

**Comment by dzhulgakov** [comment]
Another potential library for secure unpickling: https://github.com/trailofbits/fickling (also a custom virtual machine). Besides they had DEFCON talk last year specifically with examples of injecting stuff in PyTorch's pickle archives.

**Comment by KOLANICH** [comment]
I have tried it for analyzing some suspicious pickle, it hadn't worked, the opcode was not implemented. But a much older lib has worked better.

**Comment by vadimkantorov** [comment]
This is even more important now that people exchange "private" checkpoint files for various diffusion models :)

**Comment by sjkoelle** [comment]
We started using hdf5 for this after reading this thread.  Made sense to us and wasn't too much work to set up.

**Comment by vadimkantorov** [comment]
One more argument on practicality of HDF5 (tf uses hd5 for storing weights): https://mobile.twitter.com/carrigmat/status/1566795349573894145

**Comment by KOLANICH** [comment]
Can plain (non-pickle) numpy `npy` arrays be used instead of HDF? HDF is a complex format. And, BTW, why yet another format and why not adopting the simplest format that fits our needs that is already used in ML for storing models, i.e. [TFLite](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_v3.fbs) or ONNX?

**Comment by vadimkantorov** [comment]
For me, npy is worse than hdf5 because it's less exchange-ready for C++ world. For ONNX / other portable binary formats - I personally don't mind

**Comment by KOLANICH** [comment]
>it's less exchange-ready for C++ world

The `npy` format is damn simple, that's why I consider it more exchange-ready for C++ world - if one needs a small and simple lib and is not satisfied with the existing libs, one can easily reinvent an own wheel. One only needs some JSON-parsing lib to parse its header properly (after some string replacements the header becomes valid JSON).

**Comment by julien-c** [comment]
Yet another format™, but I also want to plug @narsil's prototype of `safetensors`: https://github.com/Narsil/safetensors

Slightly reformatted excerpt:

> The format is composed of:
> - a JSON utf-8 string representing the header.
>          The header is a dict like `{"TENSOR_NAME": {"dtype": "float16", "shape": [1, 16, 256], "offsets": (X, Y)}}`, where X and Y are the offsets in the byte buffer of the tensor data
> - Rest of the file: byte-buffer.

**Comment by KOLANICH** [comment]
BTW I have found the lib I have used, it is https://github.com/CensoredUsername/picklemagic

**Comment by dzhulgakov** [comment]
Another contender on the possible format is torchsnapshot. It's in the very early stages and mostly focuses on distributed model checkpointing, but it's rolling its own YAML-based format similar to safetensors above: https://github.com/pytorch/torchsnapshot/blob/main/torchsnapshot/manifest.py cc @yifuwang

**Comment by vadimkantorov** [comment]
Also, what may be good is to introduce some file extensions indicating the format and then having PyTorch enforce it. E.g. if there's a pth5 or .pt.h5 or sth similar, pytorch would actually assert that the contents is hdf5, and then the user could be sure it is safe, and that inside the file there is no legacy file and HF hub could verify safety in an easy way by allowing only this new extension

**Comment by vadimkantorov** [comment]
There's also another usecase of serialization: https://github.com/pytorch/pytorch/issues/73479#issuecomment-1248718946 (easy compact ascii-only serialization / deserialization for pasting tensor examples preserving coalesced-ness, transpose-bits and other attributes of example tensors)

**Comment by Narsil** [comment]
@vadimkantorov is there an exhaustive list of all possible tensors that might exist for PyTorch ?

Also for distributed settings, are we talking multi node (trying to minimize network) or multi process.
For the multiprocess, I'm considering options akin to `h5` (`h5` doesn't support `bfloat16` afaik). https://github.com/huggingface/safetensors/pull/6.
For multi-node, couldn't this sort of approach still work ? (With a master node having all the tensors/weights and distributing only tensor parts through this lazy loading mecanism)

> If a new format is rolled, it would be good to also provide C-only and Python-only examples / libs of reading/writing it without having PyTorch as a dependency (for good citizen interop).

Amen ! I'll try to look at exporting C bindings too! 

Regardless of the new format that ends up being used, I feel like a security audit would be welcome. Arbitrary code execution is not the only form of attack on files.

**Comment by vadimkantorov** [comment]
> @vadimkantorov is there an exhaustive list of all possible tensors that might exist for PyTorch ?

no ideas :) someone from core pytorch team might be able to answer this, i'm not a team member

> Arbitrary code execution is not the only form of attack on files.

i wonder what's state-of-the-art of actually generating format parsers from a formal spec to ensure that generated C is safe

> Amen ! I'll try to look at exporting C bindings too!

also versioning needs to be baked in from the start. I think dlpack structures missed it in the beginning :(

> `h5` doesn't support `bfloat16` afaik

seems so, so maybe some hacks can be done for recording actual dtype and then doing reinterpret cast, but in case of non 16/32/64-bitwidth types, this would break, so some convention for "opaque" type support (akin to h5py) would be needed

**Comment by vadimkantorov** [comment]
Also, slide 16 in this deck from the official HDF group website (https://www.hdfgroup.org/wp-content/uploads/2020/10/tar2h5_V1.pdf) has some information about bf16 support in HDF5, marked as "future work":
```
Future Work: Mixed Precision Support in HDF5
• IEEE FP16
• Google BFloat16
• NVIDIA TensorFloat (TF32)
• AMD FP24
```

![image](https://user-images.githubusercontent.com/1041752/192558431-18f3c61b-bcd3-43c9-94ed-55db80bcfce1.png)

so probably authors of this deck "Gerd Heber (The HDF Group), Dawei Mu (NCSA), Volodymyr Kindratenko (NCSA)" could be contacted to get their perspective / timeline of adding of these dtypes to HDF5 and if users can define them before full support is official

**Comment by dzhulgakov** [comment]
Btw, I wanted to clarify that PyTorch's default format is actually a zip file where tensor storages are just binary uncompressed files on the side and pickle contains only metadata: https://github.com/huggingface/safetensors/issues/18 for more description and https://colab.research.google.com/drive/1DUoqwbmBTiDsTUggZsBJL8UIKv_AjKSa?usp=sharing for an example. It makes the existing format both lazy-loadable and mmappable with a bit of additional work. And as mentioned above torch.jit already has a minimal C++ pickle implementation for a "safe" subset.

**Comment by vadimkantorov** [comment]
@dzhulgakov If HDF5 to be also [supported by torch.save/load](https://twitter.com/ducha_aiki/status/1590236275990462465), then it'd also fix the interop by itself. For that, I'd guess one would need to map more python types to HDF5 datasets (usually is fine for python scalars, strings, arrays, dicts; but will require some mapping for sparse pytorch arrays, preferrably just dumping the internal representation as is but maybe including some meta information in array names or in a separate field). I'm not very sure, it's not needed, but it might also provide natively mmap-loading/rewriting of a given array slice and some native compression.

**Comment by vadimkantorov** [comment]
Related on safetensors: https://mobile.twitter.com/narsilou/status/1590640997431939072

**Comment by KOLANICH** [comment]
>i wonder what's state-of-the-art of actually generating format parsers from a formal spec to ensure that generated C is safe

Kaitai Struct has a Rust target (C++ target is also present, and is thought to be secure, but I'm not sure anyone has really checked it,  C target is very immature, and none of the targets (except of Java one to some minor extent) support serialization currently).

**Comment by vadimkantorov** [comment]
Might be good to have safe mode default for pytorch 2.0

**Comment by vadimkantorov** [comment]
Is weights_only=True default in PyTorch 2.0 now?

**Comment by sjkoelle** [comment]
Putting in a request for weights_only=True support for OrderedDict 's

**Comment by ezyang** [comment]
Adding typing.OrderedDict to the allowed list shouldn't be too hard. Send us a patch?

**Comment by vadimkantorov** [comment]
@malfet using `weights_only=True` gives an ungentle error: "TypedStorage is deprecated" (please see https://github.com/pytorch/pytorch/issues/109108 for repro)

**Comment by vadimkantorov** [comment]
I hope that TorchServe loads models with `weights_only`: https://www.oligo.security/shelltorch

Otherwise, one untrusted model can gain access to the server (e.g. one team's model can steal some private data from another team's model)

**Comment by julien-c** [comment]
also quite in favor of something like this^

**Comment by vadimkantorov** [comment]
give the recent popularity of "backdoor" theme in general, hoping `weights_only=True` can become default and an audit of all unsafe pickle.load in all pytorch codebase can be done :)

**Comment by Jannat20242NSU** [comment]
When I tried to upload the pickle file in the hf space for my ensemble model on prediction, it shows hf picklescan error. Can you provide any solutions?

joblib
gradio==4.44.1
huggingface_hub
scikit-learn==1.2.2
seaborn
matplotlib
lightgbm
xgboost
numpy
pandas

This is my requirements.txt file

**Comment by mikaylagawarecki** [comment]
@Jannat20242NSU that looks like an issue that should be filed to the respective huggingface repository that shows the picklescan error

**Comment by mikaylagawarecki** [comment]
Closing as complete since `weights_only` default was flipped in https://github.com/pytorch/pytorch/pull/137602
