### ISSUE TITLE
Proposal: Possibly run python tests with verbose (-v) on CI

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#5240]
If a test segfaults, it's hard to determine which test it is because the output looks like:
![image](https://user-images.githubusercontent.com/5652049/36221597-90966bd6-118c-11e8-8a9c-a3cf321cfc79.png)

I can work on this if we think this is a good idea.

**Comment by ezyang** [comment]
Last time I asked @colesbury about this, he didn't want to because it adds a lot of scrolling. I also did some work to move the CI tests to `pytest` so that we can output XML status files, but (1) this is unlikely to help in case of segfault, and (2) you can't do this straightforwardly, because we run some test files multiple times with different environment variables, and the XML exporter isn't really set up to handle this case.

For the record, I am personally OK with just slapping `-v` on the tests and calling it a day.

**Comment by colesbury** [comment]
`-v` in the conbuild sounds good to me too

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/5259
