### ISSUE TITLE
Skip handle_r_to_c for torch.dot and torch.vdot in derivatives.yaml

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#52455]
Both `torch.dot` and `torch.vdot` require the input tensors to be of the same dtype, so we don't need to pass the derivative to `handle_r_to_c` [here](https://github.com/pytorch/pytorch/blob/c7a70eec1b1a8aaac1f5659f688cd625c4a67831/tools/autograd/derivatives.yaml#L411-L417).

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by 85ayush** [comment]
hello I would like to do this contribution, I am new to open source contribution, can you please guide me and I will give my 100%.

**Comment by imaginary-person** [comment]
Hello @85ayush, I think the PR I submitted on Feb 18 resolves this issue. However, if it turns out that it doesn't, or if Anjali or someone else from the PyTorch team would insist, then you can submit another PR to resolve this issue.

If #52474 indeed resolves this issue, then I think that the changes required in this issue are trivial even for a first issue, and that this issue was tagged as a `good first issue`  with the goal of introducing one to PyTorch's autograd implementation, as it served that particular purpose for me.

Until someone from the PyTorch team gets a chance to respond, if you already haven't, you might want to read the [Contribution guide](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md) regarding advice on debugging, etc.

**Comment by imaginary-person** [comment]
Hello @85ayush, Anjali has imported #52474, so this issue would be resolved by it.
Other issues with the tag `good first issue` are listed [here](https://github.com/pytorch/pytorch/labels/good%20first%20issue).
