### ISSUE TITLE
Pytorch inconsistent behavior for boundary checks

### ISSUE THREAD

**Issue by lazypanda1** [pytorch/pytorch#5248]
Hi,

I observe inconsistent behavior when running the Bernoulli distribution with invalid values (code snippets below). When I run it with input that is outside the expected range (`2.0` in this case) the `sample` function fails as expected, with this message:

```bash
python /home/torchtest.py
Traceback (most recent call last):
  File "/home/torchtest.py", line 9, in <module>
    print(b.sample())
  File "/home/pytorch/torch/distributions/bernoulli.py", line 75, in sample
    return torch.bernoulli(self.probs.expand(shape))
RuntimeError: invalid argument 1: must be >= 0 and <= 1 at /home/pytorch/aten/src/TH/THRandom.cpp:343
```

Code:
```Python
p = torch.Tensor([2.0])
b = torch.distributions.Bernoulli(p)
print(b.sample())
```

but the `log_prob` function does not fail and returns the following:
```bash
-15.9424
[torch.FloatTensor of size 1]
```

Code:
```Python
p = torch.Tensor([2.0])
b = torch.distributions.Bernoulli(p)
print(b.log_prob((torch.Tensor([0]))))
```
Is this expected? Shouldn't both functions (`sample` and `log_prob`) fail with the same error?

**Comment by apaszke** [comment]
cc: @fritzo @neerajprad 
I don't think we've considered this scenario during our meetings

**Comment by neerajprad** [comment]
We are not validating arguments provided to the distribution constructors, as far as I know. The `sample` call fails because `torch.bernoulli` internally does a validation check of the arguments, which `log_prob` does not need to. To prevent such differences in behavior, we could add a validation check for distribution parameters in the constructor for all distributions. If there is a significant performance impact, we could also support a mode that skips these checks. What do you think?

**Comment by apaszke** [comment]
I have mixed feelings. On one hand we're ok with paying the performance penalty in `log_prob`, on the other hand, putting those checks everywhere seems kinda expensive.

**Comment by fritzo** [comment]
I think the `.__init__()` method would be the right place for these checks if we decide to perform them consistently, but I worry that this would cause significant performance overhead, especially since we consider distributions to be flyweight objects that merely wrap methods. Maybe we could add a new method `.validate()` to do this expensive validation logic?

**Comment by neerajprad** [comment]
I also think that the right place for these validation checks should be the constructor, so that any penalty is paid once and not multiple times as we call `sample` or `log_prob` on the same instance. This also ensures that we fail fast, and prevents ad-hoc behavior like this that results from shifting the onus of argument validation to the underlying sampler. Adding a `validate=False` argument to the constructor (or a separate `.validate()` method) might be a reasonable step forward, given that performance impact could be non trivial for large tensors.

**Comment by lazypanda1** [comment]
Like @neerajprad mentioned, I think it would be useful to have an optional debug flag which, when set, would cause pytorch to check for boundary conditions for all distributions instead of having checks for individual distributions. Tensorflow has a similar flag, [validate_args](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/distributions/Bernoulli#validate_args), which is an optional argument for all distributions. Also, it seems like torch already has some of these checks in place for some distributions(may not be all). I would be happy to contribute the feature and the test cases, if this proposal sounds reasonable. Any suggestions on how to proceed?

**Comment by fritzo** [comment]
@lazypanda1 Sure, I think an argument `validate_args=False` make sense. You can even add a generic test to tests/test_distributions.py
```py
class TestValidation(TestCase):
    def test_valid(self):
        for Dist, params in EXAMPLES:
            for i, param in enumerate(params):
                Dist(validate_args=True, **param)  # should not error

    def test_invalid(self):
        # this requires actual bad examples
```
This will ensure that all distributions take a `validate_args` argument. We may also want to add a `validate_args` argument to `Transform`s in a later PR.

**Comment by lazypanda1** [comment]
Should I print the tensor as well when the values are invalid?

**Comment by apaszke** [comment]
No, printing whole tensors is rarely a good idea. It takes up too much space

**Comment by fritzo** [comment]
@lazypanda1 It looks like @vishwakftw just started to add some validation logic in https://github.com/probtorch/pytorch/pull/133. If you'd like early code review, feel free to send a work-in-progress PR to probtorch/pytorch. We've been doing that for alot of the distributions PRs: first a review on probtorch/pytorch, then close that and open a final PR for review on pytorch/pytorch.
