### ISSUE TITLE
Pytorch changes the values assigned to it which causes problems.

### ISSUE THREAD

**Issue by Emmanuel357** [pytorch/pytorch#52560]
## 🐛 Bug

Pytorch changes the values you assign to it. Even if it is a small change, It leads to really different output than what the original value would have produced in my neural network. For example below:

## To Reproduce
```
a = [234678.5462495405945]
b = torch.tensor(a)
print(b.item())
```
output:
`234678.546875`

The small change pytorch made to my variable led to really different result in my neural network because my neural is very sensitive to small changes.

## Expected behavior
Pytorch should not make any changes to the variables.

cc @gchanan @mruberry

**Comment by vadimkantorov** [comment]
Does it work better if you replace the line by `b = torch.tensor(a, dtype = torch.float64)`? But maybe even for float32 this divergence is a bit too harsh

**Comment by aranganath** [comment]
So if you use a torch tensor without dtype, then it kind of rounds it off.

```a = [2.456778865432]  
b = torch.tensor(a)
b.item()  
2.4567787647247314
```
It works when you use the dtype:

```  
b = torch.tensor(a, dtype=torch.double)  
b.item()  
2.456778865432
```

**Comment by mruberry** [comment]
This is a little confusing, but it's by design.

The value you're creating a float32 tensor with is not representable in float32. You can see the same behavior when creating a NumPy array with the float32 dtype:

```
a = np.array(234678.5462495405945, dtype=np.float32)
a.item()
: 234678.546875
```

PyTorch's default floating point dtype is float32, which is why the tensor constructed here has the float32 dtype. The value would be more accurately represented in double, although not every value is representable in double, either.

Note that in NumPy the default floating point dtype is float64, so when a float array is created in NumPy without specifying a dtype it's float64.
