### ISSUE TITLE
Extend matmul to scalars

### ISSUE THREAD

**Issue by KolyaIvankov** [pytorch/pytorch#52623]
## 🚀 Feature

It is logical to extend `matmul` function to the case when at least one of the multipliers is a scalar value.

In one of the functions I've made for my project I have tensors of variable dimensions, which sometimes take dimension 0. Normally one would expect that one of the tensors will be multiplied by a scalar. Instead, I get an exception.
```
RuntimeError: both arguments to matmul need to be at least 1D, but they are 0D and 0D
```
This means that, in order to be able to multiply one or two occasional scalars, I have to do some magic. The most elegant way I've found is like that
```
def mymul(tensor: torch.Tensor, other: torch.Tensor):
    mul = torch.matmul
    if tensor.dim() == 0 or other.dim() == 0:
        mul = torch.mul
    return mul(tensor, other)
```
the actual code is more verbose, of course, and does other things. But, mathematically speaking, multiplication by a scalar is a matrix multiplication over a virtual dimension of size 0. And practically speaking - just why not?

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @rgommers

**Comment by gchanan** [comment]
NumPy doesn't do this, and it's reasonable as what you are asking for is not matrix multiplication.

You could potentially do it with a lot of restrictions, similar to 1-D matrices are treated (and the rule for removing dimensions no longer makes sense):
```
If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.

If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.
```

**Comment by mruberry** [comment]
Following what @gchanan wrote, while I appreciate it would have been helpful to implement this functionality in your application, the workaround you've written seems straightforward, and I'm not sure this change would be intuitive for most users. That is, if we asked most people what would happen when calling matmul with a 2D matrix and a scalar, would most users tell us that it would perform an elementwise multiplication of the matrix and the scalar? We'd also lose some error-checking surface where people might accidentally get into that state.

Absent this becoming an especially common pattern, I don't think we're likely to make this change, especially since the workaround is so simple.

**Comment by KolyaIvankov** [comment]
From a mathematical, physical and engineering point of view, matrix products, dot products, multiplication by scalars and the general `matmul` used in pytorch are cases of tensor convolution; since python tends to be less restrictive towards notation and function call than strongly typed languages, I would expect the scalars case to be covered, and surprised that numpy decided to treat this separately.

Anyway, I see that ONNX uses the numpy conventions, and adding this feature may cause compatibility problems - which, should I like it or not, are of higher priority.

Thank everyone for clarification!
