### ISSUE TITLE
Using TensorpipeAgent for inter-node communication

### ISSUE THREAD

**Issue by nick-furry** [pytorch/pytorch#52706]
## 🚀 Feature
Ability to receive data using TensorpipeAgent (https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/tensorpipe_agent.cpp) method

## Motivation

I would like to use Tensorpipe as a transport layer for data between different nodes (C++ program). Tensorpipe by itself doesn't perform rendezvous between nodes so I wanted to leverage existing PyTorch code to achieve my task. I came across TensorpipeAgent, linked above, that provides critical infrastructure i.e. setting up rendezvous and initializing Tensorpipe listeners on each node. There is a `TensorPipeAgent::send(...)` method that I believe is used to send data to a particular node but I'm not clear as to how to receive the sent data on the destination node. There is neither any equivalent recv() method nor do I see any other method that has that functionality at least to my understanding.

## Pitch

It would be really helpful to have a receive method that can receive the data on the destination node using TensorpipeAgent.  

## Alternatives

Alternative would be to establish rendezvous using c10d::Store, somehow get the url's of all the connected nodes, and pass them to Tensorpipe objects. 

## Additional context
The following is the sample code snippet that I'm using to test out my theory:
```
    size_t world_size = atoi(getenv("SIZE"));
    size_t rank = atoi(getenv("RANK"));
    std::string serverAddress = getenv("ADDRESS"); //"127.0.0.1"
    float rpcTimeout = 30;

    c10::intrusive_ptr<c10d::Store> store = c10::make_intrusive<c10d::TCPStore>(
        serverAddress, 0, world_size, true, std::chrono::seconds(10));


    c10d::ProcessGroupGloo::Options options;
    options.devices.push_back(
        ::c10d::ProcessGroupGloo::createDeviceForHostname(serverAddress));

    // Initialize server rpc agent.
    auto pg = c10::make_intrusive<c10d::ProcessGroupGloo>(
        store, rank, world_size, options);

    std::shared_ptr<torch::distributed::rpc::RpcAgent> rpcAgent;
    
    torch::distributed::rpc::TensorPipeRpcBackendOptions opts(
        /*numWorkerThreads=*/std::max(16U, std::thread::hardware_concurrency()),
        /*transports=*/c10::nullopt,
        /*channels=*/c10::nullopt,
        /*rpc_timeout=*/rpcTimeout,
        /*init_method=*/"unused");

    rpcAgent = std::make_shared<torch::distributed::rpc::TensorPipeAgent>(
        store,
        "worker",
        rank,
        world_size,
        pg,
        opts,
        std::make_unique<torch::distributed::rpc::RequestCallbackNoPython>());

    rpcAgent->start();

    auto w_info = rpcAgent->getWorkerInfo(0);

    torch::Tensor tensor_data = torch::ones({2, 2});
    std::string msg_str = "test data";

    std::vector<char> payload_data(msg_str.begin(), msg_str.end());
    std::vector<torch::Tensor> tensor_vec;
    tensor_vec.push_back(tensor_data);

    torch::distributed::rpc::Message msg(std::move(payload_data),std::move(tensor_vec),
                                            torch::distributed::rpc::MessageType::SCRIPT_RREF_FETCH_CALL);

    auto f_msg = rpcAgent->send(w_info, std::move(msg), rpcTimeout);
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @lw @beauby @agolynski @SciPioneer @H-Huang @cbalioglu

**Comment by pritamdamania87** [comment]
The TensorPipeAgent currently serves as a backend for the RPC framework: https://pytorch.org/docs/stable/rpc.html. Currently, the RPC framework has an officially supported python API, but no C++ API yet. There is no explicit `recv` API since it is designed as an RPC framework where you call an RPC on a remote end and retrieve a result. 

With the python API typically you would write somme arbitrary python code that can be called remotely and use `https://pytorch.org/docs/stable/rpc.html#rref` to store state remotely if needed. The C++ TensorPipeAgent doesn't have the functionality yet to call arbitrary C++ code on the remote end.

Could you describe your use case a bit more in detail? For example, what does the receiver do with the Tensor received? One option would be to use the TensorPipe APIs (https://github.com/pytorch/tensorpipe) directly instead of going through the TensorPipeAgent which is built specifically for RPCs.

**Comment by nick-furry** [comment]
My use case is that I should be able to send data across nodes and use it to train network (no DDP, just run programs independently on different nodes for now but with data shuttling capacity). And all the work is in C++. My idea is to mimic what pytorch does for RPC calls since it's backend is written in C++.

Once I use the `send()` in TensorPipeAgent to send data, how do I trigger a callbackfunction or any method to notify the remote that data has been received.

**Comment by nick-furry** [comment]
Using TensorPipe API directly would be my next option. I need to do rendezvous and get the address of every node from the store before I can use TensorPipe. Since TensorPipeAgent already does all that I wanted to see if I can leverage existing code.

Or it could be the case that I'm over-complicating how to get address(es) of each node. In the above code snippet after I initialize TPC store and process group, is there a way to get all the address? I wasn't able to find any methods in them.

**Comment by mrshenli** [comment]
> 1. Is it possible at all to do RPC using TensorPipeAgent? If not, could you point me as to how PyTorch does it?

In theory, yes, but you will lose access to Distributed Autograd and RRef built on top of the comm Agent. Besides, `TensorPipeAgent::send` currently operates on `Message` data structure which is treated as an internal type today. Compared to the Python RPC APIs, test coverage on internal C++ APIs are very limited so there might be unknown gaps.  

> 2. Once I use the send() in TensorPipeAgent to send data, how do I trigger a callbackfunction or any other way to notify the remote that data has been received and then run my trainer?

As long as you pass the callback function to `TensorPipeAgent` ctor, `TensorPipe` will trigger it automatically on the receiver side using [its listener](https://github.com/pytorch/pytorch/blob/3489b4a7b8629ce53b0bc6a3cf6fdc6107edd070/torch/csrc/distributed/rpc/tensorpipe_agent.cpp#L577). However, the native callback function only processes existing types listed below. To customize it for your use case, you will need to create your own message type, callback function. And we might also need to have a better way to expose the lower-level C++ APIs. 

https://github.com/pytorch/pytorch/blob/3489b4a7b8629ce53b0bc6a3cf6fdc6107edd070/torch/csrc/distributed/rpc/message.h#L27-L90

cc @lw @H-Huang for comments on directly using Tensorpipe for comm + `c10d:Store` for rendezvous.

**Comment by lw** [comment]
As others already said, the TensorPipeAgent class (and the rest of the stack, such as RRefs, distributed autograd, ...) are intended to be used from Python and TorchScript, hence direct C++ usage is not in a good state. (Technically usable, I guess, but probably quite awkward).

If you want to use TensorPipe directly you'll need to take care of rendezvous. For "inspiration", the relevant parts of the TensorPipe agent that take care of rendezvous are the `guessAddress`, `collectNames` and `findWorkerURL` methods, and this piece of code: https://github.com/pytorch/pytorch/blob/27d04f291e99f93d772c43b40b53f3285c9c6172/torch/csrc/distributed/rpc/tensorpipe_agent.cpp#L553-L569

I may have some even simpler code to copy from: at some point I experimented with a ProcessGroup based on TensorPipe, which I've since abandoned but which re-implemented its own (very basic) rendezvous logic. It's not perfect, but it used to work. You can find the code here: https://gist.github.com/lw/63e7886db8ebfb9caec2f54154b3dbc2. A big disclaimer: that code is completely unsupported hence no guarantees of any kind.

**Comment by lw** [comment]
Let me also add another caveat: TensorPipe is a quite low-level library, and using it may not be straightforward. Some aspects of its behavior are "unusual" and may be hard to understand at first (for example the threading model). Unfortunately the documentation around it is severely lacking. I'd suggest to consider this as a last resort option.

**Comment by nick-furry** [comment]
Based on all your inputs, I've decided not to use TensorPipeAgent but instead try rendezvous using c10d::Store and Tensorpipe for transferring data between nodes. 

Thank you everyone.
