### ISSUE TITLE
CUDA (batched only?) det() can incorrectly have NaNs in output

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#52700]
Separated from https://github.com/pytorch/pytorch/issues/51930.

As reported by @rightaditya: "For certain tensors on CUDA, calling tensor.det() returns some nan values where it should return 0."

See original issue for more context, but let's keep all future discussion of this issue here.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
It's interesting that our testing didn't catch this issue. See

https://github.com/pytorch/pytorch/blob/1cddb27f397168755d45099a7d044e1da0bffa5b/test/test_linalg.py#L496

and 

https://github.com/pytorch/pytorch/blob/1cddb27f397168755d45099a7d044e1da0bffa5b/test/test_linalg.py#L5816

**Comment by ngimel** [comment]
It fails only for specific inputs.

**Comment by v0dro** [comment]
Looping over the input in parallel and replacing `NaN` with 0 is a pretty cheap operation compared to the cost of the determinant itself. Would that be a good way to solve this problem? If I remember, adding a new keyword argument to the function to conditionally check for `NaNs` is not an acceptable change due to backward compatibility issues.

**Comment by Lezcano** [comment]
This is currently fixed. See
https://github.com/pytorch/pytorch/blob/3afc802c5a5111b18b91bac973ea9f3d220530fa/aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp#L1748-L1760
