### ISSUE TITLE
Python 3.9 installs torch to a wrong version if git commit starts with '0'

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#52857]
## 🐛 Bug

Probably not a big issue, but an interesting one.

In python 3.9, when a torch git commit starts with '0', e.g. `0567988`, a `python setup.py install` would install it to a version of `1.9.0a0+567988` with the leading 0 removed.

A python warning message like this is printed

```
Building wheel torch-1.9.0a0+0567988
/usr/lib/python3.9/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.9.0a0+0567988' to '1.9.0a0+567988'
  warnings.warn(tmpl.format(**locals()))
```

The version in pip freeze is "wrong",

```
$ pip freeze | grep -i torch
torch==1.9.0a0+567988
```

but the version in `torch.__version__` is correct

```
$ python -c 'import torch; print(torch.__version__)'                    
1.9.0a0+0567988
```

Theoretically, this behavior will trigger with an odd of 1 in 16. 🤔

cc @malfet @seemethere @walterddr @albanD

**Comment by albanD** [comment]
cc @malfet what do you think should be the priority here?

**Comment by malfet** [comment]
Hmm, if I understand what is going on, it should be much more rare:  `0567988` is at some point is interpreted as number rather than string, but I guess this would only hold true for short hexadecimal hashes that do not contain hexadecimal digits. 
It potentially can get even weirder if all digits would be less than 8, because then it might potentially be interpreted as octal number (by C)

I think it's a low pri, but should be pretty easy to fix

**Comment by walterddr** [comment]
Good first time issue probably?

**Comment by malfet** [comment]
This is a way to reproduce the problem: `python3 -c "from setuptools.extern import packaging;print(packaging.version.Version('1.2.3+002345'))"`
Although https://www.python.org/dev/peps/pep-0440/#local-version-identifiers does not says anything about stripping leading zeros from the local version, so not sure what is going on.
