### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 3, 1, 7, 7], expected input[1, 64, 8, 64, 114] to have 3 channels, but got 64 channels instead

### ISSUE THREAD

**Issue by Darshcg** [pytorch/pytorch#53036]
Hi pytorch Team,

I am converting the Slowfast pytorch model to ONNX model using torch.onnx.export().
During Conversion, I am getting an error as: **RuntimeError: Given groups=1, weight of size [64, 3, 1, 7, 7], expected input[1, 64, 8, 64, 114] to have 3 channels, but got 64 channels instead**.
Having said that, the pytorch model Inference is working fine, but do no why it is throwing above error during .pt to .onnx conversion.

Can you please assist me to solve this error? Would be a great help from yourside.

**Environment**:
Pytorch version: 1.6.0
Torchvision: 0.7.0
ONNX version: 1.7.0

One Note: Model is Slowfast. The input shape is: input0: (1,3,8,256,455), input1: (1,3,32,256,455). input0 is Slow pathway, and input1 is Fast pathway.

Thanks,
Darshan

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
Hi @Darshcg can you reproduce the issue on the latest PyTorch nightly?
If so can you please provide some code we can copy-paste to reproduce the issue?

**Comment by shubhambhokare1** [comment]
Hi @Darshcg

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
