### ISSUE TITLE
[nnc] Uneven split w/ tail + reorder causes a segfault

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#53092]
As demonstrated in the SplitUnevenReorder test case in #53091.  I haven't debugged this at all yet, but the loop structure of split with tail might be confusing to the reorder pass.

**Comment by navahgar** [comment]
The problem here is not the reorder. It is actually the call to `getLoopStmtsFor` that is called after `splitWithTail` here (https://github.com/pytorch/pytorch/blob/master/test/cpp/tensorexpr/test_loopnest.cpp#L3852).

For uneven splits, a tail loop is added. So, the code after `splitWithTail` looks like the following:
```
{
  for (int n_outer = 0; n_outer < (100 - 0) / 8; n_outer++) {
    for (int n_inner = 0; n_inner < 8; n_inner++) {
      b[n_outer * 8 + n_inner] = float(0);
      for (int m = 0; m < 76; m++) {
        b[n_outer * 8 + n_inner] = ReduceOp((b[n_outer * 8 + n_inner]) + (a[m, n_outer * 8 + n_inner]), reduce_args={m});
      }
    }
  }
  for (int n_tail = 0; n_tail < (100 - 0) % 8; n_tail++) {
    b[n_tail + ((100 - 0) / 8) * 8] = float(0);
    for (int m = 0; m < 76; m++) {
      b[n_tail + ((100 - 0) / 8) * 8] = ReduceOp((b[n_tail + ((100 - 0) / 8) * 8]) + (a[m, n_tail + ((100 - 0) / 8) * 8]), reduce_args={m});
    }
  }
}
```

Now, `getLoopStmtsFor` looks up the writes to the buf, and when there are multiple writes to the same buffer it returns their shared parent, which is not a loop in this case. Hence the error.

**Comment by bertmaher** [comment]
I mean, this still seems broken.  It leaves you with no way to reorder after a split.

**Comment by navahgar** [comment]
> I mean, this still seems broken. It leaves you with no way to reorder after a split.

Oh yeah, totally. I didn't mean to say the test case is wrong. You are right that there is currently no way to do this. 

We have to fix the `getLoopStmtsFor` API in order to do this.
