### ISSUE TITLE
DISABLED test_qr_square_many_batched_complex_cuda (__main__.TestAutogradDeviceTypeCUDA)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53184]
see also #51552

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by IvanYashchuk** [comment]
"square_many_batched" was part of old generated tests and tested input of shape `(3, 2, 5, 5)`:
https://github.com/pytorch/pytorch/blob/e0495a7aa104471d95dc85a1b8f6473fbcc427a8/torch/testing/_internal/common_methods_invocations.py#L3055

Currently tests for `torch.linalg.qr` are generated using OpInfo and there are batched inputs generated in sample_inputs function:
https://github.com/pytorch/pytorch/blob/98207aabf69bb95013fa9bc98162b6ecda053cda/torch/testing/_internal/common_methods_invocations.py#L6073-L6083

The problem was likely fixed with updates of internal code for the QR decomposition, we can close this issue.
