### ISSUE TITLE
Try Blocks unsupported in ScriptModules

### ISSUE THREAD

**Issue by shubhambhokare1** [pytorch/pytorch#53382]
## 🐛 Bug

I'm trying to export a script module to ONNX, however run into issues when the model consist of try catch blocks

## To Reproduce

Here is a simple repro of the issue
```
class TryModel(torch.jit.ScriptModule):
            @torch.jit.script_method
            def forward(self, x):
                try:
                    return x.size(4)
                except:
                    return x
        x = torch.randn(3, 4, 5)
        m = TryModel()
        print(m(x))
```

This is the error message I see
```
torch.jit.frontend.UnsupportedNodeError: try blocks aren't supported:
  File "test/onnx/test_pytorch_onnx_onnxruntime.py", line 3714
            @torch.jit.script_method
            def forward(self, x):
                try:
                ~~~ <--- HERE
                    return x.size(4)
                except:
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0a0+282ed1c
 - OS (e.g., Linux): Ubuntu 16.04.7 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Python version: 3.7 (64-bit runtime)
 - CUDA/cuDNN version: 11.1

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks for reporting this issue. This is indeed an unimplemented feature in TorchScript. However, I'd like to know a bit more about your use case. In my experience the use of try-except is to provide a more descriptive error rather than running a different branch of computation in `except`. Is this your case as well? If so, maybe we can implement a poor-man's try-exception really quickly that ignores `except` branch and just throws the exception in `try`.

**Comment by frankiedrake** [comment]
> Thanks for reporting this issue. This is indeed an unimplemented feature in TorchScript. However, I'd like to know a bit more about your use case. In my experience the use of try-except is to provide a more descriptive error rather than running a different branch of computation in `except`. Is this your case as well? If so, maybe we can implement a poor-man's try-exception really quickly that ignores `except` branch and just throws the exception in `try`.

Hello, I'm facing the same issue, is it a way to do what you've suggested to export the model to jit?

**Comment by augustus-thomas** [comment]
Hello I am facing the same issue still 3 years after this issue was first posted. Is there a way to use try and except when exporting a model to jit? In my case there is no way to implement the "poor man's try-except" since the error occurs when I try to execute a generic user defined function on a submodule. I am not sure why this issue was closed.
