### ISSUE TITLE
SIGSEGV in torch.linalg.inv

### ISSUE THREAD

**Issue by branfosj** [pytorch/pytorch#53454]
## 🐛 Bug

Various inputs for `test_inverse_cpu_*` (in `test_linalg.py`) are resulting in seg faults. The issue is seen for all the datatypes tested. I'm only seeing the seg faults when using `torch.linalg.inv` (i.e. `torch.inverse` is fine).

I'm also seeing seg faults in the following tests in `test_ops.py`:
* `test_out_linalg_inv_cpu_*`
* `test_variant_consistency_eager_linalg_inv_cpu_*`
* `test_variant_consistency_jit_linalg_inv_cpu_*`
* `test_fn_grad_linalg_inv_cpu_*`
* `test_fn_gradgrad_linalg_inv_cpu_*`
* `test_supported_dtypes_linalg_inv_cpu_*`

I've not fully tested, but the `linalg_inv` makes me suspect that these are been caused by the same issue.

## To Reproduce

```
import torch
n = 0
batches = []
a = random_fullrank_matrix_distinct_singular_value(n, *batches, dtype=torch.float32).to('cpu')
torch.linalg.inv(a)
```

`random_fullrank_matrix_distinct_singular_value` being from https://github.com/pytorch/pytorch/blob/8c798e062216278673a75bac0848ea69a8bd3f03/torch/testing/_internal/common_utils.py#L1676

Fails with `n = 0` when `batches` is one of `[]`, `[1]`, `[4]`, `[2, 3]`.

## Expected behavior

No seg fault.

## Environment

PyTorch 1.8.0 release - built from source.

```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 8.2.2004 (Core)  (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.0
[conda] Could not collect
```

## Build info

```
PYTORCH_BUILD_VERSION=1.8.0 PYTORCH_BUILD_NUMBER=1 MAX_JOBS=40 BLAS=Eigen USE_FFMPEG=1 BUILD_CUSTOM_PROTOBUF=0 USE_IBVERBS=1 USE_CUDA=0 USE_METAL=0   /rds/bear-apps/devel/eb-sjb-up/EL8/EL8-cas/software/Python/3.8.6-GCCcore-10.2.0/bin/python setup.py build
```

* GCC: 10.2.0
* OpenBLAS: 0.3.12
* FFTW: 3.3.8
* CMake: 3.18.4
* Extra C/CXX flags: `-O2 -ftree-vectorize -march=native -fno-math-errno`

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @VitalyFedyunin

**Comment by branfosj** [comment]
These failures have been seen on:
* Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake)
* Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake)
* Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell)

**Comment by branfosj** [comment]
I suspected this based on the issue I'm seeing in #53456 - the tests I mention above pass if I build PyTorch with MKL.

**Comment by mruberry** [comment]
Thank you for reporting this issue, @branfosj. We'll take a look.

@IvanYashchuk or @nikitaved, would one of you be interested in figuring out what's going on here?

**Comment by IvanYashchuk** [comment]
BLAS and LAPACK implementations from the Eigen library were not tested with PyTorch. @branfosj could you also tell what version of Eigen is used?

**Comment by branfosj** [comment]
eigen @ d41dc4d - as supplied from a recursive `git clone` of PyTorch v1.8.0.

**Comment by IvanYashchuk** [comment]
The problem was that one of the arguments to the LAPACK call was not correct for 0x0 matrices. I submitted a fix for that.
Even though our tests are failing because of 0x0 test cases, PyTorch v1.8.0 compiled with OpenBLAS is expected to work correctly for non-empty inputs.

The `BLAS=Eigen` option is misleading and it affects only the Caffe2 code and is not used in ATen. https://github.com/pytorch/pytorch/blob/e5ecd1ddf84787789dfdadc8ff8af34a180180fd/cmake/Dependencies.cmake#L124-L126

The following message is printed with `BLAS=Eigen`:
```
-- Trying to find preferred BLAS backend of choice: Eigen
CMake Warning at cmake/Dependencies.cmake:175 (message):
  Preferred BLAS (Eigen) cannot be found, now searching for a general BLAS
  library
```
Then BLAS is searched with `find_package(BLAS)`.  https://github.com/pytorch/pytorch/blob/e5ecd1ddf84787789dfdadc8ff8af34a180180fd/cmake/Dependencies.cmake#L174-L176
CMake log is needed to know what BLAS and LAPACK libraries are picked actually. Or at least `print(torch.__config__.show())`, it should contain the line `Build settings: BLAS_INFO=...`.

I assume OpenBLAS is picked up. I compiled with OpenBLAS 0.3.12 and I see the segfault for 0x0 input. `torch.inverse` is fine because it explicitly returns for this case without relying on the LAPACK library to do that.

**Comment by mruberry** [comment]
> The `BLAS=Eigen` option is misleading and it affects only the Caffe2 code and is not used in ATen.

Is there an obvious, simple way to make this clearer?

I wonder if we should create a page for build flags on the [Wiki](https://github.com/pytorch/pytorch/wiki)?  

And this is making me think we should add a test flags section to the test wiki article, too.
