### ISSUE TITLE
torch.byte/torch.cuda.byte doesn't exist

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5381]
I'd really like them to exist pretty please

**Comment by SsnL** [comment]
I'll do this.

**Comment by gchanan** [comment]
I don't think we should add this, np.byte is and int8, but for us it's an uint8, which seems confusing.  Also, byte in pytorch sometimes really means bool.  So I'd say ask for what you want: if you want a uint8, use that, if you want a bool, use that (we need to implement bool tensors though).

**Comment by ezyang** [comment]
A few thoughts, then.

- By the same reasoning, `ByteTensor` is a confusing to users (because it's `uint8`) and we're going to deprecate this name, right? (BTW, I use ByteTensor all the time without any confusion because all I really need is some opaque blob of data whose size is counted in bytes, because I'm passing it on to cuDNN or something; in this case the signedness of the bytes themselves doesn't matter because I'm never going to interpret the bytes as numbers.)
- Can we make a use of `torch.byte` raise an error explaining why we don't want to let you use it, and how to use the one you actually want?
- What are the semantics of arithmetic operations on `BoolTensor`? The most natural mathematical interpretation is that boolean tensors are tensors of integers modulo two. But representing this with bytes is actively harmful for implementing these semantics correctly. So I really don't like calling it a `BoolTensor` unless we also work to make the ops correct (or exclude them.)

**Comment by gchanan** [comment]
> By the same reasoning, ByteTensor is also confusing to users (because it's uint8) and we're going to deprecate this name, right? ;)

I'm not against that, but it's at least _less_ confusing than `torch.byte` because there is no np.ByteArray equivalent.

> BTW, I use ByteTensor all the time without any confusion because all I really need is some opaque blob of data whose size is counted in bytes, because I'm passing it on to cuDNN or something; in this case the signedness of the bytes themselves doesn't matter because I'm never going to interpret the bytes as numbers.

I've always found this usage a little weird, it reminds me a bit of using CharStorages for strings in TH, i.e. just because something can hold something doesn't mean it should  (what is the cumprod of your blob?).  Why isn't this just some python byte blob object (I don't know the right one to use) that gets translated into some reasonable C++ class (pointer and size pair?)

> Can we make a use of torch.byte raise an error explaining why we don't want to let you use it, and how to use the one you actually want?

I thought about that and I'm not totally against it, but it does seem a little...mean.  I.e. we give an error with a suggestion, but we don't just apply the suggestion (because we don't want them to be lazy and use `torch.byte`?  Well, that sounds a lot like deprecation, but if we do that we are introducing something and immediately deprecating it?

> What are the semantics of arithmetic operations on BoolTensor? The most natural mathematical interpretation is that boolean tensors are tensors of integers modulo two. But representing this with bytes is actively harmful for implementing these semantics correctly. So I really don't like calling it a BoolTensor unless we also work to make the ops correct (or exclude them.)

Right, I'm not suggesting we end up in that state.  I'm just saying we treat ByteTensors as BoolTensors now (e.g. for boolean indexing), so `torch.byte` is again misleading.

**Comment by ezyang** [comment]
WONTFIX.
