### ISSUE TITLE
[JIT] support torch.future.Futures API for creating Futures

### ISSUE THREAD

**Issue by Lilyjjo** [pytorch/pytorch#53839]
## 🚀Feature Request 

TS doesn't support creating futures from torch.futures.Future() but it dos support creating them from torch.jit.fork(). It'd be good for eager parity to allow the futures.Future API to work with TS if it's an easy thing to do 

From a TS Q&A post: 
```
class MyModuleFork(nn.Module):
    def forward(self) -> futures.Future[torch.Tensor]:
        fut = torch.jit.fork(torch.rand, 2, 2)
        return fut

class MyModuleFut(nn.Module):
    def forward(self) -> futures.Future[torch.Tensor]:
        fut = futures.Future() # jit compile error 
        fut.set_result(torch.rand(2, 2))
        return fut

torch.jit.script(MyModuleFork()) # works fine 
torch.jit.script(MyModuleFut()) # error 
```
error thrown:
```
File "local/pytorch/torch/jit/frontend.py", line 300, in build_def
    type_comment_decl = torch._C.parse_type_comment(type_line)
RuntimeError: expected type comment but found 'def' here:
def _add_done_callback(self, callback):  # type: (Callable[[Future[T]], None]) -> None
~~~ <--- HERE
```

cc @gmagogsfm

**Comment by gcramer23** [comment]
I talked with @wanchaol and @tugsbayasgalan about potential solutions to this issue. A possible short term solution is to use torch jit ignore context and making it work with torchbind. A possible long term solution is to support first class function and python hybrid mode.

**Comment by gmagogsfm** [comment]
Thought a bit more about adding `torch.future.Futures` support:

`torch.jit.fork` is essentially TorchScript's way of creating a restricted thread (ie, it must conform to a well defined function, must guarantee to produce requested results etc).

Supporting `torch.future.Futures` is essentially allowing creation of an empty future that doesn't have a well-defined computation behind it and may never be filled. And we'd need to support other ways of creating threads like pthread in order to make future meaningful. 

The amount of work seems high, it probably makes sense to stick to the work-around for now. Closing this issue. 

@suo
