### ISSUE TITLE
[JIT] TorchScript to support typed tensor annotation

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#53933]
## 🚀 Feature
For tensor input, currently only `torch.Tensor` is supported. typed tensors like `FloatTensor`, `LongTensor`, etc are not supported.

## Motivation
Typed tensor annotation is common in models, e.g.: Huggingface transformer snippet

```python
@torch.jit.script
def _prepare_decoder_input_ids_for_generation(
    input_ids: torch.LongTensor, decoder_start_token_id: int = None, bos_token_id: int = None
) -> torch.LongTensor:
    decoder_start_token_id = 47  # for simplicity
    decoder_input_ids = (
        torch.ones((input_ids.shape[0], 1), dtype=input_ids.dtype, device=input_ids.device)
        * decoder_start_token_id
    )
    return decoder_input_ids
```

Log
```
Traceback (most recent call last):
  File "repro_mar_script_longtensor.py", line 7, in <module>
    ) -> torch.LongTensor:
  File "/home/bowbao/repos/pytorch_dev/torch/jit/_script.py", line 995, in script
    qualified_name, ast, _rcb, get_default_args(obj)
RuntimeError:
Unknown type name 'torch.LongTensor':
```

cc @gmagogsfm

**Comment by tugsbayasgalan** [comment]
should we introduce an enum class that contains different kind of tensors inside TensorType @gmagogsfm ?

**Comment by gmagogsfm** [comment]
> should we introduce an enum class that contains different kind of tensors inside TensorType @gmagogsfm ? Or maybe just adding them as special cases here (https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/frontend/string_to_type.cpp#L8)?

I think the main ask is just to support `torch.LongTensor` as type annotation. Given that we don't currently record `dtype` when resolving type annotations, I think we can simply add `torch.LongTensor` and many other dtyped-Tensors as aliases to `torch.Tensor` in [`try_ann_to_type`](https://github.com/pytorch/pytorch/blob/547f43576399eb4237eb005ffb91039f29bdab58/torch/jit/annotations.py#L279)

The link you referred to is only used in type string parsing in operator schema matching (like the case where you added `add` operator for tuples)

**Comment by eellison** [comment]
We have to be careful with this because a user might reasonably assume that because they've added `torch.LongTensor` and it compiles in TorchScript we will throw if the dtype isn't long, however that's not the case.

**Comment by tugsbayasgalan** [comment]
For some reason, torch.LongTensor is not considered as subclass of torch.Tensor even though it is declared as:
```class LongTensor(Tensor)

**Comment by neginraoof** [comment]
@tugsbayasgalan Do we have any updates on this issue? ONNX conversion on blocked for scripting these types.
Moreover, once scripting is enabled, I think we still need to enable annotations for these types in the graph. Similar to Optional[Tensor] which is annotated as Tensor? in the graph, can we enable annotations for Optional[FloatTenosr] and etc.?

**Comment by tugsbayasgalan** [comment]
@neginraoof @BowenBao seems like torch.LongTensor is deprecated and it is not recommended to use it anymore. But, I am working on a PR to support it in Torchscript. For now, the workaround is to do something like: 
`torch.tensor(you_data, dtype=torch.long)`

**Comment by ezyang** [comment]
IMO LongTensor and the other legacy dtype-d tensor constructors should just be treated as Tensor for the purposes of TorchScript. There isn't any serious typechecking going on (for example, I think we accept a Tensor in any context where LongTensor is expected without a refinement)

**Comment by neginraoof** [comment]
Thanks @tugsbayasgalan and @ezyang.

Do you think it is possible to propagate the tensor type (specifically for optional tensors) to the graph, and have a corresponding alias like "FloatTensor?" in the graph for a value annotated in the model as Optional[FloatTensor] ?
I am mainly looking into this for ONNX conversion purposes. Since for ONNX conversion of an optional tensor, the scalar type should be known of inferred from the graph.

Thanks!

**Comment by gmagogsfm** [comment]
> Thanks @tugsbayasgalan and @ezyang.
> 
> Do you think it is possible to propagate the tensor type (specifically for optional tensors) to the graph, and have a corresponding alias like "FloatTensor?" in the graph for a value annotated in the model as Optional[FloatTensor] ?
> I am mainly looking into this for ONNX conversion purposes. Since for ONNX conversion of an optional tensor, the scalar type should be known of inferred from the graph.
> 
> Thanks!

Hi @neginaroof,

Talk about timing! We are actively looking into adding scalar type (dtype) into TorchScript IR, which would then ONNX conversion process. We will publish an RFC once the design is more stable, stay tuned.

CC @penguinwu

**Comment by ezyang** [comment]
@gmagogsfm can you add me to the design discussion, this is related to meta tensors

**Comment by neginraoof** [comment]
> > Thanks @tugsbayasgalan and @ezyang.
> > Do you think it is possible to propagate the tensor type (specifically for optional tensors) to the graph, and have a corresponding alias like "FloatTensor?" in the graph for a value annotated in the model as Optional[FloatTensor] ?
> > I am mainly looking into this for ONNX conversion purposes. Since for ONNX conversion of an optional tensor, the scalar type should be known of inferred from the graph.
> > Thanks!
> 
> Hi @neginaroof,
> 
> Talk about timing! We are actively looking into adding scalar type (dtype) into TorchScript IR, which would then ONNX conversion process. We will publish an RFC once the design is more stable, stay tuned.
> 
> CC @penguinwu

Thanks a lot @gmagogsfm for letting us know. 
A question about having scalar type in TorchScript graph: To what extent would it support Optional types? For example, for a model input of type optional tensor, can we expect the scalar type to be added to the graph, and would it depend on the type annotations?

**Comment by gmagogsfm** [comment]
> > > Thanks @tugsbayasgalan and @ezyang.
> > > Do you think it is possible to propagate the tensor type (specifically for optional tensors) to the graph, and have a corresponding alias like "FloatTensor?" in the graph for a value annotated in the model as Optional[FloatTensor] ?
> > > I am mainly looking into this for ONNX conversion purposes. Since for ONNX conversion of an optional tensor, the scalar type should be known of inferred from the graph.
> > > Thanks!
> > 
> > 
> > Hi @neginaroof,
> > Talk about timing! We are actively looking into adding scalar type (dtype) into TorchScript IR, which would then ONNX conversion process. We will publish an RFC once the design is more stable, stay tuned.
> > CC @penguinwu
> 
> Thanks a lot @gmagogsfm for letting us know.
> A question about having scalar type in TorchScript graph: To what extent would it support Optional types? For example, for a model input of type optional tensor, can we expect the scalar type to be added to the graph, and would it depend on the type annotations?

For a TorchScript graph generated from `torch.jit.script`, optional tensors should already have the right type, ie `Optional[TensorType]`. After implementing the prospective feature, you should be able to extract the scalar type (dtype) from `TensorType` that is contained in `Optional[TensorType]`

Since you are asking from ONNX's perspective, and I heard ONNX performs a step of `jit.trace` at the very beginning of exporting to get shape and dtype information. Are there any other reasons for doing `jit.trace` as part of exporting? If not, I think after the we implement this feature, you won't need `jit.trace` and shape/dtype info will just be handed to ONNX on a silver platter. What's even better is that the information will be comprehensive from sound analysis, rather than from specialization of `jit.trace` on a set of input.

**Comment by neginraoof** [comment]
Thanks for the details. My question is about jit.script path since in ONNX team, we are planning to extend our support for jit.script path. So, ONNX exporter takes in IR graphs form both tracing and scripting. 
In this specific case, we are working to support Optional types in models as it has a growing usage by our customers.
Optional types only  appear in scripting, and currently there is not much information about tensor type provided in the scripting IR.
