### ISSUE TITLE
How to set the amp to all fp16 training?

### ISSUE THREAD

**Issue by sky-fly97** [pytorch/pytorch#53993]
Hello, I would like to ask how to set up all amp training for fp16? Similar to apex's O1 O2 O3 mode? thank you very much!

cc @mcarilli @ptrblck

**Comment by ptrblck** [comment]
Hi @sky-fly97,

the native mixed-precision training utility doesn't use different `opt_levels` as apex did.
The the general usage, please refer to the [amp examples](https://pytorch.org/docs/stable/notes/amp_examples.html#amp-examples).
In case you want to use "pure `FP16`" training, you should be able to directly call `half()` on the data and model.
Note however, that this could yield to instable training behavior, which is why we recommend to use `torch.cuda.amp` instead.

**Comment by sky-fly97** [comment]
> Hi @sky-fly97,
> 
> the native mixed-precision training utility doesn't use different `opt_levels` as apex did.
> The the general usage, please refer to the [amp examples](https://pytorch.org/docs/stable/notes/amp_examples.html#amp-examples).
> In case you want to use "pure `FP16`" training, you should be able to directly call `half()` on the data and model.
> Note however, that this could yield to instable training behavior, which is why we recommend to use `torch.cuda.amp` instead.

Thank you！
