### ISSUE TITLE
improve parallel performance for RNN models

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#54]
Requests from M'aurelio and Sumit Chopra.

RNN Example with:
- [ ] DataParallel Multi-GPU
- [ ] ModelParallel Multi-GPU and part CPU - part GPU
- [ ] PipelineParallel
- [ ] RNN + Reinforce / Mixer ( https://github.com/facebookresearch/mixer )

**Comment by jekbradbury** [comment]
ModelParallel and RNN DataParallel are both things we should have at some point but don't (in the case of ModelParallel, that's because the non-cuDNN RNNs aren't fast enough; in the case of DataParallel, because the parallelism is limited by Python threading). Let's keep thinking about these as goals?

**Comment by ezyang** [comment]
@soumith Do you know what the status on this issue is now?

**Comment by soumith** [comment]
DistributedDataParallel handles the basic cases.
Upcoming `torch.rpc` will handle the other cases (pipeline and model parallel)
