### ISSUE TITLE
Instructions of building PyTorch with Intel OpenMP on Windows

### ISSUE THREAD

**Issue by skyline75489** [pytorch/pytorch#54054]
After #52964, I failed to build PyTorch on Windows due to the lacking of intel-openmp. I did my investigation and found the following things:

* `conda install intel-openmp`: installs the `libiomp5md.dll` and related, but NOT headers.
* `conda install mkl mkl-include`: installs the MKL libraries & headers, but NOT anything OpenMP.
* [This link](https://s3.amazonaws.com/ossci-windows/mkl_2020.2.254.7z) used in #52964: include both libraries & headers for both MKL & OpenMP.

So how do we expect users to build the code right now, using intel-openmp? The current instruction no longer works. 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by skyline75489** [comment]
Also /cc @imaginary-person as he is the one who filed #52907.

**Comment by imaginary-person** [comment]
Hello @skyline75489, before #52964, the [Microsoft OpenMP header file was being used by default](https://github.com/pytorch/pytorch/issues/52907#issuecomment-787270250) with Intel OpenMP while building with Visual Studio on Windows.

@peterjc123 included the Intel OpenMP headers in #52964.

While I personally haven't built PyTorch on Windows, I think #52964 isn't causing the build failure in this issue. Perhaps @peterjc123 can shed some light on this.

**Comment by skyline75489** [comment]
Thanks @imaginary-person for the reply. My point isn't that #52964 causing the build failure. My point is that it includes the needed header for the *CI build*. This is OK. But how do we expect the outside developers to get the correct header? As I pointed out, there's no package available even with Anaconda. We cannot expect the outsider developers to go this far to *manually* download & set up headers for OpenMP, right?

Also with #52964, the current instructions for Windows no longer works, because the Microsoft OpenMP header no longer works. You'll have to get the Intel OpenMP header *somewhere*.

**Comment by imaginary-person** [comment]
Thanks for elaborating, @skyline75489!

In the current codebase, no OpenMP function incompatible with Microsoft OpenMP is being used, so perhaps `FindOpenMP.cmake` can be modified to use the Microsoft OpenMP header, if the Intel one isn't found.
While doing so or reverting some changes in #52964 might fix the issue for some time, such an approach might not be future-proof, as some change in the future (maybe #53737) might introduce an OpenMP function in the codebase that's not supported by Microsoft OpenMP (which doesn't fully conform to the OpenMP specifications).

Intel provides these [instructions for using Intel OpenMP with Visual Studio on Windows](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/optimization-and-programming-guide/openmp-support/openmp-library-support/using-the-openmp-libraries.html), but since you mentioned that Conda doesn't install Intel OpenMP headers alongside the Intel OpenMP library, perhaps Intel OpenMP would then have to be installed from some other source on Windows. In this case, build instructions would've to be updated.

**Comment by imaginary-person** [comment]
Hello @malfet & @seemethere,
Prior to #52964, builds on Windows used Microsoft's OpenMP header to use Intel OpenMP.
#52964 enabled Windows builds to use Intel's OpenMP headers for using Intel OpenMP.
@skyline75489 reported that the current `build from source` instructions aren't working on Windows, as post-#52964, the Microsoft OpenMP header isn't being used.
Please suggest how to solve this issue. Thanks!

**Comment by skyline75489** [comment]
I'd love to go with option 3, which is the best solution going forward. But I found no public Intel OpenMP headers available. And due to licensing issue, I don't think I'm eligible to publish anything that belongs to Intel. However there're many OpenMP headers available that are OSS-licensed. I *think* some of them might just work, since the OpenMP spec is a universal across platforms.

Also I noted that VS 16.9 begun adding [experimental support for newer versions of the OpenMP standard](https://devblogs.microsoft.com/cppblog/improved-openmp-support-for-cpp-in-visual-studio/) by leveraging llvm-openmp. This is also an interesting option in the future.

**Comment by xsacha** [comment]
Just a FYI,
I saw the commit by @peterjc123 and had used the 7z package that was used for the CI to build pytorch, as I typically do. I had not noticed that there was special OMP files added to that MKL build. As a typical outside developer, I assumed this was the norm.
Has there been any comparisons done of Intel OpenMP and Visual Studio OpenMP (particularly 16.9+)?

**Comment by skyline75489** [comment]
@xsacha There's this comment https://github.com/pytorch/pytorch/pull/52964#issuecomment-788253883 which may interest you. Do note that the official build and nightly build are all using Intel OpenMP. I think we should consider vcomp as a fallback solution at the moment.
