### ISSUE TITLE
API suggestion: ".gpu()" instead of ".cuda()"

### ISSUE THREAD

**Issue by rasbt** [pytorch/pytorch#542]
Hi, I was thinking, that renaming `.cuda()` to `.gpu()` would before the API stabilizes in the later beta. I I am not sure if OpenCL support is planned at all, but I thought that `gpu` would be more general than `cuda` -- and if OpenCL support is going to be added one day, one wouldn't have to rewrite already existing PyTorch implementations but just change an environment variable, e.g., `$PYTORCH_GPU=CUDA` or` $PYTORCH_GPU=OPENCL` or sth. along those lines. 

Let me know if there's interest in that, I'd more than happy to submit a PR at some point. Also, in this context, maybe having a documentation that is decoupled from the master branches (e.g., adding the  "pytorch/tutorlials" to the website) may be a good idea so that users of the current stable release don't get confused when API changes get introduced.

**Comment by Bachstelze** [comment]
jo, cuda and gpu should be the same. But for now its seams like they are developing in two different worlds.

**Comment by soumith** [comment]
Hi @rasbt 

The reason we explicitly named it `.cuda()` is because of how it is named in Torch itself. 

The origin of the API naming in Torch is untraceable, but it worked out well to keep it as `.cuda()` rather than change it to `.gpu()`. How did it work out well?
- the opencl package is [a separate package and repository in torch](https://github.com/hughperkins/cltorch) that doesn't need to sit in the core and has a `cl()` function. It can be installed and imported separately, after which a `.cl()` function will be available to users.
- In the same process, the OpenCL and CUDA packages can coexist (for example if you have a GPU that's AMD and another NVIDIA for example).

Saying that, we dont plan to add any official OpenCL support (see #488) but instead will wait for AMD's HIP technology that has a much better chance of actually being (a) successful (b) on performance parity with CUDA at the software level. (c) has a CUDA to HIP transpiler

Now that I've given you context, I kinda like the naming `.gpu()` more, and we'll think about if we can depreceate `.cuda()` in the favor of `.gpu()`, I'll get back to you on a decision.

**Comment by apaszke** [comment]
I think that once we add support for non-CUDA technologies, there might be value in keeping both - exactly for the case then you want to use some NVIDIA GPUs, and some AMD. You can have `.gpu()` sending tensors using the currently selected "default GPU backend", and `.cuda()` and `.cl()` for backend specific transfers. Otherwise `.gpu()` would have to accept additional arguments, and passing them to every single call would look awful.

That being said, I think that deprecating `.cuda()` in favor of `.gpu()` seems reasonable for now.

**Comment by suryabhupa** [comment]
I would have voted to keep the old '.cuda()' and '.cli()' API to be reflective of Torch's way of doing this, but if '.gpu()' can be called without extra arguments, then I'm okay with this, especially when multiple backends are supported. 

At the same time, I'm not sure if that means '.cuda()' should be deprecated entirely, and for me it would be nice if both APIs could be supported (again, this could just be my torch bias speaking).

**Comment by rasbt** [comment]
When I suggested this, I was thinking of a use case where we may have a bunch of model-training scripts that we want to execute in an environment where a different backend is installed (some time along the road). In this case, it would be slightly more convenient to just set the "default" backend instead of modifying all the 'cuda' calls to 'cl' or vice versa. 

However, I also agree that 

> .cuda() and .cl() for backend specific transfers.

may be a good idea to avoid cluttering the internals with `if ... then`s. (vs `gpu('cuda')` and `gpu('cl')`).

**Comment by alexjc** [comment]
As a Torch/PyTorch beginner, I found the naming a little confusing at first and requiring education what exactly is going on when I call this. I thought it was configuration-only at first, so it's not as self-explanatory as it could be.  Fortunately, this can be addressed entirely with an extra helper method — hence backward-compatible and Torch-friendly too.

I'd personally suggest naming to reflect the operation actually done under the hood.  I tend to name functions as verbs, so something like `transfer(gpu=0)` or some combination of `upload(device='gpu0')` / `download(...)`.

**Comment by soumith** [comment]
there is no movement on this, and there is no consensus from us maintainers (we've discussed it a couple of times). 
We think the naming change is unnecessary (at this stage).
I'm closing an issue that is honestly making no progress.
