### ISSUE TITLE
Incorrect Example Code from LSTMCell

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#54319]
## 📚 Documentation

The example code from https://pytorch.org/docs/stable/generated/torch.nn.LSTMCell.html seems to be incorrect.
```
import torch
from torch import nn
rnn = nn.LSTMCell(10, 20)
input = torch.randn(3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(6):
  hx, cx = rnn(input[i], (hx, cx))
  output.append(hx)
```
However, it throws `IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

I think the simplest fix should be replacing `hx, cx = rnn(input[i], (hx, cx))` with `hx, cx = rnn(input, (hx, cx))`.

**Comment by ilovepytorch** [comment]
Another more reasonable fix may be to use `input = torch.randn(6, 3, 10)` instead of `input = torch.randn(3, 10)`.

**Comment by zou3519** [comment]
Thanks for the bug report, @ilovepytorch. We've fixed this on master (https://pytorch.org/docs/master/generated/torch.nn.LSTMCell.html#torch.nn.LSTMCell) and the fix will be in the very soon upcoming PyTorch 1.8.1 release. We generally don't backport fixes to already-released versions of PyTorch. Closing this issue because it has been fixed.
