### ISSUE TITLE
Join/concatenate distributions of different types

### ISSUE THREAD

**Issue by francois-rozet** [pytorch/pytorch#54411]
## 🚀 Feature

Implement a class (e.g. `Join`), child of `Distribution` to join/concatenate distributions of different types. This would allow to sample easily from the joined distributions, but also compute compute the log joined-probability.

For instance

```python
>>> a, b = Uniform(0, 1), Normal(0, 1)
>>> c = Join([a, b])
>>> x = c.sample()
>>> x
tensor([ 0.7235, -1.1922])
>>> c.log_prob(x)
tensor(-1.6296)
>>> a.log_prob(x[0]) + b.log_prob(x[1])
tensor(-1.6296)
```

This is actually similar to `Independent`, but is much more versatile as it would allow to join different distribution types.

## Motivation

I often work with complex parameter distributions, where some parameters are drawn from `Uniform` and others from `MultivariateNormal`. Being able to sample from such distribution with the same API as those that are already implemented would save a lot of (development) time and complexity.

## Possible implementation

In `sample`, the events are flattened and concatenated, resulting in an output of the shape `(sample_shape, batch_shape, -1)`.
When evaluating `log_prob`, the samples are split back into the respective sub-distributions and the total log probability is the sum of the individual log probabilities.

```python
class Join(Distribution):

    arg_constraints: dict = {}

    def __init__(self, subs: List[Distribution]):
        super().__init__()

        self.subs = subs

    @property
    def mean(self):
        return torch.cat([sub.mean.view(-1) for sub in self.subs])

    @property
    def variance(self):
        return torch.cat([sub.variance.view(-1) for sub in self.subs])

    @property
    def event_shape(self) -> torch.Size:
        shape = [0]

        for sub in self.subs:
            shape[0] += sub.event_shape.numel()

        return torch.Size(shape)

    @property
    def batch_shape(self) -> torch.Size:
        return self.subs[0].batch_shape  # assume same batch_shape

    def expand(self, batch_shape: torch.Size):  # -> Join
        return Compose([sub.expand(batch_shape) for sub in self.subs])

    def sample(self, sample_shape: torch.Size = ()):
        x = []

        for sub in self.subs:
            y = sub.sample(sample_shape)
            y = y.view(sample_shape + self.batch_shape + (-1,))
            x.append(y)

        return torch.cat(x, dim=-1)

    def log_prob(self, x: torch.Tensor) -> torch.Tensor:
        i, logp = 0, torch.tensor(0.)

        for sub in self.subs:
            j = i + sub.event_shape.numel()
            y = x[..., i:j].view(x.shape[:-1] + sub.event_shape)
            i = j

            logp = logp + sub.log_prob(y)

        return logp
```

In this implementation, it is assumed that each sub-distribution has the same `batch_shape`.

cc @fritzo @neerajprad @alicanb @vishwakftw @nikitaved

**Comment by fritzo** [comment]
@francois-rozet It sounds like you're looking for a probabilistic programming language.  Have you considered using Pyro or ProbTorch?

**Comment by francois-rozet** [comment]
@fritzo I work with probabilistic programming languages, but it is not really related. This issue is just a feature proposition for the `torch.distributions` module as joined distributions are not available.

The proposed implementation in the first post is working (at least for me), so I don't "need" the feature to be added, but I was thinking it could be great to have this available in "vanilla" PyTorch :wink: If you don't think this is useful, you can close the issue.

**Comment by fritzo** [comment]
@francois-rozet while I agree it is sensible to add something like `StackDistribution` and `CatDistribution`, I am worried that might open up room for an avalanche of structural distribution combinators accounting for nontrivial event shapes, differing batch shapes (plates), dependencies, conditional execution etc., something similar to Tensorflow Probability's [JointDistribution](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/JointDistribution).  Even your proposed first step has awkward limitations due to dtype (e.g. stacking Categorical vs Normal) and support for reparametrization (e.g. if only a subset of distributions are reparametrizable).  IMHO it is cleanest to clearly separate a low-level layer of basic distributions ("elementary random primitives") that contain nontrivial numerical mathematics, from a separate high-level layer allowing composition of those distributions.  That higher level is basically a probabilistic programming language, and arguably deserves more thorough composition mechanisms than would fit into a distributions library.

**Comment by francois-rozet** [comment]
@fritzo Indeed, the proposed implementation isn't very robust and it would require way too much complexity to handle everything correctly... I agree it would not fit in `torch.distributions`, then. This closes the issue, thank you!
