### ISSUE TITLE
ConvTranspose2d with padding being a python list raises exception

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#54452]
## 🐛 Bug

ConvTranspose2d with padding being a python list crashes

## To Reproduce

```python
import torch

x = torch.randn(4, 8, 32, 32, device='cuda', dtype=torch.float)
net = torch.nn.ConvTranspose2d(8, 16, kernel_size=3, padding=[3, 3])
net = net.cuda()

y = net(x)
torch.cuda.synchronize()
```

error message:

```
Traceback (most recent call last):
  File "/home/xwang/Developer/pytorch-test/random-things/padding-tuple.py", line 7, in <module>
    y = net(x)
  File "/home/xwang/Developer/pytorch/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xwang/Developer/pytorch/torch/nn/modules/conv.py", line 890, in forward
    assert isinstance(self.padding, tuple)
AssertionError
```

https://github.com/pytorch/pytorch/pull/45667 is related.

See comments https://github.com/pytorch/pytorch/pull/45667#discussion_r599070539

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @albanD @mruberry @peterbell10 @ptrblck

**Comment by jbschlosser** [comment]
Thanks for reporting this! I agree that lists should be supported for padding and the docs should be updated to indicate this as well.

In the details, it seems like the problem comes from:
https://github.com/pytorch/pytorch/blob/263cd5cf98fe83d535aada119cada00209d562d5/torch/nn/modules/conv.py#L879

`torch.nn.modules.utils._pair()` will return a list if one is input, despite it being defined as `_pair = _ntuple(2)`. The `_ntuple()` family of functions is badly named.
