### ISSUE TITLE
tools/git-clang-format: The downloaded binary is not what was expected!

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#54790]
`tools/git-clang-format` seems to do a test on hash of the clang-format binary, but if it mismatches it just says "The downloaded binary is not what was expected!" and no instructions how to remediate. I rm -rf'ed .clang-format-bin that might help

**Comment by SplitInfinity** [comment]
Deleting `.clang-format-bin` should trigger another downloaded the next time you run `clang_format_all.sh`. Would it be useful to include this suggestion in the error message?

**Comment by SplitInfinity** [comment]
I misunderstood what was going on. #53932 changed the hash algorithm and therefore the hashes, so it could be that they are wrong.

**Comment by SplitInfinity** [comment]
I just tried with the latest master and my previously downloaded binary (which is verified before it is used) worked, as did downloading a new one by removing `.clang-format-bin`.

**Comment by SplitInfinity** [comment]
Oh, turns out the clang format utils code tries to delete the file for you if the hash doesn't match:

https://github.com/pytorch/pytorch/blob/master/tools/clang_format_utils.py#L139-L147

So perhaps it should print out that the file has been deleted.

**Comment by ezyang** [comment]
If the tool is willing to delete the binary directly it should just immediately redownload without re-running. (Or you can just edit the error message, that's fine too)

**Comment by SplitInfinity** [comment]
Okay, looks like the actual problem is that #54737 added newlines to the reference hashes, causing the download script to print `The downloaded binary is not what was expected!` even though the only difference between the reference hash and locally computed hash is the newline.

I fixed this in #55328, but also added a message that tells you that the binary has been deleted. 

> If the tool is willing to delete the binary directly it should just immediately redownload without re-running

This makes sense if there is some issue with downloading the binary, but in the case I detailed above, this would have led to an infinite loop. Should I add a retry limit?

**Comment by ezyang** [comment]
> This makes sense if there is some issue with downloading the binary, but in the case I detailed above, this would have led to an infinite loop. Should I add a retry limit? Even then, the vast majority of hash mismatches cannot be fixed by redownloading (e.g. someone adds a newline to the end of the reference hash, someone updates the binary but not the hash, someone updates the hash but not the binary).

You should be willing to redownload exactly once (and if that doesn't work, bail with a nice scary error)
