### ISSUE TITLE
[feature request] Dockerfile for python 2.7

### ISSUE THREAD

**Issue by CharlesJQuarra** [pytorch/pytorch#5514]
The current Dockerfile only covers python 3.6. I tried updating it to work with python 2.7, but I haven't been able to get it to work (conda throws some InstallationErrors)

Here is the preliminar `Dockerfile`:

```
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         vim \
         ca-certificates \
         libjpeg-dev \
         libpng-dev &&\
     rm -rf /var/lib/apt/lists/*


ENV PYTHON_VERSION=2.7
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install numpy pyyaml scipy ipython mkl && \
     /opt/conda/bin/conda install -c soumith magma-cuda90 && \
     /opt/conda/bin/conda clean -ya

#ENV PATH /opt/conda/bin:/opt/conda/envs/pytorch-py$PYTHON_VERSION/bin:$PATH
#RUN /opt/conda/bin/conda update -n base conda
#RUN /opt/conda/bin/conda install --name pytorch-py$PYTHON_VERSION -c soumith magma-cuda90

# This must be done before pip so that requirements.txt is available
ENV PATH /opt/conda/bin:$PATH

WORKDIR /opt/pytorch
COPY . .
RUN ls -ltah

RUN git submodule update --init
RUN TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    pip install -v .

RUN git clone https://github.com/pytorch/vision.git && cd vision && pip install -v .

WORKDIR /workspace
RUN ls -ltah
RUN chmod -R a+w /workspace
```

**Comment by varunagrawal** [comment]
Python 2 is nearing its end-of-life in 2020. As such, I don't think it is worthwhile to support Python2.7 containers.

**Comment by vsoch** [comment]
I think both of these points are fair, and actually 90% of the time I'd take team "It's been 10 years already migrate to Python 3!" But I also now that there are several users (non developers) that are using older software (without an ability to update for python 3) that still have a good 2 years with python 2, and would greatly benefit from having such a container. On the flip side, it really hurts them to not have it because it puts a stop to their work. It doesn't necessarily need to be maintained officially, but some kind of discussion or at least a working prototype I think would be well worth the effort.

**Comment by ezyang** [comment]
FWIW, we still officially support Python 2 and test against it. I'm not sure what problems you ran into updating the Dockerfile (you didn't post them) but it *should* work, if you line everything up right.

**Comment by ezyang** [comment]
python 2 is dead, this issue is obsolete
