### ISSUE TITLE
Preserve PyObject even when it is dead from Python side

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#55686]
In https://github.com/pytorch/pytorch/issues/22884 I observed that if the Python object representing a Tensor gets deallocated, it promptly goes dead and we create a new Python object to replace it next time it passes from C++ to Python. This is problematic for tensors that represent Python subclasses and/or have custom `__dict__` entries, because all of that information solely lives in Python and is lost when this occurs.

I have devised a scheme to solve this problem, based off of @colesbury's POC for keeping two PyObjects live so long as one of them lives https://github.com/colesbury/refcount/blob/master/refcount.c The key idea is that it is possible to "rescue" a Python object from being deallocated, even if its refcount goes to zero (this is easy to do safely in Python because of the GIL). So here's the idea:

* Ordinarily, PyObject holds an owning reference to TensorImpl
* When the PyObject would die, we now check if the TensorImpl is uniquely owned by the PyObject's owning reference. If so, the TensorImpl is dead too and we can destruct everything as normal. HOWEVER, if the TensorImpl is still live, we now flip ownership: we toggle a boolean on TensorImpl indicating that it has an owning reference to the PyObject, and we bump the PyObject's reference count to make sure it doesn't go dead. Call this a **zombie PyObject**
* If a TensorImpl dies while holding an owning reference to a PyObject, it is responsible for also deallocating the PyObject. This will be done using a virtual call in to the libpython.
* If we try to take an owning reference to a zombie PyObject, we flip the ownership back again. So we toggle the TensorImpl to be non-owning again, skip the Python incref and directly return the PyObject (no longer zombie)

The key invariant of this scheme is that it is not necessary to have resurrect a zombie TensorImpl; the invariant is that a TensorImpl only ever goes dead if there are truly no references (no direct references to the TensorImpl, and no owning reference from a non-zombie PyObject).

To make testing out this scheme less risky, we can opt into this scheme only for subclasses of Tensor. However, I think that if there is no major performance impact we should eventually turn this on globally.

**Comment by albanD** [comment]
It is not specified in the second point, but when you do the flipping, you also remove the owning reference from the PyObject to the TensorImpl right?

**Comment by ezyang** [comment]
Yes, so the PyObject reference Tensor has to be made weak. We can use @swolchok's MaybeOwned class to conveniently do this.

**Comment by colesbury** [comment]
I like this idea a lot more than the refcount.c POC. I've been thinking about this a bit more based on your write-up:

1) Every [`Tensor`](https://github.com/pytorch/pytorch/blob/b80c6f863f2327c712c478f67c248b94d66b65ac/torch/_tensor.py#L50) is a Python subclass of [`torch._C._TensorBase`](https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/torch/csrc/autograd/python_variable.cpp#L794-L799). Presumably, we'd put the "cancel dealloc" code in [`THPVariable_dealloc`](https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/torch/csrc/autograd/python_variable.cpp#L163-L169). The problem is that Python subtype's [`tp_dealloc`](https://github.com/python/cpython/blob/b38601d49675d90e1ee6faa47f7adaeca992d02d/Objects/typeobject.c#L1229-L1230) gets called before the `_TensorBase`'s dealloc. By that point, it's too late: weakrefs have already been cleared and the finalizer (`__del__` in Python code) gets called it's one and only time. We might be able to work around this with some metaclass shenanigans to ensure that the "maybe-cancel-dealloc" code gets called before subtype_dealloc for all TensorBase subclasses.

2) You mention that If a TensorImpl dies while holding an owning reference to a PyObject, the TensorImpl needs to dealloc the PyObject -- that requires acquiring the GIL. In current PyTorch programs, the Python Tensor objects typically die before the corresponding C++ objects. That will change -- we'll have a lot of "zombie" PyObjects for all saved-for-backward Tensors. The multi-threaded autograd engine will be calling back into the Python API a lot more frequently. This might not be an issue, but we should design benchmark to explicitly measure for this impact.

**Comment by ezyang** [comment]
Also, colesbury tells me we need to add enough debug statements to make sure tracemalloc keeps working https://github.com/python/cpython/blob/b98eba5bc2ffbe7a0ed49d540ebc4f756ae61985/Objects/object.c#L248-L259

**Comment by ezyang** [comment]
Current status: I implemented most of the stuff but I am having difficulty implementing the metaclass entirely in C++. I've been working off of https://github.com/python/cpython/blob/v3.7.0/Modules/xxsubtype.c but even a trivial metaclass results in `Fatal Python error: GC object already tracked` while initializing unrelated classes from `import torch._C`. Trivial metaclass looks like:

```
+#define DEFERRED_ADDRESS(ADDR) nullptr
+
+PyTypeObject THPVariableMetaType = {
+  PyVarObject_HEAD_INIT(DEFERRED_ADDRESS(&PyType_Type), 0)
+  "torch._C._TensorMeta",                      /* tp_name */
+  sizeof(THPVariableMeta),                     /* tp_basicsize */
+  0,                                           /* tp_itemsize */
+  nullptr,                                     /* tp_dealloc */
+  0,                                           /* tp_vectorcall_offset */
+  nullptr,                                     /* tp_getattr */
+  nullptr,                                     /* tp_setattr */
+  nullptr,                                     /* tp_reserved */
+  nullptr,                                     /* tp_repr */
+  nullptr,                                     /* tp_as_number */
+  nullptr,                                     /* tp_as_sequence */
+  nullptr,                                     /* tp_as_mapping */
+  nullptr,                                     /* tp_hash  */
+  nullptr,                                     /* tp_call */
+  nullptr,                                     /* tp_str */
+  nullptr,                                     /* tp_getattro */
+  nullptr,                                     /* tp_setattro */
+  nullptr,                                     /* tp_as_buffer */
+  Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,    /* tp_flags */
+  nullptr,                                     /* tp_doc */
+  nullptr,                                     /* tp_traverse */
+  nullptr,                                     /* tp_clear */
+  nullptr,                                     /* tp_richcompare */
+  0,                                           /* tp_weaklistoffset */
+  nullptr,                                     /* tp_iter */
+  nullptr,                                     /* tp_iternext */
+  nullptr,                                     /* tp_methods */
+  nullptr,                                     /* tp_members */
+  nullptr,                                     /* tp_getset */
+  DEFERRED_ADDRESS(&PyType_Type),                                /* tp_base */
+  nullptr,                                     /* tp_dict */
+  nullptr,                                     /* tp_descr_get */
+  nullptr,                                     /* tp_descr_set */
+  0,                                           /* tp_dictoffset */
+  // THPVariableMetaType_init,                    /* tp_init */
+  nullptr,
+  nullptr,                                     /* tp_alloc */
+  nullptr                                      /* tp_new */
+};
+
 PyTypeObject THPVariableType = {
-  PyVarObject_HEAD_INIT(nullptr, 0)
+  PyVarObject_HEAD_INIT(&THPVariableMetaType, 0)
   "torch._C._TensorBase",                      /* tp_name */
   sizeof(THPVariable),                         /* tp_basicsize */
```
