### ISSUE TITLE
Add Scale Factor To SGD

### ISSUE THREAD

**Issue by kevinzakka** [pytorch/pytorch#5572]
Was wondering if it would be possible to add a `weight` or `scale` argument to SGD. This is useful for methods using importance sampling where we would like to scale the `gradient*learning_rate` by the likelihood ratio. In the default setting, `scale=1`.

I can submit a PR if this get a green light.

**Comment by apaszke** [comment]
Wouldn't doing this before calling the optimizer work?
```python3
for p in model.parameters():
    p.grad *= scale
```

**Comment by ruotianluo** [comment]
If so, why was weight decay added? You can achieve weight decay in this way too.

**Comment by apaszke** [comment]
1. because it's so much more common than rescaling gradients by a constant that doesn't depend on the iteration
2. it needs to be performed on weights and not gradients, and this requires an extra `no_grad` block
3. ideally it wouldn't be part of the optimizer, but we're stuck with it for now because of backward compatibility

**Comment by lianzhibin** [comment]
AttributeError: module 'torch' has no attribute 'no_grad'

**Comment by fmassa** [comment]
@lianzhibin `no_grad` was recently added, and you need to compile from source to have it.
