### ISSUE TITLE
Print Bug of Tensor Grad After Backward

### ISSUE THREAD

**Issue by michaelowenliu** [pytorch/pytorch#55980]
## 🐛 Bug

Pytorch 1.8

```python
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv2d(12, 12, 3)
    def forward(self, x, y):
        x = self.conv(x)
        y = self.conv(y)
        var = y.flatten()
        x[0, :, 0, 0] *= var

        loss = torch.mean(x)
        var.register_hook(lambda grad: print('var grad', grad.sum()))
        return loss

model = Model()

x = torch.ones([1, 12, 3, 3]).float()
y = torch.ones([1, 12, 3, 3]).float()
loss = model(x, y)

loss.backward()
```

The above code has correct output , but when I change `x[0, :, 0, 0] *= var` to `x[0, :, 0, 0] = x[0, :, 0, 0] * var`, which is equal calculation. The error occurs:
![image](https://user-images.githubusercontent.com/14087480/114640663-29ff6c00-9d03-11eb-9e2a-f11a1065f47f.png)

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by ezyang** [comment]
Unfortunately, this is expected. The multiplication `x[0, :, 0, 0] * var` saves `x[0, :, 0, 0]` for backwards, but then you mutate it and we are then unable to use it for backwards. The inplace formula doesn't have this problem because it knows the clobber is coming and does something special. A simple fix is `x[0, :, 0, 0] = x[0, :, 0, 0].clone() * var`. Could you tell us a little more about what you're trying to do?

**Comment by michaelowenliu** [comment]
@ezyang Hi, Edward, I got the point! Good design.Thanks a lot.
