### ISSUE TITLE
Include Python version in libtorch_python.so

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#56046]
## 🚀 Feature

I propose to include the Python version in `libtorch_python.so` 's soname, similar to the Python modules.

## Motivation

As evidenced by the "Start Locally" page, PyTorch has a rather complex matrix of different builds (see also eg #56038).
One of the axes is the Python version. However, >90% (totally made up) of PyTorch packages are identical between Python versions with the differences being the C extension modules and `libtorch_python.so`. Both of these depend on the specific Python version. The C-extension modules include `sysconfig.get_config_var('EXT_SUFFIX')` from package sysconfig.

So we could save a lot of build time and distribution if we just re-used the common parts. Using the EXT_SUFFIX would make it possible to PyTorch for multiple Python versions in the same space. This is also useful for development installations.

## Pitch

Rename `libtorch_python.so` to 'libtorch_python' + sysconfig.get_config_var('EXT_SUFFIX').

## Alternatives

Status Quo.

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Thank you for your suggestion. I've discussed some of those ideas with @janeyx99 and @seemethere few weeks ago.

At the very least we should accelerate nightly build matrix by reusing torch_cpu and torch_cuda across the builds of python flavors.
Packaging multiple version of libtorch_python in whl package also sounds attractive, but is not as straightforward as previous item due to the current size of the library (sizeof(libtorch-python) is currently around 25mb on Linux)
