### ISSUE TITLE
pytorch_linux_bionic_py3_8_gcc9_coverage_test1 / 2 duplicate tests

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56113]
I'm guessing test1 and test2 are supposed to run disjoint tests, but they are not. At the very least I know that ProcessGroupJitRpcTestWithSpawn is replicated in both (see https://app.circleci.com/pipelines/github/pytorch/pytorch/301716/workflows/cb3d7c0f-6dc1-40b6-9ae7-5294e24206c8/jobs/12414389 https://app.circleci.com/pipelines/github/pytorch/pytorch/301716/workflows/cb3d7c0f-6dc1-40b6-9ae7-5294e24206c8/jobs/12414391 ) but possibly there are others.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @mruberry @VitalyFedyunin

**Comment by samestep** [comment]
@janeyx99

**Comment by janeyx99** [comment]
Ah, the same test case seems to be spawned by two different test files and are a part of two different test suites, so I think this might have been intentional, as I believe there are other test cases like this (with the same name but belonging to different suites). The current sharding algorithm operates on the test file level, so this isn't unexpected in that aspect. 

It looks like  `test_call_fork_in_jit_with_profiling` in `TensorPipeJitRpcTestWithSpawn` from `distributed/rpc/test_tensorpipe_agent.py` and its counterpart in`ProcessGroupJitRpcTestWithSpawn` from `distributed/rpc/test_process_group_agent.py`are separately generated intentionally, though I'm not sure what the difference is right away.
