### ISSUE TITLE
[structured] Porting to structured kernels can be BC breaking for non-differentiable operators that used CompositeImplicitAutograd

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56273]
I ported `bitwise_not` to structured:

```
diff --git a/aten/src/ATen/native/native_functions.yaml b/aten/src/ATen/native/native_functions.yaml
index bf52225f185..56155761ff7 100644
--- a/aten/src/ATen/native/native_functions.yaml
+++ b/aten/src/ATen/native/native_functions.yaml
@@ -741,12 +741,16 @@
     CUDA: _bincount_cuda
 
 - func: bitwise_not(Tensor self) -> Tensor
+  structured_delegate: bitwise_not.out
   variants: function, method
 
 - func: bitwise_not_(Tensor(a!) self) -> Tensor(a!)
+  structured_delegate: bitwise_not.out
   variants: method
 
 - func: bitwise_not.out(Tensor self, *, Tensor(a!) out) -> Tensor(a!)
+  structured: True
+  structured_inherits: TensorIteratorBase
   dispatch:
     CPU, CUDA: bitwise_not_out
 ```

Unfortunately, this broke XLA:

```
Apr 15 21:08:16 [ RUN      ] AtenXlaTensorTest.TestBitwiseNot
Apr 15 21:08:17 /var/lib/jenkins/workspace/xla/test/cpp/torch_xla_test.cpp:50: Failure
Apr 15 21:08:17 Value of: changed.empty()
Apr 15 21:08:17   Actual: false
Apr 15 21:08:17 Expected: true
Apr 15 21:08:17 [  FAILED  ] AtenXlaTensorTest.TestBitwiseNot (49 ms)
Apr 15 21:08:17 [ RUN      ] AtenXlaTensorTest.TestBitwiseNotInPlace
Apr 15 21:08:17 /var/lib/jenkins/workspace/xla/test/cpp/torch_xla_test.cpp:50: Failure
Apr 15 21:08:17 Value of: changed.empty()
Apr 15 21:08:17   Actual: false
Apr 15 21:08:17 Expected: true
Apr 15 21:08:17 [  FAILED  ] AtenXlaTensorTest.TestBitwiseNotInPlace (63 ms)
```

So it seems that the CompositeImplicitAutograd was required to make XLA work, and not even structured kernel's automatically generated CompositeExplicitAutograd was enough to solve the problem.  What this suggests is that https://github.com/pytorch/pytorch/pull/53037 wasn't enough to fix the XLA case (the PR is fine, it stands alone, but I had been hoping that it would also help XLA out, which it doesn't seem to.)

**Comment by ezyang** [comment]
cc @bdhirsh @ailzhang

**Comment by bdhirsh** [comment]
I think we can actually fix this pretty easily: after https://github.com/pytorch/pytorch/pull/53037, the info in `RegistrationDeclarations.yaml` is technically wrong. Since with that PR, every `functional`/`inplace` op that has an `out` variant gets a code-generated `CompositeExplicitAugrad` kernel, that means that all of those ops don't need backend overrides in order to work properly (we can set the `default: true` field for those entries in `RegistrationDeclarations.yaml`).

I'm going to test that out. But the reason that the XLA test in that PR failed is that the XLA codegen is needlessly creating CPU fallback kernels for `inplace`/`functional` ops that already have a `CompositeImplicitAutograd` kernel: the CPU fallback has higher precedence than the alias key, and the CPU fallback is what's registered to the XLA dispatch key. So with your change, we now dispatch to xla's CPU fallback kernel. Which maybe isn't all that bad, except that pytorch/XLA has tests that assert that we didn't call the CPU fallbacks.


I think that this could be an issue for the boxed CPU fallback though. I guess the question is which kernel we think should have a higher precedence: a composite kernel? Or a kernel that automatically redispatches to CPU. We probably want the composite kernel to have higher precedence in this case, so we'll need to somehow make sure that the codegen'd `CompositeImplicitAutograd` kernels get called instead of the CPU fallback kernel.

IDEA: Is registering a boxed fallback to an alias key a thing? We could maybe register the boxed CPU fallback to `CompositeExplicitAutograd`....

**Comment by ezyang** [comment]
Thanks, that's a really nice diagnosis.  The upcoming problem with backend fallback reminds me of #55104
