### ISSUE TITLE
[docs] Rendering type hint issues at torchvision

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#56382]
Note the missing types, missing generic types, and super-large spacing (e.g. RandomCrop)

![image](https://user-images.githubusercontent.com/1041752/115263947-25d5b300-a136-11eb-8a03-6c9bd9331ab6.png)

![image](https://user-images.githubusercontent.com/1041752/115264019-38e88300-a136-11eb-9ea5-93924d694b11.png)

cc @brianjo @mruberry

**Comment by mruberry** [comment]
You probably want to file this issue at the torchvision github, @vadimkantorov: https://github.com/pytorch/vision.

**Comment by vadimkantorov** [comment]
Is documentation rendering not managed in a unified fashion? If not, please feel free to transfer this issue to that repo (I think GitHub has such an option, right?)

**Comment by oke-aditya** [comment]
Hello @vadimkantorov 
This was issued due to Sphinx 3.x. This has been fixed over torchvision master by downgrading Sphinx to 2.4.4. Documentations are fine now!

@vadimkantorov rendering is not unified, for each domain library text, vision and audio docs are built and deployed over GitHub pages from their respective repos!

Feel free to close this as it is fixed!

**Comment by vadimkantorov** [comment]
Just before closing, is the issue reported to Sphinx? So that rendering doesn't degrade again when you try upgrading Sphinx again...

**Comment by oke-aditya** [comment]
Yes it is related to Sphinx. The PyTorch theme is not fully compatibly with Sphinx 3.x and hence the issue.

For more details see t[orchvision issue ](https://github.com/pytorch/vision/issues/3681)

Also Sphinx 3.x compatibility is opened with theme repo too. [Here](https://github.com/pytorch/pytorch_sphinx_theme/issues/115) is the ticket.

Thank you for reporting @vadimkantorov
