### ISSUE TITLE
Chunk operation in ONNX opset 11 is much more complex than opset 9.

### ISSUE THREAD

**Issue by PeterL1n** [pytorch/pytorch#56404]
## 🐛 Bug

This is what opset 9 and 10 looks like.
<img width="435" alt="chunk opset9" src="https://user-images.githubusercontent.com/7651753/115294753-d8455000-a10d-11eb-92dc-9db525bc5dc4.png">

This is what opset 11 and 12 looks like.
<img width="829" alt="chunk opset 11" src="https://user-images.githubusercontent.com/7651753/115294855-fb6fff80-a10d-11eb-80aa-1ba71aaf444e.png">

## To Reproduce

```python
class TestModel(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x.chunk(4, dim=1)

model = TestModel().eval()

x = torch.randn(1, 4, 256, 256)
torch.onnx.export(
    model,
    x,
    'test.onnx',
    export_params=True,
    opset_version=9) # change here between 9 and 11.
```

## Expected behavior

Opset 11, 12 export of chunk should just be as simple as Opset 9 and 10.
Note that split operation is correct for all opsets. Only chunk is messed up in 11 and 12.

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: None

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by BowenBao** [comment]
The idea behind the more complex graph in opset 12, is to be able to support dynamic shape inputs. Consider passing input of shape (1, 8, 256, 256). The resulting dimension size of each chunk will be 2 instead of 1, and need to be dynamically computed.

On the other hand, we are also improving our shape inference to detect static shape input scenarios and fold away unnecessary operators. This will likely improve in the future, and is controlled by the export argument `dynamic_axes`, notifying the exporter whether input shapes are dynamic or static.

**Comment by AllenTiTaiWang** [comment]
We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
