### ISSUE TITLE
[onnx export]UserWarning: Exporting aten::index operator with indices of type Byte.

### ISSUE THREAD

**Issue by mathmax12** [pytorch/pytorch#56753]
I am trying to convert a model to onnx in pytorch. But I got warning :
`C:\Users\xiaoj\.conda\envs\yolact_clone\lib\site-packages\torch\onnx\symbolic_opset9.py:2691: UserWarning: Exporting aten::index operator with indices of type Byte. Only 1-D indices are supported. In any other case, this will produce an incorrect ONNX graph.
  warnings.warn("Exporting aten::index operator with indices of type Byte. "`

After some research i found this https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py#L2700
But I still not sure how to fix this warning.
Please help.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by BowenBao** [comment]
@mathmax12 The problem is presumably not with type Byte, but with index rank being larger than 1-D. There are certain subset of indexing in PyTorch that is not supported for exporting. Please checkout https://pytorch.org/docs/master/onnx.html#unsupported-tensor-indexing-patterns for examples of such cases, and their suggested workarounds.

**Comment by shubhambhokare1** [comment]
Hi @mathmax12 ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
