### ISSUE TITLE
Addition of different transforms on train, test and validation data in random_split method

### ISSUE THREAD

**Issue by Aradhya-Tripathi** [pytorch/pytorch#56886]
## 🚀 Feature
The `torch.utils.data.dataset.random_split()` takes in an object of the dataset class and applies random split on it,
however, the transformations on train and test data might be different thus using this as an additional argument to pass different transforms for the test, train, and validation datasets be helpful and hassle-free.

## Motivation
As I generally write a custom dataset class for loading in my image data it would be helpful and hassle-free if I could have an 
option of using `random_split()` with this custom class and as an additional argument to this adding different transformations for train, test, and validation would be helpful.

## Pitch

Depending on the split of data providing an option to treat the transformations separately for each of the split.

## Alternatives

I  don't have an alternative for this, as the random_split function although being helpful does not accept the different transformations for my data.

## Additional context

Thanks!

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
Thank you @Aradhya-Tripathi for the feature request.
We are currently working on a new design of DataLoader, which will easily resolve this problem. Please check the RFC #49440 and we would appreciate if you can provide feedback on that.
And, in terms of your pitch, I don't think it's doable since each `Subset` shares the custom dataset instance. Even if you add a `split_index` to each `Subset`, your custom dataset instance can not figure out which `split_index` belongs to itself. And, it's also not feasible to assign new attribute `split_index` to the custom dataset instance as there is only one instance.
So, I recommend an alternative solution below:
```py
class CustomDataset:
    pass

class SplitDataset:
    def __init__(dataset, split: str = 'train'):
        self.ds = dataset
        self.split = split

    def __getitem__(self, idx):
        d = self.dataset[idex]
        if self.split == 'train':
            d = train_op(d)
        elif self.split == 'test':
            d = test_op(d)
        else:
            d = val_op(d)
        return d

    def __len__(self):
        return len(self.ds)

ds = CustomDataset()
train, test, val = random_split(ds, [100, 50, 10])
train, test, val = SplitDataset(train, 'train'), SplitDataset(test, 'test'), SplitDataset(val, 'val')
```

**Comment by Aradhya-Tripathi** [comment]
Ok sure, 
Makes sense ;)
