### ISSUE TITLE
torch.arange cannot create torch.FloatTensor of size 13

### ISSUE THREAD

**Issue by freedrone** [pytorch/pytorch#5704]
![image](https://user-images.githubusercontent.com/16558669/37276081-de282fe6-25f1-11e8-8bac-9f7fb4e08c35.png)

- OS: Ubuntu 17.10
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6.4
- CUDA/cuDNN version: -
- GPU models and configuration: -

```
import torch as th
th.arange(0, 1.1, 0.1)
th.arange(0, 1.2, 0.1)
th.arange(0, 1.3, 0.1)
```

**Comment by bheinzerling** [comment]
This is a floating point problem that has been mitigated in master with this commit:
https://github.com/pytorch/pytorch/pull/5600

But even with that fix, arange doesn't always give the expected result. You can avoid this issue by doing
`torch.arange(0, 13) / 10`

**Comment by apaszke** [comment]
It’s impossible to have arange work in all kinda of possible conditions due to rounding errors in floating point math. What we did in master was to make it consistent with numpy. An alternate solution would be to avoid having the length of the interval be exactly divisible by its length (you can make it a tiny bit larger).

**Comment by bheinzerling** [comment]
The numpy docs have a note saying "When using a non-integer step, such as 0.1, the results will often not be consistent."

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

Maybe this could be added to the torch.arange doc as well?
