### ISSUE TITLE
torch.onnx.export cannot work with torch.unfold when dynamic_axes is set.

### ISSUE THREAD

**Issue by lawlict** [pytorch/pytorch#57086]
## 🐛 Bug

Pytorch version: 1.8.1.
Code:
```
import torch
import torch.nn as nn


class Unfold1(nn.Module):
    def forward(self, x):
        return x.unfold(-1, 4, 2)

model = Unfold1()

x = torch.arange(72).reshape(1, 3, 24).float()
y = model(x)
print(y.shape)

torch.onnx.export(
    model, x, 'model.onnx', verbose=False,
    input_names=['input'], output_names=['output'],
    dynamic_axes={'input': {0: 'batch', 1: 'time', 2: 'freq'}}, opset_version=11
)
```
Error:
```
RuntimeError: ONNX export failed: Couldn't export operator aten::unfold
```
If I remove the `dynamic_axes` argument, the code runs normally. In this case, the exported model is like:
![image](https://user-images.githubusercontent.com/35951198/116342244-dcabf000-a814-11eb-81f7-237e7bf78228.png)
What if I hope to set the input size dynamically? Many thanks.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by SEMLLYCAT** [comment]
请求相同问题的解决方法

**Comment by BowenBao** [comment]
@lawlict @SEMLLYCAT please try with latest PyTorch and opset 12. `unfold` in opset 12 utilize `Loop` to handle dynamic size inputs.

**Comment by tszhang97** [comment]
same problem

**Comment by shubhambhokare1** [comment]
Hi @lawlict, @SEMLLYCAT, @tszhang97,

We’ve gone ahead and closed this issue because it has been resolved elsewhere. This resolution can be found in the comment above
```
please try with latest PyTorch and opset 12. unfold in opset 12 utilize Loop to handle dynamic size inputs.
```
Also in this scenario, all the input dims cannot be dynamic, try with any combination of two dims as dynamic. For example,
```
dynamic_axes={'input': {0: 'batch', 1: 'time'}}
```
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
