### ISSUE TITLE
Help regarding integration of torch model deployment in flutter 

### ISSUE THREAD

**Issue by bilal-aamer** [pytorch/pytorch#57548]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hello im getting started with flutter, and am quite accustomed to pytorch. 
I require help in it's integration in flutter.

**Comment by mrshenli** [comment]
Hey @bilal-aamer, could you please use the [forum](https://discuss.pytorch.org/) for questions. Besides, I think most people in PyTorch github and forum don't have knowledge on flutter. You probably need to provide some context to help people understand the problem. 

I am closing this issue for now. Please feel free to open another one this if this turns out to be a feature request or bug report. Thanks!
