### ISSUE TITLE
difference in behavior between quicklint and lint

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#57644]
Repro:
1. Change `torch/package/package_exporter.py` in some trivial way.
2. Run `make lint -j 20`, observe no failures.
3. Run `make quicklint -j 20`, observe failures in `package_exporter.py`.

I think the problem is in how we invoke mypy:
```
for CONFIG in mypy*.ini; do mypy --config="$CONFIG" $LOCAL_FILES; done
```

The `files` entry in the mypy config only kicks in when mypy is invoked with no arguments. So when we pass explicit `$LOCAL_FILES` as we do in quicklint, we end up running mypy-strict on whatever files we pass (whereas we wouldn't do that in CI).

cc @driazati

**Comment by driazati** [comment]
We're running up against a lot of problems since we're applying the raw scripts from our GitHub actions workflows locally. `LOCAL_FILES` is a bit of a hack that diverges the behavior between local lints + CI, we should probably unify our linting into some locally-runnable mega script that we just run in CI (broken up by job name), something like `python setup.py lint --job mypy` or `python setup.py lint --job quick-checks`. There we could call the relevant commands and do less-hacky switching to enable certain behavior locally (like checking the list of files supplied against `mypy.ini`'s allowlist)

@samestep what do you think?

**Comment by samestep** [comment]
Linking https://github.com/pytorch/pytorch/issues/55847#issuecomment-825176051 for context.

Solving the more general problem @driazati mentions will take some more effort, and I would like to spend time on it but have not gotten around to it yet.

However, it seems to me that the specific issue around `mypy` in this thread could have a much easier fix: change `quicklint` to use `tools/mypy_wrapper.py` instead of just `mypy`, as I originally suggested a couple weeks ago: https://github.com/pytorch/pytorch/pull/56559#issuecomment-824201436

@driazati I don't know enough about `tools/actions_local_runner` (and our `Makefile` setup) to know how easy/difficult this would be to do; could you comment on that idea? I believe it would also require me to change `tools/mypy_wrapper.py` to allow multiple filenames to be passed instead of just one, which is something I can do without too much difficulty, so just let me know if you'd like me to do that.

**Comment by driazati** [comment]
It'd be pretty easy to do in a brittle way. The nice aspect of `actions_local_runner.py` is that we run the same thing in CI as we do locally (at least in theory, `LOCAL_FILES` makes this not be the case), but I don't think that's really tenable and it's making for a worse UX (see this, and flake8 duplicates error outputs since it's 2 separate stages in `lint.yml`). I'll put up a PR to make those manual runs since the invocations are pretty simple for flake8 / mypy

**Comment by samestep** [comment]
@driazati I do agree that it's brittle but I think it's unavoidable for `quicklint` to be implemented differently from `lint`, to some degree. Until we are able to switch from the model of our local runner parsing our CI configuration to our CI configuration just invoking our local runner, I do agree that we should avoid adding special cases for `make lint`, but for `make quicklint`, I'd be more inclined to prioritize correctness over parity in cases like this.

For the PR you're making, you can probably just use something like `xargs -n1` for now, to invoke `tools/mypy_wrapper.py` with just one file at a time; I can put together a PR that allows it to be called with multiple files.
