### ISSUE TITLE
torch.cuda.amp cannot speed up on A100

### ISSUE THREAD

**Issue by thomas0809** [pytorch/pytorch#57806]
## ❓ Questions and Help

I am trying to use `torch.cuda.amp` to speed up training. The following code works well on V100 (120s w/o amp and 67s w/ amp), but cannot get a reasonable speedup on A100 (53s w/o amp and 50s w/ amp).

I am using the most recent NGC docker [nvcr.io/nvidia/pytorch:21.04-py3](https://ngc.nvidia.com/catalog/containers/nvidia:pytorch), which has CUDA 11.3, pytorch 1.9.0.

The strange thing is if I change the model to resnet101, both V100 and A100 can get speedup, but not for the swin transformer on A100. See the following table for the running time (in sec) on different machines.
 
<google-sheets-html-origin style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

  | resnet101 | resnet101 amp | swin_base | swin_base amp
-- | -- | -- | -- | --
V100 | 49.19 | 19.62 | 120.07 | 67.19
A100 | 40.9 | 29.35 | 47.19 | 44.97
A100 w/ docker | 24.32 | 13.26 | 53.68 | 50.04

</google-sheets-html-origin>

```
import torch
import argparse
import os
import time
import timm
from tqdm import trange

parser = argparse.ArgumentParser()
parser.add_argument("--model", type=str, default='swin_base')
parser.add_argument("--fp16", action='store_true')
args = parser.parse_args()

N = 32
input_size = 384

x = torch.randn(N, 3, input_size, input_size).cuda()
y = torch.randint(1000, (N,)).cuda()

if args.model == 'swin_base':
    model = timm.create_model('swin_base_patch4_window12_384').cuda()
elif args.model == 'resnet101':
    model = timm.create_model('resnet101').cuda()

loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

if args.fp16:
    scaler = torch.cuda.amp.GradScaler()

start = time.time()

for t in trange(100):
#     optimizer.zero_grad()
    with torch.cuda.amp.autocast(enabled=args.fp16):
        y_pred = model(x)
        if args.fp16:
            assert y_pred.dtype is torch.float16
        loss = loss_fn(y_pred, y)
    if args.fp16:
        scaler.scale(loss).backward()
    else:
        loss.backward()
#     optimizer.step()

end = time.time()

print('Time:', end-start)
```

cc @mcarilli @ptrblck @VitalyFedyunin @ngimel @zasdfgbnm

**Comment by xwang233** [comment]
Thanks for the report. Can you try if converting the input `x` to channels-last gives any performance boost? Something like

```python
x = torch.randn(N, 3, input_size, input_size, device='cuda')
if args.fp16:
  x = x.to(memory_format=torch.channels_last)
```

cc @ptrblck

**Comment by thomas0809** [comment]
> Thanks for the report. Can you try if converting the input `x` to channels-last gives any performance boost? Something like
> 
> ```python
> x = torch.randn(N, 3, input_size, input_size, device='cuda')
> if args.fp16:
>   x = x.to(memory_format=torch.channels_last)
> ```
> 
> cc @ptrblck

Thank you for the suggestion. I tried it but there was no performance boost. The runtime was 50.0s on A100.

**Comment by ptrblck** [comment]
Double post from [here](https://discuss.pytorch.org/t/torch-cuda-amp-cannot-speed-up-on-a100/120525/2).

**Comment by ezyang** [comment]
cc @mcarilli

**Comment by mcarilli** [comment]
To see a performance benefit from channels-last, you should also convert the model to channels last, preferably before constructing the optimizer:
```python
x = x.to(memory_format=torch.channels_last)
model = model.to(memory_format=torch.channels_last)

loss_fn = ...
```
Hopefully, this will give additional speedup on V100 or A100.

Concerning the lousy "speedup" with amp on A100, first of all I'd expect less of a relative difference because A100 should use TF32 tensor cores by default for FP32 (non-amp) runs, which is 2X less throughput than FP16 for matmuls on paper, but much faster than not using tensor cores at all. This closes the performance gap to amp, so I do expect the FP32 vs amp difference to be more modest on Ampere. It's possible that with FP32 backed by TF32 library math, ops that benefit most from tensor cores (ie matmuls, convs) have been accelerated enough that the network is mainly bound by CPU overhead or by ops Amp doesn't affect as much, so turning on Amp doesn't squeeze much more blood from the stone.

What is the difference between "A100" and "A100 w/docker"?

Also, GradScaler's constructor has an `enabled=` argument like autocast. False turns its calls into no-ops. Instead of
```python
    if args.fp16:
        scaler.scale(loss).backward()
    else:
        loss.backward()
```
you can do
```
scaler = GradScaler(enabled=args.fp16)
...
# unconditionally
scaler.scale(loss).backward()
```

**Comment by ngimel** [comment]
A100 uses tf32 by default, so you are getting a lot of TensorCore benefits without amp, so amp relative improvement is less. To improve performance further, try converting to channels last, as suggested above.

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org, github is for reporting bugs/requesting features.
