### ISSUE TITLE
Add a `descending` flag to `linalg.eigh` and `linalg.svd` 

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#58034]
At the moment the eigenvalues are returned in `linalg.eigh` in ascending order, while the singular values in `linalg.svd` are returned in descending order.

This dissonance is annoying but it goes in line with Numpy. Even then, we should at least give the user a nice interface to ask for the order they want the spectral values in. The name of the flag is in line with that present in `torch.sort`.

cc @svekars @carljparker @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @heitorschueroff

**Comment by mruberry** [comment]
Should the Python Array API consider specifying they both be returned in ascending (or descending) order for consistency?

cc @rgommers

**Comment by rgommers** [comment]
To add to that, for `numpy.linalg.eigvals`:
```
        The eigenvalues, each repeated according to its multiplicity.
        They are not necessarily ordered, nor are they necessarily
        real for real matrices.
```
`torch.linalg.eigvals` does not document its behavior.

> Should the Python Array API consider specifying they both be returned in ascending (or descending) order for consistency?

I'm not really a fan of such keywords, because they don't do anything more than `s = s[..., ::-1]`, you rarely need them, and if you do need them it's unlikely you get it wrong. So my preference would be to just have good documentation.

**Comment by Lezcano** [comment]
Note that `linalg.eigvals` does not have it because it always returns a complex tensor.

I do not have a strong preference for one or the other, but it's just a bit odd that the order for `svdvals` and `eigvalsh` is the opposite...

**Comment by trbedwards** [comment]
Can we also add the option of **not** sorting the eigenvalues?

**Comment by lezcano** [comment]
Just out of curiosity, what's the motivation for that request?

Now, I don't think we would be able to implement that, as these algorithms are intrinsically sequential. You start finding the k largest singular values, and then the next k and so on, so the result you get is already ordered. You can always scramble it if you need that for your application.

**Comment by trbedwards** [comment]
> Just out of curiosity, what's the motivation for that request?
> 
> Now, I don't think we would be able to implement that, as these algorithms are intrinsically sequential. You start finding the k largest singular values, and then the next k and so on, so the result you get is already ordered. You can always scramble it if you need that for your application.

I'm attempting to do Gaussian Process regression with constraints on the derivatives (i.e, monotonicity). For this I'm using a [Truncated multivariate sampler](https://github.com/brunzema/truncated-mvn-sampler) as a drop-in replacement for the `MultivariateNormal` object that GPs usually return in their `forward` method. I have implemented a custom kernel which returns a matrix consisting of the covariances between the function values and derivatives (sort of like `RBFKernelGrad` in `gpytorch`).  

The truncated mvn sampler requires a covariance matrix that is positive semi definite (PSD), but since my cov matrix has such a high dynamic range it often doesn't fulfil that requirement. Most of the routines in gpytorch get around this by automatically adding jitter until the matrix is PSD. But in my case I have such as poorly conditioned matrix that adding jitter to it doesn't work. I think get around this problem by computing the eigenvalues `L` and eigenvectors `V`, then returning the matrix product `V @ diag(L) @ V.T`. If I sort the eigenvalues then the data that I'm computing the covariance on `X` must be sorted as well

**Comment by trbedwards** [comment]
`linalg.eig` doesn't sort the eigenvalues, but I confess I haven't looked into the details of how it works compared to `linalg.eigh`, only that it's slower as it doesn't assume symmetric/hermitian matrices.

**Comment by lezcano** [comment]
I don't understand what do you mean by "If I sort the eigenvalues then the data that I'm computing the covariance on X must be sorted as well". The eigenvalues and eigenvectors of a matrix may be permuted in any way and that will give other valid eigendecompositions of the matrix  (without having to touch the initial matrix at all).  

About `linalg.eig`: Even though some matrices with real coefficients happen to have real eigenvalues, this is not the case in general. As such, in general, the eigenvalue decomposition of a real matrix is a complex matrix with complex eigenvalues. For this  reason, there's no total ordering one may impose on them. That being said `linalg.eigvals` (and `linalg.eig`) returns the eigenvalues from largest to smallest in modulus. The implementation does not say anything about what  happens if there's repeated eigenvalues of the same modulus though.

**Comment by vadimkantorov** [comment]
Also, docs of `linalg.eig` do not say anything about the sorting/order of the returned eigvals. I propose that it should explicitly say that the order is not guaranteed (although for my usecase the eigvals from `linalg.eig` are sorted somehow in ascending order).

Also, sorting complex eigvals by magnitude is one of reasonable choices.

Maybe `.sort` and `.argsort` should then also support complex inputs.

A more complicated (maybe too complicated?) solution can be having a `descending=True|False` and `complex_mode="real" | "imag" | "abs" | "angle"` args as an argument to `.sort` / `.argsort` and supporting the same argument to `.eig`

**Comment by lezcano** [comment]
OK, let's go with Ralf's solution in https://github.com/pytorch/pytorch/issues/58034#issuecomment-839124610, and just add proper documentation rather than adding a full flag.

`eigh`/`svd`/`eigvalsh`/`svdvals` already have lines of the form
>The singular values are returned in descending order.

Let's add equivalent lines to `eig`/`eigvals` saying that 
>The returned eigenvalues are not guaranteed to be in any specific order.

Whoever wants to pick up this issue, feel free to simply submit a fix and add me as a reviewer.
