### ISSUE TITLE
Nightly Build wont install

### ISSUE THREAD

**Issue by caseybasichis** [pytorch/pytorch#58163]
Torch refuses to install the nightly -- always jumping to 1.8.1 instead.

[pip3_torch_nightly.txt](https://github.com/pytorch/pytorch/files/6468075/pip3_torch_nightly.txt)

I'm on Linux Mint 20.1

cc @ezyang @seemethere @malfet @walterddr

**Comment by seemethere** [comment]
We’re not currently building CUDA 11.2 binaries, can you try again with the CUDA 11.1 binaries to see if that resolves your issues?

```
pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
```

**Comment by caseybasichis** [comment]
I have a RTX A6000 system where 11.2 is required, I'm trying to keep this system in sync with that setup.

I was able to install the nightly build with CUDA 11.2 about about month ago, for the A6000 system.

Has 11.2 support since been discontinued?

**Comment by seemethere** [comment]
I believe you should be able to use CUDA 11.1 binaries with a CUDA 11.2 driver.

CUDA 11.2 is not built due to issues with regarding functionality and performance, see https://github.com/pytorch/pytorch/issues/50232#issuecomment-777703998

We have no plans to support CUDA 11.2, you can refer to https://github.com/pytorch/pytorch/issues/56721 to track progress on CUDA 11.3
