### ISSUE TITLE
Flake8 triggers E902 FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#58253]
## 🐛 Bug
Per title
PR is blocked due to the test.

## To Reproduce

1. Remove any file
1. run `make quicklint -j 6` or `python tools/actions_local_runner.py --file-filter '.py' --changed-only --job 'flake8-py3'`
1. `E902 FileNotFoundError: [Errno 2] No such file or directory`

## Expected behavior

No error and CI is green

I think we need to filter out the deleted file from here:
https://github.com/pytorch/pytorch/blob/098d9975a7c6b33ada382bd51f322f7f5c694a17/tools/actions_local_runner.py#L62-L82

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by samestep** [comment]
> PR is blocked due to the test.

Which PR?

**Comment by ejguan** [comment]
> Which PR?

#58244

**Comment by samestep** [comment]
Thanks for flagging this! For that PR, please just bypass the failure and land. I'll open a PR to disable the flaky test, and also look into fixing this specific issue.

**Comment by ejguan** [comment]
It can be fixed pretty easily! Use `git diff --name-status` and filter out `D`.

**Comment by samestep** [comment]
> It can be fixed pretty easily! Use `git diff --name-status` and filter out `D`.

@ejguan I think there are [a couple others](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) that would have to be accounted for, such as `R`, so I think instead of changing those commands and parsing their output more, I'll just add another check at the end of the `find_changed_files` function to filter out files that don't exist.

**Comment by samestep** [comment]
For more context, this is another example of #56745.
