### ISSUE TITLE
Create an OpInfo test for CPU vs CUDA consistency

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#58294]
**Updated 6/7/2021**

PyTorch once had "tensor_op_tests", but they were removed in https://github.com/pytorch/pytorch/pull/55558. These tests would run a method once on the CPU and once on a CUDA or XLA device and compare the results. What these tests did and how they should be used was confusing, however, and they were often added when it was unnecessary to do so or removed as OpInfos were created for them, even though the OpInfo tests do not yet cover the same cases.

After some discussion (see below), instead of using the CPU as the source of truth, we would like to generalize the OpInfo architecture to support references. UnaryUfuncInfos already support references, but the OpInfo base class does not. This reference can then be compared against PyTorch's implementation of the operation on its sample inputs.

cc @mruberry @VitalyFedyunin @walterddr @kshitij12345 @krshrimali -- maybe an interesting task for @krshrimali's onboarding?

**Comment by ngimel** [comment]
Why do we need CPU vs CUDA consistency as opposed to reference consistency?

**Comment by mruberry** [comment]
> Why do we need CPU vs CUDA consistency as opposed to reference consistency?

Good question: this is for tests that don't compare with references. Currently only UnaryUfuncInfos have special tests that compare with NumPy references.

**Comment by ngimel** [comment]
Then maybe the right direction is to make those tests compare with references too? These tests don't compare with references not because it's impractical or impossible, but because at the time they were written "compare with reference" was not a widely accepted approach to testing.

**Comment by mruberry** [comment]
> Then maybe the right direction is to make those tests compare with references too? These tests don't compare with references not because it's impractical or impossible, but because at the time they were written "compare with reference" was not a widely accepted approach to testing.

That's true; I guess the refinement here would be:

- we should start an effort focused on adding references for every OpInfo
- for operators that have references we can compare to the reference instead using CPU vs CUDA as the reference impl

I still want to write this test (and have the UnaryUfuncInfos skip it) because adding references is a longer term project, and adding references for functions in torch.nn is nontrivial.

**Comment by mruberry** [comment]
Summary of offline discussion with @ngimel:

This test seems very limited in its appeal, and it might be interesting, instead, to start adding reference implementations to every OpInfo. We wouldn't require references, but if an OpInfo has a reference we could validate its CPU and CUDA sample inputs against it in a new test. 

Adding more references to OpInfos is interesting (it's basically implementing PyTorch's operators in NumPy and SciPy, which is kinda cool), but also not something we should spend a ton of time on. So this test would apply to OpInfos which have references BUT not UnaryUfuncInfos, which test against their references elsewhere.

@kshitij12345 @krshrimali What do you think of that proposal? It's more general and future looking, but we would lose CPU vs CUDA coverage of ops we remove from `tensor_op_tests` until we add references to their OpInfos. I guess that shouldn't be too hard to do?

**Comment by krshrimali** [comment]
> Summary of offline discussion with @ngimel:
> 
> This test seems very limited in its appeal, and it might be interesting, instead, to start adding reference implementations to every OpInfo. We wouldn't require references, but if an OpInfo has a reference we could validate its CPU and CUDA sample inputs against it in a new test.
> 
> Adding more references to OpInfos is interesting (it's basically implementing PyTorch's operators in NumPy and SciPy, which is kinda cool), but also not something we should spend a ton of time on. So this test would apply to OpInfos which have references BUT not UnaryUfuncInfos, which test against their references elsewhere.
> 
> @kshitij12345 @krshrimali What do you think of that proposal? It's more general and future looking, but we would lose CPU vs CUDA coverage of ops we remove from `tensor_op_tests` until we add references to their OpInfos. I guess that shouldn't be too hard to do?

Thanks for the detailed description, @mruberry. I understand why having references to OpInfos is interesting assuring consistency of NumPy/SciPy with PyTorch. I'm, though, curious to hear from you or anyone who can help with this, on these points:

1. Is there any difference when we say `start adding reference implementations to every OpInfo` vs `until we add references to their OpInfos`? I'm assuming that you mean something similar to how `UnaryUFuncInfo` does it: `ref=np.<op>` or in some cases reference from SciPy. (https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L384)
2. Is there a reason why unary funcs should implement their tests for references separately? If there is an existing discussion on this, I'm curious to understand the motivation of having their tests against their references implemented elsewhere. And if that's the case, do we plan to implement separate classes for Binary Funcs, Reduction Funcs etc. as well? (hopefully, any PR/issue where this has been discussed will help me get an answer) (cc: @kshitij12345 on this since he might be able to help with this as well)

Adding references is a good idea, it (ideally) will be able to do both: CPU vs CUDA coverage as well as test consistency. But we won't be checking (explicitly) CPU vs CUDA coverage if we add reference tests, right? In that case, if the reference test fails, we'll have to infer about the CPU vs CUDA coverage from the output of reference test. As an example, reference test for an op from OpInfo should ideally have these permutations as results: (the **CPU vs CUDA coverage** is inference from reference test and not a test result)

1. **Reference test**: Satisfies the conditions: PyTorch op is consistent on both devices vs the reference. (**CPU vs CUDA coverage**: satisfied)
2. **Reference test**: Satisfied on CUDA but not on CPU: PyTorch op is consistent on CUDA vs the reference, but not on CPU. (**CPU vs CUDA coverage**: not satisfied)
3. **Reference test**: Satisfied on CPU but on CUDA: PyTorch op is consistent on CPU vs the reference, but not on CUDA. (**CPU vs CUDA coverage**: not satisfied)
4. **Reference test**: Not satisfied on both CPU and CUDA: PyTorch op is _not_ consistent on CPU & CUDA vs the reference. (**CPU vs CUDA coverage**: ?)

The only thing I'm not sure here is for the 4th permutation, because even if the PyTorch ops is not consistent with the reference, there are possibilities (w.r.t CPU vs CUDA consistency) that:

1. The op is not consistent on CUDA and CPU devices.
2. The op is consistent on CUDA and CPU devices. (but just not consistent with the reference)

In this case, I do think that having a CPU vs CUDA consistency coverage will still help to debug issues! I apologize if any if I misunderstood the point, but just asking questions I've in mind to be clear before we start implementing.

**Comment by mruberry** [comment]
Good questions. Answers inline:

> 1. Is there any difference when we say `start adding reference implementations to every OpInfo` vs `until we add references to their OpInfos`? I'm assuming that you mean something similar to how `UnaryUFuncInfo` does it: `ref=np.<op>` or in some cases reference from SciPy. (https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L384)

Yes, every OpInfo would support an optional reference attribute.

> 2. Is there a reason why unary funcs should implement their tests for references separately? If there is an existing discussion on this, I'm curious to understand the motivation of having their tests against their references implemented elsewhere. And if that's the case, do we plan to implement separate classes for Binary Funcs, Reduction Funcs etc. as well? (hopefully, any PR/issue where this has been discussed will help me get an answer) (cc: @kshitij12345 on this since he might be able to help with this as well)

Yes, because the special unary elementwise tests exploit the structure of unary elementwise operations and don't rely on sample inputs.

Yes, we plan to implement specialized tests for binary elementwise and reduction options, too, again because those classes of operations are large enough and have enough common structure that tests can programmatically generate interesting inputs to them.
 
> Adding references is a good idea, it (ideally) will be able to do both: CPU vs CUDA coverage as well as test consistency. But we won't be checking (explicitly) CPU vs CUDA coverage if we add reference tests, right? In that case, if the reference test fails, we'll have to infer about the CPU vs CUDA coverage from the output of reference test. As an example, reference test for an op from OpInfo should ideally have these permutations as results: (the **CPU vs CUDA coverage** is inference from reference test and not a test result)

If both CPU and CUDA inputs to the operation are compared against the reference then we will be testing CPU vs CUDA transitively. If only the CPU version of the test fails that suggests the CPU implementation of the operation is incorrect, and if only the CUDA version of the test fails that suggests the CUDA implementation of the operation is incorrect. Note also that both could fail, in which case the reference is incorrect or both are implemented incorrectly.

> The only thing I'm not sure here is for the 4th permutation, because even if the PyTorch ops is not consistent with the reference, there are possibilities (w.r.t CPU vs CUDA consistency) that:
> 
> 1. The op is not consistent on CUDA and CPU devices.
> 2. The op is consistent on CUDA and CPU devices. (but just not consistent with the reference)
 
> In this case, I do think that having a CPU vs CUDA consistency coverage will still help to debug issues! I apologize if any if I misunderstood the point, but just asking questions I've in mind to be clear before we start implementing.

This is possible but I don't think it's worth developing and running a new test for. Engineers can easily test for CPU vs CUDA consistency themselves, if it would be helpful, and tests are expensive,

**Comment by walterddr** [comment]
Adding to the discussion regarding CI cost? Do we plan to add another argument (e.g. `slow_test`) to 
https://github.com/pytorch/pytorch/blob/452569dffb59a0dead6f46dc540fa46009b71c3a/test/test_torch.py#L8047
in order to guard the slowest operations?

Another alternative what @janeyx99 implemented for automatically categorizing slow test in #54456. We might need to tweak the threshold a bit though.

**Comment by mruberry** [comment]
> Adding to the discussion regarding CI cost? Do we plan to add another argument (e.g. `slow_test`) to
> https://github.com/pytorch/pytorch/blob/452569dffb59a0dead6f46dc540fa46009b71c3a/test/test_torch.py#L8047
> 
> 
> in order to guard the slowest operations?

The plan is to kill 

https://github.com/pytorch/pytorch/blob/452569dffb59a0dead6f46dc540fa46009b71c3a/test/test_torch.py#L7815

by porting them to OpInfos. OpInfos already support decorating generated tests as slow, if necessary.

**Comment by mruberry** [comment]
Fixed by #59369.
