### ISSUE TITLE
MacOS Nightly Conda 3.9 builds timeout

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#58534]
See here for example:
https://app.circleci.com/pipelines/github/pytorch/pytorch/323740/workflows/c13cf64a-77cd-4f32-b735-6b5014e826bf/jobs/13539544

No such problem exists for wheel builds, nor for arm64 conda build(which cross compiles M1 binaries on x86 host), even though the build is running on node with identical HW characteristics.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by datumbox** [comment]
@malfet Thanks for flagging.

This is probably the reason why CI jobs such as the [binary_macos_conda_py3.9_cpu](https://app.circleci.com/pipelines/github/pytorch/vision/8370/workflows/ad4d7e61-8421-48c2-92c2-df8b501c905e/jobs/601827) and [unittest_macos_cpu_py3.9](https://app.circleci.com/pipelines/github/pytorch/vision/8370/workflows/7c926d8b-c06b-42c0-95c2-779b875a1e37/jobs/601757) fail on Vision and Audio. Judging from the [released binaries](https://conda.anaconda.org/pytorch-nightly/osx-64), the last time this worked was on 20210419. Given it's been over a month since we ran the unit-tests on MacOS+Py39 and we are getting close to the release, could you bump the priority so that we have time to properly test and fix potential issues? Thanks!

cc @fmassa @mthrok @seemethere

**Comment by malfet** [comment]
@datumbox we definitely need to fix it ASAP. And next time please do not hesitate adding `high priority` label yourself

**Comment by malfet** [comment]
Found huge perf fix in one of conda-build dependencies: https://github.com/lief-project/LIEF/pull/579

**Comment by datumbox** [comment]
@malfet Thanks for looking into it. I assume that the problem is now fixed and tomorrow we should have nightlies. If it fails again, would it be possible to run the job manually to create a binary so that we can start testing our code?
