### ISSUE TITLE
Import fails after Conda install

### ISSUE THREAD

**Issue by arinbjornk** [pytorch/pytorch#5905]
I installed pytorch via Conda but some of the cuda files cannot be imported. TensorFlow installed via conda on the same machine is working.

- OS: Ubuntu 16.04.4
- PyTorch version: 0.3.1
- How you installed PyTorch: conda
- Python version: 3.6.1
- CUDA/cuDNN version: CUDA 8.0, cudnn 7.0.5
- GPU models and configuration: GTX 1080
- GCC version (if compiling from source): n/a

Steps:
1. Install pytorch with conda
```
$ conda install pytorch torchvision -c pytorch
```
2. Verify pytorch and cuda
```
$ conda list
# packages in environment at /home/[...]
#
[...]
cudatoolkit               8.0                           2 
cudnn                     7.0.5                 cuda8.0_0  
[...]
pytorch                   0.3.1           py36_cuda8.0.61_cudnn7.0.5_2    pytorch

```
3. Try to import pytorch
```
$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ak711/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory

```

**Comment by soumith** [comment]
your `cudatoolkit` from anaconda is build 2, which had a bug. Anaconda team fixed this in build 3. Do this: `conda install cudatoolkit`, and that should install build 3.

**Comment by arinbjornk** [comment]
@soumith Fantastic, that was it. Thanks for the quick response.

**Comment by thebeancounter** [comment]
Not working for me...

**Comment by wfedorko** [comment]
Hi,
I am experiencing the same issue now with pytorch 1.0.0 and cuda 10.
I did a pip pytorch install since that works better with my workflow and the system I am using...
`
$ python
Python 3.6.3 (default, Dec  4 2017, 16:33:31) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wfedorko/.local/lib/python3.6/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory
` 

Any help very appreciated...

**Comment by pdeperth** [comment]
Same with pytorch 0.3.0, cuda 9.2 and python 2.7 in a conda environment.
