### ISSUE TITLE
Document on how to use ATEN_CPU_CAPABILITY

### ISSUE THREAD

**Issue by derneuere** [pytorch/pytorch#59186]
## 🚀 Feature

It would be great if ATEN_CPU_CAPABILITY would be documented with an example on how to use it. 

## Motivation

I am currently trying to build PyTorch without AVX instructions, because I am deploying my docker image to a lot of different systems. While trying to understand how to remove AVX instructions I found ATEN_CPU_CAPABILITY. It is not clear on how to use it. 

My unanswered questions are: Does it work on runtime? Do I have build PyTorch myself and set ATEN_CPU_CAPABILITY before building? Can I pass ATEN_CPU_CAPABILITY to setup.py? How do I know if I set it the right way? Are there any wheels without AVX instructions available?

**Comment by imaginary-person** [comment]
Currently, the build process separately compiles ATen kernels for 3 vectorization levels `default`, `AVX`, and `AVX2`.

> Does it work on runtime? 

Yes, systems without `AVX2` or `AVX` will only use `default` ATen kernels at runtime, so you won't have to worry about `SIGILL`s occurring due to instructions unsupported by that system.

**Comment by derneuere** [comment]
Thank you! I looked in the wrong dependency.
