### ISSUE TITLE
typing_extensions required only for py<38

### ISSUE THREAD

**Issue by cdeepali** [pytorch/pytorch#59202]
I think `typing_extensions` is not required for python versions >3.7. 
The features of `typing_extensions` like `Literal`,  `Final`, `Protocol` and `Text` are all available in the typing module in py38.

https://docs.python.org/3/whatsnew/3.8.html#typing.

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by cdeepali** [comment]
Shall I work on a PR for this?

**Comment by rgommers** [comment]
Thanks for looking at this @cdeepali.

I'm not sure about doing this, because it's a light dependency and we may have to undo your proposed changes again if we want to use new features like `TypeAlias`, `Annotated` or `TypeGuard` that are not in Python 3.8 or 3.9.

Do you see a real-world benefit to removing the dependency on 3.8 or 3.9 right now?

**Comment by ezyang** [comment]
Agreed with @rgommers. If there isn't a problem with perpetually carrying `typing_extensions` I'd prefer to keep it around in case there are other extensions we need.

**Comment by cdeepali** [comment]
Sure, in case we are benefitting from some features that are available in `typing_extensions` and yet not available in py38 and py39, then we must keep it. 

Thanks for clarification on this @rgommers.
