### ISSUE TITLE
r.is_sparse() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by AdarshSubramaniam** [pytorch/pytorch#59916]
## 🐛 Bug

\nRuntimeError: r.is_sparse() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/sparse/SparseTensorMath.cpp:69, please report a bug to PyTorch. \n

Happens when adding 2 sparse torch.sparse tensors 

sparse_vec_gradient = (sparse_topK_gradient + M_value*sparse_randK_gradient)
Here M_value is a torch 1d tensor, sparse_topK_gradient and sparse_randK_gradient are torch.sparse dtype tensors. 

## To Reproduce

1. Code is too big to upload 
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @nikitaved @pearu @cpuhrsch @IvanYashchuk

**Comment by soulitzer** [comment]
Could you provide a small snippet to reproduce this issue @AdarshSubramaniam ?

**Comment by IvanYashchuk** [comment]
The error is raised for `0d_tensor * sparse_coo`, it works fine for `sparse_coo * 0d_tensor`:
```python
In [1]: import torch
In [2]: i = [[0], [1]]
In [3]: v = [5.0]
In [4]: s = torch.sparse_coo_tensor(i, v, (2, 3))
In [5]: s
Out[5]: 
tensor(indices=tensor([[0],
                       [1]]),
       values=tensor([5.]),
       size=(2, 3), nnz=1, layout=torch.sparse_coo)
In [6]: 2.0 * s
Out[6]: 
tensor(indices=tensor([[0],
                       [1]]),
       values=tensor([10.]),
       size=(2, 3), nnz=1, layout=torch.sparse_coo)
In [7]: s * 2.0
Out[7]: 
tensor(indices=tensor([[0],
                       [1]]),
       values=tensor([10.]),
       size=(2, 3), nnz=1, layout=torch.sparse_coo)
In [8]: s * torch.tensor(2.0)
Out[8]: 
tensor(indices=tensor([[0],
                       [1]]),
       values=tensor([10.]),
       size=(2, 3), nnz=1, layout=torch.sparse_coo)
In [9]: torch.tensor(2.0) * s
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-b35d34d51f46> in <module>
----> 1 torch.tensor(2.0) * s

RuntimeError: r.is_sparse()INTERNAL ASSERT FAILED at "../aten/src/ATen/native/sparse/SparseTensorMath.cpp":53, please report a bug to PyTorch. 
```

**Comment by mattip** [comment]
The failure is in the allocation of the output type: a non-sparse Tensor is allocated.

**Comment by mattip** [comment]
xref #3158 about sparse-dense mutliplication. It seems multiplication works differently than addition:
```
>>> s = torch.sparse_coo_tensor([[0, 1], [0, 0]], [1.0, 2.0], (2, 1)
>>> t = torch.tensor([[0], [1]])
>>> t + s
tensor([[1.],
        [3.]])
>>> s + t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: add(sparse, dense) is not supported. Use add(dense, sparse) instead.
```

but `t * s` and `s * t` fail with a 
<details>
<summary> unhelpful error message </summary>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: Could not run 'aten::_nnz' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_nnz' is only available for these backends: [SparseCPU, SparseCUDA, SparseCsrCPU, SparseCsrCUDA, BackendSelect, Python, Named, Conjugate, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

SparseCPU: registered at aten/src/ATen/RegisterSparseCPU.cpp:961 [kernel]
SparseCUDA: registered at aten/src/ATen/RegisterSparseCUDA.cpp:1092 [kernel]
SparseCsrCPU: registered at aten/src/ATen/RegisterSparseCsrCPU.cpp:202 [kernel]
SparseCsrCUDA: registered at aten/src/ATen/RegisterSparseCsrCUDA.cpp:229 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:38 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:118 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradMLC: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:11202 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_2.cpp:10254 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:446 [backend fallback]
Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:285 [backend fallback]
Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
</details>
