### ISSUE TITLE
add `--init_method` to `torch.distributed.launch`

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#59978]
## 🚀 Feature

This is a request to add a `--init_method` option to `torch.distributed.launch`.

## Motivation

I'm currently dealing with  "Address already in use" in a tests suite which runs tests concurrently, so the default port doesn't work. Trying to use random ports isn't great for tests either, since they could still clash and tests fail. So I was thinking that switching to `init_method='file:///path/to/tempfile.randomfile',` would be a perfect solution since we can ensure that `tempfile` will generate a truly unique file system-wide (this is one node tests).

but `torch.distributed.launch` doesn't have this option - it only support `env://`

So the test could do:
```
import tempfile
f = tempfile.NamedTemporaryFile()
cmd = f"python -m torch.distributed.launch --init_method=file://{f.name} --nproc_per_node=2 ..."
```

Thank you!

I also tried to solve the problem of autofinding a free port in https://github.com/pytorch/pytorch/pull/52482 but I failed to find a solid solution.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by cbalioglu** [comment]
Hey Stas,

Obviously my first suggestion would be to run your tests sequentially, but I assume for one reason or another this is not possible in your case. Having said that, be aware that we plan to deprecate `torch.distributed.launch` in the near future. With PyTorch v1.9 we upstreamed TorchElastic to PyTorch and introduced a new `torch.distributed.run` script that also supports elasticity. Please take a quick look at its [documentation](https://pytorch.org/docs/1.9.0/elastic/quickstart.html) before reading the rest of my comment since some of my suggestions require familiarity with the new `torch.distributed.run` script.

Coming back to your problem, there are four potential solutions that I can think of:

1) #59719 will most likely address your concern in a very similar way you proposed here. It will allow you to specify a `FileStore` as a "rendezvous endpoint" in `torch.distributed.run`. Unfortunately this PR couldn't make the v1.9 cut, so won't be included in the official v1.9 release. However once merged you will be able to run your script similar to:

```bash
python -m torch.distributed.run
        --nnodes=<world_size>
        --nproc_per_node=<workers_per_node>
        --rdzv_id=<job_id>
        --rdzv_backend=c10d
        --rdzv_endpoint=<path_to_your_temp_file>
        --rdzv_conf="store_type=file"
        <your_script>.py (--arg1 ... train script args...)
```

2) Another option you will have with v1.9 is to use an etcd server/cluster as your rendezvous endpoint. etcd is pretty lightweight and can easily be installed and run locally with a simple shell script just before you execute your test suite. Similar to the first option, the way you will run your script will be similar to:

```bash
python -m torch.distributed.run
        --nnodes=<world_size>
        --nproc_per_node=<workers_per_node>
        --rdzv_id=<job_id>
        --rdzv_backend=etcd-v2
        --rdzv_endpoint=<hostname_of_etcd_server>
        <your_script>.py (--arg1 ... train script args...)
```

Since all tests will share the same etcd server, there is no such thing as a port conflict in this case.

3) If you are using PyTorch v1.8 or earlier (and don't want to migrate to v1.9 soon), you can leverage TorchElastic. The second option was in fact upstreamed from TorchElastic to PyTorch. TorchElastic comes with a launcher script that is very similar to `torch.distributed.run` and mostly expects the same arguments. You can find its documentation [here](https://pytorch.org/elastic/0.2.2/quickstart.html).

4) If none of these suggestions work for you, yet another option might be to reserve a range of port numbers that is large enough (e.g. from 3000 to 3999) and during test time assign them sequentially to the tests to be executed. A naive bash implementation would like this:

```bash
for (( port = 300; port < 3999;  port++ )); do
  # Run in background.
  python -m torch_distributed_run --master_port=$port ... &
done

# Wait for all tests to finish.
wait
```

**Comment by stas00** [comment]
Thank you for this awesome detailed reply, @cbalioglu.

I agree that sequential run would be the simplest, but (1) it costs more $$, so distributed tests uses less time renting an instance (2) it takes longer to complete.

So there are 2 unrelated issues I'm discussing here - 1. future 2. testing with older pytorch builds

The first 2 solutions sound great, so in a sense you described an alternative solution to my requests which if it works this request can then be closed. I will study these. Thank you!

----------------

So the rest of this is how to solve it to support older pytorch - and so I'm aware that my feature request won't help with that particular issue.

The 3rd solution sounds like an unnecessary potential point of failure, when it comes to CI systems. I'd rather use the simple local filesystem via `file://`, since the test suite runs on a single node. But I'm definitely going to give it try as I'm yet to try `torchelastic` and I wanted to do it anyway. And hopefully it will work.  Thank you!

The 4th solution won't work, since the test suite has thousands of tests and only some of them are distributed and only in specific circumstances are run. i.e. it's `pytest` and a bash shell. Here what's need is some sort of param server, which controls and returns a free port to each test client upon request.

**Comment by stas00** [comment]
If someone needs here is a much simpler solution specific to `pytest-xdist` port collision:
```
def pytest_xdist_worker_id():
    """
    Returns an int value of worker's numerical id under ``pytest-xdist``'s concurrent workers ``pytest -n N`` regime,
    or 0 if ``-n 1`` or ``pytest-xdist`` isn't being used.
    """
    worker = os.environ.get("PYTEST_XDIST_WORKER", "gw0")
    worker = re.sub(r"^gw", "", worker, 0, re.M)
    return int(worker)


def get_torch_dist_unique_port():
    """
    Returns a port number that can be fed to ``torch.distributed.launch``'s ``--master_port`` argument.

    Under ``pytest-xdist`` it adds a delta number based on a worker id so that concurrent tests don't try to use the
    same port at once.
    """
    port = 29500
    uniq_delta = pytest_xdist_worker_id()
    return port + uniq_delta
```

**Comment by cbalioglu** [comment]
Glad that I could help! Let us now in case you have further questions, or if you have any feedback about the new `torch.distributed.run` script.

**Comment by stas00** [comment]
As mentioned in the earlier comment, you have already answered my feature requests, so this ticket can be closed.

Thanks again, @cbalioglu
