### ISSUE TITLE
Adam Optimizer Implemented Incorrectly for Complex Tensors

### ISSUE THREAD

**Issue by allevitan** [pytorch/pytorch#59998]
## 🐛 Bug

The calculation of the second moment estimate for Adam (`torch.optim.Adam`) assumes that the parameters being optimized over are real-valued. This leads to unexpected behavior when using Adam to optimize over complex-valued parameters. AdamW, Adadelta, and potentially other Adam-related optimizers are affected as well. 

The issue is that variance is currently estimated from `param.grad * param.grad`, but for complex numbers the appropriate calculation is `param.grad * param.grad.conj()`, a.k.a. `t.abs(param.grad * param.grad)`. As currently implemented, the variance estimate is complex-valued, which causes unexpected behavior and prevents convergence in almost all cases when optimizing over complex parameters. The properly calculated variance remains real-valued, even for complex-valued parameters, and behaves as expected across both real and complex-valued parameters. The original source noting this issue and the fix, as far as I am aware, is [Andy Saroff's Dissertation](https://digitalcommons.dartmouth.edu/dissertations/55).

## To Reproduce

The following script demonstrates a simple optimization problem where the as-implemented version of Adam fails:

```python
import torch as t
from matplotlib import pyplot as plt

complex_param = t.tensor([1],dtype=t.complex64, requires_grad=True)

# We will optimize on the mean squared error from a 1j
target = 1j

def calc_loss(x):
    return t.abs(x - target)**2

optimizer = t.optim.Adam([complex_param], lr=0.001)

n = 10000
values = t.zeros(n, dtype=t.complex64)
for i in range(n):
    optimizer.zero_grad()
    loss = calc_loss(complex_param)
    loss.backward()
    optimizer.step()
    values[i] = complex_param.detach()


# Plot the results
plt.plot(values.real, label='Real Part')
plt.plot(values.imag, label='Imaginary Part')
plt.legend()
plt.xlabel('Iteration')
plt.ylabel('Complex Parameter')
plt.title('Optimization Progress with as-implemented Adam')
plt.show()
```

This script produces the following plot:

![Screen Shot 2021-06-14 at 7 22 12 PM](https://user-images.githubusercontent.com/3151604/121971071-e3031680-cd45-11eb-87e0-8f9a945b6207.png)

## Expected behavior

The optimization process should show convergence, as in the following plot, generated after applying the correction below:

![Screen Shot 2021-06-14 at 7 24 59 PM](https://user-images.githubusercontent.com/3151604/121971243-4c832500-cd46-11eb-94c1-d2b78a78b596.png)

A simple (but almost certainly not optimal) correction can be applied at line 87 of `torch.optim._functional` [here](https://github.com/pytorch/pytorch/blob/5e993e6c81202ad6c734196f158bb13daab0d5df/torch/optim/_functional.py#L87), by changing:

```python
exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)
```

to

```python
exp_avg_sq.mul_(beta2).addcmul_(grad, grad.conj(), value=1 - beta2)
```

## Environment

This is likely not relevant to this issue, but in the interest of completeness:

PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.1.0
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.33

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.12.6-arch1-1-x86_64-with-glibc2.33
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA Quadro P6000
Nvidia driver version: 465.31
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.2.0
/usr/lib/libcudnn_adv_infer.so.8.2.0
/usr/lib/libcudnn_adv_train.so.8.2.0
/usr/lib/libcudnn_cnn_infer.so.8.2.0
/usr/lib/libcudnn_cnn_train.so.8.2.0
/usr/lib/libcudnn_ops_infer.so.8.2.0
/usr/lib/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.17.2           py37haad9e8e_0  
[conda] numpy-base                1.17.0           py37hde5b4d6_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1

## Additional context

The same issue was noted by a user in the tensorflow bug tracker [here](https://github.com/tensorflow/tensorflow/issues/38541), although the tensorflow maintainers ultimately declined to implement the fix due to maintenance implications.

Currently, the pytorch documentation states that [...all the existing optimizers work out of the box with complex parameters](https://pytorch.org/docs/stable/complex_numbers.html#autograd), so if it is not possible to implement a fix, the documentation should at least be updated to highlight this issue.

I am happy to work on implementing a permanant fix for this issue, although I don't have the relevant expertise to make sure it is done in a robust and optimized fashion.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @vincentqb @iramazanli

**Comment by ezyang** [comment]
Is this literally as simple as dropping in a `conj()` call inside the optimizers? If so we're happy to take it. If there are other complex problems in other optimizers, we would also like to fix all of them, whenever the fix is just making the real code generalize correctly to complex domain (but otherwise stay unchanged in the complex domain).

**Comment by allevitan** [comment]
I believe it is as simple as that, although this may not be the most stable or performant way to make the change because `param.grad * param.grad.conj()` will still calculate the imaginary part even though it is guaranteed to be zero.

**Comment by ezyang** [comment]
@allevitan This is true on master, but actually we can optimize this case automatically because `conj()` doesn't actually compute the conjugate directly, it delays it so that multiplication can be taught to do a fused kernel when it sees `x * x.conj()`. @anjali411 this is another good one to make sure we hit for conjugate view payoff.

**Comment by allevitan** [comment]
If I were interested in submitting a fix for this, what would be the correct next steps?

**Comment by ezyang** [comment]
Open a PR with the one line change you suggested, and a new test in `test/test_optim.py` that shows that complex optimization works OK after this change.

**Comment by remifan** [comment]
It's great to see more interest in proper optimizations of complex variables! Unfortunately, TF's maintainers had no plan to push forward this part when I raised that [issue](https://github.com/tensorflow/tensorflow/issues/38541).
There are so many Science and Engineering disciplines that work on complex numbers. I think ML will make bigger impacts if efforts are made to cater to more communities.

There also exist some practices and discussions under this topic in JAX's community:
[JAX's doc on complex numbers](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#complex-numbers-and-differentiation)
[convention of gradient on complex numbers](https://github.com/google/jax/issues/4891#issuecomment-821268608)

I have adapted some optimizers to handle complex variables, though they are written in JAX but should be still readable. Hope this can help a bit.
(https://github.com/remifan/commplax/blob/dd8890c04c1e1545ee4132e4c4c8968f742e3d00/commplax/cxopt.py#L191)

**Comment by weissercn** [comment]
This is a very important bug catch relevant to a project I am working on. What do you think is the timeline for the implementation of a solution?

**Comment by iramazanli** [comment]
Hey ! Thanks for pointing this bug. I will analyze this issue this week.

**Comment by weissercn** [comment]
Thank you, @iramazanli !

**Comment by Lezcano** [comment]
@iramazanli Note that this problem is present in many other optimisers as well. I've checked a few and it's at least in `adamW`, `adagrad`, `rmsprop` and `adadelta` (see all the appearances of `addcmul` in the optimisers file)

**Comment by allevitan** [comment]
Sorry for the wait on putting together a pull request for this, I will finally have time to work on this this week.

I believe @Lezcano is correct about the other affected optimizers. In addition, it seems that there are further optimizers which do not work on complex-valued parameters, but for different reasons. I know L-BFGS, for instance, doesn't work, but I haven't done a comprehensive search.

Given this, would it be appropriate to include an edit to the documentation on [Autograd for Complex Parameters](https://pytorch.org/docs/stable/notes/autograd.html#complex-autograd-doc) to note that complex numbers will work with all optimizers **when used as an intermediate step in calculations**, but that not all optimizers are will work on leaf tensors which are complex valued? Could it even be appropriate to cause optimizers which either haven't been updated for complex numbers, or don't have a natural extension to the complex domain, to throw an exception or a warning when used to optimize over a complex parameter?

Finally, it might also be helpful to note in the documentation the tried-and-true trick of optimizing on the real and imaginary parts separately, i.e. defining and optimizing over two leaf tensors `myparam_real` and `myparam_imag`, such that `myparam = t.complex(myparam_real, myparam_imag)`. This enables one to use optimizers that only work on real-valued parameters, at the cost of losing some information about the structure of the problem.

**Comment by Lezcano** [comment]
L-BFGS should work on complex values when implemented properly. We should fix this as well. Perhaps @iramazanli could look into this as well?

Correcting all these things should not be too difficult, so I believe it's best to correct them and having them working as expected by default rather than editing the documentation to note that they do not work.

**Comment by iramazanli** [comment]
Thank you for all these comments, yes i have noticed that we indeed need to fix the way we compute the variance in these mentioned optimizers. ( and i will check L-BFGS as well) 

Before going ahead and fixing this issue, i would want to have the following discussion. I am interested in keeping optimizers mathematically rigorous. I can see that in the posted plots we already have experimental proof that indeed Adam optimizer optimizes real part of the complex function.

What is the precise setting on complex optimization ? 

Do we always want to optimize real part of functions, or there exists some norm ( L_2 or L_1) we want to focus on optimizing ?  

In the paper https://arxiv.org/pdf/1412.6980.pdf  authors proving convergence in Real numbers, with the assumption of convexity. Is there any similar paper that does analysis for complex numbers in a convenient setting ? (if not do you think you can provide me setting, so I myself can go ahead and adjust the proof in Adam to new setting)

**Comment by Lezcano** [comment]
All these papers come from Adagrad (see Duchi's paper that introduces it). The squred term is a diagonal approximation to multiplying by the inverse of a squared Hessian. When taking the diagonal approximation you end up with some squared terms. In the complex setting, this accounts for computing the squared norm, which is given by `z * z.conj()`.

**Comment by Lezcano** [comment]
@iramazanli About the optimisation setting yes, we always optimise functions onto the reals. In particular, we treat the real and imaginary part of the complex tensor as "two separate real tensors".

In more mathy terms "we see C^n as a real vector space and we compute the gradients with respect to its real structure, i.e. the canonical real inner product". I just finished writing a document that explains all this formalism starting from basic principles. If you are interested pop me a message on pytorch slack and I can share it with you :)

**Comment by avitase** [comment]
I do 100% agree with @Lezcano but maybe it helps to rephrase the argument a bit: Assuming that the target of our optimization is a real-valued scalar (otherwise the optimization goal is ill-defined) our goal is to change all free parameters of the model such that this scalar becomes minimal. If parameters happens to be complex this only means that they have 2 degrees of freedom rather than one but there are no constraints which would require us to not deal with them as two separate values. Being "real" or "complex" _only_ matters when both types collide during calculation but this not affects the optimization. Alternatively, every complex value can always be replaced by a tuple of two real values. During calculations we then have to wonder what, for instance, the product of two such tuples is, but again, this is nothing what changes the way the optimization procedure works.

**Comment by iramazanli** [comment]
I agree with you guys, and i would want to express my thanks to everyone who participated in this discussion.

I will go ahead and fix this bug. An additional nice next step would be to add a little bit information regarding complex optimizers in the optimizers documentation. I am happy to receive PR's regarding documentation in the following weeks before going ahead and adding myself.

**Comment by allevitan** [comment]
I'm glad this is reaching a resolution, and my apologies for not having sent out a PR with the updated optimizers - I've had issues getting the tests running properly in my environment.

I think it's worth elaborating slightly on what @Lezcano said, with an eye toward what information should be put in the docs. If I understood correctly, Lezcano noted that the traditional way of doing this kind of optimization with complex parameters is to optimize over the (real-valued) real and imaginary parts. This is what I've seen done almost universally in the literature in my field as well.

However, we should probably note that using the Adam optimizer directly on a complex-valued parameter (as defined above) is *not* the same as optimizing on the real and imaginary parts separately using Adam. When used on complex parameters, a single (real-valued) estimate of the variance of the (complex-valued) gradients is calculated, which is the sum of the variances in the real and imaginary channels. When optimizing over the real and imaginary parts separately, a separate variance is estimated for the real and imaginary parts.

Using Adam to optimize directly on complex variables makes sense for problems which do have a genuinely complex structure, but I think it's going to be key to note in the docs that (1) lots of historical work is done by separately optimizing on the real and imaginary parts, and (2) optimizing directly on complex-valued parameters may not be equivalent, depending on the optimizer.

**Comment by remifan** [comment]
I agree with @allevitan, as supplementary info to note(2), most complex variables in my field(optics) cannot be trivially treated as 2 independent real variables, instead, they are connected by [Kramers–Kronig relations](https://en.wikipedia.org/wiki/Kramers%E2%80%93Kronig_relations) which also apply to some other fields AFAIK.

 In such cases, to implement a true gradient descent algorithm, one might need to know metric tensor to get "natural gradient" as stated in the literature [Shun-ichi Amari 1998](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.452.7280&rep=rep1&type=pdf) and [Ken Kreutz-Delgado 2009](https://arxiv.org/abs/0906.4835). 

With minimal changes of codes, `grad*grad.conj()` is an okay/safe default but needs further domain-specific treatment by the users themselves for better results.

**Comment by Lezcano** [comment]
You are completely right @allevitan!

Now the question that comes to mind is, how come we do not do adam component-wise for complex tensors? I believe that a correct implementation would continue seeing C as R^2, so rather than doing `z*z.conj()` we should do `z = (a, b)` and compute `(a^2, b^2)`. Could you implement this splitting the complex tensor into their real and complex parts (I can help if you find any problems) and plot the resulting loss for that problem? I would assume that it should never be no worse, and if anything better than the one we observe when doing `z*z.conj()`.

**Comment by remifan** [comment]
@Lezcano If I understood correctly, when we treat `z = (a, b)`, I think it implies not just replacing `z*z.conj()` with something like `z.real**2 + 1j * z.imag**2` but also similarly adapting the rest computations (like `m_ema/sqrt(v_ema + eps)`) to be `R`-wise equivalent?

**Comment by Lezcano** [comment]
I think that that should be a better solution, yes, but it would be good to confirm this with the script that @allevitan provided in the OP.

The way I see this is that, when it comes to optimisation and gradient methods, the complex structure is irrelevant. As such, we just care about the real structure of the problem. We just clamp together two parameters and we provide some algebraic manipulations for them (complex multiplication and so on) because it is useful in some fields but, to the eyes of autograd, this is should be as transparent as it is to concatenate two tensors and treat it as "one big tensor of twice the dimension".

**Comment by remifan** [comment]
I agree with @Lezcano, then Adam becomes Domain agnostic which should be least controversial. So in terms of implementations, to avoid struggling with operators, it needs slightly more efforts, for example, to first split grad argument (should be complex-valued variable returned by Autograd by definition?) to 2 parts which are then mapped by original Adam seperately before combined as complex number and update.

**Comment by albanD** [comment]
One plausible end-state I would see here is:
- Optimizers, when given complex numbers, perform their update following the complex structure.
- We have a simple way (that we explicitly document) to perform computation on the complex space as if it was a R^2 space.

In particular, this can be done with a simple parametrization that will make the Parameter we optimize over is a real valued Tensor and the Module works with a complex Tensor.

**Comment by Lezcano** [comment]
After an offline discussion with @albanD, we were discussing that the correction `z * z.conj()` might just not be the right one, but rather that "Optimizer on complex tensors should behave the same way are if they were running on two real tensors".

The reasons for this choice are best explained via an example:
One way of implementing a network with complex tensors is to use the dtype `torch.complex64`. Another way is to just instantiate for every complex parameter two real parameters. Then, one would have to reimplement most operations. For example you would need to write ` torch.mm((A, B), (C, D)) = (AC-BD, AD+BC)` and so on. Now, the results and gradients that you would get if you write your network in either of these two ways are exactly the same. As such, the behaviour of the optimisers on these two networks should be the same, as they are computing exactly the same values and have the same gradients. It is for this reason, that optimisers should see complex parameters as pairs of real parameters. This also explains why this approach is preferred over the `z*z.conj()` approach. 

A more technical explanation can be found in these comments: https://github.com/pytorch/pytorch/issues/59998#issuecomment-877421918 https://github.com/pytorch/pytorch/issues/59998#issuecomment-879105401

We would like the input from the people here, and if it seems reasonable, we will implement it throughout PyTorch.

**Comment by avitase** [comment]
> After an offline discussion with @albanD, we were discussing that the correction `z * z.conj()` might just not be the right one, but rather that "Optimizer on complex tensors should behave the same way are if they were running on two real tensors".
> 
> The reasons for this choice are best explained via an example:
> One way of implementing a network with complex tensors is to use the dtype `torch.complex64`. Another way is to just instantiate for every complex parameter two real parameters. Then, one would have to reimplement most operations. For example you would need to write ` torch.mm((A, B), (C, D)) = (AC-BD, AD+BC)` and so on. Now, the results and gradients that you would get if you write your network in either of these two ways are exactly the same. As such, the behaviour of the optimisers on these two networks should be the same, as they are computing exactly the same values and have the same gradients. It is for this reason, that optimisers should see complex parameters as pairs of real parameters. This also explains why this approach is preferred over the `z*z.conj()` approach.
> 
> A more technical explanation can be found in these comments: [#59998 (comment)](https://github.com/pytorch/pytorch/issues/59998#issuecomment-877421918) [#59998 (comment)](https://github.com/pytorch/pytorch/issues/59998#issuecomment-879105401)
> 
> We would like the input from the people here, and if it seems reasonable, we will implement it throughout PyTorch.

This seems indeed one of these rare occasions where opposite opinions can both be valid at the same time. However, in terms of a general purpose ML framework such as PyTorch, I think it is the best **default** behavior to treat complex parameters as a tuple of real numbers contributing two independent DoF. @Lezcano did a good job in explaining what I tried to phrase in https://github.com/pytorch/pytorch/issues/59998#issuecomment-878890409. What if we make the `z*z.conj()` an alternative implementation which can be toggled with a flag?

**Comment by allevitan** [comment]
I don't have a particularly strong opinion about this, but I think there are a few further notes worth considering:

1) Using the variance `z*z.conj()` has the nice property that it will perform equally well, regardless of the phase (argument) of the optimal value of z. When we use Adam on a tuple of real/imaginary parts, the performance of the algorithm will be different when optimizing around, say, sqrt(2) as compared to 1 + 1j, because Adam throws out all information about correlations in the variance between different parameters. In other words, the choice of "basis" for representing the complex number affects the results. If this is done behind the scenes, it could cause unexpected behavior for users who would expect the properties of their optimization to be independent of the overall phase of their result.
 
2) It is possible to implement the "optimize on a tuple of real parameters" method as a user more simply than the approach described by @Lezcano above. One sets`complex_tensor = t.complex(real_part, imaginary_part)` as the first step, and all further operations can piggyback on the complex arithmetic implementation in pytorch. This is the workaround I am currently using for, e.g., L-BFGS optimization on complex tensors in my research code.

I suppose the major advantage of the "treat all complex parameters as two real parameters" approach, from my perspective, is that it would definitely workwith *every* optimizer, even if for some optimizers there are better implementations available that better respect the structure of the complex variables. I don't have a great understanding of how this would be implemented behind the scenes, but is the idea envisioned by @Lezcano, @albanD, and @avitase one that would be able to easily map across all optimizers, not just Adam?

**Comment by iramazanli** [comment]
My observations to the point is indeed PyTorch complex optimization had problem with Adam, as we used to multiply gradient with a complex number in the last step - updating parameter part of optimization

It could be shown that, it is necessary to multiply gradient always with a real number instead of complex when we are updating parameter no matter domain we are working is complex or not (any generalized space). In that respect we still need to fix bugs in AdaDelta, RMSProp, NAdam, Radam and AdamW.

I agree with @allevitan  there is a slight difference between approaching problem as complex optimization in C^n and and real optimization in R^2n. I also agree with @Lezcano that it seems slightly more safe to work on R^2n than C^n as Adam already has good performance record on real datasets, but i don't know how correct would it be calling resulting algorithm via R^2n mapping as Adam. To my understanding, generalizing a mathematical concept / algorithm generally requires metrics used in the simpler case to be consistent with the generalized case. Which looking in this perspective suggests maybe preserving complex structure inside optimizers could be a good option ?

**Comment by danmackinlay** [comment]
A keyword we might be looking for here is  _Wirtinger calculus_. This is a pretty standard convention for optimising wirt to complex arguments in the signal processing community - see e.g. [here](https://onlinelibrary.wiley.com/doi/10.1002/0471439002.app1) or [here](https://arxiv.org/pdf/1005.5170.pdf) for background. **tl;dr** if we want to get a complex gradient of $f$ wrt some complex argument $\frac{\partial f(z)}{\partial z}$ which behaves as similarly to the real one as possible, it is natural to consider gradients wrt $\frac{\partial f(z)}{\partial z^*}$, i.e. the conjugate of $z$ also, and then analogues for all the usual rules for derivatives pop out nicely. Or, at least, _nicer_ than if we had done it in terms of $\operator{Re}(z)$ and $\operator{Im}(z)$.

(Blech that is ugly, sorry. I thought we supported math markup in gihub markdown. Apparently not.)

**Comment by boeddeker** [comment]
Maybe another idea, to find a reasonable choice, how optimizers could be implemented is viewing at alternatives to NNs and how the community addressed this problem. Many other areas started much earlier to think about complex numbers.

I had a lecture about adaptive filters. In that area, also complex numbers are used and because of the adaptive part, they often need thinks like momentum and normalization too.

I found one free example online, that could be used for inspiration of an implementation (Maybe others know more?):
https://en.wikipedia.org/wiki/Least_mean_squares_filter#Normalized_least_mean_squares_filter_(NLMS)
There the normalization is done with the "x*x.conj()". This is an indicator, that, at least some, people use this concept, when they aren't constraint by the software (That people optimize the real and imag part in NNs is simply motivated that it can be executed).

Maybe someone reads this, who knows more about adaptive filters and complex numbers and can contribute more know how.

**Comment by Lezcano** [comment]
Note that the expression `x*x.conj()` is just the norm on the complex numbers so it is natural for it to pop up as regularisers or places where you need a norm.

On the Wirtinger calculus, note that this is just a different explanation on C^n  for the usual calculus of Riemannian geometry via metrics and adjoints (only that the latter one works also for more general spaces). See https://github.com/pytorch/pytorch/issues/59998#issuecomment-896933501 for a non-technical explanation and https://github.com/pytorch/pytorch/issues/59998#issuecomment-877421918 for a more technical one. The keywords for this in the literature are "Riemannian geometry" / "adjoint method". Examples of relevant manifolds are the complex unitary group U(n), the special unitary group SU(n) or the complex Stiefel manifold St_k(C^n). From these three, the first and the third are (real) Riemannian manifolds, but they are *not* complex Riemannian manifold (i.e. Kähler manifolds). Nonetheless, one can compute derivatives on all these manifolds. For example, we do so when we compute the derivatives for the SVD or the QR decomposition.

**Comment by remifan** [comment]
> Maybe another idea, to find a reasonable choice, how optimizers could be implemented is viewing at alternatives to NNs and how the community addressed this problem. Many other areas started much earlier to think about complex numbers.
> 
> I had a lecture about adaptive filters. In that area, also complex numbers are used and because of the adaptive part, they often need thinks like momentum and normalization too.
> 
> I found one free example online, that could be used for inspiration of an implementation (Maybe others know more?):
> https://en.wikipedia.org/wiki/Least_mean_squares_filter#Normalized_least_mean_squares_filter_(NLMS)
> There the normalization is done with the "x*x.conj()". This is an indicator, that, at least some, people use this concept, when they aren't constraint by the software (That people optimize the real and imag part in NNs is simply motivated that it can be executed).
> 
> Maybe someone reads this, who knows more about adaptive filters and complex numbers and can contribute more know how.


Adaptive filtering is something a bit different since it's not a traditional optimizaiton problem(we could intuitively say its loss surface is stochastic) but also a task to track a dynamic system. For example, real-valued adaptive filtering in a rapidly changing system, the value of "instant gradient" is sometimes less imformative but its signs are often good enough since the direction of the "instant gradient" tells at last moment is questionable if the "loss surface" changes at next moment. I tend to treat the NLMS in adaptive filtering as an effective controlling machanisim. There exist other theoretical frameworks (RLS, Kalman...) which might better solve it from different perspectives. In a word, how the complex number is treated there is rather practice-based decison from my experiences. 

The discussion here is growing to become an informal reference👍. Though there are divergences on how the CR optimization is made, I think treating a complex number as a pair of real values, as suggested by @Lezcano, is a sensible default setting to make optimizers working on complex numbers out-of-the-box regardless of the optimizers in use, which is what this issue is originally about. At the end of the day, we may use domain-specific solutions for our own interests and targets.

**Comment by Kharitok** [comment]
Hi! 

What is the proper way to work with complex-valued optimization in PyTorch now then  -  to use @allevitan approach and just construct all complex-valued parameters from two real ones or just use the hand-patched  _functional.py version?
Cause, if I understand it correctly this issue is not yet patched on master.

I'm working on AD-powered phase-retrieval and before used R^2 tensors and my own crude implementation of the complex arithmetic, but I've recently switched to PyTorch 1.91 and so to proper complex tensors representation and also observe the lack of convergence with most of optimizers now.

**Comment by Lezcano** [comment]
As it stands, yes, you need to define your parameters as noted in https://github.com/pytorch/pytorch/issues/59998#issuecomment-874782743 until this issue is fixed.

**Comment by Lezcano** [comment]
For anyone here, @albanD opened a tracking issue (https://github.com/pytorch/pytorch/issues/65711) to have this fixed. We would very much welcome contributions in this area from anyone interested.

The fixes should not be too difficult and they are all in the Python side of the project, so this could be a good first issue for anyone willing to contribute to PyTorch :)

**Comment by Akira-exo** [comment]
Hello everyone,

I have a question related to Optimization of Complex Valued Variables, does the pytorch.optim.lbfgs implementation not support Complex Tensors?
My model with Complex Leaf Tensors that works with all other torch optimizers (ADAM, SGD etc.) throws the following error with torch.lbfgs -->


`"gt_cuda" not implemented for 'ComplexDouble'`

**Comment by lezcano** [comment]
See https://github.com/pytorch/pytorch/issues/86340

**Comment by jiezhangMars** [comment]
great
