### ISSUE TITLE
USE_SYSTEM_GLOO: The dependency target "gloo_cuda" of target "c10d" does not exist.

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#60270]
## 🐛 Bug

When trying to build PyTorch with `USE_SYSTEM_GLOO`, I encounter a CMake error:
```
CMake Error at torch/lib/c10d/CMakeLists.txt:104 (add_dependencies):
  The dependency target "gloo_cuda" of target "c10d" does not exist.
```

## To Reproduce

1. Build your own gloo
1. `export USE_SYSTEM_GLOO=ON`
1. `python setup.py install`

## Expected behavior

I would expect to be able to use a system installation of gloo.

## Environment

 - PyTorch Version: 1.9.0
 - OS: Linux (Ubuntu 18.04)
 - How you installed PyTorch: `spack`
 - Build command you used: `python setup.py install`
 - Python version: 3.8.10
 - CUDA/cuDNN version: 10.1.243/8.0.5.39
 - GPU models and configuration: K80 (sm_37)

## Additional context

My gloo installation is built with CUDA support. PyTorch finds the right installation prefix:
```
Found gloo: /home/t-astewart/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/gloo-2021-05-04-brcgtbkgrqt3shkmvz46m56gzrqunbdh/lib/libgloo.a
```
In this same directory, there is a `libgloo_cuda.a` static library.

* [build log](https://github.com/pytorch/pytorch/files/6677760/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/6677762/spack-build-env.txt)

This bug doesn't seem to affect the `master` branch. It also doesn't occur when I use the git submodule for gloo instead of using `USE_SYSTEM_GLOO`.

cc @malfet @seemethere @walterddr @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by lw** [comment]
> This bug doesn't seem to affect the master branch.

This is odd, since I'm not seeing any recent changes in the code that should be responsible for this. Would you mind double-checking?

BTW, that code is [here](https://github.com/pytorch/pytorch/blob/0c916c8a4e94c50ae65c2acdfed348cb94bd26de/cmake/Dependencies.cmake#L1330-L1340) and indeed it seems that when `USE_SYSTEM_GLOO` is set we only load the `gloo` library and not `gloo_cuda` nor `gloo_hip`. That should be easy to fix. (Though it's unlikely this fix will be backported to v1.9, hence if it's already somehow fixed in master then there's nothing we can do).

**Comment by adamjstewart** [comment]
> Would you mind double-checking?

Just tried again, I see the `gloo_cuda` error on 1.9.0 but not on master.

**Comment by lw** [comment]
Well, on one hand this is good news, on the other hand I think this means there's nothing we can do here: this probably doesn't raise to the bar justifying a backport fix to 1.9...

**Comment by adamjstewart** [comment]
That's fine. If anyone figures out which commit changed this behavior, let me know and I'll add a patch to our [Spack](https://spack.io) package.

**Comment by malfet** [comment]
@adamjstewart what was the last version when it worked for you? Your build most likely fails due to this dependency:
https://github.com/pytorch/pytorch/blob/e7cd59c7a061c78d8d0265e4308b5933e44f9176/torch/lib/c10d/CMakeLists.txt#L79-L81

But it's been there since 1.4 or even older. I guess this could be worked around by modifying conditions to something like `if(USE_CUDA && NOT USE_SYSTEM_GLOO)`

**Comment by adamjstewart** [comment]
I've actually never tried building with a system gloo installation before now. Even if I build gloo with CUDA support I still get the same error message.

**Comment by adamjstewart** [comment]
The diff for that file looks like:
```diff
diff --git a/torch/lib/c10d/CMakeLists.txt b/torch/lib/c10d/CMakeLists.txt
index 3c11526f0c..3e93108e2a 100644
--- a/torch/lib/c10d/CMakeLists.txt
+++ b/torch/lib/c10d/CMakeLists.txt
@@ -114,15 +115,15 @@ target_include_directories(c10d PUBLIC
 target_include_directories(c10d PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/..)
 
 if(USE_C10D_NCCL)
-  target_compile_definitions(c10d INTERFACE USE_C10D_NCCL)
+  target_compile_definitions(c10d PUBLIC USE_C10D_NCCL)
 endif()
 
 if(USE_C10D_MPI)
-  target_compile_definitions(c10d INTERFACE USE_C10D_MPI)
+  target_compile_definitions(c10d PUBLIC USE_C10D_MPI)
 endif()
 
 if(USE_C10D_GLOO)
-  target_compile_definitions(c10d INTERFACE USE_C10D_GLOO)
+  target_compile_definitions(c10d PUBLIC USE_C10D_GLOO)
 endif()
 
 copy_header(FileStore.hpp)
```
Could that be the fix? I don't know CMake very well.

**Comment by adamjstewart** [comment]
Might still be broken in 1.9 but works great in 2.1 so I think we can close this. Note that if PyTorch is built with CUDA support, gloo must also be built with CUDA support or linking fails.
