### ISSUE TITLE
Tuning `SumKernel` for Float16 on CPU with AVX512 vectorization

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#60337]
## ❓ Questions and Help

Hello,

`SumKernel` in the CPU implementation has been implemented with pairwise addition, and uses some tunable _knobs_,
such as `ilp_factor` (which seems to mean Instruction level parallelism, perhaps?), whose documentation isn't present in the comments. If I use the current `SumKernel` implementation with AVX512 in #56992, then the output of sum of `Float16` tensors becomes less accurate, given that sum's accuracy for `Float16` is already not very good in some cases, such as #59489. So, I'm reluctant to enable AVX512 support for it.

Can you please advise as to how to tune these parameters for Float16 with 512-bit vector-size?
Thanks!

cc @VitalyFedyunin @peterbell10 @kshitij12345

**Comment by peterbell10** [comment]
Yes, `ilp_factor` stands for instruction level parallelism. It's the number of vector accumulators that get summed in paralllel. So it's a performance optimization. In theory, the optimal value would be the add latency (clocks) divided by the inverse throughput of load + add (clocks per element). Which is roughly 4, but depends on the data type and exact CPU. I usually refer to the [intel intrinsics guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#!=undefined&text=_add_ps&techs=AVX,AVX_512&expand=139,124,3333,3336,139,136,139,136).

The summation in #59489 is so small that I can't see `ilp_factor` having any impact. More likely, the issue is that the final sum of the vector accumulator isn't done pairwise which for float16 on avx512 would be summing 32 elements.

**Comment by imaginary-person** [comment]
Thanks for your help, @peterbell10! Are there any other knobs you'd recommend tuning, as in any other changes to `SumKernel`? BTW, `nansum` for Float16 doesn't use `SumKernel` but has the [same accuracy issue](https://github.com/pytorch/pytorch/issues/59415) that Float16 has with `sum`, even with AVX2.

**Comment by imaginary-person** [comment]
Resolved with #60387.

**Comment by chandankds** [comment]
Hello @peterbell10 and @imaginary-person , While working on one of the benchmarks, I realized that most of the benchmark's time (around 98%) is spent in the sum function. With an ilp_factor of 4, I can see that the compiler uses xmm registers, but when I change it to 8, the benchmark performs much better, and ymm registers are being utilized and with 16 zmm. As @peterbell10 already pointed out, the optimum value of ilp_factor depends on the data type and the exact CPU architecture. I wanted to know --what could be the potential downsides of using a higher ilp_factor? Additionally, is it possible/good idea to detect the CPU being used at compile time and scale the ilp_factor accordingly? 
Thank you for your time and insightes, Regards, Chandan.
