### ISSUE TITLE
[rfc] optimize distributed and RPC tests in CI

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#60344]
See discussion in #60136 

Overview
==
There are several recent flakiness discovered on these distributed tests. We were wondering if we can improve they way they got launch in CI.

Status Quo
==
0. Existing test statistic shows that with the different backend/init method combination, it is one of the longest test job in machine time:

| test filename | Total machine time per commit (min) | 
| -- | --  |
| distributed/test_distributed_spawn | 121.32353 |
| distributed/test_distributed_fork | 67.34653 |
| distributed/rpc/test_tensorpipe_agent | 63.42157 |
| distributed/rpc/cuda/test_tensorpipe_agent | 39.29293 |
| distributed/rpc/test_faulty_agent | 14 |
| distributed/test_c10d_gloo | 7.41584 |
| distributions/test_distributions | 5.26263 |

1. currently distributed/rpc tests are ran expensively on "all-other" configurations in here:(https://github.com/pytorch/pytorch/blob/d8849bdb039aa4a8260466d03a36d0819bbcdc76/.jenkins/pytorch/test.sh#L518-L528). 
This means it is ran on a lot of combination of CI,
  - OS: Linux (various ubuntu releases), Win, MacOS (10.13, 10.15)
  - Device: CUDA (10/11), ROCM, CPU-only
  - Other special tags:
    - special tests: ASAN / COVERAGE / NO-ARCH
    - special devices: no-gpu/multi-gpu/no-avx
    - special parallel?: parallelnative/paralleltbb
  - special jobs: slowtest, gradcheck

2. for distributed_test_[spawn/fork], what we found in the previous issue was that distributed tests were ran against 3 different backends and 2 different init methods when running CI (on almost all eligible variance of the CI configuration)
  - init via env / file
  - backend: mpi / gloo / nccl

Pitch
==
1. Run distributed in less configurations
  - We can test less: e.g. if distributed test that fails CPU device, it is also going to fail on COVERAGE, they we should not run distributed in coverage, yes?
2. Have fine-grain control on test case or test suite level
  - We can have decorators similar to `@slowtest` that decorates a test case/suite so that it can only run on specific configuration/backend/init-method
3. spin distributed into its own job for test distributed only:
  - This way we reduce flakiness in distributed that could affect other tests within the same CI job, also will save test times.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @mruberry @VitalyFedyunin @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
I think we may be able to reduce some of the CI cost by not running both file and env tests on every distributed PR and instead only running both versions on master. The reason for this is that the initialization method is pretty abstracted away from most of our core test logic and it shouldn't affect the test correctness.

There have been bugs in the past that have come up due to differences in `init_method` though, but they are quite rare, the tradeoff being proposed here is that we'd have to revert master commits that end up not working for a specific type of init_method.

**Comment by walterddr** [comment]
Hi All, I updated the description based on some more data and analysis. 

I guess we would like more feedback from the distributed team:
1. what are the config combination that we can skip testing for the moment (for example do we really need to test against all GCC 5.4/7/9?
2. is there any test cases/suites that we can just run against the default backend instead of running against all 3?

**Comment by rohan-varma** [comment]
@walterddr and I discussed offline:

1. Probably no need to test against the different GCC versions, one is sufficient.
2. We'd prefer all backends to be tested on PRs due to important differences in implementation.
3. Currently we run file and env init method tests, we can probably just do only file on PRs.
4. We can likely only run one of test_distributed_{fork/spawn} on PRs.

**Comment by walterddr** [comment]
Yes. adding additional execution step for our discussion:

1. Move test_distributed() and test_rpc() out from https://github.com/pytorch/pytorch/blob/92f470da08b3f4fc29ff1cca8dc637ccce2c863a/.jenkins/pytorch/test.sh#L518 to its own CI job
2. provide two "ON_PULL_REQUEST" vs. "ON_MASTER_CI" behavior
  a. "ON_MASTER_CI" basically test the full set of configurations we desired for distributed. 
  b. "ON_PULL_REQUEST" only tests: (1) file init; (2) test_distributed_fork only; (3) one CUDA build and one CPU build; (4) all 3 backends (mpi, nccl on CUDA, gloo)
3. provide additional control/override
  a. when "ci/master" label is applied to PR, "ON_MASTER_CI" behavior is expected.
  b. tentatively provide a decorator such as `@testOnAllEnv` for python test cases that will test additional environment on PR (same as on master commits)

**Comment by mruberry** [comment]
Really nice write-up, @walterddr and @rohan-varma!

I like the idea of separating the distributed tests because they seem significant enough to merit their own build. Using a decorator to enforce what is and isn't tested is a great idea because we want as much logic in the test files as possible for readability and maintainability. 

One idea would be a decorator like `@testOnMainOnly`. To run tests decorated with this a user would have to set an environment variable like `MAIN=1`. This could then be triggered locally or by applying a label like "ci: main" (or whatever). This would be useful beyond distributed.

Having to apply a label like "ci: main" might be onerous when just testing distributed updates, however. And locally it might be frustrating to always have to set an environment variable to run the distributed tests. A more distributed-specific idea would be a decorator like `@distributedTargetDeterminator` that would check if running in a CI environment and additionally check if a distributed file was altered. This would be testable locally but reduce CI time significantly for PRs that don't touch files related to distributed, while distributed developers shouldn't have to do anything to their PRs to run the tests they like. That could be a significant better engineering win.

**Comment by seemethere** [comment]
Distributed job has been migrated to it's own job so we can probably close.
