### ISSUE TITLE
When I run an algorithm get an error: "OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by Austinzhenghua** [pytorch/pytorch#60515]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
Can someone tell me why and how to fix it, thanks a lot!

**Comment by shikharvashistha** [comment]
Try running 


- `export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH`


- Initialize python in same terminal session and try to import `pytorch`. You probably forgot to add these lines to your `.bashrc` or `.profile` so pytorch can’t find cuda.


- `export LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"`
`export PATH="/usr/local/cuda/bin:$PATH"`
A symlink that links /usr/local/cuda-10.0 to /usr/local/cuda will be created automatically when you installed cuda if nvidia’s repos is used, so you don’t have to change these every time you install a different version of cuda. If the link doesn’t exist then you need to create it by `sudo ln -s /usr/local/cuda-10.0 /usr/local/cuda`


More on this could be found [here](https://stackoverflow.com/questions/55224016/importerror-libcublas-so-10-0-cannot-open-shared-object-file-no-such-file-or)

**Comment by shikharvashistha** [comment]
In my opinion it's because cuda dll isn't linked.

- Try running:
`sudo ldconfig /usr/local/cuda-X/lib64`

- If it reports an error try establishing a symbolic link try running:
`ln -sf /usr/local/cuda-X/lib64/libcudnn.so.7.6.Y /usr/local/cuda-X/lib64/libcudnn.so.7`


Note:
- `X` replaces your installed cuda version 
(Eg: `10.0`, `9.0`)
Try checking it.

- `Y` replaces your installed libcudnn.so version
(Eg: For `cuda-10.0` it's `libcudnn.so.7.6.5` and for `cuda-9.0` it's `libcudnn.so.7.6.1`)
Try checking it.

**Comment by shikharvashistha** [comment]
In my opinion it's because cuda dll isn't linked.

- Try running:
`sudo ldconfig /usr/local/cuda-X/lib64`

- If it reports an error try establishing a symbolic link try running:
`ln -sf /usr/local/cuda-X/lib64/libcudnn.so.7.6.Y /usr/local/cuda-X/lib64/libcudnn.so.7`


Note:
- `X` replaces your installed cuda version 
(Eg: `10.0`, `9.0`)
Try checking it.

- `Y` replaces your installed libcudnn.so version
(Eg: For `cuda-10.0` it's `libcudnn.so.7.6.5` and for `cuda-9.0` it's `libcudnn.so.7.6.1`).
It is present under subdirectory `/usr/local/cuda-X/lib64/`)
Try checking it.

**Comment by shikharvashistha** [comment]
> ## ❓ Questions and Help
> ### Please note that this issue tracker is not a help form and this issue will be closed.
> We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:
> 
> * [Discussion Forum](https://discuss.pytorch.org/)
>   Can someone tell me why and how to fix it, thanks a lot!

As per my knowldge it's because cuda dll isn't linked.

- Try running:
`sudo ldconfig /usr/local/cuda-X/lib64`

- If it reports an error try establishing a symbolic link try running:
`ln -sf /usr/local/cuda-X/lib64/libcudnn.so.7.6.Y /usr/local/cuda-X/lib64/libcudnn.so.7`


Note:
- `X` replaces your installed cuda version 
(Eg: `10.0`, `9.0`)
Try checking it.

- `Y` replaces your installed libcudnn.so version
(Eg: For `cuda-10.0` it's `libcudnn.so.7.6.5` and for `cuda-9.0` it's `libcudnn.so.7.6.1`).
It is present under subdirectory `/usr/local/cuda-X/lib64/`)
Try checking it.

**Comment by Austinzhenghua** [comment]
> > ## ❓ Questions and Help
> > ### Please note that this issue tracker is not a help form and this issue will be closed.
> > We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:
> > 
> > * [Discussion Forum](https://discuss.pytorch.org/)
> >   Can someone tell me why and how to fix it, thanks a lot!
> 
> As per my knowldge it's because cuda dll isn't linked.
> 
> * Try running:
>   `sudo ldconfig /usr/local/cuda-X/lib64`
> * If it reports an error try establishing a symbolic link try running:
>   `ln -sf /usr/local/cuda-X/lib64/libcudnn.so.7.6.Y /usr/local/cuda-X/lib64/libcudnn.so.7`
> 
> Note:
> 
> * `X` replaces your installed cuda version
>   (Eg: `10.0`, `9.0`)
>   Try checking it.
> * `Y` replaces your installed libcudnn.so version
>   (Eg: For `cuda-10.0` it's `libcudnn.so.7.6.5` and for `cuda-9.0` it's `libcudnn.so.7.6.1`).
>   It is present under subdirectory `/usr/local/cuda-X/lib64/`)
>   Try checking it.

Thank you very much, my cuda version is 10.1,  I get the following error:
 ldconfig /usr/local/cuda-X/lib64
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.418.56 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libcuda.so.418.56 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.418.56 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.418.56 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.418.56 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.418.56 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.418.56 is empty, not checked.

Do you know, what is wrong? Thanks!

**Comment by shikharvashistha** [comment]
> /sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.418.56 is empty, not checked.

In this case I would recommend a reinstall, as your system seems to be broken.

**Comment by albanD** [comment]
As you can see in the template, please use the forum to ask questions.
