### ISSUE TITLE
Use decorator to `handle_torch_function` in functional

### ISSUE THREAD

**Issue by ZhiyuanChen** [pytorch/pytorch#60749]
## 🚀 Feature

replace
```python
def xxx():
    if cond:
        handle_torch_function(xxx, *args, **kwargs)
    ...
```

with 

```python
@handle(cond)
def xxx():
    ...
```

## Motivation

There are currently 91 `handle_torch_function` in functional, and all of them share a similar structure. It would take less effort to use a decorator to `handle_torch_function`.

## Pitch

replace
```python
def xxx():
    if cond:
        handle_torch_function(xxx, *args, **kwargs)
    ...
```

with 

```python
@handle(cond)
def xxx():
    ...
```

## Additional context

cc @hameerabbasi @rgommers @peterbell10

**Comment by peterbell10** [comment]
Such a decorator already exists:
https://github.com/pytorch/pytorch/blob/7585783b8d35cc115eac8a68ee97dd37bf2fbd0e/torch/overrides.py#L1171

My understanding is the extra function call overhead caused by the decorator was deemed unacceptable. Also, you're hiding with your abbreviated form that `if cond` isn't actually the same for all operators and created the need to define a `dispatcher` function; removing most of the brevity gains from this proposal.

**Comment by rgommers** [comment]
What @peterbell10 says is correct. A lot of effort was spent on minimizing function call overhead, which was critical to the introduction of `__torch_function__`. Having this snippet in every function is the price to pay.

**Comment by ZhiyuanChen** [comment]
> What @peterbell10 says is correct. A lot of effort was spent on minimizing function call overhead, which was critical to the introduction of `__torch_function__`. Having this snippet in every function is the price to pay.

Thank you for answering!
