### ISSUE TITLE
mpiexec fails in GitHub Actions

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#60756]
[This GitHub Actions run](https://github.com/pytorch/pytorch/runs/2853101845?check_suite_focus=true) used to test #60204 failed with the following log:
```
++ command -v mpiexec
+ MPIEXEC=/usr/bin/mpiexec
+ [[ -n /usr/bin/mpiexec ]]
+ MPICMD='/usr/bin/mpiexec -np 2 build/bin/ProcessGroupMPITest'
+ eval '/usr/bin/mpiexec -np 2 build/bin/ProcessGroupMPITest'
++ /usr/bin/mpiexec -np 2 build/bin/ProcessGroupMPITest
--------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
```
This is blocking the bionic-cuda10.2-cudnn7-py3.9-gcc7 job from being migrated to GitHub Actions, so the `mpiexec` section will be disabled on GitHub Actions until this issue is resolved.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by zhaojuanmao** [comment]
@samestep should we make some changes in CI setup script? we do not know where and how to fix the CI setup

**Comment by samestep** [comment]
@zhaojuanmao Yeah, I'm guessing something will need to be changed in `.circleci/docker`; I plan on investigating/fixing that (and reenabling the `mpiexec` section) after merging #60204.

**Comment by walterddr** [comment]
Another example of this occurred on CircleCI job as well when I reorder the distributed python test.
https://app.circleci.com/pipelines/github/pytorch/pytorch/364181/workflows/3e71e4a1-0108-45d5-9d14-97358bb1bb35/jobs/15362526

I was wondering if there's any relevance between the GHA issue and this CircleCI one

**Comment by walterddr** [comment]
reproduction found --> previously the reason why we cant reproduce is because this error specifically happens when @samestep migrate the job from circle to GHA without shard test enable. 

Now that shard test is enabled, it no longer runs the else branch in https://github.com/pytorch/pytorch/blob/daba5519220b0143b825b31b8f10786a6d111255/.jenkins/pytorch/test.sh#L519-L529, thus we were not able to repro. 

I ssh into the containers for those bionic docker images and it seems like it doesn't have ssh installed:
https://app.circleci.com/pipelines/github/pytorch/pytorch/364847/workflows/9a5a2709-20e8-4c3a-9f50-15ec4954b6dd/jobs/15392791
but ssh is available on xenial containers: https://app.circleci.com/pipelines/github/pytorch/pytorch/364847/workflows/9a5a2709-20e8-4c3a-9f50-15ec4954b6dd/jobs/15410154

since we dont install openssh directly in our dockerfiles I am assuming this is some sort of changes from the nvidia/cuda base image side. a solution will be simply install openssh in our dockerfiles when we do https://github.com/pytorch/pytorch/blob/daba5519220b0143b825b31b8f10786a6d111255/.circleci/docker/ubuntu-cuda/Dockerfile#L75. 

thoughts?
