### ISSUE TITLE
RuntimeError: UNSUPPORTED DTYPE

### ISSUE THREAD

**Issue by Krovatkin** [pytorch/pytorch#60763]
## To Reproduce

1. Put the following test in `test_jit_fuser_te.py`

```
    def test_mm_cat(self):

        @torch.jit.script
        def func(x, y, w, b):
            l = [x, y]
            z = torch.cat(l, dim = 0)
            li = torch.torch.nn.functional.linear(z, w, b)
            return torch.nn.functional.layer_norm(li, li.size())

        x = torch.rand(5, 20)
        y = torch.rand(5, 20)
        w = torch.rand(40, 20)
        b = torch.rand(40)

        with num_profiled_runs(1):
            func(x, y, w, b)
            func(x, y, w, b)
            func(x, y, w, b)
```

2. add `from torch.testing._internal.common_utils import num_profiled_runs` to the top of the file
3. ` python test_jit_fuser_te.py TestTEFuser.test_mm_cat`

```
======================================================================
ERROR: test_mm_cat (__main__.TestTEFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit_fuser_te.py", line 186, in test_mm_cat
    func(x, y, w, b)
  File "/scratch/villedepommes/miniconda3/envs/pytorch1/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 133, in prof_func_call
    return prof_callable(func_call, *args, **kwargs)
  File "/scratch/villedepommes/miniconda3/envs/pytorch1/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 130, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: UNSUPPORTED DTYPE

----------------------------------------------------------------------
```

## Expected behavior

No error

## Environment

1.9.0a0+git781eb0e

**Comment by ZolotukhinM** [comment]
The error occurs because the fusion group has a single node, which is `aten::cat`. The input of this node is a List[Tensor] value which in this case is a graph argument. The fuser cannot deduce device type in that situation and thus throws this error. This only can occur when we allow fusion groups of size 1 (which we manually set in this test), which is not our default setting and we do not have plans to officially guarantee it always works.

We already have a test (disabled now) exposing this so Im going to close this issue:
https://github.com/pytorch/pytorch/blob/e1bd4963e23835e307792eb3e49cb5f1b8f771c5/test/test_tensorexpr.py#L1045-L1050
