### ISSUE TITLE
[Bug] linalg.eigh fails if device not set

### ISSUE THREAD

**Issue by wjmaddox** [pytorch/pytorch#60892]
## 🐛 Bug

`torch.linalg.eigh` fails on the gpu if device not set beforehand (thanks @ngimel for the fix). 

## To Reproduce

```python
import torch
torch.__version__
# nightly 1.10

# fix is next line
# torch.cuda.set_device("cuda:1")
device = torch.device("cuda:1")

a = torch.randn(20, 50)
b = a @ a.t() + 1e-3 * torch.eye(20)
b = b.to(device)
torch.linalg.eigh(b)
```
results in 
```
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnXsyevd( handle, params, jobz, uplo, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(W), CUDA_R_32F, reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost), workspaceInBytesOnHost, info)`

```

## Expected behavior

this should work, and works when device is set.

## Environment
```
PyTorch version: 1.10.0.dev20210628
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-99-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: 
GPU 0: NVIDIA TITAN RTX
GPU 1: NVIDIA TITAN RTX
GPU 2: NVIDIA TITAN RTX
GPU 3: NVIDIA TITAN RTX
GPU 4: NVIDIA TITAN RTX
GPU 5: NVIDIA TITAN RTX
GPU 6: NVIDIA TITAN RTX
GPU 7: NVIDIA TITAN RTX

Nvidia driver version: 465.19.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] gpytorch==1.5.0
[pip3] numpy==1.20.2
[pip3] torch==1.10.0.dev20210628
[pip3] torchaudio==0.10.0a0+abaa088
[pip3] torchvision==0.11.0.dev20210628
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] gpytorch                  1.5.0                     dev_0    <develop>
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] pytorch                   1.10.0.dev20210628 py3.8_cuda11.1_cudnn8.0.5_0    pytorch-nightly
[conda] torchaudio                0.10.0.dev20210628            py38    pytorch-nightly
[conda] torchvision               0.11.0.dev20210628      py38_cu111    pytorch-nightly
```

## Additional context

seemingly breaks some gpytorch linear algebra. 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by ngimel** [comment]
Hi-pri as it is a crash for all practical purposes, it nukes cuda context so any operations after this are not possible.

**Comment by xwang233** [comment]
I've tried that adding a `CUDAGuard` may solve the issue

```diff
diff --git a/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cu b/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cu
index 0b10b34833..2a788c9578 100644
--- a/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cu
+++ b/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cu
@@ -1030,6 +1030,8 @@ template <typename scalar_t>
 static void apply_syevd(Tensor& values, Tensor& vectors, Tensor& infos, bool upper, bool compute_eigenvectors) {
   using value_t = typename c10::scalar_value_type<scalar_t>::type;
 
+  ::at::cuda::CUDAGuard guard(values.device());
+
   cublasFillMode_t uplo = upper ? CUBLAS_FILL_MODE_UPPER : CUBLAS_FILL_MODE_LOWER;
   cusolverEigMode_t jobz = compute_eigenvectors ? CUSOLVER_EIG_MODE_VECTOR : CUSOLVER_EIG_MODE_NOVECTOR;
 
```

but I'm not sure if this is the right approach. I didn't see many `CUDAGuard`s exist in the codebase. Is there any dispatch logic that guarantees this, otherwise, wouldn't many operators have this problem as well?

**Comment by ngimel** [comment]
DeviceGuards are usually codegened to the first tensor in the list of arguments, and recently automatic codegened tests that guarantee that all inputs are on the same device have been added, so it's unclear why the correct behavior doesn't happen automatically. cc @bdhirsh for codegen questions.

**Comment by ngimel** [comment]
It looks like all non-structured CompositeExplicitAutograd functions have device checks and device guards omitted:
```
::std::tuple<at::Tensor,at::Tensor> wrapper__linalg_eigh(const at::Tensor & self, c10::string_view UPLO) {
    // No device check


  // DeviceGuard omitted
  return at::native::linalg_eigh(self, UPLO);
}
```
(from generated RegisterCompositeExplicitAutograd.cpp)

**Comment by ngimel** [comment]
I guess this (and other linalg ops) should not be registered to CompositeExplicitAutograd, because they use Dispatchstub inside, #40564 seems to be related.

**Comment by bdhirsh** [comment]
@ngimel that looks like the right diagnosis to me: `at::linalg_eigh()` is definitely not backend-agnostic, since it has separate cpu and cuda implementations using dispatch stub.

So updating native_functions.yaml entry to point CPU/CUDA to `linalg_eigh` should correct the op (so it correctly errors if we try to call it with another backend), and also add the missing device guard logic for cuda.

**Comment by ngimel** [comment]
@ezyang, @bdhirsh do we have some tests to identify incorrect dispatch keys in the native_functions.yaml? I'm pretty sure this is the case for a lot of linalg (and maybe some other) functions. cc @IvanYashchuk

**Comment by IvanYashchuk** [comment]
cuSOLVER fails as its handle and temporary work buffers are initialized on a different device than input tensors. Unfortunately,  it was overlooked for some functions, when introducing the dispatch stubs, that the keys in native_functions.yaml need to be changed as well. I'll submit a patch fixing that.

I've noticed other interesting behavior
```python
In [1]: import torch

In [2]: device = torch.device("cuda:1")

In [3]: torch.linalg.eigh(torch.randn(3, 3, device='cuda:0'))
Device is 0
Device is 0
Out[3]: 
torch.return_types.linalg_eigh(
eigenvalues=tensor([-1.8241,  2.3956,  2.9491], device='cuda:0'),
eigenvectors=tensor([[-0.2985,  0.6476,  0.7010],
        [ 0.4553, -0.5489,  0.7010],
        [ 0.8388,  0.5285, -0.1310]], device='cuda:0'))

In [4]: torch.lu_solve(torch.randn(3, 1, device=device), torch.randn(3, 3, device=device), torch.arange(1, 4, device=device, dtype=torch.int))
   ...: 
Out[4]: 
tensor([[ 1.4775],
        [-2.1323],
        [-4.3082]], device='cuda:1')

In [5]: torch.linalg.eigh(torch.randn(3, 3, device='cuda:0'))
Device is 1
Device is 1
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-f46d4d323bc3> in <module>
----> 1 torch.linalg.eigh(torch.randn(3, 3, device='cuda:0'))

RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnSsyevd(handle, jobz, uplo, n, A, lda, W, work, lwork, info)`
```

`lu_solve` also uses (incorrectly) CompositeExplicitAutograd key, it should use CPU, CUDA keys because dispatch stubs are used in the implementation. For this input, size MAGMA is used internally and it seems that it sets the device somewhere. Using "CPU, CUDA" keys for `lu_solve` removes this behavior.

**Comment by bdhirsh** [comment]
I made a little test that looks for ops that map to `CompositeExplicitAutograd`, but use DispatchStub. It's a little fragile, so idk if it's worth landing - especially because a lot of ops follow a weird pattern that turn up false positives - e.g. `at::cumprod` is `CompositeExplicitAutograd`, because it has a derivatives entry, but it calls into `at::_cumprod` for all of the real work.

But the ops that came up on the list are:

```
eig
lu_solve
linalg_eigh
```

@IvanYashchuk  has a fix for `lu_solve` and `linalg_eigh` in his PR.

`eig.e` also looks wrong, since it's CompositeExplicitAutograd but has separate DispatchStub kernels for cpu and cuda. The `eig` (functional) op looks fine though, since it redispatches to `eig.e`, but also has its own derivatives formula.

**Comment by ezyang** [comment]
i say land it, at the very least its failure will make people think twice, even if it is a false positive

**Comment by bdhirsh** [comment]
PR for it here: https://github.com/pytorch/pytorch/pull/61134. Let me know if you still think it's worth landing after taking a look at it 😛
