### ISSUE TITLE
Data Parallel splits Complex Parameter

### ISSUE THREAD

**Issue by lthilnklover** [pytorch/pytorch#60931]
## 🐛 Bug
I am testing a toy model that fourier transforms an image and do pointwise multiplication with a complex tensor and then inverse fourier transform. When I train the model with single GPU everything works fine, however, when I try to train the model with DataParallel wrapping, there seems to be a dimension mismatch issue:
```
RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 3
```

My model looks like this:

```
import torch
import torch.fft as fft


class PointwiseMultiplication(torch.nn.Module):
    def __init__(self, c, h, w):
        super(PointwiseMultiplication, self).__init__()
        real_matrix = torch.empty(c, h, w)
        imaginary_matrix = torch.empty(c, h, w)
        torch.nn.init.kaiming_normal_(real_matrix)
        torch.nn.init.kaiming_normal_(imaginary_matrix)
        cplx_matrix = torch.complex(real_matrix, imaginary_matrix)
        self.weight = torch.nn.Parameter(cplx_matrix, requires_grad=True)

    def forward(self, x):
        out = fft.fft2(x)
        out = out * self.weight
        return fft.ifft2(out).real
```

To debug the problem, I printed the shape of self.weight at initialization, and at forward pass, and got

```
weight shape at initialization:  torch.Size([3, 256, 256])
weight shape at forward pass:  torch.Size([3, 256, 256, 2])
weight shape at forward pass:  torch.Size([3, 256, 256, 2])
weight shape at forward pass:  torch.Size([3, 256, 256, 2])
weight shape at forward pass:  torch.Size([3, 256, 256, 2])
```

Then I realized, the complex weight tensor is transformed to real tensor with real and imaginary part splitted: for instance [1 + 1j] -> [[1], [1]] 

## Environment

 - PyTorch Version (e.g., 1.0): 1.9
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.0
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 4 rtx 2080 Ti
 - Any other relevant information:

**Comment by DamonDeng** [comment]
@osalpekar, is this issue duplicated with #47330?

 If yes, shouldn't it be fixed by PR #48686?

Did not try to reproduce the issue yet, just trying to find useful information in historical issues.

**Comment by osalpekar** [comment]
@DamonDeng Yes that is the correct issue and PR that enables complex tensor support in DataParallel. The shapes you printed are expected since we internally call `torch.view_as_real` and add an extra dimension to split the real and imaginary parts of each tensor item. 

Can you produce a stack trace so we know which line the RuntimeError is coming from? Is your input `x` to this model real or complex? It seems like the real view of the weight tensor is being multiplied with another tensor, resulting in a dimension mismatch (a stack trace would confirm this).

**Comment by DamonDeng** [comment]
@osalpekar , I am not the author who created this issue, I am just trying to look into this to help.

I looked into the `_handle_complex(tensor)` method and found the `return torch.view_as_real(tensor)` too, then got an understanding of how you handle the complex number.

According to the description from the author @lthilnklover , he is handling image data, so that I assume the `x` he inputed is a real tensor, not a complex tensor. (Complex number does not have a meaning in image, right?)

So, if the assumption is right, the issue turns out to be an issue of multiplying real tesnor and complex tensor in `DataParallel`. In fact, numpy can support this type of operation correctly by upcasting real number to complex number.

@lthilnklover , can you help to confirm whether your input `x` is real tensor?

**Comment by lthilnklover** [comment]
@DamonDeng @osalpekar Thank you all for kindly looking into my issue. 

Here is the full stack trace of the error:

```
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    recon_img = model(measurement)
  File "/home/lthilnklover/.conda/envs/torch_1.9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthilnklover/.conda/envs/torch_1.9/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lthilnklover/.conda/envs/torch_1.9/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lthilnklover/.conda/envs/torch_1.9/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/lthilnklover/.conda/envs/torch_1.9/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 1.
Original Traceback (most recent call last):
  File "/home/lthilnklover/.conda/envs/torch_1.9/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/lthilnklover/.conda/envs/torch_1.9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthilnklover/fourier/fourier.py", line 22, in forward
    out = out * self.weight
RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 3
```


1. Yes my input ```x``` is a real tensor, or image. However since i'm doing fourier transform, ```out``` is a complex tensor.
2. So if complex tensor is viewed as real in data parallel, I think it only applies to the parameters, because ```out``` is kept as a complex tensor.

**Comment by osalpekar** [comment]
Thanks for confirming @lthilnklover. One workaround could be to do compute `out_real = torch.view_as_real(out)`, and use `out_real` when multiplying with `self.weight`. If both are real, they will have the same shape, and the matrix multiplication will work.

A more general suggestion is to use DistributedDataParallel (DDP). DDP is being actively worked on, whereas DataParallel is largely in maintenance mode and it's unlikely we will add new features (the fix for this seems to be convert tensors back to complex after broadcasting them to the other GPUs, as well as converting between complex and real in the backward-pass broadcast). See discussion here: https://github.com/pytorch/pytorch/issues/55375. The DDP API does not require too much change from standard PyTorch code, while supporting a far broader set of features.

**Comment by lthilnklover** [comment]
@osalpekar Thank you for the advice. I will look into DDP, and use it instead of DP in the future!

**Comment by fschiffers** [comment]
Why was this issue closed ?

I think DataParallel still returns a real valued complex tensor which fully breaks my code.

I'm using DataParallel because I want to do interactive optimization using a Jupyter Notebook, hence DDP is not an option for me rn.

Is there any current work around ? I only have a minimal working example of this behavior in Pytorch Lightning, but I'll work to provide one in Pytorch only.

**Comment by Kharitok** [comment]
@osalpekar  @DamonDeng  Sorry for the late posting but this issue is very live to me, since I am interested in doing some interactive optimization  (hence DDP is not an option for me) for complex-valued functions. Do you maybe have some updates/ workarounds on how to prevent complex tensors from being split while using DP for multi-gpu calculations?
