### ISSUE TITLE
ONNX  index_put works wrong when repeated indices and True accumulate exist

### ISSUE THREAD

**Issue by johnnyleeRH** [pytorch/pytorch#61034]
## 🐛 Bug

when repeated indices exist, the result will only add the last index element even the accumulate set to True

## To Reproduce

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import onnxruntime


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        

    def forward(self,  index,  A, B):
        A = A.index_put((index,), B, accumulate=True)
        return A

trained_model = Net()
A= torch.ones(5, 3)
B = torch.tensor([[1, 1, 1], [1, 1, 1], [1, 1, 1],[1, 1, 1],[1,1,1]], dtype=torch.float)
index = torch.tensor([0, 4, 2,2,4])
input = (index,A,B)
torch.onnx.export(
                trained_model,
                input,
                "net_demo.onnx",
                # operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
                opset_version=11)

ort_session = onnxruntime.InferenceSession("net_demo.onnx")
ort_inputs = {ort_session.get_inputs()[0].name:index.cpu().numpy(),
    ort_session.get_inputs()[1].name:A.cpu().numpy(),
    ort_session.get_inputs()[2].name: B.cpu().numpy()}

ort_outs = ort_session.run(None, ort_inputs)
print('ort_outs:')
print(ort_outs)
```

## Expected behavior

expect result is :
[array([[2., 2., 2.],
[1., 1., 1.],
[3., 3., 3.],
[1., 1., 1.],
[3., 3., 3.]], dtype=float32)]
but the actual result is:
[array([[2., 2., 2.],
[1., 1., 1.],
[2., 2., 2.],
[1., 1., 1.],
[2., 2., 2.]], dtype=float32)]

## Environment

Linux Ubuntu 18.04:
ONNX version : 1.9
Python version: 3.8.5
GCC/Compiler version (if compiling from source): 7.5
CMake version: 3.10.2
Protobuf version:
Visual Studio version (if applicable):

cc @BowenBao @neginraoof

**Comment by fatcat-z** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1335043.

**Comment by johnnyleeRH** [comment]
> This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1335043.

Thanks for your reply

**Comment by AllenTiTaiWang** [comment]
Related to #80271

**Comment by AllenTiTaiWang** [comment]
Hi @johnnyleeRH ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team

**Comment by martinResearch** [comment]
I found a workaround which consists `rewriting A = A.index_put((index,), B, accumulate=True)` as
```
        index1d = (index * A.shape[1])[:, None] + torch.arange(A.shape[1])
        A = torch.scatter_add(A.flatten(), 0, index1d.flatten(), B.flatten()).reshape(A.shape)
```
This might need some rewriting to handle different case for the shapes of A, index and B than used in the example above.
You will also using opset_version=16 when exporting to onnx, otherwise you will get wrong results (see https://github.com/pytorch/pytorch/issues/32960).
Posted the same workaround on https://github.com/onnx/onnx/issues/3547
