### ISSUE TITLE
libtorch1.8 cannot recognize 3060's gpu

### ISSUE THREAD

**Issue by woshichunge12** [pytorch/pytorch#61284]
windows10+libtorch1.8.1+cuda11.1+RTX3060 +VS2017
**It seems that the gpu is not recognized, can someone help me?**
![捕获](https://user-images.githubusercontent.com/40681348/124592334-efcfe180-de8f-11eb-8579-6aeed061bbb5.PNG)
![捕获1](https://user-images.githubusercontent.com/40681348/124592342-f199a500-de8f-11eb-8763-45565b2318b4.PNG)
![捕获2](https://user-images.githubusercontent.com/40681348/124592347-f2cad200-de8f-11eb-9ed2-e63c50347997.PNG)

**Comment by woshichunge12** [comment]
Thank you in advance

**Comment by malfet** [comment]
More context is needed in order to debug the issue. For example: does PyTorch `import torch;print(torch.rand(3,3,device="cuda")" works on your system. if so,  does LibTorch CPP example pass?
As bug template suggest, please run and share the output of https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py
And last but not the lest, please write in English, as not everyone (myself included) can parse screenshot of an error message in Mandarin.
Do not hesitate to reopen the issue after you provide above-mentioned additional info
