### ISSUE TITLE
[jit][script] Support shape inference of ops with integral constant arguments

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#6139]
The following will compile:
```
import torch
@torch.jit.script
def unsqueeze0(x):
    return x.unsqueeze(dim=0)
x = torch.randn((2, 2), requires_grad=True)
unsqueeze0(x)
```
while the following will not:
```
import torch
@torch.jit.script
def unsqueeze0(x):
    return x.unsqueeze(0)
x = torch.randn((2, 2), requires_grad=True)
unsqueeze0(x)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-6be6b64cf00e> in <module>()
      4     return x.unsqueeze(0)
      5 x = torch.randn((2, 2), requires_grad=True)
----> 6 unsqueeze0(x)

RuntimeError: torch/csrc/jit/autodiff.cpp:194: createZerosLike: can't allocate zero gradient for a value without a type
```
because the shapecheck pass ultimately doesn't recognize `x.unsqueeze(0)` and does not infer the type of its output as a result

Both of these two examples should be compile-able.

cc @zdevito

**Comment by apaszke** [comment]
The problem lies elsewhere. Shape inference pass can execute `x.unsqueeze(0)` just fine. The initial graph looks like this:
```
graph(%x : Dynamic) {
  %1 : Dynamic = prim::Constant[value={0}]()
  %2 : Dynamic = aten::unsqueeze(%x, %1)
  return (%2);
}
```
You can see that the `0` gets inlined into the IR as a constant tensor, and shape inference will correctly infer that the type of `%1` is `Long()`. Then, we get to the second node, but `unsqueeze` is not a supported operation, and it has an integral input, so we can't create a dummy input, and run the op to infer the shape.

I've been thinking about how to handle the viewing ops, and I'm not sure if we want to implement shape inference for them, because the way they handle strides is quite complicated (I think stride handling in `unsqueeze` changed at least 3 times), and it would be terrible if it got out of sync with the ATen impls. We should discuss that in our next meeting.

**Comment by apaszke** [comment]
NB as a proof that this works (and is only a problem with shape inference), you can remove `requires_grad=True` in which case the scripted function will run just fine

**Comment by zou3519** [comment]
I'm not sure if this is useful or if it's exactly what you're saying @apaszke , but I've noticed there's a special case in the shape analysis for `unsqueeze`:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/shape_analysis.cpp#L188-L200

Tracing `unsqueeze(dim=0)` causes different behavior than `unsqueeze(0)`: `unsqueeze(dim=0)` results in the Node having 1 input, while `unsqueeze(0)` results in the node having 2 inputs. The [check_overload](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/shape_analysis.cpp#L189-L190) returns false in the case of `unsqueeze(0)` because it has 2 inputs instead of 1, breaking out of this case and keeping the type of the outputs as DynamicType instead of inferring the sizes of the outputs.

**Comment by zou3519** [comment]
Not sure which PR did it, but this appears to be supported now
