### ISSUE TITLE
Better version reporting

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#61540]
### Problem

PyTorch reports its version as a string, which is hard to compare. In addition to that, with the upcoming release of 1.10, version comparison is going to have a silent bug.

Below are some problems with the current version reporting

#### Comparing 1.1x -- incorrect result after comparison

Because this behavior is silent, it might be a potential bug.

```
>>> "1.10" < "1.3.0"
True
```

#### Comparing to version tuples -- Error as we report a string

This issue fails, so might be OK. However, it would still be nice to be able to compare the versions and tuples

```
>>> torch.__version__ < (1, 3, 0)
TypeError: '<' not supported between instances of 'str' and 'tuple'
>>> torch.__version__
1.9.0+cu102
```

### Resolution 1. Use  python's version parser directly, and return the built-in `Version` class

```
>>> from packaging import version
>>> version.parse("1.10") < version.parse("1.3.0")
False
>>> version.parse("1.9.0+cu102") < version.parse("1.3.0")
False
>>> version.parse("1.9.0+cu102") > version.parse("1.3.0")
True
>>> type(version.parse("1.9.0+cu102"))
packaging.version.Version
```

The main problem with this resolution is that it expects the users to compare the instances of the `packaging.version.Version`.

### Resolution 2. Report version as a tuple

```
>>> (1, 9, 0, 'cu102') < (1, 3, 0)
False
>>> (1, 10) < (1, 3, 0)
False
```

I think this is a better way, as it follows the style that is returned by the python's `sys.version_info`. However, this does not follow the pattern used by NumPy.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by z-a-f** [comment]
Sorry, @seemethere, didn't know who to tag

**Comment by seemethere** [comment]
Another janky way to do this (while keeping backward compat) would be to create an object that implements its own comparison logic using the python magic methods (`__gt__`, `__lt__`, etc.).

Basically just check what its comparing against (i.e. `str`. vs. `tuple` vs. `packaging.version.Version`) and do the comparison that way so that no matter what peopel are comparing against it'll mostly just work

**Comment by z-a-f** [comment]
> Another janky way to do this (while keeping backward compat) would be to create an object that implements its own comparison logic using the python magic methods (`__gt__`, `__lt__`, etc.).
> 
> Basically just check what its comparing against (i.e. `str`. vs. `tuple` vs. `packaging.version.Version`) and do the comparison that way so that no matter what peopel are comparing against it'll mostly just work

I actually like this idea, as it also would allow us to compare internal versioning, such as `torch-deploy-1.8` (https://github.com/pytorch/pytorch/blob/3faf6a715dcdffeb03ccccf35c74ea57cd781634/torch/__init__.py#L27).

**Comment by seemethere** [comment]
Working on a PR for this right now

**Comment by z-a-f** [comment]
I am gonna reopen it for one little comment. @seemethere, please, close it if you think it is not necessary.

Firstly, thank you for landing this. One case, that I think might be problematic is the comparison of the local versions. I believe that if the requirements say something like "1.9.0", it should match any local versions (s.a. "1.9.0+cu102", "1.9.0+post0", etc). Currently, if we do `TorchVersion("1.9.0+cu102") == TorchVersion("1.9.0")`, it would return False. Correct me if I am wrong.

**Comment by seemethere** [comment]
Yes that would be the case since `1.9.0+cu102` != `1.9.0`,

I don't think we should make a requirement for the version to not check local versions since there's not a lot of people that do that anyways (as far as I could find from my search on github for uses of `torch.__version__`

I don't necessarily think there's a huge use case for directly comparing the versions (including the local versions).

Things like `TorchVersion('1.9.0+cu102').endswith('cu102')` will still work in these cases

**Comment by malfet** [comment]
Closing the issue, as it's tagged to be completed for 1.10 milestone and there do not seem to be any activity in the last 2+ month)
