### ISSUE TITLE
Is there any way to get the number of Operators in my model?

### ISSUE THREAD

**Issue by jinluyang** [pytorch/pytorch#61639]
## ❓ Questions and Help
Hello, Is there any way to get the number of Operators in my model? I tried to add a counter in the constructor of struct OperatorKernel, but the number is wrong.
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by zou3519** [comment]
We like to keep our issue tracker high-signal and full of feature requests and valid bug reports. Because this is a question, please ask over at our forums: https://discuss.pytorch.org/.

To answer the question really quickly though, you can use the pytorch profiler to do this:
https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/

**Comment by jinluyang** [comment]
I couldn't sign up the website due to "New registrations are not allowed from your IP address (maximum limit reached)", but still, thank you very much.
