### ISSUE TITLE
`torch.median` on empty tensor causes segfault

### ISSUE THREAD

**Issue by nik-sm** [pytorch/pytorch#61656]
## 🐛 Bug

Calling `torch.median()` on an empty tensor causes segfault.

## To Reproduce

```python
import torch
t = torch.tensor([])
t.median()
```

## Expected behavior

Similar to other ops like `torch.mean()` or `torch.sum()` - attempting to find median of an empty tensor should cause a `RuntimeError` or otherwise produce a stack trace, rather than causing segfault.

## Environment

```shell
Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.5 (default, May 27 2021, 13:30:53)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.8.0-53-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX TITAN X
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] pytorch-lightning==1.3.8
[pip3] torch==1.9.0
[pip3] torch-tb-profiler==0.2.1
[pip3] torchmetrics==0.4.1
[pip3] torchvision==0.10.0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @heitorschueroff

**Comment by malfet** [comment]
Seems easy to fix, but I guess we need a better audit for those types of errors

**Comment by malfet** [comment]
Though, I guess the question is, what it should return? `nan` as `torch.mean` or exception, as `torch.quantile`

**Comment by heitorschueroff** [comment]
> Though, I guess the question is, what it should return? `nan` as `torch.mean` or exception, as `torch.quantile`

That is an interesting question. I think a more general question is what should we do with reductions over empty slices for operations that don't have an identity. For `mean` and `median` NumPy returns `nan` because these have no identity and the return type is float. For `max` and `min` NumPy raises an error saying these have no identity. For `quantile` NumPy also raises an error but it's not a descriptive one. Finally, `sum` and `prod` have identities so NumPy just returns 0 and 1 respectively. @mruberry  @rgommers do you think we should follow NumPy or always raise an exception for reductions over empty slices? Is this something the Python Array API Standard specifies, or should specify?

**Comment by rgommers** [comment]
> Is this something the Python Array API Standard specifies, or should specify?

It's not specified (yet). I'd like the test suite to cover it. It may be useful to put it in the spec, but I'm not 100% sure - it may be a lot of boilerplate. Perhaps it could be a general design rule somewhere.


> @rgommers do you think we should follow NumPy or always raise an exception for reductions over empty slices without identity

I have the feeling we discussed this somewhere else recently, and the outcome was that an exception should only be raised if no sensible answer is possible. Which is consistent with what NumPy does now.

**Comment by Jup11ter** [comment]
It seems like there is an underlying implementation bug, `torch.nanmedian` also returns `Segmentation fault (core dumped)` in 1.9.0 versions when running the following codes.

In 1.10.0, by contrast, it can run without crashing. I think the reason is that [pr #61698](https://github.com/pytorch/pytorch/pull/61698) also fixes the bug on `torch.nanmedian`.

```python
import torch

func_cls=torch.nanmedian
t = torch.tensor([])

def test():
	func_cls(t)
test()
```
