### ISSUE TITLE
How data transfer from disk to GPU?

### ISSUE THREAD

**Issue by pyhundan** [pytorch/pytorch#61831]
## ❓ Questions and Help

I have learned that we can use.to(device) to.CUDA () to transfer data to the GPU. I want to know how this process is implemented in the bottom layer.

Thanks, hundan.

**Comment by mrshenli** [comment]
Hey @pyhundan, there is a Copy CUDA kernel for this. See https://github.com/pytorch/pytorch/blob/26d17ddc9f4f765ac07d550f296b0b35340a3a34/aten/src/ATen/native/cuda/Copy.cu

Please use [PyTorch Forum](https://discuss.pytorch.org/) for questions. I am closing this issue. If this turns out to be a feature request or bug report, please feel free to open another issue.
