### ISSUE TITLE
[BUG] Incorrect behavior of sparse matrix-matrix multiplication

### ISSUE THREAD

**Issue by kose-y** [pytorch/pytorch#6219]
This PyTorch bug was introduced by https://github.com/pytorch/pytorch/pull/4707. 
Unlike claimed there, `indices` should not only be unique, but also be sorted in coalesced matrix for correct behavior of matrix multiplication. This raises a major issue when performing matrix multiplication with coalesced then transposed matrix. 

The following is tested on 2e156f3, but any version after https://github.com/pytorch/pytorch/commit/5e72d7af136eb5a9105b501923f68d1246fa90b1 will have the same behavior. 

```python
import torch
idx = torch.LongTensor([[0,1,2], [2,1,0]])
val = torch.ones(3)
D = torch.sparse.FloatTensor(idx,val,torch.Size([3,3]))
Dc = D.coalesce()
x = torch.ones((3,1))
```

```python
torch.mm(D.t(), x)
```    
     1
     1
     1
    [torch.FloatTensor of size (3,1)]

```python
torch.mm(Dc.t(), x)
```    
     3
     0
     0
    [torch.FloatTensor of size (3,1)]

I will create a pull request regarding this and https://github.com/pytorch/pytorch/issues/6171 later today.

**Comment by weiyangfb** [comment]
This issue is caused by the following:
- `t()` because it swaps the indices of a sparse tensor without setting `coalesce=false`
- calling `coalesce()` sets `coalesce=true`
- `mm(Sparse, Dense)` doesn't really sort the sparse tensor - the [call to `coalesce()`](https://github.com/pytorch/pytorch/blob/216961b7bf59577cee7d3e47c2eef6243ae187d8/aten/src/ATen/native/sparse/SparseTensorMath.cpp#L528) doesn't do anything.

A simple fix will be to either:
1. set `coalesce=false` at `t()`
2. or set `coalesce=false` wherever [`set_indices_and_values`](https://github.com/pytorch/pytorch/blob/216961b7bf59577cee7d3e47c2eef6243ae187d8/aten/src/ATen/SparseTensorImpl.cpp#L64) gets called
