### ISSUE TITLE
Modify test runner to run disabled tests for PR that attempt to fix it

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62359]
Right now, if test is marked as disabled, there are no way to test the fix without removing it from https://github.com/pytorch/test-infra/blob/main/stats/disabled-tests.json (i.e. by closing issue that disabled it)
Perhaps this could be solved by:
 - Adding `IGNORE_DISABLED_ISSUES` environment variable, that would have comma separated issue numbers
 - Modify GHA workflows to set this environment variable for PRs that have "Fixes #XYZ" text in top commit

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
I think @janeyx99 mentioned this in one of the documents that there's a label to ignore disabled test cases, correct?

**Comment by janeyx99** [comment]
> I think @janeyx99 mentioned this in one of the documents that there's a label to ignore disabled test cases, correct?

Actually no, there currently isn't any functionality similar to the one requested here. I had thought there was at least an environment variable PYTORCH_RUN_DISABLED_TESTS that could switch between running versus not running them, but it turns out we never even use this variable in our test case logic (which is pretty bad).

I agree this functionality is pretty crucial and I can work on it.

**Comment by walterddr** [comment]
Sounds good. but please put the logic in tools/testing/test_selections.py that generates the disable test xml file (e.g. parse the file and get rid of the issue(s) mentioned in the PR description or commit message is a good idea.

**Comment by janeyx99** [comment]
Closing this issue now that #62851 is merged. This functionality is now available for GHA through using the PR body!
