### ISSUE TITLE
`torch.disributed.GradBucket.is_last()` returns is first instead of is last

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#63210]
Per the [documentation](https://pytorch.org/docs/master/ddp_comm_hooks.html#torch.distributed.GradBucket.is_last), `torch.distributed.GradBucket.is_last()` should return whether the bucket is the last to all-reduce in an iteration. However, [the current implementation returns if the index is 0](https://github.com/pytorch/pytorch/blob/ee82e7a14ea55101dfe4d245c4c9413b8313fc4c/torch/csrc/distributed/c10d/comm.hpp#L65-L67), which corresponds to the first bucket to all-reduce.

If this is fixed, then we should follow-up to https://github.com/pytorch/pytorch/pull/63164 with the change described in https://github.com/pytorch/pytorch/pull/63164#discussion_r688022154. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
self-assigned to reserve it as a bootcamp task

**Comment by mrshenli** [comment]
## Background

The `GradBucket` is defined in the location below. It is used by DistributedDataParallel (DDP) to perform gradient synchronization. This [note](https://pytorch.org/docs/stable/notes/ddp.html) and [paper](http://www.vldb.org/pvldb/vol13/p3005-li.pdf) explain how DDP works. 

https://github.com/pytorch/pytorch/blob/32b6104f37a0d2db68fb8378143ed7c7685c4782/torch/csrc/distributed/c10d/comm.hpp#L17-L31

The `GradBucket` is also exposed as a Python type through pybind and used by [DDP communication hook](https://pytorch.org/docs/stable/ddp_comm_hooks.html). 

https://github.com/pytorch/pytorch/blob/32b6104f37a0d2db68fb8378143ed7c7685c4782/torch/csrc/distributed/c10d/init.cpp#L264-L330

## Problem Statement

Some DDP communication hooks needs to know whether the current `GradBucket` is the last one or not, and if yes, the hook will finalize the backward pass. Currently, the `is_last()` API returns `True` when the index is 0, but we believe this is incorrect. The bucket orders are determined at two different locations. 

1. During `Reducer` construction: it uses the reserve order of buckets, so that the bucket order could approximate the backward order, i.e., bucket0 fires first.
 
 
 
 https://github.com/pytorch/pytorch/blob/32b6104f37a0d2db68fb8378143ed7c7685c4782/torch/nn/parallel/distributed.py#L629-L645 
2. DDP bucket rebuild: parameters are pushed to the vector based on the autograd order, i.e., bucket0 fires first. 
    https://github.com/pytorch/pytorch/blob/32b6104f37a0d2db68fb8378143ed7c7685c4782/torch/csrc/distributed/c10d/reducer.cpp#L641


In both case, bucket0 fires first (@rohan-varma @SciPioneer please correct me if I was wrong). So `is_last()` should return when its index equals the number of buckets.

**Comment by andwgu** [comment]
> So is_last() should return when its index equals the number of buckets.

nit: This should be equal to the number of buckets - 1 (since zero-indexed)?

**Comment by SciPioneer** [comment]
> > So is_last() should return when its index equals the number of buckets.
> 
> nit: This should be equal to the number of buckets - 1 (since zero-indexed)?

# of buckets is not stored in `GradBucket`. Wonder if we can always use `is_first()` with small changes in the application code instead.

**Comment by mrshenli** [comment]
>  I wonder if we can always use is_first() with small changes in the application code instead

There are use cases for `is_last()`, e.g., the ZeroRedundancyOptimizer non-interleaved hooks need run optimizer computation and communication when the bucket is the last one.

**Comment by awgu** [comment]
I think this can be closed by https://github.com/pytorch/pytorch/pull/63768. The follow up to https://github.com/pytorch/pytorch/pull/63164 is also no longer needed.
