### ISSUE TITLE
Exporting the operator tile to ONNX is not supported. 

### ISSUE THREAD

**Issue by IpekUyguner** [pytorch/pytorch#63796]
## 🚀 Feature
torch.tile() is not supported in ONNX. Is it possible to add it or any workaround?
 

cc @BowenBao @neginraoof

**Comment by fatcat-z** [comment]
Could you please try to use torch.repeat() to replace torch.tile() function? They are similar and torch.repeat() is supported by exporter now.

**Comment by fatcat-z** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1335018.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
