### ISSUE TITLE
[project/wishlist] splitting embedded TH* libraries ?

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#640]
Torch7 (luajit) ships another copy of source of libTH* libraries.
Then which one is the "master" branch for the code of libTH* ? The original one shipped in torch7 or the one embedded in pytorch? How are they synchronized?

https://tracker.debian.org/pkg/lua-torch-torch7  
https://tracker.debian.org/pkg/lua-torch-nn  

As shown by the above links, libTH.so and libTHNN.so and their corresponding headers are already packaged for Debian/Experimental. Maybe pytorch can use some of the libraries provided by torch7?

**Comment by apaszke** [comment]
It's not another copy, it's the same code. We're using git subtrees to sync both repos, and we're considering torch/* to be master, but we also accept PRs here, and push the changes upstream.

Not sure what do you mean when you say "Maybe pytorch can use some of the libraries provided by torch7?". We're using the same library code, but we can't use the same .so files, because of differences in `TH_INDEX_BASE` (that's why pytorch's libs have different soversion than the ones in Lua torch). We plan to make it a run time constant, but it's not yet implemented.

**Comment by CDLuminate** [comment]
`"Maybe pytorch can use some of the libraries provided by torch7?"` means Maybe the `libTH*.so` files provided by torch7 can be used to compile pytorch. In this way Debian maintainers can reduce work maintaining pytorch/torch packages.

Pytorch and Torch7 cannot shared the same .so files unless the `TH_INDEX_BASE` issue is solved -- Is my understanding correct?

**Comment by apaszke** [comment]
Yes, correct. Unfortunately that's also not the highest priority for now. We'd have to change the signatures of all TH functions to take `THState` as the first argument. It's a huge and breaking change.

**Comment by CDLuminate** [comment]
Thanks, this is helpful for distribution package maintainers.

**Comment by soumith** [comment]
we're not going to solve this completely.
However, it might be notable that with pytorch, we explicitly link against libTH.so.1 instead of torch7's libTH.so.0
