### ISSUE TITLE
THPPointer cannot handle the case when assigning to itself.

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/pytorch#64132]
See the code
https://github.com/pytorch/pytorch/blob/a3a7a67048c11ee74fbdd54037a6dbaf90367964/torch/csrc/utils/object_ptr.h#L18

When `&p == this`, it results in errors.

**Comment by soulitzer** [comment]
Does this happen anywhere in the code?  This can only happen if someone writes `a = std::move(a)` right?

**Comment by csukuangfj** [comment]
No. But that is a pattern in C++ and this kind of code leaves a door open to bugs.

**Comment by soulitzer** [comment]
That is fair, but my point was that for something to be on LHS of an assignment, it needs to be an lvalue, and since this is a move assignment the lvalue needs to be explicitly it to an ravlue via `std::move`. Therefore the only case where the issue happens is when someone writes `a = std::move(a)`, and we would be OK with not supporting that use case.
