### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

### ISSUE THREAD

**Issue by captain81** [pytorch/pytorch#64283]
Hi,
I’m trying to convert a pytorch model to onnx, but the conversion gives the following error:

RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

The definition for qfn is:

class qfn(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input, k):
        n = float(2**k - 1)
        out = torch.round(input * n) / n
        return out

    @staticmethod
    def backward(ctx, grad_output):
        grad_input = grad_output.clone()
        return grad_input, None

qfn_tmp = qfn.apply

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment]
@captain81  
Please check https://github.com/pytorch/pytorch/blob/master/docs/source/onnx.rst#torch-autograd-functions

**Comment by AllenTiTaiWang** [comment]
Hi @captain81 ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
