### ISSUE TITLE
Nightly MacOS M1 builds are broken

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#64649]
From [binary_macos_arm64_conda_3_9_cpu_nightly_build]( https://app.circleci.com/pipelines/github/pytorch/pytorch/377348/workflows/45cd19e8-a05d-49bc-8260-c9e4a9525225/jobs/15904309): 
```
/Users/distiller/project/conda/conda-bld/pytorch_1631110279997/work/third_party/tensorpipe/third_party/libuv/src/unix/async.c:217:31: error: use of undeclared identifier
      'UV_NONBLOCK_PIPE'
  err = uv__make_pipe(pipefd, UV_NONBLOCK_PIPE);
                              ^
1 error generated.
```

Happened because of some change in the environment as it is also affecting historical builds.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra @albanD @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma

**Comment by lw** [comment]
This issue seems to come from _within_ libuv, a dependency of TensorPipe.

First guess: there's two conflicting versions of libuv (e.g., a preinstalled one and the one shipped as a submodule of TensorPipe), and we build the one shipped by TensorPipe but somehow it ends up including the headers of the other one?

In particular, the constant it's complaining about was added in https://github.com/libuv/libuv/commit/4ddc292774be827a297449e2d5ef4047c85de7ca, which became part of libuv 1.41.0, which is the version that TensorPipe bundles. But it seems those jobs are installing version 1.40.0 via conda:
```
Sep 08 07:16:19 The following NEW packages will be INSTALLED:
Sep 08 07:16:19     libuv:             1.40.0-haf1e3a3_0    
```

So the question is why are the conda headers picked up and prioritized? I feel this will require some CMake digging, and it's possible that the fix will have to land in libuv's upstream CMake files. Ugh.

**Comment by lw** [comment]
BTW, if you want to validate this theory you can try setting this flag to `OFF`:
https://github.com/pytorch/pytorch/blob/b616132403697a043fd9691693e40f407e77063a/cmake/Dependencies.cmake#L1415
Which will cause TensorPipe to use the preinstalled libuv instead of building its own one.

But please don't land this "workaround", as it will only lead to users coming to complain that they couldn't build PyTorch because their system has a libuv version that is too old for what TensorPipe needs.

**Comment by malfet** [comment]
@lw, this is definitely what is happening: libuv-1.40 is installed from conda, which does not have `UV_NONBLOCK_PIPE` in the header: https://github.com/libuv/libuv/blob/v1.40.0/include/uv.h

But I'm still confused why it started to happen just now

**Comment by malfet** [comment]
Finally found a PR that caused a regression:  https://github.com/pytorch/builder/pull/842 (and testing were clearly regressed in CI: https://github.com/pytorch/pytorch/pull/64552 )
