### ISSUE TITLE
Some tests are running multiple times

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#65012]
This was pointed out by @albanD, we are missing some entries here https://github.com/pytorch/pytorch/blob/master/test/run_test.py#L82-L94 for https://github.com/pytorch/pytorch/blob/master/test/autograd/test_complex.py. It might be worth it to spot check some test reports with a `grep def test_` of `test/*` until we see that the numbers match too

cc @mruberry

**Comment by malfet** [comment]
I don't think it will work like that, as some tests are only executed on certain platforms and a lot of tests are generated from templates, so there are no easy formulaic correlation between  `grep def test_ fname.py|wc -l` and actual number of tests it is going to run.

Otherwise, we already have a mechanism that raises a warning if same test is found twice, perhaps we just need to extend it
https://github.com/pytorch/pytorch/blob/ff6b475d4a7e35d71eabfbd7bcbcada3a449ddce/tools/stats/print_test_stats.py#L647-L648

**Comment by malfet** [comment]
This does not seem to be affecting CI anymore, closing
