### ISSUE TITLE
Fix autograd engine checks

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#65016]
When you accumulate gradient into a tensor with a custom tensor subclass that doesn't match the base tensor (e.g., think sparse gradients), we will fail you:

```
RuntimeError: Function AddBackward0 returned an invalid gradient at index 0 - expected type TensorOptions(dtype=float, device=meta, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)) but got TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))
```

This issue is to relax the checks.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
In more details about what needs to be done here:
- Fix the dtype check to only check dtype https://github.com/pytorch/pytorch/blob/9157a2889f9e17dda1be6b0b137ab1801ba253a9/torch/csrc/autograd/engine.cpp#L708 (the method on TensorOption used is actually also checking device because it checks dispatch keys).
- Add to input metadata a boolean field to know if the input was a subclass https://github.com/pytorch/pytorch/blob/9157a2889f9e17dda1be6b0b137ab1801ba253a9/torch/csrc/autograd/input_metadata.h#L20
- Skip the device check in the engine when either the input or the grad is a subclass https://github.com/pytorch/pytorch/blob/9157a2889f9e17dda1be6b0b137ab1801ba253a9/torch/csrc/autograd/engine.cpp#L715


Note that this is a quick fix until we can properly create "wrapper Tensors" that report the correct device as tracked in https://github.com/pytorch/pytorch/issues/62730
