### ISSUE TITLE
Stale References in RNNBase and Correct Device in Embedding

### ISSUE THREAD

**Issue by bmccann** [pytorch/pytorch#651]
In RNNBase, self.all_weights contains references to all parameters. In the case of using DataParallel, those parameters are replaced by replicate, but the stale references in self.all_weights are sent to cuDNN.

In thnn/sparse.py, Embedding's backward should create grad_weight, _indices, _counts, and _sorted on the same device as grad_output.

**Comment by adamlerer** [comment]
Thanks @bmccann . Yes, it seems that DataParallel has an implicit expectation that a module only holds parameters as module attributes.

This can easily be fixed by constructing `all_weights` on the fly in `forward`. @bmccann are you working on this? Otherwise I can make a PR for it.

P.S. Are you adding data parallel support to OpenNMT? That would be great.

**Comment by bmccann** [comment]
I went this route in my fork:
https://github.com/bmccann/pytorch/tree/rnn_base_references, and I can make
that a PR if it seems solid to you.

And yeah! I'm working on adding DataParallel to OpenNMT here:
https://github.com/bmccann/examples/tree/multi-gpu-nmt. That led me to this
issue, and you can see the changes I've made so far in an attempt to use
DataParallel, but there is still at least one lingering problem that I
haven't figured out. I can keep you updated on progress there.

**Comment by bmccann** [comment]
Made the PR here: https://github.com/pytorch/pytorch/pull/660 for easier comparison.
