### ISSUE TITLE
Pytorch in java

### ISSUE THREAD

**Issue by sm-jalali-f** [pytorch/pytorch#6570]
I create a deep neural network and train it with my data. then i want to use the model in android device.
for example i create neural network that can classify handwriting image. and i want to use this model in android camera?

how use trained model in android or java??

**Comment by goldsborough** [comment]
I would not say that this is possible at the moment. Your best bet is to use [autogradpp](https://github.com/ebetica/autogradpp/), our unofficial C++ API, to rewrite your model in C++, and then use JNI to wrap it.

We are actively working on an official C++ API [here](https://github.com/pytorch/pytorch/pull/6345) and we'll make sure to allow deserialization of models written in Python. But this is still a little far away at the moment. You'll have to use JNI either way.

You may also be able to export your model to Caffe2 with ONNX, and then wrap the inference code (maybe 30 lines of C++).

Of course, you could also put your Python model behind a REST server somewhere and make calls to it, if feasible.

**Comment by orionr** [comment]
As an example of an Android application running a Caffe2 model, feel free to take a look at https://github.com/caffe2/AICamera

**Comment by soumith** [comment]
@sm-jalali-f here's a tutorial on taking pytorch trained model, putting it in onnx format and deploying it to Android / iOS device via Caffe2: http://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html

**Comment by hadim** [comment]
Hello. Just to clarify things, there is no plan to add Java support (not Android only) to pytorch in a near future correct? I am considering switching from TF to pytorch but the lack of Java support is currently a limitation in my case.

**Comment by soumith** [comment]
We dont have any immediate plans to support Java.

**Comment by mobiusinversion** [comment]
@sm-jalali-f Just use TensorFlow, its easy:

In Python:

        builder = tf.saved_model.builder.SavedModelBuilder(path)
        builder.add_meta_graph_and_variables(sess, [tf.saved_model.tag_constants.SERVING])
        builder.save(False)

In Java:

        SavedModelBundle.load(path, "serve").session();

@soumith @goldsborough

**Comment by hadim** [comment]
I am not sure this is the good place to troll about TF/PyTorch... (I am a TF user myself).

**Comment by beyondpie** [comment]
Hi, I wonder is it possible for java to run pytorch through Jython?

**Comment by nvinayvarma189** [comment]
Yeah, I have the same query as @beyondpie has. Is it possible to use Pytorch through Jython? JNI is required to run the CPython extensions. Right? Even if this is possible, I'm not sure how smooth this can be considering that Jython supports only Python 2.X and JNI can handle only CPython extensions (like numpy), meaning if pytorch has dependencies other those which are CPython extensions, even JNI can't be of any help.

Your views, please? @soumith @ezyang @apaszke @gchanan

**Comment by ezyang** [comment]
I'm not going to say it's impossible. It's going to take someone with determination though.

**Comment by dwilliams999** [comment]
It is not currently possible.   Your best best is to use the Tensorflow JNI bindings, and write a DSL layer.  The PyTorch authors have decided not to support Java, and that’s the current state.

@beyondpie @nvinayvarma189

**Comment by dwilliams999** [comment]
One other thing, the Jython interpreter is heavy, expensive, and not thread safe.  I recommend LuaJ, Clojure, or JavaScript with Nashorn / GraalVM.

**Comment by gerwang** [comment]
Since pytorch 1.3 has added android support, is it possible now to run pytorch from Java on x86 platforms?

**Comment by ezyang** [comment]
@gerwang I heard from @dreiss that this is something we'll be doing soon.

**Comment by fjug** [comment]
That would be sooo cool! (What kind of 'soon' are we talking?) :wink:

**Comment by dreiss** [comment]
Should be ready in a few weeks.  I've got it working on my laptop, but we need to clean up one of our dependencies before we can make a release that I'd feel good about.

Just as a reminder, this won't be the full torch/ATen API.  It will be the inference-oriented API that we're supporting on Android: https://pytorch.org/docs/stable/packages.html

**Comment by dreiss** [comment]
This is ready for some preliminary testing.  We'll get the setup procedure significantly simplified before the 1.4 release.  Please provide feedback!

- Download and unpack libtorch 1.3 or nightly.  (From the pytorch.org homepage under "Quick Start
Locally", make sure "LibTorch" is the selected package.)
- Make sure you have a recent Gradle and CMake installed.  Also elinks if you want test results displayed in the terminal.
- Check out PyTorch *master* from git.
- Apply this patch: https://gist.github.com/dreiss/a4914508fbcf973a8c8dc137cae249a4
- Run these commands: https://gist.github.com/dreiss/7c30ea0fc836d607ff899d9e3927466e .  You'll need to edit the paths at the top.  If you're on Mac, you'll probably need to change LD_LIBRARY_PATH to DYLD_LIBRARY_PATH and turn off SIP (see https://github.com/conda-forge/staged-recipes/issues/913 ).  On Windows, you might need to tweak our CMake scripts to find the proper JNI include files.
- This will build the library and run the tests.  In order to use them in your own application, you'll need to grab `./build-cmake/libpytorch.so` and `./build-cmake/fbjni/host/libfbjni.so` and put them in your library path, plus grab `./build-gradle/libs/pytorch_host.jar` and incorporate that into your build and runtime environment.
- My plan is to get the two `.so` files bundled into the official libtorch nightlies and releases, and get the host jar into jcenter, so by the time 1.4 releases, the only setup steps should be "Download libtorch, set your library path, add a one-line gradle dep".

**Comment by mathpopo** [comment]
>     * so by the time 1.4 releases, the only setup steps should be "Download libtorch, set your library path, add a one-line gradle dep".

good job,wish quickly.

**Comment by dreiss** [comment]
Nightly libtorch builds now include JNI bindings on Linux.  Mac and Windows will follow.  The Java API is now on Sonatype.  

Here's a repository that demonstrates how to use it: https://github.com/dreiss/java-demo .  Setup instructions are in the readme.  They're very short and don't require building any C++ code or checking out the PyTorch repository.

Please send feedback!

**Comment by suyashjoshi** [comment]
> Nightly libtorch builds now include JNI bindings on Linux. Mac and Windows will follow. The Java API is now on Sonatype.
> 
> Here's a repository that demonstrates how to use it: https://github.com/dreiss/java-demo . Setup instructions are in the readme. They're very short and don't require building any C++ code or checking out the PyTorch repository.
> 
> Please send feedback!

Love to try it but I'm on Mac and currently looks like project is for Linux only.

**Comment by dreiss** [comment]
Last night's nightly build now includes the JNI bindings for Mac.  However, they fail to load when trying the demo program.  (It starts loading libpytorch_jni, but fails to find libfbjni.)  I don't use Mac, so I'm not able to debug it.  If someone wants to give this a try and figure out what's wrong, that would be awesome.  In the past, I've seen this sort of error be related to System Integrity Protection, so that might be one place to look.

**Comment by volpato30** [comment]
> Nightly libtorch builds now include JNI bindings on Linux. Mac and Windows will follow. The Java API is now on Sonatype.
> 
> Here's a repository that demonstrates how to use it: https://github.com/dreiss/java-demo . Setup instructions are in the readme. They're very short and don't require building any C++ code or checking out the PyTorch repository.
> 
> Please send feedback!

It seems the current Java API only supports CPU mode. Is there any plan to add CUDA support in the near future?

**Comment by dreiss** [comment]
No immediate plans to add CUDA to the API, but it should be possible to use CUDA by adding a method to your TorchScript model that takes the input as a CPU tensor, sends it to CUDA, runs the rest of the model, the brings the result back to the CPU before returning to Java.  Feel free to give it a try and let me know how it goes!

**Comment by dreiss** [comment]
Nightly libtorch releases now have working JNI bindings on Mac.  The demo repo has been moved to https://github.com/pytorch/java-demo/ , and the readme has been updated to include instructions for running against a nightly release.

Windows support is turning out to be much more complicated than I thought.  I'll still put some more effort into it, but I can't guarantee that we'll be able to support this.  I've filed https://github.com/pytorch/pytorch/issues/32516 to track Windows support.

I'm going to close this issue because Java support is working now.  Please file separate issues for any problems you run into with it.  And feel free to comment on this issue to let us know that you're using it successfully!

**Comment by dreiss** [comment]
Confirming that it's possible to use CUDA models from Java with a little help from TorchScript: https://github.com/dreiss/java-demo/issues/2

**Comment by fzwqq** [comment]
> Confirming that it's possible to use CUDA models from Java with a little help from TorchScript: [dreiss/java-demo#2](https://github.com/dreiss/java-demo/issues/2)

Yes, the example works well. But it seems to set all the parameters of model without grad, how to do if we load the model from checkpoint.
