### ISSUE TITLE
Closing tar file in `TarFileReader` breaks buffered datapipes

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#65808]
```python
from torch.utils.data.datapipes.iter import IterableWrapper, TarArchiveReader, FileLoader, Shuffler

# instantiate dp from any tar archive, 
# e.g. https://github.com/pytorch/data/blob/main/examples/vision/fakedata/caltech101/101_ObjectCategories.tar.gz
dp = FileLoader(dp)
dp = TarArchiveReader(dp)
dp = Shuffler(dp)

_, buffer = next(iter(dp))
buffer.read()
```

```
ValueError: seek of closed file
```

If the `buffer_size` of `Shuffler` exceeds the number of files in the tar archive, this triggers

https://github.com/pytorch/pytorch/blob/07d5d7b5cc83422913958a78eb5c8c60ae181be0/torch/utils/data/datapipes/iter/tararchivereader.py#L59-L60

which also makes it impossible to read from the files within the closed archive.

This was introduced in #64788. cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Looking into why our test doesn't cover this case.

We did add a test to validate all file descriptors are yielded before reading here.
https://github.com/pytorch/pytorch/blob/aebde1bc2be708607cc9c6baf9fe402b368eb946/test/test_datapipe.py#L247-L253

**Comment by NivekT** [comment]
I have taken a look and this issue arises when the `TarArchiveReader` DataPipe is read into an intermediate object (e.g. a buffer), and then read from the buffer later. This is because the `finally` executes after the DataPipe is read into the buffer, thus closing the stream. In contract, if you apply `map` to the DataPipe, since `map` also yields one at a time, it still works.
```
path = '/Users/ktse/101_ObjectCategories.tar.gz'
dp = IterableWrapper([path])
dp = FileLoader(dp)
tar_dp = TarArchiveReader(dp)

buffer = []
for item in tar_dp:
    buffer.append(item)
for fname, stream in buffer:
    print(stream.read())  # Fails

# Other Examples:
shuffle_dp = Shuffler(tar_dp)  # Fails, has buffer
batch_dp = tar_dp.batch(batch_size=1)  # Works, no buffer
bucket_batcher_dp = tar_dp.bucketbatch(batch_size=1)  # Fails, has buffer
map_dp = tar_dp.map(lambda x: x)  # Works
```

I am making a PR to remove the `finally` clause. Then, I will make more comprehensive changes to allow similar DataPipes to 1) keep track of what streams are open and 2) give users the ability to close those streams.
