### ISSUE TITLE
Implementation of Parameterized Hypercomplex Multiplication Layer

### ISSUE THREAD

**Issue by Demirrr** [pytorch/pytorch#65916]
[Zhang et al. [2021]](https://openreview.net/forum?id=rcQdycl0zyk) proposed the parameterized hypercomplex multiplication (PHM) layer. According to their results, this layer enjoys parameter efficiency without decreasing modelling capability of an affine transformation. This paper is selected as a best paper in [ICLR 2021](https://iclr-conf.medium.com/announcing-iclr-2021-outstanding-paper-awards-9ae0514734ab).

I have already implemented the proposed method to use it in my own research by [following the implementation of linear transofrmation in pytorch](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear). Hence, I was wondering whether my implementation would be useful for other PyTorch users.

Cheers,

cc @albanD @mruberry @jbschlosser @walterddr

**Comment by albanD** [comment]
Hi,

Thank you for suggesting this.
From looking at the paper release date and the number of citation on google scolar, I do not think we want to add it to PyTorch core at the moment.
The best place for such projects is on a personal github repo to share it with the community.

On the future, if the paper and/or the repo has gained significant traction from the community, feel free to re-open this issue so that we can discuss the possibility to add this to core again.
