### ISSUE TITLE
No win cuda tests are running on PRs?

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#66471]
On https://github.com/pytorch/pytorch/pull/65948, it looks like we did not actually run CUDA tests for windows builds: https://github.com/pytorch/pytorch/actions/runs/1321834530. Notice the lack of gpu tests vs. the equivalent master commit: https://hud.pytorch.org/commit/a6774d6e1f3a88f931a3786b7c2617a74bdaa50e

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
I agree that current messaging about smoke tests is a bit confusing.
Few thoughts:
- PR that do something quite fundamental as rectifying THC should run with `ciflow/all`
- Why the same test passed on Linux but failed on Windows?
- Perhaps to avoid the confusion, we should have win-cuda-11.3-smoke-ony workflow (runs only on PRs) and win-cuda-11.3-full (runs with ciflow/win and on master)

**Comment by janeyx99** [comment]
Based on the stats gathered on 219 commits since removing Windows CUDA testing from PRs, an estimate of 8 reverts were due to broken Windows CUDA tests on trunk (3 of them were from before smoke tests were added), which is smaller than 4%. I think it's okay to not run the full Windows CUDA tests for PRs due to the stats.

I have not yet investigated the value of smoke tests just yet.

**Comment by janeyx99** [comment]
Looking at our collected stats for our smoke_tests job since its introduction on 10/4/21, about 2.26% of the jobs failed (~137/6.05k), contrasted with 8.12% for any test PR job. This suggests that windows smoke tests provides nonzero value, but not at all more than other PR jobs. This is not surprising as we do test a significantly smaller subset of tests for this job compared to other jobs, and most PyTorch developers are not working with Windows specific things often.

To capture what was considered a meaningful failure, I limited
- failed step to "Test" to exclude some other steps that may have failed due to infrastructure flakiness
- conclusion to "failed" to weed out cancelled jobs
- the logs to exclude "No module named torch" as that was another common flaky error.

The result was a total of ~137 legitimate failures out of 6000. If you are a FB employee, you can observe the statistics [here](https://fburl.com/scuba/opensource_ci_jobs/irlfwl3k). 

To compare with any PR test job, I calculated that the failure rate for any test job on PRs is around 8.12%.
- There were around 20.82k failed test jobs on PR based on stats [here](https://fburl.com/scuba/opensource_ci_jobs/w0tvo95p)
- There were a total of around 256.17k PR tests jobs [here](https://fburl.com/scuba/opensource_ci_jobs/q4s7uyp0).

**Comment by janeyx99** [comment]
Based on the above rough analysis, we should probably keep smoke tests for Windows.
