### ISSUE TITLE
libcaffe2.a for Android is too large

### ISSUE THREAD

**Issue by funzhang** [pytorch/pytorch#6652]
I built the libcaffe2.a for android as the guide[./scripts/build_android.sh]. The build is success, but I find that the library is too large[800MB+]. The library file in Android Demo(such as AICamera-Style-Transfer & AICamera) is small[Only 60MB]. Is there a way to reduce the file size? How to config?

**Comment by yinghai** [comment]
@Maratyszcza

**Comment by Maratyszcza** [comment]
It doesn't make much sense to look at the size of `libcaffe2.a`, because it is just a collection of object files. They contain duplicates of the same symbols, and much debug information. The size you should be looking it is increase in the size of your shared library after you link `libcaffe2.a`: the linker will remove duplicate symbols, and can strip debug symbols.

**Comment by funzhang** [comment]
Thank you for your help. I will try it.
