### ISSUE TITLE
[elastic] Keep rank 0 static during the distributed elastic training

### ISSUE THREAD

**Issue by gaocegege** [pytorch/pytorch#67615]
## 🚀 Feature

Keep rank 0 static during the distributed elastic training

## Motivation

The rank 0 will change (e.g. from agent1.worker1 to agent2.worker2) when the worker group failed and the workers re-join the rendezvous.

Can we support keeping rank 0 static during the fault-tolerant mode?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by gaocegege** [comment]
oncall: elastic

**Comment by gaocegege** [comment]
cc @kiukchung

**Comment by kiukchung** [comment]
As documented in the [rendezvous docs](https://pytorch.org/docs/stable/elastic/rendezvous.html) ranks are not stable by design.

![image](https://user-images.githubusercontent.com/43595115/139703120-4d7e6fb4-5073-404c-9599-af07833befab.png)

This is so that a new implicit (rank 0) master is assigned on each rendezvous even when agent 0 or trainer 0 is lost. Could you elaborate more on the particular use-case that would require rank 0 to be static and how you'd like to deal with agent 0 and/or trainer 0 going down (in this case you would HAVE to re-assign ranks)?

**Comment by gaocegege** [comment]
@kiukchung Thanks for your reply.

The rank-0 trainer will do some additional logic with its local storage. Thus I expect to keep it static. But I think it makes sense to keep it dynamic.
