### ISSUE TITLE
Convert pytorch to onnx, Unsupported: ONNX export of operator adaptive_avg_pool2d

### ISSUE THREAD

**Issue by Sobel-Li** [pytorch/pytorch#67611]

**Comment by hwangdeyu** [comment]
Could you please provide more details, such as minimum script for us to reproduce the issue?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.

**Comment by listener17** [comment]
Hi all: 

I'm getting this error while trying ONNX export on our model. 

`RuntimeError: Unsupported: ONNX export of operator adaptive_avg_pool2d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.`

Is it expected ONNX will support the export of adaptive_avg_pool2d anytime soon?
Is there any workaround?
