### ISSUE TITLE
Support for quantized model's function

### ISSUE THREAD

**Issue by Force1ess** [pytorch/pytorch#67967]
## To Reproduce

1. Load a model from torchvision.quantization
2. run`next(model.named_parameters())` 
3. StopIteration Raised

## Expected behavior
This expects to return a generator like normal models, but it works doesn't well on quantized models
## Additional context
This bug is obvious, I don't think it need any additional info

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by Force1ess** [comment]
By the way, copy.deepcopy also cannot copy all original quantized model's property, that's not good

**Comment by HDCharles** [comment]
looks like this is due to the weights of quantized ops not being set as parameters, not sure if this is a bug because a parameter is supposed to be a tensor and we don't actually store the tensors, we pack in a packedparams object so that they can be used quickly by the quantized op. Unsure if there's a way to remedy this.

**Comment by Force1ess** [comment]
@vkuzo Hi,
I'm not a English native, can you explain me the meaning of KP？
And I want to assure that copy.deepcopy can copy full state_dict of quantized model
Thanks

**Comment by vkuzo** [comment]
> I'm not a English native, can you explain me the meaning of KP？

Sure, KP is an abbreviation of "known problem", this is an issue which has also been reported previously and we are aware of it.  Here is the existing issue: https://github.com/pytorch/pytorch/issues/47311

> And I want to assure that copy.deepcopy can copy full state_dict of quantized model

The recommended way to save quantized models is to save the state dict instead of the model.  To load, quantize the model again with dummy weights and then load the state dict.  `torch.save` and `torch.load` is not supported well on quantized models, which is why we recommend the state dict.
