### ISSUE TITLE
Audit use of matmuls in backward formulas of linear algebra operations

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#68020]
By default, matmul on Ampere cards will use tf32, and this leads to unacceptable accuracy loss for linalg ops. 
When linalg ops are using magma, we are disabling tf32, but in other cases there's no systematic approach. 
see #67948

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @zasdfgbnm @ptrblck

**Comment by vadimkantorov** [comment]
It may be useful for functions like matmul / conv to have explicit hints/algo arg...

**Comment by mruberry** [comment]
Notes from linalg meeting:

- we can't programmatically detect this so it will require manual review
- suggestion: throw an error/warning whenever this occurs and run the OpInfo and/or linalg tests
- some tests disable TF32 matmuls so that would need to be changed or different tests run
- there are no known cases where TF32 should be enabled for a linear algebra operation
- torch.matmul and torch.linalg.matmul should remain consistent, however
- we should see if the TF32 global issue resolves this for us
