### ISSUE TITLE
Upgrade macOS and iOS workflows to xcode 12.4+

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#68039]
## 🚀 Feature

In the future we'd like to upgrade all macOS and iOS workflows for PyTorch CI to more modern versions of xcode.

However in previous attempts to do this we've encountered some issues like: https://github.com/pytorch/pytorch/pull/67717#issuecomment-963485900

This issue is meant as a tracking issue to track both the progress of upgrading to xcode 12.4 as well as the issues that come along with upgrade to xcode 12.4

cc @seemethere @malfet @pytorch/pytorch-dev-infra @albanD

**Comment by malfet** [comment]
After adding debug prints to 
https://github.com/pytorch/pytorch/blob/cdd5d16489fa4563b16ddd3ef338dbeb37063d80/aten/src/ATen/core/ivalue.h#L1230
and
https://github.com/pytorch/pytorch/blob/cdd5d16489fa4563b16ddd3ef338dbeb37063d80/aten/src/ATen/core/custom_class.cpp#L90-L91
I finally know what is going on: even though the name of method is the same, hash code can be different, probably due to non-unique implementation of typeinfo, see 
https://github.com/llvm/llvm-project/blob/0309e50f33f616baa8fcac8365b728be3ccf06dd/libcxx/include/typeinfo#L136
