### ISSUE TITLE
Question about wait() for asynchronous collective operations with NCCL

### ISSUE THREAD

**Issue by vycezhong** [pytorch/pytorch#68112]
I notice that the semantics of `wait()` for CPU collectives and CUDA collectives are different as shown in the documentation (https://pytorch.org/docs/stable/distributed.html#synchronous-and-asynchronous-collective-operations). 

> `wait()` - in the case of CPU collectives, will block the process until the operation is completed. In the case of CUDA collectives, will block until the operation has been successfully enqueued onto a CUDA stream and the output can be utilized on the default stream without further synchronization.

I don't get the point about "the output can be utilized on the default stream without further synchronization". In my understanding, returning from `wait()` does not mean that the CUDA collective operation is finished. It may still be running on the GPU. Then how could we directly use the output without further synchronization?

To be specific, suppose we want to perform allreduce on a tensor named `x` and then print the value of it. Does PyTorch guarantee that the allreduce operation is completed when we print the value of `x`?
```py
torch.distributed.allreduce(x)
print(x)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by pritamdamania87** [comment]
> In my understanding, returning from wait() does not mean that the CUDA collective operation is finished. It may still be running on the GPU. Then how could we directly use the output without further synchronization?

CUDA's programming model is asynchronous and by default everything runs in parallel, however in some cases we need sequential execution due to dependencies between two computations. For this purpose CUDA has streams: https://developer.download.nvidia.com/CUDA/training/StreamsAndConcurrencyWebinar.pdf, where the operations on a single stream are executed in the order that they are scheduled on that stream.

Let us take this example:

```
t = torch.rand(10, 10, device="cuda")
x = torch.rand(10, 10, device="cuda")
work = torch.distributed.allreduce(x)
t1 = t + t
work.wait()
res = x + x
```

There are two streams involved here. The first stream is the PyTorch default stream (s1) and ops like `t = torch.rand(10, 10)` etc. are sent to the default stream and as a result we get nice sequential execution on a single stream. However, when we do `torch.distributed.allreduce(x)` we don't want to block the default stream since unrelated operations like `t1 = t + t` can execute without waiting for the allreduce to finish. As a result, we use a separate CUDA stream (s2) to do the allreduce such that compute and communication can overlap.

Now we come to the part of `res = x + x`, this operation depends on the result of allreduce which runs on stream s2, whereas this computation needs to run on stream s1. The `work.wait()` call does the necessary work of synchronizing these streams such that s1 waits for the work on s2 to finish before proceeding.

Although, note that the execution on CUDA is all still async. So when `work.wait()` returns the allreduce hasn't finished but we have only instructed stream s1 to wait for s2. Even when `res = x + x` executes and returns the operation hasn't finished successfully, we are only launching (or queueing) these operations to the GPU. You actually need to use something like https://pytorch.org/docs/stable/generated/torch.cuda.synchronize.html to actually block for all GPU execution to finish.

> To be specific, suppose we want to perform allreduce on a tensor named x and then print the value of it. Does PyTorch guarantee that the allreduce operation is completed when we print the value of x?

Yes, PyTorch guarantees that the allreduce operation is completed when we print since `allreduce` by default has `async_op=False` which causes `wait()` to be called internally.

**Comment by vycezhong** [comment]
@pritamdamania87  Thank you so much for your detailed explanation! It makes clear now!

**Comment by lorenzocesconetto** [comment]
This is a very clarifying issue, but just for the record I'd like to point out a couple things:

1. The example code is missing `async_op=True`, otherwise the explanation wouldn't make sense.
```python
...
work = torch.distributed.allreduce(x, async_op=True)
...
```

2. I think when `async_op=False` it's not that `wait()` gets called, but rather the NCCL kernel is enqueued into the current active stream, since streams are sequential, it's safe to enqueue new kernels later on that use the result from `allreduce`. Also, when you call `print`, it actually implicitly causes a host-device synchronization, i.e., a `cudaMemcpy` from device to host. So the host will wait for that synchronization to happen before printing the tensor. Assuming all modifications to `x` are in the same stream, it should be safe to use it cause you'll get the latest value.
