### ISSUE TITLE
DISABLED test_nadam (__main__.TestOptim)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68171]
Platforms: dynamo

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/9605//console

```
10:35:33 ======================================================================
10:35:33 FAIL [0.421s]: test_nadam (__main__.TestOptim)
10:35:33 ----------------------------------------------------------------------
10:35:33 Traceback (most recent call last):
10:35:33   File "test_optim.py", line 630, in test_nadam
10:35:33     lambda weight, bias: optimizer(
10:35:33   File "test_optim.py", line 231, in _test_basic_cases
10:35:33     make_two_arg_constructor(constructor, maximize),
10:35:33   File "test_optim.py", line 209, in _test_state_dict
10:35:33     self.assertEqual(bias, bias_cuda)
10:35:33   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1928, in assertEqual
10:35:33     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
10:35:33 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 10) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.9073486328125e-05 (-1.0852036476135254 vs. -1.0851845741271973), which occurred at index 1.
10:35:33 
10:35:33 ----------------------------------------------------------------------
```

cc @ezyang @gchanan @zou3519 @jansel @lezcano @fdrocha @bdhirsh @jbschlosser @vincentqb @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by ngimel** [comment]
Tolerance issue

**Comment by KyleCZH** [comment]
Hi @mruberry 
can we close this issue?

I found out that the test passes when running with single gpu. Because now test 1, 2 force jobs to run on only 1 gpus, I think we can close this issue:
https://github.com/pytorch/pytorch/blob/8880e3a3c72c9dc24f82ba3c12303181c0af08d8/.jenkins/pytorch/test.sh#L42

log:

$ /var/lib/jenkins/pytorch# CUDA_VISIBLE_DEVICES=0 python3 test/test_optim.py -v TestOptim.test_nadam

test_nadam (__main__.TestOptim) ... /opt/conda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
ok

----------------------------------------------------------------------
Ran 1 test in 2.030s

OK

**Comment by albanD** [comment]
This is a new error now related to dynamo

**Comment by jeffdaily** [comment]
> the platforms list still claims rocm?

Would it break the bot automation if we removed the platform: rocm from the issue?  It's no longer a rocm issue.

**Comment by zou3519** [comment]
Test has a skip label. Closing this issue. Use https://github.com/pytorch/pytorch/issues/103322 to track.
