### ISSUE TITLE
torch.stack() err in pytorch 0.4.0 - TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not collections.deque

### ISSUE THREAD

**Issue by forhonourlx** [pytorch/pytorch#6844]
>>> from collections import deque
>>> import torch
>>> x = deque([torch.ones(3), torch.ones(3)])
>>> torch.stack(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not collections.deque

>>> torch.stack(list(x))
 1  1  1
 1  1  1
[torch.FloatTensor of size (2,3)]

**Comment by SsnL** [comment]
What's wrong with the error?

**Comment by forhonourlx** [comment]
It is not compatible with previous version and exsisting scripts.

**Comment by SsnL** [comment]
It's never a documented behavior so I don't think this is a bug.

**Comment by alvations** [comment]
This should be fixed if you upgrade to `torch>=0.4.1`, `pip install -U torch` =)

**Comment by fmassa** [comment]
I believe this still hasn't been addressed as of version `1.0.0a0+dd2c487`.
I believe though that we should support arbitrary iterables of tensors. Also, the error message is not good, because we support lists of tensors as well (not only tuple of tensors).
My two cents: we should just call `tuple(tensors)` in the beginning of the function call.
This also apply to other functions, like `torch.cat`, where a similar discussion has been raised, see https://github.com/pytorch/pytorch/issues/10182

**Comment by SsnL** [comment]
:) I think the fix is to make TensorList accept a wider range of things.

**Comment by sotte** [comment]
This feature was rejected in #10182 (or `cat`, not `stack`) . So I guess this ticket should be closed as well then?

**Comment by vincentqb** [comment]
The feature was indeed rejected in [comment](https://github.com/pytorch/pytorch/issues/10182#issuecomment-410859656) of #10182. I'll close this issue. Please feel free to re-open if you would like to continue the discussion.
