### ISSUE TITLE
Could not run 'aten::empty_strided' with arguments from the 'HIP'

### ISSUE THREAD

**Issue by ablazet** [pytorch/pytorch#68929]
### Could not run 'aten::empty_strided' with arguments from the 'HIP' backend

When I ran the resnet50 model on an AMD graphics card, I found the above problem. The version used was rocm4.2 and pytorch1.10.0，so how should I solve the problem？

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @fmassa @vfdev-5 @pmeier

**Comment by samdow** [comment]
Could you provide a script to repro and the full stack trace? It would be great to know if you're using the resnet from `torch/vision` and get some more information on this

**Comment by ablazeTang** [comment]
(amd pytorch):test_resnet$ python3 test resnet50.py 
x:torch.Size([128，3，32，32])label:torch.Size([128]) Traceback (most recent call last):
File "test resnet50.py", line 92, in <module> 
        main()
File "test resnet50.py", line 39, in main 
        model =ResNet50().to(device)
File"/anaconda3/envs/amd_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899,in to 
	return self. apply(convert)
File"/anaconda3/envs/amd pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py",line 570,in _apply 
	module. apply(fn)
File"/anaconda3/envs/amd_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py",line 593,in _apply 
	param_applied =fn(param)
File "/anaconda3/envs/amd pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897,in convert 
	return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Could not run 'aten::empty_strided' with arguments from the "hip' backend. 
This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process ( if using custom build).

The full stack trace details are as above. When this code running on NVIDIA card, it can run normally.

**Comment by ablazeTang** [comment]
> Could you provide a script to repro and the full stack trace? It would be great to know if you're using the resnet from `torch/vision` and get some more information on this

(amd pytorch):test_resnet$ python3 test resnet50.py 
x:torch.Size([128，3，32，32])label:torch.Size([128]) Traceback (most recent call last):
File "test resnet50.py", line 92, in <module> 
        main()
File "test resnet50.py", line 39, in main 
        model =ResNet50().to(device)
File"/anaconda3/envs/amd_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899,in to 
	return self. apply(convert)
File"/anaconda3/envs/amd pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py",line 570,in _apply 
	module. apply(fn)
File"/anaconda3/envs/amd_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py",line 593,in _apply 
	param_applied =fn(param)
File "/anaconda3/envs/amd pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897,in convert 
	return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Could not run 'aten::empty_strided' with arguments from the "hip' backend. 
This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process ( if using custom build).

The full stack trace details are as above. When this code running on NVIDIA card, it can run normally.

**Comment by jeffdaily** [comment]
Where can we find the `test_resnet50.py` file?  

If this is a torch application (and not caffe2), then the correct device name for AMD devices is still "cuda" for historical/compatibility reasons.

**Comment by hongxiayang** [comment]
@jeffdaily gave the right answer . let's close this
