### ISSUE TITLE
repr of tensors seems to have extra space

### ISSUE THREAD

**Issue by alok** [pytorch/pytorch#6918]
- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip
- OS: macos 10.13
- PyTorch version: 0.4.0
- Python version: 3.6.5

If I run this code in the interpreter,

```python
import torch
t = torch.tensor([1, 2])
repr(t)
```

I get this output:

```python
tensor([~1,~~2])
```

I put a `~` instead of a space for clarity. As you can see, extra spaces are printed. This happens even if I create a singleton 1D tensor.

**Comment by SsnL** [comment]
There isn't really extra space. It is `" 1" + ", " + " 2"`.

**Comment by Alok** [comment]
Compared to the repr of lists and numpy arrays, that is an extra space. The first element of an array has no space in its string repr, and there should be just one space after the comma. It should be `"1" + ", " + "2"` rather than putting a space before each element rather than a single space after the comma.

Ultimately, this isn't terribly important, but it does make reading arrays feel a bit *off* (to me anyway).

**Comment by fmassa** [comment]
I believe this is to accommodate a possible `-` sign that could appear, and could make the printing odd/tight

**Comment by li-roy** [comment]
Hm, I guess we should match the those functionalities and only add the extra space if there's a minus sign somewhere in the repr.
