### ISSUE TITLE
How to assign tensor to tensor

### ISSUE THREAD

**Issue by LeZhengThu** [pytorch/pytorch#69204]
I have a 3D tensor J, and I want to assign values to it. Below is my code
```
import torch
J = torch.eye(2).unsqueeze(0).expand(5, 2, 2)
for i in range(2):
    J[:, i, :] = torch.randn([5, 2])
```
Then there is an error: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.

**Comment by H-Huang** [comment]
This is because [`expand()` does not allocate new memory](https://pytorch.org/docs/master/generated/torch.Tensor.expand.html#:~:text=Expanding%20a%20tensor%20does%20not%20allocate%20new%20memory%2C%20but%20only%20creates%20a%20new%20view%20on%20the%20existing%20tensor%20where%20a%20dimension%20of%20size%20one%20is%20expanded%20to%20a%20larger%20size%20by%20setting%20the%20stride%20to%200.%20Any%20dimension%20of%20size%201%20can%20be%20expanded%20to%20an%20arbitrary%20value%20without%20allocating%20new%20memory.) so overwriting one index would overwrite everything. The error is thrown to prevent that from happening.

You can create a clone as the message mentions to prevent this:
```
import torch
J = torch.eye(2).unsqueeze(0).expand(5, 2, 2)
# completely new tensor allocated by cloning
J_clone = J.clone()
for i in range(2):
    J_clone[:, i, :] = torch.randn([5, 2])
print(J_clone)
```
or simply not use expand:
```
import torch
J = torch.ones((5,2,2))
for i in range(2):
    J[:, i, :] = torch.randn([5, 2])
print(J)
```
