### ISSUE TITLE
Unexpected Float64 type output for float input to default_collate

### ISSUE THREAD

**Issue by sadrodin1376** [pytorch/pytorch#69446]
https://github.com/pytorch/pytorch/blob/3202028ed1ca24c91dc7192ef69b305690db7abc/torch/utils/data/_utils/collate.py#L78

Hi. When `DataLoader` gets a float array (which in python is equivalent with C's `double`) from the `Dataset`, in its `default_collate` it returns a `torch.DoubleTensor` instance, but normally user expects a `torch.Tensor` instance which, as is stated in the documentation, is an alias of the `torch.FloatTensor` type (equivalent with `numpy.float32`) . This causes users confront with errors like `Found dtype Double but expected Float` in the codes like below:
```
loss = criterion(pred, target) # target comes from Dataset and is of type torch.DoubleTensor,
                               # but pred is of type torch.Tensor
loss.backward()
```
I propose to change the `default_collate` to return a tensor of type `torch.Tensor` (the same `torch.FloatTensor`)

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Thanks for opening the issue.
IMO, as you mentioned, it's way safer for us to use Double because we have zero prior knowledge from users' Dataset implementation. Changing it to float tensor can potentially downcast users' data. You should be able to provide a custom collate_fn to DataLoader to accomplish your requirement.
