### ISSUE TITLE
Incorrect default initialization for convolutional kernels

### ISSUE THREAD

**Issue by emitch** [pytorch/pytorch#6950]
## Issue description

The default initialization for convolutional kernels is missing a factor of sqrt(3), which causes exponential decay in the variance of the outputs in deep networks. The weights are drawn from a uniform distribution, the standard deviation of which has been computed incorrectly.

## Code example

The following code in torch.nn.modules.conv contains the problem:

    def reset_parameters(self):
        n = self.in_channels
        for k in self.kernel_size:
            n *= k
        stdv = 1. / math.sqrt(n)
        self.weight.data.uniform_(-stdv, stdv)
        if self.bias is not None:
            self.bias.data.uniform_(-stdv, stdv)

The standard deviation is computed as 1. / sqrt(n), when it should be sqrt(3) / sqrt(n) in order to preserve the standard deviation of the inputs. It is less clear that this is a problem for the biases (though it isn't clear why the biases are being generated the way they are anyway).

## System Info

PyTorch version: 0.3.0.post4
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 390.25
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/lib64/libcudnn.so.7
/usr/local/cuda-8.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn-900fef33.so.7.0.5
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudnn-a2b758a6.so.7.0.3

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] torch (0.3.0.post4)
[pip] torchfile (0.1.0)
[pip] torchnet (0.0.1)
[pip] torchvision (0.2.0)
[conda] Could not collect

**Comment by soumith** [comment]
So, this is historical to an accidental bug from about ~15 years or so that ended up empirically working better. That being said, in the age of very deep ResNets and ReLUs, I'm not sure if it's still empirically better anymore, someone has to do an ablation study. (resnets btw use Kaiming initialization, I just wanted to talk about modernization of the field)

For full context see my comments in this Google+ thread: https://plus.google.com/+SoumithChintala/posts/RZfdrRQWL6u

The actual initialization comes from [LeCun'98 Efficient Backprop](http://yann.lecun.com/exdb/publis/pdf/lecun-98b.pdf).

From my conversation with @andresy 4 years ago, @andresy or @leonbottou or someone from that era briefly didn't multiply the stddev by `sqrt(3)` and noticed that this bug empirically works better in practice. And hence this bug has been kept.

**Comment by emitch** [comment]
@apaszke @soumith Thanks for your responses! Very interesting to hear about the history of the initialization and the empirical results. I'd be curious to know what benchmarks this initialization performed better on. Just a thought: it might be worth making the documentation a bit more clear about this caveat (if it is documented somewhere already, my apologies!), because I suspect people would in general assume that the initialization is something more standard. The improvement in performance might not generalize to some people's specific tasks, and the fact that the default initialization is non-standard might not be immediately obvious. Could cause some unnecessary consternation in certain cases.

**Comment by vishwakftw** [comment]
The initialization schemes have now been documented. I think this can be closed now.
