### ISSUE TITLE
PyTorch cuBLAS bindings are not thread-safe when used with multiple streams

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#6962]
PyTorch's cuBLAS bindings are not thread-safe when used with multiple streams on the same device. The underlying cuBLAS API **is** thread-safe, even with the same handle. However, each call in [`aten/src/THC/THCBlas.cu`](https://github.com/pytorch/pytorch/blob/333e8c9b227057635d365af96430cc6f4a1bab86/aten/src/THC/THCBlas.cu#L18-L19) first sets the stream on the cuBLAS handle before calling into cuBLAS. These changes to the handle are visible to other threads. The handle's stream may change in between the call to `cublasSetStream` and the subsequent cuBLAS call.

The [cuBLAS API](https://docs.nvidia.com/cuda/cublas/index.html#thread-safety2) recommends using one cuBLAS handle per thread. We may not want to do this because threads are relatively light-weight, but creating and destroying handles is expensive (destroying the handle causes synchronizations). DataParallel, for example, creates new threads for each forward pass.

Alternatively, we could use a mutex around the `cublasSetStream` and subsequent API call. The mutex should be per-cuBLAS handle (and the handles are per-device).

We can also delete the "reserve BLAS handles" functionality from THC, since it is not used in PyTorch. 
 
Version: PyTorch master (0.5)

**Comment by corsix** [comment]
Have there been any developments on this issue which haven't made their way to comments on the issue? It looks like `caffe2/core/context_gpu.h` has a promising `ThreadLocalCUDAObjects::GetHandle` method, which gives a cuBLAS handle pre-bound to a particular fixed stream (which means no subsequent `cublasSetStream` calls, and thus no race conditions), but it isn't used much?

For context, I'm trying to write a PyTorch C++ extension which uses cuBLAS and also respects the current stream. When users call into this extension from their `Function`'s `backward`, things get interesting, as autograd has multiple threads in play. Note that unlike #7601, I'm not concerned about calling a `Tensor`'s `backward` from within a `with torch.cuda.stream` block - I'm concerned about `with torch.cuda.stream` appearing within a `Function`'s `backward`, and any calls to my extension within that `with` block being able to (get a cuBLAS handle from somewhere in order to) invoke cuBLAS operations on that stream.

**Comment by gchanan** [comment]
@ezyang do we have a c10/internal mechanism we could use for this?

**Comment by ezyang** [comment]
(clearing myself since I know I won't be getting around to working on this for at least the next few weeks).

@corsix Caching cublas per stream may indeed be a good way to go about doing this. It seems to work around @colesbury's original concerns. Would you be interested in trying to make this happen? You can add me as reviewer if you do.

**Comment by ezyang** [comment]
Oh oops, I think I was assigned this as high priority issue fixing work assignment. Reassigning.

**Comment by ezyang** [comment]
Recording an in-person conversation with @colesbury: it's probably going to be hard to test if we've actually gotten this right or not.

**Comment by mcarilli** [comment]
Would the cudnn handle pool approach also work for cublas handles?  The handle pool returns handles on demand as threads request them.  If all existing handles in the pool are in use, it creates a new one.  As threads terminate, they release handles back into the pool.  In this way, the handle pool never creates more handles than the high-water mark of active threads, so it's efficient with DataParallel.

https://github.com/pytorch/pytorch/pull/15668
^ first merged version
https://github.com/pytorch/pytorch/pull/22405
^ hotfix because thread_local on Windows machines didn't mean what we thought it did/what the standard says it should mean

**Comment by mcarilli** [comment]
My original PR included [a test](https://github.com/pytorch/pytorch/pull/15668/files#diff-d89baec73022f5f511c5beb5ce6498dfR3839-R3887) that robustly showed (or at least provided strong evidence) that we got it right.  The test failed consistently prior to https://github.com/pytorch/pytorch/pull/15668 and passed consistently after https://github.com/pytorch/pytorch/pull/15668.  

On my local machine, out of curiosity I also rewrote that test to use gemms instead of convolutions.  The race condition seemed rarer, but the test did show that cublas use is not thread safe.  I can share the script if you want.

**Comment by mruberry** [comment]
@mcarilli I think an approach like that would work. Let's discuss offline.

**Comment by ezyang** [comment]
This sounds good to me!

**Comment by HapeMask** [comment]
Adding an additional set of datapoints in support of @mcarilli 's approach:

* We have a model on Windows which contains th.nn.Linear layers (which will call cuBLAS), and we are calling the model in two concurrent threads.
* If left to run long enough (anywhere from a few seconds to ~20mins), the runtime will eventually hang somewhere in a GPU call w/100% GPU usage.
* If we replace the Linear layers with layers which perform the same computation on the CPU, we observe no hangs.
* If we replace the Linear layers with equivalent 1x1 Conv2d layers on the GPU, we observe no hangs (presumably because the 1x1 conv uses cuDNN which has been fixed in #22405).
