### ISSUE TITLE
Flatbuffers dependency causing dirty git checkout

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70097]
For some reason, flatbuffer is not cleaning up after itself, and our assertion that at the end of each job the git checkout is clean is failing. This is the most significant issues currently affecting PyTorch CI flakiness. 

See [examples](http://torchci.us-east-1.elasticbeanstalk.com/failure?capture=Build+left+local+git+repository+checkout+dirty).

cc @ezyang @gchanan @zou3519 @bdhirsh @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
@gmagogsfm it looks like @qihqi is out. Can you find someone to take a look at this?

**Comment by malfet** [comment]
I though `flatbuffer` PR was reverted, wasn't it?

**Comment by gmagogsfm** [comment]
It was reverted (a few days ago actually), I checked `master` there is no reference to flatbuffer submodule. @suo, is this issue persistent now, or is it historical failure?

**Comment by ngimel** [comment]
The examples above show failures today and yesterday

**Comment by qihqi** [comment]
hi @suo Do you have a link with full log? Clicking any link on http://torchci.us-east-1.elasticbeanstalk.com/failure?capture=Build+left+local+git+repository+checkout+dirty gets back to a similar page...

**Comment by suo** [comment]
@qihqi sorry, my website was broken. You can click the links now

**Comment by suo** [comment]
Btw this is still ongoing and still the top cause of flaky job failures in CI. The fixed [failures page](http://hud2.pytorch.org/failure?capture=Build+left+local+git+repository+checkout+dirty) shows samples from an hour ago.

**Comment by qihqi** [comment]
Investigation so far:
1. Looked at: https://github.com/pytorch/pytorch/runs/4595505484?check_suite_focus=true; the logs has phrases `2021-12-21T14:58:14.6109736Z Entering 'third_party/flatbuffers'` meaning it has flatbuffers as a submodule. 

2. It's corresponding PR is https://github.com/pytorch/pytorch/pull/67475/commits
Looking at its corresponding repo state has no flatbuffers third_party/ nor in .gitmodules

3. Looking at logs see `2021-12-21T14:58:16.4262221Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/67475/merge
2021-12-21T14:58:16.5068645Z warning: unable to rmdir 'third_party/flatbuffers': Directory not empty
2021-12-21T14:58:16.7766848Z Previous HEAD position was 6fd69f10ce Merge `. Meaning, when CI tried to checkout the diff to run test; CI attempted to delete third_party/flatbuffers because third_party/flatbuffers is not part of the diff. However, that deletion failed. then subsequence submodules init just crawled it leaving it in dirty status.

Based on above my deduction is that the machine that ran this CI has third_party/flatbuffers directory somehow from before. That before could because the machine ran some CIs of when flatbuffer change was in, and didn't clean properly.

I don't know how to fix it per-se. However, since we are rolling flatbuffer change out again: https://github.com/pytorch/pytorch/pull/70201 (and it has no CI failures on dirty change). So current course of action should be continuing with flatbuffer rollout then this problem will be fixed automatically.

**Comment by janeyx99** [comment]
When do you anticipate the rollout to be complete? If the rollout is not for a while, some options we could explore are:
- forcefully removing the third_party dir (though I believe we've tried this for clean checkouts)
- somehow manually getting rid of the runners with the contaminated flatbuffers

**Comment by qihqi** [comment]
Hi @janeyx99  Probably by end of this week or next... There are few comments from @malfet to be addressed then the usual few tries of rebase / land.

The 2 options you listed sounds good as well, if they are easy to try then we should.

**Comment by malfet** [comment]
Our CI system shoudl be resilient against dirty checkouts, I think we should investigate and fix the problem

**Comment by malfet** [comment]
#m gogogo

**Comment by suo** [comment]
@malfet and I investigated (mostly @malfet), and we found the following:
- If you switch from a branch *with* submodules to a branch *without* the same submodule, the submodule directory persists as an [untracked directory](https://git-scm.com/book/en/v2/Git-Tools-Submodules#:~:text=Issues%20with%20Submodules). We assert that there are no untracked files produced by our build/test system, so we were tripping on that.
- Normally we use [ephemeral runners](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#using-ephemeral-runners-for-autoscaling) to provide clean workspace for each job, but we turned them off for GPU jobs because we have trouble launching new GPU instances sometimes when AWS runs out (@seemethere knows the details there).
- Even without ephemeral runners though, I was puzzled why we are starting out from a branch with the flatbuffers submodule since I thought we [cleaned](https://github.com/pytorch/pytorch/actions/runs/1613090243/workflow#L98) the workspace, but @malfet pointed out that our cleaning command `rm -rf {GITHUB_WORKSPACE}/*` will not glob hidden files (namely `.git`). You can tell we are not doing a clean checkout as we don't see the normal `Receiving object: (x/716280)` and the checkout completes in only a few seconds.

Okay mystery solved and https://github.com/pytorch/pytorch/pull/70337 should resolve the issue by force cleaning after checkout. Some followups:
- Ideally we could use ephemeral runners for everything, as it prevents this entire class of issues. But due to the aforementioned GPU capacity issues, we would probably need to put in substantial infra work (make it so that we can use ephemeral runners on top of pre-reserved instances, or scale out our infra across multiple AWS AZs/regions).
- We *could* modify the cleaning script to nuke the entire workspace (including hidden folders), but it would slow down checkout. So we're leaving it in for now, but if there's one more weird issue like this I think we should nuke it.
