### ISSUE TITLE
Allow saved tensor hooks to be composed and nested

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#70134]
### 🚀 The feature, motivation and pitch

[Saved tensor hooks](https://pytorch.org/docs/master/autograd.html?highlight=saved_tensors_hooks#torch.autograd.graph.saved_tensors_hooks) are very useful in terms of providing flexibility in terms of controlling what we can do with a tensor when it is saved for backwards. For example, these hooks can be used to implement checkpointing and offload of intermediate tensors to CPU.

It would be useful to be able to nest these hooks, for example to implement both activation offloading to CPU and saved tensor hooks-based checkpointing. For example, we could have a model structure such as

```
model = nn.Sequential(checkpoint(layer1), ... checkpoint(layer_n))
```

and want to offload outer activations to CPU, such as
```
with save_on_cpu():
    outputs = model(inputs)
```

This would require saved tensor hooks to be nested. A concrete way of implementing something like this would be to stash the outer hooks, override the hooks with the inner ones during the course of their execution, and then pop/unstash when the inner hooks are finished executing. 

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by rohan-varma** [comment]
@albanD @jbschlosser Is this something that the autograd team will be able to prioritize soon?

**Comment by Varal7** [comment]
I have trouble formalizing what the expected behavior would be here.

The contract for hooks is that they should be a pair of functions (`pack`, `unpack`) with `pack: torch.Tensor -> Any` and `unpack: Any -> torch.Tensor` and `pack(unpack(x)) = x`.

- In the case where where output of `pack_1` and `pack_2` are tensors, I can visualize how composing them would work. 
```
 with saved_tensors_hooks(pack_2, unpack_2):
     with saved_tensors_hooks(pack_1, unpack_1):
          y = f(x)
```
If the forward pass needs to a tensor `a`, the above code would save `saved = pack_2(pack_1(a))`.
Then during backward, the tensor would be retrieved with `unpack_1(unpack_2(saved))`.
(I guess even in the above example it's a bit unclear which order the operations should be done in).

- However, in the case where the output of the inner `pack` function is not a tensor, do we then need to change what is acceptable as an outer hook? Concretely, in your example, the `checkpoint` inner hook outputs an `int`. Clearly, moving the `int` to CPU is not what you'd want. Alternatively, the saved tensor can be unpacked (by the inner unpack) before being packed by the outer pack. But that would void using the inner hook altogether.

What am I missing here?

**Comment by rohan-varma** [comment]
@Varal7 Thanks for your comment and for implementing this feature, it has been very useful for distributed!

I should've been clearer in my original description, but my proposal was to not run both hooks, i.e. we wouldn't do something like pack2(pack1(a)). 

What I would like is for the inner hook to have "priority", i.e. in your example, for `y = f(x)`, we would use `pack_1` when autograd is saving the tensor for backward, and `unpack_1` when autograd is retrieving the saved tensor during backward. So within the innermost context manager, the outer hooks would not be run at all.

Regarding my example, since `checkpoint` is the inner hook, we should not run the outer hook `save_on_cpu` at all within the `checkpoint` context manager (and similarly for backward).

I don't have insight into how this is implemented in autograd, but a simple concept I had was that we could have a global stack of hooks, which we push onto whenever we enter a saved tensor hook and pop whenever we leave one. Then, when deciding which hooks to run, we simply take the top of the stack. Although, I'm unsure how we'd make this work for backwards since we can't just pop off the hook in the forward pass. During the forward pass, is it possible to somehow tell autograd which hook to use in backward?

Thanks for your help!
