### ISSUE TITLE
DISABLED test_cuda_memory_leak_detection (__main__.TestCuda)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70226]
Platforms: windows

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by suo** [comment]
@mruberry related to your new stuff?

**Comment by suo** [comment]
example failures: http://hud2.pytorch.org/failure?capture=test_cuda_memory_leak_detection%2C%20TestCuda

**Comment by mruberry** [comment]
> @mruberry related to your new stuff?

And because some Windows tests weren't running. I think @janeyx99 has a fix for this just by increasing the size of the tensor the test allocates.

**Comment by janeyx99** [comment]
The fix should have been merged in https://github.com/pytorch/pytorch/pull/70010 on 12/20, but it looks like the most recent failure is from 10 days ago on master, so maybe the fix didn't work?

**Comment by mruberry** [comment]
@janeyx99 #70010 modified `test_mem_get_info` correctly but I think these lines:

https://github.com/pytorch/pytorch/blob/d35fc409ad84c1a837e7e07ffe3f4e4942538e50/test/test_cuda.py#L1665

https://github.com/pytorch/pytorch/blob/d35fc409ad84c1a837e7e07ffe3f4e4942538e50/test/test_cuda.py#L1675

need a similar fix because they're also trying to trigger leaks.

**Comment by janeyx99** [comment]
https://github.com/pytorch/pytorch/pull/70603 should fix! Waiting for CI results
