### ISSUE TITLE
`torch.index_select` will return a random value if input tensor is empty

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#70675]
### 🐛 Describe the bug

`torch.index_select` will return a random value if input tensor is empty

```python
import torch
a = torch.rand([0, 4])
dim = 0
indices = torch.tensor([0, 1])
torch.index_select(a, dim, indices)
# tensor([[1.1704e-19, 1.3563e-19, 7.7098e-33, 1.3594e-19],
#       [1.3563e-19, 2.6451e+20, 1.2708e+31, 6.1186e-04]])
```

### Versions

pytorch: 1.10.1

**Comment by albanD** [comment]
Out of curiosity what would you expect the output contains here? Given that there are no inputs.

But both 0 and 1 are out of range for a dimension of size 0 so this should raise an error right?

**Comment by TestSomething22** [comment]
@albanD Yes, I think it should raise an error since the index is out of bound

**Comment by albanD** [comment]
Ok! We would accept a PR fixing the boundary check.

Out of curiosity, does the same thing happens on GPU?

**Comment by TestSomething22** [comment]
On GPU, it will raise an error that "RuntimeError: CUDA error: device-side assert triggered". I think this error message is not clear enough.

**Comment by Jup11ter** [comment]
I have observed a similar buggy behavior on `torch.Tensor.index_select` in PyTorch 1.10.0 and 1.11.0 versions. The following codes will return random value outputs.
However, in 1.12.0 version, these codes will raise:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    result = test()
  File "test.py", line 11, in test
    tmp_result=torch.Tensor.index_select(a, dim, indices)
RuntimeError: index_select(): self indexing axis dim should be positive
```

Considering that the implementation of `torch.index_select` and `torch.Tensor.index_select` should be the same (in [docs](https://pytorch.org/docs/stable/generated/torch.Tensor.index_select.html)), the random output problem of `torch.Tensor.index_select` in earlier versions should also be fixed by this [pr](https://github.com/pytorch/pytorch/pull/77881).

```

import torch

torch.manual_seed(0)
a = torch.rand([0, 4])
dim = 0
indices = torch.tensor([0, 1])

def test():
    # tmp_result=torch.index_select(a, dim, indices)
    tmp_result=torch.Tensor.index_select(a, dim, indices)
    return tmp_result
result = test()
print(result)
```
