### ISSUE TITLE
Automatically Detect and Remove Flaky Tests

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#71005]
### 🚀 The feature, motivation and pitch

Current progress for flaky test detection can be read about in the following slideshow
[CI Reliability_ Flaky Tests.pdf](https://github.com/pytorch/pytorch/files/7830511/CI.Reliability_.Flaky.Tests.pdf)

Next steps:
- [x] Automatically file issues for detected disabled tests pytorch/test-infra#186
- [x] Shield developers from flaky tests in CI (have they show up as green instead of red)
- [ ] Display flaky tests differently on the HUD 
- [ ] Add functionality to flaky test bot to automatically close disabled issues
    - [ ] See if the test is still in the code base. If not, close issue with comment.
    - [ ] See if the test is still flaky. Run it X times and see if they all pass.
  

Please comment suggestions and questions! 
 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
Some feedback on the flaky test view, recorded from offline discussion:
- At a high level, we should thing about the user story of: I got a flaky test issue and clicked this link, how can I understand what is flaky, why, and how to fix it?
- Can we add an orderby to the query? Right now it reorders each time there is data pull from the backend.
- Clickable anchor links should be added for various columns.
- Workflow URLs should link to the failing job instead of the entire workflow. The workflow name should be workflow name + job name. This is especially important when we go green for flaky tests, since users will have no way to know which of the jobs is the one containing the flaky test.
- #green and #red columns are inscrutable to people who aren't familiar with the implementation of flaky test handling, we should figure out some way to communicate that information in a more understandable way.
- People probably don't know what `%` means, since it's an implementation detail of our data backend. Let's make `%` displayed as something more user-understandable, like "<any>" or something.
- Not sure the factoring of the view makes sense. Right now each row is a name-suite-file triplet. For the common case (coming from a flaky test issue), I'll just get a single-row table with all the information squished together, which will get harder to handle as soon as we want to add richer information like flaky test logs.

**Comment by janeyx99** [comment]
This task has been mostly completed. The only missing things are stress-testing and closing issues to re-enable the tests, which are not crucial to be automated at the moment. We have
1. a flaky test bot that goes through and disables tests that have been flaky in the last 3 hours. https://github.com/pytorch/test-infra/blob/main/torchci/pages/api/flaky-tests/disable.ts
2. a rudimentary flaky test view, e.g. https://hud.pytorch.org/flakytest?name=test_comprehensive_column_stack_cpu_float16&suite=TestDecompCPU

**Comment by janeyx99** [comment]
Followup actions are already tracked with
https://github.com/pytorch/test-infra/issues/621
https://github.com/pytorch/test-infra/issues/552
https://github.com/pytorch/test-infra/issues/379
