### ISSUE TITLE
`Tensor.baddbmm_` unexpectedly succeeds!

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#71085]
### 🐛 Describe the bug

With the same invalid input, `Tensor.baddbmm` raise an error but `Tensor.baddbmm_` (the in-place version) will succeed. However, they are expected to have the same output.

```python
import torch
results = dict()
input = torch.rand([10, 3, 5, 0], dtype=torch.float32)
batch1 = torch.rand([10, 3, 4], dtype=torch.float32)
batch2 = torch.rand([10, 4, 5], dtype=torch.float32)
input.clone().baddbmm(batch1, batch2)
# RuntimeError: expand(torch.FloatTensor{[10, 3, 5, 0]}, size=[10, 3, 5]): the number of sizes provided (3) must be greater or equal to the number of dimensions in the tensor (4)
input.clone().baddbmm_(batch1, batch2)
# succeed
```

### Versions

pytorch: 1.10.1

cc @ezyang @gchanan @zou3519 @bdhirsh @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by mruberry** [comment]
Interesting! Thanks for reporting this bug, @TestSomething22. We would accept a fix for this.

**Comment by IvanYashchuk** [comment]
I can reproduce the problem in Colab with PyTorch version `1.10.0+cu111`. But on the latest master branch compiled from source and nightly wheel, the error is the same for both calls. 

It was likely fixed in https://github.com/pytorch/pytorch/pull/64805 and the fix will be included in the next PyTorch release.
