### ISSUE TITLE
torch.distributed.launch outputs all processes to stdout (single node)

### ISSUE THREAD

**Issue by SeanNaren** [pytorch/pytorch#7134]
Using the new `torch.distributed.launch` function on a single node, we get multiple processes outputting to the same stdout, which leads to a messy screen!

Previous solution from `multiproc.py` via the NVIDIA guys used stdout for the main process, and then outputted to log files for the remainder of the processes. Unsure what would be the cleanest way to handle this, but willing to help!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by apaszke** [comment]
cc: @teng-li

**Comment by fmassa** [comment]
I agree. I currently have my logger conditional on the rank of the process, so that only the main process logs something whilenthe others don't do anything.

Another thing that is worth keeping in mind is that if you want to log losses, you'd actually want to store the losses from each process, or reduce the value of the losses to in main process before printing (but this would incur extra overheads)

**Comment by percyfan** [comment]
Is this problem now solved?

**Comment by rohan-varma** [comment]
from taking a quick look, it looks like this should be as simple as adding a `stdout=file` for each subprocess that we launch. On the same node we should take care to ensure that the same file handle is not passed in, and we can take this in as an argument.
