### ISSUE TITLE
Trying to run build_libtorch.py getting, "No module named 'typing_extensions'

### ISSUE THREAD

**Issue by MotorCityCobra** [pytorch/pytorch#71360]
### 🐛 Describe the bug

File "/home/jet/pytorch/tools/codegen/gen.py", line 3, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
CMake Error at cmake/Codegen.cmake:243 (message):
  Failed to get generated_headers list
Call Stack (most recent call first):
  caffe2/CMakeLists.txt:2 (include)

### Versions

Python 3.8.12  
aarch64
Jetpack 4.6
Nvidia Jetson AGX Xavier

**Comment by MaheshPunjabi** [comment]
Hi,
This is my first time contributing to OSS. Please correct me if I missed something. 
This appears to be a setup issue. At a top level, this error suggests a dependency is missing from your python environment.

I see a couple of possibilities:
1. Install the dependencies(conda install)
OR
2. Find suitable pre-built PyTorch pip wheel installers for your setup

Background:
I found build_libtorch.sh [here](https://gist.github.com/lasagnaphil/3e0099816837318e8e8bcab7edcfd5d9). 
the script content says:
```
# Script for installing libtorch from scratch (without any python dependencies)
# Note that you need to have all the dependencies needed before running this script! (Read README.md in the main pytorch repo)
```

Which leads us to the docs, specifically the [Install dependencies topic](https://github.com/pytorch/pytorch/blob/master/README.md#install-dependencies):
```
conda install astunparse numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions ...
```

Also, there is a note just above this command, which may apply to you:
`If you are building for NVIDIA's Jetson platforms (Jetson Nano, TX1, TX2, AGX Xavier), Instructions to install PyTorch for Jetson Nano are available here(https://devtalk.nvidia.com/default/topic/1049071/jetson-nano/pytorch-for-jetson-nano/) `

Notes to self:
typing_extensions module was [included ](https://github.com/pytorch/pytorch/pull/51500) since Feb 2021.

**Comment by MotorCityCobra** [comment]
I was able to build libtorch on the AGX Xavier with python version 3.8.  
Python versions 3.6 and 3.9 did not work.  

`sudo python3.8 tools/build_libtorch.py`
