### ISSUE TITLE
Possible improvements for `torch.linalg.cholesky` and `torch.linalg.cholesky_ex` to handle positive-semidefinite matrix inputs

### ISSUE THREAD

**Issue by nonconvexopt** [pytorch/pytorch#71382]
### 🚀 The feature, motivation and pitch

Currently, user might feel inconvenience when using `torch.linalg.cholesky` because it supports only positive definite matrix inputs according to the docs of `torch.cholesky` and `torch.linalg.cholesky`.
Also, it might be better to modify `torch.linalg.cholesky_ex` to check positive-semidefiniteness, too, or add similar function checking positive-semidefiniteness.
Since pytorch does not support LDL decomposition which is implemented in Scipy, not in Numpy, Cholesky decomposition of positive-semidefinite matrix is impossible now.

### Alternatives

Implement LDL^T decompositions which can calculate cholesky decomposition for positive-semidefinite or Singular matrices.

### Additional context

Link to [`scipy.linalg.ldl`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.ldl.html)

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by nonconvexopt** [comment]
Posted while implementing #71375

**Comment by nikitaved** [comment]
LDL decomposition is coming by @IvanYashchuk . I will work on forward/backward AD once it is merged.

**Comment by nonconvexopt** [comment]
> LDL decomposition is coming implemented by @IvanYashchuk . I will work on forward/backward AD once it is merged.

That's great. Thank you for letting me know.

**Comment by nonconvexopt** [comment]
This links explains way to calculate cholesky decomposition by SVD (or eigen decomposition) [https://en.m.wikipedia.org/wiki/Cholesky_decomposition](https://en.m.wikipedia.org/wiki/Cholesky_decomposition)
In PyTorch, `torch.linalg.eig` is applicable to positive-semidefinite matrix.
After calculating PDP^T by `torch.linalg.eig` and calculate the QR factorization of PD^1/2 will attain cholesky for positive-semidefinite matrix.

**Comment by nikitaved** [comment]
This will compute the result, but you will not be able to backprop through if the input matrix is not full-rand because of limitations of the svd's backward. Have a look at the documentation of `torch.linag.svd` for more information about that. There is a effort to bring a rank-revealing SVD that will be stable for singular inputs as long as they have distinct non-zero singular values.

**Comment by Lezcano** [comment]
Note that Cholesky / LDL both expect the input to be full-rank if you want to backprop through them (this is very much expected.

Now, if you want to get Cholesky / LDL right now, before that PR mentioned above is merged, simply use `linalg.lu_factor`. If you want to unpack it, feed its output to `torch.lu_unpack`, otherwise use it with `torch.lu_solve`. We'll soon also have `linalg.lu` (https://github.com/pytorch/pytorch/pull/67833)

**Comment by nonconvexopt** [comment]
Thank you for the explanations. I didn't know that backprops is not possible for Singular inputs. It seems singular matrices are making many issues in linalg computations. Hope to contribute to solve some of the issues, soon.
