### ISSUE TITLE
[discussion] `torch.nn.init` functions should not support `__torch_function__` directly

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#72186]
Currently, the following functions in `torch.nn.init` are routed through `__torch_function__` for custom tensors:
* `uniform_`
* `normal_`
* `kaiming_uniform_`

Arguably, these should not be directly overrideable using `__torch_function__`, and calls to the Python API for the underlying ATen ops should show up instead.

For the example of `kaiming_uniform_`, this would allow custom tensors to reuse the bounds calculation and simply override `tensor.uniform_` instead. Right now, failing to provide a `kaiming_uniform_` impl in `__torch_function__` for a given custom tensor will error out when the function is called, even if `uniform_` is provided, due to a lack of `__torch_function__` re-dispatch.

Is there any use case that requires these init functions to be handled directly for a custom tensor?

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @hameerabbasi @rgommers @peterbell10 @pritamdamania87 for `ShardedTensor`

**Comment by zou3519** [comment]
I'm not sure we want to remove `__torch_function__` for all composite PyTorch Python operations. `__torch_function__` was initially marketed as "being able to override everything in the PyTorch Python API". For example, does this mean we should also remove `__torch_function__` for multi_head_attention? https://github.com/pytorch/pytorch/blob/2d5296b0e7769b9bd7cda9607c1d14820e9103e4/torch/nn/functional.py#L5049

If someone wants to "have an easier time writing their Tensor subclass" by decomposing operations into their constituents, then we should have a different mechanism (a la primtorch) to get there.

**Comment by albanD** [comment]
The problem here is that adding it at the high level completely shadows any potential calls below. So I think we should be careful about which level we add it. Because we don't want to get into a situation where all the ops are so high level that it becomes impossible to implement anything with torch_function unless you re-implement all of pytorch.

**Comment by jbschlosser** [comment]
@zou3519 Good point & I agree we don't want to remove `__torch_function__` for all composite PyTorch python ops. Without a consistent policy like that, the alternative is to ad-hoc identify which composite operations are worth supporting or not, and that seems subjective / error-prone.

**Comment by rgommers** [comment]
> The problem here is that adding it at the high level completely shadows any potential calls below. 

This is not a problem imho, it's the sensible thing to do. If you start to not dispatch but _are_ relying on `__torch_function__` dispatches inside some API, then you've just made the full implementation of that API public - any refactor may break end user code, and there are no tests to prevent that.

Ideally there should be no code inside any public API that does another `__torch_function__` dispatch below the user's function/method call.

> So I think we should be careful about which level we add it. Because we don't want to get into a situation where all the ops are so high level that it becomes impossible to implement anything with torch_function unless you re-implement all of pytorch.

This can be avoided in many cases. The docs (https://pytorch.org/docs/stable/notes/extending.html#extending-torch-with-a-tensor-like-type) recommend a `HANDLED_FUNCTIONS` pattern, so an implementation is free to return `NotImplemented` and if the custom tensor class is subclassing `torch.Tensor` then things are likely to work the same way as if there was no dispatch at all. Still not desired probably, for the same "now implementation details are public" reason as given above - but at least in that case the user explicitly opted into such potential breakage.

A better option that is likely to be sufficient in many cases is for the user to implement a generic "unpack underlying `Tensor`, pass that back to the function doing the dispatching, then re-pack the result into mycustomtensor" pattern.

**Comment by jbschlosser** [comment]
Okay I'm convinced we should keep `__torch_function__` as a feature that allows for overriding the entire public Python API. Along this line, the other `torch.nn.init` functions that currently don't have it should also get `__torch_function__` support.

It's nice to hear there is at least some way users can currently opt into overriding at lower levels (taking on some possible implementation detail related breakage).

**Comment by hameerabbasi** [comment]
> The problem here is that adding it at the high level completely shadows any potential calls below. So I think we should be careful about which level we add it. Because we don't want to get into a situation where all the ops are so high level that it becomes impossible to implement anything with torch_function unless you re-implement all of pytorch.

I think this summarizes it well, but one doesn't necessarily have to make that choice. It's a problem I foresaw and had a solution to in `uarray`. The problem statement goes as follows: We want to be able to dispatch an entire function (for example `multi_head_attention_forward`) for performance or other reasons to make it available to `__torch_function__` users), while at the same time being able to _peel off_ a layer as if `__torch_function__` wasn't there so that the internal implementation is available to `__torch_function__` users _without_ a re-implementation. Otherwise one runs into the same problem: Either one can't always dispatch what one needs due to the API being huge, or one is restricted to always using a set of core functions.

There is a middle solution that allows one to maintain a list of smaller core functions while, at the same time, being able to dispatch everything for control/performance/etc.

The solution I used in `uarray` was one of a _default implementation_. It goes something like this (adapted to `__torch_function__`):

```python
def _my_torch_func_dispatcher(a, b):
    ...

def _my_torch_func(a, b):
    ...

# Define a default implementation, which could be the function itself
# or a simpler version that doesn't contain edge cases specific to `Tensor`
_my_torch_func_default = _my_torch_func

my_torch_func = @torch_function_dispatch(_my_torch_func_dispatcher, default=_my_torch_func_default)
```

The dispatch flow happens as follows:

- The normal dipatch is tried first
- The default is used as a _fallback_.

One could define a testing strategy (for core functions needed to implement something) by _always_ taking the `default=` path unless it is unavailable.

**Comment by albanD** [comment]
Thanks @hameerabbasi for the insight! I know that you spent a lot of time on the design of this.

I was wondering what is your take on "re-dispatch" or "skip-dispatch" in general.

In both of these cases, the idea would be that there are multiple levels where a function can be intercepted.
Fro mha for example. You can override `torch.nn.init.xavier_uniform`, but since this function is written in python, it always end up calling more of pytorch's API. In particular `torch.uniform_`.
We could consider a mechanism where, within the `xavier_uniform` torch_function, we could "re-dispatch" to just use the core implementation. And thus will end up in the `uniform_` torch function.
Is that something you considered? You think would be too confusing?

**Comment by hameerabbasi** [comment]
> And thus will end up in the `uniform_` torch function.
> Is that something you considered? You think would be too confusing?

From a debugging-alternate-PyTorch point of view, it would look like the dispatcher tried `torch.nn.init.xavier_uniform`, then `uniform_` and so forth. That's 3 calls, maybe more, to `__torch_function__` instead of one. I don't feel that that's significantly more complex than what we already have, and I feel that's the best we could do. It would be a small performance hit, but that's the price of generality. If one wants performance, one could always dispatch at the top-level.

I've had this approach in `uarray` for a while and it's quite... approachable (pun not intended).
