### ISSUE TITLE
ONNX tests are broken

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#72337]
## Current Status
*ongoing*

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 2/4 6:05a incident began
- 2/4 7:30a detected by noticing failure on unrelated PR and then looking at [HUD](https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=onnx%20/%20test)

</details>

## User impact
You will see test1 is broken

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by BowenBao** [comment]
This failure in CI appears suddenly without any code changes to related files. It is likely due to different test case run order. The test code was badly written such that test class `TestModels_new_jit_API`, if called first, will assign `TestModels.onnx_shape_inference = True`, circumventing this problem. On the other hand, if `TestModels` is called first, `AttributeError` will be raised. Should be fixed by #72350.
