### ISSUE TITLE
conv_transpose3d : weird formatting in doc

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#72502]
### 📚 The doc issue

![image](https://user-images.githubusercontent.com/19503980/152934601-35087eaa-429e-4629-bad2-d7efc6401d43.png)

https://pytorch.org/docs/master/generated/torch.nn.ConvTranspose3d.html#torch.nn.ConvTranspose3d

cc: @jbschlosser

cc @brianjo @mruberry @albanD @jbschlosser @walterddr @kshitij12345

**Comment by jbschlosser** [comment]
@kshitij12345 Great catch on these! I guess this is because of the indentation when output shape is split across two lines? e.g.
https://github.com/pytorch/pytorch/blob/7176c92687d3cc847cc046bf002269c6949a21c2/torch/nn/modules/conv.py#L996-L997

Do you mind testing this out and knocking out a fix for these?
