### ISSUE TITLE
support for modern python

### ISSUE THREAD

**Issue by LifeIsStrange** [pytorch/pytorch#72779]
### 🐛 Describe the bug

I lost a day not understanding why poetry couldn't install torch 1.10.2. It happens to be that pytorch CI only test python 3.7 which is **four years old** and my python 3.10 was incompatible, of course the error gave absolutely zero indication that this was the issue.
Anyway, pytorch is dragging down the python ecosystem by not supporting and testing contemporaneous python versions.

### Versions

1.10.2

**Comment by lkct** [comment]
Pytorch has already supported python 3.9 for a year or so.
As of python 3.10, nightly builds are already available for it since last month and the next release 1.11.0 will also support it. See #66424
I think the pytorch's support for "modern" python is fair enough, since python 3.10.0 just came out when pytorch 1.10.0 was released, which is only about 4 month ago.

**Comment by LifeIsStrange** [comment]
Fair but I guess the readme should make it clearer that Python 3.9 is officially supported. My reference point was that the Continuous Integration has an empty 3.8 entry and no 3.9 entry.

**Comment by lkct** [comment]
A kind notice: on the left of the PyPI page https://pypi.org/project/torch/, you can find under "Programming Language" the python versions that pytorch currently supports.
