### ISSUE TITLE
cpp API Adam optimizer test is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#7288]
```
16:00:21 /private/var/lib/jenkins/workspace/pytorch-builds/pytorch-macos-10.13-py3-build-test/test/cpp/api/optim.cpp:93: FAILED:
16:00:21   REQUIRE( test_optimizer_xor(optim, model) )
16:00:21 with expansion:
16:00:21   false
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-macos-10.13-py3-build-test/6074//console

CC @ebetica @goldsborough

**Comment by mruberry** [comment]
I was about to file the same issue.

Some random draws will cause these optim tests to fail, and because they use std::rand() whether they pass or fail is dependent not only on the seed given and how many prior calls to std::rand() are made. Further, std::rand() does not appear to be the only source of pseudorandomness in these tests, as setting different random seeds at the start of them will still result in intermittent failures/success. (Perhaps the network initializations are pseudorandom, too?)

While controlling the pseudorandomness is one option, the fact that these tests are so fragile calls them into question. Maybe there are better tests for these optimizers?
