### ISSUE TITLE
Extension with stable build: fatal error: thrust/complex.h: No such file or directory

### ISSUE THREAD

**Issue by eddy-ilg** [pytorch/pytorch#72918]
Hi, 

I am seeing some issues with include files regarding thrust and assume there might be a fundamental issue. 

I installed the stable build (need newest version for my GPU type) using the command: 
pip install --upgrade torch==1.10.2+cu111 -f https://download.pytorch.org/whl/torch_stable.html 

Note that the CUDA version on my system is 11.6. The version of torch works fine and can use the GPU without any problems. 

However, when I try to compile an extension (see definition below), I get the following error: 
In file included from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/c10/util/Half.h:14,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/c10/core/ScalarType.h:5,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/c10/core/Scalar.h:11,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/ATen/Operators.h:13,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:3,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/ATen/Context.h:4,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/eddyilg/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from projection_kernels.h:4,
                 from projection_kernels.cu:2:
/home/eddyilg/.local/lib/python3.9/site-packages/torch/include/c10/util/complex.h:8:10: fatal error: thrust/complex.h: No such file or directory

As fas as I know, with CUDA 11 thrust was removed. What I am wondering about: 

1.) Pytorch seems to include parts of CUDA 10 in the folder "torch/include/c10", however they don't include thrust. I am wondering how this can work?  

2.) The pytorch version is compiled against CUDA 11 but still has a version 10 folder "torch/include/c10" that references thrust externally (which is not present in CUDA 11). Also here I don't understand how this can work. 

Note that in my /usr/include/cuda folder there is a "thrust" folder with the following contents: 
async
cmake
detail
iterator
mr
random
system
type_traits

However, it is missing complex.h. 

Could someone help me out what could be wrong and why the torch CUDA references thrust but doesn't include it? Thanks in advance 

-------------------
setup.py

# to install:
# CXX=g++ python setup.py install
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(
    name='projection_cuda_ext',
    ext_modules=[
        CUDAExtension(
            name='projection_cuda_ext',
            sources = [ 'projection_cuda.cpp', 'projection_kernels.cu' ],
            include_dirs=['/usr/include/eigen3'],
        ),
    ],
    cmdclass={
        'build_ext': BuildExtension
    })

cc @malfet @seemethere @zou3519

**Comment by ngimel** [comment]
C10 is not related to cuda10 at all, and c10 folder does not include any parts of cuda. Also, thrust is still part of cuda11 developer toolkit, and can be found in `cuda/include/thrust` wherever your toolkit is installed. I'm not sure if `complex.h` header has moved, cc @zasdfgbnm

**Comment by zasdfgbnm** [comment]
It looks like your CUDA installation is corrupted? The `complex.h` should still be there if your CUDA installation is correct. Could you try this simple program with nvcc to see if it work?

```CUDA
#include <thrust/complex.h>
```

**Comment by eddy-ilg** [comment]
Thanks @zasdfgbnm @ngimel! 

It turned out this is a Fedora issue - the Fedora 34 CUDA toolkit packages to not contain all files (especially the are missing thrust). 

Removing the Fedora packages and installing the CUDA toolkit from the nvidia homepage solved the problem.

**Comment by zasdfgbnm** [comment]
I am closing this issue. Feel free to open a new issue if you have further questions.

**Comment by EzioZz** [comment]
Hi I'am using AMD GPU and ROCm toolkit toadd OP with pytorch Extionsion.
same error occurred, it's reasonable because I don't hava cuda installed.
Any advice how to fix it?
`In file included from kernels/linear.hip:1:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/ATen.h:7:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/Context.h:3:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/CPUGeneratorImpl.h:3:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/ATen/core/Generator.h:22:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/c10/core/GeneratorImpl.h:8:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/c10/core/TensorImpl.h:8:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/c10/core/Storage.h:3:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/c10/core/StorageImpl.h:4:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/c10/core/ScalarType.h:5:
In file included from /usr/local/lib/python3.8/dist-packages/torch/include/c10/util/Half.h:15:
/usr/local/lib/python3.8/dist-packages/torch/include/c10/util/complex.h:8:10: fatal error: 'thrust/complex.h' file not found
#include <thrust/complex.h>
         ^~~~~~~~~~~~~~~~~~
29 warnings and 1 error generated when compiling for gfx1030.
error: command '/opt/rocm-5.4.3/bin/hipcc' failed with exit code 1`
