### ISSUE TITLE
I get an error when exporting to onnx but cannot find what it means

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#73129]
### 📚 The doc issue

I export with opset 14 and get this error

```log
allowzero=0 by default. In order to honor zero value in shape use allowzero=1
```

I am not sure what does "zero value in shape" mean and how to fix this or pass "allowzero"

**Comment by dashesy** [comment]
It is a "torch.onnx.export" of a large model, and of course "shape" is used numerous times. The error does not tell which line causes it.
I try to repro with a small model.

**Comment by BowenBao** [comment]
To clarify, the above message is a warning
`warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")` instead of error. So the model export should proceed. Did you observe any other errors?

**Comment by dashesy** [comment]
Correct, that is a warning. The model exports but I need to know why I get the warning to make sure everything is correct.
There are 2 questions:

1. What does "honor zero value in shape" mean? what are examples when that happens
2. How to pass allowzero when exporting the model?

**Comment by BowenBao** [comment]
@dashesy After internal discussion, it turns out this is implementation detail, and was supposed to be set as comment. 

Before opest 14, value `0` in `shape` input of `Reshape` bear different meaning between PyTorch and ONNX. 
For PyTorch, `0` means literal `0`. For ONNX, `0` means `keep same input dimension size`. After opset 14, ONNX supports both behavior, and is controlled by flag `allowzero`.

This line was supposed to explain the default behavior to devs using this helper function.
