### ISSUE TITLE
Pollution of GPU-0 memory

### ISSUE THREAD

**Issue by m-ph** [pytorch/pytorch#7320]
## Issue description
Copying a tensor to a GPU other than 0 uses up memory on GPU 0 too.

## Code example
```
import torch
a = torch.zeros(1).cuda(1)
```

nvidia-smi now shows:
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     93271    C   python                                         306MiB |
|    1     93271    C   python                                         306MiB |
+-----------------------------------------------------------------------------+

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 367.48
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.3)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by SsnL** [comment]
I remember that we always create context on first observable GPU. Not sure if it is the correct behavior.

**Comment by apaszke** [comment]
We really shouldn't, but that might be the case because we call some driver functions to do initialization, before we switch to the desired GPU. A fix might be complicated 😕

**Comment by ar-nowaczynski** [comment]
This:
```
import torch
a = torch.zeros(1).cuda(1)
```
works nicely in 0.3.1 (memory is taken only from the GPU 1)

**Comment by colesbury** [comment]
The problem is the `THCRandom_getGenerator` call :

https://github.com/pytorch/pytorch/blob/71626491c40c86eb1ee410e695c467486084144c/aten/src/ATen/CUDAGenerator.cpp#L17-L23

via the call chain:

```
#1  0x00007fff622869eb in at::CUDAGenerator::CUDAGenerator(at::Context*) () from /data/users/sgross/pytorch/torch/lib/libATen.so
#2  0x00007fff62286d98 in at::Context::doInitCUDA() () from /data/users/sgross/pytorch/torch/lib/libATen.so
```

That call looks incorrect: the `THCGenerator*` is per-device but we have one global default  `CUDAGenerator`. It's also not really used, since the actual THC bindings look like:

```
    auto generator_ = check_generator<CUDAGenerator>(generator, &context->defaultGenerator(backend()));
    (void) generator_; //silence unused warning
```

**Comment by lironmo** [comment]
@colesbury , sorry that i post on closed issue.
i  have problem with the footprint of using pytorch cuda at each process.
you can see https://github.com/pytorch/pytorch/issues/20532,
i believe that there is wrong usage in the cpp that use cuda api - i am not familiar with the torch implementation but it's s
[test_gpu.py.txt](https://github.com/pytorch/pytorch/files/3197441/test_gpu.py.txt)
eem it's consume huge amount of memory for each process that use cuda.

can you refer me to the cpp cuda api for pytorch?

i created a simple test to illustrate the problem.

i test it on small gpu for debugging, it's crash after 4 initialization's ~1.5 GB on gpu.

output:
Start process number2
Start process number3
Start process number1
Start process number0
After init process number2 go to sleep
After init process number3 go to sleep
After init process number1 go to sleep
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liron/work/pixoneye/algorithms_framework/edgify/test_gpu.py", line 24, in init_cuda
    create_cuda_tensor()
  File "/home/liron/work/pixoneye/algorithms_framework/edgify/test_gpu.py", line 15, in create_cuda_tensor
    b = torch.cuda.FloatTensor(1)
RuntimeError: CUDA error: out of memory

**Comment by ezyang** [comment]
@lironmo can you please open a new issue for your problem.

**Comment by lironmo** [comment]
@ezineo i already opened but the issue was closed- https://github.com/pytorch/pytorch/issues/20532
and the most wired is that torch.cuda.memory_allocated return ~43MB where the real consuming is around 700MB - and crash when i try to allocate some amount of MB that larger then what the nvidai-smi show

**Comment by colesbury** [comment]
@lironmo the issue was closed because there is no action that PyTorch can take to change the behavior. If you need support, use the discussion forums. If you want NVIDIA to change CUDA's behavior, try the NVIDIA developer forums.

The GitHub issue tracker is not the appropriate place, especially not old, closed issues.

**Comment by lironmo** [comment]
@colesbury 
Thanks for your replay , I will try nvidia as well but from quick review of nvidia it's not reasonable that nvidia will do cudamalloc just to init kernels.
I created simple c coda that use gpu with no overhead(simple multiplay function and use cuda malloc and free )

I need to read pytorch c implementation to understand why you refer to nvidia, this is the reason i replay in this closed thread(not sure if i can send direct message), anyway sorry about it and i can delete it if you want.

At any any way i will stop posting about this subject because it's seem that this is no going to be solved in this channel, but i planned to fix this overhead. 
Thanks.
