### ISSUE TITLE
[docs] distributed docs still mention/recommend deprecated torch.distributed.launch

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#73319]
### 📚 The doc issue

https://pytorch.org/docs/master/distributed.html

should be changed in favor of distributed.run?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by zhaojuanmao** [comment]
It has warning "This module is going to be deprecated in favor of [torchrun](https://pytorch.org/docs/master/elastic/run.html#launcher-api)." in the doc.  

We can replace it with torchrun once it is completely derpecated

**Comment by vadimkantorov** [comment]
Please still keep a note of using torch.distributed.run directly. I'm always wary of using some "wrappers" that I don't understand (it's harder then to debug as gdb only accepts paths to binaries and not shell scripts etc). If it's equivalent, a pure torch.distributed.run commans are also very useful- for assuring people that torchrun doesn't do any magic

**Comment by vadimkantorov** [comment]
The docs mention torch.distributed.launch. When you use it, it asks to use torch.distributed.run. Is torch.distributed.run also going to be deprecated? What's under the hood of torchrun script?

**Comment by zhaojuanmao** [comment]
reopening it, cc @kiukchung

**Comment by kiukchung** [comment]
torch.distributed.run is the module behind torchrun and torch.distributed.launch. Because many users are grandfathered into torch.distributed.launch through other tools, it will take some time to actually remove torch.distributed.launch (we might have to do it for the next major release of torch - torch-2.x). In any case torch.distributed.run is the module powering both torchrun and torch.distributed.launch.

**Comment by vadimkantorov** [comment]
Then it would be good for docs to also show an equivalent run of not-going-to-be-deprecated torch.distributed.run which is more transparent to users than torchrun script
