### ISSUE TITLE
Windows tests frequently timeout

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#73489]
### 🐛 Describe the bug

See https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=win-vs2019-cuda11.3-py3%20/%20test%20(default,%201,%202

And here are the examples of timeouts:
https://github.com/pytorch/pytorch/actions/runs/1907050384
https://github.com/pytorch/pytorch/actions/runs/1903970575
https://github.com/pytorch/pytorch/actions/runs/1902319280

### Versions

N/A

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
This should be fixed after https://github.com/pytorch/pytorch/pull/73293 and https://github.com/pytorch/pytorch/pull/73467. The first allowed the stats to be uploaded correctly, but since the jobs were still timing out, the stats were mostly empty for shard 1, which is why extending the timeout in the second PR allowed accurate stats to be collected. 

Looking at the latest trunk commit, see https://hud2.pytorch.org/pytorch/pytorch/commit/b213041df304c05980b3209dddf1b595699c8b74, sharding for windows has been back to normal, though a combined testing of 5hrs is a lot and something we should address separately.

**Comment by Blackhex** [comment]
It does not seem that the [https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=win-vs2019-cuda11](https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=win-vs2019-cuda11) pipelines are sufferring with this issue anymore.

**Comment by malfet** [comment]
I think there are multiple issues that contributed to that:
 - CUDA-11.3 has a performance bug for certain optimization 
 - We've since implemented dynamic sharding and none of the shards right now seem to exceed 100 min, see https://hud.pytorch.org/metrics

I guess good follow up would be to create a PR that reduces test timeout to 120 min
