### ISSUE TITLE
Enable squid proxy to use TLS + work with HTTPS

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73812]
### 🚀 The feature, motivation and pitch

The squid proxy would be useful in caching existing dependencies and eliminating flakiness when pulling dependencies. Currently it only works with http which is unfortunate as the modern world (rightfully) uses https.

It may be a game changer for eliminating network flakiness if we could get this working!

Current code for this is hosted at https://fburl.com/code/hmerw8ky

Here's the wiki on how to actually add tls support: https://wiki.squid-cache.org/Features/HTTPS

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
We should either kill this or enable this.

**Comment by seemethere** [comment]
Added some more context to the issue about where to find the code as well as the wiki entry on how to add tls support to squid in the first place.

**Comment by osalpekar** [comment]
Did research on this task, and discussed with @seemethere . What I found is that we already support HTTPS connections to Squid Cache, but it functions as a transparent tunnel proxy. This means that squid will still accept HTTPS connections, but the payloads are still encrypted when they pass through Squid. Since hosts/connections will use different keys to encrypt their payloads, even the same unencrypted data will appear different to Squid, since it only sees the encrypted data. Basically, apart from repeated requests from the same host, Squid will largely not cache anything.

There is a work around for this using Squid's `sslBump`, but this approach is essentially a man-in-the-middle interception. Effectively we are violating the e2e encryption of HTTPS by creating separate connections between Squid and the client/server. Certificates must be dynamically generated and self-signed, with us serving as the root cert authority. I'm not sure if this is a great practice security-wise, and since we're largely caching build/test binaries and artifacts here, HTTP can suffice.
