### ISSUE TITLE
Memory surges when loading models

### ISSUE THREAD

**Issue by travel-go** [pytorch/pytorch#7415]
Hello,I meet a problem recent.
When I want to load an already trained model, my memory will experience a surge (approximately double the memory). I would like to ask if I can avoid this when loading the model. Is there any way to solve this problem?

**Comment by ailzhang** [comment]
@travel-go  How large was your checkpoint approximately?

**Comment by ailzhang** [comment]
Discussed with @SsnL  and @colesbury , I will add a Module.load_state_from_file() function which implicitly load the checkpoint to cpu first and then move onto GPU, which avoids using doubled GPU memory.

**Comment by karandwivedi42** [comment]
Won't this lead to a confusion of whether to use `load_state_dict` or `load_state_from_file`?

**Comment by SsnL** [comment]
I’m still advocating overloading load_state_dict’s first arg. Or maybe we
can add an additiknal kwarg.

**Comment by ailzhang** [comment]
load_state_from_file will just call torch.load(, map_location='cpu') and then load_state_dict() I think. Yea this could also be done by overloading load_state_dict(), not sure changing the API is preferred.

**Comment by karandwivedi42** [comment]
Or we can better document the `map_location=cpu` in `torch.load`, stating that it should be used if GPU memory is low.

**Comment by ailzhang** [comment]
@karandwivedi42  Yep that's also one option we talked about.

**Comment by ailzhang** [comment]
Hi @travel-go , if you are referring your checkpoint as a state_dict, then load_state_dict() is doing a for loop to load them one by one. 
If you are loading your checkpoint from a file, the tensor reconstruction happens in __reduce__ behavior of Tensor & storageBase object, and triggered by pickle. Please note that loading from file is done through `torch.load()` and it has nothing to do with a model yet. Thus it's true that if you load something from a file, it will load the whole to either cpu/gpu and then you can load one by one to your model. In most cases we think it's okay to use more CPU memory rather than GPU memory. Could you elaborate more of your use case( is cpu/gpu memory constrained?) so that we could help resolve it?

**Comment by travel-go** [comment]
I am grateful for your reply.I understand it.In my code,the function of  torch.load()  loads the whole model to gpu.I just change its storage path to the cpu.Thank you,I solve it.

**Comment by aaniin** [comment]
Came across this while training on a GPU with very limited memory. Training worked fine but upon restoring from a previous checkpoint, got OOM on the GPU. Thanks so much for the hint to "load the checkpoint to cpu first and then move onto GPU" and the note in the torch.load() function! This easily worked for me:
```
# Bad gives OOM on GPU
# params = torch.load(model_save_path, map_location=lambda storage, loc: storage)
# Good. Load to cpu first, then to GPU
params = torch.load(model_save_path, map_location='cpu')
model.load_state_dict(params['state_dict'])
model = model.to(device)
```
Subsequently, I ran into them same problem with the optimizer, where I got OOM while the GPU tensors where copied. The same strategy was successful here too, namely
```
# Bad. Gives OOM
# optimizer.load_state_dict(torch.load(model_save_path + '.optim')
# Good. Works.
optimizer.load_state_dict(torch.load(model_save_path + '.optim', map_location='cpu'))
optimizer_to(optimizer,device)
```
Here, optimizer_to is the code snippet from @0phoff posted in #8741 
```
def optimizer_to(optim, device):
    for param in optim.state.values():
        # Not sure there are any global tensors in the state dict
        if isinstance(param, torch.Tensor):
            param.data = param.data.to(device)
            if param._grad is not None:
                param._grad.data = param._grad.data.to(device)
        elif isinstance(param, dict):
            for subparam in param.values():
                if isinstance(subparam, torch.Tensor):
                    subparam.data = subparam.data.to(device)
                    if subparam._grad is not None:
                        subparam._grad.data = subparam._grad.data.to(device)
```
(This issue came up prominently on google when searching my error, so just would like to share how one can solve.)
