### ISSUE TITLE
Migrate binary build and upload jobs off codegen

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#74480]
Right now, the binary build jobs are the only remaining user of `generate_ci_workflows.py`. Ideally, we could migrate them off it so that we can delete all that infra, but @seemethere pointed out that it might not be so simple given the way the binary builds are structured.

It's not a big deal to keep them either, but then maybe we should clean up the non-binary-build parts of the codegen.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
I think the only issue with doing this is that re-usable workflows cannot be used with the matrix directive in Github Actions workflows.

Given the nature of the binary builds, it seems like without codegen that we'll be copy/pasting these workflows anyways since we need them to work over a matrix of values across python versions, cuda versions, etc.

**Comment by seemethere** [comment]
> I have a scheme in mind that may work, but it has one limitation: ALL builds will have to complete before any uploads start. Do you think that would be an issue?

Yes that would be an issue, in an ideal world we wouldn't want one failing build to block all of the uploads of the builds that have been green.

An example of this would be in the last release (1.11) where CUDA 11.1 builds were knowingly failing because of a dependency issue. We decided to cut CUDA 11.1 from the official release matrix but did not want to have to build an entirely new release candidate in order to do that. If we made uploads a dependency of all builds succeeding we'd lose flexibility on that front.

**Comment by seemethere** [comment]
- [ ] Migrate current templates to re-usable workflows, still codegen nightly / master builds using `generate_ci_workflows.py`
  - [ ] linux
  - [ ] windows
  - [ ] macOS
- [ ] When re-usable workflows gain the ability to use the `strategy: matrix` we can then migrate our codegen completely out

To regenerate workflows use `.github/regenerate.sh`

**Comment by janeyx99** [comment]
ccing @ZainRizvi -- you are working on this, no?

**Comment by seemethere** [comment]
> ccing @ZainRizvi -- you are working on this, no?

work should be here: https://github.com/pytorch/pytorch/pull/80741

**Comment by suo** [comment]
reopning as we still have windows and mac to tackle I believe

**Comment by ZainRizvi** [comment]
> ccing @ZainRizvi -- you are working on this, no?

Apologies for missing the earlier ping.  I recently discovered all my github emails were still set to go to my old @google.com email address 😅

With the above PRs, the current status of the work is:

- [x] Migrate current templates to re-usable workflows, still codegen nightly / master builds using `generate_ci_workflows.py`
  - [x] linux
  - [x] windows
  - [x] macOS
- [ ] When re-usable workflows gain the ability to use the `strategy: matrix` we can then migrate our codegen completely out

**Comment by ZainRizvi** [comment]
We found bugs and reverted these PRs.

The Linux PR has been fixed and resubmitted.  The MacOS + Windows ones are hairy enough that we're going to punt on them until Github actions actually supports the matrix strategy for reusable workflows.

So the current status of the work is:

- Migrate current templates to re-usable workflows, still codegen nightly / master builds using `generate_ci_workflows.py`
  - [x] linux
  - [ ] windows - partial PR for future reference: https://github.com/pytorch/pytorch/pull/81572
  - [ ] macOS - partial PR for future reference: https://github.com/pytorch/pytorch/pull/81571
- [ ] When re-usable workflows gain the ability to use the `strategy: matrix` we can then migrate our codegen completely out
