### ISSUE TITLE
NVFuser takes a fallback with bfloat16 inputs on V100

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#75089]
```
def fn(x):
    x=x.clamp(min=1.)*.1
    return x

x=torch.randn(4, device="cuda", dtype=torch.bfloat16)
scripted = torch.jit.script(fn)
fn(x)
with torch.jit.fuser("fuser2"):
    for _ in range(10):
        out = scripted(x)
```
produces
```
/data/users/ngimel/pytorch/../playground/gelurelu.py:20: UserWarning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (Triggered internally at  /data/users/ngimel/pytorch/torch/csrc/jit/codegen/cuda/manager.cpp:255.)
```
NVFuser should either support bfloat16 or properly refuse to fuse that operation, instead of going all the way with fusion and failing only in codegen.

**Comment by jjsjann123** [comment]
Turns out I never pushed the `comment` button.

This one should have been addressed on our last upstream push (https://github.com/pytorch/pytorch/pull/73627/files#diff-9a369e3147d7eb6a66c7ced126ada0a68e2cdf34e6e677b6e17135ed2abd4e60R125-R129) and I'm not seeing it repro on master.

I'm closing this one.
