### ISSUE TITLE
checkpointing of DDP comms hook

### ISSUE THREAD

**Issue by kumpera** [pytorch/pytorch#75666]
### 🚀 The feature, motivation and pitch

Some DDP comms hook, like PowetSGD, are stateful and must be part of model checkpointing to enable trainer restarts.

Right now, this has to be manually done by users and, in some cases, requires workaround as the state objects are not serializatible. For example: https://discuss.pytorch.org/t/how-to-resume-with-powersgd-enabled-training/148747/

DDP should include those objects available on its state_dict to make restarts feasible.

### Alternatives

Make comm hook state objects serializable and let users deal with the extra plumbing

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
Thanks! I don't think we considered checkpoint implications, but a first thought is that we can override state_dict's load/save  hooks to check if there is a communication hook, and if so, checkpoint it? And have stateful hooks responsible for implementing their own __getstate__ and __setstate__ so that they can be serialized / pickled appropriately. 

cc @zhaojuanmao @mrshenli

**Comment by zhaojuanmao** [comment]
"implementing their own getstate and setstate so that they can be serialized / pickled appropriately." sounds a better solution!

**Comment by rohan-varma** [comment]
@zhaojuanmao Although, we'd still want to ensure that after they're serialized, they are checkpointed by DDP right, so they need to be included into state_dict?
