### ISSUE TITLE
Variable names created dynamically using python are not added to Module.parameters()

### ISSUE THREAD

**Issue by WangYizhang01** [pytorch/pytorch#76165]
### 🐛 Describe the bug

Variable names created dynamically using python are not added to Module.parameters().

```python
import torch
import torch.nn as nn

class Test(nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        self.c = []
        self.init_weight()
        names = self.__dict__
        for i in range(len(self.c)):
            names['weight_' + str(i)] = Parameter(self.c[i], requires_grad=True)
    
    def init_weight(self):
        a = torch.randn(2, 3, requires_grad=True)
        b = torch.randn(2, 3, requires_grad=True)
        self.c.append(a); self.c.append(b)
    
    def forward(self):
        return self.a + self.b

test = Test()
for param in test.parameters():
    print(param)
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.103.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==0.9.0
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] pytorch                   1.10.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         0.9.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py38_cu113    pytorch
[conda] torchvision               0.11.1               py38_cu113    pytorch

**Comment by ishaan-mehta** [comment]
If you check out `torch.nn.Module` [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py), you can see that the way PyTorch registers parameters is by overriding `__setattr__`, monitoring the types of the attributes being set, and calling `register_parameter` to add the parameter to `self._params`. Check out [this episode](https://pytorch-dev-podcast.simplecast.com/episodes/torchnn?t=3m10s) of @ezyang's great PyTorch Developer Podcast for more information on the implementation of `torch.nn` (the link will start the episode at the timestamp most relevant to your issue).

Since registering parameters is done by overriding `__setattr__`, the only way PyTorch knows to register a parameter is if `__setattr__` is called. Your provided code modifies `self.__dict__` directly, which bypasses `self.__setattr__`, which in the most common case is called when you do something like `foo.bar = "baz"`. That syntax does not work for dynamic parameter names, which I suspect is why you tried to do it by modifying `self.__dict__` in the first place. Fortunately, Python has a built-in function called `setattr` which will do exactly what we need. You call it like `setattr(object, name, value)`, so all we need to do to fix your code is remove/modify two lines, and it works like a charm. Here is the working code:

```
import torch
import torch.nn as nn

class Test(nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        self.c = []
        self.init_weight()
        for i in range(len(self.c)):
            setattr(self, 'weight_' + str(i), nn.Parameter(self.c[i], requires_grad=True))
    
    def init_weight(self):
        a = torch.randn(2, 3, requires_grad=True)
        b = torch.randn(2, 3, requires_grad=True)
        self.c.append(a); self.c.append(b)
    
    def forward(self):
        return self.a + self.b

test = Test()
for param in test.parameters():
    print(param)
```

**Comment by WangYizhang01** [comment]
Thanks for your reply.
