### ISSUE TITLE
view() after transpose() raises non contiguous error

### ISSUE THREAD

**Issue by wkentaro** [pytorch/pytorch#764]
I'm running below code, and got error below.
Commenting out `y = y.transpose(0, 1)` ends up without error.
Is this something expected?

```python
import torch
import torch.nn
from torch.autograd import Variable
import numpy as np

x = Variable(torch.from_numpy(np.random.randn(4, 6, 5)).float(), requires_grad=True)
x = torch.transpose(x, 1, 2)
conv = torch.nn.Conv1d(in_channels=5, out_channels=10, kernel_size=2)
y = conv(x)
y = y.transpose(0, 1)  # this line cause error
y = y.view(-1)
result = torch.sum(y)
result.backward()
```

```
Traceback (most recent call last):
  File "spam.py", line 13, in <module>
    y = y.view(-1)
  File "/home/wkentaro/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 469, in view
    return View(*sizes)(self)
  File "/home/wkentaro/anaconda2/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 96, in forward
    result = i.view(*self.sizes)
RuntimeError: input is not contiguous at /home/wkentaro/Projects/pytorch/src/pytorch/torch/lib/TH/generic/THTensor.c:231
```

In actual, I'm using `.transpose()` and `.view()` to use `cross_entropy` for `(n_batch, channel, height, width)` tensor by reshaping it to `(n_batch * height * width, channel)`

**Comment by fmassa** [comment]
Yes, this is expected, as `view` is only supposed to work on contiguous tensors, and transposing a tensor makes it non-contiguous. You can use `.contiguous()` after `transpose` to fix your issue

**Comment by wkentaro** [comment]
Thank you for the quick response. It fixes my problem!
I think I'm being familiar to pytorch.

**Comment by ducha-aiki** [comment]
@fmassa is there any good reason to add contiguous() into transpose function be default?

**Comment by fmassa** [comment]
@ducha-aiki it is much more efficient to have non-contiguous tensors, as you only need to perform a swap in the sizes/strides, instead of copying the whole memory of the tensor.
The reason why adding a `contiguous` inside `view` might not be a good idea is that we would not be guaranteed anymore that the original tensor and the viewed tensor shares the same memory address, which is supposed in the codebase atm.
Not sure which is the best approach, if we would prefer to change `view` (and maybe break existing code) or add another function which is `view`+`contiguous`, and call it something else (like `ravel` or something)

**Comment by themightyoarfish** [comment]
I'm a bit confused, how does swapping axes make the underlying memory suddenly non-contiguous?
