### ISSUE TITLE
rocm averages 20m to pull docker image

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#76413]
For the past week, rocm (specifically linux-bionic-rocm5.0-py3.7 / test) averages about 20m to pull the docker image, while the other linux jobs generally take about 2m.

Example GHA runs: https://github.com/pytorch/pytorch/runs/6178824044?check_suite_focus=true, https://github.com/pytorch/pytorch/runs/6178824044?check_suite_focus=true, https://github.com/pytorch/pytorch/runs/6132356305?check_suite_focus=true

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jeffdaily** [comment]
We discussed this with @seemethere yesterday.  Proposing #76415 to help.  ROCm runners shouldn't need to completely wipe out all docker images, just the containers.  This should hopefully speed up docker image pulls.

Follow-up: Is there a way to generate this time-to-pull metric rather than looking at individual job logs?

**Comment by clee2000** [comment]
> Follow-up: Is there a way to generate this time-to-pull metric rather than looking at individual job logs?

I look at rockset to get averages, but outside of that, I'm not sure
