### ISSUE TITLE
tensor.shape[0] return a tensor not a constant

### ISSUE THREAD

**Issue by sjbling** [pytorch/pytorch#76660]
### 🐛 Describe the bug

 import torch
image = torch.rand(6,3,64,64).cuda()
.....
torch.onnx.export(model, images,opset_version=13...)

Class Net():

def forward(image):
       print(image.shape[0])

### Versions

python 3.8.8
torch 1.8.0

**Comment by BowenBao** [comment]
Hi @sjbling ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
