### ISSUE TITLE
`torch.svd_lowrank` isn't reproducable

### ISSUE THREAD

**Issue by thomasahle** [pytorch/pytorch#77206]
### 🐛 Describe the bug

When using `torch.svd_lowrank` you easily get very unreproducible results.
Even when seeding and disabling non-deterministic algorithms:

```
>>> x = torch.randn(5, 5)
>>> torch.use_deterministic_algorithms(True)
>>> torch.manual_seed(0)
>>> torch.svd_lowrank(x, q=2)
(tensor([[-0.6710, -0.5755],
         [ 0.4112, -0.4239],
         [ 0.4226, -0.6732],
         [-0.4169, -0.1125],
         [ 0.1683,  0.1526]]),
 tensor([3.7066, 2.2229]),
 tensor([[ 0.5112,  0.1867],
         [-0.1620, -0.4347],
         [ 0.1373,  0.7884],
         [ 0.6470, -0.3911],
         [ 0.5244, -0.0402]]))
>>> torch.svd_lowrank(x, q=2)
(tensor([[-0.6738, -0.6063],
         [ 0.4073, -0.4633],
         [ 0.4279, -0.6256],
         [-0.4102, -0.0533],
         [ 0.1695,  0.1536]]),
 tensor([3.7059, 2.2296]),
 tensor([[ 0.5101,  0.2025],
         [-0.1605, -0.4348],
         [ 0.1294,  0.7400],
         [ 0.6342, -0.4687],
         [ 0.5433,  0.0524]]))
```

One issue is also the default setting of `n_iter=2`. If possible, it seems a better choice to give correct results by default (higher iteration number), and then let people set a very low iteration count if they need the extra performance.

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: version 3.21.4
Libc version: N/A

Python version: 3.9.12 (main, Apr 11 2022, 01:47:47)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.3.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.1.1
[pip3] numpy==1.19.5
[pip3] torch==1.11.0
[pip3] torchmetrics==0.8.2
[pip3] torchvision==0.12.0
[conda] Could not collect

cc @mruberry @kurtamohler @jianyuh @nikitaved @pearu @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by IvanYashchuk** [comment]
There's a note in the documentation of [`torch.svd_lowrank`](https://pytorch.org/docs/stable/generated/torch.svd_lowrank.html):
> To obtain repeatable results, reset the seed for the pseudorandom number generator

`svd_lowrank` uses a randomized algorithm and it's expected that for every call the results are different. Not every function is covered by `use_deterministic_algorithms` flag, I think the action here would be to raise an error when `use_deterministic_algorithms` is set to `True`.

**Comment by Lezcano** [comment]
cc @kurtamohler

**Comment by kurtamohler** [comment]
If I understand correctly, I think there's an argument for why we shouldn't make `svd_lowrank` raise a nondeterministic error. `svd_lowrank` does appear to use a deterministic algorithm, because if it's given all the same inputs and the same RNG seed, it gives the same output. We can think of the RNG seed as an input to the algorithm, and changing the seed can change the output of `svd_lowrank`.

If we call `svd_lowrank` twice within a script that sets `torch.use_deterministic_algorithms(True)` and `torch.manual_seed(<constant>)`, then each time you run the script, the first call to `svd_lowrank` will always produce the same result, and the second will always produce the same result, and the final output of the script itself will be the same each time you run it. I think that satisfies the purpose of `use_deterministic_algorithms`.

To give a related example, consider a script that just calls `torch.rand(...)` multiple times, and it sets the RNG seed to a constant and `torch.use_deterministic_algorithms(True)`. Even though each call to `torch.rand` will produce a different result, you'll get the same series of results each time you run the script. So it's still deterministic

**Comment by kurtamohler** [comment]
So you're saying that `pytorch_lightning.utilities.seed.seed_everything` doesn't appear to set `torch.manual_seed`? I agree that seems like a bug. You can open an issue over on the Lightning repo: https://github.com/PyTorchLightning/pytorch-lightning

As for `niter=2`, I know almost nothing about `svd_lowrank`. I think the others on this thread probably know

**Comment by carmocca** [comment]
PL dev here! `seed_everything` does call `manual_seed`: https://github.com/PyTorchLightning/pytorch-lightning/blob/32f361f86713bf6bf19525585c9602ba297d2be3/pytorch_lightning/utilities/seed.py#L75-L76

**Comment by kurtamohler** [comment]
Cool, thanks @carmocca!

I think I could improve our determinism/reproducibility docs by mentioning that some operations may change the RNG seed, and in order to get the same result from subsequent calls to those operations within one execution of a script, the seed needs to be reset before each call. I'll do that soon
