### ISSUE TITLE
Write decomposition conditionals in a way that leads to simpler shape expressions

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#77232]
### 🚀 The feature, motivation and pitch

Take code like
```
assert x.numel() != 0
```

vs. 
```
assert all([i > 0 for i in x.shape])
```

Both of these are mathematically equivalent. But, the second one will be more friendly to a dynamic shapes tracing model that guards on 0/1. It doesn't lead to less recompiles, but it could lead to simpler guard expressions.

cc: @jansel @ezyang 

cc @ezyang @mruberry @ngimel

**Comment by ezyang** [comment]
Honestly whatever symbolic reasoning we're doing should be able to simplify `a * b * c == 0` into `a != 0 & b != 0 & c != 0`, it's pretty simple...

**Comment by jansel** [comment]
`a*b*C` isn't the case I'm worried about.  I agree it is easy to write a pass to simplify that.

The problem is the input shape could be some arbitrary symbolic expression due to slicing, views, concat, etc.

`x[5:,:].numel()` might be `(a-5)*b` which might get expanded to `a*b - 5*b`.  You can construct an arbitrarily complex example.  We don't currently have anyone planning to build a powerful enough symbolic reasoning system to handle every case.

In addition to that one guard being worse.  If you think of a large system with hundreds of guards, you actually could get asymptotically more guards in total.  Consider a system that does `assert x.numel()!=0` with all pairs of variables `v0` through `vN`.  Without a simplifier coming to the rescue, expressed the first way you get `n**2` total guards.  Expressed in the second form you only get `n` guards.

**Comment by ezyang** [comment]
To be upfront about this: I don't mind making modifications to our decompositions to improve traceability. We shouldn't write `assert all([i > 0 for i in x.shape])` though, we should add some method like `x.is_empty` which can either do the fast eager computation or the slow trace friendly computation.

However...

> x[5:,:].numel() might be (a-5)*b which might get expanded to a*b - 5*b

The fact that we are worrying about this suggests that sympy may not be the right tool for the job. An analogy I'd draw is with the development of AD: before AD was a thing, people used symbolic differentiation and it sucked, because conventional differentiation rules cause term blowup. AD was an important innovation because it is work preserving. I see a similar situation playing out here, where while using a conventional symbolic mathematics program is nice and can prove a lot of things, in the worst case it could result in unboundedly horrible terms.

Our requirements are not traditional symbolic math requirements. Well, we haven't really nailed down what our requirements are, but on the simpler side we want a guard to be expressible as a conjunction of a limited set of predicate tests on a single variable; on the more complex side we might want predicate tests to involve multiple variables but we want to minimize the number of variables involved in each test. It's not right to treat sympy as a black box; we should make sure our reasoning system is doing what we need to, and be willing to develop our own reasoning system (it can be very simple! The simpler the better) to meet our requirements.

cc @mruberry

**Comment by mruberry** [comment]
> To be upfront about this: I don't mind making modifications to our decompositions to improve traceability. We shouldn't write `assert all([i > 0 for i in x.shape])` though, we should add some method like `x.is_empty` which can either do the fast eager computation or the slow trace friendly computation.
 
I agree and want to "yes, and..." that we can't require hints like `x.is_empty` but we can make them optional for better performance, and in many cases these hints should be convenient to developers, too.

**Comment by jansel** [comment]
Agreed on is_empty().

In the limit we need a full-fledged ILP solver here.  If an ILP solver were part of the plan I would be way less worried about cases like this.  ILP solvers are hard to build, so I would hesitate about starting our own.

I hoped that sympy would be good enough, though you definitely need to be careful about how you use it since it is not a solver.  That imposes requirements on how decomps are written.
