### ISSUE TITLE
[ONNX] Run vision's test_onnx.py in the PyTorch CI

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#78089]
### 🚀 The feature, motivation and pitch

Threre are some instances where a change in the ONNX exporter would break the torchvision CI. (latest https://github.com/pytorch/pytorch/pull/77448). It is cumbersome to run torchvision's tests locally every time a change is made to the exporter. It may be helpful to create a pipeline in PyTorch's CI to run `test_onnx.py`.

### Alternatives

Run vision's tests locally every time a change is made to the exporter.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @fmassa @vfdev-5 @pmeier

**Comment by pmeier** [comment]
`torchvision` only runs end-to-end ONNX tests. Thus, if some breaking changes are not detected by the PyTorch core CI we have a gap in the ONNX unit tests. Shouldn't we close that gap instead of relying on end-to-end tests of a downstream library?

That being said, there already seem to be some ONNX tests here that rely on `torchvision`:

https://github.com/pytorch/pytorch/blob/9e806619ccbd211b2501fd380ec7d1bd398ec67c/test/onnx/test_models.py#L25-L35

We could port `pytorch/vision/test/test_onnx.py` there.

`torchdata` is also running part of `torchvision`'s test suite. However, they are using a different paradigm: there is a [CI job](https://github.com/pytorch/data/blob/13b574c80e8732744fee6ab9cb7e35b5afc34a3c/.github/workflows/domain_ci.yml#L15) that installs the `torchvision` nightly, checks out the repository at the same commit and runs the original tests. This has the benefit that all changes that `torchvision` makes to the test are automatically available in the `torchdata` CI. But this requires a separate CI job, which maybe not feasible.

**Comment by justinchuby** [comment]
@pmeier thanks for the suggestions. I think they are very reasonable.
