### ISSUE TITLE
Failure to install caffe2 builded from source

### ISSUE THREAD

**Issue by iRedRum** [pytorch/pytorch#7840]
I'm folllowing the instruction on the 
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile
to build the caffe2 from source 
I followed the guidance from the part Clone & Build and when I tried to finish the final step, which is the "Compile, link, and install Caffe2" by sudo make install, I bump into the question.

## Issue description

The processing stucked at 
Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
and I can't find the resolution

## System Info
[ 29%] Built target onnx_proto
[ 30%] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
/home/yanyy/pytorch/third_party/onnx/onnx/common/ir_pb_converter.cc: In function ‘onnx_c2::Tensor onnx_c2::tensorProtoToTensor(const onnx_c2::TensorProto&)’:
/home/yanyy/pytorch/third_party/onnx/onnx/common/ir_pb_converter.cc:73:44: error: ‘fail_convert’ was not declared in this scope
     fail_convert("Unknown tensor data type");
                                            ^
/home/yanyy/pytorch/third_party/onnx/onnx/common/ir_pb_converter.cc: In function ‘void onnx_c2::convertAttribute(const onnx_c2::AttributeProto&, onnx_c2::Node*)’:
/home/yanyy/pytorch/third_party/onnx/onnx/common/ir_pb_converter.cc:155:44: error: ‘fail_convert’ was not declared in this scope
     fail_convert("Unknown tensor data type");
                                            ^
/home/yanyy/pytorch/third_party/onnx/onnx/common/ir_pb_converter.cc: In function ‘void onnx_c2::encodeTensor(onnx_c2::TensorProto*, const onnx_c2::Tensor&)’:
/home/yanyy/pytorch/third_party/onnx/onnx/common/ir_pb_converter.cc:374:44: error: ‘fail_convert’ was not declared in this scope
     fail_convert("Unknown tensor data type");
                                            ^
third_party/onnx/CMakeFiles/onnx.dir/build.make:110: recipe for target 'third_party/onnx/CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o' failed
make[2]: *** [third_party/onnx/CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o] Error 1
CMakeFiles/Makefile2:1102: recipe for target 'third_party/onnx/CMakeFiles/onnx.dir/all' failed
make[1]: *** [third_party/onnx/CMakeFiles/onnx.dir/all] Error 2
Makefile:138: recipe for target 'all' failed

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source (but I take all the step with my custom environment in anaconda)
- Build command you used (if compiling from source): I do as the exact way from: https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile 
from the part  "Clone & Build"
- OS: ubuntu 16.0
- PyTorch version: latest?
- Python version: 2.7.15
- CUDA/cuDNN version: cuda 8.0 cudnn 7.0.5
- GPU models and configuration:
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.5.1
- Versions of any other relevant libraries:

**Comment by msnhs** [comment]
I have same problem, please help~

**Comment by songzenghui** [comment]
When i run `sudo make install ` to compile ,ERRORs occurs.
I install the caffe2 from source code Here is my Linux:

- OS : Ubuntu 16.04

- CUDA ： 9.0

- CUDNN : 7.0
Here is the configure of caffe2 build(the output after running `cmake ..`):

-- Does not need to define long separately.
-- std::exception_ptr is supported.
-- NUMA is available
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/songzenghui/zee/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:Eigen
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Failed to find LLVM FileCheck
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- Found Numa  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnuma.so)
-- Found CUDA: /usr/local/cuda (found suitable exact version "9.0") 
-- OpenCV found (/usr/local/share/OpenCV)
CMake Warning at cmake/Dependencies.cmake:309 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:188 (include)


-- Did not find system Eigen. Using third party subdirectory.
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.12", minimum required is "2.7") 
-- NumPy ver. 1.14.2 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
-- MPI support found
-- MPI compile flags: 
-- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI LINK flags path:  -Wl,-rpath  -Wl,/usr/lib/openmpi/lib  -Wl,--enable-new-dtags
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
CMake Warning at cmake/Dependencies.cmake:364 (message):
  OpenMPI found, but it is not built with CUDA support.
Call Stack (most recent call first):
  CMakeLists.txt:188 (include)


-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.0") 
-- Caffe2: CUDA detected: 9.0
-- Found cuDNN: v7.1.2  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Automatic GPU detection returned 6.1 6.1.
-- Added CUDA NVCC flags for: sm_61
-- Could NOT find NCCL (missing: NCCL_INCLUDE_DIRS NCCL_LIBRARIES) 
-- Could NOT find CUB (missing: CUB_INCLUDE_DIR) 
-- Could NOT find Gloo (missing: Gloo_INCLUDE_DIR Gloo_LIBRARY) 
-- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
-- CUDA detected: 9.0
-- Found libcuda: /usr/local/cuda-9.0/lib64/stubs/libcuda.so
-- Found libnvrtc: /usr/local/cuda-9.0/lib64/libnvrtc.so
-- GCC 5.4.0: Adding gcc and gcc_s libs to link line
-- Include NCCL operators
-- Excluding ideep operators as we are not using ideep
-- Including image processing operators
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- Include Observer library
-- Using lib/python2.7/dist-packages as python relative installation path
-- Automatically generating missing __init__.py files.
-- A previous caffe2 cmake run already created the __init__.py files.
CMake Warning at CMakeLists.txt:318 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.


-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.1.11-8572-g45cdb63
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_CAFFE2          : ON
--   BUILD_ATEN            : OFF
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python includes     : /usr/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 9.0
--     cuDNN version       : 7.1.2
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda-9.0/lib64/stubs/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so
--     nvrtc               : /usr/local/cuda-9.0/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--     USE_GLOO_IBVERBS    : OFF
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : ON
--     OpenCV version      : 3.4.0
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/songzenghui/zee/pytorch/build

Here is the ERRORs:
[ 89%] Building CXX object caffe2/CMakeFiles/init_test.dir/core/init_test.cc.o
[ 89%] Linking CXX executable ../bin/init_test
[ 89%] Built target init_test
Scanning dependencies of target backend_cutting_test
[ 89%] Building CXX object caffe2/CMakeFiles/backend_cutting_test.dir/opt/backend_cutting_test.cc.o
[ 89%] Linking CXX executable ../bin/backend_cutting_test
[ 89%] Built target backend_cutting_test
Scanning dependencies of target registry_test
[ 89%] Building CXX object caffe2/CMakeFiles/registry_test.dir/core/registry_test.cc.o
[ 89%] Linking CXX executable ../bin/registry_test
[ 89%] Built target registry_test
Scanning dependencies of target pattern_net_transform_test
[ 89%] Building CXX object caffe2/CMakeFiles/pattern_net_transform_test.dir/transforms/pattern_net_transform_test.cc.o
[ 89%] Linking CXX executable ../bin/pattern_net_transform_test
[ 89%] Built target pattern_net_transform_test
Scanning dependencies of target operator_test
[ 89%] Building CXX object caffe2/CMakeFiles/operator_test.dir/core/operator_test.cc.o
[ 89%] Linking CXX executable ../bin/operator_test
[ 89%] Built target operator_test
Scanning dependencies of target smart_tensor_printer_test
[ 89%] Building CXX object caffe2/CMakeFiles/smart_tensor_printer_test.dir/utils/smart_tensor_printer_test.cc.o
[ 89%] Linking CXX executable ../bin/smart_tensor_printer_test
[ 89%] Built target smart_tensor_printer_test
Scanning dependencies of target conv_op_cache_cudnn_test
[ 89%] Building CXX object caffe2/CMakeFiles/conv_op_cache_cudnn_test.dir/operators/conv_op_cache_cudnn_test.cc.o
[ 89%] Linking CXX executable ../bin/conv_op_cache_cudnn_test
[ 89%] Built target conv_op_cache_cudnn_test
Scanning dependencies of target boolean_unmask_ops_test
[ 89%] Building CXX object caffe2/CMakeFiles/boolean_unmask_ops_test.dir/operators/boolean_unmask_ops_test.cc.o
[ 89%] Linking CXX executable ../bin/boolean_unmask_ops_test
[ 89%] Built target boolean_unmask_ops_test
Scanning dependencies of target ssa_test
[ 89%] Building CXX object caffe2/CMakeFiles/ssa_test.dir/onnx/ssa_test.cc.o
[ 89%] Linking CXX executable ../bin/ssa_test
[ 89%] Built target ssa_test
Scanning dependencies of target event_test
[ 89%] Building CXX object caffe2/CMakeFiles/event_test.dir/core/event_test.cc.o
[ 89%] Linking CXX executable ../bin/event_test
[ 89%] Built target event_test
Scanning dependencies of target module_test
[ 89%] Building CXX object caffe2/CMakeFiles/module_test.dir/core/module_test.cc.o
[ 89%] Linking CXX executable ../bin/module_test
[ 89%] Built target module_test
Scanning dependencies of target typeid_test
[ 89%] Building CXX object caffe2/CMakeFiles/typeid_test.dir/core/typeid_test.cc.o
[ 89%] Linking CXX executable ../bin/typeid_test
[ 89%] Built target typeid_test
Scanning dependencies of target parallel_net_test
[ 89%] Building CXX object caffe2/CMakeFiles/parallel_net_test.dir/core/parallel_net_test.cc.o
[ 89%] Linking CXX executable ../bin/parallel_net_test
[ 89%] Built target parallel_net_test
Scanning dependencies of target fixed_divisor_test
[ 89%] Building CXX object caffe2/CMakeFiles/fixed_divisor_test.dir/utils/fixed_divisor_test.cc.o
[ 89%] Linking CXX executable ../bin/fixed_divisor_test
[ 89%] Built target fixed_divisor_test
Scanning dependencies of target blob_test
[ 89%] Building CXX object caffe2/CMakeFiles/blob_test.dir/core/blob_test.cc.o
[ 89%] Linking CXX executable ../bin/blob_test
CMakeFiles/blob_test.dir/core/blob_test.cc.o: In function `caffe2::(anonymous namespace)::ContentChunks_Serialization_Test::TestBody()':
blob_test.cc:(.text+0x3b356): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: warning: libgflags.so.2, needed by /usr/lib/x86_64-linux-gnu/libglog.so, may conflict with libgflags.so.2.2
[ 89%] Built target blob_test
Scanning dependencies of target mpi_gpu_test
[ 89%] Building CXX object caffe2/CMakeFiles/mpi_gpu_test.dir/mpi/mpi_gpu_test.cc.o
[ 89%] Linking CXX executable ../bin/mpi_gpu_test
/usr/bin/ld: CMakeFiles/mpi_gpu_test.dir/mpi/mpi_gpu_test.cc.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
//usr/lib/libmpi_cxx.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/mpi_gpu_test.dir/build.make:110: recipe for target 'bin/mpi_gpu_test' failed
make[2]: *** [bin/mpi_gpu_test] Error 1
CMakeFiles/Makefile2:3406: recipe for target 'caffe2/CMakeFiles/mpi_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/mpi_gpu_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ClassicDaniel** [comment]
Had the same problem. One of the steps on the Caffe2 website makes you download the newest versions of third party repos. The newest version of onnx is not compilable though. You can solve the problem by going to the cloned onnx folder, and changing to a working commit. Opening a terminal and writing `git checkout 310b44c` changed to a commit which I managed to compile.

**Comment by Sanyam2095** [comment]
Hi @ClassicDaniel 
I was trying to install caffe2 from source but while doing so I encountered same error and followed you instruction. But still I got the same error after I checkout the commit you mentioned.

**Comment by songzenghui** [comment]
I have solved this problem.
U should modify this file:`pytroch/caffe2/CMakefiles.txt ` ,add  the following code at the end of this file:
`SET(CMAKE_C_COMPILER mpicc)
SET(CMAKE_CXX_COMPILER mpicxx)
include_directories(MPI_INCLUDE_PATH)
target_link_libraries(mpi_test ${MPI_LIBRARIES})`

@Sanyam2095 @msnhs @iRedRum

**Comment by songzenghui** [comment]
I have solved this problem.
U should modify this file : `pytroch/caffe2/CMakefiles.txt` ,add the following code at the end of this file:
`SET(CMAKE_C_COMPILER mpicc) `
`SET(CMAKE_CXX_COMPILER mpicxx)`
` include_directories(MPI_INCLUDE_PATH)`
` target_link_libraries(mpi_test ${MPI_LIBRARIES})`

@Sanyam2095 @msnhs @iRedRum

**Comment by Sanyam2095** [comment]
@songzenghui 
I tried this but i am getting error in " target_link_libraries(mpi_test ${MPI_LIBRARIES})" this line. 

CMake Error at CMakeLists.txt:413 (target_link_libraries):
  Attempt to add link library "/usr/lib/openmpi/lib/libmpi.so" to target
  "mpi_test" which is not built in this directory.

This is the error I am getting by adding those line.

**Comment by songzenghui** [comment]
U can try to comment this line.
I did not encounter the error you said. So it maybe not right

发送自 Windows 10 版邮件应用

发件人: Sanyam2095
发送时间: 2018年6月6日 18:45
收件人: pytorch/pytorch
抄送: Zee; Mention
主题: Re: [pytorch/pytorch] Failure to install caffe2 builded from source(#7840)

@songzenghui
I tried this but i am getting error in " target_link_libraries(mpi_test ${MPI_LIBRARIES})" this line.
CMake Error at CMakeLists.txt:413 (target_link_libraries):
Attempt to add link library "/usr/lib/openmpi/lib/libmpi.so" to target
"mpi_test" which is not built in this directory.
This is the error I am getting by adding those line.

**Comment by cece-jy** [comment]
I have same problem, Have you solved it ？

**Comment by Sanyam2095** [comment]
@cece-jy 
Apology to keep you waiting, I was stuck in some other work so wasn't able to try this. 
Update as soon as I will test it.

**Comment by Ravi2712** [comment]
@Sanyam2095  @songzenghui @BanuSelinTosun 

I have the same issue.

Ubuntu:16.04
Cuda: 9.1
cuDNN: 7.1
Python: 3.6
Any resolution yet on this? If solved, please share here.

**Comment by mruberry** [comment]
Closing this issue due to age and because it is now recommended to use PyTorch, not Caffe2. If this is still relevant please file a new issue.
