### ISSUE TITLE
Not getting consistent mypy results from lintrunner

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#78695]
### 🐛 Describe the bug

Steps to repro:

1. `ghstack checkout https://github.com/pytorch/pytorch/pull/78527` I tested on 0cbe0a04162193c8e581cb913a1c86fb08b32f45
2. Run `lintrunner -a`

Expected result: errors like this https://github.com/pytorch/pytorch/runs/6692196515?check_suite_focus=true

Actual result: I tried two machines
1. devfair: lint is clean (but mypy exited suspiciously fast)

```
[2022-06-02T02:38:25Z TRACE lintrunner::log_utils] Linter 'MYPY' matched files: [/raid/ezyang/pytorch-scratch2/torch/_meta_registrations.py, /raid/ezyang/pytorch-scratch2/torch/_prims/__init__.py]
[2022-06-02T02:38:25Z TRACE lintrunner::log_utils] Linter 'MYPYSTRICT' matched files: [] 
```

3. osx lappy 

```
>>> Lint for torch/_meta_registrations.py:

  Error (MYPY) [attr-defined]
    Module has no attribute "_resize_output_"

         25  |
         26  |@torch.library.impl(meta_lib, "index_select.out")
         27  |def meta_index_select_out(self, dim, index, out):
    >>>  28  |    torch._resize_output_(out, self.size(), self.device)
         29  |    return out.copy_(torch.index_select(self, dim, index))
         30  |
         31  |@torch.library.impl(meta_lib, "max")

  Error (MYPY) [attr-defined]
    Module has no attribute "_resize_output_"

        113  |
        114  |@torch.library.impl(meta_lib, "bernoulli.out")
        115  |def meta_bernoulli(self, *, generator=None, out):
    >>> 116  |    torch._resize_output_(out, self.size(), self.device)
        117  |    return out
        118  |
        119  |@torch.library.impl(meta_lib, "_adaptive_avg_pool2d")

```

```
[2022-06-02T02:36:46Z TRACE lintrunner::log_utils] Linter 'MYPY' matched files: [/Users/ezyang/Dev/pytorch-tmp/torch/_meta_registrations.py, /Users/ezyang/Dev/pytorch-tmp/torch/_prims/__init__.py]
[2022-06-02T02:36:46Z TRACE lintrunner::log_utils] Linter 'MYPYSTRICT' matched files: []
```

### Versions

@suo

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by ezyang** [comment]
when I run `lintrunner torch/_refs/__init__.py` I get the desired errors

**Comment by jkseppan** [comment]
I had somewhat similar problems, which I traced to mypy not being installed in the same Python environment that lintrunner was using to run the mypy adapter. `lintrunner --take MYPY path/to/file.py` was over suspiciously fast with no errors but `mypy --config-file mypy.ini path/to/file.py` took a longer time and printed out some errors. It turns out that `mypy` was `$HOME/.local/bin/mypy` which was invoking `/usr/bin/python3.9` but lintrunner was using the version of Python in my Conda environment. Installing mypy with Conda fixed this.

The mypy adapter checks for OSError, but [`python -mmypy`](https://github.com/pytorch/pytorch/blob/main/tools/linter/adapters/mypy_linter.py#L93) doesn't raise this or any other error if the Python interpreter being called doesn't find the mypy module.
