### ISSUE TITLE
MPS: Adding int64 tensor does not work on AMD GPU

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#78848]
### 🐛 Describe the bug

Consider following simple example:
```
python3 -c "import torch;x=torch.arange(6); print(x+(1<<32), x.to('mps')+(1<<32))"
```

It yields correct results on my M1 MacMini:
```
% python3 -c "import torch;x=torch.arange(6); print(x+(1<<32), x.to('mps')+(1<<32))"
tensor([4294967296, 4294967297, 4294967298, 4294967299, 4294967300, 4294967301]) tensor([4294967296, 4294967297, 4294967298, 4294967299, 4294967300, 4294967301],
       device='mps:0')
```
But fails on x86 MacBook Pro:
```
 % python3 -c "import torch;x=torch.arange(6); print(x+(1<<32), x.to('mps')+(1<<32))"
tensor([4294967296, 4294967297, 4294967298, 4294967299, 4294967300, 4294967301]) tensor([0, 1, 2, 3, 4, 5], device='mps:0')
```

### Versions

Nightly

cc @kulinseth @albanD

**Comment by kulinseth** [comment]
Thanks @malfet, we are investigating the issue. Currently due to issues on AMD for int64, we are down-casting it to int32 and that's why you are seeing this behavior. We should raise an error on x86 for int64 like we do in unary/binary ops discussed   https://github.com/pytorch/pytorch/issues/80784.

**Comment by kulinseth** [comment]
@malfet , this issue should be resolved in Ventura release. Can you please verify and close it?

**Comment by skotapati** [comment]
Closing - lack of activity + x86 issue
