### ISSUE TITLE
Backward for Root of Complex Zero Failed with NaN

### ISSUE THREAD

**Issue by ChenKuo** [pytorch/pytorch#78903]
### 🐛 Describe the bug

Backward function for pow fails when the input is complex zero `0+0j` and exponent is less than 1, even though it works when the input is real zero (with `inf ` grad but no error).

Reproducible Example:
```python
input_t = torch.tensor([0.j], requires_grad=True)
sqaure_root = input_t.pow(1/2)
loss = sqaure_root.sum() # loss is tensor(0.+0.j)
loss.backward()
print(input_t.grad)
```
```
RuntimeError                              Traceback (most recent call last)
d:\projects\src-torch\bezier_spline.ipynb Cell 3' in <cell line: 4>()
      2 sqaure_root = input_t.pow(1/2)
      3 loss = sqaure_root.sum() # loss is tensor(0.+0.j)
----> 4 loss.backward()
      5 print(input_t.grad)

File d:\projects\.venv\lib\site-packages\torch\_tensor.py:399, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    390 if has_torch_function_unary(self):
    391     return handle_torch_function(
    392         Tensor.backward,
    393         (self,),
   (...)
    397         create_graph=create_graph,
    398         inputs=inputs)
--> 399 torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)

File d:\projects\.venv\lib\site-packages\torch\autograd\__init__.py:173, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    168     retain_graph = create_graph
    170 # The reason we repeat same the comment below is that
    171 # some Python versions print out the first line of a multi-line function
    172 # calls in the traceback and some print out the last line
--> 173 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    174     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    175     allow_unreachable=True, accumulate_grad=True)

RuntimeError: Function 'PowBackward0' returned nan values in its 0th output.
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0.dev20220507+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: N/A

Python version: 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Ti
Nvidia driver version: 471.41
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.2.0a0+b2c9d60
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220507+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] No relevant packages

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @anjali411 @dylanbespalko @mruberry

**Comment by Lezcano** [comment]
I assume this happens with the anomaly detection active?

This function is tricky, because it may not be defined even in a continuous way on C (or any simply connected neighbourhood containing zero for the matter). In this case, the discontinuity of the derivative is "similar to" a pole (it's a branch point, but yeah). So we should return some infinity value (perhaps).

Now, returning NaN is not crazy either, as this is a very weird point, and if you're asking for the derivative there on the complex case, you should not rely on getting anything consistent really.

I would say we should not make less efficient the general case just to return consistent values at zero... wdyt @soulitzer @albanD

**Comment by albanD** [comment]
@Lezcano do we want to make it inf to be closer to the real case?

**Comment by Lezcano** [comment]
After looking closer, this is not an issue wiht the backward, but with `pow` itself. Even more, it is an issue with `std::pow` (which is what we're using here). It turns out that [`std::pow` for fp ](https://en.cppreference.com/w/cpp/numeric/math/pow) and [`std::pow` for complex](https://en.cppreference.com/w/cpp/numeric/complex/pow) are defined differently (perhaps unsurprisingly, but yeah). It looks like for negative exponents, for real inputs it returns inf, and for complex inputs it returns nans. Note that this is a reasonable behaviour as per the discussion above.

I'd vote no-fix, as this is a behaviour inherited from the STL.

**Comment by Lezcano** [comment]
Closing as this is inherited from C++.

Small repro in PyTorch:
```python
import torch
print(torch.tensor([0.j]).pow(-1/2))
print(torch.tensor([0.]).pow(-1/2))
```

small repro in C++
````c++
#include <complex>
#include <cmath>
#include <iostream>

int main() {
    std::cout << std::pow(0, -.5) << std::endl;
    std::cout << std::pow(std::complex<float>(0., 0.), -.5) << std::endl;
}
```
