### ISSUE TITLE
Explore add NestedTensors to CompositeImplicitAutograd / CompositeExplicitAutograd dispatches

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#79048]
This key was removed for these dispatches for this comment:
https://github.com/pytorch/pytorch/blob/ebb7f424b82d5b19d995e98ba7166a197c75fb59/c10/core/DispatchKeySet.cpp#L17-L21

Once autograd has been implemented for NestedTensor explore removing this restriction.

### Updates:

cc @cpuhrsch

**Comment by bdhirsh** [comment]
If we want to do this, I think the way to opt them into composite kernels would be:

`CompositeExplicitAutograd`: **[here](https://github.com/pytorch/pytorch/blob/0be9df4e852c0216a1de749551f16affddb63335/c10/core/DispatchKeySet.cpp#L22)**

`CompositeImplicitAutograd`: [here](https://github.com/pytorch/pytorch/blob/0be9df4e852c0216a1de749551f16affddb63335/c10/core/DispatchKeySet.cpp#L28)

It seems like the `CompositeExplicitAutograd` kernels were not re-used on purpose, so that might require more investigation. If we want to re-use `CompositeImplicitAutograd` kernels that should be doable.

**Comment by drisspg** [comment]
Update here: https://github.com/pytorch/pytorch/pull/80396 this PR updated nested tensors to use the AutogradNested key. As well it made updates so that CompositeImplicitAutograd kernels can work with nested tensors. It kept the restriction on CompositeExplicitKernels.

**Comment by drisspg** [comment]
I am closing this since there has been a lot of work here. Composite implicit kernels have been enabled for Nested Tensors. Composite explicit remains disabled.
