### ISSUE TITLE
CUDA 9.2 CI setup

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#7913]
We're not testing against CUDA 9.2 and we should. C.f. #7880

We should test against GCC 7 (because this is how Anaconda is building the packages), AND we should use test with this in OS X, because CUDA 9.2 now supports the default xcode shipped on OS X.

**Comment by wuz93308** [comment]
Building PyTorch with CUDA 9.2 for 7.0 compute compatibility devices produces quite worrisome warnings:

warning : Instruction 'vote' without '.sync' may produce unpredictable results on sm_70 and later architectures
warning : Instruction 'vote' without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued in a future PTX ISA version

warning : Instruction 'shfl' without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued in a future PTX ISA version
warning : Instruction 'shfl' without '.sync' may produce unpredictable results on sm_70 and later architectures

**Comment by yf225** [comment]
CUDA 9.2 CI on macOS is done in https://github.com/pytorch/pytorch/pull/8274
