### ISSUE TITLE
lite interpreted model performs differently in Python and Android

### ISSUE THREAD

**Issue by datu925** [pytorch/pytorch#79791]
### 🐛 Describe the bug

This may be expected, but I haven't seen it documented anywhere. I have an NLP model that produces sentence embeddings, and I want to use it in an Android app. Based on PyTorch Mobile tutorials, I'm saving it like this:

```python
traced_model = torch.jit.trace(model, example_tokens, strict=False)
optimized_model = optimize_for_mobile(traced_model)
optimized_model._save_for_lite_interpreter("qa_model.ptl")
```

Then loading in Android (Kotlin) with:
```kotlin
import org.pytorch.LiteModuleLoader

module = LiteModuleLoader.load(assetFilePath(context, model_file))
```

What's interesting is that the models in Python and Android perform slightly differently. Inspecting some of the embeddings for the same input, I've seen that the tokens passed to the model are identical. But then the resulting embeddings will be slightly different – for instance, one coefficient will be 0.016352959 and the other will be 0.016352937. Because I'm using these embeddings to retrieve answers based on cosine similarity, it causes a different answer to be retrieved about 10% of the time for my data.

I am trying to figure out if this is an unavoidable consequence of using TorchScript or the lite interpreter, or if this is something that I can better control.

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.31.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.2 (default, Aug 10 2020, 05:49:21)  [Clang 12.0.0 (clang-1200.0.31.1)] (64-bit runtime)
Python platform: macOS-12.4-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect

**Comment by datu925** [comment]
An important clarification: I tried this without the `optimize_for_mobile` call, and still found the same effect, so this isn't explained by that.

**Comment by axitkhurana** [comment]
cc @kimishpatel

**Comment by cccclai** [comment]
There is Python api `_load_for_lite_interpreter`. Is it the api you used in Python?

**Comment by datu925** [comment]
Ah, it wasn't. I was just using the model as loaded normally. So if I use `_load_for_lite_interpreter`, I should expect to get the same results in Python and Android?

**Comment by kimishpatel** [comment]
Is this just embedding lookup or some other subsequent op that consumes it? Generally each hardware is slightly different so cpus on phone may give slightly different result compared to cpu on say laptop or server due to some hardware differences combined with compiler optimizations that result in compiling code to utilize some instruction for performance reasons. Things like this show up in rounding differences or when the FP multiply adds are done using fused multiply add versus separate mul + add. So small differences are expected. This is a generic answer so I dont know if this can explain entirely the difference you see. However the values are pretty close.

It is unfurtunate that it causes such large difference in the end result. I wonder if training of the model should account for this somehow? That is enough margin is accounted for such that you dont need errors which are within 1e-9 bound but which may work with 1e-6 bound for example. Again very high level ideas.

Separate question. Is this model quantized?

**Comment by datu925** [comment]
While I still see the small differences in embedding values, the fact that it created some much variance in model outcomes was due to a flaw in our preprocessing flow that was leaving some near duplicate inputs in the dataset. After fixing that, we can get consistent outcomes from the on-device and online models.

Given that, I am going to close this, as the small differences in embedding values are probably due to low-level computation differences in the underlying platform and won't easily be addressed.
