### ISSUE TITLE
np.repeat vs torch.repeat

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#7993]
## Issue description

Numpy repeat and torch repeat have fundamentally different default behaviors. This was unexpected to me. This may be unexpected to other people. For me, this failed silently in my model, welp. 

numpy.repeat [1, 2, 3]  → [1, 1, 2, 2, 3, 3] 
torch.repeat [1, 2, 3] →  [1, 2, 3, 1, 2, 3]

I think it'd be nice to either change the default behavior or to add to the documentation a warning.

**Comment by zou3519** [comment]
Easiest thing to do for now is to add a warning to the docs. One day we'll probably re-visit the all the differences between the Numpy API and pytorch API, but for now, just changing repeat might be disruptive to our users.

Feel free to submit a pull request @PetrochukM (otherwise, I can submit one).

**Comment by Ir1d** [comment]
Btw, I found [this](https://github.com/wkentaro/pytorch-for-numpy-users), which contains some comparisons of the APIs.
