### ISSUE TITLE
[Bug] D2H copy with a different dtype is pageable even with non_blocking=True

### ISSUE THREAD

**Issue by yaox12** [pytorch/pytorch#79933]
### 🐛 Describe the bug

Copying a tensor from device to host with a different dtype is always pageable even with `non_blocking=True`.

```python
import torch

t = torch.zeros((1000000, 100), dtype=torch.float32, device=torch.device('cuda:0'))
cpu = torch.device('cpu')

t.to(cpu, non_blocking=True)  # this is correctly to pinned memory

t.to(cpu, dtype=torch.float16, non_blocking=True)  # this will copy the tensor to pageable memory

t.to(dtype=torch.float16).to(cpu, non_blocking=True)  # this will correctly copy the tensor in fp16 to pinned memory.
```

![image](https://user-images.githubusercontent.com/3831900/174734763-e206966f-b0f3-479e-8449-cb908ee30945.png)

### Versions

PyTorch version: 1.12.0a0+8a1a93a
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-81-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration:
GPU 0: Tesla V100-SXM3-32GB

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @ngimel

**Comment by ptrblck** [comment]
I don't think this is a bug but expected behavior.

Each approach will call into [`r.copy_(self, non_blocking)`](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L232) in `_to_copy` and eventually into [`copy_kernel_cuda`](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L160).

### First operation 
(`t.to(cpu, non_blocking=True)`)

The first operation uses the same `dtype` in the `CUDATensor` as in the resulting `CPUTensor` and will thus call into [`cudaMemcpyAsync`](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L232) without failing any checks in this method.

### Third operation
(`t.to(dtype=torch.float16).to(cpu, non_blocking=True)`)

The third operation will execute a similar code path, but will execute `copy_kernel_cuda` twice:
* the first time to transform the `CUDATensor` into `float16` via `copy_device_to_device` 
* and the second time to move it to the CPU (same execution as in case 1).

### Second operation
(`t.to(cpu, dtype=torch.float16, non_blocking=True)`)

The second operation, however, mixes the `dtypes` (`float32` on the GPU and `float16` on the CPU).
This call will require a temporary copy from [here](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L169-L205) as none of [these conditions](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L129-L151) are met (different `device`, different `dtype`, no p2p copy).
Since the destination device is the CPU [this `else` branch](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L181-L185) will then be executed and since also the `dtypes` are different `dst_contig` will be created via:
```
dst_contig = (dst.is_contiguous() && same_type) ? dst : at::empty_like(dst, iter.dtype(1), LEGACY_CONTIGUOUS_MEMORY_FORMAT);
```
which is not pinned.
Note that the `iter.dtype(1)` is used to create `dst_contig` on the CPU which is the `src.dtype()`, so `float32`.
[This line](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L197) will copy the `float32` `CUDATensor` to the no-pinned `float32` `CPUTensor` via `cudaMemcpyAsync` which will use the pageable memory (visible in the profile output).
After returning from this call, [this additional copy](https://github.com/pytorch/pytorch/blob/08820cb030927200c92733436f454f5fcf19c6bd/aten/src/ATen/native/cuda/Copy.cu#L199-L203) is executed, which will copy the `float32` `CPUTensor` to the `float16` `CPUTensor` destination.

My assumption is that the temp. tensor is created as a non-pinned tensor to avoid wasting pinned memory for it (potentially in a larger `dtype` as in this case), but @ngimel can correct me if I'm missing something.

**Comment by yaox12** [comment]
Thanks, @ptrblck, very detailed explanation! We should probably leave a note in the [documentation](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) or give a warning when non_blocking is not available. For now, it's really confusing operation 2 is much slower than operation 1 and 3.

**Comment by ptrblck** [comment]
@ngimel Yes, that sounds like a great idea! Let me sync with @Aidyn-A

**Comment by Aidyn-A** [comment]
Sure @ngimel and @ptrblck, 
I will take care of it.
