### ISSUE TITLE
[ci] Linux Docs is Running out of Memory (exit code 137)

### ISSUE THREAD

**Issue by zengk95** [pytorch/pytorch#79992]
### 🐛 Describe the bug

Linux doc is randomly failing within trunk and pr with OOM errors/exit code 137. 

Exampes:
https://hud.pytorch.org/pytorch/pytorch/commit/eff74ed7bdb97693535c202a669bc24dbd124641
https://hud.pytorch.org/pytorch/pytorch/commit/f5d7e5a19293c231610147b70ecbc8e705d93bf3
https://hud.pytorch.org/pytorch/pytorch/commit/73f6601cfcd9b869dde5613ab9c8aec2da28527b
https://hud.pytorch.org/pytorch/pytorch/commit/399b3dcac64917b6d49f1f7e7ba47fa29165b4b0

### Versions

n/a

cc @ezyang @gchanan @zou3519 @svekars @holly1238 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by zengk95** [comment]
cc @janeyx99 @malfet @kit1980 @seemethere

**Comment by suo** [comment]
@jbschlosser: I've been told you are the closest thing the cpp frontend has to an owner 😛. 

Currently, the docs build that generates the cpp docs is flaky due to intermittent ooms. We are disabling the build on PRs and running it nightly-only for now, but this is obviously a bad situation as someone could break the build.

Can you own the investigation/resolution for this issue?

**Comment by mruberry** [comment]
Offline discussion: 

- fixing the job is an option, but it may be preferable to disable autogeneration and preserve the useful part of the docs, directing people to the actual comments associated with function implementations to best use the C++ docs
- we should message the change to C++ docs in 1.13 (if we do something)
- check with @svekars before taking any action
- short-term fix would be to disable doxygen generation

**Comment by suo** [comment]
@mruberry that sounds good to me. Is @jbschlosser still the right owner to drive this forward?

**Comment by jbschlosser** [comment]
@suo Yep, I'll take it on
