### ISSUE TITLE
failed to move parameters to GPU

### ISSUE THREAD

**Issue by wizardk** [pytorch/pytorch#8017]
## Issue description

initialize the layers of model in loop cause parameters of layers are failed to move to GPU by Module.to() or Module.cuda() method.

## Code example

```
class Model(nn.Module):
    def __init__(self, in_channels, out_channels, layer_size):
        super(Model, self).__init__()
        self.conv = []
        for idx in range(layer_size):
            self.conv.append(nn.Conv2d(in_channels=in_channels, out_channels=out_channels,kernel_size=(3,3)))
            in_channels = out_channels
            out_channels *= 2

    def forward(self, x):
        for conv in self.conv:
            x = conv(x)
        return x

model = Model(in_channels=1, out_channels=16, layer_size=3).to(torch.device("cuda"))
assert model.conv[0].weight.is_cuda
```

## System Info

- OS: Windows 10
- PyTorch version: 0.4.0
- Python version: 3.6.4
- CUDA/cuDNN version: 9.1.85, no cuDNN

**Comment by zou3519** [comment]
The main problem here is that this code is not registering the conv `nn.Modules` correctly as submodules of `Model`. You can check this by verifying that `model.parameters()` is an empty list.

To fix this, you should set `self.conv` equal to a `nn.Sequential` instead of setting `self.conv = []`. Docs for nn.Sequential can be found here: https://pytorch.org/docs/master/nn.html?highlight=sequential#torch.nn.Sequential

**Comment by soumith** [comment]
or make self.conv = nn.ModuleList()
