### ISSUE TITLE
[ONNX] Exported model errors when executed with onnxruntime

### ISSUE THREAD

**Issue by zhang0557kui** [pytorch/pytorch#80500]
### 🐛 Describe the bug

我使用torch.onnx.export(model, x, 'model.onnx', input_names=input_names, output_names=output_names, verbose='True', opset_version=16)将pytorch模型转成onnx，pytorch版本为1.12.0GPU版，使用opset_version=16，转换过程出现如下提醒：
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.

使用onnxruntime验证onnx模型时，报错：
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Expand_627) Op (Expand) [ShapeInferenceError] Incompatible dimensions

### Versions

python 3.8
pytorch 1.12.0 （GPU）
onnxruntime 1.11.1
onnx 1.12.0

**Comment by malfet** [comment]
More details are needed to debug a problem. Also, please note that issue discussions are usually conducted in English

**Comment by justinchuby** [comment]
The warning you mentioned is a relatively common warning that does not often lead to errors. It would be helpful if you can share a self contained script that can reproduce the error you saw.

**Comment by shubhambhokare1** [comment]
Hi @zhang0557kui,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
