### ISSUE TITLE
Support layout conversions via `Tensor.to(...)`

### ISSUE THREAD

**Issue by amjames** [pytorch/pytorch#80542]
### 🚀 The feature, motivation and pitch

The general conversion utility `Tensor.to(...)` supports modification of all other tensor option fields except layout. This is a natural extension, and the lack of it will be felt more deeply as support for sparse layouts grows. In particular functions supporting sparse output generally accept an optional `layout` argument and contain the following pattern:

```c++
//Perform necessary steps to build the output in a `sparse_coo` representation
...
auto result_coo = at::sparse_coo_tensor(indices, values, shape);
if (layout) {
  if (*layout == Layout::SparseCsr) {
    return result_coo.to_sparse_csr();
  }
  if (*layout == Layout::SparseCsc) {
    return result_coo.to_sparse_csc();
  }
  ...
}
return result_coo;
```

This would simplify to:

```C++
//Perform necessary steps to build the output in a `sparse_coo` representation
...
auto result_coo = at::sparse_coo_tensor(indices, values, shape);
if (layout){
  return result_coo.to(*layout);
}
```

### Additional context

Block sparse Layouts (BSR/BSC) require an additional block size parameter in order to perform the conversion. See related #80549

cc @nikitaved @pearu @cpuhrsch @amjames

**Comment by cpuhrsch** [comment]
We can build a helper function within say [SparseTensorUtils.h](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/SparseTensorUtils.h) to alleviate the code complexity at least within our kernel authoring, but as you point out in #80549 we need some kind of innovation to extend `to` to be able to handle additional parameters as required by say BSR.

**Comment by pearu** [comment]
As a data point for prioritization of this issue, there exist numerous places where this issue is worked around by unnecessarily verbose code, for instance,
- https://github.com/pytorch/pytorch/pull/85268
- https://github.com/pytorch/pytorch/pull/86137/files#r986737270
- https://github.com/pytorch/pytorch/blob/a75edfa97c9d985a337fbea7b9c0f4061153aaf0/test/test_sparse_csr.py#L100-L107
- https://github.com/pytorch/pytorch/blob/a75edfa97c9d985a337fbea7b9c0f4061153aaf0/aten/src/ATen/native/sparse/SparseFactories.cpp#L85-L90

**Comment by pearu** [comment]
Ref: https://github.com/pytorch/pytorch/issues/84265

**Comment by cpuhrsch** [comment]
We could extend `to_sparse` with kwarg-only arguments that take in a layout and block size. 

`to_sparse()` -> COO
`to_sparse(layout=torch.sparse_csr)` -> CSR
`to_sparse(layout=torch.sparse_csr, block_size=(2, 2))` -> failure
`to_sparse(layout=torch.spasre_bsc, block_size(2, 2))` -> BSR with 2x2 blocks

That way we'd have a unified API for conversions to the sparse layouts.

**Comment by cpuhrsch** [comment]
@pearu - Yes, the only downside of `to_layout` is that we have to introduce another native function and also make it work for layouts unrelated to sparsity. The upside is a unified API. Maybe we can start with `to_sparse`, since torch.sparse covers that function entirely, and created a unified API on our end and then eventually introduce a `to_layout` that works for everything else as well.

**Comment by pearu** [comment]
The need to support all layouts in `to_layout` makes sense and that would require more than needed to resolve the origin of this issue: have a unified API to convert in between sparse (as well as strided) layouts.

If we start with `to_sparse` (that would be already very helpful to simplify codes), we could also support `to_sparse(layout=torch.strided) -> strided` for convenience, even though it reads weird.

**Comment by cpuhrsch** [comment]
@amjames @pearu for conversions to the `strided` layout I suggest we stick to `to_dense`. Both `to_dense` and `to_sparse` are already native functions, so we can use them to refactor our code. We can also still add coverage for say BSR to [`to.dtype_layout`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L6650), we'll just need to pick a default block size. scipy has heuristics to detect an optimal block size, but I suggest we set it to say `(32, 32)` by default and tell users to use `to_sparse` for more fine-grained control. That way users can easily make use for BSR via `to(layout=torch.sparse_bsr)`, but when fine-tuning for performance they can use `to_sparse`.

**Comment by cpuhrsch** [comment]
The reason I suggest we use `to_dense` instead of adding `strided` support to `to_sparse` is to avoid catastrophic materialization of memory. We want to make sure the user is very aware that they're about to say ~20x (at 95% sparsity) their memory footprint and not have that be a mistake. OOM is difficult to debug.

**Comment by pearu** [comment]
Apparently, `to.dtype_layout` is not effective in Python size, see https://github.com/pytorch/pytorch/issues/84265 .

Re `x.to(layout=torch.sparse_bsr)`, there exists two trivial blocksize cases that are always valid: `blocksize=(1, 1)` and `blocksize=x.shape`. That said, I'd personally prefer using `to_sparse(...)` rather than `to(...)` for BSR/BSC formats. In fact, implementing `to(layout=torch.sparse_bsr)` does not sound better to me than not implementing the layout support in `to(...)` at all because the default blocksize `(32, 32)` is generally useless unless the dimensions of the input tensor are 32 multiple.

**Comment by cpuhrsch** [comment]
@pearu - ok then let's error out if the users tries `to(layout=torch.sparse_bsr)` and mention `to_sparse` as the API. 

Using `(32, 32)` as a default might not work for every shape (like `(1, 1)` would), but the resulting Tensor is more likely to actually be performant in the cases that BSR shines (i.e. highly structured sparsity). It could serve as an entry point to the BSR topic overall and aid discoverability. I'm ok with referring to `to_sparse` right away as well, instead of delaying the discover with some potentially ill-chosen block size.

**Comment by pearu** [comment]
Closing via #89502 .
