### ISSUE TITLE
PyTorch 1.12 cu113 wheels cudnn discoverability issue

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#80637]
```
import torch
torch.backends.cudnn.version()
```

gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/rzou/local/miniconda3/envs/py38/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py", line 50, in version
    if not _init():
  File "/private/home/rzou/local/miniconda3/envs/py38/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py", line 39, in _init
    raise RuntimeError(
RuntimeError: cuDNN version incompatibility: PyTorch was compiled against (8, 3, 2) but linked against (8, 0, 3)
```
LD_LIBRARY_PATH:
```
(py38) [0] rzou@devfair0317:~/binaries_test  $ echo $LD_LIBRARY_PATH
/public/apps/cudnn/v8.0.3.33-cuda.11.0/cuda/lib64:/public/apps/cuda/11.0/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64::/public/slurm/20.11.8/lib:/public/slurm/20.11.8/lib
```
Pytorch installed via:
```
 pip3 install torch --extra-index-url https://download.pytorch.org/whl/cu113
 ```

cc @ezyang @seemethere @malfet

**Comment by atalman** [comment]
Here are my findings:
The -rpath command line option used to create a DT_RPATH entry in the .dynamic section, but since DT_RPATH was deprecated in favor of DT_RUNPATH, modern linker versions use DT_RUNPATH instead. This means that using -rpath on a really old linker, you will create a dynamic section entry with .d_val = DT_RPATH, but if your linker is up to date, you will create one with .d_val = DT_RUNPATH instead.

We do set DT_RUNPATH in our binaries using patchelf: https://github.com/pytorch/builder/blob/main/manywheel/build_common.sh#L358

However according to a manual: https://man7.org/linux/man-pages/man8/ld.so.8.html 
LD_LIBRARY_PATH takes precedence and hence  libraries on that path loaded before the ones specified in rpath

**Comment by atalman** [comment]
Looks like the same affects libcublas:

```
libcublas.so.11 => /usr/local/cuda/lib64/libcublas.so.11 (0x00007fe8121b0000)
libcublasLt.so.11 => /usr/local/cuda/lib64/libcublasLt.so.11 (0x00007fe7fd362000)
```

**Comment by atalman** [comment]
Closing this issue as wording is addressed

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/issues/78489 is the issue for https://github.com/pytorch/pytorch/issues/78489, right? we can use that issue to track reporting the cudnn version the user has installed
