### ISSUE TITLE
[feature request] support a `set` of indexes

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#8083]
```
In [76]: x = th.zeros(5)

In [77]: x[{2,3}]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-77-f60b906fb972> in <module>()
----> 1 x[{2,3}]

IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got set)

In [78]: th.__version__
Out[78]: '0.4.0'
```

**Comment by apaszke** [comment]
I don't think we should do this, because sets don't have any ordering guarantees, and as such the result you'd get from an expression like this would differ all the time (or at least between Python processes). If you really don't care about the ordering, just do `list(s)` before you index the tensor.

**Comment by CDLuminate** [comment]
The ordering doesn't matter when assigning a constant to several locations of a tensor. I agree that this shouldn't be done due to reproducibility in some cases.

**Comment by apaszke** [comment]
Well it doesn't matter *sometimes*, which is when all of those slices get assigned the same value, but if you were to assign a tensor of size equal to that of the resulting slice, then you'd have few guarantees about the ordering of the resulting values.
