### ISSUE TITLE
Modifying the source code

### ISSUE THREAD

**Issue by Vishesh20155** [pytorch/pytorch#81627]
I have been trying to make some changes in the source code of PyTorch library, particularly in aten/src files.

I want to modify the files on a Linux system.

## Issue description

I had downloaded the Pytorch Library from source code.
I have made made the changes in the .cpp files, particularly, I have added a few printf() statements and then I build using `python3 setup.py develop` .  The source code gets built but on running the Pytorch code, I am unable to see the anything from the printf()'s I added.

Any help would be appreciated.

**Comment by Lezcano** [comment]
That should work. If those `printf`s didn't fire it's because that code didn't run. That can be because your code didn't exercise that path, or because you are not using the version of PyTorch you just compiled (you may be using one installed from pip or conda).

In any case, the right place to discuss these points is the forum: https://discuss.pytorch.org/

**Comment by Lezcano** [comment]
Consider debugging your program for example with `gdb`. But again, the right place to discuss these points is the forums.
