### ISSUE TITLE
Issue with FSDP memory reduction scaling up GPUs

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/pytorch#82001]
### 🐛 Describe the bug

We are running FSDP with HuggingFace T5- 3B model using the transformer wrapping policy and mixed precision (BF16) with A100 gpus. Scaling up GPUs, by extending to multi nodes (each node has 8 gpus),  we are expecting to have smaller shard on each and overall proportional memory reduction. However, we see that the reserved memory for between 1-4 nodes does not change very much, whereas the allocated memory reduces to almost half. 

Revered memory has been captured using "torch.cuda.memory_reserved()" and allocated memory using "torch.cuda.memory_allocated()". 

As shown in the table below, the reserved memory on 1 node is ~ 28Gb --> 2 nodes ~ 26Gb -->3 nodes ~25Gb--> 4 nodes ~24Gb. 

<img width="928" alt="Screen Shot 2022-07-22 at 10 26 31 AM" src="https://user-images.githubusercontent.com/9162336/180493904-ea87e26a-0101-475e-b7c5-c20fde079c5e.png">

This is the same pattern for TF32 and FP32 where the memory reduction by extending nodes is even less (table below).

<img width="921" alt="Screen Shot 2022-07-19 at 12 58 11 PM" src="https://user-images.githubusercontent.com/9162336/180493956-82b53719-6a66-4a25-a5b4-59fbc2896708.png">

This results in OOM when training T5, 11B model, as the memory reduction is not happening as expected. It would be great to narrow down the root cause if this is due to the transformer wrapping policy or other design choices in FSDP. 

[Code to repro](https://github.com/lessw2020/t5_11/blob/main/main_benchmark.py).

### Versions

PyTorch Nightlies

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @ezyang

**Comment by awgu** [comment]
I think active memory is the appropriate stat to track over allocated memory due to the multiple stream usage in FSDP. Nonetheless, the rate limiter should help with this issue: https://github.com/pytorch/pytorch/pull/83917 I will close this for now, and we can open a new issue if there are similar issues even with the limiter enabled.

The limiter targets the high active memory and high reserved memory case and can bring those values down. However, if the workload has low active memory and high reserved memory, then it suffers from fragmentation, which the rate limiter cannot help on the first order.
