### ISSUE TITLE
frombuffer() returns oversized tensors when multiprocessing

### ISSUE THREAD

**Issue by kajomano** [pytorch/pytorch#82059]
### 🐛 Describe the bug

Hi,

I am trying to use torch.frombuffer() using a shared_memory buffer with multiprocessing. The function seems to work fine in the main process, but allocates oversized tensors when invoked in the child process:

```
import torch

import multiprocessing as mp
from multiprocessing import shared_memory

def printShape(shm):
    tensor = torch.frombuffer(shm.buf, dtype = torch.float32)
    print(tensor)
    print(tensor.shape)

if __name__ == '__main__':
    test_array = torch.tensor([1, 2, 3], dtype = torch.float32)
    test_shm   = shared_memory.SharedMemory(create = True, size = test_array.element_size() * test_array.numel())
    torch.frombuffer(test_shm.buf, dtype = torch.float32).copy_(test_array)

    printShape(test_shm)

    p = mp.Process(target = printShape, args = (test_shm,))
    p.start()
    p.join()

# Output:
# tensor([1., 2., 3.])
# torch.Size([3])
# tensor([1., 2., 3.,  ..., 0., 0., 0.])
# torch.Size([1024])
```

This only happens with tensors smaller than a certain size (1024?), large tensors have correct sizes.

### Versions

PyTorch version: 1.12.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] Could not collect

cc @VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
Can you also print size of the buffer:

```python
def printShape(shm):
    tensor = torch.frombuffer(shm.buf, dtype = torch.float32)
    print(len(shm.buf))
    print(tensor)
    print(tensor.shape)
```

As per python documentation https://docs.python.org/3/library/multiprocessing.shared_memory.html#multiprocessing.shared_memory.SharedMemory

"size specifies the requested number of bytes when creating a new shared memory block. Because some platforms choose to allocate chunks of memory based upon that platform’s memory page size, the exact size of the shared memory block may be larger or equal to the size requested. When attaching to an existing shared memory block, the size parameter is ignored."

Meaning your buffer can be larger than you think and you also need to pass real tensor size.
