### ISSUE TITLE
Custom functions and custom modules.

### ISSUE THREAD

**Issue by yjxiong** [pytorch/pytorch#821]
I tried writing a custom op and defining a module to wrap it. However, I came across a tedious problem which I feel useful to document here and provide some suggestions.

I started with a custom op that does very simple reduction as follows
```Python
import torch

class MyFunction(torch.nn.Function):
	def forward(self, input):
		self.shape = input.size()
		return input.mean(dim=1)
	def backward(self, grad_out):
		return grad_out.expand(self.shape) / float(self.shape[1])

class MyModule(torch.nn.Module):
	def __init__(self):
		self.op = MyFunction()

	def forward(self, input):
		return self.op(input)         
```

There you may have noticed that I have made a mistake by saving the instance in the module, provided you have read the documentation carefully and found this line

> Each function is meant to be used only once (in the forward pass). 

at http://pytorch.org/docs/autograd.html#function

However, the above snippet ran without any problem in my model under the single GPU mode, i.e. when no `torch.nn.DataParallel` is used.

When I started adding `DataParallel` to my model, the nightmare began. Pytorch repeatedly threw error like this

```
RuntimeError: arguments are located on different GPUs at ...
```
Once I remove the `DataParallel` module, the model can run smoothly.

Since this error happens in the C++ side, there is no stack trace to help debug this problem. I got no clue which arguments lead to the error and had to doubt whether it is a bug in the `DataParallel` module.

After spending a lot of time digging into the sources of `DataParallel` and even `THC` , I finally realized the mistake I made. So I changed the code to

```Python
import torch

class MyFunction(torch.nn.Function):
	def forward(self, input):
		self.shape = input.size()
		return input.mean(dim=1)
	def backward(self, grad_out):
		return grad_out.expand(self.shape) / float(self.shape[1])

class MyModule(torch.nn.Module):
	
	def forward(self, input):
		return MyFunction()(input)
```
Then everything began to work as expected.

I have a few comments afterward:
1. If it is bound to fail in the multi-GPU situation, maybe we should also let it fail in the single GPU case.
2. The mentioned line in the Doc should state this clearly that if we reuse a `Function` instance there might be some serious problem.
3. One step further, if an instance of `Function` is meant to be used only once, how about integrating it into the extension mechanism? This may potentially protect many new users from facing this kind of problems.

After all, thanks to the team for developing this awesome toolbox!

P.S. I apologize if you feel uncomfortable about the tab indent in the code snippet.

**Comment by soumith** [comment]
thanks a lot for your detailed feedback. we'll discuss this and take a direction that'll make the experience more user-friendly, either with better error messages, or with (1)

**Comment by chauhan-utk** [comment]
This is exactly what I had been facing. The stack trace is not at all helpful for a beginner/novice. I stumbled upon this issue by chance, and could not find any help when I searched for the issue.

**Comment by liyangliu** [comment]
@yjxiong Thanks for your post. I am facing a similar problem. I wonder whether it is OK to save a submodule instead of a function as follows:

import torch

class MySubModule(torch.nn.Module):
	def forward(self, input):
		self.shape = input.size()
		return input.mean(dim=1)

class MyModule(torch.nn.Module):
	def __init__(self):
		self.op = MySubModule()

	def forward(self, input):
		return self.op(input)

My code is something like above because I have some parameters in MySubModule so I have to save a instance of it and reuse the instance. But I also got the error:

RuntimeError: arguments are located on different GPUs at THCTensorMathBlas.cu.

Would you please give me some help? Thanks.

**Comment by LingxiaoShawn** [comment]
Can anyone explain why pytorch is designed to use new function object every time? 
What if I have some data want saved in function initialization? 
I think put that data inside class __init__, and use the same function object all the time can be much cleaner.

**Comment by yjxiong** [comment]
I guess Function is a pure operator without any internal state. Any data should be fed as input to it. If you want to save some state information you can make a module that saves the state data and give that as input to the function object.

**Comment by LingxiaoShawn** [comment]
@yjxiong Thank you for your quick response. However, I can't use module since I want to define my own backward gradient. And module is mostly for neural network operation, I'm coding a normal function that based on pytorch tensor. And if the problem is happened only with parallel setting, maybe we can use as that way right, in single GPU?

**Comment by yjxiong** [comment]
You can code your bp in your Function and make a Module to use that function. This is the standard pattern you can find in Pytorch tutorials.

**Comment by LingxiaoShawn** [comment]
@yjxiong Let say that I want to wrap a decision tree as a function, then I need to access the tree data in order to define the function. So my problem is that define the Function need to access the data. I guess that I should try put it into init first, and use the same function object all the time. I'm not sure if this is the right way to do that but I will try first to say if it will have error.  

And I guess the old style of extending function can save data in init function. But currently the new style approach of extending function only support put everything as input into forward method. I don't understand the design style. I hope someone can give out the advantage for this new approach.

**Comment by LingxiaoShawn** [comment]
https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/thnn/normalization.py

**Comment by apaszke** [comment]
@yjxiong is right. Functions are meant to be short lived (one application max!). Since this came out we've actually changed how functions work to make it clearer (`forward` and `backward` are now static methods), so this should be resolved now.

**Comment by LuteceSong** [comment]
is that real we can not use __init__ even on the module when we want to use multiGPU? is this problem fixed now?
