### ISSUE TITLE
Please don't move tags once released

### ISSUE THREAD

**Issue by ccoulombe** [pytorch/pytorch#8268]
When you tag a version, please do not move it afterwards. For example, the `v0.4.0` commit was initially on April 24 and the last commit ([3749c58](https://github.com/pytorch/pytorch/commit/3749c581b79cba49f511b19fa02c0f50fa05b250)) is now a few days ago. This is a nightmare to follow when building wheels.

Instead, make a new release by updating the minor release number or stack commits and release them in another version. Users can then refer to a specific version when they have issues. This also make issues less difficult to reproduce.

I cannot stress enough how important this is for everyone following `pytorch`. 

You can see a similar discussion on Tensorflow here : https://github.com/tensorflow/tensorflow/issues/18424

Citing @boegel :
> I know it can be very tempting to just quickly include another minor change and replacing the tag (probably assuming that nobody will notice), but it's really bad practice, especially for a popular project like TensorFlow (where you can be damned sure somebody will suffer from doing this).
Note that PyPI hard prevents you from doing this, if you would have pushed any pip packages there for the initial release, you would have been forced to do another point release (and rightfully so).

Tagging @soumith

**Comment by soumith** [comment]
the tag stopped working because the eigen mirror on github moved (it was one of the submodules).


Hence we were forced to re-tag.

Ironically, we had to re-tag because folks could no longer build wheels on that tag.

See this for context: https://github.com/pytorch/pytorch/issues/7793

**Comment by tgamblin** [comment]
@soumith: Submodules are a convenience for developers who are using git, but they probably shouldn't even be in a release tarball, specifically for the reasons you mention above.  They're pointers to your dependencies, but they're brittle -- a URL and a commit, where the URL might change.

People packaging your code (e.g. in [spack](https://github.com/spack/spack) or [easybuild](https://github.com/easybuilders/easybuild)) may not even use your submodules to build your code -- we typically get the dependencies by installing *their* packages.  Does your build system rely on dependencies built from submodules?  It seems like if you are building a wheel, you should rely on your dependencies *built as wheels*.  Is that not possible in this case (e.g., b/c eigen is vendored)?

Seems like in this case you could, if you must, just issue a patch release with the updated submodules.  This would make things easier on the poor packagers who have to keep up with changing checksums.  Or, even better, just don't consider the submodules part of the release.  It's the installer or packager's job to get eigen -- it doesn't have to affect release hashes.  The old version might not build with a git checkout, but package managers can likely still install it as *they* still know how to install the dependencies.

**Comment by boegel** [comment]
Very much +1 on not changing existing tags, for whatever reason.

The proper way to deal with this would have been to create a new tag with a (sub)minor version increase like `0.4.1` or `0.4.0.1`.

Changing an existing tag does more harm than good, even if the existing tag doesn't work anymore: it creates a lot of confusion all around the world, since people that checksum things may suddenly wonder why stuff changed upstream. It's quite frustrating...

As @tgamblin mentioned, I hope tagging commits isn't the only way of releasing PyTorch: you should also create source tarballs that don't require `git` at all (for example by including a `git clone` of the submodules in it, if you must).

Orthogonal to this issue: please make sure we can provide the required dependencies some other way, don't force us to deal with git submodules... They make sense for developers of software, not for packagers of the software.

It's a bit ironic that `PyTorch` is making the same mistake as `TensorFlow` was a while ago (see https://github.com/tensorflow/tensorflow/issues/18424 already referenced by @ccoulombe).

Can't resist: see https://www.youtube.com/watch?v=NSemlYagjIU for more ideas on how to make package managers cry.

**Comment by soumith** [comment]
thanks a lot for the feedback folks.
We'll try provide source tarballs from the next release. And sure, we will bump up the minor.minor version if I have to fix the git tag itself.
