### ISSUE TITLE
Pytorchbot should offer a workaround when it doesn't have access to a remote repository

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#82691]
### 🚀 The feature, motivation and pitch

This issue came up when AMD wanted to use pytorchbot to rebase a PR, only to discover that the bot [couldn't access their private pytorch branch](https://github.com/pytorch/pytorch/pull/80410#issuecomment-1201791762). 

However, there is a known workaround for this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

When pytorchbot gets a permission denied error when it tries to rebase, it should leave a message pointing the dev to the above link so that they can give pytorchbot the permissions needed to edit the branch.

**Comment by malfet** [comment]
IMO this will make system unnecessarily complex.
Instead merge bot should just check, if PR is for a fork pull request and offer an instruction how one can do it on their own.

**Comment by clee2000** [comment]
I am going to close this as the reason rebase bot doesn't work specifically for AMD is because they have more restrictive permissions for their org.  Rebasing on forks should work, and PRs automatically have the checkbox for allowing edits from maintainers so if a PR author unchecks it they will already be aware of it.  If AMD wants rebase bot, this issue can be reopened (or a new one created) but I was told that they were fine with being unable to use rebase bot.  If someone gets the permission denied error, this issue can be reopened, but I don't think anyone has actually encountered it.
