### ISSUE TITLE
[ONNX] Unable to cast from non-held to held instance

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#82998]
### 🐛 Describe the bug

A runtime error `RuntimeError: Unable to cast from non-held to held instance (T& to Holder<T>) (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for type information)` can be seen when calling `_C._jit_pass_lint(graph)` in `_optimize_graph`. The cause is yet unknown but the message is opaque.

### Versions

Latest

**Comment by qqaatw** [comment]
I encountered similar issues previously when VSCode Python debugger was being used and stepped over some lines which are C++ functions wrapped by pybind as yours. I guess it is probably because some objects' pointer ownership is taken by another process, e.g. Python debugger, in order to sniff the content of the objects and cannot be given back.
