### ISSUE TITLE
Op dispatch declaration bug

### ISSUE THREAD

**Issue by guangyey** [pytorch/pytorch#83051]
### 🐛 Describe the bug

_fake_quantize_learnable_per_tensor_affine_backward and _fake_quantize_learnable_per_channel_affine_backward should have a dispatch in pytorch/aten/src/ATen/native/native_functions.yaml. 
Currently, these two are in the CompositeImplicitAutograd category, meaning we need to provide their autograd function if we want to register a new backend. But these two are all backward operators. It doesn't make sense to implement autograd function for them

original code:
`- func: _fake_quantize_learnable_per_tensor_affine_backward(Tensor grad, Tensor self, Tensor scale, Tensor zero_point, int quant_min, int quant_max, float grad_factor=1.0) -> (Tensor, Tensor, Tensor)`
`  variants: function`

`- func: _fake_quantize_learnable_per_channel_affine_backward(Tensor grad, Tensor self, Tensor scale, Tensor zero_point, int axis, int quant_min, int quant_max, float grad_factor=1.0) -> (Tensor, Tensor, Tensor)`
`  variants: function`

expected code:
`- func: _fake_quantize_learnable_per_tensor_affine_backward(Tensor grad, Tensor self, Tensor scale, Tensor zero_point, int quant_min, int quant_max, float grad_factor=1.0) -> (Tensor, Tensor, Tensor)`
`  variants: function`
`   dispatch:`
`    CPU, CUDA: _fake_quantize_learnable_per_tensor_affine_backward`

`- func: _fake_quantize_learnable_per_channel_affine_backward(Tensor grad, Tensor self, Tensor scale, Tensor zero_point, int axis, int quant_min, int quant_max, float grad_factor=1.0) -> (Tensor, Tensor, Tensor)`
`  variants: function`
`   dispatch:`
`    CPU, CUDA: _fake_quantize_learnable_per_channel_affine_backward`

### Versions

None

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by bdhirsh** [comment]
It can still be useful to implement the derivative of backward ops if you want higher order gradients to work.

`CompositeImplicitAutograd` actually implies that your operator should get autograd "for free" - it will treat your kernel as a decomposition, and just run autograd on each of the base operators that the decomposition calls.

There are some restrictions on what `CompositeImplicitAutograd` kernels are allowed to do though, and it looks like `_fake_quantize_learnable_per_tensor_affine_backward` doesn't meet that criteria: it directly accesses the `data_ptr()` of one of the tensor inputs. So making it `CPU, CUDA: <kernel>` seems reasonable (since the data_ptr call will probably just work with cpu/cuda, and not many other backends).

**Comment by guangyey** [comment]
Hi @bdhirsh , thanks for your elaborations.
Can we have this change in the master code?
Actually, we would like to implement these ops' backward on our XPU backend.

**Comment by guangyey** [comment]
Hi @bdhirsh , is there any information about these op's dispatch?
In my option, the expected code is more reasonable to register op in the new backend. Is it right?
Waiting for your reply.

**Comment by bdhirsh** [comment]
I'll let quantized folks weigh in :) (cc @jerryzh168 @vkuzo)

**Comment by guangyey** [comment]
@bdhirsh, thanks for your help.

**Comment by jerryzh168** [comment]
makes sense, this is only implemented for CPU and CUDA and I guess it can't use `CompositeImplicitAutograd` since it's implemented directly with TensorIterators? please feel free to submit a PR
