### ISSUE TITLE
caffe2-cuda9.0-cudnn7-gcc4.8 cannot be found

### ISSUE THREAD

**Issue by barakhi** [pytorch/pytorch#8327]
While trying to install caffe2 (just typing: conda install -c caffe2 caffe2-cuda9.0-cudnn7-gcc4.8)
I got the following error:

Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - caffe2-cuda9.0-cudnn7-gcc4.8

Current channels:

  - https://conda.anaconda.org/caffe2/linux-64
  - https://conda.anaconda.org/caffe2/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

indeed wile looking in these channels (look for example: https://conda.anaconda.org/caffe2/linux-64) I couldn't see the -gcc-4.8 files (it exist only for a cpu installation).

I'm using:

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch: conda
- 
- Python version: 2.7
- CUDA/cuDNN version: cuda9.0, cudnn7
-
- GCC version (if compiling from source): 4.8.5
- 
Thanks

**Comment by ezyang** [comment]
CC @pjh5

**Comment by pjh5** [comment]
These may have been deleted so save space. BUT, right now I don't think we need the separate gcc4.8 versions because protobuf is statically linked and leveldb is not included. Can you just try the normal non-gcc4.8 conda package and see if that works for you?

I will update the documentation to remove the reference to the gcc4.8 builds. If you encounter an issue with the non-gcc4.8 builds though, please open a different issue.
