### ISSUE TITLE
periodic linux-xenial-cuda10.2-py3-gcc7-slow-gradcheck  times out

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#83335]
### 🐛 Describe the bug

See https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=slow-gradcheck

Started on Wed Aug 10th 2022:
https://hud.pytorch.org/pytorch/pytorch/commit/22830c7c77cf51a9283e12268cc0a3a9fae2e618

Recent examples:
https://hud.pytorch.org/pytorch/pytorch/commit/0e0f8fd03e0967059456d4755c47e8fd4407796d
https://hud.pytorch.org/pytorch/pytorch/commit/ba90c9f2298433778cc6a7a2008d0299aa2911da

### Versions

CI

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by albanD** [comment]
@soulitzer I think we want to do two things here:
- Check what is in each shard and if we can rebalance them
- Disable more stuff that doesn't do gradcheck.

**Comment by soulitzer** [comment]
We probably want TestGradients by itself in its own shard since that takes around 3h alone. Everything else goes in the other shard. Currently one shard takes 2h and the other takes 4h, making this change would balance both shards to take 3h each.

**Comment by albanD** [comment]
How would we go about doing this rebalancing @malfet ?

**Comment by janeyx99** [comment]
I realize the automatic sharding for periodic jobs is iffy because we use the last 3 commits from viable/strict, which may or may not include periodic jobs. We should get around to fixing this, but that's not gonna be as quick as we want..

The default sharding algorithm does a round robin on the files that are listed in alphabetical order, so it's not as easy to play with that unless you rename files. 

This leaves us with using the --includes+excludes flag in run_test.sh. If TestGradients is in its own file, instead of using dynamic sharding, we can make the first shard do run_test.py -i test_ops_gradients and then on the other shard we can do run_test.py -x test_ops_gradients.

I don't love this and this is real jank, but it would work. Since we don't wanna confuse users, we should rename the test configs so it's not shard 1 and shard 2. Of course, this can be temporary until the first is fixed--but sharding won't be good until the check stops timing out anyway (cuz we wouldn't have complete stats).
