### ISSUE TITLE
[ONNX] Add OperatorExportTypes for the usages that valid ONNX is not necessary.

### ISSUE THREAD

**Issue by AllenTiTaiWang** [pytorch/pytorch#84884]
### 🐛 Describe the bug

Currently, enve if users ONNX graph can't pass strict mode shape type inference (invalid ONNX graph), `torch.onnx.export` still supports it to take care of some existing users that use converter, but not running on onnxruntime. However, the model generated from converter should be deafult to runnable on onnxruntime, and by doing that without change on the existing API, a new **OperatorExportTypes** will be created to support the existing need on invalid ONNX graph (using ONNX_CAFFE2 for example here).

1. if OperatorExportTypes=ONNX, the graph should pass strict model shape inference check.
2. if OperatorExportTypes=ONNX_CAFFE2, the graph only needs to pass the baseline onnx checker.

### Versions

PyTorch nightly

**Comment by thiagocrepaldi** [comment]
Semantically speaking, this issue does not sound like "operator_export_type". Ideally, we could combine any `operator_export_type` with strict ONNX shape inference.

For example, currently ONNX Runtime can use `OperatorExportType.ONNX` or `OperatorExportType.ONNX_ATEN_FALLBACK`, depending on whether fallback is to be used or not. That would force us to create `OperatorExportType.ONNX_STRICT` and `OperatorExportType.ONNX_ATEN_FALLBACK_STRICT`. If a new mode is created, we would have to duplicate it to add the  *strict* version, which is not ideal.

**Comment by thiagocrepaldi** [comment]
> Is aten fallback considered strict?

That is the issue. It is not the export type that is strict - a ONNX graph without shape information is correct according to the ONNX spec (shape inference is optional).

ONNX Runtime is "the strict" entity, and it runs with ONNX models exported with different `operator_export_type`, including ONNX and ATEN_FALLBACK. In fact, ORT Inference folks run ONNX models not exported by PyTorch too, (which are not handling here)

**Comment by thiagocrepaldi** [comment]
> Context: Based on the last team discussion, the team wants exporter to follow onnxruntime. That is, set the strict as default, and provide a looser option for users who needs it on other executable platform. And as we don't want to add more parameters on exporter, some suggest we could use this type to separate it.

Wouldn't that make PyTorch ONNX converter to break ONNX spec on this instance? IIUC, 1) ONNX spec states shape inference is optional and 2) ONNX Runtime incorrectly assumes shape inference succeeds, instead of 3) Calling shape inference API from ONNX themselves. 

If we force PyTorch to mimic this behavior, it will deviate from ONNX spec and I would be very concerned about that. PyTorch would be limited to ONNX Runtime as the only official runtime as opposed to support all runtimes that abide by ONNX spec.

> 
> @thiagocrepaldi so I guess expose another parameter is the only way?
> 
> cc @abock

Not the only way, but definitely one way. If we have too many parameters on `torch.onnx.export` already, we can discuss whether enforcing shape inference is what we should do, if there are other ways to do it on demand with a reasonable default, or if we can document the recommened work around for both PyThon and C++ users that need to enforce shape inference

IMHO, more important than making sure Microsoft ONNX Runtime runs smoothly with models exported by PyTorch, is making sure that all ONNX runtimes out there run correctly, provided they implement as per ONNX specification

**Comment by AllenTiTaiWang** [comment]
Merging this task into #78834
