### ISSUE TITLE
[feat][torch.fx] use concrete trace to pass complex branches

### ISSUE THREAD

**Issue by Louis-J** [pytorch/pytorch#85253]
### 🚀 The feature, motivation and pitch

If some one write code like this:
```python
# 1. a branch
if x.dim() == 3:
  pass

# 2. actually a loop
# x = [x1, x2, x3]
if len(x) == 3:
  pass

# 3. actually a loop
# x = [x1, x2, x3]
for xitem in x:
  pass

# 4. a tuple/list unpacking
# x: List[torch.Tensor] = my_leaf_module(x)
my_func(*x)

# 5. some python operators which cannot be wrapped
# x: tensor, but actually a proxy of tensor
if isinstance(x, torch.Tensor):
  pass
# x.name: actually a proxy of 'getattr', so is not 'None'
if x.name is None:
  pass
```

The symbolic tracer in torch.fx cannot pass these codes, so I designed **a concrete tracer with executing syntaxes and saving intermediate variables** like torch.jit.trace, to bypass these restrictions.

What I did:
-  rewrote proxy to the concrete proxy to store intermediate variables.
-  added many detections and handlings to deal with branches, loops, packing and unpacking.
-  added a function patcher to patch functions to deal with operators that cannot be wrapped such as 'is', 'not', 'in'.
-  wrapped some common function and class such as 'isinstance', 'bool', 'tuple' and 'len'.

Now it is **tested ok on yolov3 and a complex mmcls model**. I think it's good to contribute it to torch.fx.

All the code is at:
https://github.com/Louis-J/nni/tree/fx_concrete_trace/nni/common/concrete_trace_utils

cc @ezyang @SherlockNoMad @soumith

**Comment by ezyang** [comment]
cc @voznesenskym 

This is pretty cool. Unfortunately, the long term technical approach we're planning to take for concrete tracing is torchdynamo based https://github.com/pytorch/torchdynamo ; where we are essentially taking over bytecode interpretation entirely (this saves you from having to do a lot of the patching for operators that cannot be wrapped). So I encourage you to use this code as you find it useful, but we're probably not going to upstream it.

**Comment by Louis-J** [comment]
Thanks for your reply.

What I want to do is to help torch.fx trace complex models better. I tried torchdynamo, and got the model split into several torch.fx.GraphModel pieces, but that's not what I want. Actually, I just want one GraphModel for the whole model, then we can use it to do optimizations.

Now I still have questions:
1. As far as I see, the main goal of torchdynamo is to use fx to accelerate the execution, but not to develop fx itself, right?
2. Do you have a plan for supporting complex models with fx? I think codes in fx.experimental now may not be enough.

**Comment by ezyang** [comment]
> I tried torchdynamo, and got the model split into several torch.fx.GraphModel pieces, but that's not what I want.

If you are willing, if you could file a bug report about the splits to dynamo that would be great. In some cases dynamo is incorrectly breaking because of missing functionality, and in those cases we can just add support for the relevant construct and get a larger piece. @voznesenskym also has an idea for a "give you one GraphModel come hell or high water" mode for torchdynamo, although this would come at the cost of soundness. But torchdynamo.export is explicitly about giving you ohne graph.

> As far as I see, the main goal of torchdynamo is to use fx to accelerate the execution, but not to develop fx itself, right?

Yes, torchdynamo targets FX IR, but it replaces FX symbolic trace. Y'all are free to use symbolic trace where it works, but we're not adding features to it.

> Do you have a plan for supporting complex models with fx? I think codes in fx.experimental now may not be enough.

There is going to be subset of models which torchdynamo.export is going to work on. But it is never going to be every model, and our philosophy is that if you have an arbitrarily complex model that uses lots of Python features, you should just use Python for the metalanguage that is gluing together the subgraph tensor operations. It's hard to tell which regime your model is in; if you're willing to share details we can help!
