### ISSUE TITLE
TORCH_WARN does not throw a warning on the backward.

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#85626]
### 🐛 Describe the bug

To reproduce, simply add a `TORCH_WARN("HI");` followed by a `TORCH_CHECK(false);` in any function from `FunctionsManual.cpp` and run a test that tests this function. The warning will not be reported. cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @peterbell10 

### Versions

master

**Comment by ezyang** [comment]
This means that autograd is not using the right error handling try-catch which also flushes warnings. This might also be the root cause of https://github.com/pytorch/pytorch/issues/82218#issuecomment-1203683244

**Comment by peterbell10** [comment]
I was able to confirm that warnings are not displayed when run under `pytest`. However, warnings are shown as expected when run interactively. I also noted that pytest doesn't display warnings even when raised from outside of autograd. The root cause seems to be in pytest's config:
https://github.com/pytorch/pytorch/blob/e38b3424c3f0555c1c255130064dad60c5046c4f/pytest.ini#L9
If I comment this line out, I see warnings printed at the end of the test output, as expected.

**Comment by lezcano** [comment]
@ezyang you added that line. Any thoughts?
I'd vote for removing it. `TORCH_WARN` is super helpful when debugging ATen / autograd stuff.

**Comment by ezyang** [comment]
I don't have a problem with printing warnings, I have a problem with pytest lumping the warnings for ALL tests into an undifferentiated slurry at the end of the test suite, forcing me to scroll up to see actual test results. If you can figure out how to get pytest not to do that I happily accept.

**Comment by lezcano** [comment]
what about setting a binding to run `pytest` with `--disable-warnings` locally / in CI, but not as a global variable in `pytest.ini`?

**Comment by ezyang** [comment]
can you try https://github.com/pytorch/pytorch/pull/86255 and tell me if this is acceptable?
