### ISSUE TITLE
create swin-block in torchvision

### ISSUE THREAD

**Issue by Sophia-66666** [pytorch/pytorch#85697]
### 🚀 The feature, motivation and pitch

I'm working on swin transformer, and noticed the excellent performance of swin transformer, now there is a swin_transformer in torchvision, but I hope to have a swin-block to help me quickly build a network.

cc @datumbox @vfdev-5 @pmeier

**Comment by samdow** [comment]
@Sophia-66666 it might also be helpful to post this in the [torchvision repo](https://github.com/pytorch/vision) so that they're sure to see it

**Comment by pmeier** [comment]
@Sophia-66666 closing this since you have opened pytorch/vision#6688.

@samdow You can "Transfer issue" (bottom of the right column on the issue) to `torchvision`. That avoids extra work for the OP as well as automatically removes the issue from this tracker. Plus, it keeps all the comments from the original thread, which admittedly are not existent here.
