### ISSUE TITLE
max_pool1d error messages diverge between CPU and CUDA

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#85712]
### 🐛 Describe the bug

Ref: https://github.com/pytorch/pytorch/blob/c8a55b3150988f3e1f632e3bc4a6e47623d3f7b5/torch/testing/_internal/common_methods_invocations.py#L3118

https://github.com/pytorch/pytorch/blob/c8a55b3150988f3e1f632e3bc4a6e47623d3f7b5/torch/testing/_internal/common_methods_invocations.py#L3125

https://github.com/pytorch/pytorch/blob/c8a55b3150988f3e1f632e3bc4a6e47623d3f7b5/torch/testing/_internal/common_methods_invocations.py#L3133

https://github.com/pytorch/pytorch/blob/c8a55b3150988f3e1f632e3bc4a6e47623d3f7b5/torch/testing/_internal/common_methods_invocations.py#L3141

https://github.com/pytorch/pytorch/blob/c8a55b3150988f3e1f632e3bc4a6e47623d3f7b5/torch/testing/_internal/common_methods_invocations.py#L3148

Surfaced in PR : #85594 

### Versions

master

**Comment by kshitij12345** [comment]
cc: @mruberry

**Comment by gsc2001** [comment]
If this is available, I would love to work on this :)

**Comment by lucyjin3** [comment]
Can I try working on this issue? It is my first contribution!

**Comment by mruberry** [comment]
> Can I try working on this issue? It is my first contribution!

Of course! Anyone can work on any issue.

**Comment by JAugusto97** [comment]
Hey, it's my first time attempting a contribution here. May I try and fix this? As far as I understood we need to make the error message the same for both GPU and CPU.

Thanks :)

**Comment by tic-Nimmons** [comment]
I would like to work on this issue! This is my first contribution, and could use some elaboration on the issue. Thank you!

**Comment by deandyu** [comment]
Hello, I took a look at the max_pool1d implementation in ATen (aten/src/ATen/native/MaxPooling.cpp) and I found that this issue arises from max_pool1d() calling max_pool1d_impl() (where error checking is performed) for CPU and max_pool1d_with_indices() which in turns calls max_pool2d_with_indices (where error checking is performed) for CPU with requires_grad and CUDA.

Since this is my first time attempting a contribution here, I was wondering if someone more familiar with the project could advise me on whether it would be better to move the error checking from max_pool1d_impl() to max_pool1d() or to change the error checking functions for max_pool2d_with_indices (like pooling_output_shape() in aten/src/ATen/native/Pool.h) to resolve this issue, or if there is another alternative solution I overlooked?  Thank you!
