### ISSUE TITLE
[ONNX] CSE pass in export pollutes Scope information

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#86627]
## Description

There are two issues found with recently adding CSE pass to ONNX export.

1. CSE pass does not update Scope information. Common subexpressions from different modules are eliminated while not updating scope information for the node that is left. The result is that it appears the node's 'users' from other modules are accessing internal information from the module where the node belongs to.
2. Some ONNX passes are re-creating duplicated Constants after the CSE pass.

Both issues are illustrated in below example.

```python
import torch


class M(torch.nn.Module):
    def __init__(self, bias):
        super().__init__()
        self.bias = bias

    def forward(self, x):
        return x + self.bias


class N(torch.nn.Module):
    def __init__(self, layers: int = 3):
        super().__init__()
        # 'bias' is same value for all layers, hence common sub expression.
        self.layers = torch.nn.ModuleList(
            [M(bias=torch.tensor([1.0])) for i in range(layers)]
        )

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x


x = torch.randn(8192, 1, 1)
model = N()

torch.onnx.export(
    model,
    x,
    "model.onnx",
    verbose=True,
    opset_version=15,
    input_names=["x"],
    dynamic_axes={"x": [0]},
)

```

Observe ONNX graph:
```python
Exported graph: graph(%x : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu)):
  %/layers.0/Constant_output_0 : Float(1, strides=[1], requires_grad=0, device=cpu) = onnx::Constant[value={1}, onnx_name="/layers.0/Constant"](), scope: __main__.N::/__main__.M::layers.0 # repro_oct_cse.py:101:0
  %/layers.0/Add_output_0 : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu) = onnx::Add[onnx_name="/layers.0/Add"](%x, %/layers.0/Constant_output_0), scope: __main__.N::/__main__.M::layers.0 # repro_oct_cse.py:101:0
  %/layers.0/Constant_1_output_0 : Float(1, strides=[1], requires_grad=0, device=cpu) = onnx::Constant[value={1}, onnx_name="/layers.0/Constant_1"](), scope: __main__.N::/__main__.M::layers.0 # repro_oct_cse.py:101:0
  %/layers.1/Add_output_0 : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu) = onnx::Add[onnx_name="/layers.1/Add"](%/layers.0/Add_output_0, %/layers.0/Constant_1_output_0), scope: __main__.N::/__main__.M::layers.1 # repro_oct_cse.py:101:0
  %/layers.0/Constant_2_output_0 : Float(1, strides=[1], requires_grad=0, device=cpu) = onnx::Constant[value={1}, onnx_name="/layers.0/Constant_2"](), scope: __main__.N::/__main__.M::layers.0 # repro_oct_cse.py:101:0
  %6 : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu) = onnx::Add[onnx_name="/layers.2/Add"](%/layers.1/Add_output_0, %/layers.0/Constant_2_output_0), scope: __main__.N::/__main__.M::layers.2 # repro_oct_cse.py:101:0
  return (%6)
```

The same constant value `onnx::Constant[value={1}]` still appeared 3 times,
`%/layers.0/Constant_output_0`, `%/layers.0/Constant_1_output_0`, `%/layers.0/Constant_2_output_0`.
And the Scope information is incorrect. All 3 constants are considered belonging to `layers.0`, where as
they should be considered belonging to `layers.0`, `layers.1` and `layers.2` respectively.
This **breaks** node naming and local function export as both depends on Scope information to figure out nodes' original module.

For comparison, this is the graph with cse disabled during export
```python
Exported graph: graph(%x : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu)):
  %/layers.0/Constant_output_0 : Float(1, strides=[1], requires_grad=0, device=cpu) = onnx::Constant[value={1}, onnx_name="/layers.0/Constant"](), scope: __main__.N::/__main__.M::layers.0 # repro_oct_cse.py:101:0
  %/layers.0/Add_output_0 : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu) = onnx::Add[onnx_name="/layers.0/Add"](%x, %/layers.0/Constant_output_0), scope: __main__.N::/__main__.M::layers.0 # repro_oct_cse.py:101:0
  %/layers.1/Constant_output_0 : Float(1, strides=[1], requires_grad=0, device=cpu) = onnx::Constant[value={1}, onnx_name="/layers.1/Constant"](), scope: __main__.N::/__main__.M::layers.1 # repro_oct_cse.py:101:0
  %/layers.1/Add_output_0 : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu) = onnx::Add[onnx_name="/layers.1/Add"](%/layers.0/Add_output_0, %/layers.1/Constant_output_0), scope: __main__.N::/__main__.M::layers.1 # repro_oct_cse.py:101:0
  %/layers.2/Constant_output_0 : Float(1, strides=[1], requires_grad=0, device=cpu) = onnx::Constant[value={1}, onnx_name="/layers.2/Constant"](), scope: __main__.N::/__main__.M::layers.2 # repro_oct_cse.py:101:0
  %6 : Float(*, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cpu) = onnx::Add[onnx_name="/layers.2/Add"](%/layers.1/Add_output_0, %/layers.2/Constant_output_0), scope: __main__.N::/__main__.M::layers.2 # repro_oct_cse.py:101:0
  return (%6)
```

## Proposal
CSE to update scope with common ancestor, whenever it finds two nodes of common sub expression.

For above example, the scopes of the 3 nodes are
```
scope: __main__.N::/__main__.M::layers.0
scope: __main__.N::/__main__.M::layers.1
scope: __main__.N::/__main__.M::layers.2
```
Hence, they have common ancestor `scope: __main__.N::`. Ideally the node should be moved upward in graph to reflect the structural changes as well.

## Alternative Solution
ONNX exporter to run additional pass following CSE to update scope information based on user scopes.

### Versions

PyTorch master:

torch                     1.13.0a0+git585452b

cc @thiagocrepaldi @AllenTiTaiWang

**Comment by thiagocrepaldi** [comment]
Great catch! Any user bug associated with this issue?
This is definitely a side effect of https://github.com/pytorch/pytorch/pull/85665 =/

Is `scope` a PyTorch concept or ONNX (didn't find in any onnx proto, but scope intuitively reminded of `FunctionProto` in which one subgraph could reference another)

Is scope associated with exporter only or torch IR in general? Asking this because this CSE is a pass used by non-exporter Pytorch JIT passes. Maybe we have a exporter bug or something more general

**Comment by BowenBao** [comment]
> Great catch! Any user bug associated with this issue? This is definitely a side effect of #85665 =/

Not yet, I came across this when trying function export for a particular model. 

> Is `scope` (new to me) a PyTorch concept or ONNX (didn't find in any onnx proto, but scope intuitively reminded of `FunctionProto` in which one subgraph could reference another)
> 
> Is scope associated with exporter only or torch IR in general? Asking this because this CSE is a pass used by non-exporter Pytorch JIT passes. Maybe we have a exporter bug or something more general

It's a PyTorch concept. It is associated with torch IR. I could be wrong but I'm not aware of major usages of it outside of exporter in jit. 

After further investigation, I found a potential solution to partially resolve the issue with naming and function export, such that it is not broken. The two main issues are still there.
1. `scalar_type_analysis` (but potentially any other onnx pass) creates common subexpression again.
2. Optimization vs trackability. There could be plenty of small constants here and there inside different modules that shares the same value. For the particular use case of function export I feel it might be better to disable cse, such that unrelated modules don't get tangled together due to somehow some constants got the same value.

**Comment by thiagocrepaldi** [comment]
> > Great catch! Any user bug associated with this issue? This is definitely a side effect of #85665 =/
> 
> Not yet, I came across this when trying function export for a particular model.
> 
> > Is `scope` (new to me) a PyTorch concept or ONNX (didn't find in any onnx proto, but scope intuitively reminded of `FunctionProto` in which one subgraph could reference another)
> > Is scope associated with exporter only or torch IR in general? Asking this because this CSE is a pass used by non-exporter Pytorch JIT passes. Maybe we have a exporter bug or something more general
> 
> It's a PyTorch concept. It is associated with torch IR. I could be wrong but I'm not aware of major usages of it outside of exporter in jit.
> 
> After further investigation, I found a potential solution to partially resolve the issue with naming and function export, such that it is not broken. The two main issues are still there.
> 
> 1. `scalar_type_analysis` (but potentially any other onnx pass) creates common subexpression again.
That is quite possible. Ideally, we should call it at the end of `_optimize_model`, after all optimizations are done and the graph is final. However, when I originally tried that, there was a conflict with `_C._jit_pass_erase_number_types` ( it changes types of nodes and `_jit_pass_cse` fails because of that). If we fix this limitation, we can get a more optimized graph


> 2. Optimization vs trackability. There could be plenty of small constants here and there inside different modules that shares the same value. For the particular use case of function export I feel it might be better to disable cse, such that unrelated modules don't get tangled together due to somehow some constants got the same value.

Maybe we can have both through optimization levels as internal flags/optimization exclusion list? In production, we use set maximum optimization by default. But during debug, we can change this flag internally (don't need to go public) so that we can see graph without `_jit_pass_cse`, possibly `_jit_pass_dce_allow_deleting_nodes_with_side_effects`, `_jit_pass_onnx_deduplicate_initializers`? Not only CSE, but many of them do change whatever goes out of the tracer. Often enough, we have to print graphs in many different parts of the export to find out where that node came from

Another idea that I might like better is changing/appending to the node name to match the latest/all passes that process that node. In that case,  if tracer creates `%/layers.2/Constant_output_0` and after CSE it becomes `%/layers.0/Constant_output_0` (because the have the same value), the node could be renamed `%/layers.0/Constant_output_0__after__jit_pass_cse`. Next if another pass, say `jit_pass_XXX`, change `%/layers.0/Constant_output_0__after__jit_pass_cse`, the new name should be ``%/layers.0/Constant_output_0__after__jit_pass_cse__after_jit_pass_XXX`. This way, there will be one node and we know which passes played a role on its existence. With this, it is easier to determine which optimization to disable and see if the bug under investigation is gone. 

We don't need to use the operator `name`, but maybe append to the bottom `description` or another field that a jit pass was changed this node. We can also use logs for that and soon we will be able to use SARIF to log this information; then naming/description are not needed as debug information will be readily available

What do you think?

**Comment by thiagocrepaldi** [comment]
closing as we are not investing on torch.onnx.export anymore
