### ISSUE TITLE
[MPS] Add support for aten::expm1.out for MPS backend

### ISSUE THREAD

**Issue by kulinseth** [pytorch/pytorch#86744]
### 🐛 Describe the bug
First time contributors are welcome!!. Add support for aten::expm1.out for MPS backend.  Generic support for adding operations to MPS backend is captured here:
https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by kulinseth** [comment]
> Hi! Would love to work on that! Would be my first contribution on the pytorch repo :)

Awesome, please let us know if you have any questions.

**Comment by arnaudstiegler** [comment]
Hello!
I’ve been looking into what I need to do to add the support for MPS, but I’m stuck because I don’t understand where the cpu/cuda function is implemented. I’m very ignorant about the codebase since it’s my first contribution, so the question is probably naive but let me explain what I looked into so far.

Essentially, I’ve looked into `aten/src/ATen/native/native_functions.yaml` where you can easily dispatch the operator to its MPS-specific implementation. It looks like I need to add to `aten/src/ATen/native/mps/operations/UnaryOps.mm` the following call: `CREATE_MPS_STRUCTURED_UNARY_TORCH_IMPL_FUNC(expm1_out_mps, {….})` but I can’t figure out what the stub is for this operator 
I tried reverse-engineering what was done for `exp.out` through `exp_out_mps` and found this line:
`CREATE_MPS_STRUCTURED_UNARY_TORCH_IMPL_FUNC(exp_out_mps, exponent)`
But I don’t see where the `exponent` stub is coming from. I looked into the entire module, couldn’t find a trace of it.

Could you give me some pointers? Thank you!

**Comment by malfet** [comment]
You probably would need to use `TORCH_IMPL_FUNC` as `expm1` is probably a combination  [`exponentWithTensor:name`](
https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/3564551-exponentwithtensor?language=objc) and [`subtractionWithPrimaryTensor:secondaryTensor:name:`](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/3564590-subtractionwithprimarytensor?language=objc)
For example, have a look at implementation of frac_out, which is also a composite graph:
https://github.com/pytorch/pytorch/blob/7c73b456211efe5d9f0d0a65f9a509b26d24f1aa/aten/src/ATen/native/mps/operations/UnaryOps.mm#L215-L232

**Comment by arnaudstiegler** [comment]
Thanks that's helpful, will look into this!
