### ISSUE TITLE
Distributed collective ops fail in `inference_mode` for CPU-only

### ISSUE THREAD

**Issue by edward-io** [pytorch/pytorch#86830]
### 🐛 Describe the bug

Calling collectives inside `@torch.inference_mode()` fails for gloo but works for nccl.

Repro, call using torchrun:

```
import torch.distributed as dist
import torch

@torch.inference_mode()
def test_inference():
    tensor_list = [torch.zeros(1) for _ in range(dist.get_world_size())]

    tensor = torch.tensor([dist.get_rank()], dtype=torch.float32)
    dist.all_gather(tensor_list, tensor)
    print(tensor_list)
    
def main():
    dist.init_process_group("gloo")
    print('rank', dist.get_rank())
    test_inference()

if __name__ == '__main__':
    main()
```

From discussion with @mrshenli  and @albanD:

> The error comes from the fact that a Tensor is written inplace without inference mode being enabled.
My first guess would be that gloo is using a worker thread but does not propagate the current TLS from the user thread to this worker thread. In particular, inference mode status is not propagated and thus this error.

> yep Gloo uses threads to send data, And yep, Gloo [does not propagate TLS](https://github.com/pytorch/pytorch/blob/86f914e9966e91b3d3e7c1504f5b1f00a9498d88/torch/csrc/distributed/c10d/ProcessGroupGloo.cpp#L772-L774)

> You can use the utilities from [https://github.com/.../aten/src/ATen/ThreadLocalState.h](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/ThreadLocalState.h) to capture the current state and restore it in the worker thread.

### Versions

Latest master

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

**Comment by liu3xing3long** [comment]
same issue.

`RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 
for more details.`

for those who follow the code in facebook detectron, just double check the `_get_global_gloo_group` code, and replace the backend from `gloo` to `nccl` will fix the problem, even though maybe more GPUmem is consumed during gather op.

**Comment by liu3xing3long** [comment]
Besides, clone() on to-be-collected Tensors also will NOT work.

**Comment by wanchaol** [comment]
cc @kumpera @XilunWu

**Comment by tonyzhao-jt** [comment]
Same issue

**Comment by dvrogozh** [comment]
I am seeing the same issue on the attempt to generalize [llama-models](https://github.com/meta-llama/llama-models) to non-CUDA backends. I would note that this will happen on using `gloo` with CPU or any device backend (including CUDA) since that's `gloo` specific, not CPU specific issue. I observed this with Llama3.2-11B-Vision-Instruct on https://github.com/meta-llama/llama-models/commit/17107dbe165f48270eebb17014ba880c6eb6a7c9 with applied https://github.com/meta-llama/llama-models/pull/233. Relevant places in llama-models:
* https://github.com/meta-llama/llama-models/blob/17107dbe165f48270eebb17014ba880c6eb6a7c9/models/llama3/reference_impl/generation.py#L163 (inference mode)
* https://github.com/meta-llama/llama-models/blob/17107dbe165f48270eebb17014ba880c6eb6a7c9/models/llama3/reference_impl/multimodal/model.py#L66 (all gather)

Non-modified llama-models don't see this since they are using cuda with `nccl`.

@albanD : are there plans to fix this issue? can you, please, highlight which changes needs to be made?
@EikanWang : fyi in respect to planned work around xpu specific distributed backend.

**Comment by albanD** [comment]
Given the comment above, within the Gloo backend at https://github.com/pytorch/pytorch/blob/86f914e9966e91b3d3e7c1504f5b1f00a9498d88/torch/csrc/distributed/c10d/ProcessGroupGloo.cpp#L772-L774 we would need, every time we send some work there, to capture the TLS of the calling thread and propagate it to the worker similar to how it is done in the native threadpool: https://github.com/pytorch/pytorch/blob/4981bd83554401bcca5b998b8c2fbfcc9f6d8df5/aten/src/ATen/ParallelThreadPoolNative.cpp#L86C35-L86C48

I guess another option would also be to migrate the gloo backend to use our native thread pool to get this feature for free rather than having their own thread workers.

**Comment by dvrogozh** [comment]
@albanD : thank you for the guidance. Here is a PR with the proposed fix:
* https://github.com/pytorch/pytorch/pull/142184
