### ISSUE TITLE
`torch.std` output is not zero for an array of the same values

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#87171]
### 🐛 Describe the bug

`torch.std` computes the standard deviation, but on the CPU the output is not zero for an array of the same values. Interestingly this bug is triggered only for certain values. See code below.

```
import torch
import numpy as np

input = torch.tensor([0.5250, 0.5250, 0.5250, 0.5250, 0.5250, 0.5250])
print(torch.std(input)) # this gives 6.5294e-08 and not ZERO!!! on the cpu

input = torch.tensor([0.5250, 0.5250, 0.5250, 0.5250, 0.5250, 0.5250]).cuda()
print(torch.std(input)) # this gives zero! on the gpu

# even more surprisingly
input = torch.tensor([0.5251, 0.5251, 0.5251, 0.5251, 0.5251, 0.5251]) # off by one
print(torch.std(input)) # this gives zero now!

input = torch.tensor([0.5249, 0.5249, 0.5249, 0.5249, 0.5249, 0.5249]) # off by one
print(torch.std(input)) # this gives zero now!
```

Outputs:
```
tensor(6.5294e-08)
tensor(0., device='cuda:0')
tensor(0.)
tensor(0.)
```

### Versions

1.12.1+cu113

**Comment by Rick0317** [comment]
Seems like whether the torch.std gives 0 or not also depends on the number of elements in the tensor. The increased significant figures due to 0 at the end may not contribute to this incident.

PyTorch sets float32 as its default dtype, but if you change it to float16, it may solve the problem. (Making it less precise)

This also happens to NumPy. The problem seems to lie in torch.mean and numpy.mean. 

Decimals will be represented by certain bits(32, 64) in CPU memory. The difference between CPU and GPU might be due to the fact the memory in GPU runs faster than that of CPU. Lazy memory may not be able to calculate thoroughly. Storing some of the numbers in binary with 64 precision, but leaving other numbers less precise (The last one is my guess).

**Comment by albanD** [comment]
Hi,

A floating point number of 6.5294e-08 is the same as 0 effectively. So it is expected indeed.
See https://pytorch.org/docs/master/notes/numerical_accuracy.html for more details.
