### ISSUE TITLE
[be] Change the structure of BackendConfig so that we don't need to write helper functions

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#87412]
### 🐛 Describe the bug

we probably want to change how the backend configs are stored so that we don't need to write these helper functions: https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/backend_config/utils.py#L24

e.g. changing it from a list to a dictionary

### Versions

master

cc @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by andrewor14** [comment]
Hey @jerryzh168, I took a quick look at this and looks like we already put the configs in a dictionary (`backend_config._pattern_complex_format_to_config`). However, we still need many of these helper functions since they simplify the prepare/convert code significantly, e.g. `get_root_module_to_quantized_reference_module` is helpful because it's used in multiple places and cannot be expressed in `backend_config` easily.

I'm inclined to close this for now since it's not clear if we can get rid of these helper functions. Please feel free to reopen if you think we should still do this.
