### ISSUE TITLE
`InstanceNorm3d` returns different value on cpu and cuda for the same input

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#87557]
### 🐛 Describe the bug

`InstanceNorm3d` returns different value on cpu and cuda for the same input

```py
import torch
torch.manual_seed(0)

def f(input_data, device='cpu'):
    model = torch.nn.InstanceNorm3d(3, device=device)
    out = model(input_data)
    return out.sum()

input_data = torch.rand(100, 3, 1, 10, 10)

inp_cpu = input_data.clone().cpu()
inp_cuda = input_data.clone().cuda()

print(f(inp_cpu)) # tensor(0.0001)
print(f(inp_cuda, 'cuda')) # tensor(0.0014, device='cuda:0')
```

### Versions

torch: 1.12.1
cuda: 11.6

**Comment by ngimel** [comment]
Comparing values element by element (`print((out_cpu-out_cuda).abs().max())`) reveals max difference of O(1e-7), which is expected for floating point computations.

**Comment by nobody81127** [comment]
I applied a floating-point error analysis algorithm to calculate the error bounds for the result of inp_cpu, and I found that the result of inp_cuda falls within this range. Therefore, I believe this is indeed a floating-point error, likely caused by differences in the order of operations. @fuzzyswan @ngimel
