### ISSUE TITLE
fuse qat model using `fuse_modules_qat` instead of `fuse_modules`

### ISSUE THREAD

**Issue by yiliu30** [pytorch/pytorch#87679]
### 📚 The doc issue

In the [Quantization Aware Training for Static Quantization](https://pytorch.org/docs/stable/quantization.html#quantization-aware-training-for-static-quantization) session.

In the API example, the code using `torch.quantization.fuse_modules` to fuse the fp32 model which will raise an error: `Conv and BN both must be in the same mode (train or eval).` 

### Suggest a potential alternative/fix

It should use the `torch.quantization.fuse_modules_qat` instead of `torch.quantization.fuse_modules`.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen

**Comment by HDCharles** [comment]
I can update that since that would be more consistent.

Having said that, I don't think that the error you are seeing is related to this. we have a test that runs that code and it isn't erroring:

https://github.com/pytorch/pytorch/blob/3f612b58be58fe38eb57cad7cbca545887ce7759/test/quantization/core/test_docs.py#L117

this makes sense because both fuse_modules -> prepare_qat and and fuse_modules_qat -> prepare_qat should yield the same result given that prepare_qat applies the qat transform for fused modules.
