### ISSUE TITLE
KPI: Relative performance metric that compares Windows x64/ARM64, Linux and MacOS

### ISSUE THREAD

**Issue by vladimir-aubrecht** [pytorch/pytorch#87707]
- Investigate on how we can collect performance metric
- Review solution on collecting performance metric with a team.
- Implement solution which would allow compare performance of Windows x64/ARM64, Linux, MacOS.

**Comment by vladimir-aubrecht** [comment]
@Blackhex Could you please break this down to smaller issues?

**Comment by malfet** [comment]
Just want to point out that we have the following framework, that is currently can be used to collect some performance numbers (but limited to Linux x64 only): https://github.com/pytorch/benchmark

Also, to compare apples to apples, wouldn't it be better to separate the task of comparing performance on x86 platform vs performance on ARM platform (because the later one is much more far fetched, as currently there are no CI pipleines to build PyTorch for aarch64 for neither Linux nor Windows)

**Comment by iremyux** [comment]
Closing this issue as we have concluded that KPI Dashboard implementation no longer holds a high priority. In the future, should we choose to prioritize this issue further, we can consider opening a new issue accordingly.
