### ISSUE TITLE
`Tensor.where` inconsistent with `torch.where`

### ISSUE THREAD

**Issue by davidgilbertson** [pytorch/pytorch#88470]
### 🐛 Describe the bug

`torch.where()` allows the 'other' value to be a float, but `tensor.where()` requires it to be a tensor.

Let's say I want to replace all zeros with 0.001. I would expect this code to run:
```py
import torch

a = torch.arange(4.0)

not_zero = 0.001

b = torch.where(a != 0, a, not_zero)
c = a.where(a != 0, not_zero)  # Error!

assert b.equal(c)
```

Note, it doesn't fail on the assert, it fails with `TypeError: where(): argument 'other' (position 2) must be Tensor, not float`

This code runs fine:
```py
import torch

a = torch.arange(4.0)

not_zero = 0.001

b = torch.where(a != 0, a, not_zero)
c = a.where(a != 0, torch.full_like(a, not_zero))  # manually create a tensor for the replacement value

assert b.equal(c)
```

Side note: this is inefficient, I should really use `broadcast_to()`, but unlike NumPy, this won't let me broadcast a float, so I end up with something like:
```py
c = a.where(a != 0, torch.broadcast_to(torch.tensor(not_zero), a.shape))
```
making this short version (tensor method) much longer than the `torch.where()` approach.

### Versions

```
PyTorch version: 1.13.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 516.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.971
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] pytorch-forecasting==0.10.3
[pip3] pytorch-ignite==0.4.10
[pip3] pytorch-lightning==1.7.7
[pip3] pytorch-tabnet==3.0.0
[pip3] torch==1.13.0+cu116
[pip3] torchaudio==0.13.0+cu116
[pip3] torchmetrics==0.10.0
[pip3] torchvision==0.14.0+cu116
[conda] Could not collect
```

cc @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by albanD** [comment]
Note that the broadcasting will happen automatically so you don't need to call broadcast to and can just do `a.where(a != 0, torch.tensor(not_zero)`.
This happens because we don't allow float promotion for this function AND the scalar overloads are only for the torch. function version: https://github.com/pytorch/pytorch/blob/4b898a7304246275b250b159dd0ac8e68a6df95d/aten/src/ATen/native/native_functions.yaml#L5686-L5693

We could add method for the ScalarOther overload to enable this.

**Comment by davidgilbertson** [comment]
Ah, that's helpful, thanks @albanD, I didn't think to try a 0D tensor.

**Comment by pierreHaslee** [comment]
> We could add method for the ScalarOther overload to enable this.

could I try doing this?

**Comment by albanD** [comment]
Sure!
The first thing to try would be to write a test for this case and modify the entry in native_functions.yaml to add a method variant and see if that works.

**Comment by pierreHaslee** [comment]
Hi, I modified the native_functions.yaml and I want to test things out, unfortunately whenever I try to build pytorch from source I encounter this [issue](https://github.com/pytorch/pytorch/issues/90448#issue-1483711134):

I did all the conda installs required in the [readme](https://github.com/pytorch/pytorch#from-source), but whenever I do `python setup.py install` it fails at [6062/6378].

**Comment by albanD** [comment]
Hey!
You can check the contributing doc for details of the compile flag. But in this case you can build with `USE_DISTRIBUTED=0` to disable distributed (and thus gloo) altogether. That should avoid that issue.

**Comment by pierreHaslee** [comment]
Thank you very much, it worked.

I was able to modify the native_functions.yaml and used the author's first code snippet to test the code.

> We could add method for the ScalarOther overload to enable this.
You were absolutely right this is what I did to make it work.

The python code snippet ran without an error after recompiling with the change.

I never contributed to an open source project, how would I go about to commit this change? (and are there further tests to pass?)

**Comment by albanD** [comment]
I think the simplest steps are:
- On the github UI, fork PyTorch
- Add your fork as a new remote in your local git (git remote add name same_url_as_the_one_you_give_to_git_clone)
- Locally, create a new branch and commit your changes there
- You can add the test above as a one-off test in test/test_torch.py this can simply test that the code snippet above runs fine
- Push your branch into your fork: git push -u name_of_the_remote name_of_your_branch
- From the landing page of the repro, github should now allow you to create a PR for this new branch (otherwise find the branch and create a pull request for it)
- In the description, explain what you did and say that you're fixing this issue.
- Add me as a reviewer.
- That's it!

**Comment by pierreHaslee** [comment]
Thank you very much for the details, I'll also check the contribution guide to do things right.
I'm having exams rn so I'll expect to PR the resolved issue in about a week.
