### ISSUE TITLE
docker: pytorch-nightly latest tag hasn't been published in 18 days

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#88833]
### 🐛 Describe the bug

If you go here https://github.com/orgs/pytorch/packages/container/pytorch-nightly/versions?filters%5Bversion_type%5D=tagged you'll see
![Screen Shot 2022-11-10 at 10 49 58 AM](https://user-images.githubusercontent.com/3282513/201181110-b6c9d606-d3dc-4b6b-bf88-83796dfa6dde.png)

There is a workaround in that you can check the page for what was the most recently updated package but if you `docker pull pytorch-nightly` you're not actually pulling the nightlies

cc @malfet 

### Versions

n/a

**Comment by malfet** [comment]
May be we just need to update the tag when new image is published

**Comment by malfet** [comment]
Ok, did a bit of digging: 
We used to have 2 workflows:
 - `push_nightly_docker_ghcr.yml` which build nightly docker (for x86 only) and updated the tag
 - `docker-release.yml` which build x86 and arm64 nightly/release dockers + devel image + few other things

About 18 days ago, both workflows were broken by adding `ciflow` labels to https://github.com/pytorch/pytorch/pull/26921 which broke nightly labels parsing logic, which I've fixed in the followup PRs, but also deleted `push_nightly_docker_ghcr.yml`, which seemed redundant to `docker-release.yml`, but I've failed to notice the tag updating logic. Will add it back shortly.
