### ISSUE TITLE
The torch.special.multigammaln operator can still run if the parameters are out of range.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#90062]
### 🐛 Describe the bug

    import torch
    a = torch.empty(2, 3).uniform_(1, 2)
    print(torch.special.multigammaln(a, 5))

result: tensor([[11.2000,  8.8569, 10.0778],
        [10.1121, 11.5120,  8.6177]])

The torch.special.multigammaln operator has a restriction `All elements must be greater than p-1/2`, but when this restriction is violated, the program can still run, unlike the operator torch.mvlgamma with the same function, when encountering This case throws `RuntimeError: All elements must be greater than (p-1)/2`.
I suggest that torch.special.multigammaln also throw `RuntimeError: All elements must be greater than (p-1)/2` when encountering this situation.

### Versions

pytorch: 2.13
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.7
GPU models and configuration: RTX3060
Operating System：Windows

cc @mruberry @kshitij12345

**Comment by kshitij12345** [comment]
@triumph-wangyuyang Thanks for reporting the issue. The behaviour of throwing error was changed in https://github.com/pytorch/pytorch/pull/85153. PR also updates the doc to mention that passing invalid inputs henceforth is undefined behaviour (rather than a hard-error).

Doc: https://pytorch.org/docs/stable/special.html#torch.special.multigammaln

**Comment by lezcano** [comment]
As discussed, this is expected and documented. If you want to be sure the inputs are correct, you can run the relevant checks yourself before calling this function.
Closing.
