### ISSUE TITLE
onnx RNN conversion has some unhygenic steps

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#9043]
pytorch's nn.RNN (and analogously, nn.GRU and nn.LSTM) don't have a direct ONNX analog. When we export them, they produce a subgraph which is intended to fully match the semantics of the original nn operator.

Another complication is that packed sequences do not exist in onnx. To get by this, we introduce a fictional onnx::PackPadded and onnx::PadPacked, which are defined to have exactly the same semantics as the corresponding pytorch operators, but which have no implementation. We eliminate this in an "optimization" pass.

In order to maintain full correctness and cleanliness throughout all transformation stages, rather than directly produce the subgraph containing onnx::RNN, which isn't actually compatible with the fictional onnx::PackPadded, we should instead produce onnx::FakeRNN, which is, and then gradually convert all the fake ops in a way that maintains correctness at each stage.

**Comment by hdubey** [comment]
@anderspapitto Wonderful post. How did you solved it? You re-trained without packed sequence (which is slower in my experiments) or write a wrapper to allow ONNX conversion of models with packer sequence input. Is would be nice to have a link to your repos or PRs? Thanks!

**Comment by garymm** [comment]
I guess this is referring to this code: https://github.com/pytorch/pytorch/blob/dcfccab1e4f47b7eaf65627639e015d5ec893ef6/torch/csrc/jit/passes/onnx/peephole.cpp#L242

Since @anderspapitto has left the PyTorch team and nobody else has been motivated to improve this in the past 3 years, I'm going to close this issue. We can open a new one if the code becomes a maintenance burden.
