### ISSUE TITLE
`torch.compile` doesn't seem to work for flash attention

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#90550]
### 🐛 Describe the bug

When using `torch.compile` with [flash attention](https://github.com/HazyResearch/flash-attention), I obtained the following error:

```bash
[2022-12-09 15:37:45,884] torch._inductor.lowering: [WARNING] using triton random, expect difference from eager
Epoch: [0]  [   0/5004]  eta: 2 days, 13:57:51  lr: 0.000000  loss: 6.9077 (6.9077)  time: 44.5786  data: 2.2891  max mem: 17607
[2022-12-09 15:37:59,048] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (64)
   function: '<graph break in forward>' (/home/user/.local/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py:57)
   reasons:  ['___guarded_code.valid']
```

**Please note that it works when flash attention is disabled.**

### Versions

1.14.0.dev20221206+cu117 with [this patch](https://github.com/pytorch/pytorch/pull/90392) applied.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by wconstab** [comment]
@netw0rkf10w first let's talk about your primary error-
`[WARNING] torch._dynamo hit config.cache_size_limit (64)` - to be clear, this is a warning and signals that compilation is giving up, but should still run correctly.  I'm assuming that's what you're seeing, and you're trying to solve the problem of why compilation is giving up.

On this note, if you're hitting the cache size limit it's likely due to dynamic shapes causing recompilations.  There are tools [here](https://pytorch.org/docs/master/dynamo/troubleshooting.html#excessive-recompilation) to help diagnose excessive recompilation, and if it's indeed caused by different shapes seen at runtime then you may benefit from our WIP 'symbolic shapes' feature. You can learn more about our symbolic-shapes progress [here](https://dev-discuss.pytorch.org/t/state-of-symbolic-shapes-branch/777).

Secondly, RE the minifier-  I am not surprised that the minifier did not help find your primary issue, since there is actually no "error" for the minifier to catch.  It does look like there is a bug with the minifier in this case if it's erroneously finding a bug that isn't there.  (does the script found by the minifier actually run successfully for you, or is it indeed an error?)

**Comment by netw0rkf10w** [comment]
@wconstab I was asked by the author of flash attention what are the requirements for a layer or function to be compilable by `torch.compile`. Could you please answer this question? For example, does `torch.compile` support C++/CUDA/Triton extensions out-of-the box? Thanks.

**Comment by wconstab** [comment]
torch.compile can handle "things it doesn't support" if you don't force it to capture a full graph (fullgraph=True).

C++/cuda/Triton extensions would fall into the category of "things it doesn't support", but again, these would just cause graph breaks and the unsupported pieces would run eagerly, with compilation happening for the other parts.

In full graph mode, these fallbacks become hard errors instead.

**Comment by netw0rkf10w** [comment]
@wconstab That's a very clear answer, thanks!
