### ISSUE TITLE
[jit] [proposal] replace consecutive view ops with as_strided

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9066]

**Comment by SsnL** [comment]
I hope it's possible to replace consecutive `IndexBackward` with a single one... But it doesn't seem so.

**Comment by apaszke** [comment]
Hmm why not? Viewing ops should be easily composable.

**Comment by SsnL** [comment]
Okay I think I understand now. You are talking about doing that in symbolic AD, right?

**Comment by apaszke** [comment]
Yeah. We never trace the internals of `IndexBackward` or `IndexBackwardBackward`. We should just have a JIT pass that merges that viewing ops in the forward (and so their backward will get fused automatically, even if it's going to be differentiated by autograd). If you care about this optimization for 2nd order derivatives, then we'd need to add symbolic AD formulas for viewing ops, but since their backward involves mutation, we'd need to add that to the JIT IR first.

**Comment by zdevito** [comment]
Closing this old issue, if this is still relevant, please reopen.
