### ISSUE TITLE
CUDA 8 build failed on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#9092]
## Issue description

The error `LINK : fatal error LNK1189: library limit of 65535 objects exceeded` occurred when linking caffe2 using Visual Studio 2015. 

## Code example

```CMD
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
REM The following line is needed for Python 2.7, but the support for it is very experimental.
set MSSdk=1

call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
python setup.py install
```

## System Info

PyTorch or Caffe2: PyTorch
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Pro
GCC version: (Rev2, Built by MSYS2 project) 7.1.0
CMake version: version 3.8.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 398.36
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy (1.13.3)
[pip] torch (0.4.0)
[pip] torchfile (0.1.0)
[pip] torchnet (0.0.1)
[pip] torchtext (0.2.1)
[pip] torchvision (0.1.9)
[pip] warpctc-pytorch (0.1)
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.1                     <pip>
[conda] torchtext                 0.2.1                     <pip>
[conda] torchvision               0.1.9                     <pip>
[conda] warpctc-pytorch           0.1                       <pip>

**Comment by peterjc123** [comment]
Similar issue: https://github.com/caffe2/caffe2/issues/2294
CC: @orionr @pjh5

**Comment by yf225** [comment]
@orionr @pjh5 Should we find a way to trim down the number of symbols exported? Also this only affects CUDA 8 (VS 2015) because for CUDA 9 we use VS2017 to compile and it doesn't have this problem.

**Comment by orionr** [comment]
Adding @Yangqing and @mingzhe09088 to this one, since it will likely get worse when we remove `BUILD_ATEN` and `BUILD_CAFFE2` and build everything.

@yf225 , any thoughts on how close are we to the 65535 limit? We actually make some effort to match visibility across platforms (see https://github.com/pytorch/pytorch/blob/master/caffe2/core/common.h) but it's possible that we need to trim things down more.

**Comment by yf225** [comment]
@peterjc123 , re @orionr 's comment, is there a way to know how close we are to the 65535 limit? Perhaps we can count the number of exported symbols in a CUDA 9 build?

**Comment by peterjc123** [comment]
@yf225 Yes, we could use `dumpbin /exports caffe2.dll` to do that.

**Comment by peterjc123** [comment]
The number of the exported symbols in `caffe2.dll` is 16938, while it increased to 51473 for `caffe2_gpu.dll` with CUDA 9.

**Comment by peterjc123** [comment]
@orionr Any progress here? It seems that this issue is listed in the 0.4.1 to-do list #9280.

**Comment by pjh5** [comment]
@peterjc123 if we remove all files under caffe2/operators, what are the number of exported symbols?

**Comment by peterjc123** [comment]
@pjh5 Is there a PR or branch that I can test?

**Comment by peterjc123** [comment]
@pjh5 Actually the number increased to 52382 in the CUDA 9 build, and the CUDA 8 build still fails.

**Comment by pjh5** [comment]
@peterjc123 Orion and I don't have much experience with Windows. Do you have any ideas how to tell what is causing most of the exported symbols and where/how we should start limiting these?

**Comment by peterjc123** [comment]
@pjh5 @orionr Here is the full [list](https://gist.github.com/peterjc123/8cc18c15af402b1b320bd307a58ea26c) of the exported symbols. I hope that it's helpful. I skimmed the list and saw `kernelPointwiseApply2,3,4` takes a large part.

**Comment by orionr** [comment]
Thanks @peterjc123 - that is. Also cc'ing @ezyang and @zdevito since it looks like this is ATen.

**Comment by peterjc123** [comment]
@ezyang @zdevito Any ideas on this?

**Comment by fmassa** [comment]
@colesbury with the TensorIterator PR, aren't we going to reduce the usage of the kernelPointwiseApply functions (for now it's only for a few ops, but I suspect that we will extend it to all pointwise ops, right?), which have many specializations?

**Comment by ezyang** [comment]
It looks like the problem is that CUDA kernels marked `__global__` on Windows get exported from the DLL by default, even if they're not tagged `__declspec(dllexport)`. I checked and saw that marking the kernel as `static` does prevent this export from happening, but for obvious reasons this won't work for kernels which are referenced from multiple compilation units. So, if there is some way to make the nvcc (or maybe the linker?) not export these, that should solve our problem for good.

**Comment by peterjc123** [comment]
@ezyang I wonder if there's any way to get it done with some modification to NVCC, since the [document](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#code-changes-for-separate-compilation) only mentions that it can be controlled by using `static/extern` . However, [this post](https://stackoverflow.com/questions/13029038/hiding-functions-in-static-library) mentioned a rather ugly method, that is to wrap them in a header file and mark them as static.

**Comment by ezyang** [comment]
> However, this post mentioned a rather ugly method, that is to wrap them in a header file and mark them as static.

Yes, but then we'll end up with a copy of the kernel every time it's instantiated. Maybe this won't add too many extra duplicates (because it's already a template that is being instantiated per use site) but it seems a bit dangerous. But it might still be worth a try (and we can see how much binary size increases.)

**Comment by ezyang** [comment]
With the help of @ngimel, we noticed that a minimal repro does NOT export symbols when they're marked `__global__`, so it must be something else (a compile flag, or some other pragma) which is causing these symbols to leak.

Here's the repro:

```
#include <stdio.h>

#if EXPORT_GLOBAL
 #define DECLSPEC_GLOBAL __declspec(dllexport)
#else
 #define DECLSPEC_GLOBAL 
#endif

extern "C" { // Not necessary, but makes output look nicer

DECLSPEC_GLOBAL __global__ void my_kernel(int i)
{
   printf("%i\n", i);
}

} // extern "C"
```

I used the following batch script on the CI server to reproduce the error with as much fidelity as possible:

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc" -o kernel.dll --shared  kernel.cu
dumpbin /EXPORTS kernel.dll
```

**Comment by peterjc123** [comment]
@ezyang Yes, I've checked your example and got the same result. So I'll check what's wrong there in the code.

**Comment by peterjc123** [comment]
Actually, I've checked the number of the exported symbols of `ATen.dll` at 0.4.0. It is only about 8k. So the problem probably is brought by the merge of Caffe2 and ATen.

**Comment by peterjc123** [comment]
Actually, a `.def` file is generated now before linking. After inspecting that file of caffe2_gpu, the number of the exported symbols seems to be nearly 80000. I've also checked the object files under ATen. They're all good and not exporting additional symbols. So, my question is how is the `.def` file generated? Are we using some flags like `WINDOWS_EXPORT_ALL_SYMBOLS`?

**Comment by cbecker** [comment]
@peterjc123 I checked a month ago and that was the issue, exporting all symbols. I think this will require manually exporting the symbols that are necessary and hiding the rest.

**Comment by peterjc123** [comment]
@cbecker Okay, I'll try to add them. If you know what is missing, just tell me directly.

**Comment by ezyang** [comment]
@peterjc123 Very nice catch, I don't know how we forgot about this.

Adding sufficient API annotations to Caffe2 is probably going to take a lot of work, because Caffe2 was never written with correct symbol annotations in mind. I wonder if there is a way to selectively apply "export all" to certain files instead.

**Comment by ezyang** [comment]
Actually, let me be more specific: as @cbecker pointed out, I don't want you to underestimate the work involved in getting Caffe2 to be export clean. There is a lot of code to fix. If we can figure out how to set things up so that we can incrementally fix the situation (and farm things out to Caffe2 devs), that would be much, much more sustainable.

CC @Yangqing

**Comment by peterjc123** [comment]
@ezyang What about deleting some lines in the `.def` file before linking to make the symbol table smaller?

**Comment by cbecker** [comment]
@ezyang I tried that but didn't succeed, because with the export all symbols option of CMake it's not possible to get in between cmake and vsc++ to modify the def file (at least as far as I reached).
(i.e. cmake calls msvc to export all symbols and then starts the linking process, and I didn't find a way to split this process in two so I can modify the .def file)

**Comment by peterjc123** [comment]
@cbecker Then what about we just generate the def file, turn the flag off, delete some lines in it and use the modified one directly?

**Comment by cbecker** [comment]
That could work. I am no MSVC guru so I didn't know how to generate the .def file from many projects/libs as CMake did internally.

The cleanest solution IMO is to define exports manually and enforce that for linux & mac. I understand that this is time consuming, but will free us from having this type of problems later, plus we know what's exported and keep the rest as 'private'

**Comment by yf225** [comment]
We probably need this for the 0.4.1 release because rolling back the Caffe2-PyTorch merge in the build system would be difficult and more like unnecessary work.

**Comment by peterjc123** [comment]
@cbecker Fixed in both master and v0.4.1. You can have a try.

**Comment by ezyang** [comment]
@peterjc123 Do you remember how many symbols the build had after the fix?

**Comment by peterjc123** [comment]
@ezyang The number decreased to 4958 and 3321 for `caffe2.dll` and `caffe2_gpu.dll`.
