### ISSUE TITLE
DistributedDataParallel Batch Size

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#9105]
## Issue description

The documentation for ``DistributedDataParallel`` mentions:

> The batch size should be larger than the number of GPUs used locally. It
> should also be an integer multiple of the number of GPUs so that each chunk
> is the same size (so that each GPU processes the same number of samples).

It's not clear if this is a suggestion or requirement. Does the module break if a batch size of one is run? 

Concerning my use case, sometimes during training, an evaluating step is run with a batch size of one to generate a result for tensorboard. It's not clear to me if it's okay for me to do that with  ``DistributedDataParallel`` or if I need to use the ``DistributedDataParallel.module`` attribute.

**Comment by ailzhang** [comment]
Hi @PetrochukM , for the first question, it's a suggestion instead of a requirement. In DDP we only run `len(inputs)` modules in parallel. In another word, if you only have batch 1 but device_ids=[0,1,2,3] in DDP, it will not break but only waste resources. 
For your use case, if the evaluation step is in model train, it's safe to call DistributedDataParallel.

**Comment by PetrochukM** [comment]
Okay! Was worried because, to me, that did not read as a suggestion, sorry!
