### ISSUE TITLE
functorch.functionalize doesn't allow t.data update

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/pytorch#91093]
### 🐛 Describe the bug

functorch.functionalize doesn't allow t.data update.

```python
import torch
import functorch

def poc5():
  device = 'cpu'

  t1 = torch.zeros(50, device=device)
  t1_slice = t1.data[:5]
  # Assigning the view back to origonal tensor's data should be OK.
  t1.data = t1_slice
  print(t1)

print("CPU")
poc5()
print()

print("CPU Functionalize")
functorch.functionalize(poc5)()
```

Output:
```
CPU
tensor([0., 0., 0., 0., 0.])

CPU Functionalize
FunctionalTensor(lvl=1, value=\
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]))
```

We can see that `t1.data = t1_slice` update `t1` for cpu tensors but not for FunctionalTensor.

### Versions

Nightly.

cc @ezyang @gchanan @zou3519 @bdhirsh @soumith @wonjoolee95

**Comment by JackCaoG** [comment]
A side note, we should test the FSDP before merging the functionalization pr since FSDP heavily rely on views and `.data` update.

**Comment by albanD** [comment]
@bdhirsh would it be possible to warn/error out for .data inplace update during functionalization.

**Comment by bdhirsh** [comment]
@albanD that sounds like it should be possible. Although with the PyTorch/XLA's usage of functionalization, it's possible that they need .data inplace updates to work to avoid regressing behavior when they turn on functionalization. Does that sound like something we can support? I can look into how .data is implemented some more.

**Comment by albanD** [comment]
It is a very tricky one as it changes the c++ Tensor object directly. And that's the only way to actually define what it does.
Not sure how functionalization will be able to replicate that though.

**Comment by alanwaketan** [comment]
Will it be reasonable to assume that `copy_` can be used for most of the places where `tensor.data = other_tensor`?

**Comment by albanD** [comment]
In general, you can do without `.data` yes.
```
with torch.no_grad():
  tensor.copy_(other_tensor)
```
Is the way to go.

The only thing that `.data = ` allows you to do (and most like shouldn't) is to change the device/dtype/... of `tensor` inplace!
But maybe we can just forbid such change for functional transforms.

**Comment by JackCaoG** [comment]
@ronghanghu for info regarding our `.data` usage in current FSDP bridge.

**Comment by alanwaketan** [comment]
Just copy and paste conversations between Ronghang and me:
In the current XLA FSDP implementation above, the .data is only used to free storage by setting t.data = dummy_scalar to free t's storage (while allowing autograd to keep tracing t) and reconstructing t's storage by setting t.data = new_tensor.

For the later usage, we can use with torch.no_grad(): tensor.copy_(other_tensor). For the former usage, we either need to find another PyTorch API to free the storage or PyTorch/XLA introduces a new API/op to free the underneath storage.

**Comment by ezyang** [comment]
`set_` should work in that case.

**Comment by bdhirsh** [comment]
Thanks for the context! I was talking to @albanD on Friday to sum up what sounds like the current state:

(1) XLA's FSDP integration needs a way to be able to free a tensor's underlying memory (and then regenerate it later when needed), without messing with autograd

(2) today, you can free memory by calling resize on a storage, but not on a tensor. For CPU/CUDA, `x.storage().resize_(smaller_size)`, will deallocated the existing storage and allocate the new (smaller) size. Bu `x.resize_(smaller_size)` will not mess with the storage (the idea being that we can think of resizing a tensor into a smaller "view" of some existing storage).

(3) That means that FSDP can use the `x.storage().resize_(0)` trick for strided tensors, but not for other tensors that don't have a real backing storage.

Alban suggested two ideas for API's that can help in this case. Either:

(1) update `x.resize_(0)` to free the backing storage if "0" is the new specified size
(2) give resize_ and optional flag, e.g. `x.resize_(0, free_smaller_size=True)`, to indicate that we should free memory.

(2) feels a bit less risky, since (1) is BC-breaking. Would that be enough to get rid of the existing .data usage  @alanwaketan @ronghanghu?

**Comment by alanwaketan** [comment]
Thanks Ed, Brian, and Alban. Let me digest more on the options provided.

BTW, here is a little experiment I did to replace .data with .copy_: https://github.com/pytorch/xla/pull/4485. It looks like when we are updating the value with .copy_, it would mess up with the autograd engine by bumping the tensor version as well.

**Comment by bdhirsh** [comment]
@alanwaketan the idiom that you want there is to wrap the .copy_() in a `no_grad()` block, so autograd isn't aware of the update:
```
with torch.no_grad():
    x.copy_(...)
```

**Comment by ronghanghu** [comment]
@bdhirsh @alanwaketan Thanks for the discussions! I think the tricky part with `x.copy_` is that we hoped to free a tensor `x`'s storage (and reconstruct it later via `x.data = <something>`) without bumping its version counter `x._version`. Otherwise although autograd isn't aware of the update, it could still keeps the `._version` of the saved forward pass tensor, and could raise an error when it sees the version counter changes.

(I think every time we call `.data` it creates a new Tensor that shares storage but not the version counter. But `.copy_` changes the version counter.)

While in the long-run this probably requires a re-design of FSDP to make it compatible with PT 2.0, do you know if there are any short-term workarounds to bypass this?

**Comment by bdhirsh** [comment]
hmm @ronghanghu I'm probably talking past you - but what's wrong with the following?
```
# First, free the underlying storage of `param` without messing with autograd
with torch.no_grad():
  # this doesn't exist today, but pretend that it deallocate's param's storage
  # under torch.no_grad, param's version counter will not change
    param.resize_(0, free_buffer=True)

...

# Later, reconstruct the parameter (without affecting it's autograd data)
# under torch.no_grad, param._version will be unchanged
with torch.no_grad():
    param.copy_(correct_data)
```

**Comment by ronghanghu** [comment]
@bdhirsh Thanks for the suggestion, and please forgive my stupidity :) I'm a bit not sure about the part of "under torch.no_grad, param._version will be unchanged"

I think `with torch.no_grad()` will still give the same problem. For example:
```python3
import torch

x = torch.nn.Parameter(torch.ones(10))
print("x._version before:", x._version)

with torch.no_grad():
    x.copy_(2.0)

print("x._version after:", x._version)
```
prints
```
x._version before: 0
x._version after: 1
```

So this approach does not work even for CPU or GPU tensors. For example, if we do
```python3
import torch

size = 10
param = torch.nn.Parameter(torch.ones(size))
loss = torch.sum(torch.abs(param))

# First, free the underlying storage of `param` without messing with autograd
with torch.no_grad():
    # this doesn't exist today, but pretend that it does and it deallocates param's storage
    # under torch.no_grad, param's version counter will not change
    param.storage().resize_(0)

# Do something

# Later, reconstruct the parameter (without affecting it's autograd data)
# under torch.no_grad, param._version will be unchanged
with torch.no_grad():
    correct_data = torch.ones(size)
    param.storage().resize_(size)
    param.copy_(correct_data)

loss.backward()
```
it raises the error below:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by bdhirsh** [comment]
@ronghanghu oh nope you are totally right, I messed up my experiment when I was messing around locally 😄. Looks like the `copy_()` inside of the torch.no_grad() block will affect the version counter (same thing with `.set_()` and also true for `inference_mode()`).

hmm @albanD, what do you think - does there exist (or do we want) a way to much with underlying data without affecting a tensor's version counter?

**Comment by albanD** [comment]
Yes the version counter is always updated. This is necessary to ensure correctness indeed.

> hmm @albanD, what do you think - does there exist (or do we want) a way to muck with underlying data without affecting a tensor's version counter?

This does not exist but we do need something like that at some point yes.
I am not sure what is the safest version of this unsafe API though haha

Right now I think the best way to do this is to have `torch.autograd.decrement_version(t)` function. That will allow you to "undo" one inplace call.
This will ensure that if another inplace happens you don't know about, they will still be properly tracked.
WDYT?

**Comment by albanD** [comment]
Sounds good to me! Let's add that!

**Comment by alanwaketan** [comment]
The API sounds perfect. I guess it's better for us to test and validate the API for you before landing it? Please let me know once the PR is up.
