### ISSUE TITLE
First class dims doesn't work with python 3.11

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#91246]
Trying to do `a, b = dims()` will always raise `SyntaxError: dims() must be assigned to a sequence of variable names or have argument n specified`.

As far as I can tell, the OPCODE detection at https://github.com/pytorch/pytorch/blob/15af4b1ceea3b689354ad664675b930486804c8e/functorch/csrc/dim/dim.cpp#LL1531C7-L1531C7 is not working anymore.

cc @zou3519 @Chillee @samdow @soumith @zdevito

**Comment by malfet** [comment]
Yep, they are not. I've tried to make them compile, but refuse to make it work, as this code is fantastically wrong even on older versions of Python runtime. As PyTorch depends on sympy right now, I wonder if we should use it instead.

**Comment by zdevito** [comment]
We can switch this stuff to always requiring `n` to be specified (the docs don't say that you can omit it anymore, because it confuses people). Just the tests need to be updated. However, the byte code parsing stuff really needs to be there to get the variable names for debug info (telling people "unknown dim d12" isn't helpful), but since the debug info doesn't have to be there for functionality it lets us get it into a state where it compiles for 3.11 unblocking having a building release. Does SymPy provide the functionality to extract this stuff? It would save having to maintain it here.

**Comment by zdevito** [comment]
It looks like the bytecodes are the same, but the encoding of `lasti` has changed to allow variable length instruction encodings. Seems like I could fix it. Is there anything special needed to compile PyTorch with 3.11 for trying this out?

```
def foo():
	a, b = dims()
```
Older Pythons:
```
  4           0 LOAD_GLOBAL              0 (dims)
              2 CALL_FUNCTION            0
              4 UNPACK_SEQUENCE          2
              6 STORE_FAST               0 (a)
              8 STORE_FAST               1 (b)
             10 LOAD_CONST               0 (None)
             12 RETURN_VALUE
```

3.11
```
  3           0 RESUME                   0

  4           2 LOAD_GLOBAL              1 (NULL + dims)
             14 PRECALL                  0
             18 CALL                     0
             28 UNPACK_SEQUENCE          2
             32 STORE_FAST               0 (a)
             34 STORE_FAST               1 (b)
             36 LOAD_CONST               0 (None)
             38 RETURN_VALUE
```
