### ISSUE TITLE
how to Wrap normalization layers like LayerNorm in FP32 when use FSDP

### ISSUE THREAD

**Issue by xiaohu2015** [pytorch/pytorch#91498]
in the blog https://pytorch.org/blog/scaling-vision-model-training-platforms-with-pytorch/

<img width="904" alt="image" src="https://user-images.githubusercontent.com/16861194/209910992-619704cd-0ef4-42ec-9d5c-ec7b42005b8b.png">

how to Wrap normalization layers like LayerNorm in FP32 when use FSDP, do we have a example code?

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
Note: That blog references Fairscale FSDP, which has a similar but separate API compared to PyTorch FSDP. I will consider PyTorch FSDP since we hope to migrate users to it now that Fairscale FSDP is not actively developed.

Currently, there are two approaches to wrapping for `FullyShardedDataParallel`: manual wrapping and auto wrapping.
- For manual wrapping, the user calls `submodule = FullyShardedDataParallel(submodule, **fsdp_kwargs)` in a bottom-up manner ending with a final `root_module = FullyShardedDataParallel(root_module, **fsdp_kwargs)`. In this case, the user can make sure to call `layernorm = FullyShardedDataParallel(layernorm, mixed_precision=None)` for any `layernorm: nn.LayerNorm` to avoid it using any mixed precision. In my understanding, the authors from the blog used manual wrapping.
- Auto wrapping refers to passing an `auto_wrap_policy` constructor argument. At the moment, auto wrapping does not support using different `kwargs` across different `FullyShardedDataParallel` instances constructed in the auto wrapping, so it would not be possible to directly use auto wrapping to have the layer norm submodules have a different mixed precision setting than the other submodules.

Let me know if anything is unclear!

**Comment by xiaohu2015** [comment]
@awgu Thanks very much, if we can add more FSDP examples, it is very helpful!

**Comment by zhaojuanmao** [comment]
here are two tutorials about PyTorch FSDP https://pytorch.org/tutorials/intermediate/FSDP_adavnced_tutorial.html and https://pytorch.org/tutorials/intermediate/FSDP_tutorial.html

**Comment by rxqy** [comment]
Hi @awgu @zhaojuanmao , sorry to bother again

From the transformers's [website](https://huggingface.co/docs/transformers/v4.13.0/en/performance),  layernorm are autocasted to fp32 in recent pytorch versions (>=1.10).
`For example, LayerNorm has to be done in fp32 and recent pytorch (1.10+) has been fixed to do that regardless of the input types, but earlier pytorch versions accumulate in the input type which can be an issue.`

And this should be fixed in this issue https://github.com/pytorch/pytorch/issues/66707

So I'm wondering if this is still the case with fsdp in float16 or bfloat16? Do we still have to manully wrap these normalization layers with mixed_precision=None inside the fsdp module?

Many thanks in advance!

**Comment by awgu** [comment]
Hi @rxqy! The accumulation dtype for layer norm is FP32 regardless of the input dtype. However, the output dtype matches the input dtype, as is conventional in PyTorch ops. Therefore, for FSDP with float16 or bfloat16, at the layer norm op level, there will be a downcast to float16 or bfloat16 before returning the final layer norm output.

For some workloads, whether or not that output downcast happens can affect model convergence. If it does, then wrapping the layer norm separately with `mixed_precision=None` may be necessary.
