### ISSUE TITLE
Support forward hooks with torch.compile

### ISSUE THREAD

**Issue by kunalb** [pytorch/pytorch#91665]
### 🚀 The feature, motivation and pitch

This is mentioned in the announcement post, but I couldn't find an issue: https://pytorch.org/get-started/pytorch-2.0/#hooks. Creating one explicitly after a chat with @ezyang.

None of forward, forward_pre or backward hooks appear to fire on the compiled module.

![image](https://user-images.githubusercontent.com/377991/210452512-e1c949a1-0c68-4f20-bd38-f146938ac896.png)

(notebook: https://gist.github.com/kunalb/6c3eae96636f972d73b6357f92935980)

### Implementation Suggestion
(taken from https://github.com/pytorch/pytorch/issues/93726)
We should check for hooks, inline them if they exist, and guard on them not changing.

To make the guards cheaper, we could add a "hooks changed" callback to PyTorch, allowing us to invalidate generated code rather than adding guards.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @soumith @msaroufim @wconstab @ngimel @bdhirsh @Chillee @samdow @kshitij12345 @janeyx99 @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by vadimkantorov** [comment]
(in addition to niceness of supporting hooks) I also suggest that there should also be a way in PyTorch to faithfully declare that no hooks will be added / should be run on a given module + maybe some concept of ownership of module (then for sequential modules with shape-preserving ops can make inplace optimizations in forward and backward). This should allow more free and correct optimization + reasoning + introduction of inplace for more complex/unfusable yet ops:

* https://github.com/pytorch/pytorch/issues/46168
* https://github.com/pytorch/pytorch/issues/23756

**Comment by ezyang** [comment]
Note that there are two distinct types of hooks here, which have differing levels of implementation complexity.

Forward hooks solely affect the forward execution of the graph, and are relatively simple to support: Dynamo simply needs to know that a module can have forward hooks, and be sure to trace into them.

Backward hooks affect the backward execution of the graph. Dynamo cannot trace into them; they execute too late. The only way to trace backward hooks is to promise that they are side effect free (sound to trace), and then directly propagate them to the graph we pass to proxy tensor tracing (so they trace out into the backwards.)

Also cc @wconstab since hooks also affect our distributed integration, which uses them.

Also cc @Chillee who thinks we should be able to use our escape hatches to handle these (specifically `allow_in_graph`)

**Comment by wconstab** [comment]
👍 
@kunalb and I have discussed some places to get started on forward hooks.  He may not have had a chance to dive in yet.

**Comment by wconstab** [comment]
This is done now. I forgot to close the issue a while back.

**Comment by mushkevych** [comment]
In what version of `pytorch` is this fix available? I tried the same notebook in 2.0.1, but the issue persist:
![image](https://github.com/pytorch/pytorch/assets/1039233/aa4e9462-f002-41a7-9af6-32efb1a5c4c3)

**Comment by harshitAgr** [comment]
+1, does not work for me eighter.

**Comment by wconstab** [comment]
could you try with the latest nightly? or at least with 2.1? I am pretty sure 2.0 would not have had these fixes.

**Comment by harshitAgr** [comment]
yes, it works.
