### ISSUE TITLE
Build Pytorch without thirdparty?

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#9201]
Is it possible to build Pytorch withou any thirdparty?

Cheers
Pei

**Comment by zou3519** [comment]
What do you mean by third party?

Pytorch has some dependencies that must be installed if that is what you are referring to.

**Comment by jiapei100** [comment]
@zou3519 
There is a subfolder named [third_party](https://github.com/pytorch/pytorch/tree/master/third_party) ?
It seems either Pytorch or Caffe2 requires/depends on some of the third party libraries?

**Comment by pjh5** [comment]
Why do you want to build without using our third_party? 

We populate third_party with git hashes that we test against and that we're sure work. For most of the packages, third_party is a fallback, and cmake will preferentially find packages in CMAKE_PREFIX_PATH or in system paths before finding them in third_party. More often then not, this causes problems for people when cmake picks up a system package that is misconfigured or otherwise incompatible with another package like CUDA (system Eigen often causes problems with CUDA for example).
