### ISSUE TITLE
Complex Not Supported in Torchinductor

### ISSUE THREAD

**Issue by acohen13** [pytorch/pytorch#93424]
### 🐛 Describe the bug

A linear layer with complex valued weights (e.g. nn.Linear(inp_size, out_size, dtype=torch.complex64)) produces the following NotImplementedError with `dynamo.optimize()(model)`

### Error logs

```
Traceback (most recent call last):
  
  File "*/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 169, in _fn
    return fn(*args, **kwargs)
  File "*/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 951, in forward
    return compiled_f(
  File "*/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 937, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "*/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 657, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "*/lib/python3.10/site-packages/functorch/_src/aot_autograd.py", line 501, in aot_dispatch_autograd
    fw_module, bw_module = aot_config.partition_fn(fx_g, joint_inputs)
  File "*/lib/python3.10/site-packages/functorch/_src/partitioners.py", line 420, in min_cut_rematerialization_partition
    weight = get_node_weight(node)
  File "*/lib/python3.10/site-packages/functorch/_src/partitioners.py", line 382, in get_node_weight
    mem_sz = _size_of(node)
  File "*/lib/python3.10/site-packages/functorch/_src/partitioners.py", line 225, in _size_of
    return _tensor_nbytes(to_size_hint(val.numel()), val.dtype)
  File "*/lib/python3.10/site-packages/functorch/_src/partitioners.py", line 206, in _tensor_nbytes
    raise NotImplementedError("Don't know the size of dtype ", dtype)
NotImplementedError: ("Don't know the size of dtype ", torch.complex64)
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/96297 fixes the issue from original reporter (because it was easy), but actually getting something fast for stft-istft is not going to be so easy. But I am wondering: do y'all actually want fusion into stft/istft, or do you just want to fuse the pointwise/reductions and use the normal kernels for stft/istft?

**Comment by naba89** [comment]
I am not sure I understand your question, or properly understand what compile exactly does. But, looking at all the speed-ups, it is tempting to try torch.compile. Now, for my use case, istft is part of the training graph and gradients need to flow through it, but currently compile fails due to the originally reported issue.

So, in that case, do I just want to fuse the pointwise/reductions and use the normal kernels for stft/istft? I am not sure.

**Comment by naba89** [comment]
One option I am currently considering is to avoid using torch.stft/istft and instead use conv1d/trconv1d, which operates on complex-as-channels paradigm, similar to https://github.com/pseeth/torch-stft/blob/master/torch_stft/stft.py .

Will that provide speed-ups with fusion/compile? If it will then I will consider using that, else will not try it and just accept my fate 😅

**Comment by ezyang** [comment]
No, this is perfectly clear. https://github.com/pytorch/pytorch/pull/96297 should help. Maybe need some other fixes too.

**Comment by ngimel** [comment]
We probably would need to implement complex support in inductor, which should be doable but isn't planned yet (contributions welcome lol)

**Comment by eellison** [comment]
It would be easy enough to fallback for every op that inputs/outputs Complex tensors
