### ISSUE TITLE
[Inductor] [CPU] Torchbench model hf_Reformer performance regression > 10% on ww03.4

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#93513]
### 🐛 Describe the bug

Compare with the [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531) on ww03.2, there is a performance regression on Torchbench model hf_Reformer on ww03.4 as bellow:

|  ww03.4   |   |     |   |  ww03.2   |   |     |   |   |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|0.9781	|0.0372362	|0.036420727	|1	|1.2345	|0.0302742	|0.0373735	|0.79	|1.03	|0.81

WW03.4 SW info:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[69dbc7d](https://github.com/pytorch/pytorch/commit/69dbc7dca8c3a2625edcf20b5a4a3c595d37aa1c)|[00fe63d](https://github.com/pytorch/pytorch/commit/00fe63d1d8c5c6411e093fa4388dc98c3683d236)
Torchbench|/|[ef39f8c](https://github.com/pytorch/benchmark/commit/ef39f8ca47e288ce7206fe92a0eaac03e85623b8)
torchaudio|[ecc2781](https://github.com/pytorch/audio/commit/ecc2781b5b5c353e85a8ca9f16741cf92dd08344)|[4a037b0](https://github.com/pytorch/audio/commit/4a037b03915c4f6f81407e697fb11a7e7ace27fa)
torchtext|[112d757](https://github.com/pytorch/text/commit/112d757efd2482ea5f60bc23d85c2c09f0cfde61)	| [c7cc5fc](https://github.com/pytorch/text/commit/c7cc5fc1e669f548eef619ae055690831d6cc75e)
torchvision|[ac06efe](https://github.com/pytorch/vision/commit/ac06efed4ad2867c68e6b49ac31b554fcbbaa472)|[35f68a0](https://github.com/pytorch/vision/commit/35f68a09f94b2d7afb3f6adc2ba850216413f28e)
torchdata|[049fb62](https://github.com/pytorch/data/commit/049fb626615e6cd965897af8fea2fa73cecd6a2a)|[c0934b9](https://github.com/pytorch/data/commit/c0934b9afa96458c0f8aa3bef528830835c22195)
dynamo_benchmarks|[fac4361](https://github.com/pytorch/pytorch/commit/fac4361e840f6da36ba8c83359c7d0ab5e00cf37)|/

WW03.2 SW info:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[868797a](https://github.com/pytorch/pytorch/commit/868797ac1f173cfe188a0d0641297f9ddb372348)|[d41b5d7](https://github.com/pytorch/pytorch/commit/d41b5d7c145f3e09c7223c2b707933266241ec9b)
Torchbench|/|[bbdc777](https://github.com/pytorch/benchmark/commit/bbdc777837bf0c02b00e20b9178a0f6a9595bda4)
torchaudio|[ecc2781](https://github.com/pytorch/audio/commit/ecc2781b5b5c353e85a8ca9f16741cf92dd08344)|[4a037b0](https://github.com/pytorch/audio/commit/4a037b03915c4f6f81407e697fb11a7e7ace27fa)
torchtext|[112d757](https://github.com/pytorch/text/commit/112d757efd2482ea5f60bc23d85c2c09f0cfde61)	| [c7cc5fc](https://github.com/pytorch/text/commit/c7cc5fc1e669f548eef619ae055690831d6cc75e)
torchvision|[ac06efe](https://github.com/pytorch/vision/commit/ac06efed4ad2867c68e6b49ac31b554fcbbaa472)|[35f68a0](https://github.com/pytorch/vision/commit/35f68a09f94b2d7afb3f6adc2ba850216413f28e)
torchdata|[049fb62](https://github.com/pytorch/data/commit/049fb626615e6cd965897af8fea2fa73cecd6a2a)|[c0934b9](https://github.com/pytorch/data/commit/c0934b9afa96458c0f8aa3bef528830835c22195)
dynamo_benchmarks|[fac4361](https://github.com/pytorch/pytorch/commit/fac4361e840f6da36ba8c83359c7d0ab5e00cf37)|/

### Error logs

</details>

<details>
<summary>grapy.py of this model on ww03.4</summary>

[graph - Copy.txt](https://github.com/pytorch/torchdynamo/files/10463530/graph.-.Copy.txt)

</details>

<details>
<summary>grapy.py of this model on ww03.2</summary>

[graph - Copy.txt](https://github.com/pytorch/torchdynamo/files/10463533/graph.-.Copy.txt)

### Minified repro

```
python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only hf_Reformer  --cold_start_latency

```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by blzheng** [comment]
This regression is caused by a fix for randn #91945 
cc [min-jean-cho](https://github.com/min-jean-cho)

**Comment by chunyuan-w** [comment]
@min-jean-cho is the performance drop expected?

**Comment by min-jean-cho** [comment]
Thanks @blzheng, @chunyuan-w, the performance drop is expected. Few things to note, 

- Before #91945, philox `randn` was not random (all generated values were 1.7567) due to `reset_state()` per generation [here](https://github.com/pytorch/pytorch/blob/a4cc63991ad351f1e98c4bac8955e34a0cb7b1a6/aten/src/ATen/core/PhiloxRNGEngine.h#L108). 
- `random `generation (without `reset_state()`) probably has lower cache hit compared to `non-random` generation (with `reset_state()`), hence the end-to-end performance drop.

Below is a benchmark of avg time in ms. `non-random` denotes with `reset_state()` and `random` denotes without `reset_state()`. `fresh_inductor_cache` refers to https://github.com/pytorch/pytorch/blob/master/torch/_inductor/utils.py#L317-L342. 

|                                  	| **non-random** 	| **random** 	| **% diff** 	|
|:--------------------------------:	|----------------	|------------	|------------	|
| **with fresh_inductor_cache**    	| **0.49 ms**    	| **0.60 ms**    	| 20.18349   	|
| **without fresh_inductor_cache** 	| **0.03 ms**    	| 0.19 ms    	| 145.4545   	|   

Notice `non-random` avg time increased from 0.03 ms to 0.49 ms `with fresh_inductor_cache`, probably due to lower cache hit per iteration. And notice `with fresh_inductor_cache`, `non-random` avg time from 0.49 ms to `random` 0.60 ms, probably even `with fresh_inductor_cache` per iteration, `non-random` has higher cache hit inherently than `random` generation. 

<details>
<summary>benchmark script used</summary>

```python
import torch._dynamo
from torch._inductor.utils import fresh_inductor_cache
import time

@torch._dynamo.optimize("inductor")
def foo():
    return torch.randn(10000)

def fresh_cache(fn):
    def inner(*args, **kwargs):
        cache_entries = {}
        cache_minder = fresh_inductor_cache(cache_entries)
        
        with cache_minder:
            return fn(*args, **kwargs)
    return inner

fresh_cache(foo)()

# warm up
start = time.time()
for _ in range(100):
    #foo()
    fresh_cache(foo)()
end = time.time()
print('average warmup: {:.2f} ms'.format((end-start)/100*1000))

# measure
start = time.time()
for _ in range(100):
    #foo()
    fresh_cache(foo)()
end = time.time()
print('average measure: {:.2f} ms'.format((end-start)/100*1000))

from torch.profiler import profile, ProfilerActivity
with profile(activities=[ProfilerActivity.CPU]) as prof:
    #foo()
    fresh_cache(foo)()
print(prof.key_averages().table(sort_by="self_cpu_time_total"))
```
</details> 

Further, torch profiling doesn't show such performance gap between `with fresh_inductor_cache, non-random` --vs-- `without fresh_inductor_cache, random`. So the end-to-end performance drop is expected from lower cache hit with random generation by nature. 
 
**with fresh_inductor_cache, non-random** 
```
-----------------------  ------------  ------------  ------------  ------------  ------------  ------------
                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
-----------------------  ------------  ------------  ------------  ------------  ------------  ------------
          aten::randint        65.62%      21.000us        81.25%      26.000us      26.000us             1
    aten::empty_strided        18.75%       6.000us        18.75%       6.000us       6.000us             1
          aten::random_        12.50%       4.000us        12.50%       4.000us       4.000us             1
          aten::resize_         3.12%       1.000us         3.12%       1.000us       1.000us             1
-----------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 32.000us
```
**with fresh_inductor_cache, random**
```
-----------------------  ------------  ------------  ------------  ------------  ------------  ------------
                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
-----------------------  ------------  ------------  ------------  ------------  ------------  ------------
          aten::randint        69.23%      18.000us        84.62%      22.000us      22.000us             1
          aten::random_        15.38%       4.000us        15.38%       4.000us       4.000us             1
    aten::empty_strided        15.38%       4.000us        15.38%       4.000us       4.000us             1
          aten::resize_         0.00%       0.000us         0.00%       0.000us       0.000us             1
-----------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 26.000us
```
</details> 

Actually in the above profiling, `with fresh_inductor_cache, random` shows slightly better performance without the extra `reset_state()`.
