### ISSUE TITLE
[caffe2] caffe2 install tutorial error: no module named hypothesis, cannot import_name caffe2_pb2

### ISSUE THREAD

**Issue by ujsyehao** [pytorch/pytorch#9373]
In relu_op_test.py,
 `from hypothesis import given`, so we should **pip install hypothesis first**, but 
![175](https://user-images.githubusercontent.com/17454232/42611262-d594d114-85c7-11e8-8bb8-0fa34bfdcaf3.png)
the tutorial doesn't say anything about hypothesis.

![176](https://user-images.githubusercontent.com/17454232/42611312-02076a9a-85c8-11e8-8302-773ec6672341.png)
When I `cd pytorch` and `python caffe2/python/operator_test/relu_op_test.py`, it has the error **"cannot import_name caffe2_pb2".**
I modify PYTHONPATH several times, it doesn't work. At last, I use the command                           
`python pytorch/caffe2/python/operator_test/relu_op_test.py` and it works. **So why relu_op_test.py can not find caffe2_pb2 in current path?** 
Please update the tutorial(it confused me long) [tutorial](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile)

**Comment by pjh5** [comment]
The instructions only specify the packages needed for the tutorials, not the extra packages that are also needed to run the tests.

Please read https://caffe2.ai/docs/faq.html#why-do-i-get-import-errors-in-python-when-i-try-to-use-caffe2 and https://caffe2.ai/docs/faq.html#null__how-do-python-installations-work before changing your PYTHONPATH. You probably should not change your PYTHONPATH.

Since this issue is actually two issues, let's keep this one about the tutorial question. Please open a new issue about "cannot import caffe2_pb2" if you cannot find the answer in the links above.
