### ISSUE TITLE
Dockerizing lintjob made them 10x larger

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#94716]
### 🐛 Describe the bug

For example, before size of https://github.com/pytorch/pytorch/actions/runs/4152711462/jobs/7183856511 is 1824 lines

After https://github.com/pytorch/pytorch/pull/94255 size of https://github.com/pytorch/pytorch/actions/runs/4153749039/jobs/7185574044 is 16565 lines, i.e. 10x increase 
(Measured by clicking on "Show raw logs" button and piping it to `wc -l`)

Also, due to the log size, github UI often fails to load the log, for example see  https://github.com/pytorch/pytorch/actions/runs/4158268242/jobs/7193445969

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
This is most likely because `lintrunner init` isn't actually being cached correctly since the directory where it's run (in the `Dockerfile) is blown away when we volume mount the jenkins directory.

Short term fix would probably be to cache it somewhere else like `/lintrunner-init` and then do a `mv` of that directory into the jenkins directory in the lintrunner job.

Longer term fix would be to build support into `lintrunner` to reference a different init directory (probably activated with an environment variable like a `LINTRUNNER_INIT_DIR`). Then you could just set `LINTRUNNER_INIT_DIR=/lintrunner-init` and it'd most likely be fine forever.

**Comment by huydhn** [comment]
Good catch! These redundant logs all come from `lintrunner init` just to display the progress of downloading `actionlint`, `clang-tidy`, and `clang-format` from S3 (too verbose).  While pip and conda dependencies have been cached in the image, binaries downloaded from S3 aren't cached yet as @seemethere points out.  I'll draft a fix for this with:

1. Cache S3 dependencies somewhere else, and then mv them into the workspace
1. Redirect the output of `lintrunner init` to a file, and print it only when the command fails.  In normal case, there is little reason to look into that log because everything should have already been cached

**Comment by huydhn** [comment]
A side note:  The lint command itself `lintrunner --all-files` also blows up the amount of logs to display the linting progress (STDERR).  This has been fixed https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml#L46.  Quoted from https://github.com/suo/lintrunner

> Any lint messages a linter would like to communicate the user must be represented as a LintMessage. The linter, must print LintMessages as [JSON Lines](https://jsonlines.org/) to stdout, one message per line. Output to stderr will be ignored.
