### ISSUE TITLE
git clone --recursive https://github.com/caffe2/caffe2.git gives error that Eigen repository is not found.

### ISSUE THREAD

**Issue by 008karan** [pytorch/pytorch#9489]
1. Installing caffe2 is being a nightmare now for me. Many methods follow cloning caffe2 which results in error that eigen repository is not found. I came to know that it has been moved to another place called eigen git mirror. So how to proceed now as it not able to find it by cloning caffe2.

2. When I follow builing from source [method ](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile) i am getting error in make  like [this](https://github.com/pytorch/pytorch/issues/9181)

3. I also tried to use [conda](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt) installation but after importing . when I test with 'from caffe2.python import core' getting this message:

**WARNING:root:This caffe2 python run does not have GPU support. Will run in
 CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_hip
CRITICAL:root:Cannot load caffe2.python. Error: /home/g008kaaraan/pytorch/
build/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZN6caffe2
24OptimizationPassRegistryB5cxx11Ev**

I am doing this on Google cloud environment. 
Ubunto 16.04  python 2.7

I am frustated now please suggest any valid method to do this.

**Comment by jerryzh168** [comment]
feels like it's protobuf version mismatch, cc @pjh5 could you help?

**Comment by pjh5** [comment]
https://github.com/caffe2/caffe2.git is a few months out of date. The code moved to https://github.com/pytorch/pytorch.git 

This path in your error message "/home/g008kaaraan/pytorch/build/caffe2/python/" tells me that you are still trying to run Caffe2 out of your build directory. You should not run your commands from your root Caffe2 directory (which should actually be the root pytorch directory now) or from your build directory; this is because the presence of directories called 'caffe2' confuses python; python should import Caffe2 from its own site-packages, not from the source files. This https://caffe2.ai/docs/faq.html#why-do-i-get-import-errors-in-python-when-i-try-to-use-caffe2 and the next few questions should help you avoid many Python problems.

Can you
1. Make sure you are using the most current code in https://github.com/pytorch/pytorch if you want to build from source. If you don't need to edit the source code or build from source, then you don't actually need to clone any code at all. You can just the pre-built packages.
2. Create a brand new conda environment, see the link above for the right way to do that
3. Try a simple "conda install -c caffe2 caffe2" in the new environment. 
4. Make sure your Python environment is clean. Again see the link above. Make sure you don't have environment variables set that you don't need.

**Comment by soumith** [comment]
closing this via https://github.com/pytorch/pytorch/issues/9489#issuecomment-405755002 's comment

**Comment by 008karan** [comment]
So I followed your method of creating a new environment and installing caffe2 as 'conda install -c caffe2 caffe2'. It passed both tests:
```# To check if Caffe2 build was successful
python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"

# To check if Caffe2 GPU build was successful
# This must print a number > 0 in order to use Detectron
python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
``` 

Then I moved ahead for densepose by following [this](https://github.com/facebookresearch/DensePose/blob/master/INSTALL.md). I am getting error in this line:
`cd $DENSEPOSE && make ops` 

output:

> 
mkdir -p build && cd build && cmake .. && make -j1
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-lin
ux-gnu/libglog.so)
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Caffe2: CUDA detected: 8.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-8.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-8.0
-- Caffe2: Header version is: 8.0
-- Found cuDNN: v6.0.21  (include: /usr/local/cuda-8.0/include, library: /
usr/local/cuda-8.0/lib64/libcudnn.so)
CMake Error at /home/g008kaaraan/pytorch/build/public/utils.cmake:164 (cud
a_select_nvcc_arch_flags):
  Unknown CMake command "cuda_select_nvcc_arch_flags".
Call Stack (most recent call first):
/home/g008kaaraan/pytorch/build/public/cuda.cmake:332 (torch_cuda_get_nv
cc_gencode_flag)
  /home/g008kaaraan/pytorch/build/Caffe2Config.cmake:79 (include)
  CMakeLists.txt:8 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/g008kaaraan/densepose/build/CMakeFiles/CMakeOutput.log".
See also "/home/g008kaaraan/densepose/build/CMakeFiles/CMakeError.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1

> 
How to proceed now. Thanks for the help!

**Comment by 008karan** [comment]
After researching I got to know that it is probably because of my old cmake version(3.5).
So I removed it and updated using the following command:
```version=3.11
build=4
mkdir ~/temp
cd ~/temp
wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
tar -xzvf cmake-$version.$build.tar.gz
cd cmake-$version.$build/
./bootstrap
make -j4
sudo make install
```
Then I created new environment and installed caffe2 again and when this time I run `cd $DENSEPOSE && make ops` I get following error message:

**Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer requ
ired:
  cmake-data libjsoncpp1
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  cmake
0 upgraded, 0 newly installed, 1 to remove and 12 not upgraded.
After this operation, 14.6 MB disk space will be freed.
Do you want to continue? [Y/n] y
ls.
  Use the cmake_policy command to set the policy and suppress this warning
.
  get_target_property() called with non-existent target "caffe2".
Call Stack (most recent call first):
  /home/g008kaaraan/pytorch/build/Caffe2Config.cmake:106 (caffe2_interface
_library)
  CMakeLists.txt:8 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Error at /home/g008kaaraan/pytorch/build/public/utils.cmake:65 (mess
age):
  You made a CMake build file error: target caffe2 must be of type either
 CMakeLists.txt:8 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/g008kaaraan/densepose/build/CMakeFiles/CMakeOutput.log".
See also "/home/g008kaaraan/densepose/build/CMakeFiles/CMakeError.log".
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 1**

Not able to find cause of this. @pjh5 @soumith @jerryzh168 Please help!

**Comment by pjh5** [comment]
Sorry, I did not realize you were trying to install detectron. It looks like detectron expects to find Caffe2 through find_package, which right now requires Caffe2 to be built from source. What's causing that error message is that a source build (through Caffe2's cmake) populates a "Caffe2 target" that tells other cmake projects (Detectron) where to find Caffe2. These extra cmake files aren't included in the pre-built packages because you shouldn't need cmake to install and use Caffe2.

When installing from source, do still read through  https://caffe2.ai/docs/faq.html#why-do-i-get-import-errors-in-python-when-i-try-to-use-caffe2  and follow it's recommendations; it can save you from a lot of frustrating errors.

**Comment by veralauee** [comment]
I have the exact same problem!! How did you solve that? @008karan
