### ISSUE TITLE
autogen out doesn't do anything on empty_strided

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#95068]
### 🐛 Describe the bug

I see

```
- func: empty_strided(SymInt[] size, SymInt[] stride, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor
  dispatch:
    CPU: empty_strided_cpu
    CUDA: empty_strided_cuda
    MPS: empty_strided_mps
    Meta: empty_strided_meta_symint
    QuantizedCPU, QuantizedCUDA: empty_strided_unknown_quantized
  autogen: empty_strided.out
  tags: core
```

but this does not work

```
>>> torch.empty_strided((), (), out=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: empty_strided() got an unexpected keyword argument 'out'
```

this is not caught in testing as empty_strided does not have an OpInfo.

cc @bdhirsh 

### Versions

master

**Comment by bdhirsh** [comment]
I think this is by design - `autogen` added out= variants for a lot of aten ops, but today they don't have efficient kernels implemented, or have proper docs, so they're hidden from python (see [code](https://github.com/pytorch/pytorch/blob/766d51b496bb85feab4b0f23977b4ffc0a0e354b/tools/autograd/gen_python_functions.py#L188))
