### ISSUE TITLE
Symmetric and skew-symmetric initialization 

### ISSUE THREAD

**Issue by abdulfatir** [pytorch/pytorch#95204]
### 🚀 The feature, motivation and pitch

Initializing a square matrix to a random symmetric or skew-symmetric matrix is sometimes required. In a model I was working on recently, I needed to ensure that the `matrix_exp` of a matrix was orthogonal. For this, I initialized the matrix to a random skew-symmetric matrix. It would be nice to have an initializer for random symmetric or skew-symmetric matrices, similar to `torch.nn.init.orthogonal_`. 

Generating random symmetric matrix:
- X ~ randn(n, n)
- A = (X + X.T)/2

Generating random skew-symmetric matrix:
- X ~ randn(n, n)
- A = (X - X.T)/2

cc @albanD @mruberry @jbschlosser @walterddr @saketh-are

**Comment by abdulfatir** [comment]
I have implemented an initial version here: https://github.com/pytorch/pytorch/compare/master...abdulfatir:pytorch:add-sksymm. I will be happy to send a PR.

**Comment by jbschlosser** [comment]
Hey @lezcano, do you mind looking into this? I believe you're fairly familiar with this area

**Comment by lezcano** [comment]
This is a bit too niche to be implemented in core. Perhaps you could have a look at https://github.com/lezcano/geotorch for an implementation?

The more mathy response would go as: The orthogonal group (the set of orthogonal matrices) is compact, so it has a diatinguished measure: the Haar measure. That's the one we implement in PyTorch. 
The sets of symmetric and skew-symmetric matrices are not compact, so they do not have a distinguished probability measure (i.e. why would you sample via randn and not via rand and then project? or why not sample from a laplace) so there is no sampling method better than the other. As such, it's best to just sample a matrix and project it yourself in your own auxiliary function rather than adding an arbitrary sampler to core.

**Comment by abdulfatir** [comment]
@lezcano Thanks for sharing your thoughts. GeoTorch looks cool, I did not know about that.
