### ISSUE TITLE
`add/add_` returns/modifies indices by downcasting `int64` to `int32` for CSR inputs.

### ISSUE THREAD

**Issue by nikitaved** [pytorch/pytorch#95224]
### 🐛 Describe the bug

```python
In [1]: import torch

In [2]: x = torch.rand(3, 3).to_sparse_csr()

In [3]: x.crow_indices().dtype
Out[3]: torch.int64

In [4]: x.add(x).crow_indices().dtype
Out[4]: torch.int32

In [5]: x.crow_indices().dtype
Out[5]: torch.int64

In [6]: x.add_(x).crow_indices().dtype
Out[6]: torch.int32

In [7]: x.crow_indices().dtype
Out[7]: torch.int32

In [8]: x = torch.rand(3, 3, device='cuda').to_sparse_csr()

In [9]: x.crow_indices().dtype
Out[9]: torch.int64

In [10]: x.add(x).crow_indices().dtype
Out[10]: torch.int32

In [11]: x.add_(x).crow_indices().dtype
Out[11]: torch.int32

In [12]: x.crow_indices().dtype
Out[12]: torch.int32
```

### Versions

Current master.

cc @alexsamardzic @pearu @cpuhrsch @amjames @bhosmer

**Comment by nikitaved** [comment]
There are no checks whether the cast is potentially safe, so we have potential correctness/segfault issues on our hands.

**Comment by nikitaved** [comment]
OK, the downcasting is documented: https://pytorch.org/docs/stable/generated/torch.Tensor.col_indices.html, but probably warning the user will not hurt.

**Comment by cpuhrsch** [comment]
@nikitaved - Well it's saying " When using MKL routines such as sparse matrix multiplication, it is *necessary* to use int32 indexing in order to avoid downcasting and potentially losing information.", but it doesn't tell the user how to achieve that or how it happens. We don't have an in-place conversion and we can't assign to values. So it'd require the user to use the constructor again. Our CSR constructor doesn't have a way of specifying an indices dtype. Maybe we should add that option, set it to int32 by default and not use MKL and such when the user passes int64 and are confident that they really need those additional bits. This then would also allow us to enable int16 indices at some point in the future. What do you think?

**Comment by nikitaved** [comment]
I think we should provide a workaround to be safe, i.e. we could use the COO operations for pure int64 indices. And if needed, we can even extend these to batch dimensions easily.
