### ISSUE TITLE
Change behavior of kl_div

### ISSUE THREAD

**Issue by veritas9872** [pytorch/pytorch#95687]
### 🚀 The feature, motivation and pitch

The warning message in `torch.nn.functional.kl_div` states that the `batchmean` option and `mean` option will be merged in the next major release. Though PyTorch 2.0 is meant to be fully compatible, I think that changing the behavior might be a good option.

### Alternatives

Perhaps convert the `batchmean` option automatically to `mean`?

### Additional context

This may cause some confusion as kl_div is so widely used. However, not fixing it will increase the technical debt of the project.

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @saketh-are @ezyang @gchanan

**Comment by jbschlosser** [comment]
Hey @veritas9872, thanks for the report! While I agree it would be ideal to correct the behavior of `mean`, in practice it is very BC-breaking to make this change. Our policy is to avoid silent BC-breaking changes when possible, especially for a function as widely used as `kl_div`.

To smooth this out, we'd generally throw a warning about the changing behavior for a release before making the change. When changing the default, it's nice to provide users a way to explicitly opt in to either the old or new behavior to reduce warning spam, and this is particularly important since it's the default behavior that would warn.

Rather than go through this process and introduce yet another kwarg for opting in to the old behavior, I'd prefer just removing the note in the kl_div docs that states that the behavior of mean will change. It seems like overall more pain than it's worth when it's possible now for users to opt in to either behavior.

**Comment by jbschlosser** [comment]
Actionable to remove the statement from the `kl_div` docs.
