### ISSUE TITLE
Tracer incorrectly get Guard name in dynamo

### ISSUE THREAD

**Issue by liuzeming-yuxi** [pytorch/pytorch#96737]
### 🐛 Describe the bug

It looks that torch dynamo mistakenly parsed ```___odict_getitem(np_to_torch, np.float16)``` into ```___odict_getitem(np_to_torch, <class 'numpy.float16'>)```.Through pdb, we found this bug has already occurred in the tracer.output (torch/_dynamo/convert_frame.py(314))

### Error logs

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 373, in _compile
    check_fn = CheckFunctionManager(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 640, in __init__
    guard.create(local_builder, global_builder)
  File "/opt/conda/lib/python3.8/site-packages/torch/_guards.py", line 159, in create
    return self.create_fn(self.source.select(local_builder, global_builder), self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 298, in CONSTANT_MATCH
    val = self.get(guard.name)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 146, in get
    return eval(name, self.scope, CLOSURE_VARS)
  File "<string>", line 1
    ___odict_getitem(np_to_torch, <class 'numpy.float16'>)
                                  ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "collect_env.py", line 36, in <module>
    generate((2, 3, 4))
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 254, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 391, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 413, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 105, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 263, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 403, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
```

### Minified repro

```
import torch
import numpy as np
from typing import Union, List

np_to_torch = {np.float16: torch.float16, np.float32: torch.float32, bool: torch.bool}


class Device:
    def __init__(self, device, device_type):
        self.dev = device
        self.device_type = device_type
        
    def create_tensor(self, shape, dtype):
        dtype = np_to_torch[dtype]
        data = torch.empty(shape, dtype=dtype, device=self.dev)
        return data

class Model:
    def __init__(self, device):
        self.device = device
        
    def forward(self,
                 inputs: Union[np.array, List[List[int]]]):
        x = self.device.create_tensor(inputs, np.float16)
        y = self.device.create_tensor(inputs, np.float16)
        return x + y
    
dev = Device(torch.device('cuda:0'), 'GPU')
model = Model(dev)

def wrapper_fn(inputs: Union[np.array, List[List[int]]]):
    return model.forward(inputs)

generate = torch.compile(wrapper_fn)

generate((2, 3, 4))
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230312+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090
GPU 5: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.141.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          40
On-line CPU(s) list:             0-39
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:                        1
CPU MHz:                         1200.000
CPU max MHz:                     3100.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4399.66
Virtualization:                  VT-x
L1d cache:                       640 KiB
L1i cache:                       640 KiB
L2 cache:                        5 MiB
L3 cache:                        50 MiB
NUMA node0 CPU(s):               0-9,20-29
NUMA node1 CPU(s):               10-19,30-39
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+2c32f43999
[pip3] torch==2.1.0.dev20230312+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+2c32f43999          pypi_0    pypi
[conda] torch                     2.1.0.dev20230312+cu117          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
This should be easy to fix. Happy to advise / review.

**Comment by voznesenskym** [comment]
Hey, the way to fix this is by finding the source that has that string in it. `___odict_getitem` leads us to ODictGetItemSource. However,  I am not sure the solution is so simple. 

Now, we only have 1 instantiation of this, `ODictGetItemSource(self.source, key.as_python_constant()),`

Seeing as this looks like numpy, let's go look at where we handle those types. Aha, NumpyVariable!
Now, what does as_python_constant look like for that class?

```
def as_python_constant(self):
        return self.value
```
Reasonable... so why is it returning a class?
Well, because that's what is in the odict! 

`np_to_torch = {np.float16: torch.float16, np.float32: torch.float32, bool: torch.bool}`

So, that seems good! Now, however, the question is... what should a guard look like here? Well, guards get evaluated, so it has to be valid python.

` <class 'np.float16'>` is not evaluatable. However, `eval('numpy.float16')` gives us `<class 'numpy.float16'>`. 

So, having verified that the source is sound, we need to make sure that the guard is produced correctly. 

The problem with this, is that we do not necessarily have the info we need, nor a centralized place to put it.

Problem 1 - The info we need:

For info, we need a way to get the evaluatable name here. The problem with that, is that we do not have easy or ready access to that data. If we do something like 

```
if isinstance(self.index, type):
            rep = f"{self.index.__module__}.{self.index.__qualname__}"
            return f"___odict_getitem({self.base.name()}, {rep})"
```

In the source mentioned above, we would get `NameError: name 'numpy' is not defined`, because you import it as `np`. Changing the script to `import numpy` with the fix above, or hacking in `np` instead of the `.__module__` works, but it's obviously brittle and just an example.

Problem 2 - A place to put it:

On top of that, we also do not have a good place to do this! Specifically, there are lots of guards that could refer to a type, and run into this same issue. This one is extra egregious because it is used under `Any`, and so while other guards will implement a `___check_type_id` to use the id_ref of a type in place of the type for this reason, it does not suffice for something like this, because you cannot just use a whole different value (an id of the type) in place of the type:

```
(Pdb) hash(self.index)
8760046238050
(Pdb) hash(type(self.index))
476498
```

So what do we do:

For problem 1, I could imagine a few solutions, just to spitball a bit, none of these feel particularly great atm:

a) Don't guard on this, namely, types in "Any" source fields where the guards do not do a ___check_type_id rewrite/ or where a class name str may end up leaking into eval
b) Use some python witchcraft to support ` f"{self.index.__module__}.{self.index.__qualname__}"` for these cases, where the locally used name (`np` in the case above) is mapped to the true name of the module (`numpy` in the case above).
c) Whenever we encounter a class name in python, record it's mapping to the real thing and store a resolution function in the guard context closure vars that is used to turn the string above into the real module. (I did a little hack of this, it passes, but is gross)

For problem 2, we could:
a) Check through every source and apply the logic
b) Maybe detect when a .value in a VariableTracker is a class, and add support for something to automatically registers the name remap for a mechanism above
c) I dont know

**Comment by Chillee** [comment]
I think Voz basically said everything I was going to say, but here's a smaller repro that doesn't depend on numpy at all.

```
import torch
d = {int: torch.float}
@torch.compile
def f(x, y):
    return torch.randn(5, dtype=d[y])

f(torch.zeros(4), int)
```

**Comment by ezyang** [comment]
I think a short fix that only works for Numpy is doable in not too many lines of code. The idea is to:

1. Modify ODictGetItemSource to call a custom repr for the keys, which special cases Numpy to print as `numpy.XXX`
2. Update `CLOSURE_VARS` in torch/_dynamo/guards.py to ensure that numpy is in scope.

The fully general fix is more involved, but I think doable as a starter project. We simply need to make the expansion of Python constants into Python program fragments programmable, so that you can extend it however you need as more exotic things show up in keys. This could just be a function with lots of elif statements, but we could also program it into VariableTracker as an alternative to as_python_constant (perhaps as_python_expr).

I also considered adding a mechanism for directly shunting python constants into the environment, but macro systems like Racket enforce strong phase separation where the only way to transmit from compile-time to run-time is via program text expansion, and I generally think this is a good idea, so let's keep this invariant.

**Comment by voznesenskym** [comment]
> I think a short fix that only works for Numpy is doable in not too many lines of code. The idea is to:
> 
> 1. Modify ODictGetItemSource to call a custom repr for the keys, which special cases Numpy to print as `numpy.XXX`
> 2. Update `CLOSURE_VARS` in torch/_dynamo/guards.py to ensure that numpy is in scope.
> 

Agreed :) 

> The fully general fix is more involved, but I think doable as a starter project. We simply need to make the expansion of Python constants into Python program fragments programmable, so that you can extend it however you need as more exotic things show up in keys. This could just be a function with lots of elif statements, but we could also program it into VariableTracker as an alternative to as_python_constant (perhaps as_python_expr).

I think the conflation of printable name and evaluatable name keep biting us in random places. Perhaps source should just call a new method on VariableTracker, (perhaps your as_python_expr). So big +1 from me there. 

> I also considered adding a mechanism for directly shunting python constants into the environment, but macro systems like Racket enforce strong phase separation where the only way to transmit from compile-time to run-time is via program text expansion, and I generally think this is a good idea, so let's keep this invariant.

I am not smart enough to understand this part of the comment, lol.

**Comment by knwng** [comment]
Hi @ezyang @voznesenskym, I created a quick fix under your guidance. Please let me know what else I should do, for example, whether I need to create some unit tests(I didn't find where to add them). :-)

I'm still working on the more general solution. But since I'm not very familiar with dynamo's souce code yet, it may take me some time.

**Comment by knwng** [comment]
> Add a unit test to test/dynamo/test_repros.py

OK, done.
