### ISSUE TITLE
Slicing a nn.ModuleList

### ISSUE THREAD

**Issue by jzbontar** [pytorch/pytorch#974]
Slicing operation don't seem to work on nn.ModuleList. 

    from torch import nn
    list = nn.ModuleList([nn.Module(), nn.Module()])
    print list[1:]

produces the following error:

    KeyError: 'slice(1, None, None)'

**Comment by apaszke** [comment]
After giving it a thought, I concluded that there's no good way to solve this.
Returning another `nn.ModuleList` doesn't feel right, because we discourage sharing modules between containers.
Returning a Python list seems bug prone, because someone might do sth like below, and the modules wouldn't get registered, even though it looks as if they should:
```python
l = nn.ModuleList([...])
class MyModule(nn.Module):
    def __init__(self):
        self.submodule = l[1:]
```

**Comment by sharma409** [comment]
Why do you discourage sharing modules between containers? Perhaps you can explicitly give a view into the container rather than return a new container if you want to preserve this.

Though there are typically workarounds, splicing can be useful, for example in a project I'm working on that builds on recent work progressively growing nerual networks and slowly adding to the number of layers being trained. The growth of an encoder-decoder architecture, for example, is inherently middle-out, so lends itself to splicing. One can be clever with indexing and make it work, but splicing seems more natural for this problem.

**Comment by apaszke** [comment]
I think in the end we decided to accept this change and it is merged in master

**Comment by lpuglia** [comment]
Useful note: If you are using python 3 with pytorch 0.3.1, this:

```
from torch import nn
list = nn.ModuleList([nn.Module(), nn.Module()])
print(list[1:])
```

gives:
```
TypeError: '<=' not supported between instances of 'int' and 'slice'
```

It seems that the feature has been reintroduced in pytorch 0.4.1 with #4491
