### ISSUE TITLE
[JIT] Parsing of declarations at static initialization time leads to very strange errors when _C.so is stale

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#9760]
The root cause is the same as #9493 but I think some stuff JIT is doing is exacerbating the problem.

I was doing a rebuild of PyTorch one day after making some modifications, and I got this error:

```
/home/ezyang/Dev/pytorch-tmp-env/bin/python tools/setup_helpers/generate_code.py
terminate called after throwing an instance of 'std::runtime_error'
  what():  expected long but found 'int' here:
aten::RoiPooling2d_backward(Tensor input, Tensor rois, int pooledHeight, int pooledWidth, float spatialScale
, Tensor gradOutput, Tensor argmaxes) -> Tensor
                                                       ~~~ <--- HERE

ninja: build stopped: subcommand failed.
```

Deleting torch/*.so fixed the problem.

I think there are a few problems here:

1. This is ostensibly some sort of internal error for the JIT schema, but the error gives no indication as such
2. Parsing at static initialization time means that you get this error even if you don't use any JIT functionality

**Comment by zdevito** [comment]
I think the root cause is the major problem, because it breaks the build.  But it would be a good idea to delay operator registration until it is needed anyway to lower startup times.

We can make parsing lazy by:

1. switching Operator to have a .schema() function, and only lazily generating the schema if initialized from a string.
2. in registration of an operator just putting the operators in a todo list for adding to the registration map.
3. on operator lookup, flushing the todo list of any additional operators to add before looking up the result.
