### ISSUE TITLE
llocated memory try setting max_split_size_mb to avoid fragmentation

### ISSUE THREAD

**Issue by Franchisco123** [pytorch/pytorch#97925]
### 🐛 Describe the bug

i using the webui in stable diffusion

and i have 8 gb ram 
and i got this error and i want how to solve it by steps 

llocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CON

### Versions

?

**Comment by jbschlosser** [comment]
Sounds like you're running out of CUDA memory. Here is a link to the referenced [docs](https://pytorch.org/docs/stable/notes/cuda.html#memory-management).

I suggest asking questions like this on the [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to get help there. The issues here are reserved for problems within PyTorch itself. Closing as expected behavior.
