### ISSUE TITLE
Support custom device and custom backend for Dispatching PyTorch Distributed Collectives

### ISSUE THREAD

**Issue by shaoyf42** [pytorch/pytorch#97938]
### 🚀 The feature, motivation and pitch

Currently, PyTorch supports the extension of third-party libraries for collection communication. However, only CPU and GPU are distributed for collection communication.  When we extend Pytorch, a scenario is using custom device and custom backend e.g. `"cpu:gloo,privateuse1:custom_backend"`.

### Alternatives
To support custom device and backend:

First, add PrivateUse1 for dispatching PyTorch Distributed Collectives. 
Here is a examples:
```c++
c10::intrusive_ptr<c10d::Work> send_privateuse1(
    at::TensorList tensors,
    const c10::intrusive_ptr<c10d::ProcessGroup>& process_group,
    int64_t dstRank,
    int64_t tag) {
  auto tensor_vec = tensors.vec();
  return process_group->getBackend(c10::DeviceType::PrivateUse1)
      ->send(tensor_vec, static_cast<int>(dstRank), static_cast<int>(tag));
}

TORCH_LIBRARY_IMPL(c10d, PrivateUse1, m) {
  m.impl("send", send_privateuse1);
}
```

Second, some collective functions need to be updated to support custom backends, e.g:
```python
# 1 add device parameter
def all_gather_object(object_list, obj, group=None, device=None):
    current_device = device or _get_pg_device(group)
```

```python
# 2 Add judgment for custom backend
def barrier(group=GroupMember.WORLD, async_op=False, device_ids=None):
    if device_ids is not None:
        if (get_backend(group) != Backend.NCCL) or (get_backend(group) in Backend._plugins) :
            raise RuntimeError(
                "Function argument device_ids not supported "
                "for the selected backend {}".format(get_backend(group))
            )
```
```python
# 3 add judgment for custom device
if not torch.cuda.is_available() or not custom_device_is_available:
    raise ValueError("Subgroups can only be created when CUDA or custom device is available")
```

_No response_

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by wanchaol** [comment]
we do have a custom backend registration (for both python and C++), is there a reason why this is needed instead of registering a custom backend?

cc @H-Huang

**Comment by kumpera** [comment]
The issue is not a custom backend, but a backend for a custom device type.

Today, for example, we can't use PTD on newer macs because we don't handle the MPS device type.

**Comment by kumpera** [comment]
For items 2 and 3 I rather an explicit abstraction that given a device/backend we can query the functionality we need.

This is inline with work we need to do do support non CUDA accelerators for other parts of PyTorch Distributed like FSDP and DDP.

**Comment by kwen2501** [comment]
Hi @shaoyf42 In PyTorch 2.0, we added a mechanism to dispatch c10d collectives to a custom device's collective implementation, exactly for the purpose you described.

You may refer to this [RFC](https://github.com/pytorch/pytorch/issues/86225) for more design details.

Today, the collectives for `cpu` and `cuda` tensors are already implemented in the same style as in your first code snippet.
For a custom device, you can put your implementation in a plugin. During import of your plugin in user script (like `import torch-xla`), the implementation for respective collective function (i.e. destination of dispatching) would be registered into PyTorch's dispatching table.

IIRC, if your device has a specific name (like `ypu`), it would be better to register such name in PyTorch trunk so as to get a good user experience. Otherwise, you may use the `privateuse1` placeholder for experiment purposes.

Now, for the detailed 1, 2, 3 problems:

Problem 1:
I think a follow-up task of our dispatching design is yet to move all `***_object` methods to cpu only, hence can be handled by Gloo, instead of requiring custom implementation. @H-Huang to see if things are aligned here.

Problem 2:
Indeed `barrier` is an exception of "collectives." Nonetheless, we still allow custom backend implementation for barriers. Maybe @H-Huang remember more clearly how we did it last half?

Problem 3:
Can you point us to the context of this code snippet? I can't recognize where it comes from out of my head. Thanks.

**Comment by H-Huang** [comment]
Thanks for the RFC! `PrivateUse1` default implementation makes sense. Here are my thoughts on updates for the `object` and `barrier` collectives

> Problem 1:
I think a follow-up task of our dispatching design is yet to move all ***_object methods to cpu only, hence can be handled by Gloo, instead of requiring custom implementation.

I agree this is the route we want to go since object based collectives with gpu tensors + NCCL have been problematic. However, the problem with only allowing CPU/gloo object collectives it that it requires the user to have cpu backend.

For the issue at hand, we can notice that all object collectives call into `_get_pg_device()` to determine that device is used

https://github.com/pytorch/pytorch/blob/7b25976323751291171e60dc557bc61973427d32/torch/distributed/distributed_c10d.py#L461-L468

I think we should move away from the hardcoding of nccl backend checks (although nccl is the most popular and default, pytorch itself should be backend agnostic), and perhaps add a flag in BackendConfig for the "preferred device type". Then these collectives can stay the same and user just needs to update the backend config of their process group. This could also be used to solve problem 2.

> Problem 2:
Indeed barrier is an exception of "collectives." Nonetheless, we still allow custom backend implementation for barriers.

This is currently implemented in a not ideal way. It assumes if the backend is nccl then we want to do barrier with cuda tensor, but this means this does not support custom cuda backends and defaults to cpu backend. I think that a `device` argument or the flag mentioned above makes sense for this collective (we already do have `device_ids` argument).
