### ISSUE TITLE
Siganture of fractional_max_pool3d is undescriptive

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#97982]
### 📚 The doc issue

![image](https://user-images.githubusercontent.com/5652049/228876327-3f24e80a-0b07-458b-91bb-3e7a349fc43a.png)

### Suggest a potential alternative/fix

It should not say (*args, **kwargs) and should list out all the arguments.

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by albanD** [comment]
It's due to the jit wrapper for boolean dispatch... We should definitely fix it, most likely with the appropriate `@wraps()` or remove the `boolean_dispatch` altogether if we can safely do it?

**Comment by mikaylagawarecki** [comment]
I think adding a line with the correct function signature to the start of the docstring should fix this (e.g. [max_pool1d also uses boolean_dispatch](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L699) but the [args and kwargs render ok](https://pytorch.org/docs/stable/generated/torch.nn.functional.max_pool1d.html#torch.nn.functional.max_pool1d), I think that is [because of this line ](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L633). 

Is it worth looking into removing boolean_dispatch?

**Comment by albanD** [comment]
Ho interesting! Adding the signature by hand sounds a lot simpler for sure!

Not sure it is worth looking into boolean_dispatch unless someone is interested in cleaning up jit shenanigans :D
