### ISSUE TITLE
Unable to run session using exported ONNX model using dictionary input

### ISSUE THREAD

**Issue by satyajandhyala** [pytorch/pytorch#98100]
### 🐛 Describe the bug

The following example tries to export CustomAdd ONNX model and tries to run using onnxruntime session. I have tried a few variations of passing the inputs with the run call. But I keep getting errors.
Traceback (most recent call last):
  File "add.py", line 23, in <module>
    ort_outputs = ort_sess.run(None, d)
  File "/home/sajandhy/.conda/envs/py38/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Input must be a list of dictionaries or a single numpy array for input 'x'.

Not clear what I am missing

```
import numpy
import onnxruntime
import torch

class CustomAdd(torch.nn.Module):
    def forward(self, d):
        x = d["x"]
        y = d["y"]
        return torch.add(x, y)

x = torch.randn(3, 3)
y = torch.randn(3, 3)

d = {"x":x, "y":y}
model = CustomAdd()
pt_outputs = model(d)

torch.onnx.export(CustomAdd(), (d, {}), "add.onnx")

ort_sess = onnxruntime.InferenceSession("add.onnx")

ort_inputs = (x, y)
ort_outputs = ort_sess.run(None, d)
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1035-azure-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
GPU 2: Tesla V100-PCIE-16GB
GPU 3: Tesla V100-PCIE-16GB

Nvidia driver version: 525.89.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              1
Core(s) per socket:              12
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
Stepping:                        1
CPU MHz:                         2593.992
BogoMIPS:                        5187.98
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        6 MiB
L3 cache:                        70 MiB
NUMA node0 CPU(s):               0-11
NUMA node1 CPU(s):               12-23
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt md_clear

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.1.4
[pip3] torch==2.0.0
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.23.5           py38h14f4228_0
[conda] numpy-base                1.23.5           py38h31eccc5_0
[conda] pytorch-lightning         1.1.4                    pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by jjmmchema** [comment]
### Solution to the issue
The problem is caused because the items in the dictionary `d` that you created the inputs are still tensors when you are calling `ort_outputs = ort_sess.run(None, d)`. You should call the methods `cpu()` and `numpy()` on each input tensor.

See the code below that works well for me:

```python
torch.manual_seed(420)

x = torch.randn(3, 3)
y = torch.randn(3, 3)

d = {"x":x, "y":y}
model = CustomAdd()
model.eval()

pt_outputs = model(d)
print('From PyTorch:', pt_outputs)

input_names = ["x", "y"]
torch.onnx.export(model, (d, {}), "add.onnx", input_names=input_names)

ort_sess = onnxruntime.InferenceSession("add.onnx")
ort_inputs = {"x":x.cpu().numpy(), "y":y.cpu().numpy()}
ort_outputs = ort_sess.run(None, ort_inputs)
print('From onnxruntime:', ort_outputs)
```
You should see one tensor and one numpy array printed which approximately the same values.

### Explanation and Recommendations.
When calling `ort_sess.run(None, ort_inputs)`, `onnxruntime` expects the inputs to be numpy arrays, not tensors. As you can see, I created another input dictionary called `ort_inputs` which contains the key-value of each input. I'm calling the 'cpu()' method on each of them to ensure that they are not in the GPU but on the CPU memory. Then I convert each of them to a numpy array with the `numpy()` method.

Now here are my recommendations:

1. When creating Tensors or Numpy Arrays with random values you should set a manual seed in order to make your code reproducible. If you don't, then every time you run the code the tensors `x` and `y` will have different values and it will be a nightmare to debug as the output will also be different each time. By calling `torch.manual_seed(420)` every time you run the code you should get the same output.
2. You are not training the model, just making some predictions. That's why you should set your model to evaluation mode with `model.eval()`. _The default is training mode_.
3. You don't need to create another instance of CustomAdd, you can just pass the model `model` in `torch.onnx.export`.
4. Give **ALWAYS** a name to each input of your model when exporting it as a onnx file. Just pass a list of strings like `input_names` in the code above. The number of elements in that list depends of how many inputs you have, in this case it's only 2 so just pass two names, then add this as the parameter `input_names` when calling `torch.onnx.export`.

It's important to name the inputs because then you are creating the dictionary that will be passed when calling `onnxruntime.InferenceSession.run` the key of each value **needs** to be the name that `onnxruntime` gave to each input. If not, you are probably going to get an error as onnx just gave each one of them some name that you don't know and `ort_inputs = {"x":x.cpu().numpy(), "y":y.cpu().numpy()}` wont work since `"x"` and `"y"` are not the names of each input.

You can see by youself what is the name that onnx assigns the each input by simply deleting `input_names=input_names` in `torch.onnx.export` and then running this code:
```python
for input in ort_sess.get_inputs():
    print(input.name)
```
An alternative way of doing this if you don't want to manually name your inputs is by creating `ort_inputs` like this:
```python
ort_inputs = {ort_sess.get_inputs()[0].name: x, ort_sess.get_inputs()[1].name: y}
```
But as you can see it gets annoying to type all that if you have a lot of inputs.
