### ISSUE TITLE
Deterministic option for bincount_cuda

### ISSUE THREAD

**Issue by csiefer2** [pytorch/pytorch#98316]
### 🚀 The feature, motivation and pitch

I'm working on a multiclass classifier, and I would really like to have deterministic confusion matrices on cuda.  Since that is implemented in torchmetrics using bincount_cuda, which doesn't currently support determinism, this is a bit of a bummer.

### Alternatives

Right now, I either pop the data back to CPU (slow) or turn off determinism and hope for be best.

### Additional context

Torch speaks thusly:
```
UserWarning: _bincount_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at  ../aten/src/ATen/Context.cpp:82.)
```

cc @mruberry @kurtamohler

**Comment by ReinGrad** [comment]
Perhaps this is a problem with the Python library itself

**Comment by vadimkantorov** [comment]
Hmm, this is quite strange, because it operates on integral inputs, right? So it probably is already deterministic? @ezyang 

Also, `histc` should rather return integral outputs https://github.com/pytorch/pytorch/issues/32305

**Comment by kurtamohler** [comment]
Operating on integral types doesn't mean that it's deterministic, there are a number of different sources of nondeterminism.

There's a note in `_bincount_cuda` saying that the reason it's nondeterministic is because of its use of atomicAdd:
https://github.com/pytorch/pytorch/blob/937ba248eb3c18146064e98f16a0ec4a042b47f8/aten/src/ATen/native/cuda/SummaryOps.cu#L369-L371

In that file, `_bincount_cuda` calls `_bincount_cuda_template`, which calls `CUDA_tensor_histogram`, which calls a `HANDLE_SWITCH_CASE` macro. In all cases of that switch case, it calls `kernelHistogram1D`, which uses `gpuAtomicAddNoReturn`.

I don't really know much about atomicAdd, why it's nondeterministic, or how to write an implementation that avoids it. I will learn more about it, since it's a known reason for many of our nondeterministic algorithms

**Comment by ngimel** [comment]
the kernel uses atomicAdd on values of `output_t` https://github.com/pytorch/pytorch/blob/bd78532020d4b9b184a5c41df915a61e47371483/aten/src/ATen/native/cuda/SummaryOps.cu#L95. For a histogram without weights that would be int64_t, and atomicAdd is deterministic for those, so we should adjust non-determinism warning/error to be more relaxed.

**Comment by kurtamohler** [comment]
Thanks @ngimel! I will make that change
