### ISSUE TITLE
Inconsistent argument names in Linear and Conv layers

### ISSUE THREAD

**Issue by Maratyszcza** [pytorch/pytorch#984]
Linear layers accept `in_features` and `out_features` arguments, and save them as similarly named instance variables. Similar arguments for Conv1d/Conv2d/Conv3d layers are called `in_channels` and `out_channels`. I think its worth to standardize on one set of names.

**Comment by Jerrynet** [comment]
"Linear" operates on 2D Tensor: N x Features
"ConvNd" operates on N x Channels x ? x ? x...

So it's not inconsistent.

**Comment by Maratyszcza** [comment]
It could be said that Linear layers operate on 2D Tensor of N x Channels, and that ConvXd operates on consumes a produces a set of feature maps.

**Comment by szali** [comment]
It is really inconsistent. I think it should be fixed before 1.0 comes out.

**Comment by zou3519** [comment]
If we do this, we need to take care that it's not BC-Breaking.

In general I don't think we should do this because "channels" only make context in the vision domain. Linear is pretty general, so we shouldn't tell, say, NLP users, to use "channels". 

One thing we could do is to add extra keyword args that behave the same, but that complicates the API.

**Comment by gchanan** [comment]
We aren't going to do this, too many BC concerns.
