### ISSUE TITLE
Windows CPU runner long queue

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#98474]
## Current Status
Ongoing

## Error looks like
Long queue of more than 2 hours

![Screenshot 2023-04-05 at 19 55 16](https://user-images.githubusercontent.com/475357/230261032-7ca5b9ab-ce09-49db-8ea7-d1a4c7b953a0.png)

## Incident timeline (all times pacific)
* April 5th

## User impact
Long delay in PR

## Root cause
TBD

## Mitigation
Disable the job temporarily to let the queue drain.
* https://github.com/pytorch/pytorch/issues/98475
* https://github.com/pytorch/pytorch/issues/98476

## Prevention/followups
TBD

**Comment by huydhn** [comment]
![Screenshot 2023-04-05 at 20 04 58](https://user-images.githubusercontent.com/475357/230262126-5eb63e33-6aef-4f17-99ca-1337087b4aad.png)

The queue is draining ...

**Comment by huydhn** [comment]
The mitigation doesn't cover with Windows binary build though as the disable mechanism hasn't been extended to binary build workflow yet.

**Comment by jeanschmidt** [comment]
![338211207_618893113420721_2332023324726379009_n](https://user-images.githubusercontent.com/4520845/230415573-7407f978-1daa-4424-b2a1-d7358efcc111.png)

Issue might be related to lack of capacity in AWS region.

**Comment by jeanschmidt** [comment]
After collecting more evidence, we conclude that the issue was originated in the lack of capacity to serve these particular instances by AWS in the region we operate.

As the capacity recovered, I will now consider this issue mitigated. Work is already planned to include support for other regions and it will be prioritized ASAP.
