### ISSUE TITLE
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::logical_not to ONNX opset version 12 is not supported.

### ISSUE THREAD

**Issue by cqray1990** [pytorch/pytorch#99266]
### 🐛 Describe the bug

i try pytorch 1.10 1.12  to export logical_not to op  onnx  with opset_version 11 ,12,13  but all failed
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::logical_not to ONNX opset version 12 is not supported.
 how to export logical_not to onnx

### Versions

i try pytorch 1.10 1.12  to export logical_not to op  onnx  but all failed
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::logical_not to ONNX opset version 12 is not supported.

@malfet

**Comment by justinchuby** [comment]
Logical not is supported from opset9: https://github.com/pytorch/pytorch/blob/b0df0cd7cc00faae718a456eb831bcb5bdaa6fcc/torch/onnx/symbolic_opset9.py#L2299-L2300

I suggest testing with the latest pytorch release (2.0)

**Comment by justinchuby** [comment]
Please re-open if you still hit an error.

**Comment by yeonsun-ahn** [comment]
Hi, @justinchuby 
I'm experiencing the same error,
If I use opset9, I can't use cumsum, so I got a message to use opset11, and if I use opset11 or later, all model outputs are `nan` values.

XLM-Roberta is used to extract embeddings of the text: `input_embs`, and then the following operations are performed in the classifier header.
```python
mask_sfmx = - 1e+10 * torch.logical_not(attn_mask)[:, :, None]
weight = F.softmax(self.attn(input_embs) + mask_sfmx, dim=1)
mean = torch.sum(input_embs*weight, dim=1)
```
The `mean` value is passed through a linear layer, the output is the model logit, and all of these values are returned as `nan`.
When I used the torch model rather than onnx, there was no problem.

My Envs are:
- torch 2.1.2+cu118
- onnx 1.13.1
- onnxruntime-gpu 1.11.0

**Comment by justinchuby** [comment]
Can you attach a minimal ONNX model files that exhibits this error?

**Comment by justinchuby** [comment]
Also please consider testing with the latest version of ONNX runtime.

**Comment by valaxkong** [comment]
Hi @cqray1990 , I encounter the same issue.  I am wondering how you get passed that error. Thank you!
