### ISSUE TITLE
torch.matrix_exp doesnt give the same result as scipy.linalg.expm

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#99322]
### 🐛 Describe the bug

```
import torch
import scipy.linalg
arg_1_tensor = torch.rand([5, 5, 5], dtype=torch.complex128)
noise = torch.rand(arg_1_tensor.shape)
mask = noise < 0.05
noise_tensor = arg_1_tensor.clone()
noise_tensor[mask] = 0
noise_tensor[~mask] = 255
arg_1_tensor = noise_tensor
arg_1 = arg_1_tensor.clone()
print('scipy results')
print(scipy.linalg.expm(arg_1))
results = torch.matrix_exp(input=arg_1,)
print('torch results')
print(results)
# scipy results as: tensor([[[inf+nanj inf+nanj inf+nanj inf+nanj inf+nanj]...
# torch results as: tensor([[[inf+0.j, inf+0.j, inf+0.j, inf+0.j, inf+0.j]...
```
torch.matrix_exp should give the same result as scipy.linalg.expm

### Versions

pytorch version: 2.0.0+cu118

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by gnehzza** [comment]
Could I try working on this? (I'm also unsure how contributing works, I just read somewhere that I should comment that I want to work on an issue)

**Comment by lezcano** [comment]
Alas, this is expected as per https://pytorch.org/docs/stable/notes/numerical_accuracy.html#extremal-values-in-linalg. The matrix will have very large eigenvalues, and that's why you get infs as results. Even more, I would suggest that the PyTorch inf is more correct than the nans from scipy, as the matrix_exp is well-defined for all input matrices.
