### ISSUE TITLE
Not Preserving Grad For Tensor Created Inside torch.compile

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#99455]
### 🐛 Describe the bug
```
import torch

def foo():
    x = torch.randn(5, 5, requires_grad=True)
    y = x + 2
    return x, y

x, y = foo()
print(x.requires_grad, y.requires_grad)
# True True

x, y = torch.compile()(foo)()
print(x.requires_grad, y.requires_grad)
# False False
```

### Versions

master

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by yanboliang** [comment]
dynamo eager passed, seems inductor doesn't preserve the grad. cc @ngimel

**Comment by bdhirsh** [comment]
This looks similar to https://github.com/pytorch/pytorch/issues/90552 (so general AOTAutograd problem, not specific to inductor).

There are probably several ways to deal with this, but the one proposed in the linked issue is to promote the randn call to a graph input, that way AOTAutograd will know run it through autograd properly.

**Comment by ezyang** [comment]
@bdhirsh this seems pretty similar to the other thing you fixed by pulling things into inputs. ARe you planning to do this one?

**Comment by bdhirsh** [comment]
@ezyang I'm actually not convinced this is very hi-pri (Elias said this didn't come from an existing model, and as pointed out in the linked issue, this shouldn't really happen when compiling a normal model). I tentatively won't try to fix this in the next week or two, since the fix is involved. But if you think it deserves to be higher priority, let me know and I can get to it sooner.

**Comment by ezyang** [comment]
oh, if eellison downgraded prio, feel free to defer
