### ISSUE TITLE
Some detectron2_maskrcnn models fails on periodic dynamo_eager_torchbench

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#99665]
### 🐛 Describe the bug

4 of them failed with the same key error `_ignore_torch_cuda_oom`:

```
ERROR:common:
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 729, in LOAD_GLOBAL
    value = self.f_globals[name]
KeyError: '_ignore_torch_cuda_oom'
...
detectron2_maskrcnn_r_101_c4       fail_to_run
detectron2_maskrcnn_r_101_fpn      fail_to_run
detectron2_maskrcnn_r_50_c4        fail_to_run
detectron2_maskrcnn_r_50_fpn       fail_to_run
```

The error starts with this commit https://hud.pytorch.org/pytorch/pytorch/commit/e9be0b0fb93c271ba3deb31b5ccc8f4c4f602ef9 (cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire @jansel)

They have been temporarily skipped by https://github.com/pytorch/pytorch/pull/99599.

### Versions

PyTorch CI

**Comment by yanboliang** [comment]
I guess this is the culprit:
https://github.com/facebookresearch/detectron2/blob/ecb786ccd26de4086a6fede437e7d728199470e2/detectron2/utils/memory.py#L67-L84

```detectron2``` uses ```functools.wraps``` to wrap a function who is using a context manager ```_ignore_torch_cuda_oom```, #98699 maybe don't handle this case well.

@jansel not sure if you have a fix in your mind, otherwise, I can take a look at this.

**Comment by jansel** [comment]
@yanboliang feel free take a look.
